Fritzing: ZoomButton Class Reference
ZoomButton Class Reference
#include <zoomcontrols.h>
Public Types
enum ZoomType { ZoomIn, ZoomOut }
Signals
void clicked ()
Public Member Functions
ZoomButton (QBoxLayout::Direction dir, ZoomButton::ZoomType type, ZoomableGraphicsView *view, QWidget *parent)
Protected Slots
void zoom ()
Protected Member Functions
void enterEvent (QEvent *event)
void leaveEvent (QEvent *event)
void mousePressEvent (QMouseEvent *event)
Protected Attributes
ZoomableGraphicsView * m_owner
double m_step
ZoomButton::ZoomType m_type
Member Enumeration Documentation
ZoomType
enum ZoomButton::ZoomType
Enumerator
ZoomIn
ZoomOut
Constructor & Destructor Documentation
ZoomButton()
ZoomButton::ZoomButton (QBoxLayout::Direction dir, ZoomButton::ZoomType type, ZoomableGraphicsView * view, QWidget * parent)
References clicked(), m_owner, m_step, m_type, zoom(), ZoomIn, and ZoomSlider::ZoomStep.
Member Function Documentation
clicked
void ZoomButton::clicked () signal
enterEvent()
void ZoomButton::enterEvent (QEvent * event) protected
References MainWindow::event().
leaveEvent()
void ZoomButton::leaveEvent (QEvent * event) protected
References MainWindow::event().
mousePressEvent()
void ZoomButton::mousePressEvent (QMouseEvent * event) protected
References clicked(), and MainWindow::event().
zoom
void ZoomButton::zoom () protected slot
References ZoomableGraphicsView::ensureFixedToBottomRightItems(), m_owner, m_step, m_type, ZoomableGraphicsView::relativeZoom(), and ZoomIn.
Member Data Documentation
m_owner
ZoomableGraphicsView* ZoomButton::m_owner protected
m_step
double ZoomButton::m_step protected
m_type
ZoomButton::ZoomType ZoomButton::m_type protected
The documentation for this class was generated from the following files:
autoroute/zoomcontrols.h
autoroute/zoomcontrols.cpp