Fritzing: AddRemoveListWidget Class Reference
AddRemoveListWidget Class Reference
#include <addremovelistwidget.h>
Public Member Functions
AddRemoveListWidget (QString title, QWidget *parent=0)
int count ()
QStringList & getItemsText ()
QListWidgetItem * itemAt (int rowIdx)
void setItemsText (const QStringList &texts)
Protected Slots
void addItem ()
void addItem (QString itemText)
void removeSelectedItems ()
Protected Attributes
QPushButton * m_addButton
QLabel * m_label
QListWidget * m_list
QPushButton * m_removeButton
Constructor & Destructor Documentation
AddRemoveListWidget()
AddRemoveListWidget::AddRemoveListWidget (QString title, QWidget * parent = 0)
References addItem(), BUTTON_SIZE, m_addButton, m_label, m_list, m_removeButton, and removeSelectedItems().
Member Function Documentation
addItem [1/2]
void AddRemoveListWidget::addItem () protected slot
References m_label.
addItem [2/2]
void AddRemoveListWidget::addItem (QString itemText) protected slot
References m_list.
count()
int AddRemoveListWidget::count ()
References m_list.
getItemsText()
QStringList & AddRemoveListWidget::getItemsText ()
References count(), and itemAt().
itemAt()
QListWidgetItem * AddRemoveListWidget::itemAt (int rowIdx)
References m_list.
removeSelectedItems
void AddRemoveListWidget::removeSelectedItems () protected slot
References m_list.
setItemsText()
void AddRemoveListWidget::setItemsText (const QStringList & texts)
References addItem(), and m_list.
Member Data Documentation
m_addButton
QPushButton* AddRemoveListWidget::m_addButton protected
m_label
QLabel* AddRemoveListWidget::m_label protected
m_list
QListWidget* AddRemoveListWidget::m_list protected
m_removeButton
QPushButton* AddRemoveListWidget::m_removeButton protected
The documentation for this class was generated from the following files:
partseditor/obsolete/addremovelistwidget.h
partseditor/obsolete/addremovelistwidget.cpp