Fritzing: GroundFillSeedDialog Class Reference
GroundFillSeedDialog Class Reference
#include <groundfillseeddialog.h>
Public Slots
void accept ()
void changedSlot (QListWidgetItem *)
void clickedSlot (QListWidgetItem *)
void doFill (bool)
void reject ()
Public Member Functions
GroundFillSeedDialog (class PCBSketchWidget *, QList< class ConnectorItem * > &, const QString &intro, QWidget *parent=0)
~GroundFillSeedDialog ()
bool getFill ()
void getResults (QList< bool > &results)
Protected Member Functions
void showEqualPotential (ConnectorItem *connectorItem, bool show)
Protected Attributes
ConnectorItem * m_activeConnectorItem
QList< ConnectorItem * > m_connectorItems
bool m_doFill
QPushButton * m_doFillButton
QListWidget * m_listWidget
PCBSketchWidget * m_sketchWidget
Constructor & Destructor Documentation
GroundFillSeedDialog()
GroundFillSeedDialog::GroundFillSeedDialog (class PCBSketchWidget * sketchWidget, QList< class ConnectorItem * > & connectorItems, const QString & intro, QWidget * parent = 0)
References accept(), changedSlot(), clickedSlot(), ConnectorItem::connectorSharedName(), doFill(), ConnectorItem::isGroundFillSeed(), m_activeConnectorItem, m_connectorItems, m_doFill, m_doFillButton, m_listWidget, m_sketchWidget, reject(), and ConnectorItem::updateTooltip().
~GroundFillSeedDialog()
GroundFillSeedDialog::~GroundFillSeedDialog ()
Member Function Documentation
accept
void GroundFillSeedDialog::accept () slot
References m_activeConnectorItem, and showEqualPotential().
changedSlot
void GroundFillSeedDialog::changedSlot (QListWidgetItem *) slot
References m_doFillButton, and m_listWidget.
clickedSlot
void GroundFillSeedDialog::clickedSlot (QListWidgetItem * item) slot
References m_activeConnectorItem, m_connectorItems, and showEqualPotential().
doFill
void GroundFillSeedDialog::doFill (bool) slot
References accept(), and m_doFill.
getFill()
bool GroundFillSeedDialog::getFill ()
References m_doFill.
getResults()
void GroundFillSeedDialog::getResults (QList< bool > & results)
References m_listWidget.
reject
void GroundFillSeedDialog::reject () slot
References m_activeConnectorItem, and showEqualPotential().
showEqualPotential()
void GroundFillSeedDialog::showEqualPotential (ConnectorItem * connectorItem, bool show) protected
References ConnectorItem::collectEqualPotential(), ViewGeometry::NoFlag, and ConnectorItem::showEqualPotential().
Member Data Documentation
m_activeConnectorItem
ConnectorItem* GroundFillSeedDialog::m_activeConnectorItem protected
m_connectorItems
QList<ConnectorItem *> GroundFillSeedDialog::m_connectorItems protected
m_doFill
bool GroundFillSeedDialog::m_doFill protected
m_doFillButton
QPushButton* GroundFillSeedDialog::m_doFillButton protected
m_listWidget
QListWidget* GroundFillSeedDialog::m_listWidget protected
m_sketchWidget
PCBSketchWidget* GroundFillSeedDialog::m_sketchWidget protected
The documentation for this class was generated from the following files:
dialogs/groundfillseeddialog.h
dialogs/groundfillseeddialog.cpp