Fritzing: sketch/sketchwidget.cpp File Reference
sketchwidget.cpp File Reference
#include <QtCore>
#include <QGraphicsScene>
#include <QPoint>
#include <QPair>
#include <QMatrix>
#include <QtAlgorithms>
#include <QPen>
#include <QColor>
#include <QRubberBand>
#include <QLine>
#include <QHash>
#include <QMultiHash>
#include <QBrush>
#include <QGraphicsItem>
#include <QMainWindow>
#include <QApplication>
#include <QDomElement>
#include <QSettings>
#include <QClipboard>
#include <QScrollBar>
#include <QStatusBar>
#include <limits>
#include "../items/partfactory.h"
#include "../items/paletteitem.h"
#include "../items/logoitem.h"
#include "../items/pad.h"
#include "../items/ruler.h"
#include "../items/symbolpaletteitem.h"
#include "../items/wire.h"
#include "../commands.h"
#include "../model/modelpart.h"
#include "../debugdialog.h"
#include "../items/layerkinpaletteitem.h"
#include "sketchwidget.h"
#include "../connectors/connectoritem.h"
#include "../connectors/svgidlayer.h"
#include "../items/jumperitem.h"
#include "../items/stripboard.h"
#include "../items/virtualwire.h"
#include "../items/tracewire.h"
#include "../itemdrag.h"
#include "../layerattributes.h"
#include "../waitpushundostack.h"
#include "fgraphicsscene.h"
#include "../version/version.h"
#include "../items/partlabel.h"
#include "../items/note.h"
#include "../svg/svgfilesplitter.h"
#include "../svg/svgflattener.h"
#include "../infoview/htmlinfoview.h"
#include "../items/resizableboard.h"
#include "../utils/graphicsutils.h"
#include "../utils/textutils.h"
#include "../utils/bezier.h"
#include "../utils/cursormaster.h"
#include "../utils/fmessagebox.h"
#include "../fsvgrenderer.h"
#include "../items/resistor.h"
#include "../items/mysterypart.h"
#include "../items/pinheader.h"
#include "../items/dip.h"
#include "../items/groundplane.h"
#include "../items/moduleidnames.h"
#include "../items/hole.h"
#include "../items/capacitor.h"
#include "../items/schematicframe.h"
#include "../utils/graphutils.h"
#include "../utils/ratsnestcolors.h"
Classes
struct ConnectionThing
Enumerations
enum ConnectionStatus { IN_, OUT_, FREE_, UNDETERMINED_ }
Functions
bool ensureStrokeWidth (QDomDocument &doc, const QString &connectorID, double factor)
bool hideTerminalID (QDomDocument &doc, const QString &terminalID)
bool isVirtualWireConnector (ConnectorItem *toConnectorItem)
QString translateSVG (QString &svg, QPointF loc, double dpi, double printerScale)
bool zLessThan (QGraphicsItem *&p1, QGraphicsItem *&p2)
Variables
static constexpr int AutoRepeatDelay = 750
static constexpr double CloseEnough = 0.5
Enumeration Type Documentation
ConnectionStatus
enum ConnectionStatus
Enumerator
IN_
OUT_
FREE_
UNDETERMINED_
Function Documentation
ensureStrokeWidth()
bool ensureStrokeWidth (QDomDocument & doc, const QString & connectorID, double factor)
References TextUtils::findElementWithAttribute(), and TextUtils::getStrokeWidth().
hideTerminalID()
bool hideTerminalID (QDomDocument & doc, const QString & terminalID)
References TextUtils::findElementWithAttribute().
isVirtualWireConnector()
bool isVirtualWireConnector (ConnectorItem * toConnectorItem)
References NonConnectorItem::attachedTo().
translateSVG()
QString translateSVG (QString & svg, QPointF loc, double dpi, double printerScale)
zLessThan()
bool zLessThan (QGraphicsItem *& p1, QGraphicsItem *& p2)
Variable Documentation
AutoRepeatDelay
constexpr int AutoRepeatDelay = 750 static
CloseEnough
constexpr double CloseEnough = 0.5 static