Fritzing: PartsBinPaletteWidget Class Reference
PartsBinPaletteWidget Class Reference
#include <partsbinpalettewidget.h>
Public Slots
void addPartCommand (const QString &moduleID)
void changeIconColor ()
void itemMoved ()
void removeAlienParts ()
bool save ()
bool saveAs ()
void toIconView ()
void toListView ()
Signals
void fileNameUpdated (PartsBinPaletteWidget *, const QString &newFileName, const QString &oldFilename)
void focused (PartsBinPaletteWidget *)
void saved (bool hasPartsFromBundled)
Public Member Functions
PartsBinPaletteWidget (class ReferenceModel *referenceModel, class HtmlInfoView *infoView, WaitPushUndoStack *undoStack, class BinManager *manager)
~PartsBinPaletteWidget ()
void addNewPart (ModelPart *modelPart)
void addPart (ModelPart *modelPart, int position=-1)
void addPart (const QString &moduleID, int position)
QAction * addPartToMeAction ()
bool allowsChanges ()
bool beforeClosing ()
QMenu * binContextMenu ()
bool canClose ()
QMenu * combinedMenu ()
bool contains (const QString &moduleID)
void copyFilesToContrib (ModelPart *, QWidget *originator)
bool currentBinIsCore ()
class PartsBinView * currentView ()
bool currentViewIsIconView ()
bool fastLoaded ()
const QString & fileName ()
void focusSearch ()
QList< ModelPart * > getAllParts ()
bool hasAlienParts ()
bool hasMonoIcon ()
QIcon icon ()
bool isTempPartsBin ()
void load (const QString &filename, QWidget *progressTarget, bool fastLoad)
void loadFromModel (PaletteModel *model)
BinLocation::Location location ()
QIcon monoIcon ()
bool open (QString fileName, QWidget *progressTarget, bool fastLoad)
QMenu * partContextMenu ()
bool readOnly ()
void reloadPart (const QString &moduleID)
void removePart (const QString &moduleID, const QString &path)
void removeParts ()
ModelPart * root ()
void saveBundledBin ()
ItemBase * selectedItemBase ()
ModelPart * selectedModelPart ()
void setAllowsChanges (bool)
void setDirty (bool dirty=true)
void setInfoViewOnHover (bool infoViewOnHover)
void setPaletteModel (PaletteModel *model, bool clear=false)
void setReadOnly (bool)
void setSaveQuietly (bool)
void setTitle (const QString &title)
QSize sizeHint () const
QString title () const
Public Member Functions inherited from Bundler
virtual ~Bundler ()
virtual bool loadBundledAux (QDir &dir, QList< class ModelPart * > mps)
virtual bool preloadBundledAux (QDir &dir, bool dontAsk)
Static Public Member Functions
static void cleanup ()
Static Public Attributes
static QString Title
Protected Slots
void addSketchPartToMe ()
void focusSearchAfter ()
void search ()
void undoStackCleanChanged (bool isClean)
Protected Member Functions
void afterModelSetted (PaletteModel *model)
void closeEvent (QCloseEvent *event)
void dragEnterEvent (QDragEnterEvent *event)
void dragLeaveEvent (QDragLeaveEvent *event)
void dragMoveEvent (QDragMoveEvent *event)
void dropEvent (QDropEvent *event)
bool eventFilter (QObject *obj, QEvent *event)
void grabTitle (PaletteModel *model)
void grabTitle (const QString &title, QString &iconFilename)
bool loadBundledAux (QDir &unzipDir, QList< ModelPart * > mps)
void mousePressEvent (QMouseEvent *event)
QToolButton * newToolButton (const QString &btnObjName, const QString &imgPath, const QString &text)
bool saveAsAux (const QString &filename)
void setFilename (const QString &filename)
void setupHeader ()
void setView (class PartsBinView *view)
Protected Attributes
QAction * m_addPartToMeAction
QStringList m_alienParts
bool m_allowsChanges
QLabel * m_binLabel
bool m_canDeleteModel
QToolButton * m_combinedBinMenuButton
PartsBinView * m_currentView
QString m_defaultSaveFolder
bool m_fastLoaded
QString m_fileName
QFrame * m_header
QIcon * m_icon
class PartsBinIconView * m_iconView
bool m_isDirty
class PartsBinListView * m_listView
FileProgressDialog * m_loadingProgressDialog
BinLocation::Location m_location
BinManager * m_manager
PaletteModel * m_model
QIcon * m_monoIcon
bool m_orderHasChanged
ReferenceModel * m_referenceModel
QStringList m_removed
bool m_saveQuietly
class SearchLineEdit * m_searchLineEdit
QStackedWidget * m_searchStackedWidget
QStackedWidget * m_stackedWidget
QString m_title
WaitPushUndoStack * m_undoStack
QString m_untitledFileName
Constructor & Destructor Documentation
PartsBinPaletteWidget()
PartsBinPaletteWidget::PartsBinPaletteWidget (class ReferenceModel * referenceModel, class HtmlInfoView * infoView, WaitPushUndoStack * undoStack, class BinManager * manager)
References addSketchPartToMe(), FolderUtils::getUserBinsPath(), itemMoved(), m_addPartToMeAction, m_binLabel, m_canDeleteModel, m_defaultSaveFolder, m_fastLoaded, m_header, m_icon, m_iconView, m_listView, m_loadingProgressDialog, m_manager, m_model, m_monoIcon, m_orderHasChanged, m_referenceModel, m_saveQuietly, m_searchLineEdit, m_stackedWidget, m_title, m_undoStack, m_untitledFileName, setAllowsChanges(), PartsBinListView::setInfoView(), InfoGraphicsView::setInfoView(), setupHeader(), toIconView(), and undoStackCleanChanged().
~PartsBinPaletteWidget()
PartsBinPaletteWidget::~PartsBinPaletteWidget ()
References m_canDeleteModel, m_icon, m_model, and m_monoIcon.
Member Function Documentation
addNewPart()
void PartsBinPaletteWidget::addNewPart (ModelPart * modelPart)
addPart() [1/2]
void PartsBinPaletteWidget::addPart (ModelPart * modelPart, int position = -1)
References ModelBase::addModelPart(), PartsBinView::addPart(), PartsBinIconView::addPart(), ModelPart::isAlien(), m_alienParts, m_iconView, m_listView, m_model, ModelPart::moduleID(), and ModelBase::root().
addPart() [2/2]
void PartsBinPaletteWidget::addPart (const QString & moduleID, int position)
References addPart(), m_referenceModel, and ReferenceModel::retrieveModelPart().
addPartCommand
void PartsBinPaletteWidget::addPartCommand (const QString & moduleID) slot
References addPart(), m_listView, m_undoStack, PartsBinListView::position(), and WaitPushUndoStack::push().
addPartToMeAction()
QAction * PartsBinPaletteWidget::addPartToMeAction ()
References m_addPartToMeAction.
addSketchPartToMe
void PartsBinPaletteWidget::addSketchPartToMe () protected slot
References addPart(), contains(), BinManager::getSelectedModuleIDFromSketch(), m_fileName, m_manager, BinManager::openBinIn(), and setDirty().
afterModelSetted()
void PartsBinPaletteWidget::afterModelSetted (PaletteModel * model) protected
References grabTitle(), PaletteModel::loadedFrom(), m_model, m_undoStack, and setFilename().
allowsChanges()
bool PartsBinPaletteWidget::allowsChanges ()
References m_allowsChanges.
beforeClosing()
bool PartsBinPaletteWidget::beforeClosing ()
References m_saveQuietly, save(), and title().
binContextMenu()
QMenu * PartsBinPaletteWidget::binContextMenu ()
References BinManager::binContextMenu(), changeIconColor(), CustomIconName, isCustomSvg(), m_manager, m_model, root(), and ModelBase::rootModelPartShared().
canClose()
bool PartsBinPaletteWidget::canClose ()
References BinLocation::App, BinManager::ContribPartsBinLocation, BinManager::isTempPartsBin(), m_fileName, m_location, m_manager, BinLocation::More, BinManager::MyPartsBinLocation, BinLocation::Outside, BinManager::SearchBinLocation, and BinLocation::User.
changeIconColor
void PartsBinPaletteWidget::changeIconColor () slot
References CustomIconName, CustomIconTitle, getColor(), m_icon, m_manager, m_model, root(), ModelBase::rootModelPartShared(), setDirty(), BinManager::setTabIcon(), and ModelPartShared::setTitle().
cleanup()
void PartsBinPaletteWidget::cleanup () static
References PaletteBinModels.
closeEvent()
void PartsBinPaletteWidget::closeEvent (QCloseEvent * event) protected
combinedMenu()
QMenu * PartsBinPaletteWidget::combinedMenu ()
References BinManager::combinedMenu(), and m_manager.
contains()
bool PartsBinPaletteWidget::contains (const QString & moduleID)
References PartsBinView::contains(), and m_iconView.
copyFilesToContrib()
void PartsBinPaletteWidget::copyFilesToContrib (ModelPart * mp, QWidget * originator)
References BinManager::copyFilesToContrib(), and m_manager.
currentBinIsCore()
bool PartsBinPaletteWidget::currentBinIsCore ()
References BinManager::CorePartsBinLocation, and m_fileName.
currentView()
PartsBinView * PartsBinPaletteWidget::currentView ()
References m_currentView.
currentViewIsIconView()
bool PartsBinPaletteWidget::currentViewIsIconView ()
References m_currentView, and m_iconView.
dragEnterEvent()
void PartsBinPaletteWidget::dragEnterEvent (QDragEnterEvent * event) protected
dragLeaveEvent()
void PartsBinPaletteWidget::dragLeaveEvent (QDragLeaveEvent * event) protected
dragMoveEvent()
void PartsBinPaletteWidget::dragMoveEvent (QDragMoveEvent * event) protected
dropEvent()
void PartsBinPaletteWidget::dropEvent (QDropEvent * event) protected
eventFilter()
bool PartsBinPaletteWidget::eventFilter (QObject * obj, QEvent * event) protected
References focused().
fastLoaded()
bool PartsBinPaletteWidget::fastLoaded ()
References m_fastLoaded.
fileName()
const QString & PartsBinPaletteWidget::fileName ()
References m_fileName.
fileNameUpdated
void PartsBinPaletteWidget::fileNameUpdated (PartsBinPaletteWidget * , const QString & newFileName, const QString & oldFilename) signal
focused
void PartsBinPaletteWidget::focused (PartsBinPaletteWidget *) signal
focusSearch()
void PartsBinPaletteWidget::focusSearch ()
References focusSearchAfter(), and m_searchLineEdit.
focusSearchAfter
void PartsBinPaletteWidget::focusSearchAfter () protected slot
References SearchLineEdit::decoy(), m_searchLineEdit, and SearchLineEdit::setDecoy().
getAllParts()
QList< ModelPart * > PartsBinPaletteWidget::getAllParts ()
References ModelPart::getAllParts(), m_model, and ModelBase::root().
grabTitle() [1/2]
void PartsBinPaletteWidget::grabTitle (PaletteModel * model) protected
References m_searchLineEdit, root(), ModelBase::rootModelPartShared(), and ModelPart::title().
grabTitle() [2/2]
void PartsBinPaletteWidget::grabTitle (const QString & title, QString & iconFilename) protected
References CustomIconName, TextUtils::getViewBoxCoord(), isCustomSvg(), m_addPartToMeAction, m_binLabel, m_fileName, m_icon, m_monoIcon, m_title, BinManager::StandardBinIcons, and title().
hasAlienParts()
bool PartsBinPaletteWidget::hasAlienParts ()
References m_alienParts.
hasMonoIcon()
bool PartsBinPaletteWidget::hasMonoIcon ()
References m_monoIcon.
icon()
QIcon PartsBinPaletteWidget::icon ()
References EmptyIcon, and m_icon.
isTempPartsBin()
bool PartsBinPaletteWidget::isTempPartsBin ()
References BinManager::isTempPartsBin(), and m_manager.
itemMoved
void PartsBinPaletteWidget::itemMoved () slot
References m_manager, m_orderHasChanged, and BinManager::setDirtyTab().
load()
void PartsBinPaletteWidget::load (const QString & filename, QWidget * progressTarget, bool fastLoad)
References DebugDialog::debug(), BinLocation::findLocation(), BinManager::getBinTitle(), grabTitle(), PaletteModel::loadFromFile(), m_fastLoaded, m_fileName, m_iconView, m_listView, m_loadingProgressDialog, m_location, m_referenceModel, m_title, PaletteBinModels, FileProgressDialog::setBinLoadingChunk(), FileProgressDialog::setBinLoadingCount(), FileProgressDialog::setMessage(), and setPaletteModel().
loadBundledAux()
bool PartsBinPaletteWidget::loadBundledAux (QDir & unzipDir, QList< ModelPart * > mps) protected
References ___emptyString___, FritzingBinExtension(), ModelPart::isAlien(), load(), m_alienParts, ModelPart::moduleID(), and setFilename().
loadFromModel()
void PartsBinPaletteWidget::loadFromModel (PaletteModel * model)
References afterModelSetted(), PaletteModel::loadedFrom(), PartsBinIconView::loadFromModel(), m_canDeleteModel, m_iconView, m_listView, setFilename(), and PartsBinView::setPaletteModel().
location()
BinLocation::Location PartsBinPaletteWidget::location ()
References m_location.
monoIcon()
QIcon PartsBinPaletteWidget::monoIcon ()
References EmptyIcon, and m_monoIcon.
mousePressEvent()
void PartsBinPaletteWidget::mousePressEvent (QMouseEvent * event) protected
References focused().
newToolButton()
QToolButton * PartsBinPaletteWidget::newToolButton (const QString & btnObjName, const QString & imgPath, const QString & text) protected
open()
bool PartsBinPaletteWidget::open (QString fileName, QWidget * progressTarget, bool fastLoad)
References fileName(), FritzingBinExtension(), FritzingBundledBinExtension(), load(), MainWindow::loadBundledNonAtomicEntity(), m_isDirty, m_manager, and BinManager::mainWindow().
partContextMenu()
QMenu * PartsBinPaletteWidget::partContextMenu ()
References m_manager, and BinManager::partContextMenu().
readOnly()
bool PartsBinPaletteWidget::readOnly ()
References allowsChanges().
reloadPart()
void PartsBinPaletteWidget::reloadPart (const QString & moduleID)
References m_iconView, m_listView, PartsBinListView::reloadPart(), and PartsBinIconView::reloadPart().
removeAlienParts
void PartsBinPaletteWidget::removeAlienParts () slot
References m_alienParts, and removePart().
removePart()
void PartsBinPaletteWidget::removePart (const QString & moduleID, const QString & path)
References FolderUtils::getUserPartsPath(), m_iconView, m_listView, m_model, m_removed, PartsBinListView::removePart(), PartsBinIconView::removePart(), and PaletteModel::removePart().
removeParts()
void PartsBinPaletteWidget::removeParts ()
References m_iconView, m_listView, m_model, PartsBinListView::removeParts(), PartsBinIconView::removeParts(), and PaletteModel::removeParts().
root()
ModelPart * PartsBinPaletteWidget::root ()
References m_model, and ModelBase::root().
save
bool PartsBinPaletteWidget::save () slot
References currentBinIsCore(), FolderUtils::isEmptyFileName(), m_fileName, m_untitledFileName, saveAs(), and saveAsAux().
saveAs
bool PartsBinPaletteWidget::saveAs () slot
References FritzingWindow::alreadyHasExtension(), fileName(), FritzingBinExtension(), m_defaultSaveFolder, m_fileName, saveAsAux(), and title().
saveAsAux()
bool PartsBinPaletteWidget::saveAsAux (const QString & filename) protected virtual
Implements Bundler.
References DebugDialog::debug(), fileNameUpdated(), BinLocation::findLocation(), hasAlienParts(), m_fileName, m_iconView, m_location, m_model, m_orderHasChanged, m_removed, m_undoStack, PartsBinIconView::orderedChildren(), root(), ModelBase::rootModelPartShared(), ModelBase::save(), saved(), setFilename(), PaletteModel::setOrdererChildren(), and title().
saveBundledBin()
void PartsBinPaletteWidget::saveBundledBin ()
References FritzingBundledBinExtension(), ModelPart::getAllNonCoreParts(), m_fileName, m_isDirty, m_manager, m_model, BinManager::mainWindow(), ModelBase::root(), MainWindow::saveBundledNonAtomicEntity(), and setDirty().
saved
void PartsBinPaletteWidget::saved (bool hasPartsFromBundled) signal
search
void PartsBinPaletteWidget::search () protected slot
References m_manager, m_model, root(), ModelBase::rootModelPartShared(), and BinManager::search().
selectedItemBase()
ItemBase * PartsBinPaletteWidget::selectedItemBase ()
References m_currentView, and PartsBinView::selectedItemBase().
selectedModelPart()
ModelPart * PartsBinPaletteWidget::selectedModelPart ()
References m_currentView, and PartsBinView::selectedModelPart().
setAllowsChanges()
void PartsBinPaletteWidget::setAllowsChanges (bool allowsChanges)
References allowsChanges(), and m_allowsChanges.
setDirty()
void PartsBinPaletteWidget::setDirty (bool dirty = true)
References m_isDirty, m_manager, and BinManager::setDirtyTab().
setFilename()
void PartsBinPaletteWidget::setFilename (const QString & filename) protected
References currentBinIsCore(), m_fileName, m_iconView, m_listView, m_searchStackedWidget, and BinManager::SearchBinLocation.
setInfoViewOnHover()
void PartsBinPaletteWidget::setInfoViewOnHover (bool infoViewOnHover)
References m_iconView, m_listView, and PartsBinView::setInfoViewOnHover().
setPaletteModel()
void PartsBinPaletteWidget::setPaletteModel (PaletteModel * model, bool clear = false)
References afterModelSetted(), m_iconView, m_listView, PartsBinView::setPaletteModel(), and PartsBinIconView::setPaletteModel().
setReadOnly()
void PartsBinPaletteWidget::setReadOnly (bool readOnly)
References readOnly(), and setAllowsChanges().
setSaveQuietly()
void PartsBinPaletteWidget::setSaveQuietly (bool saveQuietly)
References m_saveQuietly.
setTitle()
void PartsBinPaletteWidget::setTitle (const QString & title)
References m_binLabel, m_title, and title().
setupHeader()
void PartsBinPaletteWidget::setupHeader () protected
References ___emptyString___, combinedMenu(), BinManager::combinedMenu(), m_binLabel, m_combinedBinMenuButton, m_header, m_manager, m_searchLineEdit, m_searchStackedWidget, newToolButton(), and search().
setView()
void PartsBinPaletteWidget::setView (class PartsBinView * view) protected
References m_currentView, m_iconView, m_manager, m_stackedWidget, and BinManager::updateViewChecks().
sizeHint()
QSize PartsBinPaletteWidget::sizeHint () const
References DockWidthDefault, and PartsBinHeightDefault.
title()
QString PartsBinPaletteWidget::title () const
References m_title.
toIconView
void PartsBinPaletteWidget::toIconView () slot
References m_iconView, and setView().
toListView
void PartsBinPaletteWidget::toListView () slot
References m_iconView, m_listView, and setView().
undoStackCleanChanged
void PartsBinPaletteWidget::undoStackCleanChanged (bool isClean) protected slot
References currentBinIsCore(), m_manager, BinManager::setDirtyTab(), and setFilename().
Member Data Documentation
m_addPartToMeAction
QAction* PartsBinPaletteWidget::m_addPartToMeAction protected
m_alienParts
QStringList PartsBinPaletteWidget::m_alienParts protected
m_allowsChanges
bool PartsBinPaletteWidget::m_allowsChanges protected
m_binLabel
QLabel* PartsBinPaletteWidget::m_binLabel protected
m_canDeleteModel
bool PartsBinPaletteWidget::m_canDeleteModel protected
m_combinedBinMenuButton
QToolButton* PartsBinPaletteWidget::m_combinedBinMenuButton protected
m_currentView
PartsBinView* PartsBinPaletteWidget::m_currentView protected
m_defaultSaveFolder
QString PartsBinPaletteWidget::m_defaultSaveFolder protected
m_fastLoaded
bool PartsBinPaletteWidget::m_fastLoaded protected
m_fileName
QString PartsBinPaletteWidget::m_fileName protected
m_header
QFrame* PartsBinPaletteWidget::m_header protected
m_icon
QIcon* PartsBinPaletteWidget::m_icon protected
m_iconView
class PartsBinIconView* PartsBinPaletteWidget::m_iconView protected
m_isDirty
bool PartsBinPaletteWidget::m_isDirty protected
m_listView
class PartsBinListView* PartsBinPaletteWidget::m_listView protected
m_loadingProgressDialog
FileProgressDialog* PartsBinPaletteWidget::m_loadingProgressDialog protected
m_location
BinLocation::Location PartsBinPaletteWidget::m_location protected
m_manager
BinManager* PartsBinPaletteWidget::m_manager protected
m_model
PaletteModel* PartsBinPaletteWidget::m_model protected
m_monoIcon
QIcon* PartsBinPaletteWidget::m_monoIcon protected
m_orderHasChanged
bool PartsBinPaletteWidget::m_orderHasChanged protected
m_referenceModel
ReferenceModel* PartsBinPaletteWidget::m_referenceModel protected
m_removed
QStringList PartsBinPaletteWidget::m_removed protected
m_saveQuietly
bool PartsBinPaletteWidget::m_saveQuietly protected
m_searchLineEdit
class SearchLineEdit* PartsBinPaletteWidget::m_searchLineEdit protected
m_searchStackedWidget
QStackedWidget* PartsBinPaletteWidget::m_searchStackedWidget protected
m_stackedWidget
QStackedWidget* PartsBinPaletteWidget::m_stackedWidget protected
m_title
QString PartsBinPaletteWidget::m_title protected
m_undoStack
WaitPushUndoStack* PartsBinPaletteWidget::m_undoStack protected
m_untitledFileName
QString PartsBinPaletteWidget::m_untitledFileName protected
Title
QString PartsBinPaletteWidget::Title static
The documentation for this class was generated from the following files:
partsbinpalette/partsbinpalettewidget.h
partsbinpalette/partsbinpalettewidget.cpp