Fritzing: BusShared Class Reference
BusShared Class Reference
#include <busshared.h>
Public Member Functions
BusShared (const QDomElement &busElement, const QHash< QString, QPointer< class ConnectorShared > > &connectorHash)
BusShared (const QString &id)
void addConnectorShared (class ConnectorShared *)
const QList< class ConnectorShared * > & connectors ()
const QString & id () const
Protected Member Functions
void initConnector (QDomElement &connector, const QHash< QString, QPointer< class ConnectorShared > > &connectorHash)
Protected Attributes
QList< class ConnectorShared * > m_connectors
QString m_id
Constructor & Destructor Documentation
BusShared() [1/2]
BusShared::BusShared (const QDomElement & busElement, const QHash< QString, QPointer< class ConnectorShared > > & connectorHash)
BusShared() [2/2]
BusShared::BusShared (const QString & id)
References id(), and m_id.
Member Function Documentation
addConnectorShared()
void BusShared::addConnectorShared (class ConnectorShared * connectorShared)
References m_connectors, and ConnectorShared::setBus().
connectors()
const QList< ConnectorShared * > & BusShared::connectors ()
References m_connectors.
id()
const QString & BusShared::id () const
References m_id.
initConnector()
void BusShared::initConnector (QDomElement & connector, const QHash< QString, QPointer< class ConnectorShared > > & connectorHash) protected
References DebugDialog::debug(), TextUtils::elementToString(), m_connectors, and ConnectorShared::setBus().
Member Data Documentation
m_connectors
QList<class ConnectorShared *> BusShared::m_connectors protected
m_id
QString BusShared::m_id protected
The documentation for this class was generated from the following files:
connectors/busshared.h
connectors/busshared.cpp