Fritzing: SketchToolButton Class Reference
SketchToolButton Class Reference
#include <sketchtoolbutton.h>
Signals
void entered ()
void left ()
Public Member Functions
SketchToolButton (const QString &imageName, QWidget *parent, QAction *defaultAction)
SketchToolButton (const QString &imageName, QWidget *parent, QList< QAction * > menuActions)
void updateEnabledState ()
Public Member Functions inherited from AbstractStatesButton
virtual ~AbstractStatesButton ()
void setDisabledIcon ()
void setEnabledIcon ()
void setPressedIcon ()
Protected Slots
void setEnabledIconAux ()
Protected Member Functions
void actionEvent (QActionEvent *)
void changeEvent (QEvent *)
void enterEvent (QEvent *)
QString imagePrefix ()
void leaveEvent (QEvent *)
void mousePressEvent (QMouseEvent *)
void mouseReleaseEvent (QMouseEvent *)
void setImage (const QPixmap &pixmap)
void setupIcons (const QString &imageName, bool hasStates=true)
Protected Member Functions inherited from AbstractStatesButton
virtual QString imageSubfix ()
Protected Attributes
QString m_imageName
Protected Attributes inherited from AbstractStatesButton
QPixmap m_disabledImage
QPixmap m_enabledImage
QPixmap m_pressedImage
Constructor & Destructor Documentation
SketchToolButton() [1/2]
SketchToolButton::SketchToolButton (const QString & imageName, QWidget * parent, QAction * defaultAction)
References m_imageName, and setupIcons().
SketchToolButton() [2/2]
SketchToolButton::SketchToolButton (const QString & imageName, QWidget * parent, QList< QAction * > menuActions)
References m_imageName, setEnabledIconAux(), and setupIcons().
Member Function Documentation
actionEvent()
void SketchToolButton::actionEvent (QActionEvent * event) protected
changeEvent()
void SketchToolButton::changeEvent (QEvent * event) protected
References AbstractStatesButton::setDisabledIcon(), and AbstractStatesButton::setEnabledIcon().
entered
void SketchToolButton::entered () signal
enterEvent()
void SketchToolButton::enterEvent (QEvent * event) protected
References entered().
imagePrefix()
QString SketchToolButton::imagePrefix () protected virtual
Implements AbstractStatesButton.
leaveEvent()
void SketchToolButton::leaveEvent (QEvent * event) protected
References left().
left
void SketchToolButton::left () signal
mousePressEvent()
void SketchToolButton::mousePressEvent (QMouseEvent * event) protected
References AbstractStatesButton::setPressedIcon().
mouseReleaseEvent()
void SketchToolButton::mouseReleaseEvent (QMouseEvent * event) protected
References AbstractStatesButton::setEnabledIcon().
setEnabledIconAux
void SketchToolButton::setEnabledIconAux () protected slot
References AbstractStatesButton::setEnabledIcon().
setImage()
void SketchToolButton::setImage (const QPixmap & pixmap) protected virtual
Implements AbstractStatesButton.
setupIcons()
void SketchToolButton::setupIcons (const QString & imageName, bool hasStates = true) protected virtual
Reimplemented from AbstractStatesButton.
References AbstractStatesButton::setupIcons().
updateEnabledState()
void SketchToolButton::updateEnabledState ()
Member Data Documentation
m_imageName
QString SketchToolButton::m_imageName protected
The documentation for this class was generated from the following files:
sketchtoolbutton.h
sketchtoolbutton.cpp