Fritzing: Wire Class Reference
Wire Class Reference
#include <wire.h>
Signals
void wireChangedCurveSignal (Wire *me, const Bezier *oldB, const Bezier *newB, bool triggerFirstTime)
void wireChangedSignal (Wire *me, const QLineF &oldLine, const QLineF &newLine, QPointF oldPos, QPointF newPos, ConnectorItem *from, ConnectorItem *to)
void wireJoinSignal (Wire *me, ConnectorItem *clickedConnectorItem)
void wireSplitSignal (Wire *me, QPointF newPos, QPointF oldPos, const QLineF &oldLine)
Public Member Functions
Wire (class ModelPart *, ViewLayer::ViewID, const ViewGeometry &, long id, QMenu *itemMenu, bool initLabel)
virtual ~Wire ()
void addedToScene (bool temporary)
bool banded ()
QRectF boundingRect () const
bool canChainMultiple ()
bool canChangeColor ()
bool canHaveCurve ()
virtual bool canSwitchLayers ()
void changeCurve (const class Bezier *)
void collectChained (QList< Wire * > &, QList< ConnectorItem * > &ends)
void collectDirectWires (QList< Wire * > &wires)
bool collectExtraInfo (QWidget *parent, const QString &family, const QString &prop, const QString &value, bool swappingEnabled, QString &returnProp, QString &returnValue, QWidget *&returnWidget, bool &hide)
void collectWires (QList< Wire * > &wires)
const QColor & color ()
void colorByLength (bool)
QString colorString ()
void connectedMoved (ConnectorItem *from, ConnectorItem *to, QList< ConnectorItem * > &already)
ConnectorItem * connector0 ()
QRectF connector0Rect (const QLineF &line)
ConnectorItem * connector1 ()
QRectF connector1Rect (const QLineF &line)
void cursorKeyEvent (Qt::KeyboardModifiers modifiers)
const class Bezier * curve ()
bool draggingEnd ()
void findConnectorsUnder ()
Wire * findTraced (ViewGeometry::WireFlags flags, QList< ConnectorItem * > &ends)
bool getAutoroutable ()
bool getNormal ()
virtual const QLineF & getPaintLine ()
bool getRouted ()
bool getTrace ()
bool hasAnyFlag (ViewGeometry::WireFlags)
bool hasFlag (ViewGeometry::WireFlag)
bool hasPartLabel ()
bool hasPartNumberProperty ()
bool hasShadow ()
QString hexString ()
void hoverEnterConnectorItem (QGraphicsSceneHoverEvent *event, class ConnectorItem *item)
void hoverLeaveConnectorItem (QGraphicsSceneHoverEvent *event, class ConnectorItem *item)
QPainterPath hoverShape () const
double hoverStrokeWidth ()
void initDragCurve (QPointF scenePos)
void initDragEnd (ConnectorItem *dragEnd, QPointF scenePos)
bool initNewBendpoint (QPointF scenePos, class Bezier &left, class Bezier &right)
bool isCurved ()
bool isGrounded ()
PluralType isPlural ()
bool isTraceType (ViewGeometry::WireFlag)
bool itemMoved ()
QLineF line () const
double mils ()
void moveItem (ViewGeometry &viewGeometry)
double opacity ()
void originalConnectorDimensions (double &width, double &height)
ConnectorItem * otherConnector (ConnectorItem *)
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)
void paintBody (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
QPen pen () const
bool rotation45Allowed ()
bool rotationAllowed ()
void saveGeometry ()
void saveInstanceLocation (QXmlStreamWriter &)
QPolygonF sceneCurve (QPointF offset)
void setAutoroutable (bool)
void setBanded (bool)
void setCanChainMultiple (bool)
virtual void setColor (const QColor &, double opacity)
void setColorString (QString, double opacity, bool restore)
void setConnector0Rect ()
void setConnector1Rect ()
void setConnectorDimensions (double width, double height)
void setDisplayBendpointCursor (bool)
void setExtras (QDomElement &, InfoGraphicsView *)
virtual void setLine (const QLineF &line)
void setLine (double x1, double y1, double x2, double y2)
void setLineAnd (QLineF line, QPointF pos, bool useLine)
void setNormal (bool)
void setOpacity (double opacity)
void setPcbPenBrush (QBrush &brush)
void setPen (const QPen &pen)
void setPenWidth (double width, InfoGraphicsView *, double hoverStrokeWidth)
void setProp (const QString &prop, const QString &value)
void setRatsnest (bool)
void setRouted (bool)
virtual class FSvgRenderer * setUp (ViewLayer::ViewLayerID viewLayerID, const LayerHash &viewLayers, class InfoGraphicsView *)
void setWireFlags (ViewGeometry::WireFlags)
void setWireWidth (double width, InfoGraphicsView *, double hoverStrokeWidth)
QString shadowHexString ()
double shadowWidth ()
QPainterPath shape () const
void simpleConnectedMoved (ConnectorItem *to)
void simpleConnectedMoved (ConnectorItem *from, ConnectorItem *to)
bool stickyEnabled ()
const class Bezier * undoCurve ()
double width ()
void writeGeometry (QXmlStreamWriter &)
Public Member Functions inherited from ItemBase
ItemBase (ModelPart *, ViewLayer::ViewID, const ViewGeometry &, long id, QMenu *itemMenu)
virtual ~ItemBase ()
virtual bool acceptsMousePressConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual bool acceptsMousePressLegEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual void addSticky (ItemBase *, bool stickem)
void addSubpart (ItemBase *)
virtual bool alreadySticking (ItemBase *itemBase)
ConnectorItem * anyConnectorItem ()
QRectF boundingRect () const
virtual QRectF boundingRectWithoutLegs () const
virtual void busConnectorItems (Bus *bus, ConnectorItem *, QList< ConnectorItem * > &items)
QList< Bus * > buses ()
const QList< ConnectorItem * > & cachedConnectorItems ()
const QList< ConnectorItem * > & cachedConnectorItemsConst () const
virtual void calcRotation (QTransform &rotation, QPointF center, ViewGeometry &)
virtual bool canEditPart ()
bool canFlip (Qt::Orientations)
bool canFlipHorizontal ()
bool canFlipVertical ()
virtual void clearConnectorHover ()
void clearConnectorItemCache ()
virtual void clearModelPart ()
void clearPartLabel ()
void collectConnectors (ConnectorPairHash &connectorHash, SkipCheckFunction)
virtual bool collectFemaleConnectees (QSet< ItemBase * > &items)
void collectPropsMap (QString &family, QMap< QString, QString > &)
virtual void collectWireConnectees (QSet< Wire * > &wires)
virtual void connectorHover (ConnectorItem *, ItemBase *, bool hovering)
const QString & constTitle () const
void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
void debugInfo (const QString &msg) const
void debugInfo2 (const QString &msg) const
virtual void doneLoading ()
void doRotateFlipPartLabel (double degrees, Qt::Orientations)
void ensureUniqueTitle (const QString &title, bool force)
QString family ()
virtual void figureHover ()
const QString & filename ()
virtual bool filterMousePressConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
ConnectorItem * findConnectorItemWithSharedID (const QString &connectorID, ViewLayer::ViewLayerPlacement)
ConnectorItem * findConnectorItemWithSharedID (const QString &connectorID)
ItemBase * findSubpart (const QString &connectorID, ViewLayer::ViewLayerPlacement)
virtual void flipItem (Qt::Orientations orientation)
virtual bool freeRotationAllowed ()
FSvgRenderer * fsvgRenderer () const
virtual const QCursor * getCursor (Qt::KeyboardModifiers)
virtual void getEqualPotentialColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
virtual void getHoverColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
virtual QString getInspectorTitle ()
virtual void getNormalColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
QPixmap * getPixmap (QSize size)
void getPixmaps (QPixmap *&, QPixmap *&, QPixmap *&, bool swappingEnabled, QSize)
virtual QString getProperty (const QString &key)
bool getRatsnest ()
virtual void getUnconnectedColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
ViewGeometry & getViewGeometry ()
bool hasConnections ()
bool hasConnectors ()
virtual bool hasCustomSVG ()
bool hasNonConnectors ()
bool hasRubberBandLeg () const
constexpr bool hidden () const noexcept
void hoverEnterConnectorItem ()
void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
void hoverLeaveConnectorItem ()
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
virtual void hoverMoveConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
virtual void hoverUpdate ()
constexpr qint64 id () const noexcept
constexpr bool inactive () const noexcept
bool inHover ()
void initLayerAttributes (LayerAttributes &layerAttributes, ViewLayer::ViewID, ViewLayer::ViewLayerID, ViewLayer::ViewLayerPlacement, bool doConnectors, bool doCreateShape)
virtual bool inRotation ()
const QString & instanceTitle () const
virtual bool isBaseSticky ()
bool isEverVisible ()
bool isLocalSticky ()
bool isObsolete ()
bool isPartLabelVisible ()
virtual bool isSticky ()
virtual bool isSwappable ()
int itemType () const
void killRubberBandLeg ()
QString label ()
constexpr bool layerHidden () const noexcept
virtual const QList< ItemBase * > & layerKin ()
virtual ItemBase * layerKinChief ()
QString makePartLabelSvg (bool blackOnly, double dpi, double printerScale)
ModelPart * modelPart ()
ModelPartShared * modelPartShared ()
const QString & moduleID ()
void mousePressEvent (QGraphicsSceneMouseEvent *event)
bool moveLock ()
void movePartLabel (QPointF newPos, QPointF newOffset)
virtual ConnectorItem * newConnectorItem (Connector *connector)
virtual ConnectorItem * newConnectorItem (ItemBase *layerkin, Connector *connector)
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
PartLabel * partLabel ()
void partLabelMoved (QPointF oldPos, QPointF oldOffset, QPointF newPos, QPointF newOffset)
QRectF partLabelSceneBoundingRect ()
QPointF partLabelScenePos ()
void partLabelSetHidden (bool hide)
ViewLayer::ViewLayerID partLabelViewLayerID ()
void prepareGeometryChange ()
virtual QHash< QString, QString > prepareProps (ModelPart *, bool wantDebug, QStringList &keys)
QString prop (const QString &p)
bool reloadRenderer (const QString &svg, bool fastload)
virtual void removeLayerKin ()
void removeTooltip ()
virtual void resetID ()
bool resetRenderer (const QString &svg)
bool resetRenderer (const QString &svg, QString &newSvg)
void resetValues (const QString &family, const QString &prop)
void restorePartLabel (QDomElement &labelGeometry, ViewLayer::ViewLayerID)
virtual QString retrieveSvg (ViewLayer::ViewLayerID, QHash< QString, QString > &svgHash, bool blackOnly, double dpi, double &factor)
ConnectorItem * rightClickedConnector ()
void rotateFlipPartLabel (double degrees, Qt::Orientations)
virtual void rotateItem (double degrees, bool includeRatsnest)
virtual void saveInstance (QXmlStreamWriter &)
bool sceneEvent (QEvent *event)
const QPainterPath & selectionShape ()
virtual void setAcceptsMousePressLegEvent (bool)
void setCanFlipHorizontal (bool)
void setCanFlipVertical (bool)
virtual void setDropOffset (QPointF offset)
void setEverVisible (bool)
void setFilename (const QString &)
virtual void setHidden (bool hidden)
virtual void setInactive (bool inactivate)
virtual void setInRotation (bool)
virtual void setInspectorTitle (const QString &oldText, const QString &newText)
virtual void setInstanceTitle (const QString &title, bool initial)
void setItemIsSelectable (bool selectable)
virtual void setItemPos (QPointF &pos)
virtual void setLayerHidden (bool hidden)
void setLocalSticky (bool)
void setModelPart (ModelPart *)
virtual void setMoveLock (bool)
void setSharedRendererEx (FSvgRenderer *)
void setSquashShape (bool)
virtual void setSticky (bool)
void setSuperpart (ItemBase *)
virtual void setSwappable (bool)
void setTooltip ()
virtual void setTransform2 (const QTransform &)
FSvgRenderer * setUpImage (ModelPart *modelPart, LayerAttributes &)
void setViewLayerID (ViewLayer::ViewLayerID, const LayerHash &viewLayers)
void setViewLayerID (const QString &layerName, const LayerHash &viewLayers)
void setViewLayerPlacement (ViewLayer::ViewLayerPlacement)
void showConnectors (const QStringList &)
constexpr QSizeF size () const noexcept
virtual void slamZ (double newZ)
const QString & spice () const
const QString & spiceModel () const
virtual ItemBase * stickingTo ()
virtual QList< QPointer< ItemBase > > stickyList ()
const QList< QPointer< ItemBase > > & subparts ()
ItemBase * superpart ()
virtual const QString & title ()
bool topLevel ()
virtual void transformItem (const QTransform &, bool includeRatsnest)
virtual void transformItem2 (const QMatrix &)
void updateConnections (ConnectorItem *, bool includeRatsnest, QList< ConnectorItem * > &already)
virtual void updateConnections (bool includeRatsnest, QList< ConnectorItem * > &already)
void updateConnectionsAux (bool includeRatsnest, QList< ConnectorItem * > &already)
void updateConnectors ()
void updatePartLabelInstanceTitle ()
virtual void updateTooltip ()
ViewLayer::ViewID viewID ()
QString & viewIDName ()
ViewLayer::ViewLayerID viewLayerID () const
ViewLayer::ViewLayerPlacement viewLayerPlacement () const
ViewGeometry::WireFlags wireFlags () const
virtual void writeXml (QXmlStreamWriter &)
double z ()
Static Public Member Functions
static void cleanup ()
static void initNames ()
Static Public Member Functions inherited from ItemBase
static void cleanup ()
static QColor connectedColor ()
static ItemBase * extractTopLevelItemBase (QGraphicsItem *thing)
static qint64 getNextID ()
static qint64 getNextID (qint64 fromIndex)
static void initNames ()
static void renderOne (QDomDocument *, QImage *, const QRectF &renderRect)
static void setConnectedColor (QColor &)
static void setReferenceModel (ReferenceModel *)
static void setUnconnectedColor (QColor &)
static QColor standardConnectedColor ()
static QColor standardUnconnectedColor ()
static QString translatePropertyName (const QString &key)
static QColor unconnectedColor ()
static bool zLessThan (ItemBase *&p1, ItemBase *&p2)
Static Public Attributes
static QStringList colorNames
static QHash< QString, QString > colorTrans
static double HALF_STANDARD_TRACE_WIDTH = 0.0
static QList< QColor > lengthColorTrans
static double STANDARD_TRACE_WIDTH = 0.0
static QVector< qreal > TheDash
static double THIN_TRACE_WIDTH = 0.0
static QList< int > widths
static QHash< int, QString > widthTrans
Static Public Attributes inherited from ItemBase
static const QColor ConnectorHoverColor
static const double ConnectorHoverOpacity = .40
static const QList< ItemBase * > EmptyList
static const QColor HoverColor
static const double HoverOpacity = .20
static const QString ITEMBASE_FONT_PREFIX = "<font size='2'>"
static const QString ITEMBASE_FONT_SUFFIX = "</font>"
static QString PartInstanceDefaultTitle
static QHash< QString, QString > TranslatedPropertyNames
Protected Slots
void colorEntry (const QString &text)
void setBandedProp (bool)
Protected Member Functions
bool acceptsMouseDoubleClickConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
bool acceptsMouseMoveConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
bool acceptsMouseReleaseConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
void calcNewLine (ConnectorItem *from, ConnectorItem *to, QPointF &p1, QPointF &p2)
void checkVisibility (ConnectorItem *onMe, ConnectorItem *onIt, bool connect)
void collectChained (ConnectorItem *connectorItem, QList< Wire * > &chained, QList< ConnectorItem * > &ends)
void collectDirectWires (ConnectorItem *connectorItem, QList< Wire * > &wires, QList< ConnectorItem * > &junctions)
void collectWiresAux (QList< Wire * > &wires, ConnectorItem *start)
bool coloredByLength ()
QColor colorForLength ()
void connectionChange (ConnectorItem *onMe, ConnectorItem *onIt, bool connect)
bool connectionIsAllowed (ConnectorItem *)
void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
void dragCurve (QPointF eventPos, Qt::KeyboardModifiers)
void getConnectedColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
void initEnds (const ViewGeometry &, QRectF defaultRect, class InfoGraphicsView *)
bool isBendpoint (ConnectorItem *connectorItem)
QVariant itemChange (GraphicsItemChange change, const QVariant &value)
void mouseDoubleClickConnectorEvent (ConnectorItem *)
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event)
void mouseMoveConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
void mouseMoveEventAux (QPointF eventPos, Qt::KeyboardModifiers)
void mousePressConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
void mousePressEvent (QGraphicsSceneMouseEvent *event)
void mouseReleaseConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
void paintHover (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
bool releaseDrag ()
virtual void setColorFromElement (QDomElement &element)
void setConnectorDimensionsAux (ConnectorItem *, double width, double height)
void setIgnoreSelectionChange (bool)
void setShadowColor (QColor &, bool restore)
virtual class FSvgRenderer * setUpConnectors (class ModelPart *, ViewLayer::ViewID)
QPainterPath shapeAux (double width) const
void updateCursor (Qt::KeyboardModifiers)
ViewLayer::ViewID useViewIDForPixmap (ViewLayer::ViewID, bool swappingEnabled)
Protected Member Functions inherited from ItemBase
virtual QStringList collectValues (const QString &family, const QString &prop, QString &value)
void createShape (LayerAttributes &layerAttributes)
QPixmap * getPixmap (ViewLayer::ViewID, bool swappingEnabled, QSize size)
QVariant itemChange (QGraphicsItem::GraphicsItemChange change, const QVariant &value)
virtual bool makeLocalModifications (QByteArray &svg, const QString &filename)
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
virtual void paintHover (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget, const QPainterPath &shape)
virtual void paintSelected (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
void saveLocAndTransform (QXmlStreamWriter &streamWriter)
virtual void setDefaultTooltip ()
void setInstanceTitleAux (const QString &title, bool initial)
void setInstanceTitleTooltip (const QString &text)
void updateHidden ()
Protected Attributes
bool m_banded
QPen m_bendpoint2Pen
double m_bendpoint2Width
QPen m_bendpointPen
double m_bendpointWidth
class Bezier * m_bezier
bool m_canChainMultiple
bool m_canHaveCurve
bool m_colorByLength
QString m_colorName
QPointer< class ConnectorItem > m_connector0
QPointer< class ConnectorItem > m_connector1
QPointer< class ConnectorItem > m_connectorHover
bool m_displayBendpointCursor
bool m_drag0
bool m_dragCurve
bool m_dragEnd
double m_hoverStrokeWidth
bool m_ignoreSelectionChange
QLineF m_line
bool m_markedDeleted
bool m_negativeOffsetRect
double m_opacity
QRectF m_originalConnectorRect
QPen m_pen
QBrush m_shadowBrush
QPen m_shadowPen
QPointF m_wireDragOrigin
Protected Attributes inherited from ItemBase
bool m_acceptsMousePressLegEvent = true
QList< ConnectorItem * > m_cachedConnectorItems
bool m_canFlipHorizontal = false
bool m_canFlipVertical = false
int m_connectorHoverCount = 0
int m_connectorHoverCount2 = 0
bool m_everVisible = true
QString m_filename
FSvgRenderer * m_fsvgRenderer = nullptr
bool m_hasRubberBandLeg = false
bool m_hidden = false
int m_hoverCount = 0
bool m_hoverEnterSpaceBarWasPressed = false
qint64 m_id = 0
bool m_inactive = false
bool m_inRotation = false
QMenu * m_itemMenu = nullptr
bool m_layerHidden = false
QPointer< ModelPart > m_modelPart
bool m_moveLock = false
QGraphicsSvgItem * m_moveLockItem = nullptr
QPointer< PartLabel > m_partLabel
QMap< QString, QString > m_propsMap
ConnectorItem * m_rightClickedConnector = nullptr
QPainterPath m_selectionShape
QSizeF m_size
bool m_spaceBarWasPressed = false
bool m_squashShape = false
bool m_sticky = false
QGraphicsSvgItem * m_stickyItem = nullptr
QHash< long, QPointer< ItemBase > > m_stickyList
QList< QPointer< ItemBase > > m_subparts
QPointer< ItemBase > m_superpart
bool m_swappable = true
ViewGeometry m_viewGeometry
ViewLayer::ViewID m_viewID
ViewLayer::ViewLayerID m_viewLayerID
ViewLayer::ViewLayerPlacement m_viewLayerPlacement
bool m_zUninitialized = true
Additional Inherited Members
Public Types inherited from ItemBase
enum PluralType { Singular, Plural, NotSure }
Public Slots inherited from ItemBase
void hidePartLabel ()
void partLabelChanged (const QString &newText)
void showInFolder ()
void showPartLabel (bool show, ViewLayer *)
virtual void swapEntry (const QString &text)
Static Protected Member Functions inherited from ItemBase
static bool fixCopper1 (ModelPart *modelPart, const QString &filename, ViewLayer::ViewLayerID viewLayerID, ViewLayer::ViewLayerPlacement, QDomDocument &)
static bool getFlipDoc (ModelPart *modelPart, const QString &filename, ViewLayer::ViewLayerID viewLayerID, ViewLayer::ViewLayerPlacement, QDomDocument &, Qt::Orientations)
Static Protected Attributes inherited from ItemBase
static QBrush ChosenBrush
static QPen ChosenPen
static QBrush ConnectedBrush
static QPen ConnectedPen
static QBrush EqualPotentialBrush
static QPen EqualPotentialPen
static QBrush HoverBrush
static QPen HoverPen
static long nextID
static QBrush NormalBrush
static constexpr double NormalConnectorOpacity = 0.4
static QPen NormalPen
static QPointer< ReferenceModel > TheReferenceModel = nullptr
static QBrush UnconnectedBrush
static QPen UnconnectedPen
Constructor & Destructor Documentation
Wire()
Wire::Wire (class ModelPart * modelPart, ViewLayer::ViewID viewID, const ViewGeometry & viewGeometry, long id, QMenu * itemMenu, bool initLabel)
References DefaultHoverStrokeWidth, ViewGeometry::loc(), m_banded, m_bezier, m_canChainMultiple, m_canHaveCurve, m_colorByLength, m_connector0, m_connector1, m_connectorHover, m_displayBendpointCursor, m_dragCurve, m_dragEnd, m_hoverStrokeWidth, m_ignoreSelectionChange, m_opacity, ItemBase::m_partLabel, and ItemBase::m_viewGeometry.
~Wire()
Wire::~Wire () virtual
References m_bezier.
Member Function Documentation
acceptsMouseDoubleClickConnectorEvent()
bool Wire::acceptsMouseDoubleClickConnectorEvent (ConnectorItem * , QGraphicsSceneMouseEvent *) protected virtual
Reimplemented from ItemBase.
acceptsMouseMoveConnectorEvent()
bool Wire::acceptsMouseMoveConnectorEvent (ConnectorItem * , QGraphicsSceneMouseEvent *) protected virtual
Reimplemented from ItemBase.
acceptsMouseReleaseConnectorEvent()
bool Wire::acceptsMouseReleaseConnectorEvent (ConnectorItem * , QGraphicsSceneMouseEvent *) protected virtual
Reimplemented from ItemBase.
addedToScene()
void Wire::addedToScene (bool temporary) virtual
Reimplemented from ItemBase.
References ItemBase::addedToScene(), InfoGraphicsView::getInfoGraphicsView(), and InfoGraphicsView::newWire().
banded()
bool Wire::banded ()
References m_banded.
boundingRect()
QRectF Wire::boundingRect () const
References hoverShape(), m_line, m_pen, qMax(), and qMin().
calcNewLine()
void Wire::calcNewLine (ConnectorItem * from, ConnectorItem * to, QPointF & p1, QPointF & p2) protected
References m_connector0, m_connector1, and ConnectorItem::sceneAdjustedTerminalPoint().
canChainMultiple()
bool Wire::canChainMultiple ()
References m_canChainMultiple.
canChangeColor()
bool Wire::canChangeColor ()
References ItemBase::getRatsnest(), getTrace(), ItemBase::m_viewID, and ViewLayer::SchematicView.
canHaveCurve()
bool Wire::canHaveCurve ()
References ItemBase::getRatsnest(), and m_canHaveCurve.
canSwitchLayers()
bool Wire::canSwitchLayers () virtual
Reimplemented in TraceWire.
changeCurve()
void Wire::changeCurve (const class Bezier *)
References Bezier::copy(), m_bezier, and ItemBase::prepareGeometryChange().
checkVisibility()
void Wire::checkVisibility (ConnectorItem * onMe, ConnectorItem * onIt, bool connect) protected
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToItemType(), ConnectorItem::connectedToItems(), otherConnector(), and ModelPart::Wire.
cleanup()
void Wire::cleanup () static
collectChained() [1/2]
void Wire::collectChained (QList< Wire * > & chained, QList< ConnectorItem * > & ends)
References m_connector0, and m_connector1.
collectChained() [2/2]
void Wire::collectChained (ConnectorItem * connectorItem, QList< Wire * > & chained, QList< ConnectorItem * > & ends) protected
References NonConnectorItem::attachedTo(), and ConnectorItem::connectedToItems().
collectDirectWires() [1/2]
void Wire::collectDirectWires (QList< Wire * > & wires)
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToItemType(), collectDirectWires(), ConnectorItem::connectedToItems(), connector0(), connector1(), m_connector0, m_connector1, and ModelPart::Wire.
collectDirectWires() [2/2]
void Wire::collectDirectWires (ConnectorItem * connectorItem, QList< Wire * > & wires, QList< ConnectorItem * > & junctions) protected
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToItemType(), collectDirectWires(), ConnectorItem::connectedToItems(), ConnectorItem::connectionsCount(), otherConnector(), and ModelPart::Wire.
collectExtraInfo()
bool Wire::collectExtraInfo (QWidget * parent, const QString & family, const QString & prop, const QString & value, bool swappingEnabled, QString & returnProp, QString & returnValue, QWidget *& returnWidget, bool & hide) virtual
Reimplemented from ItemBase.
References canChangeColor(), ItemBase::collectExtraInfo(), colorEntry(), colorNames, colorString(), colorTrans, ItemBase::family(), hasShadow(), m_banded, ItemBase::m_viewID, ItemBase::prop(), ViewLayer::SchematicView, and setBandedProp().
collectWires()
void Wire::collectWires (QList< Wire * > & wires)
References collectWiresAux(), m_connector0, and m_connector1.
collectWiresAux()
void Wire::collectWiresAux (QList< Wire * > & wires, ConnectorItem * start) protected
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToItemType(), collectWires(), ConnectorItem::connectedToItems(), and ModelPart::Wire.
color()
const QColor & Wire::color ()
References m_pen.
colorByLength()
void Wire::colorByLength (bool colorByLength)
References m_colorByLength.
coloredByLength()
bool Wire::coloredByLength () protected
References m_colorByLength.
colorEntry
void Wire::colorEntry (const QString & text) protected slot
References InfoGraphicsView::changeWireColor(), color(), and InfoGraphicsView::getInfoGraphicsView().
colorForLength()
QColor Wire::colorForLength () protected
References color(), lengthColorTrans, m_bezier, and m_line.
colorString()
QString Wire::colorString ()
References m_colorName.
connectedMoved()
void Wire::connectedMoved (ConnectorItem * from, ConnectorItem * to, QList< ConnectorItem * > & already) virtual
Reimplemented from ItemBase.
References ConnectorItem::connectedToItems(), and simpleConnectedMoved().
connectionChange()
void Wire::connectionChange (ConnectorItem * onMe, ConnectorItem * onIt, bool connect) protected virtual
Reimplemented from ItemBase.
References NonConnectorItem::attachedToItemType(), checkVisibility(), m_connector0, m_connector1, and ModelPart::Wire.
connectionIsAllowed()
bool Wire::connectionIsAllowed (ConnectorItem * to) protected virtual
Reimplemented from ItemBase.
References NonConnectorItem::attachedTo(), ViewLayer::BreadboardView, ItemBase::connectionIsAllowed(), ItemBase::getRatsnest(), and ItemBase::m_viewID.
connector0()
ConnectorItem * Wire::connector0 ()
References m_connector0.
connector0Rect()
QRectF Wire::connector0Rect (const QLineF & line)
References m_connector0.
connector1()
ConnectorItem * Wire::connector1 ()
References m_connector1.
connector1Rect()
QRectF Wire::connector1Rect (const QLineF & line)
References line(), and m_connector1.
contextMenuEvent()
void Wire::contextMenuEvent (QGraphicsSceneContextMenuEvent * event) protected
References ItemBase::contextMenuEvent(), InfoGraphicsView::getInfoGraphicsView(), and InfoGraphicsView::setActiveWire().
cursorKeyEvent()
void Wire::cursorKeyEvent (Qt::KeyboardModifiers modifiers) virtual
Implements CursorKeyListener.
References InfoGraphicsView::getInfoGraphicsView(), m_dragCurve, m_dragEnd, and updateCursor().
curve()
const Bezier * Wire::curve ()
References m_bezier.
dragCurve()
void Wire::dragCurve (QPointF eventPos, Qt::KeyboardModifiers) protected
References m_bezier, and Bezier::recalc().
draggingEnd()
bool Wire::draggingEnd ()
References m_dragCurve, and m_dragEnd.
findConnectorsUnder()
void Wire::findConnectorsUnder () virtual
Implements ItemBase.
References ItemBase::cachedConnectorItems(), ConnectorItem::connectionsCount(), ConnectorItem::emptyConnectorItemList, and ConnectorItem::findConnectorUnder().
findTraced()
Wire * Wire::findTraced (ViewGeometry::WireFlags flags, QList< ConnectorItem * > & ends)
References collectChained(), DebugDialog::debug(), and ConnectorItem::directlyWiredTo().
getAutoroutable()
bool Wire::getAutoroutable ()
References ViewGeometry::getAutoroutable(), and ItemBase::m_viewGeometry.
getConnectedColor()
void Wire::getConnectedColor (ConnectorItem * connectorItem, QBrush & brush, QPen & pen, double & opacity, double & negativePenWidth, bool & negativeOffsetRect) protected virtual
Reimplemented from ItemBase.
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToItemType(), ConnectorItem::connectedToItems(), ConnectorItem::connectionsCount(), ItemBase::getConnectedColor(), InfoGraphicsView::getInfoGraphicsView(), InfoGraphicsView::getTraceFlag(), InfoGraphicsView::hasBigDots(), isTraceType(), m_bendpoint2Pen, m_bendpoint2Width, m_bendpointPen, m_bendpointWidth, m_negativeOffsetRect, m_shadowBrush, opacity(), pen(), ViewGeometry::SchematicTraceFlag, ConnectorItem::setBigDot(), and ModelPart::Wire.
getNormal()
bool Wire::getNormal ()
References ViewGeometry::getNormal(), and ItemBase::m_viewGeometry.
getPaintLine()
const QLineF & Wire::getPaintLine () virtual
Reimplemented in ClipableWire.
References m_line.
getRouted()
bool Wire::getRouted ()
References ViewGeometry::getRouted(), and ItemBase::m_viewGeometry.
getTrace()
bool Wire::getTrace ()
References ViewGeometry::getAnyTrace(), and ItemBase::m_viewGeometry.
hasAnyFlag()
bool Wire::hasAnyFlag (ViewGeometry::WireFlags flags)
References ViewGeometry::hasAnyFlag(), and ItemBase::m_viewGeometry.
hasFlag()
bool Wire::hasFlag (ViewGeometry::WireFlag flag)
References ViewGeometry::hasFlag(), and ItemBase::m_viewGeometry.
hasPartLabel()
bool Wire::hasPartLabel () virtual
Reimplemented from ItemBase.
hasPartNumberProperty()
bool Wire::hasPartNumberProperty () virtual
Reimplemented from ItemBase.
hasShadow()
bool Wire::hasShadow ()
References ItemBase::getRatsnest(), getTrace(), m_pen, and m_shadowPen.
hexString()
QString Wire::hexString ()
References m_pen.
hoverEnterConnectorItem()
void Wire::hoverEnterConnectorItem (QGraphicsSceneHoverEvent * event, class ConnectorItem * item) virtual
Reimplemented from ItemBase.
References ItemBase::hoverEnterConnectorItem(), and m_connectorHover.
hoverEnterEvent()
void Wire::hoverEnterEvent (QGraphicsSceneHoverEvent * event) protected
References CursorMaster::addCursor(), ItemBase::hoverEnterEvent(), CursorMaster::instance(), and updateCursor().
hoverLeaveConnectorItem()
void Wire::hoverLeaveConnectorItem (QGraphicsSceneHoverEvent * event, class ConnectorItem * item) virtual
Reimplemented from ItemBase.
References ItemBase::hoverLeaveConnectorItem(), and m_connectorHover.
hoverLeaveEvent()
void Wire::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) protected
References ItemBase::hoverLeaveEvent(), CursorMaster::instance(), and CursorMaster::removeCursor().
hoverShape()
QPainterPath Wire::hoverShape () const virtual
Reimplemented from ItemBase.
References m_hoverStrokeWidth, and shapeAux().
hoverStrokeWidth()
double Wire::hoverStrokeWidth ()
References m_hoverStrokeWidth.
initDragCurve()
void Wire::initDragCurve (QPointF scenePos)
References connector0(), connector1(), Bezier::copy(), Bezier::initControlIndex(), BezierDisplay::initDisplay(), Bezier::initToEnds(), Bezier::isEmpty(), m_bezier, m_dragCurve, m_dragEnd, m_pen, ConnectorItem::sceneAdjustedTerminalPoint(), Bezier::set_endpoints(), TheBezierDisplay, and UndoBezier.
initDragEnd()
void Wire::initDragEnd (ConnectorItem * dragEnd, QPointF scenePos)
References ConnectorItem::chained(), collectChained(), line(), m_connector0, m_drag0, m_dragCurve, m_dragEnd, m_wireDragOrigin, and saveGeometry().
initEnds()
void Wire::initEnds (const ViewGeometry & vg, QRectF defaultRect, class InfoGraphicsView * infoGraphicsView) protected
References ItemBase::cachedConnectorItems(), ConnectorItem::connectorSharedID(), InfoGraphicsView::initWire(), ViewGeometry::line(), line(), m_connector0, m_connector1, m_pen, m_shadowPen, ItemBase::m_viewGeometry, pen(), ItemBase::prepareGeometryChange(), setConnector0Rect(), setConnector1Rect(), ViewGeometry::setLine(), setLine(), and setPen().
initNames()
void Wire::initNames () static
References colorNames, colorTrans, HALF_STANDARD_TRACE_WIDTH, lengthColorTrans, GraphicsUtils::mils2pixels(), RatDash, STANDARD_TRACE_WIDTH, GraphicsUtils::SVGDPI, TheDash, THIN_TRACE_WIDTH, widths, and widthTrans.
initNewBendpoint()
bool Wire::initNewBendpoint (QPointF scenePos, class Bezier & left, class Bezier & right)
References Bezier::clear(), connector0(), connector1(), Bezier::copy(), Bezier::findSplit(), Bezier::isEmpty(), m_bezier, m_pen, ConnectorItem::sceneAdjustedTerminalPoint(), Bezier::set_endpoints(), Bezier::split(), and UndoBezier.
isBendpoint()
bool Wire::isBendpoint (ConnectorItem * connectorItem) protected
References ConnectorItem::isBendpoint().
isCurved()
bool Wire::isCurved ()
References Bezier::isEmpty(), and m_bezier.
isGrounded()
bool Wire::isGrounded ()
References connector0(), connector1(), and ConnectorItem::isGrounded().
isPlural()
ItemBase::PluralType Wire::isPlural () virtual
Reimplemented from ItemBase.
References ItemBase::Plural.
isTraceType()
bool Wire::isTraceType (ViewGeometry::WireFlag flag)
References hasFlag().
itemChange()
QVariant Wire::itemChange (GraphicsItemChange change, const QVariant & value) protected
References collectChained(), InfoGraphicsView::getInfoGraphicsView(), ItemBase::itemChange(), m_ignoreSelectionChange, ItemBase::m_partLabel, setIgnoreSelectionChange(), and InfoGraphicsView::setIgnoreSelectionChangeEvents().
itemMoved()
bool Wire::itemMoved () virtual
Implements ItemBase.
References ViewGeometry::line(), line(), ViewGeometry::loc(), and ItemBase::m_viewGeometry.
line()
QLineF Wire::line () const
Returns the item's line, or a null line if no line has been set.
See also
setLine()
References m_line.
mils()
double Wire::mils ()
References m_pen, and GraphicsUtils::SVGDPI.
mouseDoubleClickConnectorEvent()
void Wire::mouseDoubleClickConnectorEvent (ConnectorItem * connectorItem) protected virtual
Reimplemented from ItemBase.
References NonConnectorItem::attachedToItemType(), ConnectorItem::connectedToItems(), ModelPart::Wire, and wireJoinSignal().
mouseDoubleClickEvent()
void Wire::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) protected
References line(), and wireSplitSignal().
mouseMoveConnectorEvent()
void Wire::mouseMoveConnectorEvent (ConnectorItem * connectorItem, QGraphicsSceneMouseEvent * event) protected virtual
Reimplemented from ItemBase.
References mouseMoveEventAux().
mouseMoveEvent()
void Wire::mouseMoveEvent (QGraphicsSceneMouseEvent * event) protected
References mouseMoveEventAux().
mouseMoveEventAux()
void Wire::mouseMoveEventAux (QPointF eventPos, Qt::KeyboardModifiers modifiers) protected
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToItemType(), ItemBase::cachedConnectorItems(), GraphicsUtils::calcConstraint(), collectChained(), ConnectorItem::connectedToItems(), GraphicsUtils::distanceSqd(), dragCurve(), ConnectorItem::findConnectorUnder(), InfoGraphicsView::getInfoGraphicsView(), ItemBase::getRatsnest(), InfoGraphicsView::getTraceFlag(), isBendpoint(), isTraceType(), ViewGeometry::loc(), m_bezier, m_connector0, m_connector1, m_drag0, m_dragCurve, m_dragEnd, ItemBase::m_spaceBarWasPressed, ItemBase::m_viewGeometry, m_wireDragOrigin, otherConnector(), ItemBase::prepareGeometryChange(), ConnectorItem::sceneAdjustedTerminalPoint(), setConnector1Rect(), setLine(), simpleConnectedMoved(), TheBezierDisplay, BezierDisplay::updateDisplay(), and ModelPart::Wire.
mousePressConnectorEvent()
void Wire::mousePressConnectorEvent (ConnectorItem * connectorItem, QGraphicsSceneMouseEvent * event) protected virtual
Reimplemented from ItemBase.
References altOrMetaModifier(), InfoGraphicsView::getInfoGraphicsView(), initDragEnd(), m_canChainMultiple, InfoGraphicsView::mousePressConnectorEvent(), and ConnectorItem::setOverConnectorItem().
mousePressEvent()
void Wire::mousePressEvent (QGraphicsSceneMouseEvent * event) protected
References ItemBase::mousePressEvent().
mouseReleaseConnectorEvent()
void Wire::mouseReleaseConnectorEvent (ConnectorItem * connectorItem, QGraphicsSceneMouseEvent * event) protected virtual
Reimplemented from ItemBase.
References releaseDrag().
mouseReleaseEvent()
void Wire::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected
References ItemBase::m_spaceBarWasPressed, ItemBase::mouseReleaseEvent(), and releaseDrag().
moveItem()
void Wire::moveItem (ViewGeometry & viewGeometry) virtual
Implements ItemBase.
References ViewGeometry::line(), ViewGeometry::loc(), and setLine().
opacity()
double Wire::opacity ()
References m_opacity.
originalConnectorDimensions()
void Wire::originalConnectorDimensions (double & width, double & height)
References m_originalConnectorRect, and width().
otherConnector()
ConnectorItem * Wire::otherConnector (ConnectorItem * oneConnector)
References m_connector0, and m_connector1.
paint()
void Wire::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0)
References ItemBase::m_hidden, and ItemBase::paint().
paintBody()
void Wire::paintBody (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) virtual
Reimplemented from ItemBase.
References BandedBrush(), color(), coloredByLength(), colorForLength(), Bezier::cp0(), Bezier::cp1(), getPaintLine(), ItemBase::getRatsnest(), hasShadow(), Bezier::isEmpty(), line(), m_banded, m_bezier, ItemBase::m_inactive, m_opacity, m_pen, m_shadowPen, RatDash, and TheDash.
paintHover()
void Wire::paintHover (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) protected virtual
Reimplemented from ItemBase.
References ItemBase::ConnectorHoverColor, ItemBase::HoverColor, ItemBase::HoverOpacity, hoverShape(), ItemBase::m_connectorHoverCount, ItemBase::m_connectorHoverCount2, m_dragCurve, and m_dragEnd.
pen()
QPen Wire::pen () const
Returns the item's pen, or a black solid 0-width pen if no pen has been set.
See also
setPen()
References m_pen.
releaseDrag()
bool Wire::releaseDrag () protected
References ViewGeometry::line(), line(), ViewGeometry::loc(), m_bezier, m_connector0, m_connector1, m_drag0, m_dragCurve, m_dragEnd, ItemBase::m_viewGeometry, ConnectorItem::releaseDrag(), TheBezierDisplay, UndoBezier, wireChangedCurveSignal(), and wireChangedSignal().
rotation45Allowed()
bool Wire::rotation45Allowed () virtual
Reimplemented from ItemBase.
rotationAllowed()
bool Wire::rotationAllowed () virtual
Reimplemented from ItemBase.
saveGeometry()
void Wire::saveGeometry () virtual
Implements ItemBase.
References line(), ItemBase::m_viewGeometry, ViewGeometry::setLine(), ViewGeometry::setLoc(), ViewGeometry::setSelected(), and ViewGeometry::setZ().
saveInstanceLocation()
void Wire::saveInstanceLocation (QXmlStreamWriter & streamWriter) virtual
Implements ItemBase.
References ViewGeometry::flagsAsInt(), ViewGeometry::line(), line(), ViewGeometry::loc(), and ItemBase::m_viewGeometry.
sceneCurve()
QPolygonF Wire::sceneCurve (QPointF offset)
References Bezier::cp0(), Bezier::cp1(), Bezier::isEmpty(), m_bezier, and m_line.
setAutoroutable()
void Wire::setAutoroutable (bool ar)
References ItemBase::m_viewGeometry, and ViewGeometry::setAutoroutable().
setBanded()
void Wire::setBanded (bool banded)
References banded(), collectChained(), and m_banded.
setBandedProp
void Wire::setBandedProp (bool banded) protected slot
References banded(), InfoGraphicsView::getInfoGraphicsView(), m_banded, InfoGraphicsView::setProp(), and ItemBase::TranslatedPropertyNames.
setCanChainMultiple()
void Wire::setCanChainMultiple (bool can)
References m_canChainMultiple.
setColor()
void Wire::setColor (const QColor & color, double opacity) virtual
References color(), m_colorName, m_opacity, and m_pen.
setColorFromElement()
void Wire::setColorFromElement (QDomElement & element) protected virtual
Reimplemented in TraceWire.
References colorString(), and setColorString().
setColorString()
void Wire::setColorString (QString colorName, double opacity, bool restore)
References colorString(), m_colorName, ItemBase::m_viewID, setColor(), setShadowColor(), RatsnestColors::shadowColor(), and RatsnestColors::wireColor().
setConnector0Rect()
void Wire::setConnector0Rect ()
References m_connector0.
setConnector1Rect()
void Wire::setConnector1Rect ()
References line(), and m_connector1.
setConnectorDimensions()
void Wire::setConnectorDimensions (double width, double height)
References connector0(), connector1(), setConnectorDimensionsAux(), and width().
setConnectorDimensionsAux()
void Wire::setConnectorDimensionsAux (ConnectorItem * connectorItem, double width, double height) protected
References ConnectorItem::setTerminalPoint(), and width().
setDisplayBendpointCursor()
void Wire::setDisplayBendpointCursor (bool dbc)
References m_displayBendpointCursor.
setExtras()
void Wire::setExtras (QDomElement & element, InfoGraphicsView * infoGraphicsView)
References connector0(), connector1(), Bezier::copy(), Bezier::fromElement(), InfoGraphicsView::getWireStrokeWidth(), Bezier::isEmpty(), m_banded, m_bezier, GraphicsUtils::mils2pixels(), ItemBase::prepareGeometryChange(), ConnectorItem::sceneAdjustedTerminalPoint(), Bezier::set_endpoints(), setColorFromElement(), setWireWidth(), and GraphicsUtils::SVGDPI.
setIgnoreSelectionChange()
void Wire::setIgnoreSelectionChange (bool ignore) protected
References m_ignoreSelectionChange.
setLine() [1/2]
void Wire::setLine (const QLineF & line) virtual
Sets the item's line to be the given line.
See also
line()
References line(), m_line, and ItemBase::prepareGeometryChange().
setLine() [2/2]
void Wire::setLine (double x1, double y1, double x2, double y2) inline
References setLine().
setLineAnd()
void Wire::setLineAnd (QLineF line, QPointF pos, bool useLine)
References setConnector1Rect(), and setLine().
setNormal()
void Wire::setNormal (bool normal)
References ItemBase::m_viewGeometry, and ViewGeometry::setNormal().
setOpacity()
void Wire::setOpacity (double opacity)
References m_opacity, and opacity().
setPcbPenBrush()
void Wire::setPcbPenBrush (QBrush & brush)
setPen()
void Wire::setPen (const QPen & pen)
Sets the item's pen to pen. If no pen is set, the line will be painted using a black solid 0-width pen.
See also
pen()
References m_pen, pen(), and ItemBase::prepareGeometryChange().
setPenWidth()
void Wire::setPenWidth (double width, InfoGraphicsView * infoGraphicsView, double hoverStrokeWidth)
References InfoGraphicsView::getBendpointWidths(), hoverStrokeWidth(), m_bendpoint2Pen, m_bendpoint2Width, m_bendpointPen, m_bendpointWidth, m_hoverStrokeWidth, m_negativeOffsetRect, m_pen, and m_shadowPen.
setProp()
void Wire::setProp (const QString & prop, const QString & value) virtual
Reimplemented from ItemBase.
References ItemBase::prop(), setBanded(), and ItemBase::setProp().
setRatsnest()
void Wire::setRatsnest (bool ratsnest)
References ItemBase::m_viewGeometry, and ViewGeometry::setRatsnest().
setRouted()
void Wire::setRouted (bool routed)
References ItemBase::m_viewGeometry, and ViewGeometry::setRouted().
setShadowColor()
void Wire::setShadowColor (QColor & color, bool restore) protected
References color(), m_bendpoint2Pen, m_bendpointPen, m_connector0, m_connector1, m_shadowBrush, and m_shadowPen.
setUp()
FSvgRenderer * Wire::setUp (ViewLayer::ViewLayerID viewLayerID, const LayerHash & viewLayers, class InfoGraphicsView * infoGraphicsView) virtual
References initEnds(), ItemBase::m_modelPart, ItemBase::m_viewGeometry, ItemBase::m_viewID, setUpConnectors(), ItemBase::setViewLayerID(), ItemBase::viewLayerID(), and ItemBase::z().
setUpConnectors()
FSvgRenderer * Wire::setUpConnectors (class ModelPart * modelPart, ViewLayer::ViewID viewID) protected virtual
Reimplemented in VirtualWire.
References ItemBase::clearConnectorItemCache(), ModelPart::connectors(), Connector::fullPinInfo(), ItemBase::initLayerAttributes(), m_originalConnectorRect, ItemBase::m_viewLayerID, ItemBase::m_viewLayerPlacement, ItemBase::modelPart(), ItemBase::newConnectorItem(), SvgIdLayer::point(), SvgIdLayer::rect(), NonConnectorItem::setCircular(), ConnectorItem::setTerminalPoint(), FSvgRenderer::setUpConnector(), ItemBase::setUpImage(), ItemBase::viewID(), and ItemBase::viewLayerPlacement().
setWireFlags()
void Wire::setWireFlags (ViewGeometry::WireFlags wireFlags)
References ItemBase::m_viewGeometry, ViewGeometry::setWireFlags(), and ItemBase::wireFlags().
setWireWidth()
void Wire::setWireWidth (double width, InfoGraphicsView * infoGraphicsView, double hoverStrokeWidth)
References hoverStrokeWidth(), m_connector0, m_connector1, m_pen, ItemBase::prepareGeometryChange(), setPenWidth(), and width().
shadowHexString()
QString Wire::shadowHexString ()
References m_shadowPen.
shadowWidth()
double Wire::shadowWidth ()
References m_shadowPen.
shape()
QPainterPath Wire::shape () const
References m_pen, and shapeAux().
shapeAux()
QPainterPath Wire::shapeAux (double width) const protected
References Bezier::cp0(), Bezier::cp1(), Bezier::isEmpty(), m_bezier, m_line, m_pen, GraphicsUtils::shapeFromPath(), and width().
simpleConnectedMoved() [1/2]
void Wire::simpleConnectedMoved (ConnectorItem * to)
References ConnectorItem::firstConnectedToIsh().
simpleConnectedMoved() [2/2]
void Wire::simpleConnectedMoved (ConnectorItem * from, ConnectorItem * to)
References calcNewLine(), setConnector1Rect(), and setLine().
stickyEnabled()
bool Wire::stickyEnabled () virtual
Reimplemented from ItemBase.
References collectChained(), and ConnectorItem::connectionsCount().
undoCurve()
const Bezier * Wire::undoCurve ()
References UndoBezier.
updateCursor()
void Wire::updateCursor (Qt::KeyboardModifiers modifiers) protected
References CursorMaster::addCursor(), altOrMetaModifier(), NonConnectorItem::attachedToItemType(), ItemBase::cachedConnectorItems(), ConnectorItem::connectedToItems(), ConnectorItem::connectionsCount(), InfoGraphicsView::curvyWiresIndicated(), InfoGraphicsView::getInfoGraphicsView(), CursorMaster::instance(), m_connectorHover, m_displayBendpointCursor, CursorMaster::MakeCurveCursor, CursorMaster::MoveCursor, CursorMaster::NewBendpointCursor, CursorMaster::RubberbandCursor, and ModelPart::Wire.
useViewIDForPixmap()
ViewLayer::ViewID Wire::useViewIDForPixmap (ViewLayer::ViewID vid, bool swappingEnabled) protected virtual
Reimplemented from ItemBase.
References ViewLayer::BreadboardView, ViewLayer::IconView, and ViewLayer::UnknownView.
width()
double Wire::width ()
References m_pen.
wireChangedCurveSignal
void Wire::wireChangedCurveSignal (Wire * me, const Bezier * oldB, const Bezier * newB, bool triggerFirstTime) signal
wireChangedSignal
void Wire::wireChangedSignal (Wire * me, const QLineF & oldLine, const QLineF & newLine, QPointF oldPos, QPointF newPos, ConnectorItem * from, ConnectorItem * to) signal
wireJoinSignal
void Wire::wireJoinSignal (Wire * me, ConnectorItem * clickedConnectorItem) signal
wireSplitSignal
void Wire::wireSplitSignal (Wire * me, QPointF newPos, QPointF oldPos, const QLineF & oldLine) signal
writeGeometry()
void Wire::writeGeometry (QXmlStreamWriter & streamWriter) virtual
Reimplemented from ItemBase.
References m_banded, m_bezier, m_opacity, m_pen, mils(), Bezier::write(), and ItemBase::writeGeometry().
Member Data Documentation
colorNames
QStringList Wire::colorNames static
colorTrans
QHash< QString, QString > Wire::colorTrans static
HALF_STANDARD_TRACE_WIDTH
double Wire::HALF_STANDARD_TRACE_WIDTH = 0.0 static
lengthColorTrans
QList< QColor > Wire::lengthColorTrans static
m_banded
bool Wire::m_banded protected
m_bendpoint2Pen
QPen Wire::m_bendpoint2Pen protected
m_bendpoint2Width
double Wire::m_bendpoint2Width protected
m_bendpointPen
QPen Wire::m_bendpointPen protected
m_bendpointWidth
double Wire::m_bendpointWidth protected
m_bezier
class Bezier* Wire::m_bezier protected
m_canChainMultiple
bool Wire::m_canChainMultiple protected
m_canHaveCurve
bool Wire::m_canHaveCurve protected
m_colorByLength
bool Wire::m_colorByLength protected
m_colorName
QString Wire::m_colorName protected
m_connector0
QPointer<class ConnectorItem> Wire::m_connector0 protected
m_connector1
QPointer<class ConnectorItem> Wire::m_connector1 protected
m_connectorHover
QPointer<class ConnectorItem> Wire::m_connectorHover protected
m_displayBendpointCursor
bool Wire::m_displayBendpointCursor protected
m_drag0
bool Wire::m_drag0 protected
m_dragCurve
bool Wire::m_dragCurve protected
m_dragEnd
bool Wire::m_dragEnd protected
m_hoverStrokeWidth
double Wire::m_hoverStrokeWidth protected
m_ignoreSelectionChange
bool Wire::m_ignoreSelectionChange protected
m_line
QLineF Wire::m_line protected
m_markedDeleted
bool Wire::m_markedDeleted protected
m_negativeOffsetRect
bool Wire::m_negativeOffsetRect protected
m_opacity
double Wire::m_opacity protected
m_originalConnectorRect
QRectF Wire::m_originalConnectorRect protected
m_pen
QPen Wire::m_pen protected
m_shadowBrush
QBrush Wire::m_shadowBrush protected
m_shadowPen
QPen Wire::m_shadowPen protected
m_wireDragOrigin
QPointF Wire::m_wireDragOrigin protected
STANDARD_TRACE_WIDTH
double Wire::STANDARD_TRACE_WIDTH = 0.0 static
TheDash
QVector< qreal > Wire::TheDash static
THIN_TRACE_WIDTH
double Wire::THIN_TRACE_WIDTH = 0.0 static
widths
QList< int > Wire::widths static
widthTrans
QHash< int, QString > Wire::widthTrans static
The documentation for this class was generated from the following files:
items/wire.h
items/wire.cpp