Fritzing: GraphicsFlowLayout Class Reference
GraphicsFlowLayout Class Reference
#include <graphicsflowlayout.h>
Public Member Functions
GraphicsFlowLayout (QGraphicsLayoutItem *parent, int spacing)
void clear ()
int heightForWidth (int width)
int indexOf (const QGraphicsLayoutItem *item)
void setGeometry (const QRectF &rect)
Protected Member Functions
int doLayout (const QRectF &rect)
void widgetEvent (QEvent *e)
Protected Attributes
double m_lastWidth
Constructor & Destructor Documentation
GraphicsFlowLayout()
GraphicsFlowLayout::GraphicsFlowLayout (QGraphicsLayoutItem * parent, int spacing)
Member Function Documentation
clear()
void GraphicsFlowLayout::clear ()
doLayout()
int GraphicsFlowLayout::doLayout (const QRectF & rect) protected
References m_lastWidth, qMax(), SpaceAfter, and SpaceBefore.
heightForWidth()
int GraphicsFlowLayout::heightForWidth (int width)
References doLayout().
indexOf()
int GraphicsFlowLayout::indexOf (const QGraphicsLayoutItem * item)
setGeometry()
void GraphicsFlowLayout::setGeometry (const QRectF & rect)
References doLayout().
widgetEvent()
void GraphicsFlowLayout::widgetEvent (QEvent * e) protected
Member Data Documentation
m_lastWidth
double GraphicsFlowLayout::m_lastWidth protected
The documentation for this class was generated from the following files:
partsbinpalette/graphicsflowlayout.h
partsbinpalette/graphicsflowlayout.cpp