Fritzing: connectors/connectoritem.cpp File Reference
connectoritem.cpp File Reference
#include "connectoritem.h"
#include <QBrush>
#include <QPen>
#include <QColor>
#include <limits>
#include <QSet>
#include <QToolTip>
#include <QBitmap>
#include <QApplication>
#include <qmath.h>
#include "../sketch/infographicsview.h"
#include "../debugdialog.h"
#include "bus.h"
#include "../items/wire.h"
#include "../items/virtualwire.h"
#include "../model/modelpart.h"
#include "../utils/graphicsutils.h"
#include "../utils/graphutils.h"
#include "../utils/textutils.h"
#include "../utils/ratsnestcolors.h"
#include "../utils/bezier.h"
#include "../utils/bezierdisplay.h"
#include "../utils/cursormaster.h"
#include "ercdata.h"
Functions
QColor addColor (QColor &color, int offset)
bool isGrey (QColor color)
bool wireLessThan (ConnectorItem *c1, ConnectorItem *c2)
Variables
static double MAX_DOUBLE = std::numeric_limits<double>::max()
static const double StandardLegConnectorDetectLength = 9
static const double StandardLegConnectorDrawEnabledLength = 5
static BezierDisplay * TheBezierDisplay = nullptr
static Bezier UndoBezier
Function Documentation
addColor()
QColor addColor (QColor & color, int offset)
References qMax(), and qMin().
isGrey()
bool isGrey (QColor color)
wireLessThan()
bool wireLessThan (ConnectorItem * c1, ConnectorItem * c2)
References ConnectorItem::connectorType(), Connector::Female, Connector::Male, and Connector::Pad.
Variable Documentation
MAX_DOUBLE
double MAX_DOUBLE = std::numeric_limits<double>::max() static
StandardLegConnectorDetectLength
const double StandardLegConnectorDetectLength = 9 static
StandardLegConnectorDrawEnabledLength
const double StandardLegConnectorDrawEnabledLength = 5 static
TheBezierDisplay
BezierDisplay* TheBezierDisplay = nullptr static
UndoBezier
Bezier UndoBezier static