Fritzing: TextUtils Class Reference
TextUtils Class Reference
#include <textutils.h>
Static Public Member Functions
static bool addCopper1 (const QString &filename, QDomDocument &doc, const QString &srcAtt, const QString &destAtt)
static bool cleanSodipodi (QString &bytes)
static void collectLeaves (QDomElement &element, int &index, QVector< QDomElement > &leaves)
static void collectLeaves (QDomElement &element, QList< QDomElement > &leaves)
static QString convertExtendedChars (const QString &str)
static double convertFromPowerPrefix (const QString &val, const QString &symbol)
static double convertFromPowerPrefixU (QString &val, const QString &symbol)
static double convertToInches (const QString &string, bool *ok, bool isIllustrator)
static double convertToInches (const QString &string)
static QString convertToPowerPrefix (double)
static QMatrix elementToMatrix (QDomElement &element)
static QString elementToString (const QDomElement &)
static bool elevateTransform (QDomElement &)
static bool ensureViewBox (QDomDocument doc, double dpi, QRectF &rect, bool toInches, double &w, double &h, bool getwh)
static QString escapeAnd (const QString &)
static QString expandAndFill (const QString &svg, const QString &color, double expandBy)
static void expandAndFillAux (QDomElement &, const QString &color, double expandBy)
static QString findAnchor (const QDomElement &text)
static void findElementsWithAttribute (QDomElement &element, const QString &att, QList< QDomElement > &elements)
static QDomElement findElementWithAttribute (QDomElement element, const QString &attributeName, const QString &attributeValue)
static bool findText (const QDomNode &node, QString &text)
static bool fixFonts (QString &svg, const QString &destFont, bool &reallyFixed)
static bool fixInternalUnits (QString &svg)
static bool fixMuch (QString &svg, bool fixStrokeWidth)
static bool fixPixelDimensionsIn (QString &fileContent)
static void fixStyleAttribute (QDomElement &element)
static int getPinsAndSpacing (const QString &expectedFileName, QString &spacingString)
static QString getRandText ()
static QSet< QString > getRegexpCaptures (const QString &pattern, const QString &textToSearchIn)
static double getStrokeWidth (QDomElement &, double defaultValue)
static bool getSvgSizes (QDomDocument &doc, double &sWidth, double &sHeight, double &vbWidth, double &vbHeight)
static QList< double > getTransformFloats (QDomElement &element)
static QList< double > getTransformFloats (const QString &transform)
static double getViewBoxCoord (const QString &svg, int coord)
static void gornTree (QDomDocument &)
static void gWrap (QDomDocument &domDocument, const QHash< QString, QString > &attributes)
static QString incCopyPinFunction (int pin, const QString &argString, void *userData)
static QString incMultiplyPinFunction (int pin, double increment, double value)
static QString incrementTemplate (const QString &filename, int pins, double unitIncrement, MultiplyPinFunction, CopyPinFunction, void *userData)
static QString incrementTemplateString (const QString &templateString, int pins, double increment, MultiplyPinFunction, CopyPinFunction, void *userData)
static bool isIllustratorDoc (const QDomDocument &doc)
static bool isIllustratorFile (const QString &fileContent)
static bool isIllustratorFile (const QByteArray &fileContent)
static QString killXMLNS (QString svgContent)
static QString makeCubicBezierSVG (const QPolygonF &controlPoints, double width, QString colorString, double dpi, double printerScale, bool blackOnly, bool dashed, const QVector< qreal > &)
static QString makeLineSVG (QPointF p1, QPointF p2, double width, QString colorString, double dpi, double printerScale, bool blackOnly, bool dashed, const QVector< qreal > &)
static QString makePolySVG (const QPolygonF &poly, QPointF offset, double width, QString colorString, double dpi, double printerScale, bool blackOnly)
static QString makeRectSVG (QRectF r, QPointF offset, double dpi, double printerscale)
static QString makeSVGHeader (double printerscale, double dpi, double width, double height)
static QString mergeSvg (const QString &svg1, const QString &svg2, const QString &id, bool flip)
static bool mergeSvg (QDomDocument &doc1, const QString &svg, const QString &id)
static QString mergeSvgFinish (QDomDocument &doc)
static QString negIncCopyPinFunction (int pin, const QString &argString, void *userData)
static QString noCopyPinFunction (int pin, const QString &argString, void *userData)
static QString parseFileForModuleID (const QString &fzpPath)
static QString parseForModuleID (const QString &fzpXmlString)
static QSizeF parseForWidthAndHeight (QXmlStreamReader &, QRectF &viewBox, bool getViewBox)
static QSizeF parseForWidthAndHeight (QXmlStreamReader &)
static QSizeF parseForWidthAndHeight (const QString &svg, QRectF &viewBox, bool getViewBox)
static QSizeF parseForWidthAndHeight (const QString &svg)
static QString pointToSvgString (QPointF p, QPointF offset, double dpi, double printerScale)
static QPolygonF polygonFromElement (QDomElement &element)
static QString removeSVGHeader (QString &string)
static QString removeXMLEntities (QString svgContent)
static void replaceChildText (QDomNode &node, const QString &text)
static void replaceElementChildText (QDomElement &root, const QString &elementName, const QString &text)
static QString replaceTextElement (const QString &svg, const QString &id, const QString &newValue)
static QByteArray replaceTextElement (const QByteArray &svg, const QString &id, const QString &newValue)
static QString replaceTextElements (const QString &svg, const QHash< QString, QString > &)
static void resplit (QStringList &names, const QString &split)
static void setSVGTransform (QDomElement &, QMatrix &)
static void slamStrokeAndFill (QDomElement &, const QString &stroke, const QString &strokeWidth, const QString &fill)
static QString slamStrokeAndFill (const QString &svg, const QString &stroke, const QString &strokeWidth, const QString &fill)
static bool squashElement (QDomDocument &, const QString &elementName, const QString &attName, const QRegExp &matchContent)
static QString standardCopyPinFunction (int pin, const QString &argString, void *userData)
static QString standardMultiplyPinFunction (int pin, double increment, double value)
static QString stripNonValidXMLCharacters (const QString &str)
static QString svgMatrix (const QMatrix &)
static QString svgMatrix (const QTransform &)
static QString svgNSOnly (QString svgContent)
static QString svgTransform (const QString &svg, QTransform &transform, bool translate, const QString extra)
static QMatrix transformStringToMatrix (const QString &transform)
static bool writeUtf8 (const QString &fileName, const QString &text)
Static Public Attributes
static const QString AdobeIllustratorIdentifier = "Generator: Adobe Illustrator"
static const QString CreatedWithFritzingString
static const QString CreatedWithFritzingXmlComment
static const QRegExp FindWhitespace
static const QRegExp floatingPointMatcher
static const QString MicroSymbol = QString::fromUtf16(&MicroSymbolCode, 1)
static const ushort MicroSymbolCode = 181
static const QString PowerPrefixesString = QString("pnmkMGTu\\x%1").arg(MicroSymbolCode, 4, 16, QChar('0'))
static const QString RegexFloatDetector = "[-+]?[0-9]*\\.?[0-9]+([eE][-+]?[0-9]+)?"
static const QString SMDFlipSuffix
Static Protected Member Functions
static void chopNotDigits (QString &)
static void collectTransforms (QDomElement &root, QList< QDomElement > &transforms)
static QDomElement copyText (QDomDocument &svgDom, QDomElement &parent, QDomElement &text, const QString &defaultX, const QString &defaultY, bool copyAttributes)
static bool fixStrokeWidth (QDomDocument &svgDoc)
static void fixStyleAttribute (QDomElement &element, QString &style, const QString &attributeName)
static bool fixViewBox (QDomElement &root)
static void gornTreeAux (QDomElement &)
static void initPowerPrefixes ()
static bool noPatternAux (QDomDocument &svgDom, const QString &tag)
static bool noUseAux (QDomDocument &svgDom)
static bool pxToInches (QDomElement &elem, const QString &attrName, bool isIllustrator)
static void squashNotElement (QDomElement &element, const QString &elementName, const QString &attName, const QRegExp &matchContent, bool &result)
static bool tspanRemoveAux (QDomDocument &svgDom)
Static Private Member Functions
static bool removeFontFamilySingleQuotes (QString &fileContent)
Member Function Documentation
addCopper1()
bool TextUtils::addCopper1 (const QString & filename, QDomDocument & doc, const QString & srcAtt, const QString & destAtt) static
References findElementsWithAttribute().
chopNotDigits()
void TextUtils::chopNotDigits (QString & string) static protected
cleanSodipodi()
bool TextUtils::cleanSodipodi (QString & bytes) static
References SodipodiAttributeDetector(), and SodipodiElementDetector().
collectLeaves() [1/2]
void TextUtils::collectLeaves (QDomElement & element, int & index, QVector< QDomElement > & leaves) static
collectLeaves() [2/2]
void TextUtils::collectLeaves (QDomElement & element, QList< QDomElement > & leaves) static
References collectLeaves().
collectTransforms()
void TextUtils::collectTransforms (QDomElement & root, QList< QDomElement > & transforms) static protected
convertExtendedChars()
QString TextUtils::convertExtendedChars (const QString & str) static
convertFromPowerPrefix()
double TextUtils::convertFromPowerPrefix (const QString & val, const QString & symbol) static
References initPowerPrefixes(), PowerPrefixes, and PowerPrefixValues.
convertFromPowerPrefixU()
double TextUtils::convertFromPowerPrefixU (QString & val, const QString & symbol) static
References convertFromPowerPrefix(), and MicroSymbol.
convertToInches() [1/2]
double TextUtils::convertToInches (const QString & string, bool * ok, bool isIllustrator) static
References chopNotDigits().
convertToInches() [2/2]
double TextUtils::convertToInches (const QString & string) static
References convertToInches().
convertToPowerPrefix()
QString TextUtils::convertToPowerPrefix (double q) static
References initPowerPrefixes(), PowerPrefixes, and PowerPrefixValues.
copyText()
QDomElement TextUtils::copyText (QDomDocument & svgDom, QDomElement & parent, QDomElement & text, const QString & defaultX, const QString & defaultY, bool copyAttributes) static protected
References ___emptyElement___.
elementToMatrix()
QMatrix TextUtils::elementToMatrix (QDomElement & element) static
References transformStringToMatrix().
elementToString()
QString TextUtils::elementToString (const QDomElement & element) static
elevateTransform()
bool TextUtils::elevateTransform (QDomElement & root) static
References collectTransforms().
ensureViewBox()
bool TextUtils::ensureViewBox (QDomDocument doc, double dpi, QRectF & rect, bool toInches, double & w, double & h, bool getwh) static
References convertToInches(), and isIllustratorDoc().
escapeAnd()
QString TextUtils::escapeAnd (const QString & string) static
expandAndFill()
QString TextUtils::expandAndFill (const QString & svg, const QString & color, double expandBy) static
References expandAndFillAux().
expandAndFillAux()
void TextUtils::expandAndFillAux (QDomElement & element, const QString & color, double expandBy) static
findAnchor()
QString TextUtils::findAnchor (const QDomElement & text) static
findElementsWithAttribute()
void TextUtils::findElementsWithAttribute (QDomElement & element, const QString & att, QList< QDomElement > & elements) static
findElementWithAttribute()
QDomElement TextUtils::findElementWithAttribute (QDomElement element, const QString & attributeName, const QString & attributeValue) static
References ___emptyElement___.
findText()
bool TextUtils::findText (const QDomNode & node, QString & text) static
fixFonts()
bool TextUtils::fixFonts (QString & svg, const QString & destFont, bool & reallyFixed) static
References fixUnavailableFontFamilies(), and removeFontFamilySingleQuotes().
fixInternalUnits()
bool TextUtils::fixInternalUnits (QString & svg) static
References convertToInches(), and parseForWidthAndHeight().
fixMuch()
bool TextUtils::fixMuch (QString & svg, bool fixStrokeWidth) static
References cleanSodipodi(), elevateTransform(), fixInternalUnits(), fixStrokeWidth(), fixViewBox(), noPatternAux(), noUseAux(), removeXMLEntities(), and tspanRemoveAux().
fixPixelDimensionsIn()
bool TextUtils::fixPixelDimensionsIn (QString & fileContent) static
References isIllustratorFile(), pxToInches(), and removeXMLEntities().
fixStrokeWidth()
bool TextUtils::fixStrokeWidth (QDomDocument & svgDoc) static protected
References fixStyleAttribute(), and getStrokeWidth().
fixStyleAttribute() [1/2]
void TextUtils::fixStyleAttribute (QDomElement & element) static
fixStyleAttribute() [2/2]
void TextUtils::fixStyleAttribute (QDomElement & element, QString & style, const QString & attributeName) static protected
fixViewBox()
bool TextUtils::fixViewBox (QDomElement & root) static protected
getPinsAndSpacing()
int TextUtils::getPinsAndSpacing (const QString & expectedFileName, QString & spacingString) static
getRandText()
QString TextUtils::getRandText () static
getRegexpCaptures()
QSet< QString > TextUtils::getRegexpCaptures (const QString & pattern, const QString & textToSearchIn) static
getStrokeWidth()
double TextUtils::getStrokeWidth (QDomElement & element, double defaultValue) static
getSvgSizes()
bool TextUtils::getSvgSizes (QDomDocument & doc, double & sWidth, double & sHeight, double & vbWidth, double & vbHeight) static
References convertToInches(), isIllustratorDoc(), and isIllustratorFile().
getTransformFloats() [1/2]
QList< double > TextUtils::getTransformFloats (QDomElement & element) static
getTransformFloats() [2/2]
QList< double > TextUtils::getTransformFloats (const QString & transform) static
References floatingPointMatcher.
getViewBoxCoord()
double TextUtils::getViewBoxCoord (const QString & svg, int coord) static
gornTree()
void TextUtils::gornTree (QDomDocument & doc) static
References gornTreeAux().
gornTreeAux()
void TextUtils::gornTreeAux (QDomElement & root) static protected
gWrap()
void TextUtils::gWrap (QDomDocument & domDocument, const QHash< QString, QString > & attributes) static
incCopyPinFunction()
QString TextUtils::incCopyPinFunction (int pin, const QString & argString, void * userData) static
incMultiplyPinFunction()
QString TextUtils::incMultiplyPinFunction (int pin, double increment, double value) static
incrementTemplate()
QString TextUtils::incrementTemplate (const QString & filename, int pins, double unitIncrement, MultiplyPinFunction multiFun, CopyPinFunction copyFun, void * userData) static
References incrementTemplateString().
incrementTemplateString()
QString TextUtils::incrementTemplateString (const QString & templateString, int pins, double increment, MultiplyPinFunction multiFun, CopyPinFunction copyFun, void * userData) static
References MatchThing::len, MatchThing::pos, and MatchThing::val.
initPowerPrefixes()
void TextUtils::initPowerPrefixes () static protected
References MicroSymbol, PowerPrefixes, and PowerPrefixValues.
isIllustratorDoc()
bool TextUtils::isIllustratorDoc (const QDomDocument & doc) static
References isIllustratorFile().
isIllustratorFile() [1/2]
bool TextUtils::isIllustratorFile (const QString & fileContent) static
References AdobeIllustratorIdentifier.
isIllustratorFile() [2/2]
bool TextUtils::isIllustratorFile (const QByteArray & fileContent) static
References AdobeIllustratorIdentifier.
killXMLNS()
QString TextUtils::killXMLNS (QString svgContent) static
References Xmlns().
makeCubicBezierSVG()
QString TextUtils::makeCubicBezierSVG (const QPolygonF & controlPoints, double width, QString colorString, double dpi, double printerScale, bool blackOnly, bool dashed, const QVector< qreal > & pattern) static
References makeDashString().
makeLineSVG()
QString TextUtils::makeLineSVG (QPointF p1, QPointF p2, double width, QString colorString, double dpi, double printerScale, bool blackOnly, bool dashed, const QVector< qreal > & pattern) static
References makeDashString().
makePolySVG()
QString TextUtils::makePolySVG (const QPolygonF & poly, QPointF offset, double width, QString colorString, double dpi, double printerScale, bool blackOnly) static
makeRectSVG()
QString TextUtils::makeRectSVG (QRectF r, QPointF offset, double dpi, double printerscale) static
makeSVGHeader()
QString TextUtils::makeSVGHeader (double printerscale, double dpi, double width, double height) static
References CreatedWithFritzingXmlComment.
mergeSvg() [1/2]
QString TextUtils::mergeSvg (const QString & svg1, const QString & svg2, const QString & id, bool flip) static
References ___emptyString___, gWrap(), mergeSvgFinish(), and svgMatrix().
mergeSvg() [2/2]
bool TextUtils::mergeSvg (QDomDocument & doc1, const QString & svg, const QString & id) static
References findElementWithAttribute().
mergeSvgFinish()
QString TextUtils::mergeSvgFinish (QDomDocument & doc) static
References removeXMLEntities().
negIncCopyPinFunction()
QString TextUtils::negIncCopyPinFunction (int pin, const QString & argString, void * userData) static
noCopyPinFunction()
QString TextUtils::noCopyPinFunction (int pin, const QString & argString, void * userData) static
noPatternAux()
bool TextUtils::noPatternAux (QDomDocument & svgDom, const QString & tag) static protected
noUseAux()
bool TextUtils::noUseAux (QDomDocument & svgDom) static protected
References findElementWithAttribute().
parseFileForModuleID()
QString TextUtils::parseFileForModuleID (const QString & fzpPath) static
parseForModuleID()
QString TextUtils::parseForModuleID (const QString & fzpXmlString) static
parseForWidthAndHeight() [1/4]
QSizeF TextUtils::parseForWidthAndHeight (QXmlStreamReader & svg, QRectF & viewBox, bool getViewBox) static
References chopNotDigits(), convertToInches(), and isIllustratorFile().
parseForWidthAndHeight() [2/4]
QSizeF TextUtils::parseForWidthAndHeight (QXmlStreamReader & svg) static
References parseForWidthAndHeight().
parseForWidthAndHeight() [3/4]
QSizeF TextUtils::parseForWidthAndHeight (const QString & svg, QRectF & viewBox, bool getViewBox) static
References parseForWidthAndHeight().
parseForWidthAndHeight() [4/4]
QSizeF TextUtils::parseForWidthAndHeight (const QString & svg) static
References parseForWidthAndHeight().
pointToSvgString()
QString TextUtils::pointToSvgString (QPointF p, QPointF offset, double dpi, double printerScale) static
polygonFromElement()
QPolygonF TextUtils::polygonFromElement (QDomElement & element) static
pxToInches()
bool TextUtils::pxToInches (QDomElement & elem, const QString & attrName, bool isIllustrator) static protected
References convertToInches().
removeFontFamilySingleQuotes()
bool TextUtils::removeFontFamilySingleQuotes (QString & fileContent) static private
References fontFamilyQuotesPattern, and getRegexpCaptures().
removeSVGHeader()
QString TextUtils::removeSVGHeader (QString & string) static
removeXMLEntities()
QString TextUtils::removeXMLEntities (QString svgContent) static
References HexExpr(), and svgNSOnly().
replaceChildText()
void TextUtils::replaceChildText (QDomNode & node, const QString & text) static
replaceElementChildText()
void TextUtils::replaceElementChildText (QDomElement & root, const QString & elementName, const QString & text) static
References replaceChildText().
replaceTextElement() [1/2]
QString TextUtils::replaceTextElement (const QString & svg, const QString & id, const QString & newValue) static
References replaceChildText().
replaceTextElement() [2/2]
QByteArray TextUtils::replaceTextElement (const QByteArray & svg, const QString & id, const QString & newValue) static
References replaceChildText().
replaceTextElements()
QString TextUtils::replaceTextElements (const QString & svg, const QHash< QString, QString > & hash) static
References replaceChildText().
resplit()
void TextUtils::resplit (QStringList & names, const QString & split) static
setSVGTransform()
void TextUtils::setSVGTransform (QDomElement & element, QMatrix & matrix) static
References svgMatrix().
slamStrokeAndFill() [1/2]
void TextUtils::slamStrokeAndFill (QDomElement & element, const QString & stroke, const QString & strokeWidth, const QString & fill) static
slamStrokeAndFill() [2/2]
QString TextUtils::slamStrokeAndFill (const QString & svg, const QString & stroke, const QString & strokeWidth, const QString & fill) static
References slamStrokeAndFill().
squashElement()
bool TextUtils::squashElement (QDomDocument & doc, const QString & elementName, const QString & attName, const QRegExp & matchContent) static
squashNotElement()
static void TextUtils::squashNotElement (QDomElement & element, const QString & elementName, const QString & attName, const QRegExp & matchContent, bool & result) static protected
standardCopyPinFunction()
QString TextUtils::standardCopyPinFunction (int pin, const QString & argString, void * userData) static
standardMultiplyPinFunction()
QString TextUtils::standardMultiplyPinFunction (int pin, double increment, double value) static
stripNonValidXMLCharacters()
QString TextUtils::stripNonValidXMLCharacters (const QString & str) static
svgMatrix() [1/2]
QString TextUtils::svgMatrix (const QMatrix & matrix) static
svgMatrix() [2/2]
QString TextUtils::svgMatrix (const QTransform & matrix) static
svgNSOnly()
QString TextUtils::svgNSOnly (QString svgContent) static
References Xmlns().
svgTransform()
QString TextUtils::svgTransform (const QString & svg, QTransform & transform, bool translate, const QString extra) static
transformStringToMatrix()
QMatrix TextUtils::transformStringToMatrix (const QString & transform) static
References getTransformFloats().
tspanRemoveAux()
bool TextUtils::tspanRemoveAux (QDomDocument & svgDom) static protected
References copyText().
writeUtf8()
bool TextUtils::writeUtf8 (const QString & fileName, const QString & text) static
Member Data Documentation
AdobeIllustratorIdentifier
const QString TextUtils::AdobeIllustratorIdentifier = "Generator: Adobe Illustrator" static
CreatedWithFritzingString
const QString TextUtils::CreatedWithFritzingString static
CreatedWithFritzingXmlComment
const QString TextUtils::CreatedWithFritzingXmlComment static
FindWhitespace
const QRegExp TextUtils::FindWhitespace static
floatingPointMatcher
const QRegExp TextUtils::floatingPointMatcher static
MicroSymbol
const QString TextUtils::MicroSymbol = QString::fromUtf16(&MicroSymbolCode, 1) static
MicroSymbolCode
const ushort TextUtils::MicroSymbolCode = 181 static
PowerPrefixesString
const QString TextUtils::PowerPrefixesString = QString("pnmkMGTu\\x%1").arg(MicroSymbolCode, 4, 16, QChar('0')) static
RegexFloatDetector
const QString TextUtils::RegexFloatDetector = "[-+]?[0-9]*\\.?[0-9]+([eE][-+]?[0-9]+)?" static
SMDFlipSuffix
const QString TextUtils::SMDFlipSuffix static
The documentation for this class was generated from the following files:
utils/textutils.h
utils/textutils.cpp