Fritzing: AutorouterSettingsDialog Class Reference
AutorouterSettingsDialog Class Reference
#include <autoroutersettingsdialog.h>
Public Member Functions
AutorouterSettingsDialog (QHash< QString, QString > &settings, QWidget *parent=0)
~AutorouterSettingsDialog ()
QHash< QString, QString > getSettings ()
Static Public Attributes
static const QString AutorouteTraceWidth = "autorouteTraceWidth"
Protected Slots
void changeDiameter ()
void changeHoleSize (const QString &)
void changeThickness ()
void changeUnits (bool)
void keepoutEntry ()
void production (bool)
void toInches ()
void toMM ()
void widthEntry (const QString &)
Protected Member Functions
QWidget * createKeepoutWidget (const QString &keepoutString)
QWidget * createTraceWidget ()
QWidget * createViaWidget ()
void enableCustom (bool enable)
QString getKeepoutString ()
bool initProductionType ()
void setDefaultKeepout ()
void setTraceWidth (int newWidth)
Protected Attributes
QRadioButton * m_customButton
QFrame * m_customFrame
HoleSettings m_holeSettings
QRadioButton * m_homebrewButton
bool m_inches
QRadioButton * m_inRadio
double m_keepoutMils
QDoubleSpinBox * m_keepoutSpinBox
QRadioButton * m_mmRadio
QRadioButton * m_professionalButton
int m_traceWidth
QComboBox * m_traceWidthComboBox
Constructor & Destructor Documentation
AutorouterSettingsDialog()
AutorouterSettingsDialog::AutorouterSettingsDialog (QHash< QString, QString > & settings, QWidget * parent = 0)
References AutorouteTraceWidth, Via::AutorouteViaHoleSize, Via::AutorouteViaRingThickness, createKeepoutWidget(), createTraceWidget(), createViaWidget(), enableCustom(), HoleSettings::holeDiameter, Via::initHoleSettings(), initProductionType(), DRC::KeepoutSettingName, m_customButton, m_customFrame, m_holeSettings, m_homebrewButton, m_professionalButton, m_traceWidth, production(), and HoleSettings::ringThickness.
~AutorouterSettingsDialog()
AutorouterSettingsDialog::~AutorouterSettingsDialog ()
Member Function Documentation
changeDiameter
void AutorouterSettingsDialog::changeDiameter () protected slot
References PaletteItem::changeDiameter(), changeHoleSize(), HoleSettings::currentUnits(), m_holeSettings, and HoleSettings::ringThickness.
changeHoleSize
void AutorouterSettingsDialog::changeHoleSize (const QString & newSize) protected slot
References m_holeSettings, and PaletteItem::setHoleSize().
changeThickness
void AutorouterSettingsDialog::changeThickness () protected slot
References changeHoleSize(), PaletteItem::changeThickness(), HoleSettings::currentUnits(), HoleSettings::holeDiameter, and m_holeSettings.
changeUnits
void AutorouterSettingsDialog::changeUnits (bool) protected slot
References PaletteItem::changeUnits(), and m_holeSettings.
createKeepoutWidget()
QWidget * AutorouterSettingsDialog::createKeepoutWidget (const QString & keepoutString) protected
References TextUtils::convertToInches(), keepoutEntry(), ItemBase::label(), m_inRadio, m_keepoutMils, m_keepoutSpinBox, m_mmRadio, toInches(), and toMM().
createTraceWidget()
QWidget * AutorouterSettingsDialog::createTraceWidget () protected
References TraceWire::createWidthComboBox(), m_traceWidth, m_traceWidthComboBox, and widthEntry().
createViaWidget()
QWidget * AutorouterSettingsDialog::createViaWidget () protected
References changeDiameter(), changeHoleSize(), changeThickness(), changeUnits(), PaletteItem::createHoleSettings(), HoleSettings::diameterEdit, HoleSettings::inRadioButton, m_holeSettings, HoleSettings::mmRadioButton, HoleSettings::sizesComboBox, and HoleSettings::thicknessEdit.
enableCustom()
void AutorouterSettingsDialog::enableCustom (bool enable) protected
References m_customFrame.
getKeepoutString()
QString AutorouterSettingsDialog::getKeepoutString () protected
References m_inRadio, and m_keepoutSpinBox.
getSettings()
QHash< QString, QString > AutorouterSettingsDialog::getSettings ()
References AutorouteTraceWidth, Via::AutorouteViaHoleSize, Via::AutorouteViaRingThickness, getKeepoutString(), HoleSettings::holeDiameter, DRC::KeepoutSettingName, m_holeSettings, m_traceWidth, and HoleSettings::ringThickness.
initProductionType()
bool AutorouterSettingsDialog::initProductionType () protected
References TextUtils::convertToInches(), getKeepoutString(), HoleSettings::holeDiameter, HoleClassThing::holeSizeKeys, HoleClassThing::holeSizes, HoleSettings::holeThing, DRC::KeepoutDefaultMils, m_customButton, m_holeSettings, m_homebrewButton, m_professionalButton, m_traceWidth, Wire::mils(), GraphicsUtils::pixels2mils(), HoleSettings::ringThickness, Wire::STANDARD_TRACE_WIDTH, and GraphicsUtils::SVGDPI.
keepoutEntry
void AutorouterSettingsDialog::keepoutEntry () protected slot
References m_inRadio, m_keepoutMils, and m_keepoutSpinBox.
production
void AutorouterSettingsDialog::production (bool checked) protected slot
References changeHoleSize(), enableCustom(), m_customButton, m_homebrewButton, m_professionalButton, setDefaultKeepout(), and setTraceWidth().
setDefaultKeepout()
void AutorouterSettingsDialog::setDefaultKeepout () protected
References DRC::KeepoutDefaultMils, m_inRadio, m_keepoutMils, and m_keepoutSpinBox.
setTraceWidth()
void AutorouterSettingsDialog::setTraceWidth (int newWidth) protected
References m_traceWidthComboBox, and Wire::width().
toInches
void AutorouterSettingsDialog::toInches () protected slot
References m_keepoutMils, and m_keepoutSpinBox.
toMM
void AutorouterSettingsDialog::toMM () protected slot
References m_keepoutMils, and m_keepoutSpinBox.
widthEntry
void AutorouterSettingsDialog::widthEntry (const QString & text) protected slot
References m_traceWidth, and TraceWire::widthEntry().
Member Data Documentation
AutorouteTraceWidth
const QString AutorouterSettingsDialog::AutorouteTraceWidth = "autorouteTraceWidth" static
m_customButton
QRadioButton* AutorouterSettingsDialog::m_customButton protected
m_customFrame
QFrame* AutorouterSettingsDialog::m_customFrame protected
m_holeSettings
HoleSettings AutorouterSettingsDialog::m_holeSettings protected
m_homebrewButton
QRadioButton* AutorouterSettingsDialog::m_homebrewButton protected
m_inches
bool AutorouterSettingsDialog::m_inches protected
m_inRadio
QRadioButton* AutorouterSettingsDialog::m_inRadio protected
m_keepoutMils
double AutorouterSettingsDialog::m_keepoutMils protected
m_keepoutSpinBox
QDoubleSpinBox* AutorouterSettingsDialog::m_keepoutSpinBox protected
m_mmRadio
QRadioButton* AutorouterSettingsDialog::m_mmRadio protected
m_professionalButton
QRadioButton* AutorouterSettingsDialog::m_professionalButton protected
m_traceWidth
int AutorouterSettingsDialog::m_traceWidth protected
m_traceWidthComboBox
QComboBox* AutorouterSettingsDialog::m_traceWidthComboBox protected
The documentation for this class was generated from the following files:
autoroute/autoroutersettingsdialog.h
autoroute/autoroutersettingsdialog.cpp