Fritzing: FMessageBox Class Reference
FMessageBox Class Reference
#include <fmessagebox.h>
Public Member Functions
FMessageBox (QWidget *parent=0)
int exec ()
Static Public Member Functions
static QMessageBox::StandardButton critical (QWidget *parent, const QString &title, const QString &text, StandardButtons buttons=Ok, StandardButton defaultButton=NoButton)
static QMessageBox::StandardButton information (QWidget *parent, const QString &title, const QString &text, StandardButtons buttons=Ok, StandardButton defaultButton=NoButton)
static QMessageBox::StandardButton question (QWidget *parent, const QString &title, const QString &text, StandardButtons buttons=Ok, StandardButton defaultButton=NoButton)
static QMessageBox::StandardButton warning (QWidget *parent, const QString &title, const QString &text, StandardButtons buttons=Ok, StandardButton defaultButton=NoButton)
Static Public Attributes
static bool BlockMessages = false
Constructor & Destructor Documentation
FMessageBox()
FMessageBox::FMessageBox (QWidget * parent = 0)
Member Function Documentation
critical()
QMessageBox::StandardButton FMessageBox::critical (QWidget * parent, const QString & title, const QString & text, StandardButtons buttons = Ok, StandardButton defaultButton = NoButton) static
References BlockMessages, and DebugDialog::debug().
exec()
int FMessageBox::exec ()
References BlockMessages.
information()
QMessageBox::StandardButton FMessageBox::information (QWidget * parent, const QString & title, const QString & text, StandardButtons buttons = Ok, StandardButton defaultButton = NoButton) static
References BlockMessages, and DebugDialog::debug().
question()
QMessageBox::StandardButton FMessageBox::question (QWidget * parent, const QString & title, const QString & text, StandardButtons buttons = Ok, StandardButton defaultButton = NoButton) static
References BlockMessages, and DebugDialog::debug().
warning()
QMessageBox::StandardButton FMessageBox::warning (QWidget * parent, const QString & title, const QString & text, StandardButtons buttons = Ok, StandardButton defaultButton = NoButton) static
References BlockMessages, and DebugDialog::debug().
Member Data Documentation
BlockMessages
bool FMessageBox::BlockMessages = false static
The documentation for this class was generated from the following files:
utils/fmessagebox.h
utils/fmessagebox.cpp