Fritzing: CursorMaster Class Reference
CursorMaster Class Reference
#include <cursormaster.h>
Public Member Functions
void addCursor (QObject *listener, const QCursor &cursor)
void block ()
void removeCursor (QObject *listener)
void unblock ()
Static Public Member Functions
static void cleanup ()
static void initCursors ()
static CursorMaster * instance ()
Static Public Attributes
static QCursor * BendlegCursor = NULL
static QCursor * BendpointCursor = NULL
static QCursor * MakeCurveCursor = NULL
static QCursor * MakeWireCursor = NULL
static QCursor * MoveCursor = NULL
static QCursor * NewBendpointCursor = NULL
static QCursor * RotateCursor = NULL
static QCursor * RubberbandCursor = NULL
static QCursor * ScaleCursor = NULL
Protected Slots
void deleteCursor (QObject *)
void moveCursor ()
Protected Member Functions
CursorMaster ()
bool eventFilter (QObject *obj, QEvent *event)
Protected Attributes
bool m_blocked
Static Protected Attributes
static CursorMaster TheCursorMaster
Constructor & Destructor Documentation
CursorMaster()
CursorMaster::CursorMaster () protected
References m_blocked.
Member Function Documentation
addCursor()
void CursorMaster::addCursor (QObject * listener, const QCursor & cursor)
References deleteCursor(), Listeners, and m_blocked.
block()
void CursorMaster::block ()
References m_blocked.
cleanup()
void CursorMaster::cleanup () static
References Cursors.
deleteCursor
void CursorMaster::deleteCursor (QObject * object) protected slot
References removeCursor().
eventFilter()
bool CursorMaster::eventFilter (QObject * obj, QEvent * event) protected
References Listeners.
initCursors()
void CursorMaster::initCursors () static
References BendlegCursor, BendpointCursor, Cursors, instance(), MakeCurveCursor, MakeWireCursor, MoveCursor, NewBendpointCursor, RotateCursor, RubberbandCursor, and ScaleCursor.
instance()
CursorMaster * CursorMaster::instance () static
References TheCursorMaster.
moveCursor
void CursorMaster::moveCursor () protected slot
removeCursor()
void CursorMaster::removeCursor (QObject * listener)
References deleteCursor(), and Listeners.
unblock()
void CursorMaster::unblock ()
References m_blocked.
Member Data Documentation
BendlegCursor
QCursor * CursorMaster::BendlegCursor = NULL static
BendpointCursor
QCursor * CursorMaster::BendpointCursor = NULL static
m_blocked
bool CursorMaster::m_blocked protected
MakeCurveCursor
QCursor * CursorMaster::MakeCurveCursor = NULL static
MakeWireCursor
QCursor * CursorMaster::MakeWireCursor = NULL static
MoveCursor
QCursor * CursorMaster::MoveCursor = NULL static
NewBendpointCursor
QCursor * CursorMaster::NewBendpointCursor = NULL static
RotateCursor
QCursor * CursorMaster::RotateCursor = NULL static
RubberbandCursor
QCursor * CursorMaster::RubberbandCursor = NULL static
ScaleCursor
QCursor * CursorMaster::ScaleCursor = NULL static
TheCursorMaster
CursorMaster CursorMaster::TheCursorMaster static protected
The documentation for this class was generated from the following files:
utils/cursormaster.h
utils/cursormaster.cpp