Fritzing: GedaElementParser Class Reference
GedaElementParser Class Reference
#include <gedaelementparser.h>
Public Member Functions
GedaElementParser ()
~GedaElementParser ()=default
QString errorMessage () const noexcept
bool parse (GedaElementLexer *lexer)
QVariant result () const noexcept
QVector< QVariant > & symStack ()
Private Member Functions
void reallocateStack ()
Private Attributes
QString m_errorMessage
QVariant m_result
QVector< int > m_stateStack
QVector< QVariant > m_symStack
int m_tos
Additional Inherited Members
Public Types inherited from GedaElementGrammar
enum {
EOF_SYMBOL = 0, ATTRIBUTE = 7, ELEMENT = 1, ELEMENTARC = 6,
ELEMENTLINE = 5, HEXNUMBER = 14, LEFTBRACKET = 10, LEFTPAREN = 8,
MARK = 4, NUMBER = 12, PAD = 2, PIN = 3,
RIGHTBRACKET = 11, RIGHTPAREN = 9, STRING = 13, ACCEPT_STATE = 189,
RULE_COUNT = 104, STATE_COUNT = 190, TERMINAL_COUNT = 15, NON_TERMINAL_COUNT = 85,
GOTO_INDEX_OFFSET = 190, GOTO_INFO_OFFSET = 73, GOTO_CHECK_OFFSET = 73
}
Static Public Member Functions inherited from GedaElementGrammar
static int nt_action (int state, int nt)
static int t_action (int state, int token)
Static Public Attributes inherited from GedaElementGrammar
static const int action_check []
static const int action_default []
static const int action_index []
static const int action_info []
static const int goto_default []
static const int lhs []
static const int rhs []
static const int rule_index []
static const int rule_info []
static const char *const spell []
Constructor & Destructor Documentation
GedaElementParser()
GedaElementParser::GedaElementParser ()
~GedaElementParser()
GedaElementParser::~GedaElementParser () default
Member Function Documentation
errorMessage()
QString GedaElementParser::errorMessage () const noexcept
References m_errorMessage.
parse()
bool GedaElementParser::parse (GedaElementLexer * lexer)
References GedaElementGrammar::ACCEPT_STATE, GedaElementGrammar::action_index, GedaElementLexer::currentCommand(), GedaElementLexer::currentNumber(), GedaElementLexer::currentString(), GedaElementLexer::lex(), GedaElementGrammar::lhs, m_errorMessage, m_stateStack, m_symStack, m_tos, GedaElementGrammar::nt_action(), reallocateStack(), GedaElementGrammar::rhs, GedaElementGrammar::spell, GedaElementGrammar::t_action(), and GedaElementGrammar::TERMINAL_COUNT.
reallocateStack()
void GedaElementParser::reallocateStack () private
References m_stateStack.
result()
QVariant GedaElementParser::result () const noexcept
References m_result.
symStack()
QVector< QVariant > & GedaElementParser::symStack ()
References m_symStack.
Member Data Documentation
m_errorMessage
QString GedaElementParser::m_errorMessage private
m_result
QVariant GedaElementParser::m_result private
m_stateStack
QVector<int> GedaElementParser::m_stateStack private
m_symStack
QVector<QVariant> GedaElementParser::m_symStack private
m_tos
int GedaElementParser::m_tos private
The documentation for this class was generated from the following files:
svg/gedaelementparser.h
svg/gedaelementparser.cpp