Fritzing: FLineEdit Class Reference
FLineEdit Class Reference
#include <flineedit.h>
Signals
void editable (bool)
void mouseEnter ()
void mouseLeave ()
Public Member Functions
FLineEdit (QWidget *parent=NULL)
~FLineEdit ()
Protected Slots
void editingFinishedSlot ()
Protected Member Functions
void enterEvent (QEvent *)
void leaveEvent (QEvent *)
void mousePressEvent (QMouseEvent *event)
Protected Attributes
bool m_readOnly
Constructor & Destructor Documentation
FLineEdit()
FLineEdit::FLineEdit (QWidget * parent = NULL)
References editingFinishedSlot().
~FLineEdit()
FLineEdit::~FLineEdit ()
Member Function Documentation
editable
void FLineEdit::editable (bool) signal
editingFinishedSlot
void FLineEdit::editingFinishedSlot () protected slot
References editable(), and m_readOnly.
enterEvent()
void FLineEdit::enterEvent (QEvent * event) protected
References m_readOnly, and mouseEnter().
leaveEvent()
void FLineEdit::leaveEvent (QEvent * event) protected
References m_readOnly, and mouseLeave().
mouseEnter
void FLineEdit::mouseEnter () signal
mouseLeave
void FLineEdit::mouseLeave () signal
mousePressEvent()
void FLineEdit::mousePressEvent (QMouseEvent * event) protected
References editable(), and m_readOnly.
Member Data Documentation
m_readOnly
bool FLineEdit::m_readOnly protected
The documentation for this class was generated from the following files:
utils/flineedit.h
utils/flineedit.cpp