Fritzing: PinLabelDialog Class Reference
PinLabelDialog Class Reference
#include <pinlabeldialog.h>
Public Member Functions
PinLabelDialog (const QStringList &labels, bool singleRow, const QString &chipLabel, bool isCore, QWidget *parent=0)
~PinLabelDialog ()
bool doSaveAs ()
const QStringList & labels ()
void setLabelText (int index, QLineEdit *, const QString &text)
Protected Slots
void buttonClicked (QAbstractButton *)
void labelChanged ()
void labelEdited (const QString &)
void undoChanged (bool)
Protected Member Functions
QFrame * initLabels (const QStringList &labels, bool singleRow, const QString &chipLabel)
void keyPressEvent (QKeyEvent *e)
void makeOnePinEntry (int index, const QString &label, Qt::Alignment alignment, int row, QGridLayout *)
Protected Attributes
bool m_doSaveAs
bool m_isCore
QStringList m_labels
QPushButton * m_redoButton
QPushButton * m_saveAsButton
QPushButton * m_undoButton
QUndoStack m_undoStack
Constructor & Destructor Documentation
PinLabelDialog()
PinLabelDialog::PinLabelDialog (const QStringList & labels, bool singleRow, const QString & chipLabel, bool isCore, QWidget * parent = 0)
References buttonClicked(), initLabels(), labels(), m_doSaveAs, m_isCore, m_labels, m_redoButton, m_saveAsButton, m_undoButton, m_undoStack, and undoChanged().
~PinLabelDialog()
PinLabelDialog::~PinLabelDialog ()
Member Function Documentation
buttonClicked
void PinLabelDialog::buttonClicked (QAbstractButton * button) protected slot
References m_redoButton, m_undoButton, and m_undoStack.
doSaveAs()
bool PinLabelDialog::doSaveAs ()
References m_doSaveAs.
initLabels()
QFrame * PinLabelDialog::initLabels (const QStringList & labels, bool singleRow, const QString & chipLabel) protected
References labels(), and makeOnePinEntry().
keyPressEvent()
void PinLabelDialog::keyPressEvent (QKeyEvent * e) protected
labelChanged
void PinLabelDialog::labelChanged () protected slot
References m_labels, and m_undoStack.
labelEdited
void PinLabelDialog::labelEdited (const QString &) protected slot
References m_saveAsButton.
labels()
const QStringList & PinLabelDialog::labels ()
References m_labels.
makeOnePinEntry()
void PinLabelDialog::makeOnePinEntry (int index, const QString & label, Qt::Alignment alignment, int row, QGridLayout * gridLayout) protected
References labelChanged(), and labelEdited().
setLabelText()
void PinLabelDialog::setLabelText (int index, QLineEdit * lineEdit, const QString & text)
References m_labels.
undoChanged
void PinLabelDialog::undoChanged (bool) protected slot
References m_redoButton, m_saveAsButton, m_undoButton, and m_undoStack.
Member Data Documentation
m_doSaveAs
bool PinLabelDialog::m_doSaveAs protected
m_isCore
bool PinLabelDialog::m_isCore protected
m_labels
QStringList PinLabelDialog::m_labels protected
m_redoButton
QPushButton* PinLabelDialog::m_redoButton protected
m_saveAsButton
QPushButton* PinLabelDialog::m_saveAsButton protected
m_undoButton
QPushButton* PinLabelDialog::m_undoButton protected
m_undoStack
QUndoStack PinLabelDialog::m_undoStack protected
The documentation for this class was generated from the following files:
dialogs/pinlabeldialog.h
dialogs/pinlabeldialog.cpp