Fritzing: SwapTimer Class Reference
SwapTimer Class Reference
#include <mainwindow.h>
Public Member Functions
SwapTimer ()
const QString & family ()
ItemBase * itemBase ()
const QString & prop ()
QMap< QString, QString > propsMap ()
void setAll (const QString &family, const QString &prop, QMap< QString, QString > &propsMap, ItemBase *)
Protected Attributes
QString m_family
QPointer< ItemBase > m_itemBase
QString m_prop
QMap< QString, QString > m_propsMap
Constructor & Destructor Documentation
SwapTimer()
SwapTimer::SwapTimer ()
Member Function Documentation
family()
const QString & SwapTimer::family ()
References m_family.
itemBase()
ItemBase * SwapTimer::itemBase ()
References m_itemBase.
prop()
const QString & SwapTimer::prop ()
References m_prop.
propsMap()
QMap< QString, QString > SwapTimer::propsMap ()
References m_propsMap.
setAll()
void SwapTimer::setAll (const QString & family, const QString & prop, QMap< QString, QString > & propsMap, ItemBase * itemBase)
References family(), itemBase(), m_family, m_itemBase, m_prop, m_propsMap, prop(), and propsMap().
Member Data Documentation
m_family
QString SwapTimer::m_family protected
m_itemBase
QPointer<ItemBase> SwapTimer::m_itemBase protected
m_prop
QString SwapTimer::m_prop protected
m_propsMap
QMap<QString, QString> SwapTimer::m_propsMap protected
The documentation for this class was generated from the following files:
mainwindow/mainwindow.h
mainwindow/mainwindow.cpp