Fritzing: ResizableBoard Class Reference
ResizableBoard Class Reference
#include <resizableboard.h>
Public Slots
virtual void heightEntry ()
void keepAspectRatio (bool checkState)
virtual void paperSizeChanged (int)
void revertSize (bool)
virtual void widthEntry ()
Public Slots inherited from ItemBase
void hidePartLabel ()
void partLabelChanged (const QString &newText)
void showInFolder ()
void showPartLabel (bool show, ViewLayer *)
virtual void swapEntry (const QString &text)
Public Member Functions
ResizableBoard (ModelPart *, ViewLayer::ViewID, const ViewGeometry &viewGeometry, long id, QMenu *itemMenu, bool doLabel)
~ResizableBoard ()
void addedToScene (bool temporary)
bool collectExtraInfo (QWidget *parent, const QString &family, const QString &prop, const QString &value, bool swappingEnabled, QString &returnProp, QString &returnValue, QWidget *&returnWidget, bool &hide)
void figureHover ()
void getParams (QPointF &, QSizeF &)
QSizeF getSizeMM ()
bool hasCustomSVG ()
bool hasPartNumberProperty ()
bool inResize ()
void loadLayerKin (const LayerHash &viewLayers, ViewLayer::ViewLayerPlacement)
void paintSelected (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
virtual bool resizeMM (double w, double h, const LayerHash &viewLayers)
void resizePixels (double w, double h, const LayerHash &viewLayers)
QString retrieveSvg (ViewLayer::ViewLayerID, QHash< QString, QString > &svgHash, bool blackOnly, double dpi, double &factor)
void saveParams ()
virtual void setInitialSize ()
Public Member Functions inherited from Board
Board (ModelPart *, ViewLayer::ViewID, const ViewGeometry &viewGeometry, long id, QMenu *itemMenu, bool doLabel)
~Board ()
bool canFindConnectorsUnder ()
PluralType isPlural ()
void paintHover (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
bool rotation45Allowed ()
bool stickyEnabled ()
Public Member Functions inherited from PaletteItem
PaletteItem (ModelPart *, ViewLayer::ViewID, const ViewGeometry &viewGeometry, long id, QMenu *itemMenu, bool doLabel)
~PaletteItem ()
void addLayerKin (class LayerKinPaletteItem *lkpi)
virtual bool changePinLabels (bool singleRow, bool sip)
void clearModelPart ()
bool collectFemaleConnectees (QSet< ItemBase * > &items)
void collectWireConnectees (QSet< class Wire * > &wires)
void flipItem (Qt::Orientations orientation)
QStringList getPinLabels (bool &hasLocal)
const QList< class ItemBase * > & layerKin ()
bool mousePressEventK (PaletteItemBase *originalItem, QGraphicsSceneMouseEvent *)
void moveItem (ViewGeometry &viewGeometry)
void removeLayerKin ()
void renamePins (const QStringList &labels, bool singleRow)
bool renderImage (ModelPart *modelPart, ViewLayer::ViewID viewID, const LayerHash &viewLayers, ViewLayer::ViewLayerID, bool doConnectors, QString &error)
void resetConnector (ItemBase *itemBase, SvgIdLayer *svgIdLayer)
void resetConnectors ()
void resetConnectors (ItemBase *otherLayer, FSvgRenderer *otherLayerRenderer)
void resetID ()
void resetImage (class InfoGraphicsView *)
void resetKinImage (ItemBase *layerKin, InfoGraphicsView *infoGraphicsView)
void resetLayerKin (const QString &svg)
void retransform (const QTransform &)
void rotateItem (double degrees, bool includeRatsnest)
void setHidden (bool hidden)
void setInactive (bool inactivate)
void setInstanceTitle (const QString &, bool initial)
void setItemPos (QPointF &pos)
void setTransforms ()
QStringList sipOrDipOrLabels (bool &hasLayout, bool &sip)
void slamZ (double z)
bool swap (ModelPart *newModelPart, const LayerHash &layerHash, bool reinit, class SwapCommand *)
void syncKinMoved (QPointF offset, QPointF loc)
void transformItem2 (const QMatrix &)
QTransform untransform ()
Public Member Functions inherited from PaletteItemBase
PaletteItemBase (ModelPart *, ViewLayer::ViewID, const ViewGeometry &viewGeometry, long id, QMenu *itemMenu)
bool acceptsMousePressConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
void blockItemSelectedChange (bool selected)
QRectF boundingRect () const
QRectF boundingRectWithoutLegs () const
virtual bool canEditPart ()
bool collectFemaleConnectees (QSet< ItemBase * > &items)
void collectWireConnectees (QSet< class Wire * > &wires)
void connectedMoved (ConnectorItem *from, ConnectorItem *to, QList< ConnectorItem * > &already)
void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
void cursorKeyEvent (Qt::KeyboardModifiers modifiers)
const QCursor * getCursor (Qt::KeyboardModifiers)
void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
void hoverMoveEvent (QGraphicsSceneHoverEvent *event)
QPainterPath hoverShape () const
bool itemMoved ()
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
virtual void mouseMoveEventK (PaletteItemBase *originalItem, QGraphicsSceneMouseEvent *event)
void mousePressConnectorEvent (class ConnectorItem *, QGraphicsSceneMouseEvent *)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
virtual void mouseReleaseEventK (PaletteItemBase *originalItem, QGraphicsSceneMouseEvent *event)
void moveItem (ViewGeometry &)
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
void saveGeometry ()
virtual void saveInstanceLocation (QXmlStreamWriter &)
void setProp (const QString &prop, const QString &value)
virtual bool setUpImage (ModelPart *modelPart, const LayerHash &viewLayers, LayerAttributes &)
QPainterPath shape () const
QPointF syncMoved ()
bool syncSelected ()
Public Member Functions inherited from ItemBase
ItemBase (ModelPart *, ViewLayer::ViewID, const ViewGeometry &, long id, QMenu *itemMenu)
virtual ~ItemBase ()
virtual bool acceptsMouseDoubleClickConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual bool acceptsMouseMoveConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual bool acceptsMousePressLegEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual bool acceptsMouseReleaseConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual void addSticky (ItemBase *, bool stickem)
void addSubpart (ItemBase *)
virtual bool alreadySticking (ItemBase *itemBase)
ConnectorItem * anyConnectorItem ()
QRectF boundingRect () const
virtual void busConnectorItems (Bus *bus, ConnectorItem *, QList< ConnectorItem * > &items)
QList< Bus * > buses ()
const QList< ConnectorItem * > & cachedConnectorItems ()
const QList< ConnectorItem * > & cachedConnectorItemsConst () const
virtual void calcRotation (QTransform &rotation, QPointF center, ViewGeometry &)
bool canFlip (Qt::Orientations)
bool canFlipHorizontal ()
bool canFlipVertical ()
virtual void clearConnectorHover ()
void clearConnectorItemCache ()
void clearPartLabel ()
void collectConnectors (ConnectorPairHash &connectorHash, SkipCheckFunction)
void collectPropsMap (QString &family, QMap< QString, QString > &)
virtual void collectWireConnectees (QSet< Wire * > &wires)
virtual void connectionChange (ConnectorItem *onMe, ConnectorItem *onIt, bool connect)
virtual bool connectionIsAllowed (ConnectorItem *)
virtual void connectorHover (ConnectorItem *, ItemBase *, bool hovering)
const QString & constTitle () const
void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
void debugInfo (const QString &msg) const
void debugInfo2 (const QString &msg) const
virtual void doneLoading ()
void doRotateFlipPartLabel (double degrees, Qt::Orientations)
void ensureUniqueTitle (const QString &title, bool force)
QString family ()
const QString & filename ()
virtual bool filterMousePressConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
ConnectorItem * findConnectorItemWithSharedID (const QString &connectorID, ViewLayer::ViewLayerPlacement)
ConnectorItem * findConnectorItemWithSharedID (const QString &connectorID)
ItemBase * findSubpart (const QString &connectorID, ViewLayer::ViewLayerPlacement)
FSvgRenderer * fsvgRenderer () const
virtual void getConnectedColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
virtual void getEqualPotentialColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
virtual void getHoverColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
virtual QString getInspectorTitle ()
virtual void getNormalColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
QPixmap * getPixmap (QSize size)
void getPixmaps (QPixmap *&, QPixmap *&, QPixmap *&, bool swappingEnabled, QSize)
virtual QString getProperty (const QString &key)
bool getRatsnest ()
virtual void getUnconnectedColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
ViewGeometry & getViewGeometry ()
bool hasConnections ()
bool hasConnectors ()
bool hasNonConnectors ()
virtual bool hasPartLabel ()
bool hasRubberBandLeg () const
constexpr bool hidden () const noexcept
virtual void hoverEnterConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
void hoverEnterConnectorItem ()
void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
virtual void hoverLeaveConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
void hoverLeaveConnectorItem ()
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
virtual void hoverMoveConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
virtual void hoverUpdate ()
constexpr qint64 id () const noexcept
constexpr bool inactive () const noexcept
bool inHover ()
void initLayerAttributes (LayerAttributes &layerAttributes, ViewLayer::ViewID, ViewLayer::ViewLayerID, ViewLayer::ViewLayerPlacement, bool doConnectors, bool doCreateShape)
virtual bool inRotation ()
const QString & instanceTitle () const
virtual bool isBaseSticky ()
bool isEverVisible ()
bool isLocalSticky ()
bool isObsolete ()
bool isPartLabelVisible ()
virtual bool isSticky ()
virtual bool isSwappable ()
int itemType () const
void killRubberBandLeg ()
QString label ()
constexpr bool layerHidden () const noexcept
virtual ItemBase * layerKinChief ()
QString makePartLabelSvg (bool blackOnly, double dpi, double printerScale)
ModelPart * modelPart ()
ModelPartShared * modelPartShared ()
const QString & moduleID ()
virtual void mouseDoubleClickConnectorEvent (ConnectorItem *)
virtual void mouseMoveConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
void mousePressEvent (QGraphicsSceneMouseEvent *event)
virtual void mouseReleaseConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
bool moveLock ()
void movePartLabel (QPointF newPos, QPointF newOffset)
virtual ConnectorItem * newConnectorItem (Connector *connector)
virtual ConnectorItem * newConnectorItem (ItemBase *layerkin, Connector *connector)
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
PartLabel * partLabel ()
void partLabelMoved (QPointF oldPos, QPointF oldOffset, QPointF newPos, QPointF newOffset)
QRectF partLabelSceneBoundingRect ()
QPointF partLabelScenePos ()
void partLabelSetHidden (bool hide)
ViewLayer::ViewLayerID partLabelViewLayerID ()
void prepareGeometryChange ()
virtual QHash< QString, QString > prepareProps (ModelPart *, bool wantDebug, QStringList &keys)
QString prop (const QString &p)
bool reloadRenderer (const QString &svg, bool fastload)
void removeTooltip ()
bool resetRenderer (const QString &svg)
bool resetRenderer (const QString &svg, QString &newSvg)
void resetValues (const QString &family, const QString &prop)
void restorePartLabel (QDomElement &labelGeometry, ViewLayer::ViewLayerID)
ConnectorItem * rightClickedConnector ()
void rotateFlipPartLabel (double degrees, Qt::Orientations)
virtual bool rotationAllowed ()
virtual void saveInstance (QXmlStreamWriter &)
bool sceneEvent (QEvent *event)
const QPainterPath & selectionShape ()
virtual void setAcceptsMousePressLegEvent (bool)
void setCanFlipHorizontal (bool)
void setCanFlipVertical (bool)
virtual void setDropOffset (QPointF offset)
void setEverVisible (bool)
void setFilename (const QString &)
virtual void setInRotation (bool)
virtual void setInspectorTitle (const QString &oldText, const QString &newText)
void setItemIsSelectable (bool selectable)
virtual void setLayerHidden (bool hidden)
void setLocalSticky (bool)
void setModelPart (ModelPart *)
virtual void setMoveLock (bool)
void setSharedRendererEx (FSvgRenderer *)
void setSquashShape (bool)
virtual void setSticky (bool)
void setSuperpart (ItemBase *)
virtual void setSwappable (bool)
void setTooltip ()
virtual void setTransform2 (const QTransform &)
FSvgRenderer * setUpImage (ModelPart *modelPart, LayerAttributes &)
void setViewLayerID (ViewLayer::ViewLayerID, const LayerHash &viewLayers)
void setViewLayerID (const QString &layerName, const LayerHash &viewLayers)
void setViewLayerPlacement (ViewLayer::ViewLayerPlacement)
void showConnectors (const QStringList &)
constexpr QSizeF size () const noexcept
const QString & spice () const
const QString & spiceModel () const
virtual ItemBase * stickingTo ()
virtual QList< QPointer< ItemBase > > stickyList ()
const QList< QPointer< ItemBase > > & subparts ()
ItemBase * superpart ()
virtual const QString & title ()
bool topLevel ()
virtual void transformItem (const QTransform &, bool includeRatsnest)
void updateConnections (ConnectorItem *, bool includeRatsnest, QList< ConnectorItem * > &already)
void updateConnectionsAux (bool includeRatsnest, QList< ConnectorItem * > &already)
void updateConnectors ()
void updatePartLabelInstanceTitle ()
virtual void updateTooltip ()
ViewLayer::ViewID viewID ()
QString & viewIDName ()
ViewLayer::ViewLayerID viewLayerID () const
ViewLayer::ViewLayerPlacement viewLayerPlacement () const
ViewGeometry::WireFlags wireFlags () const
virtual void writeGeometry (QXmlStreamWriter &)
virtual void writeXml (QXmlStreamWriter &)
double z ()
Protected Types
enum Corner {
NO_CORNER = 0, TOP_LEFT, TOP_RIGHT, BOTTOM_LEFT,
BOTTOM_RIGHT
}
Protected Member Functions
QStringList collectValues (const QString &family, const QString &prop, QString &value)
virtual ResizableBoard::Corner findCorner (QPointF p, Qt::KeyboardModifiers)
void fixWH ()
QString getShapeForRenderer (const QString &svg, ViewLayer::ViewLayerID viewLayerID)
void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
void hoverMoveEvent (QGraphicsSceneHoverEvent *event)
void initPaperSizes ()
virtual void loadTemplates ()
QString makeBoardSvg (double mmW, double mmH, double milsW, double milsH)
virtual QString makeFirstLayerSvg (double mmW, double mmH, double milsW, double milsH)
virtual QString makeLayerSvg (ViewLayer::ViewLayerID viewLayerID, double mmW, double mmH, double milsW, double milsH)
virtual QString makeNextLayerSvg (ViewLayer::ViewLayerID, double mmW, double mmH, double milsW, double milsH)
QString makeSilkscreenSvg (ViewLayer::ViewLayerID, double mmW, double mmH, double milsW, double milsH)
QString makeSvg (double mmW, double mmH, const QString &layerTemplate)
virtual double minHeight ()
virtual double minWidth ()
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
void mousePressEvent (QGraphicsSceneMouseEvent *event)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
virtual void resizeMMAux (double w, double h)
void setKinCursor (QCursor &)
void setKinCursor (Qt::CursorShape)
QFrame * setUpDimEntry (bool includeAspectRatio, bool includeRevert, bool includePaperSizes, QWidget *&returnWidget)
void setWidthAndHeight (double w, double h)
virtual ViewLayer::ViewID theViewID ()
void updatePaperSizes (double width, double height)
Protected Member Functions inherited from Board
bool canLoad (const QString &fileName, const QString &reason)
virtual bool checkImage (const QString &filename)
virtual QStringList & getImageNames ()
virtual QStringList & getNewImageNames ()
virtual void prepLoadImageAux (const QString &fileName, bool addName)
void setFileNameItems ()
void setupLoadImage (QWidget *parent, const QString &family, const QString &prop, const QString &value, bool swappingEnabled, QString &returnProp, QString &returnValue, QWidget *&returnWidget)
void unableToLoad (const QString &fileName, const QString &reason)
ViewLayer::ViewID useViewIDForPixmap (ViewLayer::ViewID, bool swappingEnabled)
Protected Member Functions inherited from PaletteItem
QString appendHoleSize (const QString &moduleID, const QString &holeSize, const QString &ringThickness)
bool collectHoleSizeInfo (const QString &defaultHoleSizeValue, QWidget *parent, bool swappingEnabled, QString &returnProp, QString &returnValue, QWidget *&returnWidget)
void generateSwap (const QString &text, GenModuleID, GenFzp, GenSvg makeBreadboardSvg, GenSvg makeSchematicSvg, GenSvg makePcbSvg)
QString hackFzpHoleSize (const QString &moduleID, const QString &pcbFilename, const QString &holeSize)
QString hackSvgHoleSize (const QString &holeDiameter, const QString &ringThickness)
bool isSingleRow (const QList< ConnectorItem * > &connectorItems)
QVariant itemChange (GraphicsItemChange change, const QVariant &value)
bool makeLocalModifications (QByteArray &svg, const QString &filename)
void makeOneKin (qint64 &id, ViewLayer::ViewLayerID, ViewLayer::ViewLayerPlacement, ViewGeometry &, const LayerHash &)
void mousePressEvent (QGraphicsSceneMouseEvent *event)
void setUpHoleSizes (const QString &type, HoleClassThing &)
void setUpHoleSizesAux (HoleClassThing &, const QString &type)
QList< Connector * > sortConnectors ()
void syncKinSelection (bool selected, PaletteItemBase *originator)
void updateConnections (bool includeRatsnest, QList< ConnectorItem * > &already)
Protected Member Functions inherited from PaletteItemBase
virtual void cacheLoaded (const LayerAttributes &)
void checkFreeRotation (Qt::KeyboardModifiers modifiers, QPointF scenePos)
void findConnectorsUnder ()
virtual bool freeRotationAllowed (Qt::KeyboardModifiers modifiers)
bool freeRotationAllowed ()
bool inRotationLocation (QPointF scenePos, Qt::KeyboardModifiers modifiers, QPointF &returnPoint)
virtual LayerKinPaletteItem * newLayerKinPaletteItem (PaletteItemBase *chief, ModelPart *, const ViewGeometry &, long id, QMenu *itemMenu, const LayerHash &, LayerAttributes &)
virtual void setInitialTransform (const QTransform &)
void setUpConnectors (FSvgRenderer *, bool ignoreTerminalPoints)
Protected Member Functions inherited from ItemBase
void createShape (LayerAttributes &layerAttributes)
QPixmap * getPixmap (ViewLayer::ViewID, bool swappingEnabled, QSize size)
QVariant itemChange (QGraphicsItem::GraphicsItemChange change, const QVariant &value)
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
virtual void paintBody (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
virtual void paintHover (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget, const QPainterPath &shape)
void saveLocAndTransform (QXmlStreamWriter &streamWriter)
virtual void setDefaultTooltip ()
void setInstanceTitleAux (const QString &title, bool initial)
void setInstanceTitleTooltip (const QString &text)
void updateHidden ()
Protected Attributes
QSizeF m_aspectRatio
QPointer< QCheckBox > m_aspectRatioCheck
QPointer< QLabel > m_aspectRatioLabel
QPointF m_boardPos
QSizeF m_boardSize
Corner m_corner
double m_currentScale
int m_decimalsAfter
QPointer< QLineEdit > m_heightEditor
bool m_keepAspectRatio
QPointer< QComboBox > m_paperSizeComboBox
QPointF m_resizeMousePos
QPointF m_resizeStartBottomLeft
QPointF m_resizeStartBottomRight
QPointF m_resizeStartPos
QSizeF m_resizeStartSize
QPointF m_resizeStartTopLeft
QPointF m_resizeStartTopRight
QPointer< QPushButton > m_revertButton
QPointer< QLineEdit > m_widthEditor
Protected Attributes inherited from Board
QPointer< QComboBox > m_fileNameComboBox
bool m_svgOnly
Protected Attributes inherited from PaletteItem
int m_flipCount
HoleSettings m_holeSettings
QList< class ItemBase * > m_layerKin
Protected Attributes inherited from PaletteItemBase
bool m_blockItemSelectedChange
bool m_blockItemSelectedValue
QPointF m_offset
bool m_svg
QPointF m_syncMoved
bool m_syncSelected
Protected Attributes inherited from ItemBase
bool m_acceptsMousePressLegEvent = true
QList< ConnectorItem * > m_cachedConnectorItems
bool m_canFlipHorizontal = false
bool m_canFlipVertical = false
int m_connectorHoverCount = 0
int m_connectorHoverCount2 = 0
bool m_everVisible = true
QString m_filename
FSvgRenderer * m_fsvgRenderer = nullptr
bool m_hasRubberBandLeg = false
bool m_hidden = false
int m_hoverCount = 0
bool m_hoverEnterSpaceBarWasPressed = false
qint64 m_id = 0
bool m_inactive = false
bool m_inRotation = false
QMenu * m_itemMenu = nullptr
bool m_layerHidden = false
QPointer< ModelPart > m_modelPart
bool m_moveLock = false
QGraphicsSvgItem * m_moveLockItem = nullptr
QPointer< PartLabel > m_partLabel
QMap< QString, QString > m_propsMap
ConnectorItem * m_rightClickedConnector = nullptr
QPainterPath m_selectionShape
QSizeF m_size
bool m_spaceBarWasPressed = false
bool m_squashShape = false
bool m_sticky = false
QGraphicsSvgItem * m_stickyItem = nullptr
QHash< long, QPointer< ItemBase > > m_stickyList
QList< QPointer< ItemBase > > m_subparts
QPointer< ItemBase > m_superpart
bool m_swappable = true
ViewGeometry m_viewGeometry
ViewLayer::ViewID m_viewID
ViewLayer::ViewLayerID m_viewLayerID
ViewLayer::ViewLayerPlacement m_viewLayerPlacement
bool m_zUninitialized = true
Static Protected Attributes
static const double CornerHandleSize = 7.0
Static Protected Attributes inherited from Board
static QStringList BoardImageNames
static QStringList NewBoardImageNames
Static Protected Attributes inherited from ItemBase
static QBrush ChosenBrush
static QPen ChosenPen
static QBrush ConnectedBrush
static QPen ConnectedPen
static QBrush EqualPotentialBrush
static QPen EqualPotentialPen
static QBrush HoverBrush
static QPen HoverPen
static long nextID
static QBrush NormalBrush
static constexpr double NormalConnectorOpacity = 0.4
static QPen NormalPen
static QPointer< ReferenceModel > TheReferenceModel = nullptr
static QBrush UnconnectedBrush
static QPen UnconnectedPen
Additional Inherited Members
Public Types inherited from ItemBase
enum PluralType { Singular, Plural, NotSure }
Signals inherited from PaletteItem
void pinLabelSwap (ItemBase *, const QString &moduleID)
Static Public Member Functions inherited from Board
static QString convertFromXmlName (const QString &)
static QString convertToXmlName (const QString &)
static bool isBoard (ItemBase *)
static bool isBoard (ModelPart *)
Static Public Member Functions inherited from PaletteItem
static bool changeDiameter (HoleSettings &holeSettings, QObject *sender)
static bool changeThickness (HoleSettings &holeSettings, QObject *sender)
static QString changeUnits (HoleSettings &)
static QWidget * createHoleSettings (QWidget *parent, HoleSettings &, bool swappingEnabled, const QString &currentHoleSize, bool advanced)
static QString genFZP (const QString &moduleid, const QString &templateName, int minPins, int maxPins, int steps, bool smd)
static void initHoleSettings (HoleSettings &holeSettings, HoleClassThing *)
static bool setHoleSize (QString &holeSize, bool force, HoleSettings &holeSettings)
static void updateEditTexts (HoleSettings &)
static void updateSizes (HoleSettings &)
static void updateValidators (HoleSettings &)
Static Public Member Functions inherited from ItemBase
static void cleanup ()
static QColor connectedColor ()
static ItemBase * extractTopLevelItemBase (QGraphicsItem *thing)
static qint64 getNextID ()
static qint64 getNextID (qint64 fromIndex)
static void initNames ()
static void renderOne (QDomDocument *, QImage *, const QRectF &renderRect)
static void setConnectedColor (QColor &)
static void setReferenceModel (ReferenceModel *)
static void setUnconnectedColor (QColor &)
static QColor standardConnectedColor ()
static QColor standardUnconnectedColor ()
static QString translatePropertyName (const QString &key)
static QColor unconnectedColor ()
static bool zLessThan (ItemBase *&p1, ItemBase *&p2)
Static Public Attributes inherited from Board
static QString OneLayerTranslated
static QString TwoLayersTranslated
Static Public Attributes inherited from PaletteItem
static const QString HoleSizePrefix
Static Public Attributes inherited from ItemBase
static const QColor ConnectorHoverColor
static const double ConnectorHoverOpacity = .40
static const QList< ItemBase * > EmptyList
static const QColor HoverColor
static const double HoverOpacity = .20
static const QString ITEMBASE_FONT_PREFIX = "<font size='2'>"
static const QString ITEMBASE_FONT_SUFFIX = "</font>"
static QString PartInstanceDefaultTitle
static QHash< QString, QString > TranslatedPropertyNames
Protected Slots inherited from Board
void fileNameEntry (const QString &filename)
void prepLoadImage ()
Protected Slots inherited from PaletteItem
void changeDiameter ()
virtual void changeHoleSize (const QString &)
void changeThickness ()
virtual void changeUnits (bool)
void openPinLabelDialog ()
Protected Slots inherited from PaletteItemBase
void partPropertyEntry ()
Static Protected Member Functions inherited from Board
static void moreCheckImage (const QString &filename)
static QString setBoardOutline (const QString &svg)
Static Protected Member Functions inherited from PaletteItem
static QStringList getSizes (QString &holeSize, HoleSettings &)
static QString hackFzpHoleSize (QDomDocument &document, const QString &newModuleID, const QString &pcbFilename, const QString &newSize)
static QString hackFzpHoleSize (const QString &fzp, const QString &moduleid, int hsix)
static QString hackSvgHoleSize (QDomDocument &domDocument, const QString &holeDiameter, const QString &ringThickness)
static QString hackSvgHoleSizeAux (const QString &svg, const QString &expectedFileName)
Static Protected Member Functions inherited from PaletteItemBase
static QString normalizeSvg (QString &svg, ViewLayer::ViewLayerID viewLayerID, bool blackOnly, double dpi, double &factor)
Static Protected Member Functions inherited from ItemBase
static bool fixCopper1 (ModelPart *modelPart, const QString &filename, ViewLayer::ViewLayerID viewLayerID, ViewLayer::ViewLayerPlacement, QDomDocument &)
static bool getFlipDoc (ModelPart *modelPart, const QString &filename, ViewLayer::ViewLayerID viewLayerID, ViewLayer::ViewLayerPlacement, QDomDocument &, Qt::Orientations)
Member Enumeration Documentation
Corner
enum ResizableBoard::Corner protected
Enumerator
NO_CORNER
TOP_LEFT
TOP_RIGHT
BOTTOM_LEFT
BOTTOM_RIGHT
Constructor & Destructor Documentation
ResizableBoard()
ResizableBoard::ResizableBoard (ModelPart * modelPart, ViewLayer::ViewID viewID, const ViewGeometry & viewGeometry, long id, QMenu * itemMenu, bool doLabel)
References fixWH(), m_aspectRatioCheck, m_aspectRatioLabel, m_corner, m_currentScale, m_decimalsAfter, m_heightEditor, m_keepAspectRatio, m_paperSizeComboBox, m_revertButton, m_widthEditor, and NO_CORNER.
~ResizableBoard()
ResizableBoard::~ResizableBoard ()
Member Function Documentation
addedToScene()
void ResizableBoard::addedToScene (bool temporary) virtual
Reimplemented from ItemBase.
Reimplemented in SchematicFrame.
References ItemBase::addedToScene(), loadTemplates(), and setInitialSize().
collectExtraInfo()
bool ResizableBoard::collectExtraInfo (QWidget * parent, const QString & family, const QString & prop, const QString & value, bool swappingEnabled, QString & returnProp, QString & returnValue, QWidget *& returnWidget, bool & hide) virtual
Reimplemented from Board.
Reimplemented in SchematicFrame.
References PaletteItemBase::boundingRect(), Board::collectExtraInfo(), ItemBase::family(), m_decimalsAfter, ItemBase::m_modelPart, GraphicsUtils::pixels2mm(), ItemBase::prop(), setUpDimEntry(), and GraphicsUtils::SVGDPI.
collectValues()
QStringList ResizableBoard::collectValues (const QString & family, const QString & prop, QString & value) protected virtual
Reimplemented from Board.
References Board::collectValues(), ItemBase::family(), and ItemBase::prop().
figureHover()
void ResizableBoard::figureHover () virtual
Reimplemented from PaletteItem.
References ALLMOUSEBUTTONS, and PaletteItem::m_layerKin.
findCorner()
ResizableBoard::Corner ResizableBoard::findCorner (QPointF p, Qt::KeyboardModifiers modifiers) protected virtual
Reimplemented in LogoItem, and Pad.
References BOTTOM_LEFT, BOTTOM_RIGHT, CornerHandleSize, GraphicsUtils::distanceSqd(), m_currentScale, ItemBase::m_size, ItemBase::moveLock(), NO_CORNER, TOP_LEFT, and TOP_RIGHT.
fixWH()
void ResizableBoard::fixWH () protected
References DebugDialog::debug(), and ItemBase::m_modelPart.
getParams()
void ResizableBoard::getParams (QPointF & p, QSizeF & s)
References m_boardPos, and m_boardSize.
getShapeForRenderer()
QString ResizableBoard::getShapeForRenderer (const QString & svg, ViewLayer::ViewLayerID viewLayerID) protected
References SvgFileSplitter::domDocument(), SvgFileSplitter::elementString(), SvgFileSplitter::splitString(), ItemBase::viewLayerID(), and ViewLayer::viewLayerXmlNameFromID().
getSizeMM()
QSizeF ResizableBoard::getSizeMM ()
References ItemBase::m_modelPart.
hasCustomSVG()
bool ResizableBoard::hasCustomSVG () virtual
Reimplemented from ItemBase.
References ItemBase::m_viewID, and theViewID().
hasPartNumberProperty()
bool ResizableBoard::hasPartNumberProperty () virtual
Reimplemented from ItemBase.
Reimplemented in SchematicFrame.
heightEntry
void ResizableBoard::heightEntry () virtual slot
References InfoGraphicsView::getInfoGraphicsView(), ItemBase::m_modelPart, and InfoGraphicsView::resizeBoard().
hoverEnterEvent()
void ResizableBoard::hoverEnterEvent (QGraphicsSceneHoverEvent * event) protected
References PaletteItemBase::hoverEnterEvent().
hoverLeaveEvent()
void ResizableBoard::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) protected
References PaletteItemBase::hoverLeaveEvent(), and setKinCursor().
hoverMoveEvent()
void ResizableBoard::hoverMoveEvent (QGraphicsSceneHoverEvent * event) protected
References BOTTOM_LEFT, BOTTOM_RIGHT, findCorner(), PaletteItemBase::hoverMoveEvent(), m_corner, CursorMaster::ScaleCursor, setKinCursor(), TOP_LEFT, and TOP_RIGHT.
initPaperSizes()
void ResizableBoard::initPaperSizes () protected
References PaperSizeDimensions, and PaperSizeNames.
inResize()
bool ResizableBoard::inResize ()
References m_corner, and NO_CORNER.
keepAspectRatio
void ResizableBoard::keepAspectRatio (bool checkState) slot
References m_keepAspectRatio.
loadLayerKin()
void ResizableBoard::loadLayerKin (const LayerHash & viewLayers, ViewLayer::ViewLayerPlacement viewLayerPlacement) virtual
Reimplemented from PaletteItem.
References PaletteItem::loadLayerKin(), loadTemplates(), ItemBase::m_modelPart, resizeMM(), and ItemBase::viewLayerPlacement().
loadTemplates()
void ResizableBoard::loadTemplates () protected virtual
Reimplemented in SchematicFrame.
References ViewLayer::Board, BoardLayerTemplates, getShapeForRenderer(), ItemBase::m_filename, ItemBase::moduleID(), ViewLayer::Silkscreen0, Silkscreen0LayerTemplates, ViewLayer::Silkscreen1, and SilkscreenLayerTemplates.
makeBoardSvg()
QString ResizableBoard::makeBoardSvg (double mmW, double mmH, double milsW, double milsH) protected
References BoardLayerTemplates, makeSvg(), and ItemBase::moduleID().
makeFirstLayerSvg()
QString ResizableBoard::makeFirstLayerSvg (double mmW, double mmH, double milsW, double milsH) protected virtual
Reimplemented in CopperBlocker, SchematicFrame, and Pad.
References makeBoardSvg().
makeLayerSvg()
QString ResizableBoard::makeLayerSvg (ViewLayer::ViewLayerID viewLayerID, double mmW, double mmH, double milsW, double milsH) protected virtual
Reimplemented in SchematicFrame, and Pad.
References ViewLayer::Board, makeBoardSvg(), makeSilkscreenSvg(), ViewLayer::Silkscreen0, ViewLayer::Silkscreen1, and ItemBase::viewLayerID().
makeNextLayerSvg()
QString ResizableBoard::makeNextLayerSvg (ViewLayer::ViewLayerID viewLayerID, double mmW, double mmH, double milsW, double milsH) protected virtual
Reimplemented in SchematicFrame, and Pad.
References makeSilkscreenSvg(), ViewLayer::Silkscreen0, ViewLayer::Silkscreen1, and ItemBase::viewLayerID().
makeSilkscreenSvg()
QString ResizableBoard::makeSilkscreenSvg (ViewLayer::ViewLayerID viewLayerID, double mmW, double mmH, double milsW, double milsH) protected
References makeSvg(), ItemBase::moduleID(), ViewLayer::Silkscreen0, Silkscreen0LayerTemplates, SilkscreenLayerTemplates, and ItemBase::viewLayerID().
makeSvg()
QString ResizableBoard::makeSvg (double mmW, double mmH, const QString & layerTemplate) protected
References TextUtils::collectLeaves().
minHeight()
double ResizableBoard::minHeight () protected virtual
Reimplemented in LogoItem, SchematicFrame, and Pad.
References GraphicsUtils::SVGDPI.
minWidth()
double ResizableBoard::minWidth () protected virtual
Reimplemented in LogoItem, SchematicFrame, and Pad.
References GraphicsUtils::SVGDPI.
mouseMoveEvent()
void ResizableBoard::mouseMoveEvent (QGraphicsSceneMouseEvent * event) protected
References BOTTOM_LEFT, BOTTOM_RIGHT, DebugDialog::debug(), ItemBase::getViewGeometry(), PaletteItem::layerKin(), ItemBase::layerKinChief(), m_aspectRatio, m_corner, m_keepAspectRatio, m_resizeMousePos, m_resizeStartBottomLeft, m_resizeStartBottomRight, m_resizeStartSize, m_resizeStartTopRight, ItemBase::m_size, minHeight(), minWidth(), PaletteItemBase::mouseMoveEvent(), NO_CORNER, resizePixels(), ViewGeometry::setTransform(), TextUtils::svgMatrix(), TOP_LEFT, and TOP_RIGHT.
mousePressEvent()
void ResizableBoard::mousePressEvent (QGraphicsSceneMouseEvent * event) protected
References findCorner(), InfoGraphicsView::getInfoGraphicsView(), m_corner, m_resizeMousePos, m_resizeStartBottomLeft, m_resizeStartBottomRight, m_resizeStartPos, m_resizeStartSize, m_resizeStartTopLeft, m_resizeStartTopRight, ItemBase::m_size, ItemBase::m_spaceBarWasPressed, PaletteItem::mousePressEvent(), NO_CORNER, setInitialSize(), and InfoGraphicsView::viewItemInfo().
mouseReleaseEvent()
void ResizableBoard::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected
References InfoGraphicsView::getInfoGraphicsView(), m_corner, PaletteItemBase::mouseReleaseEvent(), NO_CORNER, setKinCursor(), and InfoGraphicsView::viewItemInfo().
paintSelected()
void ResizableBoard::paintSelected (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) virtual
Reimplemented from PaletteItemBase.
References CornerHandleSize, m_currentScale, ItemBase::m_hidden, ItemBase::m_layerHidden, ItemBase::m_size, and PaletteItemBase::paintSelected().
paperSizeChanged
void ResizableBoard::paperSizeChanged (int index) virtual slot
References InfoGraphicsView::getInfoGraphicsView(), and InfoGraphicsView::resizeBoard().
resizeMM()
bool ResizableBoard::resizeMM (double w, double h, const LayerHash & viewLayers) virtual
Reimplemented in BoardLogoItem, and LogoItem.
References PaletteItemBase::boundingRect(), ItemBase::initLayerAttributes(), ItemBase::m_viewID, ItemBase::m_viewLayerID, ItemBase::m_viewLayerPlacement, ItemBase::modelPart(), GraphicsUtils::pixels2mm(), resizeMMAux(), ModelPart::setLocalProp(), PaletteItemBase::setUpImage(), and GraphicsUtils::SVGDPI.
resizeMMAux()
void ResizableBoard::resizeMMAux (double w, double h) protected virtual
Reimplemented in Pad.
References m_decimalsAfter, PaletteItem::m_layerKin, makeFirstLayerSvg(), makeNextLayerSvg(), GraphicsUtils::mm2mils(), ItemBase::modelPart(), ItemBase::resetRenderer(), ModelPart::setLocalProp(), setWidthAndHeight(), and ItemBase::viewLayerID().
resizePixels()
void ResizableBoard::resizePixels (double w, double h, const LayerHash & viewLayers)
References GraphicsUtils::pixels2mm(), resizeMM(), and GraphicsUtils::SVGDPI.
retrieveSvg()
QString ResizableBoard::retrieveSvg (ViewLayer::ViewLayerID viewLayerID, QHash< QString, QString > & svgHash, bool blackOnly, double dpi, double & factor) virtual
Reimplemented from PaletteItemBase.
Reimplemented in SchematicFrame.
References ItemBase::m_modelPart, makeLayerSvg(), GraphicsUtils::mm2mils(), PaletteItemBase::normalizeSvg(), PaletteItemBase::retrieveSvg(), and ItemBase::viewLayerID().
revertSize
void ResizableBoard::revertSize (bool) slot
References InfoGraphicsView::getInfoGraphicsView(), ModelPart::localProp(), m_revertButton, ItemBase::modelPart(), and InfoGraphicsView::resizeBoard().
saveParams()
void ResizableBoard::saveParams ()
References ModelPart::localProp(), m_boardPos, m_boardSize, and ItemBase::modelPart().
setInitialSize()
void ResizableBoard::setInitialSize () virtual
Reimplemented in SchematicFrame, and Pad.
References PaletteItemBase::boundingRect(), ItemBase::m_modelPart, ItemBase::modelPart(), GraphicsUtils::pixels2mm(), ModelPart::setLocalProp(), and GraphicsUtils::SVGDPI.
setKinCursor() [1/2]
void ResizableBoard::setKinCursor (QCursor & cursor) protected
References ItemBase::layerKin(), and ItemBase::layerKinChief().
setKinCursor() [2/2]
void ResizableBoard::setKinCursor (Qt::CursorShape cursor) protected
References ItemBase::layerKin(), and ItemBase::layerKinChief().
setUpDimEntry()
QFrame * ResizableBoard::setUpDimEntry (bool includeAspectRatio, bool includeRevert, bool includePaperSizes, QWidget *& returnWidget) protected
References heightEntry(), initPaperSizes(), JND, keepAspectRatio(), ModelPart::localProp(), m_aspectRatioCheck, m_aspectRatioLabel, m_decimalsAfter, m_heightEditor, m_keepAspectRatio, ItemBase::m_modelPart, m_paperSizeComboBox, m_revertButton, m_widthEditor, ItemBase::modelPart(), paperSizeChanged(), PaperSizeDimensions, PaperSizeNames, revertSize(), updatePaperSizes(), and widthEntry().
setWidthAndHeight()
void ResizableBoard::setWidthAndHeight (double w, double h) protected
References m_heightEditor, m_widthEditor, and updatePaperSizes().
theViewID()
ViewLayer::ViewID ResizableBoard::theViewID () protected virtual
Reimplemented in SchematicFrame, and Pad.
References ViewLayer::PCBView.
updatePaperSizes()
void ResizableBoard::updatePaperSizes (double width, double height) protected
References m_paperSizeComboBox, PaperSizeDimensions, and PaperSizeNames.
widthEntry
void ResizableBoard::widthEntry () virtual slot
References InfoGraphicsView::getInfoGraphicsView(), ItemBase::m_modelPart, and InfoGraphicsView::resizeBoard().
Member Data Documentation
CornerHandleSize
const double ResizableBoard::CornerHandleSize = 7.0 static protected
m_aspectRatio
QSizeF ResizableBoard::m_aspectRatio protected
m_aspectRatioCheck
QPointer<QCheckBox> ResizableBoard::m_aspectRatioCheck protected
m_aspectRatioLabel
QPointer<QLabel> ResizableBoard::m_aspectRatioLabel protected
m_boardPos
QPointF ResizableBoard::m_boardPos protected
m_boardSize
QSizeF ResizableBoard::m_boardSize protected
m_corner
Corner ResizableBoard::m_corner protected
m_currentScale
double ResizableBoard::m_currentScale protected
m_decimalsAfter
int ResizableBoard::m_decimalsAfter protected
m_heightEditor
QPointer<QLineEdit> ResizableBoard::m_heightEditor protected
m_keepAspectRatio
bool ResizableBoard::m_keepAspectRatio protected
m_paperSizeComboBox
QPointer<QComboBox> ResizableBoard::m_paperSizeComboBox protected
m_resizeMousePos
QPointF ResizableBoard::m_resizeMousePos protected
m_resizeStartBottomLeft
QPointF ResizableBoard::m_resizeStartBottomLeft protected
m_resizeStartBottomRight
QPointF ResizableBoard::m_resizeStartBottomRight protected
m_resizeStartPos
QPointF ResizableBoard::m_resizeStartPos protected
m_resizeStartSize
QSizeF ResizableBoard::m_resizeStartSize protected
m_resizeStartTopLeft
QPointF ResizableBoard::m_resizeStartTopLeft protected
m_resizeStartTopRight
QPointF ResizableBoard::m_resizeStartTopRight protected
m_revertButton
QPointer<QPushButton> ResizableBoard::m_revertButton protected
m_widthEditor
QPointer<QLineEdit> ResizableBoard::m_widthEditor protected
The documentation for this class was generated from the following files:
items/resizableboard.h
items/resizableboard.cpp