Fritzing: TranslatorListModel Class Reference
TranslatorListModel Class Reference
#include <translatorlistmodel.h>
Public Member Functions
TranslatorListModel (QFileInfoList &, QObject *parent=0)
~TranslatorListModel ()
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
int findIndex (const QString &language)
const QLocale * locale (int index)
int rowCount (const QModelIndex &parent=QModelIndex()) const
Static Public Member Functions
static void cleanup ()
Static Protected Attributes
static QHash< QString, QString > m_languages
static QList< QLocale * > m_localeList
Constructor & Destructor Documentation
TranslatorListModel()
TranslatorListModel::TranslatorListModel (QFileInfoList & fileInfoList, QObject * parent = 0)
References locale(), m_languages, and m_localeList.
~TranslatorListModel()
TranslatorListModel::~TranslatorListModel ()
Member Function Documentation
cleanup()
void TranslatorListModel::cleanup () static
References locale(), and m_localeList.
data()
QVariant TranslatorListModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const
References emptyVariant, m_languages, and m_localeList.
findIndex()
int TranslatorListModel::findIndex (const QString & language)
References locale(), and m_localeList.
locale()
const QLocale * TranslatorListModel::locale (int index)
References m_localeList.
rowCount()
int TranslatorListModel::rowCount (const QModelIndex & parent = QModelIndex()) const
References m_localeList.
Member Data Documentation
m_languages
QHash< QString, QString > TranslatorListModel::m_languages static protected
m_localeList
QList< QLocale * > TranslatorListModel::m_localeList static protected
The documentation for this class was generated from the following files:
dialogs/translatorlistmodel.h
dialogs/translatorlistmodel.cpp