Fritzing: S2S Class Reference
S2S Class Reference
#include <s2s.h>
Signals
void messageSignal (const QString &message)
Public Member Functions
S2S (bool fzpzStyle)
bool onefzp (QString &fzpFilePath, QString &schematicFilePath)
void setSvgDirs (QDir &oldDir, QDir &newDir)
Protected Member Functions
bool ensureTerminalPoints (const QString &fzpFilename, const QString &svgFilename, QDomElement &fzpRoot)
QList< ConnectorLocation * > initConnectors (const QDomElement &root, const QSvgRenderer &, const QString &fzpFilename, const QString &svgFilename)
double lrtb (QList< ConnectorLocation * > &, const QRectF &viewBox)
void message (const QString &)
void saveFile (const QString &content, const QString &path)
void setHidden (QList< ConnectorLocation * > &)
double spaceTitle (QStringList &titles, int openUnits)
double stringWidthMM (double fontSize, const QString &string)
Protected Attributes
QString m_andPath
QList< ConnectorLocation * > m_bottoms
double m_fudge = 0.0
bool m_fzpzStyle
QImage * m_image
QList< ConnectorLocation * > m_lefts
double m_maxBottom = 0.0
double m_maxRight = 0.0
double m_minLeft = 0.0
double m_minTop = 0.0
QDir m_newSvgDir
QDir m_oldSvgDir
QList< ConnectorLocation * > m_rights
QList< ConnectorLocation * > m_tops
Constructor & Destructor Documentation
S2S()
S2S::S2S (bool fzpzStyle)
Member Function Documentation
ensureTerminalPoints()
bool S2S::ensureTerminalPoints (const QString & fzpFilename, const QString & svgFilename, QDomElement & fzpRoot) protected
References TextUtils::findElementWithAttribute(), message(), TextUtils::removeXMLEntities(), and TextUtils::writeUtf8().
initConnectors()
QList< ConnectorLocation * > S2S::initConnectors (const QDomElement & root, const QSvgRenderer & renderer, const QString & fzpFilename, const QString & svgFilename) protected
References ConnectorLocation::bounds, ConnectorLocation::displayPinNumber, ConnectorLocation::hidden, ConnectorLocation::id, IntegerFinder(), m_maxBottom, m_maxRight, m_minLeft, m_minTop, message(), ConnectorLocation::name, ConnectorLocation::svgID, ConnectorLocation::terminalID, and ConnectorLocation::terminalPoint.
lrtb()
double S2S::lrtb (QList< ConnectorLocation * > & connectorLocations, const QRectF & viewBox) protected
References distances, FudgeDivisor, m_bottoms, m_fudge, m_lefts, m_maxBottom, m_maxRight, m_minLeft, m_minTop, m_rights, m_tops, qMax(), ConnectorLocation::terminalPoint, xLessThan(), and yLessThan().
message()
void S2S::message (const QString & msg) protected
References messageSignal().
messageSignal
void S2S::messageSignal (const QString & message) signal
onefzp()
bool S2S::onefzp (QString & fzpFilePath, QString & schematicFilePath)
References ensureTerminalPoints(), TextUtils::escapeAnd(), TextUtils::findText(), SchematicRectConstants::FontFamily, initConnectors(), SchematicRectConstants::LabelTextHeight, SchematicRectConstants::LabelTextSpace, layers(), lrtb(), m_bottoms, m_fzpzStyle, m_lefts, m_newSvgDir, m_oldSvgDir, m_rights, m_tops, makePin(), makePinNumber(), makePinText(), TextUtils::makeSVGHeader(), makeTerminal(), message(), SchematicRectConstants::NewUnit, SchematicRectConstants::PinBigTextHeight, SchematicRectConstants::PinTextIndent, SchematicRectConstants::PinWidth, qMax(), qMin(), SchematicRectConstants::RectFillColor, SchematicRectConstants::RectStrokeColor, SchematicRectConstants::RectStrokeWidth, TextUtils::resplit(), setHidden(), spaceTitle(), stringWidthMM(), ConnectorLocation::terminalPoint, SchematicRectConstants::TitleColor, and TextUtils::writeUtf8().
saveFile()
void S2S::saveFile (const QString & content, const QString & path) protected
setHidden()
void S2S::setHidden (QList< ConnectorLocation * > & connectorLocations) protected
References getX(), getY(), m_bottoms, m_fudge, m_lefts, m_rights, m_tops, and setHiddenAux().
setSvgDirs()
void S2S::setSvgDirs (QDir & oldDir, QDir & newDir)
References m_newSvgDir, and m_oldSvgDir.
spaceTitle()
double S2S::spaceTitle (QStringList & titles, int openUnits) protected
References SchematicRectConstants::LabelTextHeight, SchematicRectConstants::NewUnit, qMax(), and stringWidthMM().
stringWidthMM()
double S2S::stringWidthMM (double fontSize, const QString & string) protected
References TextUtils::escapeAnd(), SchematicRectConstants::FontFamily, ImageFactor, m_image, and TextUtils::makeSVGHeader().
Member Data Documentation
m_andPath
QString S2S::m_andPath protected
m_bottoms
QList<ConnectorLocation *> S2S::m_bottoms protected
m_fudge
double S2S::m_fudge = 0.0 protected
m_fzpzStyle
bool S2S::m_fzpzStyle protected
m_image
QImage* S2S::m_image protected
m_lefts
QList<ConnectorLocation *> S2S::m_lefts protected
m_maxBottom
double S2S::m_maxBottom = 0.0 protected
m_maxRight
double S2S::m_maxRight = 0.0 protected
m_minLeft
double S2S::m_minLeft = 0.0 protected
m_minTop
double S2S::m_minTop = 0.0 protected
m_newSvgDir
QDir S2S::m_newSvgDir protected
m_oldSvgDir
QDir S2S::m_oldSvgDir protected
m_rights
QList<ConnectorLocation *> S2S::m_rights protected
m_tops
QList<ConnectorLocation *> S2S::m_tops protected
The documentation for this class was generated from the following files:
utils/s2s.h
utils/s2s.cpp