Fritzing: BinManager Class Reference
BinManager Class Reference
#include <binmanager.h>
Public Slots
void setAsCurrentBin (PartsBinPaletteWidget *bin)
void toIconView ()
void toListView ()
void updateBinCombinedMenuCurrent ()
Signals
void savePartAsBundled (const QString &moduleId)
Public Member Functions
BinManager (class ReferenceModel *referenceModel, class HtmlInfoView *infoView, class WaitPushUndoStack *undoStack, MainWindow *parent)
virtual ~BinManager ()
void addBin (PartsBinPaletteWidget *bin)
void addNewPart (ModelPart *modelPart)
void addPartTo (PartsBinPaletteWidget *bin, ModelPart *mp, bool setDirty)
void addPartToBin (ModelPart *modelPart, int position=-1)
void addToMyParts (ModelPart *modelPart)
void addToTempPartsBin (ModelPart *modelPart)
bool beforeClosing ()
QMenu * binContextMenu (PartsBinPaletteWidget *)
void closeBinIn (int index)
QMenu * combinedMenu (PartsBinPaletteWidget *)
QMenu * combinedMenu ()
void copyFilesToContrib (ModelPart *, QWidget *originator)
QString createIfBinNotExists (const QString &dest, const QString &source)
QString createIfMyPartsNotExists ()
QString createIfSearchNotExists ()
bool currentViewIsIconView ()
void editSelectedPartNewFrom (PartsBinPaletteWidget *bin)
const QString & getSelectedModuleIDFromSketch ()
bool hasAlienParts ()
void hideTabBar ()
void hideTempPartsBin ()
void importPartToCurrentBin (const QString &filename)
void importPartToMineBin (const QString &filename)
void initStandardBins ()
void insertBin (PartsBinPaletteWidget *bin, int index)
bool isTempPartsBin (PartsBinPaletteWidget *bin)
void load (const QString &)
MainWindow * mainWindow ()
void openBin (const QString &fileName)
PartsBinPaletteWidget * openBinIn (QString fileName, bool fastLoad)
PartsBinPaletteWidget * openCoreBinIn ()
QList< QAction * > openedBinsActions (const QString &moduleId)
QMenu * partContextMenu (PartsBinPaletteWidget *)
void reloadPart (const QString &moduleID)
void search (const QString &searchText)
void setDirtyTab (PartsBinPaletteWidget *w, bool dirty=true)
void setInfoViewOnHover (bool infoViewOnHover)
void setTabIcon (PartsBinPaletteWidget *w, QIcon *)
void setTempPartsBinLocation (const QString &filename)
void updateTitle (PartsBinPaletteWidget *w, const QString &newTitle)
void updateViewChecks (bool iconView)
Static Public Member Functions
static bool getBinTitle (const QString &filename, QString &binTitle, QString &binIcon)
static void initNames ()
static bool isTabReorderingEvent (QDropEvent *event)
Static Public Attributes
static QString ContribPartsBinLocation
static QString CorePartsBinLocation
static QString MyPartsBinLocation
static QString MyPartsBinTemplateLocation
static QString SearchBinLocation
static QString SearchBinTemplateLocation
static QHash< QString, QString > StandardBinIcons
static QString TempPartsBinTemplateLocation
static QString Title
Protected Slots
void closeBin ()
void copyAllToSketch ()
void copyToSketch ()
void currentChanged (int)
void deleteBin ()
void editSelectedNew ()
void exportSelected ()
void findSelected ()
void mainLoad ()
PartsBinPaletteWidget * newBinIn ()
bool removeSelected ()
void renameBin ()
void saveBin ()
void saveBinAs ()
void saveBundledBin ()
void tabCloseRequested (int)
void updateFileName (PartsBinPaletteWidget *bin, const QString &newFileName, const QString &oldFilename)
Protected Member Functions
void addPartToBinAux (PartsBinPaletteWidget *bin, ModelPart *modelPart, int position=-1)
void connectTabWidget ()
void createCombinedMenu ()
void createContextMenus ()
void createMenu ()
PartsBinPaletteWidget * currentBin ()
void findAllBins (QList< BinLocation * > &actualLocations)
PartsBinPaletteWidget * findBin (const QString &binLocation)
void findBins (QDir &, QList< BinLocation * > &actualLocations, BinLocation::Location)
PartsBinPaletteWidget * getBin (int index)
PartsBinPaletteWidget * getOrOpenBin (const QString &dest, const QString &source)
PartsBinPaletteWidget * getOrOpenMyPartsBin ()
PartsBinPaletteWidget * getOrOpenSearchBin ()
void hackLocalContrib (QList< BinLocation * > &)
void importPart (const QString &filename, PartsBinPaletteWidget *bin)
PartsBinPaletteWidget * newBin ()
void readTheoreticalLocations (QList< BinLocation * > &theoreticalLocations)
void registerBin (PartsBinPaletteWidget *bin)
void restoreStateAndGeometry (QList< BinLocation * > &actualLocations)
void saveStateAndGeometry ()
void setAsCurrentTab (PartsBinPaletteWidget *bin)
void updateBinCombinedMenu (PartsBinPaletteWidget *bin)
Protected Attributes
QMenu * m_binContextMenu
QAction * m_closeBinAction
QMenu * m_combinedMenu
QAction * m_copyAllToSketchAction
QAction * m_copyToSketchAction
PartsBinPaletteWidget * m_currentBin
QString m_defaultSaveFolder
QAction * m_deleteBinAction
QAction * m_editPartNewAction
QAction * m_exportPartAction
QAction * m_findPartAction
HtmlInfoView * m_infoView
MainWindow * m_mainWindow
QAction * m_newBinAction
QAction * m_openAction
QHash< QString,PartsBinPaletteWidget * > m_openedBins
QMenu * m_partContextMenu
QMenu * m_partMenu
ReferenceModel * m_referenceModel
QAction * m_removePartAction
QAction * m_renameBinAction
QAction * m_saveBinAction
QAction * m_saveBinAsAction
QAction * m_saveBinAsBundledAction
QAction * m_showIconViewAction
QAction * m_showListViewAction
class StackTabWidget * m_stackTabWidget
QString m_tempPartsBinLocation
WaitPushUndoStack * m_undoStack
int m_unsavedBinsCount
Static Protected Attributes
static QString CurrentBinStyle = "background-color: black;"
static QString StandardBinStyle = "background-color: gray;"
Constructor & Destructor Documentation
BinManager()
BinManager::BinManager (class ReferenceModel * referenceModel, class HtmlInfoView * infoView, class WaitPushUndoStack * undoStack, MainWindow * parent)
References FolderUtils::getUserBinsPath(), m_combinedMenu, m_currentBin, m_defaultSaveFolder, m_infoView, m_mainWindow, m_referenceModel, m_showIconViewAction, m_showListViewAction, m_stackTabWidget, m_undoStack, m_unsavedBinsCount, savePartAsBundled(), and Title.
~BinManager()
BinManager::~BinManager () virtual
Member Function Documentation
addBin()
void BinManager::addBin (PartsBinPaletteWidget * bin)
References PartsBinPaletteWidget::icon(), m_stackTabWidget, registerBin(), setAsCurrentBin(), and PartsBinPaletteWidget::title().
addNewPart()
void BinManager::addNewPart (ModelPart * modelPart)
References PartsBinPaletteWidget::addPart(), getOrOpenMyPartsBin(), and setDirtyTab().
addPartTo()
void BinManager::addPartTo (PartsBinPaletteWidget * bin, ModelPart * mp, bool setDirty)
References PartsBinPaletteWidget::addPart(), PartsBinPaletteWidget::contains(), ModelPart::moduleID(), and setDirtyTab().
addPartToBin()
void BinManager::addPartToBin (ModelPart * modelPart, int position = -1)
References addPartToBinAux(), getOrOpenMyPartsBin(), and m_currentBin.
addPartToBinAux()
void BinManager::addPartToBinAux (PartsBinPaletteWidget * bin, ModelPart * modelPart, int position = -1) protected
References PartsBinPaletteWidget::addPart(), PartsBinPaletteWidget::fastLoaded(), PartsBinPaletteWidget::fileName(), PartsBinPaletteWidget::load(), and setDirtyTab().
addToMyParts()
void BinManager::addToMyParts (ModelPart * modelPart)
References addPartToBinAux(), getOrOpenMyPartsBin(), and setAsCurrentTab().
addToTempPartsBin()
void BinManager::addToTempPartsBin (ModelPart * modelPart)
References addPartToBinAux(), getOrOpenBin(), m_tempPartsBinLocation, setAsCurrentTab(), PartsBinPaletteWidget::setDirty(), and TempPartsBinTemplateLocation.
beforeClosing()
bool BinManager::beforeClosing ()
References PartsBinPaletteWidget::beforeClosing(), PartsBinPaletteWidget::fastLoaded(), m_stackTabWidget, saveStateAndGeometry(), and setAsCurrentTab().
binContextMenu()
QMenu * BinManager::binContextMenu (PartsBinPaletteWidget * bin)
References m_binContextMenu, and updateBinCombinedMenu().
closeBin
void BinManager::closeBin () protected slot
References closeBinIn().
closeBinIn()
void BinManager::closeBinIn (int index)
References PartsBinPaletteWidget::beforeClosing(), PartsBinPaletteWidget::fileName(), getBin(), m_openedBins, and m_stackTabWidget.
combinedMenu() [1/2]
QMenu * BinManager::combinedMenu (PartsBinPaletteWidget * bin)
References m_combinedMenu, and updateBinCombinedMenu().
combinedMenu() [2/2]
QMenu * BinManager::combinedMenu ()
References m_combinedMenu.
connectTabWidget()
void BinManager::connectTabWidget () protected
References currentChanged(), m_stackTabWidget, and tabCloseRequested().
copyAllToSketch
void BinManager::copyAllToSketch () protected slot
References MainWindow::addToSketch(), and m_mainWindow.
copyFilesToContrib()
void BinManager::copyFilesToContrib (ModelPart * mp, QWidget * originator)
References ViewLayer::BreadboardView, PartsBinPaletteWidget::fileName(), FolderUtils::getUserPartsPath(), ModelPart::hasBaseNameFor(), ViewLayer::IconView, m_tempPartsBinLocation, ModelPart::path(), ViewLayer::PCBView, ViewLayer::SchematicView, and FolderUtils::slamCopy().
copyToSketch
void BinManager::copyToSketch () protected slot
References MainWindow::addToSketch(), currentBin(), PartsBinPaletteWidget::getAllParts(), and m_mainWindow.
createCombinedMenu()
void BinManager::createCombinedMenu () protected
References closeBin(), copyAllToSketch(), copyToSketch(), deleteBin(), editSelectedNew(), exportSelected(), findSelected(), m_closeBinAction, m_combinedMenu, m_copyAllToSketchAction, m_copyToSketchAction, m_deleteBinAction, m_editPartNewAction, m_exportPartAction, m_findPartAction, m_newBinAction, m_openAction, m_removePartAction, m_renameBinAction, m_saveBinAction, m_saveBinAsAction, m_saveBinAsBundledAction, m_showIconViewAction, m_showListViewAction, mainLoad(), newBinIn(), removeSelected(), renameBin(), saveBin(), saveBinAs(), saveBundledBin(), toIconView(), toListView(), and updateBinCombinedMenuCurrent().
createContextMenus()
void BinManager::createContextMenus () protected
References m_binContextMenu, m_closeBinAction, m_deleteBinAction, m_editPartNewAction, m_exportPartAction, m_findPartAction, m_partContextMenu, m_removePartAction, m_renameBinAction, m_saveBinAction, m_saveBinAsAction, and m_saveBinAsBundledAction.
createIfBinNotExists()
QString BinManager::createIfBinNotExists (const QString & dest, const QString & source)
References FolderUtils::slamCopy().
createIfMyPartsNotExists()
QString BinManager::createIfMyPartsNotExists ()
References createIfBinNotExists(), MyPartsBinLocation, and MyPartsBinTemplateLocation.
createIfSearchNotExists()
QString BinManager::createIfSearchNotExists ()
References createIfBinNotExists(), SearchBinLocation, and SearchBinTemplateLocation.
createMenu()
void BinManager::createMenu () protected
currentBin()
PartsBinPaletteWidget * BinManager::currentBin () protected
References m_stackTabWidget.
currentChanged
void BinManager::currentChanged (int index) protected slot
References getBin(), PartsBinPaletteWidget::hasMonoIcon(), PartsBinPaletteWidget::icon(), m_stackTabWidget, PartsBinPaletteWidget::monoIcon(), and setAsCurrentBin().
currentViewIsIconView()
bool BinManager::currentViewIsIconView ()
References currentBin(), and PartsBinPaletteWidget::currentViewIsIconView().
deleteBin
void BinManager::deleteBin () protected slot
References closeBinIn(), currentBin(), PartsBinPaletteWidget::fileName(), and PartsBinPaletteWidget::title().
editSelectedNew
void BinManager::editSelectedNew () protected slot
References currentBin(), and editSelectedPartNewFrom().
editSelectedPartNewFrom()
void BinManager::editSelectedPartNewFrom (PartsBinPaletteWidget * bin)
References MainWindow::getPartsEditorNewAnd(), m_mainWindow, and PartsBinPaletteWidget::selectedItemBase().
exportSelected
void BinManager::exportSelected () protected slot
References currentBin(), ModelPart::moduleID(), savePartAsBundled(), and PartsBinPaletteWidget::selectedModelPart().
findAllBins()
void BinManager::findAllBins (QList< BinLocation * > & actualLocations) protected
References BinLocation::App, ContribPartsBinLocation, CorePartsBinLocation, findBins(), FolderUtils::getAppPartsSubFolderPath(), getBinTitle(), FolderUtils::getUserBinsPath(), BinLocation::location, BinLocation::More, BinLocation::path, BinLocation::title, and BinLocation::User.
findBin()
PartsBinPaletteWidget * BinManager::findBin (const QString & binLocation) protected
References PartsBinPaletteWidget::fileName(), and m_stackTabWidget.
findBins()
void BinManager::findBins (QDir & dir, QList< BinLocation * > & actualLocations, BinLocation::Location loc) protected
References FritzingBinExtension(), getBinTitle(), BinLocation::location, BinLocation::path, and BinLocation::title.
findSelected
void BinManager::findSelected () protected slot
References currentBin(), m_mainWindow, PartsBinPaletteWidget::selectedModelPart(), and MainWindow::selectPartsWithModuleID().
getBin()
PartsBinPaletteWidget * BinManager::getBin (int index) protected
References m_stackTabWidget.
getBinTitle()
bool BinManager::getBinTitle (const QString & filename, QString & binTitle, QString & binIcon) static
getOrOpenBin()
PartsBinPaletteWidget * BinManager::getOrOpenBin (const QString & dest, const QString & source) protected
References createIfBinNotExists(), PartsBinPaletteWidget::fastLoaded(), PartsBinPaletteWidget::fileName(), findBin(), PartsBinPaletteWidget::load(), and openBinIn().
getOrOpenMyPartsBin()
PartsBinPaletteWidget * BinManager::getOrOpenMyPartsBin () protected
References getOrOpenBin(), MyPartsBinLocation, and MyPartsBinTemplateLocation.
getOrOpenSearchBin()
PartsBinPaletteWidget * BinManager::getOrOpenSearchBin () protected
References getOrOpenBin(), SearchBinLocation, SearchBinTemplateLocation, and PartsBinPaletteWidget::setSaveQuietly().
getSelectedModuleIDFromSketch()
const QString & BinManager::getSelectedModuleIDFromSketch ()
References m_mainWindow, and MainWindow::selectedModuleID().
hackLocalContrib()
void BinManager::hackLocalContrib (QList< BinLocation * > & locations) protected
References createIfBinNotExists(), DebugDialog::debug(), getBinTitle(), BinLocation::location, MyPartsBinLocation, MyPartsBinTemplateLocation, BinLocation::path, BinLocation::title, BinLocation::User, and TextUtils::writeUtf8().
hasAlienParts()
bool BinManager::hasAlienParts ()
hideTabBar()
void BinManager::hideTabBar ()
References m_stackTabWidget, and StackTabWidget::stackTabBar().
hideTempPartsBin()
void BinManager::hideTempPartsBin ()
References PartsBinPaletteWidget::fileName(), m_stackTabWidget, and m_tempPartsBinLocation.
importPart()
void BinManager::importPart (const QString & filename, PartsBinPaletteWidget * bin) protected
References addPartTo(), PartsBinPaletteWidget::allowsChanges(), MainWindow::loadBundledPart(), and m_mainWindow.
importPartToCurrentBin()
void BinManager::importPartToCurrentBin (const QString & filename)
References currentBin(), and importPart().
importPartToMineBin()
void BinManager::importPartToMineBin (const QString & filename)
References getOrOpenBin(), importPart(), MyPartsBinLocation, MyPartsBinTemplateLocation, and setAsCurrentTab().
initNames()
void BinManager::initNames () static
References ContribPartsBinLocation, CorePartsBinLocation, FolderUtils::getAppPartsSubFolderPath(), FolderUtils::getUserBinsPath(), MyPartsBinLocation, MyPartsBinTemplateLocation, SearchBinLocation, SearchBinTemplateLocation, StandardBinIcons, and TempPartsBinTemplateLocation.
initStandardBins()
void BinManager::initStandardBins ()
References connectTabWidget(), createCombinedMenu(), createContextMenus(), currentChanged(), MainWindow::fileProgressDialog(), findAllBins(), hackLocalContrib(), PartsBinPaletteWidget::icon(), PartsBinPaletteWidget::load(), m_mainWindow, m_stackTabWidget, newBin(), openCoreBinIn(), BinLocation::path, registerBin(), restoreStateAndGeometry(), StackTabWidget::stackTabBar(), and PartsBinPaletteWidget::title().
insertBin()
void BinManager::insertBin (PartsBinPaletteWidget * bin, int index)
References PartsBinPaletteWidget::icon(), m_stackTabWidget, registerBin(), and PartsBinPaletteWidget::title().
isTabReorderingEvent()
bool BinManager::isTabReorderingEvent (QDropEvent * event) static
isTempPartsBin()
bool BinManager::isTempPartsBin (PartsBinPaletteWidget * bin)
References PartsBinPaletteWidget::fileName(), and m_tempPartsBinLocation.
load()
void BinManager::load (const QString & filename)
References openBin().
mainLoad
void BinManager::mainLoad () protected slot
References FritzingBinExtension(), FritzingBundledBinExtension(), FritzingBundledPartExtension(), FolderUtils::getOpenFileName(), importPartToCurrentBin(), m_defaultSaveFolder, and openBinIn().
mainWindow()
MainWindow * BinManager::mainWindow ()
References m_mainWindow.
newBin()
PartsBinPaletteWidget * BinManager::newBin () protected
References m_infoView, m_mainWindow, m_referenceModel, m_undoStack, setAsCurrentBin(), and updateFileName().
newBinIn
PartsBinPaletteWidget * BinManager::newBinIn () protected slot
References insertBin(), m_stackTabWidget, m_unsavedBinsCount, newBin(), renameBin(), PartsBinPaletteWidget::setPaletteModel(), PartsBinPaletteWidget::setReadOnly(), and PartsBinPaletteWidget::setTitle().
openBin()
void BinManager::openBin (const QString & fileName)
References openBinIn().
openBinIn()
PartsBinPaletteWidget * BinManager::openBinIn (QString fileName, bool fastLoad)
References FritzingBinExtension(), FritzingBundledBinExtension(), insertBin(), m_defaultSaveFolder, m_openedBins, m_stackTabWidget, newBin(), PartsBinPaletteWidget::open(), setAsCurrentBin(), and setDirtyTab().
openCoreBinIn()
PartsBinPaletteWidget * BinManager::openCoreBinIn ()
References CorePartsBinLocation, findBin(), insertBin(), PartsBinPaletteWidget::load(), newBin(), PartsBinPaletteWidget::setAllowsChanges(), setAsCurrentBin(), and setAsCurrentTab().
openedBinsActions()
QList< QAction * > BinManager::openedBinsActions (const QString & moduleId)
References PartsBinPaletteWidget::addPartToMeAction(), PartsBinPaletteWidget::contains(), m_stackTabWidget, PartsBinPaletteWidget::readOnly(), and PartsBinPaletteWidget::title().
partContextMenu()
QMenu * BinManager::partContextMenu (PartsBinPaletteWidget * bin)
References m_partContextMenu, and updateBinCombinedMenu().
readTheoreticalLocations()
void BinManager::readTheoreticalLocations (QList< BinLocation * > & theoreticalLocations) protected
References DebugDialog::debug(), BinLocation::fromString(), BinLocation::location, and BinLocation::title.
registerBin()
void BinManager::registerBin (PartsBinPaletteWidget * bin) protected
References ContribPartsBinLocation, CorePartsBinLocation, PartsBinPaletteWidget::fileName(), FolderUtils::getAppPartsSubFolderPath(), m_openedBins, m_tempPartsBinLocation, SearchBinLocation, and PartsBinPaletteWidget::setAllowsChanges().
reloadPart()
void BinManager::reloadPart (const QString & moduleID)
References m_stackTabWidget, PartsBinPaletteWidget::reloadPart(), and PartsBinView::removePartReference().
removeSelected
bool BinManager::removeSelected () protected slot
References MainWindow::anyUsePart(), currentBin(), m_mainWindow, m_undoStack, ModelPart::moduleID(), ModelPart::path(), WaitPushUndoStack::push(), PartsBinPaletteWidget::removePart(), PartsBinPaletteWidget::selectedModelPart(), PartsBinPaletteWidget::setDirty(), and ModelPart::title().
renameBin
void BinManager::renameBin () protected slot
References PartsBinPaletteWidget::addPartToMeAction(), currentBin(), m_stackTabWidget, PartsBinPaletteWidget::setTitle(), StackTabWidget::stackTabBar(), PartsBinPaletteWidget::title(), and updateTitle().
restoreStateAndGeometry()
void BinManager::restoreStateAndGeometry (QList< BinLocation * > & actualLocations) protected
References BinLocation::fromString(), BinLocation::location, BinLocation::marked, BinLocation::path, readTheoreticalLocations(), and BinLocation::title.
saveBin
void BinManager::saveBin () protected slot
References currentBin(), PartsBinPaletteWidget::save(), and setDirtyTab().
saveBinAs
void BinManager::saveBinAs () protected slot
References currentBin(), and PartsBinPaletteWidget::saveAs().
saveBundledBin
void BinManager::saveBundledBin () protected slot
References currentBin(), and PartsBinPaletteWidget::saveBundledBin().
savePartAsBundled
void BinManager::savePartAsBundled (const QString & moduleId) signal
saveStateAndGeometry()
void BinManager::saveStateAndGeometry () protected
References PartsBinPaletteWidget::fileName(), PartsBinPaletteWidget::location(), m_stackTabWidget, PartsBinPaletteWidget::title(), and BinLocation::toString().
search()
void BinManager::search (const QString & searchText)
References addPartTo(), getOrOpenSearchBin(), FileProgressDialog::incValue(), ModelPart::itemType(), m_referenceModel, ModelPart::moduleID(), PartFactory::OldSchematicPrefix, PartsBinPaletteWidget::removeParts(), ModelPart::SchematicSubpart, PaletteModel::search(), setDirtyTab(), and FileProgressDialog::setIncValueMod().
setAsCurrentBin
void BinManager::setAsCurrentBin (PartsBinPaletteWidget * bin) slot
References PartsBinPaletteWidget::fastLoaded(), PartsBinPaletteWidget::fileName(), PartsBinPaletteWidget::focusSearch(), PartsBinPaletteWidget::load(), m_currentBin, and SearchBinLocation.
setAsCurrentTab()
void BinManager::setAsCurrentTab (PartsBinPaletteWidget * bin) protected
References m_stackTabWidget.
setDirtyTab()
void BinManager::setDirtyTab (PartsBinPaletteWidget * w, bool dirty = true)
References m_stackTabWidget, and PartsBinPaletteWidget::title().
setInfoViewOnHover()
void BinManager::setInfoViewOnHover (bool infoViewOnHover)
setTabIcon()
void BinManager::setTabIcon (PartsBinPaletteWidget * w, QIcon * icon)
References m_stackTabWidget.
setTempPartsBinLocation()
void BinManager::setTempPartsBinLocation (const QString & filename)
References m_tempPartsBinLocation.
tabCloseRequested
void BinManager::tabCloseRequested (int index) protected slot
References closeBinIn().
toIconView
void BinManager::toIconView () slot
References currentBin(), and PartsBinPaletteWidget::toIconView().
toListView
void BinManager::toListView () slot
References currentBin(), and PartsBinPaletteWidget::toListView().
updateBinCombinedMenu()
void BinManager::updateBinCombinedMenu (PartsBinPaletteWidget * bin) protected
References PartsBinPaletteWidget::allowsChanges(), PartsBinPaletteWidget::canClose(), ItemBase::canEditPart(), ModelPart::isCore(), m_closeBinAction, m_combinedMenu, m_deleteBinAction, m_editPartNewAction, m_exportPartAction, m_findPartAction, m_removePartAction, m_renameBinAction, m_saveBinAction, ItemBase::modelPart(), and PartsBinPaletteWidget::selectedItemBase().
updateBinCombinedMenuCurrent
void BinManager::updateBinCombinedMenuCurrent () slot
References currentBin(), and updateBinCombinedMenu().
updateFileName
void BinManager::updateFileName (PartsBinPaletteWidget * bin, const QString & newFileName, const QString & oldFilename) protected slot
References m_openedBins.
updateTitle()
void BinManager::updateTitle (PartsBinPaletteWidget * w, const QString & newTitle)
References m_stackTabWidget, setDirtyTab(), and PartsBinPaletteWidget::title().
updateViewChecks()
void BinManager::updateViewChecks (bool iconView)
References m_showIconViewAction, and m_showListViewAction.
Member Data Documentation
ContribPartsBinLocation
QString BinManager::ContribPartsBinLocation static
CorePartsBinLocation
QString BinManager::CorePartsBinLocation static
CurrentBinStyle
QString BinManager::CurrentBinStyle = "background-color: black;" static protected
m_binContextMenu
QMenu* BinManager::m_binContextMenu protected
m_closeBinAction
QAction* BinManager::m_closeBinAction protected
m_combinedMenu
QMenu* BinManager::m_combinedMenu protected
m_copyAllToSketchAction
QAction* BinManager::m_copyAllToSketchAction protected
m_copyToSketchAction
QAction* BinManager::m_copyToSketchAction protected
m_currentBin
PartsBinPaletteWidget* BinManager::m_currentBin protected
m_defaultSaveFolder
QString BinManager::m_defaultSaveFolder protected
m_deleteBinAction
QAction* BinManager::m_deleteBinAction protected
m_editPartNewAction
QAction* BinManager::m_editPartNewAction protected
m_exportPartAction
QAction* BinManager::m_exportPartAction protected
m_findPartAction
QAction* BinManager::m_findPartAction protected
m_infoView
HtmlInfoView* BinManager::m_infoView protected
m_mainWindow
MainWindow* BinManager::m_mainWindow protected
m_newBinAction
QAction* BinManager::m_newBinAction protected
m_openAction
QAction* BinManager::m_openAction protected
m_openedBins
QHash<QString ,PartsBinPaletteWidget*> BinManager::m_openedBins protected
m_partContextMenu
QMenu* BinManager::m_partContextMenu protected
m_partMenu
QMenu* BinManager::m_partMenu protected
m_referenceModel
ReferenceModel* BinManager::m_referenceModel protected
m_removePartAction
QAction* BinManager::m_removePartAction protected
m_renameBinAction
QAction* BinManager::m_renameBinAction protected
m_saveBinAction
QAction* BinManager::m_saveBinAction protected
m_saveBinAsAction
QAction* BinManager::m_saveBinAsAction protected
m_saveBinAsBundledAction
QAction* BinManager::m_saveBinAsBundledAction protected
m_showIconViewAction
QAction* BinManager::m_showIconViewAction protected
m_showListViewAction
QAction* BinManager::m_showListViewAction protected
m_stackTabWidget
class StackTabWidget* BinManager::m_stackTabWidget protected
m_tempPartsBinLocation
QString BinManager::m_tempPartsBinLocation protected
m_undoStack
WaitPushUndoStack* BinManager::m_undoStack protected
m_unsavedBinsCount
int BinManager::m_unsavedBinsCount protected
MyPartsBinLocation
QString BinManager::MyPartsBinLocation static
MyPartsBinTemplateLocation
QString BinManager::MyPartsBinTemplateLocation static
SearchBinLocation
QString BinManager::SearchBinLocation static
SearchBinTemplateLocation
QString BinManager::SearchBinTemplateLocation static
StandardBinIcons
QHash< QString, QString > BinManager::StandardBinIcons static
StandardBinStyle
QString BinManager::StandardBinStyle = "background-color: gray;" static protected
TempPartsBinTemplateLocation
QString BinManager::TempPartsBinTemplateLocation static
Title
QString BinManager::Title static
The documentation for this class was generated from the following files:
partsbinpalette/binmanager/binmanager.h
partsbinpalette/binmanager/binmanager.cpp