Fritzing: PartsEditorMainWindow Class Reference
PartsEditorMainWindow Class Reference
#include <partseditormainwindow.h>
Public Slots
void parentAboutToClose ()
Signals
void alienPartUsed ()
void changeActivationSignal (bool activate, QWidget *originator)
void closed (long id)
void partUpdated (const QString &filename, long myId, bool connectorsChanged)
void saveButtonClicked ()
Signals inherited from FritzingWindow
void readOnlyChanged (bool isReadOnly)
Public Member Functions
PartsEditorMainWindow (QWidget *parent=0)
~PartsEditorMainWindow ()
bool save ()
void setup (long id, ModelPart *modelPart, bool fromTemplate, class ItemBase *fromItem)
void setViewItems (class ItemBase *, class ItemBase *, class ItemBase *, class ItemBase *)
const QDir & tempDir ()
bool validateMinRequirements ()
Public Member Functions inherited from FritzingWindow
FritzingWindow (const QString &untitledFileName, int &untitledFileCount, QString fileExt, QWidget *parent=0, Qt::WindowFlags f=0)
const QString & fileName ()
virtual void notClosableForAWhile ()
void setFileName (const QString &)
Public Member Functions inherited from Bundler
virtual ~Bundler ()
virtual bool loadBundledAux (QDir &dir, QList< class ModelPart * > mps)
virtual bool preloadBundledAux (QDir &dir, bool dontAsk)
Static Public Member Functions
static QGraphicsProxyWidget * emptyViewItem (QString iconFile, QString text="")
static void initText ()
Static Public Member Functions inherited from FritzingWindow
static bool alreadyHasExtension (const QString &fileName, const QString &extension=___emptyString___)
Static Public Attributes
static QString DescriptionFreshStartText
static QString FooterText
static QString LabelFreshStartText
static QString TagsFreshStartText
static QString TaxonomyFreshStartText
static const QString templatePath
static QString TitleFreshStartText
static int UntitledPartIndex = 1
static QString UntitledPartName
Static Public Attributes inherited from FritzingWindow
static const QString QtFunkyPlaceholder = QLatin1String("[*]")
static QString ReadOnlyPlaceholder
Protected Slots
void propertiesChanged ()
void updateDateAndAuthor ()
Protected Slots inherited from FritzingWindow
void undoStackCleanChanged (bool isClean)
Protected Member Functions
void cleanUp ()
void closeEvent (QCloseEvent *event)
void connectWidgetsToSave (const QList< QWidget * > &widgets)
void createCenter (ModelPart *=0, class ItemBase *fromItem=0)
void createFooter ()
void createHeader (ModelPart *=0)
ModelPartShared * createModelPartShared ()
const QDir & createTempFolderIfNecessary ()
const QString defaultSaveFolder ()
bool event (QEvent *)
bool eventFilter (QObject *object, QEvent *event)
const QString fileExtension ()
const QString fritzingTitle ()
QStringList getExtensions ()
QString getExtensionString ()
void makeNonCore ()
bool saveAs ()
bool saveAsAux (const QString &fileName)
int & untitledFileCount ()
const QString untitledFileName ()
void updateButtons ()
void updateSaveButton ()
bool wannaSaveAfterWarning (bool savingAsNew)
Protected Member Functions inherited from FritzingWindow
virtual bool anyModified ()
virtual bool beforeClosing (bool showCancel, bool &discard)
QMessageBox::StandardButton beforeClosingMessage (const QString &filename, bool showCancel)
void createCloseAction ()
bool save (const QString &filename, bool readOnly)
bool saveAs (const QString &filename, bool readOnly)
virtual void setBeforeClosingText (const QString &filename, QMessageBox &messageBox)
void setReadOnly (bool readOnly)
virtual void setTitle ()
Protected Attributes
QPointer< EditableLineWidget > m_author
QPointer< class ItemBase > m_breadboardItem
QPointer< QPushButton > m_cancelCloseButton
QPointer< QFrame > m_centerFrame
QPointer< ConnectorsInfoWidget > m_connsInfo
QPointer< QLabel > m_createdByText
QPointer< class EditableDateWidget > m_createdOn
QPointer< class EditableTextWidget > m_description
bool m_editingAlien
QPointer< QFrame > m_footerFrame
QPointer< QFrame > m_headerFrame
QPointer< class ItemBase > m_iconItem
QPointer< class PartsEditorView > m_iconViewImage
long m_id
QPointer< EditableLineWidget > m_label
QPointer< QFrame > m_mainFrame
QString m_moduleId
QPointer< class PaletteModel > m_paletteModel
bool m_partUpdated
QPointer< class ItemBase > m_pcbItem
QPointer< class HashPopulateWidget > m_properties
QPointer< QPushButton > m_saveAsNewPartButton
QPointer< QPushButton > m_saveButton
bool m_savedAsNewPart
QPointer< class ItemBase > m_schematicItem
QPointer< class SketchModel > m_sketchModel
QPointer< QTabWidget > m_tabWidget
QPointer< EditableLineWidget > m_tags
QPointer< EditableLineWidget > m_title
bool m_updateEnabled
QString m_uri
QString m_version
QPointer< class PartsEditorViewsWidget > m_views
Protected Attributes inherited from FritzingWindow
QAction * m_closeAct = nullptr
QString m_fwFilename
bool m_readOnly = false
QStatusBar * m_statusBar = nullptr
QDir m_tempDir
class WaitPushUndoStack * m_undoStack = nullptr
Static Protected Attributes
static QString ___partsEditorName___
static bool m_closeAfterSaving = true
static int m_closedBeforeCount = 0
static QPointer< PartsEditorMainWindow > m_lastOpened = NULL
Static Protected Attributes inherited from FritzingWindow
static QStringList OtherKnownExtensions
Constructor & Destructor Documentation
PartsEditorMainWindow()
PartsEditorMainWindow::PartsEditorMainWindow (QWidget * parent = 0)
References m_breadboardItem, m_editingAlien, m_iconItem, m_pcbItem, and m_schematicItem.
~PartsEditorMainWindow()
PartsEditorMainWindow::~PartsEditorMainWindow ()
References m_iconItem, m_paletteModel, and m_sketchModel.
Member Function Documentation
alienPartUsed
void PartsEditorMainWindow::alienPartUsed () signal
changeActivationSignal
void PartsEditorMainWindow::changeActivationSignal (bool activate, QWidget * originator) signal
cleanUp()
void PartsEditorMainWindow::cleanUp () protected
References m_closedBeforeCount, FritzingWindow::m_fwFilename, m_lastOpened, FritzingWindow::m_tempDir, FolderUtils::rmdir(), untitledFileName(), and UntitledPartIndex.
closed
void PartsEditorMainWindow::closed (long id) signal
closeEvent()
void PartsEditorMainWindow::closeEvent (QCloseEvent * event) protected
References FritzingWindow::beforeClosing(), cleanUp(), closed(), event(), m_connsInfo, FritzingWindow::m_fwFilename, m_id, m_partUpdated, m_savedAsNewPart, m_views, and partUpdated().
connectWidgetsToSave()
void PartsEditorMainWindow::connectWidgetsToSave (const QList< QWidget * > & widgets) protected
References m_saveAsNewPartButton, and saveButtonClicked().
createCenter()
void PartsEditorMainWindow::createCenter (ModelPart * modelPart = 0, class ItemBase * fromItem = 0) protected
References ModelPart::author(), ModelPart::date(), ModelPart::description(), DescriptionFreshStartText, FooterText, getenvUser, ModelPart::label(), LabelFreshStartText, m_author, m_centerFrame, m_connsInfo, m_createdByText, m_createdOn, m_description, m_label, m_moduleId, m_properties, m_sketchModel, m_tabWidget, m_tags, FritzingWindow::m_undoStack, m_uri, m_version, m_views, ModelPart::moduleID(), ModelPart::properties(), propertiesChanged(), ModelPart::tags(), TagsFreshStartText, updateDateAndAuthor(), ModelPart::uri(), and ModelPart::version().
createFooter()
void PartsEditorMainWindow::createFooter () protected
References connectWidgetsToSave(), m_author, m_cancelCloseButton, m_connsInfo, m_createdOn, m_description, m_footerFrame, m_label, m_saveAsNewPartButton, m_saveButton, m_tags, m_title, save(), saveAs(), and updateSaveButton().
createHeader()
void PartsEditorMainWindow::createHeader (ModelPart * modelPart = 0) protected
References ___emptyString___, createTempFolderIfNecessary(), emptyViewItem(), ViewLayer::Icon, ViewLayer::IconView, m_headerFrame, m_iconItem, m_iconViewImage, m_paletteModel, m_sketchModel, m_title, FritzingWindow::m_undoStack, ModelPart::title(), and TitleFreshStartText.
createModelPartShared()
ModelPartShared * PartsEditorMainWindow::createModelPartShared () protected
References m_author, m_connsInfo, m_createdOn, m_description, m_iconViewImage, m_label, m_moduleId, m_properties, m_tags, m_title, m_uri, m_version, m_views, ModelPartShared::setAuthor(), ModelPartShared::setConnectorsShared(), ModelPartShared::setDate(), ModelPartShared::setDescription(), ModelPartShared::setLabel(), ModelPartShared::setModuleID(), ModelPartShared::setProperties(), ModelPartShared::setTags(), ModelPartShared::setTitle(), ModelPartShared::setUri(), and ModelPartShared::setVersion().
createTempFolderIfNecessary()
const QDir & PartsEditorMainWindow::createTempFolderIfNecessary () protected
References FritzingWindow::m_tempDir.
defaultSaveFolder()
const QString PartsEditorMainWindow::defaultSaveFolder () protected virtual
Implements FritzingWindow.
emptyViewItem()
QGraphicsProxyWidget * PartsEditorMainWindow::emptyViewItem (QString iconFile, QString text = "") static
event()
bool PartsEditorMainWindow::event (QEvent * e) protected
References changeActivationSignal().
eventFilter()
bool PartsEditorMainWindow::eventFilter (QObject * object, QEvent * event) protected
References event(), FritzingWindow::notClosableForAWhile(), and ProcessEventBlocker::processEvents().
fileExtension()
const QString PartsEditorMainWindow::fileExtension () protected virtual
Implements FritzingWindow.
References FritzingPartExtension().
fritzingTitle()
const QString PartsEditorMainWindow::fritzingTitle () protected virtual
Reimplemented from FritzingWindow.
References ___partsEditorName___, and FritzingWindow::fritzingTitle().
getExtensions()
QStringList PartsEditorMainWindow::getExtensions () protected virtual
Implements FritzingWindow.
References fileExtension().
getExtensionString()
QString PartsEditorMainWindow::getExtensionString () protected virtual
Implements FritzingWindow.
References fileExtension().
initText()
void PartsEditorMainWindow::initText () static
References ___partsEditorName___, DescriptionFreshStartText, FooterText, LabelFreshStartText, TagsFreshStartText, TaxonomyFreshStartText, TitleFreshStartText, and UntitledPartName.
makeNonCore()
void PartsEditorMainWindow::makeNonCore () protected
References m_tags.
parentAboutToClose
void PartsEditorMainWindow::parentAboutToClose () slot
References FritzingWindow::beforeClosing(), and cleanUp().
partUpdated
void PartsEditorMainWindow::partUpdated (const QString & filename, long myId, bool connectorsChanged) signal
propertiesChanged
void PartsEditorMainWindow::propertiesChanged () protected slot
References FritzingWindow::m_undoStack, and WaitPushUndoStack::push().
save()
bool PartsEditorMainWindow::save () virtual
Reimplemented from FritzingWindow.
References m_cancelCloseButton, m_closeAfterSaving, m_saveButton, FritzingWindow::save(), saveAs(), validateMinRequirements(), and wannaSaveAfterWarning().
saveAs()
bool PartsEditorMainWindow::saveAs () protected virtual
Reimplemented from FritzingWindow.
References ___emptyString___, FritzingWindow::alreadyHasExtension(), FritzingPartExtension(), FolderUtils::isEmptyFileName(), m_closeAfterSaving, FritzingWindow::m_fwFilename, m_moduleId, m_savedAsNewPart, m_title, m_updateEnabled, makeNonCore(), saveAsAux(), untitledFileName(), updateButtons(), validateMinRequirements(), and wannaSaveAfterWarning().
saveAsAux()
bool PartsEditorMainWindow::saveAsAux (const QString & fileName) protected virtual
Implements FritzingWindow.
References alienPartUsed(), createModelPartShared(), FritzingWindow::fileName(), m_editingAlien, m_iconViewImage, m_partUpdated, m_sketchModel, FritzingWindow::m_undoStack, m_views, FritzingWindow::setFileName(), FritzingWindow::setTitle(), and updateDateAndAuthor().
saveButtonClicked
void PartsEditorMainWindow::saveButtonClicked () signal
setup()
void PartsEditorMainWindow::setup (long id, ModelPart * modelPart, bool fromTemplate, class ItemBase * fromItem)
References Connector::connectorLocalName(), ModelPart::connectors(), Connector::connectorSharedID(), CORE_EDITION_ENABLED, createCenter(), createFooter(), createHeader(), ModelPart::isAlien(), ModelPart::isContrib(), ModelPart::isCore(), ModelPart::localProp(), m_breadboardItem, m_centerFrame, m_editingAlien, m_footerFrame, FritzingWindow::m_fwFilename, m_headerFrame, m_id, m_lastOpened, m_mainFrame, m_paletteModel, m_partUpdated, m_pcbItem, m_savedAsNewPart, m_schematicItem, m_sketchModel, m_updateEnabled, m_views, ModelPart::modelPartShared(), ModelPart::path(), ModelPartShared::properties(), Connector::setConnectorLocalName(), FritzingWindow::setTitle(), and UntitledPartIndex.
setViewItems()
void PartsEditorMainWindow::setViewItems (class ItemBase * iiItem, class ItemBase * bbItem, class ItemBase * schemItem, class ItemBase * pcbItem)
References m_breadboardItem, m_iconItem, m_pcbItem, and m_schematicItem.
tempDir()
const QDir & PartsEditorMainWindow::tempDir ()
References createTempFolderIfNecessary().
untitledFileCount()
int & PartsEditorMainWindow::untitledFileCount () protected virtual
Implements FritzingWindow.
References UntitledPartIndex.
untitledFileName()
const QString PartsEditorMainWindow::untitledFileName () protected virtual
Implements FritzingWindow.
References UntitledPartName.
updateButtons()
void PartsEditorMainWindow::updateButtons () protected
References m_cancelCloseButton, and m_saveAsNewPartButton.
updateDateAndAuthor
void PartsEditorMainWindow::updateDateAndAuthor () protected slot
References FooterText, m_author, m_createdByText, and m_createdOn.
updateSaveButton()
void PartsEditorMainWindow::updateSaveButton () protected
References m_saveButton, and m_updateEnabled.
validateMinRequirements()
bool PartsEditorMainWindow::validateMinRequirements ()
References m_iconViewImage.
wannaSaveAfterWarning()
bool PartsEditorMainWindow::wannaSaveAfterWarning (bool savingAsNew) protected
References m_connsInfo, m_savedAsNewPart, and saveButtonClicked().
Member Data Documentation
___partsEditorName___
QString PartsEditorMainWindow::___partsEditorName___ static protected
DescriptionFreshStartText
QString PartsEditorMainWindow::DescriptionFreshStartText static
FooterText
QString PartsEditorMainWindow::FooterText static
LabelFreshStartText
QString PartsEditorMainWindow::LabelFreshStartText static
m_author
QPointer<EditableLineWidget> PartsEditorMainWindow::m_author protected
m_breadboardItem
QPointer<class ItemBase> PartsEditorMainWindow::m_breadboardItem protected
m_cancelCloseButton
QPointer<QPushButton> PartsEditorMainWindow::m_cancelCloseButton protected
m_centerFrame
QPointer<QFrame> PartsEditorMainWindow::m_centerFrame protected
m_closeAfterSaving
bool PartsEditorMainWindow::m_closeAfterSaving = true static protected
m_closedBeforeCount
int PartsEditorMainWindow::m_closedBeforeCount = 0 static protected
m_connsInfo
QPointer<ConnectorsInfoWidget> PartsEditorMainWindow::m_connsInfo protected
m_createdByText
QPointer<QLabel> PartsEditorMainWindow::m_createdByText protected
m_createdOn
QPointer<class EditableDateWidget> PartsEditorMainWindow::m_createdOn protected
m_description
QPointer<class EditableTextWidget> PartsEditorMainWindow::m_description protected
m_editingAlien
bool PartsEditorMainWindow::m_editingAlien protected
m_footerFrame
QPointer<QFrame> PartsEditorMainWindow::m_footerFrame protected
m_headerFrame
QPointer<QFrame> PartsEditorMainWindow::m_headerFrame protected
m_iconItem
QPointer<class ItemBase> PartsEditorMainWindow::m_iconItem protected
m_iconViewImage
QPointer<class PartsEditorView> PartsEditorMainWindow::m_iconViewImage protected
m_id
long PartsEditorMainWindow::m_id protected
m_label
QPointer<EditableLineWidget> PartsEditorMainWindow::m_label protected
m_lastOpened
QPointer< PartsEditorMainWindow > PartsEditorMainWindow::m_lastOpened = NULL static protected
m_mainFrame
QPointer<QFrame> PartsEditorMainWindow::m_mainFrame protected
m_moduleId
QString PartsEditorMainWindow::m_moduleId protected
m_paletteModel
QPointer<class PaletteModel> PartsEditorMainWindow::m_paletteModel protected
m_partUpdated
bool PartsEditorMainWindow::m_partUpdated protected
m_pcbItem
QPointer<class ItemBase> PartsEditorMainWindow::m_pcbItem protected
m_properties
QPointer<class HashPopulateWidget> PartsEditorMainWindow::m_properties protected
m_saveAsNewPartButton
QPointer<QPushButton> PartsEditorMainWindow::m_saveAsNewPartButton protected
m_saveButton
QPointer<QPushButton> PartsEditorMainWindow::m_saveButton protected
m_savedAsNewPart
bool PartsEditorMainWindow::m_savedAsNewPart protected
m_schematicItem
QPointer<class ItemBase> PartsEditorMainWindow::m_schematicItem protected
m_sketchModel
QPointer<class SketchModel> PartsEditorMainWindow::m_sketchModel protected
m_tabWidget
QPointer<QTabWidget> PartsEditorMainWindow::m_tabWidget protected
m_tags
QPointer<EditableLineWidget> PartsEditorMainWindow::m_tags protected
m_title
QPointer<EditableLineWidget> PartsEditorMainWindow::m_title protected
m_updateEnabled
bool PartsEditorMainWindow::m_updateEnabled protected
m_uri
QString PartsEditorMainWindow::m_uri protected
m_version
QString PartsEditorMainWindow::m_version protected
m_views
QPointer<class PartsEditorViewsWidget> PartsEditorMainWindow::m_views protected
TagsFreshStartText
QString PartsEditorMainWindow::TagsFreshStartText static
TaxonomyFreshStartText
QString PartsEditorMainWindow::TaxonomyFreshStartText static
templatePath
const QString PartsEditorMainWindow::templatePath static
TitleFreshStartText
QString PartsEditorMainWindow::TitleFreshStartText static
UntitledPartIndex
int PartsEditorMainWindow::UntitledPartIndex = 1 static
UntitledPartName
QString PartsEditorMainWindow::UntitledPartName static
The documentation for this class was generated from the following files:
partseditor/obsolete/partseditormainwindow.h
partseditor/obsolete/partseditormainwindow.cpp