Fritzing: GroundFillSeedCommand Class Reference
GroundFillSeedCommand Class Reference
#include <commands.h>
Public Member Functions
GroundFillSeedCommand (class SketchWidget *sketchWidget, QUndoCommand *parent)
void addItem (long id, const QString &connectorID, bool seed)
void redo ()
void undo ()
Public Member Functions inherited from BaseCommand
BaseCommand (BaseCommand::CrossViewType, SketchWidget *, QUndoCommand *parent)
~BaseCommand ()
void addSubCommand (BaseCommand *subCommand)
BaseCommand::CrossViewType crossViewType () const noexcept
virtual QString getDebugString () const
int index () const
const QUndoCommand * parentCommand () const
void redo ()
void setCrossViewType (BaseCommand::CrossViewType)
void setRedoOnly ()
void setSkipFirstRedo ()
void setUndoOnly ()
SketchWidget * sketchWidget () const
const BaseCommand * subCommand (int index) const
int subCommandCount () const
void subRedo ()
void subRedo (int index)
void subUndo ()
void subUndo (int index)
void undo ()
Protected Member Functions
QString getParamString () const
Protected Attributes
QList< GFSThing > m_items
Protected Attributes inherited from BaseCommand
QList< BaseCommand * > m_commands
BaseCommand::CrossViewType m_crossViewType
int m_index = 0
QUndoCommand * m_parentCommand = nullptr
bool m_redoOnly = false
SketchWidget * m_sketchWidget = nullptr
bool m_skipFirstRedo = false
bool m_undoOnly = false
Additional Inherited Members
Public Types inherited from BaseCommand
enum CrossViewType { SingleView, CrossView }
Static Public Member Functions inherited from BaseCommand
static void clearProgress ()
static CommandProgress * initProgress ()
static int totalChildCount (const QUndoCommand *)
Static Protected Attributes inherited from BaseCommand
static CommandProgress m_commandProgress
static int nextIndex = 0
Constructor & Destructor Documentation
GroundFillSeedCommand()
GroundFillSeedCommand::GroundFillSeedCommand (class SketchWidget * sketchWidget, QUndoCommand * parent)
Member Function Documentation
addItem()
void GroundFillSeedCommand::addItem (long id, const QString & connectorID, bool seed)
References GFSThing::connectorID, GFSThing::id, m_items, and GFSThing::seed.
getParamString()
QString GroundFillSeedCommand::getParamString () const protected virtual
Reimplemented from BaseCommand.
References BaseCommand::getParamString(), and m_items.
redo()
void GroundFillSeedCommand::redo ()
References GFSThing::connectorID, GFSThing::id, m_items, BaseCommand::m_sketchWidget, BaseCommand::redo(), GFSThing::seed, and SketchWidget::setGroundFillSeed().
undo()
void GroundFillSeedCommand::undo ()
References GFSThing::connectorID, GFSThing::id, m_items, BaseCommand::m_sketchWidget, GFSThing::seed, SketchWidget::setGroundFillSeed(), and BaseCommand::undo().
Member Data Documentation
m_items
QList<GFSThing> GroundFillSeedCommand::m_items protected
The documentation for this class was generated from the following files:
commands.h
commands.cpp