Fritzing: AddSubpartCommand Class Reference
AddSubpartCommand Class Reference
#include <commands.h>
Public Member Functions
AddSubpartCommand (class SketchWidget *sketchWidget, CrossViewType crossView, long id, long subpartID, QUndoCommand *parent)
void redo ()
void undo ()
Public Member Functions inherited from BaseCommand
BaseCommand (BaseCommand::CrossViewType, SketchWidget *, QUndoCommand *parent)
~BaseCommand ()
void addSubCommand (BaseCommand *subCommand)
BaseCommand::CrossViewType crossViewType () const noexcept
virtual QString getDebugString () const
int index () const
const QUndoCommand * parentCommand () const
void redo ()
void setCrossViewType (BaseCommand::CrossViewType)
void setRedoOnly ()
void setSkipFirstRedo ()
void setUndoOnly ()
SketchWidget * sketchWidget () const
const BaseCommand * subCommand (int index) const
int subCommandCount () const
void subRedo ()
void subRedo (int index)
void subUndo ()
void subUndo (int index)
void undo ()
Protected Member Functions
QString getParamString () const
Protected Attributes
long m_itemID
long m_subpartItemID
Protected Attributes inherited from BaseCommand
QList< BaseCommand * > m_commands
BaseCommand::CrossViewType m_crossViewType
int m_index = 0
QUndoCommand * m_parentCommand = nullptr
bool m_redoOnly = false
SketchWidget * m_sketchWidget = nullptr
bool m_skipFirstRedo = false
bool m_undoOnly = false
Additional Inherited Members
Public Types inherited from BaseCommand
enum CrossViewType { SingleView, CrossView }
Static Public Member Functions inherited from BaseCommand
static void clearProgress ()
static CommandProgress * initProgress ()
static int totalChildCount (const QUndoCommand *)
Static Protected Attributes inherited from BaseCommand
static CommandProgress m_commandProgress
static int nextIndex = 0
Constructor & Destructor Documentation
AddSubpartCommand()
AddSubpartCommand::AddSubpartCommand (class SketchWidget * sketchWidget, CrossViewType crossView, long id, long subpartID, QUndoCommand * parent)
Member Function Documentation
getParamString()
QString AddSubpartCommand::getParamString () const protected virtual
Reimplemented from BaseCommand.
References BaseCommand::getParamString(), m_itemID, and m_subpartItemID.
redo()
void AddSubpartCommand::redo ()
References SketchWidget::addSubpart(), m_itemID, BaseCommand::m_sketchWidget, m_subpartItemID, BaseCommand::m_undoOnly, and BaseCommand::redo().
undo()
void AddSubpartCommand::undo ()
References SketchWidget::addSubpart(), m_itemID, BaseCommand::m_redoOnly, BaseCommand::m_sketchWidget, m_subpartItemID, and BaseCommand::undo().
Member Data Documentation
m_itemID
long AddSubpartCommand::m_itemID protected
m_subpartItemID
long AddSubpartCommand::m_subpartItemID protected
The documentation for this class was generated from the following files:
commands.h
commands.cpp