Fritzing: PESvgView Class Reference
PESvgView Class Reference
#include <pesvgview.h>
Public Member Functions
PESvgView (QWidget *parent=NULL)
~PESvgView ()
void highlightElement (class PEGraphicsItem *)
void setChildrenVisible (bool vis)
void setFilename (const QString &)
Protected Attributes
QLabel * m_filename
QLabel * m_height
class PEGraphicsItem * m_pegi
QLabel * m_svgElement
QLabel * m_units
QLabel * m_width
QLabel * m_x
QLabel * m_y
Constructor & Destructor Documentation
PESvgView()
PESvgView::PESvgView (QWidget * parent = NULL)
References m_filename, m_height, m_pegi, m_svgElement, m_units, m_width, m_x, m_y, and PEUtils::Spacing.
~PESvgView()
PESvgView::~PESvgView ()
Member Function Documentation
highlightElement()
void PESvgView::highlightElement (class PEGraphicsItem * pegi)
References PEUtils::convertUnitsStr(), PEGraphicsItem::element(), TextUtils::killXMLNS(), m_height, m_pegi, m_svgElement, m_units, m_width, m_x, m_y, PEGraphicsItem::offset(), and PEUtils::Units.
setChildrenVisible()
void PESvgView::setChildrenVisible (bool vis)
setFilename()
void PESvgView::setFilename (const QString & filename)
References m_filename.
Member Data Documentation
m_filename
QLabel* PESvgView::m_filename protected
m_height
QLabel* PESvgView::m_height protected
m_pegi
class PEGraphicsItem* PESvgView::m_pegi protected
m_svgElement
QLabel* PESvgView::m_svgElement protected
m_units
QLabel* PESvgView::m_units protected
m_width
QLabel* PESvgView::m_width protected
m_x
QLabel* PESvgView::m_x protected
m_y
QLabel* PESvgView::m_y protected
The documentation for this class was generated from the following files:
partseditor/pesvgview.h
partseditor/pesvgview.cpp