Fritzing: FirstTimeHelpDialog Class Reference
FirstTimeHelpDialog Class Reference
#include <firsttimehelpdialog.h>
Static Public Member Functions
static void cleanup ()
static void hideFirstTimeHelp ()
static void setViewID (ViewLayer::ViewID)
static void showFirstTimeHelp ()
Static Protected Member Functions
static void init ()
Protected Attributes
QLabel * m_label
Private Member Functions
FirstTimeHelpDialog (QWidget *parent=0)
~FirstTimeHelpDialog ()
Constructor & Destructor Documentation
FirstTimeHelpDialog()
FirstTimeHelpDialog::FirstTimeHelpDialog (QWidget * parent = 0) private
References m_label.
~FirstTimeHelpDialog()
FirstTimeHelpDialog::~FirstTimeHelpDialog () private
Member Function Documentation
cleanup()
void FirstTimeHelpDialog::cleanup () static
References Singleton.
hideFirstTimeHelp()
void FirstTimeHelpDialog::hideFirstTimeHelp () static
References init(), and Singleton.
init()
void FirstTimeHelpDialog::init () static protected
References ViewLayer::BreadboardView, FirstTimeHelpDialog(), ViewLayer::PCBView, ViewLayer::SchematicView, Singleton, and TheTexts.
setViewID()
void FirstTimeHelpDialog::setViewID (ViewLayer::ViewID viewID) static
References m_label, Singleton, TheTexts, and TheViewID.
showFirstTimeHelp()
void FirstTimeHelpDialog::showFirstTimeHelp () static
References init(), m_label, Singleton, TheTexts, and TheViewID.
Member Data Documentation
m_label
QLabel* FirstTimeHelpDialog::m_label protected
The documentation for this class was generated from the following files:
help/firsttimehelpdialog.h
help/firsttimehelpdialog.cpp