Fritzing: SvgFileSplitter Class Reference
SvgFileSplitter Class Reference
#include <svgfilesplitter.h>
Public Member Functions
SvgFileSplitter ()=default
const QByteArray & byteArray () const noexcept
const QDomDocument & domDocument () const noexcept
QString elementString (const QString &elementID)
void gReplace (const QString &id)
void gWrap (const QHash< QString, QString > &attributes)
bool load (const QString *filename)
bool load (QFile *)
bool load (const QString &string)
bool normalize (double dpi, const QString &elementID, bool blackOnly, double &factor)
QPainterPath painterPath (double dpi, const QString &elementID)
virtual bool parsePath (const QString &data, const char *slot, PathUserData &, QObject *slotTarget, bool convertHV)
QString shift (double x, double y, const QString &elementID, bool shiftTransforms)
void shiftChild (QDomElement &element, double x, double y, bool shiftTransforms)
QVector< QVariant > simpleParsePath (const QString &data)
Parse content of path element d attribute into validated tokens.
bool split (const QString &filename, const QString &elementID)
bool splitString (QString &contents, const QString &elementID)
QString toString ()
Static Public Member Functions
static bool changeColors (const QString &svg, QString &toColor, QStringList &exceptions, QByteArray &)
static void changeColors (QDomElement &element, QString &toColor, QStringList &exceptions)
static bool changeStrokeWidth (const QString &svg, double delta, bool absolute, bool changeOpacity, QByteArray &)
static void changeStrokeWidth (QDomElement &element, double delta, bool absolute, bool changeOpacity)
static void fixColorRecurse (QDomElement &element, const QString &newColor, const QStringList &exceptions)
static void fixStyleAttributeRecurse (QDomElement &element)
static void forceStrokeWidth (QDomElement &element, double delta, const QString &stroke, bool recurse, bool fill)
static bool getSvgSizeAttributes (const QString &svg, QString &width, QString &height, QString &viewBox)
static QByteArray hideText (const QString &filename)
static QByteArray hideText2 (const QByteArray &svg)
static QString hideText3 (const QString &svg)
static QByteArray showText (const QString &filename, bool &hasText)
static QByteArray showText2 (const QByteArray &svg, bool &hasText)
static QString showText3 (const QString &svg, bool &hasText)
Protected Slots
void convertHVSlot (QChar command, bool relative, QList< double > &args, void *userData)
void normalizeCommandSlot (QChar command, bool relative, QList< double > &args, void *userData)
void painterPathCommandSlot (QChar command, bool relative, QList< double > &args, void *userData)
virtual void rotateCommandSlot (QChar, bool, QList< double > &, void *)
void shiftCommandSlot (QChar command, bool relative, QList< double > &args, void *userData)
Protected Member Functions
bool normalizeAttribute (QDomElement &element, const char *attributeName, double num, double denom)
void normalizeChild (QDomElement &childElement, double sNewWidth, double sNewHeight, double vbWidth, double vbHeight, bool blackOnly)
bool normalizeFontSize (QDomElement &element, const char *attributeName, double num, double denom)
void normalizeTranslation (QDomElement &element, double sNewWidth, double sNewHeight, double vbWidth, double vbHeight)
void painterPathChild (QDomElement &element, QPainterPath &ppath)
bool shiftTranslation (QDomElement &element, double x, double y)
void standardArgs (bool relative, bool starting, QList< double > &args, PathUserData *pathUserData)
Static Protected Member Functions
static void hideTextAux (QDomElement &parent, bool hideChildren)
static void setStrokeOrFill (QDomElement &element, bool doIt, const QString &color, bool force)
static bool shiftAttribute (QDomElement &element, const char *attributeName, double d)
static void showTextAux (QDomElement &parent, bool &hasText, bool root)
Protected Attributes
QByteArray m_byteArray
QDomDocument m_domDocument
Constructor & Destructor Documentation
SvgFileSplitter()
SvgFileSplitter::SvgFileSplitter () default
Member Function Documentation
byteArray()
const QByteArray& SvgFileSplitter::byteArray () const inline noexcept
References m_byteArray.
changeColors() [1/2]
bool SvgFileSplitter::changeColors (const QString & svg, QString & toColor, QStringList & exceptions, QByteArray & byteArray) static
References byteArray(), and domDocument().
changeColors() [2/2]
void SvgFileSplitter::changeColors (QDomElement & element, QString & toColor, QStringList & exceptions) static
References changeColors().
changeStrokeWidth() [1/2]
bool SvgFileSplitter::changeStrokeWidth (const QString & svg, double delta, bool absolute, bool changeOpacity, QByteArray & byteArray) static
References byteArray(), and domDocument().
changeStrokeWidth() [2/2]
void SvgFileSplitter::changeStrokeWidth (QDomElement & element, double delta, bool absolute, bool changeOpacity) static
References changeStrokeWidth().
convertHVSlot
void SvgFileSplitter::convertHVSlot (QChar command, bool relative, QList< double > & args, void * userData) protected slot
References appendPair(), SVGPathLexer::FakeClosePathChar, HVConvertData::path, HVConvertData::subX, HVConvertData::subY, HVConvertData::x, and HVConvertData::y.
domDocument()
const QDomDocument& SvgFileSplitter::domDocument () const inline noexcept
References m_domDocument.
elementString()
QString SvgFileSplitter::elementString (const QString & elementID)
References ___emptyString___, TextUtils::findElementWithAttribute(), and m_domDocument.
fixColorRecurse()
void SvgFileSplitter::fixColorRecurse (QDomElement & element, const QString & newColor, const QStringList & exceptions) static
References TextUtils::fixStyleAttribute(), and setStrokeOrFill().
fixStyleAttributeRecurse()
void SvgFileSplitter::fixStyleAttributeRecurse (QDomElement & element) static
References TextUtils::fixStyleAttribute().
forceStrokeWidth()
void SvgFileSplitter::forceStrokeWidth (QDomElement & element, double delta, const QString & stroke, bool recurse, bool fill) static
References qMax().
getSvgSizeAttributes()
bool SvgFileSplitter::getSvgSizeAttributes (const QString & svg, QString & width, QString & height, QString & viewBox) static
gReplace()
void SvgFileSplitter::gReplace (const QString & id)
References TextUtils::findElementWithAttribute(), and m_domDocument.
gWrap()
void SvgFileSplitter::gWrap (const QHash< QString, QString > & attributes)
References TextUtils::gWrap(), and m_domDocument.
hideText()
QByteArray SvgFileSplitter::hideText (const QString & filename) static
References hideTextAux(), and TextUtils::removeXMLEntities().
hideText2()
QByteArray SvgFileSplitter::hideText2 (const QByteArray & svg) static
References hideTextAux(), and TextUtils::removeXMLEntities().
hideText3()
QString SvgFileSplitter::hideText3 (const QString & svg) static
References hideTextAux(), and TextUtils::removeXMLEntities().
hideTextAux()
void SvgFileSplitter::hideTextAux (QDomElement & parent, bool hideChildren) static protected
load() [1/3]
bool SvgFileSplitter::load (const QString * filename)
load() [2/3]
bool SvgFileSplitter::load (QFile * file)
References m_domDocument.
load() [3/3]
bool SvgFileSplitter::load (const QString & string)
References m_domDocument.
normalize()
bool SvgFileSplitter::normalize (double dpi, const QString & elementID, bool blackOnly, double & factor)
References TextUtils::findElementWithAttribute(), TextUtils::getSvgSizes(), m_domDocument, and normalizeChild().
normalizeAttribute()
bool SvgFileSplitter::normalizeAttribute (QDomElement & element, const char * attributeName, double num, double denom) protected
References DebugDialog::debug().
normalizeChild()
void SvgFileSplitter::normalizeChild (QDomElement & childElement, double sNewWidth, double sNewHeight, double vbWidth, double vbHeight, bool blackOnly) protected
References TextUtils::fixStyleAttribute(), normalizeAttribute(), normalizeCommandSlot(), normalizeFontSize(), normalizeTranslation(), parsePath(), PathUserData::pathStarting, setStrokeOrFill(), PathUserData::sNewHeight, PathUserData::sNewWidth, PathUserData::string, PathUserData::vbHeight, and PathUserData::vbWidth.
normalizeCommandSlot
void SvgFileSplitter::normalizeCommandSlot (QChar command, bool relative, QList< double > & args, void * userData) protected slot
References SVGPathLexer::FakeClosePathChar, PathUserData::sNewHeight, PathUserData::sNewWidth, PathUserData::string, PathUserData::vbHeight, and PathUserData::vbWidth.
normalizeFontSize()
bool SvgFileSplitter::normalizeFontSize (QDomElement & element, const char * attributeName, double num, double denom) protected
References DebugDialog::debug().
normalizeTranslation()
void SvgFileSplitter::normalizeTranslation (QDomElement & element, double sNewWidth, double sNewHeight, double vbWidth, double vbHeight) protected
References TextUtils::elementToMatrix(), and TextUtils::setSVGTransform().
painterPath()
QPainterPath SvgFileSplitter::painterPath (double dpi, const QString & elementID)
References TextUtils::findElementWithAttribute(), m_domDocument, normalize(), and painterPathChild().
painterPathChild()
void SvgFileSplitter::painterPathChild (QDomElement & element, QPainterPath & ppath) protected
References PathUserData::painterPath, painterPathCommandSlot(), parsePath(), and PathUserData::pathStarting.
painterPathCommandSlot
void SvgFileSplitter::painterPathCommandSlot (QChar command, bool relative, QList< double > & args, void * userData) protected slot
References PathUserData::painterPath.
parsePath()
bool SvgFileSplitter::parsePath (const QString & data, const char * slot, PathUserData & pathUserData, QObject * slotTarget, bool convertHV) virtual
References convertHVSlot(), HVConvertData::path, SVGPathRunner::runPath(), simpleParsePath(), HVConvertData::subX, HVConvertData::subY, HVConvertData::x, and HVConvertData::y.
rotateCommandSlot
virtual void SvgFileSplitter::rotateCommandSlot (QChar , bool , QList< double > & , void *) inline protected virtual slot
setStrokeOrFill()
void SvgFileSplitter::setStrokeOrFill (QDomElement & element, bool doIt, const QString & color, bool force) static protected
shift()
QString SvgFileSplitter::shift (double x, double y, const QString & elementID, bool shiftTransforms)
References TextUtils::findElementWithAttribute(), m_domDocument, and shiftChild().
shiftAttribute()
bool SvgFileSplitter::shiftAttribute (QDomElement & element, const char * attributeName, double d) static protected
shiftChild()
void SvgFileSplitter::shiftChild (QDomElement & element, double x, double y, bool shiftTransforms)
References parsePath(), PathUserData::pathStarting, shiftAttribute(), shiftCommandSlot(), shiftTranslation(), PathUserData::string, PathUserData::x, and PathUserData::y.
shiftCommandSlot
void SvgFileSplitter::shiftCommandSlot (QChar command, bool relative, QList< double > & args, void * userData) protected slot
References SVGPathLexer::FakeClosePathChar, PathUserData::pathStarting, standardArgs(), PathUserData::string, PathUserData::x, and PathUserData::y.
shiftTranslation()
bool SvgFileSplitter::shiftTranslation (QDomElement & element, double x, double y) protected
References TextUtils::elementToMatrix(), and TextUtils::setSVGTransform().
showText()
QByteArray SvgFileSplitter::showText (const QString & filename, bool & hasText) static
References TextUtils::removeXMLEntities(), and showTextAux().
showText2()
QByteArray SvgFileSplitter::showText2 (const QByteArray & svg, bool & hasText) static
References TextUtils::removeXMLEntities(), and showTextAux().
showText3()
QString SvgFileSplitter::showText3 (const QString & svg, bool & hasText) static
References TextUtils::removeXMLEntities(), and showTextAux().
showTextAux()
void SvgFileSplitter::showTextAux (QDomElement & parent, bool & hasText, bool root) static protected
simpleParsePath()
QVector< QVariant > SvgFileSplitter::simpleParsePath (const QString & pathData)
Parse content of path element d attribute into validated tokens.
Parameters
pathData raw svg path element d[ata] attribute
Returns
parsed commands and parameters
References DebugDialog::debug(), SVGPathParser::parse(), and SVGPathParser::symStack().
split()
bool SvgFileSplitter::split (const QString & filename, const QString & elementID)
References m_byteArray, and splitString().
splitString()
bool SvgFileSplitter::splitString (QString & contents, const QString & elementID)
References TextUtils::cleanSodipodi(), TextUtils::findElementWithAttribute(), m_byteArray, and m_domDocument.
standardArgs()
void SvgFileSplitter::standardArgs (bool relative, bool starting, QList< double > & args, PathUserData * pathUserData) protected
References PathUserData::string, PathUserData::x, and PathUserData::y.
toString()
QString SvgFileSplitter::toString ()
References m_domDocument, and TextUtils::removeXMLEntities().
Member Data Documentation
m_byteArray
QByteArray SvgFileSplitter::m_byteArray protected
m_domDocument
QDomDocument SvgFileSplitter::m_domDocument protected
The documentation for this class was generated from the following files:
svg/svgfilesplitter.h
svg/svgfilesplitter.cpp