Fritzing: autoroute/cmrouter/search2.cpp File Reference
search2.cpp File Reference
#include <stdio.h>
#include "tile.h"
Functions
int TiSrArea (Tile *hintTile, Plane *plane, TileRect *rect, TileCallback tileCallback, UserData arg)
int tiSrAreaEnum (Tile *enumRT, int enumBottom, TileRect *rect, TileCallback, UserData arg)
Variables
int MINDIFF = 1
Function Documentation
TiSrArea()
int TiSrArea (Tile * hintTile, Plane * plane, TileRect * rect, TileCallback tileCallback, UserData arg)
References gotoPoint(), MINDIFF, Plane::pl_hint, searchArg::plane, searchArg::rect, RIGHT(), tiSrAreaEnum(), TR(), TilePoint::xi, TileRect::xmini, TilePoint::yi, TileRect::ymaxi, YMIN(), and TileRect::ymini.
tiSrAreaEnum()
int tiSrAreaEnum (Tile * enumRT, int enumBottom, TileRect * rect, TileCallback tileCallback, UserData arg)
References LB(), searchArg::rect, RIGHT(), TR(), YMAX(), TileRect::ymaxi, YMIN(), and TileRect::ymini.
Variable Documentation
MINDIFF
int MINDIFF = 1