Fritzing: PaletteModel Class Reference
PaletteModel Class Reference
#include <palettemodel.h>
Signals
void addSearchMaximum (int)
void incSearch ()
void loadedPart (int i, int total)
void partsToLoad (int total)
Signals inherited from ModelBase
void loadedInstances (ModelBase *, QDomElement &instances)
void loadedRoot (const QString &fileName, ModelBase *, QDomElement &root)
void loadedViews (ModelBase *, QDomElement &views)
void loadingInstance (ModelBase *, QDomElement &instance)
void loadingInstances (ModelBase *, QDomElement &instances)
void obsoleteSMDOrientationSignal ()
void oldSchematicsSignal (const QString &filename, bool &useOldSchematics)
Public Member Functions
PaletteModel ()
PaletteModel (bool makeRoot, bool doInit)
~PaletteModel ()
ModelPart * addPart (QString newPartPath, bool addToReference, bool updateIdAlreadyExists)
QList< ModelPart * > allParts ()
void clear ()
void clearPartHash ()
virtual bool containsModelPart (const QString &moduleID)
QList< ModelPart * > findContribNoBin ()
QString loadedFrom ()
bool loadedFromFile ()
bool loadFromFile (const QString &fileName, ModelBase *referenceModel, bool checkViews)
virtual ModelPart * loadPart (const QString &path, bool update)
void removePart (const QString &moduleID)
void removeParts ()
ModelPart * retrieveModelPart (const QString &moduleID)
QList< ModelPart * > search (const QString &searchText, bool allowObsolete)
void search (ModelPart *modelPart, const QStringList &searchStrings, QList< ModelPart * > &modelParts, bool allowObsolete)
void setOrdererChildren (QList< QObject * > children)
Public Member Functions inherited from ModelBase
ModelBase (bool makeRoot)
virtual ~ModelBase ()
virtual ModelPart * addModelPart (ModelPart *parent, ModelPart *copyChild)
virtual ModelPart * addPart (QString newPartPath, bool addToReference)
virtual bool addPart (ModelPart *modelPart, bool update)
bool checkForReversedWires ()
const QString & fritzingVersion ()
ModelPart * genFZP (const QString &moduleID, ModelBase *referenceModel)
bool loadFromFile (const QString &fileName, ModelBase *referenceModel, QList< ModelPart * > &modelParts, bool checkInstances)
bool paste (ModelBase *referenceModel, QByteArray &data, QList< ModelPart * > &modelParts, QHash< QString, QRectF > &boundingRects, bool preserveIndex)
ModelPart * root ()
ModelPartSharedRoot * rootModelPartShared ()
void save (const QString &fileName, bool asPart)
void save (const QString &fileName, class QXmlStreamWriter &, bool asPart)
void setReferenceModel (ModelBase *)
void setReportMissingModules (bool)
Static Public Member Functions
static void initNames ()
static void setFzpOverrideFolder (const QString &)
Static Public Member Functions inherited from ModelBase
static bool onCoreList (const QString &moduleID)
Protected Member Functions
void countParts (QDir &dir, QStringList &nameFilters, int &partCount)
virtual void initParts (bool dbExists)
void loadParts (bool dbExists)
void loadPartsAux (QDir &dir, QStringList &nameFilters, int &loadedPart, int totalParts)
ModelPart * makeSubpart (ModelPart *originalModelPart, const QDomElement &originalSubparth)
Protected Member Functions inherited from ModelBase
ModelPart * createOldSchematicPart (ModelPart *, QString &moduleIDRef)
ModelPart * createOldSchematicPartAux (ModelPart *, const QString &oldModuleIDRef, const QString &oldSchematicFileName, const QString &oldSvgPath)
ModelPart * fixObsoleteModuleID (QDomDocument &domDocument, QDomElement &instance, QString &moduleIDRef)
bool loadInstances (QDomDocument &, QDomElement &root, QList< ModelPart * > &modelParts, bool checkViews)
void renewModelIndexes (QDomElement &root, const QString &childName, QHash< long, long > &oldToNew)
Protected Attributes
bool m_fullLoad
QString m_loadedFrom
bool m_loadedFromFile
bool m_loadingContrib
QHash< QString, ModelPart * > m_partHash
Protected Attributes inherited from ModelBase
bool m_checkForReversedWires
QString m_fritzingVersion
QPointer< ModelBase > m_referenceModel
bool m_reportMissingModules
QPointer< ModelPart > m_root
bool m_useOldSchematics
Static Protected Attributes
static QString s_fzpOverrideFolder
Static Protected Attributes inherited from ModelBase
static QList< QString > CoreList
Additional Inherited Members
Static Protected Member Functions inherited from ModelBase
static void checkMystery (QDomElement &instance)
static bool checkObsoleteOrientation (QDomElement &instance)
static bool checkOldSchematics (QDomElement &instance)
static void checkTraces (QDomElement &instance)
static bool isRatsnest (QDomElement &instance)
Constructor & Destructor Documentation
PaletteModel() [1/2]
PaletteModel::PaletteModel ()
References m_fullLoad, m_loadedFromFile, and m_loadingContrib.
PaletteModel() [2/2]
PaletteModel::PaletteModel (bool makeRoot, bool doInit)
References initParts(), m_fullLoad, m_loadedFromFile, and m_loadingContrib.
~PaletteModel()
PaletteModel::~PaletteModel ()
References m_partHash.
Member Function Documentation
addPart()
ModelPart * PaletteModel::addPart (QString newPartPath, bool addToReference, bool updateIdAlreadyExists) virtual
Reimplemented from ModelBase.
Reimplemented in SqliteReferenceModel, and ReferenceModel.
References loadPart(), and ModelBase::m_referenceModel.
addSearchMaximum
void PaletteModel::addSearchMaximum (int) signal
allParts()
QList< ModelPart * > PaletteModel::allParts ()
References ModelPart::isObsolete(), and m_partHash.
clear()
void PaletteModel::clear ()
clearPartHash()
void PaletteModel::clearPartHash ()
References m_partHash, ModelPart::modelPartShared(), and ModelPart::setModelPartShared().
containsModelPart()
bool PaletteModel::containsModelPart (const QString & moduleID) virtual
Reimplemented in SqliteReferenceModel.
References m_partHash.
countParts()
void PaletteModel::countParts (QDir & dir, QStringList & nameFilters, int & partCount) protected
findContribNoBin()
QList< ModelPart * > PaletteModel::findContribNoBin ()
References ModelPart::isContrib(), ModelPart::isInBin(), and m_partHash.
incSearch
void PaletteModel::incSearch () signal
initNames()
void PaletteModel::initNames () static
initParts()
void PaletteModel::initParts (bool dbExists) protected virtual
Reimplemented in SqliteReferenceModel.
References FMessageBox::information(), loadParts(), and ModelBase::m_root.
loadedFrom()
QString PaletteModel::loadedFrom ()
References ___emptyString___, m_loadedFrom, and m_loadedFromFile.
loadedFromFile()
bool PaletteModel::loadedFromFile ()
References m_loadedFromFile.
loadedPart
void PaletteModel::loadedPart (int i, int total) signal
loadFromFile()
bool PaletteModel::loadFromFile (const QString & fileName, ModelBase * referenceModel, bool checkViews)
References ModelBase::loadFromFile(), m_loadedFrom, and m_loadedFromFile.
loadPart()
ModelPart * PaletteModel::loadPart (const QString & path, bool update) virtual
Reimplemented in SqliteReferenceModel, and ReferenceModel.
References ModelPart::Board, ModelPart::Breadboard, ModelPart::CopperFill, TextUtils::findText(), ModuleIDNames::GroundModuleIDName, ModuleIDNames::GroundPlaneModuleIDName, ModelPart::Hole, ModuleIDNames::HoleModuleIDName, FMessageBox::information(), ModelPart::Jumper, ModuleIDNames::JumperModuleIDName, ModelPart::Logo, ModuleIDNames::LogoImageModuleIDName, ModuleIDNames::LogoTextModuleIDName, m_loadingContrib, m_partHash, ModelBase::m_root, makeSubpart(), ModelPart::moduleID(), ModuleIDNames::NetLabelModuleIDName, ModelPart::Note, ModuleIDNames::NoteModuleIDName, ModelBase::onCoreList(), ModelPart::Part, ModuleIDNames::PerfboardModuleIDName, ModuleIDNames::PowerLabelModuleIDName, ModuleIDNames::PowerModuleIDName, ModelPart::ResizableBoard, ResourcePath(), ModelBase::root(), ModelPart::Ruler, ModuleIDNames::RulerModuleIDName, ModelPart::setContrib(), ModelPart::setCore(), ModuleIDNames::Stripboard2ModuleIDName, ModuleIDNames::StripboardModuleIDName, ModelPart::Symbol, ModelPart::title(), ModuleIDNames::TwoPowerModuleIDName, ModelPart::Via, ModuleIDNames::ViaModuleIDName, FMessageBox::warning(), ModelPart::Wire, and ModuleIDNames::WireModuleIDName.
loadParts()
void PaletteModel::loadParts (bool dbExists) protected
References countParts(), FritzingPartExtension(), FolderUtils::getAppPartsSubFolder(), FolderUtils::getUserPartsPath(), loadedPart(), loadPartsAux(), m_fullLoad, partsToLoad(), and s_fzpOverrideFolder.
loadPartsAux()
void PaletteModel::loadPartsAux (QDir & dir, QStringList & nameFilters, int & loadedPart, int totalParts) protected
References loadedPart(), loadPart(), and m_loadingContrib.
makeSubpart()
ModelPart * PaletteModel::makeSubpart (ModelPart * originalModelPart, const QDomElement & originalSubparth) protected
References ModelPartShared::addSubpart(), PartFactory::fzpPath(), layers(), m_partHash, ModelPart::modelPartShared(), TextUtils::replaceChildText(), retrieveModelPart(), ModelBase::root(), ViewLayer::Schematic, ModelPart::SchematicSubpart, ViewLayer::SchematicView, ModelPart::setSubpartID(), ViewLayer::viewIDXmlName(), ViewLayer::viewLayerXmlNameFromID(), and TextUtils::writeUtf8().
partsToLoad
void PaletteModel::partsToLoad (int total) signal
removePart()
void PaletteModel::removePart (const QString & moduleID)
References m_partHash, ModelBase::m_root, and ModelPart::moduleID().
removeParts()
void PaletteModel::removeParts ()
References m_partHash, ModelBase::m_root, and ModelPart::moduleID().
retrieveModelPart()
ModelPart * PaletteModel::retrieveModelPart (const QString & moduleID) virtual
Reimplemented from ModelBase.
Reimplemented in SqliteReferenceModel, and ReferenceModel.
References m_partHash, and ModelBase::m_referenceModel.
search() [1/2]
QList< ModelPart * > PaletteModel::search (const QString & searchText, bool allowObsolete)
References ModelBase::m_root.
search() [2/2]
void PaletteModel::search (ModelPart * modelPart, const QStringList & searchStrings, QList< ModelPart * > & modelParts, bool allowObsolete)
References addSearchMaximum(), ModelPart::author(), ModelPart::description(), incSearch(), ModelPart::isObsolete(), ModelPart::moduleID(), ModelPart::properties(), search(), ModelPart::tags(), ModelPart::title(), and ModelPart::url().
setFzpOverrideFolder()
void PaletteModel::setFzpOverrideFolder (const QString & fzpOverrideFolder) static
References s_fzpOverrideFolder.
setOrdererChildren()
void PaletteModel::setOrdererChildren (QList< QObject * > children)
References ModelBase::m_root.
Member Data Documentation
m_fullLoad
bool PaletteModel::m_fullLoad protected
m_loadedFrom
QString PaletteModel::m_loadedFrom protected
m_loadedFromFile
bool PaletteModel::m_loadedFromFile protected
m_loadingContrib
bool PaletteModel::m_loadingContrib protected
m_partHash
QHash<QString, ModelPart *> PaletteModel::m_partHash protected
s_fzpOverrideFolder
QString PaletteModel::s_fzpOverrideFolder static protected
The documentation for this class was generated from the following files:
model/palettemodel.h
model/palettemodel.cpp