Fritzing: PEMainWindow Class Reference
PEMainWindow Class Reference
#include <pemainwindow.h>
Public Slots
void busModeChanged (bool)
void connectorCountChanged (int)
void connectorMetadataChanged (struct ConnectorMetadata *)
void connectorsTypeChanged (Connector::ConnectorType)
void deleteBusConnection ()
void getSpinAmount (double &amount)
void highlightSlot (PEGraphicsItem *)
void metadataChanged (const QString &name, const QString &value)
void newWireSlot (Wire *)
void pegiMousePressed (PEGraphicsItem *, bool &ignore)
void pegiMouseReleased (PEGraphicsItem *)
void pegiTerminalPointChanged (PEGraphicsItem *, QPointF before, QPointF after)
void pegiTerminalPointMoved (PEGraphicsItem *, QPointF)
void pickModeChanged (bool)
void propertiesChanged (const QHash< QString, QString > &)
void removedConnector (const QDomElement &)
void removedConnectors (QList< ConnectorMetadata * > &)
void s2sMessageSlot (const QString &message)
void showing (SketchWidget *)
void smdChanged (const QString &)
void switchedConnector (int)
void tagsChanged (const QStringList &)
void terminalPointChanged (const QString &how)
void terminalPointChanged (const QString &coord, double value)
void updateEditMenu ()
void updateExportMenu ()
void wireChangedSlot (Wire *, const QLineF &oldLine, const QLineF &newLine, QPointF oldPos, QPointF newPos, ConnectorItem *from, ConnectorItem *to)
Public Slots inherited from MainWindow
void acceptAlienFiles ()
void changeBoardLayers (int layers, bool doEmit)
void clearGroundFillSeeds ()
void copperFill ()
void ensureClosable ()
void groundFill ()
QList< ModelPart * > loadBundledPart (const QString &fileName, bool addToBin)
void oldSchematicsSlot (const QString &filename, bool &useOldSchematics)
void orderFabHoverEnter ()
void orderFabHoverLeave ()
void removeGroundFill ()
void selectAllObsolete ()
void setGroundFillKeepout ()
void setGroundFillSeeds ()
void setOneGroundFillSeed ()
void showPCBView ()
void showStatusMessage (const QString &)
void showWelcomeView ()
void statusMessage (QString message, int timeout)
void swapBoardImageSlot (SketchWidget *sketchWidget, ItemBase *itemBase, const QString &filename, const QString &moduleID, bool addName)
void swapObsolete ()
virtual void updateExportMenu ()
void updateTraceMenu ()
Signals
void addToMyPartsSignal (ModelPart *, const QStringList &)
Signals inherited from MainWindow
void alienPartsDismissed ()
void changeActivationSignal (bool activate, QWidget *originator)
void externalProcessSignal (QString &name, QString &path, QStringList &args)
void mainWindowMoved (QWidget *)
Signals inherited from FritzingWindow
void readOnlyChanged (bool isReadOnly)
Public Member Functions
PEMainWindow (ReferenceModel *referenceModel, QWidget *parent)
~PEMainWindow ()
void addBusConnector (const QString &busID, const QString &connectorID)
void changeConnectorMetadata (ConnectorMetadata *, bool updateDisplay)
void changeMetadata (const QString &name, const QString &value, bool updateDisplay)
void changeOriginalFile (ViewLayer::ViewID viewID, const QString originalFile, int changeCount)
void changeProperties (const QHash< QString, QString > &, bool updateDisplay)
void changeReferenceFile (ViewLayer::ViewID viewID, const QString referenceFile)
void changeSMD (const QString &smd, const QString &filename, int changeDirection)
void changeSvg (SketchWidget *, const QString &filename, int changeDirection)
void changeTags (const QStringList &, bool updateDisplay)
bool editsModuleID (const QString &)
void moveTerminalPoint (SketchWidget *, const QString &id, QSizeF, QPointF, int changeDirection)
void relocateConnectorSvg (SketchWidget *, const QString &id, const QString &terminalID, const QString &oldGorn, const QString &oldGornTerminal, const QString &newGorn, const QString &newGornTerminal, int changeDirection)
void removeBusConnector (const QString &busID, const QString &connectorID, bool display)
void restoreFzp (const QString &filename)
bool setInitialItem (PaletteItem *)
Public Member Functions inherited from MainWindow
MainWindow (class ReferenceModel *referenceModel, QWidget *parent)
MainWindow (QFile &fileToLoad)
~MainWindow ()
void addDefaultParts ()
void addToSketch (QList< ModelPart * > &)
bool anyUsePart (const QString &moduleID)
void clearFileProgressDialog ()
void copperFill (ViewLayer::ViewLayerID)
void enableCheckUpdates (bool enabled)
void exportSvg (double res, bool selectedItems, bool flatten, const QString &filename)
class FileProgressDialog * fileProgressDialog ()
int fireQuoteDelay ()
const QString & fritzingVersion ()
void getPartsEditorNewAnd (ItemBase *fromItem)
void groundFill (ViewLayer::ViewLayerID)
bool hasAnyAlien ()
bool hasCustomBoardShape ()
void hideTempPartsBin ()
void init (ReferenceModel *referenceModel, bool lockFiles)
bool loadBundledNonAtomicEntity (const QString &filename, Bundler *bundler, bool addToBin, bool dontAsk)
bool loadWhich (const QString &fileName, bool setAsLastOpened, bool addToRecent, bool checkObsolete, const QString &displayName)
void mainLoad (const QString &fileName, const QString &displayName, bool checkObsolete)
QStringList newDesignRulesCheck (bool showOkMessage)
void noBackup ()
void noSchematicConversion ()
void notClosableForAWhile ()
class PCBSketchWidget * pcbView ()
ProgramWindow * programmingWidget ()
QAction * raiseWindowAction ()
QStatusBar * realStatusBar ()
void redrawSketch ()
void removeGroundFill (ViewLayer::ViewLayerID, QUndoCommand *parentCommand)
void restoreDocks ()
bool saveAsAux (const QString &fileName)
void saveAsShareable (const QString &path, bool saveModel)
void saveBundledNonAtomicEntity (QString &filename, const QString &extension, Bundler *bundler, const QList< ModelPart * > &partsToSave, bool askForFilename, const QString &destFolderPath, bool saveModel, bool deleteLeftovers)
void saveDocks ()
QList< ItemBase * > selectAllObsolete (bool displayFeedback)
const QString & selectedModuleID ()
void selectPartsWithModuleID (ModelPart *)
void setCloseSilently (bool)
void setCurrentFile (const QString &fileName, bool addToRecent, bool setAsLastOpened)
void setCurrentView (ViewLayer::ViewID)
void setFileProgressPath (const QString &path)
void setFireQuoteDelay (int)
void setInitialTab (int)
void setReportMissingModules (bool)
void showFileProgressDialog (const QString &path)
QSizeGrip * sizeGrip ()
QList< class SketchWidget * > sketchWidgets ()
void swapLayers (ItemBase *itemBase, int layers, const QString &msg, int delay)
void swapObsolete (bool displayFeedback, QList< ItemBase * > &)
void swapSelectedAux (ItemBase *itemBase, const QString &moduleID, bool useViewLayerPlacement, ViewLayer::ViewLayerPlacement, QMap< QString, QString > &propsMap)
bool updateParts (const QString &moduleID, QUndoCommand *parentCommand)
void updatePartsBin (const QString &moduleID)
bool usesPart (const QString &moduleID)
Public Member Functions inherited from FritzingWindow
FritzingWindow (const QString &untitledFileName, int &untitledFileCount, QString fileExt, QWidget *parent=0, Qt::WindowFlags f=0)
const QString & fileName ()
void setFileName (const QString &)
Public Member Functions inherited from Bundler
virtual ~Bundler ()
virtual bool loadBundledAux (QDir &dir, QList< class ModelPart * > mps)
virtual bool preloadBundledAux (QDir &dir, bool dontAsk)
Protected Slots
void backupSketch ()
void clickedItemCandidateSlot (QGraphicsItem *, bool &ok)
void closeLater ()
void convertToTenth ()
void hideOtherViews ()
void initZoom ()
void itemAddedSlot (ModelPart *, ItemBase *, ViewLayer::ViewLayerPlacement, const ViewGeometry &, long id, SketchWidget *dropOrigin)
void itemMovedSlot (ItemBase *)
void loadImage ()
void resetNextPick ()
void resizedSlot (ItemBase *)
void reuseBreadboard ()
void reusePCB ()
void reuseSchematic ()
bool save ()
bool saveAs ()
void showConnectorsView ()
void showIconView ()
void showInOS ()
void showMetadataView ()
void tabWidget_currentChanged (int index)
void updateAssignedConnectors ()
void updateLayerMenu (bool resetLayout=false)
void updateWindowMenu ()
void updateWireMenu ()
Protected Slots inherited from MainWindow
void about ()
void activateWindowAux ()
void activeLayerBoth ()
void activeLayerBottom ()
void activeLayerTop ()
void actualSize ()
void addBendpoint ()
void addNote ()
void addToMyParts (ModelPart *, const QStringList &)
void alignBottom ()
void alignHorizontalCenter ()
void alignLeft ()
void alignRight ()
void alignToGrid ()
void alignTop ()
void alignVerticalCenter ()
void applyReadOnlyChange (bool isReadOnly)
void autorouterSettings ()
void autosaveNeeded (int index=0)
virtual void backupSketch ()
void binSaved (bool hasAlienParts)
void boardDeletedSlot ()
void bringForward ()
void bringToFront ()
void changeTraceLayer ()
void changeWireColor (bool checked)
void checkLoadedTraces ()
void colorWiresByLength ()
void convertToBendpoint ()
void convertToVia ()
void copy ()
void createNewSketch ()
void createTrace ()
void cursorLocationSlot (double, double, double=0.0, double=0.0)
void cut ()
void deselect ()
void disconnectAll ()
void dockChangeActivation (bool activate, QWidget *originator)
void doDelete ()
void doDeleteMinus ()
void doExport ()
void dropPaste (SketchWidget *)
void dumpAllParts ()
void duplicate ()
void enableDebug ()
void excludeFromAutoroute ()
void exportEtchable ()
void exportNormalizedFlattenedSVG ()
void exportNormalizedSVG ()
bool externalProcess (QString &name, QString &path, QStringList &args)
void fabQuote ()
void filenameIfSlot (QString &filename)
void findPartInSketch ()
void fireQuote ()
void firstTimeHelp ()
void fitInWindow ()
void flattenCurve ()
void flipHorizontal ()
void flipVertical ()
void gridUnits (bool)
void hideAllLayers ()
void hidePartSilkscreen ()
void hundredPercentSize ()
virtual void initZoom ()
void keepMargins ()
void launchExternalProcess ()
void linkToProgramFile (const QString &filename, Platform *platform, bool addLink, bool strong)
void loadedRootSlot (const QString &filename, ModelBase *, QDomElement &views)
void loadedViewsSlot (class ModelBase *, QDomElement &views)
void locationLabelClicked ()
void mainLoad ()
void minimize ()
void moveLock ()
void newAutoroute ()
QStringList newDesignRulesCheck ()
void obsoleteSMDOrientationSlot ()
void openDonate ()
void openExamples ()
void openHelp ()
void openInPartsEditorNew ()
void openNewPartsEditor (class PaletteItem *)
void openPartsReference ()
void openProgramWindow ()
void openRecentOrExampleFile ()
void openRecentOrExampleFile (const QString &filename, const QString &actionText)
void openURL ()
void orderFab ()
void pageSetup ()
void partsEditorHelp ()
void paste ()
void pasteInPlace ()
void print ()
void processError (QProcess::ProcessError processError)
void processFinished (int exitCode, QProcess::ExitStatus exitStatus)
void processReadyRead ()
void processStateChanged (QProcess::ProcessState newState)
void raiseAndActivate ()
void reportBug ()
void restoreDefaultGrid ()
void revert ()
void rotate180 ()
void rotate45ccw ()
void rotate45cw ()
void rotate90ccw ()
void rotate90cw ()
void rotateIncCCW ()
void rotateIncCCWRubberBand ()
void rotateIncCW ()
void rotateIncCWRubberBand ()
void routingStatusLabelMousePress (QMouseEvent *)
void routingStatusLabelMouseRelease (QMouseEvent *)
void routingStatusSlot (class SketchWidget *, const RoutingStatus &)
bool save ()
bool saveAs ()
QStringList saveBundledAux (ModelPart *mp, const QDir &destFolder)
void saveBundledPart (const QString &moduleId=___emptyString___)
void selectAll ()
void selectAllCopperFill ()
void selectAllExcludedTraces ()
void selectAllIncludedTraces ()
void selectAllJumperItems ()
void selectAllTraces ()
void selectAllVias ()
void selectMoveLock ()
void sendBackward ()
void sendToBack ()
void setActiveConnectorItem (class ConnectorItem *)
void setActiveWire (class Wire *)
void setBackgroundColor ()
void setGridSize ()
void setInfoViewOnHover (bool infoViewOnHover)
void setSticky ()
void setViewFromAbove ()
void setViewFromBelow ()
void setViewFromBelowToggle ()
void shareOnline ()
void showAllLayers ()
void showBreadboardView ()
void showGrid ()
void showPartLabels ()
void showPartsBinIconView ()
void showPartsBinListView ()
void showProgramView ()
void showSchematicView ()
void showUnrouted ()
void startSaveInstancesSlot (const QString &fileName, ModelPart *, QXmlStreamWriter &)
void subSwapSlot (SketchWidget *, ItemBase *, const QString &newModuleID, ViewLayer::ViewLayerPlacement, long &newID, QUndoCommand *parentCommand)
void swapSelectedDelay (const QString &family, const QString &prop, QMap< QString, QString > &currPropsMap, ItemBase *)
void swapSelectedMap (const QString &family, const QString &prop, QMap< QString, QString > &currPropsMap, ItemBase *)
void swapSelectedTimeout ()
virtual void tabWidget_currentChanged (int index)
void testConnectors ()
void throwFakeException ()
void tidyWires ()
void tipsAndTricks ()
void toggleActiveLayer ()
void toggleDebuggerOutput (bool toggle)
void toggleInfo (bool toggle)
void togglePartLibrary (bool toggle)
void toggleToolbar (bool toggle)
void toggleUndoHistory (bool toggle)
void undoStackCleanChanged (bool isClean)
virtual void updateEditMenu ()
void updateItemMenu ()
virtual void updateLayerMenu (bool resetLayout=false)
void updateLayerMenuSlot ()
void updatePartMenu ()
void updateRecentFileActions ()
void updateRoutingStatus ()
void updateTransformationActions ()
void updateViewZoom (double newZoom)
void updateWelcomeViewRecentList (bool doEmit=true)
virtual void updateWindowMenu ()
virtual void updateWireMenu ()
void updateZoomOptionsNoMatterWhat (double zoom)
void updateZoomSlider (double zoom)
void visitFritzingDotOrg ()
void zoomIn ()
void zoomOut ()
Protected Slots inherited from FritzingWindow
virtual bool save ()
virtual bool saveAs ()
void undoStackCleanChanged (bool isClean)
Protected Member Functions
bool activeLayerWidgetAlwaysOn ()
void addTab (QWidget *widget, const QString &label)
bool anyMarquee ()
bool anyVisible ()
QMenu * breadboardItemMenu ()
QMenu * breadboardWireMenu ()
bool canSave ()
void changeConnectorElement (QDomElement &connector, ConnectorMetadata *)
void changeSpecialProperty (const QString &name, const QString &value)
void clearPickMode ()
void closeEvent (QCloseEvent *event)
void connectorWarning ()
void connectPairs ()
void createActions ()
void createEditMenu ()
void createFileMenu ()
void createFileMenuActions ()
void createMenus ()
QString createSvgFromImage (const QString &origFilePath)
QWidget * createTabWidget ()
void createViewMenu ()
void createViewMenuActions (bool showWelcome)
int currentTabIndex ()
QWidget * currentTabWidget ()
void deleteBuses ()
void displayBuses ()
bool event (QEvent *)
bool eventFilter (QObject *, QEvent *)
void fillInMetadata (const QDomElement &connector, ConnectorMetadata &cmd)
QDomElement findBus (const QDomElement &, const QString &)
QDomElement findConnector (const QString &id, int &index)
PEGraphicsItem * findConnectorItem ()
QDomElement findNodeMemberBus (const QDomElement &buses, const QString &connectorID)
QList< QWidget * > getButtonsForView (ViewLayer::ViewID)
QHash< QString, QString > getOldProperties ()
QString getPartTitle ()
QList< PEGraphicsItem * > getPegiList (SketchWidget *)
QRectF getPixelBounds (FSvgRenderer &renderer, QDomElement &element)
QString getSvgReferenceFile (const QString &filename)
void initConnectors (bool updateConnectorsView)
void initDock ()
void initLockedFiles (bool lockFiles)
void initProgrammingWidget ()
void initSketchWidgets (bool withIcons)
void initSvgTree (SketchWidget *, ItemBase *, QDomDocument &)
void initWelcomeView ()
void insertDesc (const QString &referenceFile, QString &svg)
void killPegi ()
bool loadFzp (const QString &path)
QString makeDesc (const QString &referenceFile)
QString makeDirName ()
QString makeNewVariant (const QString &family)
PEGraphicsItem * makePegi (QSizeF size, QPointF topLeft, ItemBase *itemBase, QDomElement &element, double z)
QString makeSvgPath2 (SketchWidget *sketchWidget)
void moreInitDock ()
QMenu * pcbItemMenu ()
QMenu * pcbWireMenu ()
void reload (bool firstTime)
void relocateConnector (PEGraphicsItem *pegi)
void removedConnectorsAux (QList< QDomElement > &connectors)
void replaceProperty (const QString &key, const QString &value, QDomElement &properties)
void reuseImage (ViewLayer::ViewID)
bool saveAs (bool overWrite)
QString saveFzp ()
QMenu * schematicItemMenu ()
QMenu * schematicWireMenu ()
void setBeforeClosingText (const QString &filename, QMessageBox &messageBox)
void setConnectorSMD (bool toSMD, QDomElement &connector)
void setCurrentTabIndex (int)
void setImageAttribute (QDomElement &layers, const QString &image)
void setImageAttribute (QDomElement &fzpRoot, const QString &svgPath, ViewLayer::ViewID viewID)
void setInitialView ()
void setTitle ()
void showInOS (QWidget *parent, const QString &pathIn)
void switchedConnector (int, SketchWidget *)
void terminalPointChangedAux (PEGraphicsItem *pegi, QPointF before, QPointF after)
void updateChangeCount (SketchWidget *sketchWidget, int changeDirection)
void updateFileMenu ()
void updateRaiseWindowAction ()
bool writeXml (const QString &path, const QString &text, bool temp)
Protected Member Functions inherited from MainWindow
int activeLayerIndex ()
void addBottomMargin (FDockWidget *dock)
virtual void addTab (QWidget *widget, const QString &iconPath, const QString &label, bool withIcon)
void addTopMargin (FDockWidget *dock)
bool alreadyOpen (const QString &fileName)
void backupExistingFileIfExists (const QString &destFilePath)
void checkSwapObsolete (QList< ItemBase * > &, bool includeUpdateLaterMessage)
void closeEvent (QCloseEvent *event)
void closeIfEmptySketch (MainWindow *mw)
void connectPair (SketchWidget *signaller, SketchWidget *slotter)
void connectStartSave (bool connect)
QString constructFileName (const QString &differentiator, const QString &extension)
bool copySvg (const QString &path, QFileInfoList &svgEntryInfoList)
ModelPart * copyToPartsFolder (const QFileInfo &file, bool addToAlien, const QString &prefixFolder, const QString &destFolder)
QString copyToSvgFolder (const QFileInfo &file, bool addToAlien, const QString &prefixFolder, const QString &destFolder)
void createActiveLayerActions ()
QWidget * createActiveLayerButton (SketchAreaWidget *parent)
virtual void createAddToBinSubmenu (QMenu *parentMenu)
virtual void createAlignSubmenu (QMenu *parentMenu)
SketchToolButton * createAutorouteButton (SketchAreaWidget *parent)
void createDockWindows ()
void createEditMenuActions ()
void createExportActions ()
SketchToolButton * createExportEtchableButton (SketchAreaWidget *parent)
SketchToolButton * createFlipButton (SketchAreaWidget *parent)
QWidget * createGridSizeForm (GridSizeThing *)
virtual void createHelpMenu ()
void createHelpMenuActions ()
SketchToolButton * createNoteButton (SketchAreaWidget *parent)
void createOpenExampleMenu ()
void createOpenRecentMenu ()
void createOrderFabAct ()
SketchToolButton * createOrderFabButton (SketchAreaWidget *parent)
virtual void createPartMenu ()
void createPartMenuActions ()
void createRaiseWindowActions ()
class SketchToolButton * createRotateButton (SketchAreaWidget *parent)
virtual void createRotateSubmenu (QMenu *parentMenu)
class ExpandingLabel * createRoutingStatusLabel (SketchAreaWidget *)
SketchToolButton * createShareButton (SketchAreaWidget *parent)
void createStatusBar ()
QWidget * createToolbarSpacer (SketchAreaWidget *parent)
void createTraceMenuActions ()
virtual void createTraceMenus ()
QWidget * createViewFromButton (SketchAreaWidget *parent)
virtual void createWindowMenu ()
void createWindowMenuActions ()
void createZoomOptions (SketchAreaWidget *parent)
virtual void createZOrderSubmenu (QMenu *parentMenu)
SketchAreaWidget * currentSketchArea ()
const QString defaultSaveFolder ()
class FDockWidget * dockIt (FDockWidget *dock, int dockMinHeight, int dockDefaultHeight, Qt::DockWidgetArea area=Qt::RightDockWidgetArea)
void dockMarginAux (FDockWidget *dock, const QString &name, const QString &style)
void dontKeepMargins ()
void dragEnterEvent (QDragEnterEvent *event)
void dropEvent (QDropEvent *event)
void enableAddBendpointAct (QGraphicsItem *)
bool event (QEvent *)
bool eventFilter (QObject *obj, QEvent *event)
void exportAux (QString fileName, QImage::Format format, int quality, bool removeBackground)
void exportBOM ()
void exportEtchable (bool wantPDF, bool wantSVG)
void exportNetlist ()
class FileProgressDialog * exportProgress ()
void exportSpiceNetlist ()
void exportSvg (double res, bool selectedItems, bool flatten)
void exportSvgWatermark (QString &svg, double res)
void exportToEagle ()
void exportToGerber ()
const QString fileExtension ()
ModelPart * findReplacedby (ModelPart *originalModelPart)
const QString fritzingTitle ()
QString genIcon (SketchWidget *, LayerList &partViewLayerIDs, LayerList &wireViewLayerIDs)
QString getBoardSvg (ItemBase *board, int res, LayerList &)
QString getBomProps (ItemBase *)
QStringList getExtensions ()
QString getExtensionString ()
virtual QString getStyleSheetSuffix ()
void groundFillAux (bool fillGroundTraces, ViewLayer::ViewLayerID viewLayerID)
void groundFillAux2 (bool fillGroundTraces)
bool hasLinkedProgramFiles (const QString &filename, QStringList &linkedProgramFiles)
void hideShowProgramMenu ()
void hideShowTraceMenu ()
QHash< QString, struct SketchDescriptor * > indexAvailableElements (QDomElement &domElem, const QString &srcPrefix, QStringList &actionsTracker, const QString &localeName)
virtual void initMenus ()
void initSketchWidget (SketchWidget *)
void initStyleSheet ()
bool isGroundFill (ItemBase *itemBase)
void loadBundledSketch (const QString &fileName, bool addToRecent, bool setAsLastOpened, bool checkObsolete)
void mainLoadAux (const QString &fileName)
class FDockWidget * makeDock (const QString &title, QWidget *widget, int dockMinHeight, int dockDefaultHeight, Qt::DockWidgetArea area=Qt::RightDockWidgetArea, DockFactory dockFactory=NULL)
void massageOutput (QString &svg, bool doMask, bool doSilk, bool doPaste, QString &maskTop, QString &maskBottom, const QString &fileName, ItemBase *board, int dpi, const LayerList &)
QString mergeBoardSvg (QString &svg, ItemBase *board, int res, bool flip, LayerList &)
void moveEvent (QMoveEvent *event)
QList< ModelPart * > moveToPartsFolder (QDir &unzipDir, MainWindow *mw, bool addToBin, bool addToAlien, const QString &prefixFolder, const QString &destFolder, bool importingSinglePart)
FDockWidget * newBottomWidget ()
FDockWidget * newTopWidget ()
void notYetImplemented (QString action)
QMessageBox::StandardButton oldSchematicMessage (const QString &filename)
void pasteAux (bool pasteInPlace)
virtual void populateExportMenu ()
void populateMenuFromFolderContent (QMenu *parentMenu, const QString &path)
void populateMenuFromXMLFile (QMenu *parentMenu, QStringList &actionsTracker, const QString &folderPath, const QString &indexFileName)
void populateMenuWithIndex (const QHash< QString, struct SketchDescriptor * > &, QMenu *parentMenu, QDomElement &domElem, const QString &localeName)
void printAux (QPrinter &printer, bool removeBackground, bool paginate)
void recoverBackupedFiles ()
void removeMargin (FDockWidget *dock)
void resetTempFolder ()
void resizeEvent (QResizeEvent *event)
class ConnectorItem * retrieveConnectorItem ()
class Wire * retrieveWire ()
MainWindow * revertAux ()
void routingStatusLabelMouse (QMouseEvent *, bool show)
void saveAsAuxAux (const QString &fileName)
void saveLastTabList ()
void setActionsIcons (int index, QList< QAction * > &)
void svgMissingLayer (const QString &layername, const QString &path)
long swapSelectedAuxAux (ItemBase *itemBase, const QString &moduleID, ViewLayer::ViewLayerPlacement viewLayerPlacement, QMap< QString, QString > &propsMap, QUndoCommand *parentCommand)
bool swapSpecial (const QString &prop, QMap< QString, QString > &currPropsMap)
bool undoStackIsEmpty ()
int & untitledFileCount ()
const QString untitledFileName ()
void updateActiveLayerButtons ()
void updatePCBTraceMenu (QGraphicsItem *, TraceMenuThing &)
QMenu * viewItemMenuAux (QMenu *menu)
bool whatToDoWithAlienFiles ()
Protected Member Functions inherited from FritzingWindow
virtual bool anyModified ()
virtual bool beforeClosing (bool showCancel, bool &discard)
QMessageBox::StandardButton beforeClosingMessage (const QString &filename, bool showCancel)
void createCloseAction ()
bool save (const QString &filename, bool readOnly)
bool saveAs (const QString &filename, bool readOnly)
void setReadOnly (bool readOnly)
Protected Attributes
QDomDocument m_breadboardDocument
bool m_canSave
QList< QDomElement > m_connectorList
PEConnectorsView * m_connectorsView = nullptr
QAction * m_convertToTenthAct = nullptr
WireAction * m_deleteBusConnectionAct = nullptr
int m_fileIndex
QStringList m_filesToDelete
QDomDocument m_fzpDocument
bool m_gaveSaveWarning
QString m_guid
QAction * m_hideOtherViewsAct = nullptr
QDomDocument m_iconDocument
QPointer< IconSketchWidget > m_iconGraphicsView
QPointer< SketchAreaWidget > m_iconWidget
QList< QPointer< QWidget > > m_inFocusWidgets
bool m_inPickMode
PEMetadataView * m_metadataView = nullptr
QString m_originalFzpPath
QString m_originalModuleID
QDomDocument m_pcbDocument
PESvgView * m_peSvgView = nullptr
PEToolView * m_peToolView = nullptr
QString m_prefix
QString m_removedConnector
QAction * m_reuseBreadboardAct = nullptr
QAction * m_reusePCBAct = nullptr
QAction * m_reuseSchematicAct = nullptr
QDomDocument m_schematicDocument
QAction * m_showConnectorsViewAct = nullptr
QAction * m_showIconAct = nullptr
QAction * m_showInOSAct = nullptr
QAction * m_showMetadataViewAct = nullptr
bool m_useNextPick
QString m_userPartsFolderPath
QString m_userPartsFolderSvgPath
QHash< ViewLayer::ViewID, ViewThing * > m_viewThings
Protected Attributes inherited from MainWindow
QAction * m_100PercentSizeAct = nullptr
QAction * m_aboutAct = nullptr
QAction * m_aboutQtAct = nullptr
QPointer< ConnectorItem > m_activeConnectorItem
QAction * m_activeLayerBothAct = nullptr
QAction * m_activeLayerBottomAct = nullptr
QStackedWidget * m_activeLayerButtonWidget = nullptr
QAction * m_activeLayerTopAct = nullptr
QPointer< Wire > m_activeWire
QAction * m_actualSizeAct = nullptr
QAction * m_addBendpointAct = nullptr
bool m_addedToTemp = false
QAction * m_addNoteAct = nullptr
QMenu * m_addToBinMenu = nullptr
QStringList m_alienFiles
QString m_alienPartsMsg
QAction * m_alignBottomAct = nullptr
QAction * m_alignHorizontalCenterAct = nullptr
QAction * m_alignLeftAct = nullptr
QMenu * m_alignMenu = nullptr
QAction * m_alignRightAct = nullptr
QAction * m_alignToGridAct = nullptr
QAction * m_alignTopAct = nullptr
QAction * m_alignVerticalCenterAct = nullptr
QAction * m_autorouterSettingsAct = nullptr
bool m_autosaveNeeded = false
QTimer m_autosaveTimer
bool m_backingUp = false
QString m_backupFileNameAndPath
QPointer< class BinManager > m_binManager
FDockWidget * m_bottomDock = nullptr
QPointer< class BreadboardSketchWidget > m_breadboardGraphicsView
QMenu * m_breadboardTraceMenu = nullptr
QPointer< SketchAreaWidget > m_breadboardWidget
QMenu * m_breadboardWireColorMenu = nullptr
QAction * m_bringForwardAct = nullptr
class WireAction * m_bringForwardWireAct = nullptr
QAction * m_bringToFrontAct = nullptr
class WireAction * m_bringToFrontWireAct = nullptr
QString m_bundledSketchName
QAction * m_changeTraceLayerAct = nullptr
class WireAction * m_changeTraceLayerWireAct = nullptr
QAction * m_checkForUpdatesAct = nullptr
QAction * m_checkLoadedTracesAct = nullptr
QAction * m_clearGroundFillSeedsAct = nullptr
bool m_closeSilently = false
bool m_closing = false
QAction * m_colorWiresByLengthAct = nullptr
bool m_comboboxChanged = false
bool m_convertedSchematic = false
QAction * m_convertToBendpointAct = nullptr
QAction * m_convertToBendpointSeparator = nullptr
QAction * m_convertToViaAct = nullptr
QAction * m_copperFillAct = nullptr
QAction * m_copyAct = nullptr
QAction * m_createJumperAct = nullptr
class WireAction * m_createTraceWireAct = nullptr
class WireAction * m_createWireWireAct = nullptr
QPointer< SketchWidget > m_currentGraphicsView
QPointer< SketchAreaWidget > m_currentWidget
QAction * m_cutAct = nullptr
QAction * m_deleteAct = nullptr
QAction * m_deleteMinusAct = nullptr
class WireAction * m_deleteWireAct = nullptr
class WireAction * m_deleteWireMinusAct = nullptr
QAction * m_deselectAct = nullptr
QAction * m_disconnectAllAct = nullptr
QList< FDockWidget * > m_docks
bool m_dontClose = false
bool m_dontKeepMargins = false
QIcon m_dotIcon
QAction * m_dumpAllPartsAction = nullptr
QAction * m_duplicateAct = nullptr
QMenu * m_editMenu = nullptr
QIcon m_emptyIcon
QAction * m_enableDebugAct = nullptr
QAction * m_examplesAct = nullptr
QAction * m_exceptionAct = nullptr
QAction * m_excludeFromAutorouteAct = nullptr
class WireAction * m_excludeFromAutorouteWireAct = nullptr
QAction * m_exportBomAct = nullptr
QAction * m_exportEagleAct = nullptr
QAction * m_exportEtchablePdfAct = nullptr
QAction * m_exportEtchableSvgAct = nullptr
QAction * m_exportGerberAct = nullptr
QAction * m_exportJpgAct = nullptr
QMenu * m_exportMenu = nullptr
QAction * m_exportNetlistAct = nullptr
QAction * m_exportNormalizedFlattenedSvgAction = nullptr
QAction * m_exportNormalizedSvgAction = nullptr
QAction * m_exportPdfAct = nullptr
QAction * m_exportPngAct = nullptr
QAction * m_exportSpiceNetlistAct = nullptr
QAction * m_exportSvgAct = nullptr
QByteArray m_externalProcessOutput
QAction * m_fabQuoteAct = nullptr
QMenu * m_fileMenu = nullptr
QPointer< class FileProgressDialog > m_fileProgressDialog
QStringList m_filesReplacedByAlienOnes
QAction * m_findPartInSketchAct = nullptr
int m_fireQuoteDelay = 0
QTimer m_fireQuoteTimer
bool m_firstOpen = false
QAction * m_firstTimeHelpAct = nullptr
QAction * m_fitInWindowAct = nullptr
QAction * m_flattenCurveAct = nullptr
QList< SketchToolButton * > m_flipButtons
QAction * m_flipHorizontalAct = nullptr
QAction * m_flipVerticalAct = nullptr
QMenu * m_fritzingMenu = nullptr
QHash< QString, struct LockedFile * > m_fzzFiles
QString m_fzzFolder
QAction * m_groundFillAct = nullptr
QMenu * m_helpMenu = nullptr
QAction * m_hideAllLayersAct = nullptr
QAction * m_hidePartSilkscreenAct = nullptr
QPointer< class HtmlInfoView > m_infoView
QAction * m_infoViewOnHoverAction = nullptr
int m_initialTab = 0
QAction * m_launchExternalProcessAct = nullptr
QPointer< class LayerPalette > m_layerPalette
QList< LinkedFile * > m_linkedProgramFiles
QPointer< QLabel > m_locationLabel
QString m_locationLabelUnits
QAction * m_minimizeAct = nullptr
QAction * m_moveLockAct = nullptr
QAction * m_newAct = nullptr
QAction * m_newAutorouteAct = nullptr
QAction * m_newDesignRulesCheckAct = nullptr
bool m_noSchematicConversion = false
int m_numFixedActionsInViewMenu = 0
bool m_obsoleteSMDOrientation = false
QString m_oldBottomDockStyle
QString m_oldTopDockStyle
QAction * m_openAct = nullptr
QAction * m_openDonateAct = nullptr
QStringList m_openExampleActions
QMenu * m_openExampleMenu = nullptr
QAction * m_openHelpAct = nullptr
QAction * m_openInPartsEditorNewAct = nullptr
QAction * m_openProgramWindowAct = nullptr
QAction * m_openRecentFileActs [MaxRecentFiles] = { nullptr }
QMenu * m_openRecentFileMenu = nullptr
QAction * m_orderFabAct = nullptr
QWidget * m_orderFabButton = nullptr
bool m_orderFabEnabled = false
QAction * m_pageSetupAct = nullptr
QMenu * m_partMenu = nullptr
QAction * m_partsEditorHelpAct = nullptr
QAction * m_partsRefAct = nullptr
QAction * m_pasteAct = nullptr
QAction * m_pasteInPlaceAct = nullptr
QPointer< class PCBSketchWidget > m_pcbGraphicsView
QMenu * m_pcbTraceMenu = nullptr
QPointer< SketchAreaWidget > m_pcbWidget
QAction * m_preferencesAct = nullptr
QAction * m_printAct = nullptr
QPointer< class ProgramWindow > m_programView
QPointer< class ProgramWindow > m_programWindow
QAction * m_quitAct = nullptr
QAction * m_raiseWindowAct = nullptr
QAction * m_redoAct = nullptr
QPointer< ReferenceModel > m_referenceModel
QAction * m_regeneratePartsDatabaseAct = nullptr
QAction * m_removeGroundFillAct = nullptr
QAction * m_reportBugAct = nullptr
bool m_restarting = false
QAction * m_revertAct = nullptr
QPointer< QDialog > m_rolloverQuoteDialog
QAction * m_rotate180Act = nullptr
QAction * m_rotate45ccwAct = nullptr
QAction * m_rotate45cwAct = nullptr
QAction * m_rotate90ccwAct = nullptr
QAction * m_rotate90cwAct = nullptr
QList< SketchToolButton * > m_rotateButtons
QMenu * m_rotateMenu = nullptr
RoutingStatus m_routingStatus
QAction * m_saveAct = nullptr
QAction * m_saveAsAct = nullptr
QAction * m_saveBundledPart = nullptr
QPointer< class SchematicSketchWidget > m_schematicGraphicsView
QMenu * m_schematicTraceMenu = nullptr
QPointer< SketchAreaWidget > m_schematicWidget
QMenu * m_schematicWireColorMenu = nullptr
QAction * m_selectAllAct = nullptr
QAction * m_selectAllCopperFillAct = nullptr
QAction * m_selectAllExcludedTracesAct = nullptr
QAction * m_selectAllIncludedTracesAct = nullptr
QAction * m_selectAllJumperItemsAct = nullptr
QAction * m_selectAllObsoleteAct = nullptr
QAction * m_selectAllTracesAct = nullptr
QAction * m_selectAllViasAct = nullptr
QAction * m_selectAllWiresAct = nullptr
QAction * m_selectMoveLockAct = nullptr
QAction * m_sendBackwardAct = nullptr
class WireAction * m_sendBackwardWireAct = nullptr
QAction * m_sendToBackAct = nullptr
class WireAction * m_sendToBackWireAct = nullptr
QAction * m_setBackgroundColorAct = nullptr
QAction * m_setGridSizeAct = nullptr
QAction * m_setGroundFillKeepoutAct = nullptr
QAction * m_setGroundFillSeedsAct = nullptr
class ConnectorItemAction * m_setOneGroundFillSeedAct = nullptr
QString m_settingsPrefix
QTimer m_setUpDockManagerTimer
QAction * m_shareOnlineAct = nullptr
QAction * m_showAllLayersAct = nullptr
QAction * m_showBreadboardAct = nullptr
QAction * m_showGridAct = nullptr
QAction * m_showPartLabelAct = nullptr
QAction * m_showPartsBinIconViewAct = nullptr
QAction * m_showPartsBinListViewAct = nullptr
QAction * m_showPCBAct = nullptr
QAction * m_showProgramAct = nullptr
QAction * m_showSchematicAct = nullptr
QAction * m_showUnroutedAct = nullptr
QAction * m_showWelcomeAct = nullptr
QPointer< class FSizeGrip > m_sizeGrip
QPointer< class SketchModel > m_sketchModel
QAction * m_stickyAct = nullptr
QAction * m_swapObsoleteAct = nullptr
SwapTimer m_swapTimer
QPointer< QWidget > m_tabWidget
QAction * m_testConnectorsAction = nullptr
QAction * m_tidyWiresAct = nullptr
QAction * m_tipsAndTricksAct = nullptr
QAction * m_toggleDebuggerOutputAct = nullptr
QAction * m_toggleInfoAct = nullptr
QAction * m_togglePartLibraryAct = nullptr
QAction * m_toggleUndoHistoryAct = nullptr
QPointer< QToolBar > m_toolbar
FDockWidget * m_topDock = nullptr
QAction * m_undoAct = nullptr
QUndoGroup * m_undoGroup = nullptr
QUndoView * m_undoView = nullptr
QAction * m_updateRoutingStatusAct = nullptr
bool m_useOldSchematic = false
QAction * m_viewFromAboveAct = nullptr
QAction * m_viewFromBelowAct = nullptr
QAction * m_viewFromBelowToggleAct = nullptr
QStackedWidget * m_viewFromButtonWidget = nullptr
QMenu * m_viewMenu = nullptr
QAction * m_visitFritzingDotOrgAct = nullptr
class WelcomeView * m_welcomeView = nullptr
QPointer< SketchAreaWidget > m_welcomeWidget
QMenu * m_windowMenu = nullptr
QAction * m_windowMenuSeparator = nullptr
QAction * m_zoomInAct = nullptr
QAction * m_zoomInShortcut = nullptr
QAction * m_zoomOutAct = nullptr
QPointer< class ZoomSlider > m_zoomSlider
QMenu * m_zOrderMenu = nullptr
QMenu * m_zOrderWireMenu = nullptr
Protected Attributes inherited from FritzingWindow
QAction * m_closeAct = nullptr
QString m_fwFilename
bool m_readOnly = false
QStatusBar * m_statusBar = nullptr
QDir m_tempDir
class WaitPushUndoStack * m_undoStack = nullptr
Additional Inherited Members
Static Public Member Functions inherited from MainWindow
static void initNames ()
static MainWindow * newMainWindow (ReferenceModel *referenceModel, const QString &displayPath, bool showProgress, bool lockFiles, int initialTab)
static void setAutosaveEnabled (bool)
static void setAutosavePeriod (int)
Static Public Member Functions inherited from FritzingWindow
static bool alreadyHasExtension (const QString &fileName, const QString &extension=___emptyString___)
Static Public Attributes inherited from MainWindow
static bool AutosaveEnabled = true
static int AutosaveTimeoutMinutes = 10
static QString BackupFolder
static const int DockMinHeight = 30
static const int DockMinWidth = 130
Static Public Attributes inherited from FritzingWindow
static const QString QtFunkyPlaceholder = QLatin1String("[*]")
static QString ReadOnlyPlaceholder
Protected Types inherited from MainWindow
enum { MaxRecentFiles = 10 }
Static Protected Member Functions inherited from MainWindow
static void removeActionsStartingAt (QMenu *menu, int start=0)
static void setAutosave (int, bool)
Static Protected Attributes inherited from MainWindow
static int CascadeFactorX = 21
static int CascadeFactorY = 19
static QRegExp GuidMatcher = QRegExp("[A-Fa-f0-9]{32}")
static int UntitledSketchIndex = 1
static const QString UntitledSketchName = "Untitled Sketch"
Static Protected Attributes inherited from FritzingWindow
static QStringList OtherKnownExtensions
Properties inherited from MainWindow
int fireQuoteDelay
Constructor & Destructor Documentation
PEMainWindow()
PEMainWindow::PEMainWindow (ReferenceModel * referenceModel, QWidget * parent)
References backupSketch(), ViewLayer::BreadboardView, FolderUtils::getUserPartsPath(), ViewLayer::IconView, MainWindow::m_autosaveTimer, MainWindow::m_settingsPrefix, m_userPartsFolderPath, m_userPartsFolderSvgPath, m_viewThings, ViewLayer::PCBView, and ViewLayer::SchematicView.
~PEMainWindow()
PEMainWindow::~PEMainWindow ()
References killPegi(), m_filesToDelete, and makeDirName().
Member Function Documentation
activeLayerWidgetAlwaysOn()
bool PEMainWindow::activeLayerWidgetAlwaysOn () protected virtual
Reimplemented from MainWindow.
addBusConnector()
void PEMainWindow::addBusConnector (const QString & busID, const QString & connectorID)
References ItemBase::buses(), displayBuses(), findBus(), m_fzpDocument, and removeBusConnector().
addTab()
void PEMainWindow::addTab (QWidget * widget, const QString & label) protected virtual
Reimplemented from MainWindow.
References ItemBase::label(), and MainWindow::m_tabWidget.
addToMyPartsSignal
void PEMainWindow::addToMyPartsSignal (ModelPart * , const QStringList &) signal
anyMarquee()
bool PEMainWindow::anyMarquee () protected
References getPegiList(), MainWindow::m_currentGraphicsView, and PEGraphicsItem::showingMarquee().
anyVisible()
bool PEMainWindow::anyVisible () protected
References MainWindow::m_currentGraphicsView.
backupSketch
void PEMainWindow::backupSketch () protected slot
breadboardItemMenu()
QMenu * PEMainWindow::breadboardItemMenu () protected virtual
Reimplemented from MainWindow.
breadboardWireMenu()
QMenu * PEMainWindow::breadboardWireMenu () protected virtual
Reimplemented from MainWindow.
References m_deleteBusConnectionAct, and updateWireMenu().
busModeChanged
void PEMainWindow::busModeChanged (bool state) slot
References ViewThing::busMode, deleteBuses(), displayBuses(), PEGraphicsItem::element(), PEToolView::enableConnectorChanges(), ViewLayer::getConnectorPElement(), getPegiList(), SketchWidget::hideConnectors(), ViewThing::itemBase, m_connectorList, MainWindow::m_currentGraphicsView, m_fzpDocument, m_peToolView, m_viewThings, reload(), ItemBase::showConnectors(), ViewThing::sketchWidget, and SketchWidget::viewID().
canSave()
bool PEMainWindow::canSave () protected
References m_canSave.
changeConnectorElement()
void PEMainWindow::changeConnectorElement (QDomElement & connector, ConnectorMetadata * cmd) protected
References ConnectorMetadata::connectorDescription, ConnectorMetadata::connectorID, ConnectorMetadata::connectorName, Connector::connectorNameFromType(), ConnectorMetadata::connectorType, DebugDialog::debug(), and TextUtils::replaceElementChildText().
changeConnectorMetadata()
void PEMainWindow::changeConnectorMetadata (ConnectorMetadata * cmd, bool updateDisplay)
References changeConnectorElement(), ConnectorMetadata::connectorID, findConnector(), initConnectors(), m_peToolView, and PEToolView::setCurrentConnector().
changeMetadata()
void PEMainWindow::changeMetadata (const QString & name, const QString & value, bool updateDisplay)
References PEMetadataView::initMetadata(), m_fzpDocument, m_metadataView, and TextUtils::replaceElementChildText().
changeOriginalFile()
void PEMainWindow::changeOriginalFile (ViewLayer::ViewID viewID, const QString originalFile, int changeCount)
changeProperties()
void PEMainWindow::changeProperties (const QHash< QString, QString > & newProperties, bool updateDisplay)
References PEMetadataView::initMetadata(), m_fzpDocument, m_metadataView, ItemBase::prop(), and TextUtils::replaceChildText().
changeReferenceFile()
void PEMainWindow::changeReferenceFile (ViewLayer::ViewID viewID, const QString referenceFile)
References DebugDialog::debug(), m_viewThings, ViewThing::referenceFile, and ItemBase::viewID().
changeSMD()
void PEMainWindow::changeSMD (const QString & smd, const QString & filename, int changeDirection)
References changeSvg(), TextUtils::findElementWithAttribute(), layers(), m_fzpDocument, MainWindow::m_pcbGraphicsView, MainWindow::pcbView(), and setConnectorSMD().
changeSpecialProperty()
void PEMainWindow::changeSpecialProperty (const QString & name, const QString & value) protected
References changeProperties(), getOldProperties(), m_metadataView, FritzingWindow::m_undoStack, SketchWidget::PropChangeDelay, PEMetadataView::resetProperty(), BaseCommand::setSkipFirstRedo(), and WaitPushUndoStack::waitPush().
changeSvg()
void PEMainWindow::changeSvg (SketchWidget * sketchWidget, const QString & filename, int changeDirection)
References ViewThing::itemBase, ItemBase::layerKin(), m_fzpDocument, m_viewThings, reload(), setImageAttribute(), updateChangeCount(), and SketchWidget::viewID().
changeTags()
void PEMainWindow::changeTags (const QStringList & newTags, bool updateDisplay)
References PEMetadataView::initMetadata(), m_fzpDocument, m_metadataView, and TextUtils::replaceChildText().
clearPickMode()
void PEMainWindow::clearPickMode () protected
References MainWindow::m_currentGraphicsView, m_inPickMode, m_useNextPick, and PEGraphicsItem::setPickAppearance().
clickedItemCandidateSlot
void PEMainWindow::clickedItemCandidateSlot (QGraphicsItem * item, bool & ok) protected slot
References PEGraphicsItem::showingMarquee().
closeEvent()
void PEMainWindow::closeEvent (QCloseEvent * event) protected
References FritzingWindow::beforeClosing(), connectorWarning(), event(), PEMetadataView::family(), ItemBase::family(), m_inFocusWidgets, m_metadataView, MainWindow::m_settingsPrefix, PEMetadataView::properties(), and ItemBase::saveGeometry().
closeLater
void PEMainWindow::closeLater () protected slot
connectorCountChanged
void PEMainWindow::connectorCountChanged (int newCount) slot
References byID(), IntegerFinder(), m_fzpDocument, m_removedConnector, FritzingWindow::m_undoStack, SketchWidget::PropChangeDelay, removedConnectorsAux(), TextUtils::replaceChildText(), saveFzp(), and WaitPushUndoStack::waitPush().
connectorMetadataChanged
void PEMainWindow::connectorMetadataChanged (struct ConnectorMetadata * cmd) slot
References changeConnectorElement(), ConnectorMetadata::connectorID, ConnectorMetadata::connectorName, fillInMetadata(), findConnector(), initConnectors(), m_connectorsView, FritzingWindow::m_undoStack, SketchWidget::PropChangeDelay, BaseCommand::setSkipFirstRedo(), and WaitPushUndoStack::waitPush().
connectorsTypeChanged
void PEMainWindow::connectorsTypeChanged (Connector::ConnectorType ct) slot
References Connector::connectorNameFromType(), ConnectorMetadata::connectorType, fillInMetadata(), m_fzpDocument, FritzingWindow::m_undoStack, SketchWidget::PropChangeDelay, and WaitPushUndoStack::waitPush().
connectorWarning()
void PEMainWindow::connectorWarning () protected
References TextUtils::findElementWithAttribute(), ViewLayer::getConnectorSvgIDs(), ViewLayer::IconView, m_fzpDocument, m_viewThings, and ItemBase::viewID().
connectPairs()
void PEMainWindow::connectPairs () protected virtual
Reimplemented from MainWindow.
References MainWindow::cursorLocationSlot(), MainWindow::m_breadboardGraphicsView, MainWindow::m_pcbGraphicsView, MainWindow::m_schematicGraphicsView, and MainWindow::setActiveWire().
convertToTenth
void PEMainWindow::convertToTenth () protected slot
References ItemBase::filename(), ViewThing::itemBase, MainWindow::m_currentGraphicsView, FritzingWindow::m_undoStack, m_userPartsFolderSvgPath, m_viewThings, makeSvgPath2(), S2S::onefzp(), SketchWidget::PropChangeDelay, s2sMessageSlot(), saveFzp(), ViewLayer::SchematicView, and WaitPushUndoStack::waitPush().
createActions()
void PEMainWindow::createActions () protected virtual
Reimplemented from MainWindow.
References convertToTenth(), MainWindow::createActiveLayerActions(), MainWindow::createEditMenuActions(), createFileMenuActions(), MainWindow::createHelpMenuActions(), createViewMenuActions(), MainWindow::createWindowMenuActions(), deleteBusConnection(), loadImage(), m_convertToTenthAct, m_deleteBusConnectionAct, MainWindow::m_openAct, m_showInOSAct, MainWindow::mainLoad(), and showInOS().
createEditMenu()
void PEMainWindow::createEditMenu () protected virtual
Reimplemented from MainWindow.
References m_convertToTenthAct, MainWindow::m_editMenu, MainWindow::m_redoAct, MainWindow::m_undoAct, and updateEditMenu().
createFileMenu()
void PEMainWindow::createFileMenu () protected virtual
Reimplemented from MainWindow.
References FritzingWindow::m_closeAct, MainWindow::m_exportMenu, MainWindow::m_fileMenu, MainWindow::m_openAct, MainWindow::m_printAct, MainWindow::m_quitAct, m_reuseBreadboardAct, m_reusePCBAct, m_reuseSchematicAct, MainWindow::m_saveAct, MainWindow::m_saveAsAct, m_showInOSAct, MainWindow::populateExportMenu(), and updateFileMenu().
createFileMenuActions()
void PEMainWindow::createFileMenuActions () protected virtual
Reimplemented from MainWindow.
References MainWindow::createFileMenuActions(), m_reuseBreadboardAct, m_reusePCBAct, m_reuseSchematicAct, reuseBreadboard(), reusePCB(), and reuseSchematic().
createMenus()
void PEMainWindow::createMenus () protected virtual
Reimplemented from MainWindow.
References createEditMenu(), createFileMenu(), MainWindow::createHelpMenu(), createViewMenu(), and MainWindow::createWindowMenu().
createSvgFromImage()
QString PEMainWindow::createSvgFromImage (const QString & origFilePath) protected
References GedaElement2Svg::convert(), KicadModule2Svg::convert(), KicadSchematic2Svg::convert(), KicadSchematic2Svg::listDefs(), KicadModule2Svg::listModules(), and KicadModuleDialog::selectedModule().
createTabWidget()
QWidget * PEMainWindow::createTabWidget () protected virtual
Reimplemented from MainWindow.
createViewMenu()
void PEMainWindow::createViewMenu () protected virtual
Reimplemented from MainWindow.
References MainWindow::createViewMenu(), m_hideOtherViewsAct, MainWindow::m_numFixedActionsInViewMenu, MainWindow::m_setBackgroundColorAct, m_showConnectorsViewAct, m_showIconAct, m_showMetadataViewAct, MainWindow::m_showPCBAct, and MainWindow::m_viewMenu.
createViewMenuActions()
void PEMainWindow::createViewMenuActions (bool showWelcome) protected virtual
Reimplemented from MainWindow.
References MainWindow::createViewMenuActions(), hideOtherViews(), m_hideOtherViewsAct, m_showConnectorsViewAct, m_showIconAct, m_showMetadataViewAct, showConnectorsView(), showIconView(), and showMetadataView().
currentTabIndex()
int PEMainWindow::currentTabIndex () protected virtual
Reimplemented from MainWindow.
References MainWindow::m_tabWidget.
currentTabWidget()
QWidget * PEMainWindow::currentTabWidget () protected virtual
Reimplemented from MainWindow.
References MainWindow::m_tabWidget.
deleteBusConnection
void PEMainWindow::deleteBusConnection () slot
References ItemBase::buses(), Wire::collectChained(), TextUtils::findElementWithAttribute(), m_fzpDocument, FritzingWindow::m_undoStack, SketchWidget::PropChangeDelay, WaitPushUndoStack::waitPush(), and WireAction::wire().
deleteBuses()
void PEMainWindow::deleteBuses () protected
References m_viewThings, and ViewThing::sketchWidget.
displayBuses()
void PEMainWindow::displayBuses () protected
References ItemBase::buses(), deleteBuses(), ItemBase::findConnectorItemWithSharedID(), ViewThing::itemBase, m_fzpDocument, m_viewThings, SketchWidget::makeOneRatsnestWire(), RatZ, ViewThing::sketchWidget, ItemBase::viewID(), and ItemBase::viewLayerPlacement().
editsModuleID()
bool PEMainWindow::editsModuleID (const QString & moduleID)
References m_originalModuleID, and ItemBase::moduleID().
event()
bool PEMainWindow::event (QEvent * e) protected
References MainWindow::event().
eventFilter()
bool PEMainWindow::eventFilter (QObject * object, QEvent * event) protected
References clearPickMode(), event(), m_inFocusWidgets, m_inPickMode, m_useNextPick, and resetNextPick().
fillInMetadata()
void PEMainWindow::fillInMetadata (const QDomElement & connector, ConnectorMetadata & cmd) protected
References ConnectorMetadata::connectorDescription, ConnectorMetadata::connectorID, ConnectorMetadata::connectorName, ConnectorMetadata::connectorType, and Connector::connectorTypeFromName().
findBus()
QDomElement PEMainWindow::findBus (const QDomElement & buses, const QString & id) protected
References ItemBase::buses().
findConnector()
QDomElement PEMainWindow::findConnector (const QString & id, int & index) protected
References m_fzpDocument.
findConnectorItem()
PEGraphicsItem * PEMainWindow::findConnectorItem () protected
References PEToolView::currentConnectorIndex(), PEGraphicsItem::element(), ViewLayer::getConnectorSvgIDs(), getPegiList(), m_connectorList, MainWindow::m_currentGraphicsView, and m_peToolView.
findNodeMemberBus()
QDomElement PEMainWindow::findNodeMemberBus (const QDomElement & buses, const QString & connectorID) protected
References ItemBase::buses().
getButtonsForView()
QList< QWidget * > PEMainWindow::getButtonsForView (ViewLayer::ViewID viewID) protected virtual
Reimplemented from MainWindow.
References ViewLayer::BreadboardView, MainWindow::m_breadboardWidget, MainWindow::m_pcbWidget, MainWindow::m_schematicWidget, ViewLayer::PCBView, ViewLayer::SchematicView, and ItemBase::viewID().
getOldProperties()
QHash< QString, QString > PEMainWindow::getOldProperties () protected
References m_fzpDocument, and ItemBase::prop().
getPartTitle()
QString PEMainWindow::getPartTitle () protected
References ViewThing::itemBase, m_fzpDocument, m_viewThings, and ItemBase::title().
getPegiList()
QList< PEGraphicsItem * > PEMainWindow::getPegiList (SketchWidget * sketchWidget) protected
getPixelBounds()
QRectF PEMainWindow::getPixelBounds (FSvgRenderer & renderer, QDomElement & element) protected
References FSvgRenderer::defaultSizeF().
getSpinAmount
void PEMainWindow::getSpinAmount (double & amount) slot
References MainWindow::m_currentGraphicsView, and qMin().
getSvgReferenceFile()
QString PEMainWindow::getSvgReferenceFile (const QString & filename) protected
References ReferenceFileString().
hideOtherViews
void PEMainWindow::hideOtherViews () protected slot
References ViewLayer::BreadboardView, ItemBase::filename(), MainWindow::m_currentGraphicsView, m_fzpDocument, FritzingWindow::m_undoStack, m_viewThings, ViewLayer::PCBView, SketchWidget::PropChangeDelay, saveFzp(), ViewLayer::SchematicView, ItemBase::viewID(), ViewLayer::viewIDXmlName(), and WaitPushUndoStack::waitPush().
highlightSlot
void PEMainWindow::highlightSlot (PEGraphicsItem * pegi) slot
References anyMarquee(), anyVisible(), PEToolView::enableConnectorChanges(), PESvgView::highlightElement(), m_connectorList, m_peSvgView, m_peToolView, and PEGraphicsItem::showingMarquee().
initConnectors()
void PEMainWindow::initConnectors (bool updateConnectorsView) protected
References byID(), PEConnectorsView::initConnectors(), PEToolView::initConnectors(), m_connectorList, m_connectorsView, m_fzpDocument, m_peToolView, and updateAssignedConnectors().
initDock()
void PEMainWindow::initDock () protected virtual
Reimplemented from MainWindow.
References MainWindow::m_layerPalette.
initLockedFiles()
void PEMainWindow::initLockedFiles (bool lockFiles) protected virtual
Reimplemented from MainWindow.
initProgrammingWidget()
void PEMainWindow::initProgrammingWidget () protected virtual
Reimplemented from MainWindow.
initSketchWidgets()
void PEMainWindow::initSketchWidgets (bool withIcons) protected virtual
Reimplemented from MainWindow.
References addTab(), clickedItemCandidateSlot(), connectorCountChanged(), connectorMetadataChanged(), connectorsTypeChanged(), ViewThing::document, ViewThing::everZoomed, ViewThing::firstTime, ViewLayer::IconView, MainWindow::initSketchWidget(), MainWindow::initSketchWidgets(), itemAddedSlot(), itemMovedSlot(), m_breadboardDocument, MainWindow::m_breadboardGraphicsView, m_connectorsView, m_iconDocument, m_iconGraphicsView, m_iconWidget, m_metadataView, m_pcbDocument, MainWindow::m_pcbGraphicsView, m_schematicDocument, MainWindow::m_schematicGraphicsView, m_viewThings, metadataChanged(), newWireSlot(), propertiesChanged(), removedConnectors(), resizedSlot(), ZoomableGraphicsView::setAcceptWheelEvents(), SketchWidget::setChainDrag(), showing(), ViewThing::sketchWidget, smdChanged(), and tagsChanged().
initSvgTree()
void PEMainWindow::initSvgTree (SketchWidget * sketchWidget, ItemBase * itemBase, QDomDocument & svgDocument) protected
References DebugDialog::debug(), ItemBase::filename(), TextUtils::findElementWithAttribute(), ViewLayer::getConnectorSvgIDs(), getPixelBounds(), TextUtils::gornTree(), FSvgRenderer::loadSvg(), m_fzpDocument, makePegi(), ViewLayer::PCBView, PegiZ, PEGraphicsItem::setTerminalPoint(), PEGraphicsItem::showTerminalPoint(), ItemBase::viewID(), SketchWidget::viewID(), and ItemBase::z().
initWelcomeView()
void PEMainWindow::initWelcomeView () protected virtual
Reimplemented from MainWindow.
initZoom
void PEMainWindow::initZoom () protected slot
References ViewThing::everZoomed, ViewThing::itemBase, MainWindow::m_currentGraphicsView, m_peSvgView, m_peToolView, m_viewThings, ViewThing::referenceFile, and PESvgView::setFilename().
insertDesc()
void PEMainWindow::insertDesc (const QString & referenceFile, QString & svg) protected
References makeDesc(), and ReferenceFileString().
itemAddedSlot
void PEMainWindow::itemAddedSlot (ModelPart * , ItemBase * itemBase, ViewLayer::ViewLayerPlacement , const ViewGeometry & , long id, SketchWidget * dropOrigin) protected slot
References ItemBase::boundingRect(), getPegiList(), MainWindow::m_currentGraphicsView, makePegi(), ItemBase::viewID(), and ItemBase::z().
itemMovedSlot
void PEMainWindow::itemMovedSlot (ItemBase * itemBase) protected slot
References getPegiList(), PEGraphicsItem::itemBase(), MainWindow::m_currentGraphicsView, PEGraphicsItem::offset(), and ItemBase::viewID().
killPegi()
void PEMainWindow::killPegi () protected
References m_viewThings, and ViewThing::sketchWidget.
loadFzp()
bool PEMainWindow::loadFzp (const QString & path) protected
References m_fzpDocument.
loadImage
void PEMainWindow::loadImage () protected slot
References createSvgFromImage(), ItemBase::filename(), TextUtils::findElementWithAttribute(), TextUtils::fixFonts(), TextUtils::fixMuch(), FolderUtils::getOpenFileName(), getSvgReferenceFile(), insertDesc(), InstalledFonts::InstalledFontsList, ViewThing::itemBase, MainWindow::m_currentGraphicsView, MainWindow::m_pcbGraphicsView, FritzingWindow::m_undoStack, m_userPartsFolderSvgPath, m_viewThings, makeSvgPath2(), FolderUtils::openSaveFolder(), ViewLayer::PCBView, SketchWidget::PropChangeDelay, removeGorn(), WaitPushUndoStack::waitPush(), and writeXml().
makeDesc()
QString PEMainWindow::makeDesc (const QString & referenceFile) protected
References ReferenceFileString().
makeDirName()
QString PEMainWindow::makeDirName () protected
References m_guid.
makeNewVariant()
QString PEMainWindow::makeNewVariant (const QString & family) protected
References ItemBase::family(), and MainWindow::m_referenceModel.
makePegi()
PEGraphicsItem * PEMainWindow::makePegi (QSizeF size, QPointF topLeft, ItemBase * itemBase, QDomElement & element, double z) protected
References highlightSlot(), pegiMousePressed(), pegiMouseReleased(), pegiTerminalPointChanged(), pegiTerminalPointMoved(), PEGraphicsItem::setElement(), PEGraphicsItem::setOffset(), PEGraphicsItem::showTerminalPoint(), terminalPointChanged(), and ItemBase::z().
makeSvgPath2()
QString PEMainWindow::makeSvgPath2 (SketchWidget * sketchWidget) protected
References m_fileIndex, m_guid, m_prefix, SketchWidget::viewID(), and ViewLayer::viewIDNaturalName().
metadataChanged
void PEMainWindow::metadataChanged (const QString & name, const QString & value) slot
References changeMetadata(), changeSpecialProperty(), PEMetadataView::family(), ItemBase::family(), m_canSave, m_fzpDocument, m_metadataView, MainWindow::m_referenceModel, FritzingWindow::m_undoStack, ItemBase::moduleID(), SketchWidget::PropChangeDelay, BaseCommand::setSkipFirstRedo(), and WaitPushUndoStack::waitPush().
moreInitDock()
void PEMainWindow::moreInitDock () protected virtual
Reimplemented from MainWindow.
References busModeChanged(), connectorMetadataChanged(), MainWindow::DockMinHeight, MainWindow::DockMinWidth, getSpinAmount(), InfoViewHeightDefault, InfoViewMinHeight, MainWindow::m_binManager, MainWindow::m_hideAllLayersAct, MainWindow::m_infoView, MainWindow::m_layerPalette, m_peSvgView, m_peToolView, MainWindow::m_showAllLayersAct, MainWindow::makeDock(), pickModeChanged(), removedConnector(), switchedConnector(), terminalPointChanged(), and BinManager::Title.
moveTerminalPoint()
void PEMainWindow::moveTerminalPoint (SketchWidget * sketchWidget, const QString & id, QSizeF size, QPointF p, int changeDirection)
References DebugDialog::debug(), ViewThing::document, PEGraphicsItem::element(), FakeGornSiblingNumber, TextUtils::findElementWithAttribute(), ViewLayer::getConnectorPElement(), getPegiList(), ViewThing::itemBase, FSvgRenderer::loadSvg(), m_fzpDocument, m_peToolView, m_userPartsFolderSvgPath, m_viewThings, makePegi(), makeSvgPath2(), PEGraphicsItem::offset(), removeGorn(), setImageAttribute(), PEGraphicsItem::setTerminalPoint(), PEToolView::setTerminalPointCoords(), TextUtils::svgNSOnly(), updateChangeCount(), SketchWidget::viewID(), and writeXml().
newWireSlot
void PEMainWindow::newWireSlot (Wire * wire) slot
References m_viewThings, Wire::setDisplayBendpointCursor(), ItemBase::viewID(), and wireChangedSlot().
pcbItemMenu()
QMenu * PEMainWindow::pcbItemMenu () protected virtual
Reimplemented from MainWindow.
pcbWireMenu()
QMenu * PEMainWindow::pcbWireMenu () protected virtual
Reimplemented from MainWindow.
References breadboardWireMenu().
pegiMousePressed
void PEMainWindow::pegiMousePressed (PEGraphicsItem * pegi, bool & ignore) slot
References PEToolView::currentConnectorIndex(), PEGraphicsItem::element(), ViewLayer::getConnectorPElement(), ItemBase::id(), ViewThing::itemBase, PEGraphicsItem::itemBase(), m_connectorList, MainWindow::m_currentGraphicsView, m_fzpDocument, m_peToolView, m_useNextPick, m_viewThings, relocateConnector(), and PEToolView::setCurrentConnector().
pegiMouseReleased
void PEMainWindow::pegiMouseReleased (PEGraphicsItem *) slot
pegiTerminalPointChanged
void PEMainWindow::pegiTerminalPointChanged (PEGraphicsItem * pegi, QPointF before, QPointF after) slot
References terminalPointChangedAux().
pegiTerminalPointMoved
void PEMainWindow::pegiTerminalPointMoved (PEGraphicsItem * pegi, QPointF p) slot
References m_peToolView, and PEToolView::setTerminalPointCoords().
pickModeChanged
void PEMainWindow::pickModeChanged (bool state) slot
References MainWindow::m_currentGraphicsView, m_inPickMode, and PEGraphicsItem::setPickAppearance().
propertiesChanged
void PEMainWindow::propertiesChanged (const QHash< QString, QString > & newProperties) slot
References changeProperties(), getOldProperties(), FritzingWindow::m_undoStack, SketchWidget::PropChangeDelay, BaseCommand::setSkipFirstRedo(), and WaitPushUndoStack::waitPush().
reload()
void PEMainWindow::reload (bool firstTime) protected
References CursorMaster::addCursor(), PEToolView::currentConnectorIndex(), ViewThing::document, ViewThing::everZoomed, ItemBase::filename(), ModelPart::flippedSMD(), ItemBase::getNextID(), getSvgReferenceFile(), SketchWidget::hideConnectors(), initConnectors(), PEMetadataView::initMetadata(), initSvgTree(), initZoom(), CursorMaster::instance(), ViewThing::itemBase, killPegi(), MainWindow::m_breadboardGraphicsView, m_connectorsView, MainWindow::m_currentGraphicsView, m_fzpDocument, m_iconGraphicsView, m_metadataView, MainWindow::m_pcbGraphicsView, m_peToolView, MainWindow::m_schematicGraphicsView, m_viewThings, ItemBase::modelPart(), ModelPart::Part, ViewThing::referenceFile, CursorMaster::removeCursor(), saveFzp(), ItemBase::setAcceptsMousePressLegEvent(), ViewGeometry::setLoc(), PEConnectorsView::setSMD(), ItemBase::setSwappable(), showing(), BaseCommand::SingleView, ViewThing::sketchWidget, switchedConnector(), and ItemBase::viewID().
relocateConnector()
void PEMainWindow::relocateConnector (PEGraphicsItem * pegi) protected
References PEToolView::currentConnectorIndex(), PEGraphicsItem::element(), TextUtils::findElementWithAttribute(), ViewLayer::getConnectorSvgIDs(), m_connectorList, MainWindow::m_currentGraphicsView, m_fzpDocument, m_peToolView, FritzingWindow::m_undoStack, m_viewThings, SketchWidget::PropChangeDelay, and WaitPushUndoStack::waitPush().
relocateConnectorSvg()
void PEMainWindow::relocateConnectorSvg (SketchWidget * sketchWidget, const QString & id, const QString & terminalID, const QString & oldGorn, const QString & oldGornTerminal, const QString & newGorn, const QString & newGornTerminal, int changeDirection)
References PEToolView::currentConnectorIndex(), ViewThing::document, PEGraphicsItem::element(), TextUtils::findElementWithAttribute(), ViewLayer::getConnectorPElement(), ViewLayer::getConnectorSvgIDs(), m_fzpDocument, m_peToolView, m_userPartsFolderSvgPath, m_viewThings, makeSvgPath2(), removeGorn(), PEGraphicsItem::setHighlighted(), setImageAttribute(), PEGraphicsItem::showMarquee(), PEGraphicsItem::showTerminalPoint(), TextUtils::svgNSOnly(), switchedConnector(), updateAssignedConnectors(), updateChangeCount(), ItemBase::viewID(), SketchWidget::viewID(), and writeXml().
removeBusConnector()
void PEMainWindow::removeBusConnector (const QString & busID, const QString & connectorID, bool display)
References ItemBase::buses(), displayBuses(), and m_fzpDocument.
removedConnector
void PEMainWindow::removedConnector (const QDomElement & element) slot
References removedConnectorsAux().
removedConnectors
void PEMainWindow::removedConnectors (QList< ConnectorMetadata * > & cmdList) slot
References ConnectorMetadata::connectorID, findConnector(), ConnectorMetadata::index, and removedConnectorsAux().
removedConnectorsAux()
void PEMainWindow::removedConnectorsAux (QList< QDomElement > & connectors) protected
References m_removedConnector, FritzingWindow::m_undoStack, SketchWidget::PropChangeDelay, saveFzp(), and WaitPushUndoStack::waitPush().
replaceProperty()
void PEMainWindow::replaceProperty (const QString & key, const QString & value, QDomElement & properties) protected
References m_fzpDocument, ItemBase::prop(), and TextUtils::replaceChildText().
resetNextPick
void PEMainWindow::resetNextPick () protected slot
References m_useNextPick.
resizedSlot
void PEMainWindow::resizedSlot (ItemBase * itemBase) protected slot
References ItemBase::boundingRect(), getPegiList(), PEGraphicsItem::itemBase(), MainWindow::m_currentGraphicsView, PEGraphicsItem::offset(), and ItemBase::viewID().
restoreFzp()
void PEMainWindow::restoreFzp (const QString & filename)
References loadFzp(), and reload().
reuseBreadboard
void PEMainWindow::reuseBreadboard () protected slot
References ViewLayer::BreadboardView, and reuseImage().
reuseImage()
void PEMainWindow::reuseImage (ViewLayer::ViewID viewID) protected
References ItemBase::filename(), ViewThing::itemBase, MainWindow::m_currentGraphicsView, FritzingWindow::m_undoStack, m_viewThings, SketchWidget::PropChangeDelay, ItemBase::viewID(), and WaitPushUndoStack::waitPush().
reusePCB
void PEMainWindow::reusePCB () protected slot
References ViewLayer::PCBView, and reuseImage().
reuseSchematic
void PEMainWindow::reuseSchematic () protected slot
References reuseImage(), and ViewLayer::SchematicView.
s2sMessageSlot
void PEMainWindow::s2sMessageSlot (const QString & message) slot
save
bool PEMainWindow::save () protected slot
References canSave(), and saveAs().
saveAs() [1/2]
bool PEMainWindow::saveAs (bool overWrite) protected
References addToMyPartsSignal(), ViewLayer::Copper0, ViewLayer::Copper1, ViewThing::document, PEMetadataView::family(), ItemBase::family(), TextUtils::findElementWithAttribute(), TextUtils::getSvgSizes(), insertDesc(), ViewThing::itemBase, ItemBase::layerKinChief(), layers(), MainWindow::m_autosaveNeeded, m_canSave, m_fileIndex, m_fzpDocument, m_gaveSaveWarning, m_guid, m_metadataView, m_originalFzpPath, m_originalModuleID, m_prefix, MainWindow::m_referenceModel, FritzingWindow::m_undoStack, m_userPartsFolderPath, m_userPartsFolderSvgPath, m_viewThings, makeNewVariant(), makeSvgPath2(), ItemBase::modelPart(), WaitPushUndoStack::push(), ViewThing::referenceFile, removeGorn(), removeID(), replaceProperty(), PEMetadataView::resetProperty(), ItemBase::retrieveSvg(), ModelPart::setAlien(), setImageAttribute(), ViewThing::sketchWidget, GraphicsUtils::SVGDPI, MainWindow::updateParts(), MainWindow::updatePartsBin(), MainWindow::usesPart(), PEMetadataView::variant(), ItemBase::viewID(), ViewLayer::viewIDXmlName(), ItemBase::viewLayerID(), SketchWidget::viewLayers(), ViewLayer::viewLayerXmlNameFromID(), and writeXml().
saveAs [2/2]
bool PEMainWindow::saveAs () protected slot
saveFzp()
QString PEMainWindow::saveFzp () protected
References DebugDialog::debug(), m_fileIndex, m_fzpDocument, m_guid, m_prefix, makeDirName(), and writeXml().
schematicItemMenu()
QMenu * PEMainWindow::schematicItemMenu () protected virtual
Reimplemented from MainWindow.
schematicWireMenu()
QMenu * PEMainWindow::schematicWireMenu () protected virtual
Reimplemented from MainWindow.
References breadboardWireMenu().
setBeforeClosingText()
void PEMainWindow::setBeforeClosingText (const QString & filename, QMessageBox & messageBox) protected virtual
Reimplemented from FritzingWindow.
References getPartTitle().
setConnectorSMD()
void PEMainWindow::setConnectorSMD (bool toSMD, QDomElement & connector) protected
References DebugDialog::debug(), TextUtils::findElementWithAttribute(), and MainWindow::pcbView().
setCurrentTabIndex()
void PEMainWindow::setCurrentTabIndex (int index) protected virtual
Reimplemented from MainWindow.
References MainWindow::m_tabWidget.
setImageAttribute() [1/2]
void PEMainWindow::setImageAttribute (QDomElement & layers, const QString & image) protected
References layers(), m_fzpDocument, ViewLayer::UnknownLayer, and ViewLayer::viewLayerXmlNameFromID().
setImageAttribute() [2/2]
void PEMainWindow::setImageAttribute (QDomElement & fzpRoot, const QString & svgPath, ViewLayer::ViewID viewID) protected
References layers(), setImageAttribute(), ItemBase::viewID(), and ViewLayer::viewIDXmlName().
setInitialItem()
bool PEMainWindow::setInitialItem (PaletteItem * paletteItem)
References ModelPart::connectorLocalName(), ViewLayer::Copper0, ViewLayer::Copper1, MainWindow::createRaiseWindowActions(), DebugDialog::debug(), ItemBase::family(), ItemBase::filename(), TextUtils::findElementWithAttribute(), TextUtils::fixMuch(), getenvUser, getSvgReferenceFile(), MainWindow::GuidMatcher, ItemBase::hasCustomSVG(), insertDesc(), ViewThing::itemBase, layers(), loadFzp(), m_canSave, m_fzpDocument, m_guid, m_originalFzpPath, m_originalModuleID, MainWindow::m_pcbGraphicsView, m_prefix, MainWindow::m_referenceModel, m_userPartsFolderPath, m_userPartsFolderSvgPath, m_viewThings, makeDesc(), makeNewVariant(), TextUtils::makeSVGHeader(), makeSvgPath2(), ItemBase::modelPart(), ModelPart::moduleID(), ViewThing::originalSvgPath, ModelPart::path(), ModelPart::properties(), ViewThing::referenceFile, ReferenceFileString(), reload(), removeGorn(), TextUtils::replaceChildText(), replaceProperty(), ItemBase::retrieveSvg(), RubberBandLegWarning, setImageAttribute(), setTitle(), ViewLayer::Silkscreen0, ViewLayer::Silkscreen1, ItemBase::size(), ViewThing::sketchWidget, GraphicsUtils::StandardFritzingDPI, ViewThing::svgChangeCount, GraphicsUtils::SVGDPI, SketchWidget::viewID(), ViewLayer::viewIDXmlName(), ModelPart::viewItem(), ViewLayer::viewLayerID(), SketchWidget::viewLayers(), and writeXml().
setInitialView()
void PEMainWindow::setInitialView () protected virtual
Reimplemented from MainWindow.
References tabWidget_currentChanged().
setTitle()
void PEMainWindow::setTitle () protected virtual
Reimplemented from FritzingWindow.
References ConnectorsViewIndex, currentTabIndex(), getPartTitle(), IconViewIndex, MainWindow::m_currentGraphicsView, MetadataViewIndex, FritzingWindow::QtFunkyPlaceholder, and ItemBase::title().
showConnectorsView
void PEMainWindow::showConnectorsView () protected slot
References ConnectorsViewIndex, and setCurrentTabIndex().
showIconView
void PEMainWindow::showIconView () protected slot
References IconViewIndex, and setCurrentTabIndex().
showing
void PEMainWindow::showing (SketchWidget * sketchWidget) slot
References SketchWidget::alignOneToGrid(), ViewThing::firstTime, getPegiList(), ViewThing::itemBase, m_viewThings, PEGraphicsItem::offset(), PEGraphicsItem::setOffset(), ViewThing::sketchWidget, and SketchWidget::viewID().
showInOS() [1/2]
void PEMainWindow::showInOS (QWidget * parent, const QString & pathIn) protected
References FolderUtils::showInFolder().
showInOS [2/2]
void PEMainWindow::showInOS () protected slot
References ItemBase::filename(), ViewThing::itemBase, MainWindow::m_currentGraphicsView, and m_viewThings.
showMetadataView
void PEMainWindow::showMetadataView () protected slot
References MetadataViewIndex, and setCurrentTabIndex().
smdChanged
void PEMainWindow::smdChanged (const QString & after) slot
References ItemBase::filename(), TextUtils::findElementWithAttribute(), ViewThing::itemBase, m_pcbDocument, MainWindow::m_pcbGraphicsView, FritzingWindow::m_undoStack, m_userPartsFolderSvgPath, m_viewThings, makeSvgPath2(), ViewLayer::PCBView, SketchWidget::PropChangeDelay, removeGorn(), TextUtils::svgNSOnly(), WaitPushUndoStack::waitPush(), and writeXml().
switchedConnector [1/2]
void PEMainWindow::switchedConnector (int ix) slot
References MainWindow::m_currentGraphicsView.
switchedConnector() [2/2]
void PEMainWindow::switchedConnector (int ix, SketchWidget * sketchWidget) protected
References PEGraphicsItem::element(), ViewLayer::getConnectorSvgIDs(), getPegiList(), m_connectorList, m_peToolView, PEGraphicsItem::setHighlighted(), PEToolView::setTerminalPointCoords(), PEToolView::setTerminalPointLimits(), PEGraphicsItem::showMarquee(), PEGraphicsItem::terminalPoint(), and SketchWidget::viewID().
tabWidget_currentChanged
void PEMainWindow::tabWidget_currentChanged (int index) protected slot
References PEToolView::currentConnectorIndex(), IconViewIndex, MainWindow::m_currentGraphicsView, m_peSvgView, m_peToolView, PESvgView::setChildrenVisible(), PEToolView::setChildrenVisible(), setTitle(), switchedConnector(), MainWindow::tabWidget_currentChanged(), MainWindow::updateActiveLayerButtons(), and updateAssignedConnectors().
tagsChanged
void PEMainWindow::tagsChanged (const QStringList & newTags) slot
References changeTags(), m_fzpDocument, FritzingWindow::m_undoStack, SketchWidget::PropChangeDelay, BaseCommand::setSkipFirstRedo(), and WaitPushUndoStack::waitPush().
terminalPointChanged [1/2]
void PEMainWindow::terminalPointChanged (const QString & how) slot
References findConnectorItem(), PEGraphicsItem::terminalPoint(), and terminalPointChangedAux().
terminalPointChanged [2/2]
void PEMainWindow::terminalPointChanged (const QString & coord, double value) slot
References findConnectorItem(), qMax(), qMin(), PEGraphicsItem::terminalPoint(), and terminalPointChangedAux().
terminalPointChangedAux()
void PEMainWindow::terminalPointChangedAux (PEGraphicsItem * pegi, QPointF before, QPointF after) protected
References PEToolView::currentConnectorIndex(), m_connectorList, MainWindow::m_currentGraphicsView, m_peToolView, FritzingWindow::m_undoStack, PEGraphicsItem::pendingTerminalPoint(), SketchWidget::PropChangeDelay, PEGraphicsItem::setPendingTerminalPoint(), and WaitPushUndoStack::waitPush().
updateAssignedConnectors
void PEMainWindow::updateAssignedConnectors () protected slot
References MainWindow::m_currentGraphicsView, m_peToolView, m_viewThings, and PEToolView::showAssignedConnectors().
updateChangeCount()
void PEMainWindow::updateChangeCount (SketchWidget * sketchWidget, int changeDirection) protected
References m_viewThings, ViewThing::svgChangeCount, and SketchWidget::viewID().
updateEditMenu
void PEMainWindow::updateEditMenu () slot
References m_convertToTenthAct, MainWindow::m_currentGraphicsView, ViewLayer::SchematicView, and MainWindow::updateEditMenu().
updateExportMenu
void PEMainWindow::updateExportMenu () slot
References MainWindow::m_exportMenu.
updateFileMenu()
void PEMainWindow::updateFileMenu () protected virtual
Reimplemented from MainWindow.
References canSave(), ViewLayer::IconView, MainWindow::m_currentGraphicsView, m_reuseBreadboardAct, m_reusePCBAct, m_reuseSchematicAct, MainWindow::m_saveAct, and MainWindow::updateFileMenu().
updateLayerMenu
void PEMainWindow::updateLayerMenu (bool resetLayout = false) protected slot
References ViewLayer::BreadboardView, MainWindow::m_currentGraphicsView, m_hideOtherViewsAct, ViewLayer::PCBView, ViewLayer::SchematicView, and MainWindow::updateLayerMenu().
updateRaiseWindowAction()
void PEMainWindow::updateRaiseWindowAction () protected virtual
Reimplemented from MainWindow.
References getPartTitle(), MainWindow::m_raiseWindowAct, and ItemBase::title().
updateWindowMenu
void PEMainWindow::updateWindowMenu () protected slot
updateWireMenu
void PEMainWindow::updateWireMenu () protected slot
References MainWindow::m_activeWire, m_deleteBusConnectionAct, and WireAction::setWire().
wireChangedSlot
void PEMainWindow::wireChangedSlot (Wire * wire, const QLineF & oldLine, const QLineF & newLine, QPointF oldPos, QPointF newPos, ConnectorItem * from, ConnectorItem * to) slot
References ItemBase::buses(), ConnectorItem::connectorSharedID(), ConnectorItem::connectorSharedName(), findBus(), findNodeMemberBus(), ConnectorItem::firstConnectedToIsh(), m_fzpDocument, FritzingWindow::m_undoStack, Wire::otherConnector(), SketchWidget::PropChangeDelay, and WaitPushUndoStack::waitPush().
writeXml()
bool PEMainWindow::writeXml (const QString & path, const QString & text, bool temp) protected
References m_filesToDelete, TextUtils::svgNSOnly(), and TextUtils::writeUtf8().
Member Data Documentation
m_breadboardDocument
QDomDocument PEMainWindow::m_breadboardDocument protected
m_canSave
bool PEMainWindow::m_canSave protected
m_connectorList
QList<QDomElement> PEMainWindow::m_connectorList protected
m_connectorsView
PEConnectorsView* PEMainWindow::m_connectorsView = nullptr protected
m_convertToTenthAct
QAction* PEMainWindow::m_convertToTenthAct = nullptr protected
m_deleteBusConnectionAct
WireAction* PEMainWindow::m_deleteBusConnectionAct = nullptr protected
m_fileIndex
int PEMainWindow::m_fileIndex protected
m_filesToDelete
QStringList PEMainWindow::m_filesToDelete protected
m_fzpDocument
QDomDocument PEMainWindow::m_fzpDocument protected
m_gaveSaveWarning
bool PEMainWindow::m_gaveSaveWarning protected
m_guid
QString PEMainWindow::m_guid protected
m_hideOtherViewsAct
QAction* PEMainWindow::m_hideOtherViewsAct = nullptr protected
m_iconDocument
QDomDocument PEMainWindow::m_iconDocument protected
m_iconGraphicsView
QPointer<IconSketchWidget> PEMainWindow::m_iconGraphicsView protected
m_iconWidget
QPointer<SketchAreaWidget> PEMainWindow::m_iconWidget protected
m_inFocusWidgets
QList< QPointer<QWidget> > PEMainWindow::m_inFocusWidgets protected
m_inPickMode
bool PEMainWindow::m_inPickMode protected
m_metadataView
PEMetadataView* PEMainWindow::m_metadataView = nullptr protected
m_originalFzpPath
QString PEMainWindow::m_originalFzpPath protected
m_originalModuleID
QString PEMainWindow::m_originalModuleID protected
m_pcbDocument
QDomDocument PEMainWindow::m_pcbDocument protected
m_peSvgView
PESvgView* PEMainWindow::m_peSvgView = nullptr protected
m_peToolView
PEToolView* PEMainWindow::m_peToolView = nullptr protected
m_prefix
QString PEMainWindow::m_prefix protected
m_removedConnector
QString PEMainWindow::m_removedConnector protected
m_reuseBreadboardAct
QAction* PEMainWindow::m_reuseBreadboardAct = nullptr protected
m_reusePCBAct
QAction* PEMainWindow::m_reusePCBAct = nullptr protected
m_reuseSchematicAct
QAction* PEMainWindow::m_reuseSchematicAct = nullptr protected
m_schematicDocument
QDomDocument PEMainWindow::m_schematicDocument protected
m_showConnectorsViewAct
QAction* PEMainWindow::m_showConnectorsViewAct = nullptr protected
m_showIconAct
QAction* PEMainWindow::m_showIconAct = nullptr protected
m_showInOSAct
QAction* PEMainWindow::m_showInOSAct = nullptr protected
m_showMetadataViewAct
QAction* PEMainWindow::m_showMetadataViewAct = nullptr protected
m_useNextPick
bool PEMainWindow::m_useNextPick protected
m_userPartsFolderPath
QString PEMainWindow::m_userPartsFolderPath protected
m_userPartsFolderSvgPath
QString PEMainWindow::m_userPartsFolderSvgPath protected
m_viewThings
QHash<ViewLayer::ViewID, ViewThing *> PEMainWindow::m_viewThings protected
The documentation for this class was generated from the following files:
partseditor/pemainwindow.h
partseditor/pemainwindow.cpp