Fritzing: SvgIconWidget Class Reference
SvgIconWidget Class Reference
#include <svgiconwidget.h>
Public Member Functions
SvgIconWidget (ModelPart *, ViewLayer::ViewID, ItemBase *, bool plural)
~SvgIconWidget ()=default
ItemBase * itemBase () const noexcept
ModelPart * modelPart () const noexcept
constexpr const QString & moduleID () const noexcept
void setItemBase (ItemBase *, bool plural)
Static Public Member Functions
static void cleanup ()
static void initNames ()
Protected Member Functions
void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
void setupImage (bool plural, ViewLayer::ViewID viewID)
Protected Attributes
QPointer< ItemBase > m_itemBase
QString m_moduleId
SvgIconPixmapItem * m_pixmapItem = nullptr
Constructor & Destructor Documentation
SvgIconWidget()
SvgIconWidget::SvgIconWidget (ModelPart * modelPart, ViewLayer::ViewID viewID, ItemBase * itemBase, bool plural)
References ModelPart::instanceText(), itemBase(), ModelPart::itemType(), m_itemBase, m_moduleId, modelPart(), ModelPart::moduleID(), PluralImage, setupImage(), ModelPart::Space, ModuleIDNames::SpacerModuleIDName, and PartsBinView::TranslatedCategoryNames.
~SvgIconWidget()
SvgIconWidget::~SvgIconWidget () default
Member Function Documentation
cleanup()
void SvgIconWidget::cleanup () static
References PluralImage, and SingularImage.
hoverEnterEvent()
void SvgIconWidget::hoverEnterEvent (QGraphicsSceneHoverEvent * event) protected
References InfoGraphicsView::getInfoGraphicsView(), InfoGraphicsView::hoverEnterItem(), and m_itemBase.
hoverLeaveEvent()
void SvgIconWidget::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) protected
References InfoGraphicsView::getInfoGraphicsView(), InfoGraphicsView::hoverLeaveItem(), and m_itemBase.
initNames()
void SvgIconWidget::initNames () static
References PluralImage, and SingularImage.
itemBase()
ItemBase * SvgIconWidget::itemBase () const noexcept
References m_itemBase.
modelPart()
ModelPart * SvgIconWidget::modelPart () const noexcept
References m_itemBase.
moduleID()
constexpr const QString& SvgIconWidget::moduleID () const inline noexcept
References m_moduleId.
paint()
void SvgIconWidget::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) protected
References m_moduleId, SectionHeaderColor(), and ModuleIDNames::SpacerModuleIDName.
setItemBase()
void SvgIconWidget::setItemBase (ItemBase * itemBase, bool plural)
References itemBase(), m_itemBase, setupImage(), and ItemBase::viewID().
setupImage()
void SvgIconWidget::setupImage (bool plural, ViewLayer::ViewID viewID) protected
Todo:
make sure this doesn't leak if this function is called multiple times on the same object.
References DebugDialog::debug(), FSvgRenderer::filename(), FSvgRenderer::getPixmap(), ViewLayer::Icon, ICON_SIZE, m_itemBase, m_pixmapItem, modelPart(), ModelPart::moduleID(), ViewLayer::NewTop, PLURAL_OFFSET, PluralImage, SINGULAR_OFFSET, and SingularImage.
Member Data Documentation
m_itemBase
QPointer<ItemBase> SvgIconWidget::m_itemBase protected
m_moduleId
QString SvgIconWidget::m_moduleId protected
m_pixmapItem
SvgIconPixmapItem* SvgIconWidget::m_pixmapItem = nullptr protected
The documentation for this class was generated from the following files:
partsbinpalette/svgiconwidget.h
partsbinpalette/svgiconwidget.cpp