Fritzing: Note Class Reference
Note Class Reference
#include <note.h>
Public Member Functions
Note (class ModelPart *, ViewLayer::ViewID, const ViewGeometry &, long id, QMenu *itemMenu)
void addedToScene (bool temporary)
void findConnectorsUnder ()
bool hasPartLabel ()
bool hasPartNumberProperty ()
bool itemMoved ()
void moveItem (ViewGeometry &)
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
bool rotation45Allowed ()
bool rotationAllowed ()
void saveGeometry ()
void saveInstanceLocation (QXmlStreamWriter &)
void setHidden (bool hide)
void setInactive (bool inactivate)
void setSize (const QSizeF &size)
void setText (const QString &text, bool checkSize)
QPainterPath shape () const
bool stickyEnabled ()
QString text ()
Public Member Functions inherited from ItemBase
ItemBase (ModelPart *, ViewLayer::ViewID, const ViewGeometry &, long id, QMenu *itemMenu)
virtual ~ItemBase ()
virtual bool acceptsMouseDoubleClickConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual bool acceptsMouseMoveConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual bool acceptsMousePressConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual bool acceptsMousePressLegEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual bool acceptsMouseReleaseConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual void addSticky (ItemBase *, bool stickem)
void addSubpart (ItemBase *)
virtual bool alreadySticking (ItemBase *itemBase)
ConnectorItem * anyConnectorItem ()
QRectF boundingRect () const
virtual QRectF boundingRectWithoutLegs () const
virtual void busConnectorItems (Bus *bus, ConnectorItem *, QList< ConnectorItem * > &items)
QList< Bus * > buses ()
const QList< ConnectorItem * > & cachedConnectorItems ()
const QList< ConnectorItem * > & cachedConnectorItemsConst () const
virtual void calcRotation (QTransform &rotation, QPointF center, ViewGeometry &)
virtual bool canEditPart ()
bool canFlip (Qt::Orientations)
bool canFlipHorizontal ()
bool canFlipVertical ()
virtual void clearConnectorHover ()
void clearConnectorItemCache ()
virtual void clearModelPart ()
void clearPartLabel ()
void collectConnectors (ConnectorPairHash &connectorHash, SkipCheckFunction)
virtual bool collectExtraInfo (QWidget *parent, const QString &family, const QString &prop, const QString &value, bool swappingEnabled, QString &returnProp, QString &returnValue, QWidget *&returnWidget, bool &hide)
virtual bool collectFemaleConnectees (QSet< ItemBase * > &items)
void collectPropsMap (QString &family, QMap< QString, QString > &)
virtual void collectWireConnectees (QSet< Wire * > &wires)
virtual void connectedMoved (ConnectorItem *from, ConnectorItem *to, QList< ConnectorItem * > &already)
virtual void connectionChange (ConnectorItem *onMe, ConnectorItem *onIt, bool connect)
virtual bool connectionIsAllowed (ConnectorItem *)
virtual void connectorHover (ConnectorItem *, ItemBase *, bool hovering)
const QString & constTitle () const
void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
void debugInfo (const QString &msg) const
void debugInfo2 (const QString &msg) const
virtual void doneLoading ()
void doRotateFlipPartLabel (double degrees, Qt::Orientations)
void ensureUniqueTitle (const QString &title, bool force)
QString family ()
virtual void figureHover ()
const QString & filename ()
virtual bool filterMousePressConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
ConnectorItem * findConnectorItemWithSharedID (const QString &connectorID, ViewLayer::ViewLayerPlacement)
ConnectorItem * findConnectorItemWithSharedID (const QString &connectorID)
ItemBase * findSubpart (const QString &connectorID, ViewLayer::ViewLayerPlacement)
virtual void flipItem (Qt::Orientations orientation)
virtual bool freeRotationAllowed ()
FSvgRenderer * fsvgRenderer () const
virtual void getConnectedColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
virtual const QCursor * getCursor (Qt::KeyboardModifiers)
virtual void getEqualPotentialColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
virtual void getHoverColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
virtual QString getInspectorTitle ()
virtual void getNormalColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
QPixmap * getPixmap (QSize size)
void getPixmaps (QPixmap *&, QPixmap *&, QPixmap *&, bool swappingEnabled, QSize)
virtual QString getProperty (const QString &key)
bool getRatsnest ()
virtual void getUnconnectedColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
ViewGeometry & getViewGeometry ()
bool hasConnections ()
bool hasConnectors ()
virtual bool hasCustomSVG ()
bool hasNonConnectors ()
bool hasRubberBandLeg () const
constexpr bool hidden () const noexcept
virtual void hoverEnterConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
void hoverEnterConnectorItem ()
void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
virtual void hoverLeaveConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
void hoverLeaveConnectorItem ()
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
virtual void hoverMoveConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
virtual QPainterPath hoverShape () const
virtual void hoverUpdate ()
constexpr qint64 id () const noexcept
constexpr bool inactive () const noexcept
bool inHover ()
void initLayerAttributes (LayerAttributes &layerAttributes, ViewLayer::ViewID, ViewLayer::ViewLayerID, ViewLayer::ViewLayerPlacement, bool doConnectors, bool doCreateShape)
virtual bool inRotation ()
const QString & instanceTitle () const
virtual bool isBaseSticky ()
bool isEverVisible ()
bool isLocalSticky ()
bool isObsolete ()
bool isPartLabelVisible ()
virtual PluralType isPlural ()
virtual bool isSticky ()
virtual bool isSwappable ()
int itemType () const
void killRubberBandLeg ()
QString label ()
constexpr bool layerHidden () const noexcept
virtual const QList< ItemBase * > & layerKin ()
virtual ItemBase * layerKinChief ()
QString makePartLabelSvg (bool blackOnly, double dpi, double printerScale)
ModelPart * modelPart ()
ModelPartShared * modelPartShared ()
const QString & moduleID ()
virtual void mouseDoubleClickConnectorEvent (ConnectorItem *)
virtual void mouseMoveConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual void mousePressConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
void mousePressEvent (QGraphicsSceneMouseEvent *event)
virtual void mouseReleaseConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
bool moveLock ()
void movePartLabel (QPointF newPos, QPointF newOffset)
virtual ConnectorItem * newConnectorItem (Connector *connector)
virtual ConnectorItem * newConnectorItem (ItemBase *layerkin, Connector *connector)
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
PartLabel * partLabel ()
void partLabelMoved (QPointF oldPos, QPointF oldOffset, QPointF newPos, QPointF newOffset)
QRectF partLabelSceneBoundingRect ()
QPointF partLabelScenePos ()
void partLabelSetHidden (bool hide)
ViewLayer::ViewLayerID partLabelViewLayerID ()
void prepareGeometryChange ()
virtual QHash< QString, QString > prepareProps (ModelPart *, bool wantDebug, QStringList &keys)
QString prop (const QString &p)
bool reloadRenderer (const QString &svg, bool fastload)
virtual void removeLayerKin ()
void removeTooltip ()
virtual void resetID ()
bool resetRenderer (const QString &svg)
bool resetRenderer (const QString &svg, QString &newSvg)
void resetValues (const QString &family, const QString &prop)
void restorePartLabel (QDomElement &labelGeometry, ViewLayer::ViewLayerID)
ConnectorItem * rightClickedConnector ()
void rotateFlipPartLabel (double degrees, Qt::Orientations)
virtual void rotateItem (double degrees, bool includeRatsnest)
virtual void saveInstance (QXmlStreamWriter &)
bool sceneEvent (QEvent *event)
const QPainterPath & selectionShape ()
virtual void setAcceptsMousePressLegEvent (bool)
void setCanFlipHorizontal (bool)
void setCanFlipVertical (bool)
virtual void setDropOffset (QPointF offset)
void setEverVisible (bool)
void setFilename (const QString &)
virtual void setInRotation (bool)
virtual void setInspectorTitle (const QString &oldText, const QString &newText)
virtual void setInstanceTitle (const QString &title, bool initial)
void setItemIsSelectable (bool selectable)
virtual void setItemPos (QPointF &pos)
virtual void setLayerHidden (bool hidden)
void setLocalSticky (bool)
void setModelPart (ModelPart *)
virtual void setMoveLock (bool)
virtual void setProp (const QString &prop, const QString &value)
void setSharedRendererEx (FSvgRenderer *)
void setSquashShape (bool)
virtual void setSticky (bool)
void setSuperpart (ItemBase *)
virtual void setSwappable (bool)
void setTooltip ()
virtual void setTransform2 (const QTransform &)
FSvgRenderer * setUpImage (ModelPart *modelPart, LayerAttributes &)
void setViewLayerID (ViewLayer::ViewLayerID, const LayerHash &viewLayers)
void setViewLayerID (const QString &layerName, const LayerHash &viewLayers)
void setViewLayerPlacement (ViewLayer::ViewLayerPlacement)
void showConnectors (const QStringList &)
constexpr QSizeF size () const noexcept
virtual void slamZ (double newZ)
const QString & spice () const
const QString & spiceModel () const
virtual ItemBase * stickingTo ()
virtual QList< QPointer< ItemBase > > stickyList ()
const QList< QPointer< ItemBase > > & subparts ()
ItemBase * superpart ()
virtual const QString & title ()
bool topLevel ()
virtual void transformItem (const QTransform &, bool includeRatsnest)
virtual void transformItem2 (const QMatrix &)
void updateConnections (ConnectorItem *, bool includeRatsnest, QList< ConnectorItem * > &already)
virtual void updateConnections (bool includeRatsnest, QList< ConnectorItem * > &already)
void updateConnectionsAux (bool includeRatsnest, QList< ConnectorItem * > &already)
void updateConnectors ()
void updatePartLabelInstanceTitle ()
virtual void updateTooltip ()
ViewLayer::ViewID viewID ()
QString & viewIDName ()
ViewLayer::ViewLayerID viewLayerID () const
ViewLayer::ViewLayerPlacement viewLayerPlacement () const
ViewGeometry::WireFlags wireFlags () const
virtual void writeGeometry (QXmlStreamWriter &)
virtual void writeXml (QXmlStreamWriter &)
double z ()
Static Public Attributes
static const int emptyMinHeight = 25
static const int emptyMinWidth = 40
static const int initialMinHeight = 45
static const int initialMinWidth = 140
static QString initialTextString
Static Public Attributes inherited from ItemBase
static const QColor ConnectorHoverColor
static const double ConnectorHoverOpacity = .40
static const QList< ItemBase * > EmptyList
static const QColor HoverColor
static const double HoverOpacity = .20
static const QString ITEMBASE_FONT_PREFIX = "<font size='2'>"
static const QString ITEMBASE_FONT_SUFFIX = "</font>"
static QString PartInstanceDefaultTitle
static QHash< QString, QString > TranslatedPropertyNames
Protected Slots
void contentsChangedSlot ()
void contentsChangeSlot (int position, int charsAdded, int charsRemoved)
void handleMouseMoveSlot (QGraphicsSceneMouseEvent *event, class ResizeHandle *resizeHandle)
void handleMousePressSlot (QGraphicsSceneMouseEvent *event, class ResizeHandle *resizeHandle)
void handleMouseReleaseSlot (QGraphicsSceneMouseEvent *event, class ResizeHandle *resizeHandle)
void handleZoomChangedSlot (double scale)
void linkDialog ()
Protected Member Functions
QRectF boundingRect () const
void checkSize (QSizeF &newSize)
void connectSlots ()
void disconnectSlots ()
bool eventFilter (QObject *object, QEvent *event)
void forceFormat (int position, int charsAdded)
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
void mousePressEvent (QGraphicsSceneMouseEvent *event)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
void positionGrip ()
QString retrieveSvg (ViewLayer::ViewLayerID viewLayerID, QHash< QString, QString > &svgHash, bool blackOnly, double dpi, double &factor)
ViewLayer::ViewID useViewIDForPixmap (ViewLayer::ViewID, bool swappingEnabled)
Protected Member Functions inherited from ItemBase
virtual QStringList collectValues (const QString &family, const QString &prop, QString &value)
void createShape (LayerAttributes &layerAttributes)
QPixmap * getPixmap (ViewLayer::ViewID, bool swappingEnabled, QSize size)
QVariant itemChange (QGraphicsItem::GraphicsItemChange change, const QVariant &value)
virtual bool makeLocalModifications (QByteArray &svg, const QString &filename)
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
virtual void paintBody (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
virtual void paintHover (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
virtual void paintHover (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget, const QPainterPath &shape)
virtual void paintSelected (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
void saveLocAndTransform (QXmlStreamWriter &streamWriter)
virtual void setDefaultTooltip ()
void setInstanceTitleAux (const QString &title, bool initial)
void setInstanceTitleTooltip (const QString &text)
void updateHidden ()
Protected Attributes
QBrush m_brush
int m_charsAdded
int m_charsPosition
QGraphicsTextItem * m_graphicsTextItem
class ResizeHandle * m_inResize
QPen m_pen
QRectF m_rect
class ResizeHandle * m_resizeGrip
Protected Attributes inherited from ItemBase
bool m_acceptsMousePressLegEvent = true
QList< ConnectorItem * > m_cachedConnectorItems
bool m_canFlipHorizontal = false
bool m_canFlipVertical = false
int m_connectorHoverCount = 0
int m_connectorHoverCount2 = 0
bool m_everVisible = true
QString m_filename
FSvgRenderer * m_fsvgRenderer = nullptr
bool m_hasRubberBandLeg = false
bool m_hidden = false
int m_hoverCount = 0
bool m_hoverEnterSpaceBarWasPressed = false
qint64 m_id = 0
bool m_inactive = false
bool m_inRotation = false
QMenu * m_itemMenu = nullptr
bool m_layerHidden = false
QPointer< ModelPart > m_modelPart
bool m_moveLock = false
QGraphicsSvgItem * m_moveLockItem = nullptr
QPointer< PartLabel > m_partLabel
QMap< QString, QString > m_propsMap
ConnectorItem * m_rightClickedConnector = nullptr
QPainterPath m_selectionShape
QSizeF m_size
bool m_spaceBarWasPressed = false
bool m_squashShape = false
bool m_sticky = false
QGraphicsSvgItem * m_stickyItem = nullptr
QHash< long, QPointer< ItemBase > > m_stickyList
QList< QPointer< ItemBase > > m_subparts
QPointer< ItemBase > m_superpart
bool m_swappable = true
ViewGeometry m_viewGeometry
ViewLayer::ViewID m_viewID
ViewLayer::ViewLayerID m_viewLayerID
ViewLayer::ViewLayerPlacement m_viewLayerPlacement
bool m_zUninitialized = true
Additional Inherited Members
Public Types inherited from ItemBase
enum PluralType { Singular, Plural, NotSure }
Public Slots inherited from ItemBase
void hidePartLabel ()
void partLabelChanged (const QString &newText)
void showInFolder ()
void showPartLabel (bool show, ViewLayer *)
virtual void swapEntry (const QString &text)
Static Public Member Functions inherited from ItemBase
static void cleanup ()
static QColor connectedColor ()
static ItemBase * extractTopLevelItemBase (QGraphicsItem *thing)
static qint64 getNextID ()
static qint64 getNextID (qint64 fromIndex)
static void initNames ()
static void renderOne (QDomDocument *, QImage *, const QRectF &renderRect)
static void setConnectedColor (QColor &)
static void setReferenceModel (ReferenceModel *)
static void setUnconnectedColor (QColor &)
static QColor standardConnectedColor ()
static QColor standardUnconnectedColor ()
static QString translatePropertyName (const QString &key)
static QColor unconnectedColor ()
static bool zLessThan (ItemBase *&p1, ItemBase *&p2)
Static Protected Member Functions inherited from ItemBase
static bool fixCopper1 (ModelPart *modelPart, const QString &filename, ViewLayer::ViewLayerID viewLayerID, ViewLayer::ViewLayerPlacement, QDomDocument &)
static bool getFlipDoc (ModelPart *modelPart, const QString &filename, ViewLayer::ViewLayerID viewLayerID, ViewLayer::ViewLayerPlacement, QDomDocument &, Qt::Orientations)
Static Protected Attributes inherited from ItemBase
static QBrush ChosenBrush
static QPen ChosenPen
static QBrush ConnectedBrush
static QPen ConnectedPen
static QBrush EqualPotentialBrush
static QPen EqualPotentialPen
static QBrush HoverBrush
static QPen HoverPen
static long nextID
static QBrush NormalBrush
static constexpr double NormalConnectorOpacity = 0.4
static QPen NormalPen
static QPointer< ReferenceModel > TheReferenceModel = nullptr
static QBrush UnconnectedBrush
static QPen UnconnectedPen
Constructor & Destructor Documentation
Note()
Note::Note (class ModelPart * modelPart, ViewLayer::ViewID viewID, const ViewGeometry & viewGeometry, long id, QMenu * itemMenu)
References borderWidth, connectSlots(), handleMouseMoveSlot(), handleMousePressSlot(), handleMouseReleaseSlot(), initialMinHeight, initialMinWidth, initialTextString, ViewGeometry::loc(), m_brush, m_charsAdded, m_graphicsTextItem, m_inResize, m_pen, m_rect, m_resizeGrip, ItemBase::m_viewGeometry, positionGrip(), and ViewGeometry::rect().
Member Function Documentation
addedToScene()
void Note::addedToScene (bool temporary) virtual
Reimplemented from ItemBase.
References ItemBase::addedToScene(), and positionGrip().
boundingRect()
QRectF Note::boundingRect () const protected
References m_rect.
checkSize()
void Note::checkSize (QSizeF & newSize) protected
References m_graphicsTextItem, m_rect, m_resizeGrip, positionGrip(), and ItemBase::prepareGeometryChange().
connectSlots()
void Note::connectSlots () protected
References contentsChangedSlot(), contentsChangeSlot(), and m_graphicsTextItem.
contentsChangedSlot
void Note::contentsChangedSlot () protected slot
References checkSize(), forceFormat(), InfoGraphicsView::getInfoGraphicsView(), m_charsAdded, m_charsPosition, m_graphicsTextItem, ItemBase::m_modelPart, m_rect, and InfoGraphicsView::noteChanged().
contentsChangeSlot
void Note::contentsChangeSlot (int position, int charsAdded, int charsRemoved) protected slot
References m_charsAdded, and m_charsPosition.
disconnectSlots()
void Note::disconnectSlots () protected
References contentsChangedSlot(), contentsChangeSlot(), and m_graphicsTextItem.
eventFilter()
bool Note::eventFilter (QObject * object, QEvent * event) protected
References linkDialog(), and m_graphicsTextItem.
findConnectorsUnder()
void Note::findConnectorsUnder () virtual
Implements ItemBase.
forceFormat()
void Note::forceFormat (int position, int charsAdded) protected
References connectSlots(), disconnectSlots(), and m_graphicsTextItem.
handleMouseMoveSlot
void Note::handleMouseMoveSlot (QGraphicsSceneMouseEvent * event, class ResizeHandle * resizeHandle) protected slot
References boundingRect(), emptyMinHeight, emptyMinWidth, m_graphicsTextItem, m_inResize, m_rect, m_resizeGrip, positionGrip(), ItemBase::prepareGeometryChange(), and ResizeHandle::resizeOffset().
handleMousePressSlot
void Note::handleMousePressSlot (QGraphicsSceneMouseEvent * event, class ResizeHandle * resizeHandle) protected slot
References boundingRect(), m_inResize, ItemBase::m_spaceBarWasPressed, saveGeometry(), and ResizeHandle::setResizeOffset().
handleMouseReleaseSlot
void Note::handleMouseReleaseSlot (QGraphicsSceneMouseEvent * event, class ResizeHandle * resizeHandle) protected slot
References InfoGraphicsView::getInfoGraphicsView(), m_inResize, m_rect, ItemBase::m_viewGeometry, InfoGraphicsView::noteSizeChanged(), and ViewGeometry::rect().
handleZoomChangedSlot
void Note::handleZoomChangedSlot (double scale) protected slot
References positionGrip().
hasPartLabel()
bool Note::hasPartLabel () virtual
Reimplemented from ItemBase.
hasPartNumberProperty()
bool Note::hasPartNumberProperty () virtual
Reimplemented from ItemBase.
itemMoved()
bool Note::itemMoved () virtual
Implements ItemBase.
References ViewGeometry::loc(), and ItemBase::m_viewGeometry.
linkDialog
void Note::linkDialog () protected slot
References DebugDialog::debug(), findA(), TextUtils::findText(), m_graphicsTextItem, LinkDialog::setText(), LinkDialog::setUrl(), text(), LinkDialog::text(), LinkDialog::url(), and UrlTag().
mouseMoveEvent()
void Note::mouseMoveEvent (QGraphicsSceneMouseEvent * event) protected
References ItemBase::m_spaceBarWasPressed, and ItemBase::mouseMoveEvent().
mousePressEvent()
void Note::mousePressEvent (QGraphicsSceneMouseEvent * event) protected
References InfoGraphicsView::getInfoGraphicsView(), m_inResize, ItemBase::m_spaceBarWasPressed, ItemBase::mousePressEvent(), and InfoGraphicsView::spaceBarIsPressed().
mouseReleaseEvent()
void Note::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected
References ItemBase::m_spaceBarWasPressed, and ItemBase::mouseReleaseEvent().
moveItem()
void Note::moveItem (ViewGeometry & viewGeometry) virtual
Implements ItemBase.
References ViewGeometry::loc().
paint()
void Note::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget)
References borderWidth, boundingRect(), InactiveOpacity, m_brush, ItemBase::m_hidden, ItemBase::m_inactive, m_pen, m_rect, GraphicsUtils::qt_graphicsItem_highlightSelected(), and TriangleOffset.
positionGrip()
void Note::positionGrip () protected
References boundingRect(), m_graphicsTextItem, m_resizeGrip, and TriangleOffset.
retrieveSvg()
QString Note::retrieveSvg (ViewLayer::ViewLayerID viewLayerID, QHash< QString, QString > & svgHash, bool blackOnly, double dpi, double & factor) protected virtual
Reimplemented from ItemBase.
References addText(), ViewLayer::BreadboardNote, ViewLayer::BreadboardView, m_brush, m_graphicsTextItem, m_pen, m_rect, m_resizeGrip, ViewLayer::PcbNote, ViewLayer::PCBView, ViewLayer::SchematicNote, ViewLayer::SchematicView, GraphicsUtils::SVGDPI, UrlTag(), ItemBase::viewID(), and ItemBase::viewLayerID().
rotation45Allowed()
bool Note::rotation45Allowed () virtual
Reimplemented from ItemBase.
rotationAllowed()
bool Note::rotationAllowed () virtual
Reimplemented from ItemBase.
saveGeometry()
void Note::saveGeometry () virtual
Implements ItemBase.
References boundingRect(), ItemBase::m_viewGeometry, ViewGeometry::setLoc(), ViewGeometry::setRect(), ViewGeometry::setSelected(), and ViewGeometry::setZ().
saveInstanceLocation()
void Note::saveInstanceLocation (QXmlStreamWriter & streamWriter) virtual
Implements ItemBase.
References ViewGeometry::loc(), ItemBase::m_viewGeometry, and ViewGeometry::rect().
setHidden()
void Note::setHidden (bool hide) virtual
Reimplemented from ItemBase.
References m_graphicsTextItem, m_resizeGrip, and ItemBase::setHidden().
setInactive()
void Note::setInactive (bool inactivate) virtual
Reimplemented from ItemBase.
References ItemBase::setInactive().
setSize()
void Note::setSize (const QSizeF & size)
References m_rect, positionGrip(), and ItemBase::prepareGeometryChange().
setText()
void Note::setText (const QString & text, bool checkSize)
References checkSize(), connectSlots(), disconnectSlots(), forceFormat(), m_graphicsTextItem, and text().
shape()
QPainterPath Note::shape () const
References boundingRect().
stickyEnabled()
bool Note::stickyEnabled () virtual
Reimplemented from ItemBase.
text()
QString Note::text ()
References m_graphicsTextItem.
useViewIDForPixmap()
ViewLayer::ViewID Note::useViewIDForPixmap (ViewLayer::ViewID , bool swappingEnabled) protected virtual
Reimplemented from ItemBase.
References ViewLayer::IconView.
Member Data Documentation
emptyMinHeight
const int Note::emptyMinHeight = 25 static
emptyMinWidth
const int Note::emptyMinWidth = 40 static
initialMinHeight
const int Note::initialMinHeight = 45 static
initialMinWidth
const int Note::initialMinWidth = 140 static
initialTextString
QString Note::initialTextString static
m_brush
QBrush Note::m_brush protected
m_charsAdded
int Note::m_charsAdded protected
m_charsPosition
int Note::m_charsPosition protected
m_graphicsTextItem
QGraphicsTextItem* Note::m_graphicsTextItem protected
m_inResize
class ResizeHandle* Note::m_inResize protected
m_pen
QPen Note::m_pen protected
m_rect
QRectF Note::m_rect protected
m_resizeGrip
class ResizeHandle* Note::m_resizeGrip protected
The documentation for this class was generated from the following files:
items/note.h
items/note.cpp