Fritzing: partseditor/pemainwindow.cpp File Reference
pemainwindow.cpp File Reference
#include "pemainwindow.h"
#include "pemetadataview.h"
#include "peconnectorsview.h"
#include "pecommands.h"
#include "petoolview.h"
#include "pesvgview.h"
#include "pegraphicsitem.h"
#include "kicadmoduledialog.h"
#include "../debugdialog.h"
#include "../sketch/breadboardsketchwidget.h"
#include "../sketch/schematicsketchwidget.h"
#include "../sketch/pcbsketchwidget.h"
#include "../mainwindow/sketchareawidget.h"
#include "../referencemodel/referencemodel.h"
#include "../utils/graphicsutils.h"
#include "../utils/textutils.h"
#include "../utils/folderutils.h"
#include "../utils/s2s.h"
#include "../mainwindow/fdockwidget.h"
#include "../fsvgrenderer.h"
#include "../partsbinpalette/binmanager/binmanager.h"
#include "../svg/gedaelement2svg.h"
#include "../svg/kicadmodule2svg.h"
#include "../svg/kicadschematic2svg.h"
#include "../sketchtoolbutton.h"
#include "../items/virtualwire.h"
#include "../connectors/connectoritem.h"
#include "../connectors/bus.h"
#include "../installedfonts.h"
#include "../dock/layerpalette.h"
#include "../utils/cursormaster.h"
#include "../infoview/htmlinfoview.h"
#include <QtDebug>
#include <QInputDialog>
#include <QApplication>
#include <QSvgGenerator>
#include <QMenuBar>
#include <QMessageBox>
#include <QDesktopServices>
#include <QUrl>
#include <QBuffer>
#include <QClipboard>
#include <limits>
Functions
bool byID (QDomElement &c1, QDomElement &c2)
static const QString ReferenceFileString ("referenceFile")
QString removeGorn (QString &svg)
void removeGornAux (QDomElement &element)
void removeID (QDomElement &root, const QString &value)
Variables
static const int ConnectorsViewIndex = 5
static long FakeGornSiblingNumber = 0
static bool GotZeroConnector = false
static const int IconViewIndex = 3
static const int MetadataViewIndex = 4
static const int PegiZ = 5000
static const int RatZ = 6000
static bool RubberBandLegWarning = false
Function Documentation
byID()
bool byID (QDomElement & c1, QDomElement & c2)
References GotZeroConnector, and IntegerFinder().
ReferenceFileString()
static const QString ReferenceFileString ("referenceFile") static
removeGorn()
QString removeGorn (QString & svg)
References DebugDialog::debug(), and removeGornAux().
removeGornAux()
void removeGornAux (QDomElement & element)
removeID()
void removeID (QDomElement & root, const QString & value)
Variable Documentation
ConnectorsViewIndex
const int ConnectorsViewIndex = 5 static
FakeGornSiblingNumber
long FakeGornSiblingNumber = 0 static
GotZeroConnector
bool GotZeroConnector = false static
IconViewIndex
const int IconViewIndex = 3 static
MetadataViewIndex
const int MetadataViewIndex = 4 static
PegiZ
const int PegiZ = 5000 static
RatZ
const int RatZ = 6000 static
RubberBandLegWarning
bool RubberBandLegWarning = false static