Fritzing: SvgFlattener Class Reference
SvgFlattener Class Reference
#include <svgflattener.h>
Public Member Functions
SvgFlattener ()
void flattenChildren (QDomElement &element)
void unRotateChild (QDomElement &element, QMatrix transform)
Public Member Functions inherited from SvgFileSplitter
SvgFileSplitter ()=default
const QByteArray & byteArray () const noexcept
const QDomDocument & domDocument () const noexcept
QString elementString (const QString &elementID)
void gReplace (const QString &id)
void gWrap (const QHash< QString, QString > &attributes)
bool load (const QString *filename)
bool load (QFile *)
bool load (const QString &string)
bool normalize (double dpi, const QString &elementID, bool blackOnly, double &factor)
QPainterPath painterPath (double dpi, const QString &elementID)
virtual bool parsePath (const QString &data, const char *slot, PathUserData &, QObject *slotTarget, bool convertHV)
QString shift (double x, double y, const QString &elementID, bool shiftTransforms)
void shiftChild (QDomElement &element, double x, double y, bool shiftTransforms)
QVector< QVariant > simpleParsePath (const QString &data)
Parse content of path element d attribute into validated tokens.
bool split (const QString &filename, const QString &elementID)
bool splitString (QString &contents, const QString &elementID)
QString toString ()
Static Public Member Functions
static void flipSMDSvg (const QString &filename, const QString &svg, QDomDocument &flipDoc, const QString &elementID, const QString &altElementID, double printerScale, Qt::Orientations)
static void replaceElementID (const QString &filename, const QString &svg, QDomDocument &flipDoc, const QString &elementID, const QString &altElementID)
Static Public Member Functions inherited from SvgFileSplitter
static bool changeColors (const QString &svg, QString &toColor, QStringList &exceptions, QByteArray &)
static void changeColors (QDomElement &element, QString &toColor, QStringList &exceptions)
static bool changeStrokeWidth (const QString &svg, double delta, bool absolute, bool changeOpacity, QByteArray &)
static void changeStrokeWidth (QDomElement &element, double delta, bool absolute, bool changeOpacity)
static void fixColorRecurse (QDomElement &element, const QString &newColor, const QStringList &exceptions)
static void fixStyleAttributeRecurse (QDomElement &element)
static void forceStrokeWidth (QDomElement &element, double delta, const QString &stroke, bool recurse, bool fill)
static bool getSvgSizeAttributes (const QString &svg, QString &width, QString &height, QString &viewBox)
static QByteArray hideText (const QString &filename)
static QByteArray hideText2 (const QByteArray &svg)
static QString hideText3 (const QString &svg)
static QByteArray showText (const QString &filename, bool &hasText)
static QByteArray showText2 (const QByteArray &svg, bool &hasText)
static QString showText3 (const QString &svg, bool &hasText)
Protected Slots
void rotateCommandSlot (QChar command, bool relative, QList< double > &args, void *userData)
Protected Slots inherited from SvgFileSplitter
void convertHVSlot (QChar command, bool relative, QList< double > &args, void *userData)
void normalizeCommandSlot (QChar command, bool relative, QList< double > &args, void *userData)
void painterPathCommandSlot (QChar command, bool relative, QList< double > &args, void *userData)
virtual void rotateCommandSlot (QChar, bool, QList< double > &, void *)
void shiftCommandSlot (QChar command, bool relative, QList< double > &args, void *userData)
Static Protected Member Functions
static QString flipSMDElement (QDomDocument &domDocument, QDomElement &element, const QString &att, QDomElement altAtt, const QString &altElementID, double printerScale, Qt::Orientations)
static bool hasOtherTransform (QDomElement &element)
static bool hasTranslate (QDomElement &element)
static bool loadDocIf (const QString &filename, const QString &svg, QDomDocument &domDocument)
Static Protected Member Functions inherited from SvgFileSplitter
static void hideTextAux (QDomElement &parent, bool hideChildren)
static void setStrokeOrFill (QDomElement &element, bool doIt, const QString &color, bool force)
static bool shiftAttribute (QDomElement &element, const char *attributeName, double d)
static void showTextAux (QDomElement &parent, bool &hasText, bool root)
Additional Inherited Members
Protected Member Functions inherited from SvgFileSplitter
bool normalizeAttribute (QDomElement &element, const char *attributeName, double num, double denom)
void normalizeChild (QDomElement &childElement, double sNewWidth, double sNewHeight, double vbWidth, double vbHeight, bool blackOnly)
bool normalizeFontSize (QDomElement &element, const char *attributeName, double num, double denom)
void normalizeTranslation (QDomElement &element, double sNewWidth, double sNewHeight, double vbWidth, double vbHeight)
void painterPathChild (QDomElement &element, QPainterPath &ppath)
bool shiftTranslation (QDomElement &element, double x, double y)
void standardArgs (bool relative, bool starting, QList< double > &args, PathUserData *pathUserData)
Protected Attributes inherited from SvgFileSplitter
QByteArray m_byteArray
QDomDocument m_domDocument
Constructor & Destructor Documentation
SvgFlattener()
SvgFlattener::SvgFlattener ()
Member Function Documentation
flattenChildren()
void SvgFlattener::flattenChildren (QDomElement & element)
References DebugDialog::debug(), TextUtils::getTransformFloats(), hasOtherTransform(), hasTranslate(), SvgFileSplitter::shiftChild(), TextUtils::transformStringToMatrix(), and unRotateChild().
flipSMDElement()
QString SvgFlattener::flipSMDElement (QDomDocument & domDocument, QDomElement & element, const QString & att, QDomElement altAtt, const QString & altElementID, double printerScale, Qt::Orientations orientation) static protected
References SvgFileSplitter::domDocument(), TextUtils::ensureViewBox(), and TextUtils::setSVGTransform().
flipSMDSvg()
void SvgFlattener::flipSMDSvg (const QString & filename, const QString & svg, QDomDocument & flipDoc, const QString & elementID, const QString & altElementID, double printerScale, Qt::Orientations orientation) static
References SvgFileSplitter::domDocument(), TextUtils::findElementWithAttribute(), flipSMDElement(), and loadDocIf().
hasOtherTransform()
bool SvgFlattener::hasOtherTransform (QDomElement & element) static protected
hasTranslate()
bool SvgFlattener::hasTranslate (QDomElement & element) static protected
References TextUtils::transformStringToMatrix().
loadDocIf()
bool SvgFlattener::loadDocIf (const QString & filename, const QString & svg, QDomDocument & domDocument) static protected
References SvgFileSplitter::domDocument().
replaceElementID()
void SvgFlattener::replaceElementID (const QString & filename, const QString & svg, QDomDocument & flipDoc, const QString & elementID, const QString & altElementID) static
References SvgFileSplitter::domDocument(), TextUtils::findElementWithAttribute(), and loadDocIf().
rotateCommandSlot
void SvgFlattener::rotateCommandSlot (QChar command, bool relative, QList< double > & args, void * userData) protected slot
References DebugDialog::debug(), SVGPathLexer::FakeClosePathChar, PathUserData::string, and PathUserData::transform.
unRotateChild()
void SvgFlattener::unRotateChild (QDomElement & element, QMatrix transform)
References DebugDialog::debug(), GraphicsUtils::getRect(), GraphicsUtils::isRect(), SvgFileSplitter::parsePath(), rotateCommandSlot(), PathUserData::string, and PathUserData::transform.
The documentation for this class was generated from the following files:
svg/svgflattener.h
svg/svgflattener.cpp