Fritzing: PartsChecker Class Reference
PartsChecker Class Reference
#include <partschecker.h>
Static Public Member Functions
static bool cleanRepo (const QString &repoPath, const PartsCheckerResult &partsCheckerResult)
static QString getSha (const QString &repoPath)
static bool newPartsAvailable (const QString &repoPath, const QString &shaFromDataBase, bool atUserRequest, QString &remoteSha, PartsCheckerResult &partsCheckerResult)
static bool updateParts (const QString &repoPath, const QString &remoteSha, PartsCheckerUpdateInterface *)
Static Protected Member Functions
static bool checkIfClean (const QString &repoPath, const QString &shaFromDatabase, struct git_repository *repository, PartsCheckerResult &partsCheckerResult)
static int doMerge (struct git_repository *repository, const QString &remoteSha)
static void getChanges (struct git_status_list *status_list, PartsCheckerResult &partsCheckerResult)
Member Function Documentation
checkIfClean()
bool PartsChecker::checkIfClean (const QString & repoPath, const QString & shaFromDatabase, struct git_repository * repository, PartsCheckerResult & partsCheckerResult) static protected
looks for modified or untracked files in the repo
References PartsCheckerResult::changedFiles, PartsCheckerResult::errorMessage, getChanges(), PartsCheckerResult::gitChangedFiles, PARTS_CHECKER_ERROR_LOCAL_DAMAGE, PARTS_CHECKER_ERROR_LOCAL_MODS, PARTS_CHECKER_ERROR_USED_GIT, PartsCheckerResult::partsCheckerError, sBoilerPlate1, sBoilerPlate2, sDamaged, sModified, sModifiedByGit, sNotInMasterBranch, sUnreadable, PartsCheckerResult::unreadableFiles, and PartsCheckerResult::untrackedFiles.
cleanRepo()
bool PartsChecker::cleanRepo (const QString & repoPath, const PartsCheckerResult & partsCheckerResult) static
Remove untracked files (as listed in partsCheckerResult) and perform git reset –hard
git reset –HARD and delete untracked files in the repo
References PartsCheckerResult::untrackedFiles.
doMerge()
int PartsChecker::doMerge (struct git_repository * repository, const QString & remoteSha) static protected
merge after the fetch
References DebugDialog::debug().
getChanges()
void PartsChecker::getChanges (struct git_status_list * status_list, PartsCheckerResult & partsCheckerResult) static protected
gets the details about modified or new files in the repo
References PartsCheckerResult::changedFiles, PartsCheckerResult::gitChangedFiles, PartsCheckerResult::unreadableFiles, and PartsCheckerResult::untrackedFiles.
getSha()
QString PartsChecker::getSha (const QString & repoPath) static
returns the sha1 for the last commit; used only when creating the parts db
gets the sha1 hash for the HEAD
References FMessageBox::warning().
newPartsAvailable()
bool PartsChecker::newPartsAvailable (const QString & repoPath, const QString & shaFromDatabase, bool atUserRequest, QString & remoteSha, PartsCheckerResult & partsCheckerResult) static
Check if there are any new parts available (since the last new parts check)
remoteSha and PartsErrorResult are also returned
Check whether the last commit in the remote repository matches the last commit stored in the database, or check if the last commit in the remote repository matches the commit saved last time newPartsAvailable returned true
repoPath is the local parts folder remoteSha is returned
Connect to the remote.
Get the list of references on the remote
References checkIfClean(), PartsCheckerResult::errorMessage, PARTS_CHECKER_ERROR_LOCAL_DAMAGE, PARTS_CHECKER_ERROR_NONE, PARTS_CHECKER_ERROR_REMOTE, PartsCheckerResult::partsCheckerError, sBoilerPlate1, sBoilerPlate2, sDamaged, sModified, sModifiedByGit, sNotInMasterBranch, and sUnreadable.
updateParts()
bool PartsChecker::updateParts (const QString & repoPath, const QString & remoteSha, PartsCheckerUpdateInterface * interface) static
trigger the update, with progress going to the PartsCheckerUpdateInterface
git pull origin master
Perform the fetch with the configured refspecs from the config. Update the reflog for the updated references with "fetch".
References DebugDialog::debug(), doMerge(), and transfer_progress_cb().
The documentation for this class was generated from the following files:
version/partschecker.h
version/partschecker.cpp