Fritzing: PEConnectorsView Class Reference
PEConnectorsView Class Reference
#include <peconnectorsview.h>
Signals
void connectorCountChanged (int)
void connectorMetadataChanged (struct ConnectorMetadata *)
void connectorsTypeChanged (Connector::ConnectorType)
void removedConnectors (QList< struct ConnectorMetadata * > &)
void smdChanged (const QString &)
Public Member Functions
PEConnectorsView (QWidget *parent=0)
~PEConnectorsView ()
bool anyModified ()
void initConnectors (QList< QDomElement > *connectorList)
void setSMD (bool)
Protected Slots
void allTypeEntry ()
void connectorCountEntry ()
void descriptionEntry ()
void nameEntry ()
void removeConnector ()
void smdEntry ()
void typeEntry ()
void uncheckRadios ()
Protected Member Functions
void changeConnector ()
Protected Attributes
int m_connectorCount
QMutex m_mutex
QLineEdit * m_numberEdit
QList< QRadioButton * > m_radios
QScrollArea * m_scrollArea
QFrame * m_scrollFrame
QRadioButton * m_smd
QRadioButton * m_tht
Constructor & Destructor Documentation
PEConnectorsView()
PEConnectorsView::PEConnectorsView (QWidget * parent = 0)
References allTypeEntry(), connectorCountEntry(), Connector::Female, FemaleSymbolString, m_connectorCount, m_numberEdit, m_radios, m_scrollArea, m_scrollFrame, m_smd, m_tht, Connector::Male, MaleSymbolString, Connector::Pad, and smdEntry().
~PEConnectorsView()
PEConnectorsView::~PEConnectorsView ()
Member Function Documentation
allTypeEntry
void PEConnectorsView::allTypeEntry () protected slot
References connectorsTypeChanged(), and uncheckRadios().
anyModified()
bool PEConnectorsView::anyModified ()
changeConnector()
void PEConnectorsView::changeConnector () protected
References connectorMetadataChanged(), PEUtils::fillInMetadata(), and m_scrollFrame.
connectorCountChanged
void PEConnectorsView::connectorCountChanged (int) signal
connectorCountEntry
void PEConnectorsView::connectorCountEntry () protected slot
References connectorCountChanged(), m_connectorCount, and m_mutex.
connectorMetadataChanged
void PEConnectorsView::connectorMetadataChanged (struct ConnectorMetadata *) signal
connectorsTypeChanged
void PEConnectorsView::connectorsTypeChanged (Connector::ConnectorType) signal
descriptionEntry
void PEConnectorsView::descriptionEntry () protected slot
References changeConnector().
initConnectors()
void PEConnectorsView::initConnectors (QList< QDomElement > * connectorList)
References m_connectorCount, m_numberEdit, m_scrollArea, m_scrollFrame, and PEUtils::makeConnectorForm().
nameEntry
void PEConnectorsView::nameEntry () protected slot
References changeConnector().
removeConnector
void PEConnectorsView::removeConnector () protected slot
References PEUtils::fillInMetadata(), m_scrollFrame, and removedConnectors().
removedConnectors
void PEConnectorsView::removedConnectors (QList< struct ConnectorMetadata * > &) signal
setSMD()
void PEConnectorsView::setSMD (bool smd)
References m_smd, and m_tht.
smdChanged
void PEConnectorsView::smdChanged (const QString &) signal
smdEntry
void PEConnectorsView::smdEntry () protected slot
References m_smd, and smdChanged().
typeEntry
void PEConnectorsView::typeEntry () protected slot
References changeConnector().
uncheckRadios
void PEConnectorsView::uncheckRadios () protected slot
References m_radios.
Member Data Documentation
m_connectorCount
int PEConnectorsView::m_connectorCount protected
m_mutex
QMutex PEConnectorsView::m_mutex protected
m_numberEdit
QLineEdit* PEConnectorsView::m_numberEdit protected
m_radios
QList<QRadioButton *> PEConnectorsView::m_radios protected
m_scrollArea
QScrollArea* PEConnectorsView::m_scrollArea protected
m_scrollFrame
QFrame* PEConnectorsView::m_scrollFrame protected
m_smd
QRadioButton* PEConnectorsView::m_smd protected
m_tht
QRadioButton* PEConnectorsView::m_tht protected
The documentation for this class was generated from the following files:
partseditor/peconnectorsview.h
partseditor/peconnectorsview.cpp