Fritzing: ConnectorItem Class Reference
ConnectorItem Class Reference
#include <connectoritem.h>
Public Member Functions
ConnectorItem (Connector *, ItemBase *attachedTo)
~ConnectorItem ()
void addLegBendpoint (int index, QPointF, const class Bezier *, const class Bezier *)
QPointF adjustedTerminalPoint ()
void attachedMoved (bool includeRatsnest, QList< ConnectorItem * > &already)
ViewLayer::ViewID attachedToViewID ()
ViewLayer::ViewLayerID attachedToViewLayerID ()
ViewLayer::ViewLayerPlacement attachedToViewLayerPlacement ()
const QVector< class Bezier * > & beziers ()
QRectF boundingRect () const
class Bus * bus ()
const QString & busID ()
double calcClipRadius ()
bool chained ()
void changeLegCurve (int index, const class Bezier *)
ConnectorItem * chooseFromSpec (ViewLayer::ViewLayerPlacement)
void clearConnector ()
void clearConnectorHover ()
void clearRatsnestDisplay (QList< ConnectorItem * > &connectorItems)
bool connectedTo (ConnectorItem *)
const QList< QPointer< ConnectorItem > > & connectedToItems ()
bool connectedToWires ()
bool connectionIsAllowed (ConnectorItem *other)
int connectionsCount ()
Connector * connector ()
void connectorHover (ItemBase *, bool hovering)
bool connectorHovering ()
const QString & connectorSharedDescription ()
class ErcData * connectorSharedErcData ()
const QString & connectorSharedID ()
const QString & connectorSharedName ()
const QString & connectorSharedReplacedby ()
Connector::ConnectorType connectorType ()
void connectTo (ConnectorItem *)
void cursorKeyEvent (Qt::KeyboardModifiers modifiers)
void debugInfo (const QString &msg)
void displayRatsnest (QList< ConnectorItem * > &partsConnectorItems, ViewGeometry::WireFlags myFlag)
ConnectorItem * findConnectorUnder (bool useTerminalPoint, bool allowAlready, const QList< ConnectorItem * > &exclude, bool displayDragTooltip, ConnectorItem *other)
ConnectorItem * firstConnectedToIsh ()
ConnectorItem * getCrossLayerConnectorItem ()
bool hasRubberBandLeg () const
QPainterPath hoverShape () const
bool isBendpoint ()
bool isBigDot ()
bool isCrossLayerConnectorItem (ConnectorItem *candidate)
bool isCrossLayerFrom (ConnectorItem *candidate)
bool isDraggingLeg ()
bool isEffectivelyCircular ()
bool isGrounded ()
bool isGroundFillSeed ()
bool isHybrid ()
bool isInLayers (ViewLayer::ViewLayerPlacement)
void killRubberBandLeg ()
const QPolygonF & leg ()
const QString & legID (ViewLayer::ViewID, ViewLayer::ViewLayerID)
QString makeLegSvg (QPointF offset, double dpi, double printerScale, bool blackOnly)
double minDimension ()
ModelPart * modelPart ()
ModelPartShared * modelPartShared ()
void moveDone (int &index0, QPointF &oldPos0, QPointF &newPos0, int &index1, QPointF &oldPos1, QPointF &newPos1)
void moveLegBendpoint (int index, QPointF)
ConnectorItem * overConnectorItem ()
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)
void prepareToStretch (bool activeStretch)
ConnectorItem * releaseDrag ()
ConnectorItem * removeConnection (ItemBase *)
void removeConnection (ConnectorItem *, bool emitChange)
void removeLegBendpoint (int index, const class Bezier *)
void resetLeg (const QPolygonF &, bool relative, bool active, const QString &why)
void restoreColor (QList< ConnectorItem * > &visited)
void rotateLeg (const QPolygonF &, bool active)
void saveInstance (QXmlStreamWriter &)
QPolygonF sceneAdjustedLeg ()
QPointF sceneAdjustedTerminalPoint (ConnectorItem *anchor)
void setBigDot (bool)
void setConnectorLocalName (const QString &name)
void setGroundFillSeed (bool)
void setHidden (bool hidden)
void setHoverColor ()
void setHybrid (bool)
void setInactive (bool inactivate)
void setLeg (const QPolygonF &, bool relative, const QString &why)
void setOverConnectorItem (ConnectorItem *)
void setRubberBandLeg (QColor color, double strokeWidth, QLineF parentLine)
void setTerminalPoint (QPointF)
QPainterPath shape () const
void showEqualPotential (bool show, QList< ConnectorItem * > &visited)
void stretchBy (QPointF howMuch)
void stretchDone (QPolygonF &oldLeg, QPolygonF &newLeg, bool &active)
void tempConnectTo (ConnectorItem *item, bool applyColor)
void tempRemove (ConnectorItem *item, bool applyColor)
QPointF terminalPoint ()
void updateTooltip ()
bool wiredTo (ConnectorItem *, ViewGeometry::WireFlags skipFlags)
void writeConnector (QXmlStreamWriter &writer, const QString &elementName)
Public Member Functions inherited from NonConnectorItem
NonConnectorItem (ItemBase *attachedTo)
~NonConnectorItem ()=default
ItemBase * attachedTo () const noexcept
long attachedToID ()
const QString & attachedToInstanceTitle ()
int attachedToItemType ()
const QString & attachedToTitle ()
constexpr bool hidden () const noexcept
constexpr bool inactive () const noexcept
constexpr bool isPath () const noexcept
constexpr bool layerHidden () const noexcept
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)
constexpr double radius () const noexcept
void setCircular (bool)
void setIsPath (bool)
virtual void setLayerHidden (bool hidden)
void setRadius (double radius, double strokeWidth)
void setShape (QPainterPath &)
QPainterPath shape () const
constexpr double strokeWidth () const noexcept
Static Public Member Functions
static void clearEqualPotentialDisplay ()
static void collectConnectorNames (QList< ConnectorItem * > &connectorItems, QStringList &connectorNames)
static void collectEqualPotential (QList< ConnectorItem * > &connectorItems, bool crossLayers, ViewGeometry::WireFlags skipFlags)
collect all the connectors at the same potential
static void collectParts (QList< ConnectorItem * > &connectorItems, QList< ConnectorItem * > &partsConnectors, bool includeSymbols, ViewLayer::ViewLayerPlacement)
static class Wire * directlyWiredTo (ConnectorItem *source, ConnectorItem *target, ViewGeometry::WireFlags flags)
static bool isGrounded (ConnectorItem *c1, ConnectorItem *c2)
Static Public Attributes
static const QList< ConnectorItem * > emptyConnectorItemList
Protected Types
enum CursorLocation {
InNotFound = 0, InConnector, InBendpoint, InOrigin,
InSegment
}
Protected Types inherited from NonConnectorItem
enum Effectively { EffectivelyCircular = 1, EffectivelyRectangular, EffectivelyPolygonal, EffectivelyUnknown }
Protected Member Functions
void calcConnectorEnd ()
void clearCurves ()
void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
bool curvyWiresIndicated (Qt::KeyboardModifiers)
void displayTooltip (ConnectorItem *over, ConnectorItem *other)
CursorLocation findLocation (QPointF, int &bendpointIndex)
double findT (Bezier *bezier, double blen, double length)
ViewGeometry::WireFlags getSkipFlags ()
void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
void hoverMoveEvent (QGraphicsSceneHoverEvent *event)
void insertBendpoint (QPointF pos, int bendpointIndex)
Bezier * insertBendpointAux (QPointF p, int bendpointIndex)
bool isConnectedToPart ()
bool isEverVisible ()
bool legMousePressEvent (QGraphicsSceneMouseEvent *event)
QPen legPen () const
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event)
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
void mousePressEvent (QGraphicsSceneMouseEvent *event)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
void paintLeg (QPainter *painter)
void paintLeg (QPainter *painter, bool hasCurves)
void removeBendpoint (int bendpointIndex)
void replaceBezier (int index, const Bezier *newBezier)
void repoly (const QPolygonF &poly, bool relative)
void reposition (QPointF sceneDestPos, int draggingIndex)
void repositionTarget ()
void setColorAux (const QBrush &brush, const QPen &pen, bool paint)
void setColorAux (const QColor &color, bool paint=true)
void setConnectedColor ()
void setHiddenOrInactive ()
void setNormalColor ()
void setUnconnectedColor ()
QPainterPath shapeAux (double width) const
void updateLegCursor (QPointF p, Qt::KeyboardModifiers modifiers)
void updateWireCursor (Qt::KeyboardModifiers modifiers)
void writeOtherElements (QXmlStreamWriter &writer)
Protected Member Functions inherited from NonConnectorItem
constexpr bool doNotPaint () const noexcept
Static Protected Member Functions
static void collectPart (ConnectorItem *connectorItem, QList< ConnectorItem * > &partsConnectors, ViewLayer::ViewLayerPlacement)
static class Wire * directlyWiredToAux (ConnectorItem *source, ConnectorItem *target, ViewGeometry::WireFlags flags, QList< ConnectorItem * > &visited)
Protected Attributes
bool m_activeStretch = false
bool m_bigDot = false
QList< QPointer< ConnectorItem > > m_connectedTo
QPointer< Connector > m_connector
QPointF m_connectorDetectEnd
double m_connectorDetectT = 0.0
QPointF m_connectorDrawEnd
double m_connectorDrawT = 0.0
bool m_connectorHovering = false
bool m_draggingCurve = false
bool m_draggingLeg = false
int m_draggingLegIndex = 0
bool m_groundFillSeed = false
QPointF m_holdPos
bool m_hoverEnterSpaceBarWasPressed = false
bool m_hybrid = false
bool m_insertBendpointPossible = false
QColor m_legColor
QVector< class Bezier * > m_legCurves
QPolygonF m_legPolygon
double m_legStrokeWidth = 0.0
int m_moveCount = 0
QPolygonF m_oldPolygon
QPointer< ConnectorItem > m_overConnectorItem
bool m_rubberBandLeg = false
bool m_spaceBarWasPressed = false
QPointF m_terminalPoint
Protected Attributes inherited from NonConnectorItem
QPointer< ItemBase > m_attachedTo
bool m_circular = false
Effectively m_effectively = Effectively::EffectivelyUnknown
bool m_hidden = false
bool m_inactive = false
bool m_isPath = false
bool m_layerHidden = false
bool m_negativeOffsetRect = false
double m_negativePenWidth = 0.0
double m_opacity = 0.0
bool m_paint = false
double m_radius = 0.0
QPainterPath m_shape
double m_strokeWidth = 0.0
Static Protected Attributes
static QList< ConnectorItem * > m_equalPotentialDisplayItems
Member Enumeration Documentation
CursorLocation
enum ConnectorItem::CursorLocation protected
Enumerator
InNotFound
InConnector
InBendpoint
InOrigin
InSegment
Constructor & Destructor Documentation
ConnectorItem()
ConnectorItem::ConnectorItem (Connector * connector, ItemBase * attachedTo)
References Connector::addViewItem(), NonConnectorItem::attachedTo(), CursorMaster::BendpointCursor, connector(), ItemBase::itemType(), CursorMaster::MakeWireCursor, and ModelPart::Wire.
~ConnectorItem()
ConnectorItem::~ConnectorItem ()
References NonConnectorItem::attachedToID(), clearCurves(), connector(), m_connectedTo, m_equalPotentialDisplayItems, Connector::removeViewItem(), and tempRemove().
Member Function Documentation
addLegBendpoint()
void ConnectorItem::addLegBendpoint (int index, QPointF , const class Bezier * , const class Bezier *)
References calcConnectorEnd(), m_legCurves, m_legPolygon, and replaceBezier().
adjustedTerminalPoint()
QPointF ConnectorItem::adjustedTerminalPoint ()
References m_legPolygon, m_terminalPoint, and SvgIdLayer::rect().
attachedMoved()
void ConnectorItem::attachedMoved (bool includeRatsnest, QList< ConnectorItem * > & already)
References NonConnectorItem::attachedTo(), ItemBase::connectedMoved(), connectedToItems(), ItemBase::getRatsnest(), and m_connectedTo.
attachedToViewID()
ViewLayer::ViewID ConnectorItem::attachedToViewID ()
References NonConnectorItem::m_attachedTo, and ViewLayer::UnknownView.
attachedToViewLayerID()
ViewLayer::ViewLayerID ConnectorItem::attachedToViewLayerID ()
References NonConnectorItem::m_attachedTo, and ViewLayer::UnknownLayer.
attachedToViewLayerPlacement()
ViewLayer::ViewLayerPlacement ConnectorItem::attachedToViewLayerPlacement ()
References NonConnectorItem::m_attachedTo, and ViewLayer::UnknownPlacement.
beziers()
const QVector< Bezier * > & ConnectorItem::beziers ()
References m_legCurves.
boundingRect()
QRectF ConnectorItem::boundingRect () const
References m_legPolygon, and shape().
bus()
Bus * ConnectorItem::bus ()
References m_connector.
busID()
const QString & ConnectorItem::busID ()
References ___emptyString___, and m_connector.
calcClipRadius()
double ConnectorItem::calcClipRadius ()
References NonConnectorItem::EffectivelyCircular, NonConnectorItem::m_circular, NonConnectorItem::m_effectively, NonConnectorItem::radius(), SvgIdLayer::rect(), and NonConnectorItem::strokeWidth().
calcConnectorEnd()
void ConnectorItem::calcConnectorEnd () protected
References Bezier::computeCubicCurveLength(), findT(), Bezier::isEmpty(), m_connectorDetectEnd, m_connectorDetectT, m_connectorDrawEnd, m_connectorDrawT, m_legCurves, m_legPolygon, qMax(), qMin(), Bezier::set_endpoints(), StandardLegConnectorDetectLength, and StandardLegConnectorDrawEnabledLength.
chained()
bool ConnectorItem::chained ()
References NonConnectorItem::attachedToItemType(), m_connectedTo, and ModelPart::Wire.
changeLegCurve()
void ConnectorItem::changeLegCurve (int index, const class Bezier *)
References calcConnectorEnd(), and replaceBezier().
chooseFromSpec()
ConnectorItem * ConnectorItem::chooseFromSpec (ViewLayer::ViewLayerPlacement viewLayerPlacement)
References attachedToViewLayerID(), ViewLayer::Copper0, ViewLayer::Copper1, DebugDialog::debug(), getCrossLayerConnectorItem(), ViewLayer::NewBottom, and ViewLayer::NewTop.
clearConnector()
void ConnectorItem::clearConnector ()
References m_connector.
clearConnectorHover()
void ConnectorItem::clearConnectorHover ()
References m_connectorHovering.
clearCurves()
void ConnectorItem::clearCurves () protected
References m_legCurves.
clearEqualPotentialDisplay()
void ConnectorItem::clearEqualPotentialDisplay () static
References m_equalPotentialDisplayItems, and restoreColor().
clearRatsnestDisplay()
void ConnectorItem::clearRatsnestDisplay (QList< ConnectorItem * > & connectorItems)
References NonConnectorItem::attachedTo(), connectedToItems(), Wire::connector0(), Wire::connector1(), firstConnectedToIsh(), and tempRemove().
collectConnectorNames()
void ConnectorItem::collectConnectorNames (QList< ConnectorItem * > & connectorItems, QStringList & connectorNames) static
References connectorSharedName().
collectEqualPotential()
void ConnectorItem::collectEqualPotential (QList< ConnectorItem * > & connectorItems, bool crossLayers, ViewGeometry::WireFlags skipFlags) static
collect all the connectors at the same potential
Starting from the set of connectors supplied, build and return a list of all of the connectors that are wired together
Allows direct or wired connections
Parameters
[in,out] connectorItems start of list of connected items
[in] crossLayers follow connections accross layers
[in] skipFlags filter for the types of wires that are not to be included
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToItemType(), bus(), ItemBase::busConnectorItems(), connectedToItems(), debugInfo(), getCrossLayerConnectorItem(), Wire::hasAnyFlag(), ViewGeometry::NormalFlag, and ModelPart::Wire.
collectPart()
void ConnectorItem::collectPart (ConnectorItem * connectorItem, QList< ConnectorItem * > & partsConnectors, ViewLayer::ViewLayerPlacement viewLayerPlacement) static protected
References attachedToViewLayerID(), ViewLayer::Copper0, ViewLayer::Copper1, getCrossLayerConnectorItem(), ViewLayer::NewBottom, ViewLayer::NewTop, and ViewLayer::NewTopAndBottom.
collectParts()
void ConnectorItem::collectParts (QList< ConnectorItem * > & connectorItems, QList< ConnectorItem * > & partsConnectors, bool includeSymbols, ViewLayer::ViewLayerPlacement viewLayerPlacement) static
References NonConnectorItem::attachedTo(), ModelPart::Board, collectPart(), ModelPart::CopperFill, DebugDialog::debug(), isHybrid(), ItemBase::itemType(), ModelPart::Jumper, ViewLayer::NewBottom, ViewLayer::NewTop, ViewLayer::NewTopAndBottom, ModelPart::Part, ModelPart::ResizableBoard, ModelPart::SchematicSubpart, ModelPart::Symbol, and ModelPart::Via.
connectedTo()
bool ConnectorItem::connectedTo (ConnectorItem * connectorItem)
References m_connectedTo.
connectedToItems()
const QList< QPointer< ConnectorItem > > & ConnectorItem::connectedToItems ()
References m_connectedTo.
connectedToWires()
bool ConnectorItem::connectedToWires ()
References NonConnectorItem::attachedToItemType(), connectedToItems(), getCrossLayerConnectorItem(), and ModelPart::Wire.
connectionIsAllowed()
bool ConnectorItem::connectionIsAllowed (ConnectorItem * other)
References NonConnectorItem::attachedTo(), connectedToItems(), ItemBase::connectionIsAllowed(), connector(), and NonConnectorItem::m_attachedTo.
connectionsCount()
int ConnectorItem::connectionsCount ()
References m_connectedTo.
connector()
Connector * ConnectorItem::connector ()
References m_connector.
connectorHover()
void ConnectorItem::connectorHover (ItemBase * itemBase, bool hovering)
References NonConnectorItem::m_attachedTo, m_connectorHovering, restoreColor(), and setHoverColor().
connectorHovering()
bool ConnectorItem::connectorHovering ()
References m_connectorHovering.
connectorSharedDescription()
const QString & ConnectorItem::connectorSharedDescription ()
References ___emptyString___, and m_connector.
connectorSharedErcData()
ErcData * ConnectorItem::connectorSharedErcData ()
References m_connector.
connectorSharedID()
const QString & ConnectorItem::connectorSharedID ()
References ___emptyString___, and m_connector.
connectorSharedName()
const QString & ConnectorItem::connectorSharedName ()
References ___emptyString___, and m_connector.
connectorSharedReplacedby()
const QString & ConnectorItem::connectorSharedReplacedby ()
References ___emptyString___, and m_connector.
connectorType()
Connector::ConnectorType ConnectorItem::connectorType ()
References m_connector, and Connector::Unknown.
connectTo()
void ConnectorItem::connectTo (ConnectorItem * connected)
References NonConnectorItem::m_attachedTo, m_connectedTo, and restoreColor().
contextMenuEvent()
void ConnectorItem::contextMenuEvent (QGraphicsSceneContextMenuEvent * event) protected
References findLocation(), InfoGraphicsView::getInfoGraphicsView(), InBendpoint, InSegment, insertBendpoint(), Bezier::isEmpty(), NonConnectorItem::m_hidden, m_hybrid, NonConnectorItem::m_inactive, m_legCurves, m_legPolygon, m_rubberBandLeg, InfoGraphicsView::prepLegCurveChange(), removeBendpoint(), and InfoGraphicsView::setActiveConnectorItem().
cursorKeyEvent()
void ConnectorItem::cursorKeyEvent (Qt::KeyboardModifiers modifiers) virtual
Implements CursorKeyListener.
References NonConnectorItem::attachedToItemType(), InfoGraphicsView::getInfoGraphicsView(), m_draggingLeg, m_rubberBandLeg, updateLegCursor(), updateWireCursor(), and ModelPart::Wire.
curvyWiresIndicated()
bool ConnectorItem::curvyWiresIndicated (Qt::KeyboardModifiers modifiers) protected
References InfoGraphicsView::curvyWiresIndicated(), and InfoGraphicsView::getInfoGraphicsView().
debugInfo()
void ConnectorItem::debugInfo (const QString & msg)
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToID(), NonConnectorItem::attachedToInstanceTitle(), NonConnectorItem::attachedToItemType(), NonConnectorItem::attachedToTitle(), attachedToViewID(), attachedToViewLayerID(), attachedToViewLayerPlacement(), bus(), connectorSharedID(), connectorSharedName(), DebugDialog::debug(), m_hybrid, NonConnectorItem::m_radius, NonConnectorItem::m_strokeWidth, and sceneAdjustedTerminalPoint().
directlyWiredTo()
Wire * ConnectorItem::directlyWiredTo (ConnectorItem * source, ConnectorItem * target, ViewGeometry::WireFlags flags) static
References directlyWiredToAux().
directlyWiredToAux()
Wire * ConnectorItem::directlyWiredToAux (ConnectorItem * source, ConnectorItem * target, ViewGeometry::WireFlags flags, QList< ConnectorItem * > & visited) static protected
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToItemType(), getCrossLayerConnectorItem(), Wire::hasAnyFlag(), ItemBase::itemType(), m_connectedTo, Wire::otherConnector(), and ModelPart::Wire.
displayRatsnest()
void ConnectorItem::displayRatsnest (QList< ConnectorItem * > & partsConnectorItems, ViewGeometry::WireFlags myFlag)
References NonConnectorItem::attachedTo(), GraphUtils::chooseRatsnestGraph(), clearRatsnestDisplay(), collectConnectorNames(), Wire::color(), VirtualWire::colorWasNamed(), connectedToItems(), RatsnestColors::findConnectorColor(), InfoGraphicsView::getInfoGraphicsView(), InfoGraphicsView::getRatsnestColor(), InfoGraphicsView::makeOneRatsnestWire(), ViewGeometry::NormalFlag, ViewGeometry::PCBTraceFlag, ViewGeometry::RatsnestFlag, ViewGeometry::SchematicTraceFlag, and VirtualWire::setColorWasNamed().
displayTooltip()
void ConnectorItem::displayTooltip (ConnectorItem * over, ConnectorItem * other) protected
References NonConnectorItem::attachedToInstanceTitle(), connectorHovering(), connectorSharedName(), and InfoGraphicsView::getInfoGraphicsView().
findConnectorUnder()
ConnectorItem * ConnectorItem::findConnectorUnder (bool useTerminalPoint, bool allowAlready, const QList< ConnectorItem * > & exclude, bool displayDragTooltip, ConnectorItem * other)
References NonConnectorItem::attachedTo(), connectedToItems(), connectionIsAllowed(), connector(), connectorHover(), connectorHovering(), displayTooltip(), m_overConnectorItem, SvgIdLayer::rect(), sceneAdjustedTerminalPoint(), and wireLessThan().
findLocation()
ConnectorItem::CursorLocation ConnectorItem::findLocation (QPointF location, int & bendpointIndex) protected
References Bezier::cp0(), Bezier::cp1(), GraphicsUtils::distanceSqd(), Bezier::endpoint0(), Bezier::endpoint1(), InBendpoint, InConnector, InNotFound, InOrigin, InSegment, Bezier::isEmpty(), legPen(), m_connectorDetectEnd, m_connectorDetectT, m_legCurves, m_legPolygon, m_legStrokeWidth, GraphicsUtils::shapeFromPath(), and Bezier::split().
findT()
double ConnectorItem::findT (Bezier * bezier, double blen, double length) protected
References Bezier::computeCubicCurveLength().
firstConnectedToIsh()
ConnectorItem * ConnectorItem::firstConnectedToIsh ()
References NonConnectorItem::attachedTo(), ItemBase::getRatsnest(), and m_connectedTo.
getCrossLayerConnectorItem()
ConnectorItem * ConnectorItem::getCrossLayerConnectorItem ()
References attachedToViewID(), attachedToViewLayerID(), ViewLayer::Copper0, ViewLayer::Copper1, NonConnectorItem::m_attachedTo, m_connector, and ViewLayer::PCBView.
getSkipFlags()
ViewGeometry::WireFlags ConnectorItem::getSkipFlags () protected
References InfoGraphicsView::getInfoGraphicsView(), InfoGraphicsView::getTraceFlag(), ViewGeometry::NormalFlag, ViewGeometry::PCBTraceFlag, ViewGeometry::RatsnestFlag, and ViewGeometry::SchematicTraceFlag.
hasRubberBandLeg()
bool ConnectorItem::hasRubberBandLeg () const
References m_rubberBandLeg.
hoverEnterEvent()
void ConnectorItem::hoverEnterEvent (QGraphicsSceneHoverEvent * event) protected
References CursorMaster::addCursor(), NonConnectorItem::attachedToItemType(), InfoGraphicsView::getInfoGraphicsView(), InfoGraphicsView::hoverEnterConnectorItem(), CursorMaster::instance(), NonConnectorItem::m_attachedTo, m_hoverEnterSpaceBarWasPressed, m_rubberBandLeg, CursorMaster::MakeWireCursor, setHoverColor(), InfoGraphicsView::spaceBarIsPressed(), updateLegCursor(), updateWireCursor(), and ModelPart::Wire.
hoverLeaveEvent()
void ConnectorItem::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) protected
References InfoGraphicsView::getInfoGraphicsView(), InfoGraphicsView::hoverLeaveConnectorItem(), CursorMaster::instance(), NonConnectorItem::m_attachedTo, m_hoverEnterSpaceBarWasPressed, CursorMaster::removeCursor(), and restoreColor().
hoverMoveEvent()
void ConnectorItem::hoverMoveEvent (QGraphicsSceneHoverEvent * event) protected
References NonConnectorItem::m_attachedTo, m_hoverEnterSpaceBarWasPressed, m_rubberBandLeg, and updateLegCursor().
hoverShape()
QPainterPath ConnectorItem::hoverShape () const
References m_legStrokeWidth, and shapeAux().
insertBendpoint()
void ConnectorItem::insertBendpoint (QPointF pos, int bendpointIndex) protected
References calcConnectorEnd(), InfoGraphicsView::getInfoGraphicsView(), insertBendpointAux(), m_legCurves, m_legPolygon, m_oldPolygon, InfoGraphicsView::prepLegBendpointChange(), and UndoBezier.
insertBendpointAux()
Bezier * ConnectorItem::insertBendpointAux (QPointF p, int bendpointIndex) protected
References Bezier::clear(), Bezier::copy(), Bezier::findSplit(), Bezier::isEmpty(), m_legCurves, m_legPolygon, m_legStrokeWidth, replaceBezier(), Bezier::set_endpoints(), Bezier::split(), and UndoBezier.
isBendpoint()
bool ConnectorItem::isBendpoint ()
References NonConnectorItem::attachedToItemType(), connectedToItems(), connectionsCount(), and ModelPart::Wire.
isBigDot()
bool ConnectorItem::isBigDot ()
References m_bigDot.
isConnectedToPart()
bool ConnectorItem::isConnectedToPart () protected
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToItemType(), ModelPart::Board, ModelPart::Breadboard, bus(), ItemBase::busConnectorItems(), connectedToItems(), ModelPart::CopperFill, getCrossLayerConnectorItem(), ItemBase::isEverVisible(), ModelPart::Jumper, ModelPart::Part, ModelPart::ResizableBoard, ModelPart::SchematicSubpart, ModelPart::Symbol, and ModelPart::Via.
isCrossLayerConnectorItem()
bool ConnectorItem::isCrossLayerConnectorItem (ConnectorItem * candidate)
References getCrossLayerConnectorItem().
isCrossLayerFrom()
bool ConnectorItem::isCrossLayerFrom (ConnectorItem * candidate)
References attachedToViewLayerID(), and ViewLayer::canConnect().
isDraggingLeg()
bool ConnectorItem::isDraggingLeg ()
References m_draggingLeg.
isEffectivelyCircular()
bool ConnectorItem::isEffectivelyCircular ()
References NonConnectorItem::EffectivelyCircular, NonConnectorItem::m_circular, and NonConnectorItem::m_effectively.
isEverVisible()
bool ConnectorItem::isEverVisible () protected
References NonConnectorItem::m_attachedTo.
isGrounded() [1/2]
bool ConnectorItem::isGrounded ()
References connectorSharedName().
isGrounded() [2/2]
bool ConnectorItem::isGrounded (ConnectorItem * c1, ConnectorItem * c2) static
References collectEqualPotential(), isGrounded(), and ViewGeometry::NoFlag.
isGroundFillSeed()
bool ConnectorItem::isGroundFillSeed ()
References m_groundFillSeed.
isHybrid()
bool ConnectorItem::isHybrid ()
References m_hybrid.
isInLayers()
bool ConnectorItem::isInLayers (ViewLayer::ViewLayerPlacement viewLayerPlacement)
References attachedToViewLayerID(), and ViewLayer::copperLayers().
killRubberBandLeg()
void ConnectorItem::killRubberBandLeg ()
References clearCurves(), m_legPolygon, and m_rubberBandLeg.
leg()
const QPolygonF & ConnectorItem::leg ()
References m_legPolygon, and m_rubberBandLeg.
legID()
const QString & ConnectorItem::legID (ViewLayer::ViewID viewID, ViewLayer::ViewLayerID viewLayerID)
References ___emptyString___, and m_connector.
legMousePressEvent()
bool ConnectorItem::legMousePressEvent (QGraphicsSceneMouseEvent * event) protected
References altOrMetaModifier(), NonConnectorItem::attachedTo(), Bezier::copy(), curvyWiresIndicated(), findLocation(), InfoGraphicsView::getInfoGraphicsView(), InBendpoint, InConnector, Bezier::initControlIndex(), BezierDisplay::initDisplay(), Bezier::initToEnds(), InNotFound, InOrigin, InSegment, Bezier::isEmpty(), m_draggingCurve, m_draggingLeg, m_draggingLegIndex, m_holdPos, m_insertBendpointPossible, m_legCurves, m_legPolygon, m_legStrokeWidth, m_oldPolygon, InfoGraphicsView::prepLegSelection(), TheBezierDisplay, and UndoBezier.
legPen()
QPen ConnectorItem::legPen () const protected
References m_legColor, m_legStrokeWidth, and m_rubberBandLeg.
makeLegSvg()
QString ConnectorItem::makeLegSvg (QPointF offset, double dpi, double printerScale, bool blackOnly)
References Bezier::cp0(), Bezier::cp1(), Bezier::isEmpty(), m_legColor, m_legCurves, m_legPolygon, m_legStrokeWidth, m_rubberBandLeg, and TextUtils::pointToSvgString().
minDimension()
double ConnectorItem::minDimension ()
References boundingRect(), and qMin().
modelPart()
ModelPart * ConnectorItem::modelPart ()
References NonConnectorItem::m_attachedTo.
modelPartShared()
ModelPartShared * ConnectorItem::modelPartShared ()
References NonConnectorItem::m_attachedTo.
mouseDoubleClickEvent()
void ConnectorItem::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) protected
References findLocation(), InBendpoint, InSegment, insertBendpoint(), NonConnectorItem::m_attachedTo, m_legPolygon, m_rubberBandLeg, and removeBendpoint().
mouseMoveEvent()
void ConnectorItem::mouseMoveEvent (QGraphicsSceneMouseEvent * event) protected
References calcConnectorEnd(), GraphicsUtils::calcConstraint(), GraphicsUtils::distanceSqd(), findConnectorUnder(), insertBendpointAux(), Bezier::isEmpty(), NonConnectorItem::m_attachedTo, m_draggingCurve, m_draggingLeg, m_draggingLegIndex, m_holdPos, m_insertBendpointPossible, m_legCurves, m_legPolygon, m_moveCount, m_rubberBandLeg, Bezier::recalc(), reposition(), TheBezierDisplay, and BezierDisplay::updateDisplay().
mousePressEvent()
void ConnectorItem::mousePressEvent (QGraphicsSceneMouseEvent * event) protected
References clearEqualPotentialDisplay(), collectEqualPotential(), InfoGraphicsView::getInfoGraphicsView(), legMousePressEvent(), NonConnectorItem::m_attachedTo, m_draggingCurve, m_draggingLeg, m_equalPotentialDisplayItems, m_moveCount, m_rubberBandLeg, ViewGeometry::NoFlag, showEqualPotential(), and InfoGraphicsView::spaceBarIsPressed().
mouseReleaseEvent()
void ConnectorItem::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected
References clearEqualPotentialDisplay(), InfoGraphicsView::getInfoGraphicsView(), NonConnectorItem::m_attachedTo, m_draggingCurve, m_draggingLeg, m_draggingLegIndex, m_insertBendpointPossible, m_legCurves, m_legPolygon, m_moveCount, m_oldPolygon, m_rubberBandLeg, InfoGraphicsView::prepLegBendpointChange(), InfoGraphicsView::prepLegBendpointMove(), InfoGraphicsView::prepLegCurveChange(), releaseDrag(), reposition(), sceneAdjustedTerminalPoint(), TheBezierDisplay, and UndoBezier.
moveDone()
void ConnectorItem::moveDone (int & index0, QPointF & oldPos0, QPointF & newPos0, int & index1, QPointF & oldPos1, QPointF & newPos1)
References m_activeStretch, m_legPolygon, and m_oldPolygon.
moveLegBendpoint()
void ConnectorItem::moveLegBendpoint (int index, QPointF p)
References calcConnectorEnd(), and m_legPolygon.
overConnectorItem()
ConnectorItem * ConnectorItem::overConnectorItem ()
References m_overConnectorItem.
paint()
void ConnectorItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0)
References NonConnectorItem::attachedTo(), NonConnectorItem::doNotPaint(), NonConnectorItem::EffectivelyCircular, NonConnectorItem::EffectivelyRectangular, NonConnectorItem::EffectivelyUnknown, NonConnectorItem::m_circular, NonConnectorItem::m_effectively, m_hybrid, m_legPolygon, NonConnectorItem::m_shape, NonConnectorItem::paint(), paintLeg(), ViewLayer::PCBView, SvgIdLayer::rect(), and ItemBase::viewID().
paintLeg() [1/2]
void ConnectorItem::paintLeg (QPainter * painter) protected
References addColor(), Bezier::cp0(), Bezier::cp1(), Bezier::endpoint0(), Bezier::endpoint1(), ItemBase::HoverOpacity, Bezier::isEmpty(), isGrey(), legPen(), NonConnectorItem::m_attachedTo, m_connectorDrawEnd, m_connectorDrawT, m_legColor, m_legCurves, m_legPolygon, m_legStrokeWidth, NonConnectorItem::m_opacity, and Bezier::split().
paintLeg() [2/2]
void ConnectorItem::paintLeg (QPainter * painter, bool hasCurves) protected
References Bezier::cp0(), Bezier::cp1(), Bezier::isEmpty(), m_legCurves, and m_legPolygon.
prepareToStretch()
void ConnectorItem::prepareToStretch (bool activeStretch)
References m_activeStretch, m_oldPolygon, and sceneAdjustedLeg().
releaseDrag()
ConnectorItem * ConnectorItem::releaseDrag ()
References NonConnectorItem::attachedTo(), clearConnectorHover(), ItemBase::clearConnectorHover(), m_overConnectorItem, restoreColor(), and setOverConnectorItem().
removeBendpoint()
void ConnectorItem::removeBendpoint (int bendpointIndex) protected
References calcConnectorEnd(), Bezier::copy(), InfoGraphicsView::getInfoGraphicsView(), Bezier::join(), m_legCurves, m_legPolygon, m_oldPolygon, InfoGraphicsView::prepLegBendpointChange(), replaceBezier(), and Bezier::set_endpoints().
removeConnection() [1/2]
ConnectorItem * ConnectorItem::removeConnection (ItemBase * itemBase)
References NonConnectorItem::attachedTo(), DebugDialog::debug(), NonConnectorItem::m_attachedTo, m_connectedTo, ItemBase::modelPartShared(), restoreColor(), and ModelPartShared::title().
removeConnection() [2/2]
void ConnectorItem::removeConnection (ConnectorItem * connectedItem, bool emitChange)
References NonConnectorItem::m_attachedTo, m_connectedTo, and restoreColor().
removeLegBendpoint()
void ConnectorItem::removeLegBendpoint (int index, const class Bezier *)
References calcConnectorEnd(), m_legCurves, m_legPolygon, and replaceBezier().
replaceBezier()
void ConnectorItem::replaceBezier (int index, const Bezier * newBezier) protected
References Bezier::clear(), Bezier::copy(), and m_legCurves.
repoly()
void ConnectorItem::repoly (const QPolygonF & poly, bool relative) protected
References calcConnectorEnd(), clearCurves(), m_legCurves, and m_legPolygon.
reposition()
void ConnectorItem::reposition (QPointF sceneDestPos, int draggingIndex) protected
References calcConnectorEnd(), and m_legPolygon.
repositionTarget()
void ConnectorItem::repositionTarget () protected
References connectorType(), Connector::Female, m_connectedTo, m_legPolygon, reposition(), and sceneAdjustedTerminalPoint().
resetLeg()
void ConnectorItem::resetLeg (const QPolygonF & poly, bool relative, bool active, const QString & why)
References calcConnectorEnd(), connectorType(), Connector::Female, m_connectedTo, m_legPolygon, m_rubberBandLeg, repositionTarget(), sceneAdjustedTerminalPoint(), and setLeg().
restoreColor()
void ConnectorItem::restoreColor (QList< ConnectorItem * > & visited)
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToItemType(), collectEqualPotential(), connectionsCount(), connectorType(), Connector::Female, getSkipFlags(), isEverVisible(), ItemBase::layerKinChief(), setConnectedColor(), setNormalColor(), setUnconnectedColor(), and ModelPart::Wire.
rotateLeg()
void ConnectorItem::rotateLeg (const QPolygonF & poly, bool active)
References resetLeg().
saveInstance()
void ConnectorItem::saveInstance (QXmlStreamWriter & writer)
References NonConnectorItem::attachedTo(), attachedToViewLayerID(), connectorSharedID(), ItemBase::getRatsnest(), m_connectedTo, m_groundFillSeed, m_legCurves, m_legPolygon, m_rubberBandLeg, ViewLayer::viewLayerXmlNameFromID(), Bezier::write(), writeConnector(), and writeOtherElements().
sceneAdjustedLeg()
QPolygonF ConnectorItem::sceneAdjustedLeg ()
References m_legPolygon, and m_rubberBandLeg.
sceneAdjustedTerminalPoint()
QPointF ConnectorItem::sceneAdjustedTerminalPoint (ConnectorItem * anchor)
References adjustedTerminalPoint(), NonConnectorItem::attachedTo(), NonConnectorItem::attachedToItemType(), GraphicsUtils::distanceFromLine(), ItemBase::getRatsnest(), NonConnectorItem::m_circular, NonConnectorItem::m_shape, MAX_DOUBLE, Wire::otherConnector(), sceneAdjustedTerminalPoint(), and ModelPart::Wire.
setBigDot()
void ConnectorItem::setBigDot (bool bd)
References m_bigDot.
setColorAux() [1/2]
void ConnectorItem::setColorAux (const QBrush & brush, const QPen & pen, bool paint) protected
References NonConnectorItem::m_paint, and paint().
setColorAux() [2/2]
void ConnectorItem::setColorAux (const QColor & color, bool paint = true) protected
References paint(), and setColorAux().
setConnectedColor()
void ConnectorItem::setConnectedColor () protected
References NonConnectorItem::m_attachedTo, NonConnectorItem::m_negativeOffsetRect, NonConnectorItem::m_negativePenWidth, NonConnectorItem::m_opacity, and setColorAux().
setConnectorLocalName()
void ConnectorItem::setConnectorLocalName (const QString & name)
References m_connector.
setGroundFillSeed()
void ConnectorItem::setGroundFillSeed (bool seed)
References getCrossLayerConnectorItem(), and m_groundFillSeed.
setHidden()
void ConnectorItem::setHidden (bool hidden) virtual
Reimplemented from NonConnectorItem.
References NonConnectorItem::m_hidden, and setHiddenOrInactive().
setHiddenOrInactive()
void ConnectorItem::setHiddenOrInactive () protected
References ALLMOUSEBUTTONS, NonConnectorItem::attachedToItemType(), CursorMaster::BendpointCursor, NonConnectorItem::m_hidden, m_hybrid, NonConnectorItem::m_inactive, NonConnectorItem::m_layerHidden, CursorMaster::MakeWireCursor, and ModelPart::Wire.
setHoverColor()
void ConnectorItem::setHoverColor ()
References NonConnectorItem::m_attachedTo, NonConnectorItem::m_negativeOffsetRect, NonConnectorItem::m_negativePenWidth, NonConnectorItem::m_opacity, and setColorAux().
setHybrid()
void ConnectorItem::setHybrid (bool h)
References m_hybrid, and setHiddenOrInactive().
setInactive()
void ConnectorItem::setInactive (bool inactivate) virtual
Reimplemented from NonConnectorItem.
References NonConnectorItem::m_inactive, and setHiddenOrInactive().
setLeg()
void ConnectorItem::setLeg (const QPolygonF & poly, bool relative, const QString & why)
References m_rubberBandLeg, and repoly().
setNormalColor()
void ConnectorItem::setNormalColor () protected
References NonConnectorItem::m_attachedTo, NonConnectorItem::m_negativeOffsetRect, NonConnectorItem::m_negativePenWidth, NonConnectorItem::m_opacity, and setColorAux().
setOverConnectorItem()
void ConnectorItem::setOverConnectorItem (ConnectorItem * connectorItem)
References m_overConnectorItem.
setRubberBandLeg()
void ConnectorItem::setRubberBandLeg (QColor color, double strokeWidth, QLineF parentLine)
References ALLMOUSEBUTTONS, NonConnectorItem::m_attachedTo, m_legColor, m_legCurves, m_legPolygon, m_legStrokeWidth, m_rubberBandLeg, reposition(), NonConnectorItem::setCircular(), and NonConnectorItem::strokeWidth().
setTerminalPoint()
void ConnectorItem::setTerminalPoint (QPointF p)
References m_terminalPoint.
setUnconnectedColor()
void ConnectorItem::setUnconnectedColor () protected
References NonConnectorItem::m_attachedTo, NonConnectorItem::m_negativeOffsetRect, NonConnectorItem::m_negativePenWidth, NonConnectorItem::m_opacity, and setColorAux().
shape()
QPainterPath ConnectorItem::shape () const
References m_legStrokeWidth, and shapeAux().
shapeAux()
QPainterPath ConnectorItem::shapeAux (double width) const protected
References Bezier::cp0(), Bezier::cp1(), Bezier::isEmpty(), legPen(), m_legCurves, m_legPolygon, NonConnectorItem::shape(), and GraphicsUtils::shapeFromPath().
showEqualPotential()
void ConnectorItem::showEqualPotential (bool show, QList< ConnectorItem * > & visited)
References NonConnectorItem::m_attachedTo, NonConnectorItem::m_negativeOffsetRect, NonConnectorItem::m_negativePenWidth, NonConnectorItem::m_opacity, restoreColor(), and setColorAux().
stretchBy()
void ConnectorItem::stretchBy (QPointF howMuch)
References m_activeStretch, NonConnectorItem::m_attachedTo, m_oldPolygon, m_rubberBandLeg, and resetLeg().
stretchDone()
void ConnectorItem::stretchDone (QPolygonF & oldLeg, QPolygonF & newLeg, bool & active)
References m_activeStretch, m_oldPolygon, and sceneAdjustedLeg().
tempConnectTo()
void ConnectorItem::tempConnectTo (ConnectorItem * item, bool applyColor)
References m_connectedTo, and restoreColor().
tempRemove()
void ConnectorItem::tempRemove (ConnectorItem * item, bool applyColor)
References m_connectedTo, and restoreColor().
terminalPoint()
QPointF ConnectorItem::terminalPoint ()
References m_terminalPoint.
updateLegCursor()
void ConnectorItem::updateLegCursor (QPointF p, Qt::KeyboardModifiers modifiers) protected
References CursorMaster::addCursor(), altOrMetaModifier(), NonConnectorItem::attachedTo(), CursorMaster::BendlegCursor, CursorMaster::BendpointCursor, curvyWiresIndicated(), findLocation(), ItemBase::getCursor(), InBendpoint, InConnector, InOrigin, InSegment, CursorMaster::instance(), CursorMaster::MakeCurveCursor, CursorMaster::MakeWireCursor, and CursorMaster::NewBendpointCursor.
updateTooltip()
void ConnectorItem::updateTooltip ()
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToItemType(), NonConnectorItem::attachedToTitle(), connectorSharedDescription(), connectorSharedID(), connectorSharedName(), IntegerFinder(), ItemBase::ITEMBASE_FONT_PREFIX, ItemBase::ITEMBASE_FONT_SUFFIX, ItemBase::label(), m_connectedTo, modelPart(), and ModelPart::Wire.
updateWireCursor()
void ConnectorItem::updateWireCursor (Qt::KeyboardModifiers modifiers) protected
References CursorMaster::addCursor(), altOrMetaModifier(), NonConnectorItem::attachedTo(), CursorMaster::BendpointCursor, Wire::canChainMultiple(), CursorMaster::instance(), isBendpoint(), and CursorMaster::MakeWireCursor.
wiredTo()
bool ConnectorItem::wiredTo (ConnectorItem * target, ViewGeometry::WireFlags skipFlags)
References collectEqualPotential().
writeConnector()
void ConnectorItem::writeConnector (QXmlStreamWriter & writer, const QString & elementName)
References attachedToViewLayerID(), connector(), connectorSharedID(), and ViewLayer::viewLayerXmlNameFromID().
writeOtherElements()
void ConnectorItem::writeOtherElements (QXmlStreamWriter & writer) protected
Member Data Documentation
emptyConnectorItemList
const QList< ConnectorItem * > ConnectorItem::emptyConnectorItemList static
m_activeStretch
bool ConnectorItem::m_activeStretch = false protected
m_bigDot
bool ConnectorItem::m_bigDot = false protected
m_connectedTo
QList< QPointer<ConnectorItem> > ConnectorItem::m_connectedTo protected
m_connector
QPointer<Connector> ConnectorItem::m_connector protected
m_connectorDetectEnd
QPointF ConnectorItem::m_connectorDetectEnd protected
m_connectorDetectT
double ConnectorItem::m_connectorDetectT = 0.0 protected
m_connectorDrawEnd
QPointF ConnectorItem::m_connectorDrawEnd protected
m_connectorDrawT
double ConnectorItem::m_connectorDrawT = 0.0 protected
m_connectorHovering
bool ConnectorItem::m_connectorHovering = false protected
m_draggingCurve
bool ConnectorItem::m_draggingCurve = false protected
m_draggingLeg
bool ConnectorItem::m_draggingLeg = false protected
m_draggingLegIndex
int ConnectorItem::m_draggingLegIndex = 0 protected
m_equalPotentialDisplayItems
QList< ConnectorItem * > ConnectorItem::m_equalPotentialDisplayItems static protected
m_groundFillSeed
bool ConnectorItem::m_groundFillSeed = false protected
m_holdPos
QPointF ConnectorItem::m_holdPos protected
m_hoverEnterSpaceBarWasPressed
bool ConnectorItem::m_hoverEnterSpaceBarWasPressed = false protected
m_hybrid
bool ConnectorItem::m_hybrid = false protected
m_insertBendpointPossible
bool ConnectorItem::m_insertBendpointPossible = false protected
m_legColor
QColor ConnectorItem::m_legColor protected
m_legCurves
QVector<class Bezier *> ConnectorItem::m_legCurves protected
m_legPolygon
QPolygonF ConnectorItem::m_legPolygon protected
m_legStrokeWidth
double ConnectorItem::m_legStrokeWidth = 0.0 protected
m_moveCount
int ConnectorItem::m_moveCount = 0 protected
m_oldPolygon
QPolygonF ConnectorItem::m_oldPolygon protected
m_overConnectorItem
QPointer<ConnectorItem> ConnectorItem::m_overConnectorItem protected
m_rubberBandLeg
bool ConnectorItem::m_rubberBandLeg = false protected
m_spaceBarWasPressed
bool ConnectorItem::m_spaceBarWasPressed = false protected
m_terminalPoint
QPointF ConnectorItem::m_terminalPoint protected
The documentation for this class was generated from the following files:
connectors/connectoritem.h
connectors/connectoritem.cpp