Fritzing: FGraphicsScene Class Reference
FGraphicsScene Class Reference
#include <fgraphicsscene.h>
Public Member Functions
FGraphicsScene (QObject *parent=0)
void contextMenuEvent (QGraphicsSceneContextMenuEvent *)
bool displayHandles ()
void helpEvent (QGraphicsSceneHelpEvent *)
QPointF lastContextMenuPos ()
QList< ItemBase * > lockedSelectedItems ()
void setDisplayHandles (bool)
Protected Attributes
bool m_displayHandles
QPointF m_lastContextMenuPos
Constructor & Destructor Documentation
FGraphicsScene()
FGraphicsScene::FGraphicsScene (QObject * parent = 0)
References m_displayHandles.
Member Function Documentation
contextMenuEvent()
void FGraphicsScene::contextMenuEvent (QGraphicsSceneContextMenuEvent * contextMenuEvent)
References m_lastContextMenuPos.
displayHandles()
bool FGraphicsScene::displayHandles ()
References m_displayHandles.
helpEvent()
void FGraphicsScene::helpEvent (QGraphicsSceneHelpEvent * helpEvent)
References ItemBase::updateTooltip(), and ConnectorItem::updateTooltip().
lastContextMenuPos()
QPointF FGraphicsScene::lastContextMenuPos ()
References m_lastContextMenuPos.
lockedSelectedItems()
QList< ItemBase * > FGraphicsScene::lockedSelectedItems ()
References ItemBase::moveLock().
setDisplayHandles()
void FGraphicsScene::setDisplayHandles (bool displayHandles)
References displayHandles(), and m_displayHandles.
Member Data Documentation
m_displayHandles
bool FGraphicsScene::m_displayHandles protected
m_lastContextMenuPos
QPointF FGraphicsScene::m_lastContextMenuPos protected
The documentation for this class was generated from the following files:
sketch/fgraphicsscene.h
sketch/fgraphicsscene.cpp