Fritzing: SVGPathLexer Class Reference
SVGPathLexer Class Reference
#include <svgpathlexer.h>
Public Member Functions
SVGPathLexer (const QString &source)
~SVGPathLexer ()
QChar currentCommand ()
double currentNumber ()
int lex ()
extract the next token from the current attribute source data
Static Public Attributes
static constexpr char FakeClosePathChar = 'x'
Protected Member Functions
QString clean (const QString &source)
remove unneeded whitespaces from d attribute data
QChar next ()
advance past the current token
Protected Attributes
const QChar * m_chars = nullptr
QChar m_current = 0
QChar m_currentCommand = 0
double m_currentNumber = 0.0
int m_pos = 0
int m_size = 0
QString m_source
Constructor & Destructor Documentation
SVGPathLexer()
SVGPathLexer::SVGPathLexer (const QString & source)
References clean(), m_chars, m_current, m_pos, m_size, m_source, and next().
~SVGPathLexer()
SVGPathLexer::~SVGPathLexer ()
Member Function Documentation
clean()
QString SVGPathLexer::clean (const QString & source) protected
remove unneeded whitespaces from d attribute data
Clean up svg path element data to make parsing simpler
Mostly this removes extra whitespace, but it also adds a space before any minus (-) character. The SVG element 'd' attribute specification allows a negative number (leading minus sign to follow another number without any intervening separator. The minus sign acts as the separator. However (later) grammer processing does not recognized that sequence, at least for the "a" command. Inserting a leading space avoids the failing parse sequence, and does not change anything else. The extra space will get removed again by the existing (here) preprocessing, for all cases except number (space) negative number
Parameters
source original svg path d attribute data
Returns
sanitized svg path element d attribute data string
References findMinus(), TextUtils::FindWhitespace, findWhitespaceAfter(), findWhitespaceAtEnd(), and findWhitespaceBefore().
currentCommand()
QChar SVGPathLexer::currentCommand ()
References m_currentCommand.
currentNumber()
double SVGPathLexer::currentNumber ()
References m_currentNumber.
lex()
int SVGPathLexer::lex ()
extract the next token from the current attribute source data
Return the type (enum value) of the next available token (number, drawing command, or separator) from source path element attribute data string. Setup so the token information can be retrieved
Returns
type of the next available token
References SVGPathGrammar::AE, SVGPathGrammar::AITCH, SVGPathGrammar::CEE, SVGPathGrammar::COMMA, COMMAND_FAKE_CLOSE, COMMAND_LOWER_A, COMMAND_LOWER_C, COMMAND_LOWER_H, COMMAND_LOWER_L, COMMAND_LOWER_M, COMMAND_LOWER_Q, COMMAND_LOWER_S, COMMAND_LOWER_T, COMMAND_LOWER_V, COMMAND_LOWER_Z, COMMAND_UPPER_A, COMMAND_UPPER_C, COMMAND_UPPER_H, COMMAND_UPPER_L, COMMAND_UPPER_M, COMMAND_UPPER_Q, COMMAND_UPPER_S, COMMAND_UPPER_T, COMMAND_UPPER_V, COMMAND_UPPER_Z, SVGPathGrammar::EKS, SVGPathGrammar::EL, SVGPathGrammar::EM, SVGPathGrammar::EOF_SYMBOL, SVGPathGrammar::ESS, TextUtils::floatingPointMatcher, SVGPathGrammar::KYU, m_current, m_currentCommand, m_currentNumber, m_pos, m_source, next(), SVGPathGrammar::NUMBER, SEPARATOR_COMMA, SVGPathGrammar::TEE, SVGPathGrammar::VEE, SVGPathGrammar::WHITESPACE, and SVGPathGrammar::ZEE.
next()
QChar SVGPathLexer::next () protected
advance past the current token
Returns
first character of the next token
References m_chars, m_current, m_pos, and m_size.
Member Data Documentation
FakeClosePathChar
constexpr char SVGPathLexer::FakeClosePathChar = 'x' static
m_chars
const QChar* SVGPathLexer::m_chars = nullptr protected
m_current
QChar SVGPathLexer::m_current = 0 protected
m_currentCommand
QChar SVGPathLexer::m_currentCommand = 0 protected
m_currentNumber
double SVGPathLexer::m_currentNumber = 0.0 protected
m_pos
int SVGPathLexer::m_pos = 0 protected
m_size
int SVGPathLexer::m_size = 0 protected
m_source
QString SVGPathLexer::m_source protected
The documentation for this class was generated from the following files:
svg/svgpathlexer.h
svg/svgpathlexer.cpp