Fritzing: KicadSchematic2Svg Class Reference
KicadSchematic2Svg Class Reference
#include <kicadschematic2svg.h>
Public Member Functions
KicadSchematic2Svg ()
QString convert (const QString &filename, const QString &defName)
Public Member Functions inherited from Kicad2Svg
Kicad2Svg ()
QString endMetadata ()
QString makeMetadata (const QString &filename, const QString &type, const QString &name)
Public Member Functions inherited from X2Svg
X2Svg ()
void checkXLimit (double x)
void checkYLimit (double y)
Static Public Member Functions
static QStringList listDefs (const QString &filename)
Protected Member Functions
QString addFill (const QString &line, const QString &NF, const QString &strokeString)
QString convertArc (const QString &line)
QString convertCircle (const QString &line)
QString convertField (const QString &line)
QString convertField (const QString &xString, const QString &yString, const QString &fontSizeString, const QString &orientation, const QString &hjustify, const QString &vjustify, const QString &text)
QString convertPin (const QString &line, int textOffset, bool drawPinName, bool drawPinNumber, int pinIndex)
QString convertPoly (const QString &line)
QString convertRect (const QString &line)
QString convertText (const QString &line)
QStringList splitLine (const QString &line)
Protected Member Functions inherited from X2Svg
void initLimits ()
QString offsetMin (const QString &svg)
QString unquote (const QString &)
Additional Inherited Members
Protected Attributes inherited from Kicad2Svg
QString m_description
QString m_title
Protected Attributes inherited from X2Svg
QString m_attribute
QString m_comment
double m_maxX
double m_maxY
double m_minX
double m_minY
Constructor & Destructor Documentation
KicadSchematic2Svg()
KicadSchematic2Svg::KicadSchematic2Svg ()
Member Function Documentation
addFill()
QString KicadSchematic2Svg::addFill (const QString & line, const QString & NF, const QString & strokeString) protected
References DebugDialog::debug().
convert()
QString KicadSchematic2Svg::convert (const QString & filename, const QString & defName)
References convertArc(), convertCircle(), convertField(), convertPin(), convertPoly(), convertRect(), convertText(), DebugDialog::debug(), Kicad2Svg::endMetadata(), X2Svg::initLimits(), Kicad2Svg::m_description, X2Svg::m_maxX, X2Svg::m_maxY, X2Svg::m_minX, X2Svg::m_minY, Kicad2Svg::m_title, Kicad2Svg::makeMetadata(), TextUtils::makeSVGHeader(), X2Svg::offsetMin(), splitLine(), and GraphicsUtils::StandardFritzingDPI.
convertArc()
QString KicadSchematic2Svg::convertArc (const QString & line) protected
References addFill(), X2Svg::checkXLimit(), X2Svg::checkYLimit(), DebugDialog::debug(), and splitLine().
convertCircle()
QString KicadSchematic2Svg::convertCircle (const QString & line) protected
References addFill(), X2Svg::checkXLimit(), X2Svg::checkYLimit(), DebugDialog::debug(), and splitLine().
convertField() [1/2]
QString KicadSchematic2Svg::convertField (const QString & line) protected
References DebugDialog::debug(), and splitLine().
convertField() [2/2]
QString KicadSchematic2Svg::convertField (const QString & xString, const QString & yString, const QString & fontSizeString, const QString & orientation, const QString & hjustify, const QString & vjustify, const QString & text) protected
References X2Svg::checkXLimit(), X2Svg::checkYLimit(), TextUtils::escapeAnd(), OCRAFontName(), GraphicsUtils::StandardFritzingDPI, GraphicsUtils::SVGDPI, TextUtils::svgMatrix(), and X2Svg::unquote().
convertPin()
QString KicadSchematic2Svg::convertPin (const QString & line, int textOffset, bool drawPinName, bool drawPinNumber, int pinIndex) protected
References X2Svg::checkXLimit(), X2Svg::checkYLimit(), convertField(), DebugDialog::debug(), TextUtils::escapeAnd(), and splitLine().
convertPoly()
QString KicadSchematic2Svg::convertPoly (const QString & line) protected
References addFill(), X2Svg::checkXLimit(), X2Svg::checkYLimit(), DebugDialog::debug(), and splitLine().
convertRect()
QString KicadSchematic2Svg::convertRect (const QString & line) protected
References addFill(), X2Svg::checkXLimit(), X2Svg::checkYLimit(), DebugDialog::debug(), qMin(), and splitLine().
convertText()
QString KicadSchematic2Svg::convertText (const QString & line) protected
References convertField(), DebugDialog::debug(), and splitLine().
listDefs()
QStringList KicadSchematic2Svg::listDefs (const QString & filename) static
splitLine()
QStringList KicadSchematic2Svg::splitLine (const QString & line) protected
The documentation for this class was generated from the following files:
svg/kicadschematic2svg.h
svg/kicadschematic2svg.cpp