Fritzing: PaletteItemBase Class Reference
PaletteItemBase Class Reference
#include <paletteitembase.h>
Public Member Functions
PaletteItemBase (ModelPart *, ViewLayer::ViewID, const ViewGeometry &viewGeometry, long id, QMenu *itemMenu)
bool acceptsMousePressConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
void blockItemSelectedChange (bool selected)
QRectF boundingRect () const
QRectF boundingRectWithoutLegs () const
virtual bool canEditPart ()
bool collectExtraInfo (QWidget *parent, const QString &family, const QString &prop, const QString &value, bool swappingEnabled, QString &returnProp, QString &returnValue, QWidget *&returnWidget, bool &hide)
bool collectFemaleConnectees (QSet< ItemBase * > &items)
void collectWireConnectees (QSet< class Wire * > &wires)
void connectedMoved (ConnectorItem *from, ConnectorItem *to, QList< ConnectorItem * > &already)
void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
void cursorKeyEvent (Qt::KeyboardModifiers modifiers)
const QCursor * getCursor (Qt::KeyboardModifiers)
void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
void hoverMoveEvent (QGraphicsSceneHoverEvent *event)
QPainterPath hoverShape () const
bool itemMoved ()
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
virtual void mouseMoveEventK (PaletteItemBase *originalItem, QGraphicsSceneMouseEvent *event)
void mousePressConnectorEvent (class ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual bool mousePressEventK (PaletteItemBase *originalItem, QGraphicsSceneMouseEvent *event)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
virtual void mouseReleaseEventK (PaletteItemBase *originalItem, QGraphicsSceneMouseEvent *event)
void moveItem (ViewGeometry &)
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
void paintHover (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
void paintSelected (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
QString retrieveSvg (ViewLayer::ViewLayerID, QHash< QString, QString > &svgHash, bool blackOnly, double dpi, double &factor)
void saveGeometry ()
virtual void saveInstanceLocation (QXmlStreamWriter &)
void setProp (const QString &prop, const QString &value)
virtual bool setUpImage (ModelPart *modelPart, const LayerHash &viewLayers, LayerAttributes &)
QPainterPath shape () const
virtual void syncKinMoved (QPointF offset, QPointF loc)
virtual void syncKinSelection (bool selected, PaletteItemBase *originator)
QPointF syncMoved ()
bool syncSelected ()
Public Member Functions inherited from ItemBase
ItemBase (ModelPart *, ViewLayer::ViewID, const ViewGeometry &, long id, QMenu *itemMenu)
virtual ~ItemBase ()
virtual bool acceptsMouseDoubleClickConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual bool acceptsMouseMoveConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual bool acceptsMousePressLegEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual bool acceptsMouseReleaseConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual void addedToScene (bool temporary)
virtual void addSticky (ItemBase *, bool stickem)
void addSubpart (ItemBase *)
virtual bool alreadySticking (ItemBase *itemBase)
ConnectorItem * anyConnectorItem ()
QRectF boundingRect () const
virtual void busConnectorItems (Bus *bus, ConnectorItem *, QList< ConnectorItem * > &items)
QList< Bus * > buses ()
const QList< ConnectorItem * > & cachedConnectorItems ()
const QList< ConnectorItem * > & cachedConnectorItemsConst () const
virtual void calcRotation (QTransform &rotation, QPointF center, ViewGeometry &)
bool canFlip (Qt::Orientations)
bool canFlipHorizontal ()
bool canFlipVertical ()
virtual void clearConnectorHover ()
void clearConnectorItemCache ()
virtual void clearModelPart ()
void clearPartLabel ()
void collectConnectors (ConnectorPairHash &connectorHash, SkipCheckFunction)
void collectPropsMap (QString &family, QMap< QString, QString > &)
virtual void collectWireConnectees (QSet< Wire * > &wires)
virtual void connectionChange (ConnectorItem *onMe, ConnectorItem *onIt, bool connect)
virtual bool connectionIsAllowed (ConnectorItem *)
virtual void connectorHover (ConnectorItem *, ItemBase *, bool hovering)
const QString & constTitle () const
void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
void debugInfo (const QString &msg) const
void debugInfo2 (const QString &msg) const
virtual void doneLoading ()
void doRotateFlipPartLabel (double degrees, Qt::Orientations)
void ensureUniqueTitle (const QString &title, bool force)
QString family ()
virtual void figureHover ()
const QString & filename ()
virtual bool filterMousePressConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
ConnectorItem * findConnectorItemWithSharedID (const QString &connectorID, ViewLayer::ViewLayerPlacement)
ConnectorItem * findConnectorItemWithSharedID (const QString &connectorID)
ItemBase * findSubpart (const QString &connectorID, ViewLayer::ViewLayerPlacement)
virtual void flipItem (Qt::Orientations orientation)
FSvgRenderer * fsvgRenderer () const
virtual void getConnectedColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
virtual void getEqualPotentialColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
virtual void getHoverColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
virtual QString getInspectorTitle ()
virtual void getNormalColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
QPixmap * getPixmap (QSize size)
void getPixmaps (QPixmap *&, QPixmap *&, QPixmap *&, bool swappingEnabled, QSize)
virtual QString getProperty (const QString &key)
bool getRatsnest ()
virtual void getUnconnectedColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
ViewGeometry & getViewGeometry ()
bool hasConnections ()
bool hasConnectors ()
virtual bool hasCustomSVG ()
bool hasNonConnectors ()
virtual bool hasPartLabel ()
virtual bool hasPartNumberProperty ()
bool hasRubberBandLeg () const
constexpr bool hidden () const noexcept
virtual void hoverEnterConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
void hoverEnterConnectorItem ()
void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
virtual void hoverLeaveConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
void hoverLeaveConnectorItem ()
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
virtual void hoverMoveConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
virtual void hoverUpdate ()
constexpr qint64 id () const noexcept
constexpr bool inactive () const noexcept
bool inHover ()
void initLayerAttributes (LayerAttributes &layerAttributes, ViewLayer::ViewID, ViewLayer::ViewLayerID, ViewLayer::ViewLayerPlacement, bool doConnectors, bool doCreateShape)
virtual bool inRotation ()
const QString & instanceTitle () const
virtual bool isBaseSticky ()
bool isEverVisible ()
bool isLocalSticky ()
bool isObsolete ()
bool isPartLabelVisible ()
virtual PluralType isPlural ()
virtual bool isSticky ()
virtual bool isSwappable ()
int itemType () const
void killRubberBandLeg ()
QString label ()
constexpr bool layerHidden () const noexcept
virtual const QList< ItemBase * > & layerKin ()
virtual ItemBase * layerKinChief ()
QString makePartLabelSvg (bool blackOnly, double dpi, double printerScale)
ModelPart * modelPart ()
ModelPartShared * modelPartShared ()
const QString & moduleID ()
virtual void mouseDoubleClickConnectorEvent (ConnectorItem *)
virtual void mouseMoveConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
void mousePressEvent (QGraphicsSceneMouseEvent *event)
virtual void mouseReleaseConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
bool moveLock ()
void movePartLabel (QPointF newPos, QPointF newOffset)
virtual ConnectorItem * newConnectorItem (Connector *connector)
virtual ConnectorItem * newConnectorItem (ItemBase *layerkin, Connector *connector)
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
PartLabel * partLabel ()
void partLabelMoved (QPointF oldPos, QPointF oldOffset, QPointF newPos, QPointF newOffset)
QRectF partLabelSceneBoundingRect ()
QPointF partLabelScenePos ()
void partLabelSetHidden (bool hide)
ViewLayer::ViewLayerID partLabelViewLayerID ()
void prepareGeometryChange ()
virtual QHash< QString, QString > prepareProps (ModelPart *, bool wantDebug, QStringList &keys)
QString prop (const QString &p)
bool reloadRenderer (const QString &svg, bool fastload)
virtual void removeLayerKin ()
void removeTooltip ()
virtual void resetID ()
bool resetRenderer (const QString &svg)
bool resetRenderer (const QString &svg, QString &newSvg)
void resetValues (const QString &family, const QString &prop)
void restorePartLabel (QDomElement &labelGeometry, ViewLayer::ViewLayerID)
ConnectorItem * rightClickedConnector ()
void rotateFlipPartLabel (double degrees, Qt::Orientations)
virtual void rotateItem (double degrees, bool includeRatsnest)
virtual bool rotation45Allowed ()
virtual bool rotationAllowed ()
virtual void saveInstance (QXmlStreamWriter &)
bool sceneEvent (QEvent *event)
const QPainterPath & selectionShape ()
virtual void setAcceptsMousePressLegEvent (bool)
void setCanFlipHorizontal (bool)
void setCanFlipVertical (bool)
virtual void setDropOffset (QPointF offset)
void setEverVisible (bool)
void setFilename (const QString &)
virtual void setHidden (bool hidden)
virtual void setInactive (bool inactivate)
virtual void setInRotation (bool)
virtual void setInspectorTitle (const QString &oldText, const QString &newText)
virtual void setInstanceTitle (const QString &title, bool initial)
void setItemIsSelectable (bool selectable)
virtual void setItemPos (QPointF &pos)
virtual void setLayerHidden (bool hidden)
void setLocalSticky (bool)
void setModelPart (ModelPart *)
virtual void setMoveLock (bool)
void setSharedRendererEx (FSvgRenderer *)
void setSquashShape (bool)
virtual void setSticky (bool)
void setSuperpart (ItemBase *)
virtual void setSwappable (bool)
void setTooltip ()
virtual void setTransform2 (const QTransform &)
FSvgRenderer * setUpImage (ModelPart *modelPart, LayerAttributes &)
void setViewLayerID (ViewLayer::ViewLayerID, const LayerHash &viewLayers)
void setViewLayerID (const QString &layerName, const LayerHash &viewLayers)
void setViewLayerPlacement (ViewLayer::ViewLayerPlacement)
void showConnectors (const QStringList &)
constexpr QSizeF size () const noexcept
virtual void slamZ (double newZ)
const QString & spice () const
const QString & spiceModel () const
virtual ItemBase * stickingTo ()
virtual bool stickyEnabled ()
virtual QList< QPointer< ItemBase > > stickyList ()
const QList< QPointer< ItemBase > > & subparts ()
ItemBase * superpart ()
virtual const QString & title ()
bool topLevel ()
virtual void transformItem (const QTransform &, bool includeRatsnest)
virtual void transformItem2 (const QMatrix &)
void updateConnections (ConnectorItem *, bool includeRatsnest, QList< ConnectorItem * > &already)
virtual void updateConnections (bool includeRatsnest, QList< ConnectorItem * > &already)
void updateConnectionsAux (bool includeRatsnest, QList< ConnectorItem * > &already)
void updateConnectors ()
void updatePartLabelInstanceTitle ()
virtual void updateTooltip ()
ViewLayer::ViewID viewID ()
QString & viewIDName ()
ViewLayer::ViewLayerID viewLayerID () const
ViewLayer::ViewLayerPlacement viewLayerPlacement () const
ViewGeometry::WireFlags wireFlags () const
virtual void writeGeometry (QXmlStreamWriter &)
virtual void writeXml (QXmlStreamWriter &)
double z ()
Protected Slots
void partPropertyEntry ()
Protected Member Functions
virtual void cacheLoaded (const LayerAttributes &)
virtual bool canFindConnectorsUnder ()
void checkFreeRotation (Qt::KeyboardModifiers modifiers, QPointF scenePos)
void findConnectorsUnder ()
virtual bool freeRotationAllowed (Qt::KeyboardModifiers modifiers)
bool freeRotationAllowed ()
bool inRotationLocation (QPointF scenePos, Qt::KeyboardModifiers modifiers, QPointF &returnPoint)
virtual LayerKinPaletteItem * newLayerKinPaletteItem (PaletteItemBase *chief, ModelPart *, const ViewGeometry &, long id, QMenu *itemMenu, const LayerHash &, LayerAttributes &)
virtual void setInitialTransform (const QTransform &)
void setUpConnectors (FSvgRenderer *, bool ignoreTerminalPoints)
Protected Member Functions inherited from ItemBase
virtual QStringList collectValues (const QString &family, const QString &prop, QString &value)
void createShape (LayerAttributes &layerAttributes)
QPixmap * getPixmap (ViewLayer::ViewID, bool swappingEnabled, QSize size)
QVariant itemChange (QGraphicsItem::GraphicsItemChange change, const QVariant &value)
virtual bool makeLocalModifications (QByteArray &svg, const QString &filename)
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
virtual void paintBody (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
virtual void paintHover (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget, const QPainterPath &shape)
void saveLocAndTransform (QXmlStreamWriter &streamWriter)
virtual void setDefaultTooltip ()
void setInstanceTitleAux (const QString &title, bool initial)
void setInstanceTitleTooltip (const QString &text)
void updateHidden ()
virtual ViewLayer::ViewID useViewIDForPixmap (ViewLayer::ViewID, bool swappingEnabled)
Static Protected Member Functions
static QString normalizeSvg (QString &svg, ViewLayer::ViewLayerID viewLayerID, bool blackOnly, double dpi, double &factor)
Static Protected Member Functions inherited from ItemBase
static bool fixCopper1 (ModelPart *modelPart, const QString &filename, ViewLayer::ViewLayerID viewLayerID, ViewLayer::ViewLayerPlacement, QDomDocument &)
static bool getFlipDoc (ModelPart *modelPart, const QString &filename, ViewLayer::ViewLayerID viewLayerID, ViewLayer::ViewLayerPlacement, QDomDocument &, Qt::Orientations)
Protected Attributes
bool m_blockItemSelectedChange
bool m_blockItemSelectedValue
QPointF m_offset
bool m_svg
QPointF m_syncMoved
bool m_syncSelected
Protected Attributes inherited from ItemBase
bool m_acceptsMousePressLegEvent = true
QList< ConnectorItem * > m_cachedConnectorItems
bool m_canFlipHorizontal = false
bool m_canFlipVertical = false
int m_connectorHoverCount = 0
int m_connectorHoverCount2 = 0
bool m_everVisible = true
QString m_filename
FSvgRenderer * m_fsvgRenderer = nullptr
bool m_hasRubberBandLeg = false
bool m_hidden = false
int m_hoverCount = 0
bool m_hoverEnterSpaceBarWasPressed = false
qint64 m_id = 0
bool m_inactive = false
bool m_inRotation = false
QMenu * m_itemMenu = nullptr
bool m_layerHidden = false
QPointer< ModelPart > m_modelPart
bool m_moveLock = false
QGraphicsSvgItem * m_moveLockItem = nullptr
QPointer< PartLabel > m_partLabel
QMap< QString, QString > m_propsMap
ConnectorItem * m_rightClickedConnector = nullptr
QPainterPath m_selectionShape
QSizeF m_size
bool m_spaceBarWasPressed = false
bool m_squashShape = false
bool m_sticky = false
QGraphicsSvgItem * m_stickyItem = nullptr
QHash< long, QPointer< ItemBase > > m_stickyList
QList< QPointer< ItemBase > > m_subparts
QPointer< ItemBase > m_superpart
bool m_swappable = true
ViewGeometry m_viewGeometry
ViewLayer::ViewID m_viewID
ViewLayer::ViewLayerID m_viewLayerID
ViewLayer::ViewLayerPlacement m_viewLayerPlacement
bool m_zUninitialized = true
Additional Inherited Members
Public Types inherited from ItemBase
enum PluralType { Singular, Plural, NotSure }
Public Slots inherited from ItemBase
void hidePartLabel ()
void partLabelChanged (const QString &newText)
void showInFolder ()
void showPartLabel (bool show, ViewLayer *)
virtual void swapEntry (const QString &text)
Static Public Member Functions inherited from ItemBase
static void cleanup ()
static QColor connectedColor ()
static ItemBase * extractTopLevelItemBase (QGraphicsItem *thing)
static qint64 getNextID ()
static qint64 getNextID (qint64 fromIndex)
static void initNames ()
static void renderOne (QDomDocument *, QImage *, const QRectF &renderRect)
static void setConnectedColor (QColor &)
static void setReferenceModel (ReferenceModel *)
static void setUnconnectedColor (QColor &)
static QColor standardConnectedColor ()
static QColor standardUnconnectedColor ()
static QString translatePropertyName (const QString &key)
static QColor unconnectedColor ()
static bool zLessThan (ItemBase *&p1, ItemBase *&p2)
Static Public Attributes inherited from ItemBase
static const QColor ConnectorHoverColor
static const double ConnectorHoverOpacity = .40
static const QList< ItemBase * > EmptyList
static const QColor HoverColor
static const double HoverOpacity = .20
static const QString ITEMBASE_FONT_PREFIX = "<font size='2'>"
static const QString ITEMBASE_FONT_SUFFIX = "</font>"
static QString PartInstanceDefaultTitle
static QHash< QString, QString > TranslatedPropertyNames
Static Protected Attributes inherited from ItemBase
static QBrush ChosenBrush
static QPen ChosenPen
static QBrush ConnectedBrush
static QPen ConnectedPen
static QBrush EqualPotentialBrush
static QPen EqualPotentialPen
static QBrush HoverBrush
static QPen HoverPen
static long nextID
static QBrush NormalBrush
static constexpr double NormalConnectorOpacity = 0.4
static QPen NormalPen
static QPointer< ReferenceModel > TheReferenceModel = nullptr
static QBrush UnconnectedBrush
static QPen UnconnectedPen
Constructor & Destructor Documentation
PaletteItemBase()
PaletteItemBase::PaletteItemBase (ModelPart * modelPart, ViewLayer::ViewID viewID, const ViewGeometry & viewGeometry, long id, QMenu * itemMenu)
References ItemBase::hasPartNumberProperty(), ViewGeometry::loc(), ModelPart::localProp(), m_blockItemSelectedChange, m_offset, m_syncSelected, ItemBase::modelPart(), ModelPartShared::PartNumberPropertyName, ModelPart::properties(), and ModelPart::setLocalProp().
Member Function Documentation
acceptsMousePressConnectorEvent()
bool PaletteItemBase::acceptsMousePressConnectorEvent (ConnectorItem * , QGraphicsSceneMouseEvent * event) virtual
Reimplemented from ItemBase.
blockItemSelectedChange()
void PaletteItemBase::blockItemSelectedChange (bool selected)
References m_blockItemSelectedChange, and m_blockItemSelectedValue.
boundingRect()
QRectF PaletteItemBase::boundingRect () const
References ItemBase::hasRubberBandLeg(), ItemBase::m_size, and shape().
boundingRectWithoutLegs()
QRectF PaletteItemBase::boundingRectWithoutLegs () const virtual
Reimplemented from ItemBase.
References ItemBase::m_size.
cacheLoaded()
void PaletteItemBase::cacheLoaded (const LayerAttributes &) protected virtual
Reimplemented in SchematicTextLayerKinPaletteItem.
canEditPart()
bool PaletteItemBase::canEditPart () virtual
Reimplemented from ItemBase.
Reimplemented in SchematicFrame, Hole, LogoItem, Resistor, GroundPlane, Pad, Perfboard, and LED.
References ItemBase::canEditPart(), ItemBase::itemType(), and ModelPart::Part.
canFindConnectorsUnder()
bool PaletteItemBase::canFindConnectorsUnder () protected virtual
Reimplemented in Hole, Board, Ruler, Perfboard, and Breadboard.
checkFreeRotation()
void PaletteItemBase::checkFreeRotation (Qt::KeyboardModifiers modifiers, QPointF scenePos) protected
References CursorMaster::addCursor(), freeRotationAllowed(), inRotationLocation(), CursorMaster::instance(), and CursorMaster::RotateCursor.
collectExtraInfo()
bool PaletteItemBase::collectExtraInfo (QWidget * parent, const QString & family, const QString & prop, const QString & value, bool swappingEnabled, QString & returnProp, QString & returnValue, QWidget *& returnWidget, bool & hide) virtual
Reimplemented from ItemBase.
Reimplemented in ResizableBoard, Stripboard, SymbolPaletteItem, Board, SchematicFrame, PinHeader, Ruler, Perfboard, Resistor, and ScrewTerminal.
References ItemBase::collectExtraInfo(), ItemBase::family(), ItemBase::m_modelPart, ModelPartShared::PartNumberPropertyName, partPropertyEntry(), ItemBase::prop(), and ItemBase::TranslatedPropertyNames.
collectFemaleConnectees()
bool PaletteItemBase::collectFemaleConnectees (QSet< ItemBase * > & items) virtual
Reimplemented from ItemBase.
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToItemType(), ItemBase::cachedConnectorItems(), ConnectorItem::connectedToItems(), ConnectorItem::connectorType(), Connector::Female, Connector::Male, and ModelPart::Wire.
collectWireConnectees()
void PaletteItemBase::collectWireConnectees (QSet< class Wire * > & wires)
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToItemType(), ItemBase::cachedConnectorItems(), ConnectorItem::connectedToItems(), and ModelPart::Wire.
connectedMoved()
void PaletteItemBase::connectedMoved (ConnectorItem * from, ConnectorItem * to, QList< ConnectorItem * > & already) virtual
Reimplemented from ItemBase.
References ViewLayer::BreadboardView, ConnectorItem::connectorType(), Connector::Female, ItemBase::m_viewID, ConnectorItem::sceneAdjustedTerminalPoint(), and ItemBase::updateConnections().
contextMenuEvent()
void PaletteItemBase::contextMenuEvent (QGraphicsSceneContextMenuEvent * event)
References ItemBase::contextMenuEvent().
cursorKeyEvent()
void PaletteItemBase::cursorKeyEvent (Qt::KeyboardModifiers modifiers) virtual
Implements CursorKeyListener.
References CursorMaster::addCursor(), altOrMetaModifier(), checkFreeRotation(), InfoGraphicsView::getInfoGraphicsView(), ItemBase::hasRubberBandLeg(), CursorMaster::instance(), CursorMaster::MoveCursor, and CursorMaster::RubberbandCursor.
findConnectorsUnder()
void PaletteItemBase::findConnectorsUnder () protected virtual
Implements ItemBase.
References ItemBase::cachedConnectorItems(), canFindConnectorsUnder(), ConnectorItem::connector(), Connector::connectorType(), ConnectorItem::emptyConnectorItemList, Connector::Female, ConnectorItem::findConnectorUnder(), and Connector::Pad.
freeRotationAllowed() [1/2]
bool PaletteItemBase::freeRotationAllowed (Qt::KeyboardModifiers modifiers) protected virtual
Reimplemented in LogoItem, and Pad.
References ItemBase::moveLock(), and ItemBase::rotation45Allowed().
freeRotationAllowed() [2/2]
bool PaletteItemBase::freeRotationAllowed () protected virtual
Reimplemented from ItemBase.
References ItemBase::rotation45Allowed(), ViewLayer::SchematicView, and ItemBase::viewID().
getCursor()
const QCursor * PaletteItemBase::getCursor (Qt::KeyboardModifiers modifiers) virtual
Reimplemented from ItemBase.
References altOrMetaModifier(), ItemBase::cachedConnectorItems(), ConnectorItem::connectionsCount(), ItemBase::hasRubberBandLeg(), CursorMaster::MoveCursor, and CursorMaster::RubberbandCursor.
hoverEnterEvent()
void PaletteItemBase::hoverEnterEvent (QGraphicsSceneHoverEvent * event)
References CursorMaster::addCursor(), ItemBase::cachedConnectorItems(), checkFreeRotation(), ConnectorItem::connectionsCount(), ItemBase::hasRubberBandLeg(), ItemBase::hoverEnterEvent(), and CursorMaster::instance().
hoverLeaveEvent()
void PaletteItemBase::hoverLeaveEvent (QGraphicsSceneHoverEvent * event)
References ItemBase::hasRubberBandLeg(), ItemBase::hoverLeaveEvent(), CursorMaster::instance(), and CursorMaster::removeCursor().
hoverMoveEvent()
void PaletteItemBase::hoverMoveEvent (QGraphicsSceneHoverEvent * event)
References checkFreeRotation().
hoverShape()
QPainterPath PaletteItemBase::hoverShape () const virtual
Reimplemented from ItemBase.
References ItemBase::cachedConnectorItemsConst(), ConnectorItem::hasRubberBandLeg(), ItemBase::hasRubberBandLeg(), ConnectorItem::hoverShape(), and ItemBase::m_size.
inRotationLocation()
bool PaletteItemBase::inRotationLocation (QPointF scenePos, Qt::KeyboardModifiers modifiers, QPointF & returnPoint) protected
References boundingRectWithoutLegs(), GraphicsUtils::distanceSqd(), freeRotationAllowed(), ItemBase::m_viewID, and ViewLayer::SchematicView.
itemMoved()
bool PaletteItemBase::itemMoved () virtual
Implements ItemBase.
References ViewGeometry::loc(), and ItemBase::m_viewGeometry.
mouseMoveEvent()
void PaletteItemBase::mouseMoveEvent (QGraphicsSceneMouseEvent * event)
References ViewLayer::BreadboardView, InfoGraphicsView::getInfoGraphicsView(), ItemBase::getViewGeometry(), ItemBase::inRotation(), ItemBase::layerKin(), ItemBase::layerKinChief(), ItemBase::m_viewID, ItemBase::mouseMoveEvent(), OriginalTransform, ViewLayer::PCBView, ItemBase::rotateItem(), RotationAxis, RotationCenter, ViewLayer::SchematicView, ViewGeometry::setTransform(), and InfoGraphicsView::updateRotation().
mouseMoveEventK()
void PaletteItemBase::mouseMoveEventK (PaletteItemBase * originalItem, QGraphicsSceneMouseEvent * event) virtual
Reimplemented in JumperItem.
mousePressConnectorEvent()
void PaletteItemBase::mousePressConnectorEvent (class ConnectorItem * connectorItem, QGraphicsSceneMouseEvent * event) virtual
Reimplemented from ItemBase.
References InfoGraphicsView::getInfoGraphicsView(), and InfoGraphicsView::mousePressConnectorEvent().
mousePressEventK()
bool PaletteItemBase::mousePressEventK (PaletteItemBase * originalItem, QGraphicsSceneMouseEvent * event) virtual
Reimplemented in PaletteItem, and JumperItem.
References boundingRectWithoutLegs(), ItemBase::cachedConnectorItems(), canFindConnectorsUnder(), ItemBase::debugInfo(), freeRotationAllowed(), InfoGraphicsView::getInfoGraphicsView(), inRotationLocation(), ItemBase::mousePressEvent(), OriginalTransform, RotationAxis, RotationCenter, saveGeometry(), InfoGraphicsView::setAnyInRotation(), ItemBase::setInRotation(), and ConnectorItem::setOverConnectorItem().
mouseReleaseEvent()
void PaletteItemBase::mouseReleaseEvent (QGraphicsSceneMouseEvent * event)
References InfoGraphicsView::getInfoGraphicsView(), ItemBase::inRotation(), ItemBase::layerKinChief(), ItemBase::mouseReleaseEvent(), OriginalTransform, ItemBase::rotateItem(), saveGeometry(), ItemBase::setInRotation(), and InfoGraphicsView::triggerRotate().
mouseReleaseEventK()
void PaletteItemBase::mouseReleaseEventK (PaletteItemBase * originalItem, QGraphicsSceneMouseEvent * event) virtual
Reimplemented in JumperItem.
moveItem()
void PaletteItemBase::moveItem (ViewGeometry & viewGeometry) virtual
Implements ItemBase.
References ViewGeometry::loc(), and ItemBase::updateConnections().
newLayerKinPaletteItem()
LayerKinPaletteItem * PaletteItemBase::newLayerKinPaletteItem (PaletteItemBase * chief, ModelPart * modelPart, const ViewGeometry & viewGeometry, long id, QMenu * itemMenu, const LayerHash & viewLayers, LayerAttributes & layerAttributes) protected virtual
References LayerKinPaletteItem::initLKPI(), ItemBase::modelPart(), ViewLayer::SchematicText, LayerAttributes::viewID, and LayerAttributes::viewLayerID.
normalizeSvg()
QString PaletteItemBase::normalizeSvg (QString & svg, ViewLayer::ViewLayerID viewLayerID, bool blackOnly, double dpi, double & factor) static protected
References SvgFileSplitter::elementString(), SvgFileSplitter::normalize(), SvgFileSplitter::splitString(), ItemBase::viewLayerID(), and ViewLayer::viewLayerXmlNameFromID().
paint()
void PaletteItemBase::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget)
References ItemBase::m_hidden, ItemBase::m_layerHidden, and ItemBase::paint().
paintHover()
void PaletteItemBase::paintHover (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) virtual
Reimplemented from ItemBase.
Reimplemented in Perfboard, and Board.
References ItemBase::hasRubberBandLeg(), ItemBase::m_hidden, ItemBase::m_layerHidden, ItemBase::m_size, and ItemBase::paintHover().
paintSelected()
void PaletteItemBase::paintSelected (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) virtual
Reimplemented from ItemBase.
Reimplemented in ResizableBoard.
References ItemBase::hasRubberBandLeg(), ItemBase::m_hidden, ItemBase::m_layerHidden, ItemBase::m_size, ItemBase::paintSelected(), and GraphicsUtils::qt_graphicsItem_highlightSelected().
partPropertyEntry
void PaletteItemBase::partPropertyEntry () protected slot
References InfoGraphicsView::getInfoGraphicsView(), ItemBase::m_modelPart, ModelPartShared::PartNumberPropertyName, and InfoGraphicsView::setProp().
retrieveSvg()
QString PaletteItemBase::retrieveSvg (ViewLayer::ViewLayerID viewLayerID, QHash< QString, QString > & svgHash, bool blackOnly, double dpi, double & factor) virtual
Reimplemented from ItemBase.
Reimplemented in NetLabel, ResizableBoard, Stripboard, SymbolPaletteItem, SchematicFrame, Ruler, and Resistor.
References ItemBase::cachedConnectorItems(), SvgFileSplitter::elementString(), ItemBase::filename(), ItemBase::getFlipDoc(), InfoGraphicsView::getInfoGraphicsView(), SvgFileSplitter::gReplace(), ConnectorItem::hasRubberBandLeg(), ItemBase::hasRubberBandLeg(), ConnectorItem::legID(), ItemBase::m_viewID, ItemBase::m_viewLayerID, ItemBase::m_viewLayerPlacement, ItemBase::modelPart(), SvgFileSplitter::normalize(), InfoGraphicsView::smdOrientation(), SvgFileSplitter::split(), SvgFileSplitter::splitString(), ItemBase::viewLayerID(), and ViewLayer::viewLayerXmlNameFromID().
saveGeometry()
void PaletteItemBase::saveGeometry () virtual
Implements ItemBase.
References ItemBase::m_viewGeometry, ViewGeometry::setLoc(), ViewGeometry::setSelected(), and ViewGeometry::setZ().
saveInstanceLocation()
void PaletteItemBase::saveInstanceLocation (QXmlStreamWriter & streamWriter) virtual
Implements ItemBase.
Reimplemented in JumperItem, and Via.
References ItemBase::saveLocAndTransform().
setInitialTransform()
void PaletteItemBase::setInitialTransform (const QTransform & matrix) protected virtual
Reimplemented in SchematicTextLayerKinPaletteItem.
setProp()
void PaletteItemBase::setProp (const QString & prop, const QString & value) virtual
Reimplemented from ItemBase.
Reimplemented in Stripboard, SymbolPaletteItem, SchematicFrame, Resistor, and Perfboard.
References ItemBase::m_partLabel, ItemBase::modelPart(), ModelPartShared::PartNumberPropertyName, ItemBase::prop(), ModelPart::setLocalProp(), and ItemBase::setProp().
setUpConnectors()
void PaletteItemBase::setUpConnectors (FSvgRenderer * renderer, bool ignoreTerminalPoints) protected
References ItemBase::clearConnectorItemCache(), Connector::connectorSharedID(), DebugDialog::debug(), Connector::fullPinInfo(), ViewLayer::isNonCopperLayer(), ItemBase::m_hasRubberBandLeg, SvgIdLayer::m_hybrid, SvgIdLayer::m_legColor, SvgIdLayer::m_legId, SvgIdLayer::m_legLine, SvgIdLayer::m_legStrokeWidth, ItemBase::m_modelPart, SvgIdLayer::m_path, SvgIdLayer::m_radius, SvgIdLayer::m_strokeWidth, ItemBase::m_viewID, ItemBase::m_viewLayerID, ItemBase::newConnectorItem(), ViewLayer::PCBView, SvgIdLayer::point(), SvgIdLayer::rect(), ConnectorItem::setHybrid(), NonConnectorItem::setIsPath(), NonConnectorItem::setRadius(), ConnectorItem::setRubberBandLeg(), ConnectorItem::setTerminalPoint(), FSvgRenderer::setUpConnector(), FSvgRenderer::setUpNonConnectors(), and ItemBase::viewLayerPlacement().
setUpImage()
bool PaletteItemBase::setUpImage (ModelPart * modelPart, const LayerHash & viewLayers, LayerAttributes & layerAttributes) virtual
Reimplemented in Resistor, LED, JumperItem, and GroundPlane.
References ModelPart::anySticky(), cacheLoaded(), ModelPart::canFlipHorizontal(), ModelPart::canFlipVertical(), LayerAttributes::doConnectors, LayerAttributes::filename(), ModelPart::ignoreTerminalPoints(), ItemBase::m_canFlipHorizontal, ItemBase::m_canFlipVertical, ItemBase::m_filename, m_svg, ItemBase::m_viewGeometry, ItemBase::modelPart(), setInitialTransform(), ItemBase::setSharedRendererEx(), ItemBase::setSticky(), setUpConnectors(), ItemBase::setUpImage(), ItemBase::setViewLayerID(), ViewGeometry::transform(), LayerAttributes::viewID, LayerAttributes::viewLayerID, ViewLayer::viewLayerXmlNameFromID(), and ItemBase::z().
shape()
QPainterPath PaletteItemBase::shape () const
References ItemBase::cachedConnectorItemsConst(), ConnectorItem::hasRubberBandLeg(), ItemBase::hasRubberBandLeg(), ItemBase::m_size, ItemBase::m_squashShape, and ConnectorItem::shape().
syncKinMoved()
void PaletteItemBase::syncKinMoved (QPointF offset, QPointF loc) virtual
Reimplemented in PaletteItem.
syncKinSelection()
void PaletteItemBase::syncKinSelection (bool selected, PaletteItemBase * originator) virtual
Reimplemented in PaletteItem.
References m_syncSelected.
syncMoved()
QPointF PaletteItemBase::syncMoved ()
References m_syncMoved.
syncSelected()
bool PaletteItemBase::syncSelected ()
References m_syncSelected.
Member Data Documentation
m_blockItemSelectedChange
bool PaletteItemBase::m_blockItemSelectedChange protected
m_blockItemSelectedValue
bool PaletteItemBase::m_blockItemSelectedValue protected
m_offset
QPointF PaletteItemBase::m_offset protected
m_svg
bool PaletteItemBase::m_svg protected
m_syncMoved
QPointF PaletteItemBase::m_syncMoved protected
m_syncSelected
bool PaletteItemBase::m_syncSelected protected
The documentation for this class was generated from the following files:
items/paletteitembase.h
items/paletteitembase.cpp