Fritzing: Platform Class Reference
Platform Class Reference
#include <platform.h>
Signals
void commandLocationChanged ()
Public Member Functions
Platform (const QString &name)
~Platform ()=default
bool canProgram () const
QMap< QString, QString > getBoards () const
QString getCommandLocation () const noexcept
QString getDefaultBoardName () const
QUrl getDownloadUrl () const
QStringList getExtensions () const noexcept
QString getIdeName () const
QString getMinVersion () const
QString getName () const noexcept
QUrl getReferenceUrl () const
Syntaxer * getSyntaxer () const noexcept
void setBoards (const QMap< QString, QString > &boards)
void setCanProgram (bool canProgram)
void setCommandLocation (const QString &commandLocation)
void setDefaultBoardName (const QString &defaultBoardName)
void setDownloadUrl (const QUrl &downloadUrl)
void setExtensions (const QStringList &suffixes)
void setIdeName (const QString &ideName)
void setMinVersion (const QString &minVersion)
void setReferenceUrl (const QUrl &referenceUrl)
virtual void upload (QWidget *source, const QString &port, const QString &board, const QString &fileLocation)
Protected Attributes
QMap< QString, QString > m_boards
bool m_canProgram
QString m_commandLocation
QString m_defaultBoardName
QUrl m_downloadUrl
QStringList m_extensions
QString m_ideName
QString m_minVersion
QString m_name
QUrl m_referenceUrl
Private Member Functions
void initSyntaxer ()
Private Attributes
QPointer< Syntaxer > m_syntaxer
Constructor & Destructor Documentation
Platform()
Platform::Platform (const QString & name)
References initSyntaxer().
~Platform()
Platform::~Platform () default
Member Function Documentation
canProgram()
bool Platform::canProgram () const
References m_canProgram.
commandLocationChanged
void Platform::commandLocationChanged () signal
getBoards()
QMap< QString, QString > Platform::getBoards () const
References m_boards.
getCommandLocation()
QString Platform::getCommandLocation () const inline noexcept
References m_commandLocation.
getDefaultBoardName()
QString Platform::getDefaultBoardName () const
References m_defaultBoardName.
getDownloadUrl()
QUrl Platform::getDownloadUrl () const
References m_downloadUrl.
getExtensions()
QStringList Platform::getExtensions () const inline noexcept
References m_extensions.
getIdeName()
QString Platform::getIdeName () const
References m_ideName.
getMinVersion()
QString Platform::getMinVersion () const
References m_minVersion.
getName()
QString Platform::getName () const inline noexcept
References m_name.
getReferenceUrl()
QUrl Platform::getReferenceUrl () const
References m_referenceUrl.
getSyntaxer()
Syntaxer* Platform::getSyntaxer () const inline noexcept
References m_syntaxer.
initSyntaxer()
void Platform::initSyntaxer () private
References FolderUtils::getApplicationSubFolderPath(), getName(), and m_syntaxer.
setBoards()
void Platform::setBoards (const QMap< QString, QString > & boards)
References m_boards.
setCanProgram()
void Platform::setCanProgram (bool canProgram)
References canProgram(), and m_canProgram.
setCommandLocation()
void Platform::setCommandLocation (const QString & commandLocation)
References commandLocationChanged(), getName(), and m_commandLocation.
setDefaultBoardName()
void Platform::setDefaultBoardName (const QString & defaultBoardName)
References m_defaultBoardName.
setDownloadUrl()
void Platform::setDownloadUrl (const QUrl & downloadUrl)
References m_downloadUrl.
setExtensions()
void Platform::setExtensions (const QStringList & suffixes)
References m_extensions.
setIdeName()
void Platform::setIdeName (const QString & ideName)
References m_ideName.
setMinVersion()
void Platform::setMinVersion (const QString & minVersion)
References m_minVersion.
setReferenceUrl()
void Platform::setReferenceUrl (const QUrl & referenceUrl)
References m_referenceUrl.
upload()
void Platform::upload (QWidget * source, const QString & port, const QString & board, const QString & fileLocation) virtual
Reimplemented in PlatformArduino, and PlatformPicaxe.
Member Data Documentation
m_boards
QMap<QString, QString> Platform::m_boards protected
m_canProgram
bool Platform::m_canProgram protected
m_commandLocation
QString Platform::m_commandLocation protected
m_defaultBoardName
QString Platform::m_defaultBoardName protected
m_downloadUrl
QUrl Platform::m_downloadUrl protected
m_extensions
QStringList Platform::m_extensions protected
m_ideName
QString Platform::m_ideName protected
m_minVersion
QString Platform::m_minVersion protected
m_name
QString Platform::m_name protected
m_referenceUrl
QUrl Platform::m_referenceUrl protected
m_syntaxer
QPointer<Syntaxer> Platform::m_syntaxer private
The documentation for this class was generated from the following files:
program/platform.h
program/platform.cpp