Fritzing: PEGraphicsItem Class Reference
PEGraphicsItem Class Reference
#include <pegraphicsitem.h>
Signals
void highlightSignal (PEGraphicsItem *)
void mousePressedSignal (PEGraphicsItem *, bool &ignore)
void mouseReleasedSignal (PEGraphicsItem *)
void terminalPointChanged (PEGraphicsItem *, QPointF before, QPointF after)
void terminalPointMoved (PEGraphicsItem *, QPointF)
Public Member Functions
PEGraphicsItem (double x, double y, double width, double height, class ItemBase *)
~PEGraphicsItem ()
QDomElement & element ()
void flash ()
bool highlighted ()
void hoverEnterEvent (QGraphicsSceneHoverEvent *)
void hoverLeaveEvent (QGraphicsSceneHoverEvent *)
class ItemBase * itemBase ()
void mouseMoveEvent (QGraphicsSceneMouseEvent *)
void mousePressEvent (QGraphicsSceneMouseEvent *)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *)
QPointF offset ()
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
QPointF pendingTerminalPoint ()
void setElement (QDomElement &)
void setHighlighted (bool)
void setOffset (QPointF)
void setPendingTerminalPoint (QPointF)
void setPickAppearance (bool)
void setTerminalPoint (QPointF)
bool showingMarquee ()
bool showingTerminalPoint ()
void showMarquee (bool)
void showTerminalPoint (bool)
QPointF terminalPoint ()
void wheelEvent (QGraphicsSceneWheelEvent *)
Protected Slots
void restoreColor ()
Protected Attributes
QPointF m_dragTerminalOrigin
bool m_dragTerminalPoint = false
bool m_drawHighlight = false
QDomElement m_element
bool m_flash = false
bool m_highlighted = false
class ItemBase * m_itemBase = nullptr
QPointF m_offset
QPointF m_pendingTerminalPoint
bool m_pick = false
qreal m_savedOpacity = 0
bool m_showMarquee = false
bool m_showTerminalPoint = false
QPointF m_terminalPoint
QPointF m_terminalPointOrigin
int m_wheelAccum = 0
Constructor & Destructor Documentation
PEGraphicsItem()
PEGraphicsItem::PEGraphicsItem (double x, double y, double width, double height, class ItemBase * itemBase)
References Dashes, DashLength, itemBase(), m_dragTerminalPoint, m_flash, m_itemBase, m_pick, m_showMarquee, m_showTerminalPoint, m_terminalPoint, NormalColor(), and setHighlighted().
~PEGraphicsItem()
PEGraphicsItem::~PEGraphicsItem ()
References m_element.
Member Function Documentation
element()
QDomElement & PEGraphicsItem::element ()
References m_element.
flash()
void PEGraphicsItem::flash ()
References m_flash, and m_savedOpacity.
highlighted()
bool PEGraphicsItem::highlighted ()
References m_highlighted.
highlightSignal
void PEGraphicsItem::highlightSignal (PEGraphicsItem *) signal
hoverEnterEvent()
void PEGraphicsItem::hoverEnterEvent (QGraphicsSceneHoverEvent *)
References m_wheelAccum, and setHighlighted().
hoverLeaveEvent()
void PEGraphicsItem::hoverLeaveEvent (QGraphicsSceneHoverEvent *)
References setHighlighted().
itemBase()
ItemBase * PEGraphicsItem::itemBase ()
References m_itemBase.
mouseMoveEvent()
void PEGraphicsItem::mouseMoveEvent (QGraphicsSceneMouseEvent * event)
References m_dragTerminalOrigin, m_dragTerminalPoint, m_terminalPoint, m_terminalPointOrigin, MinMouseMove, OriginalShiftPos, ShiftDown, ShiftX, ShiftY, and terminalPointMoved().
mousePressedSignal
void PEGraphicsItem::mousePressedSignal (PEGraphicsItem * , bool & ignore) signal
mousePressEvent()
void PEGraphicsItem::mousePressEvent (QGraphicsSceneMouseEvent * event)
References InfoGraphicsView::getInfoGraphicsView(), m_dragTerminalOrigin, m_dragTerminalPoint, m_highlighted, m_showMarquee, m_terminalPoint, m_terminalPointOrigin, MinMouseMove, mousePressedSignal(), OriginalShiftPos, ShiftDown, ShiftX, ShiftY, and InfoGraphicsView::spaceBarIsPressed().
mouseReleasedSignal
void PEGraphicsItem::mouseReleasedSignal (PEGraphicsItem *) signal
mouseReleaseEvent()
void PEGraphicsItem::mouseReleaseEvent (QGraphicsSceneMouseEvent *)
References m_dragTerminalPoint, m_terminalPoint, m_terminalPointOrigin, mouseReleasedSignal(), and terminalPointChanged().
offset()
QPointF PEGraphicsItem::offset ()
References m_offset.
paint()
void PEGraphicsItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget)
References m_flash, m_showMarquee, m_showTerminalPoint, m_terminalPoint, qMin(), and restoreColor().
pendingTerminalPoint()
QPointF PEGraphicsItem::pendingTerminalPoint ()
References m_pendingTerminalPoint.
restoreColor
void PEGraphicsItem::restoreColor () protected slot
References m_pick, m_savedOpacity, NormalColor(), and PickColor().
setElement()
void PEGraphicsItem::setElement (QDomElement & el)
References m_element.
setHighlighted()
void PEGraphicsItem::setHighlighted (bool highlighted)
References highlighted(), highlightSignal(), m_highlighted, and setHighlighted().
setOffset()
void PEGraphicsItem::setOffset (QPointF p)
References m_offset.
setPendingTerminalPoint()
void PEGraphicsItem::setPendingTerminalPoint (QPointF p)
References m_pendingTerminalPoint.
setPickAppearance()
void PEGraphicsItem::setPickAppearance (bool pick)
References m_pick, NormalColor(), and PickColor().
setTerminalPoint()
void PEGraphicsItem::setTerminalPoint (QPointF p)
References m_pendingTerminalPoint, and m_terminalPoint.
showingMarquee()
bool PEGraphicsItem::showingMarquee ()
References m_showMarquee.
showingTerminalPoint()
bool PEGraphicsItem::showingTerminalPoint ()
References m_showTerminalPoint.
showMarquee()
void PEGraphicsItem::showMarquee (bool show)
References m_showMarquee, showingMarquee(), and showMarquee().
showTerminalPoint()
void PEGraphicsItem::showTerminalPoint (bool show)
References m_showTerminalPoint.
terminalPoint()
QPointF PEGraphicsItem::terminalPoint ()
References m_terminalPoint.
terminalPointChanged
void PEGraphicsItem::terminalPointChanged (PEGraphicsItem * , QPointF before, QPointF after) signal
terminalPointMoved
void PEGraphicsItem::terminalPointMoved (PEGraphicsItem * , QPointF) signal
wheelEvent()
void PEGraphicsItem::wheelEvent (QGraphicsSceneWheelEvent * event)
References flash(), highlighted(), m_wheelAccum, qMin(), and setHighlighted().
Member Data Documentation
m_dragTerminalOrigin
QPointF PEGraphicsItem::m_dragTerminalOrigin protected
m_dragTerminalPoint
bool PEGraphicsItem::m_dragTerminalPoint = false protected
m_drawHighlight
bool PEGraphicsItem::m_drawHighlight = false protected
m_element
QDomElement PEGraphicsItem::m_element protected
m_flash
bool PEGraphicsItem::m_flash = false protected
m_highlighted
bool PEGraphicsItem::m_highlighted = false protected
m_itemBase
class ItemBase* PEGraphicsItem::m_itemBase = nullptr protected
m_offset
QPointF PEGraphicsItem::m_offset protected
m_pendingTerminalPoint
QPointF PEGraphicsItem::m_pendingTerminalPoint protected
m_pick
bool PEGraphicsItem::m_pick = false protected
m_savedOpacity
qreal PEGraphicsItem::m_savedOpacity = 0 protected
m_showMarquee
bool PEGraphicsItem::m_showMarquee = false protected
m_showTerminalPoint
bool PEGraphicsItem::m_showTerminalPoint = false protected
m_terminalPoint
QPointF PEGraphicsItem::m_terminalPoint protected
m_terminalPointOrigin
QPointF PEGraphicsItem::m_terminalPointOrigin protected
m_wheelAccum
int PEGraphicsItem::m_wheelAccum = 0 protected
The documentation for this class was generated from the following files:
partseditor/pegraphicsitem.h
partseditor/pegraphicsitem.cpp