Fritzing: autoroute/cmrouter/tileutils.h File Reference
tileutils.h File Reference
#include "tile.h"
Functions
int fasterRealToTile (double x)
void qrectToTile (QRectF &rect, TileRect &tileRect)
void realsToTile (TileRect &tileRect, double l, double t, double r, double b)
int realToTile (double x)
void tileRectToQRect (TileRect &tileRect, QRectF &rect)
void tileRotate90 (TileRect &tileRect, TileRect &tileRect90)
void tileToQRect (Tile *tile, QRectF &rect)
double tileToReal (int x)
void tileUnrotate90 (TileRect &tileRect90, TileRect &tileRect)
Variables
static const int TILEFACTOR = 1000
Function Documentation
fasterRealToTile()
int fasterRealToTile (double x) inline
References TILEFACTOR.
qrectToTile()
void qrectToTile (QRectF & rect, TileRect & tileRect) inline
References realsToTile().
realsToTile()
void realsToTile (TileRect & tileRect, double l, double t, double r, double b) inline
References fasterRealToTile(), TileRect::xmaxi, TileRect::xmini, TileRect::ymaxi, and TileRect::ymini.
realToTile()
int realToTile (double x) inline
References TILEFACTOR.
tileRectToQRect()
void tileRectToQRect (TileRect & tileRect, QRectF & rect) inline
References tileToReal(), TileRect::xmaxi, TileRect::xmini, TileRect::ymaxi, and TileRect::ymini.
tileRotate90()
void tileRotate90 (TileRect & tileRect, TileRect & tileRect90) inline
References TileRect::xmaxi, TileRect::xmini, TileRect::ymaxi, and TileRect::ymini.
tileToQRect()
void tileToQRect (Tile * tile, QRectF & rect) inline
References tileRectToQRect(), and TiToRect().
tileToReal()
double tileToReal (int x) inline
References TILEFACTOR.
tileUnrotate90()
void tileUnrotate90 (TileRect & tileRect90, TileRect & tileRect) inline
References TileRect::xmaxi, TileRect::xmini, TileRect::ymaxi, and TileRect::ymini.
Variable Documentation
TILEFACTOR
const int TILEFACTOR = 1000 static