Fritzing: SvgText Class Reference
SvgText Class Reference
#include <svgtext.h>
Static Public Member Functions
static void renderText (QImage &image, QDomElement &text, int &minX, int &minY, int &maxX, int &maxY, QMatrix &matrix, QRectF &viewBox)
Member Function Documentation
renderText()
void SvgText::renderText (QImage & image, QDomElement & text, int & minX, int & minY, int & maxX, int & maxY, QMatrix & matrix, QRectF & viewBox) static
References IDString(), int(), MINMAX, qMax(), and qMin().
The documentation for this class was generated from the following files:
svg/svgtext.h
svg/svgtext.cpp