Fritzing: ZoomableGraphicsView Class Reference
ZoomableGraphicsView Class Reference
#include <zoomablegraphicsview.h>
Public Types
enum WheelMapping { ScrollPrimary, ZoomPrimary, WheelMappingCount }
Signals
void wheelSignal ()
void zoomChanged (double zoom)
void zoomOutOfRange (double zoom)
Public Member Functions
ZoomableGraphicsView (QWidget *parent=0)
void absoluteZoom (double percent)
double currentZoom ()
virtual void ensureFixedToBottomRightItems ()
void relativeZoom (double step, bool centerToCursor)
void setAcceptWheelEvents (bool)
virtual void setViewFromBelow (bool)
bool viewFromBelow ()
Static Public Member Functions
static void setWheelMapping (WheelMapping)
static WheelMapping wheelMapping ()
Static Public Attributes
static const int MaxScaleValue = 3000
Protected Member Functions
virtual void wheelEvent (QWheelEvent *event)
Protected Attributes
bool m_acceptWheelEvents
int m_maxScaleValue
int m_minScaleValue
double m_scaleValue
bool m_viewFromBelow
Static Protected Attributes
static WheelMapping m_wheelMapping
Member Enumeration Documentation
WheelMapping
enum ZoomableGraphicsView::WheelMapping
Enumerator
ScrollPrimary
ZoomPrimary
WheelMappingCount
Constructor & Destructor Documentation
ZoomableGraphicsView()
ZoomableGraphicsView::ZoomableGraphicsView (QWidget * parent = 0)
References FirstTime, m_acceptWheelEvents, m_maxScaleValue, m_minScaleValue, m_scaleValue, m_viewFromBelow, m_wheelMapping, MaxScaleValue, ScrollPrimary, and WheelMappingCount.
Member Function Documentation
absoluteZoom()
void ZoomableGraphicsView::absoluteZoom (double percent)
References m_scaleValue, and relativeZoom().
currentZoom()
double ZoomableGraphicsView::currentZoom ()
References m_scaleValue.
ensureFixedToBottomRightItems()
virtual void ZoomableGraphicsView::ensureFixedToBottomRightItems () inline virtual
Reimplemented in PartsEditorView.
relativeZoom()
void ZoomableGraphicsView::relativeZoom (double step, bool centerToCursor)
References m_maxScaleValue, m_minScaleValue, m_scaleValue, m_viewFromBelow, zoomChanged(), and zoomOutOfRange().
setAcceptWheelEvents()
void ZoomableGraphicsView::setAcceptWheelEvents (bool accept)
References m_acceptWheelEvents.
setViewFromBelow()
void ZoomableGraphicsView::setViewFromBelow (bool viewFromBelow) virtual
Reimplemented in PCBSketchWidget.
References m_viewFromBelow, and viewFromBelow().
setWheelMapping()
void ZoomableGraphicsView::setWheelMapping (WheelMapping wm) static
References m_wheelMapping.
viewFromBelow()
bool ZoomableGraphicsView::viewFromBelow ()
References m_viewFromBelow.
wheelEvent()
void ZoomableGraphicsView::wheelEvent (QWheelEvent * event) protected virtual
Reimplemented in PartsEditorView.
References altOrMetaModifier(), m_acceptWheelEvents, m_wheelMapping, relativeZoom(), ScrollPrimary, wheelSignal(), ZoomPrimary, and ZoomSlider::ZoomStep.
wheelMapping()
ZoomableGraphicsView::WheelMapping ZoomableGraphicsView::wheelMapping () static
References m_wheelMapping.
wheelSignal
void ZoomableGraphicsView::wheelSignal () signal
zoomChanged
void ZoomableGraphicsView::zoomChanged (double zoom) signal
zoomOutOfRange
void ZoomableGraphicsView::zoomOutOfRange (double zoom) signal
Member Data Documentation
m_acceptWheelEvents
bool ZoomableGraphicsView::m_acceptWheelEvents protected
m_maxScaleValue
int ZoomableGraphicsView::m_maxScaleValue protected
m_minScaleValue
int ZoomableGraphicsView::m_minScaleValue protected
m_scaleValue
double ZoomableGraphicsView::m_scaleValue protected
m_viewFromBelow
bool ZoomableGraphicsView::m_viewFromBelow protected
m_wheelMapping
ZoomableGraphicsView::WheelMapping ZoomableGraphicsView::m_wheelMapping static protected
Initial value:
=
    ScrollPrimary
MaxScaleValue
const int ZoomableGraphicsView::MaxScaleValue = 3000 static
The documentation for this class was generated from the following files:
sketch/zoomablegraphicsview.h
sketch/zoomablegraphicsview.cpp