Fritzing: AbstractImageButton Class Reference
AbstractImageButton Class Reference abstract
#include <abstractimagebutton.h>
Signals
void clicked ()
Public Member Functions
AbstractImageButton (QWidget *parent=0)
virtual ~AbstractImageButton ()
Public Member Functions inherited from AbstractStatesButton
virtual ~AbstractStatesButton ()
void setDisabledIcon ()
void setEnabledIcon ()
void setPressedIcon ()
Protected Member Functions
virtual QString imagePrefix ()=0
void mousePressEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
void setImage (const QPixmap &pixmap)
Protected Member Functions inherited from AbstractStatesButton
virtual QString imageSubfix ()
virtual void setupIcons (const QString &imageName, bool hasStates=true)
Additional Inherited Members
Protected Attributes inherited from AbstractStatesButton
QPixmap m_disabledImage
QPixmap m_enabledImage
QPixmap m_pressedImage
Constructor & Destructor Documentation
AbstractImageButton()
AbstractImageButton::AbstractImageButton (QWidget * parent = 0) inline
~AbstractImageButton()
virtual AbstractImageButton::~AbstractImageButton () inline virtual
Member Function Documentation
clicked
void AbstractImageButton::clicked () signal
imagePrefix()
virtual QString AbstractImageButton::imagePrefix () protected pure virtual
Implements AbstractStatesButton.
Implemented in AddRemoveConnectorButton.
mousePressEvent()
void AbstractImageButton::mousePressEvent (QMouseEvent * event) inline protected
References AbstractStatesButton::setPressedIcon().
mouseReleaseEvent()
void AbstractImageButton::mouseReleaseEvent (QMouseEvent * event) inline protected
References clicked(), and AbstractStatesButton::setEnabledIcon().
setImage()
void AbstractImageButton::setImage (const QPixmap & pixmap) inline protected virtual
Implements AbstractStatesButton.
The documentation for this class was generated from the following file:
partseditor/obsolete/abstractimagebutton.h