Fritzing: ClipableWire Class Reference
ClipableWire Class Reference
#include <clipablewire.h>
Public Member Functions
ClipableWire (ModelPart *modelPart, ViewLayer::ViewID, const ViewGeometry &, long id, QMenu *itemMenu, bool initLabel)
bool filterMousePressConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
const QLineF & getPaintLine ()
void hoverEnterConnectorItem (QGraphicsSceneHoverEvent *event, class ConnectorItem *item)
void hoverLeaveConnectorItem (QGraphicsSceneHoverEvent *event, class ConnectorItem *item)
void hoverMoveConnectorItem (QGraphicsSceneHoverEvent *event, class ConnectorItem *item)
void mousePressEvent (QGraphicsSceneMouseEvent *event)
void setClipEnds (bool)
Public Member Functions inherited from Wire
Wire (class ModelPart *, ViewLayer::ViewID, const ViewGeometry &, long id, QMenu *itemMenu, bool initLabel)
virtual ~Wire ()
void addedToScene (bool temporary)
bool banded ()
QRectF boundingRect () const
bool canChainMultiple ()
bool canChangeColor ()
bool canHaveCurve ()
virtual bool canSwitchLayers ()
void changeCurve (const class Bezier *)
void collectChained (QList< Wire * > &, QList< ConnectorItem * > &ends)
void collectDirectWires (QList< Wire * > &wires)
bool collectExtraInfo (QWidget *parent, const QString &family, const QString &prop, const QString &value, bool swappingEnabled, QString &returnProp, QString &returnValue, QWidget *&returnWidget, bool &hide)
void collectWires (QList< Wire * > &wires)
const QColor & color ()
void colorByLength (bool)
QString colorString ()
void connectedMoved (ConnectorItem *from, ConnectorItem *to, QList< ConnectorItem * > &already)
ConnectorItem * connector0 ()
QRectF connector0Rect (const QLineF &line)
ConnectorItem * connector1 ()
QRectF connector1Rect (const QLineF &line)
void cursorKeyEvent (Qt::KeyboardModifiers modifiers)
const class Bezier * curve ()
bool draggingEnd ()
void findConnectorsUnder ()
Wire * findTraced (ViewGeometry::WireFlags flags, QList< ConnectorItem * > &ends)
bool getAutoroutable ()
bool getNormal ()
bool getRouted ()
bool getTrace ()
bool hasAnyFlag (ViewGeometry::WireFlags)
bool hasFlag (ViewGeometry::WireFlag)
bool hasPartLabel ()
bool hasPartNumberProperty ()
bool hasShadow ()
QString hexString ()
void hoverEnterConnectorItem (QGraphicsSceneHoverEvent *event, class ConnectorItem *item)
void hoverLeaveConnectorItem (QGraphicsSceneHoverEvent *event, class ConnectorItem *item)
QPainterPath hoverShape () const
double hoverStrokeWidth ()
void initDragCurve (QPointF scenePos)
void initDragEnd (ConnectorItem *dragEnd, QPointF scenePos)
bool initNewBendpoint (QPointF scenePos, class Bezier &left, class Bezier &right)
bool isCurved ()
bool isGrounded ()
PluralType isPlural ()
bool isTraceType (ViewGeometry::WireFlag)
bool itemMoved ()
QLineF line () const
double mils ()
void moveItem (ViewGeometry &viewGeometry)
double opacity ()
void originalConnectorDimensions (double &width, double &height)
ConnectorItem * otherConnector (ConnectorItem *)
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)
void paintBody (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
QPen pen () const
bool rotation45Allowed ()
bool rotationAllowed ()
void saveGeometry ()
void saveInstanceLocation (QXmlStreamWriter &)
QPolygonF sceneCurve (QPointF offset)
void setAutoroutable (bool)
void setBanded (bool)
void setCanChainMultiple (bool)
virtual void setColor (const QColor &, double opacity)
void setColorString (QString, double opacity, bool restore)
void setConnector0Rect ()
void setConnector1Rect ()
void setConnectorDimensions (double width, double height)
void setDisplayBendpointCursor (bool)
void setExtras (QDomElement &, InfoGraphicsView *)
virtual void setLine (const QLineF &line)
void setLine (double x1, double y1, double x2, double y2)
void setLineAnd (QLineF line, QPointF pos, bool useLine)
void setNormal (bool)
void setOpacity (double opacity)
void setPcbPenBrush (QBrush &brush)
void setPen (const QPen &pen)
void setPenWidth (double width, InfoGraphicsView *, double hoverStrokeWidth)
void setProp (const QString &prop, const QString &value)
void setRatsnest (bool)
void setRouted (bool)
virtual class FSvgRenderer * setUp (ViewLayer::ViewLayerID viewLayerID, const LayerHash &viewLayers, class InfoGraphicsView *)
void setWireFlags (ViewGeometry::WireFlags)
void setWireWidth (double width, InfoGraphicsView *, double hoverStrokeWidth)
QString shadowHexString ()
double shadowWidth ()
QPainterPath shape () const
void simpleConnectedMoved (ConnectorItem *to)
void simpleConnectedMoved (ConnectorItem *from, ConnectorItem *to)
bool stickyEnabled ()
const class Bezier * undoCurve ()
double width ()
void writeGeometry (QXmlStreamWriter &)
Public Member Functions inherited from ItemBase
ItemBase (ModelPart *, ViewLayer::ViewID, const ViewGeometry &, long id, QMenu *itemMenu)
virtual ~ItemBase ()
virtual bool acceptsMousePressConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual bool acceptsMousePressLegEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual void addSticky (ItemBase *, bool stickem)
void addSubpart (ItemBase *)
virtual bool alreadySticking (ItemBase *itemBase)
ConnectorItem * anyConnectorItem ()
QRectF boundingRect () const
virtual QRectF boundingRectWithoutLegs () const
virtual void busConnectorItems (Bus *bus, ConnectorItem *, QList< ConnectorItem * > &items)
QList< Bus * > buses ()
const QList< ConnectorItem * > & cachedConnectorItems ()
const QList< ConnectorItem * > & cachedConnectorItemsConst () const
virtual void calcRotation (QTransform &rotation, QPointF center, ViewGeometry &)
virtual bool canEditPart ()
bool canFlip (Qt::Orientations)
bool canFlipHorizontal ()
bool canFlipVertical ()
virtual void clearConnectorHover ()
void clearConnectorItemCache ()
virtual void clearModelPart ()
void clearPartLabel ()
void collectConnectors (ConnectorPairHash &connectorHash, SkipCheckFunction)
virtual bool collectFemaleConnectees (QSet< ItemBase * > &items)
void collectPropsMap (QString &family, QMap< QString, QString > &)
virtual void collectWireConnectees (QSet< Wire * > &wires)
virtual void connectorHover (ConnectorItem *, ItemBase *, bool hovering)
const QString & constTitle () const
void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
void debugInfo (const QString &msg) const
void debugInfo2 (const QString &msg) const
virtual void doneLoading ()
void doRotateFlipPartLabel (double degrees, Qt::Orientations)
void ensureUniqueTitle (const QString &title, bool force)
QString family ()
virtual void figureHover ()
const QString & filename ()
ConnectorItem * findConnectorItemWithSharedID (const QString &connectorID, ViewLayer::ViewLayerPlacement)
ConnectorItem * findConnectorItemWithSharedID (const QString &connectorID)
ItemBase * findSubpart (const QString &connectorID, ViewLayer::ViewLayerPlacement)
virtual void flipItem (Qt::Orientations orientation)
virtual bool freeRotationAllowed ()
FSvgRenderer * fsvgRenderer () const
virtual const QCursor * getCursor (Qt::KeyboardModifiers)
virtual void getEqualPotentialColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
virtual void getHoverColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
virtual QString getInspectorTitle ()
virtual void getNormalColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
QPixmap * getPixmap (QSize size)
void getPixmaps (QPixmap *&, QPixmap *&, QPixmap *&, bool swappingEnabled, QSize)
virtual QString getProperty (const QString &key)
bool getRatsnest ()
virtual void getUnconnectedColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
ViewGeometry & getViewGeometry ()
bool hasConnections ()
bool hasConnectors ()
virtual bool hasCustomSVG ()
bool hasNonConnectors ()
bool hasRubberBandLeg () const
constexpr bool hidden () const noexcept
void hoverEnterConnectorItem ()
void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
void hoverLeaveConnectorItem ()
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
virtual void hoverUpdate ()
constexpr qint64 id () const noexcept
constexpr bool inactive () const noexcept
bool inHover ()
void initLayerAttributes (LayerAttributes &layerAttributes, ViewLayer::ViewID, ViewLayer::ViewLayerID, ViewLayer::ViewLayerPlacement, bool doConnectors, bool doCreateShape)
virtual bool inRotation ()
const QString & instanceTitle () const
virtual bool isBaseSticky ()
bool isEverVisible ()
bool isLocalSticky ()
bool isObsolete ()
bool isPartLabelVisible ()
virtual bool isSticky ()
virtual bool isSwappable ()
int itemType () const
void killRubberBandLeg ()
QString label ()
constexpr bool layerHidden () const noexcept
virtual const QList< ItemBase * > & layerKin ()
virtual ItemBase * layerKinChief ()
QString makePartLabelSvg (bool blackOnly, double dpi, double printerScale)
ModelPart * modelPart ()
ModelPartShared * modelPartShared ()
const QString & moduleID ()
void mousePressEvent (QGraphicsSceneMouseEvent *event)
bool moveLock ()
void movePartLabel (QPointF newPos, QPointF newOffset)
virtual ConnectorItem * newConnectorItem (Connector *connector)
virtual ConnectorItem * newConnectorItem (ItemBase *layerkin, Connector *connector)
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
PartLabel * partLabel ()
void partLabelMoved (QPointF oldPos, QPointF oldOffset, QPointF newPos, QPointF newOffset)
QRectF partLabelSceneBoundingRect ()
QPointF partLabelScenePos ()
void partLabelSetHidden (bool hide)
ViewLayer::ViewLayerID partLabelViewLayerID ()
void prepareGeometryChange ()
virtual QHash< QString, QString > prepareProps (ModelPart *, bool wantDebug, QStringList &keys)
QString prop (const QString &p)
bool reloadRenderer (const QString &svg, bool fastload)
virtual void removeLayerKin ()
void removeTooltip ()
virtual void resetID ()
bool resetRenderer (const QString &svg)
bool resetRenderer (const QString &svg, QString &newSvg)
void resetValues (const QString &family, const QString &prop)
void restorePartLabel (QDomElement &labelGeometry, ViewLayer::ViewLayerID)
virtual QString retrieveSvg (ViewLayer::ViewLayerID, QHash< QString, QString > &svgHash, bool blackOnly, double dpi, double &factor)
ConnectorItem * rightClickedConnector ()
void rotateFlipPartLabel (double degrees, Qt::Orientations)
virtual void rotateItem (double degrees, bool includeRatsnest)
virtual void saveInstance (QXmlStreamWriter &)
bool sceneEvent (QEvent *event)
const QPainterPath & selectionShape ()
virtual void setAcceptsMousePressLegEvent (bool)
void setCanFlipHorizontal (bool)
void setCanFlipVertical (bool)
virtual void setDropOffset (QPointF offset)
void setEverVisible (bool)
void setFilename (const QString &)
virtual void setHidden (bool hidden)
virtual void setInactive (bool inactivate)
virtual void setInRotation (bool)
virtual void setInspectorTitle (const QString &oldText, const QString &newText)
virtual void setInstanceTitle (const QString &title, bool initial)
void setItemIsSelectable (bool selectable)
virtual void setItemPos (QPointF &pos)
virtual void setLayerHidden (bool hidden)
void setLocalSticky (bool)
void setModelPart (ModelPart *)
virtual void setMoveLock (bool)
void setSharedRendererEx (FSvgRenderer *)
void setSquashShape (bool)
virtual void setSticky (bool)
void setSuperpart (ItemBase *)
virtual void setSwappable (bool)
void setTooltip ()
virtual void setTransform2 (const QTransform &)
FSvgRenderer * setUpImage (ModelPart *modelPart, LayerAttributes &)
void setViewLayerID (ViewLayer::ViewLayerID, const LayerHash &viewLayers)
void setViewLayerID (const QString &layerName, const LayerHash &viewLayers)
void setViewLayerPlacement (ViewLayer::ViewLayerPlacement)
void showConnectors (const QStringList &)
constexpr QSizeF size () const noexcept
virtual void slamZ (double newZ)
const QString & spice () const
const QString & spiceModel () const
virtual ItemBase * stickingTo ()
virtual QList< QPointer< ItemBase > > stickyList ()
const QList< QPointer< ItemBase > > & subparts ()
ItemBase * superpart ()
virtual const QString & title ()
bool topLevel ()
virtual void transformItem (const QTransform &, bool includeRatsnest)
virtual void transformItem2 (const QMatrix &)
void updateConnections (ConnectorItem *, bool includeRatsnest, QList< ConnectorItem * > &already)
virtual void updateConnections (bool includeRatsnest, QList< ConnectorItem * > &already)
void updateConnectionsAux (bool includeRatsnest, QList< ConnectorItem * > &already)
void updateConnectors ()
void updatePartLabelInstanceTitle ()
virtual void updateTooltip ()
ViewLayer::ViewID viewID ()
QString & viewIDName ()
ViewLayer::ViewLayerID viewLayerID () const
ViewLayer::ViewLayerPlacement viewLayerPlacement () const
ViewGeometry::WireFlags wireFlags () const
virtual void writeXml (QXmlStreamWriter &)
double z ()
Protected Member Functions
void calcClip (QPointF &p1, QPointF &p2, ConnectorItem *c1, ConnectorItem *c2)
void dispatchHover (QPointF scenePos)
void dispatchHoverAux (bool inInner, Wire *inWire)
QPointF findIntersection (ConnectorItem *connectorItem, const QPointF &p)
bool insideInnerCircle (ConnectorItem *connectorItem, QPointF localPos)
bool insideSpoke (ClipableWire *wire, QPointF scenePos)
Protected Member Functions inherited from Wire
bool acceptsMouseDoubleClickConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
bool acceptsMouseMoveConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
bool acceptsMouseReleaseConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
void calcNewLine (ConnectorItem *from, ConnectorItem *to, QPointF &p1, QPointF &p2)
void checkVisibility (ConnectorItem *onMe, ConnectorItem *onIt, bool connect)
void collectChained (ConnectorItem *connectorItem, QList< Wire * > &chained, QList< ConnectorItem * > &ends)
void collectDirectWires (ConnectorItem *connectorItem, QList< Wire * > &wires, QList< ConnectorItem * > &junctions)
void collectWiresAux (QList< Wire * > &wires, ConnectorItem *start)
bool coloredByLength ()
QColor colorForLength ()
void connectionChange (ConnectorItem *onMe, ConnectorItem *onIt, bool connect)
bool connectionIsAllowed (ConnectorItem *)
void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
void dragCurve (QPointF eventPos, Qt::KeyboardModifiers)
void getConnectedColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
void initEnds (const ViewGeometry &, QRectF defaultRect, class InfoGraphicsView *)
bool isBendpoint (ConnectorItem *connectorItem)
QVariant itemChange (GraphicsItemChange change, const QVariant &value)
void mouseDoubleClickConnectorEvent (ConnectorItem *)
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event)
void mouseMoveConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
void mouseMoveEventAux (QPointF eventPos, Qt::KeyboardModifiers)
void mousePressConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
void mousePressEvent (QGraphicsSceneMouseEvent *event)
void mouseReleaseConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
void paintHover (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
bool releaseDrag ()
virtual void setColorFromElement (QDomElement &element)
void setConnectorDimensionsAux (ConnectorItem *, double width, double height)
void setIgnoreSelectionChange (bool)
void setShadowColor (QColor &, bool restore)
virtual class FSvgRenderer * setUpConnectors (class ModelPart *, ViewLayer::ViewID)
QPainterPath shapeAux (double width) const
void updateCursor (Qt::KeyboardModifiers)
ViewLayer::ViewID useViewIDForPixmap (ViewLayer::ViewID, bool swappingEnabled)
Protected Member Functions inherited from ItemBase
virtual QStringList collectValues (const QString &family, const QString &prop, QString &value)
void createShape (LayerAttributes &layerAttributes)
QPixmap * getPixmap (ViewLayer::ViewID, bool swappingEnabled, QSize size)
QVariant itemChange (QGraphicsItem::GraphicsItemChange change, const QVariant &value)
virtual bool makeLocalModifications (QByteArray &svg, const QString &filename)
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
virtual void paintHover (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget, const QPainterPath &shape)
virtual void paintSelected (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
void saveLocAndTransform (QXmlStreamWriter &streamWriter)
virtual void setDefaultTooltip ()
void setInstanceTitleAux (const QString &title, bool initial)
void setInstanceTitleTooltip (const QString &text)
void updateHidden ()
Protected Attributes
QLineF m_cachedLine
QLineF m_cachedOriginalLine
bool m_clipEnds
QGraphicsSceneMouseEvent * m_justFilteredEvent
QPointer< ConnectorItem > m_trackHoverItem
QPointer< ConnectorItem > m_trackHoverLastItem
QPointer< Wire > m_trackHoverLastWireItem
Protected Attributes inherited from Wire
bool m_banded
QPen m_bendpoint2Pen
double m_bendpoint2Width
QPen m_bendpointPen
double m_bendpointWidth
class Bezier * m_bezier
bool m_canChainMultiple
bool m_canHaveCurve
bool m_colorByLength
QString m_colorName
QPointer< class ConnectorItem > m_connector0
QPointer< class ConnectorItem > m_connector1
QPointer< class ConnectorItem > m_connectorHover
bool m_displayBendpointCursor
bool m_drag0
bool m_dragCurve
bool m_dragEnd
double m_hoverStrokeWidth
bool m_ignoreSelectionChange
QLineF m_line
bool m_markedDeleted
bool m_negativeOffsetRect
double m_opacity
QRectF m_originalConnectorRect
QPen m_pen
QBrush m_shadowBrush
QPen m_shadowPen
QPointF m_wireDragOrigin
Protected Attributes inherited from ItemBase
bool m_acceptsMousePressLegEvent = true
QList< ConnectorItem * > m_cachedConnectorItems
bool m_canFlipHorizontal = false
bool m_canFlipVertical = false
int m_connectorHoverCount = 0
int m_connectorHoverCount2 = 0
bool m_everVisible = true
QString m_filename
FSvgRenderer * m_fsvgRenderer = nullptr
bool m_hasRubberBandLeg = false
bool m_hidden = false
int m_hoverCount = 0
bool m_hoverEnterSpaceBarWasPressed = false
qint64 m_id = 0
bool m_inactive = false
bool m_inRotation = false
QMenu * m_itemMenu = nullptr
bool m_layerHidden = false
QPointer< ModelPart > m_modelPart
bool m_moveLock = false
QGraphicsSvgItem * m_moveLockItem = nullptr
QPointer< PartLabel > m_partLabel
QMap< QString, QString > m_propsMap
ConnectorItem * m_rightClickedConnector = nullptr
QPainterPath m_selectionShape
QSizeF m_size
bool m_spaceBarWasPressed = false
bool m_squashShape = false
bool m_sticky = false
QGraphicsSvgItem * m_stickyItem = nullptr
QHash< long, QPointer< ItemBase > > m_stickyList
QList< QPointer< ItemBase > > m_subparts
QPointer< ItemBase > m_superpart
bool m_swappable = true
ViewGeometry m_viewGeometry
ViewLayer::ViewID m_viewID
ViewLayer::ViewLayerID m_viewLayerID
ViewLayer::ViewLayerPlacement m_viewLayerPlacement
bool m_zUninitialized = true
Additional Inherited Members
Public Types inherited from ItemBase
enum PluralType { Singular, Plural, NotSure }
Public Slots inherited from ItemBase
void hidePartLabel ()
void partLabelChanged (const QString &newText)
void showInFolder ()
void showPartLabel (bool show, ViewLayer *)
virtual void swapEntry (const QString &text)
Signals inherited from Wire
void wireChangedCurveSignal (Wire *me, const Bezier *oldB, const Bezier *newB, bool triggerFirstTime)
void wireChangedSignal (Wire *me, const QLineF &oldLine, const QLineF &newLine, QPointF oldPos, QPointF newPos, ConnectorItem *from, ConnectorItem *to)
void wireJoinSignal (Wire *me, ConnectorItem *clickedConnectorItem)
void wireSplitSignal (Wire *me, QPointF newPos, QPointF oldPos, const QLineF &oldLine)
Static Public Member Functions inherited from Wire
static void cleanup ()
static void initNames ()
Static Public Member Functions inherited from ItemBase
static void cleanup ()
static QColor connectedColor ()
static ItemBase * extractTopLevelItemBase (QGraphicsItem *thing)
static qint64 getNextID ()
static qint64 getNextID (qint64 fromIndex)
static void initNames ()
static void renderOne (QDomDocument *, QImage *, const QRectF &renderRect)
static void setConnectedColor (QColor &)
static void setReferenceModel (ReferenceModel *)
static void setUnconnectedColor (QColor &)
static QColor standardConnectedColor ()
static QColor standardUnconnectedColor ()
static QString translatePropertyName (const QString &key)
static QColor unconnectedColor ()
static bool zLessThan (ItemBase *&p1, ItemBase *&p2)
Static Public Attributes inherited from Wire
static QStringList colorNames
static QHash< QString, QString > colorTrans
static double HALF_STANDARD_TRACE_WIDTH = 0.0
static QList< QColor > lengthColorTrans
static double STANDARD_TRACE_WIDTH = 0.0
static QVector< qreal > TheDash
static double THIN_TRACE_WIDTH = 0.0
static QList< int > widths
static QHash< int, QString > widthTrans
Static Public Attributes inherited from ItemBase
static const QColor ConnectorHoverColor
static const double ConnectorHoverOpacity = .40
static const QList< ItemBase * > EmptyList
static const QColor HoverColor
static const double HoverOpacity = .20
static const QString ITEMBASE_FONT_PREFIX = "<font size='2'>"
static const QString ITEMBASE_FONT_SUFFIX = "</font>"
static QString PartInstanceDefaultTitle
static QHash< QString, QString > TranslatedPropertyNames
Protected Slots inherited from Wire
void colorEntry (const QString &text)
void setBandedProp (bool)
Static Protected Member Functions inherited from ItemBase
static bool fixCopper1 (ModelPart *modelPart, const QString &filename, ViewLayer::ViewLayerID viewLayerID, ViewLayer::ViewLayerPlacement, QDomDocument &)
static bool getFlipDoc (ModelPart *modelPart, const QString &filename, ViewLayer::ViewLayerID viewLayerID, ViewLayer::ViewLayerPlacement, QDomDocument &, Qt::Orientations)
Static Protected Attributes inherited from ItemBase
static QBrush ChosenBrush
static QPen ChosenPen
static QBrush ConnectedBrush
static QPen ConnectedPen
static QBrush EqualPotentialBrush
static QPen EqualPotentialPen
static QBrush HoverBrush
static QPen HoverPen
static long nextID
static QBrush NormalBrush
static constexpr double NormalConnectorOpacity = 0.4
static QPen NormalPen
static QPointer< ReferenceModel > TheReferenceModel = nullptr
static QBrush UnconnectedBrush
static QPen UnconnectedPen
Constructor & Destructor Documentation
ClipableWire()
ClipableWire::ClipableWire (ModelPart * modelPart, ViewLayer::ViewID viewID, const ViewGeometry & viewGeometry, long id, QMenu * itemMenu, bool initLabel)
References m_cachedOriginalLine, m_clipEnds, m_justFilteredEvent, and m_trackHoverItem.
Member Function Documentation
calcClip()
void ClipableWire::calcClip (QPointF & p1, QPointF & p2, ConnectorItem * c1, ConnectorItem * c2) protected
References ConnectorItem::calcClipRadius(), findIntersection(), ConnectorItem::isEffectivelyCircular(), and GraphicsUtils::shortenLine().
dispatchHover()
void ClipableWire::dispatchHover (QPointF scenePos) protected
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToItemType(), dispatchHoverAux(), ItemBase::getRatsnest(), insideInnerCircle(), insideSpoke(), m_trackHoverItem, and ModelPart::Wire.
dispatchHoverAux()
void ClipableWire::dispatchHoverAux (bool inInner, Wire * inWire) protected
References Wire::hoverEnterConnectorItem(), m_trackHoverItem, m_trackHoverLastItem, and m_trackHoverLastWireItem.
filterMousePressConnectorEvent()
bool ClipableWire::filterMousePressConnectorEvent (ConnectorItem * connectorItem, QGraphicsSceneMouseEvent * event) virtual
Reimplemented from ItemBase.
References NonConnectorItem::attachedToItemType(), ConnectorItem::connectedToItems(), insideInnerCircle(), insideSpoke(), m_clipEnds, m_justFilteredEvent, ItemBase::m_viewID, ViewLayer::PCBView, and ModelPart::Wire.
findIntersection()
QPointF ClipableWire::findIntersection (ConnectorItem * connectorItem, const QPointF & p) protected
References connectorRectClipInset, and Wire::line().
getPaintLine()
const QLineF & ClipableWire::getPaintLine () virtual
Reimplemented from Wire.
References NonConnectorItem::attachedToItemType(), calcClip(), Wire::getPaintLine(), Wire::line(), m_cachedLine, m_cachedOriginalLine, m_clipEnds, Wire::m_connector0, Wire::m_connector1, Wire::m_dragEnd, and ModelPart::Wire.
hoverEnterConnectorItem()
void ClipableWire::hoverEnterConnectorItem (QGraphicsSceneHoverEvent * event, class ConnectorItem * item) virtual
Reimplemented from ItemBase.
References NonConnectorItem::attachedToItemType(), ConnectorItem::connectedToItems(), dispatchHover(), m_trackHoverItem, m_trackHoverLastItem, m_trackHoverLastWireItem, and ModelPart::Wire.
hoverLeaveConnectorItem()
void ClipableWire::hoverLeaveConnectorItem (QGraphicsSceneHoverEvent * event, class ConnectorItem * item) virtual
Reimplemented from ItemBase.
References dispatchHoverAux(), and m_trackHoverItem.
hoverMoveConnectorItem()
void ClipableWire::hoverMoveConnectorItem (QGraphicsSceneHoverEvent * event, class ConnectorItem * item) virtual
Reimplemented from ItemBase.
References dispatchHover(), ItemBase::hoverMoveConnectorItem(), and m_trackHoverItem.
insideInnerCircle()
bool ClipableWire::insideInnerCircle (ConnectorItem * connectorItem, QPointF localPos) protected
References NonConnectorItem::radius(), and NonConnectorItem::strokeWidth().
insideSpoke()
bool ClipableWire::insideSpoke (ClipableWire * wire, QPointF scenePos) protected
References CrossingsTest(), Wire::line(), Wire::width(), XCOORD, and YCOORD.
mousePressEvent()
void ClipableWire::mousePressEvent (QGraphicsSceneMouseEvent * event)
References m_justFilteredEvent, and Wire::mousePressEvent().
setClipEnds()
void ClipableWire::setClipEnds (bool clipEnds)
References m_clipEnds, and ItemBase::prepareGeometryChange().
Member Data Documentation
m_cachedLine
QLineF ClipableWire::m_cachedLine protected
m_cachedOriginalLine
QLineF ClipableWire::m_cachedOriginalLine protected
m_clipEnds
bool ClipableWire::m_clipEnds protected
m_justFilteredEvent
QGraphicsSceneMouseEvent* ClipableWire::m_justFilteredEvent protected
m_trackHoverItem
QPointer<ConnectorItem> ClipableWire::m_trackHoverItem protected
m_trackHoverLastItem
QPointer<ConnectorItem> ClipableWire::m_trackHoverLastItem protected
m_trackHoverLastWireItem
QPointer<Wire> ClipableWire::m_trackHoverLastWireItem protected
The documentation for this class was generated from the following files:
items/clipablewire.h
items/clipablewire.cpp