Fritzing: PartInfoWidget Class Reference
PartInfoWidget Class Reference
#include <partinfowidget.h>
Public Slots
void updateInfo (ModelPart *)
Public Member Functions
PartInfoWidget (QWidget *parent=0)
ModelPartShared * modelPartShared ()
Protected Attributes
QLineEdit * m_author
QDateEdit * m_date
QTextEdit * m_description
QLineEdit * m_label
AddRemoveListWidget * m_propertyList
AddRemoveListWidget * m_tagsList
QLineEdit * m_title
QLineEdit * m_version
Constructor & Destructor Documentation
PartInfoWidget()
PartInfoWidget::PartInfoWidget (QWidget * parent = 0)
References m_author, m_date, m_description, m_label, m_propertyList, m_tagsList, m_title, and m_version.
Member Function Documentation
modelPartShared()
ModelPartShared * PartInfoWidget::modelPartShared ()
References AddRemoveListWidget::getItemsText(), m_author, m_date, m_description, m_label, m_tagsList, m_title, m_version, ModelPartShared::setAuthor(), ModelPartShared::setDate(), ModelPartShared::setDescription(), ModelPartShared::setLabel(), ModelPartShared::setTags(), ModelPartShared::setTitle(), and ModelPartShared::setVersion().
updateInfo
void PartInfoWidget::updateInfo (ModelPart * modelPart) slot
References ModelPartShared::author(), ModelPartShared::date(), DebugDialog::debug(), ModelPartShared::description(), ModelPartShared::label(), m_author, m_date, m_description, m_label, m_tagsList, m_title, m_version, ModelPart::modelPartShared(), AddRemoveListWidget::setItemsText(), ModelPartShared::tags(), ModelPartShared::title(), and ModelPartShared::version().
Member Data Documentation
m_author
QLineEdit* PartInfoWidget::m_author protected
m_date
QDateEdit* PartInfoWidget::m_date protected
m_description
QTextEdit* PartInfoWidget::m_description protected
m_label
QLineEdit* PartInfoWidget::m_label protected
m_propertyList
AddRemoveListWidget* PartInfoWidget::m_propertyList protected
m_tagsList
AddRemoveListWidget* PartInfoWidget::m_tagsList protected
m_title
QLineEdit* PartInfoWidget::m_title protected
m_version
QLineEdit* PartInfoWidget::m_version protected
The documentation for this class was generated from the following files:
partseditor/obsolete/partinfowidget.h
partseditor/obsolete/partinfowidget.cpp