Fritzing: PaletteItem Class Reference
PaletteItem Class Reference
#include <paletteitem.h>
Signals
void pinLabelSwap (ItemBase *, const QString &moduleID)
Public Member Functions
PaletteItem (ModelPart *, ViewLayer::ViewID, const ViewGeometry &viewGeometry, long id, QMenu *itemMenu, bool doLabel)
~PaletteItem ()
void addLayerKin (class LayerKinPaletteItem *lkpi)
virtual bool changePinLabels (bool singleRow, bool sip)
void clearModelPart ()
bool collectExtraInfo (QWidget *parent, const QString &family, const QString &prop, const QString &value, bool swappingEnabled, QString &returnProp, QString &returnValue, QWidget *&returnWidget, bool &hide)
bool collectFemaleConnectees (QSet< ItemBase * > &items)
QStringList collectValues (const QString &family, const QString &prop, QString &value)
void collectWireConnectees (QSet< class Wire * > &wires)
void flipItem (Qt::Orientations orientation)
QStringList getPinLabels (bool &hasLocal)
const QList< class ItemBase * > & layerKin ()
virtual void loadLayerKin (const LayerHash &viewLayers, ViewLayer::ViewLayerPlacement)
bool mousePressEventK (PaletteItemBase *originalItem, QGraphicsSceneMouseEvent *)
void moveItem (ViewGeometry &viewGeometry)
void removeLayerKin ()
void renamePins (const QStringList &labels, bool singleRow)
bool renderImage (ModelPart *modelPart, ViewLayer::ViewID viewID, const LayerHash &viewLayers, ViewLayer::ViewLayerID, bool doConnectors, QString &error)
void resetConnector (ItemBase *itemBase, SvgIdLayer *svgIdLayer)
void resetConnectors ()
void resetConnectors (ItemBase *otherLayer, FSvgRenderer *otherLayerRenderer)
void resetID ()
void resetImage (class InfoGraphicsView *)
void resetKinImage (ItemBase *layerKin, InfoGraphicsView *infoGraphicsView)
void resetLayerKin (const QString &svg)
void retransform (const QTransform &)
void rotateItem (double degrees, bool includeRatsnest)
void setHidden (bool hidden)
void setInactive (bool inactivate)
void setInstanceTitle (const QString &, bool initial)
void setItemPos (QPointF &pos)
void setTransforms ()
QStringList sipOrDipOrLabels (bool &hasLayout, bool &sip)
void slamZ (double z)
bool swap (ModelPart *newModelPart, const LayerHash &layerHash, bool reinit, class SwapCommand *)
void syncKinMoved (QPointF offset, QPointF loc)
void transformItem2 (const QMatrix &)
QTransform untransform ()
Public Member Functions inherited from PaletteItemBase
PaletteItemBase (ModelPart *, ViewLayer::ViewID, const ViewGeometry &viewGeometry, long id, QMenu *itemMenu)
bool acceptsMousePressConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
void blockItemSelectedChange (bool selected)
QRectF boundingRect () const
QRectF boundingRectWithoutLegs () const
virtual bool canEditPart ()
bool collectExtraInfo (QWidget *parent, const QString &family, const QString &prop, const QString &value, bool swappingEnabled, QString &returnProp, QString &returnValue, QWidget *&returnWidget, bool &hide)
bool collectFemaleConnectees (QSet< ItemBase * > &items)
void collectWireConnectees (QSet< class Wire * > &wires)
void connectedMoved (ConnectorItem *from, ConnectorItem *to, QList< ConnectorItem * > &already)
void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
void cursorKeyEvent (Qt::KeyboardModifiers modifiers)
const QCursor * getCursor (Qt::KeyboardModifiers)
void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
void hoverMoveEvent (QGraphicsSceneHoverEvent *event)
QPainterPath hoverShape () const
bool itemMoved ()
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
virtual void mouseMoveEventK (PaletteItemBase *originalItem, QGraphicsSceneMouseEvent *event)
void mousePressConnectorEvent (class ConnectorItem *, QGraphicsSceneMouseEvent *)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
virtual void mouseReleaseEventK (PaletteItemBase *originalItem, QGraphicsSceneMouseEvent *event)
void moveItem (ViewGeometry &)
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
void paintHover (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
void paintSelected (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
QString retrieveSvg (ViewLayer::ViewLayerID, QHash< QString, QString > &svgHash, bool blackOnly, double dpi, double &factor)
void saveGeometry ()
virtual void saveInstanceLocation (QXmlStreamWriter &)
void setProp (const QString &prop, const QString &value)
virtual bool setUpImage (ModelPart *modelPart, const LayerHash &viewLayers, LayerAttributes &)
QPainterPath shape () const
QPointF syncMoved ()
bool syncSelected ()
Public Member Functions inherited from ItemBase
ItemBase (ModelPart *, ViewLayer::ViewID, const ViewGeometry &, long id, QMenu *itemMenu)
virtual ~ItemBase ()
virtual bool acceptsMouseDoubleClickConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual bool acceptsMouseMoveConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual bool acceptsMousePressLegEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual bool acceptsMouseReleaseConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual void addedToScene (bool temporary)
virtual void addSticky (ItemBase *, bool stickem)
void addSubpart (ItemBase *)
virtual bool alreadySticking (ItemBase *itemBase)
ConnectorItem * anyConnectorItem ()
QRectF boundingRect () const
virtual void busConnectorItems (Bus *bus, ConnectorItem *, QList< ConnectorItem * > &items)
QList< Bus * > buses ()
const QList< ConnectorItem * > & cachedConnectorItems ()
const QList< ConnectorItem * > & cachedConnectorItemsConst () const
virtual void calcRotation (QTransform &rotation, QPointF center, ViewGeometry &)
bool canFlip (Qt::Orientations)
bool canFlipHorizontal ()
bool canFlipVertical ()
virtual void clearConnectorHover ()
void clearConnectorItemCache ()
void clearPartLabel ()
void collectConnectors (ConnectorPairHash &connectorHash, SkipCheckFunction)
void collectPropsMap (QString &family, QMap< QString, QString > &)
virtual void collectWireConnectees (QSet< Wire * > &wires)
virtual void connectionChange (ConnectorItem *onMe, ConnectorItem *onIt, bool connect)
virtual bool connectionIsAllowed (ConnectorItem *)
virtual void connectorHover (ConnectorItem *, ItemBase *, bool hovering)
const QString & constTitle () const
void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
void debugInfo (const QString &msg) const
void debugInfo2 (const QString &msg) const
virtual void doneLoading ()
void doRotateFlipPartLabel (double degrees, Qt::Orientations)
void ensureUniqueTitle (const QString &title, bool force)
QString family ()
const QString & filename ()
virtual bool filterMousePressConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
ConnectorItem * findConnectorItemWithSharedID (const QString &connectorID, ViewLayer::ViewLayerPlacement)
ConnectorItem * findConnectorItemWithSharedID (const QString &connectorID)
ItemBase * findSubpart (const QString &connectorID, ViewLayer::ViewLayerPlacement)
FSvgRenderer * fsvgRenderer () const
virtual void getConnectedColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
virtual void getEqualPotentialColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
virtual void getHoverColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
virtual QString getInspectorTitle ()
virtual void getNormalColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
QPixmap * getPixmap (QSize size)
void getPixmaps (QPixmap *&, QPixmap *&, QPixmap *&, bool swappingEnabled, QSize)
virtual QString getProperty (const QString &key)
bool getRatsnest ()
virtual void getUnconnectedColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
ViewGeometry & getViewGeometry ()
bool hasConnections ()
bool hasConnectors ()
virtual bool hasCustomSVG ()
bool hasNonConnectors ()
virtual bool hasPartLabel ()
virtual bool hasPartNumberProperty ()
bool hasRubberBandLeg () const
constexpr bool hidden () const noexcept
virtual void hoverEnterConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
void hoverEnterConnectorItem ()
void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
virtual void hoverLeaveConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
void hoverLeaveConnectorItem ()
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
virtual void hoverMoveConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
virtual void hoverUpdate ()
constexpr qint64 id () const noexcept
constexpr bool inactive () const noexcept
bool inHover ()
void initLayerAttributes (LayerAttributes &layerAttributes, ViewLayer::ViewID, ViewLayer::ViewLayerID, ViewLayer::ViewLayerPlacement, bool doConnectors, bool doCreateShape)
virtual bool inRotation ()
const QString & instanceTitle () const
virtual bool isBaseSticky ()
bool isEverVisible ()
bool isLocalSticky ()
bool isObsolete ()
bool isPartLabelVisible ()
virtual PluralType isPlural ()
virtual bool isSticky ()
virtual bool isSwappable ()
int itemType () const
void killRubberBandLeg ()
QString label ()
constexpr bool layerHidden () const noexcept
virtual ItemBase * layerKinChief ()
QString makePartLabelSvg (bool blackOnly, double dpi, double printerScale)
ModelPart * modelPart ()
ModelPartShared * modelPartShared ()
const QString & moduleID ()
virtual void mouseDoubleClickConnectorEvent (ConnectorItem *)
virtual void mouseMoveConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
void mousePressEvent (QGraphicsSceneMouseEvent *event)
virtual void mouseReleaseConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
bool moveLock ()
void movePartLabel (QPointF newPos, QPointF newOffset)
virtual ConnectorItem * newConnectorItem (Connector *connector)
virtual ConnectorItem * newConnectorItem (ItemBase *layerkin, Connector *connector)
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
PartLabel * partLabel ()
void partLabelMoved (QPointF oldPos, QPointF oldOffset, QPointF newPos, QPointF newOffset)
QRectF partLabelSceneBoundingRect ()
QPointF partLabelScenePos ()
void partLabelSetHidden (bool hide)
ViewLayer::ViewLayerID partLabelViewLayerID ()
void prepareGeometryChange ()
virtual QHash< QString, QString > prepareProps (ModelPart *, bool wantDebug, QStringList &keys)
QString prop (const QString &p)
bool reloadRenderer (const QString &svg, bool fastload)
void removeTooltip ()
bool resetRenderer (const QString &svg)
bool resetRenderer (const QString &svg, QString &newSvg)
void resetValues (const QString &family, const QString &prop)
void restorePartLabel (QDomElement &labelGeometry, ViewLayer::ViewLayerID)
ConnectorItem * rightClickedConnector ()
void rotateFlipPartLabel (double degrees, Qt::Orientations)
virtual bool rotation45Allowed ()
virtual bool rotationAllowed ()
virtual void saveInstance (QXmlStreamWriter &)
bool sceneEvent (QEvent *event)
const QPainterPath & selectionShape ()
virtual void setAcceptsMousePressLegEvent (bool)
void setCanFlipHorizontal (bool)
void setCanFlipVertical (bool)
virtual void setDropOffset (QPointF offset)
void setEverVisible (bool)
void setFilename (const QString &)
virtual void setInRotation (bool)
virtual void setInspectorTitle (const QString &oldText, const QString &newText)
void setItemIsSelectable (bool selectable)
virtual void setLayerHidden (bool hidden)
void setLocalSticky (bool)
void setModelPart (ModelPart *)
virtual void setMoveLock (bool)
void setSharedRendererEx (FSvgRenderer *)
void setSquashShape (bool)
virtual void setSticky (bool)
void setSuperpart (ItemBase *)
virtual void setSwappable (bool)
void setTooltip ()
virtual void setTransform2 (const QTransform &)
FSvgRenderer * setUpImage (ModelPart *modelPart, LayerAttributes &)
void setViewLayerID (ViewLayer::ViewLayerID, const LayerHash &viewLayers)
void setViewLayerID (const QString &layerName, const LayerHash &viewLayers)
void setViewLayerPlacement (ViewLayer::ViewLayerPlacement)
void showConnectors (const QStringList &)
constexpr QSizeF size () const noexcept
const QString & spice () const
const QString & spiceModel () const
virtual ItemBase * stickingTo ()
virtual bool stickyEnabled ()
virtual QList< QPointer< ItemBase > > stickyList ()
const QList< QPointer< ItemBase > > & subparts ()
ItemBase * superpart ()
virtual const QString & title ()
bool topLevel ()
virtual void transformItem (const QTransform &, bool includeRatsnest)
void updateConnections (ConnectorItem *, bool includeRatsnest, QList< ConnectorItem * > &already)
void updateConnectionsAux (bool includeRatsnest, QList< ConnectorItem * > &already)
void updateConnectors ()
void updatePartLabelInstanceTitle ()
virtual void updateTooltip ()
ViewLayer::ViewID viewID ()
QString & viewIDName ()
ViewLayer::ViewLayerID viewLayerID () const
ViewLayer::ViewLayerPlacement viewLayerPlacement () const
ViewGeometry::WireFlags wireFlags () const
virtual void writeGeometry (QXmlStreamWriter &)
virtual void writeXml (QXmlStreamWriter &)
double z ()
Static Public Member Functions
static bool changeDiameter (HoleSettings &holeSettings, QObject *sender)
static bool changeThickness (HoleSettings &holeSettings, QObject *sender)
static QString changeUnits (HoleSettings &)
static QWidget * createHoleSettings (QWidget *parent, HoleSettings &, bool swappingEnabled, const QString &currentHoleSize, bool advanced)
static QString genFZP (const QString &moduleid, const QString &templateName, int minPins, int maxPins, int steps, bool smd)
static void initHoleSettings (HoleSettings &holeSettings, HoleClassThing *)
static bool setHoleSize (QString &holeSize, bool force, HoleSettings &holeSettings)
static void updateEditTexts (HoleSettings &)
static void updateSizes (HoleSettings &)
static void updateValidators (HoleSettings &)
Static Public Member Functions inherited from ItemBase
static void cleanup ()
static QColor connectedColor ()
static ItemBase * extractTopLevelItemBase (QGraphicsItem *thing)
static qint64 getNextID ()
static qint64 getNextID (qint64 fromIndex)
static void initNames ()
static void renderOne (QDomDocument *, QImage *, const QRectF &renderRect)
static void setConnectedColor (QColor &)
static void setReferenceModel (ReferenceModel *)
static void setUnconnectedColor (QColor &)
static QColor standardConnectedColor ()
static QColor standardUnconnectedColor ()
static QString translatePropertyName (const QString &key)
static QColor unconnectedColor ()
static bool zLessThan (ItemBase *&p1, ItemBase *&p2)
Static Public Attributes
static const QString HoleSizePrefix
Static Public Attributes inherited from ItemBase
static const QColor ConnectorHoverColor
static const double ConnectorHoverOpacity = .40
static const QList< ItemBase * > EmptyList
static const QColor HoverColor
static const double HoverOpacity = .20
static const QString ITEMBASE_FONT_PREFIX = "<font size='2'>"
static const QString ITEMBASE_FONT_SUFFIX = "</font>"
static QString PartInstanceDefaultTitle
static QHash< QString, QString > TranslatedPropertyNames
Protected Slots
void changeDiameter ()
virtual void changeHoleSize (const QString &)
void changeThickness ()
virtual void changeUnits (bool)
void openPinLabelDialog ()
Protected Slots inherited from PaletteItemBase
void partPropertyEntry ()
Protected Member Functions
QString appendHoleSize (const QString &moduleID, const QString &holeSize, const QString &ringThickness)
bool collectHoleSizeInfo (const QString &defaultHoleSizeValue, QWidget *parent, bool swappingEnabled, QString &returnProp, QString &returnValue, QWidget *&returnWidget)
void figureHover ()
void generateSwap (const QString &text, GenModuleID, GenFzp, GenSvg makeBreadboardSvg, GenSvg makeSchematicSvg, GenSvg makePcbSvg)
QString hackFzpHoleSize (const QString &moduleID, const QString &pcbFilename, const QString &holeSize)
QString hackSvgHoleSize (const QString &holeDiameter, const QString &ringThickness)
bool isSingleRow (const QList< ConnectorItem * > &connectorItems)
QVariant itemChange (GraphicsItemChange change, const QVariant &value)
bool makeLocalModifications (QByteArray &svg, const QString &filename)
void makeOneKin (qint64 &id, ViewLayer::ViewLayerID, ViewLayer::ViewLayerPlacement, ViewGeometry &, const LayerHash &)
void mousePressEvent (QGraphicsSceneMouseEvent *event)
void setUpHoleSizes (const QString &type, HoleClassThing &)
void setUpHoleSizesAux (HoleClassThing &, const QString &type)
QList< Connector * > sortConnectors ()
void syncKinSelection (bool selected, PaletteItemBase *originator)
void updateConnections (bool includeRatsnest, QList< ConnectorItem * > &already)
Protected Member Functions inherited from PaletteItemBase
virtual void cacheLoaded (const LayerAttributes &)
virtual bool canFindConnectorsUnder ()
void checkFreeRotation (Qt::KeyboardModifiers modifiers, QPointF scenePos)
void findConnectorsUnder ()
virtual bool freeRotationAllowed (Qt::KeyboardModifiers modifiers)
bool freeRotationAllowed ()
bool inRotationLocation (QPointF scenePos, Qt::KeyboardModifiers modifiers, QPointF &returnPoint)
virtual LayerKinPaletteItem * newLayerKinPaletteItem (PaletteItemBase *chief, ModelPart *, const ViewGeometry &, long id, QMenu *itemMenu, const LayerHash &, LayerAttributes &)
virtual void setInitialTransform (const QTransform &)
void setUpConnectors (FSvgRenderer *, bool ignoreTerminalPoints)
Protected Member Functions inherited from ItemBase
void createShape (LayerAttributes &layerAttributes)
QPixmap * getPixmap (ViewLayer::ViewID, bool swappingEnabled, QSize size)
QVariant itemChange (QGraphicsItem::GraphicsItemChange change, const QVariant &value)
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
virtual void paintBody (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
virtual void paintHover (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget, const QPainterPath &shape)
void saveLocAndTransform (QXmlStreamWriter &streamWriter)
virtual void setDefaultTooltip ()
void setInstanceTitleAux (const QString &title, bool initial)
void setInstanceTitleTooltip (const QString &text)
void updateHidden ()
virtual ViewLayer::ViewID useViewIDForPixmap (ViewLayer::ViewID, bool swappingEnabled)
Static Protected Member Functions
static QStringList getSizes (QString &holeSize, HoleSettings &)
static QString hackFzpHoleSize (QDomDocument &document, const QString &newModuleID, const QString &pcbFilename, const QString &newSize)
static QString hackFzpHoleSize (const QString &fzp, const QString &moduleid, int hsix)
static QString hackSvgHoleSize (QDomDocument &domDocument, const QString &holeDiameter, const QString &ringThickness)
static QString hackSvgHoleSizeAux (const QString &svg, const QString &expectedFileName)
Static Protected Member Functions inherited from PaletteItemBase
static QString normalizeSvg (QString &svg, ViewLayer::ViewLayerID viewLayerID, bool blackOnly, double dpi, double &factor)
Static Protected Member Functions inherited from ItemBase
static bool fixCopper1 (ModelPart *modelPart, const QString &filename, ViewLayer::ViewLayerID viewLayerID, ViewLayer::ViewLayerPlacement, QDomDocument &)
static bool getFlipDoc (ModelPart *modelPart, const QString &filename, ViewLayer::ViewLayerID viewLayerID, ViewLayer::ViewLayerPlacement, QDomDocument &, Qt::Orientations)
Protected Attributes
int m_flipCount
HoleSettings m_holeSettings
QList< class ItemBase * > m_layerKin
Protected Attributes inherited from PaletteItemBase
bool m_blockItemSelectedChange
bool m_blockItemSelectedValue
QPointF m_offset
bool m_svg
QPointF m_syncMoved
bool m_syncSelected
Protected Attributes inherited from ItemBase
bool m_acceptsMousePressLegEvent = true
QList< ConnectorItem * > m_cachedConnectorItems
bool m_canFlipHorizontal = false
bool m_canFlipVertical = false
int m_connectorHoverCount = 0
int m_connectorHoverCount2 = 0
bool m_everVisible = true
QString m_filename
FSvgRenderer * m_fsvgRenderer = nullptr
bool m_hasRubberBandLeg = false
bool m_hidden = false
int m_hoverCount = 0
bool m_hoverEnterSpaceBarWasPressed = false
qint64 m_id = 0
bool m_inactive = false
bool m_inRotation = false
QMenu * m_itemMenu = nullptr
bool m_layerHidden = false
QPointer< ModelPart > m_modelPart
bool m_moveLock = false
QGraphicsSvgItem * m_moveLockItem = nullptr
QPointer< PartLabel > m_partLabel
QMap< QString, QString > m_propsMap
ConnectorItem * m_rightClickedConnector = nullptr
QPainterPath m_selectionShape
QSizeF m_size
bool m_spaceBarWasPressed = false
bool m_squashShape = false
bool m_sticky = false
QGraphicsSvgItem * m_stickyItem = nullptr
QHash< long, QPointer< ItemBase > > m_stickyList
QList< QPointer< ItemBase > > m_subparts
QPointer< ItemBase > m_superpart
bool m_swappable = true
ViewGeometry m_viewGeometry
ViewLayer::ViewID m_viewID
ViewLayer::ViewLayerID m_viewLayerID
ViewLayer::ViewLayerPlacement m_viewLayerPlacement
bool m_zUninitialized = true
Additional Inherited Members
Public Types inherited from ItemBase
enum PluralType { Singular, Plural, NotSure }
Public Slots inherited from ItemBase
void hidePartLabel ()
void partLabelChanged (const QString &newText)
void showInFolder ()
void showPartLabel (bool show, ViewLayer *)
virtual void swapEntry (const QString &text)
Static Protected Attributes inherited from ItemBase
static QBrush ChosenBrush
static QPen ChosenPen
static QBrush ConnectedBrush
static QPen ConnectedPen
static QBrush EqualPotentialBrush
static QPen EqualPotentialPen
static QBrush HoverBrush
static QPen HoverPen
static long nextID
static QBrush NormalBrush
static constexpr double NormalConnectorOpacity = 0.4
static QPen NormalPen
static QPointer< ReferenceModel > TheReferenceModel = nullptr
static QBrush UnconnectedBrush
static QPen UnconnectedPen
Constructor & Destructor Documentation
PaletteItem()
PaletteItem::PaletteItem (ModelPart * modelPart, ViewLayer::ViewID viewID, const ViewGeometry & viewGeometry, long id, QMenu * itemMenu, bool doLabel)
References m_flipCount, and ItemBase::m_partLabel.
~PaletteItem()
PaletteItem::~PaletteItem ()
References ItemBase::m_partLabel.
Member Function Documentation
addLayerKin()
void PaletteItem::addLayerKin (class LayerKinPaletteItem * lkpi)
References m_layerKin.
appendHoleSize()
QString PaletteItem::appendHoleSize (const QString & moduleID, const QString & holeSize, const QString & ringThickness) protected
References HoleSizePrefix.
changeDiameter() [1/2]
bool PaletteItem::changeDiameter (HoleSettings & holeSettings, QObject * sender) static
References HoleSettings::holeDiameter.
changeDiameter [2/2]
void PaletteItem::changeDiameter () protected slot
References changeHoleSize(), HoleSettings::currentUnits(), m_holeSettings, and HoleSettings::ringThickness.
changeHoleSize
void PaletteItem::changeHoleSize (const QString & newSize) protected virtual slot
References appendHoleSize(), changeHoleSize(), ItemBase::family(), PartFactory::fzpPath(), InfoGraphicsView::getInfoGraphicsView(), getSizes(), hackFzpHoleSize(), hackSvgHoleSize(), m_holeSettings, ItemBase::m_propsMap, ItemBase::m_viewID, ItemBase::modelPart(), ItemBase::moduleID(), PartFactory::partPath(), ViewLayer::PCBView, InfoGraphicsView::swap(), and TextUtils::writeUtf8().
changePinLabels()
bool PaletteItem::changePinLabels (bool singleRow, bool sip) virtual
Reimplemented in MysteryPart, and Dip.
References ItemBase::m_viewID, and ViewLayer::SchematicView.
changeThickness() [1/2]
bool PaletteItem::changeThickness (HoleSettings & holeSettings, QObject * sender) static
References HoleSettings::ringThickness.
changeThickness [2/2]
void PaletteItem::changeThickness () protected slot
References changeHoleSize(), HoleSettings::currentUnits(), HoleSettings::holeDiameter, and m_holeSettings.
changeUnits() [1/2]
QString PaletteItem::changeUnits (HoleSettings & holeSettings) static
References TextUtils::convertToInches(), HoleSettings::currentUnits(), HoleSettings::holeDiameter, HoleSettings::ringThickness, updateEditTexts(), updateSizes(), and updateValidators().
changeUnits [2/2]
void PaletteItem::changeUnits (bool) protected virtual slot
References changeHoleSize(), changeUnits(), and m_holeSettings.
clearModelPart()
void PaletteItem::clearModelPart () virtual
Reimplemented from ItemBase.
References ItemBase::clearModelPart(), m_layerKin, and ItemBase::setModelPart().
collectExtraInfo()
bool PaletteItem::collectExtraInfo (QWidget * parent, const QString & family, const QString & prop, const QString & value, bool swappingEnabled, QString & returnProp, QString & returnValue, QWidget *& returnWidget, bool & hide) virtual
Reimplemented from ItemBase.
Reimplemented in ResizableBoard, Stripboard, SymbolPaletteItem, Board, SchematicFrame, PinHeader, Ruler, Perfboard, Resistor, and ScrewTerminal.
References InfoGraphicsView::boardLayers(), PaletteItemBase::collectExtraInfo(), ItemBase::family(), ModelPart::flippedSMD(), InfoGraphicsView::getInfoGraphicsView(), ItemBase::modelPart(), openPinLabelDialog(), and ItemBase::prop().
collectFemaleConnectees()
bool PaletteItem::collectFemaleConnectees (QSet< ItemBase * > & items) virtual
Reimplemented from ItemBase.
References PaletteItemBase::collectFemaleConnectees(), ItemBase::collectFemaleConnectees(), and m_layerKin.
collectHoleSizeInfo()
bool PaletteItem::collectHoleSizeInfo (const QString & defaultHoleSizeValue, QWidget * parent, bool swappingEnabled, QString & returnProp, QString & returnValue, QWidget *& returnWidget) protected
References changeDiameter(), changeHoleSize(), changeThickness(), changeUnits(), createHoleSettings(), HoleSettings::diameterEdit, HoleSettings::inRadioButton, m_holeSettings, ItemBase::m_modelPart, HoleSettings::mmRadioButton, HoleSettings::sizesComboBox, and HoleSettings::thicknessEdit.
collectValues()
QStringList PaletteItem::collectValues (const QString & family, const QString & prop, QString & value) virtual
Reimplemented from ItemBase.
Reimplemented in ResizableBoard, Stripboard, Resistor, PinHeader, Board, and ScrewTerminal.
References ItemBase::collectValues(), ViewLayer::Copper0, ItemBase::family(), ModelPart::flippedSMD(), ItemBase::itemType(), ItemBase::modelPart(), ViewLayer::NewBottom, ModelPart::Part, ViewLayer::PCBView, ItemBase::prop(), ItemBase::TranslatedPropertyNames, ModelPart::viewItem(), ItemBase::viewLayerID(), and ItemBase::viewLayerPlacement().
collectWireConnectees()
void PaletteItem::collectWireConnectees (QSet< class Wire * > & wires)
References PaletteItemBase::collectWireConnectees(), and m_layerKin.
createHoleSettings()
QWidget * PaletteItem::createHoleSettings (QWidget * parent, HoleSettings & holeSettings, bool swappingEnabled, const QString & currentHoleSize, bool advanced) static
References HoleSettings::diameterEdit, HoleSettings::diameterValidator, HoleClassThing::holeSizeKeys, HoleSettings::holeThing, HoleSettings::inRadioButton, ItemBase::label(), HoleSettings::mmRadioButton, HoleSettings::sizesComboBox, HoleSettings::thicknessEdit, HoleSettings::thicknessValidator, updateEditTexts(), updateSizes(), and updateValidators().
figureHover()
void PaletteItem::figureHover () protected virtual
Reimplemented from ItemBase.
Reimplemented in ResizableBoard.
References ALLMOUSEBUTTONS, and m_layerKin.
flipItem()
void PaletteItem::flipItem (Qt::Orientations orientation) virtual
Reimplemented from ItemBase.
References ItemBase::flipItem(), and m_layerKin.
generateSwap()
void PaletteItem::generateSwap (const QString & text, GenModuleID genModuleID, GenFzp genFzp, GenSvg makeBreadboardSvg, GenSvg makeSchematicSvg, GenSvg makePcbSvg) protected
References PartFactory::fzpFileExists(), HoleSizePrefix, ItemBase::m_propsMap, ItemBase::moduleID(), FamilyPropertyComboBox::prop(), PartFactory::svgFileExists(), and TextUtils::writeUtf8().
genFZP()
QString PaletteItem::genFZP (const QString & moduleid, const QString & templateName, int minPins, int maxPins, int steps, bool smd) static
getPinLabels()
QStringList PaletteItem::getPinLabels (bool & hasLocal)
References Connector::connectorLocalName(), Connector::connectorSharedName(), and sortConnectors().
getSizes()
QStringList PaletteItem::getSizes (QString & holeSize, HoleSettings & holeSettings) static protected
References HoleClassThing::holeSizes, and HoleSettings::holeThing.
hackFzpHoleSize() [1/3]
QString PaletteItem::hackFzpHoleSize (const QString & moduleID, const QString & pcbFilename, const QString & holeSize) protected
References DebugDialog::debug(), and ItemBase::modelPart().
hackFzpHoleSize() [2/3]
QString PaletteItem::hackFzpHoleSize (QDomDocument & document, const QString & newModuleID, const QString & pcbFilename, const QString & newSize) static protected
References layers(), ItemBase::prop(), TextUtils::removeXMLEntities(), and TextUtils::replaceChildText().
hackFzpHoleSize() [3/3]
QString PaletteItem::hackFzpHoleSize (const QString & fzp, const QString & moduleid, int hsix) static protected
References DebugDialog::debug(), and hackFzpHoleSize().
hackSvgHoleSize() [1/2]
QString PaletteItem::hackSvgHoleSize (const QString & holeDiameter, const QString & ringThickness) protected
References DebugDialog::debug(), and ItemBase::filename().
hackSvgHoleSize() [2/2]
QString PaletteItem::hackSvgHoleSize (QDomDocument & domDocument, const QString & holeDiameter, const QString & ringThickness) static protected
References ConnectorFinder(), TextUtils::convertToInches(), and TextUtils::removeXMLEntities().
hackSvgHoleSizeAux()
QString PaletteItem::hackSvgHoleSizeAux (const QString & svg, const QString & expectedFileName) static protected
References hackSvgHoleSize(), and HoleSizePrefix.
initHoleSettings()
void PaletteItem::initHoleSettings (HoleSettings & holeSettings, HoleClassThing * holeThing) static
References HoleSettings::diameterEdit, HoleSettings::diameterValidator, HoleSettings::holeThing, HoleSettings::inRadioButton, HoleSettings::mmRadioButton, HoleSettings::sizesComboBox, HoleSettings::thicknessEdit, and HoleSettings::thicknessValidator.
isSingleRow()
bool PaletteItem::isSingleRow (const QList< ConnectorItem * > & connectorItems) protected
References qMax().
itemChange()
QVariant PaletteItem::itemChange (GraphicsItemChange change, const QVariant & value) protected
References ItemBase::itemChange(), PaletteItemBase::m_blockItemSelectedChange, PaletteItemBase::m_blockItemSelectedValue, m_layerKin, PaletteItemBase::m_offset, ItemBase::m_partLabel, syncKinMoved(), and syncKinSelection().
layerKin()
const QList< class ItemBase * > & PaletteItem::layerKin () virtual
Reimplemented from ItemBase.
References m_layerKin.
loadLayerKin()
void PaletteItem::loadLayerKin (const LayerHash & viewLayers, ViewLayer::ViewLayerPlacement viewLayerPlacement) virtual
Reimplemented in ResizableBoard, JumperItem, and GroundPlane.
References ViewLayer::bottomLayers(), ModelPart::CopperFill, ItemBase::m_id, ItemBase::m_modelPart, ItemBase::m_viewGeometry, ItemBase::m_viewID, ItemBase::m_viewLayerID, makeOneKin(), ItemBase::modelPartShared(), ViewLayer::NewTop, ModelPart::Part, ViewGeometry::setZ(), ViewLayer::silkLayers(), ViewLayer::topLayers(), ItemBase::viewLayerID(), and ItemBase::viewLayerPlacement().
makeLocalModifications()
bool PaletteItem::makeLocalModifications (QByteArray & svg, const QString & filename) protected virtual
Reimplemented from ItemBase.
References ItemBase::itemType(), ItemBase::m_viewID, PartFactory::makeSchematicSipOrDipOr(), ItemBase::modelPart(), ModelPart::Part, ViewLayer::PCBView, ModelPart::properties(), qMax(), TextUtils::replaceTextElement(), ViewLayer::SchematicView, sipOrDipOrLabels(), and ItemBase::title().
makeOneKin()
void PaletteItem::makeOneKin (qint64 & id, ViewLayer::ViewLayerID viewLayerID, ViewLayer::ViewLayerPlacement viewLayerPlacement, ViewGeometry & viewGeometry, const LayerHash & viewLayers) protected
References addLayerKin(), DebugDialog::debug(), ItemBase::initLayerAttributes(), ItemBase::m_itemMenu, ItemBase::m_modelPart, ItemBase::m_viewID, PaletteItemBase::newLayerKinPaletteItem(), LayerKinPaletteItem::ok(), ItemBase::viewLayerID(), and ItemBase::viewLayerPlacement().
mousePressEvent()
void PaletteItem::mousePressEvent (QGraphicsSceneMouseEvent * event) protected
References InfoGraphicsView::getInfoGraphicsView(), mousePressEventK(), and InfoGraphicsView::spaceBarIsPressed().
mousePressEventK()
bool PaletteItem::mousePressEventK (PaletteItemBase * originalItem, QGraphicsSceneMouseEvent * event) virtual
Reimplemented from PaletteItemBase.
References PaletteItemBase::mousePressEventK().
moveItem()
void PaletteItem::moveItem (ViewGeometry & viewGeometry) virtual
Implements ItemBase.
References m_layerKin, and PaletteItemBase::moveItem().
openPinLabelDialog
void PaletteItem::openPinLabelDialog () protected slot
References ItemBase::cachedConnectorItems(), Connector::connectorSharedName(), InfoGraphicsView::getInfoGraphicsView(), ItemBase::instanceTitle(), isSingleRow(), PinLabelDialog::labels(), ModelPart::localProp(), ItemBase::modelPart(), InfoGraphicsView::renamePins(), and sortConnectors().
pinLabelSwap
void PaletteItem::pinLabelSwap (ItemBase * , const QString & moduleID) signal
removeLayerKin()
void PaletteItem::removeLayerKin () virtual
Reimplemented from ItemBase.
References m_layerKin.
renamePins()
void PaletteItem::renamePins (const QStringList & labels, bool singleRow)
References InfoGraphicsView::changePinLabels(), InfoGraphicsView::getInfoGraphicsView(), Connector::setConnectorLocalName(), and sortConnectors().
renderImage()
bool PaletteItem::renderImage (ModelPart * modelPart, ViewLayer::ViewID viewID, const LayerHash & viewLayers, ViewLayer::ViewLayerID viewLayerID, bool doConnectors, QString & error)
References LayerAttributes::error, ItemBase::initLayerAttributes(), PaletteItemBase::m_syncMoved, ItemBase::modelPart(), PaletteItemBase::setUpImage(), ItemBase::viewID(), ItemBase::viewLayerID(), and ItemBase::viewLayerPlacement().
resetConnector()
void PaletteItem::resetConnector (ItemBase * itemBase, SvgIdLayer * svgIdLayer)
References ConnectorItem::attachedMoved(), ItemBase::cachedConnectorItems(), SvgIdLayer::m_path, SvgIdLayer::m_radius, SvgIdLayer::m_strokeWidth, SvgIdLayer::point(), SvgIdLayer::rect(), NonConnectorItem::setIsPath(), NonConnectorItem::setRadius(), ConnectorItem::setTerminalPoint(), and ItemBase::viewLayerPlacement().
resetConnectors() [1/2]
void PaletteItem::resetConnectors ()
References ItemBase::cachedConnectorItems(), ConnectorItem::connector(), FSvgRenderer::defaultSizeF(), ItemBase::fsvgRenderer(), Connector::fullPinInfo(), SvgIdLayer::m_svgId, ItemBase::m_viewID, ItemBase::m_viewLayerID, and ViewLayer::SchematicView.
resetConnectors() [2/2]
void PaletteItem::resetConnectors (ItemBase * otherLayer, FSvgRenderer * otherLayerRenderer)
References ItemBase::fsvgRenderer(), Connector::fullPinInfo(), ItemBase::m_modelPart, ItemBase::m_viewID, ItemBase::m_viewLayerID, resetConnector(), FSvgRenderer::setUpConnector(), Connector::unprocess(), ItemBase::viewLayerID(), and ItemBase::viewLayerPlacement().
resetID()
void PaletteItem::resetID () virtual
Reimplemented from ItemBase.
References m_layerKin, and ItemBase::resetID().
resetImage()
void PaletteItem::resetImage (class InfoGraphicsView * infoGraphicsView)
References ItemBase::initLayerAttributes(), layerKin(), m_layerKin, ItemBase::m_selectionShape, ItemBase::modelPart(), resetKinImage(), PaletteItemBase::setUpImage(), Connector::unprocess(), ItemBase::viewID(), ItemBase::viewLayerID(), ItemBase::viewLayerPlacement(), and InfoGraphicsView::viewLayers().
resetKinImage()
void PaletteItem::resetKinImage (ItemBase * layerKin, InfoGraphicsView * infoGraphicsView)
References ItemBase::initLayerAttributes(), layerKin(), ItemBase::modelPart(), Connector::unprocess(), and InfoGraphicsView::viewLayers().
resetLayerKin()
void PaletteItem::resetLayerKin (const QString & svg)
References SvgFileSplitter::hideText3(), layerKin(), ItemBase::resetRenderer(), ViewLayer::SchematicText, SvgFileSplitter::showText3(), and ItemBase::viewLayerID().
retransform()
void PaletteItem::retransform (const QTransform & chiefTransform)
References layerKin(), and ItemBase::transformItem().
rotateItem()
void PaletteItem::rotateItem (double degrees, bool includeRatsnest) virtual
Reimplemented from ItemBase.
References m_layerKin, and ItemBase::rotateItem().
setHidden()
void PaletteItem::setHidden (bool hidden) virtual
Reimplemented from ItemBase.
References figureHover(), and ItemBase::setHidden().
setHoleSize()
bool PaletteItem::setHoleSize (QString & holeSize, bool force, HoleSettings & holeSettings) static
References getSizes(), HoleSettings::holeDiameter, HoleSettings::ringThickness, updateEditTexts(), updateSizes(), and updateValidators().
setInactive()
void PaletteItem::setInactive (bool inactivate) virtual
Reimplemented from ItemBase.
References figureHover(), and ItemBase::setInactive().
setInstanceTitle()
void PaletteItem::setInstanceTitle (const QString & title, bool initial) virtual
Reimplemented from ItemBase.
References m_layerKin, ItemBase::setInstanceTitle(), and ItemBase::title().
setItemPos()
void PaletteItem::setItemPos (QPointF & pos) virtual
Reimplemented from ItemBase.
References m_layerKin, and ItemBase::setItemPos().
setTransforms()
void PaletteItem::setTransforms ()
References ItemBase::getViewGeometry(), m_layerKin, and ViewGeometry::transform().
setUpHoleSizes()
void PaletteItem::setUpHoleSizes (const QString & type, HoleClassThing & holeThing) protected
References HoleSettings::holeDiameter, HoleClassThing::holeSize, HoleClassThing::holeSizes, initHoleSettings(), ModelPart::localProp(), m_holeSettings, ItemBase::modelPart(), ModelPart::properties(), HoleClassThing::ringThickness, HoleSettings::ringThickness, ModelPart::setLocalProp(), and setUpHoleSizesAux().
setUpHoleSizesAux()
void PaletteItem::setUpHoleSizesAux (HoleClassThing & holeThing, const QString & type) protected
References TextUtils::convertToInches(), DebugDialog::debug(), HoleClassThing::holeDiameterRange, HoleClassThing::holeSize, HoleClassThing::holeSizeKeys, HoleClassThing::holeSizes, HoleClassThing::holeSizeValue, HoleClassThing::ringThickness, and HoleClassThing::ringThicknessRange.
sipOrDipOrLabels()
QStringList PaletteItem::sipOrDipOrLabels (bool & hasLayout, bool & sip)
References getPinLabels(), ItemBase::modelPart(), and ModelPart::properties().
slamZ()
void PaletteItem::slamZ (double z) virtual
Reimplemented from ItemBase.
References m_layerKin, ItemBase::slamZ(), and ItemBase::z().
sortConnectors()
QList< Connector * > PaletteItem::sortConnectors () protected
References byID(), ByIDParseSuccessful, and ItemBase::modelPart().
swap()
bool PaletteItem::swap (ModelPart * newModelPart, const LayerHash & layerHash, bool reinit, class SwapCommand *)
syncKinMoved()
void PaletteItem::syncKinMoved (QPointF offset, QPointF loc) virtual
Reimplemented from PaletteItemBase.
References m_layerKin.
syncKinSelection()
void PaletteItem::syncKinSelection (bool selected, PaletteItemBase * originator) protected virtual
Reimplemented from PaletteItemBase.
References PaletteItemBase::blockItemSelectedChange(), m_layerKin, and PaletteItemBase::syncKinSelection().
transformItem2()
void PaletteItem::transformItem2 (const QMatrix & matrix) virtual
Reimplemented from ItemBase.
References m_layerKin, and ItemBase::transformItem2().
untransform()
QTransform PaletteItem::untransform ()
References layerKin(), and ItemBase::transformItem().
updateConnections()
void PaletteItem::updateConnections (bool includeRatsnest, QList< ConnectorItem * > & already) protected virtual
Reimplemented from ItemBase.
References m_layerKin, and ItemBase::updateConnectionsAux().
updateEditTexts()
void PaletteItem::updateEditTexts (HoleSettings & holeSettings) static
References TextUtils::convertToInches(), HoleSettings::currentUnits(), HoleSettings::diameterEdit, HoleSettings::holeDiameter, HoleSettings::mmRadioButton, HoleSettings::ringThickness, and HoleSettings::thicknessEdit.
updateSizes()
void PaletteItem::updateSizes (HoleSettings & holeSettings) static
References TextUtils::convertToInches(), HoleSettings::holeDiameter, HoleClassThing::holeSizeKeys, HoleClassThing::holeSizes, HoleSettings::holeThing, HoleSettings::ringThickness, and HoleSettings::sizesComboBox.
updateValidators()
void PaletteItem::updateValidators (HoleSettings & holeSettings) static
References HoleSettings::currentUnits(), HoleSettings::diameterValidator, HoleClassThing::holeDiameterRange, HoleSettings::holeThing, HoleSettings::mmRadioButton, HoleClassThing::ringThicknessRange, and HoleSettings::thicknessValidator.
Member Data Documentation
HoleSizePrefix
const QString PaletteItem::HoleSizePrefix static
m_flipCount
int PaletteItem::m_flipCount protected
m_holeSettings
HoleSettings PaletteItem::m_holeSettings protected
m_layerKin
QList<class ItemBase *> PaletteItem::m_layerKin protected
The documentation for this class was generated from the following files:
items/paletteitem.h
items/paletteitem.cpp