Fritzing: Connector Class Reference
Connector Class Reference
#include <connector.h>
Public Types
enum ConnectorType {
Male, Female, Wire, Pad,
Unknown
}
Public Member Functions
Connector (class ConnectorShared *, class ModelPart *modelPart)
~Connector ()
void addPin (ViewLayer::ViewID, const QString &svgId, ViewLayer::ViewLayerID, const QString &terminalId, const QString &legId, bool hybrid)
void addViewItem (class ConnectorItem *)
class Bus * bus ()
const QString & busID ()
bool connectionIsAllowed (Connector *that)
ConnectorItem * connectorItem (ViewLayer::ViewID)
ConnectorItem * connectorItemByViewLayerID (ViewLayer::ViewID, ViewLayer::ViewLayerID)
int connectorItemCount ()
const QString & connectorLocalName ()
class ConnectorShared * connectorShared ()
const QString & connectorSharedDescription () const
class ErcData * connectorSharedErcData ()
const QString & connectorSharedID () const
const QString & connectorSharedName () const
const QString & connectorSharedReplacedby () const
Connector::ConnectorType connectorType () const
void connectTo (Connector *)
void disconnectFrom (Connector *)
class SvgIdLayer * fullPinInfo (ViewLayer::ViewID viewId, ViewLayer::ViewLayerID viewLayerID)
const QString & legID (ViewLayer::ViewID, ViewLayer::ViewLayerID)
long modelIndex ()
ModelPart * modelPart ()
void removeViewItem (class ConnectorItem *)
void saveAsPart (QXmlStreamWriter &writer)
void setBus (class Bus *)
void setConnectorLocalName (const QString &)
const QList< SvgIdLayer * > svgIdLayers () const
const QList< Connector * > & toConnectors ()
void unprocess (ViewLayer::ViewID viewID, ViewLayer::ViewLayerID viewLayerID)
QList< QPointer< class ConnectorItem > > viewItems ()
Static Public Member Functions
static const QString & connectorNameFromType (ConnectorType)
static ConnectorType connectorTypeFromName (const QString &name)
static void initNames ()
Protected Member Functions
void writeLayerAttr (QXmlStreamWriter &writer, ViewLayer::ViewLayerID)
void writeSvgIdAttr (QXmlStreamWriter &writer, ViewLayer::ViewID view, QString connId)
void writeTerminalIdAttr (QXmlStreamWriter &writer, ViewLayer::ViewID view, QString terminalId)
Protected Attributes
QPointer< class Bus > m_bus
QHash< int, QPointer< class ConnectorItem > > m_connectorItems
QString m_connectorLocalName
QPointer< class ConnectorShared > m_connectorShared
QPointer< class ModelPart > m_modelPart
QList< Connector * > m_toConnectors
Static Protected Attributes
static QHash< ConnectorType, QString > Names
Member Enumeration Documentation
ConnectorType
enum Connector::ConnectorType
Enumerator
Male
Female
Wire
Pad
Unknown
Constructor & Destructor Documentation
Connector()
Connector::Connector (class ConnectorShared * connectorShared, class ModelPart * modelPart)
References connectorShared(), m_bus, m_connectorShared, m_modelPart, and modelPart().
~Connector()
Connector::~Connector ()
References ConnectorItem::clearConnector(), connectorItem(), and m_connectorItems.
Member Function Documentation
addPin()
void Connector::addPin (ViewLayer::ViewID viewID, const QString & svgId, ViewLayer::ViewLayerID viewLayerId, const QString & terminalId, const QString & legId, bool hybrid)
References m_connectorShared.
addViewItem()
void Connector::addViewItem (class ConnectorItem * item)
References ConnectorItem::attachedToViewID(), ConnectorItem::attachedToViewLayerID(), m_connectorItems, and QuickHash().
bus()
Bus * Connector::bus ()
References m_bus.
busID()
const QString & Connector::busID ()
References ___emptyString___, and m_bus.
connectionIsAllowed()
bool Connector::connectionIsAllowed (Connector * that)
References connectorType(), Unknown, and Wire.
connectorItem()
ConnectorItem * Connector::connectorItem (ViewLayer::ViewID viewID)
References ConnectorItem::attachedToViewID(), and m_connectorItems.
connectorItemByViewLayerID()
ConnectorItem * Connector::connectorItemByViewLayerID (ViewLayer::ViewID viewID, ViewLayer::ViewLayerID viewLayerID)
References m_connectorItems, and QuickHash().
connectorItemCount()
int Connector::connectorItemCount ()
References m_connectorItems.
connectorLocalName()
const QString & Connector::connectorLocalName ()
References m_connectorLocalName.
connectorNameFromType()
const QString & Connector::connectorNameFromType (ConnectorType type) static
References Names.
connectorShared()
ConnectorShared * Connector::connectorShared ()
References m_connectorShared.
connectorSharedDescription()
const QString & Connector::connectorSharedDescription () const
References ___emptyString___, and m_connectorShared.
connectorSharedErcData()
ErcData * Connector::connectorSharedErcData ()
References m_connectorShared.
connectorSharedID()
const QString & Connector::connectorSharedID () const
References ___emptyString___, and m_connectorShared.
connectorSharedName()
const QString & Connector::connectorSharedName () const
References ___emptyString___, m_connectorLocalName, and m_connectorShared.
connectorSharedReplacedby()
const QString & Connector::connectorSharedReplacedby () const
References ___emptyString___, and m_connectorShared.
connectorType()
Connector::ConnectorType Connector::connectorType () const
References m_connectorShared, and Unknown.
connectorTypeFromName()
Connector::ConnectorType Connector::connectorTypeFromName (const QString & name) static
References Names, and Unknown.
connectTo()
void Connector::connectTo (Connector * connector)
References DebugDialog::debug(), m_toConnectors, and modelPart().
disconnectFrom()
void Connector::disconnectFrom (Connector * connector)
References m_toConnectors.
fullPinInfo()
SvgIdLayer * Connector::fullPinInfo (ViewLayer::ViewID viewId, ViewLayer::ViewLayerID viewLayerID)
References m_connectorShared.
initNames()
void Connector::initNames () static
References Female, Male, Names, Pad, and Wire.
legID()
const QString & Connector::legID (ViewLayer::ViewID viewID, ViewLayer::ViewLayerID viewLayerID)
References ___emptyString___, and m_connectorShared.
modelIndex()
long Connector::modelIndex ()
References DebugDialog::debug(), and m_modelPart.
modelPart()
ModelPart * Connector::modelPart ()
References m_modelPart.
removeViewItem()
void Connector::removeViewItem (class ConnectorItem * item)
References ConnectorItem::attachedToViewID(), ConnectorItem::attachedToViewLayerID(), m_connectorItems, and QuickHash().
saveAsPart()
void Connector::saveAsPart (QXmlStreamWriter & writer)
References connectorShared(), m_connectorShared, SvgIdLayer::m_svgId, SvgIdLayer::m_svgViewLayerID, SvgIdLayer::m_terminalId, ViewLayer::viewIDXmlName(), writeLayerAttr(), writeSvgIdAttr(), and writeTerminalIdAttr().
setBus()
void Connector::setBus (class Bus * bus)
References bus(), and m_bus.
setConnectorLocalName()
void Connector::setConnectorLocalName (const QString & name)
References m_connectorLocalName, and m_connectorShared.
svgIdLayers()
const QList< SvgIdLayer * > Connector::svgIdLayers () const
References EmptySvgIdLayerList, and m_connectorShared.
toConnectors()
const QList< Connector * > & Connector::toConnectors ()
References m_toConnectors.
unprocess()
void Connector::unprocess (ViewLayer::ViewID viewID, ViewLayer::ViewLayerID viewLayerID)
References m_connectorShared, and SvgIdLayer::unprocess().
viewItems()
QList< QPointer< ConnectorItem > > Connector::viewItems ()
References m_connectorItems.
writeLayerAttr()
void Connector::writeLayerAttr (QXmlStreamWriter & writer, ViewLayer::ViewLayerID viewLayerID) protected
References ViewLayer::viewLayerXmlNameFromID().
writeSvgIdAttr()
void Connector::writeSvgIdAttr (QXmlStreamWriter & writer, ViewLayer::ViewID view, QString connId) protected
writeTerminalIdAttr()
void Connector::writeTerminalIdAttr (QXmlStreamWriter & writer, ViewLayer::ViewID view, QString terminalId) protected
References ViewLayer::BreadboardView, and ViewLayer::SchematicView.
Member Data Documentation
m_bus
QPointer<class Bus> Connector::m_bus protected
m_connectorItems
QHash< int, QPointer<class ConnectorItem> > Connector::m_connectorItems protected
m_connectorLocalName
QString Connector::m_connectorLocalName protected
m_connectorShared
QPointer<class ConnectorShared> Connector::m_connectorShared protected
m_modelPart
QPointer<class ModelPart> Connector::m_modelPart protected
m_toConnectors
QList<Connector *> Connector::m_toConnectors protected
Names
QHash< Connector::ConnectorType, QString > Connector::Names static protected
The documentation for this class was generated from the following files:
connectors/connector.h
connectors/connector.cpp