Fritzing: PlatformArduino Class Reference
PlatformArduino Class Reference
#include <platformarduino.h>
Public Member Functions
PlatformArduino ()
void upload (QWidget *source, const QString &port, const QString &board, const QString &fileLocation)
Public Member Functions inherited from Platform
Platform (const QString &name)
~Platform ()=default
bool canProgram () const
QMap< QString, QString > getBoards () const
QString getCommandLocation () const noexcept
QString getDefaultBoardName () const
QUrl getDownloadUrl () const
QStringList getExtensions () const noexcept
QString getIdeName () const
QString getMinVersion () const
QString getName () const noexcept
QUrl getReferenceUrl () const
Syntaxer * getSyntaxer () const noexcept
void setBoards (const QMap< QString, QString > &boards)
void setCanProgram (bool canProgram)
void setCommandLocation (const QString &commandLocation)
void setDefaultBoardName (const QString &defaultBoardName)
void setDownloadUrl (const QUrl &downloadUrl)
void setExtensions (const QStringList &suffixes)
void setIdeName (const QString &ideName)
void setMinVersion (const QString &minVersion)
void setReferenceUrl (const QUrl &referenceUrl)
Additional Inherited Members
Signals inherited from Platform
void commandLocationChanged ()
Protected Attributes inherited from Platform
QMap< QString, QString > m_boards
bool m_canProgram
QString m_commandLocation
QString m_defaultBoardName
QUrl m_downloadUrl
QStringList m_extensions
QString m_ideName
QString m_minVersion
QString m_name
QUrl m_referenceUrl
Constructor & Destructor Documentation
PlatformArduino()
PlatformArduino::PlatformArduino ()
References Platform::setBoards(), Platform::setCanProgram(), Platform::setDefaultBoardName(), Platform::setDownloadUrl(), Platform::setExtensions(), Platform::setIdeName(), Platform::setMinVersion(), and Platform::setReferenceUrl().
Member Function Documentation
upload()
void PlatformArduino::upload (QWidget * source, const QString & port, const QString & board, const QString & fileLocation) virtual
Reimplemented from Platform.
References ProgramTab::appendToConsole(), Platform::getBoards(), and Platform::getCommandLocation().
The documentation for this class was generated from the following files:
program/platformarduino.h
program/platformarduino.cpp