Fritzing: EditableLineWidget Class Reference
EditableLineWidget Class Reference
#include <editablelinewidget.h>
Public Member Functions
EditableLineWidget (QString text, WaitPushUndoStack *undoStack, QWidget *parent=0, QString title="", bool edited=false, bool noSpacing=false)
void setText (const QString &text)
void setValidator (const QValidator *v)
Public Member Functions inherited from AbstractEditableLabelWidget
AbstractEditableLabelWidget (QString text, WaitPushUndoStack *undoStack, QWidget *parent=0, QString title="", bool edited=false, bool noSpacing=false)
QString text ()
Protected Member Functions
QString editionText ()
QWidget * myEditionWidget ()
void setEditionText (QString text)
void setEmptyTextToEdit ()
Protected Member Functions inherited from AbstractEditableLabelWidget
void setNoSpacing (QLayout *layout)
void toEditionMode ()
void toStandardMode ()
Protected Attributes
QLineEdit * m_lineEdit
Protected Attributes inherited from AbstractEditableLabelWidget
QPushButton * m_acceptButton
QPushButton * m_cancelButton
bool m_edited
volatile bool m_isInEditionMode
EditableLabel * m_label
bool m_noSpacing
QLabel * m_title
class WaitPushUndoStack * m_undoStack
Additional Inherited Members
Signals inherited from AbstractEditableLabelWidget
void editionCompleted (QString text)
void editionFinished ()
void editionStarted ()
Protected Slots inherited from AbstractEditableLabelWidget
void editionCanceled ()
void editionStarted (QString text)
void informEditionCompleted ()
Constructor & Destructor Documentation
EditableLineWidget()
EditableLineWidget::EditableLineWidget (QString text, WaitPushUndoStack * undoStack, QWidget * parent = 0, QString title = "", bool edited = false, bool noSpacing = false)
References m_lineEdit, and AbstractEditableLabelWidget::toStandardMode().
Member Function Documentation
editionText()
QString EditableLineWidget::editionText () protected virtual
Implements AbstractEditableLabelWidget.
References m_lineEdit.
myEditionWidget()
QWidget * EditableLineWidget::myEditionWidget () protected virtual
Implements AbstractEditableLabelWidget.
References m_lineEdit.
setEditionText()
void EditableLineWidget::setEditionText (QString text) protected virtual
Implements AbstractEditableLabelWidget.
References m_lineEdit, and AbstractEditableLabelWidget::text().
setEmptyTextToEdit()
void EditableLineWidget::setEmptyTextToEdit () protected virtual
Implements AbstractEditableLabelWidget.
References m_lineEdit.
setText()
void EditableLineWidget::setText (const QString & text)
References AbstractEditableLabelWidget::m_label, m_lineEdit, and AbstractEditableLabelWidget::text().
setValidator()
void EditableLineWidget::setValidator (const QValidator * v)
References m_lineEdit.
Member Data Documentation
m_lineEdit
QLineEdit* EditableLineWidget::m_lineEdit protected
The documentation for this class was generated from the following files:
partseditor/obsolete/editablelinewidget.h
partseditor/obsolete/editablelinewidget.cpp