Fritzing: SingleConnectorInfoWidget Class Reference
SingleConnectorInfoWidget Class Reference
#include <singleconnectorinfowidget.h>
Signals
void editionFinished ()
void editionStarted ()
Signals inherited from AbstractConnectorInfoWidget
void repaintNeeded ()
void tellSistersImNewSelected (AbstractConnectorInfoWidget *)
void tellViewsMyConnectorIsNewSelected (const QString &)
Public Member Functions
SingleConnectorInfoWidget (ConnectorsInfoWidget *topLevelContainer, WaitPushUndoStack *undoStack, Connector *connector=0, QWidget *parent=0)
Connector * connector ()
Connector::ConnectorType connectorType ()
QString description ()
QString id ()
bool isInEditionMode ()
QSize maximumSizeHint () const
QSize minimumSizeHint () const
QString name ()
void setConnectorType (Connector::ConnectorType)
void setInEditionMode (bool inEditionMode)
void setName (const QString &)
void setSelected (bool selected, bool doEmitChange=true)
QSize sizeHint () const
MismatchingConnectorWidget * toMismatching (ViewLayer::ViewIdentifier viewId)
QString type ()
Public Member Functions inherited from AbstractConnectorInfoWidget
AbstractConnectorInfoWidget (class ConnectorsInfoWidget *topLevelContainer, QWidget *parent=0)
bool isSelected ()
Protected Slots
void editionCanceled ()
void editionCompleted ()
Protected Member Functions
void createInputs ()
void hideIfNeeded (QWidget *w)
void mousePressEvent (QMouseEvent *event)
void startEdition ()
void toEditionMode ()
void toStandardMode ()
Protected Member Functions inherited from AbstractConnectorInfoWidget
void reapplyStyle ()
Protected Attributes
QPushButton * m_acceptButton
QPushButton * m_cancelButton
QPointer< Connector > m_connector
QTextEdit * m_descEdit
QFrame * m_descEditContainer
QLabel * m_descLabel
QString m_id
volatile bool m_isInEditionMode
QLabel * m_nameDescSeparator
QLineEdit * m_nameEdit
QFrame * m_nameEditContainer
QLabel * m_nameLabel
ConnectorTypeWidget * m_type
WaitPushUndoStack * m_undoStack
Protected Attributes inherited from AbstractConnectorInfoWidget
volatile bool m_isSelected
ConnectorInfoRemoveButton * m_removeButton
ConnectorsInfoWidget * m_topLevelContainer
Additional Inherited Members
Static Protected Attributes inherited from AbstractConnectorInfoWidget
static int SingleConnectorHeight = 40
Constructor & Destructor Documentation
SingleConnectorInfoWidget()
SingleConnectorInfoWidget::SingleConnectorInfoWidget (ConnectorsInfoWidget * topLevelContainer, WaitPushUndoStack * undoStack, Connector * connector = 0, QWidget * parent = 0)
References connector(), Connector::connectorShared(), Connector::connectorSharedDescription(), Connector::connectorSharedID(), Connector::connectorSharedName(), Connector::connectorType(), description(), m_acceptButton, m_cancelButton, m_connector, m_descEdit, m_descEditContainer, m_descLabel, m_id, m_nameDescSeparator, m_nameEdit, m_nameEditContainer, m_nameLabel, m_type, m_undoStack, Connector::Male, name(), setSelected(), toStandardMode(), type(), and Connector::Unknown.
Member Function Documentation
connector()
Connector * SingleConnectorInfoWidget::connector ()
References m_connector.
connectorType()
Connector::ConnectorType SingleConnectorInfoWidget::connectorType ()
References m_type, ConnectorTypeWidget::type(), and Connector::Unknown.
createInputs()
void SingleConnectorInfoWidget::createInputs () protected
References m_descEdit, m_descEditContainer, m_nameEdit, and m_nameEditContainer.
description()
QString SingleConnectorInfoWidget::description ()
References m_descLabel.
editionCanceled
void SingleConnectorInfoWidget::editionCanceled () protected slot
References ConnectorTypeWidget::cancel(), editionFinished(), m_type, and toStandardMode().
editionCompleted
void SingleConnectorInfoWidget::editionCompleted () protected slot
References editionFinished(), m_descEdit, m_descLabel, m_isInEditionMode, m_nameEdit, m_nameLabel, m_undoStack, WaitPushUndoStack::push(), and toStandardMode().
editionFinished
void SingleConnectorInfoWidget::editionFinished () signal
editionStarted
void SingleConnectorInfoWidget::editionStarted () signal
hideIfNeeded()
void SingleConnectorInfoWidget::hideIfNeeded (QWidget * w) protected
id()
QString SingleConnectorInfoWidget::id ()
References m_connector, and m_id.
isInEditionMode()
bool SingleConnectorInfoWidget::isInEditionMode ()
References m_isInEditionMode.
maximumSizeHint()
QSize SingleConnectorInfoWidget::maximumSizeHint () const
References sizeHint().
minimumSizeHint()
QSize SingleConnectorInfoWidget::minimumSizeHint () const
References sizeHint().
mousePressEvent()
void SingleConnectorInfoWidget::mousePressEvent (QMouseEvent * event) protected
References isInEditionMode(), AbstractConnectorInfoWidget::isSelected(), setSelected(), and startEdition().
name()
QString SingleConnectorInfoWidget::name ()
References m_nameLabel.
setConnectorType()
void SingleConnectorInfoWidget::setConnectorType (Connector::ConnectorType type)
References m_type, ConnectorTypeWidget::setType(), and type().
setInEditionMode()
void SingleConnectorInfoWidget::setInEditionMode (bool inEditionMode)
References m_isInEditionMode, m_type, and ConnectorTypeWidget::setInEditionMode().
setName()
void SingleConnectorInfoWidget::setName (const QString & name)
References m_nameEdit, m_nameLabel, and name().
setSelected()
void SingleConnectorInfoWidget::setSelected (bool selected, bool doEmitChange = true) virtual
Reimplemented from AbstractConnectorInfoWidget.
References m_connector, m_type, AbstractConnectorInfoWidget::setSelected(), ConnectorTypeWidget::setSelected(), and AbstractConnectorInfoWidget::tellViewsMyConnectorIsNewSelected().
sizeHint()
QSize SingleConnectorInfoWidget::sizeHint () const
References m_isInEditionMode, and AbstractConnectorInfoWidget::SingleConnectorHeight.
startEdition()
void SingleConnectorInfoWidget::startEdition () protected
References createInputs(), editionStarted(), m_descEdit, m_descLabel, m_nameEdit, m_nameLabel, and toEditionMode().
toEditionMode()
void SingleConnectorInfoWidget::toEditionMode () protected
References createInputs(), editionCanceled(), editionCompleted(), editionStarted(), hideIfNeeded(), m_acceptButton, m_cancelButton, m_descEditContainer, m_descLabel, m_nameDescSeparator, m_nameEditContainer, m_nameLabel, AbstractConnectorInfoWidget::m_removeButton, m_type, setInEditionMode(), and AbstractConnectorInfoWidget::SingleConnectorHeight.
toMismatching()
MismatchingConnectorWidget * SingleConnectorInfoWidget::toMismatching (ViewLayer::ViewIdentifier viewId)
References m_connector, and AbstractConnectorInfoWidget::m_topLevelContainer.
toStandardMode()
void SingleConnectorInfoWidget::toStandardMode () protected
References hideIfNeeded(), m_acceptButton, m_cancelButton, m_descEditContainer, m_descLabel, m_nameDescSeparator, m_nameEditContainer, m_nameLabel, AbstractConnectorInfoWidget::m_removeButton, m_type, setInEditionMode(), and AbstractConnectorInfoWidget::SingleConnectorHeight.
type()
QString SingleConnectorInfoWidget::type ()
References m_type, and ConnectorTypeWidget::typeAsStr().
Member Data Documentation
m_acceptButton
QPushButton* SingleConnectorInfoWidget::m_acceptButton protected
m_cancelButton
QPushButton* SingleConnectorInfoWidget::m_cancelButton protected
m_connector
QPointer<Connector> SingleConnectorInfoWidget::m_connector protected
m_descEdit
QTextEdit* SingleConnectorInfoWidget::m_descEdit protected
m_descEditContainer
QFrame* SingleConnectorInfoWidget::m_descEditContainer protected
m_descLabel
QLabel* SingleConnectorInfoWidget::m_descLabel protected
m_id
QString SingleConnectorInfoWidget::m_id protected
m_isInEditionMode
volatile bool SingleConnectorInfoWidget::m_isInEditionMode protected
m_nameDescSeparator
QLabel* SingleConnectorInfoWidget::m_nameDescSeparator protected
m_nameEdit
QLineEdit* SingleConnectorInfoWidget::m_nameEdit protected
m_nameEditContainer
QFrame* SingleConnectorInfoWidget::m_nameEditContainer protected
m_nameLabel
QLabel* SingleConnectorInfoWidget::m_nameLabel protected
m_type
ConnectorTypeWidget* SingleConnectorInfoWidget::m_type protected
m_undoStack
WaitPushUndoStack* SingleConnectorInfoWidget::m_undoStack protected
The documentation for this class was generated from the following files:
partseditor/obsolete/singleconnectorinfowidget.h
partseditor/obsolete/singleconnectorinfowidget.cpp