Fritzing: JumperItem Class Reference
JumperItem Class Reference
#include <jumperitem.h>
Signals
void alignMe (JumperItem *, QPointF &p)
Signals inherited from PaletteItem
void pinLabelSwap (ItemBase *, const QString &moduleID)
Public Member Functions
JumperItem (ModelPart *modelPart, ViewLayer::ViewID, const ViewGeometry &, long id, QMenu *itemMenu, bool doLabel)
~JumperItem ()
void addedToScene (bool temporary)
QRectF boundingRect () const
void calcRotation (QTransform &rotation, QPointF center, ViewGeometry &)
class ConnectorItem * connector0 ()
class ConnectorItem * connector1 ()
QPointF dragOffset ()
QSizeF footprintSize ()
bool getAutoroutable ()
void getParams (QPointF &pos, QPointF &c0, QPointF &c1)
bool hasCustomSVG ()
bool hasPartNumberProperty ()
QPainterPath hoverShape () const
bool inDrag ()
PluralType isPlural ()
void loadLayerKin (const LayerHash &viewLayers, ViewLayer::ViewLayerPlacement)
void mouseMoveEventK (PaletteItemBase *originalItem, QGraphicsSceneMouseEvent *)
bool mousePressEventK (PaletteItemBase *originalItem, QGraphicsSceneMouseEvent *)
void mouseReleaseEventK (PaletteItemBase *originalItem, QGraphicsSceneMouseEvent *)
void resize (QPointF pos, QPointF c0, QPointF c1)
void resize (QPointF p0, QPointF p1)
QString retrieveSvg (ViewLayer::ViewLayerID viewLayerID, QHash< QString, QString > &svgHash, bool blackOnly, double dpi, double &factor)
void rotateItem (double degrees, bool includeRatsnest)
void saveInstanceLocation (QXmlStreamWriter &streamWriter)
void saveParams ()
void setAutoroutable (bool)
bool setUpImage (ModelPart *modelPart, const LayerHash &viewLayers, LayerAttributes &)
QPainterPath shape () const
Public Member Functions inherited from PaletteItem
PaletteItem (ModelPart *, ViewLayer::ViewID, const ViewGeometry &viewGeometry, long id, QMenu *itemMenu, bool doLabel)
~PaletteItem ()
void addLayerKin (class LayerKinPaletteItem *lkpi)
virtual bool changePinLabels (bool singleRow, bool sip)
void clearModelPart ()
bool collectExtraInfo (QWidget *parent, const QString &family, const QString &prop, const QString &value, bool swappingEnabled, QString &returnProp, QString &returnValue, QWidget *&returnWidget, bool &hide)
bool collectFemaleConnectees (QSet< ItemBase * > &items)
QStringList collectValues (const QString &family, const QString &prop, QString &value)
void collectWireConnectees (QSet< class Wire * > &wires)
void flipItem (Qt::Orientations orientation)
QStringList getPinLabels (bool &hasLocal)
const QList< class ItemBase * > & layerKin ()
bool mousePressEventK (PaletteItemBase *originalItem, QGraphicsSceneMouseEvent *)
void moveItem (ViewGeometry &viewGeometry)
void removeLayerKin ()
void renamePins (const QStringList &labels, bool singleRow)
bool renderImage (ModelPart *modelPart, ViewLayer::ViewID viewID, const LayerHash &viewLayers, ViewLayer::ViewLayerID, bool doConnectors, QString &error)
void resetConnector (ItemBase *itemBase, SvgIdLayer *svgIdLayer)
void resetConnectors ()
void resetConnectors (ItemBase *otherLayer, FSvgRenderer *otherLayerRenderer)
void resetID ()
void resetImage (class InfoGraphicsView *)
void resetKinImage (ItemBase *layerKin, InfoGraphicsView *infoGraphicsView)
void resetLayerKin (const QString &svg)
void retransform (const QTransform &)
void rotateItem (double degrees, bool includeRatsnest)
void setHidden (bool hidden)
void setInactive (bool inactivate)
void setInstanceTitle (const QString &, bool initial)
void setItemPos (QPointF &pos)
void setTransforms ()
QStringList sipOrDipOrLabels (bool &hasLayout, bool &sip)
void slamZ (double z)
bool swap (ModelPart *newModelPart, const LayerHash &layerHash, bool reinit, class SwapCommand *)
void syncKinMoved (QPointF offset, QPointF loc)
void transformItem2 (const QMatrix &)
QTransform untransform ()
Public Member Functions inherited from PaletteItemBase
PaletteItemBase (ModelPart *, ViewLayer::ViewID, const ViewGeometry &viewGeometry, long id, QMenu *itemMenu)
bool acceptsMousePressConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
void blockItemSelectedChange (bool selected)
QRectF boundingRect () const
QRectF boundingRectWithoutLegs () const
virtual bool canEditPart ()
bool collectExtraInfo (QWidget *parent, const QString &family, const QString &prop, const QString &value, bool swappingEnabled, QString &returnProp, QString &returnValue, QWidget *&returnWidget, bool &hide)
bool collectFemaleConnectees (QSet< ItemBase * > &items)
void collectWireConnectees (QSet< class Wire * > &wires)
void connectedMoved (ConnectorItem *from, ConnectorItem *to, QList< ConnectorItem * > &already)
void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
void cursorKeyEvent (Qt::KeyboardModifiers modifiers)
const QCursor * getCursor (Qt::KeyboardModifiers)
void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
void hoverMoveEvent (QGraphicsSceneHoverEvent *event)
QPainterPath hoverShape () const
bool itemMoved ()
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
void mousePressConnectorEvent (class ConnectorItem *, QGraphicsSceneMouseEvent *)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
void moveItem (ViewGeometry &)
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
void paintHover (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
void paintSelected (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
QString retrieveSvg (ViewLayer::ViewLayerID, QHash< QString, QString > &svgHash, bool blackOnly, double dpi, double &factor)
void saveGeometry ()
void setProp (const QString &prop, const QString &value)
QPainterPath shape () const
QPointF syncMoved ()
bool syncSelected ()
Public Member Functions inherited from ItemBase
ItemBase (ModelPart *, ViewLayer::ViewID, const ViewGeometry &, long id, QMenu *itemMenu)
virtual ~ItemBase ()
virtual bool acceptsMouseDoubleClickConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual bool acceptsMouseMoveConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual bool acceptsMousePressLegEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual bool acceptsMouseReleaseConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual void addSticky (ItemBase *, bool stickem)
void addSubpart (ItemBase *)
virtual bool alreadySticking (ItemBase *itemBase)
ConnectorItem * anyConnectorItem ()
QRectF boundingRect () const
virtual void busConnectorItems (Bus *bus, ConnectorItem *, QList< ConnectorItem * > &items)
QList< Bus * > buses ()
const QList< ConnectorItem * > & cachedConnectorItems ()
const QList< ConnectorItem * > & cachedConnectorItemsConst () const
bool canFlip (Qt::Orientations)
bool canFlipHorizontal ()
bool canFlipVertical ()
virtual void clearConnectorHover ()
void clearConnectorItemCache ()
void clearPartLabel ()
void collectConnectors (ConnectorPairHash &connectorHash, SkipCheckFunction)
void collectPropsMap (QString &family, QMap< QString, QString > &)
virtual void collectWireConnectees (QSet< Wire * > &wires)
virtual void connectionChange (ConnectorItem *onMe, ConnectorItem *onIt, bool connect)
virtual bool connectionIsAllowed (ConnectorItem *)
virtual void connectorHover (ConnectorItem *, ItemBase *, bool hovering)
const QString & constTitle () const
void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
void debugInfo (const QString &msg) const
void debugInfo2 (const QString &msg) const
virtual void doneLoading ()
void doRotateFlipPartLabel (double degrees, Qt::Orientations)
void ensureUniqueTitle (const QString &title, bool force)
QString family ()
const QString & filename ()
virtual bool filterMousePressConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
ConnectorItem * findConnectorItemWithSharedID (const QString &connectorID, ViewLayer::ViewLayerPlacement)
ConnectorItem * findConnectorItemWithSharedID (const QString &connectorID)
ItemBase * findSubpart (const QString &connectorID, ViewLayer::ViewLayerPlacement)
FSvgRenderer * fsvgRenderer () const
virtual void getConnectedColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
virtual void getEqualPotentialColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
virtual void getHoverColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
virtual QString getInspectorTitle ()
virtual void getNormalColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
QPixmap * getPixmap (QSize size)
void getPixmaps (QPixmap *&, QPixmap *&, QPixmap *&, bool swappingEnabled, QSize)
virtual QString getProperty (const QString &key)
bool getRatsnest ()
virtual void getUnconnectedColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
ViewGeometry & getViewGeometry ()
bool hasConnections ()
bool hasConnectors ()
bool hasNonConnectors ()
virtual bool hasPartLabel ()
bool hasRubberBandLeg () const
constexpr bool hidden () const noexcept
virtual void hoverEnterConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
void hoverEnterConnectorItem ()
void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
virtual void hoverLeaveConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
void hoverLeaveConnectorItem ()
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
virtual void hoverMoveConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
virtual void hoverUpdate ()
constexpr qint64 id () const noexcept
constexpr bool inactive () const noexcept
bool inHover ()
void initLayerAttributes (LayerAttributes &layerAttributes, ViewLayer::ViewID, ViewLayer::ViewLayerID, ViewLayer::ViewLayerPlacement, bool doConnectors, bool doCreateShape)
virtual bool inRotation ()
const QString & instanceTitle () const
virtual bool isBaseSticky ()
bool isEverVisible ()
bool isLocalSticky ()
bool isObsolete ()
bool isPartLabelVisible ()
virtual bool isSticky ()
virtual bool isSwappable ()
int itemType () const
void killRubberBandLeg ()
QString label ()
constexpr bool layerHidden () const noexcept
virtual ItemBase * layerKinChief ()
QString makePartLabelSvg (bool blackOnly, double dpi, double printerScale)
ModelPart * modelPart ()
ModelPartShared * modelPartShared ()
const QString & moduleID ()
virtual void mouseDoubleClickConnectorEvent (ConnectorItem *)
virtual void mouseMoveConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
void mousePressEvent (QGraphicsSceneMouseEvent *event)
virtual void mouseReleaseConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
bool moveLock ()
void movePartLabel (QPointF newPos, QPointF newOffset)
virtual ConnectorItem * newConnectorItem (Connector *connector)
virtual ConnectorItem * newConnectorItem (ItemBase *layerkin, Connector *connector)
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
PartLabel * partLabel ()
void partLabelMoved (QPointF oldPos, QPointF oldOffset, QPointF newPos, QPointF newOffset)
QRectF partLabelSceneBoundingRect ()
QPointF partLabelScenePos ()
void partLabelSetHidden (bool hide)
ViewLayer::ViewLayerID partLabelViewLayerID ()
void prepareGeometryChange ()
virtual QHash< QString, QString > prepareProps (ModelPart *, bool wantDebug, QStringList &keys)
QString prop (const QString &p)
bool reloadRenderer (const QString &svg, bool fastload)
void removeTooltip ()
bool resetRenderer (const QString &svg)
bool resetRenderer (const QString &svg, QString &newSvg)
void resetValues (const QString &family, const QString &prop)
void restorePartLabel (QDomElement &labelGeometry, ViewLayer::ViewLayerID)
ConnectorItem * rightClickedConnector ()
void rotateFlipPartLabel (double degrees, Qt::Orientations)
virtual bool rotation45Allowed ()
virtual bool rotationAllowed ()
virtual void saveInstance (QXmlStreamWriter &)
bool sceneEvent (QEvent *event)
const QPainterPath & selectionShape ()
virtual void setAcceptsMousePressLegEvent (bool)
void setCanFlipHorizontal (bool)
void setCanFlipVertical (bool)
virtual void setDropOffset (QPointF offset)
void setEverVisible (bool)
void setFilename (const QString &)
virtual void setInRotation (bool)
virtual void setInspectorTitle (const QString &oldText, const QString &newText)
void setItemIsSelectable (bool selectable)
virtual void setLayerHidden (bool hidden)
void setLocalSticky (bool)
void setModelPart (ModelPart *)
virtual void setMoveLock (bool)
void setSharedRendererEx (FSvgRenderer *)
void setSquashShape (bool)
virtual void setSticky (bool)
void setSuperpart (ItemBase *)
virtual void setSwappable (bool)
void setTooltip ()
virtual void setTransform2 (const QTransform &)
FSvgRenderer * setUpImage (ModelPart *modelPart, LayerAttributes &)
void setViewLayerID (ViewLayer::ViewLayerID, const LayerHash &viewLayers)
void setViewLayerID (const QString &layerName, const LayerHash &viewLayers)
void setViewLayerPlacement (ViewLayer::ViewLayerPlacement)
void showConnectors (const QStringList &)
constexpr QSizeF size () const noexcept
const QString & spice () const
const QString & spiceModel () const
virtual ItemBase * stickingTo ()
virtual bool stickyEnabled ()
virtual QList< QPointer< ItemBase > > stickyList ()
const QList< QPointer< ItemBase > > & subparts ()
ItemBase * superpart ()
virtual const QString & title ()
bool topLevel ()
virtual void transformItem (const QTransform &, bool includeRatsnest)
void updateConnections (ConnectorItem *, bool includeRatsnest, QList< ConnectorItem * > &already)
void updateConnectionsAux (bool includeRatsnest, QList< ConnectorItem * > &already)
void updateConnectors ()
void updatePartLabelInstanceTitle ()
virtual void updateTooltip ()
ViewLayer::ViewID viewID ()
QString & viewIDName ()
ViewLayer::ViewLayerID viewLayerID () const
ViewLayer::ViewLayerPlacement viewLayerPlacement () const
ViewGeometry::WireFlags wireFlags () const
virtual void writeGeometry (QXmlStreamWriter &)
virtual void writeXml (QXmlStreamWriter &)
double z ()
Protected Member Functions
QPointF calcPos (QPointF p0, QPointF p1)
void initialResize (ViewLayer::ViewID)
QString makeSvg (ViewLayer::ViewLayerID)
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
void mousePressEvent (QGraphicsSceneMouseEvent *event)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
void paintHover (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
void paintSelected (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
void resize ()
void resizeAux (double r0x, double r0y, double r1x, double r1y)
void rotateEnds (QTransform &rotation, QPointF &tc0, QPointF &tc1)
ViewLayer::ViewID useViewIDForPixmap (ViewLayer::ViewID, bool swappingEnabled)
Protected Member Functions inherited from PaletteItem
QString appendHoleSize (const QString &moduleID, const QString &holeSize, const QString &ringThickness)
bool collectHoleSizeInfo (const QString &defaultHoleSizeValue, QWidget *parent, bool swappingEnabled, QString &returnProp, QString &returnValue, QWidget *&returnWidget)
void figureHover ()
void generateSwap (const QString &text, GenModuleID, GenFzp, GenSvg makeBreadboardSvg, GenSvg makeSchematicSvg, GenSvg makePcbSvg)
QString hackFzpHoleSize (const QString &moduleID, const QString &pcbFilename, const QString &holeSize)
QString hackSvgHoleSize (const QString &holeDiameter, const QString &ringThickness)
bool isSingleRow (const QList< ConnectorItem * > &connectorItems)
QVariant itemChange (GraphicsItemChange change, const QVariant &value)
bool makeLocalModifications (QByteArray &svg, const QString &filename)
void makeOneKin (qint64 &id, ViewLayer::ViewLayerID, ViewLayer::ViewLayerPlacement, ViewGeometry &, const LayerHash &)
void mousePressEvent (QGraphicsSceneMouseEvent *event)
void setUpHoleSizes (const QString &type, HoleClassThing &)
void setUpHoleSizesAux (HoleClassThing &, const QString &type)
QList< Connector * > sortConnectors ()
void syncKinSelection (bool selected, PaletteItemBase *originator)
void updateConnections (bool includeRatsnest, QList< ConnectorItem * > &already)
Protected Member Functions inherited from PaletteItemBase
virtual void cacheLoaded (const LayerAttributes &)
virtual bool canFindConnectorsUnder ()
void checkFreeRotation (Qt::KeyboardModifiers modifiers, QPointF scenePos)
void findConnectorsUnder ()
virtual bool freeRotationAllowed (Qt::KeyboardModifiers modifiers)
bool freeRotationAllowed ()
bool inRotationLocation (QPointF scenePos, Qt::KeyboardModifiers modifiers, QPointF &returnPoint)
virtual LayerKinPaletteItem * newLayerKinPaletteItem (PaletteItemBase *chief, ModelPart *, const ViewGeometry &, long id, QMenu *itemMenu, const LayerHash &, LayerAttributes &)
virtual void setInitialTransform (const QTransform &)
void setUpConnectors (FSvgRenderer *, bool ignoreTerminalPoints)
Protected Member Functions inherited from ItemBase
void createShape (LayerAttributes &layerAttributes)
QPixmap * getPixmap (ViewLayer::ViewID, bool swappingEnabled, QSize size)
QVariant itemChange (QGraphicsItem::GraphicsItemChange change, const QVariant &value)
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
virtual void paintBody (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
virtual void paintHover (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget, const QPainterPath &shape)
void saveLocAndTransform (QXmlStreamWriter &streamWriter)
virtual void setDefaultTooltip ()
void setInstanceTitleAux (const QString &title, bool initial)
void setInstanceTitleTooltip (const QString &text)
void updateHidden ()
Protected Attributes
QPointer< ConnectorItem > m_connector0
QPointer< ConnectorItem > m_connector1
QPointF m_connectorBR
QPointF m_connectorTL
QPointer< ConnectorItem > m_dragItem
QPointF m_dragStartCenterPos
QPointF m_dragStartConnectorPos
QPointF m_dragStartScenePos
QPointF m_dragStartThisPos
QPointF m_itemC0
QPointF m_itemC1
QPointF m_itemPos
QPointer< PaletteItemBase > m_originalClickItem
QPointer< ConnectorItem > m_otherItem
QPointF m_otherPos
Protected Attributes inherited from PaletteItem
int m_flipCount
HoleSettings m_holeSettings
QList< class ItemBase * > m_layerKin
Protected Attributes inherited from PaletteItemBase
bool m_blockItemSelectedChange
bool m_blockItemSelectedValue
QPointF m_offset
bool m_svg
QPointF m_syncMoved
bool m_syncSelected
Protected Attributes inherited from ItemBase
bool m_acceptsMousePressLegEvent = true
QList< ConnectorItem * > m_cachedConnectorItems
bool m_canFlipHorizontal = false
bool m_canFlipVertical = false
int m_connectorHoverCount = 0
int m_connectorHoverCount2 = 0
bool m_everVisible = true
QString m_filename
FSvgRenderer * m_fsvgRenderer = nullptr
bool m_hasRubberBandLeg = false
bool m_hidden = false
int m_hoverCount = 0
bool m_hoverEnterSpaceBarWasPressed = false
qint64 m_id = 0
bool m_inactive = false
bool m_inRotation = false
QMenu * m_itemMenu = nullptr
bool m_layerHidden = false
QPointer< ModelPart > m_modelPart
bool m_moveLock = false
QGraphicsSvgItem * m_moveLockItem = nullptr
QPointer< PartLabel > m_partLabel
QMap< QString, QString > m_propsMap
ConnectorItem * m_rightClickedConnector = nullptr
QPainterPath m_selectionShape
QSizeF m_size
bool m_spaceBarWasPressed = false
bool m_squashShape = false
bool m_sticky = false
QGraphicsSvgItem * m_stickyItem = nullptr
QHash< long, QPointer< ItemBase > > m_stickyList
QList< QPointer< ItemBase > > m_subparts
QPointer< ItemBase > m_superpart
bool m_swappable = true
ViewGeometry m_viewGeometry
ViewLayer::ViewID m_viewID
ViewLayer::ViewLayerID m_viewLayerID
ViewLayer::ViewLayerPlacement m_viewLayerPlacement
bool m_zUninitialized = true
Additional Inherited Members
Public Types inherited from ItemBase
enum PluralType { Singular, Plural, NotSure }
Public Slots inherited from ItemBase
void hidePartLabel ()
void partLabelChanged (const QString &newText)
void showInFolder ()
void showPartLabel (bool show, ViewLayer *)
virtual void swapEntry (const QString &text)
Static Public Member Functions inherited from PaletteItem
static bool changeDiameter (HoleSettings &holeSettings, QObject *sender)
static bool changeThickness (HoleSettings &holeSettings, QObject *sender)
static QString changeUnits (HoleSettings &)
static QWidget * createHoleSettings (QWidget *parent, HoleSettings &, bool swappingEnabled, const QString &currentHoleSize, bool advanced)
static QString genFZP (const QString &moduleid, const QString &templateName, int minPins, int maxPins, int steps, bool smd)
static void initHoleSettings (HoleSettings &holeSettings, HoleClassThing *)
static bool setHoleSize (QString &holeSize, bool force, HoleSettings &holeSettings)
static void updateEditTexts (HoleSettings &)
static void updateSizes (HoleSettings &)
static void updateValidators (HoleSettings &)
Static Public Member Functions inherited from ItemBase
static void cleanup ()
static QColor connectedColor ()
static ItemBase * extractTopLevelItemBase (QGraphicsItem *thing)
static qint64 getNextID ()
static qint64 getNextID (qint64 fromIndex)
static void initNames ()
static void renderOne (QDomDocument *, QImage *, const QRectF &renderRect)
static void setConnectedColor (QColor &)
static void setReferenceModel (ReferenceModel *)
static void setUnconnectedColor (QColor &)
static QColor standardConnectedColor ()
static QColor standardUnconnectedColor ()
static QString translatePropertyName (const QString &key)
static QColor unconnectedColor ()
static bool zLessThan (ItemBase *&p1, ItemBase *&p2)
Static Public Attributes inherited from PaletteItem
static const QString HoleSizePrefix
Static Public Attributes inherited from ItemBase
static const QColor ConnectorHoverColor
static const double ConnectorHoverOpacity = .40
static const QList< ItemBase * > EmptyList
static const QColor HoverColor
static const double HoverOpacity = .20
static const QString ITEMBASE_FONT_PREFIX = "<font size='2'>"
static const QString ITEMBASE_FONT_SUFFIX = "</font>"
static QString PartInstanceDefaultTitle
static QHash< QString, QString > TranslatedPropertyNames
Protected Slots inherited from PaletteItem
void changeDiameter ()
virtual void changeHoleSize (const QString &)
void changeThickness ()
virtual void changeUnits (bool)
void openPinLabelDialog ()
Protected Slots inherited from PaletteItemBase
void partPropertyEntry ()
Static Protected Member Functions inherited from PaletteItem
static QStringList getSizes (QString &holeSize, HoleSettings &)
static QString hackFzpHoleSize (QDomDocument &document, const QString &newModuleID, const QString &pcbFilename, const QString &newSize)
static QString hackFzpHoleSize (const QString &fzp, const QString &moduleid, int hsix)
static QString hackSvgHoleSize (QDomDocument &domDocument, const QString &holeDiameter, const QString &ringThickness)
static QString hackSvgHoleSizeAux (const QString &svg, const QString &expectedFileName)
Static Protected Member Functions inherited from PaletteItemBase
static QString normalizeSvg (QString &svg, ViewLayer::ViewLayerID viewLayerID, bool blackOnly, double dpi, double &factor)
Static Protected Member Functions inherited from ItemBase
static bool fixCopper1 (ModelPart *modelPart, const QString &filename, ViewLayer::ViewLayerID viewLayerID, ViewLayer::ViewLayerPlacement, QDomDocument &)
static bool getFlipDoc (ModelPart *modelPart, const QString &filename, ViewLayer::ViewLayerID viewLayerID, ViewLayer::ViewLayerPlacement, QDomDocument &, Qt::Orientations)
Static Protected Attributes inherited from ItemBase
static QBrush ChosenBrush
static QPen ChosenPen
static QBrush ConnectedBrush
static QPen ConnectedPen
static QBrush EqualPotentialBrush
static QPen EqualPotentialPen
static QBrush HoverBrush
static QPen HoverPen
static long nextID
static QBrush NormalBrush
static constexpr double NormalConnectorOpacity = 0.4
static QPen NormalPen
static QPointer< ReferenceModel > TheReferenceModel = nullptr
static QBrush UnconnectedBrush
static QPen UnconnectedPen
Constructor & Destructor Documentation
JumperItem()
JumperItem::JumperItem (ModelPart * modelPart, ViewLayer::ViewID viewID, const ViewGeometry & viewGeometry, long id, QMenu * itemMenu, bool doLabel)
References Colors, ViewLayer::Copper0, ViewLayer::Copper0Color, Copper0LayerTemplate, ViewLayer::Copper1, ViewLayer::Copper1Color, JumperColor, JumperWireLayerTemplate, m_connector0, m_connector1, m_dragItem, m_originalClickItem, m_otherItem, ViewLayer::PartImage, ViewLayer::Silkscreen1, and ViewLayer::Silkscreen1Color.
~JumperItem()
JumperItem::~JumperItem ()
Member Function Documentation
addedToScene()
void JumperItem::addedToScene (bool temporary) virtual
Reimplemented from ItemBase.
References ItemBase::addedToScene(), m_connector0, and m_connector1.
alignMe
void JumperItem::alignMe (JumperItem * , QPointF & p) signal
boundingRect()
QRectF JumperItem::boundingRect () const
References PaletteItemBase::boundingRect(), ItemBase::m_viewID, ViewLayer::PCBView, and shape().
calcPos()
QPointF JumperItem::calcPos (QPointF p0, QPointF p1) protected
References m_connector0, m_connectorTL, and qMin().
calcRotation()
void JumperItem::calcRotation (QTransform & rotation, QPointF center, ViewGeometry & vg2) virtual
Reimplemented from ItemBase.
References boundingRect(), calcPos(), rotateEnds(), and ViewGeometry::setLoc().
connector0()
ConnectorItem * JumperItem::connector0 ()
References m_connector0.
connector1()
ConnectorItem * JumperItem::connector1 ()
References m_connector1.
dragOffset()
QPointF JumperItem::dragOffset ()
References m_dragStartCenterPos, and m_dragStartConnectorPos.
footprintSize()
QSizeF JumperItem::footprintSize ()
References m_connector0.
getAutoroutable()
bool JumperItem::getAutoroutable ()
References ViewGeometry::getAutoroutable(), and ItemBase::m_viewGeometry.
getParams()
void JumperItem::getParams (QPointF & pos, QPointF & c0, QPointF & c1)
References m_itemC0, m_itemC1, and m_itemPos.
hasCustomSVG()
bool JumperItem::hasCustomSVG () virtual
Reimplemented from ItemBase.
References ItemBase::hasCustomSVG(), ItemBase::m_viewID, and ViewLayer::PCBView.
hasPartNumberProperty()
bool JumperItem::hasPartNumberProperty () virtual
Reimplemented from ItemBase.
hoverShape()
QPainterPath JumperItem::hoverShape () const virtual
Reimplemented from ItemBase.
References PaletteItemBase::hoverShape(), m_connector0, m_connector1, m_connectorTL, ItemBase::m_viewID, ViewLayer::PCBView, and GraphicsUtils::shapeFromPath().
inDrag()
bool JumperItem::inDrag ()
References m_dragItem.
initialResize()
void JumperItem::initialResize (ViewLayer::ViewID viewID) protected
References ItemBase::m_modelPart, GraphicsUtils::mils2pixels(), ViewLayer::PCBView, resizeAux(), GraphicsUtils::SVGDPI, and ItemBase::viewID().
isPlural()
ItemBase::PluralType JumperItem::isPlural () virtual
Reimplemented from ItemBase.
References ItemBase::Singular.
loadLayerKin()
void JumperItem::loadLayerKin (const LayerHash & viewLayers, ViewLayer::ViewLayerPlacement viewLayerPlacement) virtual
Reimplemented from PaletteItem.
References PaletteItem::loadLayerKin(), resize(), and ItemBase::viewLayerPlacement().
makeSvg()
QString JumperItem::makeSvg (ViewLayer::ViewLayerID viewLayerID) protected
References ___emptyString___, Colors, ViewLayer::Copper0, Copper0LayerTemplate, ViewLayer::Copper1, m_connector0, m_connector1, m_connectorBR, m_connectorTL, makeWireImage(), ItemBase::modelPart(), ViewLayer::PartImage, GraphicsUtils::pixels2ins(), GraphicsUtils::pixels2mils(), ModelPart::setLocalProp(), ShadowColor, shorten(), ViewLayer::Silkscreen1, GraphicsUtils::StandardFritzingDPI, GraphicsUtils::SVGDPI, ItemBase::viewLayerID(), and ViewLayer::viewLayerXmlNameFromID().
mouseMoveEvent()
void JumperItem::mouseMoveEvent (QGraphicsSceneMouseEvent * event) protected
References alignMe(), m_connectorTL, m_dragItem, m_dragStartConnectorPos, m_dragStartScenePos, m_otherItem, m_otherPos, qMin(), resize(), and ItemBase::updateConnections().
mouseMoveEventK()
void JumperItem::mouseMoveEventK (PaletteItemBase * originalItem, QGraphicsSceneMouseEvent * event) virtual
Reimplemented from PaletteItemBase.
References mouseMoveEvent().
mousePressEvent()
void JumperItem::mousePressEvent (QGraphicsSceneMouseEvent * event) protected
References InfoGraphicsView::getInfoGraphicsView(), m_connector0, m_connector1, m_connectorBR, m_connectorTL, m_dragItem, m_dragStartCenterPos, m_dragStartConnectorPos, m_dragStartScenePos, m_dragStartThisPos, m_originalClickItem, m_otherItem, m_otherPos, PaletteItem::mousePressEvent(), ItemBase::mousePressEvent(), and InfoGraphicsView::spaceBarIsPressed().
mousePressEventK()
bool JumperItem::mousePressEventK (PaletteItemBase * originalItem, QGraphicsSceneMouseEvent * event) virtual
Reimplemented from PaletteItemBase.
References m_dragItem, m_originalClickItem, and mousePressEvent().
mouseReleaseEvent()
void JumperItem::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected
References m_dragItem, and PaletteItemBase::mouseReleaseEvent().
mouseReleaseEventK()
void JumperItem::mouseReleaseEventK (PaletteItemBase * originalItem, QGraphicsSceneMouseEvent * event) virtual
Reimplemented from PaletteItemBase.
References mouseReleaseEvent().
paintHover()
void JumperItem::paintHover (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) protected virtual
Reimplemented from ItemBase.
References hoverShape(), ItemBase::m_viewID, PaletteItemBase::paintHover(), ItemBase::paintHover(), and ViewLayer::PCBView.
paintSelected()
void JumperItem::paintSelected (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) protected virtual
Reimplemented from ItemBase.
References boundingRect(), hoverShape(), ItemBase::m_viewID, PaletteItemBase::paintSelected(), ViewLayer::PCBView, and GraphicsUtils::qt_graphicsItem_highlightSelected().
resize() [1/3]
void JumperItem::resize (QPointF pos, QPointF c0, QPointF c1)
References DebugDialog::debug(), and resizeAux().
resize() [2/3]
void JumperItem::resize (QPointF p0, QPointF p1)
References calcPos(), and resize().
resize() [3/3]
void JumperItem::resize () protected
References ViewLayer::Copper0, ViewLayer::Copper1, m_connector0, m_connector1, PaletteItem::m_layerKin, ItemBase::m_viewID, makeSvg(), ViewLayer::PartImage, ViewLayer::PCBView, ItemBase::prepareGeometryChange(), ItemBase::resetRenderer(), ViewLayer::Silkscreen1, and ItemBase::viewLayerID().
resizeAux()
void JumperItem::resizeAux (double r0x, double r0y, double r1x, double r1y) protected
References m_connector0, m_connector1, ItemBase::prepareGeometryChange(), and resize().
retrieveSvg()
QString JumperItem::retrieveSvg (ViewLayer::ViewLayerID viewLayerID, QHash< QString, QString > & svgHash, bool blackOnly, double dpi, double & factor) virtual
Reimplemented from ItemBase.
References ViewLayer::Copper0, ViewLayer::Copper1, makeSvg(), PaletteItemBase::normalizeSvg(), ViewLayer::PartImage, PaletteItemBase::retrieveSvg(), ViewLayer::Silkscreen1, and ItemBase::viewLayerID().
rotateEnds()
void JumperItem::rotateEnds (QTransform & rotation, QPointF & tc0, QPointF & tc1) protected
References m_connector0, and m_connector1.
rotateItem()
void JumperItem::rotateItem (double degrees, bool includeRatsnest) virtual
Reimplemented from ItemBase.
References resize(), and rotateEnds().
saveInstanceLocation()
void JumperItem::saveInstanceLocation (QXmlStreamWriter & streamWriter) virtual
Reimplemented from PaletteItemBase.
References ViewGeometry::flagsAsInt(), ViewGeometry::loc(), ItemBase::m_viewGeometry, GraphicsUtils::saveTransform(), and ViewGeometry::transform().
saveParams()
void JumperItem::saveParams ()
References m_connector0, m_connector1, m_itemC0, m_itemC1, and m_itemPos.
setAutoroutable()
void JumperItem::setAutoroutable (bool ar)
References ItemBase::m_viewGeometry, and ViewGeometry::setAutoroutable().
setUpImage()
bool JumperItem::setUpImage (ModelPart * modelPart, const LayerHash & viewLayers, LayerAttributes & layerAttributes) virtual
Reimplemented from PaletteItemBase.
References boundingRect(), ItemBase::cachedConnectorItems(), ConnectorItem::connectorSharedName(), LayerAttributes::doConnectors, initialResize(), m_connector0, m_connector1, m_connectorBR, m_connectorTL, ItemBase::modelPart(), NonConnectorItem::setCircular(), PaletteItemBase::setUpImage(), and LayerAttributes::viewID.
shape()
QPainterPath JumperItem::shape () const
References hoverShape().
useViewIDForPixmap()
ViewLayer::ViewID JumperItem::useViewIDForPixmap (ViewLayer::ViewID vid, bool swappingEnabled) protected virtual
Reimplemented from ItemBase.
References ViewLayer::IconView, ViewLayer::PCBView, and ViewLayer::UnknownView.
Member Data Documentation
m_connector0
QPointer<ConnectorItem> JumperItem::m_connector0 protected
m_connector1
QPointer<ConnectorItem> JumperItem::m_connector1 protected
m_connectorBR
QPointF JumperItem::m_connectorBR protected
m_connectorTL
QPointF JumperItem::m_connectorTL protected
m_dragItem
QPointer<ConnectorItem> JumperItem::m_dragItem protected
m_dragStartCenterPos
QPointF JumperItem::m_dragStartCenterPos protected
m_dragStartConnectorPos
QPointF JumperItem::m_dragStartConnectorPos protected
m_dragStartScenePos
QPointF JumperItem::m_dragStartScenePos protected
m_dragStartThisPos
QPointF JumperItem::m_dragStartThisPos protected
m_itemC0
QPointF JumperItem::m_itemC0 protected
m_itemC1
QPointF JumperItem::m_itemC1 protected
m_itemPos
QPointF JumperItem::m_itemPos protected
m_originalClickItem
QPointer<PaletteItemBase> JumperItem::m_originalClickItem protected
m_otherItem
QPointer<ConnectorItem> JumperItem::m_otherItem protected
m_otherPos
QPointF JumperItem::m_otherPos protected
The documentation for this class was generated from the following files:
items/jumperitem.h
items/jumperitem.cpp