Fritzing: AbstractEditableLabelWidget Class Reference
AbstractEditableLabelWidget Class Reference abstract
#include <abstracteditablelabelwidget.h>
Signals
void editionCompleted (QString text)
void editionFinished ()
void editionStarted ()
Public Member Functions
AbstractEditableLabelWidget (QString text, WaitPushUndoStack *undoStack, QWidget *parent=0, QString title="", bool edited=false, bool noSpacing=false)
QString text ()
Protected Slots
void editionCanceled ()
void editionStarted (QString text)
void informEditionCompleted ()
Protected Member Functions
virtual QString editionText ()=0
virtual QWidget * myEditionWidget ()=0
virtual void setEditionText (QString text)=0
virtual void setEmptyTextToEdit ()=0
void setNoSpacing (QLayout *layout)
void toEditionMode ()
void toStandardMode ()
Protected Attributes
QPushButton * m_acceptButton
QPushButton * m_cancelButton
bool m_edited
volatile bool m_isInEditionMode
EditableLabel * m_label
bool m_noSpacing
QLabel * m_title
class WaitPushUndoStack * m_undoStack
Constructor & Destructor Documentation
AbstractEditableLabelWidget()
AbstractEditableLabelWidget::AbstractEditableLabelWidget (QString text, WaitPushUndoStack * undoStack, QWidget * parent = 0, QString title = "", bool edited = false, bool noSpacing = false)
References editionCanceled(), editionCompleted(), editionStarted(), informEditionCompleted(), m_acceptButton, m_cancelButton, m_edited, m_isInEditionMode, m_label, m_noSpacing, m_title, m_undoStack, and text().
Member Function Documentation
editionCanceled
void AbstractEditableLabelWidget::editionCanceled () protected slot
References toStandardMode().
editionCompleted
void AbstractEditableLabelWidget::editionCompleted (QString text) signal
editionFinished
void AbstractEditableLabelWidget::editionFinished () signal
editionStarted [1/2]
void AbstractEditableLabelWidget::editionStarted (QString text) protected slot
References setEditionText(), text(), and toEditionMode().
editionStarted [2/2]
void AbstractEditableLabelWidget::editionStarted () signal
editionText()
virtual QString AbstractEditableLabelWidget::editionText () protected pure virtual
Implemented in EditableLineWidget, EditableDateWidget, and EditableTextWidget.
informEditionCompleted
void AbstractEditableLabelWidget::informEditionCompleted () protected slot
References editionCompleted(), editionText(), m_edited, m_isInEditionMode, m_undoStack, WaitPushUndoStack::push(), and toStandardMode().
myEditionWidget()
virtual QWidget* AbstractEditableLabelWidget::myEditionWidget () protected pure virtual
Implemented in EditableLineWidget, EditableDateWidget, and EditableTextWidget.
setEditionText()
virtual void AbstractEditableLabelWidget::setEditionText (QString text) protected pure virtual
Implemented in EditableLineWidget, EditableDateWidget, and EditableTextWidget.
setEmptyTextToEdit()
virtual void AbstractEditableLabelWidget::setEmptyTextToEdit () protected pure virtual
Implemented in EditableLineWidget, EditableDateWidget, and EditableTextWidget.
setNoSpacing()
void AbstractEditableLabelWidget::setNoSpacing (QLayout * layout) protected
References m_noSpacing.
text()
QString AbstractEditableLabelWidget::text ()
References ___emptyString___, m_edited, and m_label.
toEditionMode()
void AbstractEditableLabelWidget::toEditionMode () protected
References editionStarted(), m_acceptButton, m_cancelButton, m_edited, m_isInEditionMode, m_label, myEditionWidget(), setEmptyTextToEdit(), and setNoSpacing().
toStandardMode()
void AbstractEditableLabelWidget::toStandardMode () protected
References editionFinished(), m_acceptButton, m_cancelButton, m_isInEditionMode, m_label, myEditionWidget(), and setNoSpacing().
Member Data Documentation
m_acceptButton
QPushButton* AbstractEditableLabelWidget::m_acceptButton protected
m_cancelButton
QPushButton* AbstractEditableLabelWidget::m_cancelButton protected
m_edited
bool AbstractEditableLabelWidget::m_edited protected
m_isInEditionMode
volatile bool AbstractEditableLabelWidget::m_isInEditionMode protected
m_label
EditableLabel* AbstractEditableLabelWidget::m_label protected
m_noSpacing
bool AbstractEditableLabelWidget::m_noSpacing protected
m_title
QLabel* AbstractEditableLabelWidget::m_title protected
m_undoStack
class WaitPushUndoStack* AbstractEditableLabelWidget::m_undoStack protected
The documentation for this class was generated from the following files:
partseditor/obsolete/abstracteditablelabelwidget.h
partseditor/obsolete/abstracteditablelabelwidget.cpp