Fritzing: LayerPalette Class Reference
LayerPalette Class Reference
#include <layerpalette.h>
Public Member Functions
LayerPalette (QWidget *parent=nullptr)
~LayerPalette ()=default
void resetLayout (LayerHash &viewLayers, LayerList &keys)
void setHideAllLayersAction (QAction *)
void setShowAllLayersAction (QAction *)
void updateLayerPalette (LayerHash &viewLayers, LayerList &keys)
Protected Slots
void setAllLayersVisible (bool vis)
void setLayerVisibility (bool vis)
Protected Attributes
QList< ViewLayerCheckBox * > m_checkBoxes
QGroupBox * m_groupBox
QAction * m_hideAllLayersAct
QVBoxLayout * m_mainLayout
QAction * m_showAllLayersAct
QCheckBox * m_showAllWidget
Constructor & Destructor Documentation
LayerPalette()
LayerPalette::LayerPalette (QWidget * parent = nullptr)
References m_checkBoxes, m_groupBox, m_mainLayout, m_showAllWidget, setAllLayersVisible(), setLayerVisibility(), and ViewLayer::ViewLayerCount.
~LayerPalette()
LayerPalette::~LayerPalette () default
Member Function Documentation
resetLayout()
void LayerPalette::resetLayout (LayerHash & viewLayers, LayerList & keys)
References ViewLayer::action(), m_checkBoxes, m_groupBox, m_mainLayout, and ViewLayerCheckBox::setViewLayer().
setAllLayersVisible
void LayerPalette::setAllLayersVisible (bool vis) protected slot
References m_hideAllLayersAct, and m_showAllLayersAct.
setHideAllLayersAction()
void LayerPalette::setHideAllLayersAction (QAction * action)
References m_hideAllLayersAct.
setLayerVisibility
void LayerPalette::setLayerVisibility (bool vis) protected slot
References ViewLayer::action(), ViewLayer::setIncludeChildLayers(), and ViewLayerCheckBox::viewLayer().
setShowAllLayersAction()
void LayerPalette::setShowAllLayersAction (QAction * action)
References m_showAllLayersAct.
updateLayerPalette()
void LayerPalette::updateLayerPalette (LayerHash & viewLayers, LayerList & keys)
References ViewLayer::action(), m_checkBoxes, m_hideAllLayersAct, m_showAllLayersAct, and m_showAllWidget.
Member Data Documentation
m_checkBoxes
QList<ViewLayerCheckBox *> LayerPalette::m_checkBoxes protected
m_groupBox
QGroupBox* LayerPalette::m_groupBox protected
m_hideAllLayersAct
QAction* LayerPalette::m_hideAllLayersAct protected
m_mainLayout
QVBoxLayout* LayerPalette::m_mainLayout protected
m_showAllLayersAct
QAction* LayerPalette::m_showAllLayersAct protected
m_showAllWidget
QCheckBox* LayerPalette::m_showAllWidget protected
The documentation for this class was generated from the following files:
dock/layerpalette.h
dock/layerpalette.cpp