Fritzing: ProgramWindow Class Reference
ProgramWindow Class Reference
#include <programwindow.h>
Public Slots
void saveAll ()
Signals
void changeActivationSignal (bool activate, QWidget *originator)
void closed ()
void linkToProgramFile (const QString &filename, Platform *platform, bool addlink, bool strong)
Signals inherited from FritzingWindow
void readOnlyChanged (bool isReadOnly)
Public Member Functions
ProgramWindow (QWidget *parent=0)
~ProgramWindow ()
bool alreadyHasProgram (const QString &)
void createViewMenuActions (QList< QAction * > &)
const QString defaultSaveFolder ()
QList< Platform * > getAvailablePlatforms ()
const QMap< QString, QString > getBoards ()
Platform * getPlatformByName (const QString &platformName)
QList< QSerialPortInfo > getSerialPorts ()
bool hasPlatform (const QString &platformName)
bool hasPort (const QString &portName)
void initMenus (QMenuBar *menubar)
void linkFiles (const QList< LinkedFile * > &, const QString &alternativePath)
void loadProgramFileNew ()
void print ()
void setup ()
void showMenus (bool)
void updateLink (const QString &filename, Platform *platform, bool addlink, bool strong)
Public Member Functions inherited from FritzingWindow
FritzingWindow (const QString &untitledFileName, int &untitledFileCount, QString fileExt, QWidget *parent=0, Qt::WindowFlags f=0)
const QString & fileName ()
virtual void notClosableForAWhile ()
void setFileName (const QString &)
Public Member Functions inherited from Bundler
virtual ~Bundler ()
virtual bool loadBundledAux (QDir &dir, QList< class ModelPart * > mps)
virtual bool preloadBundledAux (QDir &dir, bool dontAsk)
Public Attributes
QAction * m_monitorAction
QAction * m_newAction
QAction * m_openAction
QAction * m_programAction
QAction * m_saveAction
Static Public Attributes
static const QString LocateName
Static Public Attributes inherited from FritzingWindow
static const QString QtFunkyPlaceholder = QLatin1String("[*]")
static QString ReadOnlyPlaceholder
Protected Slots
class ProgramTab * addTab ()
void closeCurrentTab ()
void closeTab (int index)
void copy ()
void cut ()
void duplicateTab ()
void loadProgramFile ()
void paste ()
void portProcessFinished (int exitCode, QProcess::ExitStatus exitStatus)
void portProcessReadyRead ()
void redo ()
void rename ()
void saveCurrentTab ()
void selectAll ()
void sendProgram ()
void serialMonitor ()
void setBoard (QAction *)
void setPlatform (QAction *)
void setPort (QAction *)
void tabBeforeClosing (int, bool &ok)
void tabDelete (int index, bool deleteFile)
void tabRename (int)
void tabSave (int)
void tabSaveAs (int)
void undo ()
void updateBoards ()
void updateMenu (bool programEnable, bool undoEnable, bool redoEnable, bool cutEnable, bool copyEnable, bool pasteEnable, Platform *platform, const QString &port, const QString &board, const QString &filename)
void updateSerialPorts ()
Protected Slots inherited from FritzingWindow
virtual bool save ()
virtual bool saveAs ()
void undoStackCleanChanged (bool isClean)
Protected Member Functions
QAction * addBoard (const QString &name, const QString &definition)
QAction * addPort (QSerialPortInfo port)
bool beforeClosing (bool showCancel, bool &discard)
bool beforeClosingTab (int index, bool showCancel)
void cleanUp ()
void closeEvent (QCloseEvent *event)
QFrame * createCenter ()
QFrame * createHeader ()
ProgramTab * currentWidget ()
bool event (QEvent *event)
bool eventFilter (QObject *object, QEvent *event)
const QString fileExtension ()
QStringList getExtensions ()
QString getExtensionString ()
QStringList getSerialPortsAux ()
ProgramTab * indexWidget (int index)
bool prepSave (class ProgramTab *, bool saveAsFlag)
bool saveAsAux (const QString &fileName)
void setTitle ()
void setTitle (const QString &filename)
int & untitledFileCount ()
const QString untitledFileName ()
Protected Member Functions inherited from FritzingWindow
virtual bool anyModified ()
QMessageBox::StandardButton beforeClosingMessage (const QString &filename, bool showCancel)
void createCloseAction ()
virtual const QString fritzingTitle ()
bool save (const QString &filename, bool readOnly)
bool saveAs (const QString &filename, bool readOnly)
virtual void setBeforeClosingText (const QString &filename, QMessageBox &messageBox)
void setReadOnly (bool readOnly)
Static Protected Member Functions
static void initPlatforms ()
Protected Attributes
QPointer< QPushButton > m_addButton
QActionGroup * m_boardActionGroup
QMap< QString, QAction * > m_boardActions
QMenu * m_boardMenu
QAction * m_copyAction
QAction * m_cutAction
QMenu * m_editMenu
QAction * m_pasteAction
QActionGroup * m_platformActionGroup
QMap< Platform *, QAction * > m_platformActions
QMenu * m_platformMenu
QMap< QString, QAction * > m_portActions
QStringList m_ports
QAction * m_preferencesAction
QAction * m_printAction
QMenu * m_programMenu
QAction * m_redoAction
QPointer< class ProgramTab > m_savingProgramTab
QAction * m_selectAction
QActionGroup * m_serialPortActionGroup
QMenu * m_serialPortMenu
QPointer< PTabWidget > m_tabWidget
QAction * m_undoAction
QMenu * m_viewMenu
QList< QAction * > m_viewMenuActions
Protected Attributes inherited from FritzingWindow
QAction * m_closeAct = nullptr
QString m_fwFilename
bool m_readOnly = false
QStatusBar * m_statusBar = nullptr
QDir m_tempDir
class WaitPushUndoStack * m_undoStack = nullptr
Static Protected Attributes
static QList< Platform * > m_platforms
Static Protected Attributes inherited from FritzingWindow
static QStringList OtherKnownExtensions
Additional Inherited Members
Static Public Member Functions inherited from FritzingWindow
static bool alreadyHasExtension (const QString &fileName, const QString &extension=___emptyString___)
Constructor & Destructor Documentation
ProgramWindow()
ProgramWindow::ProgramWindow (QWidget * parent = 0)
References initPlatforms(), m_platforms, m_savingProgramTab, setTitle(), and UntitledIndex.
~ProgramWindow()
ProgramWindow::~ProgramWindow ()
Member Function Documentation
addBoard()
QAction * ProgramWindow::addBoard (const QString & name, const QString & definition) protected
References m_boardActionGroup, m_boardActions, and m_boardMenu.
addPort()
QAction * ProgramWindow::addPort (QSerialPortInfo port) protected
References m_portActions, m_serialPortActionGroup, and m_serialPortMenu.
addTab
ProgramTab * ProgramWindow::addTab () protected slot
Create and open a new tab within the PTabWidget child. This function handled connecting all the appropriate signals and setting an appropriate filename.
References ProgramTab::initMenus(), m_tabWidget, tabDelete(), tabRename(), tabSave(), tabSaveAs(), untitledFileName(), UntitledIndex, and updateMenu().
alreadyHasProgram()
bool ProgramWindow::alreadyHasProgram (const QString & filename)
References DebugDialog::debug(), ProgramTab::filename(), indexWidget(), and m_tabWidget.
beforeClosing()
bool ProgramWindow::beforeClosing (bool showCancel, bool & discard) protected virtual
Reimplemented from FritzingWindow.
References beforeClosingTab(), and m_tabWidget.
beforeClosingTab()
bool ProgramWindow::beforeClosingTab (int index, bool showCancel) protected
References FritzingWindow::beforeClosingMessage(), ProgramTab::filename(), indexWidget(), ProgramTab::isModified(), and prepSave().
changeActivationSignal
void ProgramWindow::changeActivationSignal (bool activate, QWidget * originator) signal
cleanUp()
void ProgramWindow::cleanUp () protected
closeCurrentTab
void ProgramWindow::closeCurrentTab () protected slot
A function for closing the current displayed tab. I'm using a ProgramWindow method instead of calling deleteTab() directly as I believe it's more apropos.
References closeTab(), and m_tabWidget.
closed
void ProgramWindow::closed () signal
closeEvent()
void ProgramWindow::closeEvent (QCloseEvent * event) protected
Reimplement closeEvent to save any modified documents before closing.
References beforeClosing(), cleanUp(), closed(), and event().
closeTab
void ProgramWindow::closeTab (int index) protected slot
References ProgramTab::deleteTab(), ProgramTab::filename(), indexWidget(), and linkToProgramFile().
copy
void ProgramWindow::copy () protected slot
References ProgramTab::copy(), and currentWidget().
createCenter()
QFrame * ProgramWindow::createCenter () protected
References closeTab(), and m_tabWidget.
createHeader()
QFrame * ProgramWindow::createHeader () protected
createViewMenuActions()
void ProgramWindow::createViewMenuActions (QList< QAction * > & actions)
References m_viewMenuActions.
currentWidget()
ProgramTab * ProgramWindow::currentWidget () inline protected
References m_tabWidget.
cut
void ProgramWindow::cut () protected slot
References currentWidget(), and ProgramTab::cut().
defaultSaveFolder()
const QString ProgramWindow::defaultSaveFolder () virtual
Implements FritzingWindow.
References FolderUtils::openSaveFolder().
duplicateTab
void ProgramWindow::duplicateTab () protected slot
References addTab(), currentWidget(), ProgramTab::setText(), and ProgramTab::text().
event()
bool ProgramWindow::event (QEvent * event) protected
References changeActivationSignal().
eventFilter()
bool ProgramWindow::eventFilter (QObject * object, QEvent * event) protected
eventFilter here is used to catch the keyboard shortcuts that trigger the close event for ProgramWindow. If there are more than one tab widget the standard close shortcut should only close the current tab instead of closing the whole window. Every other case is ignored and handled by closeEvent() like normal.
References event(), and m_tabWidget.
fileExtension()
const QString ProgramWindow::fileExtension () protected virtual
Implements FritzingWindow.
getAvailablePlatforms()
QList< Platform * > ProgramWindow::getAvailablePlatforms ()
References m_platforms.
getBoards()
const QMap< QString, QString > ProgramWindow::getBoards ()
References currentWidget(), Platform::getBoards(), and ProgramTab::platform().
getExtensions()
QStringList ProgramWindow::getExtensions () protected virtual
Implements FritzingWindow.
References currentWidget(), and ProgramTab::extensions().
getExtensionString()
QString ProgramWindow::getExtensionString () protected virtual
Implements FritzingWindow.
References currentWidget(), and ProgramTab::extensionString().
getPlatformByName()
Platform * ProgramWindow::getPlatformByName (const QString & platformName)
References getAvailablePlatforms(), and Platform::getName().
getSerialPorts()
QList< QSerialPortInfo > ProgramWindow::getSerialPorts ()
getSerialPortsAux()
QStringList ProgramWindow::getSerialPortsAux () protected
hasPlatform()
bool ProgramWindow::hasPlatform (const QString & platformName)
References getPlatformByName().
hasPort()
bool ProgramWindow::hasPort (const QString & portName)
References getSerialPorts().
indexWidget()
ProgramTab * ProgramWindow::indexWidget (int index) inline protected
References m_tabWidget.
initMenus()
void ProgramWindow::initMenus (QMenuBar * menubar)
References addTab(), closeCurrentTab(), copy(), cut(), getAvailablePlatforms(), Platform::getName(), loadProgramFile(), m_boardActionGroup, m_boardMenu, m_copyAction, m_cutAction, m_editMenu, m_monitorAction, m_newAction, m_openAction, m_pasteAction, m_platformActionGroup, m_platformActions, m_platformMenu, m_preferencesAction, m_programAction, m_programMenu, m_redoAction, m_saveAction, m_selectAction, m_serialPortActionGroup, m_serialPortMenu, m_undoAction, m_viewMenu, m_viewMenuActions, paste(), redo(), rename(), saveCurrentTab(), selectAll(), sendProgram(), serialMonitor(), setBoard(), setPlatform(), setPort(), undo(), and updateSerialPorts().
initPlatforms()
void ProgramWindow::initPlatforms () static protected
References FolderUtils::getApplicationSubFolderPath(), Highlighter::loadStyles(), and m_platforms.
linkFiles()
void ProgramWindow::linkFiles (const QList< LinkedFile * > & linkedFiles, const QString & alternativePath)
References addTab(), ProgramTab::appendToConsole(), LinkedFile::fileFlags, hasPlatform(), LinkedFile::InBundleFlag, indexWidget(), LinkedFile::linkedFilename, ProgramTab::loadProgramFile(), LinkedFile::platform, LinkedFile::ReadOnlyFlag, LinkedFile::SameMachineFlag, and ProgramTab::setPlatform().
linkToProgramFile
void ProgramWindow::linkToProgramFile (const QString & filename, Platform * platform, bool addlink, bool strong) signal
loadProgramFile
void ProgramWindow::loadProgramFile () protected slot
References currentWidget(), DebugDialog::debug(), and ProgramTab::loadProgramFile().
loadProgramFileNew()
void ProgramWindow::loadProgramFileNew ()
References addTab(), and ProgramTab::loadProgramFile().
paste
void ProgramWindow::paste () protected slot
References currentWidget(), and ProgramTab::paste().
portProcessFinished
void ProgramWindow::portProcessFinished (int exitCode, QProcess::ExitStatus exitStatus) protected slot
References DebugDialog::debug().
portProcessReadyRead
void ProgramWindow::portProcessReadyRead () protected slot
References m_ports.
prepSave()
bool ProgramWindow::prepSave (class ProgramTab * programTab, bool saveAsFlag) protected
References ProgramTab::filename(), ProgramTab::isModified(), linkToProgramFile(), m_savingProgramTab, ProgramTab::platform(), ProgramTab::readOnly(), FritzingWindow::save(), FritzingWindow::saveAs(), and ProgramTab::setClean().
print()
void ProgramWindow::print ()
References currentWidget(), and ProgramTab::print().
redo
void ProgramWindow::redo () protected slot
References currentWidget(), and ProgramTab::redo().
rename
void ProgramWindow::rename () protected slot
References currentWidget(), and ProgramTab::rename().
saveAll
void ProgramWindow::saveAll () slot
References m_tabWidget, and tabSave().
saveAsAux()
bool ProgramWindow::saveAsAux (const QString & fileName) protected virtual
Implements FritzingWindow.
References FritzingWindow::fileName(), and m_savingProgramTab.
saveCurrentTab
void ProgramWindow::saveCurrentTab () protected slot
References m_tabWidget, and tabSave().
selectAll
void ProgramWindow::selectAll () protected slot
References currentWidget(), and ProgramTab::selectAll().
sendProgram
void ProgramWindow::sendProgram () protected slot
References currentWidget(), and ProgramTab::sendProgram().
serialMonitor
void ProgramWindow::serialMonitor () protected slot
References currentWidget(), and ProgramTab::serialMonitor().
setBoard
void ProgramWindow::setBoard (QAction * action) protected slot
References currentWidget(), and ProgramTab::setBoard().
setPlatform
void ProgramWindow::setPlatform (QAction * action) protected slot
References currentWidget(), and ProgramTab::setPlatform().
setPort
void ProgramWindow::setPort (QAction * action) protected slot
References currentWidget(), and ProgramTab::setPort().
setTitle() [1/2]
void ProgramWindow::setTitle () protected virtual
Reimplemented from FritzingWindow.
setTitle() [2/2]
void ProgramWindow::setTitle (const QString & filename) protected
setup()
void ProgramWindow::setup ()
References createCenter(), and createHeader().
showMenus()
void ProgramWindow::showMenus (bool show)
References m_copyAction, m_cutAction, m_editMenu, m_pasteAction, m_programMenu, m_redoAction, m_selectAction, m_undoAction, and m_viewMenu.
tabBeforeClosing
void ProgramWindow::tabBeforeClosing (int index, bool & ok) protected slot
References beforeClosingTab().
tabDelete
void ProgramWindow::tabDelete (int index, bool deleteFile) protected slot
References addTab(), ProgramTab::filename(), indexWidget(), and m_tabWidget.
tabRename
void ProgramWindow::tabRename (int index) protected slot
References ProgramTab::filename(), indexWidget(), linkToProgramFile(), and prepSave().
tabSave
void ProgramWindow::tabSave (int index) protected slot
References indexWidget(), and prepSave().
tabSaveAs
void ProgramWindow::tabSaveAs (int index) protected slot
References indexWidget(), and prepSave().
undo
void ProgramWindow::undo () protected slot
References currentWidget(), and ProgramTab::undo().
untitledFileCount()
int & ProgramWindow::untitledFileCount () protected virtual
Implements FritzingWindow.
References UntitledIndex.
untitledFileName()
const QString ProgramWindow::untitledFileName () protected virtual
Implements FritzingWindow.
updateBoards
void ProgramWindow::updateBoards () protected slot
References addBoard(), getBoards(), m_boardActionGroup, m_boardActions, and m_boardMenu.
updateLink()
void ProgramWindow::updateLink (const QString & filename, Platform * platform, bool addlink, bool strong)
References DebugDialog::debug(), and linkToProgramFile().
updateMenu
void ProgramWindow::updateMenu (bool programEnable, bool undoEnable, bool redoEnable, bool cutEnable, bool copyEnable, bool pasteEnable, Platform * platform, const QString & port, const QString & board, const QString & filename) protected slot
This slot is for updating the tab-dependent menu items.
program
undo/redo
cut/copy
References currentWidget(), ProgramTab::isModified(), m_boardActions, m_copyAction, m_cutAction, m_monitorAction, m_pasteAction, m_platformActions, m_portActions, m_programAction, m_redoAction, m_saveAction, m_undoAction, and setTitle().
updateSerialPorts
void ProgramWindow::updateSerialPorts () protected slot
References addPort(), getSerialPorts(), m_portActions, m_serialPortActionGroup, and m_serialPortMenu.
Member Data Documentation
LocateName
const QString ProgramWindow::LocateName static
m_addButton
QPointer<QPushButton> ProgramWindow::m_addButton protected
m_boardActionGroup
QActionGroup* ProgramWindow::m_boardActionGroup protected
m_boardActions
QMap<QString, QAction *> ProgramWindow::m_boardActions protected
m_boardMenu
QMenu* ProgramWindow::m_boardMenu protected
m_copyAction
QAction* ProgramWindow::m_copyAction protected
m_cutAction
QAction* ProgramWindow::m_cutAction protected
m_editMenu
QMenu* ProgramWindow::m_editMenu protected
m_monitorAction
QAction* ProgramWindow::m_monitorAction
m_newAction
QAction* ProgramWindow::m_newAction
m_openAction
QAction* ProgramWindow::m_openAction
m_pasteAction
QAction* ProgramWindow::m_pasteAction protected
m_platformActionGroup
QActionGroup* ProgramWindow::m_platformActionGroup protected
m_platformActions
QMap<Platform *, QAction *> ProgramWindow::m_platformActions protected
m_platformMenu
QMenu* ProgramWindow::m_platformMenu protected
m_platforms
QList< Platform * > ProgramWindow::m_platforms static protected
m_portActions
QMap<QString, QAction *> ProgramWindow::m_portActions protected
m_ports
QStringList ProgramWindow::m_ports protected
m_preferencesAction
QAction* ProgramWindow::m_preferencesAction protected
m_printAction
QAction* ProgramWindow::m_printAction protected
m_programAction
QAction* ProgramWindow::m_programAction
m_programMenu
QMenu* ProgramWindow::m_programMenu protected
m_redoAction
QAction* ProgramWindow::m_redoAction protected
m_saveAction
QAction* ProgramWindow::m_saveAction
m_savingProgramTab
QPointer<class ProgramTab> ProgramWindow::m_savingProgramTab protected
m_selectAction
QAction* ProgramWindow::m_selectAction protected
m_serialPortActionGroup
QActionGroup* ProgramWindow::m_serialPortActionGroup protected
m_serialPortMenu
QMenu* ProgramWindow::m_serialPortMenu protected
m_tabWidget
QPointer<PTabWidget> ProgramWindow::m_tabWidget protected
m_undoAction
QAction* ProgramWindow::m_undoAction protected
m_viewMenu
QMenu* ProgramWindow::m_viewMenu protected
m_viewMenuActions
QList<QAction *> ProgramWindow::m_viewMenuActions protected
The documentation for this class was generated from the following files:
program/programwindow.h
program/programwindow.cpp