Fritzing: autoroute/cmrouter/cmrouter.cpp File Reference
cmrouter.cpp File Reference
#include "cmrouter.h"
#include "../../sketch/pcbsketchwidget.h"
#include "../../debugdialog.h"
#include "../../items/virtualwire.h"
#include "../../items/tracewire.h"
#include "../../items/jumperitem.h"
#include "../../items/via.h"
#include "../../items/resizableboard.h"
#include "../../utils/graphicsutils.h"
#include "../../utils/graphutils.h"
#include "../../utils/textutils.h"
#include "../../connectors/connectoritem.h"
#include "../../items/moduleidnames.h"
#include "../../processeventblocker.h"
#include "../../svg/groundplanegenerator.h"
#include "../../svg/svgfilesplitter.h"
#include "../../fsvgrenderer.h"
#include "tile.h"
#include "tileutils.h"
#include <qmath.h>
#include <limits>
#include <QApplication>
#include <QMessageBox>
#include <QSettings>
#include <QCryptographicHash>
Macros
#define DGI(item) drawGridItem(item)
Functions
int checkAlready (Tile *tile, UserData userData)
static double dot (const QPointF &p1, const QPointF &p2)
void extendToBounds (TileRect &from, TileRect &to)
static void infoTile (const QString &message, Tile *tile)
static void infoTileRect (const QString &message, const TileRect &tileRect)
static int manhattan (TileRect &tr1, TileRect &tr2)
int prepDeleteTile (Tile *tile, UserData userData)
static GridEntry * TiGetGridEntry (Tile *tile)
bool tilePointRectXLessThan (TilePointRect *tpr1, TilePointRect *tpr2)
bool tilePointRectYGreaterThan (TilePointRect *tpr1, TilePointRect *tpr2)
Variables
static const double CloseEnough = 0.5
static const int DefaultMaxCycles = 10
static const int GridEntryAlpha = 128
static double HalfStandardWireWidth = 0
static const int MaximumProgress = 1000
static double StandardWireWidth = 0
static int TileHalfStandardWireWidth = 0
static int TileStandardWireWidth = 0
Macro Definition Documentation
DGI
#define DGI (item) drawGridItem(item)
Function Documentation
checkAlready()
int checkAlready (Tile * tile, UserData userData)
References Tile::BUFFER, Tile::SCHEMATICWIRESPACE, Tile::SPACE, Tile::SPACE2, and TiGetType().
dot()
static double dot (const QPointF & p1, const QPointF & p2) inline static
extendToBounds()
void extendToBounds (TileRect & from, TileRect & to)
References TileRect::xmaxi, TileRect::xmini, TileRect::ymaxi, and TileRect::ymini.
infoTile()
static void infoTile (const QString & message, Tile * tile) inline static
References DebugDialog::debug(), HEIGHT, LEFT(), TiGetBody(), TiGetType(), WIDTH(), and YMIN().
infoTileRect()
static void infoTileRect (const QString & message, const TileRect & tileRect) inline static
References DebugDialog::debug(), TileRect::xmaxi, TileRect::xmini, TileRect::ymaxi, and TileRect::ymini.
manhattan()
static int manhattan (TileRect & tr1, TileRect & tr2) inline static
References qMin(), TileRect::xmaxi, TileRect::xmini, TileRect::ymaxi, and TileRect::ymini.
prepDeleteTile()
int prepDeleteTile (Tile * tile, UserData userData)
References Tile::DUMMYBOTTOM, Tile::DUMMYLEFT, Tile::DUMMYRIGHT, Tile::DUMMYTOP, and TiGetType().
TiGetGridEntry()
static GridEntry* TiGetGridEntry (Tile * tile) inline static
References TiGetClient().
tilePointRectXLessThan()
bool tilePointRectXLessThan (TilePointRect * tpr1, TilePointRect * tpr2)
References TilePointRect::tilePoint, and TilePoint::xi.
tilePointRectYGreaterThan()
bool tilePointRectYGreaterThan (TilePointRect * tpr1, TilePointRect * tpr2)
References TilePointRect::tilePoint, and TilePoint::yi.
Variable Documentation
CloseEnough
const double CloseEnough = 0.5 static
DefaultMaxCycles
const int DefaultMaxCycles = 10 static
GridEntryAlpha
const int GridEntryAlpha = 128 static
HalfStandardWireWidth
double HalfStandardWireWidth = 0 static
MaximumProgress
const int MaximumProgress = 1000 static
StandardWireWidth
double StandardWireWidth = 0 static
TileHalfStandardWireWidth
int TileHalfStandardWireWidth = 0 static
TileStandardWireWidth
int TileStandardWireWidth = 0 static