Fritzing: ConnectorTypeWidget Class Reference
ConnectorTypeWidget Class Reference
#include <singleconnectorinfowidget.h>
Public Member Functions
ConnectorTypeWidget (Connector::ConnectorType type=Connector::Female, QWidget *parent=0)
void cancel ()
void setInEditionMode (bool edition)
void setSelected (bool selected)
void setType (Connector::ConnectorType type)
Connector::ConnectorType type ()
const QString & typeAsStr ()
Protected Slots
void toggleValue ()
Protected Member Functions
void setText (const QString &text)
const QString & text ()
Protected Attributes
QPushButton * m_editionModeWidget
volatile bool m_isInEditionMode
bool m_isSelected
QLabel * m_noEditionModeWidget
QString m_text
Connector::ConnectorType m_typeBackUp
Constructor & Destructor Documentation
ConnectorTypeWidget()
ConnectorTypeWidget::ConnectorTypeWidget (Connector::ConnectorType type = Connector::Female, QWidget * parent = 0)
References m_editionModeWidget, m_isSelected, m_noEditionModeWidget, setType(), toggleValue(), and type().
Member Function Documentation
cancel()
void ConnectorTypeWidget::cancel ()
References m_typeBackUp, and setType().
setInEditionMode()
void ConnectorTypeWidget::setInEditionMode (bool edition)
References m_editionModeWidget, m_isInEditionMode, and m_noEditionModeWidget.
setSelected()
void ConnectorTypeWidget::setSelected (bool selected)
References m_isSelected.
setText()
void ConnectorTypeWidget::setText (const QString & text) protected
References m_editionModeWidget, m_noEditionModeWidget, m_text, and text().
setType()
void ConnectorTypeWidget::setType (Connector::ConnectorType type)
References Connector::connectorNameFromType(), Connector::Female, FemaleSymbolString, m_isInEditionMode, m_typeBackUp, Connector::Male, MaleSymbolString, Connector::Pad, PadString, setText(), and type().
text()
const QString & ConnectorTypeWidget::text () protected
References m_text.
toggleValue
void ConnectorTypeWidget::toggleValue () protected slot
References Connector::Female, m_isInEditionMode, m_isSelected, Connector::Male, Connector::Pad, setType(), and type().
type()
Connector::ConnectorType ConnectorTypeWidget::type ()
References Connector::connectorTypeFromName(), FemaleSymbolString, MaleSymbolString, PadString, text(), and Connector::Unknown.
typeAsStr()
const QString & ConnectorTypeWidget::typeAsStr ()
References Connector::connectorNameFromType(), and type().
Member Data Documentation
m_editionModeWidget
QPushButton* ConnectorTypeWidget::m_editionModeWidget protected
m_isInEditionMode
volatile bool ConnectorTypeWidget::m_isInEditionMode protected
m_isSelected
bool ConnectorTypeWidget::m_isSelected protected
m_noEditionModeWidget
QLabel* ConnectorTypeWidget::m_noEditionModeWidget protected
m_text
QString ConnectorTypeWidget::m_text protected
m_typeBackUp
Connector::ConnectorType ConnectorTypeWidget::m_typeBackUp protected
The documentation for this class was generated from the following files:
partseditor/obsolete/singleconnectorinfowidget.h
partseditor/obsolete/singleconnectorinfowidget.cpp