Fritzing: FSplashScreen Class Reference
FSplashScreen Class Reference
#include <fsplashscreen.h>
Public Slots
void displaySlice ()
Public Member Functions
FSplashScreen (const QPixmap &pixmap=QPixmap(), Qt::WindowFlags f=0)
~FSplashScreen ()
void showMessage (const QString &message, const QString &id, int alignment=Qt::AlignLeft)
int showPixmap (const QPixmap &pixmap, const QString &id)
void showProgress (int index, double progress)
Protected Member Functions
void drawContents (QPainter *painter)
Protected Attributes
QHash< QString, MessageThing * > m_items
QList< MessageThing * > m_messages
QPixmap m_pixmap
QList< PixmapThing * > m_pixmaps
Constructor & Destructor Documentation
FSplashScreen()
FSplashScreen::FSplashScreen (const QPixmap & pixmap = QPixmap(), Qt::WindowFlags f = 0)
References MessageThing::color, DebugDialog::debug(), displaySlice(), m_items, and MessageThing::rect.
~FSplashScreen()
FSplashScreen::~FSplashScreen ()
References m_items, m_messages, and m_pixmaps.
Member Function Documentation
displaySlice
void FSplashScreen::displaySlice () slot
References showPixmap().
drawContents()
void FSplashScreen::drawContents (QPainter * painter) protected
References MessageThing::alignment, MessageThing::color, m_messages, m_pixmaps, MessageThing::message, PixmapThing::pixmap, MessageThing::rect, and PixmapThing::rect.
showMessage()
void FSplashScreen::showMessage (const QString & message, const QString & id, int alignment = Qt::AlignLeft)
References MessageThing::alignment, MessageThing::color, m_items, m_messages, MessageThing::message, and MessageThing::rect.
showPixmap()
int FSplashScreen::showPixmap (const QPixmap & pixmap, const QString & id)
References m_items, m_pixmaps, PixmapThing::pixmap, MessageThing::rect, and PixmapThing::rect.
showProgress()
void FSplashScreen::showProgress (int index, double progress)
References int(), m_pixmaps, and PixmapThing::rect.
Member Data Documentation
m_items
QHash<QString, MessageThing *> FSplashScreen::m_items protected
m_messages
QList<MessageThing *> FSplashScreen::m_messages protected
m_pixmap
QPixmap FSplashScreen::m_pixmap protected
m_pixmaps
QList<PixmapThing *> FSplashScreen::m_pixmaps protected
The documentation for this class was generated from the following files:
fsplashscreen.h
fsplashscreen.cpp