Fritzing: GedaElementLexer Class Reference
GedaElementLexer Class Reference
#include <gedaelementlexer.h>
Public Member Functions
GedaElementLexer (const QString &source)
~GedaElementLexer ()=default
const QStringList & comments ()
QString currentCommand ()
double currentNumber ()
QString currentString ()
int lex ()
Protected Member Functions
QString clean (const QString &source)
QChar next ()
Protected Attributes
const QChar * m_chars = nullptr
QRegExp m_commentMatcher
QStringList m_comments
QChar m_current
QString m_currentCommand
long m_currentHexString = 0l
long m_currentNumber = 0l
QString m_currentString
QRegExp m_elementMatcher
QRegExp m_hexMatcher
QRegExp m_integerMatcher
QRegExp m_nonWhitespaceMatcher
int m_pos = 0
int m_size = 0
QString m_source
QRegExp m_stringMatcher
Constructor & Destructor Documentation
GedaElementLexer()
GedaElementLexer::GedaElementLexer (const QString & source)
References clean(), m_chars, m_current, m_size, m_source, and next().
~GedaElementLexer()
GedaElementLexer::~GedaElementLexer () default
Member Function Documentation
clean()
QString GedaElementLexer::clean (const QString & source) protected
References findWhitespace(), GedaElementGrammar::HEXNUMBER, lex(), m_commentMatcher, m_comments, m_currentString, m_elementMatcher, m_nonWhitespaceMatcher, m_pos, GedaElementGrammar::NUMBER, GedaElementGrammar::RIGHTBRACKET, GedaElementGrammar::RIGHTPAREN, and GedaElementGrammar::STRING.
comments()
const QStringList & GedaElementLexer::comments ()
References m_comments.
currentCommand()
QString GedaElementLexer::currentCommand ()
References m_currentCommand.
currentNumber()
double GedaElementLexer::currentNumber ()
References m_currentNumber.
currentString()
QString GedaElementLexer::currentString ()
References m_currentString.
lex()
int GedaElementLexer::lex ()
References GedaElementGrammar::ATTRIBUTE, GedaElementGrammar::ELEMENT, GedaElementGrammar::ELEMENTARC, GedaElementGrammar::ELEMENTLINE, GedaElementGrammar::EOF_SYMBOL, GedaElementGrammar::HEXNUMBER, GedaElementGrammar::LEFTBRACKET, GedaElementGrammar::LEFTPAREN, m_current, m_currentCommand, m_currentNumber, m_currentString, m_hexMatcher, m_integerMatcher, m_pos, m_source, m_stringMatcher, GedaElementGrammar::MARK, next(), GedaElementGrammar::NUMBER, GedaElementGrammar::PAD, GedaElementGrammar::PIN, GedaElementGrammar::RIGHTBRACKET, GedaElementGrammar::RIGHTPAREN, and GedaElementGrammar::STRING.
next()
QChar GedaElementLexer::next () protected
References m_chars, m_current, m_pos, and m_size.
Member Data Documentation
m_chars
const QChar* GedaElementLexer::m_chars = nullptr protected
m_commentMatcher
QRegExp GedaElementLexer::m_commentMatcher protected
m_comments
QStringList GedaElementLexer::m_comments protected
m_current
QChar GedaElementLexer::m_current protected
m_currentCommand
QString GedaElementLexer::m_currentCommand protected
m_currentHexString
long GedaElementLexer::m_currentHexString = 0l protected
m_currentNumber
long GedaElementLexer::m_currentNumber = 0l protected
m_currentString
QString GedaElementLexer::m_currentString protected
m_elementMatcher
QRegExp GedaElementLexer::m_elementMatcher protected
m_hexMatcher
QRegExp GedaElementLexer::m_hexMatcher protected
m_integerMatcher
QRegExp GedaElementLexer::m_integerMatcher protected
m_nonWhitespaceMatcher
QRegExp GedaElementLexer::m_nonWhitespaceMatcher protected
m_pos
int GedaElementLexer::m_pos = 0 protected
m_size
int GedaElementLexer::m_size = 0 protected
m_source
QString GedaElementLexer::m_source protected
m_stringMatcher
QRegExp GedaElementLexer::m_stringMatcher protected
The documentation for this class was generated from the following files:
svg/gedaelementlexer.h
svg/gedaelementlexer.cpp