Fritzing: HtmlInfoView Class Reference
HtmlInfoView Class Reference
#include <htmlinfoview.h>
Signals
void clickObsoleteSignal ()
Public Member Functions
HtmlInfoView (QWidget *parent=0)
~HtmlInfoView ()
ItemBase * currentItem ()
void hoverEnterConnectorItem (class InfoGraphicsView *, QGraphicsSceneHoverEvent *event, ConnectorItem *item, bool swappingEnabled)
void hoverEnterItem (class InfoGraphicsView *, QGraphicsSceneHoverEvent *event, ItemBase *item, bool swappingEnabled)
void hoverLeaveConnectorItem (class InfoGraphicsView *, QGraphicsSceneHoverEvent *event, ConnectorItem *item)
void hoverLeaveItem (class InfoGraphicsView *, QGraphicsSceneHoverEvent *event, ItemBase *item)
void init (bool tinyMode)
void reloadContent (class InfoGraphicsView *)
void setContent (const QString &html)
QSize sizeHint () const
void unregisterCurrentItem ()
void unregisterCurrentItemIf (long id)
void updateLocation (ItemBase *)
void updateRotation (ItemBase *)
void viewItemInfo (class InfoGraphicsView *, ItemBase *item, bool swappingEnabled)
Static Public Member Functions
static void cleanup ()
static QHash< QString, QString > getPartProperties (ModelPart *modelPart, ItemBase *itemBase, bool wantDebug, QStringList &keys)
Static Public Attributes
static const int STANDARD_ICON_IMG_HEIGHT = 32
static const int STANDARD_ICON_IMG_WIDTH = 32
Protected Slots
void changeLock (bool)
void changeSticky (bool)
void clickObsolete (const QString &)
void instanceTitleEditable (bool editable)
void instanceTitleEnter ()
void instanceTitleLeave ()
void rotEntry ()
void setContent ()
void setInstanceTitle ()
void unitsClicked ()
void xyEntry ()
Protected Member Functions
void addTags (ModelPart *modelPart)
void appendItemStuff (ItemBase *base, bool swappingEnabled)
void appendItemStuff (ItemBase *base, ModelPart *modelPart, bool swappingEnabled)
void appendStuff (ItemBase *item, bool swappingEnabled)
void appendWireStuff (Wire *wire, bool swappingEnabled)
void clearPropThingPlugin (PropThing *propThing)
void clearPropThingPlugin (PropThing *propThing, QWidget *plugin)
void displayProps (ModelPart *modelPart, ItemBase *itemBase, bool swappingEnabled)
void makeLocationFrame ()
void makeLockFrame ()
void makeRotationFrame ()
void partTitle (const QString &title, const QString &version, const QString &url, bool obsolete)
void setCurrentItem (ItemBase *)
void setInstanceTitleColors (class FLineEdit *edit, const QColor &base, const QColor &text)
void setLocation (ItemBase *)
void setNullContent ()
void setRotation (ItemBase *)
void setUpIcons (ItemBase *, bool swappingEnabled)
void setUpTitle (ItemBase *)
void showLayers (bool show, ItemBase *, const QString &family, const QString &value, bool swappingEnabled)
void viewConnectorItemInfo (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
Protected Attributes
QLabel * m_connDescr
QFrame * m_connFrame
QLabel * m_connLabel
QLabel * m_connName
QLabel * m_connType
QPointer< ItemBase > m_currentItem
bool m_currentSwappingEnabled
QLabel * m_icon1
QLabel * m_icon2
QLabel * m_icon3
ConnectorItem * m_lastConnectorItem
int m_lastConnectorItemCount
ItemBase * m_lastIconItemBase
QPointer< ItemBase > m_lastItemBase
QString m_lastPartTitle
QString m_lastPartVersion
ItemBase * m_lastPropsItemBase
ModelPart * m_lastPropsModelPart
bool m_lastPropsSwappingEnabled
bool m_lastSwappingEnabled
ModelPart * m_lastTagsModelPart
ItemBase * m_lastTitleItemBase
QFrame * m_layerFrame
QLabel * m_layerLabel
QVBoxLayout * m_layerLayout
QWidget * m_layerWidget
QFrame * m_locationFrame
QLabel * m_locationLabel
QCheckBox * m_lockCheckbox
QFrame * m_lockFrame
QLabel * m_lockLabel
QLabel * m_partTitle
QLabel * m_partUrl
QLabel * m_partVersion
QPointer< ItemBase > m_pendingItemBase
bool m_pendingSwappingEnabled
QFrame * m_placementFrame
QLabel * m_placementLabel
QGridLayout * m_placementLayout
QFrame * m_propFrame
QLabel * m_propLabel
QGridLayout * m_propLayout
QList< PropThing * > m_propThings
QFrame * m_rotationFrame
QLabel * m_rotationLabel
QDoubleSpinBox * m_rotEdit
QTimer m_setContentTimer
QCheckBox * m_stickyCheckbox
QLabel * m_tagLabel
QLabel * m_tagsTextLabel
bool m_tinyMode
class FLineEdit * m_titleEdit
QLabel * m_unitsLabel
QDoubleSpinBox * m_xEdit
QDoubleSpinBox * m_yEdit
Constructor & Destructor Documentation
HtmlInfoView()
HtmlInfoView::HtmlInfoView (QWidget * parent = 0)
References m_connDescr, m_currentItem, m_currentSwappingEnabled, m_lastConnectorItem, m_lastIconItemBase, m_lastItemBase, m_lastPropsItemBase, m_lastPropsModelPart, m_lastSwappingEnabled, m_lastTagsModelPart, m_lastTitleItemBase, m_layerWidget, m_lockCheckbox, m_partTitle, m_partUrl, m_partVersion, m_setContentTimer, m_stickyCheckbox, m_tagsTextLabel, m_tinyMode, and setContent().
~HtmlInfoView()
HtmlInfoView::~HtmlInfoView ()
References m_propThings.
Member Function Documentation
addTags()
void HtmlInfoView::addTags (ModelPart * modelPart) protected
References m_lastTagsModelPart, m_tagsTextLabel, and ModelPart::tags().
appendItemStuff() [1/2]
void HtmlInfoView::appendItemStuff (ItemBase * base, bool swappingEnabled) protected
References ItemBase::modelPart().
appendItemStuff() [2/2]
void HtmlInfoView::appendItemStuff (ItemBase * base, ModelPart * modelPart, bool swappingEnabled) protected
References addTags(), ModelPart::description(), displayProps(), ItemBase::getInspectorTitle(), ItemBase::isBaseSticky(), ModelPart::isObsolete(), ItemBase::isSticky(), m_locationFrame, m_locationLabel, m_lockCheckbox, m_lockFrame, m_lockLabel, m_placementFrame, m_placementLabel, m_rotationFrame, m_rotationLabel, m_stickyCheckbox, ModelPart::modelPartShared(), ItemBase::moveLock(), partTitle(), ItemBase::rotationAllowed(), setLocation(), setRotation(), setUpIcons(), setUpTitle(), ModelPart::title(), ModelPart::url(), and ModelPart::version().
appendStuff()
void HtmlInfoView::appendStuff (ItemBase * item, bool swappingEnabled) protected
References appendItemStuff(), and appendWireStuff().
appendWireStuff()
void HtmlInfoView::appendWireStuff (Wire * wire, bool swappingEnabled) protected
References addTags(), ModelPart::description(), displayProps(), Wire::getAutoroutable(), ViewGeometry::getPCBTrace(), ItemBase::getRatsnest(), Wire::getTrace(), ItemBase::getViewGeometry(), ModelPart::isObsolete(), m_locationFrame, m_locationLabel, m_lockFrame, m_lockLabel, m_placementFrame, m_placementLabel, m_rotationFrame, m_rotationLabel, ItemBase::modelPart(), ModelPart::modelPartShared(), partTitle(), ViewLayer::PCBView, setUpIcons(), setUpTitle(), ModelPart::url(), ModelPart::version(), and ItemBase::viewID().
changeLock
void HtmlInfoView::changeLock (bool lockState) protected slot
References m_currentItem, m_locationFrame, m_rotationFrame, and ModelPart::Wire.
changeSticky
void HtmlInfoView::changeSticky (bool lockState) protected slot
References m_currentItem, and ModelPart::Wire.
cleanup()
void HtmlInfoView::cleanup () static
References NoIcon.
clearPropThingPlugin() [1/2]
void HtmlInfoView::clearPropThingPlugin (PropThing * propThing) protected
References PropThing::m_plugin.
clearPropThingPlugin() [2/2]
void HtmlInfoView::clearPropThingPlugin (PropThing * propThing, QWidget * plugin) protected
References PropThing::m_layout.
clickObsolete
void HtmlInfoView::clickObsolete (const QString &) protected slot
References clickObsoleteSignal().
clickObsoleteSignal
void HtmlInfoView::clickObsoleteSignal () signal
currentItem()
ItemBase * HtmlInfoView::currentItem ()
References m_currentItem.
displayProps()
void HtmlInfoView::displayProps (ModelPart * modelPart, ItemBase * itemBase, bool swappingEnabled) protected
References clearPropThingPlugin(), DebugDialog::debug(), getPartProperties(), PropThing::m_frame, m_lastPropsItemBase, m_lastPropsModelPart, m_lastPropsSwappingEnabled, PropThing::m_layout, PropThing::m_name, PropThing::m_plugin, m_propLayout, m_propThings, PropThing::m_value, ViewLayer::PCBView, showLayers(), and ItemBase::translatePropertyName().
getPartProperties()
QHash< QString, QString > HtmlInfoView::getPartProperties (ModelPart * modelPart, ItemBase * itemBase, bool wantDebug, QStringList & keys) static
References ItemBase::prepareProps().
hoverEnterConnectorItem()
void HtmlInfoView::hoverEnterConnectorItem (class InfoGraphicsView * igv, QGraphicsSceneHoverEvent * event, ConnectorItem * item, bool swappingEnabled)
References viewConnectorItemInfo().
hoverEnterItem()
void HtmlInfoView::hoverEnterItem (class InfoGraphicsView * , QGraphicsSceneHoverEvent * event, ItemBase * item, bool swappingEnabled)
References m_pendingItemBase, m_pendingSwappingEnabled, and m_setContentTimer.
hoverLeaveConnectorItem()
void HtmlInfoView::hoverLeaveConnectorItem (class InfoGraphicsView * igv, QGraphicsSceneHoverEvent * event, ConnectorItem * item)
References viewConnectorItemInfo().
hoverLeaveItem()
void HtmlInfoView::hoverLeaveItem (class InfoGraphicsView * , QGraphicsSceneHoverEvent * event, ItemBase * item)
References m_lastItemBase, m_lastSwappingEnabled, m_pendingItemBase, m_pendingSwappingEnabled, and m_setContentTimer.
init()
void HtmlInfoView::init (bool tinyMode)
References addLabel(), clickObsolete(), IconSpace, instanceTitleEditable(), instanceTitleEnter(), instanceTitleLeave(), m_connDescr, m_connFrame, m_connLabel, m_connName, m_connType, m_icon1, m_icon2, m_icon3, m_layerFrame, m_layerLabel, m_layerLayout, m_locationFrame, m_locationLabel, m_lockFrame, m_lockLabel, m_partTitle, m_partUrl, m_partVersion, m_placementFrame, m_placementLabel, m_placementLayout, m_propFrame, m_propLabel, m_propLayout, m_rotationFrame, m_rotationLabel, m_tagLabel, m_tagsTextLabel, m_tinyMode, m_titleEdit, makeLocationFrame(), makeLockFrame(), makeRotationFrame(), NoIcon, setInstanceTitle(), and setInstanceTitleColors().
instanceTitleEditable
void HtmlInfoView::instanceTitleEditable (bool editable) protected slot
References setInstanceTitleColors().
instanceTitleEnter
void HtmlInfoView::instanceTitleEnter () protected slot
References setInstanceTitleColors().
instanceTitleLeave
void HtmlInfoView::instanceTitleLeave () protected slot
References setInstanceTitleColors().
makeLocationFrame()
void HtmlInfoView::makeLocationFrame () protected
References AfterSpinBoxWidth, m_locationFrame, m_locationLabel, m_unitsLabel, m_xEdit, m_yEdit, MaxSpinBoxWidth, unitsClicked(), and xyEntry().
makeLockFrame()
void HtmlInfoView::makeLockFrame () protected
References changeLock(), changeSticky(), m_lockCheckbox, m_lockFrame, m_lockLabel, and m_stickyCheckbox.
makeRotationFrame()
void HtmlInfoView::makeRotationFrame () protected
References AfterSpinBoxWidth, m_rotationFrame, m_rotationLabel, m_rotEdit, MaxSpinBoxWidth, and rotEntry().
partTitle()
void HtmlInfoView::partTitle (const QString & title, const QString & version, const QString & url, bool obsolete) protected
References m_lastPartTitle, m_lastPartVersion, m_partTitle, m_partUrl, m_partVersion, and m_tinyMode.
reloadContent()
void HtmlInfoView::reloadContent (class InfoGraphicsView * infoGraphicsView)
References m_currentItem, m_currentSwappingEnabled, and viewItemInfo().
rotEntry
void HtmlInfoView::rotEntry () protected slot
References InfoGraphicsView::getInfoGraphicsView(), m_lastItemBase, m_rotEdit, and InfoGraphicsView::rotateX().
setContent() [1/2]
void HtmlInfoView::setContent (const QString & html)
setContent [2/2]
void HtmlInfoView::setContent () protected slot
References appendStuff(), m_connFrame, m_connLabel, m_currentSwappingEnabled, m_pendingItemBase, m_pendingSwappingEnabled, m_propFrame, m_propLabel, m_setContentTimer, m_tagLabel, m_tinyMode, setCurrentItem(), and setNullContent().
setCurrentItem()
void HtmlInfoView::setCurrentItem (ItemBase * item) protected
References m_currentItem.
setInstanceTitle
void HtmlInfoView::setInstanceTitle () protected slot
References m_currentItem, and m_partTitle.
setInstanceTitleColors()
void HtmlInfoView::setInstanceTitleColors (class FLineEdit * edit, const QColor & base, const QColor & text) protected
setLocation()
void HtmlInfoView::setLocation (ItemBase * itemBase) protected
References m_unitsLabel, m_xEdit, m_yEdit, and ItemBase::moveLock().
setNullContent()
void HtmlInfoView::setNullContent () protected
References addTags(), displayProps(), m_connFrame, m_connLabel, m_placementFrame, m_placementLabel, m_propFrame, m_propLabel, m_tagLabel, partTitle(), setUpIcons(), setUpTitle(), and viewConnectorItemInfo().
setRotation()
void HtmlInfoView::setRotation (ItemBase * itemBase) protected
References ItemBase::freeRotationAllowed(), m_rotEdit, ItemBase::moveLock(), ItemBase::rotation45Allowed(), and ItemBase::rotationAllowed().
setUpIcons()
void HtmlInfoView::setUpIcons (ItemBase * itemBase, bool swappingEnabled) protected
References ItemBase::getPixmaps(), m_icon1, m_icon2, m_icon3, m_lastIconItemBase, and NoIcon.
setUpTitle()
void HtmlInfoView::setUpTitle (ItemBase * itemBase) protected
References ItemBase::getInspectorTitle(), ViewLayer::IconView, ItemBase::instanceTitle(), m_lastTitleItemBase, m_titleEdit, ItemBase::title(), and ItemBase::viewID().
showLayers()
void HtmlInfoView::showLayers (bool show, ItemBase * itemBase, const QString & family, const QString & value, bool swappingEnabled) protected
References ItemBase::collectExtraInfo(), m_layerFrame, m_layerLabel, m_layerLayout, and m_layerWidget.
sizeHint()
QSize HtmlInfoView::sizeHint () const
References DockWidthDefault, and InfoViewHeightDefault.
unitsClicked
void HtmlInfoView::unitsClicked () protected slot
References TextUtils::convertToInches(), m_unitsLabel, m_xEdit, and m_yEdit.
unregisterCurrentItem()
void HtmlInfoView::unregisterCurrentItem ()
References m_pendingItemBase, m_setContentTimer, and setCurrentItem().
unregisterCurrentItemIf()
void HtmlInfoView::unregisterCurrentItemIf (long id)
References m_currentItem, and unregisterCurrentItem().
updateLocation()
void HtmlInfoView::updateLocation (ItemBase * itemBase)
References m_lastItemBase, and setLocation().
updateRotation()
void HtmlInfoView::updateRotation (ItemBase * itemBase)
References m_lastItemBase, and setRotation().
viewConnectorItemInfo()
void HtmlInfoView::viewConnectorItemInfo (QGraphicsSceneHoverEvent * event, ConnectorItem * item) protected
References NonConnectorItem::attachedTo(), ConnectorItem::connectionsCount(), ConnectorItem::connector(), Connector::connectorNameFromType(), Connector::connectorSharedName(), Connector::connectorType(), m_connDescr, m_connName, m_connType, m_lastConnectorItem, m_lastConnectorItemCount, and m_lastItemBase.
viewItemInfo()
void HtmlInfoView::viewItemInfo (class InfoGraphicsView * , ItemBase * item, bool swappingEnabled)
References m_lastItemBase, m_lastSwappingEnabled, m_pendingItemBase, m_pendingSwappingEnabled, and m_setContentTimer.
xyEntry
void HtmlInfoView::xyEntry () protected slot
References TextUtils::convertToInches(), DebugDialog::debug(), InfoGraphicsView::getInfoGraphicsView(), m_lastItemBase, m_unitsLabel, m_xEdit, m_yEdit, and InfoGraphicsView::moveItem().
Member Data Documentation
m_connDescr
QLabel* HtmlInfoView::m_connDescr protected
m_connFrame
QFrame* HtmlInfoView::m_connFrame protected
m_connLabel
QLabel* HtmlInfoView::m_connLabel protected
m_connName
QLabel* HtmlInfoView::m_connName protected
m_connType
QLabel* HtmlInfoView::m_connType protected
m_currentItem
QPointer<ItemBase> HtmlInfoView::m_currentItem protected
m_currentSwappingEnabled
bool HtmlInfoView::m_currentSwappingEnabled protected
m_icon1
QLabel* HtmlInfoView::m_icon1 protected
m_icon2
QLabel* HtmlInfoView::m_icon2 protected
m_icon3
QLabel* HtmlInfoView::m_icon3 protected
m_lastConnectorItem
ConnectorItem* HtmlInfoView::m_lastConnectorItem protected
m_lastConnectorItemCount
int HtmlInfoView::m_lastConnectorItemCount protected
m_lastIconItemBase
ItemBase* HtmlInfoView::m_lastIconItemBase protected
m_lastItemBase
QPointer<ItemBase> HtmlInfoView::m_lastItemBase protected
m_lastPartTitle
QString HtmlInfoView::m_lastPartTitle protected
m_lastPartVersion
QString HtmlInfoView::m_lastPartVersion protected
m_lastPropsItemBase
ItemBase* HtmlInfoView::m_lastPropsItemBase protected
m_lastPropsModelPart
ModelPart* HtmlInfoView::m_lastPropsModelPart protected
m_lastPropsSwappingEnabled
bool HtmlInfoView::m_lastPropsSwappingEnabled protected
m_lastSwappingEnabled
bool HtmlInfoView::m_lastSwappingEnabled protected
m_lastTagsModelPart
ModelPart* HtmlInfoView::m_lastTagsModelPart protected
m_lastTitleItemBase
ItemBase* HtmlInfoView::m_lastTitleItemBase protected
m_layerFrame
QFrame* HtmlInfoView::m_layerFrame protected
m_layerLabel
QLabel* HtmlInfoView::m_layerLabel protected
m_layerLayout
QVBoxLayout* HtmlInfoView::m_layerLayout protected
m_layerWidget
QWidget* HtmlInfoView::m_layerWidget protected
m_locationFrame
QFrame* HtmlInfoView::m_locationFrame protected
m_locationLabel
QLabel* HtmlInfoView::m_locationLabel protected
m_lockCheckbox
QCheckBox* HtmlInfoView::m_lockCheckbox protected
m_lockFrame
QFrame* HtmlInfoView::m_lockFrame protected
m_lockLabel
QLabel* HtmlInfoView::m_lockLabel protected
m_partTitle
QLabel* HtmlInfoView::m_partTitle protected
m_partUrl
QLabel* HtmlInfoView::m_partUrl protected
m_partVersion
QLabel* HtmlInfoView::m_partVersion protected
m_pendingItemBase
QPointer<ItemBase> HtmlInfoView::m_pendingItemBase protected
m_pendingSwappingEnabled
bool HtmlInfoView::m_pendingSwappingEnabled protected
m_placementFrame
QFrame* HtmlInfoView::m_placementFrame protected
m_placementLabel
QLabel* HtmlInfoView::m_placementLabel protected
m_placementLayout
QGridLayout* HtmlInfoView::m_placementLayout protected
m_propFrame
QFrame* HtmlInfoView::m_propFrame protected
m_propLabel
QLabel* HtmlInfoView::m_propLabel protected
m_propLayout
QGridLayout* HtmlInfoView::m_propLayout protected
m_propThings
QList<PropThing *> HtmlInfoView::m_propThings protected
m_rotationFrame
QFrame* HtmlInfoView::m_rotationFrame protected
m_rotationLabel
QLabel* HtmlInfoView::m_rotationLabel protected
m_rotEdit
QDoubleSpinBox* HtmlInfoView::m_rotEdit protected
m_setContentTimer
QTimer HtmlInfoView::m_setContentTimer protected
m_stickyCheckbox
QCheckBox* HtmlInfoView::m_stickyCheckbox protected
m_tagLabel
QLabel* HtmlInfoView::m_tagLabel protected
m_tagsTextLabel
QLabel* HtmlInfoView::m_tagsTextLabel protected
m_tinyMode
bool HtmlInfoView::m_tinyMode protected
m_titleEdit
class FLineEdit* HtmlInfoView::m_titleEdit protected
m_unitsLabel
QLabel* HtmlInfoView::m_unitsLabel protected
m_xEdit
QDoubleSpinBox* HtmlInfoView::m_xEdit protected
m_yEdit
QDoubleSpinBox* HtmlInfoView::m_yEdit protected
STANDARD_ICON_IMG_HEIGHT
const int HtmlInfoView::STANDARD_ICON_IMG_HEIGHT = 32 static
STANDARD_ICON_IMG_WIDTH
const int HtmlInfoView::STANDARD_ICON_IMG_WIDTH = 32 static
The documentation for this class was generated from the following files:
infoview/htmlinfoview.h
infoview/htmlinfoview.cpp