Fritzing: Stripbit Class Reference
Stripbit Class Reference
#include <stripboard.h>
Public Member Functions
Stripbit (const QPainterPath &path, int x, int y, bool horizontal, QGraphicsItem *parent)
~Stripbit ()
bool changed ()
bool horizontal ()
void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
QString makeRemovedString ()
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
void mousePressEvent (QGraphicsSceneMouseEvent *event)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
bool removed ()
void setChanged (bool)
void setRemoved (bool)
int x ()
int y ()
Protected Attributes
bool m_changed
bool m_horizontal
bool m_inHover
bool m_removed
int m_x
int m_y
Constructor & Destructor Documentation
Stripbit()
Stripbit::Stripbit (const QPainterPath & path, int x, int y, bool horizontal, QGraphicsItem * parent = 0)
References horizontal(), m_horizontal, m_inHover, m_removed, m_x, m_y, MagicWandCursor, SpotFaceCutterCursor, x(), and y().
~Stripbit()
Stripbit::~Stripbit ()
Member Function Documentation
changed()
bool Stripbit::changed ()
References m_changed.
horizontal()
bool Stripbit::horizontal ()
References m_horizontal.
hoverEnterEvent()
void Stripbit::hoverEnterEvent (QGraphicsSceneHoverEvent * event)
References InfoGraphicsView::getInfoGraphicsView(), m_inHover, m_removed, MagicWandCursor, InfoGraphicsView::spaceBarIsPressed(), SpaceBarWasPressed, and SpotFaceCutterCursor.
hoverLeaveEvent()
void Stripbit::hoverLeaveEvent (QGraphicsSceneHoverEvent * event)
References m_inHover, and SpaceBarWasPressed.
makeRemovedString()
QString Stripbit::makeRemovedString ()
References m_horizontal, m_x, and m_y.
mouseMoveEvent()
void Stripbit::mouseMoveEvent (QGraphicsSceneMouseEvent * event)
References m_removed, MinMouseMove, OriginalShiftPos, removed(), setChanged(), setRemoved(), ShiftDown, ShiftX, and ShiftY.
mousePressEvent()
void Stripbit::mousePressEvent (QGraphicsSceneMouseEvent * event)
References InfoGraphicsView::getInfoGraphicsView(), m_changed, m_inHover, m_removed, OriginalShiftPos, ShiftDown, ShiftX, ShiftY, and InfoGraphicsView::spaceBarIsPressed().
mouseReleaseEvent()
void Stripbit::mouseReleaseEvent (QGraphicsSceneMouseEvent * event)
paint()
void Stripbit::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget)
References m_inHover, and m_removed.
removed()
bool Stripbit::removed ()
References m_removed.
setChanged()
void Stripbit::setChanged (bool changed)
References changed(), and m_changed.
setRemoved()
void Stripbit::setRemoved (bool removed)
References m_removed, and removed().
x()
int Stripbit::x ()
References m_x.
y()
int Stripbit::y ()
References m_y.
Member Data Documentation
m_changed
bool Stripbit::m_changed protected
m_horizontal
bool Stripbit::m_horizontal protected
m_inHover
bool Stripbit::m_inHover protected
m_removed
bool Stripbit::m_removed protected
m_x
int Stripbit::m_x protected
m_y
int Stripbit::m_y protected
The documentation for this class was generated from the following files:
items/stripboard.h
items/stripboard.cpp