Fritzing: HashLineEdit Class Reference
HashLineEdit Class Reference
#include <hashpopulatewidget.h>
Public Member Functions
HashLineEdit (const QString &text, bool defaultValue=false, QWidget *parent=0)
bool hasChanged ()
QString textIfSetted ()
Protected Slots
void updateObjectName ()
Protected Member Functions
void focusOutEvent (QFocusEvent *event)
void mousePressEvent (QMouseEvent *event)
Protected Attributes
QString m_firstText
bool m_isDefaultValue
Constructor & Destructor Documentation
HashLineEdit()
HashLineEdit::HashLineEdit (const QString & text, bool defaultValue = false, QWidget * parent = 0)
References m_firstText, m_isDefaultValue, and updateObjectName().
Member Function Documentation
focusOutEvent()
void HashLineEdit::focusOutEvent (QFocusEvent * event) protected
References m_firstText.
hasChanged()
bool HashLineEdit::hasChanged ()
References m_firstText.
mousePressEvent()
void HashLineEdit::mousePressEvent (QMouseEvent * event) protected
References hasChanged(), and m_isDefaultValue.
textIfSetted()
QString HashLineEdit::textIfSetted ()
References hasChanged(), and m_isDefaultValue.
updateObjectName
void HashLineEdit::updateObjectName () protected slot
References hasChanged(), and m_isDefaultValue.
Member Data Documentation
m_firstText
QString HashLineEdit::m_firstText protected
m_isDefaultValue
bool HashLineEdit::m_isDefaultValue protected
The documentation for this class was generated from the following files:
partseditor/hashpopulatewidget.h
partseditor/hashpopulatewidget.cpp