Fritzing: SchematicSketchWidget Class Reference
SchematicSketchWidget Class Reference
#include <schematicsketchwidget.h>
Public Slots
void setInstanceTitle (long id, const QString &oldTitle, const QString &newTitle, bool isUndoable, bool doEmit)
void setProp (ItemBase *, const QString &propName, const QString &translatedPropName, const QString &oldValue, const QString &newValue, bool redraw)
void setVoltage (double voltage, bool doEmit)
Public Slots inherited from PCBSketchWidget
void changeBoardLayers (int layers, bool doEmit)
void resizeBoard (double w, double h, bool doEmit)
ItemBase * resizeBoard (long id, double w, double h)
void showLabelFirstTime (long itemID, bool show, bool doEmit)
Public Slots inherited from SketchWidget
void addSubpart (long id, long subpartid, bool doEmit)
virtual void changeBoardLayers (int layers, bool doEmit)
void changeWireColor (const QString newColor)
void changeWireWidthMils (const QString newWidth)
void checkSticky (long id, bool doEmit, bool checkCurrent, CheckStickyCommand *)
void cleanupRatsnests (bool doEmit)
void disconnectAllSlot (QList< ConnectorItem * >, QHash< ItemBase *, SketchWidget * > &itemsToDelete, QUndoCommand *parentCommand)
void incInstanceTitle (long id)
void packItems (int columns, const QList< long > &ids, QUndoCommand *parent, bool doEmit)
void ratsnestConnect (long id, const QString &connectorID, bool connect, bool doEmit)
virtual ItemBase * resizeBoard (long id, double w, double h)
void resizeBoard (double w, double h, bool doEmit)
void resizeJumperItem (long id, QPointF pos, QPointF c0, QPointF c1)
void selectAllItems (bool state, bool doEmit)
void setHoleSize (ItemBase *, const QString &propName, const QString &translatedPropName, const QString &oldValue, const QString &newValue, QRectF &oldRect, QRectF &newRect, bool redraw)
void setInstanceTitle (long id, const QString &oldTitle, const QString &newTitle, bool isUndoable, bool doEmit)
void setNoteText (long itemID, const QString &newText)
void setProp (long itemID, const QString &prop, const QString &value, bool redraw, bool doEmit)
virtual void setProp (ItemBase *, const QString &propName, const QString &translatedPropName, const QString &oldValue, const QString &newValue, bool redraw)
void setResistance (long itemID, QString resistance, QString pinSpacing, bool doEmit)
void setResistance (QString resistance, QString pinSpacing)
virtual void showLabelFirstTime (long itemID, bool show, bool doEmit)
void showPartLabel (long id, bool showIt)
void updateConnectors ()
Public Slots inherited from InfoGraphicsView
virtual void resizeBoard (double w, double h, bool doEmit)
virtual void setInstanceTitle (long id, const QString &oldTitle, const QString &newTitle, bool isUndoable, bool doEmit)
virtual void setVoltage (double, bool doEmit)
Public Member Functions
SchematicSketchWidget (ViewLayer::ViewID, QWidget *parent=0)
bool acceptsTrace (const ViewGeometry &)
void addDefaultParts ()
void addViewLayers ()
bool attachedToBottomLayer (ConnectorItem *)
bool attachedToTopLayer (ConnectorItem *)
bool autorouteTypePCB ()
bool canDropModelPart (ModelPart *modelPart)
void changeConnection (long fromID, const QString &fromConnectorID, long toID, const QString &toConnectorID, ViewLayer::ViewLayerPlacement, bool connect, bool doEmit, bool updateConnections)
Wire * createTempWireForDragging (Wire *fromWire, ModelPart *wireModel, ConnectorItem *connectorItem, ViewGeometry &viewGeometry, ViewLayer::ViewLayerPlacement)
double defaultGridSizeInches ()
void ensureTraceLayersVisible ()
void ensureTraceLayerVisible ()
QString generateCopperFillUnit (ItemBase *itemBase, QPointF whereToStart)
QHash< QString, QString > getAutorouterSettings ()
double getAutorouterTraceWidth ()
void getBendpointWidths (class Wire *, double w, double &w1, double &w2, bool &negativeOffsetRect)
ViewLayer::ViewLayerID getDragWireViewLayerID (ConnectorItem *)
double getKeepout ()
void getLabelFont (QFont &, QColor &, ItemBase *)
ViewGeometry::WireFlag getTraceFlag ()
double getTraceWidth ()
ViewLayer::ViewLayerPlacement getViewLayerPlacement (ModelPart *, QDomElement &instance, QDomElement &view, ViewGeometry &)
double getWireStrokeWidth (Wire *, double wireWidth)
ViewLayer::ViewLayerID getWireViewLayerID (const ViewGeometry &viewGeometry, ViewLayer::ViewLayerPlacement)
bool hasBigDots ()
bool includeSymbols ()
void initWire (Wire *, int penWidth)
bool isInLayers (ConnectorItem *, ViewLayer::ViewLayerPlacement)
bool isOldSchematic ()
QSizeF jumperItemSize ()
void loadFromModelParts (QList< ModelPart * > &modelParts, BaseCommand::CrossViewType, QUndoCommand *parentCommand, bool offsetPaste, const QRectF *boundingRect, bool seekOutsideConnections, QList< long > &newIDs)
void resizeLabels ()
void resizeWires ()
void rotatePartLabels (double degrees, QTransform &, QPointF center, QUndoCommand *parentCommand)
bool routeBothSides ()
LayerList routingLayers (ViewLayer::ViewLayerPlacement)
bool sameElectricalLayer2 (ViewLayer::ViewLayerID, ViewLayer::ViewLayerID)
void setAutorouterSettings (QHash< QString, QString > &)
void setClipEnds (ClipableWire *vw, bool)
void setConvertSchematic (bool)
void setNewPartVisible (ItemBase *)
void setOldSchematic (bool)
void tidyWires ()
const QString & traceColor (ConnectorItem *forColor)
const QString & traceColor (ViewLayer::ViewLayerPlacement)
Public Member Functions inherited from PCBSketchWidget
PCBSketchWidget (ViewLayer::ViewID, QWidget *parent=0)
ItemBase * addCopperLogoItem (ViewLayer::ViewLayerPlacement viewLayerPlacement)
void autorouterSettings ()
bool canChainMultiple ()
bool canCopyItem (QGraphicsItem *item, int count)
bool canDeleteItem (QGraphicsItem *item, int count)
void changeLayer (long id, double z, ViewLayer::ViewLayerID viewLayerID)
void changeTraceLayer (ItemBase *, bool force, QUndoCommand *parentCommand)
QString characterizeGroundFill (ViewLayer::ViewLayerID)
int checkLoadedTraces ()
CleanType cleanType ()
void clearGroundFillSeeds ()
void convertToBendpoint ()
void convertToVia (ConnectorItem *lastHoverEnterConnectorItem)
void createTrace (Wire *, bool useLastWireColor)
ViewLayer::ViewLayerPlacement defaultViewLayerPlacement (ModelPart *)
void deleteItem (ItemBase *, bool deleteModelPart, bool doEmit, bool later)
bool dropOnBottom ()
void excludeFromAutoroute (bool exclude)
void fabQuote ()
QList< ItemBase * > findBoard ()
ItemBase * findBoardBeneath (ItemBase *)
ItemBase * findSelectedBoard (int &boardCount)
void forwardRoutingStatus (const RoutingStatus &)
void getDefaultViaSize (QString &ringThickness, QString &holeSize)
virtual double getLabelFontSizeLarge ()
virtual double getLabelFontSizeMedium ()
virtual double getLabelFontSizeSmall ()
virtual double getLabelFontSizeTiny ()
double getSmallerTraceWidth (double minDim)
void getViaSize (double &ringThickness, double &holeSize)
bool groundFill (bool fillGroundTraces, ViewLayer::ViewLayerID, QUndoCommand *parentCommand)
bool hasAnyNets ()
bool hasCustomBoardShape ()
void hideCopperLogoItems (QList< ItemBase * > &)
void hideHoles (QList< ItemBase * > &)
void hidePartSilkscreen ()
bool isBoardLayerChange (ItemBase *itemBase, const QString &newModuleID, int &newLayers)
QString makePasteMask (const QString &svgMask, ItemBase *board, double dpi, const LayerList &maskLayerIDs)
ItemBase * placePartDroppedInOtherView (ModelPart *, ViewLayer::ViewLayerPlacement, const ViewGeometry &viewGeometry, long id, SketchWidget *dropOrigin)
QDialog * quoteDialog (QWidget *parent)
void resetKeepout ()
void restoreCopperLogoItems (QList< ItemBase * > &)
void selectAllExcludedTraces ()
void selectAllIncludedTraces ()
int selectAllItemType (ModelPart::ItemType, const QString &typeName)
void setBoardLayers (int, bool redraw)
void setGroundFillKeepout ()
void setGroundFillSeeds ()
void setKeepout (double mils)
void setViewFromBelow (bool)
void showEvent (QShowEvent *event)
void showGroundTraces (QList< ConnectorItem * > &seeds, bool show)
void swapLayers (ItemBase *itemBase, int newLayers, QUndoCommand *parentCommand)
Public Member Functions inherited from SketchWidget
SketchWidget (ViewLayer::ViewID, QWidget *parent=0, int size=400, int minSize=300)
~SketchWidget ()
void addBendpoint (ItemBase *lastHoverEnterItem, ConnectorItem *lastHoverEnterConnectorItem, QPointF lastLocation)
ItemBase * addItem (ModelPart *, ViewLayer::ViewLayerPlacement, BaseCommand::CrossViewType, const ViewGeometry &, long id, long modelIndex, AddDeleteItemCommand *originatingCommand)
ItemBase * addItem (const QString &moduleID, ViewLayer::ViewLayerPlacement, BaseCommand::CrossViewType, const ViewGeometry &, long id, long modelIndex, AddDeleteItemCommand *originatingCommand)
virtual ItemBase * addItemAux (ModelPart *, ViewLayer::ViewLayerPlacement, const ViewGeometry &, long id, bool doConnectors, ViewLayer::ViewID, bool temporary)
ItemBase * addItemAuxTemp (ModelPart *, ViewLayer::ViewLayerPlacement, const ViewGeometry &, long id, bool doConnectors, ViewLayer::ViewID, bool temporary)
void addLegBendpoint (long id, const QString &connectorID, int index, QPointF, const class Bezier *, const class Bezier *)
void addToSketch (QList< ModelPart * > &)
void addViewLayer (ViewLayer *)
QGraphicsItem * addWatermark (const QString &filename)
bool alignedToGrid ()
void alignItems (Qt::Alignment)
QPointF alignOneToGrid (ItemBase *itemBase)
void alignToGrid (bool)
const QColor & background ()
void blockUI (bool)
void bringForward ()
void bringToFront ()
ItemCount calcItemCount ()
virtual bool canDisconnectAll ()
void changeBus (ItemBase *, bool connec, const QString &oldBus, const QString &newBus, QList< ConnectorItem * > &, const QString &message, const QString &oldLayout, const QString &newLayout)
void changeLeg (long fromID, const QString &connectorID, const QPolygonF &, bool relative, const QString &why)
void changeLegCurve (long id, const QString &connectorID, int index, const Bezier *)
void changeWire (long fromID, QLineF line, QPointF pos, bool updateConnections, bool updateRatsnest)
void changeWireColor (long wireId, const QString &color, double opacity)
void changeWireCurve (long id, const Bezier *, bool autoroutable)
void changeWireFlags (long wireId, ViewGeometry::WireFlags wireFlags)
void changeWireWidth (long wireId, double width)
void changeZ (QHash< long, RealPair * >, double(*pairAccessor)(RealPair *))
void checkForReversedWires ()
void cleanUpWires (bool doEmit, class CleanUpWiresCommand *)
void clearPasteOffset ()
void clearSelection ()
void collectAllNets (QHash< class ConnectorItem *, int > &indexer, QList< QList< class ConnectorItem * > * > &allPartConnectorItems, bool includeSingletons, bool bothSides)
void collectParts (QList< ItemBase * > &partList)
void copy ()
void copyHeart (QList< ItemBase * > &bases, bool saveBoundingRects, QByteArray &itemData, QList< long > &modelIndexes)
long createWire (ConnectorItem *from, ConnectorItem *to, ViewGeometry::WireFlags, bool dontUpdate, BaseCommand::CrossViewType, QUndoCommand *parentCommand)
bool curvyWires ()
bool curvyWiresIndicated (Qt::KeyboardModifiers)
void cut ()
void deleteItem (long id, bool deleteModelPart, bool doEmit, bool later)
void deleteMiddle (QSet< ItemBase * > &deletedItems, QUndoCommand *parentCommand)
void deleteSelected (Wire *, bool minus)
void disconnectAll ()
void ensureLayerVisible (ViewLayer::ViewLayerID)
constexpr bool everZoomed () const noexcept
const QString & filenameIf ()
ConnectorItem * findConnectorItem (ConnectorItem *foreignConnectorItem)
ItemBase * findItem (long id)
double fitInWindow ()
void flattenCurve (ItemBase *lastHoverEnterItem, ConnectorItem *lastHoverEnterConnectorItem, QPointF lastLocation)
void flipItem (long id, Qt::Orientations orientation)
void flipX (Qt::Orientations orientation, bool rubberBandLegEnabled)
void getBendpointWidths (class Wire *, double w, double &w1, double &w2, bool &negativeOffsetRect)
void getRatsnestColor (QColor &)
PaletteItem * getSelectedPart ()
const QString & getShortName ()
float getTopZ ()
ViewGeometry::WireFlag getTraceFlag ()
constexpr const QColor & gridColor () const noexcept
QString gridSizeText ()
void hideConnectors (bool hide)
void hidePartLabel (ItemBase *item)
void hidePartLayer (long id, ViewLayer::ViewLayerID, bool hide)
void hidePartLayer (ItemBase *, ViewLayer::ViewLayerID, bool hide)
void hoverEnterConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
void hoverEnterItem (QGraphicsSceneHoverEvent *event, ItemBase *item)
void hoverLeaveConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
void hoverLeaveItem (QGraphicsSceneHoverEvent *event, ItemBase *item)
virtual bool ignoreFemale ()
void initGrid ()
ConnectorItem * lastHoverEnterConnectorItem ()
ItemBase * lastHoverEnterItem ()
bool layerIsActive (ViewLayer::ViewLayerID)
bool layerIsVisible (ViewLayer::ViewLayerID)
void loadLogoImage (ItemBase *, const QString &oldSvg, const QSizeF oldAspectRatio, const QString &oldFilename, const QString &newFilename, bool addName)
void loadLogoImage (long itemID, const QString &oldSvg, const QSizeF oldAspectRatio, const QString &oldFilename)
void loadLogoImage (long itemID, const QString &newFilename, bool addName)
void makeDeleteItemCommand (ItemBase *itemBase, BaseCommand::CrossViewType, QUndoCommand *parentCommand)
VirtualWire * makeOneRatsnestWire (ConnectorItem *source, ConnectorItem *dest, bool routed, QColor color, bool force)
void makeWiresChangeConnectionCommands (const QList< Wire * > &wires, QUndoCommand *parentCommand)
void mousePressConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
void moveItem (long id, ViewGeometry &, bool updateRatsnest)
void moveItem (long id, const QPointF &p, bool updateRatsnest)
void moveItem (ItemBase *, double x, double y)
void moveLegBendpoint (long id, const QString &connectorID, int index, QPointF)
void movePartLabel (long itemID, QPointF newPos, QPointF newOffset)
void noteChanged (ItemBase *, const QString &oldText, const QString &newtext, QSizeF oldSize, QSizeF newSize)
void noteSizeChanged (ItemBase *itemBase, const QSizeF &oldSize, const QSizeF &newSize)
void partLabelChanged (ItemBase *, const QString &oldText, const QString &newtext)
void partLabelMoved (ItemBase *, QPointF oldPos, QPointF oldOffset, QPointF newPos, QPointF newOffset)
bool partLabelsVisible ()
void pasteHeart (QByteArray &itemData, bool seekOutsideConnections)
void prepLegBendpointChange (ConnectorItem *from, int oldCount, int newCount, int index, QPointF pos, const class Bezier *, const class Bezier *, const class Bezier *, bool triggerFirstTime)
void prepLegBendpointMove (ConnectorItem *from, int index, QPointF oldPos, QPointF newPos, ConnectorItem *to, bool changeConnections)
void prepLegCurveChange (ConnectorItem *from, int index, const class Bezier *oldB, const class Bezier *newB, bool triggerFirstTime)
void prepLegSelection (ItemBase *)
void pushCommand (QUndoCommand *, QObject *signalTarget)
void ratsnestConnect (ConnectorItem *connectorItem, bool connect)
void ratsnestConnect (ItemBase *, bool connect)
void ratsnestConnect (ConnectorItem *c1, ConnectorItem *c2, bool connect, bool wait)
double ratsnestOpacity ()
double ratsnestWidth ()
void recalcLeg (long fromID, const QString &connectorID, const QPolygonF &, bool relative, bool active, const QString &why)
class ReferenceModel * referenceModel ()
void removeLegBendpoint (long id, const QString &connectorID, int index, const class Bezier *)
void renamePins (ItemBase *, const QStringList &oldLabels, const QStringList &newLabels, bool singleRow)
void renamePins (long itemID, const QStringList &labels, bool singleRow)
QString renderToSVG (RenderThing &, QGraphicsItem *board, const LayerList &)
void resizeNote (long itemID, const QSizeF &)
void resolveTemporary (bool, ItemBase *)
void restoreLayerVisibility ()
void restorePartLabel (long itemID, QDomElement &element)
double retrieveZoom ()
void rotateFlipPartLabel (ItemBase *, double degrees, Qt::Orientations flipDirection)
void rotateFlipPartLabel (long itemID, double degrees, Qt::Orientations flipDirection)
void rotateItem (long id, double degrees)
void rotateLeg (long fromID, const QString &connectorID, const QPolygonF &, bool active)
void rotateX (double degrees, bool rubberBandLegEnabled, ItemBase *originatingItem)
void saveLayerVisibility ()
void saveZoom (double)
int selectAllMoveLock ()
QList< ItemBase * > selectAllObsolete ()
void selectDeselectAllCommand (bool state)
const QString & selectedModuleID ()
void selectItem (long id, bool state, bool updateInfoView, bool doEmit)
void selectItem (ItemBase *itemBase)
void selectItems (QList< ItemBase * >)
void selectItemsWithModuleID (ModelPart *)
void sendBackward ()
void sendToBack ()
void setAllLayersVisible (bool visible)
void setAnyInRotation ()
void setBackground (QColor)
void setBackgroundColor (QColor, bool setPref)
void setChainDrag (bool)
virtual void setCurrent (bool current)
void setCurvyWires (bool)
void setEverZoomed (bool)
void setGridColor (QColor)
void setGridSize (const QString &)
void setGroundFillSeed (long id, const QString &connectorID, bool seed)
void setIgnoreSelectionChangeEvents (bool)
void setInfoViewOnHover (bool infoViewOnHover)
void setItemDropOffset (long id, QPointF offset)
void setItemMenu (QMenu *)
void setLayerActive (ViewLayer *viewLayer, bool active)
void setLayerActive (ViewLayer::ViewLayerID viewLayerID, bool active)
void setLayerVisible (ViewLayer *viewLayer, bool visible, bool doChildLayers)
void setLayerVisible (ViewLayer::ViewLayerID viewLayerID, bool visible, bool doChildLayers)
void setMoveLock (long id, bool lock)
void setNoteFocus (QGraphicsItem *, bool inFocus)
void setPasting (bool)
void setRatsnestOpacity (double)
void setRatsnestWidth (double)
void setReferenceModel (class ReferenceModel *referenceModel)
void setSketchModel (SketchModel *)
void setUndoStack (class WaitPushUndoStack *)
virtual long setUpSwap (SwapThing &, bool master)
void setViewLayerIDs (ViewLayer::ViewLayerID part, ViewLayer::ViewLayerID wire, ViewLayer::ViewLayerID connector, ViewLayer::ViewLayerID ruler, ViewLayer::ViewLayerID note)
void setWireExtras (long id, QDomElement &)
void setWireMenu (QMenu *)
void showEvent (QShowEvent *event)
void showGrid (bool)
bool showingGrid ()
void showPartLabels (bool show)
void showUnrouted ()
void simpleMoveItem (long id, QPointF)
void sortAnyByZ (const QList< QGraphicsItem * > &items, QList< ItemBase * > &bases)
bool spaceBarIsPressed () noexcept
class SelectItemCommand * stackSelectionState (bool pushIt, QUndoCommand *parentCommand)
QColor standardBackground ()
void stickem (long stickTargetID, long stickSourceID, bool stick)
void stickyScoop (ItemBase *stickyOne, bool checkCurrent, CheckStickyCommand *)
bool swappingEnabled (ItemBase *)
void testConnectors ()
void transformItem (long id, const QMatrix &)
void triggerRotate (ItemBase *, double degrees)
class WaitPushUndoStack * undoStack ()
void updateInfoView ()
void updateRoutingStatus (CleanUpWiresCommand *, RoutingStatus &, bool manual)
void updateRoutingStatus (RoutingStatus &, bool manual)
void updateWire (long id, const QString &connectorID, bool updateRatsnest)
void updateWires ()
constexpr ViewLayer::ViewID viewID () const noexcept
void viewItemInfo (ItemBase *item)
LayerHash & viewLayers ()
constexpr const QString & viewName () const noexcept
Public Member Functions inherited from InfoGraphicsView
InfoGraphicsView (QWidget *parent=0)
int boardLayers ()
virtual void changePinLabels (ItemBase *, bool singleRow)
virtual void changeWireColor (const QString newColor)
virtual void changeWireWidthMils (const QString newWidth)
class HtmlInfoView * infoView ()
virtual void newWire (Wire *)
void setActiveConnectorItem (ConnectorItem *)
void setActiveWire (Wire *)
virtual void setHoleSize (ItemBase *, const QString &propName, const QString &translatedPropName, const QString &oldValue, const QString &newValue, QRectF &oldRect, QRectF &newRect, bool redraw)
void setInfoView (class HtmlInfoView *)
virtual void setProp (ItemBase *, const QString &propName, const QString &translatedPropName, const QString &oldValue, const QString &newValue, bool redraw)
virtual void setResistance (QString resistance, QString pinSpacing)
void setSMDOrientation (Qt::Orientations)
Qt::Orientations smdOrientation ()
virtual void swap (const QString &family, const QString &prop, QMap< QString, QString > &propsMap, ItemBase *)
void updateRotation (ItemBase *)
Public Member Functions inherited from ZoomableGraphicsView
ZoomableGraphicsView (QWidget *parent=0)
void absoluteZoom (double percent)
double currentZoom ()
virtual void ensureFixedToBottomRightItems ()
void relativeZoom (double step, bool centerToCursor)
void setAcceptWheelEvents (bool)
bool viewFromBelow ()
Protected Slots
void getDroppedItemViewLayerPlacement (ModelPart *modelPart, ViewLayer::ViewLayerPlacement &)
void updateBigDots ()
Protected Slots inherited from PCBSketchWidget
void alignJumperItem (class JumperItem *, QPointF &)
void getDroppedItemViewLayerPlacement (ModelPart *modelPart, ViewLayer::ViewLayerPlacement &)
void gotFabQuote (QNetworkReply *)
void postImageSlot (class GroundPlaneGenerator *, QImage *copperImage, QImage *boardImage, QGraphicsItem *board, QList< QRectF > *)
void requestQuoteNow ()
void wireSplitSlot (class Wire *, QPointF newPos, QPointF oldPos, const QLineF &oldLine)
Protected Slots inherited from SketchWidget
void arrowTimerTimeout ()
void autoScrollTimeout ()
void canConnect (Wire *from, ItemBase *to, bool &connect)
void changeConnectionSlot (long fromID, QString fromConnectorID, long toID, QString toConnectorID, ViewLayer::ViewLayerPlacement, bool connect, bool updateConnections)
void changePinLabels (ItemBase *, bool singleRow)
void changePinLabelsSlot (ItemBase *itemBase, bool singleRow)
void cleanUpWiresSlot (CleanUpWiresCommand *)
void clearSelectionSlot ()
void collectRatsnestSlot (QList< SketchWidget * > &foreignSketchWidgets)
void copyBoundingRectsSlot (QHash< QString, QRectF > &)
void deleteRatsnest (Wire *, QUndoCommand *parentCommand)
void deleteTemporary ()
void deleteTracesSlot (QSet< ItemBase * > &deletedItems, QHash< ItemBase *, SketchWidget * > &otherDeletedItems, QList< long > &deletedIDs, bool isForeign, QUndoCommand *parentCommand)
void dragAutoScrollTimeout ()
void dragIsDoneSlot (class ItemDrag *)
virtual void getDroppedItemViewLayerPlacement (ModelPart *modelPart, ViewLayer::ViewLayerPlacement &)
void itemAddedSlot (ModelPart *, ItemBase *, ViewLayer::ViewLayerPlacement, const ViewGeometry &, long id, SketchWidget *dropOrigin)
void itemDeletedSlot (long id)
void itemSelectedSlot (long id, bool state)
void makeDeleteItemCommandFinalSlot (ItemBase *itemBase, bool foreign, QUndoCommand *parentCommand)
void makeDeleteItemCommandPrepSlot (ItemBase *itemBase, bool foreign, QUndoCommand *parentCommand)
void moveAutoScrollTimeout ()
void rememberSticky (long id, QUndoCommand *parentCommand)
void rememberSticky (ItemBase *, QUndoCommand *parentCommand)
void removeRatsnestSlot (QList< struct ConnectorEdge * > &cutSet, QUndoCommand *parentCommand)
void restartPasteCount ()
void selectionChangedSlot ()
void spaceBarIsPressedSlot (bool)
void statusMessage (QString message, int timeout=0)
long swapStart (SwapThing &swapThing, bool master)
void toggleLayerVisibility ()
void updateInfoViewSlot ()
void updatePartLabelInstanceTitleSlot (long itemID)
void vScrollToZero ()
void wireChangedCurveSlot (class Wire *, const Bezier *oldB, const Bezier *newB, bool triggerFirstTime)
void wireChangedSlot (class Wire *, const QLineF &oldLine, const QLineF &newLine, QPointF oldPos, QPointF newPos, ConnectorItem *from, ConnectorItem *to)
void wireConnectedSlot (long fromID, QString fromConnectorID, long toID, QString toConnectorID)
void wireDisconnectedSlot (long fromID, QString fromConnectorID)
void wireJoinSlot (class Wire *, ConnectorItem *clickedConnectorItem)
virtual void wireSplitSlot (class Wire *, QPointF newPos, QPointF oldPos, const QLineF &oldLine)
Protected Member Functions
bool canConnect (Wire *from, ItemBase *to)
QString checkDroppedModuleID (const QString &moduleID)
ViewLayer::ViewLayerPlacement createWireViewLayerPlacement (ConnectorItem *from, ConnectorItem *to)
void extraRenderSvgStep (ItemBase *, QPointF offset, double dpi, double printerScale, QString &outputSvg)
ViewLayer::ViewLayerID getLabelViewLayerID (ItemBase *)
double getRatsnestOpacity ()
double getRatsnestWidth ()
QString makeCircleSVG (QPointF p, double r, QPointF offset, double dpi, double printerScale)
void selectAllWires (ViewGeometry::WireFlag flag)
void viewGeometryConversionHack (ViewGeometry &, ModelPart *)
Protected Member Functions inherited from PCBSketchWidget
PaletteItem * addPartItem (ModelPart *modelPart, ViewLayer::ViewLayerPlacement, PaletteItem *paletteItem, bool doConnectors, bool &ok, ViewLayer::ViewID, bool temporary)
bool bothEndsConnected (Wire *wire, ViewGeometry::WireFlags, ConnectorItem *oneEnd, QList< Wire * > &wires, QList< ConnectorItem * > &partConnectorItems)
bool bothEndsConnectedAux (Wire *wire, ViewGeometry::WireFlags flag, ConnectorItem *oneEnd, QList< Wire * > &wires, QList< ConnectorItem * > &partConnectorItems, QList< Wire * > &visited)
double calcBoardArea (int &boardCount)
bool canAlignToCenter (ItemBase *)
bool canChainWire (Wire *)
bool canConnectSeed (QRectF boardRect, QImage *copperImage, ConnectorItem *connectorItem, ViewLayer::ViewLayerID viewLayerID, QRectF s)
canConnectSeed Check if we can connect a seed without getting to close to another part Also checks if a seed is already connected with a wire on that layer
bool canCreateWire (Wire *dragWire, ConnectorItem *from, ConnectorItem *to)
bool canDragWire (Wire *wire)
bool collectGroundFillSeeds (QList< ConnectorItem * > &seeds, bool includePotential)
void collectThroughHole (QList< ConnectorItem * > &th, QList< ConnectorItem * > &pads, const LayerList &)
bool connectorItemHasSpec (ConnectorItem *connectorItem, ViewLayer::ViewLayerPlacement spec)
void dealWithDefaultParts ()
ConnectorItem * findNearestPartConnectorItem (ConnectorItem *fromConnectorItem)
double getKeepoutMils ()
bool hasNeighbor (ConnectorItem *connectorItem, ViewLayer::ViewLayerID viewLayerID, const QRectF &r)
const QString & hoverEnterPartConnectorMessage (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
ViewLayer::ViewLayerID multiLayerGetViewLayerID (ModelPart *modelPart, ViewLayer::ViewID, ViewLayer::ViewLayerPlacement, LayerList &)
void prereleaseTempWireForDragging (Wire *)
void requestQuote (bool byUser)
void requestQuoteSoon ()
void resizeJumperItem ()
bool resizingJumperItemPress (ItemBase *)
bool resizingJumperItemRelease ()
void selectAllXTraces (bool autoroutable, const QString &cmdText, bool forPCB)
void setGroundFillSeeds (const QString &intro)
void setUpColor (ConnectorItem *fromConnectorItem, ConnectorItem *toConnectorItem, Wire *wire, QUndoCommand *parentCommand)
void setWireVisible (Wire *wire)
void shiftHoles ()
bool updateOK (ConnectorItem *, ConnectorItem *)
ViewLayer::ViewLayerPlacement wireViewLayerPlacement (ConnectorItem *)
Protected Member Functions inherited from SketchWidget
void addToScene (ItemBase *item, ViewLayer::ViewLayerID viewLayerID)
void addViewLayersAux (const LayerList &, const LayerList &layersFromBelow, float startZ=1.5)
void addWireExtras (long newID, QDomElement &view, QUndoCommand *parentCommand)
void alignLoc (QPointF &loc, const QPointF startPoint, const QPointF newLoc, const QPointF originalLoc)
QPointF calcNewLoc (ItemBase *moveBase, ItemBase *detachFrom)
virtual bool canAlignToTopLeft (ItemBase *)
bool canConnect (ItemBase *from, ItemBase *to)
void categorizeDragLegs (bool rubberBandLegEnabled)
void categorizeDragWires (QSet< Wire * > &wires, QList< ItemBase * > &freeWires)
void changeConnectionAux (long fromID, const QString &fromConnectorID, long toID, const QString &toConnectorID, ViewLayer::ViewLayerPlacement, bool connect, bool updateConnections)
void changeLegAux (long fromID, const QString &fromConnectorID, const QPolygonF &, bool reset, bool relative, bool active, const QString &why)
bool checkAutoscroll (QPoint globalPos)
void checkFit (ModelPart *newModelPart, ItemBase *itemBase, long newID, QHash< ConnectorItem *, Connector * > &found, QList< ConnectorItem * > &notFound, QHash< ConnectorItem *, ConnectorItem * > &m2f, QHash< ConnectorItem *, Connector * > &byWire, QHash< QString, QPolygonF > &legs, QHash< QString, ConnectorItem * > &formerLegs, QUndoCommand *parentCommand)
void checkFitAux (ItemBase *tempItemBase, ItemBase *itemBase, long newID, QHash< ConnectorItem *, Connector * > &found, QList< ConnectorItem * > &notFound, QHash< ConnectorItem *, ConnectorItem * > &m2f, QHash< ConnectorItem *, Connector * > &byWire, QHash< QString, QPolygonF > &legs, QHash< QString, ConnectorItem * > &formerLegs, QUndoCommand *parentCommand)
bool checkMoved (bool wait)
virtual bool checkUnder ()
bool checkUpdateRatsnest (QList< ConnectorItem * > &connectorItems)
void cleanupRatsnests (QList< QPointer< ConnectorItem > > &connectorItems, bool connect)
void clearDragWireTempCommand ()
void clearHoldingSelectItem ()
void clearTemporaries ()
void clickBackground (QMouseEvent *)
virtual bool collectFemaleConnectees (ItemBase *, QSet< ItemBase * > &)
QList< ItemBase * > collectSuperSubs (ItemBase *)
void contextMenuEvent (QContextMenuEvent *)
void continueZChange (QList< ItemBase * > &bases, int start, int end, bool(*test)(int current, int start), int inc, const QString &text)
void continueZChangeAux (QList< ItemBase * > &bases, const QString &text)
void continueZChangeMax (QList< ItemBase * > &bases, int start, int end, bool(*test)(int current, int start), int inc, const QString &text)
void copyAux (QList< ItemBase * > &bases, bool saveBoundingRects)
void copyDrop ()
bool createOneTrace (Wire *wire, ViewGeometry::WireFlag flag, bool allowAny, QList< Wire * > &done, bool useLastWireColor, QUndoCommand *parentCommand)
void createTrace (Wire *fromWire, const QString &commandString, ViewGeometry::WireFlag, bool useLastWireColor)
bool currentlyInfoviewed (ItemBase *item)
void cutDeleteAux (QString undoStackMessage, bool minus, Wire *wire)
void deleteAux (QSet< ItemBase * > &deletedItems, QUndoCommand *parentCommand, bool doPush)
virtual bool disconnectFromFemale (ItemBase *item, QHash< long, ItemBase * > &savedItems, ConnectorPairHash &, bool doCommand, bool rubberBandLegEnabled, QUndoCommand *parentCommand)
void dragEnterEvent (QDragEnterEvent *)
bool dragEnterEventAux (QDragEnterEvent *)
bool draggingWireEnd ()
void dragLeaveEvent (QDragLeaveEvent *)
void dragMoveEvent (QDragMoveEvent *)
void dragMoveHighlightConnector (QPoint eventPos)
void dragRatsnestChanged ()
void dragWireChanged (class Wire *wire, ConnectorItem *from, ConnectorItem *to)
void drawBackground (QPainter *painter, const QRectF &rect)
void dropEvent (QDropEvent *)
void dropItemEvent (QDropEvent *event)
ChangeConnectionCommand * extendChangeConnectionCommand (BaseCommand::CrossViewType, long fromID, const QString &fromConnectorID, long toID, const QString &toConnectorID, ViewLayer::ViewLayerPlacement, bool connect, QUndoCommand *parent)
ChangeConnectionCommand * extendChangeConnectionCommand (BaseCommand::CrossViewType, ConnectorItem *fromConnectorItem, ConnectorItem *toConnectorItem, ViewLayer::ViewLayerPlacement, bool connect, QUndoCommand *parentCommand)
virtual void findAlignmentAnchor (ItemBase *originatingItem, QHash< long, ItemBase * > &savedItems, QHash< Wire *, ConnectorItem * > &savedWires)
ConnectorItem * findConnectorItem (ItemBase *item, const QString &connectorID, ViewLayer::ViewLayerPlacement)
virtual void findConnectorsUnder (ItemBase *item)
long findPartOrWire (long itemID)
QGraphicsItem * getClickedItem (QList< QGraphicsItem * > &items)
ViewLayer::ViewLayerID getConnectorViewLayerID ()
ViewLayer::ViewLayerID getNoteViewLayerID ()
ViewLayer::ViewLayerID getPartViewLayerID ()
ViewLayer::ViewLayerID getRulerViewLayerID ()
ViewLayer::ViewLayerID getViewLayerID (ModelPart *, ViewLayer::ViewID, ViewLayer::ViewLayerPlacement)
double gridSizeInches ()
void handleConnect (QDomElement &connect, ModelPart *, const QString &fromConnectorID, ViewLayer::ViewLayerID, QStringList &alreadyConnected, QHash< long, ItemBase * > &newItems, QUndoCommand *parentCommand, bool seekOutsideConnections)
virtual const QString & hoverEnterWireConnectorMessage (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
void initBackgroundColor ()
void keyPressEvent (QKeyEvent *)
void keyReleaseEvent (QKeyEvent *)
void killDroppingItem ()
QString makeMoveSVG (double printerScale, double dpi, QPointF &offset)
void makeRatsnestViewGeometry (ViewGeometry &viewGeometry, ConnectorItem *source, ConnectorItem *dest)
void makeSwapWire (SketchWidget *, ItemBase *, long newID, ConnectorItem *fromConnectorItem, ConnectorItem *toConnectorItem, Connector *newConnector, QUndoCommand *parentCommand)
QString makeWireSVG (Wire *wire, QPointF offset, double dpi, double printerscale, bool blackOnly)
QString makeWireSVGAux (Wire *wire, double width, const QString &color, QPointF offset, double dpi, double printerScale, bool blackOnly, bool dashed)
bool matchesLayer (ModelPart *modelPart)
void mouseDoubleClickEvent (QMouseEvent *)
void mouseMoveEvent (QMouseEvent *)
virtual void mousePressEvent (QMouseEvent *)
void mouseReleaseEvent (QMouseEvent *)
bool moveByArrow (double dx, double dy, QKeyEvent *)
void moveItems (QPoint globalPos, bool checkAutoScroll, bool rubberBandLegEnabled)
void moveLegBendpoints (bool undoOnly, QUndoCommand *parentCommand)
void moveLegBendpointsAux (ConnectorItem *connectorItem, bool undoOnly, QUndoCommand *parentCommand)
AddItemCommand * newAddItemCommand (BaseCommand::CrossViewType crossViewType, ModelPart *, QString moduleID, ViewLayer::ViewLayerPlacement, ViewGeometry &viewGeometry, qint64 id, bool updateInfoView, long modelIndex, bool addSubparts, QUndoCommand *parent)
ItemBase * overSticky (ItemBase *)
void paintEvent (QPaintEvent *)
void partLabelChangedAux (ItemBase *pitem, const QString &oldText, const QString &newText)
void prepDeleteOtherProps (ItemBase *itemBase, long id, const QString &newModuleID, QMap< QString, QString > &propsMap, QUndoCommand *parentCommand)
void prepDeleteProps (ItemBase *itemBase, long id, const QString &newModuleID, QMap< QString, QString > &propsMap, QUndoCommand *parentCommand)
void prepDragBendpoint (Wire *, QPoint eventPos, bool dragCurve)
void prepDragWire (Wire *)
void prepMove (ItemBase *originatingItem, bool rubberBandLegEnabled, bool includeRatsnest)
void removeDragWire ()
QByteArray removeOutsideConnections (const QByteArray &itemData, QList< long > &modelIndexes)
void removeWire (Wire *w, QList< ConnectorItem * > &ends, QList< Wire * > &done, QUndoCommand *parentCommand)
QString renderToSVG (RenderThing &, const LayerList &)
QString renderToSVG (RenderThing &, QList< QGraphicsItem * > &itemsAndLabels)
void resizeBoard ()
void resizeEvent (QResizeEvent *)
void resizeWithHandle (ItemBase *itemBase, double mmW, double mmH)
bool resizingBoardPress (ItemBase *)
bool resizingBoardRelease ()
void rotateWire (Wire *, QTransform &rotation, QPointF center, bool undoOnly, QUndoCommand *parentCommand)
int selectAllItems (QSet< ItemBase * > &itemBases, const QString &msg)
void selectAllWiresFrom (ViewGeometry::WireFlag flag, QList< QGraphicsItem * > &items)
void setLastPaletteItemSelected (PaletteItem *paletteItem)
void setLastPaletteItemSelectedIf (ItemBase *itemBase)
void setupAutoscroll (bool moving)
void setUpSwapReconnect (SwapThing &, ItemBase *itemBase, long newID, bool master)
void showPartLabelsAux (bool show, QList< ItemBase * > &itemBases)
void squashShapes (QPointF scenePos)
bool startZChange (QList< ItemBase * > &bases)
bool swappedGender (ConnectorItem *originalConnectorItem, Connector *newConnector)
void turnOffAutoscroll ()
void unsquashShapes ()
bool viewportEvent (QEvent *)
virtual BaseCommand::CrossViewType wireSplitCrossView ()
Protected Member Functions inherited from InfoGraphicsView
QGraphicsItem * selectedAux ()
Protected Member Functions inherited from ZoomableGraphicsView
virtual void wheelEvent (QWheelEvent *event)
Protected Attributes
bool m_convertSchematic
bool m_oldSchematic
QTimer m_updateDotsTimer
Protected Attributes inherited from PCBSketchWidget
QHash< QString, QString > m_autorouterSettings
CleanType m_cleanType
QList< ConnectorItem * > * m_groundFillSeeds
QPointF m_jumperDragOffset
QPointer< class QuoteDialog > m_quoteDialog
QTimer m_requestQuoteTimer
QPointer< class JumperItem > m_resizingJumperItem
QPointer< class QuoteDialog > m_rolloverQuoteDialog
Protected Attributes inherited from SketchWidget
bool m_addDefaultParts = false
QPointer< ItemBase > m_addedDefaultPart
QList< ItemBase * > m_additionalSavedItems
QPointer< ItemBase > m_alignmentItem
QPointF m_alignmentStartPoint
bool m_alignToGrid = true
bool m_anyInRotation
QTimer m_arrowTimer
double m_arrowTotalX = 0.0
double m_arrowTotalY = 0.0
volatile int m_autoScrollCount = 0
int m_autoScrollThreshold = 0
QTimer m_autoScrollTimer
volatile int m_autoScrollX = 0
volatile int m_autoScrollY = 0
ViewGeometry m_bendpointVG
QPointer< Wire > m_bendpointWire
bool m_chainDrag = false
QList< ItemBase * > m_checkUnder
bool m_clearSceneRect = false
QPointer< ConnectorItem > m_connectorDragConnector
QPointer< Wire > m_connectorDragWire
ViewLayer::ViewLayerID m_connectorViewLayerID
bool m_current = false
bool m_curvyWires = false
QPoint m_dragBendpointPos
QPointer< Wire > m_dragBendpointWire
bool m_dragCurve = false
bool m_draggingBendpoint = false
QPointer< ItemBase > m_droppingItem
QPointF m_droppingOffset
bool m_droppingWire = false
bool m_everZoomed = false
QPoint m_globalPos
QColor m_gridColor
double m_gridSizeInches = 0.0
QString m_gridSizeText
class SelectItemCommand * m_holdingSelectItemCommand = nullptr
int m_ignoreSelectionChangeEvents = 0
QList< QGraphicsItem * > m_inFocus
bool m_infoViewOnHover
QMenu * m_itemMenu = nullptr
QString m_lastColorSelected
QPointer< ConnectorItem > m_lastHoverEnterConnectorItem
QPointer< ItemBase > m_lastHoverEnterItem
QPointer< PaletteItem > m_lastPaletteItemSelected
bool m_middleMouseIsPressed = false
QPointF m_mousePressGlobalPos
QPointF m_mousePressScenePos
ConnectorPairHash m_moveDisconnectedFromFemale
int m_moveEventCount = 0
QPointer< ItemBase > m_moveReferenceItem
bool m_movingByArrow = false
bool m_movingByMouse = false
QPointer< QGraphicsSvgItem > m_movingItem
QPointF m_movingSVGOffset
QPointer< QSvgRenderer > m_movingSVGRenderer
ViewLayer::ViewLayerID m_noteViewLayerID
QPointer< ItemBase > m_originatingItem
ViewLayer::ViewLayerID m_partViewLayerID
int m_pasteCount = 0
QPointF m_pasteOffset
bool m_pasting = false
QList< QPointer< ConnectorItem > > m_ratsnestCacheConnect
QList< QPointer< ConnectorItem > > m_ratsnestCacheDisconnect
double m_ratsnestOpacity = 0.0
QList< QPointer< ConnectorItem > > m_ratsnestUpdateConnect
QList< QPointer< ConnectorItem > > m_ratsnestUpdateDisconnect
double m_ratsnestWidth = 0.0
QPointer< class ReferenceModel > m_referenceModel
QPointer< class ResizableBoard > m_resizingBoard
RoutingStatus m_routingStatus
bool m_rubberBandLegWasEnabled = false
ViewLayer::ViewLayerID m_rulerViewLayerID
QHash< long, ItemBase * > m_savedItems
QHash< Wire *, ConnectorItem * > m_savedWires
QString m_shortName
bool m_showGrid = true
QPointer< SizeItem > m_sizeItem
QPointer< SketchModel > m_sketchModel
bool m_spaceBarIsPressed = false
bool m_spaceBarWasPressed = false
QList< QPointer< ItemBase > > m_squashShapes
StatusConnectStatus m_statusConnectState = StatusConnectNotTried
QMultiHash< ItemBase *, ConnectorItem * > m_stretchingLegs
class SelectItemCommand * m_tempDragWireCommand = nullptr
QList< QGraphicsItem * > m_temporaries
class WaitPushUndoStack * m_undoStack = nullptr
ViewLayer::ViewID m_viewID
LayerHash m_viewLayers
QHash< ViewLayer::ViewLayerID, bool > m_viewLayerVisibility
QString m_viewName
QMenu * m_wireMenu = nullptr
ViewLayer::ViewLayerID m_wireViewLayerID
float m_z
double m_zoom = 100
Protected Attributes inherited from InfoGraphicsView
int m_boardLayers
bool m_hoverEnterConnectorMode
bool m_hoverEnterMode
class HtmlInfoView * m_infoView
Qt::Orientations m_smdOrientation
Protected Attributes inherited from ZoomableGraphicsView
bool m_acceptWheelEvents
int m_maxScaleValue
int m_minScaleValue
double m_scaleValue
bool m_viewFromBelow
Static Protected Attributes
static QSizeF m_jumperItemSize = QSizeF(0, 0)
Static Protected Attributes inherited from PCBSketchWidget
static const char * FakeTraceProperty = "FakeTrace"
static QSizeF m_jumperItemSize = QSizeF(0, 0)
Static Protected Attributes inherited from SketchWidget
static constexpr int DragAutoScrollThreshold = 10
static constexpr int MoveAutoScrollThreshold = 5
Static Protected Attributes inherited from ZoomableGraphicsView
static WheelMapping m_wheelMapping
Additional Inherited Members
Public Types inherited from PCBSketchWidget
enum CleanType { noClean, ninetyClean }
Public Types inherited from ZoomableGraphicsView
enum WheelMapping { ScrollPrimary, ZoomPrimary, WheelMappingCount }
Signals inherited from PCBSketchWidget
void boardDeletedSignal ()
void copperFillSignal ()
void groundFillSignal ()
void subSwapSignal (SketchWidget *, ItemBase *, const QString &newModuleID, ViewLayer::ViewLayerPlacement, long &newID, QUndoCommand *parentCommand)
Signals inherited from SketchWidget
void addSubpartSignal (long id, long subpartID, bool doEmit)
void canConnectSignal (Wire *from, ItemBase *to, bool &connect)
void changeBoardLayersSignal (int, bool doEmit)
void changeConnectionSignal (long fromID, QString fromConnectorID, long toID, QString toConnectorID, ViewLayer::ViewLayerPlacement, bool connect, bool updateConnections)
void checkStickySignal (long id, bool doEmit, bool checkCurrent, CheckStickyCommand *)
void cleanupRatsnestsSignal (bool doEmit)
void cleanUpWiresSignal (CleanUpWiresCommand *)
void clearSelectionSignal ()
void clickedItemCandidateSignal (QGraphicsItem *, bool &ok)
void collectRatsnestSignal (QList< SketchWidget * > &foreignSketchWidgets)
void copyBoundingRectsSignal (QHash< QString, QRectF > &)
void cursorLocationSignal (double xinches, double yinches, double width=0.0, double height=0.0)
void deleteTracesSignal (QSet< ItemBase * > &deletedItems, QHash< ItemBase *, SketchWidget * > &otherDeletedItems, QList< long > &deletedIDs, bool isForeign, QUndoCommand *parentCommand)
void disconnectAllSignal (QList< ConnectorItem * >, QHash< ItemBase *, SketchWidget * > &itemsToDelete, QUndoCommand *parentCommand)
void dropPasteSignal (SketchWidget *)
void dropSignal (const QPoint &pos)
void filenameIfSignal (QString &filename)
void getDroppedItemViewLayerPlacementSignal (ModelPart *modelPart, ViewLayer::ViewLayerPlacement &)
void itemAddedSignal (ModelPart *, ItemBase *, ViewLayer::ViewLayerPlacement, const ViewGeometry &, long id, SketchWidget *dropOrigin)
void itemDeletedSignal (long id)
void itemMovedSignal (ItemBase *)
void itemSelectedSignal (long id, bool state)
void makeDeleteItemCommandFinalSignal (ItemBase *itemBase, bool foreign, QUndoCommand *parentCommand)
void makeDeleteItemCommandPrepSignal (ItemBase *itemBase, bool foreign, QUndoCommand *parentCommand)
void movingSignal (SketchWidget *, QUndoCommand *parentCommand)
void packItemsSignal (int columns, const QList< long > &ids, QUndoCommand *parent, bool doEmit)
void ratsnestConnectSignal (long id, const QString &connectorID, bool connect, bool doEmit)
void removeRatsnestSignal (QList< struct ConnectorEdge * > &cutSet, QUndoCommand *parentCommand)
void resizedSignal (ItemBase *)
void resizeSignal ()
void routingStatusSignal (SketchWidget *, const RoutingStatus &)
void selectAllItemsSignal (bool state, bool doEmit)
void selectionChangedSignal ()
void setInstanceTitleSignal (long id, const QString &oldTitle, const QString &newTitle, bool isUndoable, bool doEmit)
void setPropSignal (long itemID, const QString &prop, const QString &value, bool doRedraw, bool doEmit)
void setResistanceSignal (long itemID, QString resistance, QString pinSpacing, bool doEmit)
void showing (SketchWidget *)
void showLabelFirstTimeSignal (long itemID, bool show, bool doEmit)
void statusMessageSignal (QString, int timeout)
void swapBoardImageSignal (SketchWidget *sketchWidget, ItemBase *itemBase, const QString &filename, const QString &moduleID, bool addName)
void swapStartSignal (SwapThing &swapThing, bool master)
void updateLayerMenuSignal ()
void updatePartLabelInstanceTitleSignal (long itemID)
void wireConnectedSignal (long fromID, QString fromConnectorID, long toID, QString toConnectorID)
void wireDisconnectedSignal (long fromID, QString fromConnectorID)
Signals inherited from InfoGraphicsView
void changePinLabelsSignal (ItemBase *, bool singleRow)
void newWireSignal (Wire *)
void setActiveConnectorItemSignal (ConnectorItem *)
void setActiveWireSignal (Wire *)
void setVoltageSignal (double, bool doEmit)
void swapSignal (const QString &family, const QString &prop, QMap< QString, QString > &propsMap, ItemBase *)
Signals inherited from ZoomableGraphicsView
void wheelSignal ()
void zoomChanged (double zoom)
void zoomOutOfRange (double zoom)
Static Public Member Functions inherited from SketchWidget
static ViewLayer::ViewLayerID defaultConnectorLayer (ViewLayer::ViewID viewId)
Static Public Member Functions inherited from InfoGraphicsView
static InfoGraphicsView * getInfoGraphicsView (QGraphicsItem *)
Static Public Member Functions inherited from ZoomableGraphicsView
static void setWheelMapping (WheelMapping)
static WheelMapping wheelMapping ()
Static Public Attributes inherited from SketchWidget
static bool m_blockUI = false
static constexpr int PropChangeDelay = 100
Static Public Attributes inherited from ZoomableGraphicsView
static const int MaxScaleValue = 3000
Protected Types inherited from SketchWidget
enum StatusConnectStatus { StatusConnectNotTried, StatusConnectSucceeded, StatusConnectFailed }
Static Protected Member Functions inherited from PCBSketchWidget
static int calcDistance (Wire *wire, ConnectorItem *end, int distance, QList< Wire * > &distanceWires, bool &fromConnector0)
static int calcDistanceAux (ConnectorItem *from, ConnectorItem *to, int distance, QList< Wire * > &distanceWires)
static void calcDistances (Wire *wire, QList< ConnectorItem * > &ends)
static void clearDistances ()
Static Protected Member Functions inherited from SketchWidget
static bool greaterThan (int a, int b)
static bool lessThan (int a, int b)
Properties inherited from SketchWidget
QColor gridColor
double ratsnestOpacity
double ratsnestWidth
Constructor & Destructor Documentation
SchematicSketchWidget()
SchematicSketchWidget::SchematicSketchWidget (ViewLayer::ViewID viewID, QWidget * parent = 0)
References SketchWidget::initBackgroundColor(), PCBSketchWidget::m_cleanType, m_convertSchematic, m_oldSchematic, SketchWidget::m_shortName, m_updateDotsTimer, SketchWidget::m_viewName, PCBSketchWidget::ninetyClean, and updateBigDots().
Member Function Documentation
acceptsTrace()
bool SchematicSketchWidget::acceptsTrace (const ViewGeometry & viewGeometry) virtual
Reimplemented from PCBSketchWidget.
References ViewGeometry::getSchematicTrace().
addDefaultParts()
void SchematicSketchWidget::addDefaultParts () virtual
Reimplemented from PCBSketchWidget.
References SketchWidget::addDefaultParts().
addViewLayers()
void SchematicSketchWidget::addViewLayers () virtual
Reimplemented from PCBSketchWidget.
References SketchWidget::addViewLayersAux(), ViewLayer::layersForView(), ViewLayer::layersForViewFromBelow(), ViewLayer::Schematic, ViewLayer::SchematicNote, ViewLayer::SchematicRuler, ViewLayer::SchematicTrace, ViewLayer::SchematicView, and SketchWidget::setViewLayerIDs().
attachedToBottomLayer()
bool SchematicSketchWidget::attachedToBottomLayer (ConnectorItem * connectorItem) virtual
Reimplemented from PCBSketchWidget.
References ConnectorItem::attachedToViewLayerID(), ViewLayer::Schematic, and ViewLayer::SchematicTrace.
attachedToTopLayer()
bool SchematicSketchWidget::attachedToTopLayer (ConnectorItem *) virtual
Reimplemented from PCBSketchWidget.
autorouteTypePCB()
bool SchematicSketchWidget::autorouteTypePCB () virtual
Reimplemented from PCBSketchWidget.
canConnect()
bool SchematicSketchWidget::canConnect (Wire * from, ItemBase * to) protected virtual
Reimplemented from PCBSketchWidget.
canDropModelPart()
bool SchematicSketchWidget::canDropModelPart (ModelPart * modelPart) virtual
Reimplemented from PCBSketchWidget.
References ModelPart::Board, ModelPart::Breadboard, PCBSketchWidget::canDropModelPart(), SketchWidget::canDropModelPart(), ModuleIDNames::CopperBlockerModuleIDName, ModelPart::CopperFill, ModelPart::Hole, ModelPart::itemType(), ModelPart::Jumper, ModelPart::Logo, ModelPart::moduleID(), ModuleIDNames::PadModuleIDName, ModelPart::ResizableBoard, ModuleIDNames::SchematicFrameModuleIDName, ModelPart::SchematicSubpart, ModelPart::Symbol, and ModelPart::Via.
changeConnection()
void SchematicSketchWidget::changeConnection (long fromID, const QString & fromConnectorID, long toID, const QString & toConnectorID, ViewLayer::ViewLayerPlacement viewLayerPlacement, bool connect, bool doEmit, bool updateConnections) virtual
Reimplemented from SketchWidget.
References SketchWidget::changeConnection(), and m_updateDotsTimer.
checkDroppedModuleID()
QString SchematicSketchWidget::checkDroppedModuleID (const QString & moduleID) protected virtual
Reimplemented from PCBSketchWidget.
createTempWireForDragging()
Wire * SchematicSketchWidget::createTempWireForDragging (Wire * fromWire, ModelPart * wireModel, ConnectorItem * connectorItem, ViewGeometry & viewGeometry, ViewLayer::ViewLayerPlacement spec) virtual
Reimplemented from PCBSketchWidget.
References Wire::colorString(), SketchWidget::createTempWireForDragging(), PCBSketchWidget::FakeTraceProperty, Wire::opacity(), Wire::setColorString(), ViewGeometry::setSchematicTrace(), and traceColor().
createWireViewLayerPlacement()
ViewLayer::ViewLayerPlacement SchematicSketchWidget::createWireViewLayerPlacement (ConnectorItem * from, ConnectorItem * to) protected virtual
Reimplemented from PCBSketchWidget.
References SketchWidget::createWireViewLayerPlacement().
defaultGridSizeInches()
double SchematicSketchWidget::defaultGridSizeInches () virtual
Reimplemented from PCBSketchWidget.
References GraphicsUtils::StandardSchematicSeparation10thinMils.
ensureTraceLayersVisible()
void SchematicSketchWidget::ensureTraceLayersVisible () virtual
Reimplemented from PCBSketchWidget.
References SketchWidget::ensureLayerVisible(), and ViewLayer::SchematicTrace.
ensureTraceLayerVisible()
void SchematicSketchWidget::ensureTraceLayerVisible () virtual
Reimplemented from PCBSketchWidget.
References SketchWidget::ensureLayerVisible(), and ViewLayer::SchematicTrace.
extraRenderSvgStep()
void SchematicSketchWidget::extraRenderSvgStep (ItemBase * itemBase, QPointF offset, double dpi, double printerScale, QString & outputSvg) protected virtual
Reimplemented from SketchWidget.
References Wire::connector0(), Wire::connector1(), ConnectorItem::isBigDot(), makeCircleSVG(), and ConnectorItem::sceneAdjustedTerminalPoint().
generateCopperFillUnit()
QString SchematicSketchWidget::generateCopperFillUnit (ItemBase * itemBase, QPointF whereToStart) virtual
Reimplemented from PCBSketchWidget.
getAutorouterSettings()
QHash< QString, QString > SchematicSketchWidget::getAutorouterSettings () virtual
Reimplemented from PCBSketchWidget.
References SketchWidget::getAutorouterSettings().
getAutorouterTraceWidth()
double SchematicSketchWidget::getAutorouterTraceWidth () virtual
Reimplemented from PCBSketchWidget.
References getTraceWidth().
getBendpointWidths()
void SchematicSketchWidget::getBendpointWidths (class Wire * wire, double w, double & w1, double & w2, bool & negativeOffsetRect) virtual
Reimplemented from PCBSketchWidget.
References m_oldSchematic.
getDragWireViewLayerID()
ViewLayer::ViewLayerID SchematicSketchWidget::getDragWireViewLayerID (ConnectorItem *) virtual
Reimplemented from PCBSketchWidget.
References ViewLayer::SchematicTrace.
getDroppedItemViewLayerPlacement
void SchematicSketchWidget::getDroppedItemViewLayerPlacement (ModelPart * modelPart, ViewLayer::ViewLayerPlacement & viewLayerPlacement) protected slot
References SketchWidget::getDroppedItemViewLayerPlacement().
getKeepout()
double SchematicSketchWidget::getKeepout () virtual
Reimplemented from PCBSketchWidget.
References GraphicsUtils::SVGDPI.
getLabelFont()
void SchematicSketchWidget::getLabelFont (QFont & font, QColor & color, ItemBase *) virtual
Reimplemented from PCBSketchWidget.
References PCBSketchWidget::getLabelFontSizeSmall().
getLabelViewLayerID()
ViewLayer::ViewLayerID SchematicSketchWidget::getLabelViewLayerID (ItemBase *) protected virtual
Reimplemented from PCBSketchWidget.
References ViewLayer::SchematicLabel.
getRatsnestOpacity()
double SchematicSketchWidget::getRatsnestOpacity () protected
getRatsnestWidth()
double SchematicSketchWidget::getRatsnestWidth () protected
getTraceFlag()
ViewGeometry::WireFlag SchematicSketchWidget::getTraceFlag () virtual
Reimplemented from PCBSketchWidget.
References ViewGeometry::SchematicTraceFlag.
getTraceWidth()
double SchematicSketchWidget::getTraceWidth () virtual
Reimplemented from PCBSketchWidget.
References m_oldSchematic, GraphicsUtils::SVGDPI, TraceWidthMils, and TraceWidthMilsOld.
getViewLayerPlacement()
ViewLayer::ViewLayerPlacement SchematicSketchWidget::getViewLayerPlacement (ModelPart * modelPart, QDomElement & instance, QDomElement & view, ViewGeometry & viewGeometry) virtual
Reimplemented from PCBSketchWidget.
References SketchWidget::getViewLayerPlacement().
getWireStrokeWidth()
double SchematicSketchWidget::getWireStrokeWidth (Wire * , double wireWidth) virtual
Reimplemented from PCBSketchWidget.
References TraceHoverStrokeFactor.
getWireViewLayerID()
ViewLayer::ViewLayerID SchematicSketchWidget::getWireViewLayerID (const ViewGeometry & viewGeometry, ViewLayer::ViewLayerPlacement viewLayerPlacement) virtual
Reimplemented from PCBSketchWidget.
References ViewGeometry::getAnyTrace(), ViewGeometry::getRatsnest(), SketchWidget::getWireViewLayerID(), ViewLayer::SchematicTrace, and ViewLayer::SchematicWire.
hasBigDots()
bool SchematicSketchWidget::hasBigDots () virtual
Reimplemented from InfoGraphicsView.
includeSymbols()
bool SchematicSketchWidget::includeSymbols () virtual
Reimplemented from SketchWidget.
initWire()
void SchematicSketchWidget::initWire (Wire * wire, int penWidth) virtual
Reimplemented from PCBSketchWidget.
References ItemBase::getRatsnest(), getTraceWidth(), Wire::setColorString(), Wire::setPenWidth(), and TraceHoverStrokeFactor.
isInLayers()
bool SchematicSketchWidget::isInLayers (ConnectorItem * connectorItem, ViewLayer::ViewLayerPlacement viewLayerPlacement) virtual
Reimplemented from PCBSketchWidget.
isOldSchematic()
bool SchematicSketchWidget::isOldSchematic ()
References m_oldSchematic.
jumperItemSize()
QSizeF SchematicSketchWidget::jumperItemSize () virtual
Reimplemented from PCBSketchWidget.
References SketchWidget::addItem(), PaletteItemBase::boundingRect(), PCBSketchWidget::defaultViewLayerPlacement(), PCBSketchWidget::deleteItem(), ItemBase::getNextID(), m_jumperItemSize, ModuleIDNames::NetLabelModuleIDName, SketchWidget::referenceModel(), SymbolPaletteItem::setLabel(), ViewGeometry::setLoc(), and BaseCommand::SingleView.
loadFromModelParts()
void SchematicSketchWidget::loadFromModelParts (QList< ModelPart * > & modelParts, BaseCommand::CrossViewType crossViewType, QUndoCommand * parentCommand, bool offsetPaste, const QRectF * boundingRect, bool seekOutsideConnections, QList< long > & newIDs) virtual
Reimplemented from PCBSketchWidget.
References SketchWidget::loadFromModelParts().
makeCircleSVG()
QString SchematicSketchWidget::makeCircleSVG (QPointF p, double r, QPointF offset, double dpi, double printerScale) protected
resizeLabels()
void SchematicSketchWidget::resizeLabels ()
References PCBSketchWidget::getLabelFontSizeSmall(), ItemBase::hasPartLabel(), ItemBase::partLabel(), and PartLabel::setFontPointSize().
resizeWires()
void SchematicSketchWidget::resizeWires ()
References getTraceFlag(), getTraceWidth(), getWireStrokeWidth(), Wire::isTraceType(), and Wire::setWireWidth().
rotatePartLabels()
void SchematicSketchWidget::rotatePartLabels (double degrees, QTransform & transform, QPointF center, QUndoCommand * parentCommand) virtual
Reimplemented from PCBSketchWidget.
References PCBSketchWidget::rotatePartLabels().
routeBothSides()
bool SchematicSketchWidget::routeBothSides () virtual
Reimplemented from PCBSketchWidget.
routingLayers()
LayerList SchematicSketchWidget::routingLayers (ViewLayer::ViewLayerPlacement) virtual
Reimplemented from PCBSketchWidget.
References ViewLayer::Schematic.
sameElectricalLayer2()
bool SchematicSketchWidget::sameElectricalLayer2 (ViewLayer::ViewLayerID , ViewLayer::ViewLayerID) virtual
Reimplemented from PCBSketchWidget.
selectAllWires()
void SchematicSketchWidget::selectAllWires (ViewGeometry::WireFlag flag) protected virtual
Reimplemented from PCBSketchWidget.
References SketchWidget::selectAllWires().
setAutorouterSettings()
void SchematicSketchWidget::setAutorouterSettings (QHash< QString, QString > & autorouterSettings) virtual
Reimplemented from PCBSketchWidget.
References PCBSketchWidget::autorouterSettings(), and SketchWidget::setAutorouterSettings().
setClipEnds()
void SchematicSketchWidget::setClipEnds (ClipableWire * vw, bool) virtual
Reimplemented from PCBSketchWidget.
References ClipableWire::setClipEnds().
setConvertSchematic()
void SchematicSketchWidget::setConvertSchematic (bool convert)
References m_convertSchematic.
setInstanceTitle
void SchematicSketchWidget::setInstanceTitle (long id, const QString & oldTitle, const QString & newTitle, bool isUndoable, bool doEmit) slot
References SketchWidget::findItem(), SymbolPaletteItem::isOnlyNetLabel(), SketchWidget::setInstanceTitle(), setProp(), and ItemBase::TranslatedPropertyNames.
setNewPartVisible()
void SchematicSketchWidget::setNewPartVisible (ItemBase * itemBase) virtual
Reimplemented from PCBSketchWidget.
References ModelPart::Breadboard, ModelPart::CopperFill, ModelPart::Hole, ItemBase::itemType(), ModelPart::Jumper, ModelPart::Logo, ItemBase::moduleID(), ModuleIDNames::PadModuleIDName, ItemBase::setEverVisible(), and ModelPart::Via.
setOldSchematic()
void SchematicSketchWidget::setOldSchematic (bool old)
References m_oldSchematic.
setProp
void SchematicSketchWidget::setProp (ItemBase * itemBase, const QString & propName, const QString & translatedPropName, const QString & oldValue, const QString & newValue, bool redraw) slot
References NonConnectorItem::attachedTo(), ConnectorItem::connectedToItems(), SymbolPaletteItem::connector0(), SymbolPaletteItem::getLabel(), ItemBase::id(), SymbolPaletteItem::isOnlyNetLabel(), SketchWidget::m_undoStack, SketchWidget::PropChangeDelay, CleanUpWiresCommand::RedoOnly, SketchWidget::removeWire(), SketchWidget::setProp(), CleanUpWiresCommand::UndoOnly, and WaitPushUndoStack::waitPush().
setVoltage
void SchematicSketchWidget::setVoltage (double voltage, bool doEmit) slot
References NonConnectorItem::attachedTo(), ConnectorItem::connectedToItems(), SymbolPaletteItem::connector0(), SketchWidget::getSelectedPart(), ItemBase::id(), ItemBase::itemType(), SketchWidget::m_undoStack, ItemBase::moduleID(), SketchWidget::PropChangeDelay, CleanUpWiresCommand::RedoOnly, SketchWidget::removeWire(), ModelPart::Symbol, CleanUpWiresCommand::UndoOnly, SymbolPaletteItem::voltage(), and WaitPushUndoStack::waitPush().
tidyWires()
void SchematicSketchWidget::tidyWires () virtual
Reimplemented from SketchWidget.
References ItemBase::getViewGeometry(), ViewGeometry::SchematicTraceFlag, and ViewGeometry::wireFlags().
traceColor() [1/2]
const QString & SchematicSketchWidget::traceColor (ConnectorItem * forColor) virtual
Reimplemented from PCBSketchWidget.
References SketchWidget::m_lastColorSelected, and SchematicTraceColor.
traceColor() [2/2]
const QString & SchematicSketchWidget::traceColor (ViewLayer::ViewLayerPlacement) virtual
Reimplemented from PCBSketchWidget.
References SchematicTraceColor.
updateBigDots
void SchematicSketchWidget::updateBigDots () protected slot
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToItemType(), ConnectorItem::restoreColor(), and ModelPart::Wire.
viewGeometryConversionHack()
void SchematicSketchWidget::viewGeometryConversionHack (ViewGeometry & viewGeometry, ModelPart * modelPart) protected virtual
Reimplemented from SketchWidget.
References SketchWidget::addItemAuxTemp(), ItemBase::flipItem(), ItemBase::getViewGeometry(), GraphicsUtils::isFlipped(), ModelPart::itemType(), ItemBase::layerKin(), m_convertSchematic, ViewLayer::NewTop, ItemBase::rotateItem(), ItemBase::saveGeometry(), ViewGeometry::setTransform(), ViewGeometry::transform(), SketchWidget::viewID(), and ModelPart::Wire.
Member Data Documentation
m_convertSchematic
bool SchematicSketchWidget::m_convertSchematic protected
m_jumperItemSize
QSizeF SchematicSketchWidget::m_jumperItemSize = QSizeF(0, 0) static protected
m_oldSchematic
bool SchematicSketchWidget::m_oldSchematic protected
m_updateDotsTimer
QTimer SchematicSketchWidget::m_updateDotsTimer protected
The documentation for this class was generated from the following files:
sketch/schematicsketchwidget.h
sketch/schematicsketchwidget.cpp