Fritzing: SchematicRectConstants Class Reference
SchematicRectConstants Class Reference
#include <schematicrectconstants.h>
Static Public Member Functions
static QString genSchematicDIP (QList< QDomElement > &powers, QList< QDomElement > &grounds, QList< QDomElement > &lefts, QList< QDomElement > &rights, QList< QDomElement > &vias, QStringList &busNames, QString &boardName, bool usingParam, bool genericSMD, QString(*getConnectorName)(const QDomElement &))
static QString simpleGetConnectorName (const QDomElement &element)
Static Public Attributes
static const QString FontFamily
static const double LabelTextHeight = 1.49930556
static const double LabelTextSpace = 0.1
static const double NewUnit = 0.1 * 25.4
static const double PinBigTextHeight = 1.23472222
static const QString PinColor
static const double PinSmallTextHeight = 0.881944444
static const double PinSmallTextVert = -PinWidth / 2
static const QString PinTextColor
static const double PinTextIndent = PinWidth * 2
static const double PinTextVert = PinWidth * 1
static const double PinWidth = 0.246944
static const QString RectFillColor
static const QString RectStrokeColor
static const double RectStrokeWidth = 0.3175
static const QString TitleColor
Member Function Documentation
genSchematicDIP()
QString SchematicRectConstants::genSchematicDIP (QList< QDomElement > & powers, QList< QDomElement > & grounds, QList< QDomElement > & lefts, QList< QDomElement > & rights, QList< QDomElement > & vias, QStringList & busNames, QString & boardName, bool usingParam, bool genericSMD, QString(*)(const QDomElement &) getConnectorName) static
References TextUtils::escapeAnd(), FontFamily, TextUtils::makeSVGHeader(), NewUnit, PinBigTextHeight, PinColor, PinSmallTextHeight, PinTextIndent, PinTextVert, PinWidth, qMax(), RectStrokeWidth, schematicPinNumber(), schematicPinText(), and SW().
simpleGetConnectorName()
QString SchematicRectConstants::simpleGetConnectorName (const QDomElement & element) static
References TextUtils::escapeAnd().
Member Data Documentation
FontFamily
const QString SchematicRectConstants::FontFamily static
LabelTextHeight
const double SchematicRectConstants::LabelTextHeight = 1.49930556 static
LabelTextSpace
const double SchematicRectConstants::LabelTextSpace = 0.1 static
NewUnit
const double SchematicRectConstants::NewUnit = 0.1 * 25.4 static
PinBigTextHeight
const double SchematicRectConstants::PinBigTextHeight = 1.23472222 static
PinColor
const QString SchematicRectConstants::PinColor static
PinSmallTextHeight
const double SchematicRectConstants::PinSmallTextHeight = 0.881944444 static
PinSmallTextVert
const double SchematicRectConstants::PinSmallTextVert = -PinWidth / 2 static
PinTextColor
const QString SchematicRectConstants::PinTextColor static
PinTextIndent
const double SchematicRectConstants::PinTextIndent = PinWidth * 2 static
PinTextVert
const double SchematicRectConstants::PinTextVert = PinWidth * 1 static
PinWidth
const double SchematicRectConstants::PinWidth = 0.246944 static
RectFillColor
const QString SchematicRectConstants::RectFillColor static
RectStrokeColor
const QString SchematicRectConstants::RectStrokeColor static
RectStrokeWidth
const double SchematicRectConstants::RectStrokeWidth = 0.3175 static
TitleColor
const QString SchematicRectConstants::TitleColor static
The documentation for this class was generated from the following files:
utils/schematicrectconstants.h
utils/schematicrectconstants.cpp