Fritzing: utils/misc.cpp File Reference
misc.cpp File Reference
#include "misc.h"
#include <QDesktopServices>
#include <QCoreApplication>
#include <QDir>
#include <QSettings>
#include <QTextStream>
#include <QSet>
Functions
Qt::KeyboardModifier altOrMetaModifier ()
const QStringList & fritzingBundleExtensions ()
const QStringList & fritzingExtensions ()
static void initializeExtensionList ()
bool isParent (QObject *candidateParent, QObject *candidateChild)
Variables
static QStringList p_fritzingBundleExtensions
static QStringList p_fritzingExtensions
Function Documentation
altOrMetaModifier()
Qt::KeyboardModifier altOrMetaModifier ()
fritzingBundleExtensions()
const QStringList& fritzingBundleExtensions ()
References initializeExtensionList(), and p_fritzingBundleExtensions.
fritzingExtensions()
const QStringList& fritzingExtensions ()
References initializeExtensionList(), and p_fritzingExtensions.
initializeExtensionList()
static void initializeExtensionList () inline static
References FritzingBinExtension(), FritzingBundledBinExtension(), FritzingBundledPartExtension(), FritzingBundleExtension(), FritzingPartExtension(), FritzingSketchExtension(), p_fritzingBundleExtensions, and p_fritzingExtensions.
isParent()
bool isParent (QObject * candidateParent, QObject * candidateChild)
Variable Documentation
p_fritzingBundleExtensions
QStringList p_fritzingBundleExtensions static
p_fritzingExtensions
QStringList p_fritzingExtensions static