Fritzing: FSvgRenderer Class Reference
FSvgRenderer Class Reference
#include <fsvgrenderer.h>
Public Member Functions
FSvgRenderer (QObject *parent=0)
~FSvgRenderer ()
QSizeF defaultSizeF ()
bool fastLoad (const QByteArray &contents)
constexpr const QString & filename () const noexcept
QByteArray finalLoad (QByteArray &cleanContents, const QString &filename)
QByteArray loadSvg (const LoadInfo &)
QByteArray loadSvg (const QString &filename)
QByteArray loadSvg (const QByteArray &contents, const LoadInfo &)
QByteArray loadSvg (const QByteArray &contents, const QString &filename, bool findNonConnectors)
bool loadSvgString (const QString &svg)
bool loadSvgString (const QString &svg, QString &newSvg)
bool setUpConnector (class SvgIdLayer *svgIdLayer, bool ignoreTerminalPoint, ViewLayer::ViewLayerPlacement)
QList< SvgIdLayer * > setUpNonConnectors (ViewLayer::ViewLayerPlacement)
Static Public Member Functions
static void cleanup ()
static QPixmap * getPixmap (QSvgRenderer *renderer, QSize size)
static void initNames ()
static QSizeF parseForWidthAndHeight (QXmlStreamReader &)
Static Public Attributes
static QString NonConnectorName
Protected Member Functions
void calcLeg (SvgIdLayer *, const QRectF &viewBox, ConnectorInfo *connectorInfo)
QPointF calcTerminalPoint (const QString &terminalId, const QRectF &connectorRect, bool ignoreTerminalPoint, const QRectF &viewBox, QMatrix &terminalMatrix)
void clearConnectorInfoHash (QHash< QString, ConnectorInfo * > &hash)
bool determineDefaultSize (QXmlStreamReader &)
ConnectorInfo * getConnectorInfo (const QString &connectorID)
bool initConnectorInfo (QDomDocument &, const LoadInfo &)
void initConnectorInfoAux (QDomElement &element, const LoadInfo &)
bool initConnectorInfoCircle (QDomElement &element, ConnectorInfo *connectorInfo, const QString &filename)
bool initConnectorInfoPath (QDomElement &element, ConnectorInfo *connectorInfo, const QString &filename)
ConnectorInfo * initConnectorInfoStruct (QDomElement &connectorElement, const QString &filename, bool parsePaths)
bool initConnectorInfoStructAux (QDomElement &, ConnectorInfo *connectorInfo, const QString &filename, bool parsePaths)
void initLegInfoAux (QDomElement &element, const LoadInfo &, bool &gotOne)
bool initLegInfoAux (QDomElement &element, ConnectorInfo *connectorInfo)
void initNonConnectorInfo (QDomDocument &domDocument, const QString &filename)
void initNonConnectorInfoAux (QDomElement &element, const QString &filename)
void initTerminalInfoAux (QDomElement &element, const LoadInfo &)
QByteArray loadAux (const QByteArray &contents, const LoadInfo &)
Protected Attributes
QHash< QString, ConnectorInfo * > m_connectorInfoHash
QSizeF m_defaultSizeF
QString m_filename
QHash< QString, ConnectorInfo * > m_nonConnectorInfoHash
Constructor & Destructor Documentation
FSvgRenderer()
FSvgRenderer::FSvgRenderer (QObject * parent = 0)
References m_defaultSizeF.
~FSvgRenderer()
FSvgRenderer::~FSvgRenderer ()
References clearConnectorInfoHash(), m_connectorInfoHash, and m_nonConnectorInfoHash.
Member Function Documentation
calcLeg()
void FSvgRenderer::calcLeg (SvgIdLayer * svgIdLayer, const QRectF & viewBox, ConnectorInfo * connectorInfo) protected
References defaultSizeF(), GraphicsUtils::distanceSqd(), ConnectorInfo::legColor, ConnectorInfo::legLine, ConnectorInfo::legMatrix, ConnectorInfo::legStrokeWidth, SvgIdLayer::m_legColor, SvgIdLayer::m_legId, SvgIdLayer::m_legLine, and SvgIdLayer::m_legStrokeWidth.
calcTerminalPoint()
QPointF FSvgRenderer::calcTerminalPoint (const QString & terminalId, const QRectF & connectorRect, bool ignoreTerminalPoint, const QRectF & viewBox, QMatrix & terminalMatrix) protected
References DebugDialog::debug(), and defaultSizeF().
cleanup()
void FSvgRenderer::cleanup () static
clearConnectorInfoHash()
void FSvgRenderer::clearConnectorInfoHash (QHash< QString, ConnectorInfo * > & hash) protected
defaultSizeF()
QSizeF FSvgRenderer::defaultSizeF ()
References m_defaultSizeF.
determineDefaultSize()
bool FSvgRenderer::determineDefaultSize (QXmlStreamReader & xml) protected
References m_defaultSizeF, parseForWidthAndHeight(), and GraphicsUtils::SVGDPI.
fastLoad()
bool FSvgRenderer::fastLoad (const QByteArray & contents)
filename()
constexpr const QString& FSvgRenderer::filename () const inline noexcept
References m_filename.
finalLoad()
QByteArray FSvgRenderer::finalLoad (QByteArray & cleanContents, const QString & filename)
References determineDefaultSize(), filename(), and m_filename.
getConnectorInfo()
ConnectorInfo * FSvgRenderer::getConnectorInfo (const QString & connectorID) protected
References m_connectorInfoHash, and VanillaConnectorInfo.
getPixmap()
QPixmap * FSvgRenderer::getPixmap (QSvgRenderer * renderer, QSize size) static
References defaultSizeF().
initConnectorInfo()
bool FSvgRenderer::initConnectorInfo (QDomDocument & domDocument, const LoadInfo & loadInfo) protected
References clearConnectorInfoHash(), initConnectorInfoAux(), initLegInfoAux(), initTerminalInfoAux(), LoadInfo::legIDs, m_connectorInfoHash, and LoadInfo::terminalIDs.
initConnectorInfoAux()
void FSvgRenderer::initConnectorInfoAux (QDomElement & element, const LoadInfo & loadInfo) protected
References LoadInfo::connectorIDs, LoadInfo::filename, initConnectorInfoStruct(), m_connectorInfoHash, and LoadInfo::parsePaths.
initConnectorInfoCircle()
bool FSvgRenderer::initConnectorInfoCircle (QDomElement & element, ConnectorInfo * connectorInfo, const QString & filename) protected
References TextUtils::elementToMatrix(), TextUtils::getStrokeWidth(), ConnectorInfo::gotCircle, ConnectorInfo::radius, and ConnectorInfo::strokeWidth.
initConnectorInfoPath()
bool FSvgRenderer::initConnectorInfoPath (QDomElement & element, ConnectorInfo * connectorInfo, const QString & filename) protected
References TextUtils::elementToMatrix(), finalLoad(), TextUtils::getStrokeWidth(), ConnectorInfo::gotCircle, ConnectorInfo::gotPath, int(), qMin(), ConnectorInfo::radius, and ConnectorInfo::strokeWidth.
initConnectorInfoStruct()
ConnectorInfo * FSvgRenderer::initConnectorInfoStruct (QDomElement & connectorElement, const QString & filename, bool parsePaths) protected
References TextUtils::elementToMatrix(), ConnectorInfo::gotCircle, ConnectorInfo::gotPath, initConnectorInfoStructAux(), ConnectorInfo::matrix, ConnectorInfo::radius, and ConnectorInfo::strokeWidth.
initConnectorInfoStructAux()
bool FSvgRenderer::initConnectorInfoStructAux (QDomElement & element, ConnectorInfo * connectorInfo, const QString & filename, bool parsePaths) protected
References initConnectorInfoCircle(), and initConnectorInfoPath().
initLegInfoAux() [1/2]
void FSvgRenderer::initLegInfoAux (QDomElement & element, const LoadInfo & loadInfo, bool & gotOne) protected
References LoadInfo::connectorIDs, TextUtils::elementToMatrix(), ConnectorInfo::legColor, LoadInfo::legIDs, ConnectorInfo::legLine, ConnectorInfo::legMatrix, ConnectorInfo::legStrokeWidth, and m_connectorInfoHash.
initLegInfoAux() [2/2]
bool FSvgRenderer::initLegInfoAux (QDomElement & element, ConnectorInfo * connectorInfo) protected
References ConnectorInfo::legLine, and ConnectorInfo::legStrokeWidth.
initNames()
void FSvgRenderer::initNames () static
References ConnectorInfo::gotCircle, ConnectorInfo::gotPath, and VanillaConnectorInfo.
initNonConnectorInfo()
void FSvgRenderer::initNonConnectorInfo (QDomDocument & domDocument, const QString & filename) protected
References clearConnectorInfoHash(), initNonConnectorInfoAux(), and m_nonConnectorInfoHash.
initNonConnectorInfoAux()
void FSvgRenderer::initNonConnectorInfoAux (QDomElement & element, const QString & filename) protected
References initConnectorInfoStruct(), m_nonConnectorInfoHash, and NonConnectorName.
initTerminalInfoAux()
void FSvgRenderer::initTerminalInfoAux (QDomElement & element, const LoadInfo & loadInfo) protected
References LoadInfo::connectorIDs, TextUtils::elementToMatrix(), m_connectorInfoHash, LoadInfo::terminalIDs, and ConnectorInfo::terminalMatrix.
loadAux()
QByteArray FSvgRenderer::loadAux (const QByteArray & contents, const LoadInfo & loadInfo) protected
References LoadInfo::colorElementID, LoadInfo::connectorIDs, DebugDialog::debug(), LoadInfo::filename, finalLoad(), TextUtils::findElementWithAttribute(), LoadInfo::findNonConnectors, SvgFileSplitter::fixColorRecurse(), TextUtils::fixMuch(), TextUtils::fixPixelDimensionsIn(), initConnectorInfo(), initNonConnectorInfo(), TextUtils::removeXMLEntities(), and LoadInfo::setColor.
loadSvg() [1/4]
QByteArray FSvgRenderer::loadSvg (const LoadInfo & loadInfo)
References LoadInfo::filename, and loadAux().
loadSvg() [2/4]
QByteArray FSvgRenderer::loadSvg (const QString & filename)
References loadSvg().
loadSvg() [3/4]
QByteArray FSvgRenderer::loadSvg (const QByteArray & contents, const LoadInfo & loadInfo)
References loadAux().
loadSvg() [4/4]
QByteArray FSvgRenderer::loadSvg (const QByteArray & contents, const QString & filename, bool findNonConnectors)
References loadAux().
loadSvgString() [1/2]
bool FSvgRenderer::loadSvgString (const QString & svg)
References loadSvg().
loadSvgString() [2/2]
bool FSvgRenderer::loadSvgString (const QString & svg, QString & newSvg)
References loadSvg().
parseForWidthAndHeight()
QSizeF FSvgRenderer::parseForWidthAndHeight (QXmlStreamReader & xml) static
References DebugDialog::debug(), and TextUtils::parseForWidthAndHeight().
setUpConnector()
bool FSvgRenderer::setUpConnector (class SvgIdLayer * svgIdLayer, bool ignoreTerminalPoint, ViewLayer::ViewLayerPlacement viewLayerPlacement)
References calcLeg(), calcTerminalPoint(), DebugDialog::debug(), defaultSizeF(), getConnectorInfo(), ConnectorInfo::gotCircle, ConnectorInfo::gotPath, SvgIdLayer::m_hybrid, SvgIdLayer::m_path, SvgIdLayer::m_radius, SvgIdLayer::m_strokeWidth, SvgIdLayer::m_svgId, SvgIdLayer::m_terminalId, SvgIdLayer::processed(), ConnectorInfo::radius, SvgIdLayer::setInvisible(), SvgIdLayer::setPointRect(), ConnectorInfo::strokeWidth, SvgIdLayer::svgVisible(), and ConnectorInfo::terminalMatrix.
setUpNonConnectors()
QList< SvgIdLayer * > FSvgRenderer::setUpNonConnectors (ViewLayer::ViewLayerPlacement viewLayerPlacement)
References defaultSizeF(), ConnectorInfo::gotCircle, m_nonConnectorInfoHash, SvgIdLayer::m_radius, SvgIdLayer::m_strokeWidth, SvgIdLayer::m_svgId, ViewLayer::PCBView, ConnectorInfo::radius, SvgIdLayer::setPointRect(), and ConnectorInfo::strokeWidth.
Member Data Documentation
m_connectorInfoHash
QHash<QString, ConnectorInfo *> FSvgRenderer::m_connectorInfoHash protected
m_defaultSizeF
QSizeF FSvgRenderer::m_defaultSizeF protected
m_filename
QString FSvgRenderer::m_filename protected
m_nonConnectorInfoHash
QHash<QString, ConnectorInfo *> FSvgRenderer::m_nonConnectorInfoHash protected
NonConnectorName
QString FSvgRenderer::NonConnectorName static
The documentation for this class was generated from the following files:
fsvgrenderer.h
fsvgrenderer.cpp