Fritzing: SketchWidget Class Reference
SketchWidget Class Reference
#include <sketchwidget.h>
Public Slots
void addSubpart (long id, long subpartid, bool doEmit)
virtual void changeBoardLayers (int layers, bool doEmit)
void changeWireColor (const QString newColor)
void changeWireWidthMils (const QString newWidth)
void checkSticky (long id, bool doEmit, bool checkCurrent, CheckStickyCommand *)
void cleanupRatsnests (bool doEmit)
void disconnectAllSlot (QList< ConnectorItem * >, QHash< ItemBase *, SketchWidget * > &itemsToDelete, QUndoCommand *parentCommand)
void incInstanceTitle (long id)
void packItems (int columns, const QList< long > &ids, QUndoCommand *parent, bool doEmit)
void ratsnestConnect (long id, const QString &connectorID, bool connect, bool doEmit)
virtual ItemBase * resizeBoard (long id, double w, double h)
void resizeBoard (double w, double h, bool doEmit)
void resizeJumperItem (long id, QPointF pos, QPointF c0, QPointF c1)
void selectAllItems (bool state, bool doEmit)
void setHoleSize (ItemBase *, const QString &propName, const QString &translatedPropName, const QString &oldValue, const QString &newValue, QRectF &oldRect, QRectF &newRect, bool redraw)
void setInstanceTitle (long id, const QString &oldTitle, const QString &newTitle, bool isUndoable, bool doEmit)
void setNoteText (long itemID, const QString &newText)
void setProp (long itemID, const QString &prop, const QString &value, bool redraw, bool doEmit)
virtual void setProp (ItemBase *, const QString &propName, const QString &translatedPropName, const QString &oldValue, const QString &newValue, bool redraw)
void setResistance (long itemID, QString resistance, QString pinSpacing, bool doEmit)
void setResistance (QString resistance, QString pinSpacing)
virtual void showLabelFirstTime (long itemID, bool show, bool doEmit)
void showPartLabel (long id, bool showIt)
void updateConnectors ()
Public Slots inherited from InfoGraphicsView
virtual void resizeBoard (double w, double h, bool doEmit)
virtual void setInstanceTitle (long id, const QString &oldTitle, const QString &newTitle, bool isUndoable, bool doEmit)
virtual void setVoltage (double, bool doEmit)
Signals
void addSubpartSignal (long id, long subpartID, bool doEmit)
void canConnectSignal (Wire *from, ItemBase *to, bool &connect)
void changeBoardLayersSignal (int, bool doEmit)
void changeConnectionSignal (long fromID, QString fromConnectorID, long toID, QString toConnectorID, ViewLayer::ViewLayerPlacement, bool connect, bool updateConnections)
void checkStickySignal (long id, bool doEmit, bool checkCurrent, CheckStickyCommand *)
void cleanupRatsnestsSignal (bool doEmit)
void cleanUpWiresSignal (CleanUpWiresCommand *)
void clearSelectionSignal ()
void clickedItemCandidateSignal (QGraphicsItem *, bool &ok)
void collectRatsnestSignal (QList< SketchWidget * > &foreignSketchWidgets)
void copyBoundingRectsSignal (QHash< QString, QRectF > &)
void cursorLocationSignal (double xinches, double yinches, double width=0.0, double height=0.0)
void deleteTracesSignal (QSet< ItemBase * > &deletedItems, QHash< ItemBase *, SketchWidget * > &otherDeletedItems, QList< long > &deletedIDs, bool isForeign, QUndoCommand *parentCommand)
void disconnectAllSignal (QList< ConnectorItem * >, QHash< ItemBase *, SketchWidget * > &itemsToDelete, QUndoCommand *parentCommand)
void dropPasteSignal (SketchWidget *)
void dropSignal (const QPoint &pos)
void filenameIfSignal (QString &filename)
void getDroppedItemViewLayerPlacementSignal (ModelPart *modelPart, ViewLayer::ViewLayerPlacement &)
void itemAddedSignal (ModelPart *, ItemBase *, ViewLayer::ViewLayerPlacement, const ViewGeometry &, long id, SketchWidget *dropOrigin)
void itemDeletedSignal (long id)
void itemMovedSignal (ItemBase *)
void itemSelectedSignal (long id, bool state)
void makeDeleteItemCommandFinalSignal (ItemBase *itemBase, bool foreign, QUndoCommand *parentCommand)
void makeDeleteItemCommandPrepSignal (ItemBase *itemBase, bool foreign, QUndoCommand *parentCommand)
void movingSignal (SketchWidget *, QUndoCommand *parentCommand)
void packItemsSignal (int columns, const QList< long > &ids, QUndoCommand *parent, bool doEmit)
void ratsnestConnectSignal (long id, const QString &connectorID, bool connect, bool doEmit)
void removeRatsnestSignal (QList< struct ConnectorEdge * > &cutSet, QUndoCommand *parentCommand)
void resizedSignal (ItemBase *)
void resizeSignal ()
void routingStatusSignal (SketchWidget *, const RoutingStatus &)
void selectAllItemsSignal (bool state, bool doEmit)
void selectionChangedSignal ()
void setInstanceTitleSignal (long id, const QString &oldTitle, const QString &newTitle, bool isUndoable, bool doEmit)
void setPropSignal (long itemID, const QString &prop, const QString &value, bool doRedraw, bool doEmit)
void setResistanceSignal (long itemID, QString resistance, QString pinSpacing, bool doEmit)
void showing (SketchWidget *)
void showLabelFirstTimeSignal (long itemID, bool show, bool doEmit)
void statusMessageSignal (QString, int timeout)
void swapBoardImageSignal (SketchWidget *sketchWidget, ItemBase *itemBase, const QString &filename, const QString &moduleID, bool addName)
void swapStartSignal (SwapThing &swapThing, bool master)
void updateLayerMenuSignal ()
void updatePartLabelInstanceTitleSignal (long itemID)
void wireConnectedSignal (long fromID, QString fromConnectorID, long toID, QString toConnectorID)
void wireDisconnectedSignal (long fromID, QString fromConnectorID)
Signals inherited from InfoGraphicsView
void changePinLabelsSignal (ItemBase *, bool singleRow)
void newWireSignal (Wire *)
void setActiveConnectorItemSignal (ConnectorItem *)
void setActiveWireSignal (Wire *)
void setVoltageSignal (double, bool doEmit)
void swapSignal (const QString &family, const QString &prop, QMap< QString, QString > &propsMap, ItemBase *)
Signals inherited from ZoomableGraphicsView
void wheelSignal ()
void zoomChanged (double zoom)
void zoomOutOfRange (double zoom)
Public Member Functions
SketchWidget (ViewLayer::ViewID, QWidget *parent=0, int size=400, int minSize=300)
~SketchWidget ()
void addBendpoint (ItemBase *lastHoverEnterItem, ConnectorItem *lastHoverEnterConnectorItem, QPointF lastLocation)
virtual void addDefaultParts ()
ItemBase * addItem (ModelPart *, ViewLayer::ViewLayerPlacement, BaseCommand::CrossViewType, const ViewGeometry &, long id, long modelIndex, AddDeleteItemCommand *originatingCommand)
ItemBase * addItem (const QString &moduleID, ViewLayer::ViewLayerPlacement, BaseCommand::CrossViewType, const ViewGeometry &, long id, long modelIndex, AddDeleteItemCommand *originatingCommand)
virtual ItemBase * addItemAux (ModelPart *, ViewLayer::ViewLayerPlacement, const ViewGeometry &, long id, bool doConnectors, ViewLayer::ViewID, bool temporary)
ItemBase * addItemAuxTemp (ModelPart *, ViewLayer::ViewLayerPlacement, const ViewGeometry &, long id, bool doConnectors, ViewLayer::ViewID, bool temporary)
void addLegBendpoint (long id, const QString &connectorID, int index, QPointF, const class Bezier *, const class Bezier *)
void addToSketch (QList< ModelPart * > &)
void addViewLayer (ViewLayer *)
virtual void addViewLayers ()
QGraphicsItem * addWatermark (const QString &filename)
bool alignedToGrid ()
void alignItems (Qt::Alignment)
QPointF alignOneToGrid (ItemBase *itemBase)
void alignToGrid (bool)
const QColor & background ()
void blockUI (bool)
void bringForward ()
void bringToFront ()
ItemCount calcItemCount ()
virtual bool canCopyItem (QGraphicsItem *item, int count)
virtual bool canDeleteItem (QGraphicsItem *item, int count)
virtual bool canDisconnectAll ()
void changeBus (ItemBase *, bool connec, const QString &oldBus, const QString &newBus, QList< ConnectorItem * > &, const QString &message, const QString &oldLayout, const QString &newLayout)
virtual void changeConnection (long fromID, const QString &fromConnectorID, long toID, const QString &toConnectorID, ViewLayer::ViewLayerPlacement, bool connect, bool doEmit, bool updateConnections)
virtual void changeLayer (long id, double z, ViewLayer::ViewLayerID viewLayerID)
void changeLeg (long fromID, const QString &connectorID, const QPolygonF &, bool relative, const QString &why)
void changeLegCurve (long id, const QString &connectorID, int index, const Bezier *)
void changeWire (long fromID, QLineF line, QPointF pos, bool updateConnections, bool updateRatsnest)
void changeWireColor (long wireId, const QString &color, double opacity)
void changeWireCurve (long id, const Bezier *, bool autoroutable)
void changeWireFlags (long wireId, ViewGeometry::WireFlags wireFlags)
void changeWireWidth (long wireId, double width)
void changeZ (QHash< long, RealPair * >, double(*pairAccessor)(RealPair *))
void checkForReversedWires ()
void cleanUpWires (bool doEmit, class CleanUpWiresCommand *)
void clearPasteOffset ()
void clearSelection ()
void collectAllNets (QHash< class ConnectorItem *, int > &indexer, QList< QList< class ConnectorItem * > * > &allPartConnectorItems, bool includeSingletons, bool bothSides)
void collectParts (QList< ItemBase * > &partList)
void copy ()
void copyHeart (QList< ItemBase * > &bases, bool saveBoundingRects, QByteArray &itemData, QList< long > &modelIndexes)
virtual void createTrace (Wire *, bool useLastWireColor)
long createWire (ConnectorItem *from, ConnectorItem *to, ViewGeometry::WireFlags, bool dontUpdate, BaseCommand::CrossViewType, QUndoCommand *parentCommand)
bool curvyWires ()
bool curvyWiresIndicated (Qt::KeyboardModifiers)
void cut ()
virtual double defaultGridSizeInches ()
virtual ViewLayer::ViewLayerPlacement defaultViewLayerPlacement (ModelPart *)
void deleteItem (long id, bool deleteModelPart, bool doEmit, bool later)
virtual void deleteItem (ItemBase *, bool deleteModelPart, bool doEmit, bool later)
void deleteMiddle (QSet< ItemBase * > &deletedItems, QUndoCommand *parentCommand)
void deleteSelected (Wire *, bool minus)
void disconnectAll ()
void ensureLayerVisible (ViewLayer::ViewLayerID)
constexpr bool everZoomed () const noexcept
const QString & filenameIf ()
ConnectorItem * findConnectorItem (ConnectorItem *foreignConnectorItem)
ItemBase * findItem (long id)
double fitInWindow ()
void flattenCurve (ItemBase *lastHoverEnterItem, ConnectorItem *lastHoverEnterConnectorItem, QPointF lastLocation)
void flipItem (long id, Qt::Orientations orientation)
void flipX (Qt::Orientations orientation, bool rubberBandLegEnabled)
virtual void forwardRoutingStatus (const RoutingStatus &)
virtual QHash< QString, QString > getAutorouterSettings ()
void getBendpointWidths (class Wire *, double w, double &w1, double &w2, bool &negativeOffsetRect)
void getRatsnestColor (QColor &)
PaletteItem * getSelectedPart ()
const QString & getShortName ()
float getTopZ ()
ViewGeometry::WireFlag getTraceFlag ()
virtual ViewLayer::ViewLayerID getWireViewLayerID (const ViewGeometry &viewGeometry, ViewLayer::ViewLayerPlacement)
constexpr const QColor & gridColor () const noexcept
QString gridSizeText ()
virtual bool hasAnyNets ()
void hideConnectors (bool hide)
void hidePartLabel (ItemBase *item)
void hidePartLayer (long id, ViewLayer::ViewLayerID, bool hide)
void hidePartLayer (ItemBase *, ViewLayer::ViewLayerID, bool hide)
void hoverEnterConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
void hoverEnterItem (QGraphicsSceneHoverEvent *event, ItemBase *item)
void hoverLeaveConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
void hoverLeaveItem (QGraphicsSceneHoverEvent *event, ItemBase *item)
virtual bool ignoreFemale ()
virtual bool includeSymbols ()
void initGrid ()
ConnectorItem * lastHoverEnterConnectorItem ()
ItemBase * lastHoverEnterItem ()
bool layerIsActive (ViewLayer::ViewLayerID)
bool layerIsVisible (ViewLayer::ViewLayerID)
virtual void loadFromModelParts (QList< ModelPart * > &modelParts, BaseCommand::CrossViewType, QUndoCommand *parentCommand, bool offsetPaste, const QRectF *boundingRect, bool seekOutsideConnections, QList< long > &newIDs)
void loadLogoImage (ItemBase *, const QString &oldSvg, const QSizeF oldAspectRatio, const QString &oldFilename, const QString &newFilename, bool addName)
void loadLogoImage (long itemID, const QString &oldSvg, const QSizeF oldAspectRatio, const QString &oldFilename)
void loadLogoImage (long itemID, const QString &newFilename, bool addName)
void makeDeleteItemCommand (ItemBase *itemBase, BaseCommand::CrossViewType, QUndoCommand *parentCommand)
VirtualWire * makeOneRatsnestWire (ConnectorItem *source, ConnectorItem *dest, bool routed, QColor color, bool force)
void makeWiresChangeConnectionCommands (const QList< Wire * > &wires, QUndoCommand *parentCommand)
void mousePressConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
void moveItem (long id, ViewGeometry &, bool updateRatsnest)
void moveItem (long id, const QPointF &p, bool updateRatsnest)
void moveItem (ItemBase *, double x, double y)
void moveLegBendpoint (long id, const QString &connectorID, int index, QPointF)
void movePartLabel (long itemID, QPointF newPos, QPointF newOffset)
void noteChanged (ItemBase *, const QString &oldText, const QString &newtext, QSizeF oldSize, QSizeF newSize)
void noteSizeChanged (ItemBase *itemBase, const QSizeF &oldSize, const QSizeF &newSize)
void partLabelChanged (ItemBase *, const QString &oldText, const QString &newtext)
void partLabelMoved (ItemBase *, QPointF oldPos, QPointF oldOffset, QPointF newPos, QPointF newOffset)
bool partLabelsVisible ()
void pasteHeart (QByteArray &itemData, bool seekOutsideConnections)
void prepLegBendpointChange (ConnectorItem *from, int oldCount, int newCount, int index, QPointF pos, const class Bezier *, const class Bezier *, const class Bezier *, bool triggerFirstTime)
void prepLegBendpointMove (ConnectorItem *from, int index, QPointF oldPos, QPointF newPos, ConnectorItem *to, bool changeConnections)
void prepLegCurveChange (ConnectorItem *from, int index, const class Bezier *oldB, const class Bezier *newB, bool triggerFirstTime)
void prepLegSelection (ItemBase *)
void pushCommand (QUndoCommand *, QObject *signalTarget)
void ratsnestConnect (ConnectorItem *connectorItem, bool connect)
void ratsnestConnect (ItemBase *, bool connect)
void ratsnestConnect (ConnectorItem *c1, ConnectorItem *c2, bool connect, bool wait)
double ratsnestOpacity ()
double ratsnestWidth ()
void recalcLeg (long fromID, const QString &connectorID, const QPolygonF &, bool relative, bool active, const QString &why)
class ReferenceModel * referenceModel ()
void removeLegBendpoint (long id, const QString &connectorID, int index, const class Bezier *)
void renamePins (ItemBase *, const QStringList &oldLabels, const QStringList &newLabels, bool singleRow)
void renamePins (long itemID, const QStringList &labels, bool singleRow)
QString renderToSVG (RenderThing &, QGraphicsItem *board, const LayerList &)
void resizeNote (long itemID, const QSizeF &)
void resolveTemporary (bool, ItemBase *)
void restoreLayerVisibility ()
void restorePartLabel (long itemID, QDomElement &element)
double retrieveZoom ()
void rotateFlipPartLabel (ItemBase *, double degrees, Qt::Orientations flipDirection)
void rotateFlipPartLabel (long itemID, double degrees, Qt::Orientations flipDirection)
void rotateItem (long id, double degrees)
void rotateLeg (long fromID, const QString &connectorID, const QPolygonF &, bool active)
void rotateX (double degrees, bool rubberBandLegEnabled, ItemBase *originatingItem)
virtual bool routeBothSides ()
virtual bool sameElectricalLayer2 (ViewLayer::ViewLayerID, ViewLayer::ViewLayerID)
void saveLayerVisibility ()
void saveZoom (double)
int selectAllMoveLock ()
QList< ItemBase * > selectAllObsolete ()
virtual void selectAllWires (ViewGeometry::WireFlag)
void selectDeselectAllCommand (bool state)
const QString & selectedModuleID ()
void selectItem (long id, bool state, bool updateInfoView, bool doEmit)
void selectItem (ItemBase *itemBase)
void selectItems (QList< ItemBase * >)
void selectItemsWithModuleID (ModelPart *)
void sendBackward ()
void sendToBack ()
void setAllLayersVisible (bool visible)
void setAnyInRotation ()
virtual void setAutorouterSettings (QHash< QString, QString > &)
void setBackground (QColor)
void setBackgroundColor (QColor, bool setPref)
void setChainDrag (bool)
virtual void setClipEnds (class ClipableWire *, bool)
virtual void setCurrent (bool current)
void setCurvyWires (bool)
void setEverZoomed (bool)
void setGridColor (QColor)
void setGridSize (const QString &)
void setGroundFillSeed (long id, const QString &connectorID, bool seed)
void setIgnoreSelectionChangeEvents (bool)
void setInfoViewOnHover (bool infoViewOnHover)
void setItemDropOffset (long id, QPointF offset)
void setItemMenu (QMenu *)
void setLayerActive (ViewLayer *viewLayer, bool active)
void setLayerActive (ViewLayer::ViewLayerID viewLayerID, bool active)
void setLayerVisible (ViewLayer *viewLayer, bool visible, bool doChildLayers)
void setLayerVisible (ViewLayer::ViewLayerID viewLayerID, bool visible, bool doChildLayers)
void setMoveLock (long id, bool lock)
void setNoteFocus (QGraphicsItem *, bool inFocus)
void setPasting (bool)
void setRatsnestOpacity (double)
void setRatsnestWidth (double)
void setReferenceModel (class ReferenceModel *referenceModel)
void setSketchModel (SketchModel *)
void setUndoStack (class WaitPushUndoStack *)
virtual long setUpSwap (SwapThing &, bool master)
void setViewLayerIDs (ViewLayer::ViewLayerID part, ViewLayer::ViewLayerID wire, ViewLayer::ViewLayerID connector, ViewLayer::ViewLayerID ruler, ViewLayer::ViewLayerID note)
void setWireExtras (long id, QDomElement &)
void setWireMenu (QMenu *)
void showEvent (QShowEvent *event)
void showGrid (bool)
bool showingGrid ()
void showPartLabels (bool show)
void showUnrouted ()
void simpleMoveItem (long id, QPointF)
void sortAnyByZ (const QList< QGraphicsItem * > &items, QList< ItemBase * > &bases)
bool spaceBarIsPressed () noexcept
class SelectItemCommand * stackSelectionState (bool pushIt, QUndoCommand *parentCommand)
QColor standardBackground ()
void stickem (long stickTargetID, long stickSourceID, bool stick)
void stickyScoop (ItemBase *stickyOne, bool checkCurrent, CheckStickyCommand *)
bool swappingEnabled (ItemBase *)
void testConnectors ()
virtual void tidyWires ()
void transformItem (long id, const QMatrix &)
void triggerRotate (ItemBase *, double degrees)
class WaitPushUndoStack * undoStack ()
void updateInfoView ()
void updateRoutingStatus (CleanUpWiresCommand *, RoutingStatus &, bool manual)
void updateRoutingStatus (RoutingStatus &, bool manual)
void updateWire (long id, const QString &connectorID, bool updateRatsnest)
void updateWires ()
constexpr ViewLayer::ViewID viewID () const noexcept
void viewItemInfo (ItemBase *item)
LayerHash & viewLayers ()
constexpr const QString & viewName () const noexcept
Public Member Functions inherited from InfoGraphicsView
InfoGraphicsView (QWidget *parent=0)
int boardLayers ()
virtual void changePinLabels (ItemBase *, bool singleRow)
virtual void changeWireColor (const QString newColor)
virtual void changeWireWidthMils (const QString newWidth)
virtual QString generateCopperFillUnit (ItemBase *itemBase, QPointF whereToStart)
virtual void getLabelFont (QFont &, QColor &, ItemBase *)
virtual double getLabelFontSizeLarge ()
virtual double getLabelFontSizeMedium ()
virtual double getLabelFontSizeSmall ()
virtual double getLabelFontSizeTiny ()
virtual double getWireStrokeWidth (Wire *, double wireWidth)
virtual bool hasBigDots ()
class HtmlInfoView * infoView ()
virtual void initWire (class Wire *, int penWidth)
virtual void newWire (Wire *)
void setActiveConnectorItem (ConnectorItem *)
void setActiveWire (Wire *)
virtual void setBoardLayers (int, bool redraw)
virtual void setHoleSize (ItemBase *, const QString &propName, const QString &translatedPropName, const QString &oldValue, const QString &newValue, QRectF &oldRect, QRectF &newRect, bool redraw)
void setInfoView (class HtmlInfoView *)
virtual void setProp (ItemBase *, const QString &propName, const QString &translatedPropName, const QString &oldValue, const QString &newValue, bool redraw)
virtual void setResistance (QString resistance, QString pinSpacing)
void setSMDOrientation (Qt::Orientations)
Qt::Orientations smdOrientation ()
virtual void swap (const QString &family, const QString &prop, QMap< QString, QString > &propsMap, ItemBase *)
void updateRotation (ItemBase *)
Public Member Functions inherited from ZoomableGraphicsView
ZoomableGraphicsView (QWidget *parent=0)
void absoluteZoom (double percent)
double currentZoom ()
virtual void ensureFixedToBottomRightItems ()
void relativeZoom (double step, bool centerToCursor)
void setAcceptWheelEvents (bool)
virtual void setViewFromBelow (bool)
bool viewFromBelow ()
Static Public Member Functions
static ViewLayer::ViewLayerID defaultConnectorLayer (ViewLayer::ViewID viewId)
Static Public Member Functions inherited from InfoGraphicsView
static InfoGraphicsView * getInfoGraphicsView (QGraphicsItem *)
Static Public Member Functions inherited from ZoomableGraphicsView
static void setWheelMapping (WheelMapping)
static WheelMapping wheelMapping ()
Static Public Attributes
static bool m_blockUI = false
static constexpr int PropChangeDelay = 100
Static Public Attributes inherited from ZoomableGraphicsView
static const int MaxScaleValue = 3000
Protected Types
enum StatusConnectStatus { StatusConnectNotTried, StatusConnectSucceeded, StatusConnectFailed }
Protected Slots
void arrowTimerTimeout ()
void autoScrollTimeout ()
void canConnect (Wire *from, ItemBase *to, bool &connect)
void changeConnectionSlot (long fromID, QString fromConnectorID, long toID, QString toConnectorID, ViewLayer::ViewLayerPlacement, bool connect, bool updateConnections)
void changePinLabels (ItemBase *, bool singleRow)
void changePinLabelsSlot (ItemBase *itemBase, bool singleRow)
void cleanUpWiresSlot (CleanUpWiresCommand *)
void clearSelectionSlot ()
void collectRatsnestSlot (QList< SketchWidget * > &foreignSketchWidgets)
void copyBoundingRectsSlot (QHash< QString, QRectF > &)
void deleteRatsnest (Wire *, QUndoCommand *parentCommand)
void deleteTemporary ()
void deleteTracesSlot (QSet< ItemBase * > &deletedItems, QHash< ItemBase *, SketchWidget * > &otherDeletedItems, QList< long > &deletedIDs, bool isForeign, QUndoCommand *parentCommand)
void dragAutoScrollTimeout ()
void dragIsDoneSlot (class ItemDrag *)
virtual void getDroppedItemViewLayerPlacement (ModelPart *modelPart, ViewLayer::ViewLayerPlacement &)
void itemAddedSlot (ModelPart *, ItemBase *, ViewLayer::ViewLayerPlacement, const ViewGeometry &, long id, SketchWidget *dropOrigin)
void itemDeletedSlot (long id)
void itemSelectedSlot (long id, bool state)
void makeDeleteItemCommandFinalSlot (ItemBase *itemBase, bool foreign, QUndoCommand *parentCommand)
void makeDeleteItemCommandPrepSlot (ItemBase *itemBase, bool foreign, QUndoCommand *parentCommand)
void moveAutoScrollTimeout ()
void rememberSticky (long id, QUndoCommand *parentCommand)
void rememberSticky (ItemBase *, QUndoCommand *parentCommand)
void removeRatsnestSlot (QList< struct ConnectorEdge * > &cutSet, QUndoCommand *parentCommand)
void restartPasteCount ()
void selectionChangedSlot ()
void spaceBarIsPressedSlot (bool)
void statusMessage (QString message, int timeout=0)
long swapStart (SwapThing &swapThing, bool master)
void toggleLayerVisibility ()
void updateInfoViewSlot ()
void updatePartLabelInstanceTitleSlot (long itemID)
void vScrollToZero ()
void wireChangedCurveSlot (class Wire *, const Bezier *oldB, const Bezier *newB, bool triggerFirstTime)
void wireChangedSlot (class Wire *, const QLineF &oldLine, const QLineF &newLine, QPointF oldPos, QPointF newPos, ConnectorItem *from, ConnectorItem *to)
void wireConnectedSlot (long fromID, QString fromConnectorID, long toID, QString toConnectorID)
void wireDisconnectedSlot (long fromID, QString fromConnectorID)
void wireJoinSlot (class Wire *, ConnectorItem *clickedConnectorItem)
virtual void wireSplitSlot (class Wire *, QPointF newPos, QPointF oldPos, const QLineF &oldLine)
Protected Member Functions
virtual bool acceptsTrace (const ViewGeometry &)
virtual PaletteItem * addPartItem (ModelPart *, ViewLayer::ViewLayerPlacement, PaletteItem *, bool doConnectors, bool &ok, ViewLayer::ViewID, bool temporary)
void addToScene (ItemBase *item, ViewLayer::ViewLayerID viewLayerID)
void addViewLayersAux (const LayerList &, const LayerList &layersFromBelow, float startZ=1.5)
void addWireExtras (long newID, QDomElement &view, QUndoCommand *parentCommand)
void alignLoc (QPointF &loc, const QPointF startPoint, const QPointF newLoc, const QPointF originalLoc)
QPointF calcNewLoc (ItemBase *moveBase, ItemBase *detachFrom)
virtual bool canAlignToCenter (ItemBase *)
virtual bool canAlignToTopLeft (ItemBase *)
virtual bool canChainMultiple ()
virtual bool canChainWire (Wire *)
bool canConnect (ItemBase *from, ItemBase *to)
virtual bool canConnect (Wire *from, ItemBase *to)
virtual bool canCreateWire (Wire *dragWire, ConnectorItem *from, ConnectorItem *to)
virtual bool canDragWire (Wire *)
virtual bool canDropModelPart (ModelPart *)
void categorizeDragLegs (bool rubberBandLegEnabled)
void categorizeDragWires (QSet< Wire * > &wires, QList< ItemBase * > &freeWires)
void changeConnectionAux (long fromID, const QString &fromConnectorID, long toID, const QString &toConnectorID, ViewLayer::ViewLayerPlacement, bool connect, bool updateConnections)
void changeLegAux (long fromID, const QString &fromConnectorID, const QPolygonF &, bool reset, bool relative, bool active, const QString &why)
bool checkAutoscroll (QPoint globalPos)
virtual QString checkDroppedModuleID (const QString &moduleID)
void checkFit (ModelPart *newModelPart, ItemBase *itemBase, long newID, QHash< ConnectorItem *, Connector * > &found, QList< ConnectorItem * > &notFound, QHash< ConnectorItem *, ConnectorItem * > &m2f, QHash< ConnectorItem *, Connector * > &byWire, QHash< QString, QPolygonF > &legs, QHash< QString, ConnectorItem * > &formerLegs, QUndoCommand *parentCommand)
void checkFitAux (ItemBase *tempItemBase, ItemBase *itemBase, long newID, QHash< ConnectorItem *, Connector * > &found, QList< ConnectorItem * > &notFound, QHash< ConnectorItem *, ConnectorItem * > &m2f, QHash< ConnectorItem *, Connector * > &byWire, QHash< QString, QPolygonF > &legs, QHash< QString, ConnectorItem * > &formerLegs, QUndoCommand *parentCommand)
bool checkMoved (bool wait)
virtual bool checkUnder ()
bool checkUpdateRatsnest (QList< ConnectorItem * > &connectorItems)
void cleanupRatsnests (QList< QPointer< ConnectorItem > > &connectorItems, bool connect)
void clearDragWireTempCommand ()
void clearHoldingSelectItem ()
void clearTemporaries ()
void clickBackground (QMouseEvent *)
virtual bool collectFemaleConnectees (ItemBase *, QSet< ItemBase * > &)
QList< ItemBase * > collectSuperSubs (ItemBase *)
void contextMenuEvent (QContextMenuEvent *)
void continueZChange (QList< ItemBase * > &bases, int start, int end, bool(*test)(int current, int start), int inc, const QString &text)
void continueZChangeAux (QList< ItemBase * > &bases, const QString &text)
void continueZChangeMax (QList< ItemBase * > &bases, int start, int end, bool(*test)(int current, int start), int inc, const QString &text)
void copyAux (QList< ItemBase * > &bases, bool saveBoundingRects)
void copyDrop ()
bool createOneTrace (Wire *wire, ViewGeometry::WireFlag flag, bool allowAny, QList< Wire * > &done, bool useLastWireColor, QUndoCommand *parentCommand)
virtual Wire * createTempWireForDragging (Wire *fromWire, ModelPart *wireModel, ConnectorItem *connectorItem, ViewGeometry &viewGeometry, ViewLayer::ViewLayerPlacement)
void createTrace (Wire *fromWire, const QString &commandString, ViewGeometry::WireFlag, bool useLastWireColor)
virtual ViewLayer::ViewLayerPlacement createWireViewLayerPlacement (ConnectorItem *from, ConnectorItem *to)
bool currentlyInfoviewed (ItemBase *item)
void cutDeleteAux (QString undoStackMessage, bool minus, Wire *wire)
void deleteAux (QSet< ItemBase * > &deletedItems, QUndoCommand *parentCommand, bool doPush)
virtual bool disconnectFromFemale (ItemBase *item, QHash< long, ItemBase * > &savedItems, ConnectorPairHash &, bool doCommand, bool rubberBandLegEnabled, QUndoCommand *parentCommand)
void dragEnterEvent (QDragEnterEvent *)
bool dragEnterEventAux (QDragEnterEvent *)
bool draggingWireEnd ()
void dragLeaveEvent (QDragLeaveEvent *)
void dragMoveEvent (QDragMoveEvent *)
void dragMoveHighlightConnector (QPoint eventPos)
void dragRatsnestChanged ()
void dragWireChanged (class Wire *wire, ConnectorItem *from, ConnectorItem *to)
void drawBackground (QPainter *painter, const QRectF &rect)
void dropEvent (QDropEvent *)
void dropItemEvent (QDropEvent *event)
ChangeConnectionCommand * extendChangeConnectionCommand (BaseCommand::CrossViewType, long fromID, const QString &fromConnectorID, long toID, const QString &toConnectorID, ViewLayer::ViewLayerPlacement, bool connect, QUndoCommand *parent)
ChangeConnectionCommand * extendChangeConnectionCommand (BaseCommand::CrossViewType, ConnectorItem *fromConnectorItem, ConnectorItem *toConnectorItem, ViewLayer::ViewLayerPlacement, bool connect, QUndoCommand *parentCommand)
virtual void extraRenderSvgStep (ItemBase *, QPointF offset, double dpi, double printerScale, QString &outputSvg)
virtual void findAlignmentAnchor (ItemBase *originatingItem, QHash< long, ItemBase * > &savedItems, QHash< Wire *, ConnectorItem * > &savedWires)
ConnectorItem * findConnectorItem (ItemBase *item, const QString &connectorID, ViewLayer::ViewLayerPlacement)
virtual void findConnectorsUnder (ItemBase *item)
long findPartOrWire (long itemID)
QGraphicsItem * getClickedItem (QList< QGraphicsItem * > &items)
ViewLayer::ViewLayerID getConnectorViewLayerID ()
virtual ViewLayer::ViewLayerID getDragWireViewLayerID (ConnectorItem *)
virtual ViewLayer::ViewLayerID getLabelViewLayerID (ItemBase *)
ViewLayer::ViewLayerID getNoteViewLayerID ()
ViewLayer::ViewLayerID getPartViewLayerID ()
ViewLayer::ViewLayerID getRulerViewLayerID ()
virtual double getTraceWidth ()
ViewLayer::ViewLayerID getViewLayerID (ModelPart *, ViewLayer::ViewID, ViewLayer::ViewLayerPlacement)
virtual ViewLayer::ViewLayerPlacement getViewLayerPlacement (ModelPart *, QDomElement &instance, QDomElement &view, ViewGeometry &)
double gridSizeInches ()
void handleConnect (QDomElement &connect, ModelPart *, const QString &fromConnectorID, ViewLayer::ViewLayerID, QStringList &alreadyConnected, QHash< long, ItemBase * > &newItems, QUndoCommand *parentCommand, bool seekOutsideConnections)
virtual const QString & hoverEnterPartConnectorMessage (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
virtual const QString & hoverEnterWireConnectorMessage (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
void initBackgroundColor ()
void keyPressEvent (QKeyEvent *)
void keyReleaseEvent (QKeyEvent *)
void killDroppingItem ()
QString makeMoveSVG (double printerScale, double dpi, QPointF &offset)
void makeRatsnestViewGeometry (ViewGeometry &viewGeometry, ConnectorItem *source, ConnectorItem *dest)
void makeSwapWire (SketchWidget *, ItemBase *, long newID, ConnectorItem *fromConnectorItem, ConnectorItem *toConnectorItem, Connector *newConnector, QUndoCommand *parentCommand)
QString makeWireSVG (Wire *wire, QPointF offset, double dpi, double printerscale, bool blackOnly)
QString makeWireSVGAux (Wire *wire, double width, const QString &color, QPointF offset, double dpi, double printerScale, bool blackOnly, bool dashed)
bool matchesLayer (ModelPart *modelPart)
void mouseDoubleClickEvent (QMouseEvent *)
void mouseMoveEvent (QMouseEvent *)
virtual void mousePressEvent (QMouseEvent *)
void mouseReleaseEvent (QMouseEvent *)
bool moveByArrow (double dx, double dy, QKeyEvent *)
void moveItems (QPoint globalPos, bool checkAutoScroll, bool rubberBandLegEnabled)
void moveLegBendpoints (bool undoOnly, QUndoCommand *parentCommand)
void moveLegBendpointsAux (ConnectorItem *connectorItem, bool undoOnly, QUndoCommand *parentCommand)
virtual ViewLayer::ViewLayerID multiLayerGetViewLayerID (ModelPart *modelPart, ViewLayer::ViewID, ViewLayer::ViewLayerPlacement, LayerList &)
AddItemCommand * newAddItemCommand (BaseCommand::CrossViewType crossViewType, ModelPart *, QString moduleID, ViewLayer::ViewLayerPlacement, ViewGeometry &viewGeometry, qint64 id, bool updateInfoView, long modelIndex, bool addSubparts, QUndoCommand *parent)
ItemBase * overSticky (ItemBase *)
void paintEvent (QPaintEvent *)
void partLabelChangedAux (ItemBase *pitem, const QString &oldText, const QString &newText)
virtual ItemBase * placePartDroppedInOtherView (ModelPart *, ViewLayer::ViewLayerPlacement, const ViewGeometry &viewGeometry, long id, SketchWidget *dropOrigin)
void prepDeleteOtherProps (ItemBase *itemBase, long id, const QString &newModuleID, QMap< QString, QString > &propsMap, QUndoCommand *parentCommand)
void prepDeleteProps (ItemBase *itemBase, long id, const QString &newModuleID, QMap< QString, QString > &propsMap, QUndoCommand *parentCommand)
void prepDragBendpoint (Wire *, QPoint eventPos, bool dragCurve)
void prepDragWire (Wire *)
void prepMove (ItemBase *originatingItem, bool rubberBandLegEnabled, bool includeRatsnest)
virtual void prereleaseTempWireForDragging (Wire *)
void removeDragWire ()
QByteArray removeOutsideConnections (const QByteArray &itemData, QList< long > &modelIndexes)
void removeWire (Wire *w, QList< ConnectorItem * > &ends, QList< Wire * > &done, QUndoCommand *parentCommand)
QString renderToSVG (RenderThing &, const LayerList &)
QString renderToSVG (RenderThing &, QList< QGraphicsItem * > &itemsAndLabels)
void resizeBoard ()
void resizeEvent (QResizeEvent *)
void resizeWithHandle (ItemBase *itemBase, double mmW, double mmH)
bool resizingBoardPress (ItemBase *)
bool resizingBoardRelease ()
virtual bool resizingJumperItemPress (ItemBase *)
virtual bool resizingJumperItemRelease ()
virtual void rotatePartLabels (double degrees, QTransform &, QPointF center, QUndoCommand *parentCommand)
void rotateWire (Wire *, QTransform &rotation, QPointF center, bool undoOnly, QUndoCommand *parentCommand)
int selectAllItems (QSet< ItemBase * > &itemBases, const QString &msg)
void selectAllWiresFrom (ViewGeometry::WireFlag flag, QList< QGraphicsItem * > &items)
void setLastPaletteItemSelected (PaletteItem *paletteItem)
void setLastPaletteItemSelectedIf (ItemBase *itemBase)
virtual void setNewPartVisible (ItemBase *)
void setupAutoscroll (bool moving)
virtual void setUpColor (ConnectorItem *fromConnectorItem, ConnectorItem *toConnectorItem, Wire *wire, QUndoCommand *parentCommand)
void setUpSwapReconnect (SwapThing &, ItemBase *itemBase, long newID, bool master)
virtual void setWireVisible (Wire *)
void showPartLabelsAux (bool show, QList< ItemBase * > &itemBases)
void squashShapes (QPointF scenePos)
bool startZChange (QList< ItemBase * > &bases)
bool swappedGender (ConnectorItem *originalConnectorItem, Connector *newConnector)
virtual const QString & traceColor (ViewLayer::ViewLayerPlacement)
void turnOffAutoscroll ()
void unsquashShapes ()
virtual bool updateOK (ConnectorItem *, ConnectorItem *)
virtual void viewGeometryConversionHack (ViewGeometry &, ModelPart *)
bool viewportEvent (QEvent *)
virtual BaseCommand::CrossViewType wireSplitCrossView ()
virtual ViewLayer::ViewLayerPlacement wireViewLayerPlacement (ConnectorItem *)
Protected Member Functions inherited from InfoGraphicsView
QGraphicsItem * selectedAux ()
Protected Member Functions inherited from ZoomableGraphicsView
virtual void wheelEvent (QWheelEvent *event)
Static Protected Member Functions
static bool greaterThan (int a, int b)
static bool lessThan (int a, int b)
Protected Attributes
bool m_addDefaultParts = false
QPointer< ItemBase > m_addedDefaultPart
QList< ItemBase * > m_additionalSavedItems
QPointer< ItemBase > m_alignmentItem
QPointF m_alignmentStartPoint
bool m_alignToGrid = true
bool m_anyInRotation
QTimer m_arrowTimer
double m_arrowTotalX = 0.0
double m_arrowTotalY = 0.0
volatile int m_autoScrollCount = 0
int m_autoScrollThreshold = 0
QTimer m_autoScrollTimer
volatile int m_autoScrollX = 0
volatile int m_autoScrollY = 0
ViewGeometry m_bendpointVG
QPointer< Wire > m_bendpointWire
bool m_chainDrag = false
QList< ItemBase * > m_checkUnder
bool m_clearSceneRect = false
QPointer< ConnectorItem > m_connectorDragConnector
QPointer< Wire > m_connectorDragWire
ViewLayer::ViewLayerID m_connectorViewLayerID
bool m_current = false
bool m_curvyWires = false
QPoint m_dragBendpointPos
QPointer< Wire > m_dragBendpointWire
bool m_dragCurve = false
bool m_draggingBendpoint = false
QPointer< ItemBase > m_droppingItem
QPointF m_droppingOffset
bool m_droppingWire = false
bool m_everZoomed = false
QPoint m_globalPos
QColor m_gridColor
double m_gridSizeInches = 0.0
QString m_gridSizeText
class SelectItemCommand * m_holdingSelectItemCommand = nullptr
int m_ignoreSelectionChangeEvents = 0
QList< QGraphicsItem * > m_inFocus
bool m_infoViewOnHover
QMenu * m_itemMenu = nullptr
QString m_lastColorSelected
QPointer< ConnectorItem > m_lastHoverEnterConnectorItem
QPointer< ItemBase > m_lastHoverEnterItem
QPointer< PaletteItem > m_lastPaletteItemSelected
bool m_middleMouseIsPressed = false
QPointF m_mousePressGlobalPos
QPointF m_mousePressScenePos
ConnectorPairHash m_moveDisconnectedFromFemale
int m_moveEventCount = 0
QPointer< ItemBase > m_moveReferenceItem
bool m_movingByArrow = false
bool m_movingByMouse = false
QPointer< QGraphicsSvgItem > m_movingItem
QPointF m_movingSVGOffset
QPointer< QSvgRenderer > m_movingSVGRenderer
ViewLayer::ViewLayerID m_noteViewLayerID
QPointer< ItemBase > m_originatingItem
ViewLayer::ViewLayerID m_partViewLayerID
int m_pasteCount = 0
QPointF m_pasteOffset
bool m_pasting = false
QList< QPointer< ConnectorItem > > m_ratsnestCacheConnect
QList< QPointer< ConnectorItem > > m_ratsnestCacheDisconnect
double m_ratsnestOpacity = 0.0
QList< QPointer< ConnectorItem > > m_ratsnestUpdateConnect
QList< QPointer< ConnectorItem > > m_ratsnestUpdateDisconnect
double m_ratsnestWidth = 0.0
QPointer< class ReferenceModel > m_referenceModel
QPointer< class ResizableBoard > m_resizingBoard
RoutingStatus m_routingStatus
bool m_rubberBandLegWasEnabled = false
ViewLayer::ViewLayerID m_rulerViewLayerID
QHash< long, ItemBase * > m_savedItems
QHash< Wire *, ConnectorItem * > m_savedWires
QString m_shortName
bool m_showGrid = true
QPointer< SizeItem > m_sizeItem
QPointer< SketchModel > m_sketchModel
bool m_spaceBarIsPressed = false
bool m_spaceBarWasPressed = false
QList< QPointer< ItemBase > > m_squashShapes
StatusConnectStatus m_statusConnectState = StatusConnectNotTried
QMultiHash< ItemBase *, ConnectorItem * > m_stretchingLegs
class SelectItemCommand * m_tempDragWireCommand = nullptr
QList< QGraphicsItem * > m_temporaries
class WaitPushUndoStack * m_undoStack = nullptr
ViewLayer::ViewID m_viewID
LayerHash m_viewLayers
QHash< ViewLayer::ViewLayerID, bool > m_viewLayerVisibility
QString m_viewName
QMenu * m_wireMenu = nullptr
ViewLayer::ViewLayerID m_wireViewLayerID
float m_z
double m_zoom = 100
Protected Attributes inherited from InfoGraphicsView
int m_boardLayers
bool m_hoverEnterConnectorMode
bool m_hoverEnterMode
class HtmlInfoView * m_infoView
Qt::Orientations m_smdOrientation
Protected Attributes inherited from ZoomableGraphicsView
bool m_acceptWheelEvents
int m_maxScaleValue
int m_minScaleValue
double m_scaleValue
bool m_viewFromBelow
Static Protected Attributes
static constexpr int DragAutoScrollThreshold = 10
static constexpr int MoveAutoScrollThreshold = 5
Static Protected Attributes inherited from ZoomableGraphicsView
static WheelMapping m_wheelMapping
Properties
QColor gridColor
double ratsnestOpacity
double ratsnestWidth
Additional Inherited Members
Public Types inherited from ZoomableGraphicsView
enum WheelMapping { ScrollPrimary, ZoomPrimary, WheelMappingCount }
Member Enumeration Documentation
StatusConnectStatus
enum SketchWidget::StatusConnectStatus protected
Enumerator
StatusConnectNotTried
StatusConnectSucceeded
StatusConnectFailed
Constructor & Destructor Documentation
SketchWidget()
SketchWidget::SketchWidget (ViewLayer::ViewID viewID, QWidget * parent = 0, int size = 400, int minSize = 300)
References arrowTimerTimeout(), AutoRepeatDelay, m_arrowTimer, m_autoScrollTimer, m_infoViewOnHover, m_sizeItem, restartPasteCount(), selectionChangedSlot(), and setLastPaletteItemSelected().
~SketchWidget()
SketchWidget::~SketchWidget ()
References m_viewLayers.
Member Function Documentation
acceptsTrace()
bool SketchWidget::acceptsTrace (const ViewGeometry &) protected virtual
Reimplemented in PCBSketchWidget, and SchematicSketchWidget.
addBendpoint()
void SketchWidget::addBendpoint (ItemBase * lastHoverEnterItem, ConnectorItem * lastHoverEnterConnectorItem, QPointF lastLocation)
References NonConnectorItem::attachedTo(), lastHoverEnterConnectorItem(), lastHoverEnterItem(), Wire::line(), wireJoinSlot(), and wireSplitSlot().
addDefaultParts()
void SketchWidget::addDefaultParts () virtual
Reimplemented in SchematicSketchWidget, PCBSketchWidget, and BreadboardSketchWidget.
addItem() [1/2]
ItemBase * SketchWidget::addItem (ModelPart * modelPart, ViewLayer::ViewLayerPlacement viewLayerPlacement, BaseCommand::CrossViewType crossViewType, const ViewGeometry & viewGeometry, long id, long modelIndex, AddDeleteItemCommand * originatingCommand)
References addItemAux(), BaseCommand::CrossView, AddDeleteItemCommand::dropOrigin(), itemAddedSignal(), m_sketchModel, m_viewID, and ModelPart::moduleID().
addItem() [2/2]
ItemBase * SketchWidget::addItem (const QString & moduleID, ViewLayer::ViewLayerPlacement viewLayerPlacement, BaseCommand::CrossViewType crossViewType, const ViewGeometry & viewGeometry, long id, long modelIndex, AddDeleteItemCommand * originatingCommand)
References addItem(), m_blockUI, m_referenceModel, and statusMessage().
addItemAux()
ItemBase * SketchWidget::addItemAux (ModelPart * modelPart, ViewLayer::ViewLayerPlacement viewLayerPlacement, const ViewGeometry & viewGeometry, long id, bool doConnectors, ViewLayer::ViewID viewID, bool temporary) virtual
References Wire::addedToScene(), ItemBase::addedToScene(), addPartItem(), addToScene(), PartFactory::createPart(), ItemBase::debugInfo(), ViewGeometry::getAnyTrace(), getNoteViewLayerID(), ViewGeometry::getRatsnest(), getWireViewLayerID(), ModelPart::initConnectors(), ModelPart::itemType(), m_itemMenu, m_viewID, m_viewLayers, m_wireMenu, ModelPart::Note, setClipEnds(), setNewPartVisible(), Wire::setNormal(), Wire::setUp(), ItemBase::setViewLayerID(), setWireVisible(), ViewLayer::UnknownView, ItemBase::updateConnectors(), viewID(), ItemBase::viewLayerID(), ItemBase::viewLayerPlacement(), and ItemBase::z().
addItemAuxTemp()
ItemBase * SketchWidget::addItemAuxTemp (ModelPart * modelPart, ViewLayer::ViewLayerPlacement viewLayerPlacement, const ViewGeometry & viewGeometry, long id, bool doConnectors, ViewLayer::ViewID viewID, bool temporary)
References addItemAux(), m_sketchModel, and viewID().
addLegBendpoint()
void SketchWidget::addLegBendpoint (long id, const QString & connectorID, int index, QPointF p, const class Bezier * bezierLeft, const class Bezier * bezierRight)
References ConnectorItem::addLegBendpoint(), findConnectorItem(), findItem(), ViewLayer::specFromID(), and ItemBase::viewLayerID().
addPartItem()
PaletteItem * SketchWidget::addPartItem (ModelPart * modelPart, ViewLayer::ViewLayerPlacement viewLayerPlacement, PaletteItem * paletteItem, bool doConnectors, bool & ok, ViewLayer::ViewID viewID, bool temporary) protected virtual
Reimplemented in PCBSketchWidget.
References ItemBase::addedToScene(), addToScene(), ViewLayer::Copper0, ViewLayer::Copper1, DebugDialog::debug(), getViewLayerID(), ModelPart::hasSubparts(), FMessageBox::information(), layerIsActive(), layerIsVisible(), PaletteItem::layerKin(), PaletteItem::loadLayerKin(), m_viewLayers, ModelPart::moduleID(), ModelPart::path(), PaletteItem::renderImage(), ViewLayer::SchematicView, ItemBase::setEverVisible(), ItemBase::setHidden(), ItemBase::setInactive(), ViewLayer::UnknownLayer, viewID(), and ItemBase::viewLayerID().
addSubpart
void SketchWidget::addSubpart (long id, long subpartid, bool doEmit) slot
References ItemBase::addSubpart(), addSubpartSignal(), findItem(), and ItemBase::setInstanceTitle().
addSubpartSignal
void SketchWidget::addSubpartSignal (long id, long subpartID, bool doEmit) signal
addToScene()
void SketchWidget::addToScene (ItemBase * item, ViewLayer::ViewLayerID viewLayerID) protected
References layerIsActive(), layerIsVisible(), ItemBase::setHidden(), and ItemBase::setInactive().
addToSketch()
void SketchWidget::addToSketch (QList< ModelPart * > & modelParts)
References BaseCommand::CrossView, getDroppedItemViewLayerPlacement(), ItemBase::getNextID(), m_referenceModel, m_undoStack, ModelPart::moduleID(), newAddItemCommand(), CleanUpWiresCommand::Noop, ViewGeometry::setLoc(), stackSelectionState(), CleanUpWiresCommand::UndoOnly, and WaitPushUndoStack::waitPush().
addViewLayer()
void SketchWidget::addViewLayer (ViewLayer * viewLayer)
References ViewLayer::displayName(), m_viewLayers, ViewLayer::setAction(), toggleLayerVisibility(), ViewLayer::viewLayerID(), and ViewLayer::visible().
addViewLayers()
void SketchWidget::addViewLayers () virtual
Reimplemented in PCBSketchWidget, IconSketchWidget, BreadboardSketchWidget, and SchematicSketchWidget.
addViewLayersAux()
void SketchWidget::addViewLayersAux (const LayerList & layers, const LayerList & layersFromBelow, float startZ = 1.5) protected
References addViewLayer(), layers(), m_viewLayers, m_z, and ViewLayer::setInitialZFromBelow().
addWatermark()
QGraphicsItem * SketchWidget::addWatermark (const QString & filename)
addWireExtras()
void SketchWidget::addWireExtras (long newID, QDomElement & view, QUndoCommand * parentCommand) protected
References copy().
alignedToGrid()
bool SketchWidget::alignedToGrid ()
References m_alignToGrid.
alignItems()
void SketchWidget::alignItems (Qt::Alignment alignment)
References checkMoved(), clearHoldingSelectItem(), Wire::collectChained(), ConnectorItem::connectedToItems(), Wire::connector0(), DebugDialog::debug(), disconnectFromFemale(), findConnectorsUnder(), ItemBase::getViewGeometry(), ItemBase::id(), ItemBase::itemType(), ItemBase::layerKinChief(), ViewGeometry::loc(), m_checkUnder, m_dragBendpointWire, InfoGraphicsView::m_infoView, m_moveDisconnectedFromFemale, m_moveEventCount, m_movingByArrow, m_savedItems, m_savedWires, m_stretchingLegs, prepMove(), Wire::simpleConnectedMoved(), ConnectorItem::stretchBy(), HtmlInfoView::updateLocation(), and ModelPart::Wire.
alignLoc()
void SketchWidget::alignLoc (QPointF & loc, const QPointF startPoint, const QPointF newLoc, const QPointF originalLoc) protected
References GraphicsUtils::getNearestOrdinate(), gridSizeInches(), and GraphicsUtils::SVGDPI.
alignOneToGrid()
QPointF SketchWidget::alignOneToGrid (ItemBase * itemBase)
References alignLoc(), findAlignmentAnchor(), m_alignmentItem, m_alignmentStartPoint, and m_alignToGrid.
alignToGrid()
void SketchWidget::alignToGrid (bool align)
References m_alignToGrid, and viewName().
arrowTimerTimeout
void SketchWidget::arrowTimerTimeout () protected slot
References checkMoved(), m_movingByArrow, m_savedItems, and m_savedWires.
autoScrollTimeout
void SketchWidget::autoScrollTimeout () protected slot
References m_autoScrollX, and m_autoScrollY.
background()
const QColor & SketchWidget::background ()
blockUI()
void SketchWidget::blockUI (bool block)
References m_blockUI.
bringForward()
void SketchWidget::bringForward ()
References continueZChange(), greaterThan(), and startZChange().
bringToFront()
void SketchWidget::bringToFront ()
References continueZChangeMax(), lessThan(), and startZChange().
calcItemCount()
ItemCount SketchWidget::calcItemCount ()
References ItemBase::canFlipHorizontal(), ItemBase::canFlipVertical(), ItemBase::extractTopLevelItemBase(), ItemCount::hasLabelCount, ItemBase::hasPartLabel(), ItemBase::isObsolete(), ItemBase::isPartLabelVisible(), ItemCount::itemsCount, ItemBase::itemType(), ItemBase::moveLock(), ItemCount::moveLockCount, ItemCount::obsoleteCount, ItemBase::rotation45Allowed(), ItemBase::rotationAllowed(), ItemCount::sel45Rotatable, ItemCount::selCount, ItemCount::selHFlipable, ItemCount::selRotatable, ItemCount::selVFlipable, ItemCount::visLabelCount, ModelPart::Wire, and ItemCount::wireCount.
calcNewLoc()
QPointF SketchWidget::calcNewLoc (ItemBase * moveBase, ItemBase * detachFrom) protected
References ItemBase::boundingRect().
canAlignToCenter()
bool SketchWidget::canAlignToCenter (ItemBase *) protected virtual
Reimplemented in PCBSketchWidget.
canAlignToTopLeft()
bool SketchWidget::canAlignToTopLeft (ItemBase *) protected virtual
canChainMultiple()
bool SketchWidget::canChainMultiple () protected virtual
Reimplemented in PCBSketchWidget.
canChainWire()
bool SketchWidget::canChainWire (Wire * wire) protected virtual
Reimplemented in PCBSketchWidget.
References m_chainDrag.
canConnect() [1/3]
bool SketchWidget::canConnect (ItemBase * from, ItemBase * to) protected
References canConnectSignal(), Wire::getTrace(), getTraceFlag(), Wire::isTraceType(), and m_pasting.
canConnect() [2/3]
bool SketchWidget::canConnect (Wire * from, ItemBase * to) protected virtual
Reimplemented in PCBSketchWidget, and SchematicSketchWidget.
canConnect [3/3]
void SketchWidget::canConnect (Wire * from, ItemBase * to, bool & connect) protected slot
References canConnect(), findItem(), getTraceFlag(), ItemBase::id(), and Wire::isTraceType().
canConnectSignal
void SketchWidget::canConnectSignal (Wire * from, ItemBase * to, bool & connect) signal
canCopyItem()
bool SketchWidget::canCopyItem (QGraphicsItem * item, int count) virtual
Reimplemented in PCBSketchWidget.
References ItemBase::layerKinChief().
canCreateWire()
bool SketchWidget::canCreateWire (Wire * dragWire, ConnectorItem * from, ConnectorItem * to) protected virtual
Reimplemented in PCBSketchWidget.
canDeleteItem()
bool SketchWidget::canDeleteItem (QGraphicsItem * item, int count) virtual
Reimplemented in PCBSketchWidget.
References ItemBase::layerKinChief(), and ItemBase::moveLock().
canDisconnectAll()
bool SketchWidget::canDisconnectAll () virtual
Reimplemented in BreadboardSketchWidget.
canDragWire()
bool SketchWidget::canDragWire (Wire * wire) protected virtual
Reimplemented in PCBSketchWidget.
canDropModelPart()
bool SketchWidget::canDropModelPart (ModelPart * modelPart) protected virtual
Reimplemented in PCBSketchWidget, BreadboardSketchWidget, and SchematicSketchWidget.
References m_viewLayers, viewID(), and ModelPart::viewLayers().
categorizeDragLegs()
void SketchWidget::categorizeDragLegs (bool rubberBandLegEnabled) protected
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToItemType(), ItemBase::cachedConnectorItems(), ConnectorItem::connectedToItems(), ConnectorItem::connectionsCount(), ConnectorItem::hasRubberBandLeg(), ItemBase::hasRubberBandLeg(), ItemBase::id(), ItemBase::itemType(), ItemBase::layerKinChief(), m_savedItems, m_stretchingLegs, ConnectorItem::prepareToStretch(), and ModelPart::Wire.
categorizeDragWires()
void SketchWidget::categorizeDragWires (QSet< Wire * > & wires, QList< ItemBase * > & freeWires) protected
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToItemType(), Wire::collectChained(), ConnectorItem::connectedToItems(), ConnectorItem::connectionsCount(), Wire::connector0(), Wire::connector1(), DebugDialog::debug(), FREE_, Wire::getTrace(), ItemBase::id(), IN_, ItemBase::layerKinChief(), m_savedItems, m_savedWires, OUT_, ConnectionThing::status, ItemBase::stickingTo(), UNDETERMINED_, ModelPart::Wire, and ConnectionThing::wire.
changeBoardLayers
void SketchWidget::changeBoardLayers (int layers, bool doEmit) virtual slot
References changeBoardLayersSignal(), layers(), and InfoGraphicsView::m_boardLayers.
changeBoardLayersSignal
void SketchWidget::changeBoardLayersSignal (int , bool doEmit) signal
changeBus()
void SketchWidget::changeBus (ItemBase * itemBase, bool connec, const QString & oldBus, const QString & newBus, QList< ConnectorItem * > & connectorItems, const QString & message, const QString & oldLayout, const QString & newLayout) virtual
Reimplemented from InfoGraphicsView.
References CleanUpWiresCommand::addRatsnestConnect(), NonConnectorItem::attachedToID(), ConnectorItem::connectorSharedID(), ItemBase::id(), m_undoStack, PropChangeDelay, CleanUpWiresCommand::RedoOnly, CleanUpWiresCommand::UndoOnly, and WaitPushUndoStack::waitPush().
changeConnection()
void SketchWidget::changeConnection (long fromID, const QString & fromConnectorID, long toID, const QString & toConnectorID, ViewLayer::ViewLayerPlacement viewLayerPlacement, bool connect, bool doEmit, bool updateConnections) virtual
Reimplemented in SchematicSketchWidget.
References changeConnectionAux(), and changeConnectionSignal().
changeConnectionAux()
void SketchWidget::changeConnectionAux (long fromID, const QString & fromConnectorID, long toID, const QString & toConnectorID, ViewLayer::ViewLayerPlacement viewLayerPlacement, bool connect, bool updateConnections) protected
References NonConnectorItem::attachedTo(), canConnect(), ConnectorItem::connector(), Connector::connectTo(), ConnectorItem::connectTo(), DebugDialog::debug(), Connector::disconnectFrom(), findConnectorItem(), findItem(), ItemBase::id(), m_viewID, ratsnestConnect(), ConnectorItem::removeConnection(), ItemBase::updateConnections(), and updateOK().
changeConnectionSignal
void SketchWidget::changeConnectionSignal (long fromID, QString fromConnectorID, long toID, QString toConnectorID, ViewLayer::ViewLayerPlacement , bool connect, bool updateConnections) signal
changeConnectionSlot
void SketchWidget::changeConnectionSlot (long fromID, QString fromConnectorID, long toID, QString toConnectorID, ViewLayer::ViewLayerPlacement viewLayerPlacement, bool connect, bool updateConnections) protected slot
References changeConnection().
changeLayer()
void SketchWidget::changeLayer (long id, double z, ViewLayer::ViewLayerID viewLayerID) virtual
Reimplemented in PCBSketchWidget.
changeLeg()
void SketchWidget::changeLeg (long fromID, const QString & connectorID, const QPolygonF & leg, bool relative, const QString & why)
References changeLegAux().
changeLegAux()
void SketchWidget::changeLegAux (long fromID, const QString & fromConnectorID, const QPolygonF & leg, bool reset, bool relative, bool active, const QString & why) protected
References DebugDialog::debug(), findConnectorItem(), findItem(), ConnectorItem::resetLeg(), ConnectorItem::setLeg(), ViewLayer::specFromID(), ItemBase::updateConnections(), and ItemBase::viewLayerID().
changeLegCurve()
void SketchWidget::changeLegCurve (long id, const QString & connectorID, int index, const Bezier * bezier)
References ConnectorItem::changeLegCurve(), findConnectorItem(), findItem(), ViewLayer::specFromID(), and ItemBase::viewLayerID().
changePinLabels
void SketchWidget::changePinLabels (ItemBase * itemBase, bool singleRow) protected slot
References InfoGraphicsView::changePinLabelsSignal(), and changePinLabelsSlot().
changePinLabelsSlot
void SketchWidget::changePinLabelsSlot (ItemBase * itemBase, bool singleRow) protected slot
References PaletteItem::changePinLabels(), findItem(), ItemBase::id(), ItemBase::layerKinChief(), PartFactory::makeSchematicSipOrDipOr(), PaletteItem::resetConnectors(), PaletteItem::resetLayerKin(), PaletteItem::retransform(), ViewLayer::SchematicView, PaletteItem::sipOrDipOrLabels(), PaletteItem::untransform(), and ItemBase::viewID().
changeWire()
void SketchWidget::changeWire (long fromID, QLineF line, QPointF pos, bool updateConnections, bool updateRatsnest)
References Wire::connector0(), Wire::connector1(), findItem(), ratsnestConnect(), Wire::setLineAnd(), and ItemBase::updateConnections().
changeWireColor() [1/2]
void SketchWidget::changeWireColor (long wireId, const QString & color, double opacity)
References findItem(), Wire::setColorString(), and updateInfoView().
changeWireColor [2/2]
void SketchWidget::changeWireColor (const QString newColor) slot
References Wire::collectWires(), Wire::colorString(), ItemBase::id(), m_lastColorSelected, m_undoStack, Wire::opacity(), PropChangeDelay, and WaitPushUndoStack::waitPush().
changeWireCurve()
void SketchWidget::changeWireCurve (long id, const Bezier * bezier, bool autoroutable)
References Wire::changeCurve(), findItem(), and Wire::setAutoroutable().
changeWireFlags()
void SketchWidget::changeWireFlags (long wireId, ViewGeometry::WireFlags wireFlags)
References findItem().
changeWireWidth()
void SketchWidget::changeWireWidth (long wireId, double width)
References findItem(), InfoGraphicsView::getWireStrokeWidth(), Wire::setWireWidth(), and updateInfoView().
changeWireWidthMils
void SketchWidget::changeWireWidthMils (const QString newWidth) slot
References Wire::collectWires(), Wire::getTrace(), ItemBase::id(), m_undoStack, PropChangeDelay, GraphicsUtils::SVGDPI, WaitPushUndoStack::waitPush(), and Wire::width().
changeZ()
void SketchWidget::changeZ (QHash< long, RealPair * > triplets, double(*)(RealPair *) pairAccessor)
References ViewLayer::getZFromBelow(), ItemBase::id(), m_viewLayers, ZoomableGraphicsView::viewFromBelow(), and ItemBase::viewLayerID().
checkAutoscroll()
bool SketchWidget::checkAutoscroll (QPoint globalPos) protected
References m_autoScrollCount, m_autoScrollThreshold, m_autoScrollTimer, m_autoScrollX, m_autoScrollY, and m_clearSceneRect.
checkDroppedModuleID()
QString SketchWidget::checkDroppedModuleID (const QString & moduleID) protected virtual
Reimplemented in PCBSketchWidget, and SchematicSketchWidget.
checkFit()
void SketchWidget::checkFit (ModelPart * newModelPart, ItemBase * itemBase, long newID, QHash< ConnectorItem *, Connector * > & found, QList< ConnectorItem * > & notFound, QHash< ConnectorItem *, ConnectorItem * > & m2f, QHash< ConnectorItem *, Connector * > & byWire, QHash< QString, QPolygonF > & legs, QHash< QString, ConnectorItem * > & formerLegs, QUndoCommand * parentCommand) protected
References addItemAuxTemp(), checkFitAux(), ItemBase::getViewGeometry(), m_viewID, and ItemBase::viewLayerPlacement().
checkFitAux()
void SketchWidget::checkFitAux (ItemBase * tempItemBase, ItemBase * itemBase, long newID, QHash< ConnectorItem *, Connector * > & found, QList< ConnectorItem * > & notFound, QHash< ConnectorItem *, ConnectorItem * > & m2f, QHash< ConnectorItem *, Connector * > & byWire, QHash< QString, QPolygonF > & legs, QHash< QString, ConnectorItem * > & formerLegs, QUndoCommand * parentCommand) protected
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToID(), ConnectorItem::attachedToViewLayerID(), ItemBase::cachedConnectorItems(), CloseEnough, ConnectorItem::connectedToItems(), ConnectorItem::connector(), Connector::connectorShared(), ConnectorItem::connectorSharedID(), ConnectorItem::connectorType(), BaseCommand::CrossView, Connector::Female, ConnectorItem::hasRubberBandLeg(), ItemBase::hasRubberBandLeg(), ConnectorItem::leg(), Connector::Male, ConnectorItem::sceneAdjustedTerminalPoint(), and ViewLayer::specFromID().
checkForReversedWires()
void SketchWidget::checkForReversedWires ()
References Wire::changeCurve(), Wire::connector0(), Wire::connector0Rect(), Wire::connector1(), Wire::connector1Rect(), Bezier::cp0(), Bezier::cp1(), Wire::curve(), ItemBase::debugInfo(), Bezier::endpoint0(), Bezier::endpoint1(), ConnectorItem::firstConnectedToIsh(), getTraceFlag(), Wire::isCurved(), Wire::isTraceType(), Wire::line(), ConnectorItem::sceneAdjustedTerminalPoint(), Bezier::set_cp0(), Bezier::set_cp1(), Bezier::set_endpoints(), Wire::setConnector0Rect(), and Wire::setLineAnd().
checkMoved()
bool SketchWidget::checkMoved (bool wait) protected
References MoveItemsCommand::addItem(), MoveItemsCommand::addWire(), ConnectorItem::attachedToViewLayerID(), ModelPart::Breadboard, ItemBase::cachedConnectorItems(), ConnectorItem::clearConnectorHover(), ItemBase::clearConnectorHover(), clearHoldingSelectItem(), clearTemporaries(), ConnectorItem::connectionsCount(), ConnectorItem::connectorHover(), BaseCommand::CrossView, extendChangeConnectionCommand(), ItemBase::getViewGeometry(), ItemBase::id(), Board::isBoard(), ItemBase::itemType(), ViewGeometry::loc(), m_moveDisconnectedFromFemale, m_moveEventCount, m_savedItems, m_savedWires, m_undoStack, m_viewID, moveLegBendpoints(), ConnectorItem::overConnectorItem(), PropChangeDelay, WaitPushUndoStack::push(), CheckStickyCommand::RedoOnly, CleanUpWiresCommand::RedoOnly, rememberSticky(), ConnectorItem::restoreColor(), ItemBase::saveGeometry(), CleanUpWiresCommand::setDirection(), ConnectorItem::setOverConnectorItem(), BaseCommand::SingleView, ViewLayer::specFromID(), ItemBase::title(), CleanUpWiresCommand::UndoOnly, ViewLayer::viewIDName(), viewName(), WaitPushUndoStack::waitPush(), and ModelPart::Wire.
checkSticky
void SketchWidget::checkSticky (long id, bool doEmit, bool checkCurrent, CheckStickyCommand * checkStickyCommand) slot
References ItemBase::addSticky(), checkStickySignal(), findItem(), ItemBase::hidden(), ItemBase::id(), ItemBase::isBaseSticky(), ItemBase::layerHidden(), overSticky(), CheckStickyCommand::stick(), ItemBase::stickingTo(), and stickyScoop().
checkStickySignal
void SketchWidget::checkStickySignal (long id, bool doEmit, bool checkCurrent, CheckStickyCommand *) signal
checkUnder()
bool SketchWidget::checkUnder () protected virtual
Reimplemented in BreadboardSketchWidget.
checkUpdateRatsnest()
bool SketchWidget::checkUpdateRatsnest (QList< ConnectorItem * > & connectorItems) protected
References m_ratsnestUpdateConnect, and m_ratsnestUpdateDisconnect.
cleanupRatsnests() [1/2]
void SketchWidget::cleanupRatsnests (QList< QPointer< ConnectorItem > > & connectorItems, bool connect) protected
References ConnectorItem::collectEqualPotential(), ratsnestConnect(), and ViewGeometry::RatsnestFlag.
cleanupRatsnests [2/2]
void SketchWidget::cleanupRatsnests (bool doEmit) slot
References cleanupRatsnests(), cleanupRatsnestsSignal(), m_ratsnestCacheConnect, and m_ratsnestCacheDisconnect.
cleanupRatsnestsSignal
void SketchWidget::cleanupRatsnestsSignal (bool doEmit) signal
cleanUpWires()
void SketchWidget::cleanUpWires (bool doEmit, class CleanUpWiresCommand * command)
References cleanUpWiresSignal(), and updateRoutingStatus().
cleanUpWiresSignal
void SketchWidget::cleanUpWiresSignal (CleanUpWiresCommand *) signal
cleanUpWiresSlot
void SketchWidget::cleanUpWiresSlot (CleanUpWiresCommand * command) protected slot
References updateRoutingStatus().
clearDragWireTempCommand()
void SketchWidget::clearDragWireTempCommand () protected
References m_tempDragWireCommand.
clearHoldingSelectItem()
void SketchWidget::clearHoldingSelectItem () protected
References m_holdingSelectItemCommand.
clearPasteOffset()
void SketchWidget::clearPasteOffset ()
clearSelection()
void SketchWidget::clearSelection ()
References clearSelectionSignal().
clearSelectionSignal
void SketchWidget::clearSelectionSignal () signal
clearSelectionSlot
void SketchWidget::clearSelectionSlot () protected slot
clearTemporaries()
void SketchWidget::clearTemporaries () protected
References m_temporaries.
clickBackground()
void SketchWidget::clickBackground (QMouseEvent *) protected
clickedItemCandidateSignal
void SketchWidget::clickedItemCandidateSignal (QGraphicsItem * , bool & ok) signal
collectAllNets()
void SketchWidget::collectAllNets (QHash< class ConnectorItem *, int > & indexer, QList< QList< class ConnectorItem * > * > & allPartConnectorItems, bool includeSingletons, bool bothSides)
References ConnectorItem::attachedToViewLayerID(), ConnectorItem::collectEqualPotential(), ConnectorItem::collectParts(), ViewLayer::Copper1, includeSymbols(), ViewLayer::NewTopAndBottom, and ViewGeometry::NoFlag.
collectFemaleConnectees()
bool SketchWidget::collectFemaleConnectees (ItemBase * itemBase, QSet< ItemBase * > & items) protected virtual
Reimplemented in BreadboardSketchWidget.
collectParts()
void SketchWidget::collectParts (QList< ItemBase * > & partList)
References ItemBase::itemType(), and ModelPart::Symbol.
collectRatsnestSignal
void SketchWidget::collectRatsnestSignal (QList< SketchWidget * > & foreignSketchWidgets) signal
collectRatsnestSlot
void SketchWidget::collectRatsnestSlot (QList< SketchWidget * > & foreignSketchWidgets) protected slot
collectSuperSubs()
QList< ItemBase * > SketchWidget::collectSuperSubs (ItemBase * itemBase) protected
References ItemBase::layerKinChief(), ItemBase::subparts(), and ItemBase::superpart().
contextMenuEvent()
void SketchWidget::contextMenuEvent (QContextMenuEvent * event) protected
References squashShapes(), and unsquashShapes().
continueZChange()
void SketchWidget::continueZChange (QList< ItemBase * > & bases, int start, int end, bool(*)(int current, int start) test, int inc, const QString & text) protected
References continueZChangeAux(), ItemBase::getViewGeometry(), ViewGeometry::selected(), and ItemBase::viewLayerID().
continueZChangeAux()
void SketchWidget::continueZChangeAux (QList< ItemBase * > & bases, const QString & text) protected
References ChangeZCommand::addTriplet(), ViewLayer::getZIncrement(), m_undoStack, WaitPushUndoStack::push(), and ViewLayer::UnknownLayer.
continueZChangeMax()
void SketchWidget::continueZChangeMax (QList< ItemBase * > & bases, int start, int end, bool(*)(int current, int start) test, int inc, const QString & text) protected
References continueZChangeAux(), DebugDialog::debug(), ItemBase::getViewGeometry(), and ViewGeometry::selected().
copy()
void SketchWidget::copy ()
References collectSuperSubs(), copyAux(), ItemBase::extractTopLevelItemBase(), ItemBase::getRatsnest(), and sortAnyByZ().
copyAux()
void SketchWidget::copyAux (QList< ItemBase * > & bases, bool saveBoundingRects) protected
References NonConnectorItem::attachedTo(), Wire::collectChained(), copyHeart(), Wire::getTrace(), ItemBase::layerKinChief(), and removeOutsideConnections().
copyBoundingRectsSignal
void SketchWidget::copyBoundingRectsSignal (QHash< QString, QRectF > &) signal
copyBoundingRectsSlot
void SketchWidget::copyBoundingRectsSlot (QHash< QString, QRectF > & boundingRects) protected slot
References ItemBase::extractTopLevelItemBase(), ItemBase::getRatsnest(), and m_viewName.
copyDrop()
void SketchWidget::copyDrop () protected
References collectSuperSubs(), copyAux(), ItemBase::getViewGeometry(), ViewGeometry::loc(), m_savedItems, m_savedWires, ItemBase::setItemPos(), and ItemBase::zLessThan().
copyHeart()
void SketchWidget::copyHeart (QList< ItemBase * > & bases, bool saveBoundingRects, QByteArray & itemData, QList< long > & modelIndexes)
References copyBoundingRectsSignal(), ItemBase::getRatsnest(), m_viewName, ModelPart::modelIndex(), ItemBase::modelPart(), ModelPart::saveInstances(), and Version::versionString().
createOneTrace()
bool SketchWidget::createOneTrace (Wire * wire, ViewGeometry::WireFlag flag, bool allowAny, QList< Wire * > & done, bool useLastWireColor, QUndoCommand * parentCommand) protected
References createWire(), createWireViewLayerPlacement(), BaseCommand::CrossView, Wire::findTraced(), ItemBase::getRatsnest(), getTraceFlag(), getTraceWidth(), Wire::hasFlag(), Wire::isTraceType(), m_lastColorSelected, removeWire(), and traceColor().
createTempWireForDragging()
Wire * SketchWidget::createTempWireForDragging (Wire * fromWire, ModelPart * wireModel, ConnectorItem * connectorItem, ViewGeometry & viewGeometry, ViewLayer::ViewLayerPlacement spec) protected virtual
Reimplemented in PCBSketchWidget, and SchematicSketchWidget.
References addItemAuxTemp(), ItemBase::getNextID(), m_viewID, ViewLayer::UnknownPlacement, and wireViewLayerPlacement().
createTrace() [1/2]
void SketchWidget::createTrace (Wire * wire, bool useLastWireColor) virtual
Reimplemented in PCBSketchWidget.
References getTraceFlag().
createTrace() [2/2]
void SketchWidget::createTrace (Wire * fromWire, const QString & commandString, ViewGeometry::WireFlag flag, bool useLastWireColor) protected
References createOneTrace(), m_undoStack, WaitPushUndoStack::push(), CleanUpWiresCommand::RedoOnly, and CleanUpWiresCommand::UndoOnly.
createWire()
long SketchWidget::createWire (ConnectorItem * from, ConnectorItem * to, ViewGeometry::WireFlags wireFlags, bool dontUpdate, BaseCommand::CrossViewType crossViewType, QUndoCommand * parentCommand)
References NonConnectorItem::attachedToID(), NonConnectorItem::attachedToTitle(), ConnectorItem::connectorSharedID(), createWireViewLayerPlacement(), DebugDialog::debug(), ItemBase::getNextID(), m_viewID, CheckStickyCommand::RemoveOnly, ConnectorItem::sceneAdjustedTerminalPoint(), ViewGeometry::setLine(), ViewGeometry::setLoc(), ChangeConnectionCommand::setUpdateConnections(), ViewGeometry::setWireFlags(), and ModuleIDNames::WireModuleIDName.
createWireViewLayerPlacement()
ViewLayer::ViewLayerPlacement SketchWidget::createWireViewLayerPlacement (ConnectorItem * from, ConnectorItem * to) protected virtual
Reimplemented in PCBSketchWidget, and SchematicSketchWidget.
References ConnectorItem::attachedToViewLayerPlacement().
currentlyInfoviewed()
bool SketchWidget::currentlyInfoviewed (ItemBase * item) protected
References HtmlInfoView::currentItem(), and InfoGraphicsView::m_infoView.
cursorLocationSignal
void SketchWidget::cursorLocationSignal (double xinches, double yinches, double width = 0.0, double height = 0.0) signal
curvyWires()
bool SketchWidget::curvyWires ()
References m_curvyWires.
curvyWiresIndicated()
bool SketchWidget::curvyWiresIndicated (Qt::KeyboardModifiers modifiers) virtual
Reimplemented from InfoGraphicsView.
References m_curvyWires.
cut()
void SketchWidget::cut ()
References copy(), and cutDeleteAux().
cutDeleteAux()
void SketchWidget::cutDeleteAux (QString undoStackMessage, bool minus, Wire * wire) protected
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToItemType(), ItemBase::cachedConnectorItems(), canDeleteItem(), Wire::collectDirectWires(), ConnectorItem::connectedToItems(), deleteAux(), ConnectorItem::getCrossLayerConnectorItem(), ItemBase::getRatsnest(), ItemBase::layerKinChief(), ItemBase::subparts(), ItemBase::superpart(), ItemBase::title(), and ModelPart::Wire.
defaultConnectorLayer()
ViewLayer::ViewLayerID SketchWidget::defaultConnectorLayer (ViewLayer::ViewID viewId) static
References ViewLayer::Breadboard, ViewLayer::BreadboardView, ViewLayer::Copper0, ViewLayer::Icon, ViewLayer::IconView, ViewLayer::PCBView, ViewLayer::Schematic, ViewLayer::SchematicView, and ViewLayer::UnknownLayer.
defaultGridSizeInches()
double SketchWidget::defaultGridSizeInches () virtual
Reimplemented in PCBSketchWidget, BreadboardSketchWidget, and SchematicSketchWidget.
defaultViewLayerPlacement()
ViewLayer::ViewLayerPlacement SketchWidget::defaultViewLayerPlacement (ModelPart * modelPart) virtual
Reimplemented in PCBSketchWidget.
References ViewLayer::NewTop.
deleteAux()
void SketchWidget::deleteAux (QSet< ItemBase * > & deletedItems, QUndoCommand * parentCommand, bool doPush) protected
References BaseCommand::CrossView, deleteMiddle(), ItemBase::id(), m_undoStack, makeDeleteItemCommand(), PropChangeDelay, CleanUpWiresCommand::RedoOnly, BaseCommand::setUndoOnly(), stackSelectionState(), ItemBase::superpart(), CleanUpWiresCommand::UndoOnly, and WaitPushUndoStack::waitPush().
deleteItem() [1/2]
void SketchWidget::deleteItem (long id, bool deleteModelPart, bool doEmit, bool later)
References DebugDialog::debug(), findItem(), itemDeletedSignal(), and m_viewID.
deleteItem() [2/2]
void SketchWidget::deleteItem (ItemBase * itemBase, bool deleteModelPart, bool doEmit, bool later) virtual
Reimplemented in PartsEditorView, and PCBSketchWidget.
References DebugDialog::debug(), ItemBase::id(), itemDeletedSignal(), InfoGraphicsView::m_infoView, m_lastPaletteItemSelected, m_sketchModel, m_viewID, setLastPaletteItemSelected(), ItemBase::title(), and HtmlInfoView::unregisterCurrentItemIf().
deleteMiddle()
void SketchWidget::deleteMiddle (QSet< ItemBase * > & deletedItems, QUndoCommand * parentCommand)
References ConnectorItem::attachedToViewLayerID(), ItemBase::cachedConnectorItems(), ConnectorItem::connectedToItems(), BaseCommand::CrossView, extendChangeConnectionCommand(), ConnectorItem::getCrossLayerConnectorItem(), ViewLayer::specFromID(), and ConnectorItem::tempRemove().
deleteRatsnest
void SketchWidget::deleteRatsnest (Wire * ratsnest, QUndoCommand * parentCommand) protected slot
References ConnectorItem::collectEqualPotential(), collectRatsnestSignal(), Wire::connector0(), Wire::connector1(), ConnectorItem::firstConnectedToIsh(), GraphUtils::minCut(), ViewGeometry::RatsnestFlag, and removeRatsnestSignal().
deleteSelected()
void SketchWidget::deleteSelected (Wire * wire, bool minus)
References cutDeleteAux(), deleteRatsnest(), ItemBase::getRatsnest(), ItemBase::layerKinChief(), m_undoStack, ItemBase::moveLock(), PropChangeDelay, CleanUpWiresCommand::RedoOnly, CleanUpWiresCommand::UndoOnly, and WaitPushUndoStack::waitPush().
deleteTemporary
void SketchWidget::deleteTemporary () protected slot
References deleteItem(), WaitPushUndoStack::deleteTemporary(), ItemBase::id(), and m_undoStack.
deleteTracesSignal
void SketchWidget::deleteTracesSignal (QSet< ItemBase * > & deletedItems, QHash< ItemBase *, SketchWidget * > & otherDeletedItems, QList< long > & deletedIDs, bool isForeign, QUndoCommand * parentCommand) signal
deleteTracesSlot
void SketchWidget::deleteTracesSlot (QSet< ItemBase * > & deletedItems, QHash< ItemBase *, SketchWidget * > & otherDeletedItems, QList< long > & deletedIDs, bool isForeign, QUndoCommand * parentCommand) protected slot
References NonConnectorItem::attachedTo(), ItemBase::cachedConnectorItems(), Wire::collectChained(), ConnectorItem::connectedToItems(), findItem(), ConnectorItem::getCrossLayerConnectorItem(), getTraceFlag(), ItemBase::id(), Wire::isTraceType(), ItemBase::itemType(), ModelPart::Jumper, ItemBase::saveGeometry(), and ModelPart::Wire.
disconnectAll()
void SketchWidget::disconnectAll ()
References ConnectorItem::connectedToWires(), BaseCommand::CrossView, disconnectAllSignal(), disconnectAllSlot(), m_undoStack, WaitPushUndoStack::push(), CleanUpWiresCommand::RedoOnly, ItemBase::rightClickedConnector(), stackSelectionState(), ItemBase::title(), and CleanUpWiresCommand::UndoOnly.
disconnectAllSignal
void SketchWidget::disconnectAllSignal (QList< ConnectorItem * > , QHash< ItemBase *, SketchWidget * > & itemsToDelete, QUndoCommand * parentCommand) signal
disconnectAllSlot
void SketchWidget::disconnectAllSlot (QList< ConnectorItem * > connectorItems, QHash< ItemBase *, SketchWidget * > & itemsToDelete, QUndoCommand * parentCommand) slot
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToID(), NonConnectorItem::attachedToItemType(), calcNewLoc(), Wire::collectChained(), ConnectorItem::connectedToItems(), ConnectorItem::connectorSharedID(), ConnectorItem::connectorType(), createWire(), BaseCommand::CrossView, deleteMiddle(), disconnectFromFemale(), Connector::Female, findConnectorItem(), findItem(), ItemBase::getRatsnest(), ItemBase::getViewGeometry(), ItemBase::id(), ignoreFemale(), ViewLayer::NewBottom, ViewLayer::NewTop, ViewGeometry::NoFlag, ItemBase::saveGeometry(), ViewGeometry::setLoc(), and ModelPart::Wire.
disconnectFromFemale()
bool SketchWidget::disconnectFromFemale (ItemBase * item, QHash< long, ItemBase * > & savedItems, ConnectorPairHash & connectorHash, bool doCommand, bool rubberBandLegEnabled, QUndoCommand * parentCommand) protected virtual
Reimplemented in BreadboardSketchWidget.
dragAutoScrollTimeout
void SketchWidget::dragAutoScrollTimeout () protected slot
References autoScrollTimeout(), dragMoveHighlightConnector(), and m_globalPos.
dragEnterEvent()
void SketchWidget::dragEnterEvent (QDragEnterEvent * event) protected
References dragEnterEventAux(), m_checkUnder, m_movingItem, m_movingSVGOffset, m_movingSVGRenderer, and setupAutoscroll().
dragEnterEventAux()
bool SketchWidget::dragEnterEventAux (QDragEnterEvent * event) protected
References addItemAuxTemp(), ItemDrag::cache(), canDropModelPart(), checkDroppedModuleID(), checkUnder(), defaultViewLayerPlacement(), dragIsDoneSlot(), ensureLayerVisible(), findAlignmentAnchor(), ItemBase::getNextID(), getNoteViewLayerID(), getPartViewLayerID(), getRulerViewLayerID(), getWireViewLayerID(), ModelPart::itemType(), m_checkUnder, m_clearSceneRect, m_droppingItem, m_droppingOffset, m_droppingWire, m_referenceModel, m_viewID, ModelPart::moduleID(), ModuleIDNames::NoteModuleIDName, ModuleIDNames::RulerModuleIDName, ViewGeometry::setLoc(), ItemDrag::singleton(), and ModelPart::Wire.
draggingWireEnd()
bool SketchWidget::draggingWireEnd () protected
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToItemType(), Wire::draggingEnd(), m_connectorDragWire, and ModelPart::Wire.
dragIsDoneSlot
void SketchWidget::dragIsDoneSlot (class ItemDrag * itemDrag) protected slot
References killDroppingItem().
dragLeaveEvent()
void SketchWidget::dragLeaveEvent (QDragLeaveEvent * event) protected
References m_clearSceneRect, m_droppingItem, m_movingItem, and turnOffAutoscroll().
dragMoveEvent()
void SketchWidget::dragMoveEvent (QDragMoveEvent * event) protected
References GraphicsUtils::calcConstraint(), dragMoveHighlightConnector(), m_globalPos, m_mousePressGlobalPos, m_moveEventCount, m_movingItem, m_movingSVGOffset, m_rubberBandLegWasEnabled, and moveItems().
dragMoveHighlightConnector()
void SketchWidget::dragMoveHighlightConnector (QPoint eventPos) protected
References alignLoc(), checkAutoscroll(), m_alignmentItem, m_alignmentStartPoint, m_alignToGrid, m_checkUnder, m_droppingItem, m_droppingOffset, and m_globalPos.
dragRatsnestChanged()
void SketchWidget::dragRatsnestChanged () protected
References NonConnectorItem::attachedToID(), ViewLayer::BreadboardView, ConnectorItem::connectorSharedID(), createWireViewLayerPlacement(), BaseCommand::CrossView, ItemBase::getNextID(), getTraceFlag(), getTraceWidth(), ViewGeometry::line(), ViewGeometry::loc(), m_bendpointVG, m_bendpointWire, m_connectorDragConnector, m_connectorDragWire, m_lastColorSelected, m_undoStack, m_viewID, WaitPushUndoStack::push(), CleanUpWiresCommand::RedoOnly, removeDragWire(), CheckStickyCommand::RemoveOnly, ViewGeometry::setWireFlags(), ConnectorItem::tempConnectTo(), ConnectorItem::tempRemove(), traceColor(), CleanUpWiresCommand::UndoOnly, and ViewLayer::UnknownPlacement.
dragWireChanged()
void SketchWidget::dragWireChanged (class Wire * wire, ConnectorItem * from, ConnectorItem * to) protected
References SelectItemCommand::addRedo(), NonConnectorItem::attachedToID(), ConnectorItem::attachedToViewLayerID(), canCreateWire(), clearDragWireTempCommand(), clearTemporaries(), ConnectorItem::connectedToItems(), Wire::connector0(), Wire::connector1(), ConnectorItem::connectorSharedID(), SelectItemCommand::copyUndo(), BaseCommand::CrossView, Wire::curve(), DebugDialog::debug(), dragRatsnestChanged(), extendChangeConnectionCommand(), Wire::getAutoroutable(), ItemBase::getRatsnest(), getTraceFlag(), ItemBase::id(), ViewGeometry::line(), ViewGeometry::loc(), m_bendpointVG, m_bendpointWire, m_connectorDragConnector, m_connectorDragWire, m_tempDragWireCommand, m_undoStack, SelectItemCommand::NormalSelect, Wire::otherConnector(), prereleaseTempWireForDragging(), WaitPushUndoStack::push(), CleanUpWiresCommand::RedoOnly, removeDragWire(), CheckStickyCommand::RemoveOnly, BaseCommand::setRedoOnly(), BaseCommand::setUndoOnly(), setUpColor(), ViewGeometry::setWireFlags(), ViewLayer::specFromID(), ConnectorItem::tempRemove(), CleanUpWiresCommand::UndoOnly, and ItemBase::viewLayerID().
drawBackground()
void SketchWidget::drawBackground (QPainter * painter, const QRectF & rect) protected
References m_gridColor, m_gridSizeInches, m_showGrid, and GraphicsUtils::SVGDPI.
dropEvent()
void SketchWidget::dropEvent (QDropEvent * event) protected
References checkMoved(), ConnectorItem::clearEqualPotentialDisplay(), clearHoldingSelectItem(), copyDrop(), DebugDialog::debug(), dropItemEvent(), dropPasteSignal(), m_alignmentItem, m_mousePressGlobalPos, m_moveReferenceItem, m_movingItem, m_pasteCount, m_pasteOffset, m_savedItems, m_savedWires, and turnOffAutoscroll().
dropItemEvent()
void SketchWidget::dropItemEvent (QDropEvent * event) protected
References SelectItemCommand::addRedo(), NonConnectorItem::attachedTo(), ConnectorItem::attachedToViewLayerID(), clearTemporaries(), ConnectorItem::connectorHover(), ModelPart::CopperFill, BaseCommand::CrossView, dropSignal(), extendChangeConnectionCommand(), getDroppedItemViewLayerPlacement(), ModelPart::itemType(), killDroppingItem(), m_clearSceneRect, m_droppingItem, m_droppingOffset, m_lastColorSelected, m_undoStack, ModelPart::modelPartShared(), ModelPart::moduleID(), newAddItemCommand(), CleanUpWiresCommand::Noop, SelectItemCommand::NormalSelect, ModelPart::Note, ConnectorItem::overConnectorItem(), CleanUpWiresCommand::RedoOnly, CheckStickyCommand::RemoveOnly, ModelPart::Ruler, CleanUpWiresCommand::setDirection(), AddDeleteItemCommand::setDropOrigin(), ConnectorItem::setOverConnectorItem(), BaseCommand::SingleView, ViewLayer::specFromID(), stackSelectionState(), CleanUpWiresCommand::UndoOnly, WaitPushUndoStack::waitPush(), WaitPushUndoStack::waitPushTemporary(), and ModelPart::Wire.
dropPasteSignal
void SketchWidget::dropPasteSignal (SketchWidget *) signal
dropSignal
void SketchWidget::dropSignal (const QPoint & pos) signal
ensureLayerVisible()
void SketchWidget::ensureLayerVisible (ViewLayer::ViewLayerID viewLayerID)
References m_viewLayers, setLayerVisible(), and ViewLayer::visible().
everZoomed()
constexpr bool SketchWidget::everZoomed () const inline noexcept
References m_everZoomed.
extendChangeConnectionCommand() [1/2]
ChangeConnectionCommand * SketchWidget::extendChangeConnectionCommand (BaseCommand::CrossViewType crossView, long fromID, const QString & fromConnectorID, long toID, const QString & toConnectorID, ViewLayer::ViewLayerPlacement viewLayerPlacement, bool connect, QUndoCommand * parent) protected
References findConnectorItem(), and findItem().
extendChangeConnectionCommand() [2/2]
ChangeConnectionCommand * SketchWidget::extendChangeConnectionCommand (BaseCommand::CrossViewType crossView, ConnectorItem * fromConnectorItem, ConnectorItem * toConnectorItem, ViewLayer::ViewLayerPlacement viewLayerPlacement, bool connect, QUndoCommand * parentCommand) protected
References NonConnectorItem::attachedTo(), ConnectorItem::connectorSharedID(), and ItemBase::id().
extraRenderSvgStep()
void SketchWidget::extraRenderSvgStep (ItemBase * itemBase, QPointF offset, double dpi, double printerScale, QString & outputSvg) protected virtual
Reimplemented in SchematicSketchWidget.
filenameIf()
const QString & SketchWidget::filenameIf () virtual
Reimplemented from InfoGraphicsView.
References filenameIfSignal().
filenameIfSignal
void SketchWidget::filenameIfSignal (QString & filename) signal
findAlignmentAnchor()
void SketchWidget::findAlignmentAnchor (ItemBase * originatingItem, QHash< long, ItemBase * > & savedItems, QHash< Wire *, ConnectorItem * > & savedWires) protected virtual
References ItemBase::cachedConnectorItems(), canAlignToCenter(), canAlignToTopLeft(), Wire::connector0(), m_alignmentItem, m_alignmentStartPoint, m_alignToGrid, and ConnectorItem::sceneAdjustedTerminalPoint().
findConnectorItem() [1/2]
ConnectorItem * SketchWidget::findConnectorItem (ConnectorItem * foreignConnectorItem)
References NonConnectorItem::attachedTo(), ConnectorItem::connectorSharedID(), findItem(), ItemBase::id(), ItemBase::layerKinChief(), ViewLayer::NewBottom, and ViewLayer::NewTop.
findConnectorItem() [2/2]
ConnectorItem * SketchWidget::findConnectorItem (ItemBase * item, const QString & connectorID, ViewLayer::ViewLayerPlacement viewLayerPlacement) protected
References DebugDialog::debug(), and ItemBase::findConnectorItemWithSharedID().
findConnectorsUnder()
void SketchWidget::findConnectorsUnder (ItemBase * item) protected virtual
Reimplemented in BreadboardSketchWidget.
findItem()
ItemBase * SketchWidget::findItem (long id)
References ItemBase::id(), ModelPart::indexMultiplier, ItemBase::layerKin(), and ItemBase::layerKinChief().
findPartOrWire()
long SketchWidget::findPartOrWire (long itemID) protected
References findItem(), ItemBase::id(), ItemBase::itemType(), and ModelPart::Wire.
fitInWindow()
double SketchWidget::fitInWindow ()
References ZoomableGraphicsView::absoluteZoom(), ItemBase::isEverVisible(), and ZoomableGraphicsView::m_scaleValue.
flattenCurve()
void SketchWidget::flattenCurve (ItemBase * lastHoverEnterItem, ConnectorItem * lastHoverEnterConnectorItem, QPointF lastLocation)
References NonConnectorItem::attachedTo(), Wire::curve(), lastHoverEnterConnectorItem(), lastHoverEnterItem(), and wireChangedCurveSlot().
flipItem()
void SketchWidget::flipItem (long id, Qt::Orientations orientation)
References findItem(), ItemBase::flipItem(), InfoGraphicsView::m_infoView, ratsnestConnect(), and HtmlInfoView::updateRotation().
flipX()
void SketchWidget::flipX (Qt::Orientations orientation, bool rubberBandLegEnabled)
References NonConnectorItem::attachedToID(), ModelPart::Breadboard, ItemBase::canFlip(), clearHoldingSelectItem(), clearTemporaries(), ConnectorItem::connectorSharedID(), ModelPart::CopperFill, disconnectFromFemale(), ItemBase::extractTopLevelItemBase(), ModelPart::Hole, ItemBase::id(), Board::isBoard(), ItemBase::isSticky(), ItemBase::itemType(), m_savedItems, m_savedWires, m_stretchingLegs, m_undoStack, m_viewID, moveLegBendpoints(), ModelPart::Note, prepMove(), WaitPushUndoStack::push(), CleanUpWiresCommand::RedoOnly, ConnectorItem::stretchDone(), CleanUpWiresCommand::UndoOnly, ModelPart::Unknown, ModelPart::Via, ViewLayer::viewIDName(), and ModelPart::Wire.
forwardRoutingStatus()
void SketchWidget::forwardRoutingStatus (const RoutingStatus & routingStatus) virtual
Reimplemented in PCBSketchWidget.
References routingStatusSignal().
getAutorouterSettings()
QHash< QString, QString > SketchWidget::getAutorouterSettings () virtual
Reimplemented in PCBSketchWidget, and SchematicSketchWidget.
getBendpointWidths()
void SketchWidget::getBendpointWidths (class Wire * wire, double w, double & w1, double & w2, bool & negativeOffsetRect) virtual
Reimplemented from InfoGraphicsView.
getClickedItem()
QGraphicsItem * SketchWidget::getClickedItem (QList< QGraphicsItem * > & items) protected
References clickedItemCandidateSignal().
getConnectorViewLayerID()
ViewLayer::ViewLayerID SketchWidget::getConnectorViewLayerID () protected
References m_connectorViewLayerID.
getDragWireViewLayerID()
ViewLayer::ViewLayerID SketchWidget::getDragWireViewLayerID (ConnectorItem *) protected virtual
Reimplemented in PCBSketchWidget, and SchematicSketchWidget.
References m_wireViewLayerID.
getDroppedItemViewLayerPlacement
void SketchWidget::getDroppedItemViewLayerPlacement (ModelPart * modelPart, ViewLayer::ViewLayerPlacement & viewLayerPlacement) protected virtual slot
References getDroppedItemViewLayerPlacementSignal().
getDroppedItemViewLayerPlacementSignal
void SketchWidget::getDroppedItemViewLayerPlacementSignal (ModelPart * modelPart, ViewLayer::ViewLayerPlacement &) signal
getLabelViewLayerID()
ViewLayer::ViewLayerID SketchWidget::getLabelViewLayerID (ItemBase *) protected virtual
Reimplemented in PCBSketchWidget, SchematicSketchWidget, and BreadboardSketchWidget.
References ViewLayer::UnknownLayer.
getNoteViewLayerID()
ViewLayer::ViewLayerID SketchWidget::getNoteViewLayerID () protected
References m_noteViewLayerID.
getPartViewLayerID()
ViewLayer::ViewLayerID SketchWidget::getPartViewLayerID () protected
References m_partViewLayerID.
getRatsnestColor()
void SketchWidget::getRatsnestColor (QColor & color) virtual
Reimplemented from InfoGraphicsView.
References m_viewID, and RatsnestColors::netColor().
getRulerViewLayerID()
ViewLayer::ViewLayerID SketchWidget::getRulerViewLayerID () protected
References m_rulerViewLayerID.
getSelectedPart()
PaletteItem * SketchWidget::getSelectedPart ()
getShortName()
const QString & SketchWidget::getShortName ()
References m_shortName.
getTopZ()
float SketchWidget::getTopZ ()
References m_z.
getTraceFlag()
ViewGeometry::WireFlag SketchWidget::getTraceFlag () virtual
Reimplemented from InfoGraphicsView.
References ViewGeometry::NormalFlag.
getTraceWidth()
double SketchWidget::getTraceWidth () protected virtual
Reimplemented in PCBSketchWidget, SchematicSketchWidget, and BreadboardSketchWidget.
getViewLayerID()
ViewLayer::ViewLayerID SketchWidget::getViewLayerID (ModelPart * modelPart, ViewLayer::ViewID viewID, ViewLayer::ViewLayerPlacement viewLayerPlacement) protected
References multiLayerGetViewLayerID(), viewID(), ModelPart::viewLayers(), and viewLayers().
getViewLayerPlacement()
ViewLayer::ViewLayerPlacement SketchWidget::getViewLayerPlacement (ModelPart * modelPart, QDomElement & instance, QDomElement & view, ViewGeometry & viewGeometry) protected virtual
Reimplemented in PCBSketchWidget, and SchematicSketchWidget.
References ViewLayer::Copper0, ViewLayer::Copper0Trace, ViewLayer::Copper1, ViewLayer::Copper1Trace, defaultViewLayerPlacement(), ViewGeometry::getAnyTrace(), ViewLayer::GroundPlane0, ViewLayer::GroundPlane1, ModuleIDNames::GroundPlaneModuleIDName, ModelPart::moduleID(), ViewLayer::NewBottom, ViewLayer::NewTop, and ViewLayer::viewLayerIDFromXmlString().
getWireViewLayerID()
ViewLayer::ViewLayerID SketchWidget::getWireViewLayerID (const ViewGeometry & viewGeometry, ViewLayer::ViewLayerPlacement) virtual
Reimplemented in PCBSketchWidget, and SchematicSketchWidget.
References ViewLayer::BreadboardRatsnest, ViewGeometry::getRatsnest(), and m_wireViewLayerID.
greaterThan()
bool SketchWidget::greaterThan (int a, int b) static protected
gridColor()
constexpr const QColor& SketchWidget::gridColor () const inline noexcept
References m_gridColor.
gridSizeInches()
double SketchWidget::gridSizeInches () protected
References m_gridSizeInches.
gridSizeText()
QString SketchWidget::gridSizeText ()
References m_gridSizeInches, and m_gridSizeText.
handleConnect()
void SketchWidget::handleConnect (QDomElement & connect, ModelPart * mp, const QString & fromConnectorID, ViewLayer::ViewLayerID fromViewLayerID, QStringList & alreadyConnected, QHash< long, ItemBase * > & newItems, QUndoCommand * parentCommand, bool seekOutsideConnections) protected
References NonConnectorItem::attachedToItemType(), ConnectorItem::connector(), Connector::connectTo(), ConnectorItem::connectTo(), ItemBase::findConnectorItemWithSharedID(), findItem(), ItemBase::getNextID(), ModelPart::indexMultiplier, ModelPart::modelIndex(), ratsnestConnect(), ConnectorItem::setHidden(), BaseCommand::SingleView, ViewLayer::specFromID(), ViewLayer::viewLayerIDFromXmlString(), and ModelPart::Wire.
hasAnyNets()
bool SketchWidget::hasAnyNets () virtual
Reimplemented in PCBSketchWidget.
hideConnectors()
void SketchWidget::hideConnectors (bool hide)
References ItemBase::cachedConnectorItems().
hidePartLabel()
void SketchWidget::hidePartLabel (ItemBase * item) virtual
Reimplemented from InfoGraphicsView.
References showPartLabelsAux().
hidePartLayer() [1/2]
void SketchWidget::hidePartLayer (long id, ViewLayer::ViewLayerID viewLayerID, bool hide)
References findItem().
hidePartLayer() [2/2]
void SketchWidget::hidePartLayer (ItemBase * itemBase, ViewLayer::ViewLayerID viewLayerID, bool hide)
References ItemBase::layerKin(), ItemBase::layerKinChief(), ItemBase::setLayerHidden(), and ItemBase::viewLayerID().
hoverEnterConnectorItem()
void SketchWidget::hoverEnterConnectorItem (QGraphicsSceneHoverEvent * event, ConnectorItem * item) virtual
Reimplemented from InfoGraphicsView.
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToItemType(), ConnectorItem::chained(), currentlyInfoviewed(), InfoGraphicsView::hoverEnterConnectorItem(), hoverEnterPartConnectorMessage(), hoverEnterWireConnectorMessage(), m_chainDrag, m_infoViewOnHover, m_lastHoverEnterConnectorItem, statusMessage(), and ModelPart::Wire.
hoverEnterItem()
void SketchWidget::hoverEnterItem (QGraphicsSceneHoverEvent * event, ItemBase * item) virtual
Reimplemented from InfoGraphicsView.
References canChainWire(), ConnectorItem::chained(), ConnectorItem::connectionsCount(), Wire::connector0(), Wire::connector1(), currentlyInfoviewed(), InfoGraphicsView::hoverEnterItem(), m_infoViewOnHover, m_lastHoverEnterItem, and statusMessage().
hoverEnterPartConnectorMessage()
const QString & SketchWidget::hoverEnterPartConnectorMessage (QGraphicsSceneHoverEvent * event, ConnectorItem * item) protected virtual
Reimplemented in PCBSketchWidget.
References ___emptyString___.
hoverEnterWireConnectorMessage()
const QString & SketchWidget::hoverEnterWireConnectorMessage (QGraphicsSceneHoverEvent * event, ConnectorItem * item) protected virtual
hoverLeaveConnectorItem()
void SketchWidget::hoverLeaveConnectorItem (QGraphicsSceneHoverEvent * event, ConnectorItem * item) virtual
Reimplemented from InfoGraphicsView.
References NonConnectorItem::attachedTo(), ConnectorItem::chained(), currentlyInfoviewed(), hoverEnterItem(), InfoGraphicsView::hoverLeaveConnectorItem(), ItemBase::hoverLeaveConnectorItem(), ItemBase::itemType(), m_chainDrag, m_infoViewOnHover, m_lastHoverEnterConnectorItem, statusMessage(), and ModelPart::Wire.
hoverLeaveItem()
void SketchWidget::hoverLeaveItem (QGraphicsSceneHoverEvent * event, ItemBase * item) virtual
Reimplemented from InfoGraphicsView.
References canChainWire(), InfoGraphicsView::hoverLeaveItem(), m_infoViewOnHover, m_lastHoverEnterItem, and statusMessage().
ignoreFemale()
bool SketchWidget::ignoreFemale () virtual
Reimplemented in BreadboardSketchWidget.
incInstanceTitle
void SketchWidget::incInstanceTitle (long id) slot
References ItemBase::ensureUniqueTitle(), findItem(), ItemBase::instanceTitle(), and updatePartLabelInstanceTitleSignal().
includeSymbols()
bool SketchWidget::includeSymbols () virtual
Reimplemented in SchematicSketchWidget.
initBackgroundColor()
void SketchWidget::initBackgroundColor () protected
References getShortName(), m_curvyWires, setBackground(), and standardBackground().
initGrid()
void SketchWidget::initGrid ()
References TextUtils::convertToInches(), defaultGridSizeInches(), m_alignToGrid, m_gridSizeInches, m_gridSizeText, m_showGrid, and viewName().
itemAddedSignal
void SketchWidget::itemAddedSignal (ModelPart * , ItemBase * , ViewLayer::ViewLayerPlacement , const ViewGeometry & , long id, SketchWidget * dropOrigin) signal
itemAddedSlot
void SketchWidget::itemAddedSlot (ModelPart * modelPart, ItemBase * , ViewLayer::ViewLayerPlacement viewLayerPlacement, const ViewGeometry & viewGeometry, long id, SketchWidget * dropOrigin) protected slot
References addItemAux(), m_viewID, and placePartDroppedInOtherView().
itemDeletedSignal
void SketchWidget::itemDeletedSignal (long id) signal
itemDeletedSlot
void SketchWidget::itemDeletedSlot (long id) protected slot
References deleteItem(), and findItem().
itemMovedSignal
void SketchWidget::itemMovedSignal (ItemBase *) signal
itemSelectedSignal
void SketchWidget::itemSelectedSignal (long id, bool state) signal
itemSelectedSlot
void SketchWidget::itemSelectedSlot (long id, bool state) protected slot
References findItem(), and setLastPaletteItemSelected().
keyPressEvent()
void SketchWidget::keyPressEvent (QKeyEvent * event) protected
References ConnectorItem::clearEqualPotentialDisplay(), DebugDialog::debug(), m_arrowTimer, m_inFocus, m_movingByMouse, and moveByArrow().
keyReleaseEvent()
void SketchWidget::keyReleaseEvent (QKeyEvent * event) protected
References m_arrowTimer, m_autoScrollTimer, and m_movingByArrow.
killDroppingItem()
void SketchWidget::killDroppingItem () protected
References m_alignmentItem, and m_droppingItem.
lastHoverEnterConnectorItem()
ConnectorItem * SketchWidget::lastHoverEnterConnectorItem ()
References m_lastHoverEnterConnectorItem.
lastHoverEnterItem()
ItemBase * SketchWidget::lastHoverEnterItem ()
References m_lastHoverEnterItem.
layerIsActive()
bool SketchWidget::layerIsActive (ViewLayer::ViewLayerID viewLayerID)
References ViewLayer::isActive(), and m_viewLayers.
layerIsVisible()
bool SketchWidget::layerIsVisible (ViewLayer::ViewLayerID viewLayerID)
References m_viewLayers, and ViewLayer::visible().
lessThan()
bool SketchWidget::lessThan (int a, int b) static protected
loadFromModelParts()
void SketchWidget::loadFromModelParts (QList< ModelPart * > & modelParts, BaseCommand::CrossViewType crossViewType, QUndoCommand * parentCommand, bool offsetPaste, const QRectF * boundingRect, bool seekOutsideConnections, QList< long > & newIDs) virtual
Reimplemented in PCBSketchWidget, and SchematicSketchWidget.
References addItemAux(), ItemBase::addSubpart(), addWireExtras(), changeLeg(), changeLegCurve(), cleanUpWires(), clearHoldingSelectItem(), DebugDialog::debug(), SelectItemCommand::DeselectAll, ItemBase::doneLoading(), ItemBase::findConnectorItemWithSharedID(), findItem(), Bezier::fromElement(), getLabelViewLayerID(), ItemBase::getNextID(), getTraceFlag(), getViewLayerPlacement(), ViewLayer::getZIncrement(), handleConnect(), ViewGeometry::hasFlag(), hidePartLayer(), ItemBase::id(), ModelPart::instanceDomElement(), ModelPart::instanceText(), ItemBase::isBaseSticky(), Board::isBoard(), Bezier::isEmpty(), ItemBase::isLocalSticky(), ModelPart::itemType(), ItemBase::itemType(), ModelPart::killViewItems(), ViewGeometry::line(), ViewGeometry::loc(), ModelPart::localProp(), ModelPart::Logo, m_pasteCount, m_pasteOffset, m_sketchModel, m_viewID, m_viewLayers, ModelPart::modelIndex(), ModelPart::moduleID(), newAddItemCommand(), ModelPart::Note, ViewGeometry::offset(), TextUtils::polygonFromElement(), CleanUpWiresCommand::RedoOnly, CheckStickyCommand::RemoveOnly, ViewLayer::resetNextZ(), ItemBase::restorePartLabel(), ModelPart::Ruler, BaseCommand::setCrossViewType(), Wire::setExtras(), ConnectorItem::setGroundFillSeed(), setIgnoreSelectionChangeEvents(), ViewGeometry::setLoc(), ModelPart::setLocalProp(), ItemBase::setLocalSticky(), ItemBase::setMoveLock(), BaseCommand::setRedoOnly(), SelectItemCommand::setSelectItemType(), ChangeLegCommand::setSimple(), Note::setText(), ItemBase::slamZ(), ViewLayer::specFromID(), stackSelectionState(), stickyScoop(), CleanUpWiresCommand::UndoOnly, viewGeometryConversionHack(), ViewLayer::viewIDXmlName(), ViewLayer::viewLayerIDFromXmlString(), viewName(), ModelPart::Wire, ModuleIDNames::WireModuleIDName, and ViewGeometry::z().
loadLogoImage() [1/3]
void SketchWidget::loadLogoImage (ItemBase * itemBase, const QString & oldSvg, const QSizeF oldAspectRatio, const QString & oldFilename, const QString & newFilename, bool addName) virtual
Reimplemented from InfoGraphicsView.
References ModuleIDNames::BoardLogoImageModuleIDName, ItemBase::id(), InfoGraphicsView::m_boardLayers, m_undoStack, ModuleIDNames::OneLayerBoardLogoImageModuleIDName, PropChangeDelay, swapBoardImageSignal(), and WaitPushUndoStack::waitPush().
loadLogoImage() [2/3]
void SketchWidget::loadLogoImage (long itemID, const QString & oldSvg, const QSizeF oldAspectRatio, const QString & oldFilename)
References findItem(), and LogoItem::reloadImage().
loadLogoImage() [3/3]
void SketchWidget::loadLogoImage (long itemID, const QString & newFilename, bool addName)
References findItem(), and LogoItem::loadImage().
makeDeleteItemCommand()
void SketchWidget::makeDeleteItemCommand (ItemBase * itemBase, BaseCommand::CrossViewType crossView, QUndoCommand * parentCommand)
References BaseCommand::CrossView, makeDeleteItemCommandFinalSignal(), makeDeleteItemCommandFinalSlot(), makeDeleteItemCommandPrepSignal(), and makeDeleteItemCommandPrepSlot().
makeDeleteItemCommandFinalSignal
void SketchWidget::makeDeleteItemCommandFinalSignal (ItemBase * itemBase, bool foreign, QUndoCommand * parentCommand) signal
makeDeleteItemCommandFinalSlot
void SketchWidget::makeDeleteItemCommandFinalSlot (ItemBase * itemBase, bool foreign, QUndoCommand * parentCommand) protected slot
References findItem(), ItemBase::getViewGeometry(), ItemBase::id(), ModelPart::modelIndex(), ItemBase::modelPart(), ModelPart::moduleID(), BaseCommand::SingleView, and ItemBase::viewLayerPlacement().
makeDeleteItemCommandPrepSignal
void SketchWidget::makeDeleteItemCommandPrepSignal (ItemBase * itemBase, bool foreign, QUndoCommand * parentCommand) signal
makeDeleteItemCommandPrepSlot
void SketchWidget::makeDeleteItemCommandPrepSlot (ItemBase * itemBase, bool foreign, QUndoCommand * parentCommand) protected slot
References ShowLabelCommand::add(), ConnectorItem::beziers(), ItemBase::cachedConnectorItems(), ConnectorItem::connectorSharedID(), Wire::curve(), findItem(), Wire::getAutoroutable(), ConnectorItem::hasRubberBandLeg(), ItemBase::hasRubberBandLeg(), ItemBase::id(), ItemBase::instanceTitle(), Bezier::isEmpty(), ItemBase::isPartLabelVisible(), ConnectorItem::leg(), prepDeleteProps(), rememberSticky(), BaseCommand::setSkipFirstRedo(), BaseCommand::setUndoOnly(), and Note::text().
makeMoveSVG()
QString SketchWidget::makeMoveSVG (double printerScale, double dpi, QPointF & offset) protected
References m_savedItems, TextUtils::makeRectSVG(), TextUtils::makeSVGHeader(), and makeWireSVG().
makeOneRatsnestWire()
VirtualWire * SketchWidget::makeOneRatsnestWire (ConnectorItem * source, ConnectorItem * dest, bool routed, QColor color, bool force) virtual
Reimplemented from InfoGraphicsView.
References addItem(), NonConnectorItem::attachedTo(), ConnectorItem::bus(), ItemBase::getNextID(), m_referenceModel, makeRatsnestViewGeometry(), ratsnestOpacity(), ratsnestWidth(), ViewGeometry::setRouted(), VirtualWire::ShapeWidthExtra, BaseCommand::SingleView, ConnectorItem::tempConnectTo(), ItemBase::viewLayerPlacement(), and ModuleIDNames::WireModuleIDName.
makeRatsnestViewGeometry()
void SketchWidget::makeRatsnestViewGeometry (ViewGeometry & viewGeometry, ConnectorItem * source, ConnectorItem * dest) protected
References ViewGeometry::RatsnestFlag, ConnectorItem::sceneAdjustedTerminalPoint(), ViewGeometry::setLine(), ViewGeometry::setLoc(), and ViewGeometry::setWireFlags().
makeSwapWire()
void SketchWidget::makeSwapWire (SketchWidget * bbView, ItemBase * itemBase, long newID, ConnectorItem * fromConnectorItem, ConnectorItem * toConnectorItem, Connector * newConnector, QUndoCommand * parentCommand) protected
References NonConnectorItem::attachedToID(), ConnectorItem::attachedToViewLayerID(), Connector::connectorSharedID(), ConnectorItem::connectorSharedID(), BaseCommand::CrossView, ItemBase::getNextID(), CheckStickyCommand::RemoveOnly, ViewLayer::specFromID(), ItemBase::viewLayerPlacement(), and ModuleIDNames::WireModuleIDName.
makeWiresChangeConnectionCommands()
void SketchWidget::makeWiresChangeConnectionCommands (const QList< Wire * > & wires, QUndoCommand * parentCommand)
References NonConnectorItem::attachedToID(), ConnectorItem::attachedToViewLayerID(), ConnectorItem::connectedToItems(), Wire::connector0(), Wire::connector1(), ConnectorItem::connectorSharedID(), BaseCommand::CrossView, extendChangeConnectionCommand(), and ViewLayer::specFromID().
makeWireSVG()
QString SketchWidget::makeWireSVG (Wire * wire, QPointF offset, double dpi, double printerscale, bool blackOnly) protected
References Wire::banded(), Wire::hasShadow(), Wire::hexString(), makeWireSVGAux(), Wire::shadowHexString(), Wire::shadowWidth(), and Wire::width().
makeWireSVGAux()
QString SketchWidget::makeWireSVGAux (Wire * wire, double width, const QString & color, QPointF offset, double dpi, double printerScale, bool blackOnly, bool dashed) protected
References Wire::getPaintLine(), Wire::isCurved(), TextUtils::makeCubicBezierSVG(), TextUtils::makeLineSVG(), Wire::sceneCurve(), and Wire::TheDash.
matchesLayer()
bool SketchWidget::matchesLayer (ModelPart * modelPart) protected
References m_viewID, m_viewLayers, ViewLayer::viewLayerID(), ModelPart::viewLayers(), and viewLayers().
mouseDoubleClickEvent()
void SketchWidget::mouseDoubleClickEvent (QMouseEvent * event) protected
References squashShapes(), and unsquashShapes().
mouseMoveEvent()
void SketchWidget::mouseMoveEvent (QMouseEvent * event) protected
References alignLoc(), checkAutoscroll(), cursorLocationSignal(), DebugDialog::debug(), draggingWireEnd(), m_alignmentStartPoint, m_alignToGrid, m_dragBendpointPos, m_dragBendpointWire, m_dragCurve, m_draggingBendpoint, m_globalPos, m_mousePressGlobalPos, m_mousePressScenePos, m_moveEventCount, m_movingByArrow, m_movingByMouse, m_movingSVGOffset, m_movingSVGRenderer, m_savedItems, m_spaceBarWasPressed, makeMoveSVG(), prepDragBendpoint(), squashShapes(), GraphicsUtils::StandardFritzingDPI, GraphicsUtils::SVGDPI, and unsquashShapes().
mousePressConnectorEvent()
void SketchWidget::mousePressConnectorEvent (ConnectorItem * connectorItem, QGraphicsSceneMouseEvent * event) virtual
Reimplemented from InfoGraphicsView.
References clearDragWireTempCommand(), clearHoldingSelectItem(), createTempWireForDragging(), getDragWireViewLayerID(), m_connectorDragConnector, m_connectorDragWire, m_holdingSelectItemCommand, m_lastColorSelected, m_referenceModel, m_tempDragWireCommand, m_viewLayers, setLayerVisible(), ViewGeometry::setLine(), ViewGeometry::setLoc(), setupAutoscroll(), ViewLayer::UnknownPlacement, unsquashShapes(), updateLayerMenuSignal(), ViewLayer::visible(), and ModuleIDNames::WireModuleIDName.
mousePressEvent()
void SketchWidget::mousePressEvent (QMouseEvent * event) protected virtual
Reimplemented in PartsEditorView.
References altOrMetaModifier(), canChainWire(), canDragWire(), Wire::canHaveCurve(), clearHoldingSelectItem(), clickBackground(), ConnectorItem::connectionsCount(), curvyWiresIndicated(), Wire::draggingEnd(), getClickedItem(), ItemBase::hasConnections(), ConnectorItem::isDraggingLeg(), m_alignmentStartPoint, m_alignToGrid, m_anyInRotation, m_connectorDragWire, m_dragBendpointPos, m_dragBendpointWire, m_dragCurve, m_draggingBendpoint, m_holdingSelectItemCommand, InfoGraphicsView::m_infoView, m_middleMouseIsPressed, m_mousePressGlobalPos, m_mousePressScenePos, m_moveEventCount, m_moveReferenceItem, m_movingByArrow, m_movingByMouse, m_originatingItem, m_savedItems, m_savedWires, m_spaceBarWasPressed, PartLabel::owner(), prepDragWire(), prepMove(), resizingBoardPress(), resizingJumperItemPress(), ConnectorItem::sceneAdjustedTerminalPoint(), setLastPaletteItemSelectedIf(), setupAutoscroll(), spaceBarIsPressed(), squashShapes(), stackSelectionState(), unsquashShapes(), HtmlInfoView::viewItemInfo(), and viewItemInfo().
mouseReleaseEvent()
void SketchWidget::mouseReleaseEvent (QMouseEvent * event) protected
References ConnectorItem::clearEqualPotentialDisplay(), clearHoldingSelectItem(), DebugDialog::debug(), ViewGeometry::line(), m_alignmentItem, m_bendpointVG, m_bendpointWire, m_connectorDragConnector, m_connectorDragWire, m_dragBendpointWire, m_draggingBendpoint, m_holdingSelectItemCommand, m_middleMouseIsPressed, m_moveEventCount, m_movingByArrow, m_movingByMouse, m_savedItems, m_savedWires, m_spaceBarWasPressed, m_undoStack, WaitPushUndoStack::push(), removeDragWire(), resizingBoardRelease(), resizingJumperItemRelease(), ConnectorItem::tempConnectTo(), ConnectorItem::tempRemove(), turnOffAutoscroll(), SelectItemCommand::updated(), and updateInfoView().
moveAutoScrollTimeout
void SketchWidget::moveAutoScrollTimeout () protected slot
References autoScrollTimeout(), m_globalPos, m_rubberBandLegWasEnabled, and moveItems().
moveByArrow()
bool SketchWidget::moveByArrow (double dx, double dy, QKeyEvent * event) protected
References altOrMetaModifier(), canChainWire(), canDragWire(), clearHoldingSelectItem(), DebugDialog::debug(), gridSizeInches(), ItemBase::hasConnections(), m_alignToGrid, m_arrowTotalX, m_arrowTotalY, m_dragBendpointWire, m_mousePressScenePos, m_moveEventCount, m_movingByArrow, m_savedItems, m_savedWires, moveItems(), prepDragWire(), prepMove(), and GraphicsUtils::SVGDPI.
moveItem() [1/3]
void SketchWidget::moveItem (long id, ViewGeometry & viewGeometry, bool updateRatsnest)
References findItem(), InfoGraphicsView::m_infoView, ItemBase::moveItem(), ratsnestConnect(), and HtmlInfoView::updateLocation().
moveItem() [2/3]
void SketchWidget::moveItem (long id, const QPointF & p, bool updateRatsnest)
References findItem(), itemMovedSignal(), InfoGraphicsView::m_infoView, ratsnestConnect(), and HtmlInfoView::updateLocation().
moveItem() [3/3]
void SketchWidget::moveItem (ItemBase * itemBase, double x, double y) virtual
Reimplemented from InfoGraphicsView.
References alignToGrid(), checkMoved(), m_alignToGrid, m_movingByArrow, m_savedItems, m_savedWires, and moveByArrow().
moveItems()
void SketchWidget::moveItems (QPoint globalPos, bool checkAutoScroll, bool rubberBandLegEnabled) protected
References alignLoc(), checkAutoscroll(), disconnectFromFemale(), findConnectorsUnder(), ItemBase::getViewGeometry(), ItemBase::itemType(), ItemBase::layerKinChief(), ViewGeometry::loc(), m_alignmentItem, m_alignmentStartPoint, m_alignToGrid, m_checkUnder, InfoGraphicsView::m_infoView, m_mousePressScenePos, m_moveDisconnectedFromFemale, m_moveEventCount, m_originatingItem, m_savedItems, m_savedWires, m_stretchingLegs, Wire::simpleConnectedMoved(), ConnectorItem::stretchBy(), HtmlInfoView::updateLocation(), and ModelPart::Wire.
moveLegBendpoint()
void SketchWidget::moveLegBendpoint (long id, const QString & connectorID, int index, QPointF p)
References findConnectorItem(), findItem(), ConnectorItem::moveLegBendpoint(), ViewLayer::specFromID(), and ItemBase::viewLayerID().
moveLegBendpoints()
void SketchWidget::moveLegBendpoints (bool undoOnly, QUndoCommand * parentCommand) protected
References m_stretchingLegs, and moveLegBendpointsAux().
moveLegBendpointsAux()
void SketchWidget::moveLegBendpointsAux (ConnectorItem * connectorItem, bool undoOnly, QUndoCommand * parentCommand) protected
References NonConnectorItem::attachedToID(), ConnectorItem::connectorSharedID(), ConnectorItem::moveDone(), BaseCommand::setRedoOnly(), and BaseCommand::setUndoOnly().
movePartLabel()
void SketchWidget::movePartLabel (long itemID, QPointF newPos, QPointF newOffset)
References findItem(), and ItemBase::movePartLabel().
movingSignal
void SketchWidget::movingSignal (SketchWidget * , QUndoCommand * parentCommand) signal
multiLayerGetViewLayerID()
ViewLayer::ViewLayerID SketchWidget::multiLayerGetViewLayerID (ModelPart * modelPart, ViewLayer::ViewID viewID, ViewLayer::ViewLayerPlacement viewLayerPlacement, LayerList & layerList) protected virtual
Reimplemented in PCBSketchWidget.
References ViewLayer::UnknownLayer, and viewID().
newAddItemCommand()
AddItemCommand * SketchWidget::newAddItemCommand (BaseCommand::CrossViewType crossViewType, ModelPart * newModelPart, QString moduleID, ViewLayer::ViewLayerPlacement viewLayerPlacement, ViewGeometry & viewGeometry, qint64 id, bool updateInfoView, long modelIndex, bool addSubparts, QUndoCommand * parent) protected
References ItemBase::getNextID(), ModelPart::hasSubparts(), ViewGeometry::loc(), m_referenceModel, ModelPart::modelPartShared(), ModelPartShared::moduleID(), ViewGeometry::setLoc(), ModelPartShared::subpartOffset(), ModelPartShared::subparts(), GraphicsUtils::SVGDPI, and updateInfoView().
noteChanged()
void SketchWidget::noteChanged (ItemBase * item, const QString & oldText, const QString & newtext, QSizeF oldSize, QSizeF newSize) virtual
Reimplemented from InfoGraphicsView.
References ItemBase::id(), m_undoStack, PropChangeDelay, BaseCommand::setSkipFirstRedo(), and WaitPushUndoStack::waitPush().
noteSizeChanged()
void SketchWidget::noteSizeChanged (ItemBase * itemBase, const QSizeF & oldSize, const QSizeF & newSize) virtual
Reimplemented from InfoGraphicsView.
References clearHoldingSelectItem(), ItemBase::id(), m_undoStack, and WaitPushUndoStack::push().
overSticky()
ItemBase * SketchWidget::overSticky (ItemBase * itemBase) protected
References ItemBase::isBaseSticky(), ItemBase::layerKinChief(), and ItemBase::stickyEnabled().
packItems
void SketchWidget::packItems (int columns, const QList< long > & ids, QUndoCommand * parent, bool doEmit) slot
References findItem(), ItemBase::getViewGeometry(), ItemBase::id(), packItemsSignal(), ItemBase::saveGeometry(), and ViewGeometry::setLoc().
packItemsSignal
void SketchWidget::packItemsSignal (int columns, const QList< long > & ids, QUndoCommand * parent, bool doEmit) signal
paintEvent()
void SketchWidget::paintEvent (QPaintEvent * event) protected
partLabelChanged()
void SketchWidget::partLabelChanged (ItemBase * pitem, const QString & oldText, const QString & newtext) virtual
Reimplemented from InfoGraphicsView.
References m_current, and partLabelChangedAux().
partLabelChangedAux()
void SketchWidget::partLabelChangedAux (ItemBase * pitem, const QString & oldText, const QString & newText) protected
References ItemBase::id(), m_undoStack, PropChangeDelay, ItemBase::title(), and WaitPushUndoStack::waitPush().
partLabelMoved()
void SketchWidget::partLabelMoved (ItemBase * itemBase, QPointF oldPos, QPointF oldOffset, QPointF newPos, QPointF newOffset) virtual
Reimplemented from InfoGraphicsView.
References ItemBase::id(), m_undoStack, WaitPushUndoStack::push(), and ItemBase::title().
partLabelsVisible()
bool SketchWidget::partLabelsVisible ()
References ItemBase::isPartLabelVisible().
pasteHeart()
void SketchWidget::pasteHeart (QByteArray & itemData, bool seekOutsideConnections)
References loadFromModelParts(), m_referenceModel, m_sketchModel, BaseCommand::SingleView, and viewName().
placePartDroppedInOtherView()
ItemBase * SketchWidget::placePartDroppedInOtherView (ModelPart * modelPart, ViewLayer::ViewLayerPlacement viewLayerPlacement, const ViewGeometry & viewGeometry, long id, SketchWidget * dropOrigin) protected virtual
Reimplemented in PCBSketchWidget.
References addItemAux(), alignOneToGrid(), ViewGeometry::loc(), m_alignToGrid, m_viewID, and ViewGeometry::setLoc().
prepDeleteOtherProps()
void SketchWidget::prepDeleteOtherProps (ItemBase * itemBase, long id, const QString & newModuleID, QMap< QString, QString > & propsMap, QUndoCommand * parentCommand) protected
References Capacitor::getProperties(), ModelPart::localProp(), m_referenceModel, ItemBase::modelPart(), ItemBase::moduleID(), ModelPartShared::PartNumberPropertyName, ItemBase::prop(), ModelPart::properties(), ModuleIDNames::Stripboard2ModuleIDName, and ModuleIDNames::StripboardModuleIDName.
prepDeleteProps()
void SketchWidget::prepDeleteProps (ItemBase * itemBase, long id, const QString & newModuleID, QMap< QString, QString > & propsMap, QUndoCommand * parentCommand) protected
References ModelPart::Board, MysteryPart::chipLabel(), Wire::colorString(), ModelPart::CopperFill, SymbolPaletteItem::getLabel(), LogoItem::getNewLayerFileName(), JumperItem::getParams(), ResizableBoard::getParams(), Hole::holeSize(), ModelPart::itemType(), ModelPart::Jumper, ModelPart::localProp(), ModelPart::Logo, InfoGraphicsView::m_boardLayers, ItemBase::modelPart(), Wire::opacity(), Resistor::pinSpacing(), prepDeleteOtherProps(), ItemBase::prop(), referenceModel(), Resistor::resistance(), ModelPart::ResizableBoard, ReferenceModel::retrieveModelPart(), JumperItem::saveParams(), ResizableBoard::saveParams(), BaseCommand::setUndoOnly(), GroundPlane::svg(), ModelPart::Symbol, Wire::width(), and ModelPart::Wire.
prepDragBendpoint()
void SketchWidget::prepDragBendpoint (Wire * wire, QPoint eventPos, bool dragCurve) protected
References Wire::changeCurve(), ConnectorItem::connectedToItems(), Wire::connector1(), createTempWireForDragging(), ItemBase::getViewGeometry(), Wire::initDragCurve(), Wire::initNewBendpoint(), Wire::line(), m_bendpointVG, m_bendpointWire, m_connectorDragConnector, m_connectorDragWire, ItemBase::modelPart(), Wire::saveGeometry(), ViewGeometry::setLine(), Wire::setLine(), ViewGeometry::setLoc(), setupAutoscroll(), ConnectorItem::tempConnectTo(), ConnectorItem::tempRemove(), Bezier::translateToZero(), unsquashShapes(), and ItemBase::viewLayerPlacement().
prepDragWire()
void SketchWidget::prepDragWire (Wire * wire) protected
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToItemType(), ConnectorItem::connectedToItems(), Wire::connector0(), Wire::connector1(), ItemBase::id(), m_savedItems, m_savedWires, Wire::saveGeometry(), setupAutoscroll(), and ModelPart::Wire.
prepLegBendpointChange()
void SketchWidget::prepLegBendpointChange (ConnectorItem * from, int oldCount, int newCount, int index, QPointF pos, const class Bezier * bezier0, const class Bezier * bezier1, const class Bezier * bezier2, bool triggerFirstTime) virtual
Reimplemented from InfoGraphicsView.
References NonConnectorItem::attachedToID(), NonConnectorItem::attachedToInstanceTitle(), clearHoldingSelectItem(), ConnectorItem::connectorSharedID(), SelectItemCommand::copyRedo(), SelectItemCommand::copyUndo(), m_holdingSelectItemCommand, m_moveEventCount, m_undoStack, SelectItemCommand::NormalSelect, WaitPushUndoStack::push(), and BaseCommand::setSkipFirstRedo().
prepLegBendpointMove()
void SketchWidget::prepLegBendpointMove (ConnectorItem * from, int index, QPointF oldPos, QPointF newPos, ConnectorItem * to, bool changeConnections) virtual
Reimplemented from InfoGraphicsView.
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToID(), NonConnectorItem::attachedToInstanceTitle(), ConnectorItem::attachedToViewLayerID(), clearHoldingSelectItem(), ConnectorItem::collectEqualPotential(), ConnectorItem::connectedToItems(), ConnectorItem::connectorSharedID(), ConnectorItem::connectorSharedName(), SelectItemCommand::copyRedo(), SelectItemCommand::copyUndo(), BaseCommand::CrossView, extendChangeConnectionCommand(), ItemBase::instanceTitle(), m_holdingSelectItemCommand, m_moveEventCount, m_undoStack, SelectItemCommand::NormalSelect, ViewGeometry::PCBTraceFlag, WaitPushUndoStack::push(), ViewGeometry::RatsnestFlag, CleanUpWiresCommand::RedoOnly, ViewGeometry::SchematicTraceFlag, BaseCommand::setRedoOnly(), BaseCommand::setUndoOnly(), ChangeConnectionCommand::setUpdateConnections(), ViewLayer::specFromID(), ConnectorItem::tempRemove(), and CleanUpWiresCommand::UndoOnly.
prepLegCurveChange()
void SketchWidget::prepLegCurveChange (ConnectorItem * from, int index, const class Bezier * oldB, const class Bezier * newB, bool triggerFirstTime) virtual
Reimplemented from InfoGraphicsView.
References NonConnectorItem::attachedToID(), NonConnectorItem::attachedToInstanceTitle(), clearHoldingSelectItem(), ConnectorItem::connectorSharedID(), SelectItemCommand::copyRedo(), SelectItemCommand::copyUndo(), m_holdingSelectItemCommand, m_moveEventCount, m_undoStack, SelectItemCommand::NormalSelect, WaitPushUndoStack::push(), and BaseCommand::setSkipFirstRedo().
prepLegSelection()
void SketchWidget::prepLegSelection (ItemBase * itemBase) virtual
Reimplemented from InfoGraphicsView.
References clearHoldingSelectItem(), m_holdingSelectItemCommand, m_moveEventCount, and stackSelectionState().
prepMove()
void SketchWidget::prepMove (ItemBase * originatingItem, bool rubberBandLegEnabled, bool includeRatsnest) protected
References NonConnectorItem::attachedToID(), ItemBase::cachedConnectorItems(), categorizeDragLegs(), categorizeDragWires(), collectFemaleConnectees(), ItemBase::collectWireConnectees(), ConnectorItem::connectedToItems(), findAlignmentAnchor(), ItemBase::getRatsnest(), getTraceFlag(), ItemBase::id(), ItemBase::isSticky(), Wire::isTraceType(), ItemBase::itemType(), ItemBase::layerKinChief(), m_checkUnder, m_originatingItem, m_rubberBandLegWasEnabled, m_savedItems, m_savedWires, ItemBase::moveLock(), Wire::saveGeometry(), ItemBase::saveGeometry(), ItemBase::stickyList(), and ModelPart::Wire.
prereleaseTempWireForDragging()
void SketchWidget::prereleaseTempWireForDragging (Wire *) protected virtual
Reimplemented in PCBSketchWidget.
pushCommand()
void SketchWidget::pushCommand (QUndoCommand * command, QObject * signalTarget)
References BaseCommand::clearProgress(), BaseCommand::initProgress(), m_undoStack, and WaitPushUndoStack::push().
ratsnestConnect() [1/4]
void SketchWidget::ratsnestConnect (ConnectorItem * connectorItem, bool connect)
References m_ratsnestUpdateConnect, and m_ratsnestUpdateDisconnect.
ratsnestConnect() [2/4]
void SketchWidget::ratsnestConnect (ItemBase * itemBase, bool connect)
References ItemBase::cachedConnectorItems(), and ratsnestConnect().
ratsnestConnect() [3/4]
void SketchWidget::ratsnestConnect (ConnectorItem * c1, ConnectorItem * c2, bool connect, bool wait)
References ConnectorItem::collectEqualPotential(), m_ratsnestCacheConnect, m_ratsnestCacheDisconnect, ratsnestConnect(), and ViewGeometry::RatsnestFlag.
ratsnestConnect [4/4]
void SketchWidget::ratsnestConnect (long id, const QString & connectorID, bool connect, bool doEmit) slot
References findConnectorItem(), findItem(), ratsnestConnect(), ratsnestConnectSignal(), and ItemBase::viewLayerPlacement().
ratsnestConnectSignal
void SketchWidget::ratsnestConnectSignal (long id, const QString & connectorID, bool connect, bool doEmit) signal
ratsnestOpacity()
double SketchWidget::ratsnestOpacity ()
ratsnestWidth()
double SketchWidget::ratsnestWidth ()
recalcLeg()
void SketchWidget::recalcLeg (long fromID, const QString & connectorID, const QPolygonF & leg, bool relative, bool active, const QString & why)
References changeLegAux().
referenceModel()
ReferenceModel * SketchWidget::referenceModel ()
References m_referenceModel.
rememberSticky [1/2]
void SketchWidget::rememberSticky (long id, QUndoCommand * parentCommand) protected slot
References findItem().
rememberSticky [2/2]
void SketchWidget::rememberSticky (ItemBase * itemBase, QUndoCommand * parentCommand) protected slot
References ItemBase::id(), ItemBase::isBaseSticky(), BaseCommand::SingleView, CheckStickyCommand::stick(), ItemBase::stickingTo(), ItemBase::stickyList(), and CheckStickyCommand::UndoOnly.
removeDragWire()
void SketchWidget::removeDragWire () protected
References m_connectorDragWire.
removeLegBendpoint()
void SketchWidget::removeLegBendpoint (long id, const QString & connectorID, int index, const class Bezier * bezierCombined)
References findConnectorItem(), findItem(), ConnectorItem::removeLegBendpoint(), ViewLayer::specFromID(), and ItemBase::viewLayerID().
removeOutsideConnections()
QByteArray SketchWidget::removeOutsideConnections (const QByteArray & itemData, QList< long > & modelIndexes) protected
References ___emptyByteArray___, and DebugDialog::debug().
removeRatsnestSignal
void SketchWidget::removeRatsnestSignal (QList< struct ConnectorEdge * > & cutSet, QUndoCommand * parentCommand) signal
removeRatsnestSlot
void SketchWidget::removeRatsnestSlot (QList< struct ConnectorEdge * > & cutSet, QUndoCommand * parentCommand) protected slot
References NonConnectorItem::attachedTo(), ConnectorItem::attachedToViewID(), ConnectorEdge::c0, ConnectorEdge::c1, calcNewLoc(), Wire::collectChained(), ConnectorItem::connectorType(), createWire(), BaseCommand::CrossView, deleteAux(), disconnectFromFemale(), Connector::Female, ItemBase::getViewGeometry(), ItemBase::id(), ViewGeometry::NoFlag, ItemBase::saveGeometry(), ViewGeometry::setLoc(), viewID(), and ConnectorEdge::wire.
removeWire()
void SketchWidget::removeWire (Wire * w, QList< ConnectorItem * > & ends, QList< Wire * > & done, QUndoCommand * parentCommand) protected
References Wire::collectChained(), BaseCommand::CrossView, makeDeleteItemCommand(), and makeWiresChangeConnectionCommands().
renamePins() [1/2]
void SketchWidget::renamePins (ItemBase * itemBase, const QStringList & oldLabels, const QStringList & newLabels, bool singleRow) virtual
Reimplemented from InfoGraphicsView.
References ItemBase::id(), m_undoStack, and WaitPushUndoStack::waitPush().
renamePins() [2/2]
void SketchWidget::renamePins (long itemID, const QStringList & labels, bool singleRow)
References findItem(), ItemBase::layerKinChief(), and PaletteItem::renamePins().
renderToSVG() [1/3]
QString SketchWidget::renderToSVG (RenderThing & renderThing, QGraphicsItem * board, const LayerList & layers)
References RenderThing::board, layers(), and RenderThing::offsetRect.
renderToSVG() [2/3]
QString SketchWidget::renderToSVG (RenderThing & renderThing, const LayerList & layers) protected
References RenderThing::board, Pad::copperBlocker(), ItemBase::hidden(), ItemBase::isPartLabelVisible(), RenderThing::itemsBoundingRect, ItemBase::layerHidden(), ItemBase::layerKinChief(), layers(), ItemBase::partLabel(), ItemBase::partLabelSceneBoundingRect(), ItemBase::partLabelViewLayerID(), RenderThing::renderBlocker, renderToSVG(), RenderThing::selectedItems, and ItemBase::viewLayerID().
renderToSVG() [3/3]
QString SketchWidget::renderToSVG (RenderThing & renderThing, QList< QGraphicsItem * > & itemsAndLabels) protected
References RenderThing::blackOnly, ItemBase::cachedConnectorItems(), ConnectorItem::connector(), Pad::copperBlocker(), RenderThing::dpi, RenderThing::empty, ensureStrokeWidth(), extraRenderSvgStep(), TextUtils::fixMuch(), Connector::fullPinInfo(), ConnectorItem::hasRubberBandLeg(), hideTerminalID(), RenderThing::hideTerminalPoints, ItemBase::id(), RenderThing::imageRect, RenderThing::itemsBoundingRect, ItemBase::itemType(), SvgIdLayer::m_svgId, SvgIdLayer::m_terminalId, ConnectorItem::makeLegSvg(), ItemBase::makePartLabelSvg(), TextUtils::makeSVGHeader(), makeWireSVG(), RenderThing::offsetRect, PartLabel::owner(), ItemBase::partLabelScenePos(), RenderThing::printerScale, RenderThing::renderBlocker, ItemBase::retrieveSvg(), TextUtils::svgTransform(), translateSVG(), ItemBase::viewID(), ItemBase::viewLayerID(), ModelPart::Wire, and zLessThan().
resizeBoard() [1/3]
void SketchWidget::resizeBoard () protected
References m_resizingBoard, m_undoStack, CheckStickyCommand::RedoOnly, rememberSticky(), ViewGeometry::setLoc(), BaseCommand::SingleView, and WaitPushUndoStack::waitPush().
resizeBoard [2/3]
ItemBase * SketchWidget::resizeBoard (long id, double w, double h) virtual slot
References findItem(), ItemBase::itemType(), ModelPart::Logo, m_viewLayers, ModelPart::ResizableBoard, resizedSignal(), ResizableBoard::resizeMM(), and ModelPart::Ruler.
resizeBoard [3/3]
void SketchWidget::resizeBoard (double w, double h, bool doEmit) slot
References getSelectedPart(), ItemBase::id(), ItemBase::itemType(), ModelPart::Logo, m_undoStack, ItemBase::prop(), PropChangeDelay, InfoGraphicsView::resizeBoard(), resizeWithHandle(), ModelPart::Ruler, and WaitPushUndoStack::waitPush().
resizedSignal
void SketchWidget::resizedSignal (ItemBase *) signal
resizeEvent()
void SketchWidget::resizeEvent (QResizeEvent * event) protected
References m_sizeItem, and resizeSignal().
resizeJumperItem
void SketchWidget::resizeJumperItem (long id, QPointF pos, QPointF c0, QPointF c1) slot
References findItem(), ItemBase::itemType(), and ModelPart::Jumper.
resizeNote()
void SketchWidget::resizeNote (long itemID, const QSizeF & size)
References findItem(), and Note::setSize().
resizeSignal
void SketchWidget::resizeSignal () signal
resizeWithHandle()
void SketchWidget::resizeWithHandle (ItemBase * itemBase, double mmW, double mmH) protected
References ItemBase::id(), ModelPart::localProp(), m_undoStack, ItemBase::modelPart(), PropChangeDelay, CheckStickyCommand::RedoOnly, rememberSticky(), BaseCommand::SingleView, viewItemInfo(), and WaitPushUndoStack::waitPush().
resizingBoardPress()
bool SketchWidget::resizingBoardPress (ItemBase * itemBase) protected
References ResizableBoard::inResize(), ItemBase::layerKinChief(), and m_resizingBoard.
resizingBoardRelease()
bool SketchWidget::resizingBoardRelease () protected
References m_resizingBoard, and resizeBoard().
resizingJumperItemPress()
bool SketchWidget::resizingJumperItemPress (ItemBase *) protected virtual
Reimplemented in PCBSketchWidget.
resizingJumperItemRelease()
bool SketchWidget::resizingJumperItemRelease () protected virtual
Reimplemented in PCBSketchWidget.
resolveTemporary()
void SketchWidget::resolveTemporary (bool resolve, ItemBase * itemBase) virtual
Reimplemented from InfoGraphicsView.
References deleteTemporary(), m_undoStack, and WaitPushUndoStack::resolveTemporary().
restartPasteCount
void SketchWidget::restartPasteCount () protected slot
References m_pasteCount.
restoreLayerVisibility()
void SketchWidget::restoreLayerVisibility ()
References m_viewLayers, m_viewLayerVisibility, and setLayerVisible().
restorePartLabel()
void SketchWidget::restorePartLabel (long itemID, QDomElement & element)
References findItem(), getLabelViewLayerID(), and ItemBase::restorePartLabel().
retrieveZoom()
double SketchWidget::retrieveZoom ()
References m_zoom.
rotateFlipPartLabel() [1/2]
void SketchWidget::rotateFlipPartLabel (ItemBase * itemBase, double degrees, Qt::Orientations flipDirection) virtual
Reimplemented from InfoGraphicsView.
References ItemBase::id(), m_undoStack, WaitPushUndoStack::push(), and ItemBase::title().
rotateFlipPartLabel() [2/2]
void SketchWidget::rotateFlipPartLabel (long itemID, double degrees, Qt::Orientations flipDirection)
References ItemBase::doRotateFlipPartLabel(), and findItem().
rotateItem()
void SketchWidget::rotateItem (long id, double degrees)
References findItem(), InfoGraphicsView::m_infoView, ItemBase::rotateItem(), and HtmlInfoView::updateRotation().
rotateLeg()
void SketchWidget::rotateLeg (long fromID, const QString & connectorID, const QPolygonF & leg, bool active)
References DebugDialog::debug(), findConnectorItem(), findItem(), ConnectorItem::rotateLeg(), ViewLayer::specFromID(), and ItemBase::viewLayerID().
rotatePartLabels()
void SketchWidget::rotatePartLabels (double degrees, QTransform & , QPointF center, QUndoCommand * parentCommand) protected virtual
Reimplemented in PCBSketchWidget, and SchematicSketchWidget.
rotateWire()
void SketchWidget::rotateWire (Wire * wire, QTransform & rotation, QPointF center, bool undoOnly, QUndoCommand * parentCommand) protected
References Wire::connector0(), Wire::connector1(), Bezier::cp0(), Bezier::cp1(), Wire::curve(), Wire::getAutoroutable(), ItemBase::getViewGeometry(), ItemBase::id(), ViewGeometry::line(), ViewGeometry::loc(), ConnectorItem::sceneAdjustedTerminalPoint(), Bezier::set_cp0(), Bezier::set_cp1(), Bezier::set_endpoints(), BaseCommand::setRedoOnly(), and BaseCommand::setUndoOnly().
rotateX()
void SketchWidget::rotateX (double degrees, bool rubberBandLegEnabled, ItemBase * originatingItem) virtual
Reimplemented from InfoGraphicsView.
References NonConnectorItem::attachedToID(), ItemBase::boundingRectWithoutLegs(), ItemBase::calcRotation(), clearHoldingSelectItem(), Wire::connector0(), ConnectorItem::connectorSharedID(), disconnectFromFemale(), ItemBase::getViewGeometry(), ModelPart::Hole, ItemBase::id(), ItemBase::itemType(), ViewGeometry::line(), ViewGeometry::loc(), m_savedItems, m_savedWires, m_stretchingLegs, m_undoStack, m_viewID, moveLegBendpoints(), Wire::otherConnector(), prepMove(), WaitPushUndoStack::push(), CleanUpWiresCommand::RedoOnly, rotatePartLabels(), rotateWire(), ConnectorItem::sceneAdjustedTerminalPoint(), ViewGeometry::setLoc(), ConnectorItem::stretchDone(), CleanUpWiresCommand::UndoOnly, ModelPart::Via, ViewLayer::viewIDName(), and ModelPart::Wire.
routeBothSides()
bool SketchWidget::routeBothSides () virtual
Reimplemented in PCBSketchWidget, and SchematicSketchWidget.
routingStatusSignal
void SketchWidget::routingStatusSignal (SketchWidget * , const RoutingStatus &) signal
sameElectricalLayer2()
bool SketchWidget::sameElectricalLayer2 (ViewLayer::ViewLayerID , ViewLayer::ViewLayerID) virtual
Reimplemented in PCBSketchWidget, and SchematicSketchWidget.
saveLayerVisibility()
void SketchWidget::saveLayerVisibility ()
References m_viewLayers, m_viewLayerVisibility, and ViewLayer::visible().
saveZoom()
void SketchWidget::saveZoom (double zoom)
References m_zoom.
selectAllItems() [1/2]
int SketchWidget::selectAllItems (QSet< ItemBase * > & itemBases, const QString & msg) protected
References SelectItemCommand::addRedo(), ItemBase::id(), m_undoStack, SelectItemCommand::NormalSelect, WaitPushUndoStack::push(), and stackSelectionState().
selectAllItems [2/2]
void SketchWidget::selectAllItems (bool state, bool doEmit) slot
References selectAllItemsSignal().
selectAllItemsSignal
void SketchWidget::selectAllItemsSignal (bool state, bool doEmit) signal
selectAllMoveLock()
int SketchWidget::selectAllMoveLock ()
References ItemBase::layerKinChief(), ItemBase::moveLock(), and selectAllItems().
selectAllObsolete()
QList< ItemBase * > SketchWidget::selectAllObsolete ()
References ItemBase::isObsolete(), ItemBase::layerKinChief(), and selectAllItems().
selectAllWires()
void SketchWidget::selectAllWires (ViewGeometry::WireFlag flag) virtual
Reimplemented in PCBSketchWidget, and SchematicSketchWidget.
References selectAllWiresFrom().
selectAllWiresFrom()
void SketchWidget::selectAllWiresFrom (ViewGeometry::WireFlag flag, QList< QGraphicsItem * > & items) protected
References SelectItemCommand::addRedo(), getTraceFlag(), Wire::hasFlag(), ItemBase::id(), m_undoStack, SelectItemCommand::NormalSelect, WaitPushUndoStack::push(), ViewGeometry::RatsnestFlag, and stackSelectionState().
selectDeselectAllCommand()
void SketchWidget::selectDeselectAllCommand (bool state)
References clearHoldingSelectItem(), SelectItemCommand::DeselectAll, m_undoStack, WaitPushUndoStack::push(), SelectItemCommand::SelectAll, SelectItemCommand::setSelectItemType(), and stackSelectionState().
selectedModuleID()
const QString & SketchWidget::selectedModuleID ()
References ___emptyString___, m_lastPaletteItemSelected, and ItemBase::moduleID().
selectionChangedSignal
void SketchWidget::selectionChangedSignal () signal
selectionChangedSlot
void SketchWidget::selectionChangedSlot () protected slot
References SelectItemCommand::addRedo(), SelectItemCommand::clearRedo(), ItemBase::id(), ItemBase::layerKinChief(), m_holdingSelectItemCommand, m_ignoreSelectionChangeEvents, selectionChangedSignal(), SelectItemCommand::setUpdated(), and ItemBase::title().
selectItem() [1/2]
void SketchWidget::selectItem (long id, bool state, bool updateInfoView, bool doEmit)
References clearHoldingSelectItem(), findItem(), itemSelectedSignal(), setLastPaletteItemSelected(), updateInfoView(), and viewItemInfo().
selectItem() [2/2]
void SketchWidget::selectItem (ItemBase * itemBase)
References selectItems().
selectItems()
void SketchWidget::selectItems (QList< ItemBase * > startingItemBases)
References SelectItemCommand::addRedo(), ItemBase::id(), ItemBase::instanceTitle(), ItemBase::layerKinChief(), m_undoStack, SelectItemCommand::NormalSelect, WaitPushUndoStack::push(), and stackSelectionState().
selectItemsWithModuleID()
void SketchWidget::selectItemsWithModuleID (ModelPart * modelPart)
References ItemBase::layerKinChief(), ModelPart::moduleID(), ItemBase::moduleID(), selectItems(), and ModelPart::title().
sendBackward()
void SketchWidget::sendBackward ()
References continueZChange(), lessThan(), and startZChange().
sendToBack()
void SketchWidget::sendToBack ()
References continueZChangeMax(), greaterThan(), and startZChange().
setAllLayersVisible()
void SketchWidget::setAllLayersVisible (bool visible)
References ViewLayer::action(), m_viewLayers, and setLayerVisible().
setAnyInRotation()
void SketchWidget::setAnyInRotation () virtual
Reimplemented from InfoGraphicsView.
References m_anyInRotation.
setAutorouterSettings()
void SketchWidget::setAutorouterSettings (QHash< QString, QString > &) virtual
Reimplemented in PCBSketchWidget, and SchematicSketchWidget.
setBackground()
void SketchWidget::setBackground (QColor color)
setBackgroundColor()
void SketchWidget::setBackgroundColor (QColor color, bool setPref)
References getShortName(), and setBackground().
setChainDrag()
void SketchWidget::setChainDrag (bool chainDrag)
References m_chainDrag.
setClipEnds()
void SketchWidget::setClipEnds (class ClipableWire * vw, bool) virtual
Reimplemented in PCBSketchWidget, and SchematicSketchWidget.
References ClipableWire::setClipEnds().
setCurrent()
void SketchWidget::setCurrent (bool current) virtual
References m_current.
setCurvyWires()
void SketchWidget::setCurvyWires (bool curvyWires)
References curvyWires(), and m_curvyWires.
setEverZoomed()
void SketchWidget::setEverZoomed (bool everZoomed)
References everZoomed(), and m_everZoomed.
setGridColor()
void SketchWidget::setGridColor (QColor color)
References m_gridColor.
setGridSize()
void SketchWidget::setGridSize (const QString & newSize)
References TextUtils::convertToInches(), m_gridSizeInches, m_gridSizeText, m_showGrid, and viewName().
setGroundFillSeed()
void SketchWidget::setGroundFillSeed (long id, const QString & connectorID, bool seed)
References findConnectorItem(), findItem(), ConnectorItem::setGroundFillSeed(), ViewLayer::specFromID(), and ItemBase::viewLayerID().
setHoleSize
void SketchWidget::setHoleSize (ItemBase * item, const QString & propName, const QString & translatedPropName, const QString & oldValue, const QString & newValue, QRectF & oldRect, QRectF & newRect, bool redraw) slot
References ItemBase::getViewGeometry(), ItemBase::id(), m_undoStack, PropChangeDelay, ItemBase::saveGeometry(), and WaitPushUndoStack::waitPush().
setIgnoreSelectionChangeEvents()
void SketchWidget::setIgnoreSelectionChangeEvents (bool ignore) virtual
Reimplemented from InfoGraphicsView.
References m_ignoreSelectionChangeEvents.
setInfoViewOnHover()
void SketchWidget::setInfoViewOnHover (bool infoViewOnHover)
References m_infoViewOnHover.
setInstanceTitle
void SketchWidget::setInstanceTitle (long id, const QString & oldTitle, const QString & newTitle, bool isUndoable, bool doEmit) slot
References currentlyInfoviewed(), findItem(), partLabelChangedAux(), ItemBase::setInstanceTitle(), setInstanceTitleSignal(), and viewItemInfo().
setInstanceTitleSignal
void SketchWidget::setInstanceTitleSignal (long id, const QString & oldTitle, const QString & newTitle, bool isUndoable, bool doEmit) signal
setItemDropOffset()
void SketchWidget::setItemDropOffset (long id, QPointF offset)
References findItem(), and ItemBase::setDropOffset().
setItemMenu()
void SketchWidget::setItemMenu (QMenu * itemMenu)
References m_itemMenu.
setLastPaletteItemSelected()
void SketchWidget::setLastPaletteItemSelected (PaletteItem * paletteItem) protected
References m_lastPaletteItemSelected.
setLastPaletteItemSelectedIf()
void SketchWidget::setLastPaletteItemSelectedIf (ItemBase * itemBase) protected
References setLastPaletteItemSelected().
setLayerActive() [1/2]
void SketchWidget::setLayerActive (ViewLayer * viewLayer, bool active)
References ViewLayer::childLayers(), ViewLayer::setActive(), PartLabel::setInactive(), ItemBase::setInactive(), PartLabel::viewLayerID(), ItemBase::viewLayerID(), and ViewLayer::viewLayerID().
setLayerActive() [2/2]
void SketchWidget::setLayerActive (ViewLayer::ViewLayerID viewLayerID, bool active)
References m_viewLayers, and setLayerActive().
setLayerVisible() [1/2]
void SketchWidget::setLayerVisible (ViewLayer * viewLayer, bool visible, bool doChildLayers)
References ViewLayer::childLayers(), PartLabel::setHidden(), ItemBase::setHidden(), ViewLayer::setVisible(), PartLabel::viewLayerID(), ItemBase::viewLayerID(), and ViewLayer::viewLayerID().
setLayerVisible() [2/2]
void SketchWidget::setLayerVisible (ViewLayer::ViewLayerID viewLayerID, bool visible, bool doChildLayers)
References m_viewLayers, and setLayerVisible().
setMoveLock()
void SketchWidget::setMoveLock (long id, bool lock)
References findItem(), and ItemBase::setMoveLock().
setNewPartVisible()
void SketchWidget::setNewPartVisible (ItemBase * itemBase) protected virtual
Reimplemented in PCBSketchWidget, BreadboardSketchWidget, and SchematicSketchWidget.
setNoteFocus()
void SketchWidget::setNoteFocus (QGraphicsItem * item, bool inFocus) virtual
Reimplemented from InfoGraphicsView.
References m_inFocus.
setNoteText
void SketchWidget::setNoteText (long itemID, const QString & newText) slot
References findItem(), and Note::setText().
setPasting()
void SketchWidget::setPasting (bool pasting)
References m_pasting.
setProp [1/2]
void SketchWidget::setProp (long itemID, const QString & prop, const QString & value, bool redraw, bool doEmit) slot
References findItem(), ItemBase::setProp(), setPropSignal(), and viewItemInfo().
setProp [2/2]
void SketchWidget::setProp (ItemBase * item, const QString & propName, const QString & translatedPropName, const QString & oldValue, const QString & newValue, bool redraw) virtual slot
References ItemBase::id(), m_undoStack, PropChangeDelay, and WaitPushUndoStack::waitPush().
setPropSignal
void SketchWidget::setPropSignal (long itemID, const QString & prop, const QString & value, bool doRedraw, bool doEmit) signal
setRatsnestOpacity()
void SketchWidget::setRatsnestOpacity (double opacity)
References m_ratsnestOpacity.
setRatsnestWidth()
void SketchWidget::setRatsnestWidth (double width)
References m_ratsnestWidth.
setReferenceModel()
void SketchWidget::setReferenceModel (class ReferenceModel * referenceModel)
References m_referenceModel, and referenceModel().
setResistance [1/2]
void SketchWidget::setResistance (long itemID, QString resistance, QString pinSpacing, bool doEmit) slot
References findItem(), Resistor::setResistance(), setResistanceSignal(), and viewItemInfo().
setResistance [2/2]
void SketchWidget::setResistance (QString resistance, QString pinSpacing) slot
References getSelectedPart(), ItemBase::id(), m_undoStack, ItemBase::modelPart(), ModelPart::moduleID(), Resistor::pinSpacing(), PropChangeDelay, Resistor::resistance(), ModuleIDNames::ResistorModuleIDName, and WaitPushUndoStack::waitPush().
setResistanceSignal
void SketchWidget::setResistanceSignal (long itemID, QString resistance, QString pinSpacing, bool doEmit) signal
setSketchModel()
void SketchWidget::setSketchModel (SketchModel * sketchModel)
References m_sketchModel.
setUndoStack()
void SketchWidget::setUndoStack (class WaitPushUndoStack * undoStack)
References m_undoStack, and undoStack().
setupAutoscroll()
void SketchWidget::setupAutoscroll (bool moving) protected
References DragAutoScrollThreshold, dragAutoScrollTimeout(), m_autoScrollCount, m_autoScrollThreshold, m_autoScrollTimer, m_autoScrollX, m_autoScrollY, MoveAutoScrollThreshold, and moveAutoScrollTimeout().
setUpColor()
void SketchWidget::setUpColor (ConnectorItem * fromConnectorItem, ConnectorItem * toConnectorItem, Wire * wire, QUndoCommand * parentCommand) protected virtual
Reimplemented in PCBSketchWidget.
References ItemBase::id(), m_lastColorSelected, and Wire::opacity().
setUpSwap()
long SketchWidget::setUpSwap (SwapThing & swapThing, bool master) virtual
References ShowLabelCommand::add(), SelectItemCommand::addRedo(), SelectItemCommand::addUndo(), BaseCommand::CrossView, findItem(), SwapThing::firstTime, ItemBase::id(), ItemBase::instanceTitle(), ItemBase::isPartLabelVisible(), SwapThing::itemBase, m_viewID, makeDeleteItemCommand(), SwapThing::newID, SwapThing::newModuleID, SelectItemCommand::NormalSelect, SwapThing::parentCommand, prepDeleteProps(), SwapThing::propsMap, CleanUpWiresCommand::RedoOnly, CheckStickyCommand::RemoveOnly, setUpSwapReconnect(), BaseCommand::SingleView, swapStart(), swapStartSignal(), and ItemBase::viewID().
setUpSwapReconnect()
void SketchWidget::setUpSwapReconnect (SwapThing & swapThing, ItemBase * itemBase, long newID, bool master) protected
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToID(), ConnectorItem::attachedToViewLayerID(), SwapThing::bbView, ConnectorItem::beziers(), ViewLayer::BreadboardView, SwapThing::byWire, ItemBase::cachedConnectorItems(), checkFit(), ConnectorItem::connectedToItems(), ModelPart::connectors(), Connector::connectorSharedDescription(), ConnectorItem::connectorSharedDescription(), Connector::connectorSharedID(), ConnectorItem::connectorSharedID(), Connector::connectorSharedName(), ConnectorItem::connectorSharedName(), ConnectorItem::connectorSharedReplacedby(), ConnectorItem::connectorType(), extendChangeConnectionCommand(), Connector::Female, findConnectorItem(), ConnectorItem::getCrossLayerConnectorItem(), ItemBase::getRatsnest(), ItemBase::getViewGeometry(), ConnectorItem::hasRubberBandLeg(), ModelPart::initConnectors(), Bezier::isEmpty(), ConnectorItem::leg(), ViewGeometry::loc(), m_referenceModel, m_viewID, makeSwapWire(), Connector::Male, ItemBase::modelPart(), SwapThing::newModuleID, SwapThing::parentCommand, SwapThing::reconnections, ModelPart::replacedby(), BaseCommand::setRedoOnly(), BaseCommand::SingleView, ViewLayer::specFromID(), SwapThing::swappedGender, swappedGender(), and SwapThing::toConnectorItems.
setViewLayerIDs()
void SketchWidget::setViewLayerIDs (ViewLayer::ViewLayerID part, ViewLayer::ViewLayerID wire, ViewLayer::ViewLayerID connector, ViewLayer::ViewLayerID ruler, ViewLayer::ViewLayerID note)
References m_connectorViewLayerID, m_noteViewLayerID, m_partViewLayerID, m_rulerViewLayerID, and m_wireViewLayerID.
setWireExtras()
void SketchWidget::setWireExtras (long id, QDomElement & extras)
References findItem(), and Wire::setExtras().
setWireMenu()
void SketchWidget::setWireMenu (QMenu * wireMenu)
References m_wireMenu.
setWireVisible()
void SketchWidget::setWireVisible (Wire * wire) protected virtual
Reimplemented in PCBSketchWidget, and BreadboardSketchWidget.
showEvent()
void SketchWidget::showEvent (QShowEvent * event)
References showing().
showGrid()
void SketchWidget::showGrid (bool show)
References m_showGrid, and viewName().
showing
void SketchWidget::showing (SketchWidget *) signal
showingGrid()
bool SketchWidget::showingGrid ()
References m_showGrid.
showLabelFirstTime
void SketchWidget::showLabelFirstTime (long itemID, bool show, bool doEmit) virtual slot
References showLabelFirstTimeSignal().
showLabelFirstTimeSignal
void SketchWidget::showLabelFirstTimeSignal (long itemID, bool show, bool doEmit) signal
showPartLabel
void SketchWidget::showPartLabel (long id, bool showIt) slot
References findItem(), getLabelViewLayerID(), m_viewLayers, and ItemBase::showPartLabel().
showPartLabels()
void SketchWidget::showPartLabels (bool show)
References ItemBase::extractTopLevelItemBase(), ItemBase::hasPartLabel(), and showPartLabelsAux().
showPartLabelsAux()
void SketchWidget::showPartLabelsAux (bool show, QList< ItemBase * > & itemBases) protected
References ShowLabelCommand::add(), ItemBase::id(), ItemBase::isPartLabelVisible(), m_undoStack, and WaitPushUndoStack::push().
showUnrouted()
void SketchWidget::showUnrouted ()
References GraphUtils::chooseRatsnestGraph(), collectAllNets(), ConnectorItem::getCrossLayerConnectorItem(), getTraceFlag(), NonConnectorItem::hidden(), NonConnectorItem::layerHidden(), ViewGeometry::NormalFlag, ViewGeometry::PCBTraceFlag, ViewGeometry::RatsnestFlag, routeBothSides(), ViewGeometry::SchematicTraceFlag, and ConnectorItem::showEqualPotential().
simpleMoveItem()
void SketchWidget::simpleMoveItem (long id, QPointF p)
References findItem(), InfoGraphicsView::m_infoView, ItemBase::setItemPos(), and HtmlInfoView::updateLocation().
sortAnyByZ()
void SketchWidget::sortAnyByZ (const QList< QGraphicsItem * > & items, QList< ItemBase * > & bases)
References ItemBase::saveGeometry(), and ItemBase::zLessThan().
spaceBarIsPressed()
bool SketchWidget::spaceBarIsPressed () virtual noexcept
Reimplemented from InfoGraphicsView.
References m_middleMouseIsPressed, and m_spaceBarIsPressed.
spaceBarIsPressedSlot
void SketchWidget::spaceBarIsPressedSlot (bool isPressed) protected slot
References m_middleMouseIsPressed, and m_spaceBarIsPressed.
squashShapes()
void SketchWidget::squashShapes (QPointF scenePos) protected
References NonConnectorItem::attachedTo(), ItemBase::boundingRect(), ViewLayer::BreadboardView, ItemBase::hidden(), ItemBase::inactive(), ItemBase::layerHidden(), m_squashShapes, ItemBase::selectionShape(), ItemBase::setSquashShape(), unsquashShapes(), and viewID().
stackSelectionState()
SelectItemCommand * SketchWidget::stackSelectionState (bool pushIt, QUndoCommand * parentCommand)
References SelectItemCommand::addUndo(), ItemBase::extractTopLevelItemBase(), ItemBase::id(), m_undoStack, SelectItemCommand::NormalSelect, and WaitPushUndoStack::push().
standardBackground()
QColor SketchWidget::standardBackground ()
References RatsnestColors::backgroundColor(), and m_viewID.
startZChange()
bool SketchWidget::startZChange (QList< ItemBase * > & bases) protected
References sortAnyByZ().
statusMessage
void SketchWidget::statusMessage (QString message, int timeout = 0) protected slot
References m_statusConnectState, StatusConnectFailed, StatusConnectNotTried, StatusConnectSucceeded, and statusMessageSignal().
statusMessageSignal
void SketchWidget::statusMessageSignal (QString , int timeout) signal
stickem()
void SketchWidget::stickem (long stickTargetID, long stickSourceID, bool stick)
References ItemBase::addSticky(), and findItem().
stickyScoop()
void SketchWidget::stickyScoop (ItemBase * stickyOne, bool checkCurrent, CheckStickyCommand * checkStickyCommand)
References ItemBase::addSticky(), ItemBase::alreadySticking(), ItemBase::boundingRect(), ItemBase::id(), ItemBase::isBaseSticky(), ItemBase::layerKinChief(), CheckStickyCommand::stick(), ItemBase::stickyEnabled(), and ItemBase::stickyList().
swapBoardImageSignal
void SketchWidget::swapBoardImageSignal (SketchWidget * sketchWidget, ItemBase * itemBase, const QString & filename, const QString & moduleID, bool addName) signal
swappedGender()
bool SketchWidget::swappedGender (ConnectorItem * originalConnectorItem, Connector * newConnector) protected
References Connector::connectorType(), and ConnectorItem::connectorType().
swappingEnabled()
bool SketchWidget::swappingEnabled (ItemBase * itemBase) virtual
Implements InfoGraphicsView.
References ItemBase::isSwappable(), and m_referenceModel.
swapStart
long SketchWidget::swapStart (SwapThing & swapThing, bool master) protected slot
References findItem(), ItemBase::getNextID(), ItemBase::getViewGeometry(), ItemBase::id(), SwapThing::itemBase, m_viewID, newAddItemCommand(), SwapThing::newModelIndex, SwapThing::newModuleID, SwapThing::parentCommand, ViewGeometry::setTransform(), BaseCommand::SingleView, ViewGeometry::transform(), ItemBase::viewID(), and SwapThing::viewLayerPlacement.
swapStartSignal
void SketchWidget::swapStartSignal (SwapThing & swapThing, bool master) signal
testConnectors()
void SketchWidget::testConnectors ()
References addItemAuxTemp(), ItemBase::cachedConnectorItems(), ConnectorItem::connectorSharedID(), BaseCommand::CrossView, ModelBase::genFZP(), ItemBase::getNextID(), getTraceFlag(), ItemBase::id(), ItemBase::layerKin(), ItemBase::layerKinChief(), m_undoStack, ModelPart::moduleID(), newAddItemCommand(), ViewLayer::NewTop, PropChangeDelay, CleanUpWiresCommand::RedoOnly, referenceModel(), ConnectorItem::sceneAdjustedTerminalPoint(), ViewGeometry::setLine(), ViewGeometry::setLoc(), ViewGeometry::setWireFlags(), CleanUpWiresCommand::UndoOnly, viewID(), ItemBase::viewLayerPlacement(), WaitPushUndoStack::waitPush(), and ModuleIDNames::WireModuleIDName.
tidyWires()
void SketchWidget::tidyWires () virtual
Reimplemented in SchematicSketchWidget.
toggleLayerVisibility
void SketchWidget::toggleLayerVisibility () protected slot
References ViewLayer::includeChildLayers(), setLayerVisible(), and ViewLayer::visible().
traceColor()
const QString & SketchWidget::traceColor (ViewLayer::ViewLayerPlacement) protected virtual
Reimplemented in BreadboardSketchWidget, SchematicSketchWidget, and PCBSketchWidget.
References ___emptyString___.
transformItem()
void SketchWidget::transformItem (long id, const QMatrix & matrix)
References findItem(), InfoGraphicsView::m_infoView, ItemBase::transformItem2(), and HtmlInfoView::updateRotation().
triggerRotate()
void SketchWidget::triggerRotate (ItemBase * itemBase, double degrees) virtual
Reimplemented from InfoGraphicsView.
References clearSelection(), rotateX(), and setIgnoreSelectionChangeEvents().
turnOffAutoscroll()
void SketchWidget::turnOffAutoscroll () protected
References dragAutoScrollTimeout(), m_autoScrollTimer, and moveAutoScrollTimeout().
undoStack()
WaitPushUndoStack * SketchWidget::undoStack ()
References m_undoStack.
unsquashShapes()
void SketchWidget::unsquashShapes () protected
References m_squashShapes, and ItemBase::setSquashShape().
updateConnectors
void SketchWidget::updateConnectors () slot
References ConnectorItem::restoreColor().
updateInfoView()
void SketchWidget::updateInfoView ()
References m_blockUI, and updateInfoViewSlot().
updateInfoViewSlot
void SketchWidget::updateInfoViewSlot () protected slot
References ItemBase::layerKinChief(), m_lastPaletteItemSelected, and viewItemInfo().
updateLayerMenuSignal
void SketchWidget::updateLayerMenuSignal () signal
updateOK()
bool SketchWidget::updateOK (ConnectorItem * , ConnectorItem *) protected virtual
Reimplemented in PCBSketchWidget.
updatePartLabelInstanceTitleSignal
void SketchWidget::updatePartLabelInstanceTitleSignal (long itemID) signal
updatePartLabelInstanceTitleSlot
void SketchWidget::updatePartLabelInstanceTitleSlot (long itemID) protected slot
References findItem(), and ItemBase::updatePartLabelInstanceTitle().
updateRoutingStatus() [1/2]
void SketchWidget::updateRoutingStatus (CleanUpWiresCommand * command, RoutingStatus & routingStatus, bool manual)
References CleanUpWiresCommand::addRoutingStatus(), m_routingStatus, routingStatusSignal(), and RoutingStatus::zero().
updateRoutingStatus() [2/2]
void SketchWidget::updateRoutingStatus (RoutingStatus & routingStatus, bool manual)
References NonConnectorItem::attachedTo(), checkUpdateRatsnest(), ConnectorItem::collectEqualPotential(), ConnectorItem::collectParts(), ConnectorItem::connectionsCount(), Wire::connector0(), Wire::connector1(), getTraceFlag(), includeSymbols(), ItemBase::isEverVisible(), RoutingStatus::m_jumperItemCount, m_ratsnestUpdateConnect, m_ratsnestUpdateDisconnect, ViewLayer::NewTopAndBottom, ViewGeometry::RatsnestFlag, and GraphUtils::scoreOneNet().
updateWire()
void SketchWidget::updateWire (long id, const QString & connectorID, bool updateRatsnest)
References findConnectorItem(), findItem(), ratsnestConnect(), Wire::simpleConnectedMoved(), ViewLayer::specFromID(), and ItemBase::viewLayerID().
updateWires()
void SketchWidget::updateWires ()
References Wire::connectedMoved(), Wire::connector0(), Wire::connector1(), ConnectorItem::firstConnectedToIsh(), getTraceFlag(), and Wire::isTraceType().
viewGeometryConversionHack()
void SketchWidget::viewGeometryConversionHack (ViewGeometry & , ModelPart *) protected virtual
Reimplemented in SchematicSketchWidget.
viewID()
constexpr ViewLayer::ViewID SketchWidget::viewID () const inline noexcept
References m_viewID.
viewItemInfo()
void SketchWidget::viewItemInfo (ItemBase * item) virtual
Reimplemented from InfoGraphicsView.
References m_blockUI, and InfoGraphicsView::viewItemInfo().
viewLayers()
LayerHash & SketchWidget::viewLayers () virtual
Reimplemented from InfoGraphicsView.
References m_viewLayers.
viewName()
constexpr const QString& SketchWidget::viewName () const inline noexcept
References m_viewName.
viewportEvent()
bool SketchWidget::viewportEvent (QEvent * event) protected
References squashShapes(), and unsquashShapes().
vScrollToZero
void SketchWidget::vScrollToZero () protected slot
wireChangedCurveSlot
void SketchWidget::wireChangedCurveSlot (class Wire * wire, const Bezier * oldB, const Bezier * newB, bool triggerFirstTime) protected slot
References clearHoldingSelectItem(), Wire::getAutoroutable(), ItemBase::id(), m_moveEventCount, m_undoStack, WaitPushUndoStack::push(), and BaseCommand::setSkipFirstRedo().
wireChangedSlot
void SketchWidget::wireChangedSlot (class Wire * wire, const QLineF & oldLine, const QLineF & newLine, QPointF oldPos, QPointF newPos, ConnectorItem * from, ConnectorItem * to) protected slot
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToID(), NonConnectorItem::attachedToInstanceTitle(), clearDragWireTempCommand(), clearHoldingSelectItem(), clearTemporaries(), ConnectorItem::connectedToItems(), ConnectorItem::connectorSharedID(), BaseCommand::CrossView, dragWireChanged(), extendChangeConnectionCommand(), ItemBase::getViewGeometry(), ItemBase::id(), ViewGeometry::line(), Wire::line(), ViewGeometry::loc(), m_connectorDragWire, m_moveEventCount, m_undoStack, PropChangeDelay, CheckStickyCommand::RedoOnly, CleanUpWiresCommand::RedoOnly, rememberSticky(), BaseCommand::SingleView, ViewLayer::specFromID(), ConnectorItem::tempRemove(), ItemBase::title(), CleanUpWiresCommand::UndoOnly, ItemBase::updateConnections(), ItemBase::viewLayerID(), and WaitPushUndoStack::waitPush().
wireConnectedSignal
void SketchWidget::wireConnectedSignal (long fromID, QString fromConnectorID, long toID, QString toConnectorID) signal
wireConnectedSlot
void SketchWidget::wireConnectedSlot (long fromID, QString fromConnectorID, long toID, QString toConnectorID) protected slot
References Wire::connector0(), ConnectorItem::connectTo(), findConnectorItem(), findItem(), ConnectorItem::firstConnectedToIsh(), Wire::otherConnector(), ConnectorItem::sceneAdjustedTerminalPoint(), Wire::setLineAnd(), ViewLayer::specFromID(), and ItemBase::viewLayerID().
wireDisconnectedSignal
void SketchWidget::wireDisconnectedSignal (long fromID, QString fromConnectorID) signal
wireDisconnectedSlot
void SketchWidget::wireDisconnectedSlot (long fromID, QString fromConnectorID) protected slot
References DebugDialog::debug(), findConnectorItem(), findItem(), ConnectorItem::firstConnectedToIsh(), ConnectorItem::removeConnection(), ViewLayer::specFromID(), and ItemBase::viewLayerID().
wireJoinSlot
void SketchWidget::wireJoinSlot (class Wire * wire, ConnectorItem * clickedConnectorItem) protected slot
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToID(), clearHoldingSelectItem(), ConnectorItem::connectedToItems(), Wire::connector1(), ConnectorItem::connectorSharedID(), Bezier::copy(), BaseCommand::CrossView, Wire::curve(), Wire::getAutoroutable(), ItemBase::id(), Bezier::join(), Wire::line(), m_moveEventCount, m_undoStack, makeDeleteItemCommand(), Wire::otherConnector(), WaitPushUndoStack::push(), CleanUpWiresCommand::RedoOnly, Wire::saveGeometry(), Bezier::set_endpoints(), BaseCommand::setRedoOnly(), BaseCommand::setUndoOnly(), ViewLayer::specFromID(), Bezier::translate(), CleanUpWiresCommand::UndoOnly, and ItemBase::viewLayerID().
wireSplitCrossView()
BaseCommand::CrossViewType SketchWidget::wireSplitCrossView () protected virtual
Reimplemented in BreadboardSketchWidget.
References BaseCommand::CrossView.
wireSplitSlot
void SketchWidget::wireSplitSlot (class Wire * wire, QPointF newPos, QPointF oldPos, const QLineF & oldLine) protected virtual slot
References SelectItemCommand::addRedo(), NonConnectorItem::attachedToID(), Wire::banded(), canChainWire(), clearHoldingSelectItem(), Wire::colorString(), ConnectorItem::connectedToItems(), Wire::connector1(), ConnectorItem::connectorSharedID(), ItemBase::getNextID(), ItemBase::getViewGeometry(), ItemBase::id(), m_moveEventCount, m_undoStack, SelectItemCommand::NormalSelect, Wire::opacity(), WaitPushUndoStack::push(), CleanUpWiresCommand::RedoOnly, CheckStickyCommand::RemoveOnly, ViewGeometry::setLoc(), ViewLayer::specFromID(), CleanUpWiresCommand::UndoOnly, ItemBase::viewLayerID(), ItemBase::viewLayerPlacement(), Wire::width(), ModuleIDNames::WireModuleIDName, and wireSplitCrossView().
wireViewLayerPlacement()
ViewLayer::ViewLayerPlacement SketchWidget::wireViewLayerPlacement (ConnectorItem *) protected virtual
Reimplemented in PCBSketchWidget.
References InfoGraphicsView::m_boardLayers, ViewLayer::NewBottom, and ViewLayer::NewTop.
Member Data Documentation
DragAutoScrollThreshold
constexpr int SketchWidget::DragAutoScrollThreshold = 10 static protected
m_addDefaultParts
bool SketchWidget::m_addDefaultParts = false protected
m_addedDefaultPart
QPointer<ItemBase> SketchWidget::m_addedDefaultPart protected
m_additionalSavedItems
QList<ItemBase *> SketchWidget::m_additionalSavedItems protected
m_alignmentItem
QPointer<ItemBase> SketchWidget::m_alignmentItem protected
m_alignmentStartPoint
QPointF SketchWidget::m_alignmentStartPoint protected
m_alignToGrid
bool SketchWidget::m_alignToGrid = true protected
m_anyInRotation
bool SketchWidget::m_anyInRotation protected
m_arrowTimer
QTimer SketchWidget::m_arrowTimer protected
m_arrowTotalX
double SketchWidget::m_arrowTotalX = 0.0 protected
m_arrowTotalY
double SketchWidget::m_arrowTotalY = 0.0 protected
m_autoScrollCount
volatile int SketchWidget::m_autoScrollCount = 0 protected
m_autoScrollThreshold
int SketchWidget::m_autoScrollThreshold = 0 protected
m_autoScrollTimer
QTimer SketchWidget::m_autoScrollTimer protected
m_autoScrollX
volatile int SketchWidget::m_autoScrollX = 0 protected
m_autoScrollY
volatile int SketchWidget::m_autoScrollY = 0 protected
m_bendpointVG
ViewGeometry SketchWidget::m_bendpointVG protected
m_bendpointWire
QPointer<Wire> SketchWidget::m_bendpointWire protected
m_blockUI
bool SketchWidget::m_blockUI = false static
m_chainDrag
bool SketchWidget::m_chainDrag = false protected
m_checkUnder
QList<ItemBase *> SketchWidget::m_checkUnder protected
m_clearSceneRect
bool SketchWidget::m_clearSceneRect = false protected
m_connectorDragConnector
QPointer<ConnectorItem> SketchWidget::m_connectorDragConnector protected
m_connectorDragWire
QPointer<Wire> SketchWidget::m_connectorDragWire protected
m_connectorViewLayerID
ViewLayer::ViewLayerID SketchWidget::m_connectorViewLayerID protected
m_current
bool SketchWidget::m_current = false protected
m_curvyWires
bool SketchWidget::m_curvyWires = false protected
m_dragBendpointPos
QPoint SketchWidget::m_dragBendpointPos protected
m_dragBendpointWire
QPointer<Wire> SketchWidget::m_dragBendpointWire protected
m_dragCurve
bool SketchWidget::m_dragCurve = false protected
m_draggingBendpoint
bool SketchWidget::m_draggingBendpoint = false protected
m_droppingItem
QPointer<ItemBase> SketchWidget::m_droppingItem protected
m_droppingOffset
QPointF SketchWidget::m_droppingOffset protected
m_droppingWire
bool SketchWidget::m_droppingWire = false protected
m_everZoomed
bool SketchWidget::m_everZoomed = false protected
m_globalPos
QPoint SketchWidget::m_globalPos protected
m_gridColor
QColor SketchWidget::m_gridColor protected
m_gridSizeInches
double SketchWidget::m_gridSizeInches = 0.0 protected
m_gridSizeText
QString SketchWidget::m_gridSizeText protected
m_holdingSelectItemCommand
class SelectItemCommand* SketchWidget::m_holdingSelectItemCommand = nullptr protected
m_ignoreSelectionChangeEvents
int SketchWidget::m_ignoreSelectionChangeEvents = 0 protected
m_inFocus
QList<QGraphicsItem *> SketchWidget::m_inFocus protected
m_infoViewOnHover
bool SketchWidget::m_infoViewOnHover protected
m_itemMenu
QMenu* SketchWidget::m_itemMenu = nullptr protected
m_lastColorSelected
QString SketchWidget::m_lastColorSelected protected
m_lastHoverEnterConnectorItem
QPointer<ConnectorItem> SketchWidget::m_lastHoverEnterConnectorItem protected
m_lastHoverEnterItem
QPointer<ItemBase> SketchWidget::m_lastHoverEnterItem protected
m_lastPaletteItemSelected
QPointer<PaletteItem> SketchWidget::m_lastPaletteItemSelected protected
m_middleMouseIsPressed
bool SketchWidget::m_middleMouseIsPressed = false protected
m_mousePressGlobalPos
QPointF SketchWidget::m_mousePressGlobalPos protected
m_mousePressScenePos
QPointF SketchWidget::m_mousePressScenePos protected
m_moveDisconnectedFromFemale
ConnectorPairHash SketchWidget::m_moveDisconnectedFromFemale protected
m_moveEventCount
int SketchWidget::m_moveEventCount = 0 protected
m_moveReferenceItem
QPointer<ItemBase> SketchWidget::m_moveReferenceItem protected
m_movingByArrow
bool SketchWidget::m_movingByArrow = false protected
m_movingByMouse
bool SketchWidget::m_movingByMouse = false protected
m_movingItem
QPointer<QGraphicsSvgItem> SketchWidget::m_movingItem protected
m_movingSVGOffset
QPointF SketchWidget::m_movingSVGOffset protected
m_movingSVGRenderer
QPointer<QSvgRenderer> SketchWidget::m_movingSVGRenderer protected
m_noteViewLayerID
ViewLayer::ViewLayerID SketchWidget::m_noteViewLayerID protected
m_originatingItem
QPointer<ItemBase> SketchWidget::m_originatingItem protected
m_partViewLayerID
ViewLayer::ViewLayerID SketchWidget::m_partViewLayerID protected
m_pasteCount
int SketchWidget::m_pasteCount = 0 protected
m_pasteOffset
QPointF SketchWidget::m_pasteOffset protected
m_pasting
bool SketchWidget::m_pasting = false protected
m_ratsnestCacheConnect
QList< QPointer<ConnectorItem> > SketchWidget::m_ratsnestCacheConnect protected
m_ratsnestCacheDisconnect
QList< QPointer<ConnectorItem> > SketchWidget::m_ratsnestCacheDisconnect protected
m_ratsnestOpacity
double SketchWidget::m_ratsnestOpacity = 0.0 protected
m_ratsnestUpdateConnect
QList< QPointer<ConnectorItem> > SketchWidget::m_ratsnestUpdateConnect protected
m_ratsnestUpdateDisconnect
QList< QPointer<ConnectorItem> > SketchWidget::m_ratsnestUpdateDisconnect protected
m_ratsnestWidth
double SketchWidget::m_ratsnestWidth = 0.0 protected
m_referenceModel
QPointer<class ReferenceModel> SketchWidget::m_referenceModel protected
m_resizingBoard
QPointer<class ResizableBoard> SketchWidget::m_resizingBoard protected
m_routingStatus
RoutingStatus SketchWidget::m_routingStatus protected
m_rubberBandLegWasEnabled
bool SketchWidget::m_rubberBandLegWasEnabled = false protected
m_rulerViewLayerID
ViewLayer::ViewLayerID SketchWidget::m_rulerViewLayerID protected
m_savedItems
QHash<long, ItemBase *> SketchWidget::m_savedItems protected
m_savedWires
QHash<Wire *, ConnectorItem *> SketchWidget::m_savedWires protected
m_shortName
QString SketchWidget::m_shortName protected
m_showGrid
bool SketchWidget::m_showGrid = true protected
m_sizeItem
QPointer<SizeItem> SketchWidget::m_sizeItem protected
m_sketchModel
QPointer<SketchModel> SketchWidget::m_sketchModel protected
m_spaceBarIsPressed
bool SketchWidget::m_spaceBarIsPressed = false protected
m_spaceBarWasPressed
bool SketchWidget::m_spaceBarWasPressed = false protected
m_squashShapes
QList< QPointer<ItemBase> > SketchWidget::m_squashShapes protected
m_statusConnectState
StatusConnectStatus SketchWidget::m_statusConnectState = StatusConnectNotTried protected
m_stretchingLegs
QMultiHash<ItemBase *, ConnectorItem *> SketchWidget::m_stretchingLegs protected
m_tempDragWireCommand
class SelectItemCommand* SketchWidget::m_tempDragWireCommand = nullptr protected
m_temporaries
QList<QGraphicsItem *> SketchWidget::m_temporaries protected
m_undoStack
class WaitPushUndoStack* SketchWidget::m_undoStack = nullptr protected
m_viewID
ViewLayer::ViewID SketchWidget::m_viewID protected
m_viewLayers
LayerHash SketchWidget::m_viewLayers protected
m_viewLayerVisibility
QHash<ViewLayer::ViewLayerID, bool> SketchWidget::m_viewLayerVisibility protected
m_viewName
QString SketchWidget::m_viewName protected
m_wireMenu
QMenu* SketchWidget::m_wireMenu = nullptr protected
m_wireViewLayerID
ViewLayer::ViewLayerID SketchWidget::m_wireViewLayerID protected
m_z
float SketchWidget::m_z protected
m_zoom
double SketchWidget::m_zoom = 100 protected
MoveAutoScrollThreshold
constexpr int SketchWidget::MoveAutoScrollThreshold = 5 static protected
PropChangeDelay
constexpr int SketchWidget::PropChangeDelay = 100 static
Property Documentation
gridColor
QColor SketchWidget::gridColor read write
ratsnestOpacity
double SketchWidget::ratsnestOpacity read write
ratsnestWidth
double SketchWidget::ratsnestWidth read write
The documentation for this class was generated from the following files:
sketch/sketchwidget.h
sketch/sketchwidget.cpp