Fritzing: PartsEditorView Class Reference
PartsEditorView Class Reference
#include <partseditorview.h>
Public Slots
void addItemInPartsEditor (ModelPart *modelPart, SvgAndPartFilePath *svgFilePath)
void checkConnectorLayers (ViewLayer::ViewIdentifier, const QString &connId, Connector *existingConnector, Connector *newConnector)
void informConnectorSelection (const QString &connId)
void informConnectorSelectionFromView (const QString &connId)
void loadFile ()
void loadFromModel (PaletteModel *paletteModel, ModelPart *modelPart)
void loadSvgFile (const QString &origPath)
void setMismatching (ViewLayer::ViewIdentifier viewId, const QString &id, bool mismatching)
void updateModelPart (const QString &origPath)
Public Slots inherited from SketchWidget
void addSubpart (long id, long subpartid, bool doEmit)
virtual void changeBoardLayers (int layers, bool doEmit)
void changeWireColor (const QString newColor)
void changeWireWidthMils (const QString newWidth)
void checkSticky (long id, bool doEmit, bool checkCurrent, CheckStickyCommand *)
void cleanupRatsnests (bool doEmit)
void disconnectAllSlot (QList< ConnectorItem * >, QHash< ItemBase *, SketchWidget * > &itemsToDelete, QUndoCommand *parentCommand)
void incInstanceTitle (long id)
void packItems (int columns, const QList< long > &ids, QUndoCommand *parent, bool doEmit)
void ratsnestConnect (long id, const QString &connectorID, bool connect, bool doEmit)
virtual ItemBase * resizeBoard (long id, double w, double h)
void resizeBoard (double w, double h, bool doEmit)
void resizeJumperItem (long id, QPointF pos, QPointF c0, QPointF c1)
void selectAllItems (bool state, bool doEmit)
void setHoleSize (ItemBase *, const QString &propName, const QString &translatedPropName, const QString &oldValue, const QString &newValue, QRectF &oldRect, QRectF &newRect, bool redraw)
void setInstanceTitle (long id, const QString &oldTitle, const QString &newTitle, bool isUndoable, bool doEmit)
void setNoteText (long itemID, const QString &newText)
void setProp (long itemID, const QString &prop, const QString &value, bool redraw, bool doEmit)
virtual void setProp (ItemBase *, const QString &propName, const QString &translatedPropName, const QString &oldValue, const QString &newValue, bool redraw)
void setResistance (long itemID, QString resistance, QString pinSpacing, bool doEmit)
void setResistance (QString resistance, QString pinSpacing)
virtual void showLabelFirstTime (long itemID, bool show, bool doEmit)
void showPartLabel (long id, bool showIt)
void updateConnectors ()
Public Slots inherited from InfoGraphicsView
virtual void resizeBoard (double w, double h, bool doEmit)
virtual void setInstanceTitle (long id, const QString &oldTitle, const QString &newTitle, bool isUndoable, bool doEmit)
virtual void setVoltage (double, bool doEmit)
Signals
void connectorSelected (const QString &connId)
void connectorsFoundSignal (ViewLayer::ViewIdentifier viewId, const QList< QPointer< Connector > > &conns)
void removeTerminalPoint (const QString &connId, ViewLayer::ViewIdentifier vid)
void svgFileLoadNeeded (const QString &filepath)
Signals inherited from SketchWidget
void addSubpartSignal (long id, long subpartID, bool doEmit)
void canConnectSignal (Wire *from, ItemBase *to, bool &connect)
void changeBoardLayersSignal (int, bool doEmit)
void changeConnectionSignal (long fromID, QString fromConnectorID, long toID, QString toConnectorID, ViewLayer::ViewLayerPlacement, bool connect, bool updateConnections)
void checkStickySignal (long id, bool doEmit, bool checkCurrent, CheckStickyCommand *)
void cleanupRatsnestsSignal (bool doEmit)
void cleanUpWiresSignal (CleanUpWiresCommand *)
void clearSelectionSignal ()
void clickedItemCandidateSignal (QGraphicsItem *, bool &ok)
void collectRatsnestSignal (QList< SketchWidget * > &foreignSketchWidgets)
void copyBoundingRectsSignal (QHash< QString, QRectF > &)
void cursorLocationSignal (double xinches, double yinches, double width=0.0, double height=0.0)
void deleteTracesSignal (QSet< ItemBase * > &deletedItems, QHash< ItemBase *, SketchWidget * > &otherDeletedItems, QList< long > &deletedIDs, bool isForeign, QUndoCommand *parentCommand)
void disconnectAllSignal (QList< ConnectorItem * >, QHash< ItemBase *, SketchWidget * > &itemsToDelete, QUndoCommand *parentCommand)
void dropPasteSignal (SketchWidget *)
void dropSignal (const QPoint &pos)
void filenameIfSignal (QString &filename)
void getDroppedItemViewLayerPlacementSignal (ModelPart *modelPart, ViewLayer::ViewLayerPlacement &)
void itemAddedSignal (ModelPart *, ItemBase *, ViewLayer::ViewLayerPlacement, const ViewGeometry &, long id, SketchWidget *dropOrigin)
void itemDeletedSignal (long id)
void itemMovedSignal (ItemBase *)
void itemSelectedSignal (long id, bool state)
void makeDeleteItemCommandFinalSignal (ItemBase *itemBase, bool foreign, QUndoCommand *parentCommand)
void makeDeleteItemCommandPrepSignal (ItemBase *itemBase, bool foreign, QUndoCommand *parentCommand)
void movingSignal (SketchWidget *, QUndoCommand *parentCommand)
void packItemsSignal (int columns, const QList< long > &ids, QUndoCommand *parent, bool doEmit)
void ratsnestConnectSignal (long id, const QString &connectorID, bool connect, bool doEmit)
void removeRatsnestSignal (QList< struct ConnectorEdge * > &cutSet, QUndoCommand *parentCommand)
void resizedSignal (ItemBase *)
void resizeSignal ()
void routingStatusSignal (SketchWidget *, const RoutingStatus &)
void selectAllItemsSignal (bool state, bool doEmit)
void selectionChangedSignal ()
void setInstanceTitleSignal (long id, const QString &oldTitle, const QString &newTitle, bool isUndoable, bool doEmit)
void setPropSignal (long itemID, const QString &prop, const QString &value, bool doRedraw, bool doEmit)
void setResistanceSignal (long itemID, QString resistance, QString pinSpacing, bool doEmit)
void showing (SketchWidget *)
void showLabelFirstTimeSignal (long itemID, bool show, bool doEmit)
void statusMessageSignal (QString, int timeout)
void swapBoardImageSignal (SketchWidget *sketchWidget, ItemBase *itemBase, const QString &filename, const QString &moduleID, bool addName)
void swapStartSignal (SwapThing &swapThing, bool master)
void updateLayerMenuSignal ()
void updatePartLabelInstanceTitleSignal (long itemID)
void wireConnectedSignal (long fromID, QString fromConnectorID, long toID, QString toConnectorID)
void wireDisconnectedSignal (long fromID, QString fromConnectorID)
Signals inherited from InfoGraphicsView
void changePinLabelsSignal (ItemBase *, bool singleRow)
void newWireSignal (Wire *)
void setActiveConnectorItemSignal (ConnectorItem *)
void setActiveWireSignal (Wire *)
void setVoltageSignal (double, bool doEmit)
void swapSignal (const QString &family, const QString &prop, QMap< QString, QString > &propsMap, ItemBase *)
Signals inherited from ZoomableGraphicsView
void wheelSignal ()
void zoomChanged (double zoom)
void zoomOutOfRange (double zoom)
Public Member Functions
PartsEditorView (ViewLayer::ViewIdentifier, QDir tempDir, bool showingTerminalPoints, QGraphicsProxyWidget *startItem=0, QWidget *parent=0, int size=150, bool deleteModelPartOnClearScene=false, class ItemBase *fromItem=NULL)
~PartsEditorView ()
void aboutToSave (bool fakeDefaultIfNotIn)
void addFixedToBottomRight (QWidget *widget)
ViewLayer::ViewLayerID connectorsLayerId ()
bool connsPosOrSizeChanged ()
void copySvgFileToDestiny (const QString &partFileName)
void drawConector (Connector *conn, bool showTerminalPoint)
bool imageLoaded ()
void inFileDefinedConnectorChanged (PartsEditorConnectorsConnectorItem *connItem)
bool isEmpty ()
void loadSvgFile (ModelPart *modelPart)
PartsEditorConnectorsPaletteItem * myItem ()
void removeConnector (const QString &connId)
void setPaletteModel (PaletteModel *)
void setViewItem (ItemBase *)
bool showingTerminalPoints ()
void showTerminalPoints (bool show)
const QString svgFilePath ()
const SvgAndPartFilePath & svgFileSplit ()
QString svgIdForConnector (const QString &connId)
QDir tempFolder ()
QString terminalIdForConnector (const QString &connId)
void updatePinsInfo (QList< QPointer< class ConnectorShared > > conns)
Public Member Functions inherited from SketchWidget
SketchWidget (ViewLayer::ViewID, QWidget *parent=0, int size=400, int minSize=300)
~SketchWidget ()
void addBendpoint (ItemBase *lastHoverEnterItem, ConnectorItem *lastHoverEnterConnectorItem, QPointF lastLocation)
virtual void addDefaultParts ()
ItemBase * addItem (ModelPart *, ViewLayer::ViewLayerPlacement, BaseCommand::CrossViewType, const ViewGeometry &, long id, long modelIndex, AddDeleteItemCommand *originatingCommand)
ItemBase * addItem (const QString &moduleID, ViewLayer::ViewLayerPlacement, BaseCommand::CrossViewType, const ViewGeometry &, long id, long modelIndex, AddDeleteItemCommand *originatingCommand)
virtual ItemBase * addItemAux (ModelPart *, ViewLayer::ViewLayerPlacement, const ViewGeometry &, long id, bool doConnectors, ViewLayer::ViewID, bool temporary)
ItemBase * addItemAuxTemp (ModelPart *, ViewLayer::ViewLayerPlacement, const ViewGeometry &, long id, bool doConnectors, ViewLayer::ViewID, bool temporary)
void addLegBendpoint (long id, const QString &connectorID, int index, QPointF, const class Bezier *, const class Bezier *)
void addToSketch (QList< ModelPart * > &)
void addViewLayer (ViewLayer *)
virtual void addViewLayers ()
QGraphicsItem * addWatermark (const QString &filename)
bool alignedToGrid ()
void alignItems (Qt::Alignment)
QPointF alignOneToGrid (ItemBase *itemBase)
void alignToGrid (bool)
const QColor & background ()
void blockUI (bool)
void bringForward ()
void bringToFront ()
ItemCount calcItemCount ()
virtual bool canCopyItem (QGraphicsItem *item, int count)
virtual bool canDeleteItem (QGraphicsItem *item, int count)
virtual bool canDisconnectAll ()
void changeBus (ItemBase *, bool connec, const QString &oldBus, const QString &newBus, QList< ConnectorItem * > &, const QString &message, const QString &oldLayout, const QString &newLayout)
virtual void changeConnection (long fromID, const QString &fromConnectorID, long toID, const QString &toConnectorID, ViewLayer::ViewLayerPlacement, bool connect, bool doEmit, bool updateConnections)
virtual void changeLayer (long id, double z, ViewLayer::ViewLayerID viewLayerID)
void changeLeg (long fromID, const QString &connectorID, const QPolygonF &, bool relative, const QString &why)
void changeLegCurve (long id, const QString &connectorID, int index, const Bezier *)
void changeWire (long fromID, QLineF line, QPointF pos, bool updateConnections, bool updateRatsnest)
void changeWireColor (long wireId, const QString &color, double opacity)
void changeWireCurve (long id, const Bezier *, bool autoroutable)
void changeWireFlags (long wireId, ViewGeometry::WireFlags wireFlags)
void changeWireWidth (long wireId, double width)
void changeZ (QHash< long, RealPair * >, double(*pairAccessor)(RealPair *))
void checkForReversedWires ()
void cleanUpWires (bool doEmit, class CleanUpWiresCommand *)
void clearPasteOffset ()
void clearSelection ()
void collectAllNets (QHash< class ConnectorItem *, int > &indexer, QList< QList< class ConnectorItem * > * > &allPartConnectorItems, bool includeSingletons, bool bothSides)
void collectParts (QList< ItemBase * > &partList)
void copy ()
void copyHeart (QList< ItemBase * > &bases, bool saveBoundingRects, QByteArray &itemData, QList< long > &modelIndexes)
virtual void createTrace (Wire *, bool useLastWireColor)
long createWire (ConnectorItem *from, ConnectorItem *to, ViewGeometry::WireFlags, bool dontUpdate, BaseCommand::CrossViewType, QUndoCommand *parentCommand)
bool curvyWires ()
bool curvyWiresIndicated (Qt::KeyboardModifiers)
void cut ()
virtual double defaultGridSizeInches ()
virtual ViewLayer::ViewLayerPlacement defaultViewLayerPlacement (ModelPart *)
void deleteItem (long id, bool deleteModelPart, bool doEmit, bool later)
void deleteMiddle (QSet< ItemBase * > &deletedItems, QUndoCommand *parentCommand)
void deleteSelected (Wire *, bool minus)
void disconnectAll ()
void ensureLayerVisible (ViewLayer::ViewLayerID)
constexpr bool everZoomed () const noexcept
const QString & filenameIf ()
ConnectorItem * findConnectorItem (ConnectorItem *foreignConnectorItem)
ItemBase * findItem (long id)
double fitInWindow ()
void flattenCurve (ItemBase *lastHoverEnterItem, ConnectorItem *lastHoverEnterConnectorItem, QPointF lastLocation)
void flipItem (long id, Qt::Orientations orientation)
void flipX (Qt::Orientations orientation, bool rubberBandLegEnabled)
virtual void forwardRoutingStatus (const RoutingStatus &)
virtual QHash< QString, QString > getAutorouterSettings ()
void getBendpointWidths (class Wire *, double w, double &w1, double &w2, bool &negativeOffsetRect)
void getRatsnestColor (QColor &)
PaletteItem * getSelectedPart ()
const QString & getShortName ()
float getTopZ ()
ViewGeometry::WireFlag getTraceFlag ()
virtual ViewLayer::ViewLayerID getWireViewLayerID (const ViewGeometry &viewGeometry, ViewLayer::ViewLayerPlacement)
constexpr const QColor & gridColor () const noexcept
QString gridSizeText ()
virtual bool hasAnyNets ()
void hideConnectors (bool hide)
void hidePartLabel (ItemBase *item)
void hidePartLayer (long id, ViewLayer::ViewLayerID, bool hide)
void hidePartLayer (ItemBase *, ViewLayer::ViewLayerID, bool hide)
void hoverEnterConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
void hoverEnterItem (QGraphicsSceneHoverEvent *event, ItemBase *item)
void hoverLeaveConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
void hoverLeaveItem (QGraphicsSceneHoverEvent *event, ItemBase *item)
virtual bool ignoreFemale ()
virtual bool includeSymbols ()
void initGrid ()
ConnectorItem * lastHoverEnterConnectorItem ()
ItemBase * lastHoverEnterItem ()
bool layerIsActive (ViewLayer::ViewLayerID)
bool layerIsVisible (ViewLayer::ViewLayerID)
virtual void loadFromModelParts (QList< ModelPart * > &modelParts, BaseCommand::CrossViewType, QUndoCommand *parentCommand, bool offsetPaste, const QRectF *boundingRect, bool seekOutsideConnections, QList< long > &newIDs)
void loadLogoImage (ItemBase *, const QString &oldSvg, const QSizeF oldAspectRatio, const QString &oldFilename, const QString &newFilename, bool addName)
void loadLogoImage (long itemID, const QString &oldSvg, const QSizeF oldAspectRatio, const QString &oldFilename)
void loadLogoImage (long itemID, const QString &newFilename, bool addName)
void makeDeleteItemCommand (ItemBase *itemBase, BaseCommand::CrossViewType, QUndoCommand *parentCommand)
VirtualWire * makeOneRatsnestWire (ConnectorItem *source, ConnectorItem *dest, bool routed, QColor color, bool force)
void makeWiresChangeConnectionCommands (const QList< Wire * > &wires, QUndoCommand *parentCommand)
void mousePressConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
void moveItem (long id, ViewGeometry &, bool updateRatsnest)
void moveItem (long id, const QPointF &p, bool updateRatsnest)
void moveItem (ItemBase *, double x, double y)
void moveLegBendpoint (long id, const QString &connectorID, int index, QPointF)
void movePartLabel (long itemID, QPointF newPos, QPointF newOffset)
void noteChanged (ItemBase *, const QString &oldText, const QString &newtext, QSizeF oldSize, QSizeF newSize)
void noteSizeChanged (ItemBase *itemBase, const QSizeF &oldSize, const QSizeF &newSize)
void partLabelChanged (ItemBase *, const QString &oldText, const QString &newtext)
void partLabelMoved (ItemBase *, QPointF oldPos, QPointF oldOffset, QPointF newPos, QPointF newOffset)
bool partLabelsVisible ()
void pasteHeart (QByteArray &itemData, bool seekOutsideConnections)
void prepLegBendpointChange (ConnectorItem *from, int oldCount, int newCount, int index, QPointF pos, const class Bezier *, const class Bezier *, const class Bezier *, bool triggerFirstTime)
void prepLegBendpointMove (ConnectorItem *from, int index, QPointF oldPos, QPointF newPos, ConnectorItem *to, bool changeConnections)
void prepLegCurveChange (ConnectorItem *from, int index, const class Bezier *oldB, const class Bezier *newB, bool triggerFirstTime)
void prepLegSelection (ItemBase *)
void pushCommand (QUndoCommand *, QObject *signalTarget)
void ratsnestConnect (ConnectorItem *connectorItem, bool connect)
void ratsnestConnect (ItemBase *, bool connect)
void ratsnestConnect (ConnectorItem *c1, ConnectorItem *c2, bool connect, bool wait)
double ratsnestOpacity ()
double ratsnestWidth ()
void recalcLeg (long fromID, const QString &connectorID, const QPolygonF &, bool relative, bool active, const QString &why)
class ReferenceModel * referenceModel ()
void removeLegBendpoint (long id, const QString &connectorID, int index, const class Bezier *)
void renamePins (ItemBase *, const QStringList &oldLabels, const QStringList &newLabels, bool singleRow)
void renamePins (long itemID, const QStringList &labels, bool singleRow)
QString renderToSVG (RenderThing &, QGraphicsItem *board, const LayerList &)
void resizeNote (long itemID, const QSizeF &)
void resolveTemporary (bool, ItemBase *)
void restoreLayerVisibility ()
void restorePartLabel (long itemID, QDomElement &element)
double retrieveZoom ()
void rotateFlipPartLabel (ItemBase *, double degrees, Qt::Orientations flipDirection)
void rotateFlipPartLabel (long itemID, double degrees, Qt::Orientations flipDirection)
void rotateItem (long id, double degrees)
void rotateLeg (long fromID, const QString &connectorID, const QPolygonF &, bool active)
void rotateX (double degrees, bool rubberBandLegEnabled, ItemBase *originatingItem)
virtual bool routeBothSides ()
virtual bool sameElectricalLayer2 (ViewLayer::ViewLayerID, ViewLayer::ViewLayerID)
void saveLayerVisibility ()
void saveZoom (double)
int selectAllMoveLock ()
QList< ItemBase * > selectAllObsolete ()
virtual void selectAllWires (ViewGeometry::WireFlag)
void selectDeselectAllCommand (bool state)
const QString & selectedModuleID ()
void selectItem (long id, bool state, bool updateInfoView, bool doEmit)
void selectItem (ItemBase *itemBase)
void selectItems (QList< ItemBase * >)
void selectItemsWithModuleID (ModelPart *)
void sendBackward ()
void sendToBack ()
void setAllLayersVisible (bool visible)
void setAnyInRotation ()
virtual void setAutorouterSettings (QHash< QString, QString > &)
void setBackground (QColor)
void setBackgroundColor (QColor, bool setPref)
void setChainDrag (bool)
virtual void setClipEnds (class ClipableWire *, bool)
virtual void setCurrent (bool current)
void setCurvyWires (bool)
void setEverZoomed (bool)
void setGridColor (QColor)
void setGridSize (const QString &)
void setGroundFillSeed (long id, const QString &connectorID, bool seed)
void setIgnoreSelectionChangeEvents (bool)
void setInfoViewOnHover (bool infoViewOnHover)
void setItemDropOffset (long id, QPointF offset)
void setItemMenu (QMenu *)
void setLayerActive (ViewLayer *viewLayer, bool active)
void setLayerActive (ViewLayer::ViewLayerID viewLayerID, bool active)
void setLayerVisible (ViewLayer *viewLayer, bool visible, bool doChildLayers)
void setLayerVisible (ViewLayer::ViewLayerID viewLayerID, bool visible, bool doChildLayers)
void setMoveLock (long id, bool lock)
void setNoteFocus (QGraphicsItem *, bool inFocus)
void setPasting (bool)
void setRatsnestOpacity (double)
void setRatsnestWidth (double)
void setReferenceModel (class ReferenceModel *referenceModel)
void setSketchModel (SketchModel *)
void setUndoStack (class WaitPushUndoStack *)
virtual long setUpSwap (SwapThing &, bool master)
void setViewLayerIDs (ViewLayer::ViewLayerID part, ViewLayer::ViewLayerID wire, ViewLayer::ViewLayerID connector, ViewLayer::ViewLayerID ruler, ViewLayer::ViewLayerID note)
void setWireExtras (long id, QDomElement &)
void setWireMenu (QMenu *)
void showEvent (QShowEvent *event)
void showGrid (bool)
bool showingGrid ()
void showPartLabels (bool show)
void showUnrouted ()
void simpleMoveItem (long id, QPointF)
void sortAnyByZ (const QList< QGraphicsItem * > &items, QList< ItemBase * > &bases)
bool spaceBarIsPressed () noexcept
class SelectItemCommand * stackSelectionState (bool pushIt, QUndoCommand *parentCommand)
QColor standardBackground ()
void stickem (long stickTargetID, long stickSourceID, bool stick)
void stickyScoop (ItemBase *stickyOne, bool checkCurrent, CheckStickyCommand *)
bool swappingEnabled (ItemBase *)
void testConnectors ()
virtual void tidyWires ()
void transformItem (long id, const QMatrix &)
void triggerRotate (ItemBase *, double degrees)
class WaitPushUndoStack * undoStack ()
void updateInfoView ()
void updateRoutingStatus (CleanUpWiresCommand *, RoutingStatus &, bool manual)
void updateRoutingStatus (RoutingStatus &, bool manual)
void updateWire (long id, const QString &connectorID, bool updateRatsnest)
void updateWires ()
constexpr ViewLayer::ViewID viewID () const noexcept
void viewItemInfo (ItemBase *item)
LayerHash & viewLayers ()
constexpr const QString & viewName () const noexcept
Public Member Functions inherited from InfoGraphicsView
InfoGraphicsView (QWidget *parent=0)
int boardLayers ()
virtual void changePinLabels (ItemBase *, bool singleRow)
virtual void changeWireColor (const QString newColor)
virtual void changeWireWidthMils (const QString newWidth)
virtual QString generateCopperFillUnit (ItemBase *itemBase, QPointF whereToStart)
virtual void getLabelFont (QFont &, QColor &, ItemBase *)
virtual double getLabelFontSizeLarge ()
virtual double getLabelFontSizeMedium ()
virtual double getLabelFontSizeSmall ()
virtual double getLabelFontSizeTiny ()
virtual double getWireStrokeWidth (Wire *, double wireWidth)
virtual bool hasBigDots ()
class HtmlInfoView * infoView ()
virtual void initWire (class Wire *, int penWidth)
virtual void newWire (Wire *)
void setActiveConnectorItem (ConnectorItem *)
void setActiveWire (Wire *)
virtual void setBoardLayers (int, bool redraw)
virtual void setHoleSize (ItemBase *, const QString &propName, const QString &translatedPropName, const QString &oldValue, const QString &newValue, QRectF &oldRect, QRectF &newRect, bool redraw)
void setInfoView (class HtmlInfoView *)
virtual void setProp (ItemBase *, const QString &propName, const QString &translatedPropName, const QString &oldValue, const QString &newValue, bool redraw)
virtual void setResistance (QString resistance, QString pinSpacing)
void setSMDOrientation (Qt::Orientations)
Qt::Orientations smdOrientation ()
virtual void swap (const QString &family, const QString &prop, QMap< QString, QString > &propsMap, ItemBase *)
void updateRotation (ItemBase *)
Public Member Functions inherited from ZoomableGraphicsView
ZoomableGraphicsView (QWidget *parent=0)
void absoluteZoom (double percent)
double currentZoom ()
void relativeZoom (double step, bool centerToCursor)
void setAcceptWheelEvents (bool)
virtual void setViewFromBelow (bool)
bool viewFromBelow ()
Protected Slots
void ensureFixedItemsPositions ()
void fitCenterAndDeselect ()
void recoverTerminalPointsState ()
Protected Slots inherited from SketchWidget
void arrowTimerTimeout ()
void autoScrollTimeout ()
void canConnect (Wire *from, ItemBase *to, bool &connect)
void changeConnectionSlot (long fromID, QString fromConnectorID, long toID, QString toConnectorID, ViewLayer::ViewLayerPlacement, bool connect, bool updateConnections)
void changePinLabels (ItemBase *, bool singleRow)
void changePinLabelsSlot (ItemBase *itemBase, bool singleRow)
void cleanUpWiresSlot (CleanUpWiresCommand *)
void clearSelectionSlot ()
void collectRatsnestSlot (QList< SketchWidget * > &foreignSketchWidgets)
void copyBoundingRectsSlot (QHash< QString, QRectF > &)
void deleteRatsnest (Wire *, QUndoCommand *parentCommand)
void deleteTemporary ()
void deleteTracesSlot (QSet< ItemBase * > &deletedItems, QHash< ItemBase *, SketchWidget * > &otherDeletedItems, QList< long > &deletedIDs, bool isForeign, QUndoCommand *parentCommand)
void dragAutoScrollTimeout ()
void dragIsDoneSlot (class ItemDrag *)
virtual void getDroppedItemViewLayerPlacement (ModelPart *modelPart, ViewLayer::ViewLayerPlacement &)
void itemAddedSlot (ModelPart *, ItemBase *, ViewLayer::ViewLayerPlacement, const ViewGeometry &, long id, SketchWidget *dropOrigin)
void itemDeletedSlot (long id)
void itemSelectedSlot (long id, bool state)
void makeDeleteItemCommandFinalSlot (ItemBase *itemBase, bool foreign, QUndoCommand *parentCommand)
void makeDeleteItemCommandPrepSlot (ItemBase *itemBase, bool foreign, QUndoCommand *parentCommand)
void moveAutoScrollTimeout ()
void rememberSticky (long id, QUndoCommand *parentCommand)
void rememberSticky (ItemBase *, QUndoCommand *parentCommand)
void removeRatsnestSlot (QList< struct ConnectorEdge * > &cutSet, QUndoCommand *parentCommand)
void restartPasteCount ()
void selectionChangedSlot ()
void spaceBarIsPressedSlot (bool)
void statusMessage (QString message, int timeout=0)
long swapStart (SwapThing &swapThing, bool master)
void toggleLayerVisibility ()
void updateInfoViewSlot ()
void updatePartLabelInstanceTitleSlot (long itemID)
void vScrollToZero ()
void wireChangedCurveSlot (class Wire *, const Bezier *oldB, const Bezier *newB, bool triggerFirstTime)
void wireChangedSlot (class Wire *, const QLineF &oldLine, const QLineF &newLine, QPointF oldPos, QPointF newPos, ConnectorItem *from, ConnectorItem *to)
void wireConnectedSlot (long fromID, QString fromConnectorID, long toID, QString toConnectorID)
void wireDisconnectedSlot (long fromID, QString fromConnectorID)
void wireJoinSlot (class Wire *, ConnectorItem *clickedConnectorItem)
virtual void wireSplitSlot (class Wire *, QPointF newPos, QPointF oldPos, const QLineF &oldLine)
Protected Member Functions
bool addConnectorsIfNeeded (QDomDocument *svgDom, const QSizeF &sceneViewBox, const QRectF &svgViewBox, const QString &connectorsLayerId)
bool addDefaultLayerIfNotInSvg (QDomDocument *svgDom, bool fakeDefaultIfNone)
void addDefaultLayers (class ItemBase *fromItem)
void addFixedToBottomLeftItem (QGraphicsItem *item)
void addFixedToBottomRightItem (QGraphicsItem *item)
void addFixedToCenterItem (QGraphicsItem *item)
void addFixedToTopLeftItem (QGraphicsItem *item)
void addFixedToTopRightItem (QGraphicsItem *item)
ItemBase * addItemAux (ModelPart *modelPart, ViewLayer::ViewLayerSpec, const ViewGeometry &viewGeometry, long id, PaletteItem *paletteItem, bool doConnectors, ViewLayer::ViewIdentifier, bool temporary)
void addNewTerminalPoints (const QList< PartsEditorConnectorsConnectorItem * > &connsWithNewTPs, QDomDocument *svgDom, const QSizeF &sceneViewBox, const QRectF &svgViewBox, const QString &connectorsLayerId)
bool addRectToSvg (QDomDocument *svgDom, const QString &id, const QRectF &rect, const QString &connectorsLayerId)
bool addRectToSvgAux (QDomElement &docElem, const QString &connectorsLayerId, QDomElement &rectElem)
void beforeSVGLoading (const QString &filename, bool &canceled)
void clearFixedItems ()
void clearScene ()
void connectItem ()
void copyToTempAndRenameIfNecessary (SvgAndPartFilePath *filePathOrig)
void createConnector (Connector *conn, const QSize &connSize, bool showTerminalPoint)
ModelPart * createFakeModelPart (SvgAndPartFilePath *svgpath)
ModelPart * createFakeModelPart (const QHash< QString, ConnectorTerminalSvgIdPair > &connIds, const QStringList &layers, const QString &svgFilePath)
QString createSvgFromImage (const QString &filePath)
QStringList defaultLayerAsStringlist ()
LayerList defaultLayers ()
void deleteItem (ItemBase *, bool deleteModelPart, bool doEmit, bool later)
void drawBackground (QPainter *painter, const QRectF &rect)
bool ensureFilePath (const QString &filePath)
void ensureFixedToBottomLeft (QGraphicsItem *item)
void ensureFixedToBottomLeftItems ()
void ensureFixedToBottomRight (QGraphicsItem *item)
void ensureFixedToBottomRightItems ()
void ensureFixedToCenter (QGraphicsItem *item)
void ensureFixedToCenterItems ()
void ensureFixedToTopLeft (QGraphicsItem *item)
void ensureFixedToTopLeftItems ()
void ensureFixedToTopRight (QGraphicsItem *item)
void ensureFixedToTopRightItems ()
void findConnectorsLayerId ()
QString findConnectorsLayerId (QDomDocument *svgDom)
bool findConnectorsLayerIdAux (QString &result, QDomElement &docElem, QStringList &prevLayers)
QStringList findConnectorsLayerIds (QDomDocument *svgDom)
void findConnectorsLayerIdsAux (QStringList &result, QDomElement &docElem)
double fixedItemHeight (QGraphicsItem *item)
double fixedItemWidth (QGraphicsItem *item)
bool fixFonts (QString &fileContent, const QString &filename, bool &canceled)
bool fixUnavailableFontFamilies (QString &fileContent, const QString &filename, bool &canceled)
QSet< QString > getAttrFontFamilies (const QString &fileContent)
const QHash< QString, ConnectorTerminalSvgIdPair > getConnectorsSvgIds (const QString &path)
void getConnectorsSvgIdsAux (QDomElement &docElem)
QSet< QString > getFontFamiliesInsideStyleTag (const QString &fileContent)
QString getLayerFileName (ModelPart *modelPart)
const QStringList getLayers (const QString &path)
const QStringList getLayers (const QDomDocument *dom, bool fakeDefaultIfNone=true)
QString getOrCreateViewFolderInTemp ()
bool isSupposedToBeRemoved (const QString &id)
QRectF mapFromSceneToSvg (const QRectF &sceneRect, const QSizeF &defaultSize, const QRectF &viewBox)
void mouseMoveEvent (QMouseEvent *event)
void mousePressEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
PartsEditorPaletteItem * newPartsEditorPaletteItem (ModelPart *modelPart)
PartsEditorPaletteItem * newPartsEditorPaletteItem (ModelPart *modelPart, SvgAndPartFilePath *path)
void removeConnectors ()
bool removeConnectorsIfNeeded (QDomElement &docEle)
bool removeFontFamilySingleQuotes (QString &fileContent, const QString &filename)
void removeIfFixedPos (QGraphicsItem *item)
void removeTerminalPoints (const QStringList &tpIdsToRemove, QDomElement &docElem)
void resizeEvent (QResizeEvent *event)
QString saveSvg (const QString &svg, const QString &newFilePath)
void setDefaultBackground ()
QString setFriendlierSvgFileName (const QString &partFileName)
void setItemProperties ()
void setSvgFilePath (const QString &filePath)
QString svgIdForConnector (Connector *conn, const QString &connId)
bool terminalIdForConnectorIdAux (QString &result, const QString &connId, QDomElement &docElem, bool wantTerminal)
void updateSvgIdLayer (const QString &connId, const QString &terminalId, const QString &connectorsLayerId)
bool updateTerminalPoints (QDomDocument *svgDom, const QSizeF &sceneViewBox, const QRectF &svgViewBox, const QString &connectorsLayerId)
void wheelEvent (QWheelEvent *event)
Protected Member Functions inherited from SketchWidget
virtual bool acceptsTrace (const ViewGeometry &)
virtual PaletteItem * addPartItem (ModelPart *, ViewLayer::ViewLayerPlacement, PaletteItem *, bool doConnectors, bool &ok, ViewLayer::ViewID, bool temporary)
void addToScene (ItemBase *item, ViewLayer::ViewLayerID viewLayerID)
void addViewLayersAux (const LayerList &, const LayerList &layersFromBelow, float startZ=1.5)
void addWireExtras (long newID, QDomElement &view, QUndoCommand *parentCommand)
void alignLoc (QPointF &loc, const QPointF startPoint, const QPointF newLoc, const QPointF originalLoc)
QPointF calcNewLoc (ItemBase *moveBase, ItemBase *detachFrom)
virtual bool canAlignToCenter (ItemBase *)
virtual bool canAlignToTopLeft (ItemBase *)
virtual bool canChainMultiple ()
virtual bool canChainWire (Wire *)
bool canConnect (ItemBase *from, ItemBase *to)
virtual bool canConnect (Wire *from, ItemBase *to)
virtual bool canCreateWire (Wire *dragWire, ConnectorItem *from, ConnectorItem *to)
virtual bool canDragWire (Wire *)
virtual bool canDropModelPart (ModelPart *)
void categorizeDragLegs (bool rubberBandLegEnabled)
void categorizeDragWires (QSet< Wire * > &wires, QList< ItemBase * > &freeWires)
void changeConnectionAux (long fromID, const QString &fromConnectorID, long toID, const QString &toConnectorID, ViewLayer::ViewLayerPlacement, bool connect, bool updateConnections)
void changeLegAux (long fromID, const QString &fromConnectorID, const QPolygonF &, bool reset, bool relative, bool active, const QString &why)
bool checkAutoscroll (QPoint globalPos)
virtual QString checkDroppedModuleID (const QString &moduleID)
void checkFit (ModelPart *newModelPart, ItemBase *itemBase, long newID, QHash< ConnectorItem *, Connector * > &found, QList< ConnectorItem * > &notFound, QHash< ConnectorItem *, ConnectorItem * > &m2f, QHash< ConnectorItem *, Connector * > &byWire, QHash< QString, QPolygonF > &legs, QHash< QString, ConnectorItem * > &formerLegs, QUndoCommand *parentCommand)
void checkFitAux (ItemBase *tempItemBase, ItemBase *itemBase, long newID, QHash< ConnectorItem *, Connector * > &found, QList< ConnectorItem * > &notFound, QHash< ConnectorItem *, ConnectorItem * > &m2f, QHash< ConnectorItem *, Connector * > &byWire, QHash< QString, QPolygonF > &legs, QHash< QString, ConnectorItem * > &formerLegs, QUndoCommand *parentCommand)
bool checkMoved (bool wait)
virtual bool checkUnder ()
bool checkUpdateRatsnest (QList< ConnectorItem * > &connectorItems)
void cleanupRatsnests (QList< QPointer< ConnectorItem > > &connectorItems, bool connect)
void clearDragWireTempCommand ()
void clearHoldingSelectItem ()
void clearTemporaries ()
void clickBackground (QMouseEvent *)
virtual bool collectFemaleConnectees (ItemBase *, QSet< ItemBase * > &)
QList< ItemBase * > collectSuperSubs (ItemBase *)
void contextMenuEvent (QContextMenuEvent *)
void continueZChange (QList< ItemBase * > &bases, int start, int end, bool(*test)(int current, int start), int inc, const QString &text)
void continueZChangeAux (QList< ItemBase * > &bases, const QString &text)
void continueZChangeMax (QList< ItemBase * > &bases, int start, int end, bool(*test)(int current, int start), int inc, const QString &text)
void copyAux (QList< ItemBase * > &bases, bool saveBoundingRects)
void copyDrop ()
bool createOneTrace (Wire *wire, ViewGeometry::WireFlag flag, bool allowAny, QList< Wire * > &done, bool useLastWireColor, QUndoCommand *parentCommand)
virtual Wire * createTempWireForDragging (Wire *fromWire, ModelPart *wireModel, ConnectorItem *connectorItem, ViewGeometry &viewGeometry, ViewLayer::ViewLayerPlacement)
void createTrace (Wire *fromWire, const QString &commandString, ViewGeometry::WireFlag, bool useLastWireColor)
virtual ViewLayer::ViewLayerPlacement createWireViewLayerPlacement (ConnectorItem *from, ConnectorItem *to)
bool currentlyInfoviewed (ItemBase *item)
void cutDeleteAux (QString undoStackMessage, bool minus, Wire *wire)
void deleteAux (QSet< ItemBase * > &deletedItems, QUndoCommand *parentCommand, bool doPush)
virtual bool disconnectFromFemale (ItemBase *item, QHash< long, ItemBase * > &savedItems, ConnectorPairHash &, bool doCommand, bool rubberBandLegEnabled, QUndoCommand *parentCommand)
void dragEnterEvent (QDragEnterEvent *)
bool dragEnterEventAux (QDragEnterEvent *)
bool draggingWireEnd ()
void dragLeaveEvent (QDragLeaveEvent *)
void dragMoveEvent (QDragMoveEvent *)
void dragMoveHighlightConnector (QPoint eventPos)
void dragRatsnestChanged ()
void dragWireChanged (class Wire *wire, ConnectorItem *from, ConnectorItem *to)
void drawBackground (QPainter *painter, const QRectF &rect)
void dropEvent (QDropEvent *)
void dropItemEvent (QDropEvent *event)
ChangeConnectionCommand * extendChangeConnectionCommand (BaseCommand::CrossViewType, long fromID, const QString &fromConnectorID, long toID, const QString &toConnectorID, ViewLayer::ViewLayerPlacement, bool connect, QUndoCommand *parent)
ChangeConnectionCommand * extendChangeConnectionCommand (BaseCommand::CrossViewType, ConnectorItem *fromConnectorItem, ConnectorItem *toConnectorItem, ViewLayer::ViewLayerPlacement, bool connect, QUndoCommand *parentCommand)
virtual void extraRenderSvgStep (ItemBase *, QPointF offset, double dpi, double printerScale, QString &outputSvg)
virtual void findAlignmentAnchor (ItemBase *originatingItem, QHash< long, ItemBase * > &savedItems, QHash< Wire *, ConnectorItem * > &savedWires)
ConnectorItem * findConnectorItem (ItemBase *item, const QString &connectorID, ViewLayer::ViewLayerPlacement)
virtual void findConnectorsUnder (ItemBase *item)
long findPartOrWire (long itemID)
QGraphicsItem * getClickedItem (QList< QGraphicsItem * > &items)
ViewLayer::ViewLayerID getConnectorViewLayerID ()
virtual ViewLayer::ViewLayerID getDragWireViewLayerID (ConnectorItem *)
virtual ViewLayer::ViewLayerID getLabelViewLayerID (ItemBase *)
ViewLayer::ViewLayerID getNoteViewLayerID ()
ViewLayer::ViewLayerID getPartViewLayerID ()
ViewLayer::ViewLayerID getRulerViewLayerID ()
virtual double getTraceWidth ()
ViewLayer::ViewLayerID getViewLayerID (ModelPart *, ViewLayer::ViewID, ViewLayer::ViewLayerPlacement)
virtual ViewLayer::ViewLayerPlacement getViewLayerPlacement (ModelPart *, QDomElement &instance, QDomElement &view, ViewGeometry &)
double gridSizeInches ()
void handleConnect (QDomElement &connect, ModelPart *, const QString &fromConnectorID, ViewLayer::ViewLayerID, QStringList &alreadyConnected, QHash< long, ItemBase * > &newItems, QUndoCommand *parentCommand, bool seekOutsideConnections)
virtual const QString & hoverEnterPartConnectorMessage (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
virtual const QString & hoverEnterWireConnectorMessage (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
void initBackgroundColor ()
void keyPressEvent (QKeyEvent *)
void keyReleaseEvent (QKeyEvent *)
void killDroppingItem ()
QString makeMoveSVG (double printerScale, double dpi, QPointF &offset)
void makeRatsnestViewGeometry (ViewGeometry &viewGeometry, ConnectorItem *source, ConnectorItem *dest)
void makeSwapWire (SketchWidget *, ItemBase *, long newID, ConnectorItem *fromConnectorItem, ConnectorItem *toConnectorItem, Connector *newConnector, QUndoCommand *parentCommand)
QString makeWireSVG (Wire *wire, QPointF offset, double dpi, double printerscale, bool blackOnly)
QString makeWireSVGAux (Wire *wire, double width, const QString &color, QPointF offset, double dpi, double printerScale, bool blackOnly, bool dashed)
bool matchesLayer (ModelPart *modelPart)
void mouseDoubleClickEvent (QMouseEvent *)
void mouseMoveEvent (QMouseEvent *)
void mouseReleaseEvent (QMouseEvent *)
bool moveByArrow (double dx, double dy, QKeyEvent *)
void moveItems (QPoint globalPos, bool checkAutoScroll, bool rubberBandLegEnabled)
void moveLegBendpoints (bool undoOnly, QUndoCommand *parentCommand)
void moveLegBendpointsAux (ConnectorItem *connectorItem, bool undoOnly, QUndoCommand *parentCommand)
virtual ViewLayer::ViewLayerID multiLayerGetViewLayerID (ModelPart *modelPart, ViewLayer::ViewID, ViewLayer::ViewLayerPlacement, LayerList &)
AddItemCommand * newAddItemCommand (BaseCommand::CrossViewType crossViewType, ModelPart *, QString moduleID, ViewLayer::ViewLayerPlacement, ViewGeometry &viewGeometry, qint64 id, bool updateInfoView, long modelIndex, bool addSubparts, QUndoCommand *parent)
ItemBase * overSticky (ItemBase *)
void paintEvent (QPaintEvent *)
void partLabelChangedAux (ItemBase *pitem, const QString &oldText, const QString &newText)
virtual ItemBase * placePartDroppedInOtherView (ModelPart *, ViewLayer::ViewLayerPlacement, const ViewGeometry &viewGeometry, long id, SketchWidget *dropOrigin)
void prepDeleteOtherProps (ItemBase *itemBase, long id, const QString &newModuleID, QMap< QString, QString > &propsMap, QUndoCommand *parentCommand)
void prepDeleteProps (ItemBase *itemBase, long id, const QString &newModuleID, QMap< QString, QString > &propsMap, QUndoCommand *parentCommand)
void prepDragBendpoint (Wire *, QPoint eventPos, bool dragCurve)
void prepDragWire (Wire *)
void prepMove (ItemBase *originatingItem, bool rubberBandLegEnabled, bool includeRatsnest)
virtual void prereleaseTempWireForDragging (Wire *)
void removeDragWire ()
QByteArray removeOutsideConnections (const QByteArray &itemData, QList< long > &modelIndexes)
void removeWire (Wire *w, QList< ConnectorItem * > &ends, QList< Wire * > &done, QUndoCommand *parentCommand)
QString renderToSVG (RenderThing &, const LayerList &)
QString renderToSVG (RenderThing &, QList< QGraphicsItem * > &itemsAndLabels)
void resizeBoard ()
void resizeEvent (QResizeEvent *)
void resizeWithHandle (ItemBase *itemBase, double mmW, double mmH)
bool resizingBoardPress (ItemBase *)
bool resizingBoardRelease ()
virtual bool resizingJumperItemPress (ItemBase *)
virtual bool resizingJumperItemRelease ()
virtual void rotatePartLabels (double degrees, QTransform &, QPointF center, QUndoCommand *parentCommand)
void rotateWire (Wire *, QTransform &rotation, QPointF center, bool undoOnly, QUndoCommand *parentCommand)
int selectAllItems (QSet< ItemBase * > &itemBases, const QString &msg)
void selectAllWiresFrom (ViewGeometry::WireFlag flag, QList< QGraphicsItem * > &items)
void setLastPaletteItemSelected (PaletteItem *paletteItem)
void setLastPaletteItemSelectedIf (ItemBase *itemBase)
virtual void setNewPartVisible (ItemBase *)
void setupAutoscroll (bool moving)
virtual void setUpColor (ConnectorItem *fromConnectorItem, ConnectorItem *toConnectorItem, Wire *wire, QUndoCommand *parentCommand)
void setUpSwapReconnect (SwapThing &, ItemBase *itemBase, long newID, bool master)
virtual void setWireVisible (Wire *)
void showPartLabelsAux (bool show, QList< ItemBase * > &itemBases)
void squashShapes (QPointF scenePos)
bool startZChange (QList< ItemBase * > &bases)
bool swappedGender (ConnectorItem *originalConnectorItem, Connector *newConnector)
virtual const QString & traceColor (ViewLayer::ViewLayerPlacement)
void turnOffAutoscroll ()
void unsquashShapes ()
virtual bool updateOK (ConnectorItem *, ConnectorItem *)
virtual void viewGeometryConversionHack (ViewGeometry &, ModelPart *)
bool viewportEvent (QEvent *)
virtual BaseCommand::CrossViewType wireSplitCrossView ()
virtual ViewLayer::ViewLayerPlacement wireViewLayerPlacement (ConnectorItem *)
Protected Member Functions inherited from InfoGraphicsView
QGraphicsItem * selectedAux ()
Protected Attributes
ViewLayer::ViewLayerID m_connsLayerID
bool m_deleteModelPartOnSceneClear
QHash< QString,PartsEditorConnectorsConnectorItem * > m_drawnConns
QTimer * m_fitItemInViewTimer
QList< QGraphicsItem * > m_fixedToBottomLeftItems
QList< QGraphicsItem * > m_fixedToBottomRightItems
QList< QGraphicsItem * > m_fixedToCenterItems
QList< QGraphicsItem * > m_fixedToTopLeftItems
QList< QGraphicsItem * > m_fixedToTopRightItems
QList< QWidget * > m_fixedWidgets
QPointer< PartsEditorPaletteItem > m_item
QString m_lastSelectedConnId
QString m_originalSvgFilePath
PaletteModel * m_paletteModel
QStringList m_removedConnIds
bool m_showingTerminalPoints
bool m_showingTerminalPointsBackup
QPointer< QGraphicsProxyWidget > m_startItem
SvgAndPartFilePath * m_svgFilePath
QHash< QString, ConnectorTerminalSvgIdPair > m_svgIds
bool m_svgLoaded
QDir m_tempFolder
QTimer * m_terminalPointsTimer
ItemBase * m_viewItem
Protected Attributes inherited from SketchWidget
bool m_addDefaultParts = false
QPointer< ItemBase > m_addedDefaultPart
QList< ItemBase * > m_additionalSavedItems
QPointer< ItemBase > m_alignmentItem
QPointF m_alignmentStartPoint
bool m_alignToGrid = true
bool m_anyInRotation
QTimer m_arrowTimer
double m_arrowTotalX = 0.0
double m_arrowTotalY = 0.0
volatile int m_autoScrollCount = 0
int m_autoScrollThreshold = 0
QTimer m_autoScrollTimer
volatile int m_autoScrollX = 0
volatile int m_autoScrollY = 0
ViewGeometry m_bendpointVG
QPointer< Wire > m_bendpointWire
bool m_chainDrag = false
QList< ItemBase * > m_checkUnder
bool m_clearSceneRect = false
QPointer< ConnectorItem > m_connectorDragConnector
QPointer< Wire > m_connectorDragWire
ViewLayer::ViewLayerID m_connectorViewLayerID
bool m_current = false
bool m_curvyWires = false
QPoint m_dragBendpointPos
QPointer< Wire > m_dragBendpointWire
bool m_dragCurve = false
bool m_draggingBendpoint = false
QPointer< ItemBase > m_droppingItem
QPointF m_droppingOffset
bool m_droppingWire = false
bool m_everZoomed = false
QPoint m_globalPos
QColor m_gridColor
double m_gridSizeInches = 0.0
QString m_gridSizeText
class SelectItemCommand * m_holdingSelectItemCommand = nullptr
int m_ignoreSelectionChangeEvents = 0
QList< QGraphicsItem * > m_inFocus
bool m_infoViewOnHover
QMenu * m_itemMenu = nullptr
QString m_lastColorSelected
QPointer< ConnectorItem > m_lastHoverEnterConnectorItem
QPointer< ItemBase > m_lastHoverEnterItem
QPointer< PaletteItem > m_lastPaletteItemSelected
bool m_middleMouseIsPressed = false
QPointF m_mousePressGlobalPos
QPointF m_mousePressScenePos
ConnectorPairHash m_moveDisconnectedFromFemale
int m_moveEventCount = 0
QPointer< ItemBase > m_moveReferenceItem
bool m_movingByArrow = false
bool m_movingByMouse = false
QPointer< QGraphicsSvgItem > m_movingItem
QPointF m_movingSVGOffset
QPointer< QSvgRenderer > m_movingSVGRenderer
ViewLayer::ViewLayerID m_noteViewLayerID
QPointer< ItemBase > m_originatingItem
ViewLayer::ViewLayerID m_partViewLayerID
int m_pasteCount = 0
QPointF m_pasteOffset
bool m_pasting = false
QList< QPointer< ConnectorItem > > m_ratsnestCacheConnect
QList< QPointer< ConnectorItem > > m_ratsnestCacheDisconnect
double m_ratsnestOpacity = 0.0
QList< QPointer< ConnectorItem > > m_ratsnestUpdateConnect
QList< QPointer< ConnectorItem > > m_ratsnestUpdateDisconnect
double m_ratsnestWidth = 0.0
QPointer< class ReferenceModel > m_referenceModel
QPointer< class ResizableBoard > m_resizingBoard
RoutingStatus m_routingStatus
bool m_rubberBandLegWasEnabled = false
ViewLayer::ViewLayerID m_rulerViewLayerID
QHash< long, ItemBase * > m_savedItems
QHash< Wire *, ConnectorItem * > m_savedWires
QString m_shortName
bool m_showGrid = true
QPointer< SizeItem > m_sizeItem
QPointer< SketchModel > m_sketchModel
bool m_spaceBarIsPressed = false
bool m_spaceBarWasPressed = false
QList< QPointer< ItemBase > > m_squashShapes
StatusConnectStatus m_statusConnectState = StatusConnectNotTried
QMultiHash< ItemBase *, ConnectorItem * > m_stretchingLegs
class SelectItemCommand * m_tempDragWireCommand = nullptr
QList< QGraphicsItem * > m_temporaries
class WaitPushUndoStack * m_undoStack = nullptr
ViewLayer::ViewID m_viewID
LayerHash m_viewLayers
QHash< ViewLayer::ViewLayerID, bool > m_viewLayerVisibility
QString m_viewName
QMenu * m_wireMenu = nullptr
ViewLayer::ViewLayerID m_wireViewLayerID
float m_z
double m_zoom = 100
Protected Attributes inherited from InfoGraphicsView
int m_boardLayers
bool m_hoverEnterConnectorMode
bool m_hoverEnterMode
class HtmlInfoView * m_infoView
Qt::Orientations m_smdOrientation
Protected Attributes inherited from ZoomableGraphicsView
bool m_acceptWheelEvents
int m_maxScaleValue
int m_minScaleValue
double m_scaleValue
bool m_viewFromBelow
Static Protected Attributes
static int ConnDefaultHeight = ConnDefaultWidth
static int ConnDefaultWidth = 5
Static Protected Attributes inherited from SketchWidget
static constexpr int DragAutoScrollThreshold = 10
static constexpr int MoveAutoScrollThreshold = 5
Static Protected Attributes inherited from ZoomableGraphicsView
static WheelMapping m_wheelMapping
Additional Inherited Members
Public Types inherited from ZoomableGraphicsView
enum WheelMapping { ScrollPrimary, ZoomPrimary, WheelMappingCount }
Static Public Member Functions inherited from SketchWidget
static ViewLayer::ViewLayerID defaultConnectorLayer (ViewLayer::ViewID viewId)
Static Public Member Functions inherited from InfoGraphicsView
static InfoGraphicsView * getInfoGraphicsView (QGraphicsItem *)
Static Public Member Functions inherited from ZoomableGraphicsView
static void setWheelMapping (WheelMapping)
static WheelMapping wheelMapping ()
Static Public Attributes inherited from SketchWidget
static bool m_blockUI = false
static constexpr int PropChangeDelay = 100
Static Public Attributes inherited from ZoomableGraphicsView
static const int MaxScaleValue = 3000
Protected Types inherited from SketchWidget
enum StatusConnectStatus { StatusConnectNotTried, StatusConnectSucceeded, StatusConnectFailed }
Static Protected Member Functions inherited from SketchWidget
static bool greaterThan (int a, int b)
static bool lessThan (int a, int b)
Properties inherited from SketchWidget
QColor gridColor
double ratsnestOpacity
double ratsnestWidth
Constructor & Destructor Documentation
PartsEditorView()
PartsEditorView::PartsEditorView (ViewLayer::ViewIdentifier viewId, QDir tempDir, bool showingTerminalPoints, QGraphicsProxyWidget * startItem = 0, QWidget * parent = 0, int size = 150, bool deleteModelPartOnClearScene = false, class ItemBase * fromItem = NULL)
References addDefaultLayers(), addFixedToCenterItem(), ensureFixedItemsPositions(), ensureFixedToCenterItems(), fitCenterAndDeselect(), SketchWidget::m_alignToGrid, m_connsLayerID, m_deleteModelPartOnSceneClear, m_fitItemInViewTimer, m_item, m_lastSelectedConnId, SketchWidget::m_showGrid, m_showingTerminalPoints, m_showingTerminalPointsBackup, m_startItem, m_svgFilePath, m_svgLoaded, m_tempFolder, m_terminalPointsTimer, m_viewItem, recoverTerminalPointsState(), SketchWidget::resizeSignal(), setDefaultBackground(), showingTerminalPoints(), ViewLayer::UnknownLayer, and ZoomableGraphicsView::wheelSignal().
~PartsEditorView()
PartsEditorView::~PartsEditorView ()
References clearScene(), m_startItem, and m_svgFilePath.
Member Function Documentation
aboutToSave()
void PartsEditorView::aboutToSave (bool fakeDefaultIfNotIn)
References addConnectorsIfNeeded(), addDefaultLayerIfNotInSvg(), connectorsLayerId(), DebugDialog::debug(), FSvgRenderer::defaultSizeF(), ensureFilePath(), findConnectorsLayerIds(), getOrCreateViewFolderInTemp(), FSvgRenderer::loadSvg(), m_item, m_tempFolder, m_viewItem, removeConnectorsIfNeeded(), TextUtils::removeXMLEntities(), updateTerminalPoints(), and TextUtils::writeUtf8().
addConnectorsIfNeeded()
bool PartsEditorView::addConnectorsIfNeeded (QDomDocument * svgDom, const QSizeF & sceneViewBox, const QRectF & svgViewBox, const QString & connectorsLayerId) protected
References addRectToSvg(), connectorsLayerId(), m_drawnConns, mapFromSceneToSvg(), and svgIdForConnector().
addDefaultLayerIfNotInSvg()
bool PartsEditorView::addDefaultLayerIfNotInSvg (QDomDocument * svgDom, bool fakeDefaultIfNone) protected
References defaultLayerAsStringlist(), defaultLayers(), getLayers(), and layers().
addDefaultLayers()
void PartsEditorView::addDefaultLayers (class ItemBase * fromItem) protected
References ViewLayer::BreadboardView, ViewLayer::Copper0, ViewLayer::Copper0Trace, ViewLayer::Copper1, ViewLayer::Copper1Trace, DebugDialog::debug(), ModelPart::flippedSMD(), SketchWidget::m_viewLayers, ItemBase::modelPart(), ViewLayer::PcbNote, ViewLayer::PcbRuler, ViewLayer::PCBView, ViewLayer::SchematicView, SketchWidget::setViewLayerIDs(), ViewLayer::Silkscreen0, and ViewLayer::Silkscreen1.
addFixedToBottomLeftItem()
void PartsEditorView::addFixedToBottomLeftItem (QGraphicsItem * item) protected
References ensureFixedToBottomLeft(), and m_fixedToBottomLeftItems.
addFixedToBottomRight()
void PartsEditorView::addFixedToBottomRight (QWidget * widget)
References addFixedToBottomRightItem(), and m_fixedWidgets.
addFixedToBottomRightItem()
void PartsEditorView::addFixedToBottomRightItem (QGraphicsItem * item) protected
References ensureFixedToBottomRight(), and m_fixedToBottomRightItems.
addFixedToCenterItem()
void PartsEditorView::addFixedToCenterItem (QGraphicsItem * item) protected
References ensureFixedToCenter(), and m_fixedToCenterItems.
addFixedToTopLeftItem()
void PartsEditorView::addFixedToTopLeftItem (QGraphicsItem * item) protected
References ensureFixedToTopLeft(), and m_fixedToTopLeftItems.
addFixedToTopRightItem()
void PartsEditorView::addFixedToTopRightItem (QGraphicsItem * item) protected
References ensureFixedToTopRight(), and m_fixedToTopRightItems.
addItemAux()
ItemBase * PartsEditorView::addItemAux (ModelPart * modelPart, ViewLayer::ViewLayerSpec viewLayerSpec, const ViewGeometry & viewGeometry, long id, PaletteItem * paletteItem, bool doConnectors, ViewLayer::ViewIdentifier , bool temporary) protected
References addDefaultLayers(), SketchWidget::addToScene(), findConnectorsLayerId(), getLayerFileName(), SketchWidget::getViewLayerID(), ModelPart::initConnectors(), m_viewItem, SketchWidget::m_viewLayers, TextUtils::makeSVGHeader(), newPartsEditorPaletteItem(), ModelPart::path(), ItemBase::retrieveSvg(), ItemBase::size(), GraphicsUtils::StandardFritzingDPI, GraphicsUtils::SVGDPI, ViewLayer::UnknownLayer, ItemBase::viewLayerID(), ViewLayer::viewLayerID(), and ViewLayer::viewLayerIDFromXmlString().
addItemInPartsEditor
void PartsEditorView::addItemInPartsEditor (ModelPart * modelPart, SvgAndPartFilePath * svgFilePath) slot
References SketchWidget::addItem(), clearScene(), connectorsFoundSignal(), BaseCommand::CrossView, fitCenterAndDeselect(), m_item, newPartsEditorPaletteItem(), setItemProperties(), and svgFilePath().
addNewTerminalPoints()
void PartsEditorView::addNewTerminalPoints (const QList< PartsEditorConnectorsConnectorItem * > & connsWithNewTPs, QDomDocument * svgDom, const QSizeF & sceneViewBox, const QRectF & svgViewBox, const QString & connectorsLayerId) protected
References addRectToSvg(), connectorsLayerId(), and mapFromSceneToSvg().
addRectToSvg()
bool PartsEditorView::addRectToSvg (QDomDocument * svgDom, const QString & id, const QRectF & rect, const QString & connectorsLayerId) protected
References addRectToSvgAux(), and connectorsLayerId().
addRectToSvgAux()
bool PartsEditorView::addRectToSvgAux (QDomElement & docElem, const QString & connectorsLayerId, QDomElement & rectElem) protected
References connectorsLayerId().
beforeSVGLoading()
void PartsEditorView::beforeSVGLoading (const QString & filename, bool & canceled) protected
References TextUtils::cleanSodipodi(), fixFonts(), TextUtils::fixPixelDimensionsIn(), ViewLayer::IconView, and TextUtils::writeUtf8().
checkConnectorLayers
void PartsEditorView::checkConnectorLayers (ViewLayer::ViewIdentifier viewIdentifier, const QString & connId, Connector * existingConnector, Connector * newConnector) slot
References Connector::connectorShared(), SvgIdLayer::copyLayer(), ConnectorShared::insertPin(), SvgIdLayer::m_svgViewLayerID, ConnectorShared::pins(), and ConnectorShared::removePin().
clearFixedItems()
void PartsEditorView::clearFixedItems () protected
References m_fixedToBottomLeftItems, m_fixedToBottomRightItems, m_fixedToCenterItems, m_fixedToTopLeftItems, and m_fixedToTopRightItems.
clearScene()
void PartsEditorView::clearScene () protected
References deleteItem(), m_deleteModelPartOnSceneClear, and m_item.
connectItem()
void PartsEditorView::connectItem () protected
connectorSelected
void PartsEditorView::connectorSelected (const QString & connId) signal
connectorsFoundSignal
void PartsEditorView::connectorsFoundSignal (ViewLayer::ViewIdentifier viewId, const QList< QPointer< Connector > > & conns) signal
connectorsLayerId()
ViewLayer::ViewLayerID PartsEditorView::connectorsLayerId ()
References findConnectorsLayerId(), and m_connsLayerID.
connsPosOrSizeChanged()
bool PartsEditorView::connsPosOrSizeChanged ()
copySvgFileToDestiny()
void PartsEditorView::copySvgFileToDestiny (const QString & partFileName)
References DebugDialog::debug(), ensureFilePath(), m_svgFilePath, m_tempFolder, setFriendlierSvgFileName(), and svgFilePath().
copyToTempAndRenameIfNecessary()
void PartsEditorView::copyToTempAndRenameIfNecessary (SvgAndPartFilePath * filePathOrig) protected
References DebugDialog::debug(), ensureFilePath(), PartFactory::folderPath(), FolderUtils::getApplicationSubFolderPath(), m_originalSvgFilePath, m_svgFilePath, and m_tempFolder.
createConnector()
void PartsEditorView::createConnector (Connector * conn, const QSize & connSize, bool showTerminalPoint) protected
References Connector::connectorSharedID(), m_drawnConns, m_item, m_showingTerminalPoints, SketchWidget::m_undoStack, and WaitPushUndoStack::push().
createFakeModelPart() [1/2]
ModelPart * PartsEditorView::createFakeModelPart (SvgAndPartFilePath * svgpath) protected
References getConnectorsSvgIds(), getLayers(), and layers().
createFakeModelPart() [2/2]
ModelPart * PartsEditorView::createFakeModelPart (const QHash< QString, ConnectorTerminalSvgIdPair > & connIds, const QStringList & layers, const QString & svgFilePath) protected
References defaultLayerAsStringlist(), defaultLayers(), ModelPart::initConnectors(), layers(), SketchWidget::m_sketchModel, m_tempFolder, ModelPart::modelPartShared(), ModelPartShared::setDomDocument(), ModelPartShared::setPath(), svgFilePath(), and TextUtils::writeUtf8().
createSvgFromImage()
QString PartsEditorView::createSvgFromImage (const QString & filePath) protected
References GedaElement2Svg::convert(), KicadModule2Svg::convert(), KicadSchematic2Svg::convert(), ensureFilePath(), getOrCreateViewFolderInTemp(), KicadSchematic2Svg::listDefs(), KicadModule2Svg::listModules(), m_tempFolder, saveSvg(), and KicadModuleDialog::selectedModule().
defaultLayerAsStringlist()
QStringList PartsEditorView::defaultLayerAsStringlist () protected
References defaultLayers(), layers(), and ViewLayer::viewLayerXmlNameFromID().
defaultLayers()
LayerList PartsEditorView::defaultLayers () protected
References ViewLayer::Breadboard, ViewLayer::BreadboardView, ViewLayer::Copper0, ViewLayer::Copper1, ViewLayer::Icon, ViewLayer::IconView, layers(), ViewLayer::PCBView, ViewLayer::Schematic, ViewLayer::SchematicView, and ViewLayer::UnknownLayer.
deleteItem()
void PartsEditorView::deleteItem (ItemBase * itemBase, bool deleteModelPart, bool doEmit, bool later) protected virtual
Reimplemented from SketchWidget.
References SketchWidget::deleteItem(), and removeIfFixedPos().
drawBackground()
void PartsEditorView::drawBackground (QPainter * painter, const QRectF & rect) protected
References SketchWidget::drawBackground().
drawConector()
void PartsEditorView::drawConector (Connector * conn, bool showTerminalPoint)
References ConnDefaultHeight, ConnDefaultWidth, and createConnector().
ensureFilePath()
bool PartsEditorView::ensureFilePath (const QString & filePath) protected
References m_tempFolder.
ensureFixedItemsPositions
void PartsEditorView::ensureFixedItemsPositions () protected slot
References ensureFixedToBottomLeftItems(), ensureFixedToBottomRightItems(), ensureFixedToCenterItems(), ensureFixedToTopLeftItems(), and ensureFixedToTopRightItems().
ensureFixedToBottomLeft()
void PartsEditorView::ensureFixedToBottomLeft (QGraphicsItem * item) protected
References fixedItemHeight(), and int().
ensureFixedToBottomLeftItems()
void PartsEditorView::ensureFixedToBottomLeftItems () protected
References ensureFixedToBottomLeft(), and m_fixedToBottomLeftItems.
ensureFixedToBottomRight()
void PartsEditorView::ensureFixedToBottomRight (QGraphicsItem * item) protected
References fixedItemHeight(), fixedItemWidth(), and int().
ensureFixedToBottomRightItems()
void PartsEditorView::ensureFixedToBottomRightItems () protected virtual
Reimplemented from ZoomableGraphicsView.
References ensureFixedToBottomRight(), and m_fixedToBottomRightItems.
ensureFixedToCenter()
void PartsEditorView::ensureFixedToCenter (QGraphicsItem * item) protected
References fixedItemHeight(), and fixedItemWidth().
ensureFixedToCenterItems()
void PartsEditorView::ensureFixedToCenterItems () protected
References ensureFixedToCenter(), and m_fixedToCenterItems.
ensureFixedToTopLeft()
void PartsEditorView::ensureFixedToTopLeft (QGraphicsItem * item) protected
ensureFixedToTopLeftItems()
void PartsEditorView::ensureFixedToTopLeftItems () protected
References ensureFixedToTopLeft(), and m_fixedToTopLeftItems.
ensureFixedToTopRight()
void PartsEditorView::ensureFixedToTopRight (QGraphicsItem * item) protected
References fixedItemWidth(), and int().
ensureFixedToTopRightItems()
void PartsEditorView::ensureFixedToTopRightItems () protected
References ensureFixedToTopRight(), and m_fixedToTopRightItems.
findConnectorsLayerId() [1/2]
void PartsEditorView::findConnectorsLayerId () protected
References SketchWidget::defaultConnectorLayer(), m_connsLayerID, m_item, ViewLayer::UnknownLayer, and ViewLayer::viewLayerIDFromXmlString().
findConnectorsLayerId() [2/2]
QString PartsEditorView::findConnectorsLayerId (QDomDocument * svgDom) protected
References defaultLayerAsStringlist(), findConnectorsLayerIdAux(), layers(), SketchWidget::m_viewLayers, ViewLayer::UnknownLayer, and ViewLayer::viewLayerIDFromXmlString().
findConnectorsLayerIdAux()
bool PartsEditorView::findConnectorsLayerIdAux (QString & result, QDomElement & docElem, QStringList & prevLayers) protected
findConnectorsLayerIds()
QStringList PartsEditorView::findConnectorsLayerIds (QDomDocument * svgDom) protected
References defaultLayerAsStringlist(), and findConnectorsLayerIdsAux().
findConnectorsLayerIdsAux()
void PartsEditorView::findConnectorsLayerIdsAux (QStringList & result, QDomElement & docElem) protected
References isEmpty(), ViewLayer::UnknownLayer, and ViewLayer::viewLayerIDFromXmlString().
fitCenterAndDeselect
void PartsEditorView::fitCenterAndDeselect () protected slot
References m_item, ZoomableGraphicsView::m_scaleValue, and ZoomableGraphicsView::zoomChanged().
fixedItemHeight()
double PartsEditorView::fixedItemHeight (QGraphicsItem * item) protected
fixedItemWidth()
double PartsEditorView::fixedItemWidth (QGraphicsItem * item) protected
fixFonts()
bool PartsEditorView::fixFonts (QString & fileContent, const QString & filename, bool & canceled) protected
References fixUnavailableFontFamilies(), and removeFontFamilySingleQuotes().
fixUnavailableFontFamilies()
bool PartsEditorView::fixUnavailableFontFamilies (QString & fileContent, const QString & filename, bool & canceled) protected
References DebugDialog::debug(), FixFontsDialog::fixFonts(), getAttrFontFamilies(), and getFontFamiliesInsideStyleTag().
getAttrFontFamilies()
QSet< QString > PartsEditorView::getAttrFontFamilies (const QString & fileContent) protected
References TextUtils::getRegexpCaptures().
getConnectorsSvgIds()
const QHash< QString, ConnectorTerminalSvgIdPair > PartsEditorView::getConnectorsSvgIds (const QString & path) protected
References getConnectorsSvgIdsAux(), and m_svgIds.
getConnectorsSvgIdsAux()
void PartsEditorView::getConnectorsSvgIdsAux (QDomElement & docElem) protected
References ConnectorTerminalSvgIdPair::connectorId, ConnectorTerminalSvgIdPair::connectorName, m_svgIds, and ConnectorTerminalSvgIdPair::terminalId.
getFontFamiliesInsideStyleTag()
QSet< QString > PartsEditorView::getFontFamiliesInsideStyleTag (const QString & fileContent) protected
References TextUtils::getRegexpCaptures().
getLayerFileName()
QString PartsEditorView::getLayerFileName (ModelPart * modelPart) protected
References ModelPart::imageFileName().
getLayers() [1/2]
const QStringList PartsEditorView::getLayers (const QString & path) protected
References defaultLayerAsStringlist(), and ViewLayer::IconView.
getLayers() [2/2]
const QStringList PartsEditorView::getLayers (const QDomDocument * dom, bool fakeDefaultIfNone = true) protected
References isEmpty(), ViewLayer::UnknownLayer, and ViewLayer::viewLayerIDFromXmlString().
getOrCreateViewFolderInTemp()
QString PartsEditorView::getOrCreateViewFolderInTemp () protected
References m_tempFolder.
imageLoaded()
bool PartsEditorView::imageLoaded ()
References m_item.
inFileDefinedConnectorChanged()
void PartsEditorView::inFileDefinedConnectorChanged (PartsEditorConnectorsConnectorItem * connItem)
References m_drawnConns, and m_removedConnIds.
informConnectorSelection
void PartsEditorView::informConnectorSelection (const QString & connId) slot
References m_item, m_lastSelectedConnId, and myItem().
informConnectorSelectionFromView
void PartsEditorView::informConnectorSelectionFromView (const QString & connId) slot
References connectorSelected(), and informConnectorSelection().
isEmpty()
bool PartsEditorView::isEmpty ()
References m_item.
isSupposedToBeRemoved()
bool PartsEditorView::isSupposedToBeRemoved (const QString & id) protected
References isEmpty(), and m_removedConnIds.
loadFile
void PartsEditorView::loadFile () slot
References createSvgFromImage(), FolderUtils::getOpenFileName(), loadSvgFile(), m_fixedToCenterItems, m_originalSvgFilePath, m_startItem, m_viewItem, FolderUtils::openSaveFolder(), ViewLayer::PCBView, and ViewLayer::SchematicView.
loadFromModel
void PartsEditorView::loadFromModel (PaletteModel * paletteModel, ModelPart * modelPart) slot
References addItemAux(), clearScene(), copyToTempAndRenameIfNecessary(), fitCenterAndDeselect(), ItemBase::getNextID(), m_fixedToCenterItems, m_item, m_startItem, m_svgFilePath, setItemProperties(), and setPaletteModel().
loadSvgFile() [1/2]
void PartsEditorView::loadSvgFile (ModelPart * modelPart)
References addItemInPartsEditor(), copyToTempAndRenameIfNecessary(), m_item, and m_svgFilePath.
loadSvgFile [2/2]
void PartsEditorView::loadSvgFile (const QString & origPath) slot
References beforeSVGLoading(), createFakeModelPart(), loadSvgFile(), m_connsLayerID, m_drawnConns, m_removedConnIds, m_svgFilePath, m_svgIds, m_svgLoaded, SketchWidget::m_undoStack, WaitPushUndoStack::push(), setSvgFilePath(), and ViewLayer::UnknownLayer.
mapFromSceneToSvg()
QRectF PartsEditorView::mapFromSceneToSvg (const QRectF & sceneRect, const QSizeF & defaultSize, const QRectF & viewBox) protected
mouseMoveEvent()
void PartsEditorView::mouseMoveEvent (QMouseEvent * event) protected
mousePressEvent()
void PartsEditorView::mousePressEvent (QMouseEvent * event) protected virtual
Reimplemented from SketchWidget.
References SketchWidget::mousePressEvent().
mouseReleaseEvent()
void PartsEditorView::mouseReleaseEvent (QMouseEvent * event) protected
References SketchWidget::mouseReleaseEvent().
myItem()
PartsEditorConnectorsPaletteItem * PartsEditorView::myItem ()
References m_item.
newPartsEditorPaletteItem() [1/2]
PartsEditorPaletteItem * PartsEditorView::newPartsEditorPaletteItem (ModelPart * modelPart) protected
newPartsEditorPaletteItem() [2/2]
PartsEditorPaletteItem * PartsEditorView::newPartsEditorPaletteItem (ModelPart * modelPart, SvgAndPartFilePath * path) protected
recoverTerminalPointsState
void PartsEditorView::recoverTerminalPointsState () protected slot
References m_showingTerminalPointsBackup, m_terminalPointsTimer, and showTerminalPoints().
removeConnector()
void PartsEditorView::removeConnector (const QString & connId)
References ConnectorItem::connector(), Connector::connectorSharedID(), m_drawnConns, m_removedConnIds, SketchWidget::m_undoStack, and WaitPushUndoStack::push().
removeConnectors()
void PartsEditorView::removeConnectors () protected
References m_item.
removeConnectorsIfNeeded()
bool PartsEditorView::removeConnectorsIfNeeded (QDomElement & docEle) protected
References isSupposedToBeRemoved(), and m_removedConnIds.
removeFontFamilySingleQuotes()
bool PartsEditorView::removeFontFamilySingleQuotes (QString & fileContent, const QString & filename) protected
References DebugDialog::debug(), and TextUtils::getRegexpCaptures().
removeIfFixedPos()
void PartsEditorView::removeIfFixedPos (QGraphicsItem * item) protected
References m_fixedToBottomLeftItems, m_fixedToBottomRightItems, m_fixedToCenterItems, m_fixedToTopLeftItems, and m_fixedToTopRightItems.
removeTerminalPoint
void PartsEditorView::removeTerminalPoint (const QString & connId, ViewLayer::ViewIdentifier vid) signal
removeTerminalPoints()
void PartsEditorView::removeTerminalPoints (const QStringList & tpIdsToRemove, QDomElement & docElem) protected
resizeEvent()
void PartsEditorView::resizeEvent (QResizeEvent * event) protected
References m_fitItemInViewTimer, and SketchWidget::resizeEvent().
saveSvg()
QString PartsEditorView::saveSvg (const QString & svg, const QString & newFilePath) protected
References TextUtils::writeUtf8().
setDefaultBackground()
void PartsEditorView::setDefaultBackground () protected
References SketchWidget::standardBackground().
setFriendlierSvgFileName()
QString PartsEditorView::setFriendlierSvgFileName (const QString & partFileName) protected
References FritzingPartExtension(), and m_svgFilePath.
setItemProperties()
void PartsEditorView::setItemProperties () protected
References m_item, m_lastSelectedConnId, and myItem().
setMismatching
void PartsEditorView::setMismatching (ViewLayer::ViewIdentifier viewId, const QString & id, bool mismatching) slot
References m_item.
setPaletteModel()
void PartsEditorView::setPaletteModel (PaletteModel * paletteModel)
References m_paletteModel.
setSvgFilePath()
void PartsEditorView::setSvgFilePath (const QString & filePath) protected
References ensureFilePath(), PartFactory::folderPath(), FolderUtils::getApplicationSubFolderPath(), m_originalSvgFilePath, m_svgFilePath, m_tempFolder, and tempFolder().
setViewItem()
void PartsEditorView::setViewItem (ItemBase * item)
References m_viewItem.
showingTerminalPoints()
bool PartsEditorView::showingTerminalPoints ()
References m_showingTerminalPoints.
showTerminalPoints()
void PartsEditorView::showTerminalPoints (bool show)
References m_showingTerminalPoints.
svgFileLoadNeeded
void PartsEditorView::svgFileLoadNeeded (const QString & filepath) signal
svgFilePath()
const QString PartsEditorView::svgFilePath ()
References m_svgFilePath.
svgFileSplit()
const SvgAndPartFilePath & PartsEditorView::svgFileSplit ()
References m_svgFilePath.
svgIdForConnector() [1/2]
QString PartsEditorView::svgIdForConnector (const QString & connId)
References m_item, and terminalIdForConnectorIdAux().
svgIdForConnector() [2/2]
QString PartsEditorView::svgIdForConnector (Connector * conn, const QString & connId) protected
References Connector::connectorShared(), Connector::connectorSharedID(), SvgIdLayer::m_svgId, and ConnectorShared::pins().
tempFolder()
QDir PartsEditorView::tempFolder ()
References m_tempFolder.
terminalIdForConnector()
QString PartsEditorView::terminalIdForConnector (const QString & connId)
References m_item, and terminalIdForConnectorIdAux().
terminalIdForConnectorIdAux()
bool PartsEditorView::terminalIdForConnectorIdAux (QString & result, const QString & connId, QDomElement & docElem, bool wantTerminal) protected
updateModelPart
void PartsEditorView::updateModelPart (const QString & origPath) slot
References copyToTempAndRenameIfNecessary(), createFakeModelPart(), m_item, m_svgFilePath, SketchWidget::m_undoStack, WaitPushUndoStack::push(), and setSvgFilePath().
updatePinsInfo()
void PartsEditorView::updatePinsInfo (QList< QPointer< class ConnectorShared > > conns)
References connectorsLayerId(), ViewLayer::findAlternativeLayers(), ConnectorShared::fullPinInfo(), ConnectorShared::id(), SvgIdLayer::m_svgId, m_svgIds, m_svgLoaded, and SvgIdLayer::m_svgViewLayerID.
updateSvgIdLayer()
void PartsEditorView::updateSvgIdLayer (const QString & connId, const QString & terminalId, const QString & connectorsLayerId) protected
References Connector::connectorShared(), Connector::connectorSharedID(), connectorsLayerId(), m_item, SvgIdLayer::m_svgViewLayerID, SvgIdLayer::m_terminalId, ConnectorShared::pins(), ViewLayer::UnknownLayer, and ViewLayer::viewLayerIDFromXmlString().
updateTerminalPoints()
bool PartsEditorView::updateTerminalPoints (QDomDocument * svgDom, const QSizeF & sceneViewBox, const QRectF & svgViewBox, const QString & connectorsLayerId) protected
References addNewTerminalPoints(), connectorsLayerId(), removeTerminalPoint(), removeTerminalPoints(), and updateSvgIdLayer().
wheelEvent()
void PartsEditorView::wheelEvent (QWheelEvent * event) protected virtual
Reimplemented from ZoomableGraphicsView.
References m_showingTerminalPoints, m_showingTerminalPointsBackup, m_terminalPointsTimer, showTerminalPoints(), and ZoomableGraphicsView::wheelEvent().
Member Data Documentation
ConnDefaultHeight
int PartsEditorView::ConnDefaultHeight = ConnDefaultWidth static protected
ConnDefaultWidth
int PartsEditorView::ConnDefaultWidth = 5 static protected
m_connsLayerID
ViewLayer::ViewLayerID PartsEditorView::m_connsLayerID protected
m_deleteModelPartOnSceneClear
bool PartsEditorView::m_deleteModelPartOnSceneClear protected
m_drawnConns
QHash<QString ,PartsEditorConnectorsConnectorItem*> PartsEditorView::m_drawnConns protected
m_fitItemInViewTimer
QTimer* PartsEditorView::m_fitItemInViewTimer protected
m_fixedToBottomLeftItems
QList<QGraphicsItem*> PartsEditorView::m_fixedToBottomLeftItems protected
m_fixedToBottomRightItems
QList<QGraphicsItem*> PartsEditorView::m_fixedToBottomRightItems protected
m_fixedToCenterItems
QList<QGraphicsItem*> PartsEditorView::m_fixedToCenterItems protected
m_fixedToTopLeftItems
QList<QGraphicsItem*> PartsEditorView::m_fixedToTopLeftItems protected
m_fixedToTopRightItems
QList<QGraphicsItem*> PartsEditorView::m_fixedToTopRightItems protected
m_fixedWidgets
QList<QWidget* > PartsEditorView::m_fixedWidgets protected
m_item
QPointer<PartsEditorPaletteItem> PartsEditorView::m_item protected
m_lastSelectedConnId
QString PartsEditorView::m_lastSelectedConnId protected
m_originalSvgFilePath
QString PartsEditorView::m_originalSvgFilePath protected
m_paletteModel
PaletteModel* PartsEditorView::m_paletteModel protected
m_removedConnIds
QStringList PartsEditorView::m_removedConnIds protected
m_showingTerminalPoints
bool PartsEditorView::m_showingTerminalPoints protected
m_showingTerminalPointsBackup
bool PartsEditorView::m_showingTerminalPointsBackup protected
m_startItem
QPointer<QGraphicsProxyWidget> PartsEditorView::m_startItem protected
m_svgFilePath
SvgAndPartFilePath* PartsEditorView::m_svgFilePath protected
m_svgIds
QHash<QString,ConnectorTerminalSvgIdPair> PartsEditorView::m_svgIds protected
m_svgLoaded
bool PartsEditorView::m_svgLoaded protected
m_tempFolder
QDir PartsEditorView::m_tempFolder protected
m_terminalPointsTimer
QTimer* PartsEditorView::m_terminalPointsTimer protected
m_viewItem
ItemBase* PartsEditorView::m_viewItem protected
The documentation for this class was generated from the following files:
partseditor/obsolete/partseditorview.h
partseditor/obsolete/partseditorview.cpp