Fritzing: Bezier Class Reference
Bezier Class Reference
#include <bezier.h>
Public Types
using SplitBezier = std::tuple< Bezier, Bezier >
Public Member Functions
Bezier (QPointF cp1, QPointF cp2)
Bezier ()
Bezier (const Bezier &)
Bezier (QPointF endpoint0, QPointF endpoint1, QPointF cp0, QPointF cp1) noexcept
void clear ()
double computeCubicCurveLength (double z, int n) const noexcept
void copy (const Bezier *)
constexpr const QPointF & cp0 () const
constexpr const QPointF & cp1 () const
constexpr bool drag0 () const noexcept
constexpr const QPointF & endpoint0 () const
constexpr const QPointF & endpoint1 () const
double findSplit (QPointF p, double minDistance) const noexcept
void initControlIndex (QPointF fromPoint, double width)
void initToEnds (QPointF cp0, QPointF cp1)
constexpr bool isEmpty () const noexcept
Bezier join (const Bezier *other) const
Bezier join (const Bezier &other) const noexcept
bool operator!= (const Bezier &) const
bool operator== (const Bezier &) const
void recalc (QPointF p)
void set_cp0 (QPointF)
void set_cp1 (QPointF)
void set_endpoints (QPointF, QPointF)
void split (double t, Bezier &left, Bezier &right) const noexcept
SplitBezier split (double t) const noexcept
void translate (QPointF)
void translateToZero ()
void write (QXmlStreamWriter &)
double xFromT (double t) const noexcept
double xFromTPrime (double t) const noexcept
double yFromT (double t) const noexcept
Static Public Member Functions
static Bezier fromElement (QDomElement &element)
Protected Member Functions
double cubicF (double t) const noexcept
Protected Attributes
QPointF m_cp0
QPointF m_cp1
bool m_drag_cp0 = false
QPointF m_endpoint0
QPointF m_endpoint1
bool m_isEmpty
Member Typedef Documentation
SplitBezier
using Bezier::SplitBezier = std::tuple<Bezier, Bezier>
Constructor & Destructor Documentation
Bezier() [1/4]
Bezier::Bezier (QPointF cp1, QPointF cp2)
Bezier() [2/4]
Bezier::Bezier ()
Bezier() [3/4]
Bezier::Bezier (const Bezier & other)
Bezier() [4/4]
Bezier::Bezier (QPointF endpoint0, QPointF endpoint1, QPointF cp0, QPointF cp1) noexcept
Member Function Documentation
clear()
void Bezier::clear ()
References m_isEmpty.
computeCubicCurveLength()
double Bezier::computeCubicCurveLength (double z, int n) const noexcept
Gauss quadrature for cubic Bezier curves
References Cvalues, Tvalues, and ItemBase::z().
copy()
void Bezier::copy (const Bezier * other)
References m_cp0, m_cp1, m_drag_cp0, m_endpoint0, m_endpoint1, and m_isEmpty.
cp0()
constexpr const QPointF& Bezier::cp0 () const inline
References m_cp0.
cp1()
constexpr const QPointF& Bezier::cp1 () const inline
References m_cp1.
cubicF()
double Bezier::cubicF (double t) const protected noexcept
References base3().
drag0()
constexpr bool Bezier::drag0 () const inline noexcept
References m_drag_cp0.
endpoint0()
constexpr const QPointF& Bezier::endpoint0 () const inline
References m_endpoint0.
endpoint1()
constexpr const QPointF& Bezier::endpoint1 () const inline
References m_endpoint1.
findSplit()
double Bezier::findSplit (QPointF p, double minDistance) const noexcept
References GraphicsUtils::distanceSqd().
fromElement()
Bezier Bezier::fromElement (QDomElement & element) static
References set_cp0(), and set_cp1().
initControlIndex()
void Bezier::initControlIndex (QPointF fromPoint, double width)
References computeCubicCurveLength(), findSplit(), and m_drag_cp0.
initToEnds()
void Bezier::initToEnds (QPointF cp0, QPointF cp1)
References cp0(), cp1(), m_cp0, m_cp1, m_endpoint0, m_endpoint1, and m_isEmpty.
isEmpty()
constexpr bool Bezier::isEmpty () const inline noexcept
References m_isEmpty.
join() [1/2]
Bezier Bezier::join (const Bezier * other) const
References isEmpty().
join() [2/2]
Bezier Bezier::join (const Bezier & other) const noexcept
References isEmpty(), set_cp0(), and set_cp1().
operator!=()
bool Bezier::operator!= (const Bezier & other) const
References cp0(), cp1(), isEmpty(), m_cp0, m_cp1, and m_isEmpty.
operator==()
bool Bezier::operator== (const Bezier & other) const
References cp0(), cp1(), isEmpty(), m_cp0, m_cp1, and m_isEmpty.
recalc()
void Bezier::recalc (QPointF p)
References B0(), B1(), B2(), B3(), m_cp0, m_cp1, m_drag_cp0, m_endpoint0, m_endpoint1, and m_isEmpty.
set_cp0()
void Bezier::set_cp0 (QPointF cp0)
References cp0(), m_cp0, and m_isEmpty.
set_cp1()
void Bezier::set_cp1 (QPointF cp1)
References cp1(), m_cp1, and m_isEmpty.
set_endpoints()
void Bezier::set_endpoints (QPointF ep0, QPointF ep1)
References m_endpoint0, and m_endpoint1.
split() [1/2]
void Bezier::split (double t, Bezier & left, Bezier & right) const noexcept
split() [2/2]
Bezier::SplitBezier Bezier::split (double t) const noexcept
translate()
void Bezier::translate (QPointF p)
References m_cp0, m_cp1, m_endpoint0, and m_endpoint1.
translateToZero()
void Bezier::translateToZero ()
References m_cp0, m_cp1, m_endpoint0, and m_endpoint1.
write()
void Bezier::write (QXmlStreamWriter & streamWriter)
References isEmpty(), m_cp0, and m_cp1.
xFromT()
double Bezier::xFromT (double t) const noexcept
References B0(), B1(), B2(), and B3().
xFromTPrime()
double Bezier::xFromTPrime (double t) const noexcept
References base3().
yFromT()
double Bezier::yFromT (double t) const noexcept
References B0(), B1(), B2(), and B3().
Member Data Documentation
m_cp0
QPointF Bezier::m_cp0 protected
m_cp1
QPointF Bezier::m_cp1 protected
m_drag_cp0
bool Bezier::m_drag_cp0 = false protected
m_endpoint0
QPointF Bezier::m_endpoint0 protected
m_endpoint1
QPointF Bezier::m_endpoint1 protected
m_isEmpty
bool Bezier::m_isEmpty protected
The documentation for this class was generated from the following files:
utils/bezier.h
utils/bezier.cpp