Fritzing: QtSystemInfo Class Reference
QtSystemInfo Class Reference
#include <QtSystemInfo.h>
Public Types
enum ArchitectureType {
UnknownArchitectureType = -1, I386, I486, I586,
I686, X86_64, MPPC, MPPC64
}
enum SystemType {
UnknownType = -1, UnknownUnix, MacOSX, Windows,
WindowsCE, Linux, UnknownBSD, FreeBSD,
OpenBSD, NetBSD
}
Public Member Functions
QtSystemInfo (QObject *parent=0)
~QtSystemInfo ()
ArchitectureType architecture () const
QString architectureName () const
QString getSystemInformation (QString format=QString())
QString kernelName () const
QString kernelVersion () const
QString systemName () const
SystemType systemType () const
QString systemVersion () const
Private Attributes
QtSystemInfoPrivate * d
Member Enumeration Documentation
ArchitectureType
enum QtSystemInfo::ArchitectureType
Enumerator
UnknownArchitectureType
I386
I486
I586
I686
X86_64
MPPC
MPPC64
SystemType
enum QtSystemInfo::SystemType
Enumerator
UnknownType
UnknownUnix
MacOSX
Windows
WindowsCE
Linux
UnknownBSD
FreeBSD
OpenBSD
NetBSD
Constructor & Destructor Documentation
QtSystemInfo()
QtSystemInfo::QtSystemInfo (QObject * parent = 0)
~QtSystemInfo()
QtSystemInfo::~QtSystemInfo ()
References d.
Member Function Documentation
architecture()
QtSystemInfo::ArchitectureType QtSystemInfo::architecture () const
Returns
Type of currently running system's architecture.
References QtSystemInfoPrivate::architecture(), and d.
architectureName()
QString QtSystemInfo::architectureName () const
Returns
Architecture of the running system.
getSystemInformation()
QString QtSystemInfo::getSystemInformation (QString format = QString())
Parameters
format A format of the information to be returned. The following strings will be replaced: SYS_NAME - replaced with system name. SYS_VERSION - replaced with system version. KERN_NAME - replaced with kernel name. KERN_VERSION - replaced with kernel version. ARCH - replaced with architecture. If no format given, the method will default to: SYS_NAME SYS_VERSION (KERN_NAME KERN_VERSION ARCH).
Returns
Formatted information about the running system.
References architectureName(), kernelName(), kernelVersion(), systemName(), and systemVersion().
kernelName()
QString QtSystemInfo::kernelName () const
Returns
Name of currently running system's kernel.
References d, and QtSystemInfoPrivate::kernelName().
kernelVersion()
QString QtSystemInfo::kernelVersion () const
Returns
Version of currently running system's kernel.
References d, and QtSystemInfoPrivate::kernelVersion().
systemName()
QString QtSystemInfo::systemName () const
Returns
Name of currently running system.
References d, and QtSystemInfoPrivate::systemName().
systemType()
QtSystemInfo::SystemType QtSystemInfo::systemType () const
Returns
Type of currently running system.
References d, and QtSystemInfoPrivate::systemType().
systemVersion()
QString QtSystemInfo::systemVersion () const
Returns
Version of currently running system.
References d, and QtSystemInfoPrivate::systemVersion().
Member Data Documentation
d
QtSystemInfoPrivate* QtSystemInfo::d private
The documentation for this class was generated from the following files:
lib/qtsysteminfo/QtSystemInfo.h
lib/qtsysteminfo/QtSystemInfo.cpp