Fritzing: Panelizer Class Reference
Panelizer Class Reference
#include <panelizer.h>
Static Public Member Functions
static int checkDonuts (MainWindow *, bool displayMessage)
static int checkText (MainWindow *, bool displayMessage)
static void inscribe (class FApplication *, const QString &panelFilename, bool drc, bool noMessages)
static void panelize (class FApplication *, const QString &panelFilename, bool customPartsOnly)
static int placeBestFit (Tile *tile, UserData userData)
Static Protected Member Functions
static void addOptional (int optionalCount, QList< PanelItem * > &refPanelItems, QList< PanelItem * > &insertPanelItems, PanelParams &, QList< PlanePair * > &)
static void bestFit (QList< PanelItem * > &insertPanelItems, PanelParams &, QList< PlanePair * > &, bool customPartsOnly)
static int bestFitLoop (QList< PanelItem * > &refPanelItems, PanelParams &, bool customPartsOnly, QList< PlanePair * > &returnPlanePairs, QList< PanelItem * > &returnInsertPanelItems, const QDir &svgDir)
static bool bestFitOne (PanelItem *panelItem, PanelParams &panelParams, QList< PlanePair * > &planePairs, bool createNew, bool customPartsOnly)
static double calcCost (PanelParams &, QList< PlanePair * > &, int divisor)
static bool checkBoards (QDomElement &board, QHash< QString, QString > &fzzFilePaths)
static void collectFilenames (const QString &filenames)
static void collectFiles (const QDir &outputDir, QDomElement &path, QHash< QString, QString > &fzzFilePaths)
static void doOnePanelItem (PlanePair *planePair, QList< LayerThing > &layerThingList, PanelItem *panelItem, QDir &svgDir)
static void initPanelizerOutput (const QString &filename, const QString &initialMsg)
static bool initPanelParams (QDomElement &root, PanelParams &)
static class MainWindow * inscribeBoard (QDomElement &board, QHash< QString, QString > &fzzFilePaths, FApplication *app, QDir &fzDir, bool drc, bool noMessages, QDir &copyDir)
static PlanePair * makePlanePair (PanelParams &, bool big)
static void makeSVGs (MainWindow *, ItemBase *, const QString &boardName, QList< LayerThing > &layerThingList, QDir &saveDir, QFileInfo &copyInfo)
static bool openWindows (QDomElement &board, QHash< QString, QString > &fzzFilePaths, class FApplication *, PanelParams &, QDir &fzDir, QDir &svgDir, QList< PanelItem * > &refPanelItems, QList< LayerThing > &layerThingList, bool customPartsOnly, QDir &copyDir)
static void shrinkLastPanel (QList< PlanePair * > &planePairs, QList< PanelItem * > &insertPanelItems, PanelParams &, bool customPartsOnly)
static void writePanelizerFilenames (const QString &panelFilename)
static void writePanelizerOutput (const QString &message)
Member Function Documentation
addOptional()
void Panelizer::addOptional (int optionalCount, QList< PanelItem * > & refPanelItems, QList< PanelItem * > & insertPanelItems, PanelParams & panelParams, QList< PlanePair * > & planePairs) static protected
References bestFitOne(), byOptionalPriority(), PanelItem::maxOptional, and PanelItem::optionalPriority.
bestFit()
void Panelizer::bestFit (QList< PanelItem * > & insertPanelItems, PanelParams & panelParams, QList< PlanePair * > & planePairs, bool customPartsOnly) static protected
References bestFitOne().
bestFitLoop()
int Panelizer::bestFitLoop (QList< PanelItem * > & refPanelItems, PanelParams & panelParams, bool customPartsOnly, QList< PlanePair * > & returnPlanePairs, QList< PanelItem * > & returnInsertPanelItems, const QDir & svgDir) static protected
References addOptional(), areaGreaterThan(), bestFit(), calcCost(), DebugDialog::debug(), PlanePair::index, PlanePair::layoutSVG, makePlanePair(), PanelItem::maxOptional, PlanePairIndex, PanelParams::prefix, PanelItem::required, shrinkLastPanel(), and TextUtils::writeUtf8().
bestFitOne()
bool Panelizer::bestFitOne (PanelItem * panelItem, PanelParams & panelParams, QList< PlanePair * > & planePairs, bool createNew, bool customPartsOnly) static protected
References BestPlace::bestArea, BestPlace::bestTile, BestPlace::bestTileRect, PanelItem::boardName, PanelItem::boardSizeInches, DebugDialog::debug(), BestPlace::height, PlanePair::layoutSVG, makePlanePair(), BestPlace::maxRect, Tile::OBSTACLE, OCRAFontName(), PanelParams::panelSpacing, PanelItem::path, placeBestFit(), BestPlace::plane, PanelItem::planePair, realToTile(), PanelItem::rotate90, BestPlace::rotate90, GraphicsUtils::StandardFritzingDPI, PlanePair::thePlane, PlanePair::thePlane90, TiInsertTile(), PlanePair::tilePanelRect, PlanePair::tilePanelRect90, tileRotate90(), tileToReal(), tileUnrotate90(), TiSrArea(), BestPlace::width, PanelItem::x, TileRect::xmaxi, TileRect::xmini, PanelItem::y, TileRect::ymaxi, and TileRect::ymini.
calcCost()
double Panelizer::calcCost (PanelParams & panelParams, QList< PlanePair * > & planePairs, int divisor) static protected
References PanelType::c1, PanelType::c2, PanelType::height, PlanePair::panelHeight, PanelParams::panelTypes, PlanePair::panelWidth, and PanelType::width.
checkBoards()
bool Panelizer::checkBoards (QDomElement & board, QHash< QString, QString > & fzzFilePaths) static protected
References writePanelizerOutput().
checkDonuts()
int Panelizer::checkDonuts (MainWindow * mainWindow, bool displayMessage) static
References NonConnectorItem::attachedTo(), collectFilenames(), ConnectorItem::debugInfo(), ItemBase::debugInfo(), FritzingWindow::fileName(), ConnectorItem::getCrossLayerConnectorItem(), ItemBase::isEverVisible(), NonConnectorItem::isPath(), MainWindow::pcbView(), SketchWidget::selectAllItems(), SketchWidget::selectItems(), and writePanelizerOutput().
checkText()
int Panelizer::checkText (MainWindow * mainWindow, bool displayMessage) static
References collectFilenames(), DebugDialog::debug(), FritzingWindow::fileName(), ItemBase::id(), ItemBase::isEverVisible(), MainWindow::pcbView(), ItemBase::retrieveSvg(), SketchWidget::selectAllItems(), SketchWidget::selectItems(), GraphicsUtils::StandardFritzingDPI, ItemBase::viewLayerID(), and writePanelizerOutput().
collectFilenames()
void Panelizer::collectFilenames (const QString & filenames) static protected
References PanelizerFileNames.
collectFiles()
void Panelizer::collectFiles (const QDir & outputDir, QDomElement & path, QHash< QString, QString > & fzzFilePaths) static protected
References FolderUtils::collectFiles(), DebugDialog::debug(), and FritzingBundleExtension().
doOnePanelItem()
void Panelizer::doOnePanelItem (PlanePair * planePair, QList< LayerThing > & layerThingList, PanelItem * panelItem, QDir & svgDir) static protected
References PanelItem::boardID, PanelItem::boardName, DebugDialog::debug(), PanelItem::rotate90, GraphicsUtils::StandardFritzingDPI, PlanePair::svgs, PanelItem::x, and PanelItem::y.
initPanelizerOutput()
void Panelizer::initPanelizerOutput (const QString & filename, const QString & initialMsg) static protected
References PanelizerFileNames, PanelizerOutputPath, and writePanelizerOutput().
initPanelParams()
bool Panelizer::initPanelParams (QDomElement & root, PanelParams & panelParams) static protected
References PanelType::c1, PanelType::c2, TextUtils::convertToInches(), PanelType::height, PanelType::name, PanelParams::panelBorder, PanelParams::panelSpacing, PanelParams::panelTypes, PanelParams::prefix, PanelType::width, and writePanelizerOutput().
inscribe()
void Panelizer::inscribe (class FApplication * app, const QString & panelFilename, bool drc, bool noMessages) static
References checkBoards(), collectFiles(), FApplication::createUserDataStoreFolderStructures(), DebugDialog::debug(), initPanelizerOutput(), initPanelParams(), inscribeBoard(), FApplication::loadReferenceModel(), FApplication::registerFonts(), MainWindow::setCloseSilently(), DebugDialog::setEnabled(), writePanelizerFilenames(), and writePanelizerOutput().
inscribeBoard()
MainWindow * Panelizer::inscribeBoard (QDomElement & board, QHash< QString, QString > & fzzFilePaths, FApplication * app, QDir & fzDir, bool drc, bool noMessages, QDir & copyDir) static protected
References PCBSketchWidget::characterizeGroundFill(), checkDonuts(), PCBSketchWidget::checkLoadedTraces(), checkText(), collectFilenames(), MainWindow::copperFill(), DebugDialog::debug(), FritzingWindow::fileName(), GroundPlane::fillTypeGround, GroundPlane::fillTypeNone, PCBSketchWidget::findBoard(), MainWindow::fritzingVersion(), Version::greaterThan(), MainWindow::groundFill(), ViewLayer::GroundPlane0, ViewLayer::GroundPlane1, MainWindow::loadWhich(), VersionThing::majorVersion, VersionThing::minorSubVersion, VersionThing::minorVersion, MainWindow::newDesignRulesCheck(), FApplication::openWindowForService(), MainWindow::pcbView(), ProcessEventBlocker::processEvents(), ItemBase::prop(), VersionThing::releaseModifier, PCBSketchWidget::resetKeepout(), MainWindow::saveAsAux(), SketchWidget::selectAllItems(), SketchWidget::selectAllObsolete(), SketchWidget::setGridSize(), ItemBase::setMoveLock(), FolderUtils::setOpenSaveFolderAux(), SketchWidget::showGrid(), FolderUtils::slamCopy(), MainWindow::swapLayers(), Version::toVersionThing(), and writePanelizerOutput().
makePlanePair()
PlanePair * Panelizer::makePlanePair (PanelParams & panelParams, bool big) static protected
References Tile::BUFFER, fasterRealToTile(), PanelType::height, PlanePair::index, PlanePair::layoutSVG, TextUtils::makeSVGHeader(), PanelType::name, PanelParams::panelBorder, PlanePair::panelHeight, PanelParams::panelSpacing, PanelParams::panelTypes, PlanePair::panelWidth, PlanePairIndex, qrectToTile(), SETLEFT(), SETRIGHT(), SETYMAX(), SETYMIN(), Tile::SPACE, GraphicsUtils::StandardFritzingDPI, PlanePair::thePlane, PlanePair::thePlane90, TiAlloc(), TiInsertTile(), PlanePair::tilePanelRect, PlanePair::tilePanelRect90, TiNewPlane(), TiSetBody(), TiSetType(), and PanelType::width.
makeSVGs()
void Panelizer::makeSVGs (MainWindow * mainWindow, ItemBase * board, const QString & boardName, QList< LayerThing > & layerThingList, QDir & saveDir, QFileInfo & copyInfo) static protected
References NonConnectorItem::attachedToID(), RenderThing::blackOnly, GerberGenerator::cleanOutline(), GerberGenerator::clipToBoard(), collectTexts(), DebugDialog::debug(), RenderThing::dpi, TextUtils::expandAndFill(), SVG2gerber::ForCopper, SVG2gerber::ForDrill, SVG2gerber::ForMask, SVG2gerber::ForOutline, SVG2gerber::ForPasteMask, SVG2gerber::ForSilk, LayerThing::forWhy, PCBSketchWidget::hideCopperLogoItems(), PCBSketchWidget::hideHoles(), RenderThing::hideTerminalPoints, ItemBase::id(), NonConnectorItem::isPath(), LayerThing::layerList, PCBSketchWidget::makePasteMask(), GerberGenerator::MaskClearanceMils, LayerThing::name, MainWindow::pcbView(), RenderThing::printerScale, NonConnectorItem::radius(), RenderThing::renderBlocker, SketchWidget::renderToSVG(), PCBSketchWidget::restoreCopperLogoItems(), RenderThing::selectedItems, GraphicsUtils::StandardFritzingDPI, GraphicsUtils::SVGDPI, and TextUtils::writeUtf8().
openWindows()
bool Panelizer::openWindows (QDomElement & board, QHash< QString, QString > & fzzFilePaths, class FApplication * app, PanelParams & panelParams, QDir & fzDir, QDir & svgDir, QList< PanelItem * > & refPanelItems, QList< LayerThing > & layerThingList, bool customPartsOnly, QDir & copyDir) static protected
References PanelItem::boardID, PanelItem::boardName, PanelItem::boardSizeInches, checkDonuts(), PCBSketchWidget::checkLoadedTraces(), checkText(), DebugDialog::debug(), PCBSketchWidget::findBoard(), MainWindow::hasAnyAlien(), MainWindow::hasCustomBoardShape(), PanelType::height, ItemBase::id(), ItemBase::layerKinChief(), MainWindow::loadWhich(), makeSVGs(), PanelItem::maxOptional, PanelType::name, FApplication::openWindowForService(), PanelItem::optionalPriority, PanelParams::panelTypes, PanelItem::path, MainWindow::pcbView(), PanelItem::required, SketchWidget::rotateX(), SketchWidget::selectAllItems(), MainWindow::setCloseSilently(), ItemBase::setMoveLock(), FolderUtils::setOpenSaveFolderAux(), GraphicsUtils::SVGDPI, PanelType::width, and writePanelizerOutput().
panelize()
void Panelizer::panelize (class FApplication * app, const QString & panelFilename, bool customPartsOnly) static
References bestFitLoop(), PanelItem::boardName, checkBoards(), collectFiles(), GerberGenerator::CopperBottomSuffix, ViewLayer::copperLayers(), GerberGenerator::CopperTopSuffix, FApplication::createUserDataStoreFolderStructures(), DebugDialog::debug(), GerberGenerator::doEnd(), doOnePanelItem(), ViewLayer::drillLayers(), GerberGenerator::DrillSuffix, SVG2gerber::ForCopper, SVG2gerber::ForDrill, SVG2gerber::ForMask, SVG2gerber::ForOutline, SVG2gerber::ForPasteMask, SVG2gerber::ForSilk, PlanePair::index, initPanelizerOutput(), initPanelParams(), PlanePair::layoutSVG, FApplication::loadReferenceModel(), TextUtils::makeSVGHeader(), GerberGenerator::MaskBottomSuffix, ViewLayer::maskLayers(), GerberGenerator::MaskTopSuffix, TextUtils::mergeSvg(), TextUtils::mergeSvgFinish(), LayerThing::name, ViewLayer::NewBottom, ViewLayer::NewTop, openWindows(), OutlineLayer, ViewLayer::outlineLayers(), GerberGenerator::OutlineSuffix, PlanePair::panelHeight, PlanePair::panelWidth, GerberGenerator::PasteMaskBottomSuffix, GerberGenerator::PasteMaskTopSuffix, PanelItem::path, PanelItem::planePair, PanelParams::prefix, PanelItem::produced, PanelItem::refPanelItem, FApplication::registerFonts(), DebugDialog::setEnabled(), GerberGenerator::SilkBottomSuffix, ViewLayer::silkLayers(), SilkTopLayer, GerberGenerator::SilkTopSuffix, GraphicsUtils::StandardFritzingDPI, PlanePair::svgs, writePanelizerOutput(), and TextUtils::writeUtf8().
placeBestFit()
int Panelizer::placeBestFit (Tile * tile, UserData userData) static
References allObstacles(), allSpaces(), BestPlace::bestArea, BestPlace::bestTile, BestPlace::bestTileRect, BL(), Tile::BUFFER, BestPlace::height, BestPlace::maxRect, BestPlace::plane, qMax(), BestPlace::rotate90, Tile::SPACE, TiGetType(), TiSrArea(), TiToRect(), BestPlace::width, Worst, TileRect::xmaxi, TileRect::xmini, YMAX(), TileRect::ymaxi, and TileRect::ymini.
shrinkLastPanel()
void Panelizer::shrinkLastPanel (QList< PlanePair * > & planePairs, QList< PanelItem * > & insertPanelItems, PanelParams & panelParams, bool customPartsOnly) static protected
References bestFitOne(), PlanePair::index, makePlanePair(), and PanelItem::planePair.
writePanelizerFilenames()
void Panelizer::writePanelizerFilenames (const QString & panelFilename) static protected
References PanelizerFileNames.
writePanelizerOutput()
void Panelizer::writePanelizerOutput (const QString & message) static protected
References DebugDialog::debug(), and PanelizerOutputPath.
The documentation for this class was generated from the following files:
autoroute/panelizer.h
autoroute/panelizer.cpp