Fritzing: GerberGenerator Class Reference
GerberGenerator Class Reference
#include <gerbergenerator.h>
Static Public Member Functions
static QString cleanOutline (const QString &svgOutline)
static QString clipToBoard (QString svgString, QRectF &boardRect, const QString &layerName, SVG2gerber::ForWhy, const QString &clipString, bool displayMessageBoxes, QMultiHash< long, class ConnectorItem * > &treatAsCircle)
static QString clipToBoard (QString svgString, ItemBase *board, const QString &layerName, SVG2gerber::ForWhy, const QString &clipString, bool displayMessageBoxes, QMultiHash< long, class ConnectorItem * > &treatAsCircle)
static int doEnd (const QString &svg, int boardLayers, const QString &layerName, SVG2gerber::ForWhy forWhy, QSizeF svgSize, const QString &exportDir, const QString &prefix, const QString &suffix, bool displayMessageBoxes)
static void exportToGerber (const QString &prefix, const QString &exportDir, class ItemBase *board, class PCBSketchWidget *, bool displayMessageBoxes)
Static Public Attributes
static const QString CopperBottomSuffix = "_copperBottom.gbl"
static const QString CopperTopSuffix = "_copperTop.gtl"
static const QString DrillSuffix = "_drill.txt"
static const QString MagicBoardOutlineID = "boardoutline"
static const QString MaskBottomSuffix = "_maskBottom.gbs"
static const double MaskClearanceMils = 5
static const QString MaskTopSuffix = "_maskTop.gts"
static const QString OutlineSuffix = "_contour.gm1"
static const QString PasteMaskBottomSuffix = "_pasteMaskBottom.gbp"
static const QString PasteMaskTopSuffix = "_pasteMaskTop.gtp"
static const QString SilkBottomSuffix = "_silkBottom.gbo"
static const QString SilkTopSuffix = "_silkTop.gto"
Static Protected Member Functions
static bool dealWithMultipleContours (QDomElement &root, bool displayMessageBoxes)
static void displayMessage (const QString &message, bool displayMessageBoxes)
static int doCopper (ItemBase *board, PCBSketchWidget *sketchWidget, LayerList &viewLayerIDs, const QString &copperName, const QString &copperSuffix, const QString &filename, const QString &exportDir, bool displayMessageBoxes)
static int doDrill (ItemBase *board, PCBSketchWidget *sketchWidget, const QString &filename, const QString &exportDir, bool displayMessageBoxes)
static int doMask (LayerList maskLayerIDs, const QString &maskName, const QString &gerberSuffix, ItemBase *board, PCBSketchWidget *sketchWidget, const QString &filename, const QString &exportDir, bool displayMessageBoxes, QString &clipString)
static int doPasteMask (LayerList maskLayerIDs, const QString &maskName, const QString &gerberSuffix, ItemBase *board, PCBSketchWidget *sketchWidget, const QString &filename, const QString &exportDir, bool displayMessageBoxes)
static int doSilk (LayerList silkLayerIDs, const QString &silkName, const QString &gerberSuffix, ItemBase *board, PCBSketchWidget *sketchWidget, const QString &filename, const QString &exportDir, bool displayMessageBoxes, const QString &clipString)
static void exportPickAndPlace (const QString &prefix, const QString &exportDir, ItemBase *board, PCBSketchWidget *sketchWidget, bool displayMessageBoxes)
static void handleDonuts (QDomElement &root1, QMultiHash< long, ConnectorItem * > &treatAsCircle)
static QString makePath (QImage &image, double unit, const QString &colorString)
static void mergeOutlineElement (QImage &image, QRectF &target, double res, QDomDocument &document, QString &svgString, int ix, const QString &layerName)
static QString renderTo (const LayerList &, ItemBase *board, PCBSketchWidget *sketchWidget, bool &empty)
static bool saveEnd (const QString &layerName, const QString &exportDir, const QString &prefix, const QString &suffix, bool displayMessageBoxes, SVG2gerber &gerber)
Member Function Documentation
cleanOutline()
QString GerberGenerator::cleanOutline (const QString & svgOutline) static
References TextUtils::collectLeaves(), and MagicBoardOutlineID.
clipToBoard() [1/2]
static QString GerberGenerator::clipToBoard (QString svgString, QRectF & boardRect, const QString & layerName, SVG2gerber::ForWhy , const QString & clipString, bool displayMessageBoxes, QMultiHash< long, class ConnectorItem * > & treatAsCircle) static
clipToBoard() [2/2]
static QString GerberGenerator::clipToBoard (QString svgString, ItemBase * board, const QString & layerName, SVG2gerber::ForWhy , const QString & clipString, bool displayMessageBoxes, QMultiHash< long, class ConnectorItem * > & treatAsCircle) static
dealWithMultipleContours()
bool GerberGenerator::dealWithMultipleContours (QDomElement & root, bool displayMessageBoxes) static protected
References displayMessage(), MFinder(), and MultipleZs().
displayMessage()
void GerberGenerator::displayMessage (const QString & message, bool displayMessageBoxes) static protected
References DebugDialog::debug().
doCopper()
int GerberGenerator::doCopper (ItemBase * board, PCBSketchWidget * sketchWidget, LayerList & viewLayerIDs, const QString & copperName, const QString & copperSuffix, const QString & filename, const QString & exportDir, bool displayMessageBoxes) static protected
References NonConnectorItem::attachedToID(), InfoGraphicsView::boardLayers(), clipToBoard(), displayMessage(), doEnd(), SVG2gerber::ForCopper, NonConnectorItem::isPath(), TextUtils::parseForWidthAndHeight(), NonConnectorItem::radius(), renderTo(), and GraphicsUtils::StandardFritzingDPI.
doDrill()
int GerberGenerator::doDrill (ItemBase * board, PCBSketchWidget * sketchWidget, const QString & filename, const QString & exportDir, bool displayMessageBoxes) static protected
References NonConnectorItem::attachedToID(), InfoGraphicsView::boardLayers(), clipToBoard(), displayMessage(), doEnd(), ViewLayer::drillLayers(), DrillSuffix, SVG2gerber::ForDrill, NonConnectorItem::isPath(), TextUtils::parseForWidthAndHeight(), NonConnectorItem::radius(), renderTo(), and GraphicsUtils::StandardFritzingDPI.
doEnd()
int GerberGenerator::doEnd (const QString & svg, int boardLayers, const QString & layerName, SVG2gerber::ForWhy forWhy, QSizeF svgSize, const QString & exportDir, const QString & prefix, const QString & suffix, bool displayMessageBoxes) static
References SVG2gerber::convert(), and saveEnd().
doMask()
int GerberGenerator::doMask (LayerList maskLayerIDs, const QString & maskName, const QString & gerberSuffix, ItemBase * board, PCBSketchWidget * sketchWidget, const QString & filename, const QString & exportDir, bool displayMessageBoxes, QString & clipString) static protected
References InfoGraphicsView::boardLayers(), clipToBoard(), displayMessage(), doEnd(), TextUtils::expandAndFill(), SVG2gerber::ForCopper, PCBSketchWidget::hideCopperLogoItems(), MaskClearanceMils, TextUtils::parseForWidthAndHeight(), renderTo(), PCBSketchWidget::restoreCopperLogoItems(), and GraphicsUtils::StandardFritzingDPI.
doPasteMask()
int GerberGenerator::doPasteMask (LayerList maskLayerIDs, const QString & maskName, const QString & gerberSuffix, ItemBase * board, PCBSketchWidget * sketchWidget, const QString & filename, const QString & exportDir, bool displayMessageBoxes) static protected
References InfoGraphicsView::boardLayers(), clipToBoard(), displayMessage(), doEnd(), SVG2gerber::ForCopper, PCBSketchWidget::hideCopperLogoItems(), PCBSketchWidget::hideHoles(), PCBSketchWidget::makePasteMask(), TextUtils::parseForWidthAndHeight(), renderTo(), PCBSketchWidget::restoreCopperLogoItems(), and GraphicsUtils::StandardFritzingDPI.
doSilk()
int GerberGenerator::doSilk (LayerList silkLayerIDs, const QString & silkName, const QString & gerberSuffix, ItemBase * board, PCBSketchWidget * sketchWidget, const QString & filename, const QString & exportDir, bool displayMessageBoxes, const QString & clipString) static protected
References InfoGraphicsView::boardLayers(), clipToBoard(), displayMessage(), doEnd(), SVG2gerber::ForSilk, TextUtils::parseForWidthAndHeight(), renderTo(), ViewLayer::Silkscreen1, and GraphicsUtils::StandardFritzingDPI.
exportPickAndPlace()
void GerberGenerator::exportPickAndPlace (const QString & prefix, const QString & exportDir, ItemBase * board, PCBSketchWidget * sketchWidget, bool displayMessageBoxes) static protected
References ViewLayer::Copper1, displayMessage(), ItemBase::instanceTitle(), ItemBase::isEverVisible(), ItemBase::itemType(), ItemBase::layerKinChief(), ModelPart::localProp(), ItemBase::modelPart(), GraphicsUtils::pixels2mm(), ModelPart::properties(), GraphicsUtils::SVGDPI, Version::versionString(), ItemBase::viewLayerID(), and ModelPart::Wire.
exportToGerber()
void GerberGenerator::exportToGerber (const QString & prefix, const QString & exportDir, class ItemBase * board, class PCBSketchWidget * sketchWidget, bool displayMessageBoxes) static
References InfoGraphicsView::boardLayers(), cleanOutline(), clipToBoard(), SVG2gerber::convert(), CopperBottomSuffix, ViewLayer::copperLayers(), CopperTopSuffix, DebugDialog::debug(), displayMessage(), doCopper(), doDrill(), doMask(), doPasteMask(), doSilk(), exportPickAndPlace(), PCBSketchWidget::findSelectedBoard(), SVG2gerber::ForOutline, MaskBottomSuffix, ViewLayer::maskLayers(), MaskTopSuffix, ViewLayer::NewBottom, ViewLayer::NewTop, ViewLayer::outlineLayers(), OutlineSuffix, TextUtils::parseForWidthAndHeight(), PasteMaskBottomSuffix, PasteMaskTopSuffix, renderTo(), saveEnd(), SilkBottomSuffix, ViewLayer::silkLayers(), SilkTopSuffix, and GraphicsUtils::StandardFritzingDPI.
handleDonuts()
void GerberGenerator::handleDonuts (QDomElement & root1, QMultiHash< long, ConnectorItem * > & treatAsCircle) static protected
References NonConnectorItem::attachedTo(), ConnectorItem::connector(), DebugDialog::debug(), ConnectorItem::debugInfo(), Connector::fullPinInfo(), SvgIdLayer::m_svgId, NonConnectorItem::radius(), GraphicsUtils::StandardFritzingDPI, NonConnectorItem::strokeWidth(), GraphicsUtils::SVGDPI, ItemBase::viewID(), and ItemBase::viewLayerID().
makePath()
QString GerberGenerator::makePath (QImage & image, double unit, const QString & colorString) static protected
mergeOutlineElement()
void GerberGenerator::mergeOutlineElement (QImage & image, QRectF & target, double res, QDomDocument & document, QString & svgString, int ix, const QString & layerName) static protected
References FolderUtils::getTopLevelUserDataStorePath(), GroundPlaneGenerator::mergeSVGs(), GroundPlaneGenerator::newSVGs(), TextUtils::removeXMLEntities(), GroundPlaneGenerator::scanOutline(), GroundPlaneGenerator::setLayerName(), GroundPlaneGenerator::setMinRunSize(), and GraphicsUtils::StandardFritzingDPI.
renderTo()
QString GerberGenerator::renderTo (const LayerList & layers, ItemBase * board, PCBSketchWidget * sketchWidget, bool & empty) static protected
References RenderThing::blackOnly, RenderThing::dpi, RenderThing::empty, RenderThing::hideTerminalPoints, layers(), RenderThing::printerScale, RenderThing::renderBlocker, SketchWidget::renderToSVG(), RenderThing::selectedItems, GraphicsUtils::StandardFritzingDPI, and GraphicsUtils::SVGDPI.
saveEnd()
bool GerberGenerator::saveEnd (const QString & layerName, const QString & exportDir, const QString & prefix, const QString & suffix, bool displayMessageBoxes, SVG2gerber & gerber) static protected
References displayMessage(), and SVG2gerber::getGerber().
Member Data Documentation
CopperBottomSuffix
const QString GerberGenerator::CopperBottomSuffix = "_copperBottom.gbl" static
CopperTopSuffix
const QString GerberGenerator::CopperTopSuffix = "_copperTop.gtl" static
DrillSuffix
const QString GerberGenerator::DrillSuffix = "_drill.txt" static
MagicBoardOutlineID
const QString GerberGenerator::MagicBoardOutlineID = "boardoutline" static
MaskBottomSuffix
const QString GerberGenerator::MaskBottomSuffix = "_maskBottom.gbs" static
MaskClearanceMils
const double GerberGenerator::MaskClearanceMils = 5 static
MaskTopSuffix
const QString GerberGenerator::MaskTopSuffix = "_maskTop.gts" static
OutlineSuffix
const QString GerberGenerator::OutlineSuffix = "_contour.gm1" static
PasteMaskBottomSuffix
const QString GerberGenerator::PasteMaskBottomSuffix = "_pasteMaskBottom.gbp" static
PasteMaskTopSuffix
const QString GerberGenerator::PasteMaskTopSuffix = "_pasteMaskTop.gtp" static
SilkBottomSuffix
const QString GerberGenerator::SilkBottomSuffix = "_silkBottom.gbo" static
SilkTopSuffix
const QString GerberGenerator::SilkTopSuffix = "_silkTop.gto" static
The documentation for this class was generated from the following files:
svg/gerbergenerator.h
svg/gerbergenerator.cpp