Fritzing: FApplication Class Reference
FApplication Class Reference
#include <fapplication.h>
Public Slots
void changeActivation (bool activate, QWidget *originator)
void checkForUpdates ()
void checkForUpdates (bool atUserRequest)
void closeAllWindows2 ()
void createUserDataStoreFolderStructures ()
void doCommand (const QString &command, const QString &params, QString &result, int &status)
void enableCheckUpdates (bool enabled)
void externalProcessSlot (QString &name, QString &path, QStringList &args)
void gotOrderFab (QNetworkReply *)
void installNewParts ()
void loadedPart (int loaded, int total)
void newConnection (qintptr socketDescriptor)
void preferences ()
void preferencesAfter ()
void regenerateDatabaseFinished ()
void regeneratePartsDatabase ()
void topLevelWidgetDestroyed (QObject *)
void updateActivation ()
Signals
void spaceBarIsPressedSignal (bool)
Public Member Functions
FApplication (int &argc, char **argv)
~FApplication (void)
void finish ()
int init ()
bool loadReferenceModel (const QString &databaseName, bool fullLoad)
bool loadReferenceModel (const QString &databaseName, bool fullLoad, ReferenceModel *referenceModel)
class MainWindow * openWindowForService (bool lockFiles, int initialTab)
void registerFonts ()
bool runAsService ()
int serviceStartup ()
int startup ()
Static Public Member Functions
static bool spaceBarIsPressed ()
Protected Types
enum ServiceType {
PanelizerService = 1, InscriptionService, GerberService, GedaService,
KicadSchematicService, KicadFootprintService, ExampleService, DatabaseService,
SvgService, PortService, DRCService, NoService
}
Protected Member Functions
void cleanFzzs ()
void cleanupBackups ()
void clearModels ()
void doLoadPrevious (MainWindow *)
bool event (QEvent *event)
bool eventFilter (QObject *obj, QEvent *event)
bool findTranslator (const QString &translationsPath)
void initBackups ()
void initFilesToLoad ()
void initServer ()
void initService ()
void initSplash (class FSplashScreen &splash)
QList< MainWindow * > loadLastOpenSketch ()
void loadNew (QString path)
void loadOne (class MainWindow *, QString path, int loaded)
void loadSomething (const QString &previousVersion)
bool notify (QObject *receiver, QEvent *e)
QList< MainWindow * > orderedTopLevelMainWindows ()
QList< class MainWindow * > recoverBackups ()
void regeneratePartsDatabaseAux (QDialog *progressDialog)
void registerFont (const QString &fontFile, bool reallyRegister)
void runDatabaseService ()
void runDRCService ()
void runExampleService ()
void runExampleService (QDir &)
void runGedaService ()
void runGerberService ()
void runGerberServiceAux ()
void runInscriptionService ()
void runKicadFootprintService ()
void runKicadSchematicService ()
void runPanelizerService ()
void runSvgService ()
void runSvgServiceAux ()
void updatePrefs (class PrefsDialog &prefsDialog)
Protected Attributes
QTimer m_activationTimer
QStringList m_arguments
QString m_buildType
QStringList m_externalProcessArgs
QString m_externalProcessName
QString m_externalProcessPath
QStringList m_filesToLoad
FServer * m_fServer = nullptr
QPointer< class FritzingWindow > m_lastTopmostWindow
QString m_libPath
QHash< QString, struct LockedFile * > m_lockedFiles
bool m_mousePressed = false
QList< QWidget * > m_orderedTopLevelWidgets
QString m_outputFolder
QString m_panelFilename
bool m_panelizerCustom = false
int m_portNumber = 0
QString m_portRootFolder
int m_progressIndex = 0
ReferenceModel * m_referenceModel = nullptr
ServiceType m_serviceType = NoService
bool m_spaceBarIsPressed = false
class FSplashScreen * m_splash = nullptr
bool m_started = false
QString m_translationPath
QTranslator m_translator
class UpdateDialog * m_updateDialog = nullptr
Member Enumeration Documentation
ServiceType
enum FApplication::ServiceType protected
Enumerator
PanelizerService
InscriptionService
GerberService
GedaService
KicadSchematicService
KicadFootprintService
ExampleService
DatabaseService
SvgService
PortService
DRCService
NoService
Constructor & Destructor Documentation
FApplication()
FApplication::FApplication (int & argc, char ** argv)
References m_arguments.
~FApplication()
FApplication::~FApplication (void)
References RatsnestColors::cleanup(), SearchLineEdit::cleanup(), PartFactory::cleanup(), FirstTimeHelpDialog::cleanup(), TranslatorListModel::cleanup(), ItemDrag::cleanup(), PropertyDefMaster::cleanup(), LockManager::cleanup(), TipsAndTricks::cleanup(), Version::cleanup(), CursorMaster::cleanup(), SvgIconWidget::cleanup(), FolderUtils::cleanup(), DebugDialog::cleanup(), PartsBinView::cleanup(), FSvgRenderer::cleanup(), HtmlInfoView::cleanup(), ViewLayer::cleanup(), Wire::cleanup(), PartsBinPaletteWidget::cleanup(), ItemBase::cleanup(), cleanupBackups(), clearModels(), and m_updateDialog.
Member Function Documentation
changeActivation
void FApplication::changeActivation (bool activate, QWidget * originator) slot
References m_activationTimer, and m_orderedTopLevelWidgets.
checkForUpdates [1/2]
void FApplication::checkForUpdates () slot
checkForUpdates [2/2]
void FApplication::checkForUpdates (bool atUserRequest) slot
References DebugDialog::debug(), enableCheckUpdates(), VersionChecker::ignore(), m_updateDialog, Version::makeRequestParamsString(), UpdateDialog::setAtUserRequest(), VersionChecker::setUrl(), and UpdateDialog::setVersionChecker().
cleanFzzs()
void FApplication::cleanFzzs () protected
References LockManager::checkLockedFiles(), LockManager::initLockedFiles(), LockManager::releaseLockedFiles(), and LockManager::SlowTime.
cleanupBackups()
void FApplication::cleanupBackups () protected
References MainWindow::BackupFolder, m_lockedFiles, and LockManager::releaseLockedFiles().
clearModels()
void FApplication::clearModels () protected
References PaletteModel::clearPartHash(), and m_referenceModel.
closeAllWindows2
void FApplication::closeAllWindows2 () slot
createUserDataStoreFolderStructures
void FApplication::createUserDataStoreFolderStructures () slot
References FolderUtils::copyBin(), FolderUtils::createUserDataStoreFolders(), PartFactory::initFolder(), BinManager::MyPartsBinLocation, BinManager::MyPartsBinTemplateLocation, BinManager::SearchBinLocation, and BinManager::SearchBinTemplateLocation.
doCommand
void FApplication::doCommand (const QString & command, const QString & params, QString & result, int & status) slot
References FolderUtils::createZipAndSaveTo(), TextUtils::getRandText(), m_outputFolder, m_portRootFolder, runGerberServiceAux(), and runSvgServiceAux().
doLoadPrevious()
void FApplication::doLoadPrevious (MainWindow *) protected
enableCheckUpdates
void FApplication::enableCheckUpdates (bool enabled) slot
References MainWindow::enableCheckUpdates().
event()
bool FApplication::event (QEvent * event) protected
References DebugDialog::debug(), loadNew(), m_filesToLoad, and m_started.
eventFilter()
bool FApplication::eventFilter (QObject * obj, QEvent * event) protected
References CursorMaster::block(), event(), CursorMaster::instance(), m_mousePressed, m_spaceBarIsPressed, spaceBarIsPressedSignal(), and CursorMaster::unblock().
externalProcessSlot
void FApplication::externalProcessSlot (QString & name, QString & path, QStringList & args) slot
References m_externalProcessArgs, m_externalProcessName, and m_externalProcessPath.
findTranslator()
bool FApplication::findTranslator (const QString & translationsPath) protected
References DebugDialog::debug(), and m_translator.
finish()
void FApplication::finish ()
References Version::versionString().
gotOrderFab
void FApplication::gotOrderFab (QNetworkReply * networkReply) slot
References ORDERFABENABLED.
init()
int FApplication::init ()
References DatabaseService, ExampleService, findTranslator(), FInitResultHelp, FInitResultNormal, FInitResultVersion, GedaService, GerberService, FolderUtils::getApplicationSubFolderPath(), FolderUtils::getLibraryPath(), AboutBox::initBuildType(), CursorMaster::initCursors(), RatsnestColors::initNames(), SvgIconWidget::initNames(), PinHeader::initNames(), PaletteModel::initNames(), Connector::initNames(), FSvgRenderer::initNames(), ViewLayer::initNames(), Wire::initNames(), BinManager::initNames(), MainWindow::initNames(), ItemBase::initNames(), InscriptionService, KicadFootprintService, KicadSchematicService, m_activationTimer, m_arguments, m_buildType, m_externalProcessArgs, m_externalProcessName, m_externalProcessPath, m_lastTopmostWindow, m_libPath, m_outputFolder, m_panelFilename, m_panelizerCustom, m_portNumber, m_portRootFolder, m_serviceType, m_started, m_translationPath, NoService, PanelizerService, PortService, FolderUtils::setApplicationPath(), FolderUtils::setAppPartsPath(), DebugDialog::setEnabled(), PaletteModel::setFzpOverrideFolder(), SvgService, and updateActivation().
initBackups()
void FApplication::initBackups () protected
References MainWindow::BackupFolder, LockManager::FastTime, LockManager::initLockedFiles(), and m_lockedFiles.
initFilesToLoad()
void FApplication::initFilesToLoad () protected
References m_arguments, and m_filesToLoad.
initServer()
void FApplication::initServer () protected
References FMessageBox::BlockMessages, DebugDialog::debug(), m_fServer, m_portNumber, and newConnection().
initService()
void FApplication::initService () protected
References createUserDataStoreFolderStructures(), loadReferenceModel(), and registerFonts().
initSplash()
void FApplication::initSplash (class FSplashScreen & splash) protected
References Version::date(), Version::gitVersion(), m_buildType, m_progressIndex, Version::majorVersion(), Version::minorSubVersion(), Version::minorVersion(), FSplashScreen::showMessage(), FSplashScreen::showPixmap(), FSplashScreen::showProgress(), and Version::year().
installNewParts
void FApplication::installNewParts () slot
References m_updateDialog, and regeneratePartsDatabaseAux().
loadedPart
void FApplication::loadedPart (int loaded, int total) slot
References LoadProgressEnd, LoadProgressStart, m_progressIndex, m_splash, and FSplashScreen::showProgress().
loadLastOpenSketch()
QList< MainWindow * > FApplication::loadLastOpenSketch () protected
References DebugDialog::debug(), MainWindow::loadWhich(), m_referenceModel, and MainWindow::newMainWindow().
loadNew()
void FApplication::loadNew (QString path) protected
References MainWindow::clearFileProgressDialog(), MainWindow::loadWhich(), m_referenceModel, and MainWindow::newMainWindow().
loadOne()
void FApplication::loadOne (class MainWindow * mw, QString path, int loaded) protected
References loadNew(), MainWindow::loadWhich(), and MainWindow::showFileProgressDialog().
loadReferenceModel() [1/2]
bool FApplication::loadReferenceModel (const QString & databaseName, bool fullLoad)
References CurrentReferenceModel, loadedPart(), m_referenceModel, and ItemBase::setReferenceModel().
loadReferenceModel() [2/2]
bool FApplication::loadReferenceModel (const QString & databaseName, bool fullLoad, ReferenceModel * referenceModel)
References DebugDialog::debug(), FolderUtils::getAppPartsSubFolder(), PartsChecker::getSha(), ReferenceModel::loadAll(), ReferenceModel::loadFromDB(), and ReferenceModel::setSha().
loadSomething()
void FApplication::loadSomething (const QString & previousVersion) protected
References MainWindow::addDefaultParts(), MainWindow::clearFileProgressDialog(), DebugDialog::debug(), FritzingBundleExtension(), FritzingSketchExtension(), MainWindow::hideTempPartsBin(), initBackups(), initFilesToLoad(), MainWindow::loadWhich(), m_filesToLoad, m_referenceModel, MainWindow::newMainWindow(), ProcessEventBlocker::processEvents(), recoverBackups(), and MainWindow::showWelcomeView().
newConnection
void FApplication::newConnection (qintptr socketDescriptor) slot
References doCommand().
notify()
bool FApplication::notify (QObject * receiver, QEvent * e) protected
References closeAllWindows2(), and FMessageBox::critical().
openWindowForService()
MainWindow * FApplication::openWindowForService (bool lockFiles, int initialTab)
References m_referenceModel, MainWindow::newMainWindow(), MainWindow::noBackup(), MainWindow::noSchematicConversion(), and MainWindow::setReportMissingModules().
orderedTopLevelMainWindows()
QList< MainWindow * > FApplication::orderedTopLevelMainWindows () protected
References m_orderedTopLevelWidgets.
preferences
void FApplication::preferences () slot
References preferencesAfter().
preferencesAfter
void FApplication::preferencesAfter () slot
References SketchWidget::curvyWires(), ProgramWindow::getAvailablePlatforms(), SketchWidget::getShortName(), PrefsDialog::initLayout(), PrefsDialog::initViewInfo(), m_translationPath, orderedTopLevelMainWindows(), MainWindow::programmingWidget(), MainWindow::sketchWidgets(), updatePrefs(), and SketchWidget::viewName().
recoverBackups()
QList< MainWindow * > FApplication::recoverBackups () protected
References LockManager::checkLockedFiles(), DebugDialog::debug(), LockManager::FastTime, FritzingBundleExtension(), FritzingSketchExtension(), RecoveryDialog::getFileList(), FolderUtils::getSaveFileName(), m_lockedFiles, m_referenceModel, MainWindow::mainLoad(), MainWindow::newMainWindow(), MainWindow::saveAsShareable(), and MainWindow::setCurrentFile().
regenerateDatabaseFinished
void FApplication::regenerateDatabaseFinished () slot
References RegenerateDatabaseThread::error(), UpdateDialog::installFinished(), m_updateDialog, RegenerateDatabaseThread::progressDialog(), and RegenerateDatabaseThread::referenceModel().
regeneratePartsDatabase
void FApplication::regeneratePartsDatabase () slot
References regeneratePartsDatabaseAux().
regeneratePartsDatabaseAux()
void FApplication::regeneratePartsDatabaseAux (QDialog * progressDialog) protected
References FMessageBox::BlockMessages, CurrentReferenceModel, FolderUtils::getAppPartsSubFolder(), and regenerateDatabaseFinished().
registerFont()
void FApplication::registerFont (const QString & fontFile, bool reallyRegister) protected
References DebugDialog::debug(), InstalledFonts::InstalledFontsList, and InstalledFonts::InstalledFontsNameMapper.
registerFonts()
void FApplication::registerFonts ()
References registerFont().
runAsService()
bool FApplication::runAsService ()
References initServer(), m_serviceType, NoService, PortService, and DebugDialog::setEnabled().
runDatabaseService()
void FApplication::runDatabaseService () protected
References createUserDataStoreFolderStructures(), loadReferenceModel(), m_outputFolder, and DebugDialog::setEnabled().
runDRCService()
void FApplication::runDRCService () protected
References Panelizer::checkDonuts(), PCBSketchWidget::checkLoadedTraces(), Panelizer::checkText(), DebugDialog::debug(), PCBSketchWidget::findBoard(), initService(), MainWindow::loadWhich(), m_outputFolder, m_started, MainWindow::newDesignRulesCheck(), openWindowForService(), MainWindow::pcbView(), SketchWidget::selectAllItems(), MainWindow::setCloseSilently(), DebugDialog::setEnabled(), and MainWindow::showPCBView().
runExampleService() [1/2]
void FApplication::runExampleService () protected
References FolderUtils::getApplicationSubFolderPath(), initService(), and m_started.
runExampleService() [2/2]
void FApplication::runExampleService (QDir & dir) protected
References DebugDialog::debug(), FritzingBundleExtension(), MainWindow::loadWhich(), openWindowForService(), runExampleService(), MainWindow::saveAsAux(), MainWindow::selectAllObsolete(), MainWindow::setCloseSilently(), FolderUtils::setOpenSaveFolderAux(), and MainWindow::swapObsolete().
runGedaService()
void FApplication::runGedaService () protected
References GedaElement2Svg::convert(), DebugDialog::debug(), m_outputFolder, and TextUtils::writeUtf8().
runGerberService()
void FApplication::runGerberService () protected
References initService(), and runGerberServiceAux().
runGerberServiceAux()
void FApplication::runGerberServiceAux () protected
References GerberGenerator::exportToGerber(), FritzingBundleExtension(), MainWindow::loadWhich(), m_outputFolder, m_started, openWindowForService(), MainWindow::pcbView(), MainWindow::setCloseSilently(), and FolderUtils::setOpenSaveFolderAux().
runInscriptionService()
void FApplication::runInscriptionService () protected
References Panelizer::inscribe(), m_arguments, m_panelFilename, and m_started.
runKicadFootprintService()
void FApplication::runKicadFootprintService () protected
References KicadModule2Svg::convert(), DebugDialog::debug(), KicadModule2Svg::listModules(), m_outputFolder, and TextUtils::writeUtf8().
runKicadSchematicService()
void FApplication::runKicadSchematicService () protected
References KicadSchematic2Svg::convert(), DebugDialog::debug(), KicadSchematic2Svg::listDefs(), m_outputFolder, and TextUtils::writeUtf8().
runPanelizerService()
void FApplication::runPanelizerService () protected
References m_panelFilename, m_panelizerCustom, m_started, and Panelizer::panelize().
runSvgService()
void FApplication::runSvgService () protected
References initService(), and runSvgServiceAux().
runSvgServiceAux()
void FApplication::runSvgServiceAux () protected
References ViewLayer::BreadboardView, MainWindow::exportSvg(), FritzingBundleExtension(), MainWindow::loadWhich(), m_outputFolder, m_started, openWindowForService(), ViewLayer::PCBView, ViewLayer::SchematicView, MainWindow::setCloseSilently(), MainWindow::setCurrentView(), FolderUtils::setOpenSaveFolderAux(), GraphicsUtils::StandardFritzingDPI, and ViewLayer::viewIDNaturalName().
serviceStartup()
int FApplication::serviceStartup ()
References MainWindow::clearFileProgressDialog(), DatabaseService, DebugDialog::debug(), DRCService, ExampleService, GedaService, GerberService, initService(), InscriptionService, KicadFootprintService, KicadSchematicService, m_outputFolder, m_referenceModel, m_serviceType, MainWindow::newMainWindow(), PanelizerService, PortService, runDatabaseService(), runDRCService(), runExampleService(), runGedaService(), runGerberService(), runInscriptionService(), runKicadFootprintService(), runKicadSchematicService(), runPanelizerService(), runSvgService(), and SvgService.
spaceBarIsPressed()
bool FApplication::spaceBarIsPressed () static
spaceBarIsPressedSignal
void FApplication::spaceBarIsPressedSignal (bool) signal
startup()
int FApplication::startup ()
References checkForUpdates(), cleanFzzs(), createUserDataStoreFolderStructures(), DebugDialog::debug(), enableCheckUpdates(), fritzingExtensions(), FolderUtils::getAppPartsSubFolderPath(), gotOrderFab(), initSplash(), installNewParts(), LoadProgressEnd, LoadProgressStart, loadReferenceModel(), loadSomething(), m_progressIndex, m_referenceModel, m_splash, m_started, m_updateDialog, Version::makeRequestParamsString(), ProcessEventBlocker::processEvents(), registerFonts(), UpdateDialog::setRepoPath(), ReferenceModel::sha(), FSplashScreen::showProgress(), and Version::versionString().
topLevelWidgetDestroyed
void FApplication::topLevelWidgetDestroyed (QObject * object) slot
References m_orderedTopLevelWidgets.
updateActivation
void FApplication::updateActivation () slot
References m_lastTopmostWindow, m_orderedTopLevelWidgets, MainWindow::restoreDocks(), and MainWindow::saveDocks().
updatePrefs()
void FApplication::updatePrefs (class PrefsDialog & prefsDialog) protected
References PrefsDialog::cleared(), SketchWidget::getShortName(), orderedTopLevelMainWindows(), MainWindow::redrawSketch(), MainWindow::setAutosaveEnabled(), MainWindow::setAutosavePeriod(), ItemBase::setConnectedColor(), SketchWidget::setCurvyWires(), PrefsDialog::settings(), ItemBase::setUnconnectedColor(), ZoomableGraphicsView::setWheelMapping(), and MainWindow::sketchWidgets().
Member Data Documentation
m_activationTimer
QTimer FApplication::m_activationTimer protected
m_arguments
QStringList FApplication::m_arguments protected
m_buildType
QString FApplication::m_buildType protected
m_externalProcessArgs
QStringList FApplication::m_externalProcessArgs protected
m_externalProcessName
QString FApplication::m_externalProcessName protected
m_externalProcessPath
QString FApplication::m_externalProcessPath protected
m_filesToLoad
QStringList FApplication::m_filesToLoad protected
m_fServer
FServer* FApplication::m_fServer = nullptr protected
m_lastTopmostWindow
QPointer<class FritzingWindow> FApplication::m_lastTopmostWindow protected
m_libPath
QString FApplication::m_libPath protected
m_lockedFiles
QHash<QString, struct LockedFile *> FApplication::m_lockedFiles protected
m_mousePressed
bool FApplication::m_mousePressed = false protected
m_orderedTopLevelWidgets
QList<QWidget *> FApplication::m_orderedTopLevelWidgets protected
m_outputFolder
QString FApplication::m_outputFolder protected
m_panelFilename
QString FApplication::m_panelFilename protected
m_panelizerCustom
bool FApplication::m_panelizerCustom = false protected
m_portNumber
int FApplication::m_portNumber = 0 protected
m_portRootFolder
QString FApplication::m_portRootFolder protected
m_progressIndex
int FApplication::m_progressIndex = 0 protected
m_referenceModel
ReferenceModel* FApplication::m_referenceModel = nullptr protected
m_serviceType
ServiceType FApplication::m_serviceType = NoService protected
m_spaceBarIsPressed
bool FApplication::m_spaceBarIsPressed = false protected
m_splash
class FSplashScreen* FApplication::m_splash = nullptr protected
m_started
bool FApplication::m_started = false protected
m_translationPath
QString FApplication::m_translationPath protected
m_translator
QTranslator FApplication::m_translator protected
m_updateDialog
class UpdateDialog* FApplication::m_updateDialog = nullptr protected
The documentation for this class was generated from the following files:
fapplication.h
fapplication.cpp