Fritzing: UpdateDialog Class Reference
UpdateDialog Class Reference
#include <updatedialog.h>
Signals
void enableAgainSignal (bool enable)
void installNewParts ()
Public Member Functions
UpdateDialog (QWidget *parent=0)
~UpdateDialog ()
void installFinished (const QString &error)
void setAtUserRequest (bool)
void setRepoPath (const QString &repoPath, const QString &shaFromDataBase)
void setVersionChecker (class VersionChecker *)
void updateProgress (double progress)
Protected Slots
void httpErrorSlot (QNetworkReply::NetworkError)
void httpPartsErrorSlot (QString error)
void jsonPartsErrorSlot (QString error)
void onCleanRepo (class ModFileDialog *modFileDialog)
void releasesAvailableSlot ()
void stopClose ()
void updateParts ()
void xmlErrorSlot (QXmlStreamReader::Error errorCode)
Protected Member Functions
void closeEvent (QCloseEvent *)
QString genTable (const QString &title, struct AvailableRelease *)
void handleError ()
void handlePartsError (const QString &error)
bool setAvailableReleases (const QList< struct AvailableRelease * > &availableReleases)
Protected Attributes
bool m_atUserRequest = false
QDialogButtonBox * m_buttonBox = nullptr
bool m_doClose = false
bool m_doQuit = false
QLabel * m_feedbackLabel = nullptr
PartsCheckerResult m_partsCheckerResult
QProgressBar * m_progressBar = nullptr
QString m_remoteSha
QString m_repoPath
QString m_shaFromDataBase
class VersionChecker * m_versionChecker = nullptr
Constructor & Destructor Documentation
UpdateDialog()
UpdateDialog::UpdateDialog (QWidget * parent = 0)
References m_buttonBox, m_doClose, m_doQuit, m_feedbackLabel, m_progressBar, m_versionChecker, s_maxProgress, stopClose(), sUpdatePartsMessage, and updateParts().
~UpdateDialog()
UpdateDialog::~UpdateDialog ()
References m_versionChecker.
Member Function Documentation
closeEvent()
void UpdateDialog::closeEvent (QCloseEvent * event) protected
References m_doClose, and m_doQuit.
enableAgainSignal
void UpdateDialog::enableAgainSignal (bool enable) signal
genTable()
QString UpdateDialog::genTable (const QString & title, struct AvailableRelease * release) protected
References AvailableRelease::dateTime, AvailableRelease::link, AvailableRelease::summary, and AvailableRelease::versionString.
handleError()
void UpdateDialog::handleError () protected
References DebugDialog::debug(), enableAgainSignal(), and m_feedbackLabel.
handlePartsError()
void UpdateDialog::handlePartsError (const QString & error) protected
References DebugDialog::debug(), enableAgainSignal(), and m_feedbackLabel.
httpErrorSlot
void UpdateDialog::httpErrorSlot (QNetworkReply::NetworkError) protected slot
References handleError().
httpPartsErrorSlot
void UpdateDialog::httpPartsErrorSlot (QString error) protected slot
References handlePartsError().
installFinished()
void UpdateDialog::installFinished (const QString & error)
References m_buttonBox, m_doClose, m_doQuit, m_feedbackLabel, and m_progressBar.
installNewParts
void UpdateDialog::installNewParts () signal
jsonPartsErrorSlot
void UpdateDialog::jsonPartsErrorSlot (QString error) protected slot
References handlePartsError().
onCleanRepo
void UpdateDialog::onCleanRepo (class ModFileDialog * modFileDialog) protected slot
References PartsChecker::cleanRepo(), enableAgainSignal(), m_buttonBox, m_feedbackLabel, m_partsCheckerResult, m_repoPath, m_shaFromDataBase, and sUpdatePartsMessage.
releasesAvailableSlot
void UpdateDialog::releasesAvailableSlot () protected slot
References ModFileDialog::addList(), VersionChecker::availableReleases(), PartsCheckerResult::changedFiles, enableAgainSignal(), PartsCheckerResult::errorMessage, m_atUserRequest, m_buttonBox, m_doClose, m_feedbackLabel, m_partsCheckerResult, m_remoteSha, m_repoPath, m_shaFromDataBase, m_versionChecker, PartsChecker::newPartsAvailable(), onCleanRepo(), PARTS_CHECKER_ERROR_LOCAL_DAMAGE, PARTS_CHECKER_ERROR_LOCAL_MODS, PARTS_CHECKER_ERROR_NONE, PARTS_CHECKER_ERROR_REMOTE, PARTS_CHECKER_ERROR_USED_GIT, PartsCheckerResult::partsCheckerError, PartsCheckerResult::reset(), setAvailableReleases(), ModFileDialog::setText(), sUpdatePartsMessage, and PartsCheckerResult::untrackedFiles.
setAtUserRequest()
void UpdateDialog::setAtUserRequest (bool atUserRequest)
References m_atUserRequest.
setAvailableReleases()
bool UpdateDialog::setAvailableReleases (const QList< struct AvailableRelease * > & availableReleases) protected
References genTable(), AvailableRelease::interim, m_atUserRequest, m_feedbackLabel, and AvailableRelease::versionString.
setRepoPath()
void UpdateDialog::setRepoPath (const QString & repoPath, const QString & shaFromDataBase)
References m_repoPath, and m_shaFromDataBase.
setVersionChecker()
void UpdateDialog::setVersionChecker (class VersionChecker * versionChecker)
References VersionChecker::fetch(), httpErrorSlot(), m_buttonBox, m_feedbackLabel, m_progressBar, m_versionChecker, releasesAvailableSlot(), VersionChecker::stop(), and xmlErrorSlot().
stopClose
void UpdateDialog::stopClose () protected slot
References enableAgainSignal(), m_versionChecker, and VersionChecker::stop().
updateParts
void UpdateDialog::updateParts () protected slot
References installNewParts(), m_buttonBox, m_doClose, m_feedbackLabel, m_progressBar, m_remoteSha, m_repoPath, and PartsChecker::updateParts().
updateProgress()
void UpdateDialog::updateProgress (double progress) virtual
Implements PartsCheckerUpdateInterface.
References m_progressBar, and s_maxProgress.
xmlErrorSlot
void UpdateDialog::xmlErrorSlot (QXmlStreamReader::Error errorCode) protected slot
References handleError().
Member Data Documentation
m_atUserRequest
bool UpdateDialog::m_atUserRequest = false protected
m_buttonBox
QDialogButtonBox* UpdateDialog::m_buttonBox = nullptr protected
m_doClose
bool UpdateDialog::m_doClose = false protected
m_doQuit
bool UpdateDialog::m_doQuit = false protected
m_feedbackLabel
QLabel* UpdateDialog::m_feedbackLabel = nullptr protected
m_partsCheckerResult
PartsCheckerResult UpdateDialog::m_partsCheckerResult protected
m_progressBar
QProgressBar* UpdateDialog::m_progressBar = nullptr protected
m_remoteSha
QString UpdateDialog::m_remoteSha protected
m_repoPath
QString UpdateDialog::m_repoPath protected
m_shaFromDataBase
QString UpdateDialog::m_shaFromDataBase protected
m_versionChecker
class VersionChecker* UpdateDialog::m_versionChecker = nullptr protected
The documentation for this class was generated from the following files:
version/updatedialog.h
version/updatedialog.cpp