Fritzing: ProcessEventBlocker Class Reference
ProcessEventBlocker Class Reference
#include <processeventblocker.h>
Static Public Member Functions
static void block ()
static bool isProcessing ()
static void processEvents ()
static void processEvents (int maxTime)
static void unblock ()
Protected Member Functions
ProcessEventBlocker ()
~ProcessEventBlocker ()
void _inc (int i)
bool _isProcessing ()
void _processEvents ()
void _processEvents (int maxTime)
Protected Attributes
int m_count
QMutex m_mutex
Static Protected Attributes
static ProcessEventBlocker * m_singleton = new ProcessEventBlocker()
Constructor & Destructor Documentation
ProcessEventBlocker()
ProcessEventBlocker::ProcessEventBlocker () protected
References m_count.
~ProcessEventBlocker()
ProcessEventBlocker::~ProcessEventBlocker () protected
Member Function Documentation
_inc()
void ProcessEventBlocker::_inc (int i) protected
References m_count, and m_mutex.
_isProcessing()
bool ProcessEventBlocker::_isProcessing () protected
References m_count, and m_mutex.
_processEvents() [1/2]
void ProcessEventBlocker::_processEvents () protected
References m_count, and m_mutex.
_processEvents() [2/2]
void ProcessEventBlocker::_processEvents (int maxTime) protected
References m_count, and m_mutex.
block()
void ProcessEventBlocker::block () static
References _inc(), and m_singleton.
isProcessing()
bool ProcessEventBlocker::isProcessing () static
References _isProcessing(), and m_singleton.
processEvents() [1/2]
void ProcessEventBlocker::processEvents () static
References _processEvents(), and m_singleton.
processEvents() [2/2]
void ProcessEventBlocker::processEvents (int maxTime) static
References _processEvents(), and m_singleton.
unblock()
void ProcessEventBlocker::unblock () static
References _inc(), and m_singleton.
Member Data Documentation
m_count
int ProcessEventBlocker::m_count protected
m_mutex
QMutex ProcessEventBlocker::m_mutex protected
m_singleton
ProcessEventBlocker * ProcessEventBlocker::m_singleton = new ProcessEventBlocker() static protected
The documentation for this class was generated from the following files:
processeventblocker.h
processeventblocker.cpp