Fritzing: ConsoleSettings Class Reference
ConsoleSettings Class Reference
#include <consolesettings.h>
Classes
struct Settings
Public Member Functions
ConsoleSettings (QWidget *parent=0)
~ConsoleSettings ()
void selectPortName (const QString portName)
Settings settings () const
Private Slots
void apply ()
void checkCustomBaudRatePolicy (int idx)
void showPortInfo (int idx)
Private Member Functions
void fillPortsInfo ()
void fillPortsParameters ()
void updateSettings ()
Private Attributes
Settings currentSettings
QIntValidator * intValidator
Ui::ConsoleSettings * ui
Constructor & Destructor Documentation
ConsoleSettings()
QT_USE_NAMESPACE ConsoleSettings::ConsoleSettings (QWidget * parent = 0) explicit
References apply(), checkCustomBaudRatePolicy(), fillPortsInfo(), fillPortsParameters(), intValidator, showPortInfo(), ui, and updateSettings().
~ConsoleSettings()
ConsoleSettings::~ConsoleSettings ()
References ui.
Member Function Documentation
apply
void ConsoleSettings::apply () private slot
References updateSettings().
checkCustomBaudRatePolicy
void ConsoleSettings::checkCustomBaudRatePolicy (int idx) private slot
References intValidator, and ui.
fillPortsInfo()
void ConsoleSettings::fillPortsInfo () private
References ui.
fillPortsParameters()
void ConsoleSettings::fillPortsParameters () private
References ui.
selectPortName()
void ConsoleSettings::selectPortName (const QString portName)
References currentSettings, ConsoleSettings::Settings::name, and ui.
settings()
ConsoleSettings::Settings ConsoleSettings::settings () const
References currentSettings.
showPortInfo
void ConsoleSettings::showPortInfo (int idx) private slot
References ui.
updateSettings()
void ConsoleSettings::updateSettings () private
References ConsoleSettings::Settings::baudRate, currentSettings, ConsoleSettings::Settings::dataBits, ConsoleSettings::Settings::flowControl, ConsoleSettings::Settings::localEchoEnabled, ConsoleSettings::Settings::name, ConsoleSettings::Settings::parity, ConsoleSettings::Settings::stopBits, ConsoleSettings::Settings::stringBaudRate, ConsoleSettings::Settings::stringDataBits, ConsoleSettings::Settings::stringFlowControl, ConsoleSettings::Settings::stringParity, ConsoleSettings::Settings::stringStopBits, and ui.
Member Data Documentation
currentSettings
Settings ConsoleSettings::currentSettings private
intValidator
QIntValidator* ConsoleSettings::intValidator private
ui
Ui::ConsoleSettings* ConsoleSettings::ui private
The documentation for this class was generated from the following files:
program/consolesettings.h
program/consolesettings.cpp