Fritzing: PartsBinView Class Reference
PartsBinView Class Reference abstract
#include <partsbinview.h>
Public Member Functions
PartsBinView (ReferenceModel *referenceModel, PartsBinPaletteWidget *parent)
virtual ~PartsBinView ()=default
void addPart (ModelPart *model, int position=-1)
bool contains (const QString &moduleID)
void dropEventAux (QDropEvent *event, bool justAppend=false)
virtual QList< QObject * > orderedChildren ()=0
virtual void reloadPart (const QString &moduleID)=0
void reloadParts (PaletteModel *model)
virtual void removePart (const QString &moduleID)=0
virtual void removeParts ()=0
virtual ItemBase * selectedItemBase ()=0
virtual ModelPart * selectedModelPart ()=0
void setInfoViewOnHover (bool infoViewOnHover)
virtual void setPaletteModel (PaletteModel *model, bool clear=false)
Static Public Member Functions
static void cleanup ()
static void removePartReference (const QString &moduleID)
Static Public Attributes
static QHash< QString, QString > TranslatedCategoryNames
Protected Member Functions
virtual void doClear ()
void dragMoveEnterEventAux (QDragMoveEvent *event)
virtual int itemIndexAt (const QPoint &pos, bool &trustIt)=0
void mousePressOnItem (const QPoint &dragStartPos, const QString &moduleId, const QSize &size, const QPointF &dataPoint=QPointF(0, 0), const QPoint &hotspot=QPoint(0, 0))
virtual void moveItem (int fromIndex, int toIndex)=0
void setItem (ModelPart *modelPart)
virtual int setItemAux (ModelPart *modelPart, int position=-1)=0
virtual void setSelected (int position, bool doEmit=false)=0
Protected Attributes
QPoint m_dragStartPos
bool m_infoViewOnHover = false
QHash< QString, class ItemBase * > m_itemBaseHash
PartsBinPaletteWidget * m_parent = nullptr
ReferenceModel * m_referenceModel = nullptr
Static Protected Attributes
static QHash< QString, class ItemBase * > ItemBaseHash
Constructor & Destructor Documentation
PartsBinView()
PartsBinView::PartsBinView (ReferenceModel * referenceModel, PartsBinPaletteWidget * parent)
References TranslatedCategoryNames.
~PartsBinView()
virtual PartsBinView::~PartsBinView () virtual default
Member Function Documentation
addPart()
void PartsBinView::addPart (ModelPart * model, int position = -1)
References setItemAux(), and setSelected().
cleanup()
void PartsBinView::cleanup () static
References ItemBaseHash.
contains()
bool PartsBinView::contains (const QString & moduleID)
References m_itemBaseHash.
doClear()
void PartsBinView::doClear () protected virtual
Reimplemented in PartsBinListView, and PartsBinIconView.
References m_itemBaseHash.
dragMoveEnterEventAux()
void PartsBinView::dragMoveEnterEventAux (QDragMoveEvent * event) protected
dropEventAux()
void PartsBinView::dropEventAux (QDropEvent * event, bool justAppend = false)
References PartsBinPaletteWidget::addPart(), PartsBinPaletteWidget::contains(), PartsBinPaletteWidget::copyFilesToContrib(), itemIndexAt(), m_dragStartPos, m_parent, m_referenceModel, moveItem(), ItemDrag::originator(), ReferenceModel::retrieveModelPart(), and PartsBinPaletteWidget::setDirty().
itemIndexAt()
virtual int PartsBinView::itemIndexAt (const QPoint & pos, bool & trustIt) protected pure virtual
Implemented in PartsBinListView, and PartsBinIconView.
mousePressOnItem()
void PartsBinView::mousePressOnItem (const QPoint & dragStartPos, const QString & moduleId, const QSize & size, const QPointF & dataPoint = QPointF(0,0), const QPoint & hotspot = QPoint(0,0)) protected
References ItemDrag::dragIsDone(), PartsBinPaletteWidget::isTempPartsBin(), m_dragStartPos, m_parent, ItemDrag::setOriginator(), and ItemDrag::setOriginatorIsTempBin().
moveItem()
virtual void PartsBinView::moveItem (int fromIndex, int toIndex) protected pure virtual
Implemented in PartsBinListView, and PartsBinIconView.
orderedChildren()
virtual QList<QObject*> PartsBinView::orderedChildren () pure virtual
Implemented in PartsBinIconView, and PartsBinListView.
reloadPart()
virtual void PartsBinView::reloadPart (const QString & moduleID) pure virtual
Implemented in PartsBinIconView, and PartsBinListView.
reloadParts()
void PartsBinView::reloadParts (PaletteModel * model)
References setPaletteModel().
removePart()
virtual void PartsBinView::removePart (const QString & moduleID) pure virtual
Implemented in PartsBinIconView, and PartsBinListView.
removePartReference()
void PartsBinView::removePartReference (const QString & moduleID) static
References ItemBaseHash.
removeParts()
virtual void PartsBinView::removeParts () pure virtual
Implemented in PartsBinIconView, and PartsBinListView.
selectedItemBase()
virtual ItemBase* PartsBinView::selectedItemBase () pure virtual
Implemented in PartsBinIconView, and PartsBinListView.
selectedModelPart()
virtual ModelPart* PartsBinView::selectedModelPart () pure virtual
Implemented in PartsBinIconView, and PartsBinListView.
setInfoViewOnHover()
void PartsBinView::setInfoViewOnHover (bool infoViewOnHover)
References m_infoViewOnHover.
setItem()
void PartsBinView::setItem (ModelPart * modelPart) protected
References setItemAux().
setItemAux()
virtual int PartsBinView::setItemAux (ModelPart * modelPart, int position = -1) protected pure virtual
Implemented in PartsBinListView, and PartsBinIconView.
setPaletteModel()
void PartsBinView::setPaletteModel (PaletteModel * model, bool clear = false) virtual
Reimplemented in PartsBinIconView.
References doClear(), ModelBase::root(), setItem(), and setItemAux().
setSelected()
virtual void PartsBinView::setSelected (int position, bool doEmit = false) protected pure virtual
Member Data Documentation
ItemBaseHash
QHash< QString, ItemBase * > PartsBinView::ItemBaseHash static protected
m_dragStartPos
QPoint PartsBinView::m_dragStartPos protected
m_infoViewOnHover
bool PartsBinView::m_infoViewOnHover = false protected
m_itemBaseHash
QHash<QString, class ItemBase *> PartsBinView::m_itemBaseHash protected
m_parent
PartsBinPaletteWidget* PartsBinView::m_parent = nullptr protected
m_referenceModel
ReferenceModel* PartsBinView::m_referenceModel = nullptr protected
TranslatedCategoryNames
QHash< QString, QString > PartsBinView::TranslatedCategoryNames static
The documentation for this class was generated from the following files:
partsbinpalette/partsbinview.h
partsbinpalette/partsbinview.cpp