Fritzing: PEToolView Class Reference
PEToolView Class Reference
#include <petoolview.h>
Signals
void busModeChanged (bool)
void connectorMetadataChanged (struct ConnectorMetadata *)
void getSpinAmount (double &)
void pickModeChanged (bool)
void removedConnector (const QDomElement &)
void switchedConnector (int)
void terminalPointChanged (const QString &how)
void terminalPointChanged (const QString &coord, double value)
Public Member Functions
PEToolView (QWidget *parent=NULL)
~PEToolView ()
int currentConnectorIndex ()
void enableConnectorChanges (bool enableTerminalPointDrag, bool enableTerminalPointControls, bool enableInfo, bool enableAssign)
void initConnectors (QList< QDomElement > *connectorList)
void setChildrenVisible (bool vis)
void setCurrentConnector (const QDomElement &)
void setCurrentConnector (int index)
void setTerminalPointCoords (QPointF)
void setTerminalPointLimits (QSizeF)
void showAssignedConnectors (const QDomDocument *svgDoc, ViewLayer::ViewID)
Protected Slots
void busModeChangedSlot (bool)
void buttonChangeTerminalPoint ()
void descriptionEntry ()
void getSpinAmountSlot (double &)
void nameEntry ()
void pickModeChangedSlot ()
void removeConnector ()
void switchConnector (QTreeWidgetItem *current, QTreeWidgetItem *previous)
void terminalPointEntry ()
void typeEntry ()
Protected Member Functions
void changeConnector ()
void hideConnectorListStuff ()
Protected Attributes
QPointer< QPushButton > m_assignButton
QPointer< QCheckBox > m_busModeBox
QList< QPushButton * > m_buttons
QPointer< QGroupBox > m_connectorInfoGroupBox
QPointer< QBoxLayout > m_connectorInfoLayout
QPointer< QWidget > m_connectorInfoWidget
QList< QDomElement > * m_connectorList
QPointer< QTreeWidget > m_connectorListWidget
QPointer< class PEGraphicsItem > m_pegi
QPointer< QLabel > m_terminalPointDragState
QPointer< QGroupBox > m_terminalPointGroupBox
QPointer< QDoubleSpinBox > m_terminalPointX
QPointer< QDoubleSpinBox > m_terminalPointY
QPointer< QLabel > m_units
Constructor & Destructor Documentation
PEToolView()
PEToolView::PEToolView (QWidget * parent = NULL)
References busModeChangedSlot(), buttonChangeTerminalPoint(), CheckImage, enableConnectorChanges(), getSpinAmount(), getSpinAmountSlot(), m_assignButton, m_busModeBox, m_buttons, m_connectorInfoGroupBox, m_connectorInfoLayout, m_connectorInfoWidget, m_connectorListWidget, m_pegi, m_terminalPointDragState, m_terminalPointGroupBox, m_terminalPointX, m_terminalPointY, m_units, NoCheckImage, PEUtils::Spacing, switchConnector(), and terminalPointEntry().
~PEToolView()
PEToolView::~PEToolView ()
Member Function Documentation
busModeChanged
void PEToolView::busModeChanged (bool) signal
busModeChangedSlot
void PEToolView::busModeChangedSlot (bool state) protected slot
References busModeChanged().
buttonChangeTerminalPoint
void PEToolView::buttonChangeTerminalPoint () protected slot
References terminalPointChanged().
changeConnector()
void PEToolView::changeConnector () protected
References connectorMetadataChanged(), PEUtils::fillInMetadata(), and m_connectorListWidget.
connectorMetadataChanged
void PEToolView::connectorMetadataChanged (struct ConnectorMetadata *) signal
currentConnectorIndex()
int PEToolView::currentConnectorIndex ()
References m_connectorListWidget.
descriptionEntry
void PEToolView::descriptionEntry () protected slot
References changeConnector().
enableConnectorChanges()
void PEToolView::enableConnectorChanges (bool enableTerminalPointDrag, bool enableTerminalPointControls, bool enableInfo, bool enableAssign)
References m_assignButton, m_connectorInfoWidget, m_terminalPointDragState, and m_terminalPointGroupBox.
getSpinAmount
void PEToolView::getSpinAmount (double &) signal
getSpinAmountSlot
void PEToolView::getSpinAmountSlot (double & d) protected slot
References getSpinAmount().
hideConnectorListStuff()
void PEToolView::hideConnectorListStuff () protected
References m_assignButton, m_connectorListWidget, and pickModeChangedSlot().
initConnectors()
void PEToolView::initConnectors (QList< QDomElement > * connectorList)
References m_connectorList, m_connectorListWidget, NoCheckImage, and switchConnector().
nameEntry
void PEToolView::nameEntry () protected slot
References changeConnector().
pickModeChanged
void PEToolView::pickModeChanged (bool) signal
pickModeChangedSlot
void PEToolView::pickModeChangedSlot () protected slot
References pickModeChanged().
removeConnector
void PEToolView::removeConnector () protected slot
References PEGraphicsItem::element(), m_connectorList, m_connectorListWidget, and removedConnector().
removedConnector
void PEToolView::removedConnector (const QDomElement &) signal
setChildrenVisible()
void PEToolView::setChildrenVisible (bool vis)
setCurrentConnector() [1/2]
void PEToolView::setCurrentConnector (const QDomElement & newConnector)
References hideConnectorListStuff(), m_connectorList, and m_connectorListWidget.
setCurrentConnector() [2/2]
void PEToolView::setCurrentConnector (int index)
References m_connectorListWidget, and switchConnector().
setTerminalPointCoords()
void PEToolView::setTerminalPointCoords (QPointF p)
References PEUtils::convertUnits(), m_terminalPointX, and m_terminalPointY.
setTerminalPointLimits()
void PEToolView::setTerminalPointLimits (QSizeF sz)
References m_terminalPointX, and m_terminalPointY.
showAssignedConnectors()
void PEToolView::showAssignedConnectors (const QDomDocument * svgDoc, ViewLayer::ViewID viewID)
References CheckImage, PEGraphicsItem::element(), TextUtils::findElementWithAttribute(), ViewLayer::getConnectorSvgIDs(), hideConnectorListStuff(), m_connectorList, m_connectorListWidget, and NoCheckImage.
switchConnector
void PEToolView::switchConnector (QTreeWidgetItem * current, QTreeWidgetItem * previous) protected slot
References PEGraphicsItem::element(), hideConnectorListStuff(), m_connectorInfoGroupBox, m_connectorInfoLayout, m_connectorInfoWidget, m_connectorList, m_terminalPointGroupBox, m_units, PEUtils::makeConnectorForm(), switchedConnector(), and PEUtils::Units.
switchedConnector
void PEToolView::switchedConnector (int) signal
terminalPointChanged [1/2]
void PEToolView::terminalPointChanged (const QString & how) signal
terminalPointChanged [2/2]
void PEToolView::terminalPointChanged (const QString & coord, double value) signal
terminalPointEntry
void PEToolView::terminalPointEntry () protected slot
References m_terminalPointX, m_terminalPointY, terminalPointChanged(), and PEUtils::unconvertUnits().
typeEntry
void PEToolView::typeEntry () protected slot
References changeConnector().
Member Data Documentation
m_assignButton
QPointer<QPushButton> PEToolView::m_assignButton protected
m_busModeBox
QPointer<QCheckBox> PEToolView::m_busModeBox protected
m_buttons
QList<QPushButton *> PEToolView::m_buttons protected
m_connectorInfoGroupBox
QPointer<QGroupBox> PEToolView::m_connectorInfoGroupBox protected
m_connectorInfoLayout
QPointer<QBoxLayout> PEToolView::m_connectorInfoLayout protected
m_connectorInfoWidget
QPointer<QWidget> PEToolView::m_connectorInfoWidget protected
m_connectorList
QList<QDomElement>* PEToolView::m_connectorList protected
m_connectorListWidget
QPointer<QTreeWidget> PEToolView::m_connectorListWidget protected
m_pegi
QPointer<class PEGraphicsItem> PEToolView::m_pegi protected
m_terminalPointDragState
QPointer<QLabel> PEToolView::m_terminalPointDragState protected
m_terminalPointGroupBox
QPointer<QGroupBox> PEToolView::m_terminalPointGroupBox protected
m_terminalPointX
QPointer<QDoubleSpinBox> PEToolView::m_terminalPointX protected
m_terminalPointY
QPointer<QDoubleSpinBox> PEToolView::m_terminalPointY protected
m_units
QPointer<QLabel> PEToolView::m_units protected
The documentation for this class was generated from the following files:
partseditor/petoolview.h
partseditor/petoolview.cpp