Fritzing: KicadModule2Svg Class Reference
KicadModule2Svg Class Reference
#include <kicadmodule2svg.h>
Public Types
enum PadLayer { ToCopper0, ToCopper1, UnableToTranslate }
Public Member Functions
KicadModule2Svg ()
QString convert (const QString &filename, const QString &moduleName, bool allowPadsAndPins)
Public Member Functions inherited from Kicad2Svg
Kicad2Svg ()
QString endMetadata ()
QString makeMetadata (const QString &filename, const QString &type, const QString &name)
Public Member Functions inherited from X2Svg
X2Svg ()
void checkXLimit (double x)
void checkYLimit (double y)
Static Public Member Functions
static QStringList listModules (const QString &filename)
Protected Member Functions
void checkLimits (int posX, int xSize, int posY, int ySize)
KicadModule2Svg::PadLayer convertPad (QTextStream &stream, QString &pad, QList< int > &numbers)
QString drawCPad (int posX, int posY, int xSize, int ySize, int drillX, int drillY, const QString &padName, int padNumber, const QString &padType, KicadModule2Svg::PadLayer)
int drawDArc (const QString &ds, QString &arc)
int drawDCircle (const QString &ds, QString &arc)
int drawDSegment (const QString &ds, QString &line)
QString drawHorizontalOblong (int posX, int posY, double xSize, double ySize, int drillX, int drillY, const QString &padType, KicadModule2Svg::PadLayer)
QString drawOblong (int posX, int posY, double xSize, double ySize, int drillX, int drillY, const QString &padType, KicadModule2Svg::PadLayer)
QString drawRPad (int posX, int posY, int xSize, int ySize, int drillX, int drillY, const QString &padName, int padNumber, const QString &padType, KicadModule2Svg::PadLayer)
QString drawVerticalOblong (int posX, int posY, double xSize, double ySize, int drillX, int drillY, const QString &padType, KicadModule2Svg::PadLayer)
QString getColor (KicadModule2Svg::PadLayer padLayer)
QString getID (int padNumber, KicadModule2Svg::PadLayer padLayer)
Protected Member Functions inherited from X2Svg
void initLimits ()
QString offsetMin (const QString &svg)
QString unquote (const QString &)
Protected Attributes
int m_nonConnectorNumber
Protected Attributes inherited from Kicad2Svg
QString m_description
QString m_title
Protected Attributes inherited from X2Svg
QString m_attribute
QString m_comment
double m_maxX
double m_maxY
double m_minX
double m_minY
Member Enumeration Documentation
PadLayer
enum KicadModule2Svg::PadLayer
Enumerator
ToCopper0
ToCopper1
UnableToTranslate
Constructor & Destructor Documentation
KicadModule2Svg()
KicadModule2Svg::KicadModule2Svg ()
Member Function Documentation
checkLimits()
void KicadModule2Svg::checkLimits (int posX, int xSize, int posY, int ySize) protected
References X2Svg::checkXLimit(), and X2Svg::checkYLimit().
convert()
QString KicadModule2Svg::convert (const QString & filename, const QString & moduleName, bool allowPadsAndPins)
References convertPad(), DebugDialog::debug(), drawDArc(), drawDCircle(), drawDSegment(), Kicad2Svg::endMetadata(), TextUtils::escapeAnd(), X2Svg::initLimits(), KicadSilkscreenBottom, KicadSilkscreenTop, X2Svg::m_attribute, X2Svg::m_comment, Kicad2Svg::m_description, X2Svg::m_maxX, X2Svg::m_maxY, X2Svg::m_minX, X2Svg::m_minY, m_nonConnectorNumber, Kicad2Svg::m_title, Kicad2Svg::makeMetadata(), TextUtils::makeSVGHeader(), X2Svg::offsetMin(), TextUtils::stripNonValidXMLCharacters(), ToCopper0, and ToCopper1.
convertPad()
KicadModule2Svg::PadLayer KicadModule2Svg::convertPad (QTextStream & stream, QString & pad, QList< int > & numbers) protected
References checkLimits(), DebugDialog::debug(), drawCPad(), drawOblong(), drawRPad(), getID(), TextUtils::svgTransform(), ToCopper0, ToCopper1, UnableToTranslate, and X2Svg::unquote().
drawCPad()
QString KicadModule2Svg::drawCPad (int posX, int posY, int xSize, int ySize, int drillX, int drillY, const QString & padName, int padNumber, const QString & padType, KicadModule2Svg::PadLayer padLayer) protected
References checkStrokeWidth(), drawOblong(), getColor(), getID(), and qMax().
drawDArc()
int KicadModule2Svg::drawDArc (const QString & ds, QString & arc) protected
References checkStrokeWidth(), X2Svg::checkXLimit(), and X2Svg::checkYLimit().
drawDCircle()
int KicadModule2Svg::drawDCircle (const QString & ds, QString & arc) protected
References checkStrokeWidth(), X2Svg::checkXLimit(), and X2Svg::checkYLimit().
drawDSegment()
int KicadModule2Svg::drawDSegment (const QString & ds, QString & line) protected
References checkStrokeWidth(), X2Svg::checkXLimit(), and X2Svg::checkYLimit().
drawHorizontalOblong()
QString KicadModule2Svg::drawHorizontalOblong (int posX, int posY, double xSize, double ySize, int drillX, int drillY, const QString & padType, KicadModule2Svg::PadLayer padLayer) protected
References checkStrokeWidth(), getColor(), and qMin().
drawOblong()
QString KicadModule2Svg::drawOblong (int posX, int posY, double xSize, double ySize, int drillX, int drillY, const QString & padType, KicadModule2Svg::PadLayer padLayer) protected
References drawHorizontalOblong(), and drawVerticalOblong().
drawRPad()
QString KicadModule2Svg::drawRPad (int posX, int posY, int xSize, int ySize, int drillX, int drillY, const QString & padName, int padNumber, const QString & padType, KicadModule2Svg::PadLayer padLayer) protected
References checkStrokeWidth(), drawOblong(), getColor(), getID(), qMax(), and qMin().
drawVerticalOblong()
QString KicadModule2Svg::drawVerticalOblong (int posX, int posY, double xSize, double ySize, int drillX, int drillY, const QString & padType, KicadModule2Svg::PadLayer padLayer) protected
References checkStrokeWidth(), getColor(), and qMin().
getColor()
QString KicadModule2Svg::getColor (KicadModule2Svg::PadLayer padLayer) protected
References ViewLayer::Copper0Color, ViewLayer::Copper1Color, DebugDialog::debug(), ToCopper0, and ToCopper1.
getID()
QString KicadModule2Svg::getID (int padNumber, KicadModule2Svg::PadLayer padLayer) protected
References m_nonConnectorNumber, FSvgRenderer::NonConnectorName, and ToCopper1.
listModules()
QStringList KicadModule2Svg::listModules (const QString & filename) static
Member Data Documentation
m_nonConnectorNumber
int KicadModule2Svg::m_nonConnectorNumber protected
The documentation for this class was generated from the following files:
svg/kicadmodule2svg.h
svg/kicadmodule2svg.cpp