Fritzing: ZoomSlider Class Reference
ZoomSlider Class Reference
#include <zoomslider.h>
Signals
void zoomChanged (double newZoom)
Public Member Functions
ZoomSlider (int maxValue, QWidget *parent=0)
void setValue (double)
double value ()
void zoomIn ()
void zoomOut ()
Static Public Attributes
static double ZoomStep = 0.0
Protected Slots
void minusClicked ()
void plusClicked ()
void sliderTextEdited (const QString &newText)
void sliderValueChanged (int newValue)
Protected Member Functions
void showEvent (QShowEvent *event)
void sliderTextEdited (const QString &newValue, bool doEmit)
void step (int direction)
Static Protected Member Functions
static void loadFactors ()
Protected Attributes
bool m_firstTime
QLineEdit * m_lineEdit
ZoomLabel * m_minusButton
ZoomLabel * m_plusButton
QSlider * m_slider
QLabel * m_suffix
Static Protected Attributes
static QList< double > ZoomFactors
Constructor & Destructor Documentation
ZoomSlider()
ZoomSlider::ZoomSlider (int maxValue, QWidget * parent = 0)
References loadFactors(), m_firstTime, m_lineEdit, m_minusButton, m_plusButton, m_slider, m_suffix, MIN_VALUE, minusClicked(), plusClicked(), ZoomLabel::setAutoRepeat(), ZoomLabel::setImages(), sliderTextEdited(), sliderValueChanged(), STARTING_VALUE, and ZoomFactors.
Member Function Documentation
loadFactors()
void ZoomSlider::loadFactors () static protected
References ZoomFactors, and ZoomStep.
minusClicked
void ZoomSlider::minusClicked () protected slot
References step().
plusClicked
void ZoomSlider::plusClicked () protected slot
References step().
setValue()
void ZoomSlider::setValue (double value)
References m_lineEdit, sliderTextEdited(), and value().
showEvent()
void ZoomSlider::showEvent (QShowEvent * event) protected
References m_firstTime, m_lineEdit, m_minusButton, m_plusButton, m_slider, and m_suffix.
sliderTextEdited [1/2]
void ZoomSlider::sliderTextEdited (const QString & newText) protected slot
sliderTextEdited() [2/2]
void ZoomSlider::sliderTextEdited (const QString & newValue, bool doEmit) protected
References m_slider, sliderValueChanged(), value(), and zoomChanged().
sliderValueChanged
void ZoomSlider::sliderValueChanged (int newValue) protected slot
References m_lineEdit, and zoomChanged().
step()
void ZoomSlider::step (int direction) protected
References setValue(), value(), zoomChanged(), and ZoomFactors.
value()
double ZoomSlider::value ()
References m_lineEdit.
zoomChanged
void ZoomSlider::zoomChanged (double newZoom) signal
zoomIn()
void ZoomSlider::zoomIn ()
References plusClicked().
zoomOut()
void ZoomSlider::zoomOut ()
References minusClicked().
Member Data Documentation
m_firstTime
bool ZoomSlider::m_firstTime protected
m_lineEdit
QLineEdit* ZoomSlider::m_lineEdit protected
m_minusButton
ZoomLabel* ZoomSlider::m_minusButton protected
m_plusButton
ZoomLabel* ZoomSlider::m_plusButton protected
m_slider
QSlider* ZoomSlider::m_slider protected
m_suffix
QLabel* ZoomSlider::m_suffix protected
ZoomFactors
QList< double > ZoomSlider::ZoomFactors static protected
ZoomStep
double ZoomSlider::ZoomStep = 0.0 static
The documentation for this class was generated from the following files:
utils/zoomslider.h
utils/zoomslider.cpp