Fritzing: AbstractStatesButton Class Reference
AbstractStatesButton Class Reference abstract
#include <abstractstatesbutton.h>
Public Member Functions
virtual ~AbstractStatesButton ()
void setDisabledIcon ()
void setEnabledIcon ()
void setPressedIcon ()
Protected Member Functions
virtual QString imagePrefix ()=0
virtual QString imageSubfix ()
virtual void setImage (const QPixmap &pixmap)=0
virtual void setupIcons (const QString &imageName, bool hasStates=true)
Protected Attributes
QPixmap m_disabledImage
QPixmap m_enabledImage
QPixmap m_pressedImage
Constructor & Destructor Documentation
~AbstractStatesButton()
virtual AbstractStatesButton::~AbstractStatesButton () inline virtual
Member Function Documentation
imagePrefix()
virtual QString AbstractStatesButton::imagePrefix () protected pure virtual
Implemented in SketchToolButton, AbstractImageButton, and AddRemoveConnectorButton.
imageSubfix()
virtual QString AbstractStatesButton::imageSubfix () inline protected virtual
setDisabledIcon()
void AbstractStatesButton::setDisabledIcon () inline
References m_disabledImage, and setImage().
setEnabledIcon()
void AbstractStatesButton::setEnabledIcon () inline
References m_enabledImage, and setImage().
setImage()
virtual void AbstractStatesButton::setImage (const QPixmap & pixmap) protected pure virtual
Implemented in SketchToolButton, and AbstractImageButton.
setPressedIcon()
void AbstractStatesButton::setPressedIcon () inline
References m_pressedImage, and setImage().
setupIcons()
virtual void AbstractStatesButton::setupIcons (const QString & imageName, bool hasStates = true) inline protected virtual
Reimplemented in SketchToolButton.
References imagePrefix(), imageSubfix(), m_disabledImage, m_enabledImage, and m_pressedImage.
Member Data Documentation
m_disabledImage
QPixmap AbstractStatesButton::m_disabledImage protected
m_enabledImage
QPixmap AbstractStatesButton::m_enabledImage protected
m_pressedImage
QPixmap AbstractStatesButton::m_pressedImage protected
The documentation for this class was generated from the following file:
utils/abstractstatesbutton.h