Fritzing: FixFontsDialog Class Reference
FixFontsDialog Class Reference
#include <fixfontsdialog.h>
Public Member Functions
FixFontsDialog (QWidget *parent, const QSet< QString > fontsTofix)
virtual ~FixFontsDialog ()
QSet< QString > fontsToFix ()
FixedFontsHash getFixedFontsHash ()
Static Public Member Functions
static FixedFontsHash fixFonts (QWidget *parent, const QSet< QString > fontsTofix, bool &cancelPressed)
Protected Member Functions
void createLine (QLayout *layout, const QString &brokenFont, const QStringList &items, int defaultIdx)
Protected Attributes
QList< class FixedFontComboBox * > m_fixedFonts
QSet< QString > m_fontsToFix
Constructor & Destructor Documentation
FixFontsDialog()
FixFontsDialog::FixFontsDialog (QWidget * parent, const QSet< QString > fontsTofix)
References createLine(), DebugDialog::debug(), InstalledFonts::InstalledFontsList, InstalledFonts::InstalledFontsNameMapper, and m_fontsToFix.
~FixFontsDialog()
FixFontsDialog::~FixFontsDialog () virtual
Member Function Documentation
createLine()
void FixFontsDialog::createLine (QLayout * layout, const QString & brokenFont, const QStringList & items, int defaultIdx) protected
References m_fixedFonts.
fixFonts()
FixedFontsHash FixFontsDialog::fixFonts (QWidget * parent, const QSet< QString > fontsTofix, bool & cancelPressed) static
References FixFontsDialog(), fontsToFix(), and getFixedFontsHash().
fontsToFix()
QSet< QString > FixFontsDialog::fontsToFix ()
References m_fontsToFix.
getFixedFontsHash()
FixedFontsHash FixFontsDialog::getFixedFontsHash ()
References FixedFontComboBox::brokenFont(), InstalledFonts::InstalledFontsNameMapper, and m_fixedFonts.
Member Data Documentation
m_fixedFonts
QList<class FixedFontComboBox *> FixFontsDialog::m_fixedFonts protected
m_fontsToFix
QSet<QString> FixFontsDialog::m_fontsToFix protected
The documentation for this class was generated from the following files:
partseditor/obsolete/fixfontsdialog.h
partseditor/obsolete/fixfontsdialog.cpp