Fritzing: StackTabBar Class Reference
StackTabBar Class Reference
#include <stacktabbar.h>
Public Slots
void setIndex ()
Public Member Functions
StackTabBar (class StackTabWidget *parent)
Protected Slots
void showContextMenu (const QPoint &point)
Protected Member Functions
void dragEnterEvent (QDragEnterEvent *event)
void dragLeaveEvent (QDragLeaveEvent *event)
void dragMoveEvent (QDragMoveEvent *event)
void dropEvent (QDropEvent *event)
bool mimeIsAction (const class QMimeData *m, const QString &action)
void paintEvent (QPaintEvent *event)
Protected Attributes
QTimer m_dragMoveTimer
class StackTabWidget * m_parent
Constructor & Destructor Documentation
StackTabBar()
StackTabBar::StackTabBar (class StackTabWidget * parent)
References m_dragMoveTimer, m_parent, setIndex(), and showContextMenu().
Member Function Documentation
dragEnterEvent()
void StackTabBar::dragEnterEvent (QDragEnterEvent * event) protected
References mimeIsAction().
dragLeaveEvent()
void StackTabBar::dragLeaveEvent (QDragLeaveEvent * event) protected
References m_dragMoveTimer.
dragMoveEvent()
void StackTabBar::dragMoveEvent (QDragMoveEvent * event) protected
References PartsBinPaletteWidget::allowsChanges(), DebugDialog::debug(), m_dragMoveTimer, m_parent, and mimeIsAction().
dropEvent()
void StackTabBar::dropEvent (QDropEvent * event) protected
References PartsBinPaletteWidget::allowsChanges(), PartsBinPaletteWidget::currentView(), PartsBinView::dropEventAux(), m_parent, and mimeIsAction().
mimeIsAction()
bool StackTabBar::mimeIsAction (const class QMimeData * m, const QString & action) protected
paintEvent()
void StackTabBar::paintEvent (QPaintEvent * event) protected
setIndex
void StackTabBar::setIndex () slot
showContextMenu
void StackTabBar::showContextMenu (const QPoint & point) protected slot
References PartsBinPaletteWidget::binContextMenu(), and m_parent.
Member Data Documentation
m_dragMoveTimer
QTimer StackTabBar::m_dragMoveTimer protected
m_parent
class StackTabWidget* StackTabBar::m_parent protected
The documentation for this class was generated from the following files:
partsbinpalette/binmanager/stacktabbar.h
partsbinpalette/binmanager/stacktabbar.cpp