Fritzing: utils/misc.h File Reference
misc.h File Reference
#include <QHash>
#include <QVector>
#include <QString>
#include <QDir>
#include <QDomElement>
#include <QStringList>
#include <QPair>
#include <QList>
#include <QPointF>
Macros
#define ALLMOUSEBUTTONS (Qt::LeftButton | Qt::MidButton | Qt::RightButton | Qt::XButton1 | Qt::XButton2)
#define getenvUser() getenv("USER")
Typedefs
typedef QPair< double, double > RealPair
Functions
Qt::KeyboardModifier altOrMetaModifier ()
static const QString FritzingBinExtension (".fzb")
static const QString FritzingBundledBinExtension (".fzbz")
static const QString FritzingBundledPartExtension (".fzpz")
static const QString FritzingBundleExtension (".fzz")
const QStringList & fritzingBundleExtensions ()
const QStringList & fritzingExtensions ()
static const QString FritzingPartExtension (".fzp")
static const QString FritzingSketchExtension (".fz")
static QRegExp IntegerFinder ("\\d+")
bool isParent (QObject *candidateParent, QObject *candidateChild)
static const QString OCRAFontName ("OCRA")
double qMax (float f, double d)
double qMax (double d, float f)
double qMin (float f, double d)
double qMin (double d, float f)
static const QString ResourcePath (":/resources/")
Variables
static QByteArray ___emptyByteArray___
static QDir ___emptyDir___
static QDomElement ___emptyElement___
static QString ___emptyString___
static QHash< QString, QString > ___emptyStringHash___
static QStringList ___emptyStringList___
static const int DockHeightDefault = 50
static const int DockWidthDefault = 300
static const QString FemaleSymbolString = QString("%1").arg(QChar(0x2640))
static const int InfoViewHeightDefault = 220
static const int InfoViewMinHeight = 50
static const QString MaleSymbolString = QString("%1").arg(QChar(0x2642))
static const int PartsBinHeightDefault = 240
Macro Definition Documentation
ALLMOUSEBUTTONS
#define ALLMOUSEBUTTONS (Qt::LeftButton | Qt::MidButton | Qt::RightButton | Qt::XButton1 | Qt::XButton2)
getenvUser
#define getenvUser () getenv("USER")
Typedef Documentation
RealPair
typedef QPair<double, double> RealPair
Function Documentation
altOrMetaModifier()
Qt::KeyboardModifier altOrMetaModifier ()
FritzingBinExtension()
static const QString FritzingBinExtension (".fzb") static
FritzingBundledBinExtension()
static const QString FritzingBundledBinExtension (".fzbz") static
FritzingBundledPartExtension()
static const QString FritzingBundledPartExtension (".fzpz") static
FritzingBundleExtension()
static const QString FritzingBundleExtension (".fzz") static
fritzingBundleExtensions()
const QStringList& fritzingBundleExtensions ()
References initializeExtensionList(), and p_fritzingBundleExtensions.
fritzingExtensions()
const QStringList& fritzingExtensions ()
References initializeExtensionList(), and p_fritzingExtensions.
FritzingPartExtension()
static const QString FritzingPartExtension (".fzp") static
FritzingSketchExtension()
static const QString FritzingSketchExtension (".fz") static
IntegerFinder()
static QRegExp IntegerFinder ("\\d+") static
isParent()
bool isParent (QObject * candidateParent, QObject * candidateChild)
OCRAFontName()
static const QString OCRAFontName ("OCRA") static
qMax() [1/2]
double qMax (float f, double d) inline
qMax() [2/2]
double qMax (double d, float f) inline
References qMax().
qMin() [1/2]
double qMin (float f, double d) inline
qMin() [2/2]
double qMin (double d, float f) inline
References qMin().
ResourcePath()
static const QString ResourcePath (":/resources/") static
Variable Documentation
___emptyByteArray___
QByteArray ___emptyByteArray___ static
___emptyDir___
QDir ___emptyDir___ static
___emptyElement___
QDomElement ___emptyElement___ static
___emptyString___
QString ___emptyString___ static
___emptyStringHash___
QHash<QString, QString> ___emptyStringHash___ static
___emptyStringList___
QStringList ___emptyStringList___ static
DockHeightDefault
const int DockHeightDefault = 50 static
DockWidthDefault
const int DockWidthDefault = 300 static
FemaleSymbolString
const QString FemaleSymbolString = QString("%1").arg(QChar(0x2640)) static
InfoViewHeightDefault
const int InfoViewHeightDefault = 220 static
InfoViewMinHeight
const int InfoViewMinHeight = 50 static
MaleSymbolString
const QString MaleSymbolString = QString("%1").arg(QChar(0x2642)) static
PartsBinHeightDefault
const int PartsBinHeightDefault = 240 static