Fritzing: SimpleEditableLabelWidget Class Reference
SimpleEditableLabelWidget Class Reference
#include <simpleeditablelabelwidget.h>
Signals
void textChanged (const QString &text)
Public Member Functions
SimpleEditableLabelWidget (QUndoStack *undoStack, QWidget *parent=0, const QString &text="", bool edited=false)
void setText (const QString &text, bool markAsEdited=true)
QString text ()
Protected Slots
void toEditionMode ()
void toStandardMode (bool markAsEdited=true)
Protected Member Functions
void keyPressEvent (QKeyEvent *event)
void mousePressEvent (QMouseEvent *event)
void swapMode ()
void swapWidgets (QWidget *toShow, QWidget *toHide)
void updateUndoStackIfNecessary ()
Protected Attributes
bool m_hasBeenEdited
volatile bool m_isInEditionMode
QLabel * m_label
QLineEdit * m_lineEdit
QUndoStack * m_undoStack
Constructor & Destructor Documentation
SimpleEditableLabelWidget()
SimpleEditableLabelWidget::SimpleEditableLabelWidget (QUndoStack * undoStack, QWidget * parent = 0, const QString & text = "", bool edited = false)
References m_hasBeenEdited, m_isInEditionMode, m_label, m_lineEdit, m_undoStack, text(), toStandardMode(), and updateUndoStackIfNecessary().
Member Function Documentation
keyPressEvent()
void SimpleEditableLabelWidget::keyPressEvent (QKeyEvent * event) protected
References m_isInEditionMode, m_label, setText(), and toStandardMode().
mousePressEvent()
void SimpleEditableLabelWidget::mousePressEvent (QMouseEvent * event) protected
References m_isInEditionMode, and swapMode().
setText()
void SimpleEditableLabelWidget::setText (const QString & text, bool markAsEdited = true)
References m_hasBeenEdited, m_label, text(), textChanged(), and updateUndoStackIfNecessary().
swapMode()
void SimpleEditableLabelWidget::swapMode () protected
References m_isInEditionMode, toEditionMode(), and toStandardMode().
swapWidgets()
void SimpleEditableLabelWidget::swapWidgets (QWidget * toShow, QWidget * toHide) protected
References m_isInEditionMode, and m_lineEdit.
text()
QString SimpleEditableLabelWidget::text ()
References m_label.
textChanged
void SimpleEditableLabelWidget::textChanged (const QString & text) signal
toEditionMode
void SimpleEditableLabelWidget::toEditionMode () protected slot
References m_label, m_lineEdit, and swapWidgets().
toStandardMode
void SimpleEditableLabelWidget::toStandardMode (bool markAsEdited = true) protected slot
References m_label, m_lineEdit, setText(), and swapWidgets().
updateUndoStackIfNecessary()
void SimpleEditableLabelWidget::updateUndoStackIfNecessary () protected
References m_hasBeenEdited, and m_undoStack.
Member Data Documentation
m_hasBeenEdited
bool SimpleEditableLabelWidget::m_hasBeenEdited protected
m_isInEditionMode
volatile bool SimpleEditableLabelWidget::m_isInEditionMode protected
m_label
QLabel* SimpleEditableLabelWidget::m_label protected
m_lineEdit
QLineEdit* SimpleEditableLabelWidget::m_lineEdit protected
m_undoStack
QUndoStack* SimpleEditableLabelWidget::m_undoStack protected
The documentation for this class was generated from the following files:
partseditor/obsolete/simpleeditablelabelwidget.h
partseditor/obsolete/simpleeditablelabelwidget.cpp