Fritzing: NonConnectorItem Class Reference
NonConnectorItem Class Reference
#include <nonconnectoritem.h>
Public Member Functions
NonConnectorItem (ItemBase *attachedTo)
~NonConnectorItem ()=default
ItemBase * attachedTo () const noexcept
long attachedToID ()
const QString & attachedToInstanceTitle ()
int attachedToItemType ()
const QString & attachedToTitle ()
constexpr bool hidden () const noexcept
constexpr bool inactive () const noexcept
constexpr bool isPath () const noexcept
constexpr bool layerHidden () const noexcept
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)
constexpr double radius () const noexcept
void setCircular (bool)
virtual void setHidden (bool hidden)
virtual void setInactive (bool inactivate)
void setIsPath (bool)
virtual void setLayerHidden (bool hidden)
void setRadius (double radius, double strokeWidth)
void setShape (QPainterPath &)
QPainterPath shape () const
constexpr double strokeWidth () const noexcept
Protected Types
enum Effectively { EffectivelyCircular = 1, EffectivelyRectangular, EffectivelyPolygonal, EffectivelyUnknown }
Protected Member Functions
constexpr bool doNotPaint () const noexcept
Protected Attributes
QPointer< ItemBase > m_attachedTo
bool m_circular = false
Effectively m_effectively = Effectively::EffectivelyUnknown
bool m_hidden = false
bool m_inactive = false
bool m_isPath = false
bool m_layerHidden = false
bool m_negativeOffsetRect = false
double m_negativePenWidth = 0.0
double m_opacity = 0.0
bool m_paint = false
double m_radius = 0.0
QPainterPath m_shape
double m_strokeWidth = 0.0
Member Enumeration Documentation
Effectively
enum NonConnectorItem::Effectively protected
Enumerator
EffectivelyCircular
EffectivelyRectangular
EffectivelyPolygonal
EffectivelyUnknown
Constructor & Destructor Documentation
NonConnectorItem()
NonConnectorItem::NonConnectorItem (ItemBase * attachedTo)
~NonConnectorItem()
NonConnectorItem::~NonConnectorItem () default
Member Function Documentation
attachedTo()
ItemBase* NonConnectorItem::attachedTo () const inline noexcept
References m_attachedTo.
attachedToID()
long NonConnectorItem::attachedToID ()
References attachedTo(), and ItemBase::id().
attachedToInstanceTitle()
const QString & NonConnectorItem::attachedToInstanceTitle ()
References ___emptyString___, attachedTo(), and ItemBase::instanceTitle().
attachedToItemType()
int NonConnectorItem::attachedToItemType ()
References m_attachedTo, and ModelPart::Unknown.
attachedToTitle()
const QString & NonConnectorItem::attachedToTitle ()
References ___emptyString___, attachedTo(), and ItemBase::title().
doNotPaint()
constexpr bool NonConnectorItem::doNotPaint () const inline protected noexcept
References m_hidden, m_inactive, m_layerHidden, and m_paint.
hidden()
constexpr bool NonConnectorItem::hidden () const inline noexcept
References m_hidden.
inactive()
constexpr bool NonConnectorItem::inactive () const inline noexcept
References m_inactive.
isPath()
constexpr bool NonConnectorItem::isPath () const inline noexcept
References m_isPath.
layerHidden()
constexpr bool NonConnectorItem::layerHidden () const inline noexcept
References m_layerHidden.
paint()
void NonConnectorItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0)
References doNotPaint(), EffectiveAdjustmentFactor, EffectivelyCircular, EffectivelyRectangular, m_circular, m_effectively, m_negativeOffsetRect, m_negativePenWidth, m_opacity, m_shape, m_strokeWidth, and qMin().
radius()
constexpr double NonConnectorItem::radius () const inline noexcept
References m_radius.
setCircular()
void NonConnectorItem::setCircular (bool circular)
References m_circular.
setHidden()
void NonConnectorItem::setHidden (bool hidden) virtual
Reimplemented in ConnectorItem.
References m_hidden.
setInactive()
void NonConnectorItem::setInactive (bool inactivate) virtual
Reimplemented in ConnectorItem.
References m_inactive.
setIsPath()
void NonConnectorItem::setIsPath (bool path)
References m_isPath.
setLayerHidden()
void NonConnectorItem::setLayerHidden (bool hidden) virtual
References m_layerHidden.
setRadius()
void NonConnectorItem::setRadius (double radius, double strokeWidth)
References m_circular, m_radius, m_strokeWidth, radius(), and strokeWidth().
setShape()
void NonConnectorItem::setShape (QPainterPath & pp)
References m_shape, and GraphicsUtils::shapeFromPath().
shape()
QPainterPath NonConnectorItem::shape () const
References EffectivelyCircular, m_circular, m_effectively, m_shape, and GraphicsUtils::shapeFromPath().
strokeWidth()
constexpr double NonConnectorItem::strokeWidth () const inline noexcept
References m_strokeWidth.
Member Data Documentation
m_attachedTo
QPointer<ItemBase> NonConnectorItem::m_attachedTo protected
m_circular
bool NonConnectorItem::m_circular = false protected
m_effectively
Effectively NonConnectorItem::m_effectively = Effectively::EffectivelyUnknown protected
m_hidden
bool NonConnectorItem::m_hidden = false protected
m_inactive
bool NonConnectorItem::m_inactive = false protected
m_isPath
bool NonConnectorItem::m_isPath = false protected
m_layerHidden
bool NonConnectorItem::m_layerHidden = false protected
m_negativeOffsetRect
bool NonConnectorItem::m_negativeOffsetRect = false protected
m_negativePenWidth
double NonConnectorItem::m_negativePenWidth = 0.0 protected
m_opacity
double NonConnectorItem::m_opacity = 0.0 protected
m_paint
bool NonConnectorItem::m_paint = false protected
m_radius
double NonConnectorItem::m_radius = 0.0 protected
m_shape
QPainterPath NonConnectorItem::m_shape protected
m_strokeWidth
double NonConnectorItem::m_strokeWidth = 0.0 protected
The documentation for this class was generated from the following files:
connectors/nonconnectoritem.h
connectors/nonconnectoritem.cpp