Fritzing: AutorouteProgressDialog Class Reference
AutorouteProgressDialog Class Reference
#include <autorouteprogressdialog.h>
Public Slots
void disableButtons ()
void sendBest ()
void sendCancel ()
void sendSkip ()
void sendStop ()
void setMaximum (int)
void setMessage (const QString &)
void setMessage2 (const QString &)
void setMinimum (int)
void setSpinLabel (const QString &)
void setSpinValue (int)
void setValue (int)
Signals
void best ()
void cancel ()
void skip ()
void spinChange (int)
void stop ()
Public Member Functions
AutorouteProgressDialog (const QString &title, bool zoomAndPan, bool stopButton, bool bestButton, bool spin, class ZoomableGraphicsView *view, QWidget *parent=0)
~AutorouteProgressDialog ()
Protected Slots
void internalSpinChange (int)
Protected Member Functions
void closeEvent (QCloseEvent *)
Protected Attributes
QDialogButtonBox * m_buttonBox
QLabel * m_message
QLabel * m_message2
QProgressBar * m_progressBar
QSpinBox * m_spinBox
QLabel * m_spinLabel
Constructor & Destructor Documentation
AutorouteProgressDialog()
AutorouteProgressDialog::AutorouteProgressDialog (const QString & title, bool zoomAndPan, bool stopButton, bool bestButton, bool spin, class ZoomableGraphicsView * view, QWidget * parent = 0)
References best(), internalSpinChange(), m_buttonBox, m_message, m_message2, m_progressBar, m_spinBox, m_spinLabel, ScrollAmount, sendBest(), sendCancel(), and sendStop().
~AutorouteProgressDialog()
AutorouteProgressDialog::~AutorouteProgressDialog ()
Member Function Documentation
best
void AutorouteProgressDialog::best () signal
cancel
void AutorouteProgressDialog::cancel () signal
closeEvent()
void AutorouteProgressDialog::closeEvent (QCloseEvent * event) protected
References sendCancel().
disableButtons
void AutorouteProgressDialog::disableButtons () slot
References m_buttonBox.
internalSpinChange
void AutorouteProgressDialog::internalSpinChange (int value) protected slot
References spinChange().
sendBest
void AutorouteProgressDialog::sendBest () slot
References best().
sendCancel
void AutorouteProgressDialog::sendCancel () slot
References cancel().
sendSkip
void AutorouteProgressDialog::sendSkip () slot
References skip().
sendStop
void AutorouteProgressDialog::sendStop () slot
References stop().
setMaximum
void AutorouteProgressDialog::setMaximum (int maximum) slot
References m_progressBar.
setMessage
void AutorouteProgressDialog::setMessage (const QString & text) slot
References m_message.
setMessage2
void AutorouteProgressDialog::setMessage2 (const QString & text) slot
References m_message2.
setMinimum
void AutorouteProgressDialog::setMinimum (int minimum) slot
References m_progressBar.
setSpinLabel
void AutorouteProgressDialog::setSpinLabel (const QString & text) slot
References m_spinLabel.
setSpinValue
void AutorouteProgressDialog::setSpinValue (int value) slot
References m_spinBox.
setValue
void AutorouteProgressDialog::setValue (int value) slot
References m_progressBar.
skip
void AutorouteProgressDialog::skip () signal
spinChange
void AutorouteProgressDialog::spinChange (int) signal
stop
void AutorouteProgressDialog::stop () signal
Member Data Documentation
m_buttonBox
QDialogButtonBox* AutorouteProgressDialog::m_buttonBox protected
m_message
QLabel* AutorouteProgressDialog::m_message protected
m_message2
QLabel* AutorouteProgressDialog::m_message2 protected
m_progressBar
QProgressBar* AutorouteProgressDialog::m_progressBar protected
m_spinBox
QSpinBox* AutorouteProgressDialog::m_spinBox protected
m_spinLabel
QLabel* AutorouteProgressDialog::m_spinLabel protected
The documentation for this class was generated from the following files:
autoroute/autorouteprogressdialog.h
autoroute/autorouteprogressdialog.cpp