Fritzing: autoroute/drc.cpp File Reference
drc.cpp File Reference
#include "drc.h"
#include "../connectors/svgidlayer.h"
#include "../sketch/pcbsketchwidget.h"
#include "../debugdialog.h"
#include "../items/virtualwire.h"
#include "../items/tracewire.h"
#include "../items/via.h"
#include "../utils/graphicsutils.h"
#include "../utils/folderutils.h"
#include "../utils/textutils.h"
#include "../connectors/connectoritem.h"
#include "../items/moduleidnames.h"
#include "../processeventblocker.h"
#include "../fsvgrenderer.h"
#include "../viewlayer.h"
#include <qmath.h>
#include <QApplication>
#include <QMessageBox>
#include <QPixmap>
#include <QSet>
#include <QSettings>
#include <QDialogButtonBox>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QLabel>
#include <QListWidget>
#include <QRadioButton>
Functions
void allGs (QDomElement &element)
hide an element and its children from rendering
void appendChildElements (QDomElement parentElement, QList< QDomElement > &elementList)
append all immediate children of a dom element to an existing list
void collectGraphicNonNetElementIds (const QStringList &svgIDs, const QStringList &terminalIDs, ItemBase *itemBase, QStringList &notSvgIDs, QStringList &notTerminalIDs)
collect non-net connector id attribute values from part
bool containsLayer (const QString partDefinition, const QString layerName)
determine if an embedded part includes any copper layer(s)
QString getCollidingName (CollidingThing *collidingThing)
get name of the part that collided with something
QList< QDomElement > getPartConnectors (const QStringList &svgIDs, const QStringList &terminalIDs, const QStringList &notSvgIDs, const QStringList &notTerminalIDs, const QHash< QString, QString > &bothIDs, const QString &partID, const Markers &markers, const QDomElement &root)
collect dom elements for connectors of part in the current net
QByteArray getPartSvg (const QDomDocument *svgDomDocument, const QDomElement partRoot)
create svg text document string for a single part
QString getTextFileContent (QString filePath)
get the content of a text file
QList< QDomElement > markNonConnectorCopper (const QDomElement &root, const Markers &markers, const bool checkIntersection)
Split part copper into net and not net elements.
void markSubs (QDomElement &root, const QString &mark)
mark part (graphical) sub elements as belonging to net category
void matchCopperToConnectors (QDomDocument *doc, const QDomElement &root, const QList< QDomElement > toCheck, const Markers &markers, const QList< QDomElement > netElements)
link extra graphic elements to the associated connector
RenderThing pcbLayerRenderThing ()
prepare to render monochrome images of pcb content
bool pixelsCollide (QImage *image1, QImage *image2, QImage *image3, int x1, int y1, int x2, int y2, uint clr, QList< QPointF > &points)
detect pixels turned on inside a rectangle in both of 2 images
void splitSubs (QDomDocument *doc, const QDomElement &root, const QString &partID, const Markers &markers, const QStringList &svgIDs, const QStringList &terminalIDs, const QList< ItemBase * > &itemBases, const QHash< QString, QString > &bothIDs, const bool checkIntersection)
Split part connectors into net and not net elements.
Variables
static QString CancelledMessage
Function Documentation
allGs()
void allGs (QDomElement & element)
hide an element and its children from rendering
set element and all (recursively) nested child elements to 'g' elements
Parameters
element top (root) svg element to modify
appendChildElements()
void appendChildElements (QDomElement parentElement, QList< QDomElement > & elementList)
append all immediate children of a dom element to an existing list
Parameters
[in] parentElement source element to collect children from
[in,out] elementList existing list to append to
collectGraphicNonNetElementIds()
void collectGraphicNonNetElementIds (const QStringList & svgIDs, const QStringList & terminalIDs, ItemBase * itemBase, QStringList & notSvgIDs, QStringList & notTerminalIDs)
collect non-net connector id attribute values from part
collect id attribute values for connectors and terminals of a part that are not included in the current net (connections at equal potential)
Parameters
[in] svgIDs id attribute values for svg elements that are part of the current net
[in] terminalIDs id attribute values for svg terminal elements that are part of the current net
[in] itemBase the part
[out] notSvgIDs ids for svg elements that are not part of the net
[out] notTerminalIDs
References ItemBase::cachedConnectorItems(), ConnectorItem::connector(), Connector::fullPinInfo(), SvgIdLayer::m_svgId, SvgIdLayer::m_terminalId, ItemBase::viewID(), and ItemBase::viewLayerID().
containsLayer()
bool containsLayer (const QString partDefinition, const QString layerName)
determine if an embedded part includes any copper layer(s)
Parameters
[in] partDefinition string containing fzp (xml) definition for part
[in] layerName name of layer to check for
Returns
the part includes at least the specified layer (true or false)
getCollidingName()
QString getCollidingName (CollidingThing * collidingThing)
get name of the part that collided with something
Parameters
collidingThing
Returns
human readable identification of the part
References ItemBase::instanceTitle(), ItemBase::layerKinChief(), CollidingThing::nonConnectorItem, and ItemBase::title().
getPartConnectors()
QList<QDomElement> getPartConnectors (const QStringList & svgIDs, const QStringList & terminalIDs, const QStringList & notSvgIDs, const QStringList & notTerminalIDs, const QHash< QString, QString > & bothIDs, const QString & partID, const Markers & markers, const QDomElement & root)
collect dom elements for connectors of part in the current net
categorize graphic elements of the part by the net they are included in and collect all of the connectors that are part of the net.
Parameters
[in] svgIDs id attribute values for svg connector elements that are part of the current net
[in] terminalIDs id attribute values for svg terminal elements that are part of the current net
[in] notSvgIDs id attribute values for svg connector elements that are not part of the current net
[in] notTerminalIDs id attribute values for svg terminal elements that are not part of the current net
[in] bothIDs
[in] partID id of the part being split
[in] markers tag values to use for connector categorization
[in] root top/outer most svg dom element for part
Returns
svg elements that are labeled connectors in the current net
References appendChildElements(), Markers::inSvgAndID, Markers::inSvgID, Markers::inTerminalID, markSubs(), and Markers::outID.
getPartSvg()
QByteArray getPartSvg (const QDomDocument * svgDomDocument, const QDomElement partRoot)
create svg text document string for a single part
Parameters
[in] svgDomDocument source svg document
[in] partRoot top/outer most svg dom element for part
Returns
text containing complete SVG document for the part
getTextFileContent()
QString getTextFileContent (QString filePath)
get the content of a text file
Parameters
[in] filePath OS path to text file
Returns
string containing the file content
markNonConnectorCopper()
QList<QDomElement> markNonConnectorCopper (const QDomElement & root, const Markers & markers, const bool checkIntersection)
Split part copper into net and not net elements.
Parameters
[in] root top/outer most svg dom element for part
[in] markers tag values to use for connector categorization
[in] checkIntersection
Returns
part copper graphical elements to match with connectors
References appendChildElements(), and Markers::outID.
markSubs()
void markSubs (QDomElement & root, const QString & mark)
mark part (graphical) sub elements as belonging to net category
Recursively set a categorization marker tag value on a DOM element and its children
Parameters
[in,out] root (graphical) sub element of a part
[in] mark net (group) identification tag for root and nested elements
References appendChildElements().
matchCopperToConnectors()
void matchCopperToConnectors (QDomDocument * doc, const QDomElement & root, const QList< QDomElement > toCheck, const Markers & markers, const QList< QDomElement > netElements)
link extra graphic elements to the associated connector
add elements that are effectively part of a connector, but aren't separately labeled such as a rect which overlaps a (connection pad) circle, to the same network category as the connector.
Parameters
doc svg document containing part graphics
[in,out] root top/outer most svg dom element for part
[in] toCheck unlabeled connector pieces graphical elements
[in] markers tag values to use for connector categorization
[in] netElements svg elements that are labeled connectors in the current net
References getPartSvg(), Markers::inNoID, markSubs(), and Markers::outID.
pcbLayerRenderThing()
RenderThing pcbLayerRenderThing ()
prepare to render monochrome images of pcb content
Create and initialize instance instance to properly generate images of the PCB for copper collision detection
Returns
RenderThing initialized for creating single pcb layer image
References RenderThing::blackOnly, RenderThing::dpi, RenderThing::hideTerminalPoints, RenderThing::printerScale, RenderThing::renderBlocker, RenderThing::selectedItems, GraphicsUtils::StandardFritzingDPI, and GraphicsUtils::SVGDPI.
pixelsCollide()
bool pixelsCollide (QImage * image1, QImage * image2, QImage * image3, int x1, int y1, int x2, int y2, uint clr, QList< QPointF > & points)
detect pixels turned on inside a rectangle in both of 2 images
Set pixels to a specific color in one image that are on in a specified rectangular block in both of 2 other (monochrome and same dimensions) images. Accumulate coordinate points (up to 1000) of the identified (collision) pixels
Parameters
[in] image1 first monochrome input image
[in] image2 second monochrome input image
[out] image3 output image (does not need to be monochrome)
[in] x1 lower x coordinate bound of pixels to compare
[in] y1 lower y coordinate bound of pixels to compare
[in] x2 upper x coordinate bound of pixels to compare
[in] y2 upper y coordinate bound of pixels to compare
[in] clr colour for colliding pixels in the output image
[in,out] points location of pixels that collide in the input images
Returns
true when any collision(s) detected
References DRC::BitTable.
splitSubs()
void splitSubs (QDomDocument * doc, const QDomElement & root, const QString & partID, const Markers & markers, const QStringList & svgIDs, const QStringList & terminalIDs, const QList< ItemBase * > & itemBases, const QHash< QString, QString > & bothIDs, const bool checkIntersection)
Split part connectors into net and not net elements.
Parameters
[in,out] doc svg document containing part graphics
[in] root top/outer most svg dom element for part
[in] partID id of the part being split
[in] markers tag values to use for connector categorization
[in] svgIDs id attribute values for svg connector elements that are part of the current net
[in] terminalIDs id attribute values for svg terminal elements that are part of the current net
[in] itemBases
[in] bothIDs
[in] checkIntersection
References collectGraphicNonNetElementIds(), getPartConnectors(), markNonConnectorCopper(), and matchCopperToConnectors().
Variable Documentation
CancelledMessage
QString CancelledMessage static