Fritzing: Syntaxer Class Reference
Syntaxer Class Reference
#include <syntaxer.h>
Public Member Functions
Syntaxer ()
virtual ~Syntaxer ()
bool canProgram ()
const QStringList & extensions ()
const QString & extensionString ()
const CommentInfo * getCommentInfo (int ix)
bool hlCStringChar ()
bool loadSyntax (const QString &filename)
bool matchCommentStart (const QString &text, int offset, int &result, const CommentInfo *&resultCommentInfo)
bool matches (const QString &string, TrieLeaf *&leaf)
int matchStringEnd (const QString &text, int offset)
int matchStringStart (const QString &text, int offset)
Static Public Member Functions
static QString formatFromList (const QString &list)
static QString parseForName (const QString &filename)
Protected Member Functions
QChar getStringDelimiter (QDomElement &context)
void initListsToFormats (QDomElement &context)
void loadList (QDomElement &list)
Protected Attributes
bool m_canProgram = false
QList< CommentInfo * > m_commentInfo
QStringList m_extensions
QString m_extensionString
bool m_hlCStringChar = false
QString m_name
QChar m_stringDelimiter = 0
TrieNode * m_trieRoot = nullptr
Static Protected Attributes
static QHash< QString, QString > m_listsToFormats
Constructor & Destructor Documentation
Syntaxer()
Syntaxer::Syntaxer ()
References m_trieRoot.
~Syntaxer()
Syntaxer::~Syntaxer () virtual
References m_trieRoot.
Member Function Documentation
canProgram()
bool Syntaxer::canProgram ()
References m_canProgram.
extensions()
const QStringList & Syntaxer::extensions ()
References m_extensions.
extensionString()
const QString & Syntaxer::extensionString ()
References m_extensionString.
formatFromList()
QString Syntaxer::formatFromList (const QString & list) static
References ___emptyString___, and m_listsToFormats.
getCommentInfo()
const CommentInfo * Syntaxer::getCommentInfo (int ix)
References m_commentInfo.
getStringDelimiter()
QChar Syntaxer::getStringDelimiter (QDomElement & context) protected
hlCStringChar()
bool Syntaxer::hlCStringChar ()
References m_hlCStringChar.
initListsToFormats()
void Syntaxer::initListsToFormats (QDomElement & context) protected
References m_listsToFormats.
loadList()
void Syntaxer::loadList (QDomElement & list) protected
References TrieNode::addString(), TextUtils::findText(), m_trieRoot, and ProgramTab::text().
loadSyntax()
bool Syntaxer::loadSyntax (const QString & filename)
References extensions(), getStringDelimiter(), initListsToFormats(), loadList(), m_canProgram, m_commentInfo, m_extensions, m_extensionString, m_hlCStringChar, CommentInfo::m_index, m_name, m_stringDelimiter, and m_trieRoot.
matchCommentStart()
bool Syntaxer::matchCommentStart (const QString & text, int offset, int & result, const CommentInfo *& resultCommentInfo)
References CommentInfo::m_caseSensitive, m_commentInfo, CommentInfo::m_start, and ProgramTab::text().
matches()
bool Syntaxer::matches (const QString & string, TrieLeaf *& leaf)
References m_trieRoot, and TrieNode::matches().
matchStringEnd()
int Syntaxer::matchStringEnd (const QString & text, int offset)
References matchStringStart(), and ProgramTab::text().
matchStringStart()
int Syntaxer::matchStringStart (const QString & text, int offset)
References m_stringDelimiter, and ProgramTab::text().
parseForName()
QString Syntaxer::parseForName (const QString & filename) static
Member Data Documentation
m_canProgram
bool Syntaxer::m_canProgram = false protected
m_commentInfo
QList<CommentInfo *> Syntaxer::m_commentInfo protected
m_extensions
QStringList Syntaxer::m_extensions protected
m_extensionString
QString Syntaxer::m_extensionString protected
m_hlCStringChar
bool Syntaxer::m_hlCStringChar = false protected
m_listsToFormats
QHash< QString, QString > Syntaxer::m_listsToFormats static protected
m_name
QString Syntaxer::m_name protected
m_stringDelimiter
QChar Syntaxer::m_stringDelimiter = 0 protected
m_trieRoot
TrieNode* Syntaxer::m_trieRoot = nullptr protected
The documentation for this class was generated from the following files:
program/syntaxer.h
program/syntaxer.cpp