Fritzing: FDockWidget Class Reference
FDockWidget Class Reference
#include <fdockwidget.h>
Public Slots
void restoreState ()
Signals
void dockChangeActivationSignal (bool activate, QWidget *originator)
void positionChanged ()
Public Member Functions
FDockWidget (const QString &title, QWidget *parent=0)
void saveState ()
Protected Member Functions
bool event (QEvent *event)
void moveEvent (QMoveEvent *)
Protected Attributes
QString m_name
bool m_state
Constructor & Destructor Documentation
FDockWidget()
FDockWidget::FDockWidget (const QString & title, QWidget * parent = 0)
References m_state.
Member Function Documentation
dockChangeActivationSignal
void FDockWidget::dockChangeActivationSignal (bool activate, QWidget * originator) signal
event()
bool FDockWidget::event (QEvent * event) protected
References dockChangeActivationSignal().
moveEvent()
void FDockWidget::moveEvent (QMoveEvent * event) protected
References event(), and positionChanged().
positionChanged
void FDockWidget::positionChanged () signal
restoreState
void FDockWidget::restoreState () slot
References m_state.
saveState()
void FDockWidget::saveState ()
References m_state.
Member Data Documentation
m_name
QString FDockWidget::m_name protected
m_state
bool FDockWidget::m_state protected
The documentation for this class was generated from the following files:
mainwindow/fdockwidget.h
mainwindow/fdockwidget.cpp