Fritzing: ConnectorShared Class Reference
ConnectorShared Class Reference
#include <connectorshared.h>
Public Member Functions
ConnectorShared ()
ConnectorShared (const QDomElement &domElement)
~ConnectorShared ()
void addPin (ViewLayer::ViewID, const QString &svgId, ViewLayer::ViewLayerID, const QString &terminalId, const QString &legId, bool hybrid)
class BusShared * bus ()
const QString & busID ()
Connector::ConnectorType connectorType ()
const QString & connectorTypeString ()
const QString & description ()
class ErcData * ercData ()
SvgIdLayer * fullPinInfo (ViewLayer::ViewID viewId, ViewLayer::ViewLayerID viewLayerID)
const QString & id () const
void insertPin (ViewLayer::ViewID layer, SvgIdLayer *svgIdLayer)
const QString & legID (ViewLayer::ViewID viewId, ViewLayer::ViewLayerID viewLayerID)
const QMultiHash< ViewLayer::ViewID, SvgIdLayer * > & pins ()
void removePin (ViewLayer::ViewID layer, SvgIdLayer *svgIdLayer)
void removePins (ViewLayer::ViewID layer)
const QString & replacedby () const
void setBus (class BusShared *)
void setConnectorType (QString type)
void setConnectorType (Connector::ConnectorType)
void setDescription (QString description)
void setId (QString id)
void setReplacedby (QString)
void setSharedName (QString name)
const QString & sharedName ()
const QList< SvgIdLayer * > svgIdLayers () const
Protected Member Functions
void loadPin (QDomElement elem, ViewLayer::ViewID viewId)
void loadPins (const QDomElement &domElement)
Protected Attributes
class BusShared * m_bus
QString m_description
class ErcData * m_ercData
QString m_ercType
QString m_id
QString m_name
QMultiHash< ViewLayer::ViewID, SvgIdLayer * > m_pins
QString m_replacedby
Connector::ConnectorType m_type
QString m_typeString
Constructor & Destructor Documentation
ConnectorShared() [1/2]
ConnectorShared::ConnectorShared ()
References m_bus, m_description, m_ercData, m_id, m_name, m_type, m_typeString, and Connector::Unknown.
ConnectorShared() [2/2]
ConnectorShared::ConnectorShared (const QDomElement & domElement)
References Connector::connectorNameFromType(), Connector::connectorTypeFromName(), loadPins(), m_bus, m_description, m_ercData, m_id, m_name, m_pins, m_replacedby, SvgIdLayer::m_svgId, m_type, m_typeString, Connector::Pad, and Connector::Unknown.
~ConnectorShared()
ConnectorShared::~ConnectorShared ()
References m_ercData, and m_pins.
Member Function Documentation
addPin()
void ConnectorShared::addPin (ViewLayer::ViewID viewID, const QString & svgId, ViewLayer::ViewLayerID viewLayerID, const QString & terminalId, const QString & legId, bool hybrid)
References SvgIdLayer::m_hybrid, SvgIdLayer::m_legId, m_pins, SvgIdLayer::m_svgId, SvgIdLayer::m_svgViewLayerID, SvgIdLayer::m_terminalId, ItemBase::viewID(), and ItemBase::viewLayerID().
bus()
BusShared * ConnectorShared::bus ()
References m_bus.
busID()
const QString & ConnectorShared::busID ()
References ___emptyString___, BusShared::id(), and m_bus.
connectorType()
Connector::ConnectorType ConnectorShared::connectorType ()
References m_type.
connectorTypeString()
const QString & ConnectorShared::connectorTypeString ()
References m_typeString.
description()
const QString & ConnectorShared::description ()
References m_description.
ercData()
ErcData * ConnectorShared::ercData ()
References m_ercData.
fullPinInfo()
SvgIdLayer * ConnectorShared::fullPinInfo (ViewLayer::ViewID viewId, ViewLayer::ViewLayerID viewLayerID)
References m_pins, SvgIdLayer::m_svgViewLayerID, and ItemBase::viewLayerID().
id()
const QString & ConnectorShared::id () const
References m_id.
insertPin()
void ConnectorShared::insertPin (ViewLayer::ViewID layer, SvgIdLayer * svgIdLayer)
References m_pins.
legID()
const QString & ConnectorShared::legID (ViewLayer::ViewID viewId, ViewLayer::ViewLayerID viewLayerID)
References ___emptyString___, SvgIdLayer::m_legId, m_pins, SvgIdLayer::m_svgViewLayerID, and ItemBase::viewLayerID().
loadPin()
void ConnectorShared::loadPin (QDomElement elem, ViewLayer::ViewID viewId) protected
References SvgIdLayer::m_hybrid, SvgIdLayer::m_legId, m_pins, SvgIdLayer::m_svgId, SvgIdLayer::m_svgViewLayerID, SvgIdLayer::m_terminalId, ItemBase::viewID(), and ViewLayer::viewLayerIDFromXmlString().
loadPins()
void ConnectorShared::loadPins (const QDomElement & domElement) protected
References ViewLayer::BreadboardView, loadPin(), ViewLayer::PCBView, and ViewLayer::SchematicView.
pins()
const QMultiHash< ViewLayer::ViewID, SvgIdLayer * > & ConnectorShared::pins ()
References m_pins.
removePin()
void ConnectorShared::removePin (ViewLayer::ViewID layer, SvgIdLayer * svgIdLayer)
References m_pins.
removePins()
void ConnectorShared::removePins (ViewLayer::ViewID layer)
References m_pins.
replacedby()
const QString & ConnectorShared::replacedby () const
References m_replacedby.
setBus()
void ConnectorShared::setBus (class BusShared * bus)
References bus(), and m_bus.
setConnectorType() [1/2]
void ConnectorShared::setConnectorType (QString type)
References Connector::connectorTypeFromName(), m_type, and m_typeString.
setConnectorType() [2/2]
void ConnectorShared::setConnectorType (Connector::ConnectorType type)
References Connector::connectorNameFromType(), m_type, and m_typeString.
setDescription()
void ConnectorShared::setDescription (QString description)
References description(), and m_description.
setId()
void ConnectorShared::setId (QString id)
References id(), and m_id.
setReplacedby()
void ConnectorShared::setReplacedby (QString replacedby)
References m_replacedby, and replacedby().
setSharedName()
void ConnectorShared::setSharedName (QString name)
References m_name.
sharedName()
const QString & ConnectorShared::sharedName ()
References m_name.
svgIdLayers()
const QList< SvgIdLayer * > ConnectorShared::svgIdLayers () const
References m_pins.
Member Data Documentation
m_bus
class BusShared* ConnectorShared::m_bus protected
m_description
QString ConnectorShared::m_description protected
m_ercData
class ErcData* ConnectorShared::m_ercData protected
m_ercType
QString ConnectorShared::m_ercType protected
m_id
QString ConnectorShared::m_id protected
m_name
QString ConnectorShared::m_name protected
m_pins
QMultiHash<ViewLayer::ViewID, SvgIdLayer*> ConnectorShared::m_pins protected
m_replacedby
QString ConnectorShared::m_replacedby protected
m_type
Connector::ConnectorType ConnectorShared::m_type protected
m_typeString
QString ConnectorShared::m_typeString protected
The documentation for this class was generated from the following files:
connectors/connectorshared.h
connectors/connectorshared.cpp