Fritzing: ChangeWireCommand Class Reference
ChangeWireCommand Class Reference
#include <commands.h>
Public Member Functions
ChangeWireCommand (class SketchWidget *sketchWidget, long fromID, const QLineF &oldLine, const QLineF &newLine, QPointF oldPos, QPointF newPos, bool updateConnections, bool updateRatsnest, QUndoCommand *parent)
void redo ()
void undo ()
Public Member Functions inherited from BaseCommand
BaseCommand (BaseCommand::CrossViewType, SketchWidget *, QUndoCommand *parent)
~BaseCommand ()
void addSubCommand (BaseCommand *subCommand)
BaseCommand::CrossViewType crossViewType () const noexcept
virtual QString getDebugString () const
int index () const
const QUndoCommand * parentCommand () const
void redo ()
void setCrossViewType (BaseCommand::CrossViewType)
void setRedoOnly ()
void setSkipFirstRedo ()
void setUndoOnly ()
SketchWidget * sketchWidget () const
const BaseCommand * subCommand (int index) const
int subCommandCount () const
void subRedo ()
void subRedo (int index)
void subUndo ()
void subUndo (int index)
void undo ()
Protected Member Functions
QString getParamString () const
Protected Attributes
long m_fromID
QLineF m_newLine
QPointF m_newPos
QLineF m_oldLine
QPointF m_oldPos
bool m_updateConnections
bool m_updateRatsnest
Protected Attributes inherited from BaseCommand
QList< BaseCommand * > m_commands
BaseCommand::CrossViewType m_crossViewType
int m_index = 0
QUndoCommand * m_parentCommand = nullptr
bool m_redoOnly = false
SketchWidget * m_sketchWidget = nullptr
bool m_skipFirstRedo = false
bool m_undoOnly = false
Additional Inherited Members
Public Types inherited from BaseCommand
enum CrossViewType { SingleView, CrossView }
Static Public Member Functions inherited from BaseCommand
static void clearProgress ()
static CommandProgress * initProgress ()
static int totalChildCount (const QUndoCommand *)
Static Protected Attributes inherited from BaseCommand
static CommandProgress m_commandProgress
static int nextIndex = 0
Constructor & Destructor Documentation
ChangeWireCommand()
ChangeWireCommand::ChangeWireCommand (class SketchWidget * sketchWidget, long fromID, const QLineF & oldLine, const QLineF & newLine, QPointF oldPos, QPointF newPos, bool updateConnections, bool updateRatsnest, QUndoCommand * parent)
References m_fromID, m_newLine, m_newPos, m_oldLine, m_oldPos, m_updateConnections, and m_updateRatsnest.
Member Function Documentation
getParamString()
QString ChangeWireCommand::getParamString () const protected virtual
Reimplemented from BaseCommand.
References BaseCommand::getParamString(), m_fromID, m_newLine, m_newPos, m_oldLine, and m_oldPos.
redo()
void ChangeWireCommand::redo ()
References SketchWidget::changeWire(), m_fromID, m_newLine, m_newPos, BaseCommand::m_sketchWidget, BaseCommand::m_undoOnly, m_updateConnections, m_updateRatsnest, and BaseCommand::redo().
undo()
void ChangeWireCommand::undo ()
References SketchWidget::changeWire(), m_fromID, m_oldLine, m_oldPos, BaseCommand::m_redoOnly, BaseCommand::m_sketchWidget, m_updateConnections, m_updateRatsnest, and BaseCommand::undo().
Member Data Documentation
m_fromID
long ChangeWireCommand::m_fromID protected
m_newLine
QLineF ChangeWireCommand::m_newLine protected
m_newPos
QPointF ChangeWireCommand::m_newPos protected
m_oldLine
QLineF ChangeWireCommand::m_oldLine protected
m_oldPos
QPointF ChangeWireCommand::m_oldPos protected
m_updateConnections
bool ChangeWireCommand::m_updateConnections protected
m_updateRatsnest
bool ChangeWireCommand::m_updateRatsnest protected
The documentation for this class was generated from the following files:
commands.h
commands.cpp