Fritzing: FileProgressDialog Class Reference
FileProgressDialog Class Reference
#include <fileprogressdialog.h>
Public Slots
void addMaximum (int)
void incValue ()
void loadingInstanceSlot (class ModelBase *, QDomElement &instance)
void loadingInstancesSlot (class ModelBase *, QDomElement &instances)
void sendCancel ()
void setMaximum (int)
void setMessage (const QString &message)
void setMinimum (int)
void settingItemSlot ()
void setValue (int)
Signals
void cancel ()
Public Member Functions
FileProgressDialog (QWidget *parent=nullptr)
FileProgressDialog (const QString &title, int initialMaximum, QWidget *parent)
~FileProgressDialog ()
void setBinLoadingChunk (int)
void setBinLoadingCount (int)
void setIncValueMod (int)
void setIndeterminate ()
int value ()
Protected Slots
void updateIndeterminate ()
Protected Member Functions
void closeEvent (QCloseEvent *)
void init (const QString &title, int initialMaximum)
void resizeEvent (QResizeEvent *)
Protected Attributes
int m_binLoadingChunk = 0
int m_binLoadingCount = 0
double m_binLoadingInc = 0.0
int m_binLoadingIndex = 0
int m_binLoadingStart = 0
double m_binLoadingValue = 0.0
int m_incValueMod = 0
QLabel * m_message = nullptr
QProgressBar * m_progressBar = nullptr
QTimer m_timer
Constructor & Destructor Documentation
FileProgressDialog() [1/2]
FileProgressDialog::FileProgressDialog (QWidget * parent = nullptr)
References init().
FileProgressDialog() [2/2]
FileProgressDialog::FileProgressDialog (const QString & title, int initialMaximum, QWidget * parent)
References init(), and ProcessEventBlocker::processEvents().
~FileProgressDialog()
FileProgressDialog::~FileProgressDialog ()
References m_timer.
Member Function Documentation
addMaximum
void FileProgressDialog::addMaximum (int maximum) slot
References m_progressBar.
cancel
void FileProgressDialog::cancel () signal
closeEvent()
void FileProgressDialog::closeEvent (QCloseEvent * event) protected
incValue
void FileProgressDialog::incValue () slot
References m_incValueMod, m_progressBar, and ProcessEventBlocker::processEvents().
init()
void FileProgressDialog::init (const QString & title, int initialMaximum) protected
References m_message, and m_progressBar.
loadingInstanceSlot
void FileProgressDialog::loadingInstanceSlot (class ModelBase * , QDomElement & instance) slot
References settingItemSlot().
loadingInstancesSlot
void FileProgressDialog::loadingInstancesSlot (class ModelBase * , QDomElement & instances) slot
References m_binLoadingChunk, m_binLoadingCount, m_binLoadingInc, m_binLoadingIndex, m_binLoadingStart, m_binLoadingValue, and setValue().
resizeEvent()
void FileProgressDialog::resizeEvent (QResizeEvent * event) protected
sendCancel
void FileProgressDialog::sendCancel () slot
References cancel().
setBinLoadingChunk()
void FileProgressDialog::setBinLoadingChunk (int chunk)
References m_binLoadingChunk.
setBinLoadingCount()
void FileProgressDialog::setBinLoadingCount (int count)
References m_binLoadingCount, m_binLoadingIndex, m_binLoadingStart, and value().
setIncValueMod()
void FileProgressDialog::setIncValueMod (int mod)
References m_incValueMod.
setIndeterminate()
void FileProgressDialog::setIndeterminate ()
References m_progressBar, m_timer, and updateIndeterminate().
setMaximum
void FileProgressDialog::setMaximum (int maximum) slot
References m_progressBar.
setMessage
void FileProgressDialog::setMessage (const QString & message) slot
References m_message, and ProcessEventBlocker::processEvents().
setMinimum
void FileProgressDialog::setMinimum (int minimum) slot
References m_progressBar.
settingItemSlot
void FileProgressDialog::settingItemSlot () slot
References m_binLoadingInc, m_binLoadingValue, setValue(), and value().
setValue
void FileProgressDialog::setValue (int value) slot
References m_progressBar, ProcessEventBlocker::processEvents(), and value().
updateIndeterminate
void FileProgressDialog::updateIndeterminate () protected slot
References m_progressBar.
value()
int FileProgressDialog::value ()
References m_progressBar.
Member Data Documentation
m_binLoadingChunk
int FileProgressDialog::m_binLoadingChunk = 0 protected
m_binLoadingCount
int FileProgressDialog::m_binLoadingCount = 0 protected
m_binLoadingInc
double FileProgressDialog::m_binLoadingInc = 0.0 protected
m_binLoadingIndex
int FileProgressDialog::m_binLoadingIndex = 0 protected
m_binLoadingStart
int FileProgressDialog::m_binLoadingStart = 0 protected
m_binLoadingValue
double FileProgressDialog::m_binLoadingValue = 0.0 protected
m_incValueMod
int FileProgressDialog::m_incValueMod = 0 protected
m_message
QLabel* FileProgressDialog::m_message = nullptr protected
m_progressBar
QProgressBar* FileProgressDialog::m_progressBar = nullptr protected
m_timer
QTimer FileProgressDialog::m_timer protected
The documentation for this class was generated from the following files:
utils/fileprogressdialog.h
utils/fileprogressdialog.cpp