Fritzing: ItemDrag Class Reference
ItemDrag Class Reference
#include <itemdrag.h>
Signals
void dragIsDoneSignal (ItemDrag *)
Static Public Member Functions
static QHash< QObject *, QObject * > & cache ()
static void cleanup ()
static void dragIsDone ()
static QWidget * originator ()
static bool originatorIsTempBin ()
static void setOriginator (QWidget *)
static void setOriginatorIsTempBin (bool)
static ItemDrag * singleton ()
Protected Member Functions
ItemDrag (QObject *parent=0)
void __dragIsDone ()
Protected Attributes
QHash< QObject *, QObject * > m_cache
QPointer< QWidget > m_originator
bool m_originatorIsTempBin
Static Protected Attributes
static ItemDrag * Singleton = new ItemDrag()
Constructor & Destructor Documentation
ItemDrag()
ItemDrag::ItemDrag (QObject * parent = 0) protected
References m_originator, and m_originatorIsTempBin.
Member Function Documentation
__dragIsDone()
void ItemDrag::__dragIsDone () protected
References dragIsDoneSignal(), and m_cache.
cache()
QHash< QObject *, QObject * > & ItemDrag::cache () static
References m_cache, and Singleton.
cleanup()
void ItemDrag::cleanup () static
References Singleton.
dragIsDone()
void ItemDrag::dragIsDone () static
References __dragIsDone(), and Singleton.
dragIsDoneSignal
void ItemDrag::dragIsDoneSignal (ItemDrag *) signal
originator()
QWidget * ItemDrag::originator () static
References m_originator, and Singleton.
originatorIsTempBin()
bool ItemDrag::originatorIsTempBin () static
References m_originatorIsTempBin, and Singleton.
setOriginator()
void ItemDrag::setOriginator (QWidget * originator) static
References m_originator, originator(), and Singleton.
setOriginatorIsTempBin()
void ItemDrag::setOriginatorIsTempBin (bool itb) static
References m_originatorIsTempBin, and Singleton.
singleton()
ItemDrag * ItemDrag::singleton () static
References Singleton.
Member Data Documentation
m_cache
QHash<QObject *, QObject *> ItemDrag::m_cache protected
m_originator
QPointer<QWidget> ItemDrag::m_originator protected
m_originatorIsTempBin
bool ItemDrag::m_originatorIsTempBin protected
Singleton
ItemDrag * ItemDrag::Singleton = new ItemDrag() static protected
The documentation for this class was generated from the following files:
itemdrag.h
itemdrag.cpp