Fritzing: ChangeLegCurveCommand Class Reference
ChangeLegCurveCommand Class Reference
#include <commands.h>
Public Member Functions
ChangeLegCurveCommand (class SketchWidget *sketchWidget, long fromID, const QString &fromConnectorID, int index, const class Bezier *oldBezier, const class Bezier *newBezier, QUndoCommand *parent)
void redo ()
void undo ()
Public Member Functions inherited from BaseCommand
BaseCommand (BaseCommand::CrossViewType, SketchWidget *, QUndoCommand *parent)
~BaseCommand ()
void addSubCommand (BaseCommand *subCommand)
BaseCommand::CrossViewType crossViewType () const noexcept
virtual QString getDebugString () const
int index () const
const QUndoCommand * parentCommand () const
void redo ()
void setCrossViewType (BaseCommand::CrossViewType)
void setRedoOnly ()
void setSkipFirstRedo ()
void setUndoOnly ()
SketchWidget * sketchWidget () const
const BaseCommand * subCommand (int index) const
int subCommandCount () const
void subRedo ()
void subRedo (int index)
void subUndo ()
void subUndo (int index)
void undo ()
Protected Member Functions
QString getParamString () const
Protected Attributes
QString m_fromConnectorID
long m_fromID
int m_index
class Bezier * m_newBezier
class Bezier * m_oldBezier
Protected Attributes inherited from BaseCommand
QList< BaseCommand * > m_commands
BaseCommand::CrossViewType m_crossViewType
int m_index = 0
QUndoCommand * m_parentCommand = nullptr
bool m_redoOnly = false
SketchWidget * m_sketchWidget = nullptr
bool m_skipFirstRedo = false
bool m_undoOnly = false
Additional Inherited Members
Public Types inherited from BaseCommand
enum CrossViewType { SingleView, CrossView }
Static Public Member Functions inherited from BaseCommand
static void clearProgress ()
static CommandProgress * initProgress ()
static int totalChildCount (const QUndoCommand *)
Static Protected Attributes inherited from BaseCommand
static CommandProgress m_commandProgress
static int nextIndex = 0
Constructor & Destructor Documentation
ChangeLegCurveCommand()
ChangeLegCurveCommand::ChangeLegCurveCommand (class SketchWidget * sketchWidget, long fromID, const QString & fromConnectorID, int index, const class Bezier * oldBezier, const class Bezier * newBezier, QUndoCommand * parent)
References Bezier::copy(), BaseCommand::index(), m_fromConnectorID, m_fromID, m_index, m_newBezier, and m_oldBezier.
Member Function Documentation
getParamString()
QString ChangeLegCurveCommand::getParamString () const protected virtual
Reimplemented from BaseCommand.
References Bezier::cp0(), Bezier::cp1(), BaseCommand::getParamString(), m_fromID, m_newBezier, and m_oldBezier.
redo()
void ChangeLegCurveCommand::redo ()
References SketchWidget::changeLegCurve(), m_fromConnectorID, m_fromID, m_index, m_newBezier, BaseCommand::m_sketchWidget, BaseCommand::m_skipFirstRedo, BaseCommand::m_undoOnly, and BaseCommand::redo().
undo()
void ChangeLegCurveCommand::undo ()
References SketchWidget::changeLegCurve(), m_fromConnectorID, m_fromID, m_index, m_oldBezier, BaseCommand::m_sketchWidget, and BaseCommand::undo().
Member Data Documentation
m_fromConnectorID
QString ChangeLegCurveCommand::m_fromConnectorID protected
m_fromID
long ChangeLegCurveCommand::m_fromID protected
m_index
int ChangeLegCurveCommand::m_index protected
m_newBezier
class Bezier* ChangeLegCurveCommand::m_newBezier protected
m_oldBezier
class Bezier* ChangeLegCurveCommand::m_oldBezier protected
The documentation for this class was generated from the following files:
commands.h
commands.cpp