Fritzing: DRC Class Reference
DRC Class Reference
#include <drc.h>
Public Slots
void cancel ()
Signals
void hideProgress ()
void setMaximumProgress (int)
void setProgressMessage (const QString &)
void setProgressValue (int)
void wantBothVisible ()
void wantBottomVisible ()
void wantTopVisible ()
Public Member Functions
DRC (PCBSketchWidget *, ItemBase *board)
Design Rule Checks.
virtual ~DRC ()
QStringList start (bool showOkMessage, double keepoutMils)
Static Public Member Functions
static void extendBorder (double keepoutImagePixels, QImage *image)
static void splitNetPrep (QDomDocument *masterDoc, QList< ConnectorItem * > &equi, const Markers &, QList< QDomElement > &net, QList< QDomElement > &alsoNet, QList< QDomElement > &notNet, bool checkIntersection)
DRC::splitNetPrep.
Static Public Attributes
static const QString AlsoNet = "alsoNet"
static const uchar BitTable [] = { 128, 64, 32, 16, 8, 4, 2, 1 }
static const double KeepoutDefaultMils = 10
static const QString KeepoutSettingName
static const QString Net = "net"
static const QString NotNet = "notnet"
Protected Member Functions
void checkCopperBoth (QStringList &messages, QList< CollidingThing * > &collidingThings, double dpi)
locate embedded (not core) parts that are missing copper layer information
void checkHoles (QStringList &messages, QList< CollidingThing * > &collidingThings, double dpi)
locate part (mounting) holes that are too close to the edge of the board
CollidingThing * findItemsAt (QList< QPointF > &, ConnectorItem *already)
save information about part and location that failed DRC
bool makeBoard (QImage *, QRectF &sourceRes)
QList< ConnectorItem * > missingCopper (const QString &layerName, ViewLayer::ViewLayerID, ItemBase *, const QDomElement &svgRoot)
collect connector items that are missing pcb copper layer graphics
void splitNet (QDomDocument *, QList< ConnectorItem * > &, QImage *minusImage, QImage *plusImage, QRectF &sourceRes, ViewLayer::ViewLayerPlacement viewLayerPlacement, int index, double keepoutMils)
DRC::splitNet.
bool startAux (QString &message, QStringList &messages, QList< CollidingThing * > &, double keepoutMils)
do the actual rule check processing for a single PCB
void updateDisplay ()
Protected Attributes
ItemBase * m_board
bool m_cancelled
QImage * m_displayImage
QGraphicsPixmapItem * m_displayItem
double m_keepout
QHash< ViewLayer::ViewLayerPlacement, QDomDocument * > m_masterDocs
int m_maxProgress
QImage * m_minusImage
QImage * m_plusImage
PCBSketchWidget * m_sketchWidget
Private Member Functions
CollidingThing * generateCollisionData (const QRectF boardRect, NonConnectorItem *collidingItem, const double dpi)
generate record of part collision location
Constructor & Destructor Documentation
DRC()
DRC::DRC (PCBSketchWidget * sketchWidget, ItemBase * board)
Design Rule Checks.
Report conflicts with the defined printed circuit board design rules. Currently that is only the minimum separation between non electrically connected copper elements on each layer (side) of a single PCB in a sketch, and minimum separation of copper from the edge of the board.
Parameters
sketchWidget in memory PCB sketch
board single PCB within the sketch
References CancelledMessage.
~DRC()
DRC::~DRC () virtual
References m_displayImage, m_displayItem, m_masterDocs, m_minusImage, and m_plusImage.
Member Function Documentation
cancel
void DRC::cancel () slot
References m_cancelled.
checkCopperBoth()
void DRC::checkCopperBoth (QStringList & messages, QList< CollidingThing * > & collidingThings, double dpi) protected
locate embedded (not core) parts that are missing copper layer information
Parameters
[out] messages drc details for parts not following the rules
[out] collidingThings parts that have failed the design rules checks
dpi
References ConnectorItem::connectorSharedName(), containsLayer(), ViewLayer::Copper0, ViewLayer::Copper1, DebugDialog::debug(), generateCollisionData(), getCollidingName(), getTextFileContent(), ModelPart::isCore(), ItemBase::isEverVisible(), ItemBase::layerKinChief(), m_board, m_sketchWidget, missingCopper(), ItemBase::modelPart(), ModelPart::path(), setProgressMessage(), and updateDisplay().
checkHoles()
void DRC::checkHoles (QStringList & messages, QList< CollidingThing * > & collidingThings, double dpi) protected
locate part (mounting) holes that are too close to the edge of the board
Parameters
[out] messages drc details for parts not following the rules
[out] collidingThings parts that have failed the design rules checks
dpi
References NonConnectorItem::attachedToItemType(), ModelPart::CopperFill, generateCollisionData(), getCollidingName(), m_board, m_sketchWidget, setProgressMessage(), updateDisplay(), and ModelPart::Wire.
extendBorder()
void DRC::extendBorder (double keepoutImagePixels, QImage * image) static
findItemsAt()
CollidingThing * DRC::findItemsAt (QList< QPointF > & atPixels, ConnectorItem * collidingItem) protected
save information about part and location that failed DRC
Parameters
atPixels coordinate information for the where DRC failed
collidingItem the item that triggered the failure
Returns
References CollidingThing::atPixels, and CollidingThing::nonConnectorItem.
generateCollisionData()
CollidingThing * DRC::generateCollisionData (const QRectF boardRect, NonConnectorItem * collidingItem, const double dpi) private
generate record of part collision location
Parameters
boardRect pcb board bounding box
collidingItem part that failed a design rules check
dpi
References CollidingThing::atPixels, m_displayImage, CollidingThing::nonConnectorItem, and GraphicsUtils::SVGDPI.
hideProgress
void DRC::hideProgress () signal
makeBoard()
bool DRC::makeBoard (QImage * image, QRectF & sourceRes) protected
References ViewLayer::Board, SvgFileSplitter::changeColors(), DebugDialog::debug(), FolderUtils::getTopLevelUserDataStorePath(), m_board, m_sketchWidget, pcbLayerRenderThing(), and SketchWidget::renderToSVG().
missingCopper()
QList< ConnectorItem * > DRC::missingCopper (const QString & layerName, ViewLayer::ViewLayerID viewLayerID, ItemBase * itemBase, const QDomElement & root) protected
collect connector items that are missing pcb copper layer graphics
Parameters
layerName text name of the pcb layer (copper0 or copper1)
viewLayerID layer identifier
itemBase custom part in the sketch
root svg element for custom part pcb view
Returns
References ItemBase::cachedConnectorItems(), ConnectorItem::connector(), DebugDialog::debug(), TextUtils::findElementWithAttribute(), Connector::fullPinInfo(), ItemBase::id(), SvgIdLayer::m_svgId, and ItemBase::viewID().
setMaximumProgress
void DRC::setMaximumProgress (int) signal
setProgressMessage
void DRC::setProgressMessage (const QString &) signal
setProgressValue
void DRC::setProgressValue (int) signal
splitNet()
void DRC::splitNet (QDomDocument * masterDoc, QList< ConnectorItem * > & equi, QImage * minusImage, QImage * plusImage, QRectF & sourceRes, ViewLayer::ViewLayerPlacement viewLayerPlacement, int index, double keepoutMils) protected
DRC::splitNet.
Parameters
masterDoc svg for single board layer
equi all connectorItems that are in a single net
minusImage
plusImage
sourceRes
viewLayerPlacement newTop (0) or newBottom (1); only used to name debug png save files
index sequential number; only used to name debug png save files
keepoutMils
References AlsoNet, SvgFileSplitter::forceStrokeWidth(), FolderUtils::getTopLevelUserDataStorePath(), Markers::inNoID, Markers::inSvgAndID, Markers::inSvgID, Markers::inTerminalID, Net, Markers::outID, ItemBase::renderOne(), and splitNetPrep().
splitNetPrep()
void DRC::splitNetPrep (QDomDocument * masterDoc, QList< ConnectorItem * > & equi, const Markers & markers, QList< QDomElement > & net, QList< QDomElement > & alsoNet, QList< QDomElement > & notNet, bool checkIntersection) static
DRC::splitNetPrep.
Parameters
[in] masterDoc svg DOM for single board layer
[in] equi list of connector items at equal potential; a node
[in] markers
[in,out] net
[in,out] alsoNet
[in,out] notNet
[in] checkIntersection
References AlsoNet, appendChildElements(), NonConnectorItem::attachedTo(), ConnectorItem::connector(), ConnectorItem::debugInfo(), ItemBase::debugInfo(), Connector::fullPinInfo(), ItemBase::id(), ItemBase::itemType(), SvgIdLayer::m_svgId, SvgIdLayer::m_terminalId, markSubs(), Net, NotNet, splitSubs(), ItemBase::viewID(), ItemBase::viewLayerID(), and ModelPart::Wire.
start()
QStringList DRC::start (bool showOkMessage, double keepoutMils)
References FolderUtils::getTopLevelUserDataStorePath(), hideProgress(), m_displayImage, m_displayItem, m_maxProgress, m_sketchWidget, setProgressValue(), startAux(), and wantBothVisible().
startAux()
bool DRC::startAux (QString & message, QStringList & messages, QList< CollidingThing * > & collidingThings, double keepoutMils) protected
do the actual rule check processing for a single PCB
Parameters
[out] message processing summary message
[out] messages detected cases that did not pass the rules check
[out] collidingThings things not honoring the keep out distance
[in] keepoutMils minimal acceptable copper separation distance on a layer
Returns
the check ran to completion, or aborted before completion
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToItemType(), ConnectorItem::attachedToViewLayerID(), InfoGraphicsView::boardLayers(), CancelledMessage, checkCopperBoth(), checkHoles(), ConnectorItem::collectEqualPotential(), ViewLayer::copperLayers(), extendBorder(), findItemsAt(), SvgFileSplitter::forceStrokeWidth(), getCollidingName(), ItemBase::getRatsnest(), FolderUtils::getTopLevelUserDataStorePath(), PCBSketchWidget::getTraceFlag(), ViewLayer::GroundPlane0, ViewLayer::GroundPlane1, ItemBase::isEverVisible(), ItemBase::layerKinChief(), m_board, m_cancelled, m_displayImage, m_masterDocs, m_maxProgress, m_minusImage, m_plusImage, m_sketchWidget, makeBoard(), ViewLayer::NewBottom, ViewLayer::NewTop, ViewGeometry::NormalFlag, pcbLayerRenderThing(), ViewGeometry::PCBTraceFlag, pixelsCollide(), ProcessEventBlocker::processEvents(), qMax(), ViewGeometry::RatsnestFlag, ItemBase::renderOne(), SketchWidget::renderToSVG(), ViewGeometry::SchematicTraceFlag, setMaximumProgress(), setProgressMessage(), setProgressValue(), splitNet(), GraphicsUtils::SVGDPI, ItemBase::TranslatedPropertyNames, updateDisplay(), wantBottomVisible(), wantTopVisible(), and ModelPart::Wire.
updateDisplay()
void DRC::updateDisplay () protected
References SketchWidget::addItem(), m_board, m_displayImage, m_displayItem, m_sketchWidget, and ProcessEventBlocker::processEvents().
wantBothVisible
void DRC::wantBothVisible () signal
wantBottomVisible
void DRC::wantBottomVisible () signal
wantTopVisible
void DRC::wantTopVisible () signal
Member Data Documentation
AlsoNet
const QString DRC::AlsoNet = "alsoNet" static
Design Rules Checking The basic process is to render all of the copper on one layer for a single net (connected traces and pads) to a black and white image, then render all other copper for the layer to a separate image. Any pixels that are in both images indicate a collision. Repeat for each layer (top and bottom). Repeat for each net.
BitTable
const uchar DRC::BitTable = { 128, 64, 32, 16, 8, 4, 2, 1 } static
KeepoutDefaultMils
const double DRC::KeepoutDefaultMils = 10 static
KeepoutSettingName
const QString DRC::KeepoutSettingName static
m_board
ItemBase* DRC::m_board protected
m_cancelled
bool DRC::m_cancelled protected
m_displayImage
QImage* DRC::m_displayImage protected
m_displayItem
QGraphicsPixmapItem* DRC::m_displayItem protected
m_keepout
double DRC::m_keepout protected
m_masterDocs
QHash<ViewLayer::ViewLayerPlacement, QDomDocument *> DRC::m_masterDocs protected
m_maxProgress
int DRC::m_maxProgress protected
m_minusImage
QImage* DRC::m_minusImage protected
m_plusImage
QImage* DRC::m_plusImage protected
m_sketchWidget
PCBSketchWidget* DRC::m_sketchWidget protected
Net
const QString DRC::Net = "net" static
NotNet
const QString DRC::NotNet = "notnet" static
The documentation for this class was generated from the following files:
autoroute/drc.h
autoroute/drc.cpp