Fritzing: SVGView Class Reference
SVGView Class Reference
#include <svgview.h>
Public Member Functions
SVGView (const QString &name, QWidget *parent=0)
QGraphicsView * view () const
Private Slots
void importPCBXML ()
void print ()
void rotateLeft ()
void rotateRight ()
void zoomIn ()
void zoomOut ()
Private Member Functions
void drawPCBXML (QDomElement *pcbDocument)
void setupMatrix ()
Private Attributes
QDomDocument * m_domDocument
QGraphicsView * m_graphicsView
QLabel * m_label
QToolButton * m_loadPCBXMLButton
QSvgWidget * m_pcbWidget
PcbXML * m_pcbXML
QToolButton * m_printButton
QSvgRenderer * m_renderer
qreal m_rotation
QGraphicsScene m_scene
qreal m_zoom
Constructor & Destructor Documentation
SVGView()
SVGView::SVGView (const QString & name, QWidget * parent = 0)
References importPCBXML(), m_domDocument, m_graphicsView, m_label, m_loadPCBXMLButton, m_printButton, m_rotation, m_zoom, print(), rotateLeft(), rotateRight(), setupMatrix(), zoomIn(), and zoomOut().
Member Function Documentation
drawPCBXML()
void SVGView::drawPCBXML (QDomElement * pcbDocument) private
References PcbXML::getSvgFile(), m_graphicsView, m_pcbWidget, m_pcbXML, and m_scene.
importPCBXML
void SVGView::importPCBXML () private slot
References drawPCBXML(), and m_domDocument.
print
void SVGView::print () private slot
References m_graphicsView.
rotateLeft
void SVGView::rotateLeft () private slot
rotateRight
void SVGView::rotateRight () private slot
setupMatrix()
void SVGView::setupMatrix () private
References m_graphicsView, and m_rotation.
view()
QGraphicsView * SVGView::view () const
References m_graphicsView.
zoomIn
void SVGView::zoomIn () private slot
References m_zoom.
zoomOut
void SVGView::zoomOut () private slot
References m_zoom.
Member Data Documentation
m_domDocument
QDomDocument* SVGView::m_domDocument private
m_graphicsView
QGraphicsView* SVGView::m_graphicsView private
m_label
QLabel* SVGView::m_label private
m_loadPCBXMLButton
QToolButton* SVGView::m_loadPCBXMLButton private
m_pcbWidget
QSvgWidget* SVGView::m_pcbWidget private
m_pcbXML
PcbXML* SVGView::m_pcbXML private
m_printButton
QToolButton* SVGView::m_printButton private
m_renderer
QSvgRenderer* SVGView::m_renderer private
m_rotation
qreal SVGView::m_rotation private
m_scene
QGraphicsScene SVGView::m_scene private
m_zoom
qreal SVGView::m_zoom private
The documentation for this class was generated from the following files:
partseditor/obsolete/svgview.h
partseditor/obsolete/svgview.cpp