Fritzing: ItemBase Class Reference
ItemBase Class Reference abstract
#include <itembase.h>
Public Types
enum PluralType { Singular, Plural, NotSure }
Public Slots
void hidePartLabel ()
void partLabelChanged (const QString &newText)
void showInFolder ()
void showPartLabel (bool show, ViewLayer *)
virtual void swapEntry (const QString &text)
Public Member Functions
ItemBase (ModelPart *, ViewLayer::ViewID, const ViewGeometry &, long id, QMenu *itemMenu)
virtual ~ItemBase ()
virtual bool acceptsMouseDoubleClickConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual bool acceptsMouseMoveConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual bool acceptsMousePressConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual bool acceptsMousePressLegEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual bool acceptsMouseReleaseConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual void addedToScene (bool temporary)
virtual void addSticky (ItemBase *, bool stickem)
void addSubpart (ItemBase *)
virtual bool alreadySticking (ItemBase *itemBase)
ConnectorItem * anyConnectorItem ()
QRectF boundingRect () const
virtual QRectF boundingRectWithoutLegs () const
virtual void busConnectorItems (Bus *bus, ConnectorItem *, QList< ConnectorItem * > &items)
QList< Bus * > buses ()
const QList< ConnectorItem * > & cachedConnectorItems ()
const QList< ConnectorItem * > & cachedConnectorItemsConst () const
virtual void calcRotation (QTransform &rotation, QPointF center, ViewGeometry &)
virtual bool canEditPart ()
bool canFlip (Qt::Orientations)
bool canFlipHorizontal ()
bool canFlipVertical ()
virtual void clearConnectorHover ()
void clearConnectorItemCache ()
virtual void clearModelPart ()
void clearPartLabel ()
void collectConnectors (ConnectorPairHash &connectorHash, SkipCheckFunction)
virtual bool collectExtraInfo (QWidget *parent, const QString &family, const QString &prop, const QString &value, bool swappingEnabled, QString &returnProp, QString &returnValue, QWidget *&returnWidget, bool &hide)
virtual bool collectFemaleConnectees (QSet< ItemBase * > &items)
void collectPropsMap (QString &family, QMap< QString, QString > &)
virtual void collectWireConnectees (QSet< Wire * > &wires)
virtual void connectedMoved (ConnectorItem *from, ConnectorItem *to, QList< ConnectorItem * > &already)
virtual void connectionChange (ConnectorItem *onMe, ConnectorItem *onIt, bool connect)
virtual bool connectionIsAllowed (ConnectorItem *)
virtual void connectorHover (ConnectorItem *, ItemBase *, bool hovering)
const QString & constTitle () const
void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
void debugInfo (const QString &msg) const
void debugInfo2 (const QString &msg) const
virtual void doneLoading ()
void doRotateFlipPartLabel (double degrees, Qt::Orientations)
void ensureUniqueTitle (const QString &title, bool force)
QString family ()
virtual void figureHover ()
const QString & filename ()
virtual bool filterMousePressConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
ConnectorItem * findConnectorItemWithSharedID (const QString &connectorID, ViewLayer::ViewLayerPlacement)
ConnectorItem * findConnectorItemWithSharedID (const QString &connectorID)
virtual void findConnectorsUnder ()=0
ItemBase * findSubpart (const QString &connectorID, ViewLayer::ViewLayerPlacement)
virtual void flipItem (Qt::Orientations orientation)
virtual bool freeRotationAllowed ()
FSvgRenderer * fsvgRenderer () const
virtual void getConnectedColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
virtual const QCursor * getCursor (Qt::KeyboardModifiers)
virtual void getEqualPotentialColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
virtual void getHoverColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
virtual QString getInspectorTitle ()
virtual void getNormalColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
QPixmap * getPixmap (QSize size)
void getPixmaps (QPixmap *&, QPixmap *&, QPixmap *&, bool swappingEnabled, QSize)
virtual QString getProperty (const QString &key)
bool getRatsnest ()
virtual void getUnconnectedColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
ViewGeometry & getViewGeometry ()
bool hasConnections ()
bool hasConnectors ()
virtual bool hasCustomSVG ()
bool hasNonConnectors ()
virtual bool hasPartLabel ()
virtual bool hasPartNumberProperty ()
bool hasRubberBandLeg () const
constexpr bool hidden () const noexcept
virtual void hoverEnterConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
void hoverEnterConnectorItem ()
void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
virtual void hoverLeaveConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
void hoverLeaveConnectorItem ()
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
virtual void hoverMoveConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
virtual QPainterPath hoverShape () const
virtual void hoverUpdate ()
constexpr qint64 id () const noexcept
constexpr bool inactive () const noexcept
bool inHover ()
void initLayerAttributes (LayerAttributes &layerAttributes, ViewLayer::ViewID, ViewLayer::ViewLayerID, ViewLayer::ViewLayerPlacement, bool doConnectors, bool doCreateShape)
virtual bool inRotation ()
const QString & instanceTitle () const
virtual bool isBaseSticky ()
bool isEverVisible ()
bool isLocalSticky ()
bool isObsolete ()
bool isPartLabelVisible ()
virtual PluralType isPlural ()
virtual bool isSticky ()
virtual bool isSwappable ()
virtual bool itemMoved ()=0
int itemType () const
void killRubberBandLeg ()
QString label ()
constexpr bool layerHidden () const noexcept
virtual const QList< ItemBase * > & layerKin ()
virtual ItemBase * layerKinChief ()
QString makePartLabelSvg (bool blackOnly, double dpi, double printerScale)
ModelPart * modelPart ()
ModelPartShared * modelPartShared ()
const QString & moduleID ()
virtual void mouseDoubleClickConnectorEvent (ConnectorItem *)
virtual void mouseMoveConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual void mousePressConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
void mousePressEvent (QGraphicsSceneMouseEvent *event)
virtual void mouseReleaseConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual void moveItem (ViewGeometry &)=0
bool moveLock ()
void movePartLabel (QPointF newPos, QPointF newOffset)
virtual ConnectorItem * newConnectorItem (Connector *connector)
virtual ConnectorItem * newConnectorItem (ItemBase *layerkin, Connector *connector)
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
PartLabel * partLabel ()
void partLabelMoved (QPointF oldPos, QPointF oldOffset, QPointF newPos, QPointF newOffset)
QRectF partLabelSceneBoundingRect ()
QPointF partLabelScenePos ()
void partLabelSetHidden (bool hide)
ViewLayer::ViewLayerID partLabelViewLayerID ()
void prepareGeometryChange ()
virtual QHash< QString, QString > prepareProps (ModelPart *, bool wantDebug, QStringList &keys)
QString prop (const QString &p)
bool reloadRenderer (const QString &svg, bool fastload)
virtual void removeLayerKin ()
void removeTooltip ()
virtual void resetID ()
bool resetRenderer (const QString &svg)
bool resetRenderer (const QString &svg, QString &newSvg)
void resetValues (const QString &family, const QString &prop)
void restorePartLabel (QDomElement &labelGeometry, ViewLayer::ViewLayerID)
virtual QString retrieveSvg (ViewLayer::ViewLayerID, QHash< QString, QString > &svgHash, bool blackOnly, double dpi, double &factor)
ConnectorItem * rightClickedConnector ()
void rotateFlipPartLabel (double degrees, Qt::Orientations)
virtual void rotateItem (double degrees, bool includeRatsnest)
virtual bool rotation45Allowed ()
virtual bool rotationAllowed ()
virtual void saveGeometry ()=0
virtual void saveInstance (QXmlStreamWriter &)
virtual void saveInstanceLocation (QXmlStreamWriter &)=0
bool sceneEvent (QEvent *event)
const QPainterPath & selectionShape ()
virtual void setAcceptsMousePressLegEvent (bool)
void setCanFlipHorizontal (bool)
void setCanFlipVertical (bool)
virtual void setDropOffset (QPointF offset)
void setEverVisible (bool)
void setFilename (const QString &)
virtual void setHidden (bool hidden)
virtual void setInactive (bool inactivate)
virtual void setInRotation (bool)
virtual void setInspectorTitle (const QString &oldText, const QString &newText)
virtual void setInstanceTitle (const QString &title, bool initial)
void setItemIsSelectable (bool selectable)
virtual void setItemPos (QPointF &pos)
virtual void setLayerHidden (bool hidden)
void setLocalSticky (bool)
void setModelPart (ModelPart *)
virtual void setMoveLock (bool)
virtual void setProp (const QString &prop, const QString &value)
void setSharedRendererEx (FSvgRenderer *)
void setSquashShape (bool)
virtual void setSticky (bool)
void setSuperpart (ItemBase *)
virtual void setSwappable (bool)
void setTooltip ()
virtual void setTransform2 (const QTransform &)
FSvgRenderer * setUpImage (ModelPart *modelPart, LayerAttributes &)
void setViewLayerID (ViewLayer::ViewLayerID, const LayerHash &viewLayers)
void setViewLayerID (const QString &layerName, const LayerHash &viewLayers)
void setViewLayerPlacement (ViewLayer::ViewLayerPlacement)
void showConnectors (const QStringList &)
constexpr QSizeF size () const noexcept
virtual void slamZ (double newZ)
const QString & spice () const
const QString & spiceModel () const
virtual ItemBase * stickingTo ()
virtual bool stickyEnabled ()
virtual QList< QPointer< ItemBase > > stickyList ()
const QList< QPointer< ItemBase > > & subparts ()
ItemBase * superpart ()
virtual const QString & title ()
bool topLevel ()
virtual void transformItem (const QTransform &, bool includeRatsnest)
virtual void transformItem2 (const QMatrix &)
void updateConnections (ConnectorItem *, bool includeRatsnest, QList< ConnectorItem * > &already)
virtual void updateConnections (bool includeRatsnest, QList< ConnectorItem * > &already)
void updateConnectionsAux (bool includeRatsnest, QList< ConnectorItem * > &already)
void updateConnectors ()
void updatePartLabelInstanceTitle ()
virtual void updateTooltip ()
ViewLayer::ViewID viewID ()
QString & viewIDName ()
ViewLayer::ViewLayerID viewLayerID () const
ViewLayer::ViewLayerPlacement viewLayerPlacement () const
ViewGeometry::WireFlags wireFlags () const
virtual void writeGeometry (QXmlStreamWriter &)
virtual void writeXml (QXmlStreamWriter &)
double z ()
Static Public Member Functions
static void cleanup ()
static QColor connectedColor ()
static ItemBase * extractTopLevelItemBase (QGraphicsItem *thing)
static qint64 getNextID ()
static qint64 getNextID (qint64 fromIndex)
static void initNames ()
static void renderOne (QDomDocument *, QImage *, const QRectF &renderRect)
static void setConnectedColor (QColor &)
static void setReferenceModel (ReferenceModel *)
static void setUnconnectedColor (QColor &)
static QColor standardConnectedColor ()
static QColor standardUnconnectedColor ()
static QString translatePropertyName (const QString &key)
static QColor unconnectedColor ()
static bool zLessThan (ItemBase *&p1, ItemBase *&p2)
Static Public Attributes
static const QColor ConnectorHoverColor
static const double ConnectorHoverOpacity = .40
static const QList< ItemBase * > EmptyList
static const QColor HoverColor
static const double HoverOpacity = .20
static const QString ITEMBASE_FONT_PREFIX = "<font size='2'>"
static const QString ITEMBASE_FONT_SUFFIX = "</font>"
static QString PartInstanceDefaultTitle
static QHash< QString, QString > TranslatedPropertyNames
Protected Member Functions
virtual QStringList collectValues (const QString &family, const QString &prop, QString &value)
void createShape (LayerAttributes &layerAttributes)
QPixmap * getPixmap (ViewLayer::ViewID, bool swappingEnabled, QSize size)
QVariant itemChange (QGraphicsItem::GraphicsItemChange change, const QVariant &value)
virtual bool makeLocalModifications (QByteArray &svg, const QString &filename)
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
virtual void paintBody (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
virtual void paintHover (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
virtual void paintHover (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget, const QPainterPath &shape)
virtual void paintSelected (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
void saveLocAndTransform (QXmlStreamWriter &streamWriter)
virtual void setDefaultTooltip ()
void setInstanceTitleAux (const QString &title, bool initial)
void setInstanceTitleTooltip (const QString &text)
void updateHidden ()
virtual ViewLayer::ViewID useViewIDForPixmap (ViewLayer::ViewID, bool swappingEnabled)
Static Protected Member Functions
static bool fixCopper1 (ModelPart *modelPart, const QString &filename, ViewLayer::ViewLayerID viewLayerID, ViewLayer::ViewLayerPlacement, QDomDocument &)
static bool getFlipDoc (ModelPart *modelPart, const QString &filename, ViewLayer::ViewLayerID viewLayerID, ViewLayer::ViewLayerPlacement, QDomDocument &, Qt::Orientations)
Protected Attributes
bool m_acceptsMousePressLegEvent = true
QList< ConnectorItem * > m_cachedConnectorItems
bool m_canFlipHorizontal = false
bool m_canFlipVertical = false
int m_connectorHoverCount = 0
int m_connectorHoverCount2 = 0
bool m_everVisible = true
QString m_filename
FSvgRenderer * m_fsvgRenderer = nullptr
bool m_hasRubberBandLeg = false
bool m_hidden = false
int m_hoverCount = 0
bool m_hoverEnterSpaceBarWasPressed = false
qint64 m_id = 0
bool m_inactive = false
bool m_inRotation = false
QMenu * m_itemMenu = nullptr
bool m_layerHidden = false
QPointer< ModelPart > m_modelPart
bool m_moveLock = false
QGraphicsSvgItem * m_moveLockItem = nullptr
QPointer< PartLabel > m_partLabel
QMap< QString, QString > m_propsMap
ConnectorItem * m_rightClickedConnector = nullptr
QPainterPath m_selectionShape
QSizeF m_size
bool m_spaceBarWasPressed = false
bool m_squashShape = false
bool m_sticky = false
QGraphicsSvgItem * m_stickyItem = nullptr
QHash< long, QPointer< ItemBase > > m_stickyList
QList< QPointer< ItemBase > > m_subparts
QPointer< ItemBase > m_superpart
bool m_swappable = true
ViewGeometry m_viewGeometry
ViewLayer::ViewID m_viewID
ViewLayer::ViewLayerID m_viewLayerID
ViewLayer::ViewLayerPlacement m_viewLayerPlacement
bool m_zUninitialized = true
Static Protected Attributes
static QBrush ChosenBrush
static QPen ChosenPen
static QBrush ConnectedBrush
static QPen ConnectedPen
static QBrush EqualPotentialBrush
static QPen EqualPotentialPen
static QBrush HoverBrush
static QPen HoverPen
static long nextID
static QBrush NormalBrush
static constexpr double NormalConnectorOpacity = 0.4
static QPen NormalPen
static QPointer< ReferenceModel > TheReferenceModel = nullptr
static QBrush UnconnectedBrush
static QPen UnconnectedPen
Member Enumeration Documentation
PluralType
enum ItemBase::PluralType
Enumerator
Singular
Plural
NotSure
Constructor & Destructor Documentation
ItemBase()
ItemBase::ItemBase (ModelPart * modelPart, ViewLayer::ViewID viewID, const ViewGeometry & viewGeometry, long id, QMenu * itemMenu)
References m_modelPart, and CursorMaster::MoveCursor.
~ItemBase()
ItemBase::~ItemBase () virtual
References addSticky(), cachedConnectorItems(), ConnectorItem::connectedToItems(), m_fsvgRenderer, m_modelPart, m_partLabel, m_stickyList, and ConnectorItem::tempRemove().
Member Function Documentation
acceptsMouseDoubleClickConnectorEvent()
bool ItemBase::acceptsMouseDoubleClickConnectorEvent (ConnectorItem * , QGraphicsSceneMouseEvent *) virtual
Reimplemented in Wire.
acceptsMouseMoveConnectorEvent()
bool ItemBase::acceptsMouseMoveConnectorEvent (ConnectorItem * , QGraphicsSceneMouseEvent *) virtual
Reimplemented in Wire.
acceptsMousePressConnectorEvent()
bool ItemBase::acceptsMousePressConnectorEvent (ConnectorItem * , QGraphicsSceneMouseEvent *) virtual
Reimplemented in PaletteItemBase.
acceptsMousePressLegEvent()
bool ItemBase::acceptsMousePressLegEvent (ConnectorItem * , QGraphicsSceneMouseEvent *) virtual
References m_acceptsMousePressLegEvent.
acceptsMouseReleaseConnectorEvent()
bool ItemBase::acceptsMouseReleaseConnectorEvent (ConnectorItem * , QGraphicsSceneMouseEvent *) virtual
Reimplemented in Wire.
addedToScene()
void ItemBase::addedToScene (bool temporary) virtual
Reimplemented in Wire, ResizableBoard, NetLabel, Stripboard, SymbolPaletteItem, Note, SchematicFrame, Pad, LogoItem, Hole, JumperItem, Resistor, MysteryPart, Ruler, Perfboard, LED, PinHeader, GroundPlane, and Dip.
References instanceTitle(), isBaseSticky(), isLocalSticky(), setLocalSticky(), and setTooltip().
addSticky()
void ItemBase::addSticky (ItemBase * stickyBase, bool stickem) virtual
Reimplemented in LayerKinPaletteItem.
References addSticky(), id(), isBaseSticky(), layerKinChief(), and m_stickyList.
addSubpart()
void ItemBase::addSubpart (ItemBase * sub)
References Bus::addSubConnector(), Connector::bus(), ConnectorItem::bus(), cachedConnectorItems(), ConnectorItem::connector(), ConnectorItem::connectorSharedID(), debugInfo(), ModelPart::getConnector(), m_subparts, modelPart(), Connector::setBus(), and setSuperpart().
alreadySticking()
bool ItemBase::alreadySticking (ItemBase * itemBase) virtual
Reimplemented in LayerKinPaletteItem.
References id(), layerKinChief(), and m_stickyList.
anyConnectorItem()
ConnectorItem * ItemBase::anyConnectorItem ()
References cachedConnectorItems().
boundingRect()
QRectF ItemBase::boundingRect () const
References FSvgRenderer::defaultSizeF(), and fsvgRenderer().
boundingRectWithoutLegs()
QRectF ItemBase::boundingRectWithoutLegs () const virtual
Reimplemented in PaletteItemBase.
References boundingRect().
busConnectorItems()
void ItemBase::busConnectorItems (Bus * bus, ConnectorItem * , QList< ConnectorItem * > & items) virtual
Reimplemented in SymbolPaletteItem.
References NonConnectorItem::attachedTo(), ConnectorItem::attachedToViewID(), Bus::connectors(), m_subparts, m_superpart, m_viewID, Bus::subConnector(), and Connector::viewItems().
buses()
QList< Bus * > ItemBase::buses ()
References m_modelPart.
cachedConnectorItems()
const QList< ConnectorItem * > & ItemBase::cachedConnectorItems ()
References m_cachedConnectorItems.
cachedConnectorItemsConst()
const QList< ConnectorItem * > & ItemBase::cachedConnectorItemsConst () const
References m_cachedConnectorItems.
calcRotation()
void ItemBase::calcRotation (QTransform & rotation, QPointF center, ViewGeometry & vg2) virtual
Reimplemented in JumperItem.
References boundingRectWithoutLegs(), GraphicsUtils::calcRotation(), and ViewGeometry::setLoc().
canEditPart()
bool ItemBase::canEditPart () virtual
Reimplemented in PaletteItemBase, SchematicFrame, Hole, LogoItem, Resistor, GroundPlane, Pad, Perfboard, and LED.
canFlip()
bool ItemBase::canFlip (Qt::Orientations orientations)
References m_canFlipHorizontal, and m_canFlipVertical.
canFlipHorizontal()
bool ItemBase::canFlipHorizontal ()
References m_canFlipHorizontal, and m_moveLock.
canFlipVertical()
bool ItemBase::canFlipVertical ()
References m_canFlipVertical, and m_moveLock.
cleanup()
void ItemBase::cleanup () static
clearConnectorHover()
void ItemBase::clearConnectorHover () virtual
References hoverUpdate(), and m_connectorHoverCount2.
clearConnectorItemCache()
void ItemBase::clearConnectorItemCache ()
References m_cachedConnectorItems.
clearModelPart()
void ItemBase::clearModelPart () virtual
Reimplemented in PaletteItem, and LayerKinPaletteItem.
References m_modelPart.
clearPartLabel()
void ItemBase::clearPartLabel ()
References m_partLabel.
collectConnectors()
void ItemBase::collectConnectors (ConnectorPairHash & connectorHash, SkipCheckFunction skipCheckFunction)
References cachedConnectorItems(), ConnectorItem::connectedToItems(), ConnectorItem::getCrossLayerConnectorItem(), and modelPart().
collectExtraInfo()
bool ItemBase::collectExtraInfo (QWidget * parent, const QString & family, const QString & prop, const QString & value, bool swappingEnabled, QString & returnProp, QString & returnValue, QWidget *& returnWidget, bool & hide) virtual
Reimplemented in BoardLogoItem, BreadboardLogoItem, Wire, PaletteItem, ResizableBoard, Stripboard, PaletteItemBase, SymbolPaletteItem, Board, SchematicFrame, Hole, Pad, PinHeader, Ruler, LogoItem, Perfboard, MysteryPart, Resistor, Capacitor, ScrewTerminal, Dip, and TraceWire.
References collectValues(), family(), label(), m_propsMap, prop(), showInFolder(), swapEntry(), and translatePropertyName().
collectFemaleConnectees()
bool ItemBase::collectFemaleConnectees (QSet< ItemBase * > & items) virtual
Reimplemented in PaletteItem, and PaletteItemBase.
collectPropsMap()
void ItemBase::collectPropsMap (QString & family, QMap< QString, QString > & propsMap)
References collectValues(), DebugDialog::debug(), family(), and m_modelPart.
collectValues()
QStringList ItemBase::collectValues (const QString & family, const QString & prop, QString & value) protected virtual
Reimplemented in ResizableBoard, PaletteItem, LogoItem, Stripboard, Pad, MysteryPart, Resistor, PinHeader, Board, TraceWire, Dip, and ScrewTerminal.
References ___emptyStringList___, CachedValues, TextUtils::convertFromPowerPrefix(), family(), NumberMatcher, NumberMatcherValues, numberValueLessThan(), prop(), and TheReferenceModel.
collectWireConnectees()
void ItemBase::collectWireConnectees (QSet< Wire * > & wires) virtual
connectedColor()
QColor ItemBase::connectedColor () static
References ConnectedPen.
connectedMoved()
void ItemBase::connectedMoved (ConnectorItem * from, ConnectorItem * to, QList< ConnectorItem * > & already) virtual
Reimplemented in Wire, and PaletteItemBase.
connectionChange()
void ItemBase::connectionChange (ConnectorItem * onMe, ConnectorItem * onIt, bool connect) virtual
Reimplemented in Wire, and VirtualWire.
connectionIsAllowed()
bool ItemBase::connectionIsAllowed (ConnectorItem * other) virtual
Reimplemented in Wire.
References ConnectorItem::attachedToViewLayerID(), ViewLayer::canConnect(), and viewLayerID().
connectorHover()
void ItemBase::connectorHover (ConnectorItem * , ItemBase * , bool hovering) virtual
References hoverUpdate(), and m_connectorHoverCount2.
constTitle()
const QString & ItemBase::constTitle () const
References ___emptyString___, and m_modelPart.
contextMenuEvent()
void ItemBase::contextMenuEvent (QGraphicsSceneContextMenuEvent * event)
References NonConnectorItem::attachedTo(), m_hidden, m_inactive, m_itemMenu, m_layerHidden, and m_rightClickedConnector.
createShape()
void ItemBase::createShape (LayerAttributes & layerAttributes) protected
References TextUtils::ensureViewBox(), SvgFileSplitter::forceStrokeWidth(), isEverVisible(), LayerAttributes::loaded(), m_selectionShape, ViewLayer::PCBView, renderOne(), ViewLayer::SchematicView, GraphicsUtils::SVGDPI, and LayerAttributes::viewID.
debugInfo()
void ItemBase::debugInfo (const QString & msg) const
References debugInfo2().
debugInfo2()
void ItemBase::debugInfo2 (const QString & msg) const
References constTitle(), DebugDialog::debug(), instanceTitle(), m_viewID, viewLayerID(), viewLayerPlacement(), and wireFlags().
doneLoading()
void ItemBase::doneLoading () virtual
doRotateFlipPartLabel()
void ItemBase::doRotateFlipPartLabel (double degrees, Qt::Orientations orientation)
References m_partLabel.
ensureUniqueTitle()
void ItemBase::ensureUniqueTitle (const QString & title, bool force)
References instanceTitle(), modelPart(), setInstanceTitle(), and title().
extractTopLevelItemBase()
ItemBase * ItemBase::extractTopLevelItemBase (QGraphicsItem * thing) static
References topLevel().
family()
QString ItemBase::family ()
References ModelPart::family(), and modelPart().
figureHover()
void ItemBase::figureHover () virtual
Reimplemented in PaletteItem, and ResizableBoard.
filename()
const QString & ItemBase::filename ()
References m_filename.
filterMousePressConnectorEvent()
bool ItemBase::filterMousePressConnectorEvent (ConnectorItem * , QGraphicsSceneMouseEvent *) virtual
Reimplemented in ClipableWire.
findConnectorItemWithSharedID() [1/2]
ConnectorItem * ItemBase::findConnectorItemWithSharedID (const QString & connectorID, ViewLayer::ViewLayerPlacement viewLayerPlacement)
References ConnectorItem::chooseFromSpec(), and viewLayerPlacement().
findConnectorItemWithSharedID() [2/2]
ConnectorItem * ItemBase::findConnectorItemWithSharedID (const QString & connectorID)
References Connector::connectorItem(), ModelPart::getConnector(), m_viewID, and modelPart().
findConnectorsUnder()
virtual void ItemBase::findConnectorsUnder () pure virtual
Implemented in PaletteItemBase, Wire, and Note.
findSubpart()
ItemBase * ItemBase::findSubpart (const QString & connectorID, ViewLayer::ViewLayerPlacement spec)
References findConnectorItemWithSharedID(), and m_subparts.
fixCopper1()
bool ItemBase::fixCopper1 (ModelPart * modelPart, const QString & filename, ViewLayer::ViewLayerID viewLayerID, ViewLayer::ViewLayerPlacement , QDomDocument & doc) static protected
References TextUtils::addCopper1(), ViewLayer::Copper0, ViewLayer::Copper1, modelPart(), ModelPart::needsCopper1(), viewLayerID(), and ViewLayer::viewLayerXmlNameFromID().
flipItem()
void ItemBase::flipItem (Qt::Orientations orientation) virtual
Reimplemented in PaletteItem.
References transformItem().
freeRotationAllowed()
bool ItemBase::freeRotationAllowed () virtual
Reimplemented in PaletteItemBase, LogoItem, and Pad.
fsvgRenderer()
FSvgRenderer * ItemBase::fsvgRenderer () const
References DebugDialog::debug(), and m_fsvgRenderer.
getConnectedColor()
void ItemBase::getConnectedColor (ConnectorItem * , QBrush & brush, QPen & pen, double & opacity, double & negativePenWidth, bool & negativeOffsetRect) virtual
Reimplemented in Wire, and Stripboard.
References ConnectedBrush, and ConnectedPen.
getCursor()
const QCursor * ItemBase::getCursor (Qt::KeyboardModifiers) virtual
Reimplemented in PaletteItemBase.
References CursorMaster::MoveCursor.
getEqualPotentialColor()
void ItemBase::getEqualPotentialColor (ConnectorItem * , QBrush & brush, QPen & pen, double & opacity, double & negativePenWidth, bool & negativeOffsetRect) virtual
References EqualPotentialBrush, and EqualPotentialPen.
getFlipDoc()
bool ItemBase::getFlipDoc (ModelPart * modelPart, const QString & filename, ViewLayer::ViewLayerID viewLayerID, ViewLayer::ViewLayerPlacement viewLayerPlacement, QDomDocument & flipDoc, Qt::Orientations orientation) static protected
References ViewLayer::Copper0, ViewLayer::Copper1, fixCopper1(), ModelPart::flippedSMD(), SvgFlattener::flipSMDSvg(), ModelPart::itemType(), modelPart(), ViewLayer::NewBottom, ModelPart::Part, SvgFlattener::replaceElementID(), ViewLayer::Silkscreen0, ViewLayer::Silkscreen1, GraphicsUtils::SVGDPI, viewLayerID(), viewLayerPlacement(), and ViewLayer::viewLayerXmlNameFromID().
getHoverColor()
void ItemBase::getHoverColor (ConnectorItem * , QBrush & brush, QPen & pen, double & opacity, double & negativePenWidth, bool & negativeOffsetRect) virtual
References HoverBrush, HoverPen, and NormalConnectorOpacity.
getInspectorTitle()
QString ItemBase::getInspectorTitle () virtual
Reimplemented in NetLabel, and LogoItem.
References instanceTitle(), and title().
getNextID() [1/2]
qint64 ItemBase::getNextID () static
References ModelPart::indexMultiplier, and ModelPart::nextIndex().
getNextID() [2/2]
qint64 ItemBase::getNextID (qint64 fromIndex) static
References ModelPart::indexMultiplier, and ModelPart::updateIndex().
getNormalColor()
void ItemBase::getNormalColor (ConnectorItem * , QBrush & brush, QPen & pen, double & opacity, double & negativePenWidth, bool & negativeOffsetRect) virtual
References NormalBrush, NormalConnectorOpacity, and NormalPen.
getPixmap() [1/2]
QPixmap * ItemBase::getPixmap (QSize size)
References FSvgRenderer::getPixmap().
getPixmap() [2/2]
QPixmap * ItemBase::getPixmap (ViewLayer::ViewID vid, bool swappingEnabled, QSize size) protected
References getPixmap(), PartFactory::getSvgFilename(), ModelPart::hasBaseNameFor(), isEverVisible(), modelPart(), ViewLayer::UnknownView, useViewIDForPixmap(), viewID(), and ModelPart::viewItem().
getPixmaps()
void ItemBase::getPixmaps (QPixmap *& pixmap1, QPixmap *& pixmap2, QPixmap *& pixmap3, bool swappingEnabled, QSize size)
References ViewLayer::BreadboardView, getPixmap(), ViewLayer::PCBView, and ViewLayer::SchematicView.
getProperty()
QString ItemBase::getProperty (const QString & key) virtual
Reimplemented in SymbolPaletteItem, LogoItem, Hole, MysteryPart, Resistor, and PinHeader.
References m_modelPart.
getRatsnest()
bool ItemBase::getRatsnest ()
References ViewGeometry::getRatsnest(), and m_viewGeometry.
getUnconnectedColor()
void ItemBase::getUnconnectedColor (ConnectorItem * , QBrush & brush, QPen & pen, double & opacity, double & negativePenWidth, bool & negativeOffsetRect) virtual
References UnconnectedBrush, and UnconnectedPen.
getViewGeometry()
ViewGeometry & ItemBase::getViewGeometry ()
References m_viewGeometry.
hasConnections()
bool ItemBase::hasConnections ()
References cachedConnectorItems(), and ConnectorItem::connectionsCount().
hasConnectors()
bool ItemBase::hasConnectors ()
References cachedConnectorItems().
hasCustomSVG()
bool ItemBase::hasCustomSVG () virtual
Reimplemented in ResizableBoard, Hole, JumperItem, MysteryPart, Resistor, Ruler, LED, and GroundPlane.
hasNonConnectors()
bool ItemBase::hasNonConnectors ()
hasPartLabel()
bool ItemBase::hasPartLabel () virtual
Reimplemented in Wire, CopperBlocker, SymbolPaletteItem, SchematicFrame, Note, LogoItem, Pad, Ruler, and GroundPlane.
hasPartNumberProperty()
bool ItemBase::hasPartNumberProperty () virtual
Reimplemented in Wire, ResizableBoard, SymbolPaletteItem, SchematicFrame, Note, JumperItem, Pad, Hole, Ruler, and GroundPlane.
hasRubberBandLeg()
bool ItemBase::hasRubberBandLeg () const
References m_hasRubberBandLeg.
hidden()
constexpr bool ItemBase::hidden () const inline noexcept
References m_hidden.
hidePartLabel
void ItemBase::hidePartLabel () slot
References InfoGraphicsView::getInfoGraphicsView(), and InfoGraphicsView::hidePartLabel().
hoverEnterConnectorItem() [1/2]
void ItemBase::hoverEnterConnectorItem (QGraphicsSceneHoverEvent * event, ConnectorItem * item) virtual
Reimplemented in Wire, and ClipableWire.
References hoverEnterConnectorItem().
hoverEnterConnectorItem() [2/2]
void ItemBase::hoverEnterConnectorItem ()
References hoverUpdate(), and m_connectorHoverCount.
hoverEnterEvent()
void ItemBase::hoverEnterEvent (QGraphicsSceneHoverEvent * event)
References InfoGraphicsView::getInfoGraphicsView(), InfoGraphicsView::hoverEnterItem(), hoverUpdate(), m_hoverCount, m_hoverEnterSpaceBarWasPressed, and InfoGraphicsView::spaceBarIsPressed().
hoverLeaveConnectorItem() [1/2]
void ItemBase::hoverLeaveConnectorItem (QGraphicsSceneHoverEvent * event, ConnectorItem * item) virtual
Reimplemented in Wire, and ClipableWire.
References hoverLeaveConnectorItem().
hoverLeaveConnectorItem() [2/2]
void ItemBase::hoverLeaveConnectorItem ()
References hoverUpdate(), and m_connectorHoverCount.
hoverLeaveEvent()
void ItemBase::hoverLeaveEvent (QGraphicsSceneHoverEvent * event)
References InfoGraphicsView::getInfoGraphicsView(), InfoGraphicsView::hoverLeaveItem(), hoverUpdate(), m_hoverCount, and m_hoverEnterSpaceBarWasPressed.
hoverMoveConnectorItem()
void ItemBase::hoverMoveConnectorItem (QGraphicsSceneHoverEvent * event, ConnectorItem * item) virtual
Reimplemented in ClipableWire.
hoverShape()
QPainterPath ItemBase::hoverShape () const virtual
Reimplemented in Wire, CopperBlocker, PaletteItemBase, and JumperItem.
hoverUpdate()
void ItemBase::hoverUpdate () virtual
Reimplemented in Perfboard, and Breadboard.
id()
constexpr qint64 ItemBase::id () const inline noexcept
References m_id.
inactive()
constexpr bool ItemBase::inactive () const inline noexcept
References m_inactive.
inHover()
bool ItemBase::inHover ()
References m_connectorHoverCount, m_connectorHoverCount2, m_hoverCount, and m_inactive.
initLayerAttributes()
void ItemBase::initLayerAttributes (LayerAttributes & layerAttributes, ViewLayer::ViewID viewID, ViewLayer::ViewLayerID viewLayerID, ViewLayer::ViewLayerPlacement viewLayerPlacement, bool doConnectors, bool doCreateShape)
References LayerAttributes::createShape, LayerAttributes::doConnectors, InfoGraphicsView::getInfoGraphicsView(), LayerAttributes::orientation, InfoGraphicsView::smdOrientation(), LayerAttributes::viewID, viewID(), LayerAttributes::viewLayerID, viewLayerID(), LayerAttributes::viewLayerPlacement, and viewLayerPlacement().
initNames()
void ItemBase::initNames () static
References NumberMatcher, PartInstanceDefaultTitle, TextUtils::PowerPrefixesString, setConnectedColor(), setUnconnectedColor(), and TranslatedPropertyNames.
inRotation()
bool ItemBase::inRotation () virtual
Reimplemented in LayerKinPaletteItem.
References m_inRotation.
instanceTitle()
const QString & ItemBase::instanceTitle () const
References ___emptyString___, and m_modelPart.
isBaseSticky()
bool ItemBase::isBaseSticky () virtual
Reimplemented in LayerKinPaletteItem.
References m_sticky.
isEverVisible()
bool ItemBase::isEverVisible ()
References m_everVisible.
isLocalSticky()
bool ItemBase::isLocalSticky ()
References isLocalSticky(), layerKinChief(), ModelPart::localProp(), and modelPart().
isObsolete()
bool ItemBase::isObsolete ()
References ModelPart::isObsolete(), and modelPart().
isPartLabelVisible()
bool ItemBase::isPartLabelVisible ()
References hasPartLabel(), and m_partLabel.
isPlural()
ItemBase::PluralType ItemBase::isPlural () virtual
Reimplemented in Wire, NetLabel, SymbolPaletteItem, SchematicFrame, LogoItem, JumperItem, Board, Pad, Resistor, Hole, MysteryPart, Ruler, GroundPlane, Perfboard, LED, PinHeader, Capacitor, Breadboard, and ScrewTerminal.
References NotSure.
isSticky()
bool ItemBase::isSticky () virtual
Reimplemented in LayerKinPaletteItem.
References isBaseSticky(), and isLocalSticky().
isSwappable()
bool ItemBase::isSwappable () virtual
Reimplemented in LayerKinPaletteItem.
References m_swappable.
itemChange()
QVariant ItemBase::itemChange (QGraphicsItem::GraphicsItemChange change, const QVariant & value) protected
References m_partLabel.
itemMoved()
virtual bool ItemBase::itemMoved () pure virtual
Implemented in Wire, Note, and PaletteItemBase.
itemType()
int ItemBase::itemType () const
References m_modelPart, and ModelPart::Unknown.
killRubberBandLeg()
void ItemBase::killRubberBandLeg ()
References cachedConnectorItems(), hasRubberBandLeg(), ConnectorItem::killRubberBandLeg(), and prepareGeometryChange().
label()
QString ItemBase::label ()
References ___emptyString___, and m_modelPart.
layerHidden()
constexpr bool ItemBase::layerHidden () const inline noexcept
References m_layerHidden.
layerKin()
const QList< ItemBase * > & ItemBase::layerKin () virtual
Reimplemented in PaletteItem.
References EmptyList.
layerKinChief()
ItemBase * ItemBase::layerKinChief () virtual
Reimplemented in LayerKinPaletteItem.
makeLocalModifications()
bool ItemBase::makeLocalModifications (QByteArray & svg, const QString & filename) protected virtual
Reimplemented in PaletteItem.
makePartLabelSvg()
QString ItemBase::makePartLabelSvg (bool blackOnly, double dpi, double printerScale)
References m_partLabel.
modelPart()
ModelPart * ItemBase::modelPart ()
References m_modelPart.
modelPartShared()
ModelPartShared * ItemBase::modelPartShared ()
References m_modelPart.
moduleID()
const QString & ItemBase::moduleID ()
References ___emptyString___, and m_modelPart.
mouseDoubleClickConnectorEvent()
void ItemBase::mouseDoubleClickConnectorEvent (ConnectorItem *) virtual
Reimplemented in Wire.
mouseMoveConnectorEvent()
void ItemBase::mouseMoveConnectorEvent (ConnectorItem * , QGraphicsSceneMouseEvent *) virtual
Reimplemented in Wire.
mouseMoveEvent()
void ItemBase::mouseMoveEvent (QGraphicsSceneMouseEvent * event) protected
mousePressConnectorEvent()
void ItemBase::mousePressConnectorEvent (ConnectorItem * , QGraphicsSceneMouseEvent *) virtual
Reimplemented in Wire, and PaletteItemBase.
mousePressEvent()
void ItemBase::mousePressEvent (QGraphicsSceneMouseEvent * event)
References InfoGraphicsView::getInfoGraphicsView(), and InfoGraphicsView::spaceBarIsPressed().
mouseReleaseConnectorEvent()
void ItemBase::mouseReleaseConnectorEvent (ConnectorItem * , QGraphicsSceneMouseEvent *) virtual
Reimplemented in Wire.
mouseReleaseEvent()
void ItemBase::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected
References m_rightClickedConnector.
moveItem()
virtual void ItemBase::moveItem (ViewGeometry &) pure virtual
Implemented in PaletteItem, Wire, Note, and PaletteItemBase.
moveLock()
bool ItemBase::moveLock ()
References m_moveLock.
movePartLabel()
void ItemBase::movePartLabel (QPointF newPos, QPointF newOffset)
References m_partLabel.
newConnectorItem() [1/2]
ConnectorItem * ItemBase::newConnectorItem (Connector * connector) virtual
Reimplemented in LayerKinPaletteItem, Resistor, and SymbolPaletteItem.
newConnectorItem() [2/2]
ConnectorItem * ItemBase::newConnectorItem (ItemBase * layerkin, Connector * connector) virtual
Reimplemented in Resistor.
References layerKin().
paint()
void ItemBase::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget)
References InactiveOpacity, inHover(), layerKinChief(), m_inactive, paintBody(), paintHover(), and paintSelected().
paintBody()
void ItemBase::paintBody (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) protected virtual
Reimplemented in Wire.
References boundingRectWithoutLegs(), and fsvgRenderer().
paintHover() [1/2]
void ItemBase::paintHover (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) protected virtual
Reimplemented in Wire, PaletteItemBase, JumperItem, LogoItem, Pad, Perfboard, Board, and Breadboard.
References hoverShape().
paintHover() [2/2]
void ItemBase::paintHover (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget, const QPainterPath & shape) protected virtual
References ConnectorHoverColor, ConnectorHoverOpacity, HoverColor, HoverOpacity, m_connectorHoverCount, and m_connectorHoverCount2.
paintSelected()
void ItemBase::paintSelected (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) protected virtual
Reimplemented in ResizableBoard, PaletteItemBase, and JumperItem.
References boundingRect(), hoverShape(), and GraphicsUtils::qt_graphicsItem_highlightSelected().
partLabel()
PartLabel * ItemBase::partLabel ()
References m_partLabel.
partLabelChanged
void ItemBase::partLabelChanged (const QString & newText) slot
References InfoGraphicsView::getInfoGraphicsView(), ModelPart::instanceTitle(), modelPart(), InfoGraphicsView::partLabelChanged(), and setInstanceTitleAux().
partLabelMoved()
void ItemBase::partLabelMoved (QPointF oldPos, QPointF oldOffset, QPointF newPos, QPointF newOffset)
References InfoGraphicsView::getInfoGraphicsView(), and InfoGraphicsView::partLabelMoved().
partLabelSceneBoundingRect()
QRectF ItemBase::partLabelSceneBoundingRect ()
References m_partLabel.
partLabelScenePos()
QPointF ItemBase::partLabelScenePos ()
References m_partLabel.
partLabelSetHidden()
void ItemBase::partLabelSetHidden (bool hide)
References m_partLabel.
partLabelViewLayerID()
ViewLayer::ViewLayerID ItemBase::partLabelViewLayerID ()
References m_partLabel, and ViewLayer::UnknownLayer.
prepareGeometryChange()
void ItemBase::prepareGeometryChange ()
prepareProps()
QHash< QString, QString > ItemBase::prepareProps (ModelPart * modelPart, bool wantDebug, QStringList & keys) virtual
Reimplemented in TraceWire.
References family(), filename(), hasPartNumberProperty(), m_propsMap, modelPart(), ModelPart::modelPartShared(), ModelPart::moduleID(), ModelPartShared::PartNumberPropertyName, ModelPart::path(), ModelPart::properties(), viewLayerID(), and ViewLayer::viewLayerNameFromID().
prop()
QString ItemBase::prop (const QString & p)
References m_modelPart.
reloadRenderer()
bool ItemBase::reloadRenderer (const QString & svg, bool fastload)
References FSvgRenderer::fastLoad(), fsvgRenderer(), FSvgRenderer::loadSvgString(), and prepareGeometryChange().
removeLayerKin()
void ItemBase::removeLayerKin () virtual
Reimplemented in PaletteItem.
removeTooltip()
void ItemBase::removeTooltip ()
References ___emptyString___.
renderOne()
void ItemBase::renderOne (QDomDocument * masterDoc, QImage * image, const QRectF & renderRect) static
resetID()
void ItemBase::resetID () virtual
Reimplemented in PaletteItem, and LayerKinPaletteItem.
References ModelPart::indexMultiplier, m_id, and m_modelPart.
resetRenderer() [1/2]
bool ItemBase::resetRenderer (const QString & svg)
resetRenderer() [2/2]
bool ItemBase::resetRenderer (const QString & svg, QString & newSvg)
References FSvgRenderer::loadSvgString(), and setSharedRendererEx().
resetValues()
void ItemBase::resetValues (const QString & family, const QString & prop)
References CachedValues, family(), and prop().
restorePartLabel()
void ItemBase::restorePartLabel (QDomElement & labelGeometry, ViewLayer::ViewLayerID viewLayerID)
References instanceTitle(), m_partLabel, and viewLayerID().
retrieveSvg()
QString ItemBase::retrieveSvg (ViewLayer::ViewLayerID , QHash< QString, QString > & svgHash, bool blackOnly, double dpi, double & factor) virtual
Reimplemented in NetLabel, ResizableBoard, Stripboard, Note, PaletteItemBase, SymbolPaletteItem, SchematicFrame, Hole, LayerKinPaletteItem, Pad, Ruler, JumperItem, LogoItem, LED, MysteryPart, Resistor, and GroundPlane.
rightClickedConnector()
ConnectorItem * ItemBase::rightClickedConnector ()
References m_rightClickedConnector.
rotateFlipPartLabel()
void ItemBase::rotateFlipPartLabel (double degrees, Qt::Orientations orientation)
References InfoGraphicsView::getInfoGraphicsView(), and InfoGraphicsView::rotateFlipPartLabel().
rotateItem()
void ItemBase::rotateItem (double degrees, bool includeRatsnest) virtual
Reimplemented in PaletteItem, and JumperItem.
References transformItem().
rotation45Allowed()
bool ItemBase::rotation45Allowed () virtual
Reimplemented in Wire, Note, SchematicFrame, Hole, Pad, Perfboard, Board, GroundPlane, and Breadboard.
References m_moveLock.
rotationAllowed()
bool ItemBase::rotationAllowed () virtual
Reimplemented in Wire, Note, SchematicFrame, Hole, Pad, and GroundPlane.
References m_moveLock.
saveGeometry()
virtual void ItemBase::saveGeometry () pure virtual
Implemented in Wire, Note, and PaletteItemBase.
saveInstance()
void ItemBase::saveInstance (QXmlStreamWriter & streamWriter) virtual
References cachedConnectorItems(), ConnectorItem::connectionsCount(), ConnectorItem::hasRubberBandLeg(), ConnectorItem::isGroundFillSeed(), layerHidden(), layerKin(), layerKinChief(), m_moveLock, m_partLabel, m_superpart, m_viewID, m_viewLayerID, m_viewLayerPlacement, ViewLayer::NewBottom, ViewLayer::PCBView, saveGeometry(), ConnectorItem::saveInstance(), ViewLayer::viewIDXmlName(), viewLayerID(), ViewLayer::viewLayerXmlNameFromID(), and writeGeometry().
saveInstanceLocation()
virtual void ItemBase::saveInstanceLocation (QXmlStreamWriter &) pure virtual
Implemented in Wire, JumperItem, Note, PaletteItemBase, and Via.
saveLocAndTransform()
void ItemBase::saveLocAndTransform (QXmlStreamWriter & streamWriter) protected
References ViewGeometry::loc(), m_viewGeometry, GraphicsUtils::saveTransform(), and ViewGeometry::transform().
sceneEvent()
bool ItemBase::sceneEvent (QEvent * event)
selectionShape()
const QPainterPath & ItemBase::selectionShape ()
References m_selectionShape.
setAcceptsMousePressLegEvent()
void ItemBase::setAcceptsMousePressLegEvent (bool b) virtual
References m_acceptsMousePressLegEvent.
setCanFlipHorizontal()
void ItemBase::setCanFlipHorizontal (bool cf)
References m_canFlipHorizontal.
setCanFlipVertical()
void ItemBase::setCanFlipVertical (bool cf)
References m_canFlipVertical.
setConnectedColor()
void ItemBase::setConnectedColor (QColor & c) static
References ConnectedBrush, and ConnectedPen.
setDefaultTooltip()
void ItemBase::setDefaultTooltip () protected virtual
References ensureUniqueTitle(), ViewLayer::IconView, instanceTitle(), ITEMBASE_FONT_PREFIX, ITEMBASE_FONT_SUFFIX, label(), m_modelPart, m_viewID, PartInstanceDefaultTitle, setInstanceTitleTooltip(), title(), and ModelPart::Wire.
setDropOffset()
void ItemBase::setDropOffset (QPointF offset) virtual
Reimplemented in GroundPlane.
setEverVisible()
void ItemBase::setEverVisible (bool v)
References m_everVisible.
setFilename()
void ItemBase::setFilename (const QString & fn)
References m_filename.
setHidden()
void ItemBase::setHidden (bool hidden) virtual
Reimplemented in PaletteItem, Note, LayerKinPaletteItem, and VirtualWire.
References m_hidden, NonConnectorItem::setHidden(), and updateHidden().
setInactive()
void ItemBase::setInactive (bool inactivate) virtual
Reimplemented in PaletteItem, Note, LayerKinPaletteItem, and VirtualWire.
References m_inactive, NonConnectorItem::setInactive(), and updateHidden().
setInRotation()
void ItemBase::setInRotation (bool val) virtual
Reimplemented in LayerKinPaletteItem.
References m_inRotation.
setInspectorTitle()
void ItemBase::setInspectorTitle (const QString & oldText, const QString & newText) virtual
Reimplemented in NetLabel, and LogoItem.
References DebugDialog::debug(), InfoGraphicsView::getInfoGraphicsView(), and InfoGraphicsView::setInstanceTitle().
setInstanceTitle()
void ItemBase::setInstanceTitle (const QString & title, bool initial) virtual
Reimplemented in PaletteItem.
References m_partLabel, setInstanceTitleAux(), and title().
setInstanceTitleAux()
void ItemBase::setInstanceTitleAux (const QString & title, bool initial) protected
References m_modelPart, setInstanceTitleTooltip(), and title().
setInstanceTitleTooltip()
void ItemBase::setInstanceTitleTooltip (const QString & text) protected
References ITEMBASE_FONT_PREFIX, ITEMBASE_FONT_SUFFIX, and title().
setItemIsSelectable()
void ItemBase::setItemIsSelectable (bool selectable)
setItemPos()
void ItemBase::setItemPos (QPointF & pos) virtual
Reimplemented in PaletteItem.
setLayerHidden()
void ItemBase::setLayerHidden (bool hidden) virtual
References layerHidden(), m_layerHidden, NonConnectorItem::setLayerHidden(), and updateHidden().
setLocalSticky()
void ItemBase::setLocalSticky (bool s)
References layerKinChief(), m_moveLockItem, m_stickyItem, modelPart(), ModelPart::setLocalProp(), setLocalSticky(), and StickyRenderer.
setModelPart()
void ItemBase::setModelPart (ModelPart * modelPart)
References m_modelPart, and modelPart().
setMoveLock()
void ItemBase::setMoveLock (bool moveLock) virtual
References DebugDialog::debug(), m_moveLock, m_moveLockItem, m_stickyItem, moveLock(), and MoveLockRenderer.
setProp()
void ItemBase::setProp (const QString & prop, const QString & value) virtual
Reimplemented in Wire, BreadboardLogoItem, Stripboard, PaletteItemBase, SymbolPaletteItem, SchematicFrame, Resistor, LogoItem, Pad, Perfboard, LED, Hole, MysteryPart, Capacitor, and GroundPlane.
References m_modelPart, and prop().
setReferenceModel()
void ItemBase::setReferenceModel (ReferenceModel * rm) static
References TheReferenceModel.
setSharedRendererEx()
void ItemBase::setSharedRendererEx (FSvgRenderer * newRenderer)
References FSvgRenderer::defaultSizeF(), m_fsvgRenderer, and m_size.
setSquashShape()
void ItemBase::setSquashShape (bool squashShape)
References m_squashShape.
setSticky()
void ItemBase::setSticky (bool s) virtual
Reimplemented in LayerKinPaletteItem.
References m_sticky.
setSuperpart()
void ItemBase::setSuperpart (ItemBase * super)
References m_superpart.
setSwappable()
void ItemBase::setSwappable (bool swappable) virtual
Reimplemented in LayerKinPaletteItem.
References m_swappable.
setTooltip()
void ItemBase::setTooltip ()
References instanceTitle(), m_modelPart, setDefaultTooltip(), setInstanceTitleTooltip(), and title().
setTransform2()
void ItemBase::setTransform2 (const QTransform & transform) virtual
Reimplemented in SchematicTextLayerKinPaletteItem.
setUnconnectedColor()
void ItemBase::setUnconnectedColor (QColor & c) static
References UnconnectedBrush, and UnconnectedPen.
setUpImage()
FSvgRenderer * ItemBase::setUpImage (ModelPart * modelPart, LayerAttributes & layerAttributes)
References ViewLayer::BreadboardView, SvgFileSplitter::byteArray(), LoadInfo::colorElementID, LoadInfo::connectorIDs, ModelPartShared::connectorIDs(), ViewLayer::Copper0, ViewLayer::Copper0Color, ViewLayer::Copper1, ViewLayer::Copper1Color, LayerAttributes::createShape, createShape(), LayerAttributes::error, LoadInfo::filename, FSvgRenderer::filename(), filename(), LoadInfo::findNonConnectors, getFlipDoc(), PartFactory::getSvgFilename(), ModelPartShared::hasMultipleLayers(), SvgFileSplitter::hideText(), SvgFileSplitter::hideText2(), ViewLayer::IconView, ModelPartShared::imageFileName(), LoadInfo::legIDs, FSvgRenderer::loadSvg(), makeLocalModifications(), modelPart(), ModelPart::modelPartShared(), modelPartShared(), ModelPartShared::moduleID(), LayerAttributes::orientation, LoadInfo::parsePaths, ViewLayer::PCBView, ViewLayer::Schematic, ViewLayer::SchematicText, LoadInfo::setColor, LayerAttributes::setFilename(), LayerAttributes::setLoaded(), SvgFileSplitter::showText(), SvgFileSplitter::showText2(), ViewLayer::Silkscreen0, ViewLayer::Silkscreen0Color, ViewLayer::Silkscreen1, ViewLayer::Silkscreen1Color, SvgFileSplitter::split(), SvgFileSplitter::splitString(), LoadInfo::terminalIDs, ModelPartShared::title(), LayerAttributes::viewID, LayerAttributes::viewLayerID, LayerAttributes::viewLayerPlacement, and ViewLayer::viewLayerXmlNameFromID().
setViewLayerID() [1/2]
void ItemBase::setViewLayerID (ViewLayer::ViewLayerID viewLayerID, const LayerHash & viewLayers)
References ViewLayer::alreadyInLayer(), m_viewGeometry, m_viewLayerID, m_zUninitialized, ViewLayer::nextZ(), ViewGeometry::setZ(), viewLayerID(), and ViewGeometry::z().
setViewLayerID() [2/2]
void ItemBase::setViewLayerID (const QString & layerName, const LayerHash & viewLayers)
References setViewLayerID(), and ViewLayer::viewLayerIDFromXmlString().
setViewLayerPlacement()
void ItemBase::setViewLayerPlacement (ViewLayer::ViewLayerPlacement viewLayerPlacement)
References m_viewLayerPlacement, and viewLayerPlacement().
showConnectors()
void ItemBase::showConnectors (const QStringList & connectorIDs)
References cachedConnectorItems(), and ConnectorItem::connectorSharedID().
showInFolder
void ItemBase::showInFolder () slot
References FolderUtils::showInFolder().
showPartLabel
void ItemBase::showPartLabel (bool show, ViewLayer * viewLayer) slot
References m_partLabel.
size()
constexpr QSizeF ItemBase::size () const inline noexcept
References m_size.
slamZ()
void ItemBase::slamZ (double newZ) virtual
Reimplemented in PaletteItem.
References m_viewGeometry, ViewGeometry::setZ(), ViewGeometry::z(), and z().
spice()
const QString & ItemBase::spice () const
References ___emptyString___, and m_modelPart.
spiceModel()
const QString & ItemBase::spiceModel () const
References ___emptyString___, and m_modelPart.
standardConnectedColor()
QColor ItemBase::standardConnectedColor () static
References StandardConnectedColor().
standardUnconnectedColor()
QColor ItemBase::standardUnconnectedColor () static
References StandardUnconnectedColor().
stickingTo()
ItemBase * ItemBase::stickingTo () virtual
Reimplemented in LayerKinPaletteItem.
References DebugDialog::debug(), isBaseSticky(), m_stickyList, and title().
stickyEnabled()
bool ItemBase::stickyEnabled () virtual
Reimplemented in Wire, SchematicFrame, Note, LogoItem, Perfboard, Board, Pad, LayerKinPaletteItem, Ruler, and Breadboard.
stickyList()
QList< QPointer< ItemBase > > ItemBase::stickyList () virtual
Reimplemented in LayerKinPaletteItem.
References m_stickyList.
subparts()
const QList< QPointer< ItemBase > > & ItemBase::subparts ()
References m_subparts.
superpart()
ItemBase * ItemBase::superpart ()
References m_superpart.
swapEntry
void ItemBase::swapEntry (const QString & text) virtual slot
Reimplemented in Stripboard.
References FamilyPropertyComboBox::family(), InfoGraphicsView::getInfoGraphicsView(), m_propsMap, FamilyPropertyComboBox::prop(), and InfoGraphicsView::swap().
title()
const QString & ItemBase::title () virtual
Reimplemented in LED, MysteryPart, and Resistor.
References ___emptyString___, and m_modelPart.
topLevel()
bool ItemBase::topLevel ()
References layerKinChief().
transformItem()
void ItemBase::transformItem (const QTransform & currTransf, bool includeRatsnest) virtual
Reimplemented in SchematicTextLayerKinPaletteItem.
References boundingRectWithoutLegs(), getViewGeometry(), m_hasRubberBandLeg, prepareGeometryChange(), ViewGeometry::setTransform(), ViewGeometry::transform(), and updateConnections().
transformItem2()
void ItemBase::transformItem2 (const QMatrix & matrix) virtual
Reimplemented in PaletteItem.
References transformItem().
translatePropertyName()
QString ItemBase::translatePropertyName (const QString & key) static
References TranslatedPropertyNames.
unconnectedColor()
QColor ItemBase::unconnectedColor () static
References UnconnectedPen.
updateConnections() [1/2]
void ItemBase::updateConnections (ConnectorItem * connectorItem, bool includeRatsnest, QList< ConnectorItem * > & already)
References ConnectorItem::attachedMoved(), and ConnectorItem::debugInfo().
updateConnections() [2/2]
void ItemBase::updateConnections (bool includeRatsnest, QList< ConnectorItem * > & already) virtual
Reimplemented in PaletteItem, and LayerKinPaletteItem.
updateConnectionsAux()
void ItemBase::updateConnectionsAux (bool includeRatsnest, QList< ConnectorItem * > & already)
References cachedConnectorItems(), and updateConnections().
updateConnectors()
void ItemBase::updateConnectors ()
References cachedConnectorItems(), isEverVisible(), and ConnectorItem::restoreColor().
updateHidden()
void ItemBase::updateHidden () protected
References ALLMOUSEBUTTONS, m_hidden, m_inactive, and m_layerHidden.
updatePartLabelInstanceTitle()
void ItemBase::updatePartLabelInstanceTitle ()
References instanceTitle(), and m_partLabel.
updateTooltip()
void ItemBase::updateTooltip () virtual
References instanceTitle(), and setInstanceTitleTooltip().
useViewIDForPixmap()
ViewLayer::ViewID ItemBase::useViewIDForPixmap (ViewLayer::ViewID vid, bool swappingEnabled) protected virtual
Reimplemented in Wire, SymbolPaletteItem, SchematicFrame, Note, JumperItem, Hole, GroundPlane, Board, Resistor, Ruler, and LED.
References ViewLayer::BreadboardView, and ViewLayer::IconView.
viewID()
ViewLayer::ViewID ItemBase::viewID ()
References m_viewID.
viewIDName()
QString & ItemBase::viewIDName ()
References m_viewID, and ViewLayer::viewIDName().
viewLayerID()
ViewLayer::ViewLayerID ItemBase::viewLayerID () const
References m_viewLayerID.
viewLayerPlacement()
ViewLayer::ViewLayerPlacement ItemBase::viewLayerPlacement () const
References m_viewLayerPlacement.
wireFlags()
ViewGeometry::WireFlags ItemBase::wireFlags () const
References m_viewGeometry, and ViewGeometry::wireFlags().
writeGeometry()
void ItemBase::writeGeometry (QXmlStreamWriter & streamWriter) virtual
Reimplemented in Wire.
References saveInstanceLocation(), and z().
writeXml()
virtual void ItemBase::writeXml (QXmlStreamWriter &) inline virtual
z()
double ItemBase::z ()
References getViewGeometry(), and ViewGeometry::z().
zLessThan()
bool ItemBase::zLessThan (ItemBase *& p1, ItemBase *& p2) static
References z().
Member Data Documentation
ChosenBrush
QBrush ItemBase::ChosenBrush static protected
ChosenPen
QPen ItemBase::ChosenPen static protected
ConnectedBrush
QBrush ItemBase::ConnectedBrush static protected
ConnectedPen
QPen ItemBase::ConnectedPen static protected
ConnectorHoverColor
const QColor ItemBase::ConnectorHoverColor static
ConnectorHoverOpacity
const double ItemBase::ConnectorHoverOpacity = .40 static
EmptyList
const QList< ItemBase * > ItemBase::EmptyList static
EqualPotentialBrush
QBrush ItemBase::EqualPotentialBrush static protected
EqualPotentialPen
QPen ItemBase::EqualPotentialPen static protected
HoverBrush
QBrush ItemBase::HoverBrush static protected
HoverColor
const QColor ItemBase::HoverColor static
HoverOpacity
const double ItemBase::HoverOpacity = .20 static
HoverPen
QPen ItemBase::HoverPen static protected
ITEMBASE_FONT_PREFIX
const QString ItemBase::ITEMBASE_FONT_PREFIX = "<font size='2'>" static
ITEMBASE_FONT_SUFFIX
const QString ItemBase::ITEMBASE_FONT_SUFFIX = "</font>" static
m_acceptsMousePressLegEvent
bool ItemBase::m_acceptsMousePressLegEvent = true protected
m_cachedConnectorItems
QList<ConnectorItem *> ItemBase::m_cachedConnectorItems protected
m_canFlipHorizontal
bool ItemBase::m_canFlipHorizontal = false protected
m_canFlipVertical
bool ItemBase::m_canFlipVertical = false protected
m_connectorHoverCount
int ItemBase::m_connectorHoverCount = 0 protected
m_connectorHoverCount2
int ItemBase::m_connectorHoverCount2 = 0 protected
m_everVisible
bool ItemBase::m_everVisible = true protected
m_filename
QString ItemBase::m_filename protected
m_fsvgRenderer
FSvgRenderer* ItemBase::m_fsvgRenderer = nullptr protected
m_hasRubberBandLeg
bool ItemBase::m_hasRubberBandLeg = false protected
m_hidden
bool ItemBase::m_hidden = false protected
m_hoverCount
int ItemBase::m_hoverCount = 0 protected
m_hoverEnterSpaceBarWasPressed
bool ItemBase::m_hoverEnterSpaceBarWasPressed = false protected
m_id
qint64 ItemBase::m_id = 0 protected
m_inactive
bool ItemBase::m_inactive = false protected
m_inRotation
bool ItemBase::m_inRotation = false protected
m_itemMenu
QMenu* ItemBase::m_itemMenu = nullptr protected
m_layerHidden
bool ItemBase::m_layerHidden = false protected
m_modelPart
QPointer<ModelPart> ItemBase::m_modelPart protected
m_moveLock
bool ItemBase::m_moveLock = false protected
m_moveLockItem
QGraphicsSvgItem* ItemBase::m_moveLockItem = nullptr protected
m_partLabel
QPointer<PartLabel> ItemBase::m_partLabel protected
m_propsMap
QMap<QString, QString> ItemBase::m_propsMap protected
m_rightClickedConnector
ConnectorItem* ItemBase::m_rightClickedConnector = nullptr protected
m_selectionShape
QPainterPath ItemBase::m_selectionShape protected
m_size
QSizeF ItemBase::m_size protected
m_spaceBarWasPressed
bool ItemBase::m_spaceBarWasPressed = false protected
m_squashShape
bool ItemBase::m_squashShape = false protected
m_sticky
bool ItemBase::m_sticky = false protected
m_stickyItem
QGraphicsSvgItem* ItemBase::m_stickyItem = nullptr protected
m_stickyList
QHash< long, QPointer<ItemBase> > ItemBase::m_stickyList protected
m_subparts
QList< QPointer<ItemBase> > ItemBase::m_subparts protected
m_superpart
QPointer<ItemBase> ItemBase::m_superpart protected
m_swappable
bool ItemBase::m_swappable = true protected
m_viewGeometry
ViewGeometry ItemBase::m_viewGeometry protected
m_viewID
ViewLayer::ViewID ItemBase::m_viewID protected
m_viewLayerID
ViewLayer::ViewLayerID ItemBase::m_viewLayerID protected
m_viewLayerPlacement
ViewLayer::ViewLayerPlacement ItemBase::m_viewLayerPlacement protected
m_zUninitialized
bool ItemBase::m_zUninitialized = true protected
nextID
long ItemBase::nextID static protected
NormalBrush
QBrush ItemBase::NormalBrush static protected
NormalConnectorOpacity
constexpr double ItemBase::NormalConnectorOpacity = 0.4 static protected
NormalPen
QPen ItemBase::NormalPen static protected
PartInstanceDefaultTitle
QString ItemBase::PartInstanceDefaultTitle static
TheReferenceModel
QPointer< ReferenceModel > ItemBase::TheReferenceModel = nullptr static protected
TranslatedPropertyNames
QHash< QString, QString > ItemBase::TranslatedPropertyNames static
UnconnectedBrush
QBrush ItemBase::UnconnectedBrush static protected
UnconnectedPen
QPen ItemBase::UnconnectedPen static protected
The documentation for this class was generated from the following files:
items/itembase.h
items/itembase.cpp