Fritzing: SketchAreaWidget Class Reference
SketchAreaWidget Class Reference
#include <sketchareawidget.h>
Public Member Functions
SketchAreaWidget (QWidget *contentView, QMainWindow *parent)
SketchAreaWidget (QWidget *contentView, QMainWindow *parent, bool hasToolBar, bool hasStatusBar)
virtual ~SketchAreaWidget ()
void addStatusBar (QStatusBar *)
QWidget * contentView ()
class ExpandingLabel * routingStatusLabel ()
void setRoutingStatusLabel (ExpandingLabel *)
void setToolbarWidgets (QList< QWidget * > buttons)
QFrame * toolbar ()
Static Public Member Functions
static QWidget * separator (QWidget *parent)
Static Public Attributes
static const QString RoutingStateLabelName = "routingStateLabel"
Protected Member Functions
void createLayout ()
void init (QWidget *contentView, QMainWindow *parent, bool hasToolBar, bool hasStatusBar)
Protected Attributes
QWidget * m_contentView = nullptr
QHBoxLayout * m_leftButtonsContainer = nullptr
QVBoxLayout * m_middleButtonsContainer = nullptr
QHBoxLayout * m_rightButtonsContainer = nullptr
ExpandingLabel * m_routingStatusLabel = nullptr
QFrame * m_statusBarArea = nullptr
QFrame * m_toolbar = nullptr
Constructor & Destructor Documentation
SketchAreaWidget() [1/2]
SketchAreaWidget::SketchAreaWidget (QWidget * contentView, QMainWindow * parent)
References contentView(), and init().
SketchAreaWidget() [2/2]
SketchAreaWidget::SketchAreaWidget (QWidget * contentView, QMainWindow * parent, bool hasToolBar, bool hasStatusBar)
References contentView(), and init().
~SketchAreaWidget()
SketchAreaWidget::~SketchAreaWidget () virtual
Member Function Documentation
addStatusBar()
void SketchAreaWidget::addStatusBar (QStatusBar * statusBar)
References m_statusBarArea.
contentView()
QWidget * SketchAreaWidget::contentView ()
References m_contentView.
createLayout()
void SketchAreaWidget::createLayout () protected
References m_leftButtonsContainer, m_middleButtonsContainer, m_rightButtonsContainer, m_statusBarArea, and m_toolbar.
init()
void SketchAreaWidget::init (QWidget * contentView, QMainWindow * parent, bool hasToolBar, bool hasStatusBar) protected
References contentView(), createLayout(), m_contentView, m_statusBarArea, and m_toolbar.
routingStatusLabel()
ExpandingLabel * SketchAreaWidget::routingStatusLabel ()
References m_routingStatusLabel.
separator()
QWidget * SketchAreaWidget::separator (QWidget * parent) static
setRoutingStatusLabel()
void SketchAreaWidget::setRoutingStatusLabel (ExpandingLabel * rsl)
References m_routingStatusLabel.
setToolbarWidgets()
void SketchAreaWidget::setToolbarWidgets (QList< QWidget * > buttons)
References m_leftButtonsContainer, m_middleButtonsContainer, m_rightButtonsContainer, and RoutingStateLabelName.
toolbar()
QFrame * SketchAreaWidget::toolbar ()
References m_toolbar.
Member Data Documentation
m_contentView
QWidget* SketchAreaWidget::m_contentView = nullptr protected
m_leftButtonsContainer
QHBoxLayout* SketchAreaWidget::m_leftButtonsContainer = nullptr protected
m_middleButtonsContainer
QVBoxLayout* SketchAreaWidget::m_middleButtonsContainer = nullptr protected
m_rightButtonsContainer
QHBoxLayout* SketchAreaWidget::m_rightButtonsContainer = nullptr protected
m_routingStatusLabel
ExpandingLabel* SketchAreaWidget::m_routingStatusLabel = nullptr protected
m_statusBarArea
QFrame* SketchAreaWidget::m_statusBarArea = nullptr protected
m_toolbar
QFrame* SketchAreaWidget::m_toolbar = nullptr protected
RoutingStateLabelName
const QString SketchAreaWidget::RoutingStateLabelName = "routingStateLabel" static
The documentation for this class was generated from the following files:
mainwindow/sketchareawidget.h
mainwindow/sketchareawidget.cpp