Fritzing: items/wire.cpp File Reference
wire.cpp File Reference
#include "wire.h"
#include <qmath.h>
#include <QLineF>
#include <QPen>
#include <QRadialGradient>
#include <QBrush>
#include <QGraphicsScene>
#include <QList>
#include <QGraphicsItem>
#include <QSet>
#include <QComboBox>
#include <QToolTip>
#include <QApplication>
#include <QCheckBox>
#include <QHBoxLayout>
#include "../debugdialog.h"
#include "../sketch/infographicsview.h"
#include "../connectors/connectoritem.h"
#include "../connectors/svgidlayer.h"
#include "../fsvgrenderer.h"
#include "partlabel.h"
#include "../model/modelpart.h"
#include "../utils/graphicsutils.h"
#include "../utils/textutils.h"
#include "../utils/bezier.h"
#include "../utils/bezierdisplay.h"
#include "../utils/cursormaster.h"
#include "../utils/ratsnestcolors.h"
#include "../layerattributes.h"
#include <stdlib.h>
Functions
bool alphaLessThan (QColor *c1, QColor *c2)
QBrush BandedBrush (QColor(255, 255, 255))
void debugCompare (ItemBase *it)
Variables
constexpr double DefaultHoverStrokeWidth = 4
QVector< qreal > RatDash
static BezierDisplay * TheBezierDisplay = NULL
static Bezier UndoBezier
Function Documentation
alphaLessThan()
bool alphaLessThan (QColor * c1, QColor * c2)
BandedBrush()
QBrush BandedBrush (QColor(255, 255, 255))
debugCompare()
void debugCompare (ItemBase * it)
References Wire::connector0(), Wire::connector1(), DebugDialog::debug(), ItemBase::debugInfo(), ViewLayer::PCBView, and ItemBase::viewID().
Variable Documentation
DefaultHoverStrokeWidth
constexpr double DefaultHoverStrokeWidth = 4
RatDash
QVector<qreal> RatDash
TheBezierDisplay
BezierDisplay* TheBezierDisplay = NULL static
UndoBezier
Bezier UndoBezier static