Fritzing: lib/quazip/zip.c File Reference
zip.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <zlib.h>
#include "zip.h"
#include <errno.h>
#include "crypt.h"
Classes
struct curfile_info
struct linkedlist_data_s
struct linkedlist_datablock_internal_s
struct zip_internal
Macros
#define ALLOC(size) (malloc(size))
#define BUFREADCOMMENT (0x400)
#define CENTRALHEADERMAGIC (0x02014b50)
#define CRC_LOCALHEADER_OFFSET (0x0e)
#define ENDHEADERMAGIC (0x06054b50)
#define FLAG_LOCALHEADER_OFFSET (0x06)
#define INCLUDECRYPTINGCODE_IFCRYPTALLOWED
#define local static
#define LOCALHEADERMAGIC (0x04034b50)
#define SEEK_CUR 1
#define SEEK_END 2
#define SEEK_SET 0
#define SIZECENTRALHEADER (0x2e) /* 46 */
#define SIZEDATA_INDATABLOCK (4096-(4*4))
#define TRYFREE(p) {if (p) free(p);}
#define VERSIONMADEBY (0x0) /* platform depedent */
#define Z_BUFSIZE (16384)
#define Z_MAXFILENAMEINZIP (256)
Typedefs
typedef struct linkedlist_data_s linkedlist_data
typedef struct linkedlist_datablock_internal_s linkedlist_datablock_internal
Functions
int add_data_in_datablock (linkedlist_data *ll, const void *buf, uLong len)
linkedlist_datablock_internal * allocate_new_datablock ()
void free_datablock (linkedlist_datablock_internal *ldi)
void init_linkedlist (linkedlist_data *ll)
int ziplocal_putValue OF ((const zlib_filefunc_def *pzlib_filefunc_def, voidpf filestream, uLong x, int nbByte))
void ziplocal_putValue_inmemory OF ((void *dest, uLong x, int nbByte))
int ziplocal_getByte OF ((const zlib_filefunc_def *pzlib_filefunc_def, voidpf filestream, int *pi))
int ziplocal_getShort OF ((const zlib_filefunc_def *pzlib_filefunc_def, voidpf filestream, uLong *pX))
uLong ziplocal_SearchCentralDir OF ((const zlib_filefunc_def *pzlib_filefunc_def, voidpf filestream))
int ZEXPORT zipClose (zipFile file, const char *global_comment)
int ZEXPORT zipCloseFileInZip (zipFile file)
int ZEXPORT zipCloseFileInZipRaw (zipFile file, uLong uncompressed_size, uLong crc32)
int zipFlushWriteBuffer (zip_internal *zi)
int ziplocal_getByte (zlib_filefunc_def *pzlib_filefunc_def, voidpf filestream, int *pi) const
int ziplocal_getLong (zlib_filefunc_def *pzlib_filefunc_def, voidpf filestream, uLong *pX) const
int ziplocal_getShort (zlib_filefunc_def *pzlib_filefunc_def, voidpf filestream, uLong *pX) const
int ziplocal_putValue (zlib_filefunc_def *pzlib_filefunc_def, voidpf filestream, uLong x, int nbByte) const
void ziplocal_putValue_inmemory (void *dest, uLong x, int nbByte)
uLong ziplocal_SearchCentralDir (zlib_filefunc_def *pzlib_filefunc_def, voidpf filestream) const
uLong ziplocal_TmzDateToDosDate (tm_zip *ptm, uLong dosDate) const
zipFile ZEXPORT zipOpen (char *pathname, int append) const
zipFile ZEXPORT zipOpen2 (char *pathname, int append, zipcharpc *globalcomment, zlib_filefunc_def *pzlib_filefunc_def) const
int ZEXPORT zipOpenNewFileInZip (zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level)
int ZEXPORT zipOpenNewFileInZip2 (zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level, int raw)
int ZEXPORT zipOpenNewFileInZip3 (zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level, int raw, int windowBits, int memLevel, int strategy, const char *password, uLong crcForCrypting)
int ZEXPORT zipWriteInFileInZip (zipFile file, const void *buf, unsigned len)
Variables
const char zip_copyright []
Macro Definition Documentation
ALLOC
#define ALLOC (size) (malloc(size))
BUFREADCOMMENT
#define BUFREADCOMMENT (0x400)
CENTRALHEADERMAGIC
#define CENTRALHEADERMAGIC (0x02014b50)
CRC_LOCALHEADER_OFFSET
#define CRC_LOCALHEADER_OFFSET (0x0e)
ENDHEADERMAGIC
#define ENDHEADERMAGIC (0x06054b50)
FLAG_LOCALHEADER_OFFSET
#define FLAG_LOCALHEADER_OFFSET (0x06)
INCLUDECRYPTINGCODE_IFCRYPTALLOWED
#define INCLUDECRYPTINGCODE_IFCRYPTALLOWED
local
#define local static
LOCALHEADERMAGIC
#define LOCALHEADERMAGIC (0x04034b50)
SEEK_CUR
#define SEEK_CUR 1
SEEK_END
#define SEEK_END 2
SEEK_SET
#define SEEK_SET 0
SIZECENTRALHEADER
#define SIZECENTRALHEADER (0x2e) /* 46 */
SIZEDATA_INDATABLOCK
#define SIZEDATA_INDATABLOCK (4096-(4*4))
TRYFREE
#define TRYFREE (p) {if (p) free(p);}
VERSIONMADEBY
#define VERSIONMADEBY (0x0) /* platform depedent */
Z_BUFSIZE
#define Z_BUFSIZE (16384)
Z_MAXFILENAMEINZIP
#define Z_MAXFILENAMEINZIP (256)
Typedef Documentation
linkedlist_data
typedef struct linkedlist_data_s linkedlist_data
linkedlist_datablock_internal
typedef struct linkedlist_datablock_internal_s linkedlist_datablock_internal
Function Documentation
add_data_in_datablock()
int add_data_in_datablock (linkedlist_data* ll, const void* buf, uLong len)
References allocate_new_datablock(), linkedlist_datablock_internal_s::avail_in_this_block, linkedlist_datablock_internal_s::data, linkedlist_datablock_internal_s::filled_in_this_block, linkedlist_datablock_internal_s::next_datablock, ZIP_INTERNALERROR, and ZIP_OK.
allocate_new_datablock()
linkedlist_datablock_internal* allocate_new_datablock ()
References ALLOC, linkedlist_datablock_internal_s::avail_in_this_block, linkedlist_datablock_internal_s::filled_in_this_block, linkedlist_datablock_internal_s::next_datablock, and SIZEDATA_INDATABLOCK.
free_datablock()
void free_datablock (linkedlist_datablock_internal* ldi)
References linkedlist_datablock_internal_s::next_datablock, and TRYFREE.
init_linkedlist()
void init_linkedlist (linkedlist_data* ll)
References linkedlist_data_s::first_block.
OF() [1/5]
int ziplocal_putValue OF ((const zlib_filefunc_def *pzlib_filefunc_def, voidpf filestream, uLong x, int nbByte))
OF() [2/5]
void ziplocal_putValue_inmemory OF ((void *dest, uLong x, int nbByte))
OF() [3/5]
int ziplocal_getByte OF ((const zlib_filefunc_def *pzlib_filefunc_def, voidpf filestream, int *pi))
OF() [4/5]
int ziplocal_getShort OF ((const zlib_filefunc_def *pzlib_filefunc_def, voidpf filestream, uLong *pX))
OF() [5/5]
uLong ziplocal_SearchCentralDir OF ((const zlib_filefunc_def *pzlib_filefunc_def, voidpf filestream))
zipClose()
int ZEXPORT zipClose (zipFile file, const char* global_comment)
References zip_internal::add_position_when_writting_offset, zip_internal::central_dir, linkedlist_datablock_internal_s::data, ENDHEADERMAGIC, zip_internal::filestream, linkedlist_datablock_internal_s::filled_in_this_block, linkedlist_data_s::first_block, free_datablock(), zip_internal::globalcomment, zip_internal::in_opened_file_inzip, linkedlist_datablock_internal_s::next_datablock, zip_internal::number_entry, TRYFREE, uLong(), zip_internal::z_filefunc, ZCLOSE, ZIP_ERRNO, ZIP_OK, ZIP_PARAMERROR, zipCloseFileInZip(), ziplocal_putValue(), ZTELL, and ZWRITE.
zipCloseFileInZip()
int ZEXPORT zipCloseFileInZip (zipFile file)
References zipCloseFileInZipRaw().
zipCloseFileInZipRaw()
int ZEXPORT zipCloseFileInZipRaw (zipFile file, uLong uncompressed_size, uLong crc32)
References add_data_in_datablock(), curfile_info::buffered_data, zip_internal::central_dir, curfile_info::central_header, zip_internal::ci, curfile_info::crc32, curfile_info::crypt_header_size, zip_internal::filestream, zip_internal::in_opened_file_inzip, curfile_info::method, zip_internal::number_entry, curfile_info::pos_in_buffered_data, curfile_info::pos_local_header, curfile_info::raw, curfile_info::size_centralheader, curfile_info::stream, curfile_info::stream_initialised, uLong(), Z_BUFSIZE, zip_internal::z_filefunc, ZIP_ERRNO, ZIP_OK, ZIP_PARAMERROR, zipFlushWriteBuffer(), ziplocal_putValue(), ziplocal_putValue_inmemory(), ZLIB_FILEFUNC_SEEK_SET, ZSEEK, and ZTELL.
zipFlushWriteBuffer()
int zipFlushWriteBuffer (zip_internal* zi)
References zencode, ZIP_ERRNO, ZIP_OK, and ZWRITE.
ziplocal_getByte()
int ziplocal_getByte (zlib_filefunc_def* pzlib_filefunc_def, voidpf filestream, int * pi) const
References int(), ZERROR, ZIP_EOF, ZIP_ERRNO, ZIP_OK, and ZREAD.
ziplocal_getLong()
int ziplocal_getLong (zlib_filefunc_def* pzlib_filefunc_def, voidpf filestream, uLong * pX) const
References uLong(), ZIP_OK, and ziplocal_getByte().
ziplocal_getShort()
int ziplocal_getShort (zlib_filefunc_def* pzlib_filefunc_def, voidpf filestream, uLong * pX) const
References uLong(), ZIP_OK, and ziplocal_getByte().
ziplocal_putValue()
int ziplocal_putValue (zlib_filefunc_def* pzlib_filefunc_def, voidpf filestream, uLong x, int nbByte) const
References uLong(), ZIP_ERRNO, ZIP_OK, and ZWRITE.
ziplocal_putValue_inmemory()
void ziplocal_putValue_inmemory (void* dest, uLong x, int nbByte)
ziplocal_SearchCentralDir()
uLong ziplocal_SearchCentralDir (zlib_filefunc_def* pzlib_filefunc_def, voidpf filestream) const
References ALLOC, BUFREADCOMMENT, TRYFREE, uLong(), ZLIB_FILEFUNC_SEEK_END, ZLIB_FILEFUNC_SEEK_SET, ZREAD, ZSEEK, and ZTELL.
ziplocal_TmzDateToDosDate()
uLong ziplocal_TmzDateToDosDate (tm_zip* ptm, uLong dosDate) const
References uLong().
zipOpen()
zipFile ZEXPORT zipOpen (char * pathname, int append) const
References zipOpen2().
zipOpen2()
zipFile ZEXPORT zipOpen2 (char * pathname, int append, zipcharpc* globalcomment, zlib_filefunc_def* pzlib_filefunc_def) const
References add_data_in_datablock(), zip_internal::add_position_when_writting_offset, ALLOC, APPEND_STATUS_ADDINZIP, APPEND_STATUS_CREATE, zip_internal::begin_pos, zip_internal::central_dir, zip_internal::ci, zip_internal::filestream, fill_fopen_filefunc(), zip_internal::globalcomment, zip_internal::in_opened_file_inzip, init_linkedlist(), zip_internal::number_entry, zlib_filefunc_def_s::opaque, SIZEDATA_INDATABLOCK, curfile_info::stream_initialised, TRYFREE, uLong(), zip_internal::z_filefunc, ZCLOSE, ZIP_BADZIPFILE, ZIP_ERRNO, ZIP_OK, ziplocal_getLong(), ziplocal_getShort(), ziplocal_SearchCentralDir(), ZLIB_FILEFUNC_MODE_CREATE, ZLIB_FILEFUNC_MODE_EXISTING, ZLIB_FILEFUNC_MODE_READ, ZLIB_FILEFUNC_MODE_WRITE, ZLIB_FILEFUNC_SEEK_SET, zlib_filefunc_def_s::zopen_file, ZREAD, ZSEEK, and ZTELL.
zipOpenNewFileInZip()
int ZEXPORT zipOpenNewFileInZip (zipFile file, const char* filename, const zip_fileinfo* zipfi, const void* extrafield_local, uInt size_extrafield_local, const void* extrafield_global, uInt size_extrafield_global, const char* comment, int method, int level)
References zipOpenNewFileInZip2().
zipOpenNewFileInZip2()
int ZEXPORT zipOpenNewFileInZip2 (zipFile file, const char* filename, const zip_fileinfo* zipfi, const void* extrafield_local, uInt size_extrafield_local, const void* extrafield_global, uInt size_extrafield_global, const char* comment, int method, int level, int raw)
References DEF_MEM_LEVEL, and zipOpenNewFileInZip3().
zipOpenNewFileInZip3()
int ZEXPORT zipOpenNewFileInZip3 (zipFile file, const char* filename, const zip_fileinfo* zipfi, const void* extrafield_local, uInt size_extrafield_local, const void* extrafield_global, uInt size_extrafield_global, const char* comment, int method, int level, int raw, int windowBits, int memLevel, int strategy, const char* password, uLong crcForCrypting)
References zip_internal::add_position_when_writting_offset, ALLOC, curfile_info::buffered_data, curfile_info::central_header, CENTRALHEADERMAGIC, zip_internal::ci, curfile_info::crc32, curfile_info::crypt_header_size, zip_fileinfo::dosDate, curfile_info::dosDate, curfile_info::encrypt, zip_fileinfo::external_fa, zip_internal::filestream, curfile_info::flag, zip_internal::in_opened_file_inzip, zip_fileinfo::internal_fa, curfile_info::keys, LOCALHEADERMAGIC, curfile_info::method, curfile_info::pcrc_32_tab, curfile_info::pos_in_buffered_data, curfile_info::pos_local_header, curfile_info::raw, curfile_info::size_centralheader, SIZECENTRALHEADER, curfile_info::stream, curfile_info::stream_initialised, zip_fileinfo::tmz_date, uLong(), VERSIONMADEBY, voidpf(), Z_BUFSIZE, zip_internal::z_filefunc, ZIP_ERRNO, ZIP_INTERNALERROR, ZIP_OK, ZIP_PARAMERROR, zipCloseFileInZip(), ziplocal_putValue(), ziplocal_putValue_inmemory(), ziplocal_TmzDateToDosDate(), ZTELL, and ZWRITE.
zipWriteInFileInZip()
int ZEXPORT zipWriteInFileInZip (zipFile file, const void* buf, unsigned len)
References curfile_info::buffered_data, zip_internal::ci, curfile_info::crc32, zip_internal::in_opened_file_inzip, curfile_info::method, curfile_info::pos_in_buffered_data, curfile_info::raw, curfile_info::stream, uLong(), Z_BUFSIZE, ZIP_ERRNO, ZIP_OK, ZIP_PARAMERROR, and zipFlushWriteBuffer().
Variable Documentation
zip_copyright
const char zip_copyright[]
Initial value:
=
   " zip 1.01 Copyright 1998-2004 Gilles Vollant - http://www.winimage.com/zLibDll"