Fritzing: ChangeConnectionCommand Class Reference
ChangeConnectionCommand Class Reference
#include <commands.h>
Public Member Functions
ChangeConnectionCommand (class SketchWidget *sketchWidget, BaseCommand::CrossViewType, long fromID, const QString &fromConnectorID, long toID, const QString &toConnectorID, ViewLayer::ViewLayerPlacement, bool connect, QUndoCommand *parent)
void disable ()
void redo ()
void setUpdateConnections (bool updatem)
void undo ()
Public Member Functions inherited from BaseCommand
BaseCommand (BaseCommand::CrossViewType, SketchWidget *, QUndoCommand *parent)
~BaseCommand ()
void addSubCommand (BaseCommand *subCommand)
BaseCommand::CrossViewType crossViewType () const noexcept
virtual QString getDebugString () const
int index () const
const QUndoCommand * parentCommand () const
void redo ()
void setCrossViewType (BaseCommand::CrossViewType)
void setRedoOnly ()
void setSkipFirstRedo ()
void setUndoOnly ()
SketchWidget * sketchWidget () const
const BaseCommand * subCommand (int index) const
int subCommandCount () const
void subRedo ()
void subRedo (int index)
void subUndo ()
void subUndo (int index)
void undo ()
Protected Member Functions
QString getParamString () const
Protected Attributes
bool m_connect
bool m_enabled
QString m_fromConnectorID
long m_fromID
QString m_toConnectorID
long m_toID
bool m_updateConnections
ViewLayer::ViewLayerPlacement m_viewLayerPlacement
Protected Attributes inherited from BaseCommand
QList< BaseCommand * > m_commands
BaseCommand::CrossViewType m_crossViewType
int m_index = 0
QUndoCommand * m_parentCommand = nullptr
bool m_redoOnly = false
SketchWidget * m_sketchWidget = nullptr
bool m_skipFirstRedo = false
bool m_undoOnly = false
Additional Inherited Members
Public Types inherited from BaseCommand
enum CrossViewType { SingleView, CrossView }
Static Public Member Functions inherited from BaseCommand
static void clearProgress ()
static CommandProgress * initProgress ()
static int totalChildCount (const QUndoCommand *)
Static Protected Attributes inherited from BaseCommand
static CommandProgress m_commandProgress
static int nextIndex = 0
Constructor & Destructor Documentation
ChangeConnectionCommand()
ChangeConnectionCommand::ChangeConnectionCommand (class SketchWidget * sketchWidget, BaseCommand::CrossViewType crossView, long fromID, const QString & fromConnectorID, long toID, const QString & toConnectorID, ViewLayer::ViewLayerPlacement viewLayerPlacement, bool connect, QUndoCommand * parent)
References m_connect, m_enabled, m_fromConnectorID, m_fromID, m_toConnectorID, m_toID, m_updateConnections, and m_viewLayerPlacement.
Member Function Documentation
disable()
void ChangeConnectionCommand::disable ()
References m_enabled.
getParamString()
QString ChangeConnectionCommand::getParamString () const protected virtual
Reimplemented from BaseCommand.
References BaseCommand::getParamString(), m_connect, m_fromConnectorID, m_fromID, m_toConnectorID, m_toID, and m_viewLayerPlacement.
redo()
void ChangeConnectionCommand::redo ()
References SketchWidget::changeConnection(), BaseCommand::CrossView, m_connect, BaseCommand::m_crossViewType, m_enabled, m_fromConnectorID, m_fromID, BaseCommand::m_sketchWidget, m_toConnectorID, m_toID, m_updateConnections, m_viewLayerPlacement, and BaseCommand::redo().
setUpdateConnections()
void ChangeConnectionCommand::setUpdateConnections (bool updatem)
References m_updateConnections.
undo()
void ChangeConnectionCommand::undo ()
References SketchWidget::changeConnection(), BaseCommand::CrossView, m_connect, BaseCommand::m_crossViewType, m_enabled, m_fromConnectorID, m_fromID, BaseCommand::m_sketchWidget, m_toConnectorID, m_toID, m_updateConnections, m_viewLayerPlacement, and BaseCommand::undo().
Member Data Documentation
m_connect
bool ChangeConnectionCommand::m_connect protected
m_enabled
bool ChangeConnectionCommand::m_enabled protected
m_fromConnectorID
QString ChangeConnectionCommand::m_fromConnectorID protected
m_fromID
long ChangeConnectionCommand::m_fromID protected
m_toConnectorID
QString ChangeConnectionCommand::m_toConnectorID protected
m_toID
long ChangeConnectionCommand::m_toID protected
m_updateConnections
bool ChangeConnectionCommand::m_updateConnections protected
m_viewLayerPlacement
ViewLayer::ViewLayerPlacement ChangeConnectionCommand::m_viewLayerPlacement protected
The documentation for this class was generated from the following files:
commands.h
commands.cpp