Fritzing: PrefsDialog Class Reference
PrefsDialog Class Reference
#include <prefsdialog.h>
Public Member Functions
PrefsDialog (const QString &language, QWidget *parent=0)
~PrefsDialog ()
bool cleared ()
void initLayout (QFileInfoList &languages, QList< Platform * > platforms)
void initViewInfo (int index, const QString &viewName, const QString &shortName, bool curvy)
QHash< QString, QString > & settings ()
QHash< QString, QString > & tempSettings ()
Protected Slots
void changeAutosavePeriod (int)
void changeLanguage (int)
void changeWheelBehavior ()
void chooseProgrammer ()
void clear ()
void curvyChanged ()
void setConnectedColor ()
void setUnconnectedColor ()
void toggleAutosave (bool)
Protected Member Functions
QWidget * createAutosaveForm ()
QWidget * createColorForm ()
QWidget * createCurvyForm (ViewInfoThing *)
QWidget * createLanguageForm (QFileInfoList &languages)
QWidget * createOtherForm ()
QWidget * createProgrammerForm (QList< Platform * > platforms)
QWidget * createZoomerForm ()
void initBreadboard (QWidget *, ViewInfoThing *)
void initCode (QWidget *widget, QList< Platform * > platforms)
void initGeneral (QWidget *general, QFileInfoList &languages)
void initPCB (QWidget *, ViewInfoThing *)
void initSchematic (QWidget *, ViewInfoThing *)
void updateWheelText ()
Protected Attributes
QPointer< QWidget > m_breadboard
bool m_cleared = false
QPointer< QWidget > m_code
QPointer< QWidget > m_general
QString m_name
QPointer< QWidget > m_pcb
QList< Platform * > m_platforms
QHash< QString, QLineEdit * > m_programmerLEs
QPointer< QWidget > m_schematic
QHash< QString, QString > m_settings
QPointer< QTabWidget > m_tabWidget
QHash< QString, QString > m_tempSettings
class TranslatorListModel * m_translatorListModel = nullptr
ViewInfoThing m_viewInfoThings [3]
QPointer< QLabel > m_wheelLabel [3]
int m_wheelMapping = 0
Constructor & Destructor Documentation
PrefsDialog()
PrefsDialog::PrefsDialog (const QString & language, QWidget * parent = 0)
References int(), m_cleared, m_name, m_wheelMapping, and ZoomableGraphicsView::wheelMapping().
~PrefsDialog()
PrefsDialog::~PrefsDialog ()
Member Function Documentation
changeAutosavePeriod
void PrefsDialog::changeAutosavePeriod (int value) protected slot
References m_settings.
changeLanguage
void PrefsDialog::changeLanguage (int index) protected slot
References TranslatorListModel::locale(), m_name, m_settings, and m_translatorListModel.
changeWheelBehavior
void PrefsDialog::changeWheelBehavior () protected slot
References m_settings, m_wheelMapping, updateWheelText(), and ZoomableGraphicsView::WheelMappingCount.
chooseProgrammer
void PrefsDialog::chooseProgrammer () protected slot
References Platform::getName(), FolderUtils::getOpenFileName(), m_platforms, m_programmerLEs, FolderUtils::openSaveFolder(), and Platform::setCommandLocation().
clear
void PrefsDialog::clear () protected slot
References m_cleared.
cleared()
bool PrefsDialog::cleared ()
References m_cleared.
createAutosaveForm()
QWidget * PrefsDialog::createAutosaveForm () protected
References MainWindow::AutosaveEnabled, MainWindow::AutosaveTimeoutMinutes, changeAutosavePeriod(), FORMLABELWIDTH, SPACING, and toggleAutosave().
createColorForm()
QWidget * PrefsDialog::createColorForm () protected
References ItemBase::connectedColor(), FORMLABELWIDTH, MARGIN, setConnectedColor(), setUnconnectedColor(), SPACING, and ItemBase::unconnectedColor().
createCurvyForm()
QWidget * PrefsDialog::createCurvyForm (ViewInfoThing * viewInfoThing) protected
References ViewInfoThing::curvy, curvyChanged(), and ViewInfoThing::index.
createLanguageForm()
QWidget * PrefsDialog::createLanguageForm (QFileInfoList & languages) protected
References changeLanguage(), TranslatorListModel::findIndex(), m_name, and m_translatorListModel.
createOtherForm()
QWidget * PrefsDialog::createOtherForm () protected
References clear(), FORMLABELWIDTH, and SPACING.
createProgrammerForm()
QWidget * PrefsDialog::createProgrammerForm (QList< Platform * > platforms) protected
References chooseProgrammer(), Platform::getCommandLocation(), Platform::getDownloadUrl(), Platform::getIdeName(), Platform::getMinVersion(), Platform::getName(), m_programmerLEs, and SPACING.
createZoomerForm()
QWidget * PrefsDialog::createZoomerForm () protected
References changeWheelBehavior(), FORMLABELWIDTH, m_wheelLabel, SPACING, and updateWheelText().
curvyChanged
void PrefsDialog::curvyChanged () protected slot
References m_settings, m_viewInfoThings, and ViewInfoThing::shortName.
initBreadboard()
void PrefsDialog::initBreadboard (QWidget * widget, ViewInfoThing * viewInfoThing) protected
References createCurvyForm().
initCode()
void PrefsDialog::initCode (QWidget * widget, QList< Platform * > platforms) protected
References createProgrammerForm().
initGeneral()
void PrefsDialog::initGeneral (QWidget * general, QFileInfoList & languages) protected
References createAutosaveForm(), createColorForm(), createLanguageForm(), createOtherForm(), and createZoomerForm().
initLayout()
void PrefsDialog::initLayout (QFileInfoList & languages, QList< Platform * > platforms)
References initBreadboard(), initCode(), initGeneral(), initPCB(), initSchematic(), m_breadboard, m_code, m_general, m_pcb, m_platforms, m_schematic, m_tabWidget, and m_viewInfoThings.
initPCB()
void PrefsDialog::initPCB (QWidget * widget, ViewInfoThing * viewInfoThing) protected
References createCurvyForm().
initSchematic()
void PrefsDialog::initSchematic (QWidget * widget, ViewInfoThing * viewInfoThing) protected
References createCurvyForm().
initViewInfo()
void PrefsDialog::initViewInfo (int index, const QString & viewName, const QString & shortName, bool curvy)
References ViewInfoThing::curvy, ViewInfoThing::index, m_viewInfoThings, ViewInfoThing::shortName, and ViewInfoThing::viewName.
setConnectedColor
void PrefsDialog::setConnectedColor () protected slot
References ItemBase::connectedColor(), m_settings, SetColorDialog::selectedColor(), and ItemBase::standardConnectedColor().
settings()
QHash< QString, QString > & PrefsDialog::settings ()
References m_settings.
setUnconnectedColor
void PrefsDialog::setUnconnectedColor () protected slot
References m_settings, SetColorDialog::selectedColor(), ItemBase::standardUnconnectedColor(), and ItemBase::unconnectedColor().
tempSettings()
QHash< QString, QString > & PrefsDialog::tempSettings ()
References m_tempSettings.
toggleAutosave
void PrefsDialog::toggleAutosave (bool checked) protected slot
References m_settings.
updateWheelText()
void PrefsDialog::updateWheelText () protected
References m_wheelLabel, m_wheelMapping, ZoomableGraphicsView::ScrollPrimary, and ZoomableGraphicsView::ZoomPrimary.
Member Data Documentation
m_breadboard
QPointer<QWidget> PrefsDialog::m_breadboard protected
m_cleared
bool PrefsDialog::m_cleared = false protected
m_code
QPointer<QWidget> PrefsDialog::m_code protected
m_general
QPointer<QWidget> PrefsDialog::m_general protected
m_name
QString PrefsDialog::m_name protected
m_pcb
QPointer<QWidget> PrefsDialog::m_pcb protected
m_platforms
QList<Platform *> PrefsDialog::m_platforms protected
m_programmerLEs
QHash<QString, QLineEdit *> PrefsDialog::m_programmerLEs protected
m_schematic
QPointer<QWidget> PrefsDialog::m_schematic protected
m_settings
QHash<QString, QString> PrefsDialog::m_settings protected
m_tabWidget
QPointer<QTabWidget> PrefsDialog::m_tabWidget protected
m_tempSettings
QHash<QString, QString> PrefsDialog::m_tempSettings protected
m_translatorListModel
class TranslatorListModel* PrefsDialog::m_translatorListModel = nullptr protected
m_viewInfoThings
ViewInfoThing PrefsDialog::m_viewInfoThings[3] protected
m_wheelLabel
QPointer<QLabel> PrefsDialog::m_wheelLabel[3] protected
m_wheelMapping
int PrefsDialog::m_wheelMapping = 0 protected
The documentation for this class was generated from the following files:
dialogs/prefsdialog.h
dialogs/prefsdialog.cpp