Fritzing: SVG2gerber Class Reference
SVG2gerber Class Reference
#include <svg2gerber.h>
Public Types
enum ForWhy {
ForCopper, ForSilk, ForOutline, ForMask,
ForDrill, ForPasteMask
}
Public Member Functions
SVG2gerber ()=default
int convert (const QString &svgStr, bool doubleSided, const QString &mainLayerName, ForWhy, QSizeF boardSize)
QString getGerber ()
Protected Slots
void path2gerbCommandSlot (QChar command, bool relative, QList< double > &args, void *userData)
Protected Member Functions
int allPaths2gerber (ForWhy)
void convertShapes2paths (QDomNode)
void copyStyles (QDomElement, QDomElement)
void doPoly (QDomElement &polygon, ForWhy forWhy, bool closedCurve, QHash< QString, QString > &apertureMap, QString &current_dcode, int &dcode_index)
QDomElement ellipse2path (QDomElement)
void flattenSVG (QDomNode)
int flipx (double x)
double flipxNoRound (double x)
int flipy (double y)
double flipyNoRound (double y)
void handleOblongPath (QDomElement &path, int &dcode_index)
void normalizeSVG ()
QMatrix parseTransform (QDomElement)
QString path2gerber (QDomElement)
int renderGerber (bool doubleSided, const QString &mainLayerName, ForWhy)
QString standardAperture (QDomElement &element, QHash< QString, QString > &apertureMap, QString &current_dcode, int &dcode_index, double stroke_width)
Protected Attributes
QSizeF m_boardSize
QString m_drill_slots
QString m_gerber_header
QString m_gerber_paths
QMultiHash< QString, QString > m_holeApertures
double m_pathstart_x = 0.0
double m_pathstart_y = 0.0
QMultiHash< QString, QString > m_platedApertures
QDomDocument m_SVGDom
Member Enumeration Documentation
ForWhy
enum SVG2gerber::ForWhy
Enumerator
ForCopper
ForSilk
ForOutline
ForMask
ForDrill
ForPasteMask
Constructor & Destructor Documentation
SVG2gerber()
SVG2gerber::SVG2gerber () default
Member Function Documentation
allPaths2gerber()
int SVG2gerber::allPaths2gerber (ForWhy forWhy) protected
References DebugDialog::debug(), doPoly(), fillNotStroke(), flipx(), flipxNoRound(), flipy(), flipyNoRound(), ForCopper, ForDrill, ForMask, ForOutline, ForSilk, handleOblongPath(), m_gerber_header, m_gerber_paths, m_holeApertures, m_platedApertures, m_SVGDom, MaskClearance, SvgFileSplitter::parsePath(), path2gerbCommandSlot(), PathUserData::pathStarting, standardAperture(), PathUserData::string, PathUserData::x, and PathUserData::y.
convert()
int SVG2gerber::convert (const QString & svgStr, bool doubleSided, const QString & mainLayerName, ForWhy forWhy, QSizeF boardSize)
References DebugDialog::debug(), m_boardSize, m_SVGDom, normalizeSVG(), and renderGerber().
convertShapes2paths()
void SVG2gerber::convertShapes2paths (QDomNode node) protected
References copyStyles(), DebugDialog::debug(), and ellipse2path().
copyStyles()
void SVG2gerber::copyStyles (QDomElement source, QDomElement dest) protected
doPoly()
void SVG2gerber::doPoly (QDomElement & polygon, ForWhy forWhy, bool closedCurve, QHash< QString, QString > & apertureMap, QString & current_dcode, int & dcode_index) protected
References fillNotStroke(), flipx(), flipy(), ForMask, m_gerber_paths, MaskClearance, and standardAperture().
ellipse2path()
QDomElement SVG2gerber::ellipse2path (QDomElement ellipseElement) protected
flattenSVG()
void SVG2gerber::flattenSVG (QDomNode) protected
flipx()
int SVG2gerber::flipx (double x) protected
flipxNoRound()
double SVG2gerber::flipxNoRound (double x) protected
flipy()
int SVG2gerber::flipy (double y) protected
References m_boardSize.
flipyNoRound()
double SVG2gerber::flipyNoRound (double y) protected
References m_boardSize.
getGerber()
QString SVG2gerber::getGerber ()
References m_gerber_header, and m_gerber_paths.
handleOblongPath()
void SVG2gerber::handleOblongPath (QDomElement & path, int & dcode_index) protected
References flipxNoRound(), flipyNoRound(), m_drill_slots, and m_gerber_header.
normalizeSVG()
void SVG2gerber::normalizeSVG () protected
References convertShapes2paths(), SvgFlattener::flattenChildren(), and m_SVGDom.
parseTransform()
QMatrix SVG2gerber::parseTransform (QDomElement element) protected
path2gerbCommandSlot
void SVG2gerber::path2gerbCommandSlot (QChar command, bool relative, QList< double > & args, void * userData) protected slot
References DebugDialog::debug(), flipx(), flipy(), m_pathstart_x, m_pathstart_y, PathUserData::pathStarting, PathUserData::string, PathUserData::x, and PathUserData::y.
path2gerber()
QString SVG2gerber::path2gerber (QDomElement pathElement) protected
renderGerber()
int SVG2gerber::renderGerber (bool doubleSided, const QString & mainLayerName, ForWhy forWhy) protected
References allPaths2gerber(), ForDrill, m_gerber_header, m_gerber_paths, m_holeApertures, and m_platedApertures.
standardAperture()
QString SVG2gerber::standardAperture (QDomElement & element, QHash< QString, QString > & apertureMap, QString & current_dcode, int & dcode_index, double stroke_width) protected
References m_gerber_header, and m_gerber_paths.
Member Data Documentation
m_boardSize
QSizeF SVG2gerber::m_boardSize protected
m_drill_slots
QString SVG2gerber::m_drill_slots protected
m_gerber_header
QString SVG2gerber::m_gerber_header protected
m_gerber_paths
QString SVG2gerber::m_gerber_paths protected
m_holeApertures
QMultiHash<QString, QString> SVG2gerber::m_holeApertures protected
m_pathstart_x
double SVG2gerber::m_pathstart_x = 0.0 protected
m_pathstart_y
double SVG2gerber::m_pathstart_y = 0.0 protected
m_platedApertures
QMultiHash<QString, QString> SVG2gerber::m_platedApertures protected
m_SVGDom
QDomDocument SVG2gerber::m_SVGDom protected
The documentation for this class was generated from the following files:
svg/svg2gerber.h
svg/svg2gerber.cpp