Fritzing: Kicad2Svg Class Reference
Kicad2Svg Class Reference
#include <kicad2svg.h>
Public Member Functions
Kicad2Svg ()
QString endMetadata ()
QString makeMetadata (const QString &filename, const QString &type, const QString &name)
Public Member Functions inherited from X2Svg
X2Svg ()
void checkXLimit (double x)
void checkYLimit (double y)
Protected Attributes
QString m_description
QString m_title
Protected Attributes inherited from X2Svg
QString m_attribute
QString m_comment
double m_maxX
double m_maxY
double m_minX
double m_minY
Additional Inherited Members
Protected Member Functions inherited from X2Svg
void initLimits ()
QString offsetMin (const QString &svg)
QString unquote (const QString &)
Constructor & Destructor Documentation
Kicad2Svg()
Kicad2Svg::Kicad2Svg ()
Member Function Documentation
endMetadata()
QString Kicad2Svg::endMetadata ()
makeMetadata()
QString Kicad2Svg::makeMetadata (const QString & filename, const QString & type, const QString & name)
References TextUtils::escapeAnd(), X2Svg::m_attribute, m_description, m_title, TextUtils::stripNonValidXMLCharacters(), and Version::versionString().
Member Data Documentation
m_description
QString Kicad2Svg::m_description protected
m_title
QString Kicad2Svg::m_title protected
The documentation for this class was generated from the following files:
svg/kicad2svg.h
svg/kicad2svg.cpp