Fritzing: LockManager Class Reference
LockManager Class Reference
#include <lockmanager.h>
Public Slots
void touchFiles ()
Public Member Functions
LockManager ()
~LockManager ()
Static Public Member Functions
static void checkLockedFiles (const QString &prefix, QFileInfoList &backupList, QHash< QString, LockedFile * > &lockedFiles, bool recurse, long touchFrequency)
static void cleanup ()
static void initLockedFiles (const QString &prefix, QString &folder, QHash< QString, LockedFile * > &lockedFiles, long touchFrequency)
static void releaseLockedFiles (const QString &folder, QHash< QString, LockedFile * > &lockedFiles)
Static Public Attributes
static const long FastTime = 2000
static const QString LockedFileName = "___lockfile___.txt"
static const long SlowTime = 240000
Static Protected Member Functions
static bool checkLockedFilesAux (const QDir &parent, QStringList &filters)
static LockedFile * makeLockedFile (const QString &folder, long touchFrequency)
static void releaseLockedFiles (const QString &folder, QHash< QString, LockedFile * > &lockedFiles, bool remove)
Constructor & Destructor Documentation
LockManager()
LockManager::LockManager ()
~LockManager()
LockManager::~LockManager ()
References TheTimers.
Member Function Documentation
checkLockedFiles()
void LockManager::checkLockedFiles (const QString & prefix, QFileInfoList & backupList, QHash< QString, LockedFile * > & lockedFiles, bool recurse, long touchFrequency) static
References checkLockedFilesAux(), FolderUtils::getTopLevelUserDataStorePath(), LockedFileName, makeLockedFile(), and FolderUtils::rmdir().
checkLockedFilesAux()
bool LockManager::checkLockedFilesAux (const QDir & parent, QStringList & filters) static protected
cleanup()
void LockManager::cleanup () static
References TheTimers.
initLockedFiles()
void LockManager::initLockedFiles (const QString & prefix, QString & folder, QHash< QString, LockedFile * > & lockedFiles, long touchFrequency) static
References TextUtils::getRandText(), FolderUtils::getTopLevelUserDataStorePath(), LockedFileName, and makeLockedFile().
makeLockedFile()
LockedFile * LockManager::makeLockedFile (const QString & folder, long touchFrequency) static protected
References TheLockedFiles, TheLockManager, TheMutex, TheTimers, LockedFile::touch(), and touchFiles().
releaseLockedFiles() [1/2]
void LockManager::releaseLockedFiles (const QString & folder, QHash< QString, LockedFile * > & lockedFiles) static
releaseLockedFiles() [2/2]
void LockManager::releaseLockedFiles (const QString & folder, QHash< QString, LockedFile * > & lockedFiles, bool remove) static protected
References LockedFile::frequency, FolderUtils::rmdir(), TheLockedFiles, and TheMutex.
touchFiles
void LockManager::touchFiles () slot
References TheLockedFiles, TheMutex, and LockedFile::touch().
Member Data Documentation
FastTime
const long LockManager::FastTime = 2000 static
LockedFileName
const QString LockManager::LockedFileName = "___lockfile___.txt" static
SlowTime
const long LockManager::SlowTime = 240000 static
The documentation for this class was generated from the following files:
utils/lockmanager.h
utils/lockmanager.cpp