Fritzing: PartsBinIconView Class Reference
PartsBinIconView Class Reference
#include <partsbiniconview.h>
Public Slots
void informNewSelection ()
void itemMoved (int fromIndex, int toIndex)
void setSelected (int position, bool doEmit=false)
Public Slots inherited from InfoGraphicsView
virtual void resizeBoard (double w, double h, bool doEmit)
virtual void setInstanceTitle (long id, const QString &oldTitle, const QString &newTitle, bool isUndoable, bool doEmit)
virtual void setVoltage (double, bool doEmit)
Signals
void informItemMoved (int fromIndex, int toIndex)
void selectionChanged (int index)
void settingItem ()
Signals inherited from InfoGraphicsView
void changePinLabelsSignal (ItemBase *, bool singleRow)
void newWireSignal (Wire *)
void setActiveConnectorItemSignal (ConnectorItem *)
void setActiveWireSignal (Wire *)
void setVoltageSignal (double, bool doEmit)
void swapSignal (const QString &family, const QString &prop, QMap< QString, QString > &propsMap, ItemBase *)
Signals inherited from ZoomableGraphicsView
void wheelSignal ()
void zoomChanged (double zoom)
void zoomOutOfRange (double zoom)
Public Member Functions
PartsBinIconView (ReferenceModel *referenceModel, PartsBinPaletteWidget *parent)
void addPart (ModelPart *model, int position=-1)
void loadFromModel (PaletteModel *)
QList< QObject * > orderedChildren ()
void reloadPart (const QString &moduleID)
void removePart (const QString &moduleID)
void removeParts ()
int selectedIndex ()
ItemBase * selectedItemBase ()
ModelPart * selectedModelPart ()
void setPaletteModel (PaletteModel *model, bool clear=false)
bool swappingEnabled (ItemBase *)
Public Member Functions inherited from InfoGraphicsView
InfoGraphicsView (QWidget *parent=0)
int boardLayers ()
virtual void changeBus (ItemBase *, bool connect, const QString &oldBus, const QString &newBus, QList< ConnectorItem * > &, const QString &message, const QString &oldLayout, const QString &newLayout)
virtual void changePinLabels (ItemBase *, bool singleRow)
virtual void changeWireColor (const QString newColor)
virtual void changeWireWidthMils (const QString newWidth)
virtual bool curvyWiresIndicated (Qt::KeyboardModifiers)
virtual const QString & filenameIf ()
virtual QString generateCopperFillUnit (ItemBase *itemBase, QPointF whereToStart)
virtual void getBendpointWidths (class Wire *, double w, double &w1, double &w2, bool &negativeOffsetRect)
virtual void getLabelFont (QFont &, QColor &, ItemBase *)
virtual double getLabelFontSizeLarge ()
virtual double getLabelFontSizeMedium ()
virtual double getLabelFontSizeSmall ()
virtual double getLabelFontSizeTiny ()
virtual void getRatsnestColor (QColor &)
virtual ViewGeometry::WireFlag getTraceFlag ()
virtual double getWireStrokeWidth (Wire *, double wireWidth)
virtual bool hasBigDots ()
virtual void hidePartLabel (ItemBase *item)
virtual void hoverEnterConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *)
virtual void hoverEnterItem (QGraphicsSceneHoverEvent *event, ItemBase *)
virtual void hoverLeaveConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *)
virtual void hoverLeaveItem (QGraphicsSceneHoverEvent *event, ItemBase *)
class HtmlInfoView * infoView ()
virtual void initWire (class Wire *, int penWidth)
virtual void loadLogoImage (ItemBase *, const QString &oldSvg, const QSizeF oldAspectRatio, const QString &oldFilename, const QString &newFilename, bool addName)
virtual class VirtualWire * makeOneRatsnestWire (ConnectorItem *source, ConnectorItem *dest, bool routed, QColor, bool force)
virtual void mousePressConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual void moveItem (ItemBase *, double x, double y)
virtual void newWire (Wire *)
virtual void noteChanged (ItemBase *, const QString &oldText, const QString &newText, QSizeF oldSize, QSizeF newSize)
virtual void noteSizeChanged (ItemBase *itemBase, const QSizeF &oldSize, const QSizeF &newSize)
virtual void partLabelChanged (ItemBase *, const QString &oldText, const QString &newText)
virtual void partLabelMoved (ItemBase *, QPointF oldPos, QPointF oldOffset, QPointF newPos, QPointF newOffset)
virtual void prepLegBendpointChange (ConnectorItem *from, int oldCount, int newCount, int index, QPointF pos, const class Bezier *, const class Bezier *, const class Bezier *, bool triggerFirstTime)
virtual void prepLegBendpointMove (ConnectorItem *from, int index, QPointF oldPos, QPointF newPos, ConnectorItem *to, bool changeConnections)
virtual void prepLegCurveChange (ConnectorItem *from, int index, const class Bezier *oldB, const class Bezier *newB, bool triggerFirstTime)
virtual void prepLegSelection (ItemBase *)
virtual void renamePins (ItemBase *, const QStringList &oldLabels, const QStringList &newLabels, bool singleRow)
virtual void resolveTemporary (bool, ItemBase *)
virtual void rotateFlipPartLabel (ItemBase *, double degrees, Qt::Orientations flipDirection)
virtual void rotateX (double degrees, bool rubberBandLegEnabled, ItemBase *originatingItem)
void setActiveConnectorItem (ConnectorItem *)
void setActiveWire (Wire *)
virtual void setAnyInRotation ()
virtual void setBoardLayers (int, bool redraw)
virtual void setHoleSize (ItemBase *, const QString &propName, const QString &translatedPropName, const QString &oldValue, const QString &newValue, QRectF &oldRect, QRectF &newRect, bool redraw)
virtual void setIgnoreSelectionChangeEvents (bool)
void setInfoView (class HtmlInfoView *)
virtual void setNoteFocus (QGraphicsItem *, bool inFocus)
virtual void setProp (ItemBase *, const QString &propName, const QString &translatedPropName, const QString &oldValue, const QString &newValue, bool redraw)
virtual void setResistance (QString resistance, QString pinSpacing)
void setSMDOrientation (Qt::Orientations)
Qt::Orientations smdOrientation ()
virtual bool spaceBarIsPressed ()
virtual void swap (const QString &family, const QString &prop, QMap< QString, QString > &propsMap, ItemBase *)
virtual void triggerRotate (ItemBase *, double degrees)
void updateRotation (ItemBase *)
virtual void viewItemInfo (ItemBase *)
virtual LayerHash & viewLayers ()
Public Member Functions inherited from ZoomableGraphicsView
ZoomableGraphicsView (QWidget *parent=0)
void absoluteZoom (double percent)
double currentZoom ()
virtual void ensureFixedToBottomRightItems ()
void relativeZoom (double step, bool centerToCursor)
void setAcceptWheelEvents (bool)
virtual void setViewFromBelow (bool)
bool viewFromBelow ()
Public Member Functions inherited from PartsBinView
PartsBinView (ReferenceModel *referenceModel, PartsBinPaletteWidget *parent)
virtual ~PartsBinView ()=default
void addPart (ModelPart *model, int position=-1)
bool contains (const QString &moduleID)
void dropEventAux (QDropEvent *event, bool justAppend=false)
void reloadParts (PaletteModel *model)
void setInfoViewOnHover (bool infoViewOnHover)
Protected Slots
void showContextMenu (const QPoint &pos)
Protected Member Functions
QGraphicsWidget * closestItemTo (const QPoint &pos)
void doClear ()
void dragMoveEvent (QDragMoveEvent *event)
void dropEvent (QDropEvent *event)
bool inEmptyArea (const QPoint &pos)
int itemIndexAt (const QPoint &pos, bool &trustIt)
ItemBase * loadItemBase (const QString &moduleID, ItemBase::PluralType &)
void mousePressEvent (QMouseEvent *event)
void moveItem (int fromIndex, int toIndex)
void resizeEvent (QResizeEvent *event)
int setItemAux (ModelPart *, int position=-1)
void setupLayout ()
SvgIconWidget * svgIconWidgetAt (const QPoint &pos)
SvgIconWidget * svgIconWidgetAt (int x, int y)
void updateSize (QSize newSize)
void updateSize ()
void updateSizeAux (int width)
Protected Member Functions inherited from InfoGraphicsView
QGraphicsItem * selectedAux ()
Protected Member Functions inherited from ZoomableGraphicsView
virtual void wheelEvent (QWheelEvent *event)
Protected Member Functions inherited from PartsBinView
void dragMoveEnterEventAux (QDragMoveEvent *event)
void mousePressOnItem (const QPoint &dragStartPos, const QString &moduleId, const QSize &size, const QPointF &dataPoint=QPointF(0, 0), const QPoint &hotspot=QPoint(0, 0))
void setItem (ModelPart *modelPart)
virtual void setSelected (int position, bool doEmit=false)=0
Protected Attributes
QMenu * m_itemMenu = nullptr
GraphicsFlowLayout * m_layout = nullptr
QGraphicsWidget * m_layouter = nullptr
bool m_noSelectionChangeEmition = false
LayerHash m_viewLayers
Protected Attributes inherited from InfoGraphicsView
int m_boardLayers
bool m_hoverEnterConnectorMode
bool m_hoverEnterMode
class HtmlInfoView * m_infoView
Qt::Orientations m_smdOrientation
Protected Attributes inherited from ZoomableGraphicsView
bool m_acceptWheelEvents
int m_maxScaleValue
int m_minScaleValue
double m_scaleValue
bool m_viewFromBelow
Protected Attributes inherited from PartsBinView
QPoint m_dragStartPos
bool m_infoViewOnHover = false
QHash< QString, class ItemBase * > m_itemBaseHash
PartsBinPaletteWidget * m_parent = nullptr
ReferenceModel * m_referenceModel = nullptr
Additional Inherited Members
Public Types inherited from ZoomableGraphicsView
enum WheelMapping { ScrollPrimary, ZoomPrimary, WheelMappingCount }
Static Public Member Functions inherited from InfoGraphicsView
static InfoGraphicsView * getInfoGraphicsView (QGraphicsItem *)
Static Public Member Functions inherited from ZoomableGraphicsView
static void setWheelMapping (WheelMapping)
static WheelMapping wheelMapping ()
Static Public Member Functions inherited from PartsBinView
static void cleanup ()
static void removePartReference (const QString &moduleID)
Static Public Attributes inherited from ZoomableGraphicsView
static const int MaxScaleValue = 3000
Static Public Attributes inherited from PartsBinView
static QHash< QString, QString > TranslatedCategoryNames
Static Protected Attributes inherited from ZoomableGraphicsView
static WheelMapping m_wheelMapping
Static Protected Attributes inherited from PartsBinView
static QHash< QString, class ItemBase * > ItemBaseHash
Constructor & Destructor Documentation
PartsBinIconView()
PartsBinIconView::PartsBinIconView (ReferenceModel * referenceModel, PartsBinPaletteWidget * parent)
References ZoomableGraphicsView::setAcceptWheelEvents(), setupLayout(), and showContextMenu().
Member Function Documentation
addPart()
void PartsBinIconView::addPart (ModelPart * model, int position = -1)
References PartsBinView::addPart(), and updateSize().
closestItemTo()
QGraphicsWidget * PartsBinIconView::closestItemTo (const QPoint & pos) protected
References ICON_SPACING, and svgIconWidgetAt().
doClear()
void PartsBinIconView::doClear () protected virtual
Reimplemented from PartsBinView.
References GraphicsFlowLayout::clear(), PartsBinView::doClear(), m_layout, m_layouter, and setupLayout().
dragMoveEvent()
void PartsBinIconView::dragMoveEvent (QDragMoveEvent * event) protected
References PartsBinView::dragMoveEnterEventAux().
dropEvent()
void PartsBinIconView::dropEvent (QDropEvent * event) protected
References PartsBinView::dropEventAux().
inEmptyArea()
bool PartsBinIconView::inEmptyArea (const QPoint & pos) protected
References m_layout.
informItemMoved
void PartsBinIconView::informItemMoved (int fromIndex, int toIndex) signal
informNewSelection
void PartsBinIconView::informNewSelection () slot
References m_noSelectionChangeEmition, selectedIndex(), and selectionChanged().
itemIndexAt()
int PartsBinIconView::itemIndexAt (const QPoint & pos, bool & trustIt) protected virtual
Implements PartsBinView.
References closestItemTo(), GraphicsFlowLayout::indexOf(), inEmptyArea(), m_layout, and svgIconWidgetAt().
itemMoved
void PartsBinIconView::itemMoved (int fromIndex, int toIndex) slot
References m_layout, setSelected(), and updateSize().
loadFromModel()
void PartsBinIconView::loadFromModel (PaletteModel * model)
References ViewLayer::IconView, ModelPart::instanceDomElement(), ModelBase::root(), setItemAux(), and ViewLayer::viewIDXmlName().
loadItemBase()
ItemBase * PartsBinIconView::loadItemBase (const QString & moduleID, ItemBase::PluralType & plural) protected
References PartFactory::createPart(), ItemBase::getNextID(), ViewLayer::IconView, ItemBase::isPlural(), PartsBinView::ItemBaseHash, PartsBinView::m_itemBaseHash, PartsBinView::m_referenceModel, ViewLayer::NewTop, ItemBase::NotSure, ItemBase::Plural, ModelPart::properties(), ReferenceModel::propValues(), and ReferenceModel::retrieveModelPart().
mousePressEvent()
void PartsBinIconView::mousePressEvent (QMouseEvent * event) protected
References informNewSelection(), SvgIconWidget::itemBase(), SvgIconWidget::moduleID(), PartsBinView::mousePressOnItem(), svgIconWidgetAt(), and InfoGraphicsView::viewItemInfo().
moveItem()
void PartsBinIconView::moveItem (int fromIndex, int toIndex) protected virtual
Implements PartsBinView.
References informItemMoved(), and itemMoved().
orderedChildren()
QList< QObject * > PartsBinIconView::orderedChildren () virtual
Implements PartsBinView.
References m_layout, and SvgIconWidget::modelPart().
reloadPart()
void PartsBinIconView::reloadPart (const QString & moduleID) virtual
Implements PartsBinView.
References PartsBinView::contains(), SvgIconWidget::itemBase(), loadItemBase(), m_layout, ItemBase::moduleID(), and SvgIconWidget::setItemBase().
removePart()
void PartsBinIconView::removePart (const QString & moduleID) virtual
Implements PartsBinView.
References PartsBinView::m_itemBaseHash, m_layout, m_layouter, m_noSelectionChangeEmition, SvgIconWidget::moduleID(), setSelected(), and updateSize().
removeParts()
void PartsBinIconView::removeParts () virtual
Implements PartsBinView.
References PartsBinView::m_itemBaseHash, m_layout, m_layouter, m_noSelectionChangeEmition, and updateSize().
resizeEvent()
void PartsBinIconView::resizeEvent (QResizeEvent * event) protected
References updateSize().
selectedIndex()
int PartsBinIconView::selectedIndex ()
selectedItemBase()
ItemBase * PartsBinIconView::selectedItemBase () virtual
Implements PartsBinView.
References SvgIconWidget::itemBase(), and InfoGraphicsView::selectedAux().
selectedModelPart()
ModelPart * PartsBinIconView::selectedModelPart () virtual
Implements PartsBinView.
References SvgIconWidget::modelPart(), and InfoGraphicsView::selectedAux().
selectionChanged
void PartsBinIconView::selectionChanged (int index) signal
setItemAux()
int PartsBinIconView::setItemAux (ModelPart * modelPart, int position = -1) protected virtual
Implements PartsBinView.
References PartsBinView::contains(), ViewLayer::IconView, ModelPart::itemType(), loadItemBase(), m_layout, ModelPart::moduleID(), ItemBase::Plural, settingItem(), ModelPart::Space, and ModelPart::Unknown.
setPaletteModel()
void PartsBinIconView::setPaletteModel (PaletteModel * model, bool clear = false) virtual
Reimplemented from PartsBinView.
References PartsBinView::setPaletteModel(), and updateSize().
setSelected
void PartsBinIconView::setSelected (int position, bool doEmit = false) slot
References m_layout, and m_noSelectionChangeEmition.
settingItem
void PartsBinIconView::settingItem () signal
setupLayout()
void PartsBinIconView::setupLayout () protected
References ICON_SPACING, m_layout, and m_layouter.
showContextMenu
void PartsBinIconView::showContextMenu (const QPoint & pos) protected slot
References PartsBinPaletteWidget::combinedMenu(), PartsBinView::m_parent, PartsBinPaletteWidget::partContextMenu(), and svgIconWidgetAt().
svgIconWidgetAt() [1/2]
SvgIconWidget * PartsBinIconView::svgIconWidgetAt (const QPoint & pos) protected
svgIconWidgetAt() [2/2]
SvgIconWidget * PartsBinIconView::svgIconWidgetAt (int x, int y) protected
References svgIconWidgetAt().
swappingEnabled()
bool PartsBinIconView::swappingEnabled (ItemBase * itemBase) virtual
Implements InfoGraphicsView.
updateSize() [1/2]
void PartsBinIconView::updateSize (QSize newSize) protected
References updateSizeAux().
updateSize() [2/2]
void PartsBinIconView::updateSize () protected
References updateSizeAux().
updateSizeAux()
void PartsBinIconView::updateSizeAux (int width) protected
References GraphicsFlowLayout::heightForWidth(), and m_layout.
Member Data Documentation
m_itemMenu
QMenu* PartsBinIconView::m_itemMenu = nullptr protected
m_layout
GraphicsFlowLayout* PartsBinIconView::m_layout = nullptr protected
m_layouter
QGraphicsWidget* PartsBinIconView::m_layouter = nullptr protected
m_noSelectionChangeEmition
bool PartsBinIconView::m_noSelectionChangeEmition = false protected
m_viewLayers
LayerHash PartsBinIconView::m_viewLayers protected
The documentation for this class was generated from the following files:
partsbinpalette/partsbiniconview.h
partsbinpalette/partsbiniconview.cpp