Fritzing: SVGPathParser Class Reference
SVGPathParser Class Reference
#include <svgpathparser.h>
Public Member Functions
SVGPathParser ()=default
~SVGPathParser ()=default
constexpr const QString & errorMessage () const noexcept
bool parse (SVGPathLexer *lexer)
bool parse (SVGPathLexer &lexer)
constexpr const QVariant & result () const noexcept
QVector< QVariant > & symStack () noexcept
Private Member Functions
void reallocateStack ()
Private Attributes
QString m_errorMessage
QVariant m_result
QVector< int > m_stateStack
QVector< QVariant > m_symStack
int m_tos = 0
Additional Inherited Members
Public Types inherited from SVGPathGrammar
enum {
EOF_SYMBOL = 0, AE = 11, AITCH = 5, CEE = 7,
COMMA = 12, EKS = 3, EL = 4, EM = 1,
ESS = 8, KYU = 9, NUMBER = 13, TEE = 10,
VEE = 6, WHITESPACE = 14, ZEE = 2, ACCEPT_STATE = 126,
RULE_COUNT = 85, STATE_COUNT = 127, TERMINAL_COUNT = 15, NON_TERMINAL_COUNT = 48,
GOTO_INDEX_OFFSET = 127, GOTO_INFO_OFFSET = 44, GOTO_CHECK_OFFSET = 44
}
Static Public Member Functions inherited from SVGPathGrammar
static int nt_action (int state, int nt)
static int t_action (int state, int token)
Static Public Attributes inherited from SVGPathGrammar
static const int action_check []
static const int action_default []
static const int action_index []
static const int action_info []
static const int goto_default []
static const int lhs []
static const int rhs []
static const int rule_index []
static const int rule_info []
static const char *const spell []
Constructor & Destructor Documentation
SVGPathParser()
SVGPathParser::SVGPathParser () default
~SVGPathParser()
SVGPathParser::~SVGPathParser () default
Member Function Documentation
errorMessage()
constexpr const QString& SVGPathParser::errorMessage () const inline noexcept
References m_errorMessage.
parse() [1/2]
bool SVGPathParser::parse (SVGPathLexer * lexer)
parse() [2/2]
bool SVGPathParser::parse (SVGPathLexer & lexer)
References SVGPathGrammar::ACCEPT_STATE, SVGPathGrammar::action_index, SVGPathLexer::currentCommand(), SVGPathLexer::currentNumber(), SVGPathLexer::lex(), SVGPathGrammar::lhs, m_errorMessage, m_stateStack, m_symStack, m_tos, SVGPathGrammar::nt_action(), reallocateStack(), SVGPathGrammar::rhs, SVGPathGrammar::spell, SVGPathGrammar::t_action(), and SVGPathGrammar::TERMINAL_COUNT.
reallocateStack()
void SVGPathParser::reallocateStack () private
References m_stateStack.
result()
constexpr const QVariant& SVGPathParser::result () const inline noexcept
References m_result.
symStack()
QVector< QVariant > & SVGPathParser::symStack () noexcept
References m_symStack.
Member Data Documentation
m_errorMessage
QString SVGPathParser::m_errorMessage private
m_result
QVariant SVGPathParser::m_result private
m_stateStack
QVector<int> SVGPathParser::m_stateStack private
m_symStack
QVector<QVariant> SVGPathParser::m_symStack private
m_tos
int SVGPathParser::m_tos = 0 private
The documentation for this class was generated from the following files:
svg/svgpathparser.h
svg/svgpathparser.cpp