Fritzing: ChangeSvgCommand Class Reference
ChangeSvgCommand Class Reference
#include <pecommands.h>
Public Member Functions
ChangeSvgCommand (class PEMainWindow *, SketchWidget *, const QString &oldFilename, const QString &newFilename, QUndoCommand *parent)
void redo ()
void undo ()
Public Member Functions inherited from PEBaseCommand
PEBaseCommand (class PEMainWindow *, QUndoCommand *parent)
~PEBaseCommand ()
Public Member Functions inherited from BaseCommand
BaseCommand (BaseCommand::CrossViewType, SketchWidget *, QUndoCommand *parent)
~BaseCommand ()
void addSubCommand (BaseCommand *subCommand)
BaseCommand::CrossViewType crossViewType () const noexcept
virtual QString getDebugString () const
int index () const
const QUndoCommand * parentCommand () const
void redo ()
void setCrossViewType (BaseCommand::CrossViewType)
void setRedoOnly ()
void setSkipFirstRedo ()
void setUndoOnly ()
SketchWidget * sketchWidget () const
const BaseCommand * subCommand (int index) const
int subCommandCount () const
void subRedo ()
void subRedo (int index)
void subUndo ()
void subUndo (int index)
void undo ()
Protected Member Functions
QString getParamString () const
Protected Attributes
QString m_newFilename
QString m_oldFilename
Protected Attributes inherited from PEBaseCommand
class PEMainWindow * m_peMainWindow
Protected Attributes inherited from BaseCommand
QList< BaseCommand * > m_commands
BaseCommand::CrossViewType m_crossViewType
int m_index = 0
QUndoCommand * m_parentCommand = nullptr
bool m_redoOnly = false
SketchWidget * m_sketchWidget = nullptr
bool m_skipFirstRedo = false
bool m_undoOnly = false
Additional Inherited Members
Public Types inherited from BaseCommand
enum CrossViewType { SingleView, CrossView }
Static Public Member Functions inherited from BaseCommand
static void clearProgress ()
static CommandProgress * initProgress ()
static int totalChildCount (const QUndoCommand *)
Static Protected Attributes inherited from BaseCommand
static CommandProgress m_commandProgress
static int nextIndex = 0
Constructor & Destructor Documentation
ChangeSvgCommand()
ChangeSvgCommand::ChangeSvgCommand (class PEMainWindow * peMainWindow, SketchWidget * sketchWidget, const QString & oldFilename, const QString & newFilename, QUndoCommand * parent)
References m_newFilename, m_oldFilename, BaseCommand::m_sketchWidget, and BaseCommand::sketchWidget().
Member Function Documentation
getParamString()
QString ChangeSvgCommand::getParamString () const protected virtual
Reimplemented from PEBaseCommand.
References m_newFilename, m_oldFilename, BaseCommand::m_sketchWidget, and SketchWidget::viewID().
redo()
void ChangeSvgCommand::redo ()
References PEMainWindow::changeSvg(), m_newFilename, PEBaseCommand::m_peMainWindow, and BaseCommand::m_sketchWidget.
undo()
void ChangeSvgCommand::undo ()
References PEMainWindow::changeSvg(), m_oldFilename, PEBaseCommand::m_peMainWindow, and BaseCommand::m_sketchWidget.
Member Data Documentation
m_newFilename
QString ChangeSvgCommand::m_newFilename protected
m_oldFilename
QString ChangeSvgCommand::m_oldFilename protected
The documentation for this class was generated from the following files:
partseditor/pecommands.h
partseditor/pecommands.cpp