Fritzing: MainWindow Class Reference
MainWindow Class Reference
#include <mainwindow.h>
Public Slots
void acceptAlienFiles ()
void changeBoardLayers (int layers, bool doEmit)
void clearGroundFillSeeds ()
void copperFill ()
void ensureClosable ()
void groundFill ()
QList< ModelPart * > loadBundledPart (const QString &fileName, bool addToBin)
void oldSchematicsSlot (const QString &filename, bool &useOldSchematics)
void orderFabHoverEnter ()
void orderFabHoverLeave ()
void removeGroundFill ()
void selectAllObsolete ()
void setGroundFillKeepout ()
void setGroundFillSeeds ()
void setOneGroundFillSeed ()
void showPCBView ()
void showStatusMessage (const QString &)
void showWelcomeView ()
void statusMessage (QString message, int timeout)
void swapBoardImageSlot (SketchWidget *sketchWidget, ItemBase *itemBase, const QString &filename, const QString &moduleID, bool addName)
void swapObsolete ()
virtual void updateExportMenu ()
virtual void updateFileMenu ()
void updateTraceMenu ()
Signals
void alienPartsDismissed ()
void changeActivationSignal (bool activate, QWidget *originator)
void externalProcessSignal (QString &name, QString &path, QStringList &args)
void mainWindowMoved (QWidget *)
Signals inherited from FritzingWindow
void readOnlyChanged (bool isReadOnly)
Public Member Functions
MainWindow (class ReferenceModel *referenceModel, QWidget *parent)
MainWindow (QFile &fileToLoad)
~MainWindow ()
void addDefaultParts ()
void addToSketch (QList< ModelPart * > &)
bool anyUsePart (const QString &moduleID)
void clearFileProgressDialog ()
void copperFill (ViewLayer::ViewLayerID)
void enableCheckUpdates (bool enabled)
void exportSvg (double res, bool selectedItems, bool flatten, const QString &filename)
class FileProgressDialog * fileProgressDialog ()
int fireQuoteDelay ()
const QString & fritzingVersion ()
void getPartsEditorNewAnd (ItemBase *fromItem)
void groundFill (ViewLayer::ViewLayerID)
bool hasAnyAlien ()
bool hasCustomBoardShape ()
void hideTempPartsBin ()
void init (ReferenceModel *referenceModel, bool lockFiles)
bool loadBundledNonAtomicEntity (const QString &filename, Bundler *bundler, bool addToBin, bool dontAsk)
bool loadWhich (const QString &fileName, bool setAsLastOpened, bool addToRecent, bool checkObsolete, const QString &displayName)
void mainLoad (const QString &fileName, const QString &displayName, bool checkObsolete)
QStringList newDesignRulesCheck (bool showOkMessage)
void noBackup ()
void noSchematicConversion ()
void notClosableForAWhile ()
class PCBSketchWidget * pcbView ()
ProgramWindow * programmingWidget ()
QAction * raiseWindowAction ()
QStatusBar * realStatusBar ()
void redrawSketch ()
void removeGroundFill (ViewLayer::ViewLayerID, QUndoCommand *parentCommand)
void restoreDocks ()
bool saveAsAux (const QString &fileName)
void saveAsShareable (const QString &path, bool saveModel)
void saveBundledNonAtomicEntity (QString &filename, const QString &extension, Bundler *bundler, const QList< ModelPart * > &partsToSave, bool askForFilename, const QString &destFolderPath, bool saveModel, bool deleteLeftovers)
void saveDocks ()
QList< ItemBase * > selectAllObsolete (bool displayFeedback)
const QString & selectedModuleID ()
void selectPartsWithModuleID (ModelPart *)
void setCloseSilently (bool)
void setCurrentFile (const QString &fileName, bool addToRecent, bool setAsLastOpened)
void setCurrentView (ViewLayer::ViewID)
void setFileProgressPath (const QString &path)
void setFireQuoteDelay (int)
void setInitialTab (int)
void setReportMissingModules (bool)
void showFileProgressDialog (const QString &path)
QSizeGrip * sizeGrip ()
QList< class SketchWidget * > sketchWidgets ()
void swapLayers (ItemBase *itemBase, int layers, const QString &msg, int delay)
void swapObsolete (bool displayFeedback, QList< ItemBase * > &)
void swapSelectedAux (ItemBase *itemBase, const QString &moduleID, bool useViewLayerPlacement, ViewLayer::ViewLayerPlacement, QMap< QString, QString > &propsMap)
bool updateParts (const QString &moduleID, QUndoCommand *parentCommand)
void updatePartsBin (const QString &moduleID)
bool usesPart (const QString &moduleID)
Public Member Functions inherited from FritzingWindow
FritzingWindow (const QString &untitledFileName, int &untitledFileCount, QString fileExt, QWidget *parent=0, Qt::WindowFlags f=0)
const QString & fileName ()
void setFileName (const QString &)
Public Member Functions inherited from Bundler
virtual ~Bundler ()
virtual bool loadBundledAux (QDir &dir, QList< class ModelPart * > mps)
virtual bool preloadBundledAux (QDir &dir, bool dontAsk)
Static Public Member Functions
static void initNames ()
static MainWindow * newMainWindow (ReferenceModel *referenceModel, const QString &displayPath, bool showProgress, bool lockFiles, int initialTab)
static void setAutosaveEnabled (bool)
static void setAutosavePeriod (int)
Static Public Member Functions inherited from FritzingWindow
static bool alreadyHasExtension (const QString &fileName, const QString &extension=___emptyString___)
Static Public Attributes
static bool AutosaveEnabled = true
static int AutosaveTimeoutMinutes = 10
static QString BackupFolder
static const int DockMinHeight = 30
static const int DockMinWidth = 130
Static Public Attributes inherited from FritzingWindow
static const QString QtFunkyPlaceholder = QLatin1String("[*]")
static QString ReadOnlyPlaceholder
Protected Types
enum { MaxRecentFiles = 10 }
Protected Slots
void about ()
void activateWindowAux ()
void activeLayerBoth ()
void activeLayerBottom ()
void activeLayerTop ()
void actualSize ()
void addBendpoint ()
void addNote ()
void addToMyParts (ModelPart *, const QStringList &)
void alignBottom ()
void alignHorizontalCenter ()
void alignLeft ()
void alignRight ()
void alignToGrid ()
void alignTop ()
void alignVerticalCenter ()
void applyReadOnlyChange (bool isReadOnly)
void autorouterSettings ()
void autosaveNeeded (int index=0)
virtual void backupSketch ()
void binSaved (bool hasAlienParts)
void boardDeletedSlot ()
void bringForward ()
void bringToFront ()
void changeTraceLayer ()
void changeWireColor (bool checked)
void checkLoadedTraces ()
void colorWiresByLength ()
void convertToBendpoint ()
void convertToVia ()
void copy ()
void createNewSketch ()
void createTrace ()
void cursorLocationSlot (double, double, double=0.0, double=0.0)
void cut ()
void deselect ()
void disconnectAll ()
void dockChangeActivation (bool activate, QWidget *originator)
void doDelete ()
void doDeleteMinus ()
void doExport ()
void dropPaste (SketchWidget *)
void dumpAllParts ()
void duplicate ()
void enableDebug ()
void excludeFromAutoroute ()
void exportEtchable ()
void exportNormalizedFlattenedSVG ()
void exportNormalizedSVG ()
bool externalProcess (QString &name, QString &path, QStringList &args)
void fabQuote ()
void filenameIfSlot (QString &filename)
void findPartInSketch ()
void fireQuote ()
void firstTimeHelp ()
void fitInWindow ()
void flattenCurve ()
void flipHorizontal ()
void flipVertical ()
void gridUnits (bool)
void hideAllLayers ()
void hidePartSilkscreen ()
void hundredPercentSize ()
virtual void initZoom ()
void keepMargins ()
void launchExternalProcess ()
void linkToProgramFile (const QString &filename, Platform *platform, bool addLink, bool strong)
void loadedRootSlot (const QString &filename, ModelBase *, QDomElement &views)
void loadedViewsSlot (class ModelBase *, QDomElement &views)
void locationLabelClicked ()
void mainLoad ()
void minimize ()
void moveLock ()
void newAutoroute ()
QStringList newDesignRulesCheck ()
void obsoleteSMDOrientationSlot ()
void openDonate ()
void openExamples ()
void openHelp ()
void openInPartsEditorNew ()
void openNewPartsEditor (class PaletteItem *)
void openPartsReference ()
void openProgramWindow ()
void openRecentOrExampleFile ()
void openRecentOrExampleFile (const QString &filename, const QString &actionText)
void openURL ()
void orderFab ()
void pageSetup ()
void partsEditorHelp ()
void paste ()
void pasteInPlace ()
void print ()
void processError (QProcess::ProcessError processError)
void processFinished (int exitCode, QProcess::ExitStatus exitStatus)
void processReadyRead ()
void processStateChanged (QProcess::ProcessState newState)
void raiseAndActivate ()
void reportBug ()
void restoreDefaultGrid ()
void revert ()
void rotate180 ()
void rotate45ccw ()
void rotate45cw ()
void rotate90ccw ()
void rotate90cw ()
void rotateIncCCW ()
void rotateIncCCWRubberBand ()
void rotateIncCW ()
void rotateIncCWRubberBand ()
void routingStatusLabelMousePress (QMouseEvent *)
void routingStatusLabelMouseRelease (QMouseEvent *)
void routingStatusSlot (class SketchWidget *, const RoutingStatus &)
bool save ()
bool saveAs ()
QStringList saveBundledAux (ModelPart *mp, const QDir &destFolder)
void saveBundledPart (const QString &moduleId=___emptyString___)
void selectAll ()
void selectAllCopperFill ()
void selectAllExcludedTraces ()
void selectAllIncludedTraces ()
void selectAllJumperItems ()
void selectAllTraces ()
void selectAllVias ()
void selectMoveLock ()
void sendBackward ()
void sendToBack ()
void setActiveConnectorItem (class ConnectorItem *)
void setActiveWire (class Wire *)
void setBackgroundColor ()
void setGridSize ()
void setInfoViewOnHover (bool infoViewOnHover)
void setSticky ()
void setViewFromAbove ()
void setViewFromBelow ()
void setViewFromBelowToggle ()
void shareOnline ()
void showAllLayers ()
void showBreadboardView ()
void showGrid ()
void showPartLabels ()
void showPartsBinIconView ()
void showPartsBinListView ()
void showProgramView ()
void showSchematicView ()
void showUnrouted ()
void startSaveInstancesSlot (const QString &fileName, ModelPart *, QXmlStreamWriter &)
void subSwapSlot (SketchWidget *, ItemBase *, const QString &newModuleID, ViewLayer::ViewLayerPlacement, long &newID, QUndoCommand *parentCommand)
void swapSelectedDelay (const QString &family, const QString &prop, QMap< QString, QString > &currPropsMap, ItemBase *)
void swapSelectedMap (const QString &family, const QString &prop, QMap< QString, QString > &currPropsMap, ItemBase *)
void swapSelectedTimeout ()
virtual void tabWidget_currentChanged (int index)
void testConnectors ()
void throwFakeException ()
void tidyWires ()
void tipsAndTricks ()
void toggleActiveLayer ()
void toggleDebuggerOutput (bool toggle)
void toggleInfo (bool toggle)
void togglePartLibrary (bool toggle)
void toggleToolbar (bool toggle)
void toggleUndoHistory (bool toggle)
void undoStackCleanChanged (bool isClean)
virtual void updateEditMenu ()
void updateItemMenu ()
virtual void updateLayerMenu (bool resetLayout=false)
void updateLayerMenuSlot ()
void updatePartMenu ()
void updateRecentFileActions ()
void updateRoutingStatus ()
void updateTransformationActions ()
void updateViewZoom (double newZoom)
void updateWelcomeViewRecentList (bool doEmit=true)
virtual void updateWindowMenu ()
virtual void updateWireMenu ()
void updateZoomOptionsNoMatterWhat (double zoom)
void updateZoomSlider (double zoom)
void visitFritzingDotOrg ()
void zoomIn ()
void zoomOut ()
Protected Slots inherited from FritzingWindow
virtual bool save ()
virtual bool saveAs ()
void undoStackCleanChanged (bool isClean)
Protected Member Functions
int activeLayerIndex ()
virtual bool activeLayerWidgetAlwaysOn ()
void addBottomMargin (FDockWidget *dock)
virtual void addTab (QWidget *widget, const QString &label)
virtual void addTab (QWidget *widget, const QString &iconPath, const QString &label, bool withIcon)
void addTopMargin (FDockWidget *dock)
bool alreadyOpen (const QString &fileName)
void backupExistingFileIfExists (const QString &destFilePath)
virtual QMenu * breadboardItemMenu ()
virtual QMenu * breadboardWireMenu ()
void checkSwapObsolete (QList< ItemBase * > &, bool includeUpdateLaterMessage)
void closeEvent (QCloseEvent *event)
void closeIfEmptySketch (MainWindow *mw)
void connectPair (SketchWidget *signaller, SketchWidget *slotter)
virtual void connectPairs ()
void connectStartSave (bool connect)
QString constructFileName (const QString &differentiator, const QString &extension)
bool copySvg (const QString &path, QFileInfoList &svgEntryInfoList)
ModelPart * copyToPartsFolder (const QFileInfo &file, bool addToAlien, const QString &prefixFolder, const QString &destFolder)
QString copyToSvgFolder (const QFileInfo &file, bool addToAlien, const QString &prefixFolder, const QString &destFolder)
virtual void createActions ()
void createActiveLayerActions ()
QWidget * createActiveLayerButton (SketchAreaWidget *parent)
virtual void createAddToBinSubmenu (QMenu *parentMenu)
virtual void createAlignSubmenu (QMenu *parentMenu)
SketchToolButton * createAutorouteButton (SketchAreaWidget *parent)
void createDockWindows ()
virtual void createEditMenu ()
void createEditMenuActions ()
void createExportActions ()
SketchToolButton * createExportEtchableButton (SketchAreaWidget *parent)
virtual void createFileMenu ()
virtual void createFileMenuActions ()
SketchToolButton * createFlipButton (SketchAreaWidget *parent)
QWidget * createGridSizeForm (GridSizeThing *)
virtual void createHelpMenu ()
void createHelpMenuActions ()
virtual void createMenus ()
SketchToolButton * createNoteButton (SketchAreaWidget *parent)
void createOpenExampleMenu ()
void createOpenRecentMenu ()
void createOrderFabAct ()
SketchToolButton * createOrderFabButton (SketchAreaWidget *parent)
virtual void createPartMenu ()
void createPartMenuActions ()
void createRaiseWindowActions ()
class SketchToolButton * createRotateButton (SketchAreaWidget *parent)
virtual void createRotateSubmenu (QMenu *parentMenu)
class ExpandingLabel * createRoutingStatusLabel (SketchAreaWidget *)
SketchToolButton * createShareButton (SketchAreaWidget *parent)
void createStatusBar ()
virtual QWidget * createTabWidget ()
QWidget * createToolbarSpacer (SketchAreaWidget *parent)
void createTraceMenuActions ()
virtual void createTraceMenus ()
QWidget * createViewFromButton (SketchAreaWidget *parent)
virtual void createViewMenu ()
virtual void createViewMenuActions (bool showWelcome)
virtual void createWindowMenu ()
void createWindowMenuActions ()
void createZoomOptions (SketchAreaWidget *parent)
virtual void createZOrderSubmenu (QMenu *parentMenu)
SketchAreaWidget * currentSketchArea ()
virtual int currentTabIndex ()
virtual QWidget * currentTabWidget ()
const QString defaultSaveFolder ()
class FDockWidget * dockIt (FDockWidget *dock, int dockMinHeight, int dockDefaultHeight, Qt::DockWidgetArea area=Qt::RightDockWidgetArea)
void dockMarginAux (FDockWidget *dock, const QString &name, const QString &style)
void dontKeepMargins ()
void dragEnterEvent (QDragEnterEvent *event)
void dropEvent (QDropEvent *event)
void enableAddBendpointAct (QGraphicsItem *)
bool event (QEvent *)
bool eventFilter (QObject *obj, QEvent *event)
void exportAux (QString fileName, QImage::Format format, int quality, bool removeBackground)
void exportBOM ()
void exportEtchable (bool wantPDF, bool wantSVG)
void exportNetlist ()
class FileProgressDialog * exportProgress ()
void exportSpiceNetlist ()
void exportSvg (double res, bool selectedItems, bool flatten)
void exportSvgWatermark (QString &svg, double res)
void exportToEagle ()
void exportToGerber ()
const QString fileExtension ()
ModelPart * findReplacedby (ModelPart *originalModelPart)
const QString fritzingTitle ()
QString genIcon (SketchWidget *, LayerList &partViewLayerIDs, LayerList &wireViewLayerIDs)
QString getBoardSvg (ItemBase *board, int res, LayerList &)
QString getBomProps (ItemBase *)
virtual QList< QWidget * > getButtonsForView (ViewLayer::ViewID viewId)
QStringList getExtensions ()
QString getExtensionString ()
virtual QString getStyleSheetSuffix ()
void groundFillAux (bool fillGroundTraces, ViewLayer::ViewLayerID viewLayerID)
void groundFillAux2 (bool fillGroundTraces)
bool hasLinkedProgramFiles (const QString &filename, QStringList &linkedProgramFiles)
void hideShowProgramMenu ()
void hideShowTraceMenu ()
QHash< QString, struct SketchDescriptor * > indexAvailableElements (QDomElement &domElem, const QString &srcPrefix, QStringList &actionsTracker, const QString &localeName)
virtual void initDock ()
virtual void initLockedFiles (bool lockFiles)
virtual void initMenus ()
virtual void initProgrammingWidget ()
void initSketchWidget (SketchWidget *)
virtual void initSketchWidgets (bool withIcons)
void initStyleSheet ()
virtual void initWelcomeView ()
bool isGroundFill (ItemBase *itemBase)
void loadBundledSketch (const QString &fileName, bool addToRecent, bool setAsLastOpened, bool checkObsolete)
void mainLoadAux (const QString &fileName)
class FDockWidget * makeDock (const QString &title, QWidget *widget, int dockMinHeight, int dockDefaultHeight, Qt::DockWidgetArea area=Qt::RightDockWidgetArea, DockFactory dockFactory=NULL)
void massageOutput (QString &svg, bool doMask, bool doSilk, bool doPaste, QString &maskTop, QString &maskBottom, const QString &fileName, ItemBase *board, int dpi, const LayerList &)
QString mergeBoardSvg (QString &svg, ItemBase *board, int res, bool flip, LayerList &)
virtual void moreInitDock ()
void moveEvent (QMoveEvent *event)
QList< ModelPart * > moveToPartsFolder (QDir &unzipDir, MainWindow *mw, bool addToBin, bool addToAlien, const QString &prefixFolder, const QString &destFolder, bool importingSinglePart)
FDockWidget * newBottomWidget ()
FDockWidget * newTopWidget ()
void notYetImplemented (QString action)
QMessageBox::StandardButton oldSchematicMessage (const QString &filename)
void pasteAux (bool pasteInPlace)
virtual QMenu * pcbItemMenu ()
virtual QMenu * pcbWireMenu ()
virtual void populateExportMenu ()
void populateMenuFromFolderContent (QMenu *parentMenu, const QString &path)
void populateMenuFromXMLFile (QMenu *parentMenu, QStringList &actionsTracker, const QString &folderPath, const QString &indexFileName)
void populateMenuWithIndex (const QHash< QString, struct SketchDescriptor * > &, QMenu *parentMenu, QDomElement &domElem, const QString &localeName)
void printAux (QPrinter &printer, bool removeBackground, bool paginate)
void recoverBackupedFiles ()
void removeMargin (FDockWidget *dock)
void resetTempFolder ()
void resizeEvent (QResizeEvent *event)
class ConnectorItem * retrieveConnectorItem ()
class Wire * retrieveWire ()
MainWindow * revertAux ()
void routingStatusLabelMouse (QMouseEvent *, bool show)
void saveAsAuxAux (const QString &fileName)
void saveLastTabList ()
virtual QMenu * schematicItemMenu ()
virtual QMenu * schematicWireMenu ()
void setActionsIcons (int index, QList< QAction * > &)
virtual void setCurrentTabIndex (int)
virtual void setInitialView ()
void svgMissingLayer (const QString &layername, const QString &path)
long swapSelectedAuxAux (ItemBase *itemBase, const QString &moduleID, ViewLayer::ViewLayerPlacement viewLayerPlacement, QMap< QString, QString > &propsMap, QUndoCommand *parentCommand)
bool swapSpecial (const QString &prop, QMap< QString, QString > &currPropsMap)
bool undoStackIsEmpty ()
int & untitledFileCount ()
const QString untitledFileName ()
void updateActiveLayerButtons ()
void updatePCBTraceMenu (QGraphicsItem *, TraceMenuThing &)
virtual void updateRaiseWindowAction ()
QMenu * viewItemMenuAux (QMenu *menu)
bool whatToDoWithAlienFiles ()
Protected Member Functions inherited from FritzingWindow
virtual bool anyModified ()
virtual bool beforeClosing (bool showCancel, bool &discard)
QMessageBox::StandardButton beforeClosingMessage (const QString &filename, bool showCancel)
void createCloseAction ()
bool save (const QString &filename, bool readOnly)
bool saveAs (const QString &filename, bool readOnly)
virtual void setBeforeClosingText (const QString &filename, QMessageBox &messageBox)
void setReadOnly (bool readOnly)
virtual void setTitle ()
Static Protected Member Functions
static void removeActionsStartingAt (QMenu *menu, int start=0)
static void setAutosave (int, bool)
Protected Attributes
QAction * m_100PercentSizeAct = nullptr
QAction * m_aboutAct = nullptr
QAction * m_aboutQtAct = nullptr
QPointer< ConnectorItem > m_activeConnectorItem
QAction * m_activeLayerBothAct = nullptr
QAction * m_activeLayerBottomAct = nullptr
QStackedWidget * m_activeLayerButtonWidget = nullptr
QAction * m_activeLayerTopAct = nullptr
QPointer< Wire > m_activeWire
QAction * m_actualSizeAct = nullptr
QAction * m_addBendpointAct = nullptr
bool m_addedToTemp = false
QAction * m_addNoteAct = nullptr
QMenu * m_addToBinMenu = nullptr
QStringList m_alienFiles
QString m_alienPartsMsg
QAction * m_alignBottomAct = nullptr
QAction * m_alignHorizontalCenterAct = nullptr
QAction * m_alignLeftAct = nullptr
QMenu * m_alignMenu = nullptr
QAction * m_alignRightAct = nullptr
QAction * m_alignToGridAct = nullptr
QAction * m_alignTopAct = nullptr
QAction * m_alignVerticalCenterAct = nullptr
QAction * m_autorouterSettingsAct = nullptr
bool m_autosaveNeeded = false
QTimer m_autosaveTimer
bool m_backingUp = false
QString m_backupFileNameAndPath
QPointer< class BinManager > m_binManager
FDockWidget * m_bottomDock = nullptr
QPointer< class BreadboardSketchWidget > m_breadboardGraphicsView
QMenu * m_breadboardTraceMenu = nullptr
QPointer< SketchAreaWidget > m_breadboardWidget
QMenu * m_breadboardWireColorMenu = nullptr
QAction * m_bringForwardAct = nullptr
class WireAction * m_bringForwardWireAct = nullptr
QAction * m_bringToFrontAct = nullptr
class WireAction * m_bringToFrontWireAct = nullptr
QString m_bundledSketchName
QAction * m_changeTraceLayerAct = nullptr
class WireAction * m_changeTraceLayerWireAct = nullptr
QAction * m_checkForUpdatesAct = nullptr
QAction * m_checkLoadedTracesAct = nullptr
QAction * m_clearGroundFillSeedsAct = nullptr
bool m_closeSilently = false
bool m_closing = false
QAction * m_colorWiresByLengthAct = nullptr
bool m_comboboxChanged = false
bool m_convertedSchematic = false
QAction * m_convertToBendpointAct = nullptr
QAction * m_convertToBendpointSeparator = nullptr
QAction * m_convertToViaAct = nullptr
QAction * m_copperFillAct = nullptr
QAction * m_copyAct = nullptr
QAction * m_createJumperAct = nullptr
class WireAction * m_createTraceWireAct = nullptr
class WireAction * m_createWireWireAct = nullptr
QPointer< SketchWidget > m_currentGraphicsView
QPointer< SketchAreaWidget > m_currentWidget
QAction * m_cutAct = nullptr
QAction * m_deleteAct = nullptr
QAction * m_deleteMinusAct = nullptr
class WireAction * m_deleteWireAct = nullptr
class WireAction * m_deleteWireMinusAct = nullptr
QAction * m_deselectAct = nullptr
QAction * m_disconnectAllAct = nullptr
QList< FDockWidget * > m_docks
bool m_dontClose = false
bool m_dontKeepMargins = false
QIcon m_dotIcon
QAction * m_dumpAllPartsAction = nullptr
QAction * m_duplicateAct = nullptr
QMenu * m_editMenu = nullptr
QIcon m_emptyIcon
QAction * m_enableDebugAct = nullptr
QAction * m_examplesAct = nullptr
QAction * m_exceptionAct = nullptr
QAction * m_excludeFromAutorouteAct = nullptr
class WireAction * m_excludeFromAutorouteWireAct = nullptr
QAction * m_exportBomAct = nullptr
QAction * m_exportEagleAct = nullptr
QAction * m_exportEtchablePdfAct = nullptr
QAction * m_exportEtchableSvgAct = nullptr
QAction * m_exportGerberAct = nullptr
QAction * m_exportJpgAct = nullptr
QMenu * m_exportMenu = nullptr
QAction * m_exportNetlistAct = nullptr
QAction * m_exportNormalizedFlattenedSvgAction = nullptr
QAction * m_exportNormalizedSvgAction = nullptr
QAction * m_exportPdfAct = nullptr
QAction * m_exportPngAct = nullptr
QAction * m_exportSpiceNetlistAct = nullptr
QAction * m_exportSvgAct = nullptr
QByteArray m_externalProcessOutput
QAction * m_fabQuoteAct = nullptr
QMenu * m_fileMenu = nullptr
QPointer< class FileProgressDialog > m_fileProgressDialog
QStringList m_filesReplacedByAlienOnes
QAction * m_findPartInSketchAct = nullptr
int m_fireQuoteDelay = 0
QTimer m_fireQuoteTimer
bool m_firstOpen = false
QAction * m_firstTimeHelpAct = nullptr
QAction * m_fitInWindowAct = nullptr
QAction * m_flattenCurveAct = nullptr
QList< SketchToolButton * > m_flipButtons
QAction * m_flipHorizontalAct = nullptr
QAction * m_flipVerticalAct = nullptr
QMenu * m_fritzingMenu = nullptr
QHash< QString, struct LockedFile * > m_fzzFiles
QString m_fzzFolder
QAction * m_groundFillAct = nullptr
QMenu * m_helpMenu = nullptr
QAction * m_hideAllLayersAct = nullptr
QAction * m_hidePartSilkscreenAct = nullptr
QPointer< class HtmlInfoView > m_infoView
QAction * m_infoViewOnHoverAction = nullptr
int m_initialTab = 0
QAction * m_launchExternalProcessAct = nullptr
QPointer< class LayerPalette > m_layerPalette
QList< LinkedFile * > m_linkedProgramFiles
QPointer< QLabel > m_locationLabel
QString m_locationLabelUnits
QAction * m_minimizeAct = nullptr
QAction * m_moveLockAct = nullptr
QAction * m_newAct = nullptr
QAction * m_newAutorouteAct = nullptr
QAction * m_newDesignRulesCheckAct = nullptr
bool m_noSchematicConversion = false
int m_numFixedActionsInViewMenu = 0
bool m_obsoleteSMDOrientation = false
QString m_oldBottomDockStyle
QString m_oldTopDockStyle
QAction * m_openAct = nullptr
QAction * m_openDonateAct = nullptr
QStringList m_openExampleActions
QMenu * m_openExampleMenu = nullptr
QAction * m_openHelpAct = nullptr
QAction * m_openInPartsEditorNewAct = nullptr
QAction * m_openProgramWindowAct = nullptr
QAction * m_openRecentFileActs [MaxRecentFiles] = { nullptr }
QMenu * m_openRecentFileMenu = nullptr
QAction * m_orderFabAct = nullptr
QWidget * m_orderFabButton = nullptr
bool m_orderFabEnabled = false
QAction * m_pageSetupAct = nullptr
QMenu * m_partMenu = nullptr
QAction * m_partsEditorHelpAct = nullptr
QAction * m_partsRefAct = nullptr
QAction * m_pasteAct = nullptr
QAction * m_pasteInPlaceAct = nullptr
QPointer< class PCBSketchWidget > m_pcbGraphicsView
QMenu * m_pcbTraceMenu = nullptr
QPointer< SketchAreaWidget > m_pcbWidget
QAction * m_preferencesAct = nullptr
QAction * m_printAct = nullptr
QPointer< class ProgramWindow > m_programView
QPointer< class ProgramWindow > m_programWindow
QAction * m_quitAct = nullptr
QAction * m_raiseWindowAct = nullptr
QAction * m_redoAct = nullptr
QPointer< ReferenceModel > m_referenceModel
QAction * m_regeneratePartsDatabaseAct = nullptr
QAction * m_removeGroundFillAct = nullptr
QAction * m_reportBugAct = nullptr
bool m_restarting = false
QAction * m_revertAct = nullptr
QPointer< QDialog > m_rolloverQuoteDialog
QAction * m_rotate180Act = nullptr
QAction * m_rotate45ccwAct = nullptr
QAction * m_rotate45cwAct = nullptr
QAction * m_rotate90ccwAct = nullptr
QAction * m_rotate90cwAct = nullptr
QList< SketchToolButton * > m_rotateButtons
QMenu * m_rotateMenu = nullptr
RoutingStatus m_routingStatus
QAction * m_saveAct = nullptr
QAction * m_saveAsAct = nullptr
QAction * m_saveBundledPart = nullptr
QPointer< class SchematicSketchWidget > m_schematicGraphicsView
QMenu * m_schematicTraceMenu = nullptr
QPointer< SketchAreaWidget > m_schematicWidget
QMenu * m_schematicWireColorMenu = nullptr
QAction * m_selectAllAct = nullptr
QAction * m_selectAllCopperFillAct = nullptr
QAction * m_selectAllExcludedTracesAct = nullptr
QAction * m_selectAllIncludedTracesAct = nullptr
QAction * m_selectAllJumperItemsAct = nullptr
QAction * m_selectAllObsoleteAct = nullptr
QAction * m_selectAllTracesAct = nullptr
QAction * m_selectAllViasAct = nullptr
QAction * m_selectAllWiresAct = nullptr
QAction * m_selectMoveLockAct = nullptr
QAction * m_sendBackwardAct = nullptr
class WireAction * m_sendBackwardWireAct = nullptr
QAction * m_sendToBackAct = nullptr
class WireAction * m_sendToBackWireAct = nullptr
QAction * m_setBackgroundColorAct = nullptr
QAction * m_setGridSizeAct = nullptr
QAction * m_setGroundFillKeepoutAct = nullptr
QAction * m_setGroundFillSeedsAct = nullptr
class ConnectorItemAction * m_setOneGroundFillSeedAct = nullptr
QString m_settingsPrefix
QTimer m_setUpDockManagerTimer
QAction * m_shareOnlineAct = nullptr
QAction * m_showAllLayersAct = nullptr
QAction * m_showBreadboardAct = nullptr
QAction * m_showGridAct = nullptr
QAction * m_showPartLabelAct = nullptr
QAction * m_showPartsBinIconViewAct = nullptr
QAction * m_showPartsBinListViewAct = nullptr
QAction * m_showPCBAct = nullptr
QAction * m_showProgramAct = nullptr
QAction * m_showSchematicAct = nullptr
QAction * m_showUnroutedAct = nullptr
QAction * m_showWelcomeAct = nullptr
QPointer< class FSizeGrip > m_sizeGrip
QPointer< class SketchModel > m_sketchModel
QAction * m_stickyAct = nullptr
QAction * m_swapObsoleteAct = nullptr
SwapTimer m_swapTimer
QPointer< QWidget > m_tabWidget
QAction * m_testConnectorsAction = nullptr
QAction * m_tidyWiresAct = nullptr
QAction * m_tipsAndTricksAct = nullptr
QAction * m_toggleDebuggerOutputAct = nullptr
QAction * m_toggleInfoAct = nullptr
QAction * m_togglePartLibraryAct = nullptr
QAction * m_toggleUndoHistoryAct = nullptr
QPointer< QToolBar > m_toolbar
FDockWidget * m_topDock = nullptr
QAction * m_undoAct = nullptr
QUndoGroup * m_undoGroup = nullptr
QUndoView * m_undoView = nullptr
QAction * m_updateRoutingStatusAct = nullptr
bool m_useOldSchematic = false
QAction * m_viewFromAboveAct = nullptr
QAction * m_viewFromBelowAct = nullptr
QAction * m_viewFromBelowToggleAct = nullptr
QStackedWidget * m_viewFromButtonWidget = nullptr
QMenu * m_viewMenu = nullptr
QAction * m_visitFritzingDotOrgAct = nullptr
class WelcomeView * m_welcomeView = nullptr
QPointer< SketchAreaWidget > m_welcomeWidget
QMenu * m_windowMenu = nullptr
QAction * m_windowMenuSeparator = nullptr
QAction * m_zoomInAct = nullptr
QAction * m_zoomInShortcut = nullptr
QAction * m_zoomOutAct = nullptr
QPointer< class ZoomSlider > m_zoomSlider
QMenu * m_zOrderMenu = nullptr
QMenu * m_zOrderWireMenu = nullptr
Protected Attributes inherited from FritzingWindow
QAction * m_closeAct = nullptr
QString m_fwFilename
bool m_readOnly = false
QStatusBar * m_statusBar = nullptr
QDir m_tempDir
class WaitPushUndoStack * m_undoStack = nullptr
Static Protected Attributes
static int CascadeFactorX = 21
static int CascadeFactorY = 19
static QRegExp GuidMatcher = QRegExp("[A-Fa-f0-9]{32}")
static int UntitledSketchIndex = 1
static const QString UntitledSketchName = "Untitled Sketch"
Static Protected Attributes inherited from FritzingWindow
static QStringList OtherKnownExtensions
Properties
int fireQuoteDelay
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
MaxRecentFiles
Constructor & Destructor Documentation
MainWindow() [1/2]
MainWindow::MainWindow (class ReferenceModel * referenceModel, QWidget * parent)
References autosaveNeeded(), AutosaveTimeoutMinutes, BackupFolder, backupSketch(), changeActivationSignal(), externalProcessSignal(), fireQuote(), FritzingSketchExtension(), TextUtils::getRandText(), locationLabelClicked(), m_activeConnectorItem, m_activeLayerButtonWidget, m_activeWire, m_addedToTemp, m_autosaveNeeded, m_autosaveTimer, m_backingUp, m_backupFileNameAndPath, m_bottomDock, m_breadboardTraceMenu, m_breadboardWireColorMenu, m_checkForUpdatesAct, m_closeSilently, m_closing, m_comboboxChanged, m_convertedSchematic, m_currentGraphicsView, m_currentWidget, m_dontClose, m_dontKeepMargins, m_dotIcon, m_editMenu, m_emptyIcon, m_fileMenu, m_fileProgressDialog, m_fireQuoteTimer, m_firstOpen, m_hideAllLayersAct, m_infoView, m_initialTab, m_locationLabel, m_locationLabelUnits, m_noSchematicConversion, m_orderFabAct, m_orderFabEnabled, m_partMenu, m_pcbTraceMenu, m_programView, m_programWindow, m_raiseWindowAct, m_referenceModel, m_rolloverQuoteDialog, m_rotate90cwAct, m_schematicTraceMenu, m_schematicWireColorMenu, m_settingsPrefix, m_showAllLayersAct, m_showBreadboardAct, m_showPartsBinIconViewAct, m_showPCBAct, m_showProgramAct, m_showSchematicAct, m_showWelcomeAct, m_sizeGrip, m_sketchModel, FritzingWindow::m_statusBar, m_swapTimer, m_topDock, FritzingWindow::m_undoStack, m_useOldSchematic, m_viewFromButtonWidget, m_viewMenu, m_welcomeView, m_windowMenu, m_windowMenuSeparator, m_zoomSlider, MainWindowDefaultHeight, MainWindowDefaultWidth, ZoomableGraphicsView::MaxScaleValue, rotateIncCCW(), rotateIncCCWRubberBand(), rotateIncCW(), rotateIncCWRubberBand(), swapSelectedTimeout(), toggleActiveLayer(), undoStackCleanChanged(), and updateViewZoom().
MainWindow() [2/2]
MainWindow::MainWindow (QFile & fileToLoad)
~MainWindow()
MainWindow::~MainWindow ()
References dontKeepMargins(), m_backupFileNameAndPath, m_fzzFiles, m_fzzFolder, m_linkedProgramFiles, m_setUpDockManagerTimer, m_sketchModel, LockManager::releaseLockedFiles(), and FolderUtils::rmdir().
Member Function Documentation
about
void MainWindow::about () protected slot
References AboutBox::showAbout().
acceptAlienFiles
void MainWindow::acceptAlienFiles () slot
References m_alienFiles.
activateWindowAux
void MainWindow::activateWindowAux () protected slot
activeLayerBoth
void MainWindow::activeLayerBoth () protected slot
References ViewLayer::Copper0, ViewLayer::Copper1, m_currentGraphicsView, SketchWidget::setLayerActive(), AutoCloseMessageBox::showMessage(), ViewLayer::Silkscreen0, ViewLayer::Silkscreen1, and updateActiveLayerButtons().
activeLayerBottom
void MainWindow::activeLayerBottom () protected slot
References ViewLayer::Copper0, ViewLayer::Copper1, m_currentGraphicsView, SketchWidget::setLayerActive(), AutoCloseMessageBox::showMessage(), ViewLayer::Silkscreen0, ViewLayer::Silkscreen1, and updateActiveLayerButtons().
activeLayerIndex()
int MainWindow::activeLayerIndex () protected
References activeLayerWidgetAlwaysOn(), ViewLayer::Copper0, ViewLayer::Copper1, and m_currentGraphicsView.
activeLayerTop
void MainWindow::activeLayerTop () protected slot
References ViewLayer::Copper0, ViewLayer::Copper1, m_currentGraphicsView, SketchWidget::setLayerActive(), AutoCloseMessageBox::showMessage(), ViewLayer::Silkscreen0, ViewLayer::Silkscreen1, and updateActiveLayerButtons().
activeLayerWidgetAlwaysOn()
bool MainWindow::activeLayerWidgetAlwaysOn () protected virtual
Reimplemented in PEMainWindow.
actualSize
void MainWindow::actualSize () protected slot
References DebugDialog::debug(), m_currentGraphicsView, m_zoomSlider, and GraphicsUtils::SVGDPI.
addBendpoint
void MainWindow::addBendpoint () protected slot
References BendpointAction::lastHoverEnterConnectorItem(), BendpointAction::lastHoverEnterItem(), BendpointAction::lastLocation(), m_addBendpointAct, and m_currentGraphicsView.
addBottomMargin()
void MainWindow::addBottomMargin (FDockWidget * dock) protected
References dockMarginAux().
addDefaultParts()
void MainWindow::addDefaultParts ()
References m_breadboardGraphicsView, m_pcbGraphicsView, and m_schematicGraphicsView.
addNote
void MainWindow::addNote () protected slot
References ItemBase::getNextID(), Note::initialMinHeight, Note::initialMinWidth, m_currentGraphicsView, FritzingWindow::m_undoStack, ModuleIDNames::NoteModuleIDName, WaitPushUndoStack::push(), ViewGeometry::setLoc(), ViewGeometry::setRect(), and BaseCommand::SingleView.
addTab() [1/2]
void MainWindow::addTab (QWidget * widget, const QString & label) protected virtual
Reimplemented in PEMainWindow.
References m_tabWidget.
addTab() [2/2]
void MainWindow::addTab (QWidget * widget, const QString & iconPath, const QString & label, bool withIcon) protected virtual
References addTab(), and m_tabWidget.
addToMyParts
void MainWindow::addToMyParts (ModelPart * modelPart, const QStringList & peAlienFiles) protected slot
References m_alienFiles, m_alienPartsMsg, and m_binManager.
addTopMargin()
void MainWindow::addTopMargin (FDockWidget * dock) protected
References dockMarginAux().
addToSketch()
void MainWindow::addToSketch (QList< ModelPart * > & modelParts)
References m_currentGraphicsView.
alienPartsDismissed
void MainWindow::alienPartsDismissed () signal
alignBottom
void MainWindow::alignBottom () protected slot
References m_currentGraphicsView.
alignHorizontalCenter
void MainWindow::alignHorizontalCenter () protected slot
References m_currentGraphicsView.
alignLeft
void MainWindow::alignLeft () protected slot
References m_currentGraphicsView.
alignRight
void MainWindow::alignRight () protected slot
References m_currentGraphicsView.
alignToGrid
void MainWindow::alignToGrid () protected slot
References m_alignToGridAct, and m_currentGraphicsView.
alignTop
void MainWindow::alignTop () protected slot
References m_currentGraphicsView.
alignVerticalCenter
void MainWindow::alignVerticalCenter () protected slot
References m_currentGraphicsView.
alreadyOpen()
bool MainWindow::alreadyOpen (const QString & fileName) protected
References FritzingWindow::fileName().
anyUsePart()
bool MainWindow::anyUsePart (const QString & moduleID)
References usesPart().
applyReadOnlyChange
void MainWindow::applyReadOnlyChange (bool isReadOnly) protected slot
autorouterSettings
void MainWindow::autorouterSettings () protected slot
References m_currentGraphicsView, and m_pcbGraphicsView.
autosaveNeeded
void MainWindow::autosaveNeeded (int index = 0) protected slot
This function is used to trigger an autosave at the next autosave timer event. It is connected to the QUndoStack::indexChanged(int) signal so that any change to the undo stack triggers autosaves. This function can be called independent of this signal and still work properly.
References m_autosaveNeeded.
backupExistingFileIfExists()
void MainWindow::backupExistingFileIfExists (const QString & destFilePath) protected
References FolderUtils::createFolderAndCdIntoIt(), DebugDialog::debug(), TextUtils::getRandText(), m_filesReplacedByAlienOnes, FritzingWindow::m_tempDir, and FolderUtils::slamCopy().
backupSketch
void MainWindow::backupSketch () protected virtual slot
A slot for saving a copy of the current sketch to a temp location. This should be called every X minutes as well as just before certain events, such as saves, part imports, file export/printing. This relies on the m_autosaveNeeded variable and the undoStack being dirty for an autosave to be attempted.
References connectStartSave(), DebugDialog::debug(), ProcessEventBlocker::isProcessing(), m_autosaveNeeded, m_backingUp, m_backupFileNameAndPath, FritzingWindow::m_fwFilename, m_sketchModel, FritzingWindow::m_undoStack, and ProcessEventBlocker::processEvents().
binSaved
void MainWindow::binSaved (bool hasAlienParts) protected slot
References m_alienFiles, and resetTempFolder().
boardDeletedSlot
void MainWindow::boardDeletedSlot () protected slot
References activeLayerBottom().
breadboardItemMenu()
QMenu * MainWindow::breadboardItemMenu () protected virtual
Reimplemented in PEMainWindow.
References createRotateSubmenu(), and viewItemMenuAux().
breadboardWireMenu()
QMenu * MainWindow::breadboardWireMenu () protected virtual
Reimplemented in PEMainWindow.
References changeWireColor(), Wire::colorNames, Wire::colorTrans, createZOrderSubmenu(), m_addBendpointAct, m_breadboardWireColorMenu, m_createWireWireAct, m_deleteWireAct, m_deleteWireMinusAct, m_flattenCurveAct, m_infoViewOnHoverAction, and updateWireMenu().
bringForward
void MainWindow::bringForward () protected slot
References m_currentGraphicsView.
bringToFront
void MainWindow::bringToFront () protected slot
References m_currentGraphicsView.
changeActivationSignal
void MainWindow::changeActivationSignal (bool activate, QWidget * originator) signal
changeBoardLayers
void MainWindow::changeBoardLayers (int layers, bool doEmit) slot
References layers(), m_currentGraphicsView, and updateActiveLayerButtons().
changeTraceLayer
void MainWindow::changeTraceLayer () protected slot
References m_currentGraphicsView, m_pcbGraphicsView, and retrieveWire().
changeWireColor
void MainWindow::changeWireColor (bool checked) protected slot
References m_currentGraphicsView.
checkLoadedTraces
void MainWindow::checkLoadedTraces () protected slot
References m_pcbGraphicsView.
checkSwapObsolete()
void MainWindow::checkSwapObsolete (QList< ItemBase * > & items, bool includeUpdateLaterMessage) protected
References FMessageBox::question(), and swapObsolete().
clearFileProgressDialog()
void MainWindow::clearFileProgressDialog ()
References m_fileProgressDialog.
clearGroundFillSeeds
void MainWindow::clearGroundFillSeeds () slot
References m_pcbGraphicsView.
closeEvent()
void MainWindow::closeEvent (QCloseEvent * event) protected
References FritzingWindow::beforeClosing(), DebugDialog::closeDebug(), event(), m_binManager, m_closeSilently, m_closing, m_dontClose, m_programWindow, m_settingsPrefix, saveLastTabList(), and whatToDoWithAlienFiles().
closeIfEmptySketch()
void MainWindow::closeIfEmptySketch (MainWindow * mw) protected
References CascadeFactorX, CascadeFactorY, FolderUtils::isEmptyFileName(), FritzingWindow::m_fwFilename, undoStackIsEmpty(), and untitledFileName().
colorWiresByLength
void MainWindow::colorWiresByLength () protected slot
References m_breadboardGraphicsView, and m_colorWiresByLengthAct.
connectPair()
void MainWindow::connectPair (SketchWidget * signaller, SketchWidget * slotter) protected
References changeBoardLayers(), and DebugDialog::debug().
connectPairs()
void MainWindow::connectPairs () protected virtual
Reimplemented in PEMainWindow.
References boardDeletedSlot(), changeBoardLayers(), connectPair(), copperFill(), cursorLocationSlot(), DebugDialog::debug(), dropPaste(), filenameIfSlot(), groundFill(), m_breadboardGraphicsView, m_pcbGraphicsView, m_schematicGraphicsView, routingStatusSlot(), setActiveConnectorItem(), setActiveWire(), subSwapSlot(), swapBoardImageSlot(), swapSelectedDelay(), and updateLayerMenuSlot().
connectStartSave()
void MainWindow::connectStartSave (bool connect) protected
References m_sketchModel, and startSaveInstancesSlot().
constructFileName()
QString MainWindow::constructFileName (const QString & differentiator, const QString & extension) protected
References m_currentGraphicsView, and FritzingWindow::m_fwFilename.
convertToBendpoint
void MainWindow::convertToBendpoint () protected slot
References m_pcbGraphicsView.
convertToVia
void MainWindow::convertToVia () protected slot
References BendpointAction::lastHoverEnterConnectorItem(), m_convertToViaAct, and m_pcbGraphicsView.
copperFill() [1/2]
void MainWindow::copperFill (ViewLayer::ViewLayerID viewLayerID)
References groundFillAux().
copperFill [2/2]
void MainWindow::copperFill () slot
References groundFillAux2().
copy
void MainWindow::copy () protected slot
References m_currentGraphicsView.
copySvg()
bool MainWindow::copySvg (const QString & path, QFileInfoList & svgEntryInfoList) protected
References copyToSvgFolder(), DebugDialog::debug(), PartFactory::folderPath(), GuidMatcher, and FolderUtils::slamCopy().
copyToPartsFolder()
ModelPart * MainWindow::copyToPartsFolder (const QFileInfo & file, bool addToAlien, const QString & prefixFolder, const QString & destFolder) protected
References alienPartsDismissed(), backupExistingFileIfExists(), m_alienFiles, m_alienPartsMsg, m_referenceModel, recoverBackupedFiles(), ModelPart::setAlien(), FolderUtils::slamCopy(), and ZIP_PART.
copyToSvgFolder()
QString MainWindow::copyToSvgFolder (const QFileInfo & file, bool addToAlien, const QString & prefixFolder, const QString & destFolder) protected
References backupExistingFileIfExists(), FritzingWindow::fileName(), m_alienFiles, FolderUtils::slamCopy(), and ZIP_SVG.
createActions()
void MainWindow::createActions () protected virtual
Reimplemented in PEMainWindow.
References createEditMenuActions(), createFileMenuActions(), createHelpMenuActions(), createPartMenuActions(), createRaiseWindowActions(), createTraceMenuActions(), createViewMenuActions(), and createWindowMenuActions().
createActiveLayerActions()
void MainWindow::createActiveLayerActions () protected
References activeLayerBoth(), activeLayerBottom(), activeLayerTop(), m_activeLayerBothAct, m_activeLayerBottomAct, m_activeLayerTopAct, m_viewFromAboveAct, m_viewFromBelowAct, m_viewFromBelowToggleAct, setViewFromAbove(), setViewFromBelow(), and setViewFromBelowToggle().
createActiveLayerButton()
QWidget * MainWindow::createActiveLayerButton (SketchAreaWidget * parent) protected
References m_activeLayerBothAct, m_activeLayerBottomAct, m_activeLayerButtonWidget, and m_activeLayerTopAct.
createAddToBinSubmenu()
void MainWindow::createAddToBinSubmenu (QMenu * parentMenu) protected virtual
References m_binManager, and selectedModuleID().
createAlignSubmenu()
void MainWindow::createAlignSubmenu (QMenu * parentMenu) protected virtual
References m_alignBottomAct, m_alignHorizontalCenterAct, m_alignLeftAct, m_alignRightAct, m_alignTopAct, and m_alignVerticalCenterAct.
createAutorouteButton()
SketchToolButton * MainWindow::createAutorouteButton (SketchAreaWidget * parent) protected
References m_newAutorouteAct, and AbstractStatesButton::setEnabledIcon().
createDockWindows()
void MainWindow::createDockWindows () protected
References DockMinHeight, DockMinWidth, InfoViewHeightDefault, InfoViewMinHeight, m_binManager, m_hideAllLayersAct, m_infoView, m_layerPalette, m_openProgramWindowAct, m_programView, m_showAllLayersAct, m_toggleDebuggerOutputAct, m_undoView, m_windowMenu, m_windowMenuSeparator, makeDock(), PartsBinHeightDefault, PartsBinMinHeight, BinManager::Title, UndoHistoryDefaultHeight, and UndoHistoryMinHeight.
createEditMenu()
void MainWindow::createEditMenu () protected virtual
Reimplemented in PEMainWindow.
References m_addNoteAct, m_copyAct, m_cutAct, m_deleteAct, m_deleteMinusAct, m_deselectAct, m_duplicateAct, m_editMenu, m_pasteAct, m_pasteInPlaceAct, m_preferencesAct, m_redoAct, m_selectAllAct, m_undoAct, and updateEditMenu().
createEditMenuActions()
void MainWindow::createEditMenuActions () protected
References addNote(), copy(), cut(), deselect(), doDelete(), doDeleteMinus(), duplicate(), m_addNoteAct, m_copyAct, m_cutAct, m_deleteAct, m_deleteMinusAct, m_deleteWireAct, m_deleteWireMinusAct, m_deselectAct, m_duplicateAct, m_pasteAct, m_pasteInPlaceAct, m_preferencesAct, m_redoAct, m_selectAllAct, m_undoAct, m_undoGroup, paste(), pasteInPlace(), and selectAll().
createExportActions()
void MainWindow::createExportActions () protected
References bomActionType, doExport(), eagleActionType, exportEtchable(), gerberActionType, jpgActionType, m_exportBomAct, m_exportEagleAct, m_exportEtchablePdfAct, m_exportEtchableSvgAct, m_exportGerberAct, m_exportJpgAct, m_exportNetlistAct, m_exportPdfAct, m_exportPngAct, m_exportSpiceNetlistAct, m_exportSvgAct, m_printAct, m_saveAct, m_saveAsAct, m_shareOnlineAct, netlistActionType, pdfActionType, pngActionType, print(), save(), saveAs(), shareOnline(), spiceNetlistActionType, and svgActionType.
createExportEtchableButton()
SketchToolButton * MainWindow::createExportEtchableButton (SketchAreaWidget * parent) protected
References m_exportEtchablePdfAct, m_exportEtchableSvgAct, m_exportGerberAct, and AbstractStatesButton::setEnabledIcon().
createFileMenu()
void MainWindow::createFileMenu () protected virtual
Reimplemented in PEMainWindow.
References externalProcess(), FritzingWindow::m_closeAct, m_exceptionAct, m_exportBomAct, m_exportMenu, m_exportNetlistAct, m_exportSpiceNetlistAct, m_fileMenu, m_launchExternalProcessAct, m_newAct, m_openAct, m_openExampleMenu, m_openRecentFileMenu, m_orderFabAct, m_orderFabEnabled, m_printAct, m_quitAct, m_revertAct, m_saveAct, m_saveAsAct, m_shareOnlineAct, populateExportMenu(), updateExportMenu(), and updateFileMenu().
createFileMenuActions()
void MainWindow::createFileMenuActions () protected virtual
Reimplemented in PEMainWindow.
References FritzingWindow::createCloseAction(), createExportActions(), createNewSketch(), createOpenExampleMenu(), createOpenRecentMenu(), createOrderFabAct(), externalProcess(), launchExternalProcess(), m_exceptionAct, m_launchExternalProcessAct, m_newAct, m_openAct, m_quitAct, m_revertAct, mainLoad(), revert(), and throwFakeException().
createFlipButton()
SketchToolButton * MainWindow::createFlipButton (SketchAreaWidget * parent) protected
References m_flipButtons, m_flipHorizontalAct, and m_flipVerticalAct.
createGridSizeForm()
QWidget * MainWindow::createGridSizeForm (GridSizeThing * gridSizeThing) protected
References GridSizeThing::defaultGridSize, GridSizeThing::gridSizeText, gridUnits(), GridSizeThing::inButton, GridSizeThing::lineEdit, GridSizeThing::mmButton, restoreDefaultGrid(), GridSizeThing::validator, and GridSizeThing::viewName.
createHelpMenu()
void MainWindow::createHelpMenu () protected virtual
References m_aboutAct, m_aboutQtAct, m_checkForUpdatesAct, m_enableDebugAct, m_examplesAct, m_firstTimeHelpAct, m_helpMenu, m_openDonateAct, m_openHelpAct, m_partsEditorHelpAct, m_partsRefAct, m_reportBugAct, and m_tipsAndTricksAct.
createHelpMenuActions()
void MainWindow::createHelpMenuActions () protected
References about(), DebugDialog::enabled(), enableDebug(), firstTimeHelp(), m_aboutAct, m_aboutQtAct, m_checkForUpdatesAct, m_enableDebugAct, m_examplesAct, m_firstTimeHelpAct, m_openDonateAct, m_openHelpAct, m_partsEditorHelpAct, m_partsRefAct, m_reportBugAct, m_tipsAndTricksAct, openDonate(), openExamples(), openHelp(), openPartsReference(), partsEditorHelp(), reportBug(), and tipsAndTricks().
createMenus()
void MainWindow::createMenus () protected virtual
Reimplemented in PEMainWindow.
References createEditMenu(), createFileMenu(), createHelpMenu(), createPartMenu(), createTraceMenus(), createViewMenu(), createWindowMenu(), and m_programView.
createNewSketch
void MainWindow::createNewSketch () protected slot
References addDefaultParts(), CascadeFactorX, CascadeFactorY, clearFileProgressDialog(), hideTempPartsBin(), m_referenceModel, newMainWindow(), and ProcessEventBlocker::processEvents().
createNoteButton()
SketchToolButton * MainWindow::createNoteButton (SketchAreaWidget * parent) protected
References m_addNoteAct, and AbstractStatesButton::setEnabledIcon().
createOpenExampleMenu()
void MainWindow::createOpenExampleMenu () protected
References FolderUtils::getApplicationSubFolderPath(), m_openExampleActions, m_openExampleMenu, and populateMenuFromXMLFile().
createOpenRecentMenu()
void MainWindow::createOpenRecentMenu () protected
References m_openRecentFileActs, m_openRecentFileMenu, MaxRecentFiles, openRecentOrExampleFile(), and updateRecentFileActions().
createOrderFabAct()
void MainWindow::createOrderFabAct () protected
References m_orderFabAct, and orderFab().
createOrderFabButton()
SketchToolButton * MainWindow::createOrderFabButton (SketchAreaWidget * parent) protected
References m_orderFabAct, orderFabHoverEnter(), orderFabHoverLeave(), and AbstractStatesButton::setEnabledIcon().
createPartMenu()
void MainWindow::createPartMenu () protected virtual
References createAddToBinSubmenu(), createAlignSubmenu(), createRotateSubmenu(), createZOrderSubmenu(), m_dumpAllPartsAction, m_findPartInSketchAct, m_flipHorizontalAct, m_flipVerticalAct, m_moveLockAct, m_openInPartsEditorNewAct, m_partMenu, m_regeneratePartsDatabaseAct, m_saveBundledPart, m_selectAllObsoleteAct, m_selectMoveLockAct, m_showPartLabelAct, m_stickyAct, m_swapObsoleteAct, and updatePartMenu().
createPartMenuActions()
void MainWindow::createPartMenuActions () protected
References addBendpoint(), alignBottom(), alignHorizontalCenter(), alignLeft(), alignRight(), alignTop(), alignVerticalCenter(), bringForward(), bringToFront(), convertToBendpoint(), convertToVia(), disconnectAll(), dumpAllParts(), exportNormalizedFlattenedSVG(), exportNormalizedSVG(), findPartInSketch(), flattenCurve(), flipHorizontal(), flipVertical(), hidePartSilkscreen(), m_addBendpointAct, m_alignBottomAct, m_alignHorizontalCenterAct, m_alignLeftAct, m_alignRightAct, m_alignTopAct, m_alignVerticalCenterAct, m_bringForwardAct, m_bringForwardWireAct, m_bringToFrontAct, m_bringToFrontWireAct, m_convertToBendpointAct, m_convertToViaAct, m_disconnectAllAct, m_dumpAllPartsAction, m_exportNormalizedFlattenedSvgAction, m_exportNormalizedSvgAction, m_findPartInSketchAct, m_flattenCurveAct, m_flipHorizontalAct, m_flipVerticalAct, m_hidePartSilkscreenAct, m_infoViewOnHoverAction, m_moveLockAct, m_openInPartsEditorNewAct, m_regeneratePartsDatabaseAct, m_rotate180Act, m_rotate45ccwAct, m_rotate45cwAct, m_rotate90ccwAct, m_rotate90cwAct, m_saveBundledPart, m_selectAllObsoleteAct, m_selectMoveLockAct, m_sendBackwardAct, m_sendBackwardWireAct, m_sendToBackAct, m_sendToBackWireAct, m_showPartLabelAct, m_stickyAct, m_swapObsoleteAct, m_testConnectorsAction, moveLock(), openInPartsEditorNew(), rotate180(), rotate45ccw(), rotate45cw(), rotate90ccw(), rotate90cw(), saveBundledPart(), selectAllObsolete(), selectMoveLock(), sendBackward(), sendToBack(), setInfoViewOnHover(), setSticky(), showPartLabels(), swapObsolete(), and testConnectors().
createRaiseWindowActions()
void MainWindow::createRaiseWindowActions () protected
References FritzingWindow::m_fwFilename, m_raiseWindowAct, raiseAndActivate(), and updateRaiseWindowAction().
createRotateButton()
SketchToolButton * MainWindow::createRotateButton (SketchAreaWidget * parent) protected
References m_rotate180Act, m_rotate45ccwAct, m_rotate45cwAct, m_rotate90ccwAct, m_rotate90cwAct, and m_rotateButtons.
createRotateSubmenu()
void MainWindow::createRotateSubmenu (QMenu * parentMenu) protected virtual
References m_rotate180Act, m_rotate45ccwAct, m_rotate45cwAct, m_rotate90ccwAct, and m_rotate90cwAct.
createRoutingStatusLabel()
ExpandingLabel * MainWindow::createRoutingStatusLabel (SketchAreaWidget * parent) protected
References SketchAreaWidget::contentView(), m_pcbWidget, SketchAreaWidget::RoutingStateLabelName, routingStatusLabelMousePress(), routingStatusLabelMouseRelease(), routingStatusSlot(), SketchAreaWidget::setRoutingStatusLabel(), and RoutingStatus::zero().
createShareButton()
SketchToolButton * MainWindow::createShareButton (SketchAreaWidget * parent) protected
References m_shareOnlineAct, and AbstractStatesButton::setEnabledIcon().
createStatusBar()
void MainWindow::createStatusBar () protected
References FritzingWindow::m_statusBar.
createTabWidget()
QWidget * MainWindow::createTabWidget () protected virtual
Reimplemented in PEMainWindow.
createToolbarSpacer()
QWidget * MainWindow::createToolbarSpacer (SketchAreaWidget * parent) protected
createTrace
void MainWindow::createTrace () protected slot
References m_currentGraphicsView, and retrieveWire().
createTraceMenuActions()
void MainWindow::createTraceMenuActions () protected
References autorouterSettings(), changeTraceLayer(), checkLoadedTraces(), clearGroundFillSeeds(), copperFill(), createActiveLayerActions(), createOrderFabAct(), createTrace(), excludeFromAutoroute(), fabQuote(), groundFill(), m_autorouterSettingsAct, m_changeTraceLayerAct, m_changeTraceLayerWireAct, m_checkLoadedTracesAct, m_clearGroundFillSeedsAct, m_copperFillAct, m_createTraceWireAct, m_createWireWireAct, m_excludeFromAutorouteAct, m_excludeFromAutorouteWireAct, m_fabQuoteAct, m_groundFillAct, m_newAutorouteAct, m_newDesignRulesCheckAct, m_removeGroundFillAct, m_selectAllCopperFillAct, m_selectAllExcludedTracesAct, m_selectAllIncludedTracesAct, m_selectAllJumperItemsAct, m_selectAllTracesAct, m_selectAllViasAct, m_selectAllWiresAct, m_setGroundFillKeepoutAct, m_setGroundFillSeedsAct, m_setOneGroundFillSeedAct, m_showUnroutedAct, m_tidyWiresAct, m_updateRoutingStatusAct, newAutoroute(), newDesignRulesCheck(), removeGroundFill(), selectAllCopperFill(), selectAllExcludedTraces(), selectAllIncludedTraces(), selectAllJumperItems(), selectAllTraces(), selectAllVias(), setGroundFillKeepout(), setGroundFillSeeds(), setOneGroundFillSeed(), showUnrouted(), tidyWires(), and updateRoutingStatus().
createTraceMenus()
void MainWindow::createTraceMenus () protected virtual
References m_activeLayerBothAct, m_activeLayerBottomAct, m_activeLayerTopAct, m_autorouterSettingsAct, m_breadboardTraceMenu, m_changeTraceLayerAct, m_clearGroundFillSeedsAct, m_copperFillAct, m_excludeFromAutorouteAct, m_fabQuoteAct, m_groundFillAct, m_newAutorouteAct, m_newDesignRulesCheckAct, m_pcbTraceMenu, m_removeGroundFillAct, m_schematicTraceMenu, m_selectAllCopperFillAct, m_selectAllExcludedTracesAct, m_selectAllIncludedTracesAct, m_selectAllJumperItemsAct, m_selectAllTracesAct, m_selectAllViasAct, m_selectAllWiresAct, m_setGroundFillKeepoutAct, m_setGroundFillSeedsAct, m_showUnroutedAct, m_tidyWiresAct, m_viewFromBelowToggleAct, and updateTraceMenu().
createViewFromButton()
QWidget * MainWindow::createViewFromButton (SketchAreaWidget * parent) protected
References m_viewFromAboveAct, m_viewFromBelowAct, m_viewFromButtonWidget, and AbstractStatesButton::setEnabledIcon().
createViewMenu()
void MainWindow::createViewMenu () protected virtual
Reimplemented in PEMainWindow.
References m_100PercentSizeAct, m_actualSizeAct, m_alignToGridAct, m_binManager, m_colorWiresByLengthAct, m_fitInWindowAct, m_numFixedActionsInViewMenu, m_programView, m_setBackgroundColorAct, m_setGridSizeAct, m_showBreadboardAct, m_showGridAct, m_showPartsBinIconViewAct, m_showPartsBinListViewAct, m_showPCBAct, m_showProgramAct, m_showSchematicAct, m_showWelcomeAct, m_viewMenu, m_welcomeView, m_zoomInAct, m_zoomOutAct, and updateLayerMenu().
createViewMenuActions()
void MainWindow::createViewMenuActions (bool showWelcome) protected virtual
Reimplemented in PEMainWindow.
References actualSize(), alignToGrid(), colorWiresByLength(), fitInWindow(), hideAllLayers(), hundredPercentSize(), m_100PercentSizeAct, m_actualSizeAct, m_alignToGridAct, m_colorWiresByLengthAct, m_fitInWindowAct, m_hideAllLayersAct, m_programView, m_setBackgroundColorAct, m_setGridSizeAct, m_showAllLayersAct, m_showBreadboardAct, m_showGridAct, m_showPartsBinIconViewAct, m_showPartsBinListViewAct, m_showPCBAct, m_showProgramAct, m_showSchematicAct, m_showWelcomeAct, m_welcomeView, m_zoomInAct, m_zoomInShortcut, m_zoomOutAct, setBackgroundColor(), setGridSize(), showAllLayers(), showBreadboardView(), showGrid(), showPartsBinIconView(), showPartsBinListView(), showPCBView(), showProgramView(), showSchematicView(), showWelcomeView(), zoomIn(), and zoomOut().
createWindowMenu()
void MainWindow::createWindowMenu () protected virtual
References m_minimizeAct, m_windowMenu, and updateWindowMenu().
createWindowMenuActions()
void MainWindow::createWindowMenuActions () protected
References m_minimizeAct, m_openProgramWindowAct, m_toggleDebuggerOutputAct, minimize(), openProgramWindow(), and toggleDebuggerOutput().
createZoomOptions()
void MainWindow::createZoomOptions (SketchAreaWidget * parent) protected
References SketchAreaWidget::contentView(), updateZoomOptionsNoMatterWhat(), and updateZoomSlider().
createZOrderSubmenu()
void MainWindow::createZOrderSubmenu (QMenu * parentMenu) protected virtual
References m_bringForwardAct, m_bringToFrontAct, m_sendBackwardAct, and m_sendToBackAct.
currentSketchArea()
SketchAreaWidget * MainWindow::currentSketchArea () protected
References m_currentGraphicsView.
currentTabIndex()
int MainWindow::currentTabIndex () protected virtual
Reimplemented in PEMainWindow.
References m_tabWidget.
currentTabWidget()
QWidget * MainWindow::currentTabWidget () protected virtual
Reimplemented in PEMainWindow.
References m_tabWidget.
cursorLocationSlot
void MainWindow::cursorLocationSlot (double xinches, double yinches, double width = 0.0, double height = 0.0) protected slot
References m_locationLabel, m_locationLabelUnits, and GraphicsUtils::SVGDPI.
cut
void MainWindow::cut () protected slot
References m_currentGraphicsView.
defaultSaveFolder()
const QString MainWindow::defaultSaveFolder () protected virtual
Implements FritzingWindow.
References FolderUtils::openSaveFolder().
deselect
void MainWindow::deselect () protected slot
References m_currentGraphicsView.
disconnectAll
void MainWindow::disconnectAll () protected slot
References m_currentGraphicsView.
dockChangeActivation
void MainWindow::dockChangeActivation (bool activate, QWidget * originator) protected slot
References m_closing, and m_sizeGrip.
dockIt()
FDockWidget * MainWindow::dockIt (FDockWidget * dock, int dockMinHeight, int dockDefaultHeight, Qt::DockWidgetArea area = Qt::RightDockWidgetArea) protected
References dockChangeActivation(), DockMinWidth, DockWidthDefault, m_docks, and m_windowMenu.
dockMarginAux()
void MainWindow::dockMarginAux (FDockWidget * dock, const QString & name, const QString & style) protected
doDelete
void MainWindow::doDelete () protected slot
References m_currentGraphicsView, and retrieveWire().
doDeleteMinus
void MainWindow::doDeleteMinus () protected slot
References m_currentGraphicsView, and retrieveWire().
doExport
void MainWindow::doExport () protected slot
References FritzingWindow::alreadyHasExtension(), bomActionType, constructFileName(), DebugDialog::debug(), defaultSaveFolder(), eagleActionType, exportAux(), exportBOM(), exportNetlist(), exportProgress(), exportSpiceNetlist(), exportSvg(), exportToEagle(), exportToGerber(), fileExportFormats, fileExtFormats, FritzingWindow::fileName(), filePrintFormats, fileProgressDialog(), gerberActionType, FolderUtils::getSaveFileName(), GraphicsUtils::IllustratorDPI, FritzingWindow::m_statusBar, netlistActionType, pngActionType, printAux(), spiceNetlistActionType, and svgActionType.
dontKeepMargins()
void MainWindow::dontKeepMargins () protected
References m_dontKeepMargins.
dragEnterEvent()
void MainWindow::dragEnterEvent (QDragEnterEvent * event) protected
References fritzingExtensions().
dropEvent()
void MainWindow::dropEvent (QDropEvent * event) protected
References mainLoadAux().
dropPaste
void MainWindow::dropPaste (SketchWidget * sketchWidget) protected slot
References pasteInPlace().
dumpAllParts
void MainWindow::dumpAllParts () protected slot
References ItemBase::cachedConnectorItems(), ConnectorItem::connectedToItems(), ConnectorItem::connectionsCount(), ConnectorItemAction::connectorItem(), ConnectorItem::debugInfo(), ItemBase::debugInfo(), ItemBase::layerKinChief(), and m_currentGraphicsView.
duplicate
void MainWindow::duplicate () protected slot
References m_currentGraphicsView, and paste().
enableAddBendpointAct()
void MainWindow::enableAddBendpointAct (QGraphicsItem * graphicsItem) protected
References ItemBase::getRatsnest(), Wire::isCurved(), FGraphicsScene::lastContextMenuPos(), m_addBendpointAct, m_convertToViaAct, m_currentGraphicsView, m_flattenCurveAct, m_pcbGraphicsView, BendpointAction::setLastHoverEnterConnectorItem(), BendpointAction::setLastHoverEnterItem(), and BendpointAction::setLastLocation().
enableCheckUpdates()
void MainWindow::enableCheckUpdates (bool enabled)
References m_checkForUpdatesAct.
enableDebug
void MainWindow::enableDebug () protected slot
References m_enableDebugAct, m_toggleDebuggerOutputAct, m_windowMenu, m_windowMenuSeparator, DebugDialog::setEnabled(), and toggleDebuggerOutput().
ensureClosable
void MainWindow::ensureClosable () slot
References m_dontClose.
event()
bool MainWindow::event (QEvent * e) protected
References changeActivationSignal().
eventFilter()
bool MainWindow::eventFilter (QObject * obj, QEvent * event) protected
References doDelete(), doDeleteMinus(), event(), ProcessEventBlocker::processEvents(), updatePartMenu(), and updateTraceMenu().
excludeFromAutoroute
void MainWindow::excludeFromAutoroute () protected slot
References PCBSketchWidget::excludeFromAutoroute(), m_currentGraphicsView, m_excludeFromAutorouteAct, m_excludeFromAutorouteWireAct, and retrieveWire().
exportAux()
void MainWindow::exportAux (QString fileName, QImage::Format format, int quality, bool removeBackground) protected
References TextUtils::CreatedWithFritzingString, FritzingWindow::fileName(), InchesPerMeter, m_currentGraphicsView, and GraphicsUtils::SVGDPI.
exportBOM()
void MainWindow::exportBOM () protected
References FritzingWindow::alreadyHasExtension(), bomActionType, constructFileName(), DebugDialog::debug(), defaultSaveFolder(), exportProgress(), fileExtFormats, FritzingWindow::fileName(), fileProgressDialog(), getBomProps(), FolderUtils::getSaveFileName(), ItemBase::instanceTitle(), ItemBase::itemType(), m_currentGraphicsView, m_currentWidget, FritzingWindow::m_fwFilename, Version::majorVersion(), Version::minorSubVersion(), Version::minorVersion(), ModelPart::Part, sortPartList(), ItemBase::title(), and TextUtils::writeUtf8().
exportEtchable [1/2]
void MainWindow::exportEtchable () protected slot
exportEtchable() [2/2]
void MainWindow::exportEtchable (bool wantPDF, bool wantSVG) protected
References RenderThing::blackOnly, constructFileName(), ViewLayer::Copper0, ViewLayer::Copper0Trace, ViewLayer::Copper1, ViewLayer::Copper1Trace, defaultSaveFolder(), RenderThing::dpi, exportProgress(), fileExtFormats, FritzingWindow::fileName(), filePrintFormats, fileProgressDialog(), ViewLayer::GroundPlane0, ViewLayer::GroundPlane1, RenderThing::hideTerminalPoints, ItemBase::id(), GraphicsUtils::IllustratorDPI, ItemBase::instanceTitle(), RoutingStatus::m_connectorsLeftToRoute, m_pcbGraphicsView, FritzingWindow::m_statusBar, massageOutput(), mergeBoardSvg(), pdfActionType, RenderThing::printerScale, RenderThing::renderBlocker, RenderThing::selectedItems, FolderUtils::setOpenSaveFolder(), ViewLayer::Silkscreen0, ViewLayer::Silkscreen0Label, ViewLayer::Silkscreen1, ViewLayer::Silkscreen1Label, svgActionType, GraphicsUtils::SVGDPI, and TextUtils::writeUtf8().
exportNetlist()
void MainWindow::exportNetlist () protected
References FritzingWindow::alreadyHasExtension(), ErcData::Always, NonConnectorItem::attachedTo(), ConnectorItemAction::connectorItem(), ConnectorItem::connectorSharedErcData(), ConnectorItem::connectorSharedID(), ConnectorItem::connectorSharedName(), constructFileName(), TextUtils::CreatedWithFritzingXmlComment, defaultSaveFolder(), exportProgress(), fileExtFormats, FritzingWindow::fileName(), fileProgressDialog(), FolderUtils::getSaveFileName(), ItemBase::id(), ErcData::IfUnconnected, ErcData::ignore(), ItemBase::instanceTitle(), m_currentGraphicsView, FritzingWindow::m_fwFilename, netlistActionType, ItemBase::title(), and ErcData::writeToElement().
exportNormalizedFlattenedSVG
void MainWindow::exportNormalizedFlattenedSVG () protected slot
References exportSvg(), and GraphicsUtils::StandardFritzingDPI.
exportNormalizedSVG
void MainWindow::exportNormalizedSVG () protected slot
References exportSvg(), and GraphicsUtils::StandardFritzingDPI.
exportProgress()
FileProgressDialog * MainWindow::exportProgress () protected
exportSpiceNetlist()
void MainWindow::exportSpiceNetlist () protected
References FritzingWindow::alreadyHasExtension(), NonConnectorItem::attachedTo(), ItemBase::cachedConnectorItems(), ConnectorItem::connectorSharedID(), constructFileName(), DebugDialog::debug(), ConnectorItem::debugInfo(), defaultSaveFolder(), fileExtFormats, FritzingWindow::fileName(), FolderUtils::getAppPartsSubFolder(), FolderUtils::getSaveFileName(), FolderUtils::getUserPartsPath(), ItemBase::instanceTitle(), ConnectorItem::isGrounded(), ModelPart::localProp(), FritzingWindow::m_fwFilename, m_schematicGraphicsView, ItemBase::modelPart(), ModelPart::possibleFolders(), ModelPart::properties(), ItemBase::spice(), ItemBase::spiceModel(), spiceNetlistActionType, and TextUtils::writeUtf8().
exportSvg() [1/2]
void MainWindow::exportSvg (double res, bool selectedItems, bool flatten, const QString & filename)
References RenderThing::blackOnly, TextUtils::convertExtendedChars(), RenderThing::dpi, exportProgress(), exportSvgWatermark(), FritzingWindow::fileName(), fileProgressDialog(), RenderThing::hideTerminalPoints, m_currentGraphicsView, RenderThing::printerScale, RenderThing::renderBlocker, RenderThing::selectedItems, GraphicsUtils::SVGDPI, ViewLayer::viewLayerID(), ViewLayer::visible(), and TextUtils::writeUtf8().
exportSvg() [2/2]
void MainWindow::exportSvg (double res, bool selectedItems, bool flatten) protected
References constructFileName(), defaultSaveFolder(), exportSvg(), fileExtFormats, FritzingWindow::fileName(), FolderUtils::getSaveFileName(), and svgActionType.
exportSvgWatermark()
void MainWindow::exportSvgWatermark (QString & svg, double res) protected
References TextUtils::makeSVGHeader(), TextUtils::mergeSvg(), SvgFileSplitter::normalize(), TextUtils::parseForWidthAndHeight(), SvgFileSplitter::shift(), and SvgFileSplitter::splitString().
exportToEagle()
void MainWindow::exportToEagle () protected
References m_pcbGraphicsView.
exportToGerber()
void MainWindow::exportToGerber () protected
References defaultSaveFolder(), exportProgress(), GerberGenerator::exportToGerber(), fileProgressDialog(), ItemBase::id(), ItemBase::instanceTitle(), FritzingWindow::m_fwFilename, m_pcbGraphicsView, FritzingWindow::m_statusBar, and FolderUtils::setOpenSaveFolder().
externalProcess
bool MainWindow::externalProcess (QString & name, QString & path, QStringList & args) protected slot
References externalProcessSignal().
externalProcessSignal
void MainWindow::externalProcessSignal (QString & name, QString & path, QStringList & args) signal
fabQuote
void MainWindow::fabQuote () protected slot
References m_pcbGraphicsView.
fileExtension()
const QString MainWindow::fileExtension () protected virtual
Implements FritzingWindow.
References FritzingBundleExtension().
filenameIfSlot
void MainWindow::filenameIfSlot (QString & filename) protected slot
References FritzingWindow::fileName().
fileProgressDialog()
FileProgressDialog * MainWindow::fileProgressDialog ()
References m_fileProgressDialog.
findPartInSketch
void MainWindow::findPartInSketch () protected slot
References ItemBase::id(), ItemBase::instanceTitle(), ItemBase::layerKinChief(), m_currentGraphicsView, m_referenceModel, and ItemBase::modelPart().
findReplacedby()
ModelPart * MainWindow::findReplacedby (ModelPart * originalModelPart) protected
References m_referenceModel, and ModelPart::replacedby().
fireQuote
void MainWindow::fireQuote () protected slot
References m_fireQuoteTimer, m_orderFabButton, m_pcbGraphicsView, m_pcbWidget, m_rolloverQuoteDialog, and QuoteDialog::quoteSucceeded().
fireQuoteDelay()
int MainWindow::fireQuoteDelay ()
firstTimeHelp
void MainWindow::firstTimeHelp () protected slot
References m_currentGraphicsView, FirstTimeHelpDialog::setViewID(), and FirstTimeHelpDialog::showFirstTimeHelp().
fitInWindow
void MainWindow::fitInWindow () protected slot
References m_currentGraphicsView, and m_zoomSlider.
flattenCurve
void MainWindow::flattenCurve () protected slot
References BendpointAction::lastHoverEnterConnectorItem(), BendpointAction::lastHoverEnterItem(), BendpointAction::lastLocation(), m_addBendpointAct, and m_currentGraphicsView.
flipHorizontal
void MainWindow::flipHorizontal () protected slot
References m_currentGraphicsView.
flipVertical
void MainWindow::flipVertical () protected slot
References m_currentGraphicsView.
fritzingTitle()
const QString MainWindow::fritzingTitle () protected virtual
Reimplemented from FritzingWindow.
References FritzingWindow::fritzingTitle(), and m_currentGraphicsView.
fritzingVersion()
const QString & MainWindow::fritzingVersion ()
References ___emptyString___, and m_sketchModel.
genIcon()
QString MainWindow::genIcon (SketchWidget * , LayerList & partViewLayerIDs, LayerList & wireViewLayerIDs) protected
getBoardSvg()
QString MainWindow::getBoardSvg (ItemBase * board, int res, LayerList & viewLayerIDs) protected
References ___emptyString___, RenderThing::blackOnly, RenderThing::dpi, RenderThing::hideTerminalPoints, ItemBase::layerKin(), ItemBase::layerKinChief(), m_pcbGraphicsView, RenderThing::printerScale, RenderThing::renderBlocker, RenderThing::selectedItems, GraphicsUtils::SVGDPI, and ItemBase::viewLayerID().
getBomProps()
QString MainWindow::getBomProps (ItemBase * itemBase) protected
References ItemBase::collectExtraInfo(), HtmlInfoView::getPartProperties(), ItemBase::modelPart(), and ItemBase::translatePropertyName().
getButtonsForView()
QList< QWidget * > MainWindow::getButtonsForView (ViewLayer::ViewID viewId) protected virtual
Reimplemented in PEMainWindow.
References ViewLayer::BreadboardView, createActiveLayerButton(), createAutorouteButton(), createExportEtchableButton(), createFlipButton(), createNoteButton(), createOrderFabButton(), createRotateButton(), createRoutingStatusLabel(), createShareButton(), createViewFromButton(), m_breadboardWidget, m_orderFabButton, m_orderFabEnabled, m_pcbWidget, m_schematicWidget, ViewLayer::PCBView, and ViewLayer::SchematicView.
getExtensions()
QStringList MainWindow::getExtensions () protected virtual
Implements FritzingWindow.
References FritzingBundleExtension(), and FritzingSketchExtension().
getExtensionString()
QString MainWindow::getExtensionString () protected virtual
Implements FritzingWindow.
References FritzingBundleExtension(), and FritzingSketchExtension().
getPartsEditorNewAnd()
void MainWindow::getPartsEditorNewAnd (ItemBase * fromItem)
References openNewPartsEditor().
getStyleSheetSuffix()
QString MainWindow::getStyleSheetSuffix () protected virtual
gridUnits
void MainWindow::gridUnits (bool checked) protected slot
References GridSizeDialog::gridSizeThing(), GridSizeThing::inButton, GridSizeThing::lineEdit, and GridSizeThing::validator.
groundFill() [1/2]
void MainWindow::groundFill (ViewLayer::ViewLayerID viewLayerID)
References groundFillAux().
groundFill [2/2]
void MainWindow::groundFill () slot
References groundFillAux2().
groundFillAux()
void MainWindow::groundFillAux (bool fillGroundTraces, ViewLayer::ViewLayerID viewLayerID) protected
References m_pcbGraphicsView, FritzingWindow::m_undoStack, WaitPushUndoStack::push(), removeGroundFill(), and FileProgressDialog::setIndeterminate().
groundFillAux2()
void MainWindow::groundFillAux2 (bool fillGroundTraces) protected
References ViewLayer::Copper0, ViewLayer::Copper1, groundFillAux(), ViewLayer::GroundPlane0, ViewLayer::GroundPlane1, m_pcbGraphicsView, and ViewLayer::UnknownLayer.
hasAnyAlien()
bool MainWindow::hasAnyAlien ()
References m_addedToTemp.
hasCustomBoardShape()
bool MainWindow::hasCustomBoardShape ()
References m_pcbGraphicsView.
hasLinkedProgramFiles()
bool MainWindow::hasLinkedProgramFiles (const QString & filename, QStringList & linkedProgramFiles) protected
hideAllLayers
void MainWindow::hideAllLayers () protected slot
References m_currentGraphicsView, and updateLayerMenu().
hidePartSilkscreen
void MainWindow::hidePartSilkscreen () protected slot
References m_pcbGraphicsView.
hideShowProgramMenu()
void MainWindow::hideShowProgramMenu () protected
References m_copyAct, m_currentWidget, m_cutAct, m_editMenu, m_partMenu, m_programView, m_redoAct, m_selectAllAct, m_undoAct, and m_viewMenu.
hideShowTraceMenu()
void MainWindow::hideShowTraceMenu () protected
References m_breadboardGraphicsView, m_breadboardTraceMenu, m_currentGraphicsView, m_pcbGraphicsView, m_pcbTraceMenu, m_schematicGraphicsView, and m_schematicTraceMenu.
hideTempPartsBin()
void MainWindow::hideTempPartsBin ()
References m_binManager.
hundredPercentSize
void MainWindow::hundredPercentSize () protected slot
References m_currentGraphicsView, and m_zoomSlider.
indexAvailableElements()
QHash< QString, struct SketchDescriptor * > MainWindow::indexAvailableElements (QDomElement & domElem, const QString & srcPrefix, QStringList & actionsTracker, const QString & localeName) protected
References getBestLanguageChild(), and openRecentOrExampleFile().
init()
void MainWindow::init (ReferenceModel * referenceModel, bool lockFiles)
References applyReadOnlyChange(), breadboardItemMenu(), ViewLayer::BreadboardView, breadboardWireMenu(), connectPairs(), createTabWidget(), createZoomOptions(), getButtonsForView(), initDock(), initLockedFiles(), initMenus(), initProgrammingWidget(), initSketchWidgets(), initStyleSheet(), initWelcomeView(), keepMargins(), m_breadboardGraphicsView, m_breadboardWidget, m_fileProgressDialog, m_infoView, m_pcbGraphicsView, m_pcbWidget, m_referenceModel, m_restarting, m_schematicGraphicsView, m_schematicWidget, m_settingsPrefix, m_setUpDockManagerTimer, m_tabWidget, m_undoGroup, FritzingWindow::m_undoStack, m_undoView, moreInitDock(), pcbItemMenu(), ViewLayer::PCBView, pcbWireMenu(), FritzingWindow::readOnlyChanged(), schematicItemMenu(), ViewLayer::SchematicView, schematicWireMenu(), setInitialView(), and tabWidget_currentChanged().
initDock()
void MainWindow::initDock () protected virtual
Reimplemented in PEMainWindow.
References m_binManager, m_fileProgressDialog, m_infoView, m_layerPalette, m_referenceModel, FritzingWindow::m_undoStack, and selectAllObsolete().
initLockedFiles()
void MainWindow::initLockedFiles (bool lockFiles) protected virtual
Reimplemented in PEMainWindow.
References LockManager::checkLockedFiles(), LockManager::initLockedFiles(), m_fzzFiles, m_fzzFolder, and LockManager::SlowTime.
initMenus()
void MainWindow::initMenus () protected virtual
References createActions(), createMenus(), createStatusBar(), and m_fileProgressDialog.
initNames()
void MainWindow::initNames () static
References AutosaveEnabled, AutosaveTimeoutMinutes, bomActionType, fileExportFormats, fileExtFormats, filePrintFormats, jpgActionType, netlistActionType, FritzingWindow::OtherKnownExtensions, pdfActionType, pngActionType, spiceNetlistActionType, and svgActionType.
initProgrammingWidget()
void MainWindow::initProgrammingWidget () protected virtual
Reimplemented in PEMainWindow.
References addTab(), linkToProgramFile(), and m_programView.
initSketchWidget()
void MainWindow::initSketchWidget (SketchWidget * sketchWidget) protected
References SketchWidget::addViewLayers(), SketchWidget::initGrid(), m_referenceModel, m_sketchModel, FritzingWindow::m_undoStack, SketchWidget::setChainDrag(), SketchWidget::setReferenceModel(), SketchWidget::setSketchModel(), and SketchWidget::setUndoStack().
initSketchWidgets()
void MainWindow::initSketchWidgets (bool withIcons) protected virtual
Reimplemented in PEMainWindow.
References addTab(), ViewLayer::BreadboardView, initSketchWidget(), m_breadboardGraphicsView, m_breadboardWidget, m_fileProgressDialog, m_pcbGraphicsView, m_pcbWidget, m_schematicGraphicsView, m_schematicWidget, ViewLayer::PCBView, and ViewLayer::SchematicView.
initStyleSheet()
void MainWindow::initStyleSheet () protected
References DebugDialog::debug(), and getStyleSheetSuffix().
initWelcomeView()
void MainWindow::initWelcomeView () protected virtual
Reimplemented in PEMainWindow.
References addTab(), and m_welcomeView.
initZoom
void MainWindow::initZoom () protected virtual slot
References ItemBase::isEverVisible(), and m_currentGraphicsView.
isGroundFill()
bool MainWindow::isGroundFill (ItemBase * itemBase) protected
References ModelPart::CopperFill, and ItemBase::itemType().
keepMargins
void MainWindow::keepMargins () protected slot
References addBottomMargin(), m_bottomDock, m_dontKeepMargins, m_oldBottomDockStyle, m_sizeGrip, newBottomWidget(), and removeMargin().
launchExternalProcess
void MainWindow::launchExternalProcess () protected slot
References externalProcess(), FritzingWindow::fileName(), m_externalProcessOutput, processError(), processFinished(), processReadyRead(), and processStateChanged().
linkToProgramFile
void MainWindow::linkToProgramFile (const QString & filename, Platform * platform, bool addLink, bool strong) protected slot
References Platform::getName(), LinkedFile::linkedFilename, m_linkedProgramFiles, and LinkedFile::platform.
loadBundledNonAtomicEntity()
bool MainWindow::loadBundledNonAtomicEntity (const QString & filename, Bundler * bundler, bool addToBin, bool dontAsk)
References FolderUtils::createFolderAndCdIntoIt(), FritzingWindow::fileName(), TextUtils::getRandText(), FolderUtils::getUserPartsPath(), Bundler::loadBundledAux(), moveToPartsFolder(), Bundler::preloadBundledAux(), FolderUtils::rmdir(), FolderUtils::unzipTo(), and FMessageBox::warning().
loadBundledPart
QList< ModelPart * > MainWindow::loadBundledPart (const QString & fileName, bool addToBin) slot
References FolderUtils::createFolderAndCdIntoIt(), FritzingWindow::fileName(), TextUtils::getRandText(), FolderUtils::getUserPartsPath(), moveToPartsFolder(), FolderUtils::rmdir(), FolderUtils::unzipTo(), and FMessageBox::warning().
loadBundledSketch()
void MainWindow::loadBundledSketch (const QString & fileName, bool addToRecent, bool setAsLastOpened, bool checkObsolete) protected
References byConnectorCount(), MissingSvgInfo::connectorSvgIds, FolderUtils::copyBin(), copySvg(), copyToPartsFolder(), copyToSvgFolder(), DebugDialog::debug(), MissingSvgInfo::equal, FritzingWindow::fileName(), TextUtils::findElementsWithAttribute(), PartFactory::folderPath(), FritzingPartExtension(), FritzingSketchExtension(), ViewLayer::getConnectorSvgIDs(), ViewLayer::idFromXmlName(), layers(), m_addedToTemp, m_binManager, m_fzzFolder, m_referenceModel, mainLoad(), MissingSvgInfo::modelPart, TextUtils::parseForModuleID(), MissingSvgInfo::requestedPath, setCurrentFile(), ModelPart::setFzz(), FolderUtils::slamCopy(), BinManager::TempPartsBinTemplateLocation, FolderUtils::unzipTo(), and FMessageBox::warning().
loadedRootSlot
void MainWindow::loadedRootSlot (const QString & filename, ModelBase * , QDomElement & views) protected slot
References LinkedFile::fileFlags, TextUtils::findText(), LinkedFile::InBundleFlag, LinkedFile::linkedFilename, m_linkedProgramFiles, FritzingWindow::m_readOnly, LinkedFile::NoFlag, LinkedFile::ObsoleteFlag, LinkedFile::platform, LinkedFile::ReadOnlyFlag, and LinkedFile::SameMachineFlag.
loadedViewsSlot
void MainWindow::loadedViewsSlot (class ModelBase * , QDomElement & views) protected slot
References SketchWidget::alignToGrid(), autorouterSettings(), ViewLayer::BreadboardView, ViewLayer::idFromXmlName(), m_breadboardGraphicsView, m_pcbGraphicsView, m_schematicGraphicsView, ViewLayer::PCBView, ViewLayer::SchematicView, SketchWidget::setAutorouterSettings(), SketchWidget::setBackground(), SketchWidget::setGridSize(), ZoomableGraphicsView::setViewFromBelow(), and SketchWidget::showGrid().
loadWhich()
bool MainWindow::loadWhich (const QString & fileName, bool setAsLastOpened, bool addToRecent, bool checkObsolete, const QString & displayName)
References FritzingWindow::fileName(), FritzingBinExtension(), FritzingBundledBinExtension(), FritzingBundledPartExtension(), FritzingBundleExtension(), FritzingPartExtension(), FritzingSketchExtension(), loadBundledPart(), loadBundledSketch(), m_binManager, m_fzzFolder, mainLoad(), notYetImplemented(), setCurrentFile(), FolderUtils::slamCopy(), and FMessageBox::warning().
locationLabelClicked
void MainWindow::locationLabelClicked () protected slot
References cursorLocationSlot(), m_locationLabel, and m_locationLabelUnits.
mainLoad() [1/2]
void MainWindow::mainLoad (const QString & fileName, const QString & displayName, bool checkObsolete)
References checkSwapObsolete(), FritzingWindow::fileName(), ModelPart::flippedSMD(), initZoom(), ItemBase::layerKinChief(), loadedRootSlot(), loadedViewsSlot(), m_breadboardGraphicsView, m_convertedSchematic, m_fileProgressDialog, FritzingWindow::m_fwFilename, m_linkedProgramFiles, m_obsoleteSMDOrientation, m_pcbGraphicsView, m_programView, m_referenceModel, m_schematicGraphicsView, m_sketchModel, m_useOldSchematic, ItemBase::modelPart(), ViewLayer::NewBottom, obsoleteSMDOrientationSlot(), oldSchematicsSlot(), ProcessEventBlocker::processEvents(), PaletteItem::rotateItem(), BaseCommand::SingleView, and ItemBase::viewLayerPlacement().
mainLoad [2/2]
void MainWindow::mainLoad () protected slot
References defaultSaveFolder(), FritzingWindow::fileName(), FritzingBinExtension(), FritzingBundledBinExtension(), FritzingBundledPartExtension(), FritzingBundleExtension(), FritzingSketchExtension(), FolderUtils::getOpenFileName(), m_binManager, m_firstOpen, and mainLoadAux().
mainLoadAux()
void MainWindow::mainLoadAux (const QString & fileName) protected
References alreadyOpen(), clearFileProgressDialog(), closeIfEmptySketch(), FritzingWindow::fileName(), FritzingBundleExtension(), fritzingExtensions(), FritzingSketchExtension(), loadWhich(), m_referenceModel, newMainWindow(), and FMessageBox::warning().
mainWindowMoved
void MainWindow::mainWindowMoved (QWidget *) signal
makeDock()
FDockWidget * MainWindow::makeDock (const QString & title, QWidget * widget, int dockMinHeight, int dockDefaultHeight, Qt::DockWidgetArea area = Qt::RightDockWidgetArea, DockFactory dockFactory = NULL) protected
References dockIt(), and keepMargins().
massageOutput()
void MainWindow::massageOutput (QString & svg, bool doMask, bool doSilk, bool doPaste, QString & maskTop, QString & maskBottom, const QString & fileName, ItemBase * board, int dpi, const LayerList & viewLayerIDs) protected
References TextUtils::expandAndFill(), FritzingWindow::fileName(), PCBSketchWidget::makePasteMask(), GerberGenerator::MaskClearanceMils, TextUtils::mergeSvg(), and pcbView().
mergeBoardSvg()
QString MainWindow::mergeBoardSvg (QString & svg, ItemBase * board, int res, bool flip, LayerList & viewLayerIDs) protected
References RenderThing::blackOnly, GerberGenerator::cleanOutline(), TextUtils::convertExtendedChars(), RenderThing::dpi, getBoardSvg(), RenderThing::hideTerminalPoints, m_pcbGraphicsView, TextUtils::mergeSvg(), ViewLayer::outlineLayers(), RenderThing::printerScale, RenderThing::renderBlocker, RenderThing::selectedItems, TextUtils::slamStrokeAndFill(), and GraphicsUtils::SVGDPI.
minimize
void MainWindow::minimize () protected slot
moreInitDock()
void MainWindow::moreInitDock () protected virtual
Reimplemented in PEMainWindow.
References createDockWindows(), and m_fileProgressDialog.
moveEvent()
void MainWindow::moveEvent (QMoveEvent * event) protected
References event(), and mainWindowMoved().
moveLock
void MainWindow::moveLock () protected slot
References ItemBase::extractTopLevelItemBase(), ItemBase::itemType(), ItemBase::layerKinChief(), m_currentGraphicsView, m_infoView, ItemBase::moveLock(), ItemBase::setMoveLock(), and ModelPart::Wire.
moveToPartsFolder()
QList< ModelPart * > MainWindow::moveToPartsFolder (QDir & unzipDir, MainWindow * mw, bool addToBin, bool addToAlien, const QString & prefixFolder, const QString & destFolder, bool importingSinglePart) protected
References copyToPartsFolder(), copyToSvgFolder(), m_binManager, m_referenceModel, TextUtils::parseFileForModuleID(), ZIP_PART, and ZIP_SVG.
newAutoroute
void MainWindow::newAutoroute () protected slot
References activeLayerBoth(), activeLayerBottom(), activeLayerTop(), PCBSketchWidget::autorouteTypePCB(), ProcessEventBlocker::block(), SketchWidget::clearSelection(), ViewLayer::Copper0, ViewLayer::Copper1, PCBSketchWidget::findSelectedBoard(), SketchWidget::layerIsActive(), m_currentGraphicsView, ProcessEventBlocker::processEvents(), SketchWidget::setIgnoreSelectionChangeEvents(), SketchWidget::setLayerActive(), ViewLayer::Silkscreen0, ViewLayer::Silkscreen1, Autorouter::start(), ProcessEventBlocker::unblock(), and updateActiveLayerButtons().
newBottomWidget()
FDockWidget * MainWindow::newBottomWidget () protected
References m_docks.
newDesignRulesCheck() [1/2]
QStringList MainWindow::newDesignRulesCheck (bool showOkMessage)
References activeLayerBoth(), activeLayerBottom(), activeLayerTop(), PCBSketchWidget::autorouteTypePCB(), ProcessEventBlocker::block(), ViewLayer::Copper0, ViewLayer::Copper1, FMessageBox::critical(), PCBSketchWidget::findSelectedBoard(), PCBSketchWidget::getKeepout(), SketchWidget::layerIsActive(), m_currentGraphicsView, ProcessEventBlocker::processEvents(), SketchWidget::setLayerActive(), ViewLayer::Silkscreen0, ViewLayer::Silkscreen1, DRC::start(), GraphicsUtils::SVGDPI, ProcessEventBlocker::unblock(), and updateActiveLayerButtons().
newDesignRulesCheck [2/2]
QStringList MainWindow::newDesignRulesCheck () protected slot
newMainWindow()
MainWindow * MainWindow::newMainWindow (ReferenceModel * referenceModel, const QString & displayPath, bool showProgress, bool lockFiles, int initialTab) static
References init(), MainWindow(), setInitialTab(), and showFileProgressDialog().
newTopWidget()
FDockWidget * MainWindow::newTopWidget () protected
dock->isFloating() && dock->isVisible() &&
References m_docks.
noBackup()
void MainWindow::noBackup ()
References m_autosaveTimer.
noSchematicConversion()
void MainWindow::noSchematicConversion ()
References m_noSchematicConversion.
notClosableForAWhile()
void MainWindow::notClosableForAWhile () virtual
Reimplemented from FritzingWindow.
References ensureClosable(), and m_dontClose.
notYetImplemented()
void MainWindow::notYetImplemented (QString action) protected
obsoleteSMDOrientationSlot
void MainWindow::obsoleteSMDOrientationSlot () protected slot
References m_obsoleteSMDOrientation.
oldSchematicMessage()
QMessageBox::StandardButton MainWindow::oldSchematicMessage (const QString & filename) protected
References FMessageBox::exec().
oldSchematicsSlot
void MainWindow::oldSchematicsSlot (const QString & filename, bool & useOldSchematics) slot
References m_convertedSchematic, m_noSchematicConversion, FritzingWindow::m_readOnly, m_useOldSchematic, oldSchematicMessage(), and FritzingWindow::setReadOnly().
openDonate
void MainWindow::openDonate () protected slot
openExamples
void MainWindow::openExamples () protected slot
openHelp
void MainWindow::openHelp () protected slot
openInPartsEditorNew
void MainWindow::openInPartsEditorNew () protected slot
References m_currentGraphicsView, and openNewPartsEditor().
openNewPartsEditor
void MainWindow::openNewPartsEditor (class PaletteItem * paletteItem) protected slot
References addToMyParts(), PEMainWindow::editsModuleID(), init(), m_referenceModel, ItemBase::moduleID(), and PEMainWindow::setInitialItem().
openPartsReference
void MainWindow::openPartsReference () protected slot
openProgramWindow
void MainWindow::openProgramWindow () protected slot
References changeActivationSignal(), linkToProgramFile(), FritzingWindow::m_fwFilename, m_linkedProgramFiles, and m_programWindow.
openRecentOrExampleFile [1/2]
void MainWindow::openRecentOrExampleFile () protected slot
openRecentOrExampleFile [2/2]
void MainWindow::openRecentOrExampleFile (const QString & filename, const QString & actionText) protected slot
References alreadyOpen(), clearFileProgressDialog(), closeIfEmptySketch(), loadWhich(), m_openExampleActions, m_referenceModel, newMainWindow(), and FritzingWindow::setReadOnly().
openURL
void MainWindow::openURL () protected slot
orderFab
void MainWindow::orderFab () protected slot
orderFabHoverEnter
void MainWindow::orderFabHoverEnter () slot
References fireQuoteDelay(), m_fireQuoteTimer, m_rolloverQuoteDialog, and QuoteDialog::quoteSucceeded().
orderFabHoverLeave
void MainWindow::orderFabHoverLeave () slot
References m_fireQuoteTimer, and m_rolloverQuoteDialog.
pageSetup
void MainWindow::pageSetup () protected slot
References notYetImplemented().
partsEditorHelp
void MainWindow::partsEditorHelp () protected slot
References FolderUtils::getApplicationSubFolder().
paste
void MainWindow::paste () protected slot
References pasteAux().
pasteAux()
void MainWindow::pasteAux (bool pasteInPlace) protected
References SketchWidget::loadFromModelParts(), m_breadboardGraphicsView, m_currentGraphicsView, m_pcbGraphicsView, m_referenceModel, m_schematicGraphicsView, m_sketchModel, FritzingWindow::m_undoStack, pasteInPlace(), WaitPushUndoStack::push(), BaseCommand::SingleView, sketchWidgets(), and SketchWidget::viewName().
pasteInPlace
void MainWindow::pasteInPlace () protected slot
References pasteAux().
pcbItemMenu()
QMenu * MainWindow::pcbItemMenu () protected virtual
Reimplemented in PEMainWindow.
References createRotateSubmenu(), m_clearGroundFillSeedsAct, m_convertToBendpointAct, m_convertToBendpointSeparator, m_hidePartSilkscreenAct, m_setOneGroundFillSeedAct, and viewItemMenuAux().
pcbView()
PCBSketchWidget * MainWindow::pcbView ()
References m_pcbGraphicsView.
pcbWireMenu()
QMenu * MainWindow::pcbWireMenu () protected virtual
Reimplemented in PEMainWindow.
References createZOrderSubmenu(), m_addBendpointAct, m_changeTraceLayerWireAct, m_convertToViaAct, m_createTraceWireAct, m_deleteWireAct, m_deleteWireMinusAct, m_excludeFromAutorouteWireAct, m_flattenCurveAct, m_infoViewOnHoverAction, and updateWireMenu().
populateExportMenu()
void MainWindow::populateExportMenu () protected virtual
References m_exportEtchablePdfAct, m_exportEtchableSvgAct, m_exportGerberAct, m_exportJpgAct, m_exportMenu, m_exportPdfAct, m_exportPngAct, and m_exportSvgAct.
populateMenuFromFolderContent()
void MainWindow::populateMenuFromFolderContent (QMenu * parentMenu, const QString & path) protected
References m_openExampleActions, and openRecentOrExampleFile().
populateMenuFromXMLFile()
void MainWindow::populateMenuFromXMLFile (QMenu * parentMenu, QStringList & actionsTracker, const QString & folderPath, const QString & indexFileName) protected
References SketchDescriptor::id, indexAvailableElements(), populateMenuWithIndex(), and sortSketchDescriptors().
populateMenuWithIndex()
void MainWindow::populateMenuWithIndex (const QHash< QString, struct SketchDescriptor * > & index, QMenu * parentMenu, QDomElement & domElem, const QString & localeName) protected
References SketchDescriptor::action, getBestLanguageChild(), and openURL().
print
void MainWindow::print () protected slot
References m_currentGraphicsView, m_currentWidget, m_programView, FritzingWindow::m_statusBar, and printAux().
printAux()
void MainWindow::printAux (QPrinter & printer, bool removeBackground, bool paginate) protected
References DebugDialog::debug(), m_currentGraphicsView, qMin(), and GraphicsUtils::SVGDPI.
processError
void MainWindow::processError (QProcess::ProcessError processError) protected slot
References DebugDialog::debug().
processFinished
void MainWindow::processFinished (int exitCode, QProcess::ExitStatus exitStatus) protected slot
References DebugDialog::debug(), externalProcess(), and m_externalProcessOutput.
processReadyRead
void MainWindow::processReadyRead () protected slot
References DebugDialog::debug(), and m_externalProcessOutput.
processStateChanged
void MainWindow::processStateChanged (QProcess::ProcessState newState) protected slot
References DebugDialog::debug().
programmingWidget()
ProgramWindow * MainWindow::programmingWidget ()
References m_programView.
raiseAndActivate
void MainWindow::raiseAndActivate () protected slot
References activateWindowAux().
raiseWindowAction()
QAction * MainWindow::raiseWindowAction ()
References m_raiseWindowAct.
realStatusBar()
QStatusBar * MainWindow::realStatusBar ()
References FritzingWindow::m_statusBar.
recoverBackupedFiles()
void MainWindow::recoverBackupedFiles () protected
References m_filesReplacedByAlienOnes, FritzingWindow::m_tempDir, resetTempFolder(), and FolderUtils::slamCopy().
redrawSketch()
void MainWindow::redrawSketch ()
References m_currentGraphicsView, and ConnectorItem::restoreColor().
removeActionsStartingAt()
void MainWindow::removeActionsStartingAt (QMenu * menu, int start = 0) static protected
removeGroundFill() [1/2]
void MainWindow::removeGroundFill (ViewLayer::ViewLayerID viewLayerID, QUndoCommand * parentCommand)
References BaseCommand::CrossView, isGroundFill(), ItemBase::layerKinChief(), m_pcbGraphicsView, FritzingWindow::m_undoStack, ItemBase::moveLock(), WaitPushUndoStack::push(), CleanUpWiresCommand::RedoOnly, ItemBase::saveGeometry(), CleanUpWiresCommand::UndoOnly, ViewLayer::UnknownLayer, and ItemBase::viewLayerID().
removeGroundFill [2/2]
void MainWindow::removeGroundFill () slot
References ViewLayer::UnknownLayer.
removeMargin()
void MainWindow::removeMargin (FDockWidget * dock) protected
References dockMarginAux(), and m_oldBottomDockStyle.
reportBug
void MainWindow::reportBug () protected slot
resetTempFolder()
void MainWindow::resetTempFolder () protected
References m_filesReplacedByAlienOnes, FritzingWindow::m_tempDir, and FolderUtils::rmdir().
resizeEvent()
void MainWindow::resizeEvent (QResizeEvent * event) protected
References event(), and m_sizeGrip.
restoreDefaultGrid
void MainWindow::restoreDefaultGrid () protected slot
References GridSizeThing::defaultGridSize, GridSizeDialog::gridSizeThing(), GridSizeThing::inButton, GridSizeThing::lineEdit, and GridSizeThing::mmButton.
restoreDocks()
void MainWindow::restoreDocks ()
References FDockWidget::restoreState().
retrieveConnectorItem()
ConnectorItem * MainWindow::retrieveConnectorItem () protected
References ConnectorItemAction::connectorItem().
retrieveWire()
Wire * MainWindow::retrieveWire () protected
References WireAction::wire().
revert
void MainWindow::revert () protected slot
References revertAux().
revertAux()
MainWindow * MainWindow::revertAux () protected
References addDefaultParts(), clearFileProgressDialog(), currentTabIndex(), FritzingWindow::fileName(), hideTempPartsBin(), FolderUtils::isEmptyFileName(), loadWhich(), FritzingWindow::m_fwFilename, m_referenceModel, newMainWindow(), setCloseSilently(), setCurrentTabIndex(), and untitledFileName().
rotate180
void MainWindow::rotate180 () protected slot
References m_currentGraphicsView.
rotate45ccw
void MainWindow::rotate45ccw () protected slot
References m_currentGraphicsView.
rotate45cw
void MainWindow::rotate45cw () protected slot
References m_currentGraphicsView.
rotate90ccw
void MainWindow::rotate90ccw () protected slot
References m_currentGraphicsView.
rotate90cw
void MainWindow::rotate90cw () protected slot
References m_currentGraphicsView.
rotateIncCCW
void MainWindow::rotateIncCCW () protected slot
References m_currentGraphicsView, m_rotate45ccwAct, and m_rotate90ccwAct.
rotateIncCCWRubberBand
void MainWindow::rotateIncCCWRubberBand () protected slot
References m_currentGraphicsView, m_rotate45ccwAct, and m_rotate90ccwAct.
rotateIncCW
void MainWindow::rotateIncCW () protected slot
References m_currentGraphicsView, m_rotate45cwAct, m_rotate90cwAct, rotate45cw(), and rotate90cw().
rotateIncCWRubberBand
void MainWindow::rotateIncCWRubberBand () protected slot
References m_currentGraphicsView, m_rotate45cwAct, and m_rotate90cwAct.
routingStatusLabelMouse()
void MainWindow::routingStatusLabelMouse (QMouseEvent * , bool show) protected
References ConnectorItem::connectedToItems(), Wire::connector0(), Wire::connector1(), ConnectorItem::getCrossLayerConnectorItem(), NonConnectorItem::hidden(), NonConnectorItem::layerHidden(), m_currentGraphicsView, and ConnectorItem::showEqualPotential().
routingStatusLabelMousePress
void MainWindow::routingStatusLabelMousePress (QMouseEvent * event) protected slot
References event(), and routingStatusLabelMouse().
routingStatusLabelMouseRelease
void MainWindow::routingStatusLabelMouseRelease (QMouseEvent * event) protected slot
References event(), and routingStatusLabelMouse().
routingStatusSlot
void MainWindow::routingStatusSlot (class SketchWidget * sketchWidget, const RoutingStatus & routingStatus) protected slot
References RoutingStatus::m_connectorsLeftToRoute, RoutingStatus::m_jumperItemCount, RoutingStatus::m_netCount, RoutingStatus::m_netRoutedCount, m_routingStatus, and updateTraceMenu().
save
bool MainWindow::save () protected slot
References FritzingWindow::m_fwFilename, and FritzingWindow::save().
saveAs
bool MainWindow::saveAs () protected slot
References FritzingWindow::m_fwFilename, m_schematicGraphicsView, revertAux(), save(), and FritzingWindow::saveAs().
saveAsAux()
bool MainWindow::saveAsAux (const QString & fileName) virtual
Implements FritzingWindow.
References FritzingWindow::fileName(), m_autosaveNeeded, FritzingWindow::m_fwFilename, m_restarting, m_saveAct, FritzingWindow::m_statusBar, FritzingWindow::m_undoStack, saveAsAuxAux(), setCurrentFile(), FritzingWindow::setReadOnly(), and undoStackCleanChanged().
saveAsAuxAux()
void MainWindow::saveAsAuxAux (const QString & fileName) protected
References connectStartSave(), FritzingWindow::fileName(), FritzingSketchExtension(), m_fzzFolder, m_programView, m_sketchModel, saveAsShareable(), and saveLastTabList().
saveAsShareable()
void MainWindow::saveAsShareable (const QString & path, bool saveModel)
References FritzingWindow::alreadyHasExtension(), FritzingBundleExtension(), FritzingSketchExtension(), ModelPart::isCore(), m_fzzFolder, m_pcbGraphicsView, ItemBase::modelPart(), ItemBase::moduleID(), PartFactory::OldSchematicPrefix, and saveBundledNonAtomicEntity().
saveBundledAux
QStringList MainWindow::saveBundledAux (ModelPart * mp, const QDir & destFolder) protected slot
References ViewLayer::BreadboardView, PartFactory::getSvgFilename(), ModelPart::hasBaseNameFor(), ViewLayer::IconView, ModelPart::path(), ViewLayer::PCBView, ViewLayer::SchematicView, FolderUtils::slamCopy(), ZIP_PART, and ZIP_SVG.
saveBundledNonAtomicEntity()
void MainWindow::saveBundledNonAtomicEntity (QString & filename, const QString & extension, Bundler * bundler, const QList< ModelPart * > & partsToSave, bool askForFilename, const QString & destFolderPath, bool saveModel, bool deleteLeftovers)
References FritzingWindow::alreadyHasExtension(), FolderUtils::createFolderAndCdIntoIt(), FolderUtils::createFZAndSaveTo(), FolderUtils::createZipAndSaveTo(), DebugDialog::debug(), defaultSaveFolder(), FritzingWindow::fileName(), FritzingBinExtension(), FritzingBundleExtension(), fritzingBundleExtensions(), FritzingPartExtension(), FritzingSketchExtension(), TextUtils::getRandText(), FolderUtils::getSaveFileName(), LinkedFile::linkedFilename, m_linkedProgramFiles, ProcessEventBlocker::processEvents(), FolderUtils::rmdir(), Bundler::saveAsAux(), saveBundledAux(), and FolderUtils::slamCopy().
saveBundledPart
void MainWindow::saveBundledPart (const QString & moduleId = ___emptyString___) protected slot
References FritzingWindow::alreadyHasExtension(), FolderUtils::createFolderAndCdIntoIt(), FolderUtils::createZipAndSaveTo(), DebugDialog::debug(), defaultSaveFolder(), FritzingBundledPartExtension(), TextUtils::getRandText(), FolderUtils::getSaveFileName(), m_currentGraphicsView, m_referenceModel, ItemBase::modelPart(), ModelPart::moduleID(), FolderUtils::rmdir(), saveBundledAux(), FritzingWindow::setTitle(), ModelPart::title(), and FMessageBox::warning().
saveDocks()
void MainWindow::saveDocks ()
References FDockWidget::saveState().
saveLastTabList()
void MainWindow::saveLastTabList () protected
References currentTabIndex(), FritzingWindow::m_fwFilename, and MaxRecentFiles.
schematicItemMenu()
QMenu * MainWindow::schematicItemMenu () protected virtual
Reimplemented in PEMainWindow.
References createRotateSubmenu(), m_flipHorizontalAct, m_flipVerticalAct, and viewItemMenuAux().
schematicWireMenu()
QMenu * MainWindow::schematicWireMenu () protected virtual
Reimplemented in PEMainWindow.
References changeWireColor(), Wire::colorNames, Wire::colorTrans, createZOrderSubmenu(), m_addBendpointAct, m_createTraceWireAct, m_deleteWireAct, m_deleteWireMinusAct, m_excludeFromAutorouteWireAct, m_infoViewOnHoverAction, m_schematicWireColorMenu, and updateWireMenu().
selectAll
void MainWindow::selectAll () protected slot
References m_currentGraphicsView.
selectAllCopperFill
void MainWindow::selectAllCopperFill () protected slot
References ModelPart::CopperFill, and m_pcbGraphicsView.
selectAllExcludedTraces
void MainWindow::selectAllExcludedTraces () protected slot
References m_currentGraphicsView, and PCBSketchWidget::selectAllExcludedTraces().
selectAllIncludedTraces
void MainWindow::selectAllIncludedTraces () protected slot
References m_currentGraphicsView, and PCBSketchWidget::selectAllIncludedTraces().
selectAllJumperItems
void MainWindow::selectAllJumperItems () protected slot
References ModelPart::Jumper, and m_pcbGraphicsView.
selectAllObsolete() [1/2]
QList< ItemBase * > MainWindow::selectAllObsolete (bool displayFeedback)
References checkSwapObsolete(), and m_pcbGraphicsView.
selectAllObsolete [2/2]
void MainWindow::selectAllObsolete () slot
selectAllTraces
void MainWindow::selectAllTraces () protected slot
References m_currentGraphicsView.
selectAllVias
void MainWindow::selectAllVias () protected slot
References m_pcbGraphicsView, and ModelPart::Via.
selectedModuleID()
const QString & MainWindow::selectedModuleID ()
References ___emptyString___, and m_currentGraphicsView.
selectMoveLock
void MainWindow::selectMoveLock () protected slot
References m_currentGraphicsView.
selectPartsWithModuleID()
void MainWindow::selectPartsWithModuleID (ModelPart * modelPart)
References m_currentGraphicsView.
sendBackward
void MainWindow::sendBackward () protected slot
References m_currentGraphicsView.
sendToBack
void MainWindow::sendToBack () protected slot
References m_currentGraphicsView.
setActionsIcons()
void MainWindow::setActionsIcons (int index, QList< QAction * > & actions) protected
setActiveConnectorItem
void MainWindow::setActiveConnectorItem (class ConnectorItem * connectorItem) protected slot
References m_activeConnectorItem.
setActiveWire
void MainWindow::setActiveWire (class Wire * wire) protected slot
References m_activeWire.
setAutosave()
void MainWindow::setAutosave (int minutes, bool enabled) static protected
References AutosaveEnabled, AutosaveTimeoutMinutes, and m_autosaveTimer.
setAutosaveEnabled()
void MainWindow::setAutosaveEnabled (bool enabled) static
References AutosaveTimeoutMinutes, and setAutosave().
setAutosavePeriod()
void MainWindow::setAutosavePeriod (int minutes) static
References AutosaveEnabled, and setAutosave().
setBackgroundColor
void MainWindow::setBackgroundColor () protected slot
References SetColorDialog::isPrefsColor(), m_currentGraphicsView, and SetColorDialog::selectedColor().
setCloseSilently()
void MainWindow::setCloseSilently (bool cs)
References m_closeSilently.
setCurrentFile()
void MainWindow::setCurrentFile (const QString & fileName, bool addToRecent, bool setAsLastOpened)
References m_convertedSchematic, m_schematicGraphicsView, m_useOldSchematic, MaxRecentFiles, setCurrentTabIndex(), FritzingWindow::setFileName(), FritzingWindow::setTitle(), updateRaiseWindowAction(), updateRecentFileActions(), and updateWelcomeViewRecentList().
setCurrentTabIndex()
void MainWindow::setCurrentTabIndex (int index) protected virtual
Reimplemented in PEMainWindow.
References m_tabWidget.
setCurrentView()
void MainWindow::setCurrentView (ViewLayer::ViewID viewID)
References ViewLayer::BreadboardView, ViewLayer::PCBView, ViewLayer::SchematicView, showBreadboardView(), showPCBView(), and showSchematicView().
setFileProgressPath()
void MainWindow::setFileProgressPath (const QString & path)
References m_fileProgressDialog.
setFireQuoteDelay()
void MainWindow::setFireQuoteDelay (int delay)
References m_fireQuoteDelay.
setGridSize
void MainWindow::setGridSize () protected slot
References createGridSizeForm(), and m_currentGraphicsView.
setGroundFillKeepout
void MainWindow::setGroundFillKeepout () slot
References m_pcbGraphicsView.
setGroundFillSeeds
void MainWindow::setGroundFillSeeds () slot
References m_pcbGraphicsView.
setInfoViewOnHover
void MainWindow::setInfoViewOnHover (bool infoViewOnHover) protected slot
References m_binManager, m_breadboardGraphicsView, m_pcbGraphicsView, and m_schematicGraphicsView.
setInitialTab()
void MainWindow::setInitialTab (int tab)
References m_initialTab.
setInitialView()
void MainWindow::setInitialView () protected virtual
Reimplemented in PEMainWindow.
References m_initialTab, setCurrentTabIndex(), and tabWidget_currentChanged().
setOneGroundFillSeed
void MainWindow::setOneGroundFillSeed () slot
References GroundFillSeedCommand::addItem(), NonConnectorItem::attachedToID(), ConnectorItemAction::connectorItem(), ConnectorItem::connectorSharedID(), m_pcbGraphicsView, FritzingWindow::m_undoStack, and WaitPushUndoStack::push().
setReportMissingModules()
void MainWindow::setReportMissingModules (bool b)
References m_sketchModel.
setSticky
void MainWindow::setSticky () protected slot
References ItemBase::isBaseSticky(), ItemBase::isLocalSticky(), m_currentGraphicsView, and ItemBase::setLocalSticky().
setViewFromAbove
void MainWindow::setViewFromAbove () protected slot
References m_pcbGraphicsView, and updateActiveLayerButtons().
setViewFromBelow
void MainWindow::setViewFromBelow () protected slot
References m_pcbGraphicsView, and updateActiveLayerButtons().
setViewFromBelowToggle
void MainWindow::setViewFromBelowToggle () protected slot
References m_pcbGraphicsView, m_viewFromBelowToggleAct, and updateActiveLayerButtons().
shareOnline
void MainWindow::shareOnline () protected slot
showAllLayers
void MainWindow::showAllLayers () protected slot
References m_currentGraphicsView, and updateLayerMenu().
showBreadboardView
void MainWindow::showBreadboardView () protected slot
References m_welcomeView, and setCurrentTabIndex().
showFileProgressDialog()
void MainWindow::showFileProgressDialog (const QString & path)
References FritzingWindow::fileName(), m_fileProgressDialog, and setFileProgressPath().
showGrid
void MainWindow::showGrid () protected slot
References m_currentGraphicsView, and m_showGridAct.
showPartLabels
void MainWindow::showPartLabels () protected slot
References m_currentGraphicsView, and m_showPartLabelAct.
showPartsBinIconView
void MainWindow::showPartsBinIconView () protected slot
References m_binManager.
showPartsBinListView
void MainWindow::showPartsBinListView () protected slot
References m_binManager.
showPCBView
void MainWindow::showPCBView () slot
References m_welcomeView, and setCurrentTabIndex().
showProgramView
void MainWindow::showProgramView () protected slot
References m_welcomeView, and setCurrentTabIndex().
showSchematicView
void MainWindow::showSchematicView () protected slot
References m_welcomeView, and setCurrentTabIndex().
showStatusMessage
void MainWindow::showStatusMessage (const QString & message) slot
References FritzingWindow::m_statusBar.
showUnrouted
void MainWindow::showUnrouted () protected slot
References m_currentGraphicsView.
showWelcomeView
void MainWindow::showWelcomeView () slot
References setCurrentTabIndex().
sizeGrip()
QSizeGrip * MainWindow::sizeGrip ()
References m_sizeGrip.
sketchWidgets()
QList< SketchWidget * > MainWindow::sketchWidgets ()
References m_breadboardGraphicsView, m_pcbGraphicsView, and m_schematicGraphicsView.
startSaveInstancesSlot
void MainWindow::startSaveInstancesSlot (const QString & fileName, ModelPart * , QXmlStreamWriter & streamWriter) protected slot
References SketchWidget::alignedToGrid(), autorouterSettings(), SketchWidget::background(), FritzingWindow::fileName(), SketchWidget::getAutorouterSettings(), SketchWidget::gridSizeText(), ItemBase::instanceTitle(), LinkedFile::linkedFilename, m_backingUp, m_breadboardGraphicsView, FritzingWindow::m_fwFilename, m_linkedProgramFiles, m_pcbGraphicsView, m_schematicGraphicsView, ItemBase::moduleID(), LinkedFile::platform, SketchWidget::showingGrid(), GraphicsUtils::SVGDPI, ItemBase::title(), ZoomableGraphicsView::viewFromBelow(), SketchWidget::viewID(), and ViewLayer::viewIDXmlName().
statusMessage
void MainWindow::statusMessage (QString message, int timeout) slot
References realStatusBar().
subSwapSlot
void MainWindow::subSwapSlot (SketchWidget * sketchWidget, ItemBase * itemBase, const QString & newModuleID, ViewLayer::ViewLayerPlacement viewLayerPlacement, long & newID, QUndoCommand * parentCommand) protected slot
References swapSelectedAuxAux().
svgMissingLayer()
void MainWindow::svgMissingLayer (const QString & layername, const QString & path) protected
swapBoardImageSlot
void MainWindow::swapBoardImageSlot (SketchWidget * sketchWidget, ItemBase * itemBase, const QString & filename, const QString & moduleID, bool addName) slot
References FritzingWindow::m_undoStack, SketchWidget::PropChangeDelay, swapSelectedAuxAux(), ItemBase::viewLayerPlacement(), and WaitPushUndoStack::waitPush().
swapLayers()
void MainWindow::swapLayers (ItemBase * itemBase, int layers, const QString & msg, int delay)
References layers(), m_breadboardGraphicsView, m_pcbGraphicsView, FritzingWindow::m_undoStack, CleanUpWiresCommand::UndoOnly, and WaitPushUndoStack::waitPush().
swapObsolete() [1/2]
void MainWindow::swapObsolete (bool displayFeedback, QList< ItemBase * > & items)
References ModuleIDNames::ColorLEDModuleIDName, DebugDialog::debug(), findReplacedby(), FMessageBox::information(), ItemBase::isObsolete(), ItemBase::layerKinChief(), m_currentGraphicsView, FritzingWindow::m_fwFilename, m_pcbGraphicsView, FritzingWindow::m_undoStack, ItemBase::modelPart(), ModelPart::moduleID(), ModelPart::properties(), WaitPushUndoStack::push(), swapSelectedAuxAux(), ItemBase::title(), and ItemBase::viewLayerPlacement().
swapObsolete [2/2]
void MainWindow::swapObsolete () slot
swapSelectedAux()
void MainWindow::swapSelectedAux (ItemBase * itemBase, const QString & moduleID, bool useViewLayerPlacement, ViewLayer::ViewLayerPlacement overrideViewLayerPlacement, QMap< QString, QString > & propsMap)
References ModelPart::flippedSMD(), ItemBase::instanceTitle(), ModelPart::itemType(), m_breadboardGraphicsView, m_pcbGraphicsView, m_referenceModel, FritzingWindow::m_undoStack, ViewLayer::NewBottom, ModelPart::Part, SketchWidget::PropChangeDelay, swapSelectedAuxAux(), CleanUpWiresCommand::UndoOnly, ItemBase::viewLayerPlacement(), and WaitPushUndoStack::waitPush().
swapSelectedAuxAux()
long MainWindow::swapSelectedAuxAux (ItemBase * itemBase, const QString & moduleID, ViewLayer::ViewLayerPlacement viewLayerPlacement, QMap< QString, QString > & propsMap, QUndoCommand * parentCommand) protected
References SwapThing::bbView, SwapThing::firstTime, SwapThing::itemBase, m_breadboardGraphicsView, m_pcbGraphicsView, m_schematicGraphicsView, SwapThing::newModelIndex, SwapThing::newModuleID, ModelPart::nextIndex(), SwapThing::parentCommand, ViewLayer::PCBView, SwapThing::propsMap, ViewLayer::SchematicView, sketchWidgets(), ItemBase::viewID(), and SwapThing::viewLayerPlacement.
swapSelectedDelay
void MainWindow::swapSelectedDelay (const QString & family, const QString & prop, QMap< QString, QString > & currPropsMap, ItemBase * itemBase) protected slot
References m_swapTimer, and SwapTimer::setAll().
swapSelectedMap
void MainWindow::swapSelectedMap (const QString & family, const QString & prop, QMap< QString, QString > & currPropsMap, ItemBase * itemBase) protected slot
References Board::convertToXmlName(), ModelPart::flippedSMD(), Perfboard::genModuleID(), Stripboard::genModuleID(), ItemBase::itemType(), ItemBase::layerKinChief(), m_currentGraphicsView, m_pcbGraphicsView, m_referenceModel, ItemBase::modelPart(), ItemBase::moduleID(), ViewLayer::NewBottom, ViewLayer::NewTop, ModelPart::Part, ViewLayer::PCBView, AutoCloseMessageBox::showMessage(), swapSelectedAux(), swapSpecial(), ItemBase::TranslatedPropertyNames, ViewLayer::UnknownPlacement, ModelPart::viewItem(), ItemBase::viewLayerPlacement(), and ModelPart::Wire.
swapSelectedTimeout
void MainWindow::swapSelectedTimeout () protected slot
References SwapTimer::family(), SwapTimer::itemBase(), m_swapTimer, SwapTimer::prop(), SwapTimer::propsMap(), and swapSelectedMap().
swapSpecial()
bool MainWindow::swapSpecial (const QString & prop, QMap< QString, QString > & currPropsMap) protected
References Board::isBoard(), layers(), m_currentGraphicsView, m_infoView, Board::OneLayerTranslated, SketchWidget::PropChangeDelay, swapLayers(), and Board::TwoLayersTranslated.
tabWidget_currentChanged
void MainWindow::tabWidget_currentChanged (int index) protected virtual slot
References SketchAreaWidget::addStatusBar(), SketchAreaWidget::contentView(), currentTabWidget(), hideShowProgramMenu(), hideShowTraceMenu(), initZoom(), m_breadboardGraphicsView, m_currentGraphicsView, m_currentWidget, m_firstTimeHelpAct, m_infoView, m_locationLabel, m_pcbGraphicsView, m_programView, m_schematicGraphicsView, m_showBreadboardAct, m_showPCBAct, m_showProgramAct, m_showSchematicAct, m_showWelcomeAct, FritzingWindow::m_statusBar, m_welcomeView, m_zoomSlider, setActionsIcons(), FritzingWindow::setTitle(), FirstTimeHelpDialog::setViewID(), showStatusMessage(), updateActiveLayerButtons(), updateEditMenu(), updateLayerMenu(), updateTraceMenu(), and updateTransformationActions().
testConnectors
void MainWindow::testConnectors () protected slot
References m_currentGraphicsView.
throwFakeException
void MainWindow::throwFakeException () protected slot
tidyWires
void MainWindow::tidyWires () protected slot
References m_currentGraphicsView.
tipsAndTricks
void MainWindow::tipsAndTricks () protected slot
References TipsAndTricks::showTipsAndTricks().
toggleActiveLayer
void MainWindow::toggleActiveLayer () protected slot
References activeLayerBoth(), activeLayerBottom(), activeLayerIndex(), activeLayerTop(), and m_currentGraphicsView.
toggleDebuggerOutput
void MainWindow::toggleDebuggerOutput (bool toggle) protected slot
References DebugDialog::showDebug().
toggleInfo
void MainWindow::toggleInfo (bool toggle) protected slot
References m_infoView.
togglePartLibrary
void MainWindow::togglePartLibrary (bool toggle) protected slot
References m_binManager.
toggleToolbar
void MainWindow::toggleToolbar (bool toggle) protected slot
toggleUndoHistory
void MainWindow::toggleUndoHistory (bool toggle) protected slot
References m_undoView.
undoStackCleanChanged
void MainWindow::undoStackCleanChanged (bool isClean) protected slot
delete the backup file when the undostack is clean.
References m_backupFileNameAndPath.
undoStackIsEmpty()
bool MainWindow::undoStackIsEmpty () protected
References FritzingWindow::m_undoStack.
untitledFileCount()
int & MainWindow::untitledFileCount () protected virtual
Implements FritzingWindow.
References UntitledSketchIndex.
untitledFileName()
const QString MainWindow::untitledFileName () protected virtual
Implements FritzingWindow.
References UntitledSketchName.
updateActiveLayerButtons()
void MainWindow::updateActiveLayerButtons () protected
References activeLayerIndex(), m_activeLayerBothAct, m_activeLayerBottomAct, m_activeLayerButtonWidget, m_activeLayerTopAct, m_pcbGraphicsView, m_viewFromAboveAct, m_viewFromBelowAct, m_viewFromBelowToggleAct, m_viewFromButtonWidget, and setActionsIcons().
updateEditMenu
void MainWindow::updateEditMenu () protected virtual slot
References m_copyAct, m_currentGraphicsView, m_cutAct, m_deleteAct, m_deleteMinusAct, m_duplicateAct, m_editMenu, m_pasteAct, m_pasteInPlaceAct, and m_preferencesAct.
updateExportMenu
void MainWindow::updateExportMenu () virtual slot
References m_currentGraphicsView, and m_exportMenu.
updateFileMenu
void MainWindow::updateFileMenu () virtual slot
Reimplemented in PEMainWindow.
References m_currentGraphicsView, m_currentWidget, m_orderFabAct, m_printAct, m_programView, m_revertAct, FritzingWindow::m_undoStack, and updateRecentFileActions().
updateItemMenu
void MainWindow::updateItemMenu () protected slot
References NonConnectorItem::attachedToItemType(), ItemBase::canEditPart(), ModelPart::CopperFill, ItemBase::extractTopLevelItemBase(), ModelPart::isCore(), ConnectorItem::isGroundFillSeed(), m_activeConnectorItem, m_currentGraphicsView, m_disconnectAllAct, m_saveBundledPart, m_setOneGroundFillSeedAct, ItemBase::modelPart(), ItemBase::rightClickedConnector(), and ConnectorItemAction::setConnectorItem().
updateLayerMenu
void MainWindow::updateLayerMenu (bool resetLayout = false) protected virtual slot
References ViewLayer::action(), DebugDialog::debug(), m_100PercentSizeAct, m_actualSizeAct, m_alignToGridAct, m_binManager, m_breadboardGraphicsView, m_colorWiresByLengthAct, m_currentGraphicsView, m_fitInWindowAct, m_hideAllLayersAct, m_layerPalette, m_numFixedActionsInViewMenu, m_setBackgroundColorAct, m_setGridSizeAct, m_showAllLayersAct, m_showGridAct, m_showPartsBinIconViewAct, m_showPartsBinListViewAct, m_viewMenu, m_zoomInAct, m_zoomInShortcut, m_zoomOutAct, ViewLayer::parentLayer(), removeActionsStartingAt(), and setActionsIcons().
updateLayerMenuSlot
void MainWindow::updateLayerMenuSlot () protected slot
References updateLayerMenu().
updatePartMenu
void MainWindow::updatePartMenu () protected slot
References NonConnectorItem::attachedTo(), ItemBase::canEditPart(), ConnectorItem::connectedToItems(), Via::connectorItem(), enableAddBendpointAct(), ConnectorItem::getCrossLayerConnectorItem(), ItemBase::getRatsnest(), ItemCount::hasLabelCount, ItemBase::isBaseSticky(), ItemBase::isLocalSticky(), Wire::isTraceType(), ItemCount::itemsCount, ItemBase::layerHidden(), ItemBase::layerKin(), ItemBase::layerKinChief(), m_alignBottomAct, m_alignHorizontalCenterAct, m_alignLeftAct, m_alignRightAct, m_alignTopAct, m_alignVerticalCenterAct, m_bringForwardAct, m_bringToFrontAct, m_convertToBendpointAct, m_convertToBendpointSeparator, m_currentGraphicsView, m_findPartInSketchAct, m_flipHorizontalAct, m_flipVerticalAct, m_hidePartSilkscreenAct, m_moveLockAct, m_openInPartsEditorNewAct, m_openProgramWindowAct, m_partMenu, m_pcbGraphicsView, m_regeneratePartsDatabaseAct, m_rotate180Act, m_rotate45ccwAct, m_rotate45cwAct, m_rotate90ccwAct, m_rotate90cwAct, m_selectAllObsoleteAct, m_selectMoveLockAct, m_sendBackwardAct, m_sendToBackAct, m_showPartLabelAct, m_stickyAct, m_swapObsoleteAct, ItemCount::moveLockCount, ItemCount::obsoleteCount, ItemCount::sel45Rotatable, ItemCount::selCount, ItemCount::selHFlipable, ItemCount::selRotatable, ItemCount::selVFlipable, ViewLayer::Silkscreen0, ViewLayer::Silkscreen1, updateEditMenu(), updateItemMenu(), ItemBase::viewLayerID(), ItemCount::visLabelCount, and ItemCount::wireCount.
updateParts()
bool MainWindow::updateParts (const QString & moduleID, QUndoCommand * parentCommand)
References ItemBase::layerKinChief(), m_currentGraphicsView, ItemBase::moduleID(), swapSelectedAuxAux(), and ItemBase::viewLayerPlacement().
updatePartsBin()
void MainWindow::updatePartsBin (const QString & moduleID)
References m_binManager.
updatePCBTraceMenu()
void MainWindow::updatePCBTraceMenu (QGraphicsItem * item, TraceMenuThing & traceMenuThing) protected
References TraceMenuThing::boardCount, TraceMenuThing::boardSelectedCount, ModelPart::CopperFill, TraceMenuThing::exChecked, TraceMenuThing::exEnabled, TraceMenuThing::gfrEnabled, TraceMenuThing::gfsEnabled, ItemBase::hasConnectors(), Board::isBoard(), ItemBase::isEverVisible(), ItemBase::itemType(), TraceMenuThing::jiEnabled, ModelPart::Jumper, ItemBase::layerKinChief(), ModelPart::Via, and TraceMenuThing::viaEnabled.
updateRaiseWindowAction()
void MainWindow::updateRaiseWindowAction () protected virtual
Reimplemented in PEMainWindow.
References FritzingWindow::m_fwFilename, and m_raiseWindowAct.
updateRecentFileActions
void MainWindow::updateRecentFileActions () protected slot
References m_openRecentFileActs, m_openRecentFileMenu, and MaxRecentFiles.
updateRoutingStatus
void MainWindow::updateRoutingStatus () protected slot
References m_currentGraphicsView, and RoutingStatus::zero().
updateTraceMenu
void MainWindow::updateTraceMenu () slot
References TraceMenuThing::boardCount, Wire::canSwitchLayers(), ViewLayer::Copper0, ViewLayer::Copper1, TraceMenuThing::exChecked, TraceMenuThing::exEnabled, Wire::getAutoroutable(), ItemBase::getRatsnest(), TraceMenuThing::gfrEnabled, TraceMenuThing::gfsEnabled, ItemBase::isEverVisible(), Wire::isTraceType(), TraceMenuThing::jiEnabled, m_autorouterSettingsAct, m_changeTraceLayerAct, m_checkLoadedTracesAct, m_clearGroundFillSeedsAct, m_copperFillAct, m_currentGraphicsView, m_excludeFromAutorouteAct, m_fabQuoteAct, m_groundFillAct, m_newDesignRulesCheckAct, m_orderFabAct, m_pcbGraphicsView, m_pcbTraceMenu, m_removeGroundFillAct, m_selectAllCopperFillAct, m_selectAllExcludedTracesAct, m_selectAllIncludedTracesAct, m_selectAllJumperItemsAct, m_selectAllTracesAct, m_selectAllViasAct, m_selectAllWiresAct, m_setGroundFillSeedsAct, m_showUnroutedAct, m_tidyWiresAct, m_updateRoutingStatusAct, updatePCBTraceMenu(), and TraceMenuThing::viaEnabled.
updateTransformationActions
void MainWindow::updateTransformationActions () protected slot
References m_currentGraphicsView, m_flipButtons, m_flipHorizontalAct, m_flipVerticalAct, m_pcbGraphicsView, m_rotate180Act, m_rotate45ccwAct, m_rotate45cwAct, m_rotate90ccwAct, m_rotate90cwAct, m_rotateButtons, ItemCount::sel45Rotatable, ItemCount::selHFlipable, ItemCount::selRotatable, and ItemCount::selVFlipable.
updateViewZoom
void MainWindow::updateViewZoom (double newZoom) protected slot
References m_comboboxChanged, and m_currentGraphicsView.
updateWelcomeViewRecentList
void MainWindow::updateWelcomeViewRecentList (bool doEmit = true) protected slot
References m_welcomeView, WelcomeView::updateRecent(), and updateWelcomeViewRecentList().
updateWindowMenu
void MainWindow::updateWindowMenu () protected virtual slot
References m_raiseWindowAct, m_toggleDebuggerOutputAct, m_windowMenu, raiseWindowAction(), and DebugDialog::visible().
updateWireMenu
void MainWindow::updateWireMenu () protected virtual slot
References Wire::canSwitchLayers(), Wire::colorString(), enableAddBendpointAct(), Wire::findTraced(), Wire::getAutoroutable(), ItemBase::getRatsnest(), Wire::getTrace(), m_activeWire, m_breadboardGraphicsView, m_breadboardWireColorMenu, m_bringForwardWireAct, m_bringToFrontWireAct, m_changeTraceLayerAct, m_changeTraceLayerWireAct, m_createTraceWireAct, m_createWireWireAct, m_currentGraphicsView, m_deleteWireAct, m_deleteWireMinusAct, m_excludeFromAutorouteWireAct, m_pcbGraphicsView, m_schematicWireColorMenu, m_sendBackwardWireAct, m_sendToBackWireAct, WireAction::setWire(), ViewLayer::topLayers(), and ItemBase::viewLayerID().
updateZoomOptionsNoMatterWhat
void MainWindow::updateZoomOptionsNoMatterWhat (double zoom) protected slot
References m_zoomSlider.
updateZoomSlider
void MainWindow::updateZoomSlider (double zoom) protected slot
References m_zoomSlider.
usesPart()
bool MainWindow::usesPart (const QString & moduleID)
References m_currentGraphicsView, and ItemBase::moduleID().
viewItemMenuAux()
QMenu * MainWindow::viewItemMenuAux (QMenu * menu) protected
References createAddToBinSubmenu(), createZOrderSubmenu(), m_copyAct, m_deleteAct, m_deleteMinusAct, m_disconnectAllAct, m_duplicateAct, m_exportNormalizedFlattenedSvgAction, m_exportNormalizedSvgAction, m_infoViewOnHoverAction, m_moveLockAct, m_openInPartsEditorNewAct, m_showPartLabelAct, m_stickyAct, m_testConnectorsAction, and updatePartMenu().
visitFritzingDotOrg
void MainWindow::visitFritzingDotOrg () protected slot
whatToDoWithAlienFiles()
bool MainWindow::whatToDoWithAlienFiles () protected
References alienPartsDismissed(), m_alienFiles, m_alienPartsMsg, FritzingWindow::m_fwFilename, and recoverBackupedFiles().
zoomIn
void MainWindow::zoomIn () protected slot
References m_zoomSlider.
zoomOut
void MainWindow::zoomOut () protected slot
References m_zoomSlider.
Member Data Documentation
AutosaveEnabled
bool MainWindow::AutosaveEnabled = true static
AutosaveTimeoutMinutes
int MainWindow::AutosaveTimeoutMinutes = 10 static
BackupFolder
QString MainWindow::BackupFolder static
CascadeFactorX
int MainWindow::CascadeFactorX = 21 static protected
CascadeFactorY
int MainWindow::CascadeFactorY = 19 static protected
DockMinHeight
const int MainWindow::DockMinHeight = 30 static
DockMinWidth
const int MainWindow::DockMinWidth = 130 static
GuidMatcher
QRegExp MainWindow::GuidMatcher = QRegExp("[A-Fa-f0-9]{32}") static protected
m_100PercentSizeAct
QAction* MainWindow::m_100PercentSizeAct = nullptr protected
m_aboutAct
QAction* MainWindow::m_aboutAct = nullptr protected
m_aboutQtAct
QAction* MainWindow::m_aboutQtAct = nullptr protected
m_activeConnectorItem
QPointer<ConnectorItem> MainWindow::m_activeConnectorItem protected
m_activeLayerBothAct
QAction* MainWindow::m_activeLayerBothAct = nullptr protected
m_activeLayerBottomAct
QAction* MainWindow::m_activeLayerBottomAct = nullptr protected
m_activeLayerButtonWidget
QStackedWidget* MainWindow::m_activeLayerButtonWidget = nullptr protected
m_activeLayerTopAct
QAction* MainWindow::m_activeLayerTopAct = nullptr protected
m_activeWire
QPointer<Wire> MainWindow::m_activeWire protected
m_actualSizeAct
QAction* MainWindow::m_actualSizeAct = nullptr protected
m_addBendpointAct
QAction* MainWindow::m_addBendpointAct = nullptr protected
m_addedToTemp
bool MainWindow::m_addedToTemp = false protected
m_addNoteAct
QAction* MainWindow::m_addNoteAct = nullptr protected
m_addToBinMenu
QMenu* MainWindow::m_addToBinMenu = nullptr protected
m_alienFiles
QStringList MainWindow::m_alienFiles protected
m_alienPartsMsg
QString MainWindow::m_alienPartsMsg protected
m_alignBottomAct
QAction* MainWindow::m_alignBottomAct = nullptr protected
m_alignHorizontalCenterAct
QAction* MainWindow::m_alignHorizontalCenterAct = nullptr protected
m_alignLeftAct
QAction* MainWindow::m_alignLeftAct = nullptr protected
m_alignMenu
QMenu* MainWindow::m_alignMenu = nullptr protected
m_alignRightAct
QAction* MainWindow::m_alignRightAct = nullptr protected
m_alignToGridAct
QAction* MainWindow::m_alignToGridAct = nullptr protected
m_alignTopAct
QAction* MainWindow::m_alignTopAct = nullptr protected
m_alignVerticalCenterAct
QAction* MainWindow::m_alignVerticalCenterAct = nullptr protected
m_autorouterSettingsAct
QAction* MainWindow::m_autorouterSettingsAct = nullptr protected
m_autosaveNeeded
bool MainWindow::m_autosaveNeeded = false protected
m_autosaveTimer
QTimer MainWindow::m_autosaveTimer protected
m_backingUp
bool MainWindow::m_backingUp = false protected
m_backupFileNameAndPath
QString MainWindow::m_backupFileNameAndPath protected
m_binManager
QPointer<class BinManager> MainWindow::m_binManager protected
m_bottomDock
FDockWidget* MainWindow::m_bottomDock = nullptr protected
m_breadboardGraphicsView
QPointer<class BreadboardSketchWidget> MainWindow::m_breadboardGraphicsView protected
m_breadboardTraceMenu
QMenu* MainWindow::m_breadboardTraceMenu = nullptr protected
m_breadboardWidget
QPointer<SketchAreaWidget> MainWindow::m_breadboardWidget protected
m_breadboardWireColorMenu
QMenu* MainWindow::m_breadboardWireColorMenu = nullptr protected
m_bringForwardAct
QAction* MainWindow::m_bringForwardAct = nullptr protected
m_bringForwardWireAct
class WireAction* MainWindow::m_bringForwardWireAct = nullptr protected
m_bringToFrontAct
QAction* MainWindow::m_bringToFrontAct = nullptr protected
m_bringToFrontWireAct
class WireAction* MainWindow::m_bringToFrontWireAct = nullptr protected
m_bundledSketchName
QString MainWindow::m_bundledSketchName protected
m_changeTraceLayerAct
QAction* MainWindow::m_changeTraceLayerAct = nullptr protected
m_changeTraceLayerWireAct
class WireAction* MainWindow::m_changeTraceLayerWireAct = nullptr protected
m_checkForUpdatesAct
QAction* MainWindow::m_checkForUpdatesAct = nullptr protected
m_checkLoadedTracesAct
QAction* MainWindow::m_checkLoadedTracesAct = nullptr protected
m_clearGroundFillSeedsAct
QAction* MainWindow::m_clearGroundFillSeedsAct = nullptr protected
m_closeSilently
bool MainWindow::m_closeSilently = false protected
m_closing
bool MainWindow::m_closing = false protected
m_colorWiresByLengthAct
QAction* MainWindow::m_colorWiresByLengthAct = nullptr protected
m_comboboxChanged
bool MainWindow::m_comboboxChanged = false protected
m_convertedSchematic
bool MainWindow::m_convertedSchematic = false protected
m_convertToBendpointAct
QAction* MainWindow::m_convertToBendpointAct = nullptr protected
m_convertToBendpointSeparator
QAction* MainWindow::m_convertToBendpointSeparator = nullptr protected
m_convertToViaAct
QAction* MainWindow::m_convertToViaAct = nullptr protected
m_copperFillAct
QAction* MainWindow::m_copperFillAct = nullptr protected
m_copyAct
QAction* MainWindow::m_copyAct = nullptr protected
m_createJumperAct
QAction* MainWindow::m_createJumperAct = nullptr protected
m_createTraceWireAct
class WireAction* MainWindow::m_createTraceWireAct = nullptr protected
m_createWireWireAct
class WireAction* MainWindow::m_createWireWireAct = nullptr protected
m_currentGraphicsView
QPointer<SketchWidget> MainWindow::m_currentGraphicsView protected
m_currentWidget
QPointer<SketchAreaWidget> MainWindow::m_currentWidget protected
m_cutAct
QAction* MainWindow::m_cutAct = nullptr protected
m_deleteAct
QAction* MainWindow::m_deleteAct = nullptr protected
m_deleteMinusAct
QAction* MainWindow::m_deleteMinusAct = nullptr protected
m_deleteWireAct
class WireAction* MainWindow::m_deleteWireAct = nullptr protected
m_deleteWireMinusAct
class WireAction* MainWindow::m_deleteWireMinusAct = nullptr protected
m_deselectAct
QAction* MainWindow::m_deselectAct = nullptr protected
m_disconnectAllAct
QAction* MainWindow::m_disconnectAllAct = nullptr protected
m_docks
QList<FDockWidget*> MainWindow::m_docks protected
m_dontClose
bool MainWindow::m_dontClose = false protected
m_dontKeepMargins
bool MainWindow::m_dontKeepMargins = false protected
m_dotIcon
QIcon MainWindow::m_dotIcon protected
m_dumpAllPartsAction
QAction* MainWindow::m_dumpAllPartsAction = nullptr protected
m_duplicateAct
QAction* MainWindow::m_duplicateAct = nullptr protected
m_editMenu
QMenu* MainWindow::m_editMenu = nullptr protected
m_emptyIcon
QIcon MainWindow::m_emptyIcon protected
m_enableDebugAct
QAction* MainWindow::m_enableDebugAct = nullptr protected
m_examplesAct
QAction* MainWindow::m_examplesAct = nullptr protected
m_exceptionAct
QAction* MainWindow::m_exceptionAct = nullptr protected
m_excludeFromAutorouteAct
QAction* MainWindow::m_excludeFromAutorouteAct = nullptr protected
m_excludeFromAutorouteWireAct
class WireAction* MainWindow::m_excludeFromAutorouteWireAct = nullptr protected
m_exportBomAct
QAction* MainWindow::m_exportBomAct = nullptr protected
m_exportEagleAct
QAction* MainWindow::m_exportEagleAct = nullptr protected
m_exportEtchablePdfAct
QAction* MainWindow::m_exportEtchablePdfAct = nullptr protected
m_exportEtchableSvgAct
QAction* MainWindow::m_exportEtchableSvgAct = nullptr protected
m_exportGerberAct
QAction* MainWindow::m_exportGerberAct = nullptr protected
m_exportJpgAct
QAction* MainWindow::m_exportJpgAct = nullptr protected
m_exportMenu
QMenu* MainWindow::m_exportMenu = nullptr protected
m_exportNetlistAct
QAction* MainWindow::m_exportNetlistAct = nullptr protected
m_exportNormalizedFlattenedSvgAction
QAction* MainWindow::m_exportNormalizedFlattenedSvgAction = nullptr protected
m_exportNormalizedSvgAction
QAction* MainWindow::m_exportNormalizedSvgAction = nullptr protected
m_exportPdfAct
QAction* MainWindow::m_exportPdfAct = nullptr protected
m_exportPngAct
QAction* MainWindow::m_exportPngAct = nullptr protected
m_exportSpiceNetlistAct
QAction* MainWindow::m_exportSpiceNetlistAct = nullptr protected
m_exportSvgAct
QAction* MainWindow::m_exportSvgAct = nullptr protected
m_externalProcessOutput
QByteArray MainWindow::m_externalProcessOutput protected
m_fabQuoteAct
QAction* MainWindow::m_fabQuoteAct = nullptr protected
m_fileMenu
QMenu* MainWindow::m_fileMenu = nullptr protected
m_fileProgressDialog
QPointer<class FileProgressDialog> MainWindow::m_fileProgressDialog protected
m_filesReplacedByAlienOnes
QStringList MainWindow::m_filesReplacedByAlienOnes protected
m_findPartInSketchAct
QAction* MainWindow::m_findPartInSketchAct = nullptr protected
m_fireQuoteDelay
int MainWindow::m_fireQuoteDelay = 0 protected
m_fireQuoteTimer
QTimer MainWindow::m_fireQuoteTimer protected
m_firstOpen
bool MainWindow::m_firstOpen = false protected
m_firstTimeHelpAct
QAction* MainWindow::m_firstTimeHelpAct = nullptr protected
m_fitInWindowAct
QAction* MainWindow::m_fitInWindowAct = nullptr protected
m_flattenCurveAct
QAction* MainWindow::m_flattenCurveAct = nullptr protected
m_flipButtons
QList<SketchToolButton*> MainWindow::m_flipButtons protected
m_flipHorizontalAct
QAction* MainWindow::m_flipHorizontalAct = nullptr protected
m_flipVerticalAct
QAction* MainWindow::m_flipVerticalAct = nullptr protected
m_fritzingMenu
QMenu* MainWindow::m_fritzingMenu = nullptr protected
m_fzzFiles
QHash<QString, struct LockedFile *> MainWindow::m_fzzFiles protected
m_fzzFolder
QString MainWindow::m_fzzFolder protected
m_groundFillAct
QAction* MainWindow::m_groundFillAct = nullptr protected
m_helpMenu
QMenu* MainWindow::m_helpMenu = nullptr protected
m_hideAllLayersAct
QAction* MainWindow::m_hideAllLayersAct = nullptr protected
m_hidePartSilkscreenAct
QAction* MainWindow::m_hidePartSilkscreenAct = nullptr protected
m_infoView
QPointer<class HtmlInfoView> MainWindow::m_infoView protected
m_infoViewOnHoverAction
QAction* MainWindow::m_infoViewOnHoverAction = nullptr protected
m_initialTab
int MainWindow::m_initialTab = 0 protected
m_launchExternalProcessAct
QAction* MainWindow::m_launchExternalProcessAct = nullptr protected
m_layerPalette
QPointer<class LayerPalette> MainWindow::m_layerPalette protected
m_linkedProgramFiles
QList<LinkedFile *> MainWindow::m_linkedProgramFiles protected
m_locationLabel
QPointer<QLabel> MainWindow::m_locationLabel protected
m_locationLabelUnits
QString MainWindow::m_locationLabelUnits protected
m_minimizeAct
QAction* MainWindow::m_minimizeAct = nullptr protected
m_moveLockAct
QAction* MainWindow::m_moveLockAct = nullptr protected
m_newAct
QAction* MainWindow::m_newAct = nullptr protected
m_newAutorouteAct
QAction* MainWindow::m_newAutorouteAct = nullptr protected
m_newDesignRulesCheckAct
QAction* MainWindow::m_newDesignRulesCheckAct = nullptr protected
m_noSchematicConversion
bool MainWindow::m_noSchematicConversion = false protected
m_numFixedActionsInViewMenu
int MainWindow::m_numFixedActionsInViewMenu = 0 protected
m_obsoleteSMDOrientation
bool MainWindow::m_obsoleteSMDOrientation = false protected
m_oldBottomDockStyle
QString MainWindow::m_oldBottomDockStyle protected
m_oldTopDockStyle
QString MainWindow::m_oldTopDockStyle protected
m_openAct
QAction* MainWindow::m_openAct = nullptr protected
m_openDonateAct
QAction* MainWindow::m_openDonateAct = nullptr protected
m_openExampleActions
QStringList MainWindow::m_openExampleActions protected
m_openExampleMenu
QMenu* MainWindow::m_openExampleMenu = nullptr protected
m_openHelpAct
QAction* MainWindow::m_openHelpAct = nullptr protected
m_openInPartsEditorNewAct
QAction* MainWindow::m_openInPartsEditorNewAct = nullptr protected
m_openProgramWindowAct
QAction* MainWindow::m_openProgramWindowAct = nullptr protected
m_openRecentFileActs
QAction* MainWindow::m_openRecentFileActs[MaxRecentFiles] = { nullptr } protected
m_openRecentFileMenu
QMenu* MainWindow::m_openRecentFileMenu = nullptr protected
m_orderFabAct
QAction* MainWindow::m_orderFabAct = nullptr protected
m_orderFabButton
QWidget* MainWindow::m_orderFabButton = nullptr protected
m_orderFabEnabled
bool MainWindow::m_orderFabEnabled = false protected
m_pageSetupAct
QAction* MainWindow::m_pageSetupAct = nullptr protected
m_partMenu
QMenu* MainWindow::m_partMenu = nullptr protected
m_partsEditorHelpAct
QAction* MainWindow::m_partsEditorHelpAct = nullptr protected
m_partsRefAct
QAction* MainWindow::m_partsRefAct = nullptr protected
m_pasteAct
QAction* MainWindow::m_pasteAct = nullptr protected
m_pasteInPlaceAct
QAction* MainWindow::m_pasteInPlaceAct = nullptr protected
m_pcbGraphicsView
QPointer<class PCBSketchWidget> MainWindow::m_pcbGraphicsView protected
m_pcbTraceMenu
QMenu* MainWindow::m_pcbTraceMenu = nullptr protected
m_pcbWidget
QPointer<SketchAreaWidget> MainWindow::m_pcbWidget protected
m_preferencesAct
QAction* MainWindow::m_preferencesAct = nullptr protected
m_printAct
QAction* MainWindow::m_printAct = nullptr protected
m_programView
QPointer<class ProgramWindow> MainWindow::m_programView protected
m_programWindow
QPointer<class ProgramWindow> MainWindow::m_programWindow protected
m_quitAct
QAction* MainWindow::m_quitAct = nullptr protected
m_raiseWindowAct
QAction* MainWindow::m_raiseWindowAct = nullptr protected
m_redoAct
QAction* MainWindow::m_redoAct = nullptr protected
m_referenceModel
QPointer<ReferenceModel> MainWindow::m_referenceModel protected
m_regeneratePartsDatabaseAct
QAction* MainWindow::m_regeneratePartsDatabaseAct = nullptr protected
m_removeGroundFillAct
QAction* MainWindow::m_removeGroundFillAct = nullptr protected
m_reportBugAct
QAction* MainWindow::m_reportBugAct = nullptr protected
m_restarting
bool MainWindow::m_restarting = false protected
m_revertAct
QAction* MainWindow::m_revertAct = nullptr protected
m_rolloverQuoteDialog
QPointer<QDialog> MainWindow::m_rolloverQuoteDialog protected
m_rotate180Act
QAction* MainWindow::m_rotate180Act = nullptr protected
m_rotate45ccwAct
QAction* MainWindow::m_rotate45ccwAct = nullptr protected
m_rotate45cwAct
QAction* MainWindow::m_rotate45cwAct = nullptr protected
m_rotate90ccwAct
QAction* MainWindow::m_rotate90ccwAct = nullptr protected
m_rotate90cwAct
QAction* MainWindow::m_rotate90cwAct = nullptr protected
m_rotateButtons
QList<SketchToolButton*> MainWindow::m_rotateButtons protected
m_rotateMenu
QMenu* MainWindow::m_rotateMenu = nullptr protected
m_routingStatus
RoutingStatus MainWindow::m_routingStatus protected
m_saveAct
QAction* MainWindow::m_saveAct = nullptr protected
m_saveAsAct
QAction* MainWindow::m_saveAsAct = nullptr protected
m_saveBundledPart
QAction* MainWindow::m_saveBundledPart = nullptr protected
m_schematicGraphicsView
QPointer<class SchematicSketchWidget> MainWindow::m_schematicGraphicsView protected
m_schematicTraceMenu
QMenu* MainWindow::m_schematicTraceMenu = nullptr protected
m_schematicWidget
QPointer<SketchAreaWidget> MainWindow::m_schematicWidget protected
m_schematicWireColorMenu
QMenu* MainWindow::m_schematicWireColorMenu = nullptr protected
m_selectAllAct
QAction* MainWindow::m_selectAllAct = nullptr protected
m_selectAllCopperFillAct
QAction* MainWindow::m_selectAllCopperFillAct = nullptr protected
m_selectAllExcludedTracesAct
QAction* MainWindow::m_selectAllExcludedTracesAct = nullptr protected
m_selectAllIncludedTracesAct
QAction* MainWindow::m_selectAllIncludedTracesAct = nullptr protected
m_selectAllJumperItemsAct
QAction* MainWindow::m_selectAllJumperItemsAct = nullptr protected
m_selectAllObsoleteAct
QAction* MainWindow::m_selectAllObsoleteAct = nullptr protected
m_selectAllTracesAct
QAction* MainWindow::m_selectAllTracesAct = nullptr protected
m_selectAllViasAct
QAction* MainWindow::m_selectAllViasAct = nullptr protected
m_selectAllWiresAct
QAction* MainWindow::m_selectAllWiresAct = nullptr protected
m_selectMoveLockAct
QAction* MainWindow::m_selectMoveLockAct = nullptr protected
m_sendBackwardAct
QAction* MainWindow::m_sendBackwardAct = nullptr protected
m_sendBackwardWireAct
class WireAction* MainWindow::m_sendBackwardWireAct = nullptr protected
m_sendToBackAct
QAction* MainWindow::m_sendToBackAct = nullptr protected
m_sendToBackWireAct
class WireAction* MainWindow::m_sendToBackWireAct = nullptr protected
m_setBackgroundColorAct
QAction* MainWindow::m_setBackgroundColorAct = nullptr protected
m_setGridSizeAct
QAction* MainWindow::m_setGridSizeAct = nullptr protected
m_setGroundFillKeepoutAct
QAction* MainWindow::m_setGroundFillKeepoutAct = nullptr protected
m_setGroundFillSeedsAct
QAction* MainWindow::m_setGroundFillSeedsAct = nullptr protected
m_setOneGroundFillSeedAct
class ConnectorItemAction* MainWindow::m_setOneGroundFillSeedAct = nullptr protected
m_settingsPrefix
QString MainWindow::m_settingsPrefix protected
m_setUpDockManagerTimer
QTimer MainWindow::m_setUpDockManagerTimer protected
m_shareOnlineAct
QAction* MainWindow::m_shareOnlineAct = nullptr protected
m_showAllLayersAct
QAction* MainWindow::m_showAllLayersAct = nullptr protected
m_showBreadboardAct
QAction* MainWindow::m_showBreadboardAct = nullptr protected
m_showGridAct
QAction* MainWindow::m_showGridAct = nullptr protected
m_showPartLabelAct
QAction* MainWindow::m_showPartLabelAct = nullptr protected
m_showPartsBinIconViewAct
QAction* MainWindow::m_showPartsBinIconViewAct = nullptr protected
m_showPartsBinListViewAct
QAction* MainWindow::m_showPartsBinListViewAct = nullptr protected
m_showPCBAct
QAction* MainWindow::m_showPCBAct = nullptr protected
m_showProgramAct
QAction* MainWindow::m_showProgramAct = nullptr protected
m_showSchematicAct
QAction* MainWindow::m_showSchematicAct = nullptr protected
m_showUnroutedAct
QAction* MainWindow::m_showUnroutedAct = nullptr protected
m_showWelcomeAct
QAction* MainWindow::m_showWelcomeAct = nullptr protected
m_sizeGrip
QPointer<class FSizeGrip> MainWindow::m_sizeGrip protected
m_sketchModel
QPointer<class SketchModel> MainWindow::m_sketchModel protected
m_stickyAct
QAction* MainWindow::m_stickyAct = nullptr protected
m_swapObsoleteAct
QAction* MainWindow::m_swapObsoleteAct = nullptr protected
m_swapTimer
SwapTimer MainWindow::m_swapTimer protected
m_tabWidget
QPointer<QWidget> MainWindow::m_tabWidget protected
m_testConnectorsAction
QAction* MainWindow::m_testConnectorsAction = nullptr protected
m_tidyWiresAct
QAction* MainWindow::m_tidyWiresAct = nullptr protected
m_tipsAndTricksAct
QAction* MainWindow::m_tipsAndTricksAct = nullptr protected
m_toggleDebuggerOutputAct
QAction* MainWindow::m_toggleDebuggerOutputAct = nullptr protected
m_toggleInfoAct
QAction* MainWindow::m_toggleInfoAct = nullptr protected
m_togglePartLibraryAct
QAction* MainWindow::m_togglePartLibraryAct = nullptr protected
m_toggleUndoHistoryAct
QAction* MainWindow::m_toggleUndoHistoryAct = nullptr protected
m_toolbar
QPointer<QToolBar> MainWindow::m_toolbar protected
m_topDock
FDockWidget* MainWindow::m_topDock = nullptr protected
m_undoAct
QAction* MainWindow::m_undoAct = nullptr protected
m_undoGroup
QUndoGroup* MainWindow::m_undoGroup = nullptr protected
m_undoView
QUndoView* MainWindow::m_undoView = nullptr protected
m_updateRoutingStatusAct
QAction* MainWindow::m_updateRoutingStatusAct = nullptr protected
m_useOldSchematic
bool MainWindow::m_useOldSchematic = false protected
m_viewFromAboveAct
QAction* MainWindow::m_viewFromAboveAct = nullptr protected
m_viewFromBelowAct
QAction* MainWindow::m_viewFromBelowAct = nullptr protected
m_viewFromBelowToggleAct
QAction* MainWindow::m_viewFromBelowToggleAct = nullptr protected
m_viewFromButtonWidget
QStackedWidget* MainWindow::m_viewFromButtonWidget = nullptr protected
m_viewMenu
QMenu* MainWindow::m_viewMenu = nullptr protected
m_visitFritzingDotOrgAct
QAction* MainWindow::m_visitFritzingDotOrgAct = nullptr protected
m_welcomeView
class WelcomeView* MainWindow::m_welcomeView = nullptr protected
m_welcomeWidget
QPointer<SketchAreaWidget> MainWindow::m_welcomeWidget protected
m_windowMenu
QMenu* MainWindow::m_windowMenu = nullptr protected
m_windowMenuSeparator
QAction* MainWindow::m_windowMenuSeparator = nullptr protected
m_zoomInAct
QAction* MainWindow::m_zoomInAct = nullptr protected
m_zoomInShortcut
QAction* MainWindow::m_zoomInShortcut = nullptr protected
m_zoomOutAct
QAction* MainWindow::m_zoomOutAct = nullptr protected
m_zoomSlider
QPointer<class ZoomSlider> MainWindow::m_zoomSlider protected
m_zOrderMenu
QMenu* MainWindow::m_zOrderMenu = nullptr protected
m_zOrderWireMenu
QMenu* MainWindow::m_zOrderWireMenu = nullptr protected
UntitledSketchIndex
int MainWindow::UntitledSketchIndex = 1 static protected
UntitledSketchName
const QString MainWindow::UntitledSketchName = "Untitled Sketch" static protected
Property Documentation
fireQuoteDelay
int MainWindow::fireQuoteDelay read write
The documentation for this class was generated from the following files:
mainwindow/mainwindow.h
mainwindow/mainwindow.cpp
mainwindow/mainwindow_dock.cpp
mainwindow/mainwindow_export.cpp
mainwindow/mainwindow_menu.cpp