Fritzing: FServerThread Class Reference
FServerThread Class Reference
#include <fapplication.h>
Signals
void doCommand (const QString &command, const QString &params, QString &result, int &status)
void error (QTcpSocket::SocketError socketError)
Public Member Functions
FServerThread (qintptr socketDescriptor, QObject *parent)
void run ()
void setDone ()
Protected Member Functions
void writeResponse (QTcpSocket *, int code, const QString &codeString, const QString &mimeType, const QString &message)
Protected Attributes
bool m_done = false
int m_socketDescriptor = 0
Static Protected Attributes
static QMutex m_busy
Constructor & Destructor Documentation
FServerThread()
FServerThread::FServerThread (qintptr socketDescriptor, QObject * parent)
Member Function Documentation
doCommand
void FServerThread::doCommand (const QString & command, const QString & params, QString & result, int & status) signal
error
void FServerThread::error (QTcpSocket::SocketError socketError) signal
run()
void FServerThread::run ()
References DebugDialog::debug(), doCommand(), error(), m_busy, m_socketDescriptor, FolderUtils::rmdir(), and writeResponse().
setDone()
void FServerThread::setDone ()
writeResponse()
void FServerThread::writeResponse (QTcpSocket * socket, int code, const QString & codeString, const QString & mimeType, const QString & message) protected
Member Data Documentation
m_busy
QMutex FServerThread::m_busy static protected
m_done
bool FServerThread::m_done = false protected
m_socketDescriptor
int FServerThread::m_socketDescriptor = 0 protected
The documentation for this class was generated from the following files:
fapplication.h
fapplication.cpp