Fritzing: SvgIdLayer Class Reference
SvgIdLayer Class Reference
#include <svgidlayer.h>
Public Member Functions
SvgIdLayer (ViewLayer::ViewID)
SvgIdLayer (const SvgIdLayer &)
SvgIdLayer * copyLayer ()
QPointF point (ViewLayer::ViewLayerPlacement)
bool processed (ViewLayer::ViewLayerPlacement)
QRectF rect (ViewLayer::ViewLayerPlacement)
void setInvisible (ViewLayer::ViewLayerPlacement placement) noexcept
void setPointRect (ViewLayer::ViewLayerPlacement, QPointF, QRectF, bool svgVisible)
void setPointRect (ViewLayer::ViewLayerPlacement, const PointRect &newPointRect)
bool svgVisible (ViewLayer::ViewLayerPlacement)
void unprocess () noexcept
Public Attributes
bool m_hybrid
QString m_legColor
QString m_legId
QLineF m_legLine
double m_legStrokeWidth
bool m_path
double m_radius
double m_strokeWidth
QString m_svgId
ViewLayer::ViewLayerID m_svgViewLayerID
QString m_terminalId
ViewLayer::ViewID m_viewID
Protected Attributes
PointRect m_pointRectBottom
PointRect m_pointRectTop
Constructor & Destructor Documentation
SvgIdLayer() [1/2]
SvgIdLayer::SvgIdLayer (ViewLayer::ViewID viewID)
SvgIdLayer() [2/2]
SvgIdLayer::SvgIdLayer (const SvgIdLayer & other)
Member Function Documentation
copyLayer()
SvgIdLayer * SvgIdLayer::copyLayer ()
References SvgIdLayer().
point()
QPointF SvgIdLayer::point (ViewLayer::ViewLayerPlacement viewLayerPlacement)
References PointRect::getPoint(), m_pointRectBottom, m_pointRectTop, and ViewLayer::NewBottom.
processed()
bool SvgIdLayer::processed (ViewLayer::ViewLayerPlacement viewLayerPlacement)
References PointRect::isProcessed(), m_pointRectBottom, m_pointRectTop, and ViewLayer::NewBottom.
rect()
QRectF SvgIdLayer::rect (ViewLayer::ViewLayerPlacement viewLayerPlacement)
References PointRect::getRect(), m_pointRectBottom, m_pointRectTop, and ViewLayer::NewBottom.
setInvisible()
void SvgIdLayer::setInvisible (ViewLayer::ViewLayerPlacement placement) inline noexcept
References m_pointRectBottom, m_pointRectTop, and PointRect::setInvisible().
setPointRect() [1/2]
void SvgIdLayer::setPointRect (ViewLayer::ViewLayerPlacement viewLayerPlacement, QPointF point, QRectF rect, bool svgVisible)
References point(), rect(), and svgVisible().
setPointRect() [2/2]
void SvgIdLayer::setPointRect (ViewLayer::ViewLayerPlacement viewLayerPlacement, const PointRect & newPointRect)
References m_pointRectBottom, m_pointRectTop, and ViewLayer::NewBottom.
svgVisible()
bool SvgIdLayer::svgVisible (ViewLayer::ViewLayerPlacement viewLayerPlacement)
References PointRect::isSvgVisible(), m_pointRectBottom, m_pointRectTop, and ViewLayer::NewBottom.
unprocess()
void SvgIdLayer::unprocess () noexcept
References m_pointRectBottom, m_pointRectTop, and PointRect::unprocess().
Member Data Documentation
m_hybrid
bool SvgIdLayer::m_hybrid
m_legColor
QString SvgIdLayer::m_legColor
m_legId
QString SvgIdLayer::m_legId
m_legLine
QLineF SvgIdLayer::m_legLine
m_legStrokeWidth
double SvgIdLayer::m_legStrokeWidth
m_path
bool SvgIdLayer::m_path
m_pointRectBottom
PointRect SvgIdLayer::m_pointRectBottom protected
m_pointRectTop
PointRect SvgIdLayer::m_pointRectTop protected
m_radius
double SvgIdLayer::m_radius
m_strokeWidth
double SvgIdLayer::m_strokeWidth
m_svgId
QString SvgIdLayer::m_svgId
m_svgViewLayerID
ViewLayer::ViewLayerID SvgIdLayer::m_svgViewLayerID
m_terminalId
QString SvgIdLayer::m_terminalId
m_viewID
ViewLayer::ViewID SvgIdLayer::m_viewID
The documentation for this class was generated from the following files:
connectors/svgidlayer.h
connectors/svgidlayer.cpp