Fritzing: Highlighter Class Reference
Highlighter Class Reference
#include <highlighter.h>
Public Member Functions
Highlighter (QTextEdit *parent)
~Highlighter ()
void setSyntaxer (class Syntaxer *)
class Syntaxer * syntaxer ()
Static Public Member Functions
static void loadStyles (const QString &filename)
Protected Member Functions
void highlightBlock (const QString &text)
void highlightStrings (int startStringIndex, QString &text)
void highlightTerms (const QString &text)
bool isWordChar (QChar c)
Protected Attributes
QPointer< class Syntaxer > m_syntaxer
Static Protected Attributes
static QHash< QString, QTextCharFormat * > m_styleFormats
Constructor & Destructor Documentation
Highlighter()
Highlighter::Highlighter (QTextEdit * parent)
References m_syntaxer.
~Highlighter()
Highlighter::~Highlighter ()
Member Function Documentation
highlightBlock()
void Highlighter::highlightBlock (const QString & text) protected
References COMMENTOFFSET, highlightStrings(), highlightTerms(), CommentInfo::m_caseSensitive, CommentInfo::m_end, CommentInfo::m_index, CommentInfo::m_multiLine, m_styleFormats, m_syntaxer, and STRINGOFFSET.
highlightStrings()
void Highlighter::highlightStrings (int startStringIndex, QString & text) protected
References CEscapeChar(), m_styleFormats, m_syntaxer, and STRINGOFFSET.
highlightTerms()
void Highlighter::highlightTerms (const QString & text) protected
References Syntaxer::formatFromList(), isWordChar(), m_styleFormats, m_syntaxer, and SyntaxerTrieLeaf::name().
isWordChar()
bool Highlighter::isWordChar (QChar c) protected
loadStyles()
void Highlighter::loadStyles (const QString & filename) static
References m_styleFormats.
setSyntaxer()
void Highlighter::setSyntaxer (class Syntaxer * syntaxer)
References m_syntaxer, and syntaxer().
syntaxer()
Syntaxer * Highlighter::syntaxer ()
References m_syntaxer.
Member Data Documentation
m_styleFormats
QHash< QString, QTextCharFormat * > Highlighter::m_styleFormats static protected
m_syntaxer
QPointer<class Syntaxer> Highlighter::m_syntaxer protected
The documentation for this class was generated from the following files:
program/highlighter.h
program/highlighter.cpp