Fritzing: AboutBox Class Reference
AboutBox Class Reference
#include <aboutbox.h>
Public Slots
void scrollCredits ()
Static Public Member Functions
static void closeAbout ()
static void hideAbout ()
static void initBuildType (const QString &)
static void showAbout ()
Protected Member Functions
void closeEvent (QCloseEvent *event)
void keyPressEvent (QKeyEvent *event)
void show ()
Static Protected Attributes
static QString BuildType
static AboutBox * Singleton = NULL
Private Member Functions
AboutBox (QWidget *parent=0)
void resetScrollAnimation ()
Private Attributes
QTimer * m_autoScrollTimer
class ExpandingLabel * m_expandingLabel
bool m_restartAtTop
QTime m_startTime
Constructor & Destructor Documentation
AboutBox()
AboutBox::AboutBox (QWidget * parent = 0) private
References AboutText, AboutWidth, BuildType, Version::date(), Version::gitVersion(), m_autoScrollTimer, m_expandingLabel, m_restartAtTop, m_startTime, Version::majorVersion(), Version::minorSubVersion(), Version::minorVersion(), Version::modifier(), scrollCredits(), ExpandingLabel::setLabelText(), Singleton, and Version::year().
Member Function Documentation
closeAbout()
void AboutBox::closeAbout () static
References Singleton.
closeEvent()
void AboutBox::closeEvent (QCloseEvent * event) protected
References m_autoScrollTimer.
hideAbout()
void AboutBox::hideAbout () static
References Singleton.
initBuildType()
void AboutBox::initBuildType (const QString & buildType) static
References BuildType.
keyPressEvent()
void AboutBox::keyPressEvent (QKeyEvent * event) protected
References closeAbout().
resetScrollAnimation()
void AboutBox::resetScrollAnimation () private
References m_autoScrollTimer, and m_startTime.
scrollCredits
void AboutBox::scrollCredits () slot
References m_expandingLabel, m_restartAtTop, and m_startTime.
show()
void AboutBox::show () protected
References m_restartAtTop, and resetScrollAnimation().
showAbout()
void AboutBox::showAbout () static
References AboutBox(), m_expandingLabel, show(), and Singleton.
Member Data Documentation
BuildType
QString AboutBox::BuildType static protected
m_autoScrollTimer
QTimer* AboutBox::m_autoScrollTimer private
m_expandingLabel
class ExpandingLabel* AboutBox::m_expandingLabel private
m_restartAtTop
bool AboutBox::m_restartAtTop private
m_startTime
QTime AboutBox::m_startTime private
Singleton
AboutBox * AboutBox::Singleton = NULL static protected
The documentation for this class was generated from the following files:
help/aboutbox.h
help/aboutbox.cpp