Fritzing: GedaElement2Svg Class Reference
GedaElement2Svg Class Reference
#include <gedaelement2svg.h>
Public Member Functions
GedaElement2Svg ()
QString convert (const QString &filename, bool allowPadsAndPins)
Public Member Functions inherited from X2Svg
X2Svg ()
void checkXLimit (double x)
void checkYLimit (double y)
Protected Member Functions
QString convertArc (QVector< QVariant > &stack, int ix, int argCount, bool mils)
QString convertPad (QVector< QVariant > &stack, int ix, int argCount, bool mils, QString &pinID)
QString convertPin (QVector< QVariant > &stack, int ix, int argCount, bool mils, QString &pinID)
int countArgs (QVector< QVariant > &stack, int ix)
void fixQuad (int quad, double &px, double &py)
QString getPinID (QString &number, QString &name, bool isPad)
QString makeCopper (QStringList ids, QHash< QString, QString > &, const QString &filename)
int reflectQuad (int angle, int &quad)
Protected Member Functions inherited from X2Svg
void initLimits ()
QString offsetMin (const QString &svg)
QString unquote (const QString &)
Protected Attributes
int m_nonConnectorNumber = 0
Protected Attributes inherited from X2Svg
QString m_attribute
QString m_comment
double m_maxX
double m_maxY
double m_minX
double m_minY
Constructor & Destructor Documentation
GedaElement2Svg()
GedaElement2Svg::GedaElement2Svg ()
Member Function Documentation
convert()
QString GedaElement2Svg::convert (const QString & filename, bool allowPadsAndPins)
References GedaElementLexer::comments(), convertArc(), convertPad(), convertPin(), countArgs(), TextUtils::escapeAnd(), X2Svg::initLimits(), X2Svg::m_attribute, X2Svg::m_comment, X2Svg::m_maxX, X2Svg::m_maxY, X2Svg::m_minX, X2Svg::m_minY, m_nonConnectorNumber, makeCopper(), TextUtils::makeSVGHeader(), X2Svg::offsetMin(), GedaElementParser::parse(), TextUtils::stripNonValidXMLCharacters(), GedaElementParser::symStack(), X2Svg::unquote(), and Version::versionString().
convertArc()
QString GedaElement2Svg::convertArc (QVector< QVariant > & stack, int ix, int argCount, bool mils) protected
References X2Svg::checkXLimit(), X2Svg::checkYLimit(), fixQuad(), and reflectQuad().
convertPad()
QString GedaElement2Svg::convertPad (QVector< QVariant > & stack, int ix, int argCount, bool mils, QString & pinID) protected
References X2Svg::checkXLimit(), X2Svg::checkYLimit(), ViewLayer::Copper1Color, TextUtils::escapeAnd(), getPinID(), and TextUtils::stripNonValidXMLCharacters().
convertPin()
QString GedaElement2Svg::convertPin (QVector< QVariant > & stack, int ix, int argCount, bool mils, QString & pinID) protected
References X2Svg::checkXLimit(), X2Svg::checkYLimit(), ViewLayer::Copper0Color, TextUtils::escapeAnd(), getPinID(), and TextUtils::stripNonValidXMLCharacters().
countArgs()
int GedaElement2Svg::countArgs (QVector< QVariant > & stack, int ix) protected
fixQuad()
void GedaElement2Svg::fixQuad (int quad, double & px, double & py) protected
getPinID()
QString GedaElement2Svg::getPinID (QString & number, QString & name, bool isPad) protected
References m_nonConnectorNumber, FSvgRenderer::NonConnectorName, and X2Svg::unquote().
makeCopper()
QString GedaElement2Svg::makeCopper (QStringList ids, QHash< QString, QString > & strings, const QString & filename) protected
References DebugDialog::debug().
reflectQuad()
int GedaElement2Svg::reflectQuad (int angle, int & quad) protected
Member Data Documentation
m_nonConnectorNumber
int GedaElement2Svg::m_nonConnectorNumber = 0 protected
The documentation for this class was generated from the following files:
svg/gedaelement2svg.h
svg/gedaelement2svg.cpp