Fritzing: MazeRouter Class Reference
MazeRouter Class Reference
#include <mazerouter.h>
Public Slots
void incCommandProgress ()
void setMaxCycles (int)
Public Slots inherited from Autorouter
virtual void cancel ()
virtual void cancelTrace ()
virtual void setMaxCycles (int)
virtual void stopTracing ()
virtual void useBest ()
Public Member Functions
MazeRouter (class PCBSketchWidget *, QGraphicsItem *board, bool adjustIf)
~MazeRouter ()
void start ()
Public Member Functions inherited from Autorouter
Autorouter (PCBSketchWidget *)
virtual ~Autorouter ()=default
Protected Member Functions
void addConnectionToUndo (ConnectorItem *from, ConnectorItem *to, QUndoCommand *parentCommand)
void addJumperToUndo (JumperItem *, QUndoCommand *parentCommand)
void addNetLabelToUndo (SymbolPaletteItem *netLabel, QUndoCommand *parentCommand)
void addViaToUndo (Via *, QUndoCommand *parentCommand)
void cleanUpNets (NetList &)
void clearExpansion (Grid *grid)
void createTrace (Trace &, QList< GridPoint > &, TraceThing &, ConnectionThing &, Net *)
void createTraces (NetList &netList, Score &bestScore, QUndoCommand *parentCommand)
void displayTrace (Trace &)
void expand (GridPoint &, RouteThing &)
void expandOne (GridPoint &, RouteThing &, int dx, int dy, int dz, bool crossLayer)
void expandOneJ (GridPoint &gridPoint, std::priority_queue< GridPoint > &pq, int dx, int dy, int dz, GridValue targetValue, QPoint targetLocation, QSet< int > &already)
ConnectorItem * findAnchor (GridPoint gp, TraceThing &, Net *net, QPointF &p, bool &onTrace, ConnectorItem *already)
ConnectorItem * findAnchor (GridPoint gp, const QRectF &, TraceThing &, Net *net, QPointF &p, bool &onTrace, ConnectorItem *already)
void findNearestPair (QList< QList< ConnectorItem * > > &subnets, Nearest &)
void findNearestPair (QList< QList< ConnectorItem * > > &subnets, int i, QList< ConnectorItem * > &inet, Nearest &)
int findPinsWithin (QList< ConnectorItem * > *net)
void initTraceDisplay ()
void insertTrace (Trace &newTrace, int netIndex, Score &currentScore, int viaCount, bool incRouted)
GridPoint lookForJumper (GridPoint initial, GridValue targetValue, QPoint targetLocation)
bool makeBoard (QImage *, double keepout, const QRectF &r)
bool makeMasters (QString &)
SymbolPaletteItem * makeNetLabel (GridPoint &center, SymbolPaletteItem *pairedNetLabel, uchar traceFlags)
bool moveBack (Score &currentScore, int index, QList< NetOrdering > &allOrderings)
void optimizeTraces (QList< int > &order, QMultiHash< int, QList< QPointer< TraceWire > > > &, QMultiHash< int, Via * > &, QMultiHash< int, JumperItem * > &, QMultiHash< int, SymbolPaletteItem * > &, NetList &, ConnectionThing &)
void prepSourceAndTarget (QDomDocument *masterdoc, RouteThing &, QList< QList< ConnectorItem * > > &subnets, int z, ViewLayer::ViewLayerPlacement)
void reducePoints (QList< QPointF > &points, QPointF topLeft, QList< TraceWire * > &bundle, int startIndex, int endIndex, ConnectionThing &, int netIndex, ViewLayer::ViewLayerPlacement)
void removeColinear (QList< GridPoint > &gridPoints)
void removeOffBoardAnd (bool isPCBType, bool removeSingletons, bool bothSides)
void removeStep (int ix, QList< GridPoint > &gridPoints)
void removeSteps (QList< GridPoint > &gridPoints)
QList< QPoint > renderSource (QDomDocument *masterDoc, int z, ViewLayer::ViewLayerPlacement, Grid *grid, QList< QDomElement > &netElements, QList< ConnectorItem * > &subnet, GridValue value, bool clearElements, const QRectF &r)
QList< GridPoint > route (RouteThing &, int &viaCount)
void routeJumper (int netIndex, RouteThing &, Score &currentScore)
bool routeNets (NetList &, bool makeJumper, Score &currentScore, const QSizeF gridSize, QList< NetOrdering > &allOrderings)
bool routeNext (bool makeJumper, RouteThing &, QList< QList< ConnectorItem * > > &subnets, Score &currentScore, int netIndex, QList< NetOrdering > &allOrderings)
bool routeOne (bool makeJumper, Score &currentScore, int netIndex, RouteThing &, QList< NetOrdering > &allOrderings)
void setUpWidths (double width)
void traceAvoids (QList< Trace > &traces, int netIndex, RouteThing &routeThing)
QList< GridPoint > traceBack (GridPoint, Grid *, int &viaCount, GridValue sourceValue, GridValue targetValue)
GridPoint traceBackOne (GridPoint &, Grid *, int dx, int dy, int dz, GridValue sourceValue, GridValue targetValue)
void traceObstacles (QList< Trace > &traces, int netIndex, Grid *grid, int ikeepout)
void updateDisplay (int iz)
void updateDisplay (Grid *, int iz)
void updateDisplay (GridPoint &)
bool viaWillFit (GridPoint &, Grid *grid)
Protected Member Functions inherited from Autorouter
void addToUndo (QUndoCommand *parentCommand)
void addUndoConnection (bool connect, SymbolPaletteItem *, QUndoCommand *parentCommand)
void addUndoConnection (bool connect, JumperItem *, QUndoCommand *parentCommand)
void addUndoConnection (bool connect, Via *, QUndoCommand *parentCommand)
void addUndoConnection (bool connect, TraceWire *, QUndoCommand *parentCommand)
void addUndoConnection (bool connect, ConnectorItem *, BaseCommand::CrossViewType, QUndoCommand *parentCommand)
void addWireToUndo (Wire *wire, QUndoCommand *parentCommand)
virtual void cleanUpNets ()
void clearTracesAndJumpers ()
void doCancel (QUndoCommand *parentCommand)
virtual class TraceWire * drawOneTrace (QPointF fromPos, QPointF toPos, double width, ViewLayer::ViewLayerPlacement)
void initUndo (QUndoCommand *parentCommand)
void restoreOriginalState (QUndoCommand *parentCommand)
virtual void updateRoutingStatus ()
Protected Attributes
QImage * m_boardImage
int m_cleanupCount
int m_commandCount
CostFunction m_costFunction
QImage * m_displayImage [2] = { nullptr, nullptr }
QGraphicsPixmapItem * m_displayItem [2] = { nullptr, nullptr }
Grid * m_grid
double m_gridPixels
int m_halfGridJumperSize
int m_halfGridViaSize
JumperWillFitFunction m_jumperWillFitFunction
double m_keepoutGrid
int m_keepoutGridInt
double m_keepoutMils
QHash< ViewLayer::ViewLayerPlacement, QDomDocument * > m_masterDocs
int m_netLabelIndex
QImage * m_spareImage
QImage * m_spareImage2
double m_standardWireWidth
bool m_temporaryBoard
uint m_traceColors [2] = { 0 }
LayerList m_viewLayerIDs
Protected Attributes inherited from Autorouter
QList< QList< ConnectorItem * > * > m_allPartConnectorItems
QGraphicsItem * m_board = nullptr
bool m_bothSidesNow = false
bool m_cancelled = false
bool m_cancelTrace = false
int m_currentProgressPart = 0
double m_keepoutPixels = 0.0
int m_maxCycles = 0
int m_maximumProgressPart = 0
QRectF m_maxRect
bool m_pcbType = false
PCBSketchWidget * m_sketchWidget = nullptr
bool m_stopTracing = false
bool m_useBest = false
Additional Inherited Members
Signals inherited from Autorouter
void disableButtons ()
void setCycleCount (int)
void setCycleMessage (const QString &)
void setMaximumProgress (int)
void setProgressMessage (const QString &)
void setProgressMessage2 (const QString &)
void setProgressValue (int)
void wantBothVisible ()
void wantBottomVisible ()
void wantTopVisible ()
Static Public Attributes inherited from Autorouter
static const QString MaxCyclesName
Constructor & Destructor Documentation
MazeRouter()
MazeRouter::MazeRouter (class PCBSketchWidget * sketchWidget, QGraphicsItem * board, bool adjustIf)
References SketchWidget::addItem(), PCBSketchWidget::autorouteTypePCB(), CancelledMessage, DefaultMaxCycles, PCBSketchWidget::getAutorouterTraceWidth(), PCBSketchWidget::getTraceFlag(), PCBSketchWidget::getWireViewLayerID(), Autorouter::m_board, Autorouter::m_bothSidesNow, Autorouter::m_maxCycles, Autorouter::m_maxRect, Autorouter::m_pcbType, Autorouter::m_sketchWidget, m_standardWireWidth, m_temporaryBoard, m_viewLayerIDs, Autorouter::MaxCyclesName, ViewLayer::NewBottom, ViewLayer::NewTop, PCBSketchWidget::routeBothSides(), and ViewGeometry::setWireFlags().
~MazeRouter()
MazeRouter::~MazeRouter ()
Todo:
replace explicit deletes with std::shared_ptr and std::unique_ptr where it makes sense.
References Autorouter::m_board, m_boardImage, m_displayImage, m_displayItem, m_grid, m_masterDocs, m_spareImage, m_spareImage2, and m_temporaryBoard.
Member Function Documentation
addConnectionToUndo()
void MazeRouter::addConnectionToUndo (ConnectorItem * from, ConnectorItem * to, QUndoCommand * parentCommand) protected
References NonConnectorItem::attachedToID(), ConnectorItem::attachedToViewLayerID(), ConnectorItem::connectorSharedID(), BaseCommand::CrossView, Autorouter::m_sketchWidget, ChangeConnectionCommand::setUpdateConnections(), and ViewLayer::specFromID().
addJumperToUndo()
void MazeRouter::addJumperToUndo (JumperItem * jumperItem, QUndoCommand * parentCommand) protected
References BaseCommand::CrossView, JumperItem::getParams(), ItemBase::getViewGeometry(), ItemBase::id(), ModuleIDNames::JumperModuleIDName, Autorouter::m_sketchWidget, CheckStickyCommand::RemoveOnly, JumperItem::saveParams(), BaseCommand::SingleView, and ItemBase::viewLayerPlacement().
addNetLabelToUndo()
void MazeRouter::addNetLabelToUndo (SymbolPaletteItem * netLabel, QUndoCommand * parentCommand) protected
References BaseCommand::CrossView, SymbolPaletteItem::getLabel(), ItemBase::getViewGeometry(), ItemBase::id(), Autorouter::m_sketchWidget, ItemBase::moduleID(), and ItemBase::viewLayerPlacement().
addViaToUndo()
void MazeRouter::addViaToUndo (Via * via, QUndoCommand * parentCommand) protected
References BaseCommand::CrossView, ItemBase::getViewGeometry(), Hole::holeSize(), ItemBase::id(), Autorouter::m_sketchWidget, CheckStickyCommand::RemoveOnly, BaseCommand::SingleView, ModuleIDNames::ViaModuleIDName, and ItemBase::viewLayerPlacement().
cleanUpNets()
void MazeRouter::cleanUpNets (NetList & netList) protected
References Autorouter::cleanUpNets(), and NetList::nets.
clearExpansion()
void MazeRouter::clearExpansion (Grid * grid) protected
References Grid::at(), GridBoardObstacle, GridPartObstacle, Grid::setAt(), Grid::x, Grid::y, and Grid::z.
createTrace()
void MazeRouter::createTrace (Trace & trace, QList< GridPoint > & gridPoints, TraceThing & traceThing, ConnectionThing & connectionThing, Net * net) protected
References ConnectionThing::add(), SketchWidget::addItem(), atLeast(), JumperItem::connector0(), SymbolPaletteItem::connector0(), Wire::connector0(), JumperItem::connector1(), Wire::connector1(), Via::connectorItem(), DebugDialog::debug(), Autorouter::drawOneTrace(), findAnchor(), GridPoint::flags, Trace::flags, ItemBase::getNextID(), getPixelCenter(), getStepPoint(), PCBSketchWidget::getViaSize(), Trace::gridPoints, GridPointStepStart, JumperEnd, TraceThing::jumperItem, ModuleIDNames::JumperModuleIDName, JumperStart, m_gridPixels, Autorouter::m_pcbType, Autorouter::m_sketchWidget, m_standardWireWidth, makeNetLabel(), TraceThing::netLabel, ViewLayer::NewBottom, TraceThing::newJumperItems, TraceThing::newNetLabels, ViewLayer::NewTop, TraceThing::newTraces, TraceThing::newVias, TraceThing::nextTraceStart, Hole::OffsetPixels, PointZ::p, SketchWidget::referenceModel(), JumperItem::resize(), ReferenceModel::retrieveModelPart(), ConnectorItem::sceneAdjustedTerminalPoint(), Via::setAutoroutable(), JumperItem::setAutoroutable(), Hole::setHoleSize(), ViewGeometry::setLoc(), BaseCommand::SingleView, GraphicsUtils::SVGDPI, TraceThing::topLeft, ModuleIDNames::ViaModuleIDName, GridPoint::z, and PointZ::z.
createTraces()
void MazeRouter::createTraces (NetList & netList, Score & bestScore, QUndoCommand * parentCommand) protected
References addConnectionToUndo(), addJumperToUndo(), addNetLabelToUndo(), addViaToUndo(), Autorouter::addWireToUndo(), byOrder(), createTrace(), DebugDialog::debug(), Trace::flags, Trace::gridPoints, TraceThing::jumperItem, JumperStart, Autorouter::m_maxRect, ItemBase::modelPart(), NetList::nets, optimizeTraces(), NetOrdering::order, Score::ordering, removeColinear(), PaletteItem::removeLayerKin(), removeSteps(), ConnectionThing::sd, Autorouter::setMaximumProgress(), Autorouter::setProgressMessage2(), Autorouter::setProgressValue(), Score::traces, ConnectionThing::values(), and ItemBase::viewLayerID().
displayTrace()
void MazeRouter::displayTrace (Trace & trace) protected
References DebugDialog::debug(), Trace::flags, Trace::gridPoints, JumperLeft, JumperRight, m_displayImage, m_halfGridJumperSize, m_halfGridViaSize, m_traceColors, GridPoint::x, GridPoint::y, and GridPoint::z.
expand()
void MazeRouter::expand (GridPoint & gridPoint, RouteThing & routeThing) protected
References expandOne(), Autorouter::m_bothSidesNow, m_grid, GridPoint::x, Grid::x, GridPoint::y, Grid::y, GridPoint::z, and Grid::z.
expandOne()
void MazeRouter::expandOne (GridPoint & gridPoint, RouteThing & routeThing, int dx, int dy, int dz, bool crossLayer) protected
References Grid::at(), AvoidCost, RouteThing::avoids, GridPoint::baseCost, RouteThing::bestDistanceToSource, RouteThing::bestDistanceToTarget, RouteThing::bestLocationToSource, RouteThing::bestLocationToTarget, GridPoint::flags, GridAvoid, GridBoardObstacle, GridPartObstacle, GridPointDone, GridSource, GridSourceFlag, RouteThing::gridSourcePoint, RouteThing::gridTargetPoint, GridTempObstacle, m_costFunction, m_grid, GridPoint::qCost, Grid::setAt(), RouteThing::sourceQ, RouteThing::sourceValue, RouteThing::targetQ, RouteThing::targetValue, ViaCost, viaWillFit(), GridPoint::x, Grid::x, GridPoint::y, and GridPoint::z.
expandOneJ()
void MazeRouter::expandOneJ (GridPoint & gridPoint, std::priority_queue< GridPoint > & pq, int dx, int dy, int dz, GridValue targetValue, QPoint targetLocation, QSet< int > & already) protected
References Grid::at(), GridPoint::baseCost, GridAvoid, GridBoardObstacle, GridPartObstacle, gridPointInt(), GridSource, GridSourceFlag, GridTarget, GridTempObstacle, m_costFunction, m_grid, GridPoint::qCost, GridPoint::x, GridPoint::y, and GridPoint::z.
findAnchor() [1/2]
ConnectorItem * MazeRouter::findAnchor (GridPoint gp, TraceThing & traceThing, Net * net, QPointF & p, bool & onTrace, ConnectorItem * already) protected
References m_gridPixels, TraceThing::topLeft, ModelPart::Wire, GridPoint::x, and GridPoint::y.
findAnchor() [2/2]
ConnectorItem * MazeRouter::findAnchor (GridPoint gp, const QRectF & gridRect, TraceThing & traceThing, Net * net, QPointF & p, bool & onTrace, ConnectorItem * already) protected
References NonConnectorItem::attachedTo(), PCBSketchWidget::attachedToBottomLayer(), PCBSketchWidget::attachedToTopLayer(), Wire::connector0(), Wire::connector1(), DebugDialog::debug(), GraphicsUtils::distanceFromLine(), GraphicsUtils::distanceSqd(), ConnectorItem::getCrossLayerConnectorItem(), ItemBase::isEverVisible(), ItemBase::layerKinChief(), Autorouter::m_sketchWidget, Net::net, TraceThing::newTraces, TraceThing::newVias, ConnectorItem::sceneAdjustedTerminalPoint(), and GridPoint::z.
findNearestPair() [1/2]
void MazeRouter::findNearestPair (QList< QList< ConnectorItem * > > & subnets, Nearest & nearest) protected
References Nearest::distance, Nearest::i, Nearest::ic, Nearest::j, and Nearest::jc.
findNearestPair() [2/2]
void MazeRouter::findNearestPair (QList< QList< ConnectorItem * > > & subnets, int i, QList< ConnectorItem * > & inet, Nearest & nearest) protected
References ConnectorItem::attachedToViewLayerID(), ViewLayer::Copper1, CrossLayerCost, Nearest::distance, GraphicsUtils::distanceSqd(), ConnectorItem::getCrossLayerConnectorItem(), Nearest::i, Nearest::ic, Nearest::j, Nearest::jc, Layer1Cost, m_gridPixels, ConnectorItem::sceneAdjustedTerminalPoint(), and ViaCost.
findPinsWithin()
int MazeRouter::findPinsWithin (QList< ConnectorItem * > * net) protected
References Autorouter::m_sketchWidget.
incCommandProgress
void MazeRouter::incCommandProgress () slot
References m_cleanupCount, m_commandCount, ProcessEventBlocker::processEvents(), and Autorouter::setProgressValue().
initTraceDisplay()
void MazeRouter::initTraceDisplay () protected
References m_displayImage.
insertTrace()
void MazeRouter::insertTrace (Trace & newTrace, int netIndex, Score & currentScore, int viaCount, bool incRouted) protected
References DebugDialog::debug(), displayTrace(), Trace::gridPoints, Trace::netIndex, Trace::order, Score::routedCount, Score::totalRoutedCount, Score::totalViaCount, Score::traces, and Score::viaCount.
lookForJumper()
GridPoint MazeRouter::lookForJumper (GridPoint initial, GridValue targetValue, QPoint targetLocation) protected
References Grid::at(), GridPoint::baseCost, expandOneJ(), GridBoardObstacle, gridPointInt(), GridSource, GridSourceFlag, Autorouter::m_bothSidesNow, m_grid, m_halfGridJumperSize, m_jumperWillFitFunction, GridPoint::qCost, GridPoint::x, Grid::x, GridPoint::y, Grid::y, GridPoint::z, and Grid::z.
makeBoard()
bool MazeRouter::makeBoard (QImage * boardImage, double keepout, const QRectF & r) protected
References RenderThing::blackOnly, ViewLayer::Board, SvgFileSplitter::changeColors(), RenderThing::dpi, DRC::extendBorder(), RenderThing::hideTerminalPoints, Autorouter::m_board, Autorouter::m_sketchWidget, RenderThing::printerScale, RenderThing::renderBlocker, SketchWidget::renderToSVG(), RenderThing::selectedItems, GraphicsUtils::StandardFritzingDPI, and GraphicsUtils::SVGDPI.
makeMasters()
bool MazeRouter::makeMasters (QString & message) protected
References RenderThing::blackOnly, CancelledMessage, RenderThing::dpi, SvgFileSplitter::forceStrokeWidth(), RenderThing::hideTerminalPoints, Autorouter::m_board, Autorouter::m_bothSidesNow, Autorouter::m_cancelled, m_keepoutMils, m_masterDocs, Autorouter::m_sketchWidget, ViewLayer::NewBottom, ViewLayer::NewTop, RenderThing::printerScale, ProcessEventBlocker::processEvents(), RenderThing::renderBlocker, SketchWidget::renderToSVG(), PCBSketchWidget::routingLayers(), RenderThing::selectedItems, GraphicsUtils::StandardFritzingDPI, and GraphicsUtils::SVGDPI.
makeNetLabel()
SymbolPaletteItem * MazeRouter::makeNetLabel (GridPoint & center, SymbolPaletteItem * pairedNetLabel, uchar traceFlags) protected
References SketchWidget::addItem(), PaletteItemBase::boundingRect(), SymbolPaletteItem::getLabel(), ItemBase::getNextID(), getPixelCenter(), SymbolPaletteItem::isOnlyNetLabel(), JumperLeft, ModuleIDNames::LeftNetLabelModuleIDName, m_gridPixels, Autorouter::m_maxRect, m_netLabelIndex, Autorouter::m_sketchWidget, ModuleIDNames::NetLabelModuleIDName, ViewLayer::NewBottom, SketchWidget::referenceModel(), ReferenceModel::retrieveModelPart(), PaletteItemBase::saveGeometry(), SymbolPaletteItem::setAutoroutable(), SymbolPaletteItem::setLabel(), and BaseCommand::SingleView.
moveBack()
bool MazeRouter::moveBack (Score & currentScore, int index, QList< NetOrdering > & allOrderings) protected
References NetOrdering::order, and Score::ordering.
optimizeTraces()
void MazeRouter::optimizeTraces (QList< int > & order, QMultiHash< int, QList< QPointer< TraceWire > > > & bundles, QMultiHash< int, Via * > & vias, QMultiHash< int, JumperItem * > & jumperItems, QMultiHash< int, SymbolPaletteItem * > & netLabels, NetList & netList, ConnectionThing & connectionThing) protected
References NetElements::alsoNet, JumperItem::connector0(), Wire::connector0(), JumperItem::connector1(), Wire::connector1(), Via::connectorItem(), fastCopy(), initMarkers(), m_boardImage, Autorouter::m_bothSidesNow, Autorouter::m_keepoutPixels, m_masterDocs, Autorouter::m_maxRect, Autorouter::m_pcbType, m_spareImage, ConnectionThing::multi(), Net::net, NetElements::net, NetList::nets, ViewLayer::NewBottom, ViewLayer::NewTop, NetElements::notNet, OptimizeFactor, reducePoints(), ItemBase::renderOne(), ConnectorItem::sceneAdjustedTerminalPoint(), Autorouter::setProgressValue(), ViewLayer::specFromID(), and DRC::splitNetPrep().
prepSourceAndTarget()
void MazeRouter::prepSourceAndTarget (QDomDocument * masterdoc, RouteThing & routeThing, QList< QList< ConnectorItem * > > & subnets, int z, ViewLayer::ViewLayerPlacement viewLayerPlacement) protected
References NetElements::alsoNet, GridPoint::baseCost, SvgFileSplitter::forceStrokeWidth(), GridSource, GridTarget, Nearest::i, Nearest::j, m_grid, m_keepoutMils, RouteThing::nearest, NetElements::net, RouteThing::netElements, NetElements::notNet, GridPoint::qCost, RouteThing::r4, renderSource(), RouteThing::sourceQ, and RouteThing::targetQ.
reducePoints()
void MazeRouter::reducePoints (QList< QPointF > & points, QPointF topLeft, QList< TraceWire * > & bundle, int startIndex, int endIndex, ConnectionThing & connectionThing, int netIndex, ViewLayer::ViewLayerPlacement layerSpec) protected
References ConnectionThing::add(), Wire::connector0(), Wire::connector1(), Autorouter::m_pcbType, m_spareImage, m_spareImage2, ItemBase::modelPart(), OptimizeFactor, qMax(), qMin(), ConnectionThing::remove(), Wire::saveGeometry(), Wire::setLineAnd(), and ConnectionThing::values().
removeColinear()
void MazeRouter::removeColinear (QList< GridPoint > & gridPoints) protected
References GridPoint::x, GridPoint::y, and GridPoint::z.
removeOffBoardAnd()
void MazeRouter::removeOffBoardAnd (bool isPCBType, bool removeSingletons, bool bothSides) protected
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToItemType(), ConnectorItem::attachedToViewLayerID(), ViewLayer::Copper1, Via::getAutoroutable(), JumperItem::getAutoroutable(), SymbolPaletteItem::getAutoroutable(), SymbolPaletteItem::isOnlyNetLabel(), ModelPart::Jumper, ItemBase::layerKinChief(), Autorouter::m_allPartConnectorItems, Autorouter::m_board, ModelPart::Symbol, and ModelPart::Via.
removeStep()
void MazeRouter::removeStep (int ix, QList< GridPoint > & gridPoints) protected
References GridPoint::flags, getStepFlag(), GridPointStepStart, GridPoint::x, GridPoint::y, and GridPoint::z.
removeSteps()
void MazeRouter::removeSteps (QList< GridPoint > & gridPoints) protected
References removeStep().
renderSource()
QList< QPoint > MazeRouter::renderSource (QDomDocument * masterDoc, int z, ViewLayer::ViewLayerPlacement viewLayerPlacement, Grid * grid, QList< QDomElement > & netElements, QList< ConnectorItem * > & subnet, GridValue value, bool clearElements, const QRectF & r) protected
References Grid::at(), NonConnectorItem::attachedTo(), ConnectorItem::connector(), Connector::fullPinInfo(), GridAvoid, GridBoardObstacle, GridPartObstacle, ItemBase::id(), idsMatch(), Grid::init4(), m_gridPixels, Autorouter::m_keepoutPixels, Autorouter::m_maxRect, m_spareImage, SvgIdLayer::m_svgId, SvgIdLayer::m_terminalId, ItemBase::renderOne(), ConnectorItem::sceneAdjustedTerminalPoint(), Grid::setAt(), ViewLayer::specFromID(), ItemBase::viewID(), and ItemBase::viewLayerID().
route()
QList< GridPoint > MazeRouter::route (RouteThing & routeThing, int & viaCount) protected
References GridPoint::baseCost, clearExpansion(), DebugDialog::debug(), expand(), GridPoint::flags, GridPointDone, GridSource, GridTarget, Autorouter::m_cancelled, m_grid, Autorouter::m_stopTracing, GridPoint::qCost, RouteThing::sourceQ, RouteThing::sourceValue, RouteThing::targetQ, RouteThing::targetValue, and traceBack().
routeJumper()
void MazeRouter::routeJumper (int netIndex, RouteThing & routeThing, Score & currentScore) protected
References GridPoint::baseCost, RouteThing::bestDistanceToSource, RouteThing::bestDistanceToTarget, RouteThing::bestLocationToSource, RouteThing::bestLocationToTarget, clearExpansion(), GridPoint::flags, Trace::flags, GridBoardObstacle, GridPointJumperLeft, GridPointJumperRight, Trace::gridPoints, GridSource, RouteThing::gridSourcePoint, GridTarget, RouteThing::gridTargetPoint, insertTrace(), JumperEnd, JumperLeft, JumperRight, JumperStart, lookForJumper(), Autorouter::m_bothSidesNow, m_grid, Autorouter::m_pcbType, traceBack(), Score::traces, and updateDisplay().
routeNets()
bool MazeRouter::routeNets (NetList & netList, bool makeJumper, Score & currentScore, const QSizeF gridSize, QList< NetOrdering > & allOrderings) protected
References NetElements::alsoNet, Grid::clear(), Grid::copy(), displayTrace(), findNearestPair(), GridBoardObstacle, GridPartObstacle, RouteThing::gridSourcePoint, RouteThing::gridTargetPoint, Nearest::ic, Grid::init4(), initMarkers(), initTraceDisplay(), Nearest::jc, RouteThing::layerSpecs, m_boardImage, Autorouter::m_bothSidesNow, Autorouter::m_cancelled, m_grid, m_gridPixels, m_keepoutGridInt, m_masterDocs, Autorouter::m_maxRect, Autorouter::m_pcbType, m_spareImage, Autorouter::m_stopTracing, RouteThing::nearest, NetElements::net, RouteThing::netElements, NetList::nets, ViewLayer::NewBottom, ViewLayer::NewTop, NetElements::notNet, NetOrdering::order, Score::ordering, prepSourceAndTarget(), RouteThing::r, RouteThing::r4, ItemBase::renderOne(), Score::routedCount, routeNext(), routeOne(), ConnectorItem::sceneAdjustedTerminalPoint(), RouteThing::sourceQ, DRC::splitNetPrep(), RouteThing::targetQ, Score::totalRoutedCount, Score::totalViaCount, traceAvoids(), traceObstacles(), Score::traces, RouteThing::unrouted, updateDisplay(), Score::viaCount, Grid::x, and Grid::y.
routeNext()
bool MazeRouter::routeNext (bool makeJumper, RouteThing & routeThing, QList< QList< ConnectorItem * > > & subnets, Score & currentScore, int netIndex, QList< NetOrdering > & allOrderings) protected
References GridPoint::baseCost, Nearest::distance, findNearestPair(), GridPoint::flags, Trace::gridPoints, GridSource, RouteThing::gridSourcePoint, RouteThing::gridTargetPoint, Nearest::i, Nearest::ic, Nearest::j, Nearest::jc, RouteThing::layerSpecs, m_grid, m_gridPixels, m_masterDocs, Autorouter::m_maxRect, Autorouter::m_pcbType, RouteThing::nearest, ViewLayer::NewBottom, prepSourceAndTarget(), GridPoint::qCost, routeOne(), ConnectorItem::sceneAdjustedTerminalPoint(), Grid::setAt(), RouteThing::sourceQ, RouteThing::targetQ, traceAvoids(), Score::traces, RouteThing::unrouted, GridPoint::x, GridPoint::y, and GridPoint::z.
routeOne()
bool MazeRouter::routeOne (bool makeJumper, Score & currentScore, int netIndex, RouteThing & routeThing, QList< NetOrdering > & allOrderings) protected
References Score::anyUnrouted, RouteThing::bestDistanceToSource, RouteThing::bestDistanceToTarget, Trace::gridPoints, insertTrace(), Autorouter::m_bothSidesNow, Autorouter::m_cancelled, Autorouter::m_stopTracing, moveBack(), NetOrdering::order, Score::ordering, Score::reorderNet, route(), routeJumper(), RouteThing::unrouted, and updateDisplay().
setMaxCycles
void MazeRouter::setMaxCycles (int maxCycles) slot
References Autorouter::setMaxCycles(), and Autorouter::setMaximumProgress().
setUpWidths()
void MazeRouter::setUpWidths (double width) protected
start()
void MazeRouter::start () virtual
Todo:
can have leaks if ctors of these commands changes
Todo:
perfect candidate for std::unique_ptr<QImage[]>
Todo:
leaks can occur if not careful
Implements Autorouter.
References Score::anyUnrouted, SketchWidget::blockUI(), byPinsWithin(), Autorouter::cleanUpNets(), SketchWidget::collectAllNets(), ConnectorItem::collectEqualPotential(), createTraces(), Grid::data, DebugDialog::debug(), Autorouter::disableButtons(), distanceCost(), Autorouter::doCancel(), GraphicsUtils::drawBorder(), PCBSketchWidget::ensureTraceLayersVisible(), findPinsWithin(), PCBSketchWidget::getKeepout(), PCBSketchWidget::getTraceFlag(), PCBSketchWidget::getViaSize(), Net::id, Autorouter::initUndo(), PCBSketchWidget::jumperItemSize(), jumperWillFit(), Autorouter::m_allPartConnectorItems, Autorouter::m_board, m_boardImage, Autorouter::m_bothSidesNow, Autorouter::m_cancelled, m_cleanupCount, m_commandCount, m_costFunction, m_displayImage, m_displayItem, m_grid, m_gridPixels, m_halfGridJumperSize, m_halfGridViaSize, m_jumperWillFitFunction, m_keepoutGrid, m_keepoutGridInt, m_keepoutMils, Autorouter::m_keepoutPixels, Autorouter::m_maxCycles, Autorouter::m_maxRect, Autorouter::m_pcbType, Autorouter::m_sketchWidget, m_spareImage, m_spareImage2, m_standardWireWidth, Autorouter::m_stopTracing, m_temporaryBoard, m_traceColors, Autorouter::m_useBest, makeBoard(), makeMasters(), manhattanCost(), Net::net, NetList::nets, ViewGeometry::NormalFlag, OptimizeFactor, NetOrdering::order, Score::ordering, ViewGeometry::PCBTraceFlag, printOrder(), ProcessEventBlocker::processEvents(), SketchWidget::pushCommand(), qMax(), ViewGeometry::RatsnestFlag, CleanUpWiresCommand::RedoOnly, removeOffBoardAnd(), Autorouter::restoreOriginalState(), routeNets(), schematicJumperWillFit(), ViewGeometry::SchematicTraceFlag, Autorouter::setCycleCount(), Autorouter::setCycleMessage(), Autorouter::setMaximumProgress(), Score::setOrdering(), Autorouter::setProgressMessage(), Autorouter::setProgressMessage2(), Autorouter::setProgressValue(), GraphicsUtils::StandardFritzingDPI, GraphicsUtils::SVGDPI, BaseCommand::totalChildCount(), Score::totalRoutedCount, Score::totalViaCount, CleanUpWiresCommand::UndoOnly, and Autorouter::wantBothVisible().
traceAvoids()
void MazeRouter::traceAvoids (QList< Trace > & traces, int netIndex, RouteThing & routeThing) protected
References Grid::at(), RouteThing::avoids, GridPoint::flags, Trace::flags, GridAvoid, GridBoardObstacle, GridPartObstacle, GridPointJumperLeft, Trace::gridPoints, GridSource, GridTarget, m_grid, m_halfGridJumperSize, m_keepoutGridInt, Trace::netIndex, Grid::setAt(), GridPoint::x, Grid::x, and GridPoint::y.
traceBack()
QList< GridPoint > MazeRouter::traceBack (GridPoint gridPoint, Grid * grid, int & viaCount, GridValue sourceValue, GridValue targetValue) protected
References GridPoint::baseCost, GridBoardObstacle, and traceBackOne().
traceBackOne()
GridPoint MazeRouter::traceBackOne (GridPoint & gridPoint, Grid * grid, int dx, int dy, int dz, GridValue sourceValue, GridValue targetValue) protected
References Grid::at(), GridPoint::baseCost, GridBoardObstacle, GridPartObstacle, GridSource, GridSourceFlag, GridTempObstacle, GridPoint::x, Grid::x, GridPoint::y, Grid::y, GridPoint::z, and Grid::z.
traceObstacles()
void MazeRouter::traceObstacles (QList< Trace > & traces, int netIndex, Grid * grid, int ikeepout) protected
References Trace::flags, GridBoardObstacle, Trace::gridPoints, Autorouter::m_bothSidesNow, m_halfGridJumperSize, m_halfGridViaSize, Trace::netIndex, Grid::setAt(), GridPoint::x, GridPoint::y, and GridPoint::z.
updateDisplay() [1/3]
void MazeRouter::updateDisplay (int iz) protected
References SketchWidget::addItem(), m_displayImage, m_displayItem, m_gridPixels, Autorouter::m_maxRect, Autorouter::m_sketchWidget, and ProcessEventBlocker::processEvents().
updateDisplay() [2/3]
void MazeRouter::updateDisplay (Grid * grid, int iz) protected
References Grid::at(), getColor(), m_displayImage, updateDisplay(), Grid::x, and Grid::y.
updateDisplay() [3/3]
void MazeRouter::updateDisplay (GridPoint & gridPoint) protected
References Grid::at(), getColor(), m_displayImage, m_grid, updateDisplay(), GridPoint::x, GridPoint::y, and GridPoint::z.
viaWillFit()
bool MazeRouter::viaWillFit (GridPoint & gridPoint, Grid * grid) protected
References Grid::at(), GridAvoid, GridBoardObstacle, GridPartObstacle, GridSource, GridTarget, GridTempObstacle, m_halfGridViaSize, GridPoint::x, Grid::x, GridPoint::y, Grid::y, and Grid::z.
Member Data Documentation
m_boardImage
QImage* MazeRouter::m_boardImage protected
m_cleanupCount
int MazeRouter::m_cleanupCount protected
m_commandCount
int MazeRouter::m_commandCount protected
m_costFunction
CostFunction MazeRouter::m_costFunction protected
m_displayImage
QImage* MazeRouter::m_displayImage[2] = { nullptr, nullptr } protected
m_displayItem
QGraphicsPixmapItem* MazeRouter::m_displayItem[2] = { nullptr, nullptr } protected
m_grid
Grid* MazeRouter::m_grid protected
m_gridPixels
double MazeRouter::m_gridPixels protected
m_halfGridJumperSize
int MazeRouter::m_halfGridJumperSize protected
m_halfGridViaSize
int MazeRouter::m_halfGridViaSize protected
m_jumperWillFitFunction
JumperWillFitFunction MazeRouter::m_jumperWillFitFunction protected
m_keepoutGrid
double MazeRouter::m_keepoutGrid protected
m_keepoutGridInt
int MazeRouter::m_keepoutGridInt protected
m_keepoutMils
double MazeRouter::m_keepoutMils protected
m_masterDocs
QHash<ViewLayer::ViewLayerPlacement, QDomDocument *> MazeRouter::m_masterDocs protected
m_netLabelIndex
int MazeRouter::m_netLabelIndex protected
m_spareImage
QImage* MazeRouter::m_spareImage protected
m_spareImage2
QImage* MazeRouter::m_spareImage2 protected
m_standardWireWidth
double MazeRouter::m_standardWireWidth protected
m_temporaryBoard
bool MazeRouter::m_temporaryBoard protected
m_traceColors
uint MazeRouter::m_traceColors[2] = { 0 } protected
m_viewLayerIDs
LayerList MazeRouter::m_viewLayerIDs protected
The documentation for this class was generated from the following files:
autoroute/mazerouter/mazerouter.h
autoroute/mazerouter/mazerouter.cpp