Fritzing: CMRouter Class Reference
CMRouter Class Reference
#include <cmrouter.h>
Public Types
enum OverlapType { IgnoreAllOverlaps = 0, ClipAllOverlaps, ReportAllOverlaps, AllowEquipotentialOverlaps }
Public Member Functions
CMRouter (PCBSketchWidget *, ItemBase *board, bool adjustIf)
~CMRouter ()=default
TileRect boardRect ()
void drcClean ()
Plane * initPlane (bool rotate90)
Tile * insertTile (Plane *thePlane, QRectF &tileRect, QList< Tile * > &alreadyTiled, QGraphicsItem *, Tile::TileType type, CMRouter::OverlapType)
void setKeepout (double)
Protected Member Functions
Tile * addTile (class NonConnectorItem *nci, Tile::TileType type, Plane *, QList< Tile * > &alreadyTiled, CMRouter::OverlapType)
bool allowEquipotentialOverlaps (QGraphicsItem *item, QList< Tile * > &alreadyTiled)
void cleanPoints (QList< QPointF > &allPoints, Plane *)
void clearGridEntries ()
void clearPlane (Plane *thePlane)
void displayBadTileRect (TileRect &tileRect)
void displayBadTiles (QList< Tile * > &alreadyTiled)
GridEntry * drawGridItem (Tile *tile)
void drawTileRect (TileRect &tileRect, QColor &color)
void hideTiles ()
Tile * insertTile (Plane *thePlane, TileRect &tileRect, QList< Tile * > &alreadyTiled, QGraphicsItem *, Tile::TileType type, CMRouter::OverlapType)
void insertUnion (TileRect &tileRect, QGraphicsItem *, Tile::TileType tileType)
bool insideV (const QPointF &check, const QPointF &vertex)
void makeAlignTiles (QMultiHash< Tile *, TileRect * > &, Plane *thePlane)
bool overlapsOnly (QGraphicsItem *item, QList< Tile * > &alreadyTiled)
void setUpWidths (double width)
Protected Attributes
ItemBase * m_board = nullptr
QString m_error
double m_keepoutPixels = 0.0
QRectF m_maxRect
QRectF m_maxRect90
TileRect m_overlappingTileRect
QList< Plane * > m_planes
PCBSketchWidget * m_sketchWidget = nullptr
TileRect m_tileMaxRect
Plane * m_union90Plane = nullptr
Plane * m_unionPlane = nullptr
Member Enumeration Documentation
OverlapType
enum CMRouter::OverlapType
Enumerator
IgnoreAllOverlaps
ClipAllOverlaps
ReportAllOverlaps
AllowEquipotentialOverlaps
Constructor & Destructor Documentation
CMRouter()
CMRouter::CMRouter (PCBSketchWidget * sketchWidget, ItemBase * board, bool adjustIf)
References PCBSketchWidget::getAutorouterTraceWidth(), m_board, m_maxRect, m_maxRect90, m_sketchWidget, m_tileMaxRect, qrectToTile(), and setUpWidths().
~CMRouter()
CMRouter::~CMRouter () default
Member Function Documentation
addTile()
Tile * CMRouter::addTile (class NonConnectorItem * nci, Tile::TileType type, Plane * thePlane, QList< Tile * > & alreadyTiled, CMRouter::OverlapType overlapType) protected
References NonConnectorItem::attachedTo(), DGI, insertTile(), m_keepoutPixels, and realsToTile().
allowEquipotentialOverlaps()
bool CMRouter::allowEquipotentialOverlaps (QGraphicsItem * item, QList< Tile * > & alreadyTiled) protected
References ConnectorItem::collectEqualPotential(), Wire::connector0(), ViewGeometry::NoFlag, and TiGetBody().
boardRect()
TileRect CMRouter::boardRect ()
References m_tileMaxRect.
cleanPoints()
void CMRouter::cleanPoints (QList< QPointF > & allPoints, Plane *) protected
clearGridEntries()
void CMRouter::clearGridEntries () protected
References m_sketchWidget.
clearPlane()
void CMRouter::clearPlane (Plane * thePlane) protected
References Plane::maxRect, prepDeleteTile(), TiFree(), TiFreePlane(), and TiSrArea().
displayBadTileRect()
void CMRouter::displayBadTileRect (TileRect & tileRect) protected
References SketchWidget::addItem(), SketchWidget::getTopZ(), GridEntryAlpha, m_sketchWidget, ProcessEventBlocker::processEvents(), and tileRectToQRect().
displayBadTiles()
void CMRouter::displayBadTiles (QList< Tile * > & alreadyTiled) protected
References displayBadTileRect(), m_overlappingTileRect, and TiToRect().
drawGridItem()
GridEntry * CMRouter::drawGridItem (Tile * tile) protected
References SketchWidget::addItem(), Tile::DESTINATION, GridEntry::drawn(), SketchWidget::getTopZ(), GridEntryAlpha, m_sketchWidget, Tile::OBSTACLE, ProcessEventBlocker::processEvents(), Tile::SCHEMATICWIRESPACE, GridEntry::setDrawn(), Tile::SOURCE, Tile::SPACE, Tile::SPACE2, TiGetGridEntry(), TiGetType(), tileToQRect(), and TiSetClient().
drawTileRect()
void CMRouter::drawTileRect (TileRect & tileRect, QColor & color) protected
References SketchWidget::addItem(), SketchWidget::getTopZ(), m_sketchWidget, and tileRectToQRect().
drcClean()
void CMRouter::drcClean ()
References clearGridEntries(), clearPlane(), m_union90Plane, and m_unionPlane.
hideTiles()
void CMRouter::hideTiles () protected
References m_sketchWidget.
initPlane()
Plane * CMRouter::initPlane (bool rotate90)
References Tile::BUFFER, fasterRealToTile(), m_maxRect, m_maxRect90, Plane::maxRect, qrectToTile(), SETLEFT(), SETRIGHT(), SETYMAX(), SETYMIN(), Tile::SPACE, TiAlloc(), TiInsertTile(), TiNewPlane(), TiSetBody(), TiSetType(), TileRect::xmaxi, TileRect::xmini, TileRect::ymaxi, and TileRect::ymini.
insertTile() [1/2]
Tile * CMRouter::insertTile (Plane * thePlane, QRectF & tileRect, QList< Tile * > & alreadyTiled, QGraphicsItem * item, Tile::TileType type, CMRouter::OverlapType overlapType)
References qrectToTile().
insertTile() [2/2]
Tile * CMRouter::insertTile (Plane * thePlane, TileRect & tileRect, QList< Tile * > & alreadyTiled, QGraphicsItem * item, Tile::TileType type, CMRouter::OverlapType overlapType) protected
References DebugDialog::debug(), DGI, IgnoreAllOverlaps, insertUnion(), m_overlappingTileRect, Plane::maxRect, TiInsertTile(), TileRect::xmaxi, TileRect::xmini, TileRect::ymaxi, and TileRect::ymini.
insertUnion()
void CMRouter::insertUnion (TileRect & tileRect, QGraphicsItem * , Tile::TileType tileType) protected
References m_union90Plane, m_unionPlane, Plane::maxRect, Tile::OBSTACLE, Tile::SPACE, Tile::SPACE2, TiInsertTile(), tileRotate90(), TileRect::xmaxi, TileRect::xmini, TileRect::ymaxi, and TileRect::ymini.
insideV()
bool CMRouter::insideV (const QPointF & check, const QPointF & vertex) protected
References dot().
makeAlignTiles()
void CMRouter::makeAlignTiles (QMultiHash< Tile *, TileRect * > & , Plane * thePlane) protected
overlapsOnly()
bool CMRouter::overlapsOnly (QGraphicsItem * item, QList< Tile * > & alreadyTiled) protected
References TiGetBody().
setKeepout()
void CMRouter::setKeepout (double keepout)
References m_keepoutPixels.
setUpWidths()
void CMRouter::setUpWidths (double width) protected
References fasterRealToTile(), HalfStandardWireWidth, StandardWireWidth, TileHalfStandardWireWidth, and TileStandardWireWidth.
Member Data Documentation
m_board
ItemBase* CMRouter::m_board = nullptr protected
m_error
QString CMRouter::m_error protected
m_keepoutPixels
double CMRouter::m_keepoutPixels = 0.0 protected
m_maxRect
QRectF CMRouter::m_maxRect protected
m_maxRect90
QRectF CMRouter::m_maxRect90 protected
m_overlappingTileRect
TileRect CMRouter::m_overlappingTileRect protected
m_planes
QList<Plane *> CMRouter::m_planes protected
m_sketchWidget
PCBSketchWidget* CMRouter::m_sketchWidget = nullptr protected
m_tileMaxRect
TileRect CMRouter::m_tileMaxRect protected
m_union90Plane
Plane* CMRouter::m_union90Plane = nullptr protected
m_unionPlane
Plane* CMRouter::m_unionPlane = nullptr protected
The documentation for this class was generated from the following files:
autoroute/cmrouter/cmrouter.h
autoroute/cmrouter/cmrouter.cpp