Fritzing: autoroute/cmrouter/DBcell.cpp File Reference
DBcell.cpp File Reference
#include <sys/types.h>
#include <stdio.h>
#include "tile.h"
Classes
struct searchArg
Macros
#define TOPBOTTOM 12
#define TOPBOTTOMLEFT 14
#define TOPBOTTOMLEFTRIGHT 15
#define TOPLEFT 10
#define TOPLEFTRIGHT 11
Functions
void cellTileMerge (Tile *tile, Plane *plane, int direction)
Tile * clipCellTile (Tile *tile, Plane *plane, TileRect *rect)
bool ctbListMatch (Tile *tp1, Tile *tp2)
void DBDeleteCell (Plane *plane, TileRect *rect)
void DBPlaceCell (Plane *plane, TileRect *rect, QGraphicsItem *body, Tile::TileType type)
int deleteCellFunc (Tile *, UserData)
int placeCellFunc (Tile *, UserData)
Tile * TiInsertTile (Plane *plane, TileRect *rect, QGraphicsItem *body, Tile::TileType type)
Macro Definition Documentation
TOPBOTTOM
#define TOPBOTTOM 12
TOPBOTTOMLEFT
#define TOPBOTTOMLEFT 14
TOPBOTTOMLEFTRIGHT
#define TOPBOTTOMLEFTRIGHT 15
TOPLEFT
#define TOPLEFT 10
TOPLEFTRIGHT
#define TOPLEFTRIGHT 11
Function Documentation
cellTileMerge()
void cellTileMerge (Tile * tile, Plane * plane, int direction)
References BL(), ctbListMatch(), LEFT(), MINDIFF, searchArg::plane, RIGHT(), RT(), TiJoinX(), TiJoinY(), TiSplitY(), TiSrPoint(), TilePoint::xi, TilePoint::yi, YMAX(), and YMIN().
clipCellTile()
Tile * clipCellTile (Tile * tile, Plane * plane, TileRect * rect)
References cellTileMerge(), LEFT(), searchArg::plane, searchArg::rect, RIGHT(), TiSplitX(), TiSplitY(), TOPBOTTOM, TileRect::xmaxi, TileRect::xmini, YMAX(), TileRect::ymaxi, YMIN(), and TileRect::ymini.
ctbListMatch()
bool ctbListMatch (Tile * tp1, Tile * tp2)
References Tile::ti_body, and Tile::ti_type.
DBDeleteCell()
void DBDeleteCell (Plane * plane, TileRect * rect)
References deleteCellFunc(), searchArg::plane, searchArg::rect, and TiSrArea().
DBPlaceCell()
void DBPlaceCell (Plane * plane, TileRect * rect, QGraphicsItem * body, Tile::TileType type)
References searchArg::body, placeCellFunc(), searchArg::plane, searchArg::rect, TiSrArea(), and searchArg::type.
deleteCellFunc()
int deleteCellFunc (Tile * tile, UserData data)
References cellTileMerge(), searchArg::plane, searchArg::rect, RIGHT(), TOPBOTTOMLEFT, TOPBOTTOMLEFTRIGHT, TOPLEFT, TOPLEFTRIGHT, TileRect::xmaxi, YMIN(), and TileRect::ymini.
placeCellFunc()
int placeCellFunc (Tile * tile, UserData data)
References searchArg::body, cellTileMerge(), clipCellTile(), searchArg::plane, searchArg::rect, RIGHT(), TiSetBody(), TiSetType(), TOPBOTTOMLEFT, TOPBOTTOMLEFTRIGHT, TOPLEFT, TOPLEFTRIGHT, searchArg::type, TileRect::xmaxi, YMIN(), and TileRect::ymini.
TiInsertTile()
Tile* TiInsertTile (Plane * plane, TileRect * rect, QGraphicsItem * body, Tile::TileType type)
References searchArg::body, DBPlaceCell(), searchArg::plane, searchArg::rect, TiSrPoint(), searchArg::type, TileRect::xmini, and TileRect::ymini.