Fritzing: MismatchingConnectorWidget Class Reference
MismatchingConnectorWidget Class Reference
#include <mismatchingconnectorwidget.h>
Signals
void completeConn (MismatchingConnectorWidget *)
Signals inherited from AbstractConnectorInfoWidget
void repaintNeeded ()
void tellSistersImNewSelected (AbstractConnectorInfoWidget *)
void tellViewsMyConnectorIsNewSelected (const QString &)
Public Member Functions
MismatchingConnectorWidget (class ConnectorsInfoWidget *topLevelContainer, ViewLayer::ViewIdentifier viewId, const QString &connId, QWidget *parent, bool isInView=true, Connector *conn=NULL)
~MismatchingConnectorWidget ()
void addViewPresence (ViewLayer::ViewIdentifier viewId)
const QString & connId ()
QList< ViewLayer::ViewIdentifier > missingViews ()
bool onlyMissingThisView (ViewLayer::ViewIdentifier viewId)
bool presentInAllViews ()
Connector * prevConn ()
void removeViewPresence (ViewLayer::ViewIdentifier viewId)
void setSelected (bool selected, bool doEmitChange=true)
QList< ViewLayer::ViewIdentifier > views ()
Public Member Functions inherited from AbstractConnectorInfoWidget
AbstractConnectorInfoWidget (class ConnectorsInfoWidget *topLevelContainer, QWidget *parent=0)
bool isSelected ()
Protected Slots
void emitCompletion ()
Protected Member Functions
void mousePressEvent (QMouseEvent *event)
QString viewsString ()
Protected Member Functions inherited from AbstractConnectorInfoWidget
void reapplyStyle ()
Protected Attributes
QString m_connId
QLabel * m_connIdLabel
QLabel * m_connMsgLabel
QList< ViewLayer::ViewIdentifier > m_missingViews
QPointer< Connector > m_prevConn
Protected Attributes inherited from AbstractConnectorInfoWidget
volatile bool m_isSelected
ConnectorInfoRemoveButton * m_removeButton
ConnectorsInfoWidget * m_topLevelContainer
Static Protected Attributes
static QList< ViewLayer::ViewIdentifier > AllViews
Static Protected Attributes inherited from AbstractConnectorInfoWidget
static int SingleConnectorHeight = 40
Constructor & Destructor Documentation
MismatchingConnectorWidget()
MismatchingConnectorWidget::MismatchingConnectorWidget (class ConnectorsInfoWidget * topLevelContainer, ViewLayer::ViewIdentifier viewId, const QString & connId, QWidget * parent, bool isInView = true, Connector * conn = NULL)
References addViewPresence(), AllViews, ViewLayer::BreadboardView, connId(), emitCompletion(), m_connId, m_connIdLabel, m_connMsgLabel, m_missingViews, m_prevConn, AbstractConnectorInfoWidget::m_removeButton, ViewLayer::PCBView, removeViewPresence(), ViewLayer::SchematicView, AbstractConnectorInfoWidget::SingleConnectorHeight, and viewsString().
~MismatchingConnectorWidget()
MismatchingConnectorWidget::~MismatchingConnectorWidget ()
Member Function Documentation
addViewPresence()
void MismatchingConnectorWidget::addViewPresence (ViewLayer::ViewIdentifier viewId)
References m_connMsgLabel, m_missingViews, and viewsString().
completeConn
void MismatchingConnectorWidget::completeConn (MismatchingConnectorWidget *) signal
connId()
const QString & MismatchingConnectorWidget::connId ()
References m_connId.
emitCompletion
void MismatchingConnectorWidget::emitCompletion () protected slot
References completeConn().
missingViews()
QList< ViewLayer::ViewIdentifier > MismatchingConnectorWidget::missingViews ()
References m_missingViews.
mousePressEvent()
void MismatchingConnectorWidget::mousePressEvent (QMouseEvent * event) protected
References AbstractConnectorInfoWidget::isSelected(), and setSelected().
onlyMissingThisView()
bool MismatchingConnectorWidget::onlyMissingThisView (ViewLayer::ViewIdentifier viewId)
References m_missingViews.
presentInAllViews()
bool MismatchingConnectorWidget::presentInAllViews ()
References m_missingViews.
prevConn()
Connector * MismatchingConnectorWidget::prevConn ()
References m_prevConn.
removeViewPresence()
void MismatchingConnectorWidget::removeViewPresence (ViewLayer::ViewIdentifier viewId)
References m_connMsgLabel, m_missingViews, and viewsString().
setSelected()
void MismatchingConnectorWidget::setSelected (bool selected, bool doEmitChange = true) virtual
Reimplemented from AbstractConnectorInfoWidget.
References m_connId, AbstractConnectorInfoWidget::setSelected(), and AbstractConnectorInfoWidget::tellViewsMyConnectorIsNewSelected().
views()
QList< ViewLayer::ViewIdentifier > MismatchingConnectorWidget::views ()
References AllViews, and m_missingViews.
viewsString()
QString MismatchingConnectorWidget::viewsString () protected
References AllViews, and m_missingViews.
Member Data Documentation
AllViews
QList< ViewLayer::ViewIdentifier > MismatchingConnectorWidget::AllViews static protected
m_connId
QString MismatchingConnectorWidget::m_connId protected
m_connIdLabel
QLabel* MismatchingConnectorWidget::m_connIdLabel protected
m_connMsgLabel
QLabel* MismatchingConnectorWidget::m_connMsgLabel protected
m_missingViews
QList<ViewLayer::ViewIdentifier> MismatchingConnectorWidget::m_missingViews protected
m_prevConn
QPointer<Connector> MismatchingConnectorWidget::m_prevConn protected
The documentation for this class was generated from the following files:
partseditor/obsolete/mismatchingconnectorwidget.h
partseditor/obsolete/mismatchingconnectorwidget.cpp