Fritzing: referencemodel/sqlitereferencemodel.cpp File Reference
sqlitereferencemodel.cpp File Reference
#include <QSqlRecord>
#include <QSqlError>
#include <QMessageBox>
#include <QVector>
#include <QSqlResult>
#include <QSqlDriver>
#include <QDebug>
#include <limits>
#include "sqlitereferencemodel.h"
#include "../debugdialog.h"
#include "../connectors/svgidlayer.h"
#include "../connectors/connector.h"
#include "../connectors/connectorshared.h"
#include "../connectors/busshared.h"
#include "../utils/folderutils.h"
#include "../utils/fmessagebox.h"
#include "../utils/textutils.h"
Macros
#define MAX_CONN_TRIES 3
Functions
void debugError (bool result, QSqlQuery &query)
void debugExec (const QString &msg, QSqlQuery &query)
void killBuses (QVector< BusShared * > &buses)
void killConnectors (QVector< Connector * > &connectors)
void noSwappingMessage (int n)
Variables
static ModelPart * DebugModelPart = NULL
QStringList FailurePartMessages
QStringList FailurePropertyMessages
static const qulonglong NO_ID = std::numeric_limits<qulonglong>::max()
Macro Definition Documentation
MAX_CONN_TRIES
#define MAX_CONN_TRIES 3
Function Documentation
debugError()
void debugError (bool result, QSqlQuery & query)
References DebugDialog::debug().
debugExec()
void debugExec (const QString & msg, QSqlQuery & query)
References DebugDialog::debug(), DebugModelPart, and ModelPart::moduleID().
killBuses()
void killBuses (QVector< BusShared * > & buses)
killConnectors()
void killConnectors (QVector< Connector * > & connectors)
References Connector::connectorShared().
noSwappingMessage()
void noSwappingMessage (int n)
References FMessageBox::warning().
Variable Documentation
DebugModelPart
ModelPart* DebugModelPart = NULL static
FailurePartMessages
QStringList FailurePartMessages
FailurePropertyMessages
QStringList FailurePropertyMessages
NO_ID
const qulonglong NO_ID = std::numeric_limits<qulonglong>::max() static