Fritzing: Autorouter Class Reference
Autorouter Class Reference abstract
#include <autorouter.h>
Public Slots
virtual void cancel ()
virtual void cancelTrace ()
virtual void setMaxCycles (int)
virtual void stopTracing ()
virtual void useBest ()
Signals
void disableButtons ()
void setCycleCount (int)
void setCycleMessage (const QString &)
void setMaximumProgress (int)
void setProgressMessage (const QString &)
void setProgressMessage2 (const QString &)
void setProgressValue (int)
void wantBothVisible ()
void wantBottomVisible ()
void wantTopVisible ()
Public Member Functions
Autorouter (PCBSketchWidget *)
virtual ~Autorouter ()=default
virtual void start ()=0
Static Public Attributes
static const QString MaxCyclesName
Protected Member Functions
void addToUndo (QUndoCommand *parentCommand)
void addUndoConnection (bool connect, SymbolPaletteItem *, QUndoCommand *parentCommand)
void addUndoConnection (bool connect, JumperItem *, QUndoCommand *parentCommand)
void addUndoConnection (bool connect, Via *, QUndoCommand *parentCommand)
void addUndoConnection (bool connect, TraceWire *, QUndoCommand *parentCommand)
void addUndoConnection (bool connect, ConnectorItem *, BaseCommand::CrossViewType, QUndoCommand *parentCommand)
void addWireToUndo (Wire *wire, QUndoCommand *parentCommand)
virtual void cleanUpNets ()
void clearTracesAndJumpers ()
void doCancel (QUndoCommand *parentCommand)
virtual class TraceWire * drawOneTrace (QPointF fromPos, QPointF toPos, double width, ViewLayer::ViewLayerPlacement)
void initUndo (QUndoCommand *parentCommand)
void restoreOriginalState (QUndoCommand *parentCommand)
virtual void updateRoutingStatus ()
Protected Attributes
QList< QList< ConnectorItem * > * > m_allPartConnectorItems
QGraphicsItem * m_board = nullptr
bool m_bothSidesNow = false
bool m_cancelled = false
bool m_cancelTrace = false
int m_currentProgressPart = 0
double m_keepoutPixels = 0.0
int m_maxCycles = 0
int m_maximumProgressPart = 0
QRectF m_maxRect
bool m_pcbType = false
PCBSketchWidget * m_sketchWidget = nullptr
bool m_stopTracing = false
bool m_useBest = false
Constructor & Destructor Documentation
Autorouter()
Autorouter::Autorouter (PCBSketchWidget * sketchWidget)
~Autorouter()
virtual Autorouter::~Autorouter () virtual default
Member Function Documentation
addToUndo()
void Autorouter::addToUndo (QUndoCommand * parentCommand) protected
Todo:
this can cause leaks if the constructors of these commands change.
References addUndoConnection(), addWireToUndo(), BaseCommand::CrossView, PCBSketchWidget::getTraceFlag(), ModuleIDNames::JumperModuleIDName, m_board, m_pcbType, m_sketchWidget, CheckStickyCommand::RemoveOnly, PCBSketchWidget::setClipEnds(), BaseCommand::SingleView, and ModuleIDNames::ViaModuleIDName.
addUndoConnection() [1/5]
void Autorouter::addUndoConnection (bool connect, SymbolPaletteItem * netLabel, QUndoCommand * parentCommand) protected
References SymbolPaletteItem::connector0(), and BaseCommand::CrossView.
addUndoConnection() [2/5]
void Autorouter::addUndoConnection (bool connect, JumperItem * jumperItem, QUndoCommand * parentCommand) protected
References addUndoConnection(), JumperItem::connector0(), JumperItem::connector1(), and BaseCommand::CrossView.
addUndoConnection() [3/5]
void Autorouter::addUndoConnection (bool connect, Via * via, QUndoCommand * parentCommand) protected
References addUndoConnection(), Via::connectorItem(), BaseCommand::CrossView, and ConnectorItem::getCrossLayerConnectorItem().
addUndoConnection() [4/5]
void Autorouter::addUndoConnection (bool connect, TraceWire * traceWire, QUndoCommand * parentCommand) protected
References addUndoConnection(), Wire::connector0(), Wire::connector1(), and BaseCommand::CrossView.
addUndoConnection() [5/5]
void Autorouter::addUndoConnection (bool connect, ConnectorItem * connectorItem, BaseCommand::CrossViewType crossView, QUndoCommand * parentCommand) protected
References NonConnectorItem::attachedTo(), NonConnectorItem::attachedToID(), ConnectorItem::attachedToViewLayerID(), ConnectorItem::connectedToItems(), ConnectorItem::connectorSharedID(), m_sketchWidget, and ViewLayer::specFromID().
addWireToUndo()
void Autorouter::addWireToUndo (Wire * wire, QUndoCommand * parentCommand) protected
Todo:
this can cause leaks if the ctor of the commands change
References Wire::colorString(), BaseCommand::CrossView, ItemBase::getViewGeometry(), ItemBase::id(), m_sketchWidget, Wire::opacity(), CheckStickyCommand::RemoveOnly, BaseCommand::SingleView, ItemBase::viewLayerPlacement(), Wire::width(), and ModuleIDNames::WireModuleIDName.
cancel
void Autorouter::cancel () virtual slot
References m_cancelled.
cancelTrace
void Autorouter::cancelTrace () virtual slot
References m_cancelTrace.
cleanUpNets()
void Autorouter::cleanUpNets () protected virtual
References m_allPartConnectorItems.
clearTracesAndJumpers()
void Autorouter::clearTracesAndJumpers () protected
References PCBSketchWidget::deleteItem(), PCBSketchWidget::getTraceFlag(), m_board, m_pcbType, and m_sketchWidget.
disableButtons
void Autorouter::disableButtons () signal
doCancel()
void Autorouter::doCancel (QUndoCommand * parentCommand) protected
References cleanUpNets(), ProcessEventBlocker::processEvents(), restoreOriginalState(), and setProgressMessage().
drawOneTrace()
TraceWire * Autorouter::drawOneTrace (QPointF fromPos, QPointF toPos, double width, ViewLayer::ViewLayerPlacement viewLayerPlacement) protected virtual
References SketchWidget::addItem(), DebugDialog::debug(), ItemBase::getNextID(), PCBSketchWidget::getTraceFlag(), PCBSketchWidget::getWireStrokeWidth(), m_sketchWidget, SketchWidget::referenceModel(), ReferenceModel::retrieveModelPart(), ViewGeometry::setAutoroutable(), PCBSketchWidget::setClipEnds(), ViewGeometry::setLine(), ViewGeometry::setLoc(), ViewGeometry::setWireFlags(), BaseCommand::SingleView, PCBSketchWidget::traceColor(), and ModuleIDNames::WireModuleIDName.
initUndo()
void Autorouter::initUndo (QUndoCommand * parentCommand) protected
References addUndoConnection(), NonConnectorItem::attachedTo(), ConnectorItem::connectedToItems(), BaseCommand::CrossView, PCBSketchWidget::deleteItem(), Wire::getAutoroutable(), ConnectorItem::getCrossLayerConnectorItem(), PCBSketchWidget::getTraceFlag(), m_board, m_pcbType, m_sketchWidget, SketchWidget::makeDeleteItemCommand(), and Wire::setAutoroutable().
restoreOriginalState()
void Autorouter::restoreOriginalState (QUndoCommand * parentCommand) protected
setCycleCount
void Autorouter::setCycleCount (int) signal
setCycleMessage
void Autorouter::setCycleMessage (const QString &) signal
setMaxCycles
void Autorouter::setMaxCycles (int maxCycles) virtual slot
References m_maxCycles, and MaxCyclesName.
setMaximumProgress
void Autorouter::setMaximumProgress (int) signal
setProgressMessage
void Autorouter::setProgressMessage (const QString &) signal
setProgressMessage2
void Autorouter::setProgressMessage2 (const QString &) signal
setProgressValue
void Autorouter::setProgressValue (int) signal
start()
virtual void Autorouter::start () pure virtual
Implemented in MazeRouter.
stopTracing
void Autorouter::stopTracing () virtual slot
References m_stopTracing.
updateRoutingStatus()
void Autorouter::updateRoutingStatus () protected virtual
References m_sketchWidget, SketchWidget::updateRoutingStatus(), and RoutingStatus::zero().
useBest
void Autorouter::useBest () virtual slot
References m_stopTracing, and m_useBest.
wantBothVisible
void Autorouter::wantBothVisible () signal
wantBottomVisible
void Autorouter::wantBottomVisible () signal
wantTopVisible
void Autorouter::wantTopVisible () signal
Member Data Documentation
m_allPartConnectorItems
QList< QList<ConnectorItem*>* > Autorouter::m_allPartConnectorItems protected
m_board
QGraphicsItem* Autorouter::m_board = nullptr protected
m_bothSidesNow
bool Autorouter::m_bothSidesNow = false protected
m_cancelled
bool Autorouter::m_cancelled = false protected
m_cancelTrace
bool Autorouter::m_cancelTrace = false protected
m_currentProgressPart
int Autorouter::m_currentProgressPart = 0 protected
m_keepoutPixels
double Autorouter::m_keepoutPixels = 0.0 protected
m_maxCycles
int Autorouter::m_maxCycles = 0 protected
m_maximumProgressPart
int Autorouter::m_maximumProgressPart = 0 protected
m_maxRect
QRectF Autorouter::m_maxRect protected
m_pcbType
bool Autorouter::m_pcbType = false protected
m_sketchWidget
PCBSketchWidget* Autorouter::m_sketchWidget = nullptr protected
m_stopTracing
bool Autorouter::m_stopTracing = false protected
m_useBest
bool Autorouter::m_useBest = false protected
MaxCyclesName
const QString Autorouter::MaxCyclesName static
The documentation for this class was generated from the following files:
autoroute/autorouter.h
autoroute/autorouter.cpp