Fritzing: PartsEditorViewsWidget Class Reference
PartsEditorViewsWidget Class Reference
#include <partseditorviewswidget.h>
Public Slots
void drawConnector (Connector *)
void drawConnector (ViewLayer::ViewIdentifier, Connector *)
void informConnectorSelection (const QString &connId)
void removeConnectorFrom (const QString &, ViewLayer::ViewIdentifier)
void repaint ()
void setMismatching (ViewLayer::ViewIdentifier viewId, const QString &id, bool mismatching)
void showHideTerminalPoints (int checkState)
Signals
void connectorSelectedInView (const QString &connId)
void connectorsFoundSignal (QList< QPointer< Connector > >)
Public Member Functions
PartsEditorViewsWidget (SketchModel *sketchModel, class WaitPushUndoStack *undoStack, ConnectorsInfoWidget *info, QWidget *parent, class ItemBase *fromItem)
~PartsEditorViewsWidget ()
void aboutToSave ()
PartsEditorView * breadboardView ()
bool connectorsPosOrSizeChanged ()
void connectTerminalRemoval (const ConnectorsInfoWidget *connsInfo)
void copySvgFilesToDestiny (const QString &partFileName)
bool imagesLoadedInAllViews ()
void loadViewsImagesFromModel (PaletteModel *paletteModel, ModelPart *modelPart)
PartsEditorView * pcbView ()
PartsEditorView * schematicView ()
void setViewItems (class ItemBase *, class ItemBase *, class ItemBase *)
QCheckBox * showTerminalPointsCheckBox ()
const QDir & tempDir ()
void updatePinsInfo (QList< QPointer< ConnectorShared > > connsShared)
Protected Member Functions
QWidget * addZoomControlsAndBrowseButton (PartsEditorView *view)
bool checkStateToBool (int checkState)
void connectPair (PartsEditorView *v1, PartsEditorView *v2)
void connectToThis (PartsEditorView *v)
PartsEditorView * createViewImageWidget (SketchModel *sketchModel, class WaitPushUndoStack *undoStack, ViewLayer::ViewIdentifier viewId, QString iconFileName, QString startText, ConnectorsInfoWidget *info, ViewLayer::ViewLayerID viewLayerId, class ItemBase *fromItem)
void init ()
bool showingTerminalPoints ()
Protected Attributes
QPointer< PartsEditorView > m_breadView
bool m_connsPosChanged
QPointer< QLabel > m_guidelines
QPointer< PartsEditorView > m_pcbView
QPointer< PartsEditorView > m_schemView
QPointer< QCheckBox > m_showTerminalPointsCheckBox
QHash< ViewLayer::ViewIdentifier, PartsEditorView * > m_views
QSplitter * m_viewsContainter
Static Protected Attributes
static QString EmptyBreadViewText
static QString EmptyPcbViewText
static QString EmptySchemViewText
Constructor & Destructor Documentation
PartsEditorViewsWidget()
PartsEditorViewsWidget::PartsEditorViewsWidget (SketchModel * sketchModel, class WaitPushUndoStack * undoStack, ConnectorsInfoWidget * info, QWidget * parent, class ItemBase * fromItem)
References addZoomControlsAndBrowseButton(), ViewLayer::Breadboard, ViewLayer::BreadboardNote, ViewLayer::BreadboardRuler, ViewLayer::BreadboardView, ViewLayer::BreadboardWire, connectPair(), connectToThis(), ViewLayer::Copper0, createViewImageWidget(), EmptyBreadViewText, EmptyPcbViewText, EmptySchemViewText, init(), m_breadView, m_guidelines, m_pcbView, m_schemView, m_showTerminalPointsCheckBox, m_viewsContainter, ViewLayer::PcbNote, ViewLayer::PCBView, ViewLayer::Schematic, ViewLayer::SchematicNote, ViewLayer::SchematicRuler, ViewLayer::SchematicView, ViewLayer::SchematicWire, and showHideTerminalPoints().
~PartsEditorViewsWidget()
PartsEditorViewsWidget::~PartsEditorViewsWidget ()
References m_breadView, m_pcbView, and m_schemView.
Member Function Documentation
aboutToSave()
void PartsEditorViewsWidget::aboutToSave ()
References m_breadView, m_pcbView, and m_schemView.
addZoomControlsAndBrowseButton()
QWidget * PartsEditorViewsWidget::addZoomControlsAndBrowseButton (PartsEditorView * view) protected
breadboardView()
PartsEditorView * PartsEditorViewsWidget::breadboardView ()
References m_breadView.
checkStateToBool()
bool PartsEditorViewsWidget::checkStateToBool (int checkState) protected
connectorSelectedInView
void PartsEditorViewsWidget::connectorSelectedInView (const QString & connId) signal
connectorsFoundSignal
void PartsEditorViewsWidget::connectorsFoundSignal (QList< QPointer< Connector > >) signal
connectorsPosOrSizeChanged()
bool PartsEditorViewsWidget::connectorsPosOrSizeChanged ()
References m_breadView, m_pcbView, and m_schemView.
connectPair()
void PartsEditorViewsWidget::connectPair (PartsEditorView * v1, PartsEditorView * v2) protected
References informConnectorSelection().
connectTerminalRemoval()
void PartsEditorViewsWidget::connectTerminalRemoval (const ConnectorsInfoWidget * connsInfo)
References m_breadView, m_pcbView, and m_schemView.
connectToThis()
void PartsEditorViewsWidget::connectToThis (PartsEditorView * v) protected
References informConnectorSelection().
copySvgFilesToDestiny()
void PartsEditorViewsWidget::copySvgFilesToDestiny (const QString & partFileName)
References m_breadView, m_pcbView, and m_schemView.
createViewImageWidget()
PartsEditorView * PartsEditorViewsWidget::createViewImageWidget (SketchModel * sketchModel, class WaitPushUndoStack * undoStack, ViewLayer::ViewIdentifier viewId, QString iconFileName, QString startText, ConnectorsInfoWidget * info, ViewLayer::ViewLayerID viewLayerId, class ItemBase * fromItem) protected
References SketchWidget::addViewLayer(), connectorsFoundSignal(), PartsEditorMainWindow::emptyViewItem(), informConnectorSelection(), m_views, setMismatching(), SketchWidget::setSketchModel(), SketchWidget::setUndoStack(), showingTerminalPoints(), and tempDir().
drawConnector [1/2]
void PartsEditorViewsWidget::drawConnector (Connector * conn) slot
References m_breadView, m_pcbView, m_schemView, and showingTerminalPoints().
drawConnector [2/2]
void PartsEditorViewsWidget::drawConnector (ViewLayer::ViewIdentifier viewId, Connector * conn) slot
References m_views, and showingTerminalPoints().
imagesLoadedInAllViews()
bool PartsEditorViewsWidget::imagesLoadedInAllViews ()
References m_breadView, m_pcbView, and m_schemView.
informConnectorSelection
void PartsEditorViewsWidget::informConnectorSelection (const QString & connId) slot
References connectorSelectedInView().
init()
void PartsEditorViewsWidget::init () protected
References EmptyBreadViewText, EmptyPcbViewText, EmptySchemViewText, and m_connsPosChanged.
loadViewsImagesFromModel()
void PartsEditorViewsWidget::loadViewsImagesFromModel (PaletteModel * paletteModel, ModelPart * modelPart)
References ModelPart::connectors(), connectorsFoundSignal(), m_breadView, m_pcbView, and m_schemView.
pcbView()
PartsEditorView * PartsEditorViewsWidget::pcbView ()
References m_pcbView.
removeConnectorFrom
void PartsEditorViewsWidget::removeConnectorFrom (const QString & connId, ViewLayer::ViewIdentifier viewId) slot
References ViewLayer::AllViews, m_breadView, m_pcbView, m_schemView, and m_views.
repaint
void PartsEditorViewsWidget::repaint () slot
References m_breadView, m_pcbView, and m_schemView.
schematicView()
PartsEditorView * PartsEditorViewsWidget::schematicView ()
References m_schemView.
setMismatching
void PartsEditorViewsWidget::setMismatching (ViewLayer::ViewIdentifier viewId, const QString & id, bool mismatching) slot
References m_views.
setViewItems()
void PartsEditorViewsWidget::setViewItems (class ItemBase * bbItem, class ItemBase * schemItem, class ItemBase * pcbItem)
References m_breadView, m_pcbView, and m_schemView.
showHideTerminalPoints
void PartsEditorViewsWidget::showHideTerminalPoints (int checkState) slot
References checkStateToBool(), m_breadView, m_pcbView, and m_schemView.
showingTerminalPoints()
bool PartsEditorViewsWidget::showingTerminalPoints () protected
References checkStateToBool(), and m_showTerminalPointsCheckBox.
showTerminalPointsCheckBox()
QCheckBox * PartsEditorViewsWidget::showTerminalPointsCheckBox ()
References m_showTerminalPointsCheckBox.
tempDir()
const QDir & PartsEditorViewsWidget::tempDir ()
updatePinsInfo()
void PartsEditorViewsWidget::updatePinsInfo (QList< QPointer< ConnectorShared > > connsShared)
References m_breadView, m_pcbView, and m_schemView.
Member Data Documentation
EmptyBreadViewText
QString PartsEditorViewsWidget::EmptyBreadViewText static protected
EmptyPcbViewText
QString PartsEditorViewsWidget::EmptyPcbViewText static protected
EmptySchemViewText
QString PartsEditorViewsWidget::EmptySchemViewText static protected
m_breadView
QPointer<PartsEditorView> PartsEditorViewsWidget::m_breadView protected
m_connsPosChanged
bool PartsEditorViewsWidget::m_connsPosChanged protected
m_guidelines
QPointer<QLabel> PartsEditorViewsWidget::m_guidelines protected
m_pcbView
QPointer<PartsEditorView> PartsEditorViewsWidget::m_pcbView protected
m_schemView
QPointer<PartsEditorView> PartsEditorViewsWidget::m_schemView protected
m_showTerminalPointsCheckBox
QPointer<QCheckBox> PartsEditorViewsWidget::m_showTerminalPointsCheckBox protected
m_views
QHash<ViewLayer::ViewIdentifier,PartsEditorView*> PartsEditorViewsWidget::m_views protected
m_viewsContainter
QSplitter* PartsEditorViewsWidget::m_viewsContainter protected
The documentation for this class was generated from the following files:
partseditor/obsolete/partseditorviewswidget.h
partseditor/obsolete/partseditorviewswidget.cpp