Fritzing: MoveLabelCommand Class Reference
MoveLabelCommand Class Reference
#include <commands.h>
Public Member Functions
MoveLabelCommand (class SketchWidget *sketchWidget, long id, QPointF oldPos, QPointF oldOffset, QPointF newPos, QPointF newOffset, QUndoCommand *parent)
void redo ()
void undo ()
Public Member Functions inherited from BaseCommand
BaseCommand (BaseCommand::CrossViewType, SketchWidget *, QUndoCommand *parent)
~BaseCommand ()
void addSubCommand (BaseCommand *subCommand)
BaseCommand::CrossViewType crossViewType () const noexcept
virtual QString getDebugString () const
int index () const
const QUndoCommand * parentCommand () const
void redo ()
void setCrossViewType (BaseCommand::CrossViewType)
void setRedoOnly ()
void setSkipFirstRedo ()
void setUndoOnly ()
SketchWidget * sketchWidget () const
const BaseCommand * subCommand (int index) const
int subCommandCount () const
void subRedo ()
void subRedo (int index)
void subUndo ()
void subUndo (int index)
void undo ()
Protected Member Functions
QString getParamString () const
Protected Attributes
long m_itemID
QPointF m_newOffset
QPointF m_newPos
QPointF m_oldOffset
QPointF m_oldPos
Protected Attributes inherited from BaseCommand
QList< BaseCommand * > m_commands
BaseCommand::CrossViewType m_crossViewType
int m_index = 0
QUndoCommand * m_parentCommand = nullptr
bool m_redoOnly = false
SketchWidget * m_sketchWidget = nullptr
bool m_skipFirstRedo = false
bool m_undoOnly = false
Additional Inherited Members
Public Types inherited from BaseCommand
enum CrossViewType { SingleView, CrossView }
Static Public Member Functions inherited from BaseCommand
static void clearProgress ()
static CommandProgress * initProgress ()
static int totalChildCount (const QUndoCommand *)
Static Protected Attributes inherited from BaseCommand
static CommandProgress m_commandProgress
static int nextIndex = 0
Constructor & Destructor Documentation
MoveLabelCommand()
MoveLabelCommand::MoveLabelCommand (class SketchWidget * sketchWidget, long id, QPointF oldPos, QPointF oldOffset, QPointF newPos, QPointF newOffset, QUndoCommand * parent)
Member Function Documentation
getParamString()
QString MoveLabelCommand::getParamString () const protected virtual
Reimplemented from BaseCommand.
References BaseCommand::getParamString(), and m_itemID.
redo()
void MoveLabelCommand::redo ()
References m_itemID, m_newOffset, m_newPos, BaseCommand::m_sketchWidget, SketchWidget::movePartLabel(), and BaseCommand::redo().
undo()
void MoveLabelCommand::undo ()
References m_itemID, m_oldOffset, m_oldPos, BaseCommand::m_sketchWidget, SketchWidget::movePartLabel(), and BaseCommand::undo().
Member Data Documentation
m_itemID
long MoveLabelCommand::m_itemID protected
m_newOffset
QPointF MoveLabelCommand::m_newOffset protected
m_newPos
QPointF MoveLabelCommand::m_newPos protected
m_oldOffset
QPointF MoveLabelCommand::m_oldOffset protected
m_oldPos
QPointF MoveLabelCommand::m_oldPos protected
The documentation for this class was generated from the following files:
commands.h
commands.cpp