Fritzing: autoroute/cmrouter/tile.cpp File Reference
tile.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <limits>
#include "tile.h"
Functions
void dupTileBody (Tile *oldtp, Tile *newtp)
Tile * gotoPoint (Tile *tp, TilePoint p)
Tile * TiAlloc ()
void TiFree (Tile *tp)
void TiFreePlane (Plane *plane)
void TiJoinX (Tile *tile1, Tile *tile2, Plane *plane)
void TiJoinY (Tile *tile1, Tile *tile2, Plane *plane)
Plane * TiNewPlane (Tile *tile, int minx, int miny, int maxx, int maxy)
Tile * TiSplitX (Tile *tile, int x)
Tile * TiSplitX_Left (Tile *tile, int x)
Tile * TiSplitY (Tile *tile, int y)
Tile * TiSplitY_Bottom (Tile *tile, int y)
void TiToRect (Tile *tile, TileRect *rect)
Variables
int MINFINITY = -TINFINITY
int TINFINITY = (std::numeric_limits<int>::max() >> 2) - 4
Function Documentation
dupTileBody()
void dupTileBody (Tile * oldtp, Tile * newtp)
References TiGetBody(), TiGetType(), TiSetBody(), and TiSetType().
gotoPoint()
Tile* gotoPoint (Tile * tp, TilePoint p)
References BL(), LB(), LEFT(), RIGHT(), RT(), TR(), TilePoint::xi, TilePoint::yi, YMAX(), and YMIN().
TiAlloc()
Tile* TiAlloc ()
References Tile::NOTYPE, SETBL(), SETLB(), SETRT(), SETTR(), TiSetBody(), TiSetClient(), and TiSetType().
TiFree()
void TiFree (Tile * tp)
TiFreePlane()
void TiFreePlane (Plane * plane)
References Plane::pl_bottom, Plane::pl_left, Plane::pl_right, Plane::pl_top, searchArg::plane, and TiFree().
TiJoinX()
void TiJoinX (Tile * tile1, Tile * tile2, Plane * plane)
References BL(), LB(), LEFT(), Plane::pl_hint, searchArg::plane, RT(), SETBL(), SETLB(), SETLEFT(), SETRT(), SETTR(), TiFree(), and TR().
TiJoinY()
void TiJoinY (Tile * tile1, Tile * tile2, Plane * plane)
References BL(), LB(), Plane::pl_hint, searchArg::plane, RT(), SETBL(), SETLB(), SETRT(), SETTR(), SETYMIN(), TiFree(), TR(), and YMIN().
TiNewPlane()
Plane* TiNewPlane (Tile * tile, int minx, int miny, int maxx, int maxy)
References BADTILE, Tile::DUMMYBOTTOM, Tile::DUMMYLEFT, Tile::DUMMYRIGHT, Tile::DUMMYTOP, Plane::maxRect, MINFINITY, Plane::pl_bottom, Plane::pl_hint, Plane::pl_left, Plane::pl_right, Plane::pl_top, SETBL(), SETLB(), SETLEFT(), SETRT(), SETTR(), SETYMIN(), TiAlloc(), TINFINITY, TiSetBody(), TiSetType(), TileRect::xmaxi, TileRect::xmini, TileRect::ymaxi, and TileRect::ymini.
TiSplitX()
Tile* TiSplitX (Tile * tile, int x)
References BL(), dupTileBody(), LB(), LEFT(), RIGHT(), RT(), SETBL(), SETLB(), SETLEFT(), SETRT(), SETTR(), SETYMIN(), TiAlloc(), TR(), and YMIN().
TiSplitX_Left()
Tile* TiSplitX_Left (Tile * tile, int x)
References BL(), dupTileBody(), LB(), LEFT(), RIGHT(), RT(), SETBL(), SETLB(), SETLEFT(), SETRT(), SETTR(), SETYMIN(), TiAlloc(), TR(), and YMIN().
TiSplitY()
Tile* TiSplitY (Tile * tile, int y)
References BL(), dupTileBody(), LB(), LEFT(), RT(), SETBL(), SETLB(), SETLEFT(), SETRT(), SETTR(), SETYMIN(), TiAlloc(), TR(), YMAX(), and YMIN().
TiSplitY_Bottom()
Tile* TiSplitY_Bottom (Tile * tile, int y)
References BL(), dupTileBody(), LB(), LEFT(), RT(), SETBL(), SETLB(), SETLEFT(), SETRT(), SETTR(), SETYMIN(), TiAlloc(), TR(), YMAX(), and YMIN().
TiToRect()
void TiToRect (Tile * tile, TileRect * rect)
References LEFT(), searchArg::rect, RIGHT(), TileRect::xmaxi, TileRect::xmini, YMAX(), TileRect::ymaxi, YMIN(), and TileRect::ymini.
Variable Documentation
MINFINITY
int MINFINITY = -TINFINITY
TINFINITY
int TINFINITY = (std::numeric_limits<int>::max() >> 2) - 4