Fritzing: RatsnestColors Class Reference
RatsnestColors Class Reference
#include <ratsnestcolors.h>
Public Member Functions
RatsnestColors (const QDomElement &)
~RatsnestColors ()
Static Public Member Functions
static QColor backgroundColor (ViewLayer::ViewID)
static void cleanup ()
static bool findConnectorColor (const QStringList &names, QColor &color)
static void initNames ()
static bool isConnectorColor (ViewLayer::ViewID m_viewID, const QColor &)
static const QColor & netColor (ViewLayer::ViewID m_viewID)
static void reset (ViewLayer::ViewID m_viewID)
static const QString & shadowColor (ViewLayer::ViewID, const QString &name)
static QString wireColor (ViewLayer::ViewID, QString &name)
Protected Member Functions
const QColor & getNextColor ()
Protected Attributes
QColor m_backgroundColor
int m_index
QHash< QString, class RatsnestColor * > m_ratsnestColorHash
QList< class RatsnestColor * > m_ratsnestColorList
ViewLayer::ViewID m_viewID
Static Protected Attributes
static QHash< QString, class RatsnestColor * > m_allNames
static QHash< ViewLayer::ViewID, RatsnestColors * > m_viewList
Constructor & Destructor Documentation
RatsnestColors()
RatsnestColors::RatsnestColors (const QDomElement & view)
References ViewLayer::idFromXmlName(), m_allNames, m_backgroundColor, RatsnestColor::m_connectorNames, m_index, RatsnestColor::m_name, m_ratsnestColorHash, m_ratsnestColorList, and m_viewID.
~RatsnestColors()
RatsnestColors::~RatsnestColors ()
References m_ratsnestColorHash, and m_ratsnestColorList.
Member Function Documentation
backgroundColor()
QColor RatsnestColors::backgroundColor (ViewLayer::ViewID viewID) static
References m_backgroundColor, and m_viewList.
cleanup()
void RatsnestColors::cleanup () static
References m_viewList.
findConnectorColor()
bool RatsnestColors::findConnectorColor (const QStringList & names, QColor & color) static
References m_allNames, and RatsnestColor::m_ratsnest.
getNextColor()
const QColor & RatsnestColors::getNextColor () protected
References ErrorColor(), RatsnestColor::m_connectorNames, m_index, RatsnestColor::m_ratsnest, and m_ratsnestColorList.
initNames()
void RatsnestColors::initNames () static
References m_viewID, m_viewList, and RatsnestColors().
isConnectorColor()
bool RatsnestColors::isConnectorColor (ViewLayer::ViewID m_viewID, const QColor & color) static
References RatsnestColor::m_connectorNames, RatsnestColor::m_ratsnest, m_ratsnestColorList, m_viewID, and m_viewList.
netColor()
const QColor & RatsnestColors::netColor (ViewLayer::ViewID m_viewID) static
References ErrorColor(), getNextColor(), and m_viewList.
reset()
void RatsnestColors::reset (ViewLayer::ViewID m_viewID) static
References m_index, m_viewID, and m_viewList.
shadowColor()
const QString & RatsnestColors::shadowColor (ViewLayer::ViewID viewID, const QString & name) static
References ___emptyString___, m_ratsnestColorHash, RatsnestColor::m_shadow, and m_viewList.
wireColor()
QString RatsnestColors::wireColor (ViewLayer::ViewID viewID, QString & name) static
References ___emptyString___, m_ratsnestColorHash, m_viewList, RatsnestColor::m_wire, and RatsnestColor::matchColor().
Member Data Documentation
m_allNames
QHash< QString, class RatsnestColor * > RatsnestColors::m_allNames static protected
m_backgroundColor
QColor RatsnestColors::m_backgroundColor protected
m_index
int RatsnestColors::m_index protected
m_ratsnestColorHash
QHash<QString, class RatsnestColor *> RatsnestColors::m_ratsnestColorHash protected
m_ratsnestColorList
QList<class RatsnestColor *> RatsnestColors::m_ratsnestColorList protected
m_viewID
ViewLayer::ViewID RatsnestColors::m_viewID protected
m_viewList
QHash< ViewLayer::ViewID, RatsnestColors * > RatsnestColors::m_viewList static protected
The documentation for this class was generated from the following files:
utils/ratsnestcolors.h
utils/ratsnestcolors.cpp