Fritzing: SqliteReferenceModel Class Reference
SqliteReferenceModel Class Reference
#include <sqlitereferencemodel.h>
Public Member Functions
SqliteReferenceModel ()
~SqliteReferenceModel ()
bool addPart (ModelPart *newModel, bool update)
ModelPart * addPart (QString newPartPath, bool addToReference, bool updateIdAlreadyExists)
QMultiHash< QString, QString > allPropValues (const QString &family, const QString &propName)
bool containsModelPart (const QString &moduleID)
bool lastWasExactMatch ()
bool loadAll (const QString &databaseName, bool fullLoad, bool dbExists)
bool loadFromDB (const QString &databaseName)
ModelPart * loadPart (const QString &path, bool update)
QString partTitle (const QString &moduleID)
QStringList propValues (const QString &family, const QString &propName, bool distinct)
void recordProperty (const QString &name, const QString &value)
ModelPart * reloadPart (const QString &path, const QString &moduleID)
ModelPart * retrieveModelPart (const QString &moduleID)
QString retrieveModuleId (const QString &family, const QMultiHash< QString, QString > &properties, const QString &propertyName, bool closestMatch)
QString retrieveModuleIdWith (const QString &family, const QString &propertyName, bool closestMatch)
void setSha (const QString &sha)
const QString & sha () const
bool swapEnabled () const
bool updatePart (ModelPart *newModel)
Public Member Functions inherited from PaletteModel
PaletteModel ()
PaletteModel (bool makeRoot, bool doInit)
~PaletteModel ()
QList< ModelPart * > allParts ()
void clear ()
void clearPartHash ()
QList< ModelPart * > findContribNoBin ()
QString loadedFrom ()
bool loadedFromFile ()
bool loadFromFile (const QString &fileName, ModelBase *referenceModel, bool checkViews)
void removePart (const QString &moduleID)
void removeParts ()
QList< ModelPart * > search (const QString &searchText, bool allowObsolete)
void search (ModelPart *modelPart, const QStringList &searchStrings, QList< ModelPart * > &modelParts, bool allowObsolete)
void setOrdererChildren (QList< QObject * > children)
Public Member Functions inherited from ModelBase
ModelBase (bool makeRoot)
virtual ~ModelBase ()
virtual ModelPart * addModelPart (ModelPart *parent, ModelPart *copyChild)
virtual ModelPart * addPart (QString newPartPath, bool addToReference)
bool checkForReversedWires ()
const QString & fritzingVersion ()
ModelPart * genFZP (const QString &moduleID, ModelBase *referenceModel)
bool loadFromFile (const QString &fileName, ModelBase *referenceModel, QList< ModelPart * > &modelParts, bool checkInstances)
bool paste (ModelBase *referenceModel, QByteArray &data, QList< ModelPart * > &modelParts, QHash< QString, QRectF > &boundingRects, bool preserveIndex)
ModelPart * root ()
ModelPartSharedRoot * rootModelPartShared ()
void save (const QString &fileName, bool asPart)
void save (const QString &fileName, class QXmlStreamWriter &, bool asPart)
void setReferenceModel (ModelBase *)
void setReportMissingModules (bool)
Protected Member Functions
bool addPartAux (ModelPart *newModel, bool fullLoad)
QString closestMatchId (const QString &family, const QMultiHash< QString, QString > &properties, const QString &propertyName, const QString &propertyValue)
int countPropsInCommon (const QString &family, const QMultiHash< QString, QString > &properties, const ModelPart *part2)
bool createDatabase (const QString &databaseName, bool fullLoad)
void createIndexes ()
void createMoreIndexes (QSqlDatabase &)
bool createParts (QSqlDatabase &, bool fullLoad)
bool createProperties (QSqlDatabase &)
void deleteConnection ()
QString getClosestMatch (const QString &family, const QMultiHash< QString, QString > &properties, QStringList possibleMatches)
QStringList getPossibleMatches (const QString &family, const QMultiHash< QString, QString > &properties, const QString &propertyName, const QString &propertyValue)
void initParts (bool dbExists)
bool insertBus (const Bus *, qulonglong id)
bool insertBusMember (const Connector *, qulonglong id)
bool insertConnector (const class Connector *, qulonglong id)
bool insertConnectorLayer (const class SvgIdLayer *, qulonglong id)
bool insertPart (ModelPart *, bool fullLoad)
bool insertProperty (const QString &name, const QString &value, qulonglong id, bool showInLabel)
bool insertSubpart (ModelPartShared *, qulonglong id)
bool insertSubpartConnector (const ConnectorShared *cs, qulonglong id)
bool insertTag (const QString &tag, qulonglong id)
bool insertViewImage (const struct ViewImage *, qulonglong id)
void killParts ()
bool loadFromDB (QSqlDatabase &keep_db, QSqlDatabase &db)
qulonglong partId (QString moduleID)
bool removeBuses (qulonglong partId)
bool removeConnectors (qulonglong partId)
bool removePart (qulonglong partId)
bool removePart (const QString &moduleId)
bool removePartFromDataBase (const QString &moduleId)
bool removeProperties (qulonglong partId)
bool removeSchematicSubparts (qulonglong partId)
bool removeTags (qulonglong partId)
bool removeViewImages (qulonglong partId)
bool removex (qulonglong id, const QString &tableName, const QString &idName)
Protected Member Functions inherited from PaletteModel
void countParts (QDir &dir, QStringList &nameFilters, int &partCount)
void loadParts (bool dbExists)
void loadPartsAux (QDir &dir, QStringList &nameFilters, int &loadedPart, int totalParts)
ModelPart * makeSubpart (ModelPart *originalModelPart, const QDomElement &originalSubparth)
Protected Member Functions inherited from ModelBase
ModelPart * createOldSchematicPart (ModelPart *, QString &moduleIDRef)
ModelPart * createOldSchematicPartAux (ModelPart *, const QString &oldModuleIDRef, const QString &oldSchematicFileName, const QString &oldSvgPath)
ModelPart * fixObsoleteModuleID (QDomDocument &domDocument, QDomElement &instance, QString &moduleIDRef)
bool loadInstances (QDomDocument &, QDomElement &root, QList< ModelPart * > &modelParts, bool checkViews)
void renewModelIndexes (QDomElement &root, const QString &childName, QHash< long, long > &oldToNew)
Protected Attributes
QSqlDatabase m_database
bool m_init
volatile bool m_keepGoing
volatile bool m_lastWasExactMatch
QMultiHash< QString, QString > m_recordedProperties
QString m_sha
volatile bool m_swappingEnabled
Protected Attributes inherited from PaletteModel
bool m_fullLoad
QString m_loadedFrom
bool m_loadedFromFile
bool m_loadingContrib
QHash< QString, ModelPart * > m_partHash
Protected Attributes inherited from ModelBase
bool m_checkForReversedWires
QString m_fritzingVersion
QPointer< ModelBase > m_referenceModel
bool m_reportMissingModules
QPointer< ModelPart > m_root
bool m_useOldSchematics
Additional Inherited Members
Signals inherited from PaletteModel
void addSearchMaximum (int)
void incSearch ()
void loadedPart (int i, int total)
void partsToLoad (int total)
Signals inherited from ModelBase
void loadedInstances (ModelBase *, QDomElement &instances)
void loadedRoot (const QString &fileName, ModelBase *, QDomElement &root)
void loadedViews (ModelBase *, QDomElement &views)
void loadingInstance (ModelBase *, QDomElement &instance)
void loadingInstances (ModelBase *, QDomElement &instances)
void obsoleteSMDOrientationSignal ()
void oldSchematicsSignal (const QString &filename, bool &useOldSchematics)
Static Public Member Functions inherited from PaletteModel
static void initNames ()
static void setFzpOverrideFolder (const QString &)
Static Public Member Functions inherited from ModelBase
static bool onCoreList (const QString &moduleID)
Static Protected Member Functions inherited from ModelBase
static void checkMystery (QDomElement &instance)
static bool checkObsoleteOrientation (QDomElement &instance)
static bool checkOldSchematics (QDomElement &instance)
static void checkTraces (QDomElement &instance)
static bool isRatsnest (QDomElement &instance)
Static Protected Attributes inherited from PaletteModel
static QString s_fzpOverrideFolder
Static Protected Attributes inherited from ModelBase
static QList< QString > CoreList
Constructor & Destructor Documentation
SqliteReferenceModel()
SqliteReferenceModel::SqliteReferenceModel ()
References m_lastWasExactMatch, and m_swappingEnabled.
~SqliteReferenceModel()
SqliteReferenceModel::~SqliteReferenceModel ()
References deleteConnection().
Member Function Documentation
addPart() [1/2]
bool SqliteReferenceModel::addPart (ModelPart * newModel, bool update) virtual
Implements ReferenceModel.
References addPartAux(), containsModelPart(), ModelPart::moduleID(), and updatePart().
addPart() [2/2]
ModelPart * SqliteReferenceModel::addPart (QString newPartPath, bool addToReference, bool updateIdAlreadyExists) virtual
Implements ReferenceModel.
References PaletteModel::addPart().
addPartAux()
bool SqliteReferenceModel::addPartAux (ModelPart * newModel, bool fullLoad) protected
References DebugDialog::debug(), and insertPart().
allPropValues()
QMultiHash< QString, QString > SqliteReferenceModel::allPropValues (const QString & family, const QString & propName) virtual
Implements ReferenceModel.
References debugExec(), and m_swappingEnabled.
closestMatchId()
QString SqliteReferenceModel::closestMatchId (const QString & family, const QMultiHash< QString, QString > & properties, const QString & propertyName, const QString & propertyValue) protected
References getClosestMatch(), and getPossibleMatches().
containsModelPart()
bool SqliteReferenceModel::containsModelPart (const QString & moduleID) virtual
Reimplemented from PaletteModel.
References NO_ID, and partId().
countPropsInCommon()
int SqliteReferenceModel::countPropsInCommon (const QString & family, const QMultiHash< QString, QString > & properties, const ModelPart * part2) protected
References DebugDialog::debug(), and ModelPart::properties().
createDatabase()
bool SqliteReferenceModel::createDatabase (const QString & databaseName, bool fullLoad) protected
References addPartAux(), createIndexes(), createMoreIndexes(), createParts(), createProperties(), DebugDialog::debug(), debugError(), ModelPart::initConnectors(), m_database, m_keepGoing, PaletteModel::m_partHash, m_sha, and m_swappingEnabled.
createIndexes()
void SqliteReferenceModel::createIndexes () protected
References debugError().
createMoreIndexes()
void SqliteReferenceModel::createMoreIndexes (QSqlDatabase & db) protected
References debugError().
createParts()
bool SqliteReferenceModel::createParts (QSqlDatabase & db, bool fullLoad) protected
References debugError().
createProperties()
bool SqliteReferenceModel::createProperties (QSqlDatabase & db) protected
References debugError().
deleteConnection()
void SqliteReferenceModel::deleteConnection () protected
getClosestMatch()
QString SqliteReferenceModel::getClosestMatch (const QString & family, const QMultiHash< QString, QString > & properties, QStringList possibleMatches) protected
References countPropsInCommon(), and retrieveModelPart().
getPossibleMatches()
QStringList SqliteReferenceModel::getPossibleMatches (const QString & family, const QMultiHash< QString, QString > & properties, const QString & propertyName, const QString & propertyValue) protected
References debugExec().
initParts()
void SqliteReferenceModel::initParts (bool dbExists) protected virtual
Reimplemented from PaletteModel.
References PaletteModel::initParts(), and m_init.
insertBus()
bool SqliteReferenceModel::insertBus (const Bus * bus, qulonglong id) protected
References Bus::connectors(), debugExec(), Bus::id(), insertBusMember(), and m_swappingEnabled.
insertBusMember()
bool SqliteReferenceModel::insertBusMember (const Connector * connector, qulonglong id) protected
References Connector::connectorSharedID(), debugExec(), and m_swappingEnabled.
insertConnector()
bool SqliteReferenceModel::insertConnector (const class Connector * , qulonglong id) protected
References Connector::connectorSharedDescription(), Connector::connectorSharedID(), Connector::connectorSharedName(), Connector::connectorSharedReplacedby(), Connector::connectorType(), debugExec(), insertConnectorLayer(), m_swappingEnabled, and Connector::svgIdLayers().
insertConnectorLayer()
bool SqliteReferenceModel::insertConnectorLayer (const class SvgIdLayer * , qulonglong id) protected
References debugExec(), SvgIdLayer::m_hybrid, SvgIdLayer::m_legId, SvgIdLayer::m_svgId, SvgIdLayer::m_svgViewLayerID, m_swappingEnabled, SvgIdLayer::m_terminalId, and SvgIdLayer::m_viewID.
insertPart()
bool SqliteReferenceModel::insertPart (ModelPart * modelPart, bool fullLoad) protected
References ModelPart::author(), ModelPart::buses(), ModelPart::connectors(), ModelPart::date(), DebugDialog::debug(), debugExec(), DebugModelPart, ModelPart::description(), FailurePartMessages, FailurePropertyMessages, ModelPart::fritzingVersion(), FolderUtils::getAppPartsSubFolderPath(), insertBus(), insertConnector(), insertProperty(), insertSubpart(), insertTag(), insertViewImage(), ModelPart::isCore(), ModelPart::itemType(), ModelPart::label(), m_swappingEnabled, ModelPart::modelPartShared(), ModelPart::moduleID(), ModelPartShared::path(), ModelPart::path(), ModelPart::properties(), ModelPart::replacedby(), ResourcePath(), ModelPart::SchematicSubpart, ModelPart::setDBID(), ModelPart::showInLabel(), ModelPart::spice(), ModelPart::spiceModel(), ModelPartShared::subparts(), ModelPartShared::superpart(), ModelPart::tags(), ModelPart::taxonomy(), ModelPart::title(), ModelPart::version(), and ModelPart::viewImages().
insertProperty()
bool SqliteReferenceModel::insertProperty (const QString & name, const QString & value, qulonglong id, bool showInLabel) protected
References debugExec().
insertSubpart()
bool SqliteReferenceModel::insertSubpart (ModelPartShared * mps, qulonglong id) protected
References debugExec(), ModelPartShared::label(), m_swappingEnabled, and ModelPartShared::subpartID().
insertSubpartConnector()
bool SqliteReferenceModel::insertSubpartConnector (const ConnectorShared * cs, qulonglong id) protected
insertTag()
bool SqliteReferenceModel::insertTag (const QString & tag, qulonglong id) protected
References debugExec(), and m_swappingEnabled.
insertViewImage()
bool SqliteReferenceModel::insertViewImage (const struct ViewImage * , qulonglong id) protected
References ViewImage::canFlipHorizontal, ViewImage::canFlipVertical, debugExec(), ViewImage::image, ViewImage::layers, m_swappingEnabled, ViewImage::sticky, and ViewImage::viewID.
killParts()
void SqliteReferenceModel::killParts () protected
References PaletteModel::m_partHash.
lastWasExactMatch()
bool SqliteReferenceModel::lastWasExactMatch () virtual
Implements ReferenceModel.
References m_lastWasExactMatch.
loadAll()
bool SqliteReferenceModel::loadAll (const QString & databaseName, bool fullLoad, bool dbExists) virtual
Implements ReferenceModel.
References createDatabase(), DebugDialog::debug(), deleteConnection(), FailurePartMessages, FailurePropertyMessages, initParts(), PaletteModel::m_fullLoad, m_keepGoing, m_swappingEnabled, MAX_CONN_TRIES, noSwappingMessage(), and FMessageBox::warning().
loadFromDB() [1/2]
bool SqliteReferenceModel::loadFromDB (const QString & databaseName) virtual
Implements ReferenceModel.
References killParts(), m_database, m_swappingEnabled, and noSwappingMessage().
loadFromDB() [2/2]
bool SqliteReferenceModel::loadFromDB (QSqlDatabase & keep_db, QSqlDatabase & db) protected
References ModelPart::addConnector(), BusShared::addConnectorShared(), Connector::addPin(), ModelPartShared::addSubpart(), ViewLayer::BreadboardView, ViewImage::canFlipHorizontal, ViewImage::canFlipVertical, ModelBase::CoreList, ModelPart::dbid(), DebugDialog::debug(), debugError(), debugExec(), ModelPart::flipSMDAnd(), ModelPartShared::getConnectorShared(), ViewImage::image, ModelPart::initBuses(), ModelPart::initConnectors(), ModelPartShared::insertBus(), killBuses(), killConnectors(), ViewImage::layers, ModelPart::lookForZeroConnector(), PaletteModel::m_partHash, ModelBase::m_root, m_sha, MAX_CONN_TRIES, ModelPart::modelPartShared(), ModelPartShared::moduleID(), ModelPart::moduleID(), ResourcePath(), ModelPartShared::setAuthor(), ModelPartShared::setConnectorsInitialized(), ConnectorShared::setConnectorType(), ModelPart::setCore(), ModelPartShared::setDate(), ModelPartShared::setDBID(), ConnectorShared::setDescription(), ModelPartShared::setDescription(), ModelPartShared::setFamily(), ModelPartShared::setFritzingVersion(), ConnectorShared::setId(), ModelPart::setItemType(), ModelPartShared::setLabel(), ModelPart::setModelPartShared(), ModelPartShared::setModuleID(), ModelPartShared::setPath(), ModelPart::setProperty(), ConnectorShared::setReplacedby(), ModelPartShared::setReplacedby(), ConnectorShared::setSharedName(), ModelPartShared::setSpice(), ModelPartShared::setSpiceModel(), ModelPart::setSubpartID(), ModelPart::setTag(), ModelPartShared::setTaxonomy(), ModelPartShared::setTitle(), ModelPartShared::setVersion(), ModelPart::setViewImage(), ViewImage::sticky, and ViewImage::viewID.
loadPart()
ModelPart * SqliteReferenceModel::loadPart (const QString & path, bool update) virtual
Implements ReferenceModel.
References addPart(), PaletteModel::loadPart(), and m_init.
partId()
qulonglong SqliteReferenceModel::partId (QString moduleID) protected
References debugExec(), and NO_ID.
partTitle()
QString SqliteReferenceModel::partTitle (const QString & moduleID) virtual
Implements ReferenceModel.
References ___emptyString___, ModelPart::modelPartShared(), retrieveModelPart(), and ModelPartShared::title().
propValues()
QStringList SqliteReferenceModel::propValues (const QString & family, const QString & propName, bool distinct) virtual
Implements ReferenceModel.
References debugExec(), and m_swappingEnabled.
recordProperty()
void SqliteReferenceModel::recordProperty (const QString & name, const QString & value) virtual
Implements ReferenceModel.
References DebugDialog::debug(), and m_recordedProperties.
reloadPart()
ModelPart * SqliteReferenceModel::reloadPart (const QString & path, const QString & moduleID) virtual
Implements ReferenceModel.
References PaletteModel::loadPart(), PaletteModel::m_partHash, and updatePart().
removeBuses()
bool SqliteReferenceModel::removeBuses (qulonglong partId) protected
References partId(), and removex().
removeConnectors()
bool SqliteReferenceModel::removeConnectors (qulonglong partId) protected
References partId(), and removex().
removePart() [1/2]
bool SqliteReferenceModel::removePart (qulonglong partId) protected
References partId(), and removex().
removePart() [2/2]
bool SqliteReferenceModel::removePart (const QString & moduleId) protected
References PaletteModel::m_partHash, and removePartFromDataBase().
removePartFromDataBase()
bool SqliteReferenceModel::removePartFromDataBase (const QString & moduleId) protected
References NO_ID, partId(), removeBuses(), removeConnectors(), removePart(), removeProperties(), removeSchematicSubparts(), removeTags(), and removeViewImages().
removeProperties()
bool SqliteReferenceModel::removeProperties (qulonglong partId) protected
References partId(), and removex().
removeSchematicSubparts()
bool SqliteReferenceModel::removeSchematicSubparts (qulonglong partId) protected
References partId(), and removex().
removeTags()
bool SqliteReferenceModel::removeTags (qulonglong partId) protected
References partId(), and removex().
removeViewImages()
bool SqliteReferenceModel::removeViewImages (qulonglong partId) protected
References partId(), and removex().
removex()
bool SqliteReferenceModel::removex (qulonglong id, const QString & tableName, const QString & idName) protected
References DebugDialog::debug().
retrieveModelPart()
ModelPart * SqliteReferenceModel::retrieveModelPart (const QString & moduleID) virtual
Implements ReferenceModel.
References PaletteModel::m_partHash.
retrieveModuleId()
QString SqliteReferenceModel::retrieveModuleId (const QString & family, const QMultiHash< QString, QString > & properties, const QString & propertyName, bool closestMatch) virtual
Implements ReferenceModel.
References ___emptyString___, closestMatchId(), debugExec(), and m_lastWasExactMatch.
retrieveModuleIdWith()
QString SqliteReferenceModel::retrieveModuleIdWith (const QString & family, const QString & propertyName, bool closestMatch) virtual
Implements ReferenceModel.
References m_recordedProperties, and retrieveModuleId().
setSha()
void SqliteReferenceModel::setSha (const QString & sha) virtual
Implements ReferenceModel.
References m_sha, and sha().
sha()
const QString & SqliteReferenceModel::sha () const virtual
Implements ReferenceModel.
References m_sha.
swapEnabled()
bool SqliteReferenceModel::swapEnabled () const virtual
Implements ReferenceModel.
References m_swappingEnabled.
updatePart()
bool SqliteReferenceModel::updatePart (ModelPart * newModel) virtual
Implements ReferenceModel.
References addPartAux(), m_swappingEnabled, ModelPart::moduleID(), and removePartFromDataBase().
Member Data Documentation
m_database
QSqlDatabase SqliteReferenceModel::m_database protected
m_init
bool SqliteReferenceModel::m_init protected
m_keepGoing
volatile bool SqliteReferenceModel::m_keepGoing protected
m_lastWasExactMatch
volatile bool SqliteReferenceModel::m_lastWasExactMatch protected
m_recordedProperties
QMultiHash<QString , QString > SqliteReferenceModel::m_recordedProperties protected
m_sha
QString SqliteReferenceModel::m_sha protected
m_swappingEnabled
volatile bool SqliteReferenceModel::m_swappingEnabled protected
The documentation for this class was generated from the following files:
referencemodel/sqlitereferencemodel.h
referencemodel/sqlitereferencemodel.cpp