Fritzing: ConnectorsInfoWidget Class Reference
ConnectorsInfoWidget Class Reference
#include <connectorsinfowidget.h>
Public Slots
void addConnector ()
void connectorsFound (QList< QPointer< Connector > >)
void emitPaintNeeded ()
void informConnectorSelection (const QString &)
void informEditionCompleted ()
void removeConnector (AbstractConnectorInfoWidget *connInfo)
void removeSelectedConnector ()
void removeTerminalPoint (const QString &connId, ViewLayer::ViewIdentifier vid)
void syncNewConnectors (ViewLayer::ViewIdentifier viewId, const QList< QPointer< Connector > > &conns)
Signals
void connectorSelected (const QString &)
void drawConnector (Connector *)
void drawConnector (ViewLayer::ViewIdentifier, Connector *)
void editionCompleted ()
void existingConnectorSignal (ViewLayer::ViewIdentifier viewId, const QString &id, Connector *existingConnector, Connector *newConnector)
void removeConnectorFrom (const QString &connId, ViewLayer::ViewIdentifier view)
void repaintNeeded ()
void setMismatching (ViewLayer::ViewIdentifier viewId, const QString &connId, bool mismatching)
void showTerminalPoints (bool show)
Public Member Functions
ConnectorsInfoWidget (WaitPushUndoStack *undoStack, QWidget *parent=0)
bool connectorAdded ()
bool connectorsCountChanged ()
bool connectorsRemoved ()
const QList< QPointer< ConnectorShared > > connectorsShared ()
bool hasMismatchingConnectors ()
int scrollBarWidth ()
void setViews (PartsEditorViewsWidget *connsView)
QCheckBox * showTerminalPointsCheckBox ()
Protected Slots
void completeConn (MismatchingConnectorWidget *mcw)
void connectorSelectedInView (const QString &connId)
void deleteAux ()
void selectionChanged (AbstractConnectorInfoWidget *selected)
void updateLayout ()
Protected Member Functions
void addConnectorInfo (MismatchingConnectorWidget *mcw)
Connector * addConnectorInfo (QString id)
void addConnectorInfo (Connector *conn)
void addMismatchingConnectorInfo (MismatchingConnectorWidget *mcw)
void addMismatchingConnectorInfo (ViewLayer::ViewIdentifier viewID, QString connId)
void clearMismatchingForView (ViewLayer::ViewIdentifier viewId)
void createScrollArea ()
void createToolsArea ()
bool eventFilter (QObject *obj, QEvent *event)
bool existingConnId (const QString &id)
MismatchingConnectorWidget * existingMismatchingConnector (const QString &id)
Connector * findConnector (const QString &id)
SingleConnectorInfoWidget * findSCI (const QString &id)
int nextConnId ()
void removeConnectorInfo (SingleConnectorInfoWidget *sci, bool singleShot=true, bool alsoDeleteFromView=false)
void removeMismatchingConnectorInfo (MismatchingConnectorWidget *mcw, bool singleShot=true, bool alsoDeleteFromView=false)
void resetName (ViewLayer::ViewIdentifier viewId, SingleConnectorInfoWidget *sci, Connector *conn)
void resetType (ViewLayer::ViewIdentifier viewId, SingleConnectorInfoWidget *sci, Connector *conn)
QVBoxLayout * scrollContentLayout ()
void selectNext ()
void selectPrev ()
void setSelected (AbstractConnectorInfoWidget *newSelected)
void singleToMismatchingNotInView (ViewLayer::ViewIdentifier viewId, const QStringList &connIds)
Protected Attributes
QHash< QString, AbstractConnectorInfoWidget * > m_allConnsInfo
bool m_connAdded
QStringList m_connIds
bool m_connRemoved
QList< SingleConnectorInfoWidget * > m_connsInfo
QList< QPointer< MismatchingConnectorWidget > > m_mismatchConnsInfo
QFrame * m_mismatchersFrame
QFrame * m_mismatchersFrameParent
QObject * m_objToDelete
QScrollArea * m_scrollArea
QFrame * m_scrollContent
AbstractConnectorInfoWidget * m_selected
QLabel * m_title
QFrame * m_toolsContainter
WaitPushUndoStack * m_undoStack
PartsEditorViewsWidget * m_views
Constructor & Destructor Documentation
ConnectorsInfoWidget()
ConnectorsInfoWidget::ConnectorsInfoWidget (WaitPushUndoStack * undoStack, QWidget * parent = 0)
References createScrollArea(), createToolsArea(), m_connAdded, m_connRemoved, m_objToDelete, m_scrollArea, m_selected, m_title, m_toolsContainter, m_undoStack, and m_views.
Member Function Documentation
addConnector
void ConnectorsInfoWidget::addConnector () slot
References addConnectorInfo(), PartsEditorViewsWidget::breadboardView(), drawConnector(), m_allConnsInfo, m_connAdded, m_views, PartsEditorView::myItem(), nextConnId(), PartsEditorViewsWidget::pcbView(), PartsEditorViewsWidget::schematicView(), and setSelected().
addConnectorInfo() [1/3]
void ConnectorsInfoWidget::addConnectorInfo (MismatchingConnectorWidget * mcw) protected
References MismatchingConnectorWidget::connId(), and MismatchingConnectorWidget::prevConn().
addConnectorInfo() [2/3]
Connector * ConnectorsInfoWidget::addConnectorInfo (QString id) protected
References addConnectorInfo(), ConnectorShared::addPin(), PartsEditorViewsWidget::breadboardView(), ViewLayer::BreadboardView, PartsEditorView::connectorsLayerId(), m_views, PartsEditorViewsWidget::pcbView(), ViewLayer::PCBView, PartsEditorViewsWidget::schematicView(), ViewLayer::SchematicView, ConnectorShared::setId(), PartsEditorView::svgIdForConnector(), and PartsEditorView::terminalIdForConnector().
addConnectorInfo() [3/3]
void ConnectorsInfoWidget::addConnectorInfo (Connector * conn) protected
References Connector::connectorSharedID(), editionCompleted(), informConnectorSelection(), m_allConnsInfo, m_connIds, m_connsInfo, m_scrollContent, m_undoStack, scrollContentLayout(), selectionChanged(), and updateLayout().
addMismatchingConnectorInfo() [1/2]
void ConnectorsInfoWidget::addMismatchingConnectorInfo (MismatchingConnectorWidget * mcw) protected
References informConnectorSelection(), m_allConnsInfo, m_mismatchConnsInfo, m_mismatchersFrame, m_mismatchersFrameParent, selectionChanged(), and setMismatching().
addMismatchingConnectorInfo() [2/2]
void ConnectorsInfoWidget::addMismatchingConnectorInfo (ViewLayer::ViewIdentifier viewID, QString connId) protected
References addMismatchingConnectorInfo(), completeConn(), m_connIds, and m_mismatchersFrame.
clearMismatchingForView()
void ConnectorsInfoWidget::clearMismatchingForView (ViewLayer::ViewIdentifier viewId) protected
References m_mismatchConnsInfo, removeMismatchingConnectorInfo(), and MismatchingConnectorWidget::views().
completeConn
void ConnectorsInfoWidget::completeConn (MismatchingConnectorWidget * mcw) protected slot
References addConnectorInfo(), MismatchingConnectorWidget::connId(), drawConnector(), findConnector(), PartsEditorViewsWidget::imagesLoadedInAllViews(), m_views, MismatchingConnectorWidget::missingViews(), MismatchingConnectorWidget::prevConn(), removeMismatchingConnectorInfo(), setMismatching(), and MismatchingConnectorWidget::views().
connectorAdded()
bool ConnectorsInfoWidget::connectorAdded ()
References m_connAdded.
connectorsCountChanged()
bool ConnectorsInfoWidget::connectorsCountChanged ()
References connectorAdded(), and connectorsRemoved().
connectorSelected
void ConnectorsInfoWidget::connectorSelected (const QString &) signal
connectorSelectedInView
void ConnectorsInfoWidget::connectorSelectedInView (const QString & connId) protected slot
References m_allConnsInfo, and setSelected().
connectorsFound
void ConnectorsInfoWidget::connectorsFound (QList< QPointer< Connector > > conns) slot
References addConnectorInfo(), ProcessEventBlocker::processEvents(), and updateLayout().
connectorsRemoved()
bool ConnectorsInfoWidget::connectorsRemoved ()
References m_connRemoved.
connectorsShared()
const QList< QPointer< ConnectorShared > > ConnectorsInfoWidget::connectorsShared ()
References SingleConnectorInfoWidget::connector(), Connector::connectorShared(), SingleConnectorInfoWidget::description(), SingleConnectorInfoWidget::id(), m_connsInfo, SingleConnectorInfoWidget::name(), ConnectorShared::setConnectorType(), ConnectorShared::setDescription(), ConnectorShared::setId(), ConnectorShared::setSharedName(), and SingleConnectorInfoWidget::type().
createScrollArea()
void ConnectorsInfoWidget::createScrollArea () protected
References m_mismatchersFrame, m_mismatchersFrameParent, m_scrollArea, m_scrollContent, m_title, and scrollContentLayout().
createToolsArea()
void ConnectorsInfoWidget::createToolsArea () protected
References addConnector(), and m_toolsContainter.
deleteAux
void ConnectorsInfoWidget::deleteAux () protected slot
References m_objToDelete, and m_selected.
drawConnector [1/2]
void ConnectorsInfoWidget::drawConnector (Connector *) signal
drawConnector [2/2]
void ConnectorsInfoWidget::drawConnector (ViewLayer::ViewIdentifier , Connector *) signal
editionCompleted
void ConnectorsInfoWidget::editionCompleted () signal
emitPaintNeeded
void ConnectorsInfoWidget::emitPaintNeeded () slot
References repaintNeeded().
eventFilter()
bool ConnectorsInfoWidget::eventFilter (QObject * obj, QEvent * event) protected
References selectNext(), and selectPrev().
existingConnectorSignal
void ConnectorsInfoWidget::existingConnectorSignal (ViewLayer::ViewIdentifier viewId, const QString & id, Connector * existingConnector, Connector * newConnector) signal
existingConnId()
bool ConnectorsInfoWidget::existingConnId (const QString & id) protected
References findConnector().
existingMismatchingConnector()
MismatchingConnectorWidget * ConnectorsInfoWidget::existingMismatchingConnector (const QString & id) protected
References MismatchingConnectorWidget::connId(), and m_mismatchConnsInfo.
findConnector()
Connector * ConnectorsInfoWidget::findConnector (const QString & id) protected
References SingleConnectorInfoWidget::connector(), SingleConnectorInfoWidget::id(), and m_connsInfo.
findSCI()
SingleConnectorInfoWidget * ConnectorsInfoWidget::findSCI (const QString & id) protected
References SingleConnectorInfoWidget::id(), and m_connsInfo.
hasMismatchingConnectors()
bool ConnectorsInfoWidget::hasMismatchingConnectors ()
References m_mismatchConnsInfo.
informConnectorSelection
void ConnectorsInfoWidget::informConnectorSelection (const QString & connId) slot
References connectorSelected().
informEditionCompleted
void ConnectorsInfoWidget::informEditionCompleted () slot
References editionCompleted().
nextConnId()
int ConnectorsInfoWidget::nextConnId () protected
References m_connIds.
removeConnector
void ConnectorsInfoWidget::removeConnector (AbstractConnectorInfoWidget * connInfo) slot
References removeConnectorInfo(), and removeMismatchingConnectorInfo().
removeConnectorFrom
void ConnectorsInfoWidget::removeConnectorFrom (const QString & connId, ViewLayer::ViewIdentifier view) signal
removeConnectorInfo()
void ConnectorsInfoWidget::removeConnectorInfo (SingleConnectorInfoWidget * sci, bool singleShot = true, bool alsoDeleteFromView = false) protected
References ViewLayer::AllViews, deleteAux(), SingleConnectorInfoWidget::id(), m_allConnsInfo, m_connRemoved, m_connsInfo, m_objToDelete, m_selected, removeConnectorFrom(), and scrollContentLayout().
removeMismatchingConnectorInfo()
void ConnectorsInfoWidget::removeMismatchingConnectorInfo (MismatchingConnectorWidget * mcw, bool singleShot = true, bool alsoDeleteFromView = false) protected
References ViewLayer::AllViews, MismatchingConnectorWidget::connId(), deleteAux(), m_allConnsInfo, m_mismatchConnsInfo, m_mismatchersFrame, m_mismatchersFrameParent, m_objToDelete, m_selected, removeConnectorFrom(), setMismatching(), updateLayout(), and MismatchingConnectorWidget::views().
removeSelectedConnector
void ConnectorsInfoWidget::removeSelectedConnector () slot
References m_selected, and removeConnector().
removeTerminalPoint
void ConnectorsInfoWidget::removeTerminalPoint (const QString & connId, ViewLayer::ViewIdentifier vid) slot
References ___emptyString___, SingleConnectorInfoWidget::connector(), Connector::connectorShared(), Connector::connectorSharedID(), m_connsInfo, SvgIdLayer::m_terminalId, and ConnectorShared::pins().
repaintNeeded
void ConnectorsInfoWidget::repaintNeeded () signal
resetName()
void ConnectorsInfoWidget::resetName (ViewLayer::ViewIdentifier viewId, SingleConnectorInfoWidget * sci, Connector * conn) protected
References Connector::connectorSharedName(), SingleConnectorInfoWidget::name(), and SingleConnectorInfoWidget::setName().
resetType()
void ConnectorsInfoWidget::resetType (ViewLayer::ViewIdentifier viewId, SingleConnectorInfoWidget * sci, Connector * conn) protected
References Connector::connectorType(), SingleConnectorInfoWidget::connectorType(), Connector::Male, Connector::Pad, ViewLayer::PCBView, and SingleConnectorInfoWidget::setConnectorType().
scrollBarWidth()
int ConnectorsInfoWidget::scrollBarWidth ()
References m_scrollArea.
scrollContentLayout()
QVBoxLayout * ConnectorsInfoWidget::scrollContentLayout () protected
References m_scrollContent.
selectionChanged
void ConnectorsInfoWidget::selectionChanged (AbstractConnectorInfoWidget * selected) protected slot
References emitPaintNeeded(), m_selected, and AbstractConnectorInfoWidget::setSelected().
selectNext()
void ConnectorsInfoWidget::selectNext () protected
References m_connsInfo, m_mismatchConnsInfo, m_selected, and setSelected().
selectPrev()
void ConnectorsInfoWidget::selectPrev () protected
References m_connsInfo, m_mismatchConnsInfo, m_selected, and setSelected().
setMismatching
void ConnectorsInfoWidget::setMismatching (ViewLayer::ViewIdentifier viewId, const QString & connId, bool mismatching) signal
setSelected()
void ConnectorsInfoWidget::setSelected (AbstractConnectorInfoWidget * newSelected) protected
References m_selected, selectionChanged(), and AbstractConnectorInfoWidget::setSelected().
setViews()
void ConnectorsInfoWidget::setViews (PartsEditorViewsWidget * connsView)
References m_views.
showTerminalPoints
void ConnectorsInfoWidget::showTerminalPoints (bool show) signal
showTerminalPointsCheckBox()
QCheckBox* ConnectorsInfoWidget::showTerminalPointsCheckBox ()
singleToMismatchingNotInView()
void ConnectorsInfoWidget::singleToMismatchingNotInView (ViewLayer::ViewIdentifier viewId, const QStringList & connIds) protected
References addMismatchingConnectorInfo(), completeConn(), SingleConnectorInfoWidget::id(), m_connsInfo, m_mismatchersFrame, m_mismatchersFrameParent, removeConnectorInfo(), scrollContentLayout(), SingleConnectorInfoWidget::toMismatching(), and updateLayout().
syncNewConnectors
void ConnectorsInfoWidget::syncNewConnectors (ViewLayer::ViewIdentifier viewId, const QList< QPointer< Connector > > & conns) slot
References addConnectorInfo(), addMismatchingConnectorInfo(), MismatchingConnectorWidget::addViewPresence(), clearMismatchingForView(), SingleConnectorInfoWidget::connector(), Connector::connectorSharedID(), MismatchingConnectorWidget::connId(), existingConnectorSignal(), existingConnId(), existingMismatchingConnector(), findSCI(), MismatchingConnectorWidget::onlyMissingThisView(), MismatchingConnectorWidget::prevConn(), removeMismatchingConnectorInfo(), resetName(), resetType(), setMismatching(), and singleToMismatchingNotInView().
updateLayout
void ConnectorsInfoWidget::updateLayout () protected slot
References m_mismatchersFrame, m_mismatchersFrameParent, and m_scrollContent.
Member Data Documentation
m_allConnsInfo
QHash<QString , AbstractConnectorInfoWidget*> ConnectorsInfoWidget::m_allConnsInfo protected
m_connAdded
bool ConnectorsInfoWidget::m_connAdded protected
m_connIds
QStringList ConnectorsInfoWidget::m_connIds protected
m_connRemoved
bool ConnectorsInfoWidget::m_connRemoved protected
m_connsInfo
QList<SingleConnectorInfoWidget*> ConnectorsInfoWidget::m_connsInfo protected
m_mismatchConnsInfo
QList< QPointer<MismatchingConnectorWidget> > ConnectorsInfoWidget::m_mismatchConnsInfo protected
m_mismatchersFrame
QFrame* ConnectorsInfoWidget::m_mismatchersFrame protected
m_mismatchersFrameParent
QFrame* ConnectorsInfoWidget::m_mismatchersFrameParent protected
m_objToDelete
QObject* ConnectorsInfoWidget::m_objToDelete protected
m_scrollArea
QScrollArea* ConnectorsInfoWidget::m_scrollArea protected
m_scrollContent
QFrame* ConnectorsInfoWidget::m_scrollContent protected
m_selected
AbstractConnectorInfoWidget* ConnectorsInfoWidget::m_selected protected
m_title
QLabel* ConnectorsInfoWidget::m_title protected
m_toolsContainter
QFrame* ConnectorsInfoWidget::m_toolsContainter protected
m_undoStack
WaitPushUndoStack* ConnectorsInfoWidget::m_undoStack protected
m_views
PartsEditorViewsWidget* ConnectorsInfoWidget::m_views protected
The documentation for this class was generated from the following files:
partseditor/obsolete/connectorsinfowidget.h
partseditor/obsolete/connectorsinfowidget.cpp