Fritzing: ZoomLabel Class Reference
ZoomLabel Class Reference
#include <zoomslider.h>
Signals
void clicked ()
Public Member Functions
ZoomLabel (QWidget *parent)
~ZoomLabel ()
void mouseMoveEvent (QMouseEvent *)
void mousePressEvent (QMouseEvent *)
void mouseReleaseEvent (QMouseEvent *)
void setAutoRepeat (bool)
void setImages (const QString &normal, const QString &pressed)
Protected Slots
void repeat ()
Protected Attributes
bool m_autoRepeat
bool m_mouseIsDown
bool m_mouseIsIn
QPixmap m_normal
QPixmap m_pressed
bool m_repeated
QTimer m_timer
Constructor & Destructor Documentation
ZoomLabel()
ZoomLabel::ZoomLabel (QWidget * parent)
References AutoRepeatDelay, AutoRepeatInterval, m_autoRepeat, m_mouseIsDown, m_mouseIsIn, m_repeated, m_timer, and repeat().
~ZoomLabel()
ZoomLabel::~ZoomLabel ()
Member Function Documentation
clicked
void ZoomLabel::clicked () signal
mouseMoveEvent()
void ZoomLabel::mouseMoveEvent (QMouseEvent * event)
References AutoRepeatDelay, m_mouseIsDown, m_mouseIsIn, m_normal, m_pressed, and m_timer.
mousePressEvent()
void ZoomLabel::mousePressEvent (QMouseEvent * event)
References AutoRepeatDelay, m_autoRepeat, m_mouseIsDown, m_mouseIsIn, m_pressed, m_repeated, and m_timer.
mouseReleaseEvent()
void ZoomLabel::mouseReleaseEvent (QMouseEvent * event)
References clicked(), m_mouseIsDown, m_mouseIsIn, m_normal, m_repeated, and m_timer.
repeat
void ZoomLabel::repeat () protected slot
References clicked(), m_mouseIsDown, m_mouseIsIn, and m_repeated.
setAutoRepeat()
void ZoomLabel::setAutoRepeat (bool autoRepeat)
References m_autoRepeat.
setImages()
void ZoomLabel::setImages (const QString & normal, const QString & pressed)
References m_normal, and m_pressed.
Member Data Documentation
m_autoRepeat
bool ZoomLabel::m_autoRepeat protected
m_mouseIsDown
bool ZoomLabel::m_mouseIsDown protected
m_mouseIsIn
bool ZoomLabel::m_mouseIsIn protected
m_normal
QPixmap ZoomLabel::m_normal protected
m_pressed
QPixmap ZoomLabel::m_pressed protected
m_repeated
bool ZoomLabel::m_repeated protected
m_timer
QTimer ZoomLabel::m_timer protected
The documentation for this class was generated from the following files:
utils/zoomslider.h
utils/zoomslider.cpp