Fritzing: StackTabWidget Class Reference
StackTabWidget Class Reference
#include <stacktabwidget.h>
Public Slots
void informCurrentChanged (int index)
void informTabCloseRequested (int index)
Signals
void currentChanged (StackTabWidget *, int index)
void tabCloseRequested (StackTabWidget *, int index)
Public Member Functions
StackTabWidget (QWidget *parent)
class StackTabBar * stackTabBar ()
Constructor & Destructor Documentation
StackTabWidget()
StackTabWidget::StackTabWidget (QWidget * parent)
References currentChanged(), informCurrentChanged(), informTabCloseRequested(), and tabCloseRequested().
Member Function Documentation
currentChanged
void StackTabWidget::currentChanged (StackTabWidget * , int index) signal
informCurrentChanged
void StackTabWidget::informCurrentChanged (int index) slot
References currentChanged().
informTabCloseRequested
void StackTabWidget::informTabCloseRequested (int index) slot
References tabCloseRequested().
stackTabBar()
StackTabBar * StackTabWidget::stackTabBar ()
tabCloseRequested
void StackTabWidget::tabCloseRequested (StackTabWidget * , int index) signal
The documentation for this class was generated from the following files:
partsbinpalette/binmanager/stacktabwidget.h
partsbinpalette/binmanager/stacktabwidget.cpp