Fritzing: ChangeZCommand Class Reference
ChangeZCommand Class Reference
#include <commands.h>
Public Member Functions
ChangeZCommand (class SketchWidget *sketchWidget, QUndoCommand *parent)
~ChangeZCommand ()
void addTriplet (long id, double oldZ, double newZ)
void redo ()
void undo ()
Public Member Functions inherited from BaseCommand
BaseCommand (BaseCommand::CrossViewType, SketchWidget *, QUndoCommand *parent)
~BaseCommand ()
void addSubCommand (BaseCommand *subCommand)
BaseCommand::CrossViewType crossViewType () const noexcept
virtual QString getDebugString () const
int index () const
const QUndoCommand * parentCommand () const
void redo ()
void setCrossViewType (BaseCommand::CrossViewType)
void setRedoOnly ()
void setSkipFirstRedo ()
void setUndoOnly ()
SketchWidget * sketchWidget () const
const BaseCommand * subCommand (int index) const
int subCommandCount () const
void subRedo ()
void subRedo (int index)
void subUndo ()
void subUndo (int index)
void undo ()
Protected Member Functions
QString getParamString () const
Static Protected Member Functions
static double first (RealPair *)
static double second (RealPair *)
Protected Attributes
QHash< long, RealPair * > m_triplets
Protected Attributes inherited from BaseCommand
QList< BaseCommand * > m_commands
BaseCommand::CrossViewType m_crossViewType
int m_index = 0
QUndoCommand * m_parentCommand = nullptr
bool m_redoOnly = false
SketchWidget * m_sketchWidget = nullptr
bool m_skipFirstRedo = false
bool m_undoOnly = false
Additional Inherited Members
Public Types inherited from BaseCommand
enum CrossViewType { SingleView, CrossView }
Static Public Member Functions inherited from BaseCommand
static void clearProgress ()
static CommandProgress * initProgress ()
static int totalChildCount (const QUndoCommand *)
Static Protected Attributes inherited from BaseCommand
static CommandProgress m_commandProgress
static int nextIndex = 0
Constructor & Destructor Documentation
ChangeZCommand()
ChangeZCommand::ChangeZCommand (class SketchWidget * sketchWidget, QUndoCommand * parent)
~ChangeZCommand()
ChangeZCommand::~ChangeZCommand ()
References m_triplets.
Member Function Documentation
addTriplet()
void ChangeZCommand::addTriplet (long id, double oldZ, double newZ)
References m_triplets.
first()
double ChangeZCommand::first (RealPair * pair) static protected
getParamString()
QString ChangeZCommand::getParamString () const protected virtual
Reimplemented from BaseCommand.
References BaseCommand::getParamString().
redo()
void ChangeZCommand::redo ()
References SketchWidget::changeZ(), BaseCommand::m_sketchWidget, m_triplets, BaseCommand::redo(), and second().
second()
double ChangeZCommand::second (RealPair * pair) static protected
undo()
void ChangeZCommand::undo ()
References SketchWidget::changeZ(), first(), BaseCommand::m_sketchWidget, m_triplets, and BaseCommand::undo().
Member Data Documentation
m_triplets
QHash<long, RealPair *> ChangeZCommand::m_triplets protected
The documentation for this class was generated from the following files:
commands.h
commands.cpp