Fritzing: ErcData Class Reference
ErcData Class Reference
#include <ercdata.h>
Public Types
enum CurrentFlow { Source, Sink, UnknownFlow }
enum EType { Ground, VCC, UnknownEType }
enum Ignore { Never, Always, IfUnconnected }
Public Member Functions
ErcData (const QDomElement &ercElement)
constexpr EType eType () const noexcept
constexpr Ignore ignore () const noexcept
bool writeToElement (QDomElement &ercElement, QDomDocument &doc)
Protected Member Functions
void readCurrent (QDomElement &)
void readVoltage (QDomElement &)
void writeCurrent (QDomElement &, QDomDocument &)
void writeVoltage (QDomElement &, QDomDocument &)
Protected Attributes
ValidReal m_current
CurrentFlow m_currentFlow
ValidReal m_currentMax
ValidReal m_currentMin
EType m_eType
Ignore m_ignore
ValidReal m_voltage
ValidReal m_voltageMax
ValidReal m_voltageMin
Member Enumeration Documentation
CurrentFlow
enum ErcData::CurrentFlow
Enumerator
Source
Sink
UnknownFlow
EType
enum ErcData::EType
Enumerator
Ground
VCC
UnknownEType
Ignore
enum ErcData::Ignore
Enumerator
Never
Always
IfUnconnected
Constructor & Destructor Documentation
ErcData()
ErcData::ErcData (const QDomElement & ercElement)
References Always, eType(), Ground, IfUnconnected, m_eType, m_ignore, readCurrent(), readVoltage(), and VCC.
Member Function Documentation
eType()
constexpr EType ErcData::eType () const inline noexcept
References m_eType.
ignore()
constexpr Ignore ErcData::ignore () const inline noexcept
References m_ignore.
readCurrent()
void ErcData::readCurrent (QDomElement & currentElement) protected
References m_current, m_currentFlow, m_currentMax, m_currentMin, ValidReal::setValue(), Sink, Source, and UnknownFlow.
readVoltage()
void ErcData::readVoltage (QDomElement & voltageElement) protected
References m_voltage, m_voltageMax, m_voltageMin, and ValidReal::setValue().
writeCurrent()
void ErcData::writeCurrent (QDomElement & parent, QDomDocument & doc) protected
References m_current, m_currentFlow, m_currentMax, m_currentMin, Sink, Source, UnknownFlow, and ValidReal::value().
writeToElement()
bool ErcData::writeToElement (QDomElement & ercElement, QDomDocument & doc)
References Ground, m_eType, VCC, writeCurrent(), and writeVoltage().
writeVoltage()
void ErcData::writeVoltage (QDomElement & parent, QDomDocument & doc) protected
References m_voltage, m_voltageMax, m_voltageMin, and ValidReal::value().
Member Data Documentation
m_current
ValidReal ErcData::m_current protected
m_currentFlow
CurrentFlow ErcData::m_currentFlow protected
m_currentMax
ValidReal ErcData::m_currentMax protected
m_currentMin
ValidReal ErcData::m_currentMin protected
m_eType
EType ErcData::m_eType protected
m_ignore
Ignore ErcData::m_ignore protected
m_voltage
ValidReal ErcData::m_voltage protected
m_voltageMax
ValidReal ErcData::m_voltageMax protected
m_voltageMin
ValidReal ErcData::m_voltageMin protected
The documentation for this class was generated from the following files:
connectors/ercdata.h
connectors/ercdata.cpp