Fritzing: ResizeHandle Class Reference
ResizeHandle Class Reference
#include <resizehandle.h>
Public Slots
void zoomChangedSlot (double scale)
Signals
void mouseMoveSignal (QGraphicsSceneMouseEvent *event, ResizeHandle *)
void mousePressSignal (QGraphicsSceneMouseEvent *event, ResizeHandle *)
void mouseReleaseSignal (QGraphicsSceneMouseEvent *event, ResizeHandle *)
void zoomChangedSignal (double scale)
Public Member Functions
ResizeHandle (const QPixmap &pixmap, const QCursor &, bool ignoresTransforms, QGraphicsItem *parent=0)
~ResizeHandle ()
double currentScale ()
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)
QPointF resizeOffset ()
void setResizeOffset (QPointF)
Protected Member Functions
QVariant itemChange (GraphicsItemChange change, const QVariant &value)
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
void mousePressEvent (QGraphicsSceneMouseEvent *event)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
bool scaling ()
Protected Attributes
QPointF m_resizeOffset
Constructor & Destructor Documentation
ResizeHandle()
ResizeHandle::ResizeHandle (const QPixmap & pixmap, const QCursor & cursor, bool ignoresTransforms, QGraphicsItem * parent = 0)
~ResizeHandle()
ResizeHandle::~ResizeHandle ()
Member Function Documentation
currentScale()
double ResizeHandle::currentScale ()
References ZoomableGraphicsView::currentZoom(), and scaling().
itemChange()
QVariant ResizeHandle::itemChange (GraphicsItemChange change, const QVariant & value) protected
References scaling(), and zoomChangedSlot().
mouseMoveEvent()
void ResizeHandle::mouseMoveEvent (QGraphicsSceneMouseEvent * event) protected
References mouseMoveSignal().
mouseMoveSignal
void ResizeHandle::mouseMoveSignal (QGraphicsSceneMouseEvent * event, ResizeHandle *) signal
mousePressEvent()
void ResizeHandle::mousePressEvent (QGraphicsSceneMouseEvent * event) protected
References mousePressSignal().
mousePressSignal
void ResizeHandle::mousePressSignal (QGraphicsSceneMouseEvent * event, ResizeHandle *) signal
mouseReleaseEvent()
void ResizeHandle::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected
References mouseReleaseSignal().
mouseReleaseSignal
void ResizeHandle::mouseReleaseSignal (QGraphicsSceneMouseEvent * event, ResizeHandle *) signal
paint()
void ResizeHandle::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0)
References FGraphicsScene::displayHandles().
resizeOffset()
QPointF ResizeHandle::resizeOffset ()
References m_resizeOffset.
scaling()
bool ResizeHandle::scaling () protected
setResizeOffset()
void ResizeHandle::setResizeOffset (QPointF p)
References m_resizeOffset.
zoomChangedSignal
void ResizeHandle::zoomChangedSignal (double scale) signal
zoomChangedSlot
void ResizeHandle::zoomChangedSlot (double scale) slot
References zoomChangedSignal().
Member Data Documentation
m_resizeOffset
QPointF ResizeHandle::m_resizeOffset protected
The documentation for this class was generated from the following files:
utils/resizehandle.h
utils/resizehandle.cpp