Fritzing: SetColorDialog Class Reference
SetColorDialog Class Reference
#include <setcolordialog.h>
Public Member Functions
SetColorDialog (const QString &message, QColor &currentColor, QColor &standardColor, bool askPrefs, QWidget *parent=0)
~SetColorDialog ()=default
bool isPrefsColor ()
const QColor & selectedColor () const noexcept
Protected Slots
void selectCurrent ()
void selectCustom ()
void selectLastCustom ()
void selectStandard ()
Protected Member Functions
void setColor (const QColor &)
void setCustomColor (const QColor &)
Protected Attributes
QColor m_currentColor
QLabel * m_currentColorLabel
QColor m_customColor
QLabel * m_customColorLabel
QString m_message
QCheckBox * m_prefsCheckBox
QColor m_selectedColor
QLabel * m_selectedColorLabel
QColor m_standardColor
QLabel * m_standardColorLabel
Constructor & Destructor Documentation
SetColorDialog()
SetColorDialog::SetColorDialog (const QString & message, QColor & currentColor, QColor & standardColor, bool askPrefs, QWidget * parent = 0)
References BUTTON_WIDTH, m_prefsCheckBox, m_selectedColorLabel, m_standardColorLabel, MARGIN, selectCustom(), selectStandard(), setColor(), and setCustomColor().
~SetColorDialog()
SetColorDialog::~SetColorDialog () default
Member Function Documentation
isPrefsColor()
bool SetColorDialog::isPrefsColor ()
References m_prefsCheckBox.
selectCurrent
void SetColorDialog::selectCurrent () protected slot
References m_currentColor, and setColor().
selectCustom
void SetColorDialog::selectCustom () protected slot
References getColor(), m_message, m_selectedColor, setColor(), and setCustomColor().
selectedColor()
const QColor& SetColorDialog::selectedColor () const inline noexcept
References m_selectedColor.
selectLastCustom
void SetColorDialog::selectLastCustom () protected slot
References m_customColor, and setColor().
selectStandard
void SetColorDialog::selectStandard () protected slot
References m_standardColor, and setColor().
setColor()
void SetColorDialog::setColor (const QColor & color) protected
References m_selectedColor, and m_selectedColorLabel.
setCustomColor()
void SetColorDialog::setCustomColor (const QColor & color) protected
References m_customColor.
Member Data Documentation
m_currentColor
QColor SetColorDialog::m_currentColor protected
m_currentColorLabel
QLabel* SetColorDialog::m_currentColorLabel protected
m_customColor
QColor SetColorDialog::m_customColor protected
m_customColorLabel
QLabel* SetColorDialog::m_customColorLabel protected
m_message
QString SetColorDialog::m_message protected
m_prefsCheckBox
QCheckBox* SetColorDialog::m_prefsCheckBox protected
m_selectedColor
QColor SetColorDialog::m_selectedColor protected
m_selectedColorLabel
QLabel* SetColorDialog::m_selectedColorLabel protected
m_standardColor
QColor SetColorDialog::m_standardColor protected
m_standardColorLabel
QLabel* SetColorDialog::m_standardColorLabel protected
The documentation for this class was generated from the following files:
dialogs/setcolordialog.h
dialogs/setcolordialog.cpp