Fritzing: autoroute/mazerouter/mazerouter.cpp File Reference
mazerouter.cpp File Reference
#include "mazerouter.h"
#include "../../sketch/pcbsketchwidget.h"
#include "../../debugdialog.h"
#include "../../items/virtualwire.h"
#include "../../items/tracewire.h"
#include "../../items/jumperitem.h"
#include "../../items/symbolpaletteitem.h"
#include "../../items/via.h"
#include "../../items/resizableboard.h"
#include "../../utils/graphicsutils.h"
#include "../../utils/graphutils.h"
#include "../../utils/textutils.h"
#include "../../utils/folderutils.h"
#include "../../connectors/connectoritem.h"
#include "../../items/moduleidnames.h"
#include "../../processeventblocker.h"
#include "../../svg/groundplanegenerator.h"
#include "../../svg/svgfilesplitter.h"
#include "../../fsvgrenderer.h"
#include "../drc.h"
#include "../../connectors/svgidlayer.h"
#include <QApplication>
#include <QMessageBox>
#include <QSettings>
#include <qmath.h>
#include <limits>
Functions
bool atLeast (const QPointF &p1, const QPointF &p2)
bool byOrder (Trace &t1, Trace &t2)
bool byPinsWithin (Net *n1, Net *n2)
double distanceCost (const QPoint &p1, const QPoint &p2)
void fastCopy (QImage *from, QImage *to)
uint getColor (GridValue val)
QString getPartID (const QDomElement &element)
QPointF getPixelCenter (GridPoint &gp, QPointF &topLeft, double gridPixels)
uchar getStepFlag (GridPoint &gp1, GridPoint &gp2)
QPointF getStepPoint (QPointF p, uchar flags, double gridPixels)
int gridPointInt (Grid *grid, GridPoint &gp)
static bool hasID (ConnectorItem *s)
bool idsMatch (const QDomElement &element, QMultiHash< QString, QString > &partIDs)
void initMarkers (Markers &markers, bool pcbType)
bool jumperWillFit (GridPoint &gridPoint, const Grid *grid, int halfSize)
double manhattanCost (const QPoint &p1, const QPoint &p2)
void printOrder (const QString &msg, QList< int > &order)
bool schematicJumperWillFit (GridPoint &gridPoint, const Grid *grid, int halfSize)
bool schematicJumperWillFitAux (GridPoint &gridPoint, const Grid *grid, int halfSize, int xl, int xr)
Variables
static const uint AvoidCost = 7
static QString CancelledMessage
static const uint CrossLayerCost = 100
static const int DefaultMaxCycles = 100
static const GridValue GridAvoid = GridBoardObstacle - 4
static const GridValue GridBoardObstacle = std::numeric_limits<GridValue>::max()
static const GridValue GridPartObstacle = GridBoardObstacle - 1
static const uchar GridPointDone = 1
static const uchar GridPointJumperLeft = 64
static const uchar GridPointJumperRight = 128
static const uchar GridPointStepStart = 32
static const uchar GridPointStepXMinus = 16
static const uchar GridPointStepXPlus = 8
static const uchar GridPointStepYMinus = 4
static const uchar GridPointStepYPlus = 2
static const GridValue GridSource = GridBoardObstacle - 2
static const GridValue GridSourceFlag = (GridBoardObstacle / 2) + 1
static const GridValue GridTarget = GridBoardObstacle - 3
static const GridValue GridTempObstacle = GridBoardObstacle - 5
static const long IDs [] = { 1452191, 9781580, 9781600, 9781620, 9781640, 9781660, 9781680, 9781700 }
static const uchar JumperEnd = 2
static const uchar JumperLeft = 4
static const uchar JumperRight = 8
static const uchar JumperStart = 1
static const uint Layer1Cost = 100
static const double MinTraceManhattanLength = 0.1
static const int OptimizeFactor = 2
static const uint ViaCost = 2000
Function Documentation
atLeast()
bool atLeast (const QPointF & p1, const QPointF & p2)
References MinTraceManhattanLength.
byOrder()
bool byOrder (Trace & t1, Trace & t2)
References Trace::order.
byPinsWithin()
bool byPinsWithin (Net * n1, Net * n2)
References Net::net, and Net::pinsWithin.
distanceCost()
double distanceCost (const QPoint & p1, const QPoint & p2) inline
References GraphicsUtils::distanceSqd().
fastCopy()
void fastCopy (QImage * from, QImage * to)
getColor()
uint getColor (GridValue val)
References GridAvoid, GridBoardObstacle, GridPartObstacle, GridSource, GridSourceFlag, GridTarget, and GridTempObstacle.
getPartID()
QString getPartID (const QDomElement & element)
getPixelCenter()
QPointF getPixelCenter (GridPoint & gp, QPointF & topLeft, double gridPixels)
References GridPoint::x, and GridPoint::y.
getStepFlag()
uchar getStepFlag (GridPoint & gp1, GridPoint & gp2)
References GridPointStepXMinus, GridPointStepXPlus, GridPointStepYMinus, GridPointStepYPlus, GridPoint::x, and GridPoint::y.
getStepPoint()
QPointF getStepPoint (QPointF p, uchar flags, double gridPixels)
References GridPointStepXMinus, GridPointStepXPlus, and GridPointStepYPlus.
gridPointInt()
int gridPointInt (Grid * grid, GridPoint & gp) inline
References GridPoint::x, Grid::x, GridPoint::y, Grid::y, and GridPoint::z.
hasID()
static bool hasID (ConnectorItem * s) inline static
References NonConnectorItem::attachedToID(), and IDs.
idsMatch()
bool idsMatch (const QDomElement & element, QMultiHash< QString, QString > & partIDs)
References getPartID(), and IDs.
initMarkers()
void initMarkers (Markers & markers, bool pcbType)
References DRC::AlsoNet, Markers::inNoID, Markers::inSvgAndID, Markers::inSvgID, Markers::inTerminalID, DRC::Net, DRC::NotNet, and Markers::outID.
jumperWillFit()
bool jumperWillFit (GridPoint & gridPoint, const Grid * grid, int halfSize)
References Grid::at(), GridAvoid, GridBoardObstacle, GridPartObstacle, GridSource, GridTarget, GridTempObstacle, GridPoint::x, Grid::x, GridPoint::y, Grid::y, and Grid::z.
manhattanCost()
double manhattanCost (const QPoint & p1, const QPoint & p2) inline
References qMax().
printOrder()
void printOrder (const QString & msg, QList< int > & order)
References DebugDialog::debug().
schematicJumperWillFit()
bool schematicJumperWillFit (GridPoint & gridPoint, const Grid * grid, int halfSize)
References GridPoint::flags, GridPointJumperLeft, GridPointJumperRight, and schematicJumperWillFitAux().
schematicJumperWillFitAux()
bool schematicJumperWillFitAux (GridPoint & gridPoint, const Grid * grid, int halfSize, int xl, int xr)
References Grid::at(), GridPoint::baseCost, GridAvoid, GridBoardObstacle, GridPartObstacle, GridSource, GridTarget, GridTempObstacle, GridPoint::x, Grid::x, GridPoint::y, and Grid::y.
Variable Documentation
AvoidCost
const uint AvoidCost = 7 static
CancelledMessage
QString CancelledMessage static
CrossLayerCost
const uint CrossLayerCost = 100 static
DefaultMaxCycles
const int DefaultMaxCycles = 100 static
GridAvoid
const GridValue GridAvoid = GridBoardObstacle - 4 static
GridBoardObstacle
const GridValue GridBoardObstacle = std::numeric_limits<GridValue>::max() static
GridPartObstacle
const GridValue GridPartObstacle = GridBoardObstacle - 1 static
GridPointDone
const uchar GridPointDone = 1 static
GridPointJumperLeft
const uchar GridPointJumperLeft = 64 static
GridPointJumperRight
const uchar GridPointJumperRight = 128 static
GridPointStepStart
const uchar GridPointStepStart = 32 static
GridPointStepXMinus
const uchar GridPointStepXMinus = 16 static
GridPointStepXPlus
const uchar GridPointStepXPlus = 8 static
GridPointStepYMinus
const uchar GridPointStepYMinus = 4 static
GridPointStepYPlus
const uchar GridPointStepYPlus = 2 static
GridSource
const GridValue GridSource = GridBoardObstacle - 2 static
GridSourceFlag
const GridValue GridSourceFlag = (GridBoardObstacle / 2) + 1 static
GridTarget
const GridValue GridTarget = GridBoardObstacle - 3 static
GridTempObstacle
const GridValue GridTempObstacle = GridBoardObstacle - 5 static
IDs
const long IDs[] = { 1452191, 9781580, 9781600, 9781620, 9781640, 9781660, 9781680, 9781700 } static
JumperEnd
const uchar JumperEnd = 2 static
JumperLeft
const uchar JumperLeft = 4 static
JumperRight
const uchar JumperRight = 8 static
JumperStart
const uchar JumperStart = 1 static
Layer1Cost
const uint Layer1Cost = 100 static
MinTraceManhattanLength
const double MinTraceManhattanLength = 0.1 static
OptimizeFactor
const int OptimizeFactor = 2 static
ViaCost
const uint ViaCost = 2000 static