Fritzing: CleanUpWiresCommand Class Reference
CleanUpWiresCommand Class Reference
#include <commands.h>
Public Types
enum Direction { UndoOnly = 0, RedoOnly, Noop }
Public Types inherited from BaseCommand
enum CrossViewType { SingleView, CrossView }
Public Member Functions
CleanUpWiresCommand (class SketchWidget *sketchWidget, CleanUpWiresCommand::Direction, QUndoCommand *parent)
void addRatsnestConnect (long id, const QString &connectorID, bool connect)
void addRoutingStatus (SketchWidget *, const RoutingStatus &oldRoutingStatus, const RoutingStatus &newRoutingStatus)
void addTrace (SketchWidget *sketchWidget, Wire *wire)
CleanUpWiresCommand::Direction direction ()
bool hasTraces (SketchWidget *)
void redo ()
void setDirection (CleanUpWiresCommand::Direction)
void undo ()
Public Member Functions inherited from BaseCommand
BaseCommand (BaseCommand::CrossViewType, SketchWidget *, QUndoCommand *parent)
~BaseCommand ()
void addSubCommand (BaseCommand *subCommand)
BaseCommand::CrossViewType crossViewType () const noexcept
virtual QString getDebugString () const
int index () const
const QUndoCommand * parentCommand () const
void redo ()
void setCrossViewType (BaseCommand::CrossViewType)
void setRedoOnly ()
void setSkipFirstRedo ()
void setUndoOnly ()
SketchWidget * sketchWidget () const
const BaseCommand * subCommand (int index) const
int subCommandCount () const
void subRedo ()
void subRedo (int index)
void subUndo ()
void subUndo (int index)
void undo ()
Protected Member Functions
QString getParamString () const
Protected Attributes
CleanUpWiresCommand::Direction m_direction
QList< RatsnestConnectThing > m_ratsnestConnectThings
QSet< SketchWidget * > m_sketchWidgets
Protected Attributes inherited from BaseCommand
QList< BaseCommand * > m_commands
BaseCommand::CrossViewType m_crossViewType
int m_index = 0
QUndoCommand * m_parentCommand = nullptr
bool m_redoOnly = false
SketchWidget * m_sketchWidget = nullptr
bool m_skipFirstRedo = false
bool m_undoOnly = false
Additional Inherited Members
Static Public Member Functions inherited from BaseCommand
static void clearProgress ()
static CommandProgress * initProgress ()
static int totalChildCount (const QUndoCommand *)
Static Protected Attributes inherited from BaseCommand
static CommandProgress m_commandProgress
static int nextIndex = 0
Member Enumeration Documentation
Direction
enum CleanUpWiresCommand::Direction
Enumerator
UndoOnly
RedoOnly
Noop
Constructor & Destructor Documentation
CleanUpWiresCommand()
CleanUpWiresCommand::CleanUpWiresCommand (class SketchWidget * sketchWidget, CleanUpWiresCommand::Direction direction, QUndoCommand * parent)
Member Function Documentation
addRatsnestConnect()
void CleanUpWiresCommand::addRatsnestConnect (long id, const QString & connectorID, bool connect)
References RatsnestConnectThing::connect, RatsnestConnectThing::connectorID, RatsnestConnectThing::id, and m_ratsnestConnectThings.
addRoutingStatus()
void CleanUpWiresCommand::addRoutingStatus (SketchWidget * sketchWidget, const RoutingStatus & oldRoutingStatus, const RoutingStatus & newRoutingStatus)
References BaseCommand::addSubCommand(), and BaseCommand::sketchWidget().
addTrace()
void CleanUpWiresCommand::addTrace (SketchWidget * sketchWidget, Wire * wire)
References BaseCommand::addSubCommand(), NonConnectorItem::attachedToID(), Wire::colorString(), ConnectorItem::connectedToItems(), Wire::connector0(), Wire::connector1(), ConnectorItem::connectorSharedID(), BaseCommand::CrossView, ItemBase::getViewGeometry(), ItemBase::id(), AddDeleteItemCommand::itemID(), BaseCommand::m_parentCommand, m_sketchWidgets, ModelPart::modelIndex(), ItemBase::modelPart(), Wire::opacity(), BaseCommand::sketchWidget(), ViewLayer::specFromID(), ItemBase::viewLayerID(), ItemBase::viewLayerPlacement(), Wire::width(), and ModuleIDNames::WireModuleIDName.
direction()
CleanUpWiresCommand::Direction CleanUpWiresCommand::direction ()
References m_direction.
getParamString()
QString CleanUpWiresCommand::getParamString () const protected virtual
Reimplemented from BaseCommand.
References BaseCommand::getParamString(), and m_direction.
hasTraces()
bool CleanUpWiresCommand::hasTraces (SketchWidget * sketchWidget)
References m_sketchWidgets, and BaseCommand::sketchWidget().
redo()
void CleanUpWiresCommand::redo ()
References SketchWidget::cleanUpWires(), RatsnestConnectThing::connect, RatsnestConnectThing::connectorID, BaseCommand::CrossView, RatsnestConnectThing::id, BaseCommand::m_crossViewType, m_direction, m_ratsnestConnectThings, BaseCommand::m_sketchWidget, m_sketchWidgets, SketchWidget::ratsnestConnect(), BaseCommand::redo(), RedoOnly, and BaseCommand::subRedo().
setDirection()
void CleanUpWiresCommand::setDirection (CleanUpWiresCommand::Direction direction)
References direction(), and m_direction.
undo()
void CleanUpWiresCommand::undo ()
References SketchWidget::cleanUpWires(), RatsnestConnectThing::connect, RatsnestConnectThing::connectorID, BaseCommand::CrossView, RatsnestConnectThing::id, BaseCommand::m_crossViewType, m_direction, m_ratsnestConnectThings, BaseCommand::m_sketchWidget, m_sketchWidgets, SketchWidget::ratsnestConnect(), BaseCommand::subUndo(), BaseCommand::undo(), and UndoOnly.
Member Data Documentation
m_direction
CleanUpWiresCommand::Direction CleanUpWiresCommand::m_direction protected
m_ratsnestConnectThings
QList<RatsnestConnectThing> CleanUpWiresCommand::m_ratsnestConnectThings protected
m_sketchWidgets
QSet<SketchWidget *> CleanUpWiresCommand::m_sketchWidgets protected
The documentation for this class was generated from the following files:
commands.h
commands.cpp