Fritzing: SketchModel Class Reference
SketchModel Class Reference
#include <sketchmodel.h>
Public Member Functions
SketchModel (bool makeRoot)
SketchModel (ModelPart *root)
ModelPart * findModelPart (const QString &moduleID, long id)
void removeModelPart (ModelPart *)
Public Member Functions inherited from ModelBase
ModelBase (bool makeRoot)
virtual ~ModelBase ()
virtual ModelPart * addModelPart (ModelPart *parent, ModelPart *copyChild)
virtual ModelPart * addPart (QString newPartPath, bool addToReference)
virtual bool addPart (ModelPart *modelPart, bool update)
virtual ModelPart * addPart (QString newPartPath, bool addToReference, bool updateIdAlreadyExists)
bool checkForReversedWires ()
const QString & fritzingVersion ()
ModelPart * genFZP (const QString &moduleID, ModelBase *referenceModel)
bool loadFromFile (const QString &fileName, ModelBase *referenceModel, QList< ModelPart * > &modelParts, bool checkInstances)
bool paste (ModelBase *referenceModel, QByteArray &data, QList< ModelPart * > &modelParts, QHash< QString, QRectF > &boundingRects, bool preserveIndex)
virtual ModelPart * retrieveModelPart (const QString &moduleID)
ModelPart * root ()
ModelPartSharedRoot * rootModelPartShared ()
void save (const QString &fileName, bool asPart)
void save (const QString &fileName, class QXmlStreamWriter &, bool asPart)
void setReferenceModel (ModelBase *)
void setReportMissingModules (bool)
Protected Member Functions
ModelPart * findModelPartAux (ModelPart *modelPart, const QString &moduleID, long id)
Protected Member Functions inherited from ModelBase
ModelPart * createOldSchematicPart (ModelPart *, QString &moduleIDRef)
ModelPart * createOldSchematicPartAux (ModelPart *, const QString &oldModuleIDRef, const QString &oldSchematicFileName, const QString &oldSvgPath)
ModelPart * fixObsoleteModuleID (QDomDocument &domDocument, QDomElement &instance, QString &moduleIDRef)
bool loadInstances (QDomDocument &, QDomElement &root, QList< ModelPart * > &modelParts, bool checkViews)
void renewModelIndexes (QDomElement &root, const QString &childName, QHash< long, long > &oldToNew)
Additional Inherited Members
Signals inherited from ModelBase
void loadedInstances (ModelBase *, QDomElement &instances)
void loadedRoot (const QString &fileName, ModelBase *, QDomElement &root)
void loadedViews (ModelBase *, QDomElement &views)
void loadingInstance (ModelBase *, QDomElement &instance)
void loadingInstances (ModelBase *, QDomElement &instances)
void obsoleteSMDOrientationSignal ()
void oldSchematicsSignal (const QString &filename, bool &useOldSchematics)
Static Public Member Functions inherited from ModelBase
static bool onCoreList (const QString &moduleID)
Static Protected Member Functions inherited from ModelBase
static void checkMystery (QDomElement &instance)
static bool checkObsoleteOrientation (QDomElement &instance)
static bool checkOldSchematics (QDomElement &instance)
static void checkTraces (QDomElement &instance)
static bool isRatsnest (QDomElement &instance)
Protected Attributes inherited from ModelBase
bool m_checkForReversedWires
QString m_fritzingVersion
QPointer< ModelBase > m_referenceModel
bool m_reportMissingModules
QPointer< ModelPart > m_root
bool m_useOldSchematics
Static Protected Attributes inherited from ModelBase
static QList< QString > CoreList
Constructor & Destructor Documentation
SketchModel() [1/2]
SketchModel::SketchModel (bool makeRoot)
SketchModel() [2/2]
SketchModel::SketchModel (ModelPart * root)
References ModelBase::m_root, and ModelBase::root().
Member Function Documentation
findModelPart()
ModelPart * SketchModel::findModelPart (const QString & moduleID, long id)
References findModelPartAux(), and ModelBase::m_root.
findModelPartAux()
ModelPart * SketchModel::findModelPartAux (ModelPart * modelPart, const QString & moduleID, long id) protected
References ModelPart::hasViewID(), ModelPart::indexMultiplier, ModelPart::modelIndex(), and ModelPart::moduleID().
removeModelPart()
void SketchModel::removeModelPart (ModelPart * modelPart)
The documentation for this class was generated from the following files:
model/sketchmodel.h
model/sketchmodel.cpp