Fritzing: Version Class Reference
Version Class Reference
#include <version.h>
Static Public Member Functions
static bool candidateGreaterThanCurrent (const VersionThing &)
static void cleanup ()
static const QString & date ()
static const QString & fullDate ()
static const QString & gitVersion ()
static bool greaterThan (const VersionThing &myVersionThing, const VersionThing &yourVersionThing)
static bool greaterThan (const QString &myVersionStr, const QString &yourVersionStr)
static const QString & majorVersion ()
static QString makeRequestParamsString (bool withID)
static const QString & minorSubVersion ()
static const QString & minorVersion ()
static const QString & modifier ()
static bool modifierGreaterThan (const QString &myReleaseModifier, const QString &yourReleaseModifier)
static const QString & shortDate ()
static void toVersionThing (const QString &candidate, VersionThing &versionThing)
static const QString & versionString ()
static const QString & year ()
Static Public Attributes
static QString FirstVersionWithDetachedUserData = "0.3.1b.05.26.3016"
Protected Member Functions
Version ()
Static Protected Attributes
static QString m_date
static QString m_gitCommit
static QString m_gitDate
static QString m_gitVersion
static QString m_majorVersion
static QString m_minorSubVersion
static QString m_minorVersion
static QString m_modifier
static QStringList m_modifiers
static QString m_shortDate
static Version * m_singleton = new Version()
static QString m_versionString
static QString m_year
Constructor & Destructor Documentation
Version()
Version::Version () protected
References m_date, m_gitDate, m_gitVersion, m_majorVersion, m_minorSubVersion, m_minorVersion, m_modifier, m_modifiers, m_shortDate, m_versionString, and m_year.
Member Function Documentation
candidateGreaterThanCurrent()
bool Version::candidateGreaterThanCurrent (const VersionThing & candidateVersionThing) static
References greaterThan(), VersionThing::majorVersion, majorVersion(), VersionThing::minorSubVersion, minorSubVersion(), VersionThing::minorVersion, minorVersion(), modifier(), and VersionThing::releaseModifier.
cleanup()
void Version::cleanup () static
References m_singleton.
date()
const QString & Version::date () static
References m_date.
fullDate()
const QString & Version::fullDate () static
References m_gitDate.
gitVersion()
const QString & Version::gitVersion () static
References m_gitVersion.
greaterThan() [1/2]
bool Version::greaterThan (const VersionThing & myVersionThing, const VersionThing & yourVersionThing) static
References VersionThing::majorVersion, VersionThing::minorSubVersion, VersionThing::minorVersion, modifierGreaterThan(), and VersionThing::releaseModifier.
greaterThan() [2/2]
bool Version::greaterThan (const QString & myVersionStr, const QString & yourVersionStr) static
References greaterThan(), and toVersionThing().
majorVersion()
const QString & Version::majorVersion () static
References m_majorVersion.
makeRequestParamsString()
QString Version::makeRequestParamsString (bool withID) static
References QtSystemInfo::architectureName(), TextUtils::getRandText(), QtSystemInfo::kernelName(), QtSystemInfo::kernelVersion(), QtSystemInfo::systemName(), QtSystemInfo::systemVersion(), and versionString().
minorSubVersion()
const QString & Version::minorSubVersion () static
References m_minorSubVersion.
minorVersion()
const QString & Version::minorVersion () static
References m_minorVersion.
modifier()
const QString & Version::modifier () static
References m_modifier.
modifierGreaterThan()
bool Version::modifierGreaterThan (const QString & myReleaseModifier, const QString & yourReleaseModifier) static
References m_modifiers.
shortDate()
const QString & Version::shortDate () static
References m_shortDate.
toVersionThing()
void Version::toVersionThing (const QString & candidate, VersionThing & versionThing) static
References m_modifiers, VersionThing::majorVersion, VersionThing::minorSubVersion, VersionThing::minorVersion, VersionThing::ok, and VersionThing::releaseModifier.
versionString()
const QString & Version::versionString () static
References m_versionString.
year()
const QString & Version::year () static
References m_year.
Member Data Documentation
FirstVersionWithDetachedUserData
QString Version::FirstVersionWithDetachedUserData = "0.3.1b.05.26.3016" static
m_date
QString Version::m_date static protected
m_gitCommit
QString Version::m_gitCommit static protected
m_gitDate
QString Version::m_gitDate static protected
m_gitVersion
QString Version::m_gitVersion static protected
m_majorVersion
QString Version::m_majorVersion static protected
m_minorSubVersion
QString Version::m_minorSubVersion static protected
m_minorVersion
QString Version::m_minorVersion static protected
m_modifier
QString Version::m_modifier static protected
m_modifiers
QStringList Version::m_modifiers static protected
m_shortDate
QString Version::m_shortDate static protected
m_singleton
Version * Version::m_singleton = new Version() static protected
m_versionString
QString Version::m_versionString static protected
m_year
QString Version::m_year static protected
The documentation for this class was generated from the following files:
version/version.h
version/version.cpp