Fritzing: PTabWidget Class Reference
PTabWidget Class Reference
#include <programwindow.h>
Public Member Functions
PTabWidget (QWidget *parent)
QTabBar * tabBar ()
Protected Slots
void tabChanged (int index)
Protected Attributes
int m_lastTabIndex
Constructor & Destructor Documentation
PTabWidget()
PTabWidget::PTabWidget (QWidget * parent)
References m_lastTabIndex, tabBar(), and tabChanged().
Member Function Documentation
tabBar()
QTabBar * PTabWidget::tabBar ()
tabChanged
void PTabWidget::tabChanged (int index) protected slot
References m_lastTabIndex, and tabBar().
Member Data Documentation
m_lastTabIndex
int PTabWidget::m_lastTabIndex protected
The documentation for this class was generated from the following files:
program/programwindow.h
program/programwindow.cpp