Fritzing: ViewLayer Class Reference
ViewLayer Class Reference
#include <viewlayer.h>
Public Types
enum ViewID {
IconView, BreadboardView, SchematicView, PCBView,
AllViews, UnknownView, ViewCount
}
enum ViewLayerID {
Icon, BreadboardBreadboard, Breadboard, BreadboardWire,
BreadboardLabel, BreadboardRatsnest, BreadboardNote, BreadboardRuler,
SchematicFrame, Schematic, SchematicText, SchematicWire,
SchematicTrace, SchematicLabel, SchematicNote, SchematicRuler,
Board, GroundPlane0, Silkscreen0, Silkscreen0Label,
Copper0, Copper0Trace, GroundPlane1, Copper1,
Copper1Trace, Silkscreen1, Silkscreen1Label, PartImage,
PcbRatsnest, PcbNote, PcbRuler, UnknownLayer,
ViewLayerCount
}
enum ViewLayerPlacement { NewTop, NewBottom, NewTopAndBottom, UnknownPlacement }
Public Member Functions
ViewLayer (ViewLayerID, bool visible, double initialZ)
~ViewLayer ()
QAction * action ()
bool alreadyInLayer (double z)
const QList< ViewLayer * > & childLayers ()
QString & displayName ()
bool fromBelow ()
double getZFromBelow (double currentZ, bool fromBelow)
bool includeChildLayers ()
double incrementZ (double)
bool isActive ()
double nextZ ()
ViewLayer * parentLayer ()
void resetNextZ (double z)
void setAction (QAction *)
void setActive (bool)
void setFromBelow (bool)
void setIncludeChildLayers (bool)
void setInitialZFromBelow (double)
void setParentLayer (ViewLayer *)
void setVisible (bool)
ViewLayerID viewLayerID ()
bool visible ()
Static Public Member Functions
static const QList< ViewLayer::ViewLayerID > & bottomLayers ()
static bool canConnect (ViewLayerID, ViewLayerID)
static void cleanup ()
static const QList< ViewLayer::ViewLayerID > & copperLayers (ViewLayer::ViewLayerPlacement)
static const QList< ViewLayer::ViewLayerID > & drillLayers ()
static QList< ViewLayerID > findAlternativeLayers (ViewLayerID)
static QDomElement getConnectorPElement (const QDomElement &connector, ViewLayer::ViewID)
static bool getConnectorSvgIDs (QDomElement &connector, ViewLayer::ViewID, QString &id, QString &terminalID)
static double getZIncrement ()
static ViewID idFromXmlName (const QString &name)
static void initNames ()
static bool isCopperLayer (ViewLayer::ViewLayerID)
static bool isNonCopperLayer (ViewLayer::ViewLayerID viewLayerID)
static const QList< ViewLayer::ViewLayerID > & layersForView (ViewLayer::ViewID)
static const QList< ViewLayer::ViewLayerID > & layersForViewFromBelow (ViewLayer::ViewID)
static const QList< ViewLayer::ViewLayerID > & maskLayers (ViewLayer::ViewLayerPlacement)
static const QList< ViewLayer::ViewLayerID > & outlineLayers ()
static const QList< ViewLayer::ViewLayerID > & silkLayers (ViewLayer::ViewLayerPlacement)
static const QList< ViewLayer::ViewLayerID > & silkLayers ()
static ViewLayer::ViewLayerPlacement specFromID (ViewLayer::ViewLayerID)
static const QList< ViewLayer::ViewLayerID > & topLayers ()
static bool viewHasLayer (ViewID, ViewLayer::ViewLayerID)
static QString & viewIDName (ViewLayer::ViewID)
static QString & viewIDNaturalName (ViewLayer::ViewID)
static QString & viewIDXmlName (ViewLayer::ViewID)
static ViewLayerID viewLayerIDFromXmlString (const QString &)
static const QString & viewLayerNameFromID (ViewLayerID)
static const QString & viewLayerXmlNameFromID (ViewLayerID)
Static Public Attributes
static const QString BoardColor = "#ffffff"
static const QString Copper0Color = "#f9a435"
static const QString Copper0WireColor = "#f28a00"
static const QString Copper1Color = "#fdde68"
static const QString Copper1WireColor = "#f2c600"
static const QString HolesColor
static const QString Silkscreen0Color = "#444444"
static const QString Silkscreen1Color = "#000000"
Protected Attributes
QAction * m_action
bool m_active
QList< ViewLayer * > m_childLayers
bool m_fromBelow
bool m_includeChildLayers
double m_initialZ
double m_initialZFromBelow
double m_nextZ
ViewLayer * m_parentLayer
ViewLayerID m_viewLayerID
bool m_visible
Static Protected Attributes
static QMultiHash< ViewLayerID, ViewLayerID > alternatives
static QHash< ViewLayerID, NamePair * > names
static QMultiHash< ViewLayerID, ViewLayerID > unconnectables
static QHash< ViewID, class NameTriple * > ViewIDNames
static QHash< QString, ViewLayerID > xmlHash
static double zIncrement = 0.00001
Member Enumeration Documentation
ViewID
enum ViewLayer::ViewID
Enumerator
IconView
BreadboardView
SchematicView
PCBView
AllViews
UnknownView
ViewCount
ViewLayerID
enum ViewLayer::ViewLayerID
Enumerator
Icon
BreadboardBreadboard
Breadboard
BreadboardWire
BreadboardLabel
BreadboardRatsnest
BreadboardNote
BreadboardRuler
SchematicFrame
Schematic
SchematicText
SchematicWire
SchematicTrace
SchematicLabel
SchematicNote
SchematicRuler
Board
GroundPlane0
Silkscreen0
Silkscreen0Label
Copper0
Copper0Trace
GroundPlane1
Copper1
Copper1Trace
Silkscreen1
Silkscreen1Label
PartImage
PcbRatsnest
PcbNote
PcbRuler
UnknownLayer
ViewLayerCount
ViewLayerPlacement
enum ViewLayer::ViewLayerPlacement
Enumerator
NewTop
NewBottom
NewTopAndBottom
UnknownPlacement
Constructor & Destructor Documentation
ViewLayer()
ViewLayer::ViewLayer (ViewLayerID viewLayerID, bool visible, double initialZ)
References m_action, m_active, m_fromBelow, m_includeChildLayers, m_initialZ, m_initialZFromBelow, m_nextZ, m_parentLayer, m_viewLayerID, m_visible, viewLayerID(), and visible().
~ViewLayer()
ViewLayer::~ViewLayer ()
Member Function Documentation
action()
QAction * ViewLayer::action ()
References m_action.
alreadyInLayer()
bool ViewLayer::alreadyInLayer (double z)
References m_fromBelow, m_initialZ, m_initialZFromBelow, and m_nextZ.
bottomLayers()
const LayerList & ViewLayer::bottomLayers () static
References Copper0, Copper0Trace, GroundPlane0, Silkscreen0, and Silkscreen0Label.
canConnect()
bool ViewLayer::canConnect (ViewLayer::ViewLayerID v1, ViewLayer::ViewLayerID v2) static
References unconnectables.
childLayers()
const QList< ViewLayer * > & ViewLayer::childLayers ()
References m_childLayers.
cleanup()
void ViewLayer::cleanup () static
References names, and ViewIDNames.
copperLayers()
const LayerList & ViewLayer::copperLayers (ViewLayer::ViewLayerPlacement viewLayerPlacement) static
References CopperBottomLayers, CopperTopLayers, and NewTop.
displayName()
QString & ViewLayer::displayName ()
References m_viewLayerID, and names.
drillLayers()
const LayerList & ViewLayer::drillLayers () static
References Copper0, and Copper1.
findAlternativeLayers()
LayerList ViewLayer::findAlternativeLayers (ViewLayer::ViewLayerID id) static
References alternatives.
fromBelow()
bool ViewLayer::fromBelow ()
References m_fromBelow.
getConnectorPElement()
QDomElement ViewLayer::getConnectorPElement (const QDomElement & connector, ViewLayer::ViewID viewID) static
References viewIDXmlName().
getConnectorSvgIDs()
bool ViewLayer::getConnectorSvgIDs (QDomElement & connector, ViewLayer::ViewID viewID, QString & id, QString & terminalID) static
References getConnectorPElement().
getZFromBelow()
double ViewLayer::getZFromBelow (double currentZ, bool fromBelow)
References fromBelow(), m_initialZ, and m_initialZFromBelow.
getZIncrement()
double ViewLayer::getZIncrement () static
References zIncrement.
idFromXmlName()
ViewLayer::ViewID ViewLayer::idFromXmlName (const QString & name) static
References UnknownView, ViewIDNames, and NameTriple::xmlName().
includeChildLayers()
bool ViewLayer::includeChildLayers ()
References m_includeChildLayers.
incrementZ()
double ViewLayer::incrementZ (double z)
References zIncrement.
initNames()
void ViewLayer::initNames () static
References alternatives, Board, Breadboard, BreadboardBreadboard, BreadboardLabel, BreadboardNote, BreadboardRatsnest, BreadboardRuler, BreadboardView, BreadboardViewLayerList, BreadboardWire, Copper0, Copper0Trace, Copper1, Copper1Trace, CopperBottomLayers, CopperTopLayers, GroundPlane0, GroundPlane1, Icon, IconView, IconViewLayerList, names, NonCopperLayers, PartImage, PcbNote, PcbRatsnest, PcbRuler, PCBView, PCBViewFromBelowLayerList, PCBViewLayerList, Schematic, SchematicFrame, SchematicLabel, SchematicNote, SchematicRuler, SchematicText, SchematicTrace, SchematicView, SchematicViewLayerList, SchematicWire, Silkscreen0, Silkscreen0Label, Silkscreen1, Silkscreen1Label, unconnectables, UnknownLayer, ViewIDNames, and xmlHash.
isActive()
bool ViewLayer::isActive ()
References m_active.
isCopperLayer()
bool ViewLayer::isCopperLayer (ViewLayer::ViewLayerID viewLayerID) static
References CopperBottomLayers, CopperTopLayers, and viewLayerID().
isNonCopperLayer()
bool ViewLayer::isNonCopperLayer (ViewLayer::ViewLayerID viewLayerID) static
References NonCopperLayers, and viewLayerID().
layersForView()
const LayerList & ViewLayer::layersForView (ViewLayer::ViewID viewID) static
References BreadboardView, BreadboardViewLayerList, EmptyLayerList, IconView, IconViewLayerList, PCBView, PCBViewLayerList, SchematicView, and SchematicViewLayerList.
layersForViewFromBelow()
const LayerList & ViewLayer::layersForViewFromBelow (ViewLayer::ViewID viewID) static
References BreadboardView, BreadboardViewLayerList, EmptyLayerList, IconView, IconViewLayerList, PCBView, PCBViewFromBelowLayerList, SchematicView, and SchematicViewLayerList.
maskLayers()
const LayerList & ViewLayer::maskLayers (ViewLayer::ViewLayerPlacement viewLayerPlacement) static
References Copper0, Copper1, and NewTop.
nextZ()
double ViewLayer::nextZ ()
References m_fromBelow, m_initialZ, m_initialZFromBelow, m_nextZ, and zIncrement.
outlineLayers()
const LayerList & ViewLayer::outlineLayers () static
References Board.
parentLayer()
ViewLayer * ViewLayer::parentLayer ()
References m_parentLayer.
resetNextZ()
void ViewLayer::resetNextZ (double z)
References m_nextZ.
setAction()
void ViewLayer::setAction (QAction * action)
References action(), and m_action.
setActive()
void ViewLayer::setActive (bool a)
References m_active.
setFromBelow()
void ViewLayer::setFromBelow (bool fromBelow)
References fromBelow(), and m_fromBelow.
setIncludeChildLayers()
void ViewLayer::setIncludeChildLayers (bool incl)
References m_includeChildLayers.
setInitialZFromBelow()
void ViewLayer::setInitialZFromBelow (double initialZ)
References m_initialZFromBelow.
setParentLayer()
void ViewLayer::setParentLayer (ViewLayer * parent)
References m_childLayers, and m_parentLayer.
setVisible()
void ViewLayer::setVisible (bool visible)
References m_action, m_visible, and visible().
silkLayers() [1/2]
const LayerList & ViewLayer::silkLayers (ViewLayer::ViewLayerPlacement viewLayerPlacement) static
References NewTop, Silkscreen0, Silkscreen0Label, Silkscreen1, and Silkscreen1Label.
silkLayers() [2/2]
const LayerList & ViewLayer::silkLayers () static
References Silkscreen0, and Silkscreen1.
specFromID()
ViewLayer::ViewLayerPlacement ViewLayer::specFromID (ViewLayer::ViewLayerID viewLayerID) static
References Copper1, Copper1Trace, GroundPlane1, NewBottom, NewTop, and viewLayerID().
topLayers()
const LayerList & ViewLayer::topLayers () static
References Copper1, Copper1Trace, GroundPlane1, Silkscreen1, and Silkscreen1Label.
viewHasLayer()
bool ViewLayer::viewHasLayer (ViewLayer::ViewID viewID, ViewLayer::ViewLayerID viewLayerID) static
References layersForView(), and viewLayerID().
viewIDName()
QString & ViewLayer::viewIDName (ViewLayer::ViewID viewID) static
References ViewCount, and ViewIDNames.
viewIDNaturalName()
QString & ViewLayer::viewIDNaturalName (ViewLayer::ViewID viewID) static
References ViewCount, and ViewIDNames.
viewIDXmlName()
QString & ViewLayer::viewIDXmlName (ViewLayer::ViewID viewID) static
References ViewCount, and ViewIDNames.
viewLayerID()
ViewLayer::ViewLayerID ViewLayer::viewLayerID ()
References m_viewLayerID.
viewLayerIDFromXmlString()
ViewLayer::ViewLayerID ViewLayer::viewLayerIDFromXmlString (const QString & viewLayerName) static
References UnknownLayer, and xmlHash.
viewLayerNameFromID()
const QString & ViewLayer::viewLayerNameFromID (ViewLayerID viewLayerID) static
References ___emptyString___, NamePair::displayName, names, and viewLayerID().
viewLayerXmlNameFromID()
const QString & ViewLayer::viewLayerXmlNameFromID (ViewLayerID viewLayerID) static
References ___emptyString___, names, viewLayerID(), and NamePair::xmlName.
visible()
bool ViewLayer::visible ()
References m_visible.
Member Data Documentation
alternatives
QMultiHash< ViewLayer::ViewLayerID, ViewLayer::ViewLayerID > ViewLayer::alternatives static protected
BoardColor
const QString ViewLayer::BoardColor = "#ffffff" static
Copper0Color
const QString ViewLayer::Copper0Color = "#f9a435" static
Copper0WireColor
const QString ViewLayer::Copper0WireColor = "#f28a00" static
Copper1Color
const QString ViewLayer::Copper1Color = "#fdde68" static
Copper1WireColor
const QString ViewLayer::Copper1WireColor = "#f2c600" static
HolesColor
const QString ViewLayer::HolesColor static
m_action
QAction* ViewLayer::m_action protected
m_active
bool ViewLayer::m_active protected
m_childLayers
QList<ViewLayer *> ViewLayer::m_childLayers protected
m_fromBelow
bool ViewLayer::m_fromBelow protected
m_includeChildLayers
bool ViewLayer::m_includeChildLayers protected
m_initialZ
double ViewLayer::m_initialZ protected
m_initialZFromBelow
double ViewLayer::m_initialZFromBelow protected
m_nextZ
double ViewLayer::m_nextZ protected
m_parentLayer
ViewLayer* ViewLayer::m_parentLayer protected
m_viewLayerID
ViewLayerID ViewLayer::m_viewLayerID protected
m_visible
bool ViewLayer::m_visible protected
names
QHash< ViewLayer::ViewLayerID, NamePair * > ViewLayer::names static protected
Silkscreen0Color
const QString ViewLayer::Silkscreen0Color = "#444444" static
Silkscreen1Color
const QString ViewLayer::Silkscreen1Color = "#000000" static
unconnectables
QMultiHash< ViewLayer::ViewLayerID, ViewLayer::ViewLayerID > ViewLayer::unconnectables static protected
ViewIDNames
QHash< ViewLayer::ViewID, NameTriple * > ViewLayer::ViewIDNames static protected
xmlHash
QHash< QString, ViewLayer::ViewLayerID > ViewLayer::xmlHash static protected
zIncrement
double ViewLayer::zIncrement = 0.00001 static protected
The documentation for this class was generated from the following files:
viewlayer.h
viewlayer.cpp