Fritzing: RecoveryDialog Class Reference
RecoveryDialog Class Reference
#include <recoverydialog.h>
Public Member Functions
RecoveryDialog (QFileInfoList fileList, QWidget *parent=0, Qt::WindowFlags flags=0)
QList< QTreeWidgetItem * > getFileList ()
Protected Slots
void updateRecoverButton ()
Protected Member Functions
QString getOriginalFileName (const QString &path)
Protected Attributes
QList< QTreeWidgetItem * > m_fileList
QPushButton * m_ignore
QPushButton * m_recover
QTreeWidget * m_recoveryList
Constructor & Destructor Documentation
RecoveryDialog()
RecoveryDialog::RecoveryDialog (QFileInfoList fileList, QWidget * parent = 0, Qt::WindowFlags flags = 0)
References DebugDialog::debug(), getOriginalFileName(), m_fileList, m_ignore, m_recover, m_recoveryList, and updateRecoverButton().
Member Function Documentation
getFileList()
QList< QTreeWidgetItem * > RecoveryDialog::getFileList ()
References m_fileList.
getOriginalFileName()
QString RecoveryDialog::getOriginalFileName (const QString & path) protected
References DebugDialog::debug().
updateRecoverButton
void RecoveryDialog::updateRecoverButton () protected slot
References m_recover, and m_recoveryList.
Member Data Documentation
m_fileList
QList<QTreeWidgetItem*> RecoveryDialog::m_fileList protected
m_ignore
QPushButton* RecoveryDialog::m_ignore protected
m_recover
QPushButton* RecoveryDialog::m_recover protected
m_recoveryList
QTreeWidget* RecoveryDialog::m_recoveryList protected
The documentation for this class was generated from the following files:
dialogs/recoverydialog.h
dialogs/recoverydialog.cpp