Fritzing: RenamePinsCommand Class Reference
RenamePinsCommand Class Reference
#include <commands.h>
Public Member Functions
RenamePinsCommand (class SketchWidget *sketchWidget, long id, const QStringList &oldOnes, const QStringList &newOnes, bool singleRow, QUndoCommand *parent)
void redo ()
void undo ()
Public Member Functions inherited from BaseCommand
BaseCommand (BaseCommand::CrossViewType, SketchWidget *, QUndoCommand *parent)
~BaseCommand ()
void addSubCommand (BaseCommand *subCommand)
BaseCommand::CrossViewType crossViewType () const noexcept
virtual QString getDebugString () const
int index () const
const QUndoCommand * parentCommand () const
void redo ()
void setCrossViewType (BaseCommand::CrossViewType)
void setRedoOnly ()
void setSkipFirstRedo ()
void setUndoOnly ()
SketchWidget * sketchWidget () const
const BaseCommand * subCommand (int index) const
int subCommandCount () const
void subRedo ()
void subRedo (int index)
void subUndo ()
void subUndo (int index)
void undo ()
Protected Member Functions
QString getParamString () const
Protected Attributes
long m_itemID
QStringList m_newLabels
QStringList m_oldLabels
bool m_singleRow
Protected Attributes inherited from BaseCommand
QList< BaseCommand * > m_commands
BaseCommand::CrossViewType m_crossViewType
int m_index = 0
QUndoCommand * m_parentCommand = nullptr
bool m_redoOnly = false
SketchWidget * m_sketchWidget = nullptr
bool m_skipFirstRedo = false
bool m_undoOnly = false
Additional Inherited Members
Public Types inherited from BaseCommand
enum CrossViewType { SingleView, CrossView }
Static Public Member Functions inherited from BaseCommand
static void clearProgress ()
static CommandProgress * initProgress ()
static int totalChildCount (const QUndoCommand *)
Static Protected Attributes inherited from BaseCommand
static CommandProgress m_commandProgress
static int nextIndex = 0
Constructor & Destructor Documentation
RenamePinsCommand()
RenamePinsCommand::RenamePinsCommand (class SketchWidget * sketchWidget, long id, const QStringList & oldOnes, const QStringList & newOnes, bool singleRow, QUndoCommand * parent)
Member Function Documentation
getParamString()
QString RenamePinsCommand::getParamString () const protected virtual
Reimplemented from BaseCommand.
References BaseCommand::getParamString(), m_itemID, and m_singleRow.
redo()
void RenamePinsCommand::redo ()
References m_itemID, m_newLabels, m_singleRow, BaseCommand::m_sketchWidget, BaseCommand::redo(), and SketchWidget::renamePins().
undo()
void RenamePinsCommand::undo ()
References m_itemID, m_oldLabels, m_singleRow, BaseCommand::m_sketchWidget, SketchWidget::renamePins(), and BaseCommand::undo().
Member Data Documentation
m_itemID
long RenamePinsCommand::m_itemID protected
m_newLabels
QStringList RenamePinsCommand::m_newLabels protected
m_oldLabels
QStringList RenamePinsCommand::m_oldLabels protected
m_singleRow
bool RenamePinsCommand::m_singleRow protected
The documentation for this class was generated from the following files:
commands.h
commands.cpp