Fritzing: CheckStickyCommand Class Reference
CheckStickyCommand Class Reference
#include <commands.h>
Public Types
enum CheckType { UndoOnly = 0, RedoOnly, RemoveOnly }
Public Types inherited from BaseCommand
enum CrossViewType { SingleView, CrossView }
Public Member Functions
CheckStickyCommand (SketchWidget *sketchWidget, BaseCommand::CrossViewType, long itemID, bool checkCurrent, CheckType, QUndoCommand *parent)
~CheckStickyCommand ()
void redo ()
void stick (SketchWidget *, long fromID, long toID, bool stickem)
void undo ()
Public Member Functions inherited from BaseCommand
BaseCommand (BaseCommand::CrossViewType, SketchWidget *, QUndoCommand *parent)
~BaseCommand ()
void addSubCommand (BaseCommand *subCommand)
BaseCommand::CrossViewType crossViewType () const noexcept
virtual QString getDebugString () const
int index () const
const QUndoCommand * parentCommand () const
void redo ()
void setCrossViewType (BaseCommand::CrossViewType)
void setRedoOnly ()
void setSkipFirstRedo ()
void setUndoOnly ()
SketchWidget * sketchWidget () const
const BaseCommand * subCommand (int index) const
int subCommandCount () const
void subRedo ()
void subRedo (int index)
void subUndo ()
void subUndo (int index)
void undo ()
Protected Member Functions
QString getParamString () const
Protected Attributes
bool m_checkCurrent = false
CheckType m_checkType
long m_itemID = 0
QList< StickyThing * > m_stickyList
Protected Attributes inherited from BaseCommand
QList< BaseCommand * > m_commands
BaseCommand::CrossViewType m_crossViewType
int m_index = 0
QUndoCommand * m_parentCommand = nullptr
bool m_redoOnly = false
SketchWidget * m_sketchWidget = nullptr
bool m_skipFirstRedo = false
bool m_undoOnly = false
Additional Inherited Members
Static Public Member Functions inherited from BaseCommand
static void clearProgress ()
static CommandProgress * initProgress ()
static int totalChildCount (const QUndoCommand *)
Static Protected Attributes inherited from BaseCommand
static CommandProgress m_commandProgress
static int nextIndex = 0
Member Enumeration Documentation
CheckType
enum CheckStickyCommand::CheckType
Enumerator
UndoOnly
RedoOnly
RemoveOnly
Constructor & Destructor Documentation
CheckStickyCommand()
CheckStickyCommand::CheckStickyCommand (SketchWidget * sketchWidget, BaseCommand::CrossViewType crossViewType, long itemID, bool checkCurrent, CheckType checkType, QUndoCommand * parent)
References BaseCommand::m_skipFirstRedo.
~CheckStickyCommand()
CheckStickyCommand::~CheckStickyCommand ()
References m_stickyList.
Member Function Documentation
getParamString()
QString CheckStickyCommand::getParamString () const protected virtual
Reimplemented from BaseCommand.
References BaseCommand::getParamString(), and m_stickyList.
redo()
void CheckStickyCommand::redo ()
References SketchWidget::checkSticky(), BaseCommand::CrossView, StickyThing::fromID, m_checkCurrent, m_checkType, BaseCommand::m_crossViewType, m_itemID, BaseCommand::m_sketchWidget, BaseCommand::m_skipFirstRedo, m_stickyList, BaseCommand::redo(), StickyThing::sketchWidget, SketchWidget::stickem(), StickyThing::stickem, StickyThing::toID, and UndoOnly.
stick()
void CheckStickyCommand::stick (SketchWidget * sketchWidget, long fromID, long toID, bool stickem)
References StickyThing::fromID, m_stickyList, BaseCommand::sketchWidget(), StickyThing::sketchWidget, StickyThing::stickem, and StickyThing::toID.
undo()
void CheckStickyCommand::undo ()
References StickyThing::fromID, m_checkType, m_stickyList, RedoOnly, RemoveOnly, StickyThing::sketchWidget, SketchWidget::stickem(), StickyThing::stickem, StickyThing::toID, and BaseCommand::undo().
Member Data Documentation
m_checkCurrent
bool CheckStickyCommand::m_checkCurrent = false protected
m_checkType
CheckType CheckStickyCommand::m_checkType protected
m_itemID
long CheckStickyCommand::m_itemID = 0 protected
m_stickyList
QList<StickyThing *> CheckStickyCommand::m_stickyList protected
The documentation for this class was generated from the following files:
commands.h
commands.cpp