Fritzing: ModelPart Class Reference
ModelPart Class Reference
#include <modelpart.h>
Public Types
enum ItemType {
Part, Wire, Breadboard, Board,
ResizableBoard, Note, Symbol, Jumper,
CopperFill, Logo, Hole, Via,
Ruler, SchematicSubpart, Space, Unknown
}
enum LocationFlag {
NoFlag = 0, CoreFlag = 1, ContribFlag = 2, AlienFlag = 4,
FzzFlag = 8, InBinFlag = 16
}
Signals
void startSaveInstances (const QString &fileName, ModelPart *, QXmlStreamWriter &)
Public Member Functions
ModelPart (QDomDocument &, const QString &path, ItemType type)
ModelPart (ItemType type=ModelPart::Unknown)
~ModelPart ()
void addConnector (Connector *)
void addViewItem (class ItemBase *)
bool anySticky (ViewLayer::ViewID)
const QString & author ()
Bus * bus (const QString &busID)
const QHash< QString, QPointer< Bus > > & buses ()
bool canFlipHorizontal (ViewLayer::ViewID)
bool canFlipVertical (ViewLayer::ViewID)
void clearBuses ()
QString connectorLocalName (const QString &id)
const QHash< QString, QPointer< Connector > > & connectors ()
void copy (ModelPart *)
void copyNew (ModelPart *)
void copyStuff (ModelPart *modelPart)
const QDate & date ()
qulonglong dbid ()
const QString & description ()
const QStringList & displayKeys ()
QString family ()
bool flippedSMD ()
void flipSMDAnd ()
const QString & fritzingVersion ()
QList< ModelPart * > getAllNonCoreParts ()
QList< ModelPart * > getAllParts ()
Connector * getConnector (const QString &id)
QString getNextTitle (const QString &candidate)
QString hasBaseNameFor (ViewLayer::ViewID)
bool hasSubparts ()
bool hasViewFor (ViewLayer::ViewID)
bool hasViewFor (ViewLayer::ViewID, ViewLayer::ViewLayerID)
bool hasViewID (ViewLayer::ViewID)
bool hasViewID (long id)
bool hasViewItems ()
bool hasZeroConnector ()
bool ignoreTerminalPoints ()
QString imageFileName (ViewLayer::ViewID)
QString imageFileName (ViewLayer::ViewID, ViewLayer::ViewLayerID)
void initBuses ()
void initConnectors (bool force=false)
const QDomElement & instanceDomElement ()
const QString & instanceText ()
const QString & instanceTitle () const
bool isAlien ()
bool isContrib ()
bool isCore ()
bool isFzz ()
bool isInBin ()
bool isObsolete ()
ModelPart::ItemType itemType () const
void killViewItems ()
const QString & label ()
const QString & language ()
QVariant localProp (const QString &name) const
QVariant localProp (const char *name) const
void lookForZeroConnector ()
long modelIndex ()
ModelPartShared * modelPartShared ()
ModelPartSharedRoot * modelPartSharedRoot ()
const QString & moduleID () const
bool needsCopper1 ()
const QString & path ()
const QHash< QString, QString > & properties () const
void removeViewItem (class ItemBase *)
const QString & replacedby ()
void saveAsPart (QXmlStreamWriter &streamWriter, bool startDocument)
void saveInstances (const QString &fileName, QXmlStreamWriter &streamWriter, bool startDocument)
void setAlien (bool alien)
void setConnectorLocalName (const QString &id, const QString &name)
void setContrib (bool contrib)
void setCore (bool core)
void setDBID (qulonglong)
void setFzz (bool alien)
void setImageFileName (ViewLayer::ViewID, const QString &filename)
void setInBin (bool)
void setInstanceDomElement (const QDomElement &)
void setInstanceText (QString)
void setInstanceTitle (QString, bool initial)
void setItemType (ItemType)
void setLocalProp (const QString &name, const QVariant &value)
void setLocalProp (const char *name, const QVariant &value)
void setLocalTitle (const QString &)
void setLocationFlag (bool setting, LocationFlag flag)
void setModelIndex (long index)
void setModelIndexFromMultiplied (long multipliedIndex)
void setModelPartShared (ModelPartShared *modelPartShared)
void setOrderedChildren (QList< QObject * > children)
void setProperty (const QString &key, const QString &value, bool showInLabel)
void setSubpartID (const QString &)
void setTag (const QString &tag)
void setViewImage (struct ViewImage *)
bool showInLabel (const QString &key)
const QString & spice ()
const QString & spiceModel ()
const QStringList & tags ()
const QString & taxonomy ()
const QString & title ()
const QString & uri ()
const QString & url ()
const QString & version ()
const QList< ViewImage * > viewImages ()
class ItemBase * viewItem (QGraphicsScene *scene)
class ItemBase * viewItem (ViewLayer::ViewID)
LayerList viewLayers (ViewLayer::ViewID)
Static Public Member Functions
static long nextIndex ()
static const QStringList & possibleFolders ()
static void updateIndex (long index)
Static Public Attributes
static const int indexMultiplier = 10
Protected Member Functions
void clearOldInstanceTitle (const QString &title)
void commonInit (ItemType type)
QList< QPointer< ModelPart > > * ensureInstanceTitleIncrements (const QString &prefix)
void saveInstance (QXmlStreamWriter &streamWriter)
bool setSubpartInstanceTitle ()
void writeNestedTag (QXmlStreamWriter &streamWriter, QString tagName, const QStringList &values, QString childTag)
void writeNestedTag (QXmlStreamWriter &streamWriter, QString tagName, const QHash< QString, QString > &values, QString childTag, QString attrName)
void writeTag (QXmlStreamWriter &streamWriter, QString tagName, QString tagValue)
Protected Attributes
QHash< QString, QPointer< Bus > > m_busHash
QHash< QString, QPointer< Connector > > m_connectorHash
long m_index
bool m_indexSynched
QDomElement m_instanceDomElement
QString m_instanceText
QString m_instanceTitle
QString m_localTitle
LocationFlags m_locationFlags
QPointer< ModelPartShared > m_modelPartShared
QList< QObject * > m_orderedChildren
ItemType m_type
QList< QPointer< class ItemBase > > m_viewItems
Static Protected Attributes
static QHash< ItemType, QString > itemTypeNames
static long m_nextIndex = 0
static QStringList m_possibleFolders
Member Enumeration Documentation
ItemType
enum ModelPart::ItemType
Enumerator
Part
Wire
Breadboard
Board
ResizableBoard
Note
Symbol
Jumper
CopperFill
Logo
Hole
Via
Ruler
SchematicSubpart
Space
Unknown
LocationFlag
enum ModelPart::LocationFlag
Enumerator
NoFlag
CoreFlag
ContribFlag
AlienFlag
FzzFlag
InBinFlag
Constructor & Destructor Documentation
ModelPart() [1/2]
ModelPart::ModelPart (QDomDocument & domDocument, const QString & path, ItemType type)
References commonInit(), m_modelPartShared, and path().
ModelPart() [2/2]
ModelPart::ModelPart (ItemType type = ModelPart::Unknown)
References commonInit(), m_index, m_modelPartShared, and m_nextIndex.
~ModelPart()
ModelPart::~ModelPart ()
References AllInstanceTitleIncrements, clearBuses(), clearOldInstanceTitle(), m_connectorHash, and m_instanceTitle.
Member Function Documentation
addConnector()
void ModelPart::addConnector (Connector * connector)
References Connector::connectorShared(), Connector::connectorSharedID(), m_connectorHash, and m_modelPartShared.
addViewItem()
void ModelPart::addViewItem (class ItemBase * item)
References m_viewItems.
anySticky()
bool ModelPart::anySticky (ViewLayer::ViewID viewID)
References m_modelPartShared.
author()
const QString & ModelPart::author ()
References ___emptyString___, and m_modelPartShared.
bus()
Bus * ModelPart::bus (const QString & busID)
References m_busHash.
buses()
const QHash< QString, QPointer< Bus > > & ModelPart::buses ()
References m_busHash.
canFlipHorizontal()
bool ModelPart::canFlipHorizontal (ViewLayer::ViewID viewID)
References m_modelPartShared.
canFlipVertical()
bool ModelPart::canFlipVertical (ViewLayer::ViewID viewID)
References m_modelPartShared.
clearBuses()
void ModelPart::clearBuses ()
References bus(), and m_busHash.
clearOldInstanceTitle()
void ModelPart::clearOldInstanceTitle (const QString & title) protected
References AllInstanceTitleIncrements, InstanceTitleRegExp(), NullInstanceTitleIncrements, and title().
commonInit()
void ModelPart::commonInit (ItemType type) protected
References m_indexSynched, m_locationFlags, and m_type.
connectorLocalName()
QString ModelPart::connectorLocalName (const QString & id)
References Connector::connectorLocalName(), and m_connectorHash.
connectors()
const QHash< QString, QPointer< Connector > > & ModelPart::connectors ()
References m_connectorHash.
copy()
void ModelPart::copy (ModelPart * modelPart)
References itemType(), m_locationFlags, m_modelPartShared, m_type, and modelPartShared().
copyNew()
void ModelPart::copyNew (ModelPart * modelPart)
References copy().
copyStuff()
void ModelPart::copyStuff (ModelPart * modelPart)
References ModelPartShared::copy(), and modelPartShared().
date()
const QDate & ModelPart::date ()
References m_modelPartShared.
dbid()
qulonglong ModelPart::dbid ()
References m_modelPartShared.
description()
const QString & ModelPart::description ()
References ___emptyString___, and m_modelPartShared.
displayKeys()
const QStringList & ModelPart::displayKeys ()
References ___emptyStringList___, and m_modelPartShared.
ensureInstanceTitleIncrements()
ModelPartList * ModelPart::ensureInstanceTitleIncrements (const QString & prefix) protected
References AllInstanceTitleIncrements, and NullInstanceTitleIncrements.
family()
QString ModelPart::family ()
References m_modelPartShared.
flippedSMD()
bool ModelPart::flippedSMD ()
References m_modelPartShared.
flipSMDAnd()
void ModelPart::flipSMDAnd ()
References m_modelPartShared.
fritzingVersion()
const QString & ModelPart::fritzingVersion ()
References ___emptyString___, and m_modelPartShared.
getAllNonCoreParts()
QList< ModelPart * > ModelPart::getAllNonCoreParts ()
References isCore().
getAllParts()
QList< ModelPart * > ModelPart::getAllParts ()
getConnector()
Connector * ModelPart::getConnector (const QString & id)
References m_connectorHash.
getNextTitle()
QString ModelPart::getNextTitle (const QString & candidate)
References ensureInstanceTitleIncrements(), instanceTitle(), InstanceTitleRegExp(), and title().
hasBaseNameFor()
QString ModelPart::hasBaseNameFor (ViewLayer::ViewID viewID)
References ___emptyString___, and m_modelPartShared.
hasSubparts()
bool ModelPart::hasSubparts ()
References m_modelPartShared.
hasViewFor() [1/2]
bool ModelPart::hasViewFor (ViewLayer::ViewID viewID)
References m_modelPartShared.
hasViewFor() [2/2]
bool ModelPart::hasViewFor (ViewLayer::ViewID viewID, ViewLayer::ViewLayerID viewLayerID)
References m_modelPartShared.
hasViewID() [1/2]
bool ModelPart::hasViewID (ViewLayer::ViewID viewID)
References m_modelPartShared.
hasViewID() [2/2]
bool ModelPart::hasViewID (long id)
References ItemBase::id(), and m_viewItems.
hasViewItems()
bool ModelPart::hasViewItems ()
References m_viewItems.
hasZeroConnector()
bool ModelPart::hasZeroConnector ()
References m_modelPartShared.
ignoreTerminalPoints()
bool ModelPart::ignoreTerminalPoints ()
References m_modelPartShared.
imageFileName() [1/2]
QString ModelPart::imageFileName (ViewLayer::ViewID viewID)
References m_modelPartShared.
imageFileName() [2/2]
QString ModelPart::imageFileName (ViewLayer::ViewID viewID, ViewLayer::ViewLayerID viewLayerID)
References m_modelPartShared.
initBuses()
void ModelPart::initBuses ()
References Bus::addConnector(), ConnectorShared::bus(), bus(), Connector::connectorShared(), BusShared::id(), m_busHash, m_connectorHash, and Connector::setBus().
initConnectors()
void ModelPart::initConnectors (bool force = false)
References clearBuses(), ConnectorShared::id(), initBuses(), m_connectorHash, and m_modelPartShared.
instanceDomElement()
const QDomElement & ModelPart::instanceDomElement ()
References m_instanceDomElement.
instanceText()
const QString & ModelPart::instanceText ()
References m_instanceText.
instanceTitle()
const QString & ModelPart::instanceTitle () const
References m_instanceTitle.
isAlien()
bool ModelPart::isAlien ()
References AlienFlag, and m_locationFlags.
isContrib()
bool ModelPart::isContrib ()
References ContribFlag, and m_locationFlags.
isCore()
bool ModelPart::isCore ()
References CoreFlag, and m_locationFlags.
isFzz()
bool ModelPart::isFzz ()
References FzzFlag, and m_locationFlags.
isInBin()
bool ModelPart::isInBin ()
References InBinFlag, and m_locationFlags.
isObsolete()
bool ModelPart::isObsolete ()
References m_modelPartShared.
itemType()
ModelPart::ItemType ModelPart::itemType () const
References m_type.
killViewItems()
void ModelPart::killViewItems ()
References m_viewItems.
label()
const QString & ModelPart::label ()
References ___emptyString___, and m_modelPartShared.
language()
const QString& ModelPart::language ()
localProp() [1/2]
QVariant ModelPart::localProp (const QString & name) const
localProp() [2/2]
QVariant ModelPart::localProp (const char * name) const
lookForZeroConnector()
void ModelPart::lookForZeroConnector ()
References m_modelPartShared.
modelIndex()
long ModelPart::modelIndex ()
References m_index.
modelPartShared()
ModelPartShared * ModelPart::modelPartShared ()
References m_modelPartShared.
modelPartSharedRoot()
ModelPartSharedRoot * ModelPart::modelPartSharedRoot ()
References m_modelPartShared.
moduleID()
const QString & ModelPart::moduleID () const
References ___emptyString___, and m_modelPartShared.
needsCopper1()
bool ModelPart::needsCopper1 ()
References m_modelPartShared.
nextIndex()
long ModelPart::nextIndex () static
References m_nextIndex.
path()
const QString & ModelPart::path ()
References ___emptyString___, and m_modelPartShared.
possibleFolders()
const QStringList & ModelPart::possibleFolders () static
References m_possibleFolders.
properties()
const QHash< QString, QString > & ModelPart::properties () const
References ___emptyStringHash___, and m_modelPartShared.
removeViewItem()
void ModelPart::removeViewItem (class ItemBase * item)
References m_viewItems.
replacedby()
const QString & ModelPart::replacedby ()
References ___emptyString___, and m_modelPartShared.
saveAsPart()
void ModelPart::saveAsPart (QXmlStreamWriter & streamWriter, bool startDocument)
References connectors(), m_modelPartShared, m_viewItems, moduleID(), PartFactory::OldSchematicPrefix, Connector::saveAsPart(), saveAsPart(), spice(), spiceModel(), title(), Version::versionString(), writeNestedTag(), writeTag(), and ItemBase::writeXml().
saveInstance()
void ModelPart::saveInstance (QXmlStreamWriter & streamWriter) protected
References Connector::connectorLocalName(), connectors(), Connector::connectorSharedID(), TextUtils::escapeAnd(), instanceText(), instanceTitle(), localProp(), m_index, m_modelPartShared, m_viewItems, PartFactory::OldSchematicPrefix, ItemBase::saveInstance(), TextUtils::stripNonValidXMLCharacters(), title(), and writeTag().
saveInstances()
void ModelPart::saveInstances (const QString & fileName, QXmlStreamWriter & streamWriter, bool startDocument)
References ModelPartSharedRoot::icon(), m_orderedChildren, modelPartSharedRoot(), saveInstance(), saveInstances(), ModelPartSharedRoot::searchTerm(), startSaveInstances(), title(), and Version::versionString().
setAlien()
void ModelPart::setAlien (bool alien)
References AlienFlag, and setLocationFlag().
setConnectorLocalName()
void ModelPart::setConnectorLocalName (const QString & id, const QString & name)
References m_connectorHash, and Connector::setConnectorLocalName().
setContrib()
void ModelPart::setContrib (bool contrib)
References ContribFlag, and setLocationFlag().
setCore()
void ModelPart::setCore (bool core)
References CoreFlag, and setLocationFlag().
setDBID()
void ModelPart::setDBID (qulonglong dbid)
References dbid(), and m_modelPartShared.
setFzz()
void ModelPart::setFzz (bool alien)
References FzzFlag, and setLocationFlag().
setImageFileName()
void ModelPart::setImageFileName (ViewLayer::ViewID viewID, const QString & filename)
References m_modelPartShared.
setInBin()
void ModelPart::setInBin (bool inBin)
References InBinFlag, and setLocationFlag().
setInstanceDomElement()
void ModelPart::setInstanceDomElement (const QDomElement & domElement)
References m_instanceDomElement.
setInstanceText()
void ModelPart::setInstanceText (QString text)
References m_instanceText.
setInstanceTitle()
void ModelPart::setInstanceTitle (QString title, bool initial)
References clearOldInstanceTitle(), ensureInstanceTitleIncrements(), InstanceTitleRegExp(), m_instanceTitle, m_modelPartShared, m_viewItems, ItemBase::setInstanceTitle(), setSubpartInstanceTitle(), ItemBase::subparts(), and title().
setItemType()
void ModelPart::setItemType (ItemType t)
References m_type.
setLocalProp() [1/2]
void ModelPart::setLocalProp (const QString & name, const QVariant & value)
setLocalProp() [2/2]
void ModelPart::setLocalProp (const char * name, const QVariant & value)
setLocalTitle()
void ModelPart::setLocalTitle (const QString & localTitle)
References m_localTitle.
setLocationFlag()
void ModelPart::setLocationFlag (bool setting, LocationFlag flag)
References m_locationFlags.
setModelIndex()
void ModelPart::setModelIndex (long index)
References m_index, and updateIndex().
setModelIndexFromMultiplied()
void ModelPart::setModelIndexFromMultiplied (long multipliedIndex)
References indexMultiplier, m_index, m_indexSynched, and setModelIndex().
setModelPartShared()
void ModelPart::setModelPartShared (ModelPartShared * modelPartShared)
References m_modelPartShared, and modelPartShared().
setOrderedChildren()
void ModelPart::setOrderedChildren (QList< QObject * > children)
References m_orderedChildren.
setProperty()
void ModelPart::setProperty (const QString & key, const QString & value, bool showInLabel)
References m_modelPartShared, and showInLabel().
setSubpartID()
void ModelPart::setSubpartID (const QString & id)
References m_modelPartShared.
setSubpartInstanceTitle()
bool ModelPart::setSubpartInstanceTitle () protected
References ItemBase::instanceTitle(), label(), m_instanceTitle, m_modelPartShared, m_viewItems, and ItemBase::superpart().
setTag()
void ModelPart::setTag (const QString & tag)
References m_modelPartShared.
setViewImage()
void ModelPart::setViewImage (struct ViewImage * viewImage)
References m_modelPartShared.
showInLabel()
bool ModelPart::showInLabel (const QString & key)
References m_modelPartShared.
spice()
const QString & ModelPart::spice ()
References ___emptyString___, and m_modelPartShared.
spiceModel()
const QString & ModelPart::spiceModel ()
References ___emptyString___, and m_modelPartShared.
startSaveInstances
void ModelPart::startSaveInstances (const QString & fileName, ModelPart * , QXmlStreamWriter &) signal
tags()
const QStringList & ModelPart::tags ()
References ___emptyStringList___, and m_modelPartShared.
taxonomy()
const QString & ModelPart::taxonomy ()
References ___emptyString___, and m_modelPartShared.
title()
const QString & ModelPart::title ()
References m_localTitle, and m_modelPartShared.
updateIndex()
void ModelPart::updateIndex (long index) static
References m_nextIndex.
uri()
const QString & ModelPart::uri ()
References ___emptyString___, and m_modelPartShared.
url()
const QString & ModelPart::url ()
References ___emptyString___, and m_modelPartShared.
version()
const QString & ModelPart::version ()
References ___emptyString___, and m_modelPartShared.
viewImages()
const QList< ViewImage * > ModelPart::viewImages ()
References EmptyViewImages, and m_modelPartShared.
viewItem() [1/2]
ItemBase * ModelPart::viewItem (QGraphicsScene * scene)
References m_viewItems.
viewItem() [2/2]
ItemBase * ModelPart::viewItem (ViewLayer::ViewID viewID)
References m_viewItems, and ItemBase::viewID().
viewLayers()
LayerList ModelPart::viewLayers (ViewLayer::ViewID viewID)
References m_modelPartShared.
writeNestedTag() [1/2]
void ModelPart::writeNestedTag (QXmlStreamWriter & streamWriter, QString tagName, const QStringList & values, QString childTag) protected
References writeTag().
writeNestedTag() [2/2]
void ModelPart::writeNestedTag (QXmlStreamWriter & streamWriter, QString tagName, const QHash< QString, QString > & values, QString childTag, QString attrName) protected
writeTag()
void ModelPart::writeTag (QXmlStreamWriter & streamWriter, QString tagName, QString tagValue) protected
Member Data Documentation
indexMultiplier
const int ModelPart::indexMultiplier = 10 static
itemTypeNames
QHash<ItemType, QString> ModelPart::itemTypeNames static protected
m_busHash
QHash<QString, QPointer<Bus> > ModelPart::m_busHash protected
m_connectorHash
QHash<QString, QPointer<Connector> > ModelPart::m_connectorHash protected
m_index
long ModelPart::m_index protected
m_indexSynched
bool ModelPart::m_indexSynched protected
m_instanceDomElement
QDomElement ModelPart::m_instanceDomElement protected
m_instanceText
QString ModelPart::m_instanceText protected
m_instanceTitle
QString ModelPart::m_instanceTitle protected
m_localTitle
QString ModelPart::m_localTitle protected
m_locationFlags
LocationFlags ModelPart::m_locationFlags protected
m_modelPartShared
QPointer<ModelPartShared> ModelPart::m_modelPartShared protected
m_nextIndex
long ModelPart::m_nextIndex = 0 static protected
m_orderedChildren
QList<QObject*> ModelPart::m_orderedChildren protected
m_possibleFolders
QStringList ModelPart::m_possibleFolders static protected
m_type
ItemType ModelPart::m_type protected
m_viewItems
QList< QPointer<class ItemBase> > ModelPart::m_viewItems protected
The documentation for this class was generated from the following files:
model/modelpart.h
model/modelpart.cpp