Fritzing: SetPropCommand Class Reference
SetPropCommand Class Reference
#include <commands.h>
Public Member Functions
SetPropCommand (class SketchWidget *, long itemID, QString prop, QString oldValue, QString newValue, bool redraw, QUndoCommand *parent)
void redo ()
void undo ()
Public Member Functions inherited from BaseCommand
BaseCommand (BaseCommand::CrossViewType, SketchWidget *, QUndoCommand *parent)
~BaseCommand ()
void addSubCommand (BaseCommand *subCommand)
BaseCommand::CrossViewType crossViewType () const noexcept
virtual QString getDebugString () const
int index () const
const QUndoCommand * parentCommand () const
void redo ()
void setCrossViewType (BaseCommand::CrossViewType)
void setRedoOnly ()
void setSkipFirstRedo ()
void setUndoOnly ()
SketchWidget * sketchWidget () const
const BaseCommand * subCommand (int index) const
int subCommandCount () const
void subRedo ()
void subRedo (int index)
void subUndo ()
void subUndo (int index)
void undo ()
Protected Member Functions
QString getParamString () const
Protected Attributes
long m_itemID
QString m_newValue
QString m_oldValue
QString m_prop
bool m_redraw
Protected Attributes inherited from BaseCommand
QList< BaseCommand * > m_commands
BaseCommand::CrossViewType m_crossViewType
int m_index = 0
QUndoCommand * m_parentCommand = nullptr
bool m_redoOnly = false
SketchWidget * m_sketchWidget = nullptr
bool m_skipFirstRedo = false
bool m_undoOnly = false
Additional Inherited Members
Public Types inherited from BaseCommand
enum CrossViewType { SingleView, CrossView }
Static Public Member Functions inherited from BaseCommand
static void clearProgress ()
static CommandProgress * initProgress ()
static int totalChildCount (const QUndoCommand *)
Static Protected Attributes inherited from BaseCommand
static CommandProgress m_commandProgress
static int nextIndex = 0
Constructor & Destructor Documentation
SetPropCommand()
SetPropCommand::SetPropCommand (class SketchWidget * sketchWidget, long itemID, QString prop, QString oldValue, QString newValue, bool redraw, QUndoCommand * parent)
Member Function Documentation
getParamString()
QString SetPropCommand::getParamString () const protected virtual
Reimplemented from BaseCommand.
References BaseCommand::getParamString(), m_itemID, m_newValue, m_oldValue, and m_prop.
redo()
void SetPropCommand::redo ()
References m_itemID, m_newValue, m_prop, m_redraw, BaseCommand::m_sketchWidget, BaseCommand::redo(), and SketchWidget::setProp().
undo()
void SetPropCommand::undo ()
References m_itemID, m_oldValue, m_prop, m_redraw, BaseCommand::m_sketchWidget, SketchWidget::setProp(), and BaseCommand::undo().
Member Data Documentation
m_itemID
long SetPropCommand::m_itemID protected
m_newValue
QString SetPropCommand::m_newValue protected
m_oldValue
QString SetPropCommand::m_oldValue protected
m_prop
QString SetPropCommand::m_prop protected
m_redraw
bool SetPropCommand::m_redraw protected
The documentation for this class was generated from the following files:
commands.h
commands.cpp