Fritzing: ViewGeometry Class Reference
ViewGeometry Class Reference
#include <viewgeometry.h>
Public Types
enum WireFlag {
NoFlag = 0, RoutedFlag = 2, PCBTraceFlag = 4, ObsoleteJumperFlag = 8,
RatsnestFlag = 16, AutoroutableFlag = 32, NormalFlag = 64, SchematicTraceFlag = 128
}
Public Member Functions
ViewGeometry ()
ViewGeometry (QDomElement &)
ViewGeometry (const ViewGeometry &)
~ViewGeometry ()
int flagsAsInt () const
bool getAnyTrace () const
bool getAutoroutable () const
bool getNormal () const
bool getPCBTrace () const
bool getRatsnest () const
bool getRouted () const
bool getSchematicTrace () const
bool hasAnyFlag (WireFlags)
bool hasFlag (WireFlag)
constexpr QLineF line () const noexcept
constexpr QPointF loc () const noexcept
void offset (double x, double y)
constexpr QRectF rect () const noexcept
constexpr bool selected () const noexcept
void set (const ViewGeometry &)
void setAutoroutable (bool)
void setLine (QLineF)
void setLoc (QPointF)
void setNormal (bool)
void setPCBTrace (bool)
void setRatsnest (bool)
void setRect (double x, double y, double width, double height)
void setRect (const QRectF &)
void setRouted (bool)
void setSchematicTrace (bool)
void setSelected (bool)
void setTransform (QTransform)
void setWireFlags (WireFlags)
void setZ (double) noexcept
QTransform transform () const noexcept
ViewGeometry::WireFlags wireFlags () const
constexpr double z () const noexcept
Protected Member Functions
void setWireFlag (bool setting, WireFlag flag)
Protected Attributes
QLineF m_line
QPointF m_loc
QRectF m_rect
bool m_selected = false
QTransform m_transform
WireFlags m_wireFlags
double m_z = -1
Member Enumeration Documentation
WireFlag
enum ViewGeometry::WireFlag
Enumerator
NoFlag
RoutedFlag
PCBTraceFlag
ObsoleteJumperFlag
RatsnestFlag
AutoroutableFlag
NormalFlag
SchematicTraceFlag
Constructor & Destructor Documentation
ViewGeometry() [1/3]
ViewGeometry::ViewGeometry ()
ViewGeometry() [2/3]
ViewGeometry::ViewGeometry (QDomElement & geometry)
References GraphicsUtils::loadTransform(), m_line, m_rect, and m_transform.
ViewGeometry() [3/3]
ViewGeometry::ViewGeometry (const ViewGeometry & that)
~ViewGeometry()
ViewGeometry::~ViewGeometry () inline
Member Function Documentation
flagsAsInt()
int ViewGeometry::flagsAsInt () const
References m_wireFlags.
getAnyTrace()
bool ViewGeometry::getAnyTrace () const
References getPCBTrace(), and getSchematicTrace().
getAutoroutable()
bool ViewGeometry::getAutoroutable () const
References AutoroutableFlag, and m_wireFlags.
getNormal()
bool ViewGeometry::getNormal () const
References m_wireFlags, and NormalFlag.
getPCBTrace()
bool ViewGeometry::getPCBTrace () const
References m_wireFlags, and PCBTraceFlag.
getRatsnest()
bool ViewGeometry::getRatsnest () const
References m_wireFlags, and RatsnestFlag.
getRouted()
bool ViewGeometry::getRouted () const
References m_wireFlags, and RoutedFlag.
getSchematicTrace()
bool ViewGeometry::getSchematicTrace () const
References m_wireFlags, and SchematicTraceFlag.
hasAnyFlag()
bool ViewGeometry::hasAnyFlag (WireFlags)
References m_wireFlags.
hasFlag()
bool ViewGeometry::hasFlag (ViewGeometry::WireFlag flag)
References m_wireFlags.
line()
constexpr QLineF ViewGeometry::line () const inline noexcept
References m_line.
loc()
constexpr QPointF ViewGeometry::loc () const inline noexcept
References m_loc.
offset()
void ViewGeometry::offset (double x, double y)
References m_loc.
rect()
constexpr QRectF ViewGeometry::rect () const inline noexcept
References m_rect.
selected()
constexpr bool ViewGeometry::selected () const inline noexcept
References m_selected.
set()
void ViewGeometry::set (const ViewGeometry & that)
References m_line, m_loc, m_rect, m_transform, m_wireFlags, and m_z.
setAutoroutable()
void ViewGeometry::setAutoroutable (bool autoroutable)
References AutoroutableFlag, and setWireFlag().
setLine()
void ViewGeometry::setLine (QLineF loc)
References loc(), and m_line.
setLoc()
void ViewGeometry::setLoc (QPointF loc)
References loc(), and m_loc.
setNormal()
void ViewGeometry::setNormal (bool normal)
References NormalFlag, and setWireFlag().
setPCBTrace()
void ViewGeometry::setPCBTrace (bool trace)
References PCBTraceFlag, and setWireFlag().
setRatsnest()
void ViewGeometry::setRatsnest (bool ratsnest)
References RatsnestFlag, and setWireFlag().
setRect() [1/2]
void ViewGeometry::setRect (double x, double y, double width, double height)
References m_rect.
setRect() [2/2]
void ViewGeometry::setRect (const QRectF & r)
References setRect().
setRouted()
void ViewGeometry::setRouted (bool routed)
References RoutedFlag, and setWireFlag().
setSchematicTrace()
void ViewGeometry::setSchematicTrace (bool trace)
References SchematicTraceFlag, and setWireFlag().
setSelected()
void ViewGeometry::setSelected (bool selected)
References m_selected, and selected().
setTransform()
void ViewGeometry::setTransform (QTransform transform)
References m_transform, and transform().
setWireFlag()
void ViewGeometry::setWireFlag (bool setting, WireFlag flag) protected
References m_wireFlags.
setWireFlags()
void ViewGeometry::setWireFlags (WireFlags wireFlags)
References m_wireFlags, and wireFlags().
setZ()
void ViewGeometry::setZ (double z) noexcept
transform()
QTransform ViewGeometry::transform () const inline noexcept
References m_transform.
wireFlags()
ViewGeometry::WireFlags ViewGeometry::wireFlags () const
References m_wireFlags.
z()
constexpr double ViewGeometry::z () const inline noexcept
References m_z.
Member Data Documentation
m_line
QLineF ViewGeometry::m_line protected
m_loc
QPointF ViewGeometry::m_loc protected
m_rect
QRectF ViewGeometry::m_rect protected
m_selected
bool ViewGeometry::m_selected = false protected
m_transform
QTransform ViewGeometry::m_transform protected
m_wireFlags
WireFlags ViewGeometry::m_wireFlags protected
m_z
double ViewGeometry::m_z = -1 protected
The documentation for this class was generated from the following files:
viewgeometry.h
viewgeometry.cpp