Fritzing: ModelPartShared Class Reference
ModelPartShared Class Reference
#include <modelpartshared.h>
Public Member Functions
ModelPartShared ()
ModelPartShared (QDomDocument &, const QString &path)
~ModelPartShared ()
void addConnector (ConnectorShared *)
void addOwner (QObject *)
void addSubpart (ModelPartShared *subpart)
bool anySticky (ViewLayer::ViewID)
const QString & author ()
bool canFlipHorizontal (ViewLayer::ViewID)
bool canFlipVertical (ViewLayer::ViewID)
void connectorIDs (ViewLayer::ViewID viewId, ViewLayer::ViewLayerID viewLayerID, QStringList &connectorIDs, QStringList &terminalIDs, QStringList &legIDs)
const QList< QPointer< class ConnectorShared > > connectorsShared ()
void copy (ModelPartShared *other)
const QDate & date ()
const QString & dateAsStr ()
qulonglong dbid ()
const QString & description ()
const QStringList & displayKeys ()
QString family ()
bool flippedSMD ()
void flipSMDAnd ()
const QString & fritzingVersion ()
ConnectorShared * getConnectorShared (const QString &id)
QString hasBaseNameFor (ViewLayer::ViewID)
bool hasMultipleLayers (ViewLayer::ViewID)
bool hasSubparts ()
bool hasViewFor (ViewLayer::ViewID)
bool hasViewFor (ViewLayer::ViewID, ViewLayer::ViewLayerID)
bool hasViewID (ViewLayer::ViewID viewID)
bool hasZeroConnector ()
bool ignoreTerminalPoints ()
QString imageFileName (ViewLayer::ViewID, ViewLayer::ViewLayerID)
QString imageFileName (ViewLayer::ViewID)
void initConnectors ()
void insertBus (class BusShared *)
const QString & label () const
void lookForZeroConnector ()
const QString & moduleID ()
bool needsCopper1 ()
const QString & path ()
QHash< QString, QString > & properties ()
const QString & replacedby ()
void setAuthor (QString)
void setConnectorsInitialized (bool)
void setConnectorsShared (QList< QPointer< class ConnectorShared > > connectors)
void setDate (QDate)
void setDate (QString)
void setDBID (qulonglong)
void setDescription (QString)
void setFamily (const QString &family)
void setFlippedSMD (bool)
void setFritzingVersion (const QString &)
void setImageFileName (ViewLayer::ViewID, const QString &filename)
void setLabel (QString)
void setModuleID (QString)
void setPath (QString path)
void setProperties (const QHash< QString, QString > &properties)
void setProperty (const QString &key, const QString &value, bool showInLabel)
void setReplacedby (const QString &replacedby)
void setSpice (QString)
void setSpiceModel (QString)
void setSubpartID (const QString &)
void setSubpartOffset (QPointF)
void setSuperpart (ModelPartShared *)
void setTag (const QString &tag)
void setTags (const QStringList &tags)
void setTaxonomy (QString taxonomy)
void setTitle (QString)
void setUri (QString)
void setUrl (QString)
void setVersion (QString)
void setViewImage (ViewImage *)
bool showInLabel (const QString &key)
const QString & spice ()
const QString & spiceModel ()
const QString & subpartID () const
QPointF subpartOffset () const
const QList< QPointer< ModelPartShared > > & subparts ()
ModelPartShared * superpart ()
const QStringList & tags ()
const QString & taxonomy ()
const QString & title ()
const QString & uri ()
const QString & url ()
const QString & version ()
const QList< ViewImage * > viewImages ()
LayerList viewLayers (ViewLayer::ViewID viewID)
LayerList viewLayersFlipped (ViewLayer::ViewID viewID)
Static Public Attributes
static const QString PartNumberPropertyName = "part number"
Protected Slots
void removeOwner ()
Protected Member Functions
void addSchematicText (ViewImage *)
void commonInit ()
void copyPins (ViewLayer::ViewLayerID from, ViewLayer::ViewLayerID to)
void ensurePartNumberProperty ()
void loadTagText (QDomElement parent, QString tagName, QString &field)
void populateProperties (QDomElement parent, QHash< QString, QString > &hash, QStringList &displayKeys)
void populateTags (QDomElement parent, QStringList &list)
bool setDomDocument (QDomDocument &)
LayerList viewLayersAux (ViewLayer::ViewID viewID, qulonglong(*accessor)(ViewImage *))
Protected Attributes
QString m_author
QHash< QString, class BusShared * > m_buses
QHash< QString, QPointer< class ConnectorShared > > m_connectorSharedHash
bool m_connectorsInitialized
QString m_date
qulonglong m_dbid
QString m_description
QStringList m_displayKeys
bool m_flippedSMD
QString m_fritzingVersion
bool m_hasZeroConnector
bool m_ignoreTerminalPoints
QString m_label
QString m_moduleID
bool m_needsCopper1
int m_ownerCount
QString m_path
QHash< QString, QString > m_properties
QString m_replacedby
QString m_spice
QString m_spiceModel
QString m_subpartID
QPointF m_subpartOffset
QList< QPointer< ModelPartShared > > m_subparts
QPointer< ModelPartShared > m_superpart
QStringList m_tags
QString m_taxonomy
QString m_title
QString m_uri
QString m_url
QString m_version
QHash< ViewLayer::ViewID, ViewImage * > m_viewImages
Constructor & Destructor Documentation
ModelPartShared() [1/2]
ModelPartShared::ModelPartShared ()
References commonInit(), and m_path.
ModelPartShared() [2/2]
ModelPartShared::ModelPartShared (QDomDocument & domDocument, const QString & path)
References commonInit(), m_path, path(), and setDomDocument().
~ModelPartShared()
ModelPartShared::~ModelPartShared ()
References m_buses, m_connectorSharedHash, and m_viewImages.
Member Function Documentation
addConnector()
void ModelPartShared::addConnector (ConnectorShared * connectorShared)
References ConnectorShared::id(), and m_connectorSharedHash.
addOwner()
void ModelPartShared::addOwner (QObject * owner)
References m_ownerCount, and removeOwner().
addSchematicText()
void ModelPartShared::addSchematicText (ViewImage * viewImage) protected
References ViewImage::canFlipHorizontal, ViewImage::canFlipVertical, ViewImage::layers, ViewLayer::Schematic, ViewLayer::SchematicText, ViewLayer::SchematicView, and ViewImage::viewID.
addSubpart()
void ModelPartShared::addSubpart (ModelPartShared * subpart)
References m_subparts, and setSuperpart().
anySticky()
bool ModelPartShared::anySticky (ViewLayer::ViewID viewID)
References m_viewImages, ViewImage::sticky, and ItemBase::viewID().
author()
const QString & ModelPartShared::author ()
References m_author.
canFlipHorizontal()
bool ModelPartShared::canFlipHorizontal (ViewLayer::ViewID viewID)
References ViewImage::canFlipHorizontal, m_viewImages, and ItemBase::viewID().
canFlipVertical()
bool ModelPartShared::canFlipVertical (ViewLayer::ViewID viewID)
References ViewImage::canFlipVertical, m_viewImages, and ItemBase::viewID().
commonInit()
void ModelPartShared::commonInit () protected
References m_connectorsInitialized, m_dbid, m_flippedSMD, m_hasZeroConnector, m_ignoreTerminalPoints, m_moduleID, m_needsCopper1, m_ownerCount, and m_superpart.
connectorIDs()
void ModelPartShared::connectorIDs (ViewLayer::ViewID viewId, ViewLayer::ViewLayerID viewLayerID, QStringList & connectorIDs, QStringList & terminalIDs, QStringList & legIDs)
References ConnectorShared::fullPinInfo(), m_connectorSharedHash, SvgIdLayer::m_legId, SvgIdLayer::m_svgId, SvgIdLayer::m_terminalId, ItemBase::viewID(), and ItemBase::viewLayerID().
connectorsShared()
const QList< QPointer< ConnectorShared > > ModelPartShared::connectorsShared ()
References m_connectorSharedHash.
copy()
void ModelPartShared::copy (ModelPartShared * other)
References author(), ViewImage::canFlipHorizontal, ViewImage::canFlipVertical, connectorsShared(), date(), description(), family(), ViewImage::image, label(), ViewImage::layers, m_viewImages, properties(), setAuthor(), setConnectorsShared(), setDate(), setDescription(), setFamily(), setLabel(), setProperties(), setSpice(), setSpiceModel(), setSuperpart(), setTags(), setTaxonomy(), setTitle(), setUri(), setUrl(), setVersion(), spice(), spiceModel(), ViewImage::sticky, superpart(), tags(), taxonomy(), title(), uri(), url(), version(), and ItemBase::viewID().
copyPins()
void ModelPartShared::copyPins (ViewLayer::ViewLayerID from, ViewLayer::ViewLayerID to) protected
References SvgIdLayer::copyLayer(), DebugDialog::debug(), ConnectorShared::fullPinInfo(), ConnectorShared::insertPin(), m_connectorSharedHash, SvgIdLayer::m_svgViewLayerID, moduleID(), and ViewLayer::PCBView.
date()
const QDate & ModelPartShared::date ()
References m_date.
dateAsStr()
const QString & ModelPartShared::dateAsStr ()
References m_date.
dbid()
qulonglong ModelPartShared::dbid ()
References m_dbid.
description()
const QString & ModelPartShared::description ()
References m_description.
displayKeys()
const QStringList & ModelPartShared::displayKeys ()
References m_displayKeys.
ensurePartNumberProperty()
void ModelPartShared::ensurePartNumberProperty () protected
References m_displayKeys, m_properties, and PartNumberPropertyName.
family()
QString ModelPartShared::family ()
References m_properties.
flippedSMD()
bool ModelPartShared::flippedSMD ()
References m_flippedSMD.
flipSMDAnd()
void ModelPartShared::flipSMDAnd ()
References ViewLayer::Copper0, ViewLayer::Copper1, copyPins(), ViewImage::flipped, ViewImage::layers, m_needsCopper1, m_properties, m_viewImages, path(), ViewLayer::PCBView, ResourcePath(), setFlippedSMD(), ViewLayer::Silkscreen0, ViewLayer::Silkscreen1, and viewLayers().
fritzingVersion()
const QString & ModelPartShared::fritzingVersion ()
References m_fritzingVersion.
getConnectorShared()
ConnectorShared * ModelPartShared::getConnectorShared (const QString & id)
References m_connectorSharedHash.
hasBaseNameFor()
QString ModelPartShared::hasBaseNameFor (ViewLayer::ViewID viewID)
References ViewImage::image, m_viewImages, and ItemBase::viewID().
hasMultipleLayers()
bool ModelPartShared::hasMultipleLayers (ViewLayer::ViewID viewID)
References ViewImage::layers, layers(), m_viewImages, and ItemBase::viewID().
hasSubparts()
bool ModelPartShared::hasSubparts ()
References m_subparts.
hasViewFor() [1/2]
bool ModelPartShared::hasViewFor (ViewLayer::ViewID viewID)
References ViewImage::layers, m_viewImages, and ItemBase::viewID().
hasViewFor() [2/2]
bool ModelPartShared::hasViewFor (ViewLayer::ViewID viewID, ViewLayer::ViewLayerID viewLayerID)
References ViewImage::layers, m_viewImages, ItemBase::viewID(), and ItemBase::viewLayerID().
hasViewID()
bool ModelPartShared::hasViewID (ViewLayer::ViewID viewID)
References ViewImage::layers, m_viewImages, and ItemBase::viewID().
hasZeroConnector()
bool ModelPartShared::hasZeroConnector ()
References m_hasZeroConnector.
ignoreTerminalPoints()
bool ModelPartShared::ignoreTerminalPoints ()
References m_ignoreTerminalPoints.
imageFileName() [1/2]
QString ModelPartShared::imageFileName (ViewLayer::ViewID viewID, ViewLayer::ViewLayerID viewLayerID)
References ViewImage::image, ViewImage::layers, m_viewImages, ItemBase::viewID(), and ItemBase::viewLayerID().
imageFileName() [2/2]
QString ModelPartShared::imageFileName (ViewLayer::ViewID viewID)
References ViewImage::image, m_viewImages, and ItemBase::viewID().
initConnectors()
void ModelPartShared::initConnectors ()
References ItemBase::buses(), BusShared::id(), ConnectorShared::id(), lookForZeroConnector(), m_buses, m_connectorSharedHash, m_connectorsInitialized, m_ignoreTerminalPoints, and m_path.
insertBus()
void ModelPartShared::insertBus (class BusShared * busShared)
References BusShared::id(), and m_buses.
label()
const QString & ModelPartShared::label () const
References m_label.
loadTagText()
void ModelPartShared::loadTagText (QDomElement parent, QString tagName, QString & field) protected
lookForZeroConnector()
void ModelPartShared::lookForZeroConnector ()
References IntegerFinder(), m_connectorSharedHash, and m_hasZeroConnector.
moduleID()
const QString & ModelPartShared::moduleID ()
References m_moduleID.
needsCopper1()
bool ModelPartShared::needsCopper1 ()
References m_needsCopper1.
path()
const QString & ModelPartShared::path ()
References m_path.
populateProperties()
void ModelPartShared::populateProperties (QDomElement parent, QHash< QString, QString > & hash, QStringList & displayKeys) protected
References displayKeys(), ItemBase::prop(), and properties().
populateTags()
void ModelPartShared::populateTags (QDomElement parent, QStringList & list) protected
References tags().
properties()
QHash< QString, QString > & ModelPartShared::properties ()
References m_properties.
removeOwner
void ModelPartShared::removeOwner () protected slot
References m_ownerCount.
replacedby()
const QString & ModelPartShared::replacedby ()
References m_replacedby.
setAuthor()
void ModelPartShared::setAuthor (QString author)
References author(), and m_author.
setConnectorsInitialized()
void ModelPartShared::setConnectorsInitialized (bool init)
References m_connectorsInitialized.
setConnectorsShared()
void ModelPartShared::setConnectorsShared (QList< QPointer< class ConnectorShared > > connectors)
References ConnectorShared::id(), and m_connectorSharedHash.
setDate() [1/2]
void ModelPartShared::setDate (QDate date)
References date(), and m_date.
setDate() [2/2]
void ModelPartShared::setDate (QString date)
References date(), and m_date.
setDBID()
void ModelPartShared::setDBID (qulonglong dbid)
References dbid(), and m_dbid.
setDescription()
void ModelPartShared::setDescription (QString description)
References description(), and m_description.
setDomDocument()
bool ModelPartShared::setDomDocument (QDomDocument & domDocument) protected
References addSchematicText(), ensurePartNumberProperty(), ViewLayer::idFromXmlName(), layers(), loadTagText(), m_author, m_date, m_description, m_displayKeys, m_fritzingVersion, m_label, m_moduleID, m_properties, m_replacedby, m_spice, m_spiceModel, m_tags, m_taxonomy, m_title, m_url, m_version, m_viewImages, populateProperties(), populateTags(), spice(), version(), ItemBase::viewID(), ItemBase::viewLayerID(), and ViewLayer::viewLayerIDFromXmlString().
setFamily()
void ModelPartShared::setFamily (const QString & family)
References family(), and m_properties.
setFlippedSMD()
void ModelPartShared::setFlippedSMD (bool f)
References m_flippedSMD.
setFritzingVersion()
void ModelPartShared::setFritzingVersion (const QString & fv)
References m_fritzingVersion.
setImageFileName()
void ModelPartShared::setImageFileName (ViewLayer::ViewID viewID, const QString & filename)
References ViewImage::image, m_viewImages, and ItemBase::viewID().
setLabel()
void ModelPartShared::setLabel (QString label)
References label(), and m_label.
setModuleID()
void ModelPartShared::setModuleID (QString moduleID)
References m_moduleID, and moduleID().
setPath()
void ModelPartShared::setPath (QString path)
References m_path, and path().
setProperties()
void ModelPartShared::setProperties (const QHash< QString, QString > & properties)
References ensurePartNumberProperty(), m_properties, and properties().
setProperty()
void ModelPartShared::setProperty (const QString & key, const QString & value, bool showInLabel)
References m_displayKeys, m_properties, and showInLabel().
setReplacedby()
void ModelPartShared::setReplacedby (const QString & replacedby)
References m_replacedby, and replacedby().
setSpice()
void ModelPartShared::setSpice (QString spice)
References m_spice, and spice().
setSpiceModel()
void ModelPartShared::setSpiceModel (QString model)
References m_spiceModel.
setSubpartID()
void ModelPartShared::setSubpartID (const QString & id)
References ItemBase::id(), and m_subpartID.
setSubpartOffset()
void ModelPartShared::setSubpartOffset (QPointF p)
References m_subpartOffset.
setSuperpart()
void ModelPartShared::setSuperpart (ModelPartShared * sup)
References m_superpart.
setTag()
void ModelPartShared::setTag (const QString & tag)
References m_tags.
setTags()
void ModelPartShared::setTags (const QStringList & tags)
References m_tags, and tags().
setTaxonomy()
void ModelPartShared::setTaxonomy (QString taxonomy)
References m_taxonomy, and taxonomy().
setTitle()
void ModelPartShared::setTitle (QString title)
References m_title, and title().
setUri()
void ModelPartShared::setUri (QString uri)
References m_uri, and uri().
setUrl()
void ModelPartShared::setUrl (QString url)
References m_url, and url().
setVersion()
void ModelPartShared::setVersion (QString version)
References m_version, and version().
setViewImage()
void ModelPartShared::setViewImage (ViewImage * viewImage)
References addSchematicText(), m_viewImages, and ViewImage::viewID.
showInLabel()
bool ModelPartShared::showInLabel (const QString & key)
References m_displayKeys.
spice()
const QString & ModelPartShared::spice ()
References m_spice.
spiceModel()
const QString & ModelPartShared::spiceModel ()
References m_spiceModel.
subpartID()
const QString & ModelPartShared::subpartID () const
References m_subpartID.
subpartOffset()
QPointF ModelPartShared::subpartOffset () const
References m_subpartOffset.
subparts()
const QList< QPointer< ModelPartShared > > & ModelPartShared::subparts ()
References m_subparts.
superpart()
ModelPartShared * ModelPartShared::superpart ()
References m_superpart.
tags()
const QStringList & ModelPartShared::tags ()
References m_tags.
taxonomy()
const QString & ModelPartShared::taxonomy ()
References m_taxonomy.
title()
const QString & ModelPartShared::title ()
References m_title.
uri()
const QString & ModelPartShared::uri ()
References m_uri.
url()
const QString & ModelPartShared::url ()
References m_url.
version()
const QString & ModelPartShared::version ()
References m_version.
viewImages()
const QList< ViewImage * > ModelPartShared::viewImages ()
References m_viewImages.
viewLayers()
LayerList ModelPartShared::viewLayers (ViewLayer::ViewID viewID)
References layers(), ItemBase::viewID(), and viewLayersAux().
viewLayersAux()
LayerList ModelPartShared::viewLayersAux (ViewLayer::ViewID viewID, qulonglong(*)(ViewImage *) accessor) protected
References layers(), m_viewImages, ItemBase::viewID(), and ViewLayer::ViewLayerCount.
viewLayersFlipped()
LayerList ModelPartShared::viewLayersFlipped (ViewLayer::ViewID viewID)
References flipped(), ItemBase::viewID(), and viewLayersAux().
Member Data Documentation
m_author
QString ModelPartShared::m_author protected
m_buses
QHash<QString, class BusShared *> ModelPartShared::m_buses protected
m_connectorSharedHash
QHash<QString, QPointer<class ConnectorShared> > ModelPartShared::m_connectorSharedHash protected
m_connectorsInitialized
bool ModelPartShared::m_connectorsInitialized protected
m_date
QString ModelPartShared::m_date protected
m_dbid
qulonglong ModelPartShared::m_dbid protected
m_description
QString ModelPartShared::m_description protected
m_displayKeys
QStringList ModelPartShared::m_displayKeys protected
m_flippedSMD
bool ModelPartShared::m_flippedSMD protected
m_fritzingVersion
QString ModelPartShared::m_fritzingVersion protected
m_hasZeroConnector
bool ModelPartShared::m_hasZeroConnector protected
m_ignoreTerminalPoints
bool ModelPartShared::m_ignoreTerminalPoints protected
m_label
QString ModelPartShared::m_label protected
m_moduleID
QString ModelPartShared::m_moduleID protected
m_needsCopper1
bool ModelPartShared::m_needsCopper1 protected
m_ownerCount
int ModelPartShared::m_ownerCount protected
m_path
QString ModelPartShared::m_path protected
m_properties
QHash<QString,QString> ModelPartShared::m_properties protected
m_replacedby
QString ModelPartShared::m_replacedby protected
m_spice
QString ModelPartShared::m_spice protected
m_spiceModel
QString ModelPartShared::m_spiceModel protected
m_subpartID
QString ModelPartShared::m_subpartID protected
m_subpartOffset
QPointF ModelPartShared::m_subpartOffset protected
m_subparts
QList< QPointer<ModelPartShared> > ModelPartShared::m_subparts protected
m_superpart
QPointer<ModelPartShared> ModelPartShared::m_superpart protected
m_tags
QStringList ModelPartShared::m_tags protected
m_taxonomy
QString ModelPartShared::m_taxonomy protected
m_title
QString ModelPartShared::m_title protected
m_uri
QString ModelPartShared::m_uri protected
m_url
QString ModelPartShared::m_url protected
m_version
QString ModelPartShared::m_version protected
m_viewImages
QHash<ViewLayer::ViewID, ViewImage *> ModelPartShared::m_viewImages protected
PartNumberPropertyName
const QString ModelPartShared::PartNumberPropertyName = "part number" static
The documentation for this class was generated from the following files:
model/modelpartshared.h
model/modelpartshared.cpp