Fritzing: SearchLineEdit Class Reference
SearchLineEdit Class Reference
#include <searchlineedit.h>
Signals
void clicked ()
Public Member Functions
SearchLineEdit (QWidget *parent=nullptr)
~SearchLineEdit ()=default
constexpr bool decoy () const noexcept
void setDecoy (bool value)
Static Public Member Functions
static void cleanup ()
Protected Member Functions
void enterEvent (QEvent *)
void leaveEvent (QEvent *)
void mousePressEvent (QMouseEvent *)
void paintEvent (QPaintEvent *)
void setColors (const QColor &base, const QColor &text)
Protected Attributes
bool m_decoy
Constructor & Destructor Documentation
SearchLineEdit()
SearchLineEdit::SearchLineEdit (QWidget * parent = nullptr)
References SearchFieldPixmap.
~SearchLineEdit()
SearchLineEdit::~SearchLineEdit () default
Member Function Documentation
cleanup()
void SearchLineEdit::cleanup () static
References SearchFieldPixmap.
clicked
void SearchLineEdit::clicked () signal
decoy()
constexpr bool SearchLineEdit::decoy () const inline noexcept
References m_decoy.
enterEvent()
void SearchLineEdit::enterEvent (QEvent * event) protected
References m_decoy, and setColors().
leaveEvent()
void SearchLineEdit::leaveEvent (QEvent * event) protected
References m_decoy, and setColors().
mousePressEvent()
void SearchLineEdit::mousePressEvent (QMouseEvent * event) protected
References clicked().
paintEvent()
void SearchLineEdit::paintEvent (QPaintEvent * event) protected
References SearchFieldPixmap.
setColors()
void SearchLineEdit::setColors (const QColor & base, const QColor & text) protected
setDecoy()
void SearchLineEdit::setDecoy (bool value)
References m_decoy, and setColors().
Member Data Documentation
m_decoy
bool SearchLineEdit::m_decoy protected
The documentation for this class was generated from the following files:
partsbinpalette/searchlineedit.h
partsbinpalette/searchlineedit.cpp