Fritzing: BezierDisplay Class Reference
BezierDisplay Class Reference
#include <bezierdisplay.h>
Public Member Functions
BezierDisplay ()
~BezierDisplay ()
void initDisplay (QGraphicsItem *master, Bezier *)
void updateDisplay (QGraphicsItem *master, Bezier *)
Protected Attributes
QGraphicsEllipseItem * m_itemE0
QGraphicsEllipseItem * m_itemE1
QGraphicsLineItem * m_itemL0
QGraphicsLineItem * m_itemL1
Constructor & Destructor Documentation
BezierDisplay()
BezierDisplay::BezierDisplay ()
References m_itemE0, m_itemE1, m_itemL0, and m_itemL1.
~BezierDisplay()
BezierDisplay::~BezierDisplay ()
References m_itemL0, and m_itemL1.
Member Function Documentation
initDisplay()
void BezierDisplay::initDisplay (QGraphicsItem * master, Bezier * bezier)
References Bezier::drag0(), m_itemL0, m_itemL1, ProcessEventBlocker::processEvents(), and updateDisplay().
updateDisplay()
void BezierDisplay::updateDisplay (QGraphicsItem * master, Bezier * bezier)
References Bezier::cp0(), Bezier::cp1(), Bezier::endpoint0(), Bezier::endpoint1(), Bezier::isEmpty(), GraphicsUtils::liangBarskyLineClip(), m_itemL0, and m_itemL1.
Member Data Documentation
m_itemE0
QGraphicsEllipseItem* BezierDisplay::m_itemE0 protected
m_itemE1
QGraphicsEllipseItem* BezierDisplay::m_itemE1 protected
m_itemL0
QGraphicsLineItem* BezierDisplay::m_itemL0 protected
m_itemL1
QGraphicsLineItem* BezierDisplay::m_itemL1 protected
The documentation for this class was generated from the following files:
utils/bezierdisplay.h
utils/bezierdisplay.cpp