Fritzing: AutoCloseMessageBox Class Reference
AutoCloseMessageBox Class Reference
#include <autoclosemessagebox.h>
Public Member Functions
AutoCloseMessageBox (QWidget *parent)
void setEndPos (int x, int y)
void setStartPos (int x, int y)
void start ()
Static Public Member Functions
static void showMessage (QWidget *window, const QString &message)
Protected Types
enum MovingState { MovingOut, Waiting, MovingBack }
Protected Slots
void moveBack ()
void moveOut ()
void wait ()
Protected Member Functions
void mousePressEvent (QMouseEvent *)
void prepMoveBack ()
Protected Attributes
QTimer m_animationTimer
int m_counter
int m_endX
int m_endY
volatile MovingState m_movingState
int m_startX
int m_startY
Member Enumeration Documentation
MovingState
enum AutoCloseMessageBox::MovingState protected
Enumerator
MovingOut
Waiting
MovingBack
Constructor & Destructor Documentation
AutoCloseMessageBox()
AutoCloseMessageBox::AutoCloseMessageBox (QWidget * parent)
Member Function Documentation
mousePressEvent()
void AutoCloseMessageBox::mousePressEvent (QMouseEvent * event) protected
References m_animationTimer, m_movingState, moveOut(), MovingBack, MovingOut, prepMoveBack(), wait(), and Waiting.
moveBack
void AutoCloseMessageBox::moveBack () protected slot
References m_animationTimer, m_counter, m_startX, m_startY, and moveOut().
moveOut
void AutoCloseMessageBox::moveOut () protected slot
References m_animationTimer, m_counter, m_endX, m_endY, m_movingState, Wait, wait(), and Waiting.
prepMoveBack()
void AutoCloseMessageBox::prepMoveBack () protected
References m_animationTimer, m_counter, m_movingState, moveBack(), MovingBack, and Steps.
setEndPos()
void AutoCloseMessageBox::setEndPos (int x, int y)
References m_endX, and m_endY.
setStartPos()
void AutoCloseMessageBox::setStartPos (int x, int y)
References m_startX, and m_startY.
showMessage()
void AutoCloseMessageBox::showMessage (QWidget * window, const QString & message) static
References AutoCloseMessageBox(), MainWindow::realStatusBar(), setEndPos(), setStartPos(), and start().
start()
void AutoCloseMessageBox::start ()
References Interval, m_animationTimer, m_counter, m_movingState, moveOut(), MovingOut, and Steps.
wait
void AutoCloseMessageBox::wait () protected slot
References m_animationTimer, m_counter, and prepMoveBack().
Member Data Documentation
m_animationTimer
QTimer AutoCloseMessageBox::m_animationTimer protected
m_counter
int AutoCloseMessageBox::m_counter protected
m_endX
int AutoCloseMessageBox::m_endX protected
m_endY
int AutoCloseMessageBox::m_endY protected
m_movingState
volatile MovingState AutoCloseMessageBox::m_movingState protected
m_startX
int AutoCloseMessageBox::m_startX protected
m_startY
int AutoCloseMessageBox::m_startY protected
The documentation for this class was generated from the following files:
utils/autoclosemessagebox.h
utils/autoclosemessagebox.cpp