Fritzing: ModelBase Class Reference
ModelBase Class Reference
#include <modelbase.h>
Signals
void loadedInstances (ModelBase *, QDomElement &instances)
void loadedRoot (const QString &fileName, ModelBase *, QDomElement &root)
void loadedViews (ModelBase *, QDomElement &views)
void loadingInstance (ModelBase *, QDomElement &instance)
void loadingInstances (ModelBase *, QDomElement &instances)
void obsoleteSMDOrientationSignal ()
void oldSchematicsSignal (const QString &filename, bool &useOldSchematics)
Public Member Functions
ModelBase (bool makeRoot)
virtual ~ModelBase ()
virtual ModelPart * addModelPart (ModelPart *parent, ModelPart *copyChild)
virtual ModelPart * addPart (QString newPartPath, bool addToReference)
virtual bool addPart (ModelPart *modelPart, bool update)
virtual ModelPart * addPart (QString newPartPath, bool addToReference, bool updateIdAlreadyExists)
bool checkForReversedWires ()
const QString & fritzingVersion ()
ModelPart * genFZP (const QString &moduleID, ModelBase *referenceModel)
bool loadFromFile (const QString &fileName, ModelBase *referenceModel, QList< ModelPart * > &modelParts, bool checkInstances)
bool paste (ModelBase *referenceModel, QByteArray &data, QList< ModelPart * > &modelParts, QHash< QString, QRectF > &boundingRects, bool preserveIndex)
virtual ModelPart * retrieveModelPart (const QString &moduleID)
ModelPart * root ()
ModelPartSharedRoot * rootModelPartShared ()
void save (const QString &fileName, bool asPart)
void save (const QString &fileName, class QXmlStreamWriter &, bool asPart)
void setReferenceModel (ModelBase *)
void setReportMissingModules (bool)
Static Public Member Functions
static bool onCoreList (const QString &moduleID)
Protected Member Functions
ModelPart * createOldSchematicPart (ModelPart *, QString &moduleIDRef)
ModelPart * createOldSchematicPartAux (ModelPart *, const QString &oldModuleIDRef, const QString &oldSchematicFileName, const QString &oldSvgPath)
ModelPart * fixObsoleteModuleID (QDomDocument &domDocument, QDomElement &instance, QString &moduleIDRef)
bool loadInstances (QDomDocument &, QDomElement &root, QList< ModelPart * > &modelParts, bool checkViews)
void renewModelIndexes (QDomElement &root, const QString &childName, QHash< long, long > &oldToNew)
Static Protected Member Functions
static void checkMystery (QDomElement &instance)
static bool checkObsoleteOrientation (QDomElement &instance)
static bool checkOldSchematics (QDomElement &instance)
static void checkTraces (QDomElement &instance)
static bool isRatsnest (QDomElement &instance)
Protected Attributes
bool m_checkForReversedWires
QString m_fritzingVersion
QPointer< ModelBase > m_referenceModel
bool m_reportMissingModules
QPointer< ModelPart > m_root
bool m_useOldSchematics
Static Protected Attributes
static QList< QString > CoreList
Constructor & Destructor Documentation
ModelBase()
ModelBase::ModelBase (bool makeRoot)
References m_checkForReversedWires, m_referenceModel, m_reportMissingModules, m_root, and m_useOldSchematics.
~ModelBase()
ModelBase::~ModelBase () virtual
References m_root.
Member Function Documentation
addModelPart()
ModelPart * ModelBase::addModelPart (ModelPart * parent, ModelPart * copyChild) virtual
References ModelPart::copyNew(), ModelPart::flipSMDAnd(), and ModelPart::initConnectors().
addPart() [1/3]
ModelPart * ModelBase::addPart (QString newPartPath, bool addToReference) virtual
addPart() [2/3]
bool ModelBase::addPart (ModelPart * modelPart, bool update) virtual
Reimplemented in SqliteReferenceModel, and ReferenceModel.
addPart() [3/3]
ModelPart * ModelBase::addPart (QString newPartPath, bool addToReference, bool updateIdAlreadyExists) virtual
Reimplemented in PaletteModel, SqliteReferenceModel, and ReferenceModel.
checkForReversedWires()
bool ModelBase::checkForReversedWires ()
References m_checkForReversedWires.
checkMystery()
void ModelBase::checkMystery (QDomElement & instance) static protected
References TextUtils::getPinsAndSpacing().
checkObsoleteOrientation()
bool ModelBase::checkObsoleteOrientation (QDomElement & instance) static protected
checkOldSchematics()
bool ModelBase::checkOldSchematics (QDomElement & instance) static protected
References ViewGeometry::SchematicTraceFlag, and ModuleIDNames::WireModuleIDName.
checkTraces()
void ModelBase::checkTraces (QDomElement & instance) static protected
References DebugDialog::debug(), ViewGeometry::NormalFlag, ViewGeometry::PCBTraceFlag, ViewGeometry::SchematicTraceFlag, and ModuleIDNames::WireModuleIDName.
createOldSchematicPart()
ModelPart * ModelBase::createOldSchematicPart (ModelPart * modelPart, QString & moduleIDRef) protected
References createOldSchematicPartAux(), DebugDialog::debug(), FolderUtils::getAppPartsSubFolderPath(), PartFactory::getSvgFilename(), ModelPart::imageFileName(), m_referenceModel, PartFactory::OldSchematicPrefix, ViewLayer::Schematic, ViewLayer::SchematicFrame, and ViewLayer::SchematicView.
createOldSchematicPartAux()
ModelPart * ModelBase::createOldSchematicPartAux (ModelPart * modelPart, const QString & oldModuleIDRef, const QString & oldSchematicFileName, const QString & oldSvgPath) protected
References PartFactory::fzpPath(), ModelPart::isContrib(), ModelPart::isCore(), layers(), m_referenceModel, ModelPart::path(), root(), ModelPart::setContrib(), ModelPart::setCore(), and TextUtils::writeUtf8().
fixObsoleteModuleID()
ModelPart * ModelBase::fixObsoleteModuleID (QDomDocument & domDocument, QDomElement & instance, QString & moduleIDRef) protected
References PartFactory::fixObsoleteModuleID(), and m_referenceModel.
fritzingVersion()
const QString & ModelBase::fritzingVersion ()
References m_fritzingVersion.
genFZP()
ModelPart * ModelBase::genFZP (const QString & moduleID, ModelBase * referenceModel)
References addPart(), PartFactory::getFzpFilename(), and ModelPart::setCore().
isRatsnest()
bool ModelBase::isRatsnest (QDomElement & instance) static protected
References ViewGeometry::ObsoleteJumperFlag, ViewGeometry::RatsnestFlag, and ModuleIDNames::WireModuleIDName.
loadedInstances
void ModelBase::loadedInstances (ModelBase * , QDomElement & instances) signal
loadedRoot
void ModelBase::loadedRoot (const QString & fileName, ModelBase * , QDomElement & root) signal
loadedViews
void ModelBase::loadedViews (ModelBase * , QDomElement & views) signal
loadFromFile()
bool ModelBase::loadFromFile (const QString & fileName, ModelBase * referenceModel, QList< ModelPart * > & modelParts, bool checkInstances)
References checkMystery(), checkObsoleteOrientation(), checkOldSchematics(), checkTraces(), Version::greaterThan(), FMessageBox::information(), isRatsnest(), loadedInstances(), loadedRoot(), loadedViews(), loadingInstances(), loadInstances(), m_checkForReversedWires, m_fritzingVersion, m_referenceModel, m_root, m_useOldSchematics, VersionThing::majorVersion, VersionThing::minorSubVersion, VersionThing::minorVersion, obsoleteSMDOrientationSignal(), oldSchematicsSignal(), VersionThing::releaseModifier, root(), rootModelPartShared(), ModelPartSharedRoot::setIcon(), ModelPartSharedRoot::setSearchTerm(), ModelPartShared::setTitle(), Version::toVersionThing(), and FMessageBox::warning().
loadingInstance
void ModelBase::loadingInstance (ModelBase * , QDomElement & instance) signal
loadingInstances
void ModelBase::loadingInstances (ModelBase * , QDomElement & instances) signal
loadInstances()
bool ModelBase::loadInstances (QDomDocument & domDocument, QDomElement & root, QList< ModelPart * > & modelParts, bool checkViews) protected
References addModelPart(), createOldSchematicPart(), DebugDialog::debug(), fixObsoleteModuleID(), genFZP(), ModelPart::isCore(), loadingInstance(), m_referenceModel, m_reportMissingModules, m_root, m_useOldSchematics, ModelPart::modelPartShared(), ModelPart::moduleID(), ModelPart::setConnectorLocalName(), ModelPart::setInBin(), ModelPart::setInstanceDomElement(), ModelPart::setInstanceText(), ModelPart::setInstanceTitle(), ModelPart::setLocalProp(), ModelPart::setModelIndex(), ModelPartShared::setModuleID(), ModelPartShared::setPath(), ModelPart::Space, ModuleIDNames::SpacerModuleIDName, and FMessageBox::warning().
obsoleteSMDOrientationSignal
void ModelBase::obsoleteSMDOrientationSignal () signal
oldSchematicsSignal
void ModelBase::oldSchematicsSignal (const QString & filename, bool & useOldSchematics) signal
onCoreList()
bool ModelBase::onCoreList (const QString & moduleID) static
References CoreList.
paste()
bool ModelBase::paste (ModelBase * referenceModel, QByteArray & data, QList< ModelPart * > & modelParts, QHash< QString, QRectF > & boundingRects, bool preserveIndex)
References loadInstances(), m_referenceModel, ModelPart::nextIndex(), and renewModelIndexes().
renewModelIndexes()
void ModelBase::renewModelIndexes (QDomElement & root, const QString & childName, QHash< long, long > & oldToNew) protected
retrieveModelPart()
ModelPart * ModelBase::retrieveModelPart (const QString & moduleID) virtual
Reimplemented in SqliteReferenceModel, PaletteModel, and ReferenceModel.
root()
ModelPart * ModelBase::root ()
References m_root.
rootModelPartShared()
ModelPartSharedRoot * ModelBase::rootModelPartShared ()
References m_root.
save() [1/2]
void ModelBase::save (const QString & fileName, bool asPart)
References FMessageBox::warning().
save() [2/2]
void ModelBase::save (const QString & fileName, class QXmlStreamWriter & streamWriter, bool asPart)
References m_root.
setReferenceModel()
void ModelBase::setReferenceModel (ModelBase * modelBase)
References m_referenceModel.
setReportMissingModules()
void ModelBase::setReportMissingModules (bool b)
References m_reportMissingModules.
Member Data Documentation
CoreList
QList< QString > ModelBase::CoreList static protected
m_checkForReversedWires
bool ModelBase::m_checkForReversedWires protected
m_fritzingVersion
QString ModelBase::m_fritzingVersion protected
m_referenceModel
QPointer<ModelBase> ModelBase::m_referenceModel protected
m_reportMissingModules
bool ModelBase::m_reportMissingModules protected
m_root
QPointer<ModelPart> ModelBase::m_root protected
m_useOldSchematics
bool ModelBase::m_useOldSchematics protected
The documentation for this class was generated from the following files:
model/modelbase.h
model/modelbase.cpp