Fritzing: CornerHandler Class Reference
CornerHandler Class Reference
#include <cornerhandler.h>
Public Member Functions
CornerHandler (ConnectorRectangle *parent, QGraphicsItem *parentItem, Qt::Corner corner)
Qt::Corner corner ()
void doPaint (QPainter *painter)
void doSetRect (const QRectF &newRect)
void doSetVisible (bool visible)
bool isBeingDragged ()
void resize (const QPointF &mousePos)
Static Public Attributes
static QHash< Qt::Corner, QPixmap > pixmapHash
static double Size = 4
Protected Member Functions
Qt::CursorShape cursorForCorner (Qt::Corner)
void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
void initPixmapHash ()
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
void mousePressEvent (QGraphicsSceneMouseEvent *event)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
Protected Attributes
Qt::Corner m_corner
bool m_isVisible
ConnectorRectangle * m_parent
volatile bool m_resizing
Constructor & Destructor Documentation
CornerHandler()
CornerHandler::CornerHandler (ConnectorRectangle * parent, QGraphicsItem * parentItem, Qt::Corner corner)
References corner(), doSetVisible(), initPixmapHash(), m_corner, m_parent, and m_resizing.
Member Function Documentation
corner()
Qt::Corner CornerHandler::corner ()
References m_corner.
cursorForCorner()
Qt::CursorShape CornerHandler::cursorForCorner (Qt::Corner corner) protected
References corner().
doPaint()
void CornerHandler::doPaint (QPainter * painter)
References ConnectorRectangle::handlerRect(), m_corner, m_isVisible, m_parent, and pixmapHash.
doSetRect()
void CornerHandler::doSetRect (const QRectF & newRect)
doSetVisible()
void CornerHandler::doSetVisible (bool visible)
References m_isVisible.
hoverEnterEvent()
void CornerHandler::hoverEnterEvent (QGraphicsSceneHoverEvent * event) protected
References cursorForCorner(), ConnectorRectangle::isResizable(), m_corner, m_isVisible, and m_parent.
hoverLeaveEvent()
void CornerHandler::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) protected
References ConnectorRectangle::isResizable(), m_isVisible, and m_parent.
initPixmapHash()
void CornerHandler::initPixmapHash () protected
References pixmapHash.
isBeingDragged()
bool CornerHandler::isBeingDragged ()
References m_resizing.
mouseMoveEvent()
void CornerHandler::mouseMoveEvent (QGraphicsSceneMouseEvent * event) protected
References ConnectorRectangle::isResizable(), m_parent, m_resizing, and resize().
mousePressEvent()
void CornerHandler::mousePressEvent (QGraphicsSceneMouseEvent * event) protected
References ConnectorRectangle::isResizable(), m_isVisible, m_parent, m_resizing, and ConnectorRectangle::resizingStarted().
mouseReleaseEvent()
void CornerHandler::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected
References ConnectorRectangle::isResizable(), m_parent, m_resizing, and ConnectorRectangle::resizingFinished().
paint()
void CornerHandler::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) protected
References doPaint(), ConnectorRectangle::isResizable(), m_isVisible, and m_parent.
resize()
void CornerHandler::resize (const QPointF & mousePos)
References m_corner, m_parent, ConnectorRectangle::owner(), and ConnectorRectangle::resizeRect().
Member Data Documentation
m_corner
Qt::Corner CornerHandler::m_corner protected
m_isVisible
bool CornerHandler::m_isVisible protected
m_parent
ConnectorRectangle* CornerHandler::m_parent protected
m_resizing
volatile bool CornerHandler::m_resizing protected
pixmapHash
QHash< Qt::Corner, QPixmap > CornerHandler::pixmapHash static
Size
double CornerHandler::Size = 4 static
The documentation for this class was generated from the following files:
partseditor/obsolete/cornerhandler.h
partseditor/obsolete/cornerhandler.cpp