Fritzing: GraphicsUtils Class Reference
GraphicsUtils Class Reference
#include <graphicsutils.h>
Static Public Member Functions
static QPointF calcConstraint (QPointF initial, QPointF current)
static QPointF calcRotation (QTransform &rotation, QPointF rCenter, QPointF p, QPointF pCenter)
static void distanceFromLine (double cx, double cy, double ax, double ay, double bx, double by, double &dx, double &dy, double &distanceSegment, bool &atEndpoint)
static constexpr std::tuple< double, double, double, bool > distanceFromLine (double cx, double cy, double ax, double ay, double bx, double by) noexcept
static constexpr double distanceSqd (QPointF p1, QPointF p2) noexcept
static constexpr double distanceSqd (QPoint p1, QPoint p2) noexcept
static void drawBorder (QImage *image, int border)
static double getNearestOrdinate (double ordinate, double units)
static QRectF getRect (const QPolygonF &poly)
static bool isFlipped (const QMatrix &matrix, double &rotation)
static bool isRect (const QPolygonF &poly)
static bool liangBarskyLineClip (double x1, double y1, double x2, double y2, double wxmin, double wxmax, double wymin, double wymax, double &x11, double &y11, double &x22, double &y22)
static bool loadTransform (const QDomElement &transformElement, QTransform &transform)
static constexpr double mils2pixels (double m, double dpi) noexcept
static constexpr double mm2mils (double mm) noexcept
static constexpr double mm2pixels (double mm) noexcept
static constexpr double pixels2ins (double p, double dpi) noexcept
static constexpr double pixels2mils (double p, double dpi) noexcept
static constexpr double pixels2mm (double p, double dpi) noexcept
static void qt_graphicsItem_highlightSelected (QPainter *painter, const QStyleOptionGraphicsItem *option, const QRectF &boundingRect, const QPainterPath &path)
static void saveTransform (QXmlStreamWriter &streamWriter, const QTransform &transform)
static QPainterPath shapeFromPath (const QPainterPath &path, const QPen &pen, double shapeStrokeWidth, bool includeOriginalPath)
static void shortenLine (QPointF &p1, QPointF &p2, double d1, double d2)
static QString toHtmlImage (QPixmap *pixmap, const char *format="PNG")
Static Public Attributes
static constexpr double IllustratorDPI = 72
static constexpr double InchesPerMeter = 39.370078
static constexpr double StandardFritzingDPI = 1000
static constexpr double StandardSchematicSeparation10thinMils = 100
static constexpr double StandardSchematicSeparationMils = 295.275591
static constexpr double SVGDPI = 90
Member Function Documentation
calcConstraint()
QPointF GraphicsUtils::calcConstraint (QPointF initial, QPointF current) static
References distanceFromLine().
calcRotation()
QPointF GraphicsUtils::calcRotation (QTransform & rotation, QPointF rCenter, QPointF p, QPointF pCenter) static
distanceFromLine() [1/2]
void GraphicsUtils::distanceFromLine (double cx, double cy, double ax, double ay, double bx, double by, double & dx, double & dy, double & distanceSegment, bool & atEndpoint) static
distanceFromLine() [2/2]
static constexpr std::tuple<double, double, double, bool> GraphicsUtils::distanceFromLine (double cx, double cy, double ax, double ay, double bx, double by) inline static noexcept
distanceSqd() [1/2]
static constexpr double GraphicsUtils::distanceSqd (QPointF p1, QPointF p2) inline static noexcept
distanceSqd() [2/2]
static constexpr double GraphicsUtils::distanceSqd (QPoint p1, QPoint p2) inline static noexcept
drawBorder()
void GraphicsUtils::drawBorder (QImage * image, int border) static
getNearestOrdinate()
double GraphicsUtils::getNearestOrdinate (double ordinate, double units) static
getRect()
QRectF GraphicsUtils::getRect (const QPolygonF & poly) static
isFlipped()
bool GraphicsUtils::isFlipped (const QMatrix & matrix, double & rotation) static
References almostEqual().
isRect()
bool GraphicsUtils::isRect (const QPolygonF & poly) static
liangBarskyLineClip()
bool GraphicsUtils::liangBarskyLineClip (double x1, double y1, double x2, double y2, double wxmin, double wxmax, double wymin, double wymax, double & x11, double & y11, double & x22, double & y22) static
References qMax(), and qMin().
loadTransform()
bool GraphicsUtils::loadTransform (const QDomElement & transformElement, QTransform & transform) static
mils2pixels()
static constexpr double GraphicsUtils::mils2pixels (double m, double dpi) inline static noexcept
mm2mils()
static constexpr double GraphicsUtils::mm2mils (double mm) inline static noexcept
mm2pixels()
static constexpr double GraphicsUtils::mm2pixels (double mm) inline static noexcept
pixels2ins()
static constexpr double GraphicsUtils::pixels2ins (double p, double dpi) inline static noexcept
pixels2mils()
static constexpr double GraphicsUtils::pixels2mils (double p, double dpi) inline static noexcept
pixels2mm()
static constexpr double GraphicsUtils::pixels2mm (double p, double dpi) inline static noexcept
qt_graphicsItem_highlightSelected()
void GraphicsUtils::qt_graphicsItem_highlightSelected (QPainter * painter, const QStyleOptionGraphicsItem * option, const QRectF & boundingRect, const QPainterPath & path) static
References qMax(), and qMin().
saveTransform()
void GraphicsUtils::saveTransform (QXmlStreamWriter & streamWriter, const QTransform & transform) static
shapeFromPath()
QPainterPath GraphicsUtils::shapeFromPath (const QPainterPath & path, const QPen & pen, double shapeStrokeWidth, bool includeOriginalPath) static
shortenLine()
void GraphicsUtils::shortenLine (QPointF & p1, QPointF & p2, double d1, double d2) static
toHtmlImage()
QString GraphicsUtils::toHtmlImage (QPixmap * pixmap, const char * format = "PNG") static
Member Data Documentation
IllustratorDPI
constexpr double GraphicsUtils::IllustratorDPI = 72 static
InchesPerMeter
constexpr double GraphicsUtils::InchesPerMeter = 39.370078 static
StandardFritzingDPI
constexpr double GraphicsUtils::StandardFritzingDPI = 1000 static
StandardSchematicSeparation10thinMils
constexpr double GraphicsUtils::StandardSchematicSeparation10thinMils = 100 static
StandardSchematicSeparationMils
constexpr double GraphicsUtils::StandardSchematicSeparationMils = 295.275591 static
SVGDPI
constexpr double GraphicsUtils::SVGDPI = 90 static
The documentation for this class was generated from the following files:
utils/graphicsutils.h
utils/graphicsutils.cpp