Fritzing: MoveItemCommand Class Reference
MoveItemCommand Class Reference
#include <commands.h>
Public Member Functions
MoveItemCommand (SketchWidget *sketchWidget, long id, ViewGeometry &oldG, ViewGeometry &newG, bool updateRatsnest, QUndoCommand *parent)
void redo ()
void undo ()
Public Member Functions inherited from BaseCommand
BaseCommand (BaseCommand::CrossViewType, SketchWidget *, QUndoCommand *parent)
~BaseCommand ()
void addSubCommand (BaseCommand *subCommand)
BaseCommand::CrossViewType crossViewType () const noexcept
virtual QString getDebugString () const
int index () const
const QUndoCommand * parentCommand () const
void redo ()
void setCrossViewType (BaseCommand::CrossViewType)
void setRedoOnly ()
void setSkipFirstRedo ()
void setUndoOnly ()
SketchWidget * sketchWidget () const
const BaseCommand * subCommand (int index) const
int subCommandCount () const
void subRedo ()
void subRedo (int index)
void subUndo ()
void subUndo (int index)
void undo ()
Protected Member Functions
QString getParamString () const
Protected Attributes
long m_itemID = 0
ViewGeometry m_new
ViewGeometry m_old
bool m_updateRatsnest = false
Protected Attributes inherited from BaseCommand
QList< BaseCommand * > m_commands
BaseCommand::CrossViewType m_crossViewType
int m_index = 0
QUndoCommand * m_parentCommand = nullptr
bool m_redoOnly = false
SketchWidget * m_sketchWidget = nullptr
bool m_skipFirstRedo = false
bool m_undoOnly = false
Additional Inherited Members
Public Types inherited from BaseCommand
enum CrossViewType { SingleView, CrossView }
Static Public Member Functions inherited from BaseCommand
static void clearProgress ()
static CommandProgress * initProgress ()
static int totalChildCount (const QUndoCommand *)
Static Protected Attributes inherited from BaseCommand
static CommandProgress m_commandProgress
static int nextIndex = 0
Constructor & Destructor Documentation
MoveItemCommand()
MoveItemCommand::MoveItemCommand (SketchWidget * sketchWidget, long id, ViewGeometry & oldG, ViewGeometry & newG, bool updateRatsnest, QUndoCommand * parent)
Member Function Documentation
getParamString()
QString MoveItemCommand::getParamString () const protected virtual
Reimplemented from BaseCommand.
References BaseCommand::getParamString(), ViewGeometry::line(), ViewGeometry::loc(), m_itemID, m_new, and m_old.
redo()
void MoveItemCommand::redo ()
References m_itemID, m_new, BaseCommand::m_sketchWidget, m_updateRatsnest, SketchWidget::moveItem(), and BaseCommand::redo().
undo()
void MoveItemCommand::undo ()
References m_itemID, m_old, BaseCommand::m_sketchWidget, m_updateRatsnest, SketchWidget::moveItem(), and BaseCommand::undo().
Member Data Documentation
m_itemID
long MoveItemCommand::m_itemID = 0 protected
m_new
ViewGeometry MoveItemCommand::m_new protected
m_old
ViewGeometry MoveItemCommand::m_old protected
m_updateRatsnest
bool MoveItemCommand::m_updateRatsnest = false protected
The documentation for this class was generated from the following files:
commands.h
commands.cpp