Fritzing: PartFactory Class Reference
PartFactory Class Reference
#include <partfactory.h>
Static Public Member Functions
static void cleanup ()
static class ItemBase * createPart (class ModelPart *, ViewLayer::ViewLayerPlacement, ViewLayer::ViewID, const class ViewGeometry &viewGeometry, long id, QMenu *itemMenu, QMenu *wireMenu, bool doLabel)
static class ModelPart * fixObsoleteModuleID (QDomDocument &domDocument, QDomElement &instance, QString &moduleIDRef, class ModelBase *referenceModel)
static QString folderPath ()
static bool fzpFileExists (const QString &moduleID, QString &path)
static QString fzpPath ()
static QString getFzpFilename (const QString &moduleID)
static QString getSvgFilename (class ModelPart *, const QString &filename, bool generate, bool handleSubparts)
static QString getSvgFilename (const QString &filename)
static void initFolder ()
static QString makeSchematicSipOrDipOr (const QStringList &labels, bool hasLayout, bool sip)
static QString partPath ()
static bool svgFileExists (const QString &expectedFileName, QString &path)
Static Public Attributes
static const QString OldSchematicPrefix
Static Protected Member Functions
static class ItemBase * createPartAux (class ModelPart *, ViewLayer::ViewID, const class ViewGeometry &viewGeometry, long id, QMenu *itemMenu, QMenu *wireMenu, bool doLabel)
static void fixSubpartBounds (QDomElement &, ModelPartShared *)
static QString getFzpFilenameAux (const QString &moduleID, GenFzp)
static QString getSvgFilenameAux (const QString &expectedFileName, GenSvg)
static QDomElement showSubpart (QDomElement &root, const QString &subpart)
Member Function Documentation
cleanup()
void PartFactory::cleanup () static
References LockedFiles, PartFactoryFolderPath, and LockManager::releaseLockedFiles().
createPart()
ItemBase * PartFactory::createPart (class ModelPart * , ViewLayer::ViewLayerPlacement , ViewLayer::ViewID , const class ViewGeometry & viewGeometry, long id, QMenu * itemMenu, QMenu * wireMenu, bool doLabel) static
References createPartAux(), ModelPart::setModelIndexFromMultiplied(), and ItemBase::setViewLayerPlacement().
createPartAux()
ItemBase * PartFactory::createPartAux (class ModelPart * , ViewLayer::ViewID , const class ViewGeometry & viewGeometry, long id, QMenu * itemMenu, QMenu * wireMenu, bool doLabel) static protected
References ModelPart::Board, ModelPart::Breadboard, ModuleIDNames::CapacitorModuleIDName, ModuleIDNames::ColorFluxLEDModuleIDName, ModuleIDNames::ColorLEDModuleIDName, ModuleIDNames::CopperBlockerModuleIDName, ModelPart::CopperFill, ModuleIDNames::CrystalModuleIDName, ViewGeometry::getAnyTrace(), ViewGeometry::getRatsnest(), ModelPart::Hole, ModuleIDNames::InductorModuleIDName, ModelPart::itemType(), ModelPart::Jumper, ModuleIDNames::LEDModuleIDName, ModelPart::Logo, ModelPart::moduleID(), ModuleIDNames::ModuleIDNameSuffix, ModuleIDNames::NetLabelModuleIDName, ModelPart::Note, ModuleIDNames::PadModuleIDName, ModuleIDNames::PerfboardModuleIDName, ModuleIDNames::PotentiometerModuleIDName, ModelPart::properties(), ModuleIDNames::ResistorModuleIDName, ModelPart::ResizableBoard, ModelPart::Ruler, ModuleIDNames::SchematicFrameModuleIDName, ModelPart::SchematicSubpart, ModuleIDNames::Stripboard2ModuleIDName, ModuleIDNames::StripboardModuleIDName, ModelPart::Symbol, ModuleIDNames::ThermistorModuleIDName, ModuleIDNames::TwoPowerModuleIDName, ModelPart::Via, ModelPart::Wire, and ModuleIDNames::ZenerDiodeModuleIDName.
fixObsoleteModuleID()
ModelPart * PartFactory::fixObsoleteModuleID (QDomDocument & domDocument, QDomElement & instance, QString & moduleIDRef, class ModelBase * referenceModel) static
References PinHeader::FemaleRoundedFormString, PinHeader::MaleFormString, and ModelBase::retrieveModelPart().
fixSubpartBounds()
void PartFactory::fixSubpartBounds (QDomElement & top, ModelPartShared * mps) static protected
References TextUtils::ensureViewBox(), TextUtils::getSvgSizes(), SvgText::renderText(), ModelPartShared::setSubpartOffset(), ModelPartShared::subpartID(), and GraphicsUtils::SVGDPI.
folderPath()
QString PartFactory::folderPath () static
References PartFactoryFolderPath.
fzpFileExists()
bool PartFactory::fzpFileExists (const QString & moduleID, QString & path) static
References FritzingPartExtension(), fzpPath(), and FolderUtils::getAppPartsSubFolderPath().
fzpPath()
QString PartFactory::fzpPath () static
References PartFactoryFolderPath.
getFzpFilename()
QString PartFactory::getFzpFilename (const QString & moduleID) static
References fzpPath(), Dip::genDipFZP(), MysteryPart::genDipFZP(), ScrewTerminal::genFZP(), Perfboard::genFZP(), PinHeader::genFZP(), Stripboard::genFZP(), Dip::genSipFZP(), MysteryPart::genSipFZP(), getFzpFilenameAux(), ModuleIDNames::PerfboardModuleIDName, ModuleIDNames::Stripboard2ModuleIDName, and ModuleIDNames::StripboardModuleIDName.
getFzpFilenameAux()
QString PartFactory::getFzpFilenameAux (const QString & moduleID, GenFzp) static protected
References fzpFileExists(), and TextUtils::writeUtf8().
getSvgFilename() [1/2]
QString PartFactory::getSvgFilename (class ModelPart * modelPart, const QString & filename, bool generate, bool handleSubparts) static
References DebugDialog::debug(), fixSubpartBounds(), folderPath(), FolderUtils::getAppPartsSubFolderPath(), FolderUtils::getUserPartsPath(), ModelPartShared::hasSubparts(), ModelPartShared::imageFileName(), ModelPart::modelPartShared(), ModelPart::moduleID(), partPath(), ModelPart::path(), ModelPart::possibleFolders(), ViewLayer::SchematicView, ModelPartShared::setSubpartOffset(), showSubpart(), ModelPartShared::subpartID(), ModelPartShared::subpartOffset(), SubpartOffsets, ModelPartShared::subparts(), SvgFilesDir, ModelPart::title(), and TextUtils::writeUtf8().
getSvgFilename() [2/2]
QString PartFactory::getSvgFilename (const QString & filename) static
References getSvgFilenameAux(), ScrewTerminal::makeBreadboardSvg(), Dip::makeBreadboardSvg(), Perfboard::makeBreadboardSvg(), MysteryPart::makeBreadboardSvg(), PinHeader::makeBreadboardSvg(), MysteryPart::makePcbDipSvg(), ScrewTerminal::makePcbSvg(), PinHeader::makePcbSvg(), Dip::makeSchematicSvg(), ScrewTerminal::makeSchematicSvg(), MysteryPart::makeSchematicSvg(), PinHeader::makeSchematicSvg(), and OldSchematicPrefix.
getSvgFilenameAux()
QString PartFactory::getSvgFilenameAux (const QString & expectedFileName, GenSvg genSvg) static protected
References svgFileExists(), and TextUtils::writeUtf8().
initFolder()
void PartFactory::initFolder () static
References LockManager::checkLockedFiles(), LockManager::initLockedFiles(), LockedFiles, FolderUtils::makePartFolderHierarchy(), PartFactoryFolderPath, and LockManager::SlowTime.
makeSchematicSipOrDipOr()
QString PartFactory::makeSchematicSipOrDipOr (const QStringList & labels, bool hasLayout, bool sip) static
References Dip::makeSchematicSvg(), and MysteryPart::makeSchematicSvg().
partPath()
QString PartFactory::partPath () static
References PartFactoryFolderPath.
showSubpart()
QDomElement PartFactory::showSubpart (QDomElement & root, const QString & subpart) static protected
References ___emptyElement___.
svgFileExists()
bool PartFactory::svgFileExists (const QString & expectedFileName, QString & path) static
References FolderUtils::getAppPartsSubFolderPath(), partPath(), and SvgFilesDir.
Member Data Documentation
OldSchematicPrefix
const QString PartFactory::OldSchematicPrefix static
The documentation for this class was generated from the following files:
items/partfactory.h
items/partfactory.cpp