Fritzing: HashPopulateWidget Class Reference
HashPopulateWidget Class Reference
#include <hashpopulatewidget.h>
Signals
void changed ()
void editionStarted ()
Public Member Functions
HashPopulateWidget (const QString &title, const QHash< QString, QString > &initValues, const QStringList &readOnlyKeys, bool keysOnly, QWidget *parent)
const QHash< QString, QString > & hash ()
HashLineEdit * lineEditAt (int row, int col)
Protected Slots
void lastRowEditionCompleted ()
void lineEditChanged ()
void removeRow (HashRemoveButton *)
Protected Member Functions
void addRow (QGridLayout *layout=0)
HashRemoveButton * createRemoveButton (HashLineEdit *label, HashLineEdit *value)
QGridLayout * gridLayout ()
Protected Attributes
bool m_keysOnly
HashLineEdit * m_lastLabel
HashLineEdit * m_lastValue
Constructor & Destructor Documentation
HashPopulateWidget()
HashPopulateWidget::HashPopulateWidget (const QString & title, const QHash< QString, QString > & initValues, const QStringList & readOnlyKeys, bool keysOnly, QWidget * parent)
References addRow(), createRemoveButton(), m_keysOnly, m_lastLabel, and m_lastValue.
Member Function Documentation
addRow()
void HashPopulateWidget::addRow (QGridLayout * layout = 0) protected
References editionStarted(), gridLayout(), lastRowEditionCompleted(), m_keysOnly, m_lastLabel, and m_lastValue.
changed
void HashPopulateWidget::changed () signal
createRemoveButton()
HashRemoveButton * HashPopulateWidget::createRemoveButton (HashLineEdit * label, HashLineEdit * value) protected
References removeRow().
editionStarted
void HashPopulateWidget::editionStarted () signal
gridLayout()
QGridLayout * HashPopulateWidget::gridLayout () protected
hash()
const QHash< QString, QString > & HashPopulateWidget::hash ()
References gridLayout(), lineEditAt(), and HashLineEdit::textIfSetted().
lastRowEditionCompleted
void HashPopulateWidget::lastRowEditionCompleted () protected slot
References addRow(), createRemoveButton(), gridLayout(), HashLineEdit::hasChanged(), lineEditAt(), m_lastLabel, and m_lastValue.
lineEditAt()
HashLineEdit * HashPopulateWidget::lineEditAt (int row, int col)
References gridLayout().
lineEditChanged
void HashPopulateWidget::lineEditChanged () protected slot
References changed().
removeRow
void HashPopulateWidget::removeRow (HashRemoveButton * button) protected slot
References changed(), HashRemoveButton::label(), and HashRemoveButton::value().
Member Data Documentation
m_keysOnly
bool HashPopulateWidget::m_keysOnly protected
m_lastLabel
HashLineEdit* HashPopulateWidget::m_lastLabel protected
m_lastValue
HashLineEdit* HashPopulateWidget::m_lastValue protected
The documentation for this class was generated from the following files:
partseditor/hashpopulatewidget.h
partseditor/hashpopulatewidget.cpp