Fritzing: ProgramTab Class Reference
ProgramTab Class Reference
#include <programtab.h>
Public Slots
void copy ()
void cut ()
void deleteTab ()
void enableCopy (bool enable)
void enableCut (bool enable)
void enablePaste (bool enable)
void enableRedo (bool enable)
void enableUndo (bool enable)
bool loadProgramFile ()
void paste ()
void programProcessFinished (int exitCode, QProcess::ExitStatus exitStatus)
void programProcessReadyRead ()
void redo ()
void rename ()
void save ()
void saveAs ()
void selectAll ()
void sendProgram ()
void serialMonitor ()
void setBoard (const QString &)
void setPlatform (const QString &newPlatformName)
void setPlatform (Platform *newPlatform)
void setPort (const QString &)
void textChanged ()
void undo ()
void updateBoards ()
void updateMenu ()
void updateSerialPorts ()
Signals
void platformChanged (Platform *newPlatform)
void programWindowUpdateRequest (bool programEnable, bool undoEnable, bool redoEnable, bool cutEnable, bool copyEnable, bool pasteEnable, Platform *platform, const QString &port, const QString &board, const QString &filename)
void wantToDelete (int, bool deleteFile)
void wantToRename (int)
void wantToSave (int)
void wantToSaveAs (int)
Public Member Functions
ProgramTab (QString &filename, QWidget *parent)
~ProgramTab ()
void appendToConsole (const QString &)
const QStringList & extensions ()
const QString & extensionString ()
const QString & filename ()
void initMenus ()
bool isModified ()
bool loadProgramFile (const QString &filename, const QString &altFilename, bool noUpdate)
Platform * platform ()
void print (QPrinter &printer)
bool readOnly ()
bool save (const QString &filename)
void setClean ()
void setDirty ()
void setFilename (const QString &)
void setPlatform (const QString &newPlatformName, bool updateLink)
void setPlatform (Platform *newPlatform, bool updateLink)
void setText (QString text)
void showEvent (QShowEvent *event)
QString text ()
Protected Slots
void enableMonitorButton ()
void enableProgramButton ()
Protected Member Functions
QFrame * createFooter ()
Protected Attributes
QString m_board
QPointer< QComboBox > m_boardComboBox
QPointer< QPushButton > m_cancelCloseButton
bool m_canCopy
bool m_canCut
bool m_canPaste
bool m_canRedo
bool m_canUndo
QPointer< QPlainTextEdit > m_console
QString m_filename
QPointer< class Highlighter > m_highlighter
QHBoxLayout * m_leftButtonsContainer
QHBoxLayout * m_middleButtonsContainer
QPointer< SketchToolButton > m_monitorButton
QPointer< ConsoleWindow > m_monitorWindow
QPointer< SketchToolButton > m_newButton
QPointer< SketchToolButton > m_openButton
QPointer< Platform > m_platform
QPointer< QComboBox > m_platformComboBox
QString m_port
QPointer< SerialPortComboBox > m_portComboBox
QPointer< SketchToolButton > m_programButton
QPointer< ProgramWindow > m_programWindow
QHBoxLayout * m_rightButtonsContainer
QPointer< SketchToolButton > m_saveButton
QPointer< QTabWidget > m_tabWidget
QPointer< QTextEdit > m_textEdit
QPointer< QFrame > m_toolbar
QPointer< QLabel > m_unableToProgramLabel
bool m_updateEnabled
Private Member Functions
void initWithSettings ()
Constructor & Destructor Documentation
ProgramTab()
ProgramTab::ProgramTab (QString & filename, QWidget * parent)
References AsteriskIcon, enableCopy(), enableCut(), enableRedo(), enableUndo(), filename(), m_board, m_canCopy, m_canCut, m_canPaste, m_canRedo, m_canUndo, m_console, m_filename, m_highlighter, m_leftButtonsContainer, m_middleButtonsContainer, m_port, m_programWindow, m_rightButtonsContainer, m_tabWidget, m_textEdit, m_toolbar, m_updateEnabled, textChanged(), and UnableToProgramMessage.
~ProgramTab()
ProgramTab::~ProgramTab ()
Member Function Documentation
appendToConsole()
void ProgramTab::appendToConsole (const QString & text)
References m_console, and text().
copy
void ProgramTab::copy () slot
References m_textEdit.
createFooter()
QFrame* ProgramTab::createFooter () protected
cut
void ProgramTab::cut () slot
References m_textEdit.
deleteTab
void ProgramTab::deleteTab () slot
References DeleteDialog::deleteFileChecked(), FolderUtils::isEmptyFileName(), m_filename, m_tabWidget, m_textEdit, and wantToDelete().
enableCopy
void ProgramTab::enableCopy (bool enable) slot
References m_canCopy, and updateMenu().
enableCut
void ProgramTab::enableCut (bool enable) slot
References m_canCut, and updateMenu().
enableMonitorButton
void ProgramTab::enableMonitorButton () protected slot
References m_monitorButton, and m_portComboBox.
enablePaste
void ProgramTab::enablePaste (bool enable) slot
References m_canPaste, and updateMenu().
enableProgramButton
void ProgramTab::enableProgramButton () protected slot
References m_programButton.
enableRedo
void ProgramTab::enableRedo (bool enable) slot
References m_canRedo, and updateMenu().
enableUndo
void ProgramTab::enableUndo (bool enable) slot
References m_canUndo, m_saveButton, and updateMenu().
extensions()
const QStringList & ProgramTab::extensions ()
References ___emptyStringList___, Syntaxer::extensions(), and m_highlighter.
extensionString()
const QString & ProgramTab::extensionString ()
References ___emptyString___, Syntaxer::extensionString(), and m_highlighter.
filename()
const QString & ProgramTab::filename ()
References m_filename.
initMenus()
void ProgramTab::initMenus ()
References Platform::getName(), initWithSettings(), m_boardComboBox, m_leftButtonsContainer, m_middleButtonsContainer, m_monitorButton, m_newButton, m_openButton, m_platformComboBox, m_portComboBox, m_programButton, m_programWindow, m_rightButtonsContainer, m_saveButton, platform(), platformChanged(), setBoard(), setPlatform(), setPort(), updateBoards(), and updateSerialPorts().
initWithSettings()
void ProgramTab::initWithSettings () private
References m_boardComboBox, m_platformComboBox, m_portComboBox, setBoard(), setPlatform(), and setPort().
isModified()
bool ProgramTab::isModified ()
References m_textEdit.
loadProgramFile() [1/2]
bool ProgramTab::loadProgramFile (const QString & filename, const QString & altFilename, bool noUpdate)
References DebugDialog::debug(), FolderUtils::getOpenFileName(), m_filename, m_platform, m_programWindow, m_tabWidget, m_textEdit, FolderUtils::openSaveFolder(), Quote91Char(), setClean(), and text().
loadProgramFile [2/2]
bool ProgramTab::loadProgramFile () slot
References FolderUtils::getOpenFileName(), isModified(), m_highlighter, m_programWindow, m_textEdit, and FolderUtils::openSaveFolder().
paste
void ProgramTab::paste () slot
References m_textEdit.
platform()
Platform * ProgramTab::platform ()
References m_platform.
platformChanged
void ProgramTab::platformChanged (Platform * newPlatform) signal
print()
void ProgramTab::print (QPrinter & printer)
References m_textEdit.
programProcessFinished
void ProgramTab::programProcessFinished (int exitCode, QProcess::ExitStatus exitStatus) slot
References DebugDialog::debug(), m_console, and m_programButton.
programProcessReadyRead
void ProgramTab::programProcessReadyRead () slot
References m_console.
programWindowUpdateRequest
void ProgramTab::programWindowUpdateRequest (bool programEnable, bool undoEnable, bool redoEnable, bool cutEnable, bool copyEnable, bool pasteEnable, Platform * platform, const QString & port, const QString & board, const QString & filename) signal
readOnly()
bool ProgramTab::readOnly ()
redo
void ProgramTab::redo () slot
References m_textEdit.
rename
void ProgramTab::rename () slot
References m_tabWidget, and wantToRename().
save() [1/2]
bool ProgramTab::save (const QString & filename)
References m_textEdit, and setFilename().
save [2/2]
void ProgramTab::save () slot
References m_tabWidget, and wantToSave().
saveAs
void ProgramTab::saveAs () slot
References m_tabWidget, and wantToSaveAs().
selectAll
void ProgramTab::selectAll () slot
References m_textEdit.
sendProgram
void ProgramTab::sendProgram () slot
References isModified(), m_boardComboBox, m_console, m_filename, m_monitorWindow, m_platform, m_portComboBox, m_programButton, and save().
serialMonitor
void ProgramTab::serialMonitor () slot
References m_monitorWindow, and m_port.
setBoard
void ProgramTab::setBoard (const QString & newBoard) slot
References DebugDialog::debug(), m_board, m_boardComboBox, and updateMenu().
setClean()
void ProgramTab::setClean ()
References m_textEdit, and textChanged().
setDirty()
void ProgramTab::setDirty ()
References m_textEdit, and textChanged().
setFilename()
void ProgramTab::setFilename (const QString & name)
References DebugDialog::debug(), m_filename, m_tabWidget, and updateMenu().
setPlatform() [1/4]
void ProgramTab::setPlatform (const QString & newPlatformName, bool updateLink)
References m_programWindow.
setPlatform() [2/4]
void ProgramTab::setPlatform (Platform * newPlatform, bool updateLink)
References DebugDialog::debug(), enableProgramButton(), Platform::getName(), m_filename, m_highlighter, m_platform, m_platformComboBox, m_programWindow, platformChanged(), and updateMenu().
setPlatform [3/4]
void ProgramTab::setPlatform (const QString & newPlatformName) slot
References m_programWindow, and setPlatform().
setPlatform [4/4]
void ProgramTab::setPlatform (Platform * newPlatform) slot
References setPlatform().
setPort
void ProgramTab::setPort (const QString & newPort) slot
References DebugDialog::debug(), m_port, m_portComboBox, and updateMenu().
setText()
void ProgramTab::setText (QString text)
References m_textEdit, and text().
showEvent()
void ProgramTab::showEvent (QShowEvent * event)
We override the showEvent for the tab to trigger a menu update
References m_textEdit, and updateMenu().
text()
QString ProgramTab::text ()
References m_textEdit.
textChanged
void ProgramTab::textChanged () slot
References AsteriskIcon, isModified(), m_saveButton, m_tabWidget, and updateMenu().
undo
void ProgramTab::undo () slot
References m_textEdit.
updateBoards
void ProgramTab::updateBoards () slot
References m_boardComboBox, m_platform, m_programWindow, and setBoard().
updateMenu
void ProgramTab::updateMenu () slot
This function emits all the required signals to update the menu of its owning ProgramWindow. It is currently called on the QTabWidget's currentChanged() signal.
References enableProgramButton(), m_board, m_canCopy, m_canCut, m_canPaste, m_canRedo, m_canUndo, m_filename, m_platform, m_port, m_programButton, and programWindowUpdateRequest().
updateSerialPorts
void ProgramTab::updateSerialPorts () slot
References enableMonitorButton(), enableProgramButton(), m_portComboBox, and m_programWindow.
wantToDelete
void ProgramTab::wantToDelete (int , bool deleteFile) signal
wantToRename
void ProgramTab::wantToRename (int) signal
wantToSave
void ProgramTab::wantToSave (int) signal
wantToSaveAs
void ProgramTab::wantToSaveAs (int) signal
Member Data Documentation
m_board
QString ProgramTab::m_board protected
m_boardComboBox
QPointer<QComboBox> ProgramTab::m_boardComboBox protected
m_cancelCloseButton
QPointer<QPushButton> ProgramTab::m_cancelCloseButton protected
m_canCopy
bool ProgramTab::m_canCopy protected
m_canCut
bool ProgramTab::m_canCut protected
m_canPaste
bool ProgramTab::m_canPaste protected
m_canRedo
bool ProgramTab::m_canRedo protected
m_canUndo
bool ProgramTab::m_canUndo protected
m_console
QPointer<QPlainTextEdit> ProgramTab::m_console protected
m_filename
QString ProgramTab::m_filename protected
m_highlighter
QPointer<class Highlighter> ProgramTab::m_highlighter protected
m_leftButtonsContainer
QHBoxLayout* ProgramTab::m_leftButtonsContainer protected
m_middleButtonsContainer
QHBoxLayout* ProgramTab::m_middleButtonsContainer protected
m_monitorButton
QPointer<SketchToolButton> ProgramTab::m_monitorButton protected
m_monitorWindow
QPointer<ConsoleWindow> ProgramTab::m_monitorWindow protected
m_newButton
QPointer<SketchToolButton> ProgramTab::m_newButton protected
m_openButton
QPointer<SketchToolButton> ProgramTab::m_openButton protected
m_platform
QPointer<Platform> ProgramTab::m_platform protected
m_platformComboBox
QPointer<QComboBox> ProgramTab::m_platformComboBox protected
m_port
QString ProgramTab::m_port protected
m_portComboBox
QPointer<SerialPortComboBox> ProgramTab::m_portComboBox protected
m_programButton
QPointer<SketchToolButton> ProgramTab::m_programButton protected
m_programWindow
QPointer<ProgramWindow> ProgramTab::m_programWindow protected
m_rightButtonsContainer
QHBoxLayout* ProgramTab::m_rightButtonsContainer protected
m_saveButton
QPointer<SketchToolButton> ProgramTab::m_saveButton protected
m_tabWidget
QPointer<QTabWidget> ProgramTab::m_tabWidget protected
m_textEdit
QPointer<QTextEdit> ProgramTab::m_textEdit protected
m_toolbar
QPointer<QFrame> ProgramTab::m_toolbar protected
m_unableToProgramLabel
QPointer<QLabel> ProgramTab::m_unableToProgramLabel protected
m_updateEnabled
bool ProgramTab::m_updateEnabled protected
The documentation for this class was generated from the following files:
program/programtab.h
program/programtab.cpp