Fritzing: PEMetadataView Class Reference
PEMetadataView Class Reference
#include <pemetadataview.h>
Signals
void metadataChanged (const QString &name, const QString &value)
void propertiesChanged (const QHash< QString, QString > &)
void tagsChanged (const QStringList &)
Public Member Functions
PEMetadataView (QWidget *parent=0)
~PEMetadataView ()
QString family ()
void initMetadata (const QDomDocument &)
const QHash< QString, QString > & properties ()
void resetProperty (const QString &name, const QString &value)
QString variant ()
Protected Slots
void authorEntry ()
void dateEntry ()
void descriptionEntry ()
void familyEntry ()
void labelEntry ()
void propertiesEntry ()
void tagsEntry ()
void titleEntry ()
void urlEntry ()
void variantEntry ()
Protected Attributes
QPointer< QLineEdit > m_authorEdit
QPointer< QLineEdit > m_dateEdit
QPointer< QTextEdit > m_descriptionEdit
QPointer< QLineEdit > m_familyEdit
QPointer< QLineEdit > m_labelEdit
QPointer< QFrame > m_mainFrame
QPointer< class HashPopulateWidget > m_propertiesEdit
QPointer< class HashPopulateWidget > m_tagsEdit
QPointer< QLineEdit > m_titleEdit
QPointer< QLineEdit > m_urlEdit
QPointer< QLineEdit > m_variantEdit
Constructor & Destructor Documentation
PEMetadataView()
PEMetadataView::PEMetadataView (QWidget * parent = 0)
References m_mainFrame.
~PEMetadataView()
PEMetadataView::~PEMetadataView ()
Member Function Documentation
authorEntry
void PEMetadataView::authorEntry () protected slot
References m_authorEdit, and metadataChanged().
dateEntry
void PEMetadataView::dateEntry () protected slot
descriptionEntry
void PEMetadataView::descriptionEntry () protected slot
References m_descriptionEdit, and metadataChanged().
family()
QString PEMetadataView::family ()
References m_familyEdit.
familyEntry
void PEMetadataView::familyEntry () protected slot
References m_familyEdit, and metadataChanged().
initMetadata()
void PEMetadataView::initMetadata (const QDomDocument & doc)
References authorEntry(), dateEntry(), descriptionEntry(), family(), familyEntry(), labelEntry(), m_authorEdit, m_dateEdit, m_descriptionEdit, m_familyEdit, m_labelEdit, m_mainFrame, m_propertiesEdit, m_tagsEdit, m_titleEdit, m_urlEdit, m_variantEdit, properties(), propertiesEntry(), tagsEntry(), titleEntry(), urlEntry(), variant(), and variantEntry().
labelEntry
void PEMetadataView::labelEntry () protected slot
References m_labelEdit, and metadataChanged().
metadataChanged
void PEMetadataView::metadataChanged (const QString & name, const QString & value) signal
properties()
const QHash< QString, QString > & PEMetadataView::properties ()
References m_propertiesEdit.
propertiesChanged
void PEMetadataView::propertiesChanged (const QHash< QString, QString > &) signal
propertiesEntry
void PEMetadataView::propertiesEntry () protected slot
References m_propertiesEdit, and propertiesChanged().
resetProperty()
void PEMetadataView::resetProperty (const QString & name, const QString & value)
References m_familyEdit, and m_variantEdit.
tagsChanged
void PEMetadataView::tagsChanged (const QStringList &) signal
tagsEntry
void PEMetadataView::tagsEntry () protected slot
References m_tagsEdit, and tagsChanged().
titleEntry
void PEMetadataView::titleEntry () protected slot
References m_titleEdit, and metadataChanged().
urlEntry
void PEMetadataView::urlEntry () protected slot
References m_urlEdit, and metadataChanged().
variant()
QString PEMetadataView::variant ()
References m_variantEdit.
variantEntry
void PEMetadataView::variantEntry () protected slot
References m_variantEdit, and metadataChanged().
Member Data Documentation
m_authorEdit
QPointer<QLineEdit> PEMetadataView::m_authorEdit protected
m_dateEdit
QPointer<QLineEdit> PEMetadataView::m_dateEdit protected
m_descriptionEdit
QPointer<QTextEdit> PEMetadataView::m_descriptionEdit protected
m_familyEdit
QPointer<QLineEdit> PEMetadataView::m_familyEdit protected
m_labelEdit
QPointer<QLineEdit> PEMetadataView::m_labelEdit protected
m_mainFrame
QPointer<QFrame> PEMetadataView::m_mainFrame protected
m_propertiesEdit
QPointer<class HashPopulateWidget> PEMetadataView::m_propertiesEdit protected
m_tagsEdit
QPointer<class HashPopulateWidget> PEMetadataView::m_tagsEdit protected
m_titleEdit
QPointer<QLineEdit> PEMetadataView::m_titleEdit protected
m_urlEdit
QPointer<QLineEdit> PEMetadataView::m_urlEdit protected
m_variantEdit
QPointer<QLineEdit> PEMetadataView::m_variantEdit protected
The documentation for this class was generated from the following files:
partseditor/pemetadataview.h
partseditor/pemetadataview.cpp