Fritzing: PartLabel Class Reference
PartLabel Class Reference
#include <partlabel.h>
Public Member Functions
PartLabel (ItemBase *owner, QGraphicsItem *parent=0)
~PartLabel ()
void displayTexts ()
void displayTextsIf ()
constexpr bool hidden () const noexcept
constexpr bool inactive () const noexcept
constexpr bool initialized () const noexcept
QVariant itemChange (QGraphicsItem::GraphicsItemChange change, const QVariant &value)
QString makeSvg (bool blackOnly, double dpi, double printerScale, bool includeTransform)
void moveLabel (QPointF newPos, QPointF newOffset)
ItemBase * owner ()
void ownerMoved (QPointF newPos)
void ownerSelected (bool selected)
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
void restoreLabel (QDomElement &labelGeometry, ViewLayer::ViewLayerID)
void rotateFlipLabel (double degrees, Qt::Orientations orientation)
void saveInstance (QXmlStreamWriter &streamWriter)
void setFontPointSize (double pointSize)
void setHidden (bool hide)
void setInactive (bool inactivate)
void setPlainText (const QString &text)
QPainterPath shape () const
void showLabel (bool showIt, ViewLayer *)
constexpr ViewLayer::ViewLayerID viewLayerID () const noexcept
Protected Member Functions
void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
void initMenu ()
QString makeSvgAux (bool blackOnly, double dpi, double printerScale, double &w, double &h)
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event)
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
void mousePressEvent (QGraphicsSceneMouseEvent *event)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
void partLabelEdit ()
void partLabelHide ()
void resetSvg ()
void rotateFlip (int action)
void setFontSize (int action)
void setHiddenOrInactive ()
void setLabelDisplay (const QString &key)
void setUpText ()
void transformLabel (QTransform currTransf)
Protected Attributes
QColor m_color
QList< QAction * > m_displayActs
QStringList m_displayKeys
QString m_displayText
bool m_doDrag = false
QFont m_font
bool m_hidden = false
bool m_inactive = false
bool m_initialized = false
QPointF m_initialOffset
QPointF m_initialPosition
QAction * m_labelAct = nullptr
QAction * m_largeAct = nullptr
QAction * m_mediumAct = nullptr
QMenu m_menu
QPointF m_offset
QPointer< ItemBase > m_owner
QSvgRenderer * m_renderer = nullptr
QAction * m_smallAct = nullptr
bool m_spaceBarWasPressed = false
QString m_text
QAction * m_tinyAct = nullptr
ViewLayer::ViewLayerID m_viewLayerID = ViewLayer::UnknownLayer
Constructor & Destructor Documentation
PartLabel()
PartLabel::PartLabel (ItemBase * owner, QGraphicsItem * parent = 0)
References AllPartLabels, LabelTextKey, m_displayKeys, m_owner, ModelPartShared::PartNumberPropertyName, and ViewLayer::PCBView.
~PartLabel()
PartLabel::~PartLabel ()
References AllPartLabels, and m_owner.
Member Function Documentation
contextMenuEvent()
void PartLabel::contextMenuEvent (QGraphicsSceneContextMenuEvent * event) protected
References InfoGraphicsView::getInfoGraphicsView(), InfoGraphicsView::getLabelFontSizeLarge(), InfoGraphicsView::getLabelFontSizeMedium(), InfoGraphicsView::getLabelFontSizeSmall(), InfoGraphicsView::getLabelFontSizeTiny(), initMenu(), LabelTextKey, m_displayActs, m_displayKeys, m_font, m_hidden, m_inactive, m_labelAct, m_largeAct, m_mediumAct, m_menu, m_owner, m_smallAct, m_tinyAct, PartLabelDisplayLabelText, partLabelEdit(), PartLabelEdit, PartLabelFlipHorizontal, PartLabelFlipVertical, PartLabelFontSizeLarge, PartLabelFontSizeMedium, PartLabelFontSizeSmall, PartLabelFontSizeTiny, partLabelHide(), PartLabelHide, PartLabelRotate135CCW, PartLabelRotate135CW, PartLabelRotate180, PartLabelRotate45CCW, PartLabelRotate45CW, PartLabelRotate90CCW, PartLabelRotate90CW, resetSvg(), rotateFlip(), setFontSize(), and setLabelDisplay().
displayTexts()
void PartLabel::displayTexts ()
References LabelTextKey, m_displayKeys, m_displayText, m_owner, m_text, and resetSvg().
displayTextsIf()
void PartLabel::displayTextsIf ()
References displayTexts(), m_hidden, and m_initialized.
hidden()
constexpr bool PartLabel::hidden () const inline noexcept
References m_hidden.
inactive()
constexpr bool PartLabel::inactive () const inline noexcept
References m_inactive.
initialized()
constexpr bool PartLabel::initialized () const inline noexcept
References m_initialized.
initMenu()
void PartLabel::initMenu () protected
References m_displayActs, m_labelAct, m_largeAct, m_mediumAct, m_menu, m_owner, m_smallAct, m_tinyAct, PartLabelDisplayLabelText, PartLabelEdit, PartLabelFlipHorizontal, PartLabelFlipVertical, PartLabelFontSizeLarge, PartLabelFontSizeMedium, PartLabelFontSizeSmall, PartLabelFontSizeTiny, PartLabelHide, PartLabelRotate135CCW, PartLabelRotate135CW, PartLabelRotate180, PartLabelRotate45CCW, PartLabelRotate45CW, PartLabelRotate90CCW, PartLabelRotate90CW, ViewLayer::PCBView, and ItemBase::translatePropertyName().
itemChange()
QVariant PartLabel::itemChange (QGraphicsItem::GraphicsItemChange change, const QVariant & value)
makeSvg()
QString PartLabel::makeSvg (bool blackOnly, double dpi, double printerScale, bool includeTransform)
References makeSvgAux(), and TextUtils::svgTransform().
makeSvgAux()
QString PartLabel::makeSvgAux (bool blackOnly, double dpi, double printerScale, double & w, double & h) protected
References TextUtils::convertExtendedChars(), TextUtils::escapeAnd(), InstalledFonts::InstalledFontsNameMapper, m_color, m_displayText, m_font, m_viewLayerID, mapToSVGStyle(), mapToSVGWeight(), qMax(), and ViewLayer::viewLayerXmlNameFromID().
mouseDoubleClickEvent()
void PartLabel::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) protected
References m_doDrag, m_owner, and partLabelEdit().
mouseMoveEvent()
void PartLabel::mouseMoveEvent (QGraphicsSceneMouseEvent * event) protected
References m_doDrag, m_initialPosition, m_offset, m_owner, and m_spaceBarWasPressed.
mousePressEvent()
void PartLabel::mousePressEvent (QGraphicsSceneMouseEvent * event) protected
References InfoGraphicsView::getInfoGraphicsView(), m_doDrag, m_initialOffset, m_initialPosition, m_offset, m_owner, m_spaceBarWasPressed, and InfoGraphicsView::spaceBarIsPressed().
mouseReleaseEvent()
void PartLabel::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected
References m_doDrag, m_initialOffset, m_initialPosition, m_offset, m_owner, and m_spaceBarWasPressed.
moveLabel()
void PartLabel::moveLabel (QPointF newPos, QPointF newOffset)
References m_offset.
owner()
ItemBase * PartLabel::owner ()
References m_owner.
ownerMoved()
void PartLabel::ownerMoved (QPointF newPos)
References m_offset.
ownerSelected()
void PartLabel::ownerSelected (bool selected)
References ALLMOUSEBUTTONS, m_hidden, and m_inactive.
paint()
void PartLabel::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget)
References ItemBase::boundingRect(), InactiveOpacity, m_hidden, m_inactive, m_owner, GraphicsUtils::qt_graphicsItem_highlightSelected(), and shape().
partLabelEdit()
void PartLabel::partLabelEdit () protected
References AllPartLabels, m_owner, m_text, and setPlainText().
partLabelHide()
void PartLabel::partLabelHide () protected
References m_owner.
resetSvg()
void PartLabel::resetSvg () protected
References m_renderer, makeSvgAux(), TextUtils::makeSVGHeader(), GraphicsUtils::StandardFritzingDPI, and GraphicsUtils::SVGDPI.
restoreLabel()
void PartLabel::restoreLabel (QDomElement & labelGeometry, ViewLayer::ViewLayerID viewLayerID)
References displayTexts(), InfoGraphicsView::getInfoGraphicsView(), InfoGraphicsView::getLabelFontSizeMedium(), LabelTextKey, GraphicsUtils::loadTransform(), m_displayKeys, m_font, m_initialized, m_offset, m_owner, m_viewLayerID, ModelPartShared::PartNumberPropertyName, setUpText(), viewLayerID(), and ItemBase::z().
rotateFlip()
void PartLabel::rotateFlip (int action) protected
References m_owner, PartLabelFlipHorizontal, PartLabelFlipVertical, PartLabelRotate135CCW, PartLabelRotate135CW, PartLabelRotate180, PartLabelRotate45CCW, PartLabelRotate45CW, PartLabelRotate90CCW, and PartLabelRotate90CW.
rotateFlipLabel()
void PartLabel::rotateFlipLabel (double degrees, Qt::Orientations orientation)
References transformLabel().
saveInstance()
void PartLabel::saveInstance (QXmlStreamWriter & streamWriter)
References m_color, m_displayKeys, m_font, m_initialized, m_offset, and GraphicsUtils::saveTransform().
setFontPointSize()
void PartLabel::setFontPointSize (double pointSize)
References m_font, and resetSvg().
setFontSize()
void PartLabel::setFontSize (int action) protected
References InfoGraphicsView::getInfoGraphicsView(), InfoGraphicsView::getLabelFontSizeLarge(), InfoGraphicsView::getLabelFontSizeMedium(), InfoGraphicsView::getLabelFontSizeSmall(), InfoGraphicsView::getLabelFontSizeTiny(), m_font, PartLabelFontSizeLarge, PartLabelFontSizeMedium, PartLabelFontSizeSmall, and PartLabelFontSizeTiny.
setHidden()
void PartLabel::setHidden (bool hide)
References m_hidden, m_initialized, and setHiddenOrInactive().
setHiddenOrInactive()
void PartLabel::setHiddenOrInactive () protected
References ALLMOUSEBUTTONS, m_hidden, m_inactive, and m_owner.
setInactive()
void PartLabel::setInactive (bool inactivate)
References m_inactive, m_initialized, and setHiddenOrInactive().
setLabelDisplay()
void PartLabel::setLabelDisplay (const QString & key) protected
References displayTexts(), and m_displayKeys.
setPlainText()
void PartLabel::setPlainText (const QString & text)
References displayTexts(), and m_text.
setUpText()
void PartLabel::setUpText () protected
References InfoGraphicsView::getInfoGraphicsView(), InfoGraphicsView::getLabelFont(), m_color, m_font, and m_owner.
shape()
QPainterPath PartLabel::shape () const
References ItemBase::boundingRect().
showLabel()
void PartLabel::showLabel (bool showIt, ViewLayer * viewLayer)
References flipped(), m_displayKeys, m_initialized, m_offset, m_owner, m_viewLayerID, ViewLayer::nextZ(), ViewLayer::PCBView, setPlainText(), setUpText(), ViewLayer::Silkscreen0Label, transformLabel(), and ViewLayer::viewLayerID().
transformLabel()
void PartLabel::transformLabel (QTransform currTransf) protected
References ItemBase::boundingRect().
viewLayerID()
constexpr ViewLayer::ViewLayerID PartLabel::viewLayerID () const inline noexcept
References m_viewLayerID.
Member Data Documentation
m_color
QColor PartLabel::m_color protected
m_displayActs
QList<QAction *> PartLabel::m_displayActs protected
m_displayKeys
QStringList PartLabel::m_displayKeys protected
m_displayText
QString PartLabel::m_displayText protected
m_doDrag
bool PartLabel::m_doDrag = false protected
m_font
QFont PartLabel::m_font protected
m_hidden
bool PartLabel::m_hidden = false protected
m_inactive
bool PartLabel::m_inactive = false protected
m_initialized
bool PartLabel::m_initialized = false protected
m_initialOffset
QPointF PartLabel::m_initialOffset protected
m_initialPosition
QPointF PartLabel::m_initialPosition protected
m_labelAct
QAction* PartLabel::m_labelAct = nullptr protected
m_largeAct
QAction* PartLabel::m_largeAct = nullptr protected
m_mediumAct
QAction* PartLabel::m_mediumAct = nullptr protected
m_menu
QMenu PartLabel::m_menu protected
m_offset
QPointF PartLabel::m_offset protected
m_owner
QPointer<ItemBase> PartLabel::m_owner protected
m_renderer
QSvgRenderer* PartLabel::m_renderer = nullptr protected
m_smallAct
QAction* PartLabel::m_smallAct = nullptr protected
m_spaceBarWasPressed
bool PartLabel::m_spaceBarWasPressed = false protected
m_text
QString PartLabel::m_text protected
m_tinyAct
QAction* PartLabel::m_tinyAct = nullptr protected
m_viewLayerID
ViewLayer::ViewLayerID PartLabel::m_viewLayerID = ViewLayer::UnknownLayer protected
The documentation for this class was generated from the following files:
items/partlabel.h
items/partlabel.cpp