Fritzing: WaitPushUndoStack Class Reference
WaitPushUndoStack Class Reference
#include <waitpushundostack.h>
Public Member Functions
WaitPushUndoStack (QObject *parent=0)
~WaitPushUndoStack ()
void addTimer (QTimer *)
void deleteTemporary ()
void deleteTimer (QTimer *)
bool hasTimers ()
void push (QUndoCommand *)
void resolveTemporary ()
void waitPush (QUndoCommand *, int delayMS)
void waitPushTemporary (QUndoCommand *, int delayMS)
void writeUndo (const QUndoCommand *, int indent, const class BaseCommand *parent)
Protected Member Functions
void clearDeadTimers ()
void clearLiveTimers ()
void clearTimers (QList< QTimer * > &)
Protected Attributes
QList< QTimer * > m_deadTimers
QFile m_file
QList< QTimer * > m_liveTimers
QMutex m_mutex
QUndoCommand * m_temporary
Constructor & Destructor Documentation
WaitPushUndoStack()
WaitPushUndoStack::WaitPushUndoStack (QObject * parent = 0)
References FolderUtils::getTopLevelUserDataStorePath(), m_file, and m_temporary.
~WaitPushUndoStack()
WaitPushUndoStack::~WaitPushUndoStack ()
References clearDeadTimers(), and clearLiveTimers().
Member Function Documentation
addTimer()
void WaitPushUndoStack::addTimer (QTimer * timer)
References m_liveTimers, and m_mutex.
clearDeadTimers()
void WaitPushUndoStack::clearDeadTimers () protected
References clearTimers(), and m_deadTimers.
clearLiveTimers()
void WaitPushUndoStack::clearLiveTimers () protected
References clearTimers(), and m_liveTimers.
clearTimers()
void WaitPushUndoStack::clearTimers (QList< QTimer * > & timers) protected
References m_mutex.
deleteTemporary()
void WaitPushUndoStack::deleteTemporary ()
References m_temporary.
deleteTimer()
void WaitPushUndoStack::deleteTimer (QTimer * timer)
References m_deadTimers, m_liveTimers, and m_mutex.
hasTimers()
bool WaitPushUndoStack::hasTimers ()
References m_liveTimers, and m_mutex.
push()
void WaitPushUndoStack::push (QUndoCommand * cmd)
References m_temporary, and writeUndo().
resolveTemporary()
void WaitPushUndoStack::resolveTemporary ()
References m_temporary, push(), and TemporaryCommand::setEnabled().
waitPush()
void WaitPushUndoStack::waitPush (QUndoCommand * command, int delayMS)
References clearDeadTimers(), and push().
waitPushTemporary()
void WaitPushUndoStack::waitPushTemporary (QUndoCommand * command, int delayMS)
References m_temporary, and waitPush().
writeUndo()
void WaitPushUndoStack::writeUndo (const QUndoCommand * , int indent, const class BaseCommand * parent)
References BaseCommand::getDebugString(), BaseCommand::index(), m_file, BaseCommand::subCommand(), and BaseCommand::subCommandCount().
Member Data Documentation
m_deadTimers
QList<QTimer *> WaitPushUndoStack::m_deadTimers protected
m_file
QFile WaitPushUndoStack::m_file protected
m_liveTimers
QList<QTimer *> WaitPushUndoStack::m_liveTimers protected
m_mutex
QMutex WaitPushUndoStack::m_mutex protected
m_temporary
QUndoCommand* WaitPushUndoStack::m_temporary protected
The documentation for this class was generated from the following files:
waitpushundostack.h
waitpushundostack.cpp