Fritzing: ConnectorRectangle Class Reference
ConnectorRectangle Class Reference
#include <connectorrectangle.h>
Public Types
enum State { Normal = 0x00000, Highlighted = 0x00001, Hover = 0x00002, Selected = 0x00003 }
Signals
void isResizableSignal (bool &resizable)
void resizeSignal (double x1, double y1, double x2, double y2)
Public Member Functions
ConnectorRectangle (QGraphicsItem *owner, bool withHandlers=true)
~ConnectorRectangle ()
double currentScale ()
QRectF errorIconRect ()
QRectF handlerRect (Qt::Corner corner)
bool isResizable ()
QGraphicsItem * owner ()
void paint (QPainter *painter)
void resizeRect (double x1, double y1, double x2, double y2)
void resizingFinished ()
void resizingStarted ()
void setHandlersVisible (bool visible)
void setMinSize (double minWidth, double minHeight)
Static Public Attributes
static double ErrorIconSize = 6
Protected Member Functions
void placeHandlers ()
void setHandlerRect (CornerHandler *handler)
Protected Attributes
CornerHandler * m_bottomLeftHandler
CornerHandler * m_bottomRightHandler
QList< CornerHandler * > m_cornerHandlers
bool m_firstPaint
double m_minHeight
double m_minWidth
QGraphicsItem * m_owner
CornerHandler * m_topLeftHandler
CornerHandler * m_topRightHandler
Member Enumeration Documentation
State
enum ConnectorRectangle::State
Enumerator
Normal
Highlighted
Hover
Selected
Constructor & Destructor Documentation
ConnectorRectangle()
ConnectorRectangle::ConnectorRectangle (QGraphicsItem * owner, bool withHandlers = true)
References m_bottomLeftHandler, m_bottomRightHandler, m_cornerHandlers, m_firstPaint, m_minHeight, m_minWidth, m_owner, m_topLeftHandler, m_topRightHandler, owner(), and setHandlersVisible().
~ConnectorRectangle()
ConnectorRectangle::~ConnectorRectangle ()
Member Function Documentation
currentScale()
double ConnectorRectangle::currentScale ()
References ZoomableGraphicsView::currentZoom(), and m_owner.
errorIconRect()
QRectF ConnectorRectangle::errorIconRect ()
References currentScale(), ErrorIconSize, and m_owner.
handlerRect()
QRectF ConnectorRectangle::handlerRect (Qt::Corner corner)
References currentScale(), m_owner, and CornerHandler::Size.
isResizable()
bool ConnectorRectangle::isResizable ()
References isResizableSignal().
isResizableSignal
void ConnectorRectangle::isResizableSignal (bool & resizable) signal
owner()
QGraphicsItem * ConnectorRectangle::owner ()
References m_owner.
paint()
void ConnectorRectangle::paint (QPainter * painter)
References CornerHandler::doPaint(), CornerHandler::isBeingDragged(), m_cornerHandlers, m_firstPaint, m_owner, and placeHandlers().
placeHandlers()
void ConnectorRectangle::placeHandlers () protected
References m_cornerHandlers, and setHandlerRect().
resizeRect()
void ConnectorRectangle::resizeRect (double x1, double y1, double x2, double y2)
References m_minHeight, m_minWidth, owner(), and resizeSignal().
resizeSignal
void ConnectorRectangle::resizeSignal (double x1, double y1, double x2, double y2) signal
resizingFinished()
void ConnectorRectangle::resizingFinished ()
References CornerHandler::doSetVisible(), m_cornerHandlers, and setHandlerRect().
resizingStarted()
void ConnectorRectangle::resizingStarted ()
References CornerHandler::doSetVisible(), and m_cornerHandlers.
setHandlerRect()
void ConnectorRectangle::setHandlerRect (CornerHandler * handler) protected
References CornerHandler::corner(), CornerHandler::doSetRect(), and handlerRect().
setHandlersVisible()
void ConnectorRectangle::setHandlersVisible (bool visible)
References CornerHandler::doSetVisible(), and m_cornerHandlers.
setMinSize()
void ConnectorRectangle::setMinSize (double minWidth, double minHeight)
References m_minHeight, and m_minWidth.
Member Data Documentation
ErrorIconSize
double ConnectorRectangle::ErrorIconSize = 6 static
m_bottomLeftHandler
CornerHandler* ConnectorRectangle::m_bottomLeftHandler protected
m_bottomRightHandler
CornerHandler* ConnectorRectangle::m_bottomRightHandler protected
m_cornerHandlers
QList<CornerHandler*> ConnectorRectangle::m_cornerHandlers protected
m_firstPaint
bool ConnectorRectangle::m_firstPaint protected
m_minHeight
double ConnectorRectangle::m_minHeight protected
m_minWidth
double ConnectorRectangle::m_minWidth protected
m_owner
QGraphicsItem* ConnectorRectangle::m_owner protected
m_topLeftHandler
CornerHandler* ConnectorRectangle::m_topLeftHandler protected
m_topRightHandler
CornerHandler* ConnectorRectangle::m_topRightHandler protected
The documentation for this class was generated from the following files:
partseditor/obsolete/connectorrectangle.h
partseditor/obsolete/connectorrectangle.cpp