Fritzing: PartsBinListView Class Reference
PartsBinListView Class Reference
#include <partsbinlistview.h>
Public Slots
void itemMoved (int fromIndex, int toIndex)
void setSelected (int position, bool doEmit=false)
Signals
void informItemMoved (int fromIndex, int toIndex)
void settingItem ()
Public Member Functions
PartsBinListView (ReferenceModel *referenceModel, PartsBinPaletteWidget *parent)
~PartsBinListView ()
QList< QObject * > orderedChildren ()
int position (const QString &moduleID)
void reloadPart (const QString &moduleID)
void removePart (const QString &moduleID)
void removeParts ()
ItemBase * selectedItemBase ()
ModelPart * selectedModelPart ()
void setInfoView (class HtmlInfoView *)
bool swappingEnabled ()
Public Member Functions inherited from PartsBinView
PartsBinView (ReferenceModel *referenceModel, PartsBinPaletteWidget *parent)
virtual ~PartsBinView ()=default
void addPart (ModelPart *model, int position=-1)
bool contains (const QString &moduleID)
void dropEventAux (QDropEvent *event, bool justAppend=false)
void reloadParts (PaletteModel *model)
void setInfoViewOnHover (bool infoViewOnHover)
virtual void setPaletteModel (PaletteModel *model, bool clear=false)
Protected Slots
void showContextMenu (const QPoint &pos)
Protected Member Functions
void doClear ()
void dropEvent (QDropEvent *event)
bool dropMimeData (int index, const QMimeData *data, Qt::DropAction action)
int itemIndexAt (const QPoint &pos, bool &trustIt)
ItemBase * itemItemBase (const QListWidgetItem *item) const
ModelPart * itemModelPart (const QListWidgetItem *item) const
const QString & itemModuleID (const QListWidgetItem *item)
void loadImage (ModelPart *, QListWidgetItem *lwi, const QString &moduleID)
QMimeData * mimeData (const QList< QListWidgetItem * > items) const
QStringList mimeTypes () const
void mouseMoveEvent (QMouseEvent *event)
void mousePressEvent (QMouseEvent *event)
void moveItem (int fromIndex, int toIndex)
int setItemAux (ModelPart *modelPart, int position=-1)
void showInfo (QListWidgetItem *item)
void startDrag (Qt::DropActions supportedActions)
Protected Member Functions inherited from PartsBinView
void dragMoveEnterEventAux (QDragMoveEvent *event)
void mousePressOnItem (const QPoint &dragStartPos, const QString &moduleId, const QSize &size, const QPointF &dataPoint=QPointF(0, 0), const QPoint &hotspot=QPoint(0, 0))
void setItem (ModelPart *modelPart)
virtual void setSelected (int position, bool doEmit=false)=0
Protected Attributes
QListWidgetItem * m_hoverItem
class HtmlInfoView * m_infoView
Protected Attributes inherited from PartsBinView
QPoint m_dragStartPos
bool m_infoViewOnHover = false
QHash< QString, class ItemBase * > m_itemBaseHash
PartsBinPaletteWidget * m_parent = nullptr
ReferenceModel * m_referenceModel = nullptr
Additional Inherited Members
Static Public Member Functions inherited from PartsBinView
static void cleanup ()
static void removePartReference (const QString &moduleID)
Static Public Attributes inherited from PartsBinView
static QHash< QString, QString > TranslatedCategoryNames
Static Protected Attributes inherited from PartsBinView
static QHash< QString, class ItemBase * > ItemBaseHash
Constructor & Destructor Documentation
PartsBinListView()
PartsBinListView::PartsBinListView (ReferenceModel * referenceModel, PartsBinPaletteWidget * parent)
References m_hoverItem, m_infoView, PartsBinView::m_infoViewOnHover, and showContextMenu().
~PartsBinListView()
PartsBinListView::~PartsBinListView ()
Member Function Documentation
doClear()
void PartsBinListView::doClear () protected virtual
Reimplemented from PartsBinView.
References PartsBinView::doClear(), and m_hoverItem.
dropEvent()
void PartsBinListView::dropEvent (QDropEvent * event) protected
References PartsBinView::dropEventAux().
dropMimeData()
bool PartsBinListView::dropMimeData (int index, const QMimeData * data, Qt::DropAction action) protected
informItemMoved
void PartsBinListView::informItemMoved (int fromIndex, int toIndex) signal
itemIndexAt()
int PartsBinListView::itemIndexAt (const QPoint & pos, bool & trustIt) protected virtual
Implements PartsBinView.
References PartsBinView::contains().
itemItemBase()
ItemBase * PartsBinListView::itemItemBase (const QListWidgetItem * item) const protected
itemModelPart()
ModelPart * PartsBinListView::itemModelPart (const QListWidgetItem * item) const protected
References itemItemBase(), and ItemBase::modelPart().
itemModuleID()
const QString & PartsBinListView::itemModuleID (const QListWidgetItem * item) protected
References ___emptyString___, itemModelPart(), and ModelPart::moduleID().
itemMoved
void PartsBinListView::itemMoved (int fromIndex, int toIndex) slot
References setSelected().
loadImage()
void PartsBinListView::loadImage (ModelPart * modelPart, QListWidgetItem * lwi, const QString & moduleID) protected
References PartFactory::createPart(), FSvgRenderer::filename(), ItemBase::getNextID(), FSvgRenderer::getPixmap(), ViewLayer::Icon, ViewLayer::IconView, ItemBase::initLayerAttributes(), PartsBinView::ItemBaseHash, PartsBinView::m_itemBaseHash, ViewLayer::NewTop, ItemBase::setFilename(), ItemBase::setSharedRendererEx(), ItemBase::setUpImage(), HtmlInfoView::STANDARD_ICON_IMG_HEIGHT, HtmlInfoView::STANDARD_ICON_IMG_WIDTH, and ItemBase::viewLayerPlacement().
mimeData()
QMimeData * PartsBinListView::mimeData (const QList< QListWidgetItem * > items) const protected
References itemModelPart(), and ModelPart::moduleID().
mimeTypes()
QStringList PartsBinListView::mimeTypes () const protected
mouseMoveEvent()
void PartsBinListView::mouseMoveEvent (QMouseEvent * event) protected
References m_hoverItem, PartsBinView::m_infoViewOnHover, and showInfo().
mousePressEvent()
void PartsBinListView::mousePressEvent (QMouseEvent * event) protected
References itemItemBase(), PartsBinView::m_dragStartPos, m_hoverItem, m_infoView, showInfo(), and HtmlInfoView::viewItemInfo().
moveItem()
void PartsBinListView::moveItem (int fromIndex, int toIndex) protected virtual
Implements PartsBinView.
References informItemMoved(), and itemMoved().
orderedChildren()
QList< QObject * > PartsBinListView::orderedChildren () virtual
Implements PartsBinView.
References itemModelPart().
position()
int PartsBinListView::position (const QString & moduleID)
References itemModuleID().
reloadPart()
void PartsBinListView::reloadPart (const QString & moduleID) virtual
Implements PartsBinView.
References PartsBinView::contains(), itemItemBase(), loadImage(), ItemBase::modelPart(), ItemBase::moduleID(), and ItemBase::title().
removePart()
void PartsBinListView::removePart (const QString & moduleID) virtual
Implements PartsBinView.
References m_hoverItem, PartsBinView::m_itemBaseHash, and position().
removeParts()
void PartsBinListView::removeParts () virtual
Implements PartsBinView.
References m_hoverItem, and PartsBinView::m_itemBaseHash.
selectedItemBase()
ItemBase * PartsBinListView::selectedItemBase () virtual
Implements PartsBinView.
References itemItemBase().
selectedModelPart()
ModelPart * PartsBinListView::selectedModelPart () virtual
Implements PartsBinView.
References itemModelPart().
setInfoView()
void PartsBinListView::setInfoView (class HtmlInfoView * infoView)
References m_infoView.
setItemAux()
int PartsBinListView::setItemAux (ModelPart * modelPart, int position = -1) protected virtual
Implements PartsBinView.
References PartsBinView::contains(), ModelPart::instanceText(), ModelPart::itemType(), loadImage(), ModelPart::modelPartShared(), ModelPart::moduleID(), position(), SectionHeaderBackgroundColor(), SectionHeaderForegroundColor(), settingItem(), ModelPart::Space, ModelPart::title(), PartsBinView::TranslatedCategoryNames, and ModelPart::Unknown.
setSelected
void PartsBinListView::setSelected (int position, bool doEmit = false) slot
References position().
settingItem
void PartsBinListView::settingItem () signal
showContextMenu
void PartsBinListView::showContextMenu (const QPoint & pos) protected slot
References PartsBinPaletteWidget::combinedMenu(), PartsBinView::m_parent, and PartsBinPaletteWidget::partContextMenu().
showInfo()
void PartsBinListView::showInfo (QListWidgetItem * item) protected
References HtmlInfoView::hoverEnterItem(), HtmlInfoView::hoverLeaveItem(), itemItemBase(), m_hoverItem, m_infoView, and swappingEnabled().
startDrag()
void PartsBinListView::startDrag (Qt::DropActions supportedActions) protected
References ItemDrag::dragIsDone().
swappingEnabled()
bool PartsBinListView::swappingEnabled ()
Member Data Documentation
m_hoverItem
QListWidgetItem* PartsBinListView::m_hoverItem protected
m_infoView
class HtmlInfoView* PartsBinListView::m_infoView protected
The documentation for this class was generated from the following files:
partsbinpalette/partsbinlistview.h
partsbinpalette/partsbinlistview.cpp