Fritzing: PropertyDefMaster Class Reference
PropertyDefMaster Class Reference
#include <propertydef.h>
Static Public Member Functions
static void cleanup ()
static void initPropertyDefs (class ModelPart *, QHash< PropertyDef *, QString > &propertyDefs)
Static Protected Member Functions
static void loadPropertyDefs ()
Static Protected Attributes
static QList< PropertyDef * > PropertyDefs
Member Function Documentation
cleanup()
void PropertyDefMaster::cleanup () static
References PropertyDefs.
initPropertyDefs()
void PropertyDefMaster::initPropertyDefs (class ModelPart * modelPart, QHash< PropertyDef *, QString > & propertyDefs) static
References TextUtils::convertToPowerPrefix(), PropertyDef::defaultValue, loadPropertyDefs(), ModelPart::localProp(), ModelPart::moduleID(), PropertyDef::name, PropertyDef::numeric, ModelPart::properties(), PropertyDefs, ModelPart::setLocalProp(), PropertyDef::suffixes, and PropertyDef::symbol.
loadPropertyDefs()
void PropertyDefMaster::loadPropertyDefs () static protected
References PropertyDef::adjuncts, DebugDialog::debug(), PropertyDef::defaultValue, PropertyDef::editable, PropertyDef::maxValue, PropertyDef::menuItems, PropertyDef::minValue, PropertyDef::name, PropertyDef::numeric, PropertyDefs, PropertyDef::sMenuItems, PropertyDef::suffixes, and PropertyDef::symbol.
Member Data Documentation
PropertyDefs
QList< PropertyDef * > PropertyDefMaster::PropertyDefs static protected
The documentation for this class was generated from the following files:
items/propertydef.h
items/propertydef.cpp