Fritzing: DebugDialog Class Reference
DebugDialog Class Reference
#include <debugdialog.h>
Public Types
enum DebugLevel { Debug, Info, Warning, Error }
Signals
void debugBroadcast (const QString &message, DebugLevel, QObject *ancestor)
Static Public Member Functions
static void cleanup ()
static void closeDebug ()
static bool connectToBroadcast (QObject *receiver, const char *slot)
static void debug (QString, const QPointF &point, DebugLevel=Debug, QObject *ancestor=0)
static void debug (QString, const QRectF &rect, DebugLevel=Debug, QObject *ancestor=0)
static void debug (QString, const QPoint &point, DebugLevel=Debug, QObject *ancestor=0)
static void debug (QString, const QRect &rect, DebugLevel=Debug, QObject *ancestor=0)
static void debug (QString, DebugLevel=Debug, QObject *ancestor=0)
static bool enabled ()
static void hideDebug ()
static void setDebugLevel (DebugLevel)
static void setEnabled (bool)
static void showDebug ()
static bool visible ()
Protected Member Functions
bool event (QEvent *e)
void resizeEvent (QResizeEvent *event)
Protected Attributes
DebugLevel m_debugLevel
QPointer< QTextEdit > m_textEdit
Static Protected Attributes
static bool m_enabled = true
static QFile m_file
static DebugDialog * singleton = NULL
Private Member Functions
DebugDialog (QWidget *parent=0)
~DebugDialog ()
Member Enumeration Documentation
DebugLevel
enum DebugDialog::DebugLevel
Enumerator
Debug
Info
Warning
Error
Constructor & Destructor Documentation
DebugDialog()
DebugDialog::DebugDialog (QWidget * parent = 0) private
References Debug, FolderUtils::getTopLevelUserDataStorePath(), m_debugLevel, m_file, m_textEdit, and singleton.
~DebugDialog()
DebugDialog::~DebugDialog () private
References m_textEdit.
Member Function Documentation
cleanup()
void DebugDialog::cleanup () static
References singleton.
closeDebug()
void DebugDialog::closeDebug () static
References singleton.
connectToBroadcast()
bool DebugDialog::connectToBroadcast (QObject * receiver, const char * slot) static
References debugBroadcast(), DebugDialog(), and singleton.
debug() [1/5]
void DebugDialog::debug (QString prefix, const QPointF & point, DebugLevel debug = Debug, QObject * ancestor = 0) static
debug() [2/5]
void DebugDialog::debug (QString prefix, const QRectF & rect, DebugLevel debug = Debug, QObject * ancestor = 0) static
References debug().
debug() [3/5]
void DebugDialog::debug (QString prefix, const QPoint & point, DebugLevel debug = Debug, QObject * ancestor = 0) static
References debug().
debug() [4/5]
void DebugDialog::debug (QString prefix, const QRect & rect, DebugLevel debug = Debug, QObject * ancestor = 0) static
References debug().
debug() [5/5]
void DebugDialog::debug (QString message, DebugLevel debugLevel = Debug, QObject * ancestor = 0) static
References DebugDialog(), m_debugLevel, m_enabled, m_file, and singleton.
debugBroadcast
void DebugDialog::debugBroadcast (const QString & message, DebugLevel , QObject * ancestor) signal
enabled()
bool DebugDialog::enabled () static
References m_enabled.
event()
bool DebugDialog::event (QEvent * e) protected
References debugBroadcast(), DebugEventType, m_debugLevel, and m_textEdit.
hideDebug()
void DebugDialog::hideDebug () static
References singleton.
resizeEvent()
void DebugDialog::resizeEvent (QResizeEvent * event) protected
References m_textEdit.
setDebugLevel()
void DebugDialog::setDebugLevel (DebugLevel debugLevel) static
References DebugDialog(), m_debugLevel, and singleton.
setEnabled()
void DebugDialog::setEnabled (bool enabled) static
References enabled(), and m_enabled.
showDebug()
void DebugDialog::showDebug () static
References DebugDialog(), and singleton.
visible()
bool DebugDialog::visible () static
References singleton.
Member Data Documentation
m_debugLevel
DebugLevel DebugDialog::m_debugLevel protected
m_enabled
bool DebugDialog::m_enabled = true static protected
m_file
QFile DebugDialog::m_file static protected
m_textEdit
QPointer<QTextEdit> DebugDialog::m_textEdit protected
singleton
DebugDialog * DebugDialog::singleton = NULL static protected
The documentation for this class was generated from the following files:
debugdialog.h
debugdialog.cpp