Fritzing: items/paletteitem.cpp File Reference
paletteitem.cpp File Reference
#include "paletteitem.h"
#include "../debugdialog.h"
#include "../viewgeometry.h"
#include "../sketch/infographicsview.h"
#include "layerkinpaletteitem.h"
#include "../fsvgrenderer.h"
#include "partlabel.h"
#include "partfactory.h"
#include "../commands.h"
#include "../connectors/connectoritem.h"
#include "../connectors/connector.h"
#include "../connectors/svgidlayer.h"
#include "../layerattributes.h"
#include "../dialogs/pinlabeldialog.h"
#include "../utils/folderutils.h"
#include "../utils/textutils.h"
#include "../utils/graphicsutils.h"
#include "../utils/familypropertycombobox.h"
#include "../svg/svgfilesplitter.h"
#include "wire.h"
#include <QGraphicsSceneMouseEvent>
#include <QSvgRenderer>
#include <QtDebug>
#include <QPainter>
#include <QDomElement>
#include <QDir>
#include <QMessageBox>
#include <QPushButton>
#include <QVBoxLayout>
#include <QRegExp>
#include <QGroupBox>
#include <QLabel>
#include <limits>
Functions
bool byID (Connector *c1, Connector *c2)
static QRegExp ConnectorFinder ("connector\\d+pin")
int findNumber (const QString &string)
static QRegExp LabelFinder ("id=['|\"]label['|\"]")
Variables
static bool ByIDParseSuccessful = true
Function Documentation
byID()
bool byID (Connector * c1, Connector * c2)
References ByIDParseSuccessful, Connector::connectorSharedID(), and findNumber().
ConnectorFinder()
static QRegExp ConnectorFinder ("connector\\d+pin") static
findNumber()
int findNumber (const QString & string)
References IntegerFinder().
LabelFinder()
static QRegExp LabelFinder (" id = ['|\"]label['|\"]") static
Variable Documentation
ByIDParseSuccessful
bool ByIDParseSuccessful = true static