Fritzing: InfoGraphicsView Class Reference
InfoGraphicsView Class Reference abstract
#include <infographicsview.h>
Public Slots
virtual void resizeBoard (double w, double h, bool doEmit)
virtual void setInstanceTitle (long id, const QString &oldTitle, const QString &newTitle, bool isUndoable, bool doEmit)
virtual void setVoltage (double, bool doEmit)
Signals
void changePinLabelsSignal (ItemBase *, bool singleRow)
void newWireSignal (Wire *)
void setActiveConnectorItemSignal (ConnectorItem *)
void setActiveWireSignal (Wire *)
void setVoltageSignal (double, bool doEmit)
void swapSignal (const QString &family, const QString &prop, QMap< QString, QString > &propsMap, ItemBase *)
Signals inherited from ZoomableGraphicsView
void wheelSignal ()
void zoomChanged (double zoom)
void zoomOutOfRange (double zoom)
Public Member Functions
InfoGraphicsView (QWidget *parent=0)
int boardLayers ()
virtual void changeBus (ItemBase *, bool connect, const QString &oldBus, const QString &newBus, QList< ConnectorItem * > &, const QString &message, const QString &oldLayout, const QString &newLayout)
virtual void changePinLabels (ItemBase *, bool singleRow)
virtual void changeWireColor (const QString newColor)
virtual void changeWireWidthMils (const QString newWidth)
virtual bool curvyWiresIndicated (Qt::KeyboardModifiers)
virtual const QString & filenameIf ()
virtual QString generateCopperFillUnit (ItemBase *itemBase, QPointF whereToStart)
virtual void getBendpointWidths (class Wire *, double w, double &w1, double &w2, bool &negativeOffsetRect)
virtual void getLabelFont (QFont &, QColor &, ItemBase *)
virtual double getLabelFontSizeLarge ()
virtual double getLabelFontSizeMedium ()
virtual double getLabelFontSizeSmall ()
virtual double getLabelFontSizeTiny ()
virtual void getRatsnestColor (QColor &)
virtual ViewGeometry::WireFlag getTraceFlag ()
virtual double getWireStrokeWidth (Wire *, double wireWidth)
virtual bool hasBigDots ()
virtual void hidePartLabel (ItemBase *item)
virtual void hoverEnterConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *)
virtual void hoverEnterItem (QGraphicsSceneHoverEvent *event, ItemBase *)
virtual void hoverLeaveConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *)
virtual void hoverLeaveItem (QGraphicsSceneHoverEvent *event, ItemBase *)
class HtmlInfoView * infoView ()
virtual void initWire (class Wire *, int penWidth)
virtual void loadLogoImage (ItemBase *, const QString &oldSvg, const QSizeF oldAspectRatio, const QString &oldFilename, const QString &newFilename, bool addName)
virtual class VirtualWire * makeOneRatsnestWire (ConnectorItem *source, ConnectorItem *dest, bool routed, QColor, bool force)
virtual void mousePressConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual void moveItem (ItemBase *, double x, double y)
virtual void newWire (Wire *)
virtual void noteChanged (ItemBase *, const QString &oldText, const QString &newText, QSizeF oldSize, QSizeF newSize)
virtual void noteSizeChanged (ItemBase *itemBase, const QSizeF &oldSize, const QSizeF &newSize)
virtual void partLabelChanged (ItemBase *, const QString &oldText, const QString &newText)
virtual void partLabelMoved (ItemBase *, QPointF oldPos, QPointF oldOffset, QPointF newPos, QPointF newOffset)
virtual void prepLegBendpointChange (ConnectorItem *from, int oldCount, int newCount, int index, QPointF pos, const class Bezier *, const class Bezier *, const class Bezier *, bool triggerFirstTime)
virtual void prepLegBendpointMove (ConnectorItem *from, int index, QPointF oldPos, QPointF newPos, ConnectorItem *to, bool changeConnections)
virtual void prepLegCurveChange (ConnectorItem *from, int index, const class Bezier *oldB, const class Bezier *newB, bool triggerFirstTime)
virtual void prepLegSelection (ItemBase *)
virtual void renamePins (ItemBase *, const QStringList &oldLabels, const QStringList &newLabels, bool singleRow)
virtual void resolveTemporary (bool, ItemBase *)
virtual void rotateFlipPartLabel (ItemBase *, double degrees, Qt::Orientations flipDirection)
virtual void rotateX (double degrees, bool rubberBandLegEnabled, ItemBase *originatingItem)
void setActiveConnectorItem (ConnectorItem *)
void setActiveWire (Wire *)
virtual void setAnyInRotation ()
virtual void setBoardLayers (int, bool redraw)
virtual void setHoleSize (ItemBase *, const QString &propName, const QString &translatedPropName, const QString &oldValue, const QString &newValue, QRectF &oldRect, QRectF &newRect, bool redraw)
virtual void setIgnoreSelectionChangeEvents (bool)
void setInfoView (class HtmlInfoView *)
virtual void setNoteFocus (QGraphicsItem *, bool inFocus)
virtual void setProp (ItemBase *, const QString &propName, const QString &translatedPropName, const QString &oldValue, const QString &newValue, bool redraw)
virtual void setResistance (QString resistance, QString pinSpacing)
void setSMDOrientation (Qt::Orientations)
Qt::Orientations smdOrientation ()
virtual bool spaceBarIsPressed ()
virtual void swap (const QString &family, const QString &prop, QMap< QString, QString > &propsMap, ItemBase *)
virtual bool swappingEnabled (ItemBase *)=0
virtual void triggerRotate (ItemBase *, double degrees)
void updateRotation (ItemBase *)
virtual void viewItemInfo (ItemBase *)
virtual LayerHash & viewLayers ()
Public Member Functions inherited from ZoomableGraphicsView
ZoomableGraphicsView (QWidget *parent=0)
void absoluteZoom (double percent)
double currentZoom ()
virtual void ensureFixedToBottomRightItems ()
void relativeZoom (double step, bool centerToCursor)
void setAcceptWheelEvents (bool)
virtual void setViewFromBelow (bool)
bool viewFromBelow ()
Static Public Member Functions
static InfoGraphicsView * getInfoGraphicsView (QGraphicsItem *)
Static Public Member Functions inherited from ZoomableGraphicsView
static void setWheelMapping (WheelMapping)
static WheelMapping wheelMapping ()
Protected Member Functions
QGraphicsItem * selectedAux ()
Protected Member Functions inherited from ZoomableGraphicsView
virtual void wheelEvent (QWheelEvent *event)
Protected Attributes
int m_boardLayers
bool m_hoverEnterConnectorMode
bool m_hoverEnterMode
class HtmlInfoView * m_infoView
Qt::Orientations m_smdOrientation
Protected Attributes inherited from ZoomableGraphicsView
bool m_acceptWheelEvents
int m_maxScaleValue
int m_minScaleValue
double m_scaleValue
bool m_viewFromBelow
Additional Inherited Members
Public Types inherited from ZoomableGraphicsView
enum WheelMapping { ScrollPrimary, ZoomPrimary, WheelMappingCount }
Static Public Attributes inherited from ZoomableGraphicsView
static const int MaxScaleValue = 3000
Static Protected Attributes inherited from ZoomableGraphicsView
static WheelMapping m_wheelMapping
Constructor & Destructor Documentation
InfoGraphicsView()
InfoGraphicsView::InfoGraphicsView (QWidget * parent = 0)
References m_boardLayers, m_hoverEnterConnectorMode, m_hoverEnterMode, m_infoView, and m_smdOrientation.
Member Function Documentation
boardLayers()
int InfoGraphicsView::boardLayers ()
References m_boardLayers.
changeBus()
void InfoGraphicsView::changeBus (ItemBase * , bool connect, const QString & oldBus, const QString & newBus, QList< ConnectorItem * > & , const QString & message, const QString & oldLayout, const QString & newLayout) virtual
Reimplemented in SketchWidget.
changePinLabels()
void InfoGraphicsView::changePinLabels (ItemBase * itemBase, bool singleRow) virtual
changePinLabelsSignal
void InfoGraphicsView::changePinLabelsSignal (ItemBase * , bool singleRow) signal
changeWireColor()
void InfoGraphicsView::changeWireColor (const QString newColor) virtual
changeWireWidthMils()
void InfoGraphicsView::changeWireWidthMils (const QString newWidth) virtual
curvyWiresIndicated()
bool InfoGraphicsView::curvyWiresIndicated (Qt::KeyboardModifiers) virtual
Reimplemented in SketchWidget.
filenameIf()
const QString & InfoGraphicsView::filenameIf () virtual
Reimplemented in SketchWidget.
References ___emptyString___.
generateCopperFillUnit()
QString InfoGraphicsView::generateCopperFillUnit (ItemBase * itemBase, QPointF whereToStart) virtual
Reimplemented in PCBSketchWidget, and SchematicSketchWidget.
getBendpointWidths()
void InfoGraphicsView::getBendpointWidths (class Wire * , double w, double & w1, double & w2, bool & negativeOffsetRect) virtual
Reimplemented in SketchWidget, PCBSketchWidget, SchematicSketchWidget, and BreadboardSketchWidget.
getInfoGraphicsView()
InfoGraphicsView * InfoGraphicsView::getInfoGraphicsView (QGraphicsItem * item) static
getLabelFont()
void InfoGraphicsView::getLabelFont (QFont & , QColor & , ItemBase *) virtual
Reimplemented in PCBSketchWidget, BreadboardSketchWidget, and SchematicSketchWidget.
getLabelFontSizeLarge()
double InfoGraphicsView::getLabelFontSizeLarge () virtual
Reimplemented in PCBSketchWidget.
getLabelFontSizeMedium()
double InfoGraphicsView::getLabelFontSizeMedium () virtual
Reimplemented in PCBSketchWidget.
getLabelFontSizeSmall()
double InfoGraphicsView::getLabelFontSizeSmall () virtual
Reimplemented in PCBSketchWidget.
getLabelFontSizeTiny()
double InfoGraphicsView::getLabelFontSizeTiny () virtual
Reimplemented in PCBSketchWidget.
getRatsnestColor()
void InfoGraphicsView::getRatsnestColor (QColor & color) virtual
Reimplemented in SketchWidget.
getTraceFlag()
ViewGeometry::WireFlag InfoGraphicsView::getTraceFlag () virtual
Reimplemented in SketchWidget, PCBSketchWidget, and SchematicSketchWidget.
References ViewGeometry::NoFlag.
getWireStrokeWidth()
double InfoGraphicsView::getWireStrokeWidth (Wire * , double wireWidth) virtual
Reimplemented in PCBSketchWidget, SchematicSketchWidget, and BreadboardSketchWidget.
hasBigDots()
bool InfoGraphicsView::hasBigDots () virtual
Reimplemented in SchematicSketchWidget.
hidePartLabel()
void InfoGraphicsView::hidePartLabel (ItemBase * item) virtual
Reimplemented in SketchWidget.
hoverEnterConnectorItem()
void InfoGraphicsView::hoverEnterConnectorItem (QGraphicsSceneHoverEvent * event, ConnectorItem * item) virtual
Reimplemented in SketchWidget.
References NonConnectorItem::attachedTo(), HtmlInfoView::hoverEnterConnectorItem(), m_hoverEnterConnectorMode, m_infoView, and swappingEnabled().
hoverEnterItem()
void InfoGraphicsView::hoverEnterItem (QGraphicsSceneHoverEvent * event, ItemBase * itemBase) virtual
Reimplemented in SketchWidget.
References HtmlInfoView::hoverEnterItem(), ViewLayer::IconView, ItemBase::layerKinChief(), m_hoverEnterMode, m_infoView, swappingEnabled(), and ItemBase::viewID().
hoverLeaveConnectorItem()
void InfoGraphicsView::hoverLeaveConnectorItem (QGraphicsSceneHoverEvent * event, ConnectorItem * item) virtual
Reimplemented in SketchWidget.
References HtmlInfoView::hoverLeaveConnectorItem(), m_hoverEnterConnectorMode, and m_infoView.
hoverLeaveItem()
void InfoGraphicsView::hoverLeaveItem (QGraphicsSceneHoverEvent * event, ItemBase * itemBase) virtual
Reimplemented in SketchWidget.
References HtmlInfoView::hoverLeaveItem(), ItemBase::layerKinChief(), m_hoverEnterMode, and m_infoView.
infoView()
HtmlInfoView * InfoGraphicsView::infoView ()
References m_infoView.
initWire()
void InfoGraphicsView::initWire (class Wire * , int penWidth) virtual
Reimplemented in PCBSketchWidget, SchematicSketchWidget, and BreadboardSketchWidget.
loadLogoImage()
void InfoGraphicsView::loadLogoImage (ItemBase * , const QString & oldSvg, const QSizeF oldAspectRatio, const QString & oldFilename, const QString & newFilename, bool addName) virtual
Reimplemented in SketchWidget.
makeOneRatsnestWire()
VirtualWire * InfoGraphicsView::makeOneRatsnestWire (ConnectorItem * source, ConnectorItem * dest, bool routed, QColor color, bool force) virtual
Reimplemented in SketchWidget.
mousePressConnectorEvent()
void InfoGraphicsView::mousePressConnectorEvent (ConnectorItem * , QGraphicsSceneMouseEvent *) virtual
Reimplemented in SketchWidget.
moveItem()
void InfoGraphicsView::moveItem (ItemBase * , double x, double y) virtual
Reimplemented in SketchWidget.
newWire()
void InfoGraphicsView::newWire (Wire * wire) virtual
References DebugDialog::debug(), and newWireSignal().
newWireSignal
void InfoGraphicsView::newWireSignal (Wire *) signal
noteChanged()
void InfoGraphicsView::noteChanged (ItemBase * item, const QString & oldText, const QString & newText, QSizeF oldSize, QSizeF newSize) virtual
Reimplemented in SketchWidget.
noteSizeChanged()
void InfoGraphicsView::noteSizeChanged (ItemBase * itemBase, const QSizeF & oldSize, const QSizeF & newSize) virtual
Reimplemented in SketchWidget.
partLabelChanged()
void InfoGraphicsView::partLabelChanged (ItemBase * item, const QString & oldText, const QString & newText) virtual
Reimplemented in SketchWidget.
partLabelMoved()
void InfoGraphicsView::partLabelMoved (ItemBase * itemBase, QPointF oldPos, QPointF oldOffset, QPointF newPos, QPointF newOffset) virtual
Reimplemented in SketchWidget.
prepLegBendpointChange()
void InfoGraphicsView::prepLegBendpointChange (ConnectorItem * from, int oldCount, int newCount, int index, QPointF pos, const class Bezier * , const class Bezier * , const class Bezier * , bool triggerFirstTime) virtual
Reimplemented in SketchWidget.
prepLegBendpointMove()
void InfoGraphicsView::prepLegBendpointMove (ConnectorItem * from, int index, QPointF oldPos, QPointF newPos, ConnectorItem * to, bool changeConnections) virtual
Reimplemented in SketchWidget.
prepLegCurveChange()
void InfoGraphicsView::prepLegCurveChange (ConnectorItem * from, int index, const class Bezier * oldB, const class Bezier * newB, bool triggerFirstTime) virtual
Reimplemented in SketchWidget.
prepLegSelection()
void InfoGraphicsView::prepLegSelection (ItemBase *) virtual
Reimplemented in SketchWidget.
renamePins()
void InfoGraphicsView::renamePins (ItemBase * , const QStringList & oldLabels, const QStringList & newLabels, bool singleRow) virtual
Reimplemented in SketchWidget.
resizeBoard
void InfoGraphicsView::resizeBoard (double w, double h, bool doEmit) virtual slot
resolveTemporary()
void InfoGraphicsView::resolveTemporary (bool , ItemBase *) virtual
Reimplemented in SketchWidget.
rotateFlipPartLabel()
void InfoGraphicsView::rotateFlipPartLabel (ItemBase * itemBase, double degrees, Qt::Orientations flipDirection) virtual
Reimplemented in SketchWidget.
rotateX()
void InfoGraphicsView::rotateX (double degrees, bool rubberBandLegEnabled, ItemBase * originatingItem) virtual
Reimplemented in SketchWidget.
selectedAux()
QGraphicsItem * InfoGraphicsView::selectedAux () protected
setActiveConnectorItem()
void InfoGraphicsView::setActiveConnectorItem (ConnectorItem * connectorItem)
References setActiveConnectorItemSignal().
setActiveConnectorItemSignal
void InfoGraphicsView::setActiveConnectorItemSignal (ConnectorItem *) signal
setActiveWire()
void InfoGraphicsView::setActiveWire (Wire * wire)
References setActiveWireSignal().
setActiveWireSignal
void InfoGraphicsView::setActiveWireSignal (Wire *) signal
setAnyInRotation()
void InfoGraphicsView::setAnyInRotation () virtual
Reimplemented in SketchWidget.
setBoardLayers()
void InfoGraphicsView::setBoardLayers (int layers, bool redraw) virtual
Reimplemented in PCBSketchWidget.
References layers(), and m_boardLayers.
setHoleSize()
void InfoGraphicsView::setHoleSize (ItemBase * item, const QString & propName, const QString & translatedPropName, const QString & oldValue, const QString & newValue, QRectF & oldRect, QRectF & newRect, bool redraw) virtual
setIgnoreSelectionChangeEvents()
virtual void InfoGraphicsView::setIgnoreSelectionChangeEvents (bool) inline virtual
Reimplemented in SketchWidget.
setInfoView()
void InfoGraphicsView::setInfoView (class HtmlInfoView * infoView)
References infoView(), and m_infoView.
setInstanceTitle
void InfoGraphicsView::setInstanceTitle (long id, const QString & oldTitle, const QString & newTitle, bool isUndoable, bool doEmit) virtual slot
setNoteFocus()
void InfoGraphicsView::setNoteFocus (QGraphicsItem * item, bool inFocus) virtual
Reimplemented in SketchWidget.
setProp()
void InfoGraphicsView::setProp (ItemBase * item, const QString & propName, const QString & translatedPropName, const QString & oldValue, const QString & newValue, bool redraw) virtual
setResistance()
void InfoGraphicsView::setResistance (QString resistance, QString pinSpacing) virtual
setSMDOrientation()
void InfoGraphicsView::setSMDOrientation (Qt::Orientations orientation)
References m_smdOrientation.
setVoltage
void InfoGraphicsView::setVoltage (double v, bool doEmit) virtual slot
References setVoltageSignal().
setVoltageSignal
void InfoGraphicsView::setVoltageSignal (double , bool doEmit) signal
smdOrientation()
Qt::Orientations InfoGraphicsView::smdOrientation ()
References m_smdOrientation.
spaceBarIsPressed()
bool InfoGraphicsView::spaceBarIsPressed () virtual
Reimplemented in SketchWidget.
swap()
void InfoGraphicsView::swap (const QString & family, const QString & prop, QMap< QString, QString > & propsMap, ItemBase * itemBase) virtual
References swapSignal().
swappingEnabled()
virtual bool InfoGraphicsView::swappingEnabled (ItemBase *) pure virtual
Implemented in SketchWidget, and PartsBinIconView.
swapSignal
void InfoGraphicsView::swapSignal (const QString & family, const QString & prop, QMap< QString, QString > & propsMap, ItemBase *) signal
triggerRotate()
void InfoGraphicsView::triggerRotate (ItemBase * , double degrees) virtual
Reimplemented in SketchWidget.
updateRotation()
void InfoGraphicsView::updateRotation (ItemBase * itemBase)
References m_infoView, and HtmlInfoView::updateRotation().
viewItemInfo()
void InfoGraphicsView::viewItemInfo (ItemBase * item) virtual
Reimplemented in SketchWidget.
References ItemBase::layerKinChief(), m_infoView, swappingEnabled(), and HtmlInfoView::viewItemInfo().
viewLayers()
LayerHash & InfoGraphicsView::viewLayers () virtual
Reimplemented in SketchWidget.
References ViewLayers.
Member Data Documentation
m_boardLayers
int InfoGraphicsView::m_boardLayers protected
m_hoverEnterConnectorMode
bool InfoGraphicsView::m_hoverEnterConnectorMode protected
m_hoverEnterMode
bool InfoGraphicsView::m_hoverEnterMode protected
m_infoView
class HtmlInfoView* InfoGraphicsView::m_infoView protected
m_smdOrientation
Qt::Orientations InfoGraphicsView::m_smdOrientation protected
The documentation for this class was generated from the following files:
sketch/infographicsview.h
sketch/infographicsview.cpp