Fritzing: ChangeWireCurveCommand Class Reference
ChangeWireCurveCommand Class Reference
#include <commands.h>
Public Member Functions
ChangeWireCurveCommand (class SketchWidget *sketchWidget, long fromID, const class Bezier *oldBezier, const class Bezier *newBezier, bool wasAutoroutable, QUndoCommand *parent)
void redo ()
void undo ()
Public Member Functions inherited from BaseCommand
BaseCommand (BaseCommand::CrossViewType, SketchWidget *, QUndoCommand *parent)
~BaseCommand ()
void addSubCommand (BaseCommand *subCommand)
BaseCommand::CrossViewType crossViewType () const noexcept
virtual QString getDebugString () const
int index () const
const QUndoCommand * parentCommand () const
void redo ()
void setCrossViewType (BaseCommand::CrossViewType)
void setRedoOnly ()
void setSkipFirstRedo ()
void setUndoOnly ()
SketchWidget * sketchWidget () const
const BaseCommand * subCommand (int index) const
int subCommandCount () const
void subRedo ()
void subRedo (int index)
void subUndo ()
void subUndo (int index)
void undo ()
Protected Member Functions
QString getParamString () const
Protected Attributes
long m_fromID
class Bezier * m_newBezier
class Bezier * m_oldBezier
bool m_wasAutoroutable
Protected Attributes inherited from BaseCommand
QList< BaseCommand * > m_commands
BaseCommand::CrossViewType m_crossViewType
int m_index = 0
QUndoCommand * m_parentCommand = nullptr
bool m_redoOnly = false
SketchWidget * m_sketchWidget = nullptr
bool m_skipFirstRedo = false
bool m_undoOnly = false
Additional Inherited Members
Public Types inherited from BaseCommand
enum CrossViewType { SingleView, CrossView }
Static Public Member Functions inherited from BaseCommand
static void clearProgress ()
static CommandProgress * initProgress ()
static int totalChildCount (const QUndoCommand *)
Static Protected Attributes inherited from BaseCommand
static CommandProgress m_commandProgress
static int nextIndex = 0
Constructor & Destructor Documentation
ChangeWireCurveCommand()
ChangeWireCurveCommand::ChangeWireCurveCommand (class SketchWidget * sketchWidget, long fromID, const class Bezier * oldBezier, const class Bezier * newBezier, bool wasAutoroutable, QUndoCommand * parent)
References Bezier::copy(), m_fromID, m_newBezier, m_oldBezier, and m_wasAutoroutable.
Member Function Documentation
getParamString()
QString ChangeWireCurveCommand::getParamString () const protected virtual
Reimplemented from BaseCommand.
References Bezier::cp0(), Bezier::cp1(), BaseCommand::getParamString(), m_fromID, m_newBezier, and m_oldBezier.
redo()
void ChangeWireCurveCommand::redo ()
References SketchWidget::changeWireCurve(), m_fromID, m_newBezier, BaseCommand::m_sketchWidget, BaseCommand::m_skipFirstRedo, BaseCommand::m_undoOnly, and BaseCommand::redo().
undo()
void ChangeWireCurveCommand::undo ()
References SketchWidget::changeWireCurve(), m_fromID, m_oldBezier, BaseCommand::m_redoOnly, BaseCommand::m_sketchWidget, m_wasAutoroutable, and BaseCommand::undo().
Member Data Documentation
m_fromID
long ChangeWireCurveCommand::m_fromID protected
m_newBezier
class Bezier* ChangeWireCurveCommand::m_newBezier protected
m_oldBezier
class Bezier* ChangeWireCurveCommand::m_oldBezier protected
m_wasAutoroutable
bool ChangeWireCurveCommand::m_wasAutoroutable protected
The documentation for this class was generated from the following files:
commands.h
commands.cpp