Fritzing: GroundPlaneGenerator Class Reference
GroundPlaneGenerator Class Reference
#include <groundplanegenerator.h>
Signals
void postImageSignal (GroundPlaneGenerator *, QImage *copperImage, QImage *boardImage, QGraphicsItem *board, QList< QRectF > *)
Public Member Functions
GroundPlaneGenerator ()
~GroundPlaneGenerator ()
bool generateGroundPlane (const QString &boardSvg, QSizeF boardImageSize, const QString &svg, QSizeF copperImageSize, QStringList &exceptions, QGraphicsItem *board, double res, const QString &color, double keepoutMils)
bool generateGroundPlaneUnit (const QString &boardSvg, QSizeF boardImageSize, const QString &svg, QSizeF copperImageSize, QStringList &exceptions, QGraphicsItem *board, double res, const QString &color, QPointF whereToStart, double keepoutMils)
bool getBoardRects (const QByteArray &boardByteArray, QGraphicsItem *board, double res, double keepoutSpace, QList< QRect > &rects)
const QString & layerName ()
QString mergeSVGs (const QString &initialSVG, const QString &layerName)
const QList< QPointF > & newOffsets ()
const QStringList & newSVGs ()
void scanImage (QImage &image, double bWidth, double bHeight, double pixelFactor, double res, const QString &colorString, bool makeConnector, bool makeOffset, QSizeF minAreaInches, double minDimensionInches, QPointF offsetPolygons)
void scanLines (QImage &image, int bWidth, int bHeight, QList< QRect > &rects)
void scanOutline (QImage &image, double bWidth, double bHeight, double pixelFactor, double res, const QString &colorString, bool makeConnector, bool makeOffset, QSizeF minAreaInches, double minDimensionInches)
void setLayerName (const QString &)
void setMinRunSize (int minRunSize, int minRiseSize)
void setStrokeWidthIncrement (double)
Static Public Attributes
static QString ConnectorName = "connector0pad"
static const double KeepoutDefaultMils = 10
static const QString KeepoutSettingName
Protected Member Functions
double calcArea (QPolygon &poly)
bool collectBorderPoints (QImage &image, QList< QPoint > &points)
QImage * generateGroundPlaneAux (GPGParams &, double &bWidth, double &bHeight, QList< QRectF > &)
bool generateGroundPlaneFn (GPGParams &)
void joinScanLines (QList< QRect > &rects, QList< QPolygon > &polygons)
void makeConnector (QList< QPolygon > &polygons, double res, double pixelFactor, const QString &colorString, int minX, int minY, QString &svg)
QString makeOnePoly (const QPolygon &poly, const QString &colorString, const QString &id, int minX, int minY)
QString makePolySvg (QList< QPolygon > &polygons, double res, double bWidth, double bHeight, double pixelFactor, const QString &colorString, bool makeConnectorFlag, QPointF *offset, QSizeF minAreaInches, double minDimensionInches, QPointF polygonOffset)
void makePolySvg (QList< QPolygon > &polygons, double res, double bWidth, double bHeight, double pixelFactor, const QString &colorString, bool makeConnectorFlag, bool makeOffset, QSizeF minAreaInches, double minDimensionInches, QPointF polygonOffset)
void splitScanLines (QList< QRect > &rects, QList< QList< int > * > &pieces)
bool try8 (int x, int y, QImage &image, QList< QPoint > &points)
bool tryNextPoint (int x, int y, QImage &image, QList< QPoint > &points)
Protected Attributes
double m_blurBy
QString m_layerName
int m_minRiseSize
int m_minRunSize
QList< QPointF > m_newOffsets
QStringList m_newSVGs
double m_strokeWidthIncrement
Constructor & Destructor Documentation
GroundPlaneGenerator()
GroundPlaneGenerator::GroundPlaneGenerator ()
References m_minRiseSize, m_minRunSize, and m_strokeWidthIncrement.
~GroundPlaneGenerator()
GroundPlaneGenerator::~GroundPlaneGenerator ()
Member Function Documentation
calcArea()
double GroundPlaneGenerator::calcArea (QPolygon & poly) protected
collectBorderPoints()
bool GroundPlaneGenerator::collectBorderPoints (QImage & image, QList< QPoint > & points) protected
References DebugDialog::debug(), and try8().
generateGroundPlane()
bool GroundPlaneGenerator::generateGroundPlane (const QString & boardSvg, QSizeF boardImageSize, const QString & svg, QSizeF copperImageSize, QStringList & exceptions, QGraphicsItem * board, double res, const QString & color, double keepoutMils)
References GPGParams::board, GPGParams::boardImageSize, GPGParams::boardSvg, GPGParams::color, GPGParams::copperImageSize, GPGParams::exceptions, generateGroundPlaneFn(), GPGParams::keepoutMils, ProcessEventBlocker::processEvents(), GPGParams::res, and GPGParams::svg.
generateGroundPlaneAux()
QImage * GroundPlaneGenerator::generateGroundPlaneAux (GPGParams & params, double & bWidth, double & bHeight, QList< QRectF > & rects) protected
References GPGParams::board, GPGParams::boardImageSize, GPGParams::boardSvg, BORDERINCHES, SvgFileSplitter::changeColors(), GPGParams::copperImageSize, DebugDialog::debug(), GraphicsUtils::drawBorder(), GPGParams::exceptions, DRC::extendBorder(), SvgFileSplitter::forceStrokeWidth(), FolderUtils::getTopLevelUserDataStorePath(), GraphicsUtils::InchesPerMeter, GPGParams::keepoutMils, postImageSignal(), qMax(), GPGParams::res, GPGParams::svg, and GraphicsUtils::SVGDPI.
generateGroundPlaneFn()
bool GroundPlaneGenerator::generateGroundPlaneFn (GPGParams & params) protected
References GPGParams::color, generateGroundPlaneAux(), makePolySvg(), GPGParams::res, scanImage(), GraphicsUtils::StandardFritzingDPI, and GraphicsUtils::SVGDPI.
generateGroundPlaneUnit()
bool GroundPlaneGenerator::generateGroundPlaneUnit (const QString & boardSvg, QSizeF boardImageSize, const QString & svg, QSizeF copperImageSize, QStringList & exceptions, QGraphicsItem * board, double res, const QString & color, QPointF whereToStart, double keepoutMils)
References GPGParams::board, GPGParams::boardImageSize, GPGParams::boardSvg, GPGParams::color, GPGParams::copperImageSize, GPGParams::exceptions, generateGroundPlaneAux(), FolderUtils::getTopLevelUserDataStorePath(), GPGParams::keepoutMils, OFFSET(), GPGParams::res, scanImage(), GraphicsUtils::StandardFritzingDPI, GPGParams::svg, and GraphicsUtils::SVGDPI.
getBoardRects()
bool GroundPlaneGenerator::getBoardRects (const QByteArray & boardByteArray, QGraphicsItem * board, double res, double keepoutSpace, QList< QRect > & rects)
References FolderUtils::getTopLevelUserDataStorePath(), GraphicsUtils::InchesPerMeter, scanLines(), and GraphicsUtils::SVGDPI.
joinScanLines()
void GroundPlaneGenerator::joinScanLines (QList< QRect > & rects, QList< QPolygon > & polygons) protected
References reldif.
layerName()
const QString & GroundPlaneGenerator::layerName ()
References m_layerName.
makeConnector()
void GroundPlaneGenerator::makeConnector (QList< QPolygon > & polygons, double res, double pixelFactor, const QString & colorString, int minX, int minY, QString & svg) protected
References calcArea(), ConnectorName, GraphicsUtils::distanceFromLine(), makeOnePoly(), and FSvgRenderer::NonConnectorName.
makeOnePoly()
QString GroundPlaneGenerator::makeOnePoly (const QPolygon & poly, const QString & colorString, const QString & id, int minX, int minY) protected
makePolySvg() [1/2]
QString GroundPlaneGenerator::makePolySvg (QList< QPolygon > & polygons, double res, double bWidth, double bHeight, double pixelFactor, const QString & colorString, bool makeConnectorFlag, QPointF * offset, QSizeF minAreaInches, double minDimensionInches, QPointF polygonOffset) protected
References m_layerName, makeConnector(), makeOnePoly(), and reldif.
makePolySvg() [2/2]
void GroundPlaneGenerator::makePolySvg (QList< QPolygon > & polygons, double res, double bWidth, double bHeight, double pixelFactor, const QString & colorString, bool makeConnectorFlag, bool makeOffset, QSizeF minAreaInches, double minDimensionInches, QPointF polygonOffset) protected
References m_newOffsets, m_newSVGs, makePolySvg(), and GraphicsUtils::SVGDPI.
mergeSVGs()
QString GroundPlaneGenerator::mergeSVGs (const QString & initialSVG, const QString & layerName)
References layerName(), m_newSVGs, TextUtils::mergeSvg(), and TextUtils::mergeSvgFinish().
newOffsets()
const QList< QPointF > & GroundPlaneGenerator::newOffsets ()
References m_newOffsets.
newSVGs()
const QStringList & GroundPlaneGenerator::newSVGs ()
References m_newSVGs.
postImageSignal
void GroundPlaneGenerator::postImageSignal (GroundPlaneGenerator * , QImage * copperImage, QImage * boardImage, QGraphicsItem * board, QList< QRectF > *) signal
scanImage()
void GroundPlaneGenerator::scanImage (QImage & image, double bWidth, double bHeight, double pixelFactor, double res, const QString & colorString, bool makeConnector, bool makeOffset, QSizeF minAreaInches, double minDimensionInches, QPointF offsetPolygons)
References joinScanLines(), makePolySvg(), scanLines(), and splitScanLines().
scanLines()
void GroundPlaneGenerator::scanLines (QImage & image, int bWidth, int bHeight, QList< QRect > & rects)
References m_minRiseSize, and m_minRunSize.
scanOutline()
void GroundPlaneGenerator::scanOutline (QImage & image, double bWidth, double bHeight, double pixelFactor, double res, const QString & colorString, bool makeConnector, bool makeOffset, QSizeF minAreaInches, double minDimensionInches)
References collectBorderPoints(), DebugDialog::debug(), makePolySvg(), and removeRedundant().
setLayerName()
void GroundPlaneGenerator::setLayerName (const QString & layerName)
References layerName(), and m_layerName.
setMinRunSize()
void GroundPlaneGenerator::setMinRunSize (int minRunSize, int minRiseSize)
References m_minRiseSize, and m_minRunSize.
setStrokeWidthIncrement()
void GroundPlaneGenerator::setStrokeWidthIncrement (double swi)
References m_strokeWidthIncrement.
splitScanLines()
void GroundPlaneGenerator::splitScanLines (QList< QRect > & rects, QList< QList< int > * > & pieces) protected
References DebugDialog::debug(), and reldif.
try8()
bool GroundPlaneGenerator::try8 (int x, int y, QImage & image, QList< QPoint > & points) protected
References tryNextPoint().
tryNextPoint()
bool GroundPlaneGenerator::tryNextPoint (int x, int y, QImage & image, QList< QPoint > & points) protected
Member Data Documentation
ConnectorName
QString GroundPlaneGenerator::ConnectorName = "connector0pad" static
KeepoutDefaultMils
const double GroundPlaneGenerator::KeepoutDefaultMils = 10 static
KeepoutSettingName
const QString GroundPlaneGenerator::KeepoutSettingName static
m_blurBy
double GroundPlaneGenerator::m_blurBy protected
m_layerName
QString GroundPlaneGenerator::m_layerName protected
m_minRiseSize
int GroundPlaneGenerator::m_minRiseSize protected
m_minRunSize
int GroundPlaneGenerator::m_minRunSize protected
m_newOffsets
QList<QPointF> GroundPlaneGenerator::m_newOffsets protected
m_newSVGs
QStringList GroundPlaneGenerator::m_newSVGs protected
m_strokeWidthIncrement
double GroundPlaneGenerator::m_strokeWidthIncrement protected
The documentation for this class was generated from the following files:
svg/groundplanegenerator.h
svg/groundplanegenerator.cpp