Fritzing: SelectItemCommand Class Reference
SelectItemCommand Class Reference
#include <commands.h>
Public Types
enum SelectItemType { NormalSelect, NormalDeselect, SelectAll, DeselectAll }
Public Types inherited from BaseCommand
enum CrossViewType { SingleView, CrossView }
Public Member Functions
SelectItemCommand (class SketchWidget *sketchWidget, SelectItemType type, QUndoCommand *parent)
void addRedo (long id)
void addUndo (long id)
void clearRedo ()
void copyRedo (SelectItemCommand *sother)
void copyUndo (SelectItemCommand *sother)
int id () const
bool mergeWith (const QUndoCommand *other)
void redo ()
void setSelectItemType (SelectItemType)
void setUpdated (bool)
void undo ()
bool updated ()
Public Member Functions inherited from BaseCommand
BaseCommand (BaseCommand::CrossViewType, SketchWidget *, QUndoCommand *parent)
~BaseCommand ()
void addSubCommand (BaseCommand *subCommand)
BaseCommand::CrossViewType crossViewType () const noexcept
virtual QString getDebugString () const
int index () const
const QUndoCommand * parentCommand () const
void redo ()
void setCrossViewType (BaseCommand::CrossViewType)
void setRedoOnly ()
void setSkipFirstRedo ()
void setUndoOnly ()
SketchWidget * sketchWidget () const
const BaseCommand * subCommand (int index) const
int subCommandCount () const
void subRedo ()
void subRedo (int index)
void subUndo ()
void subUndo (int index)
void undo ()
Protected Member Functions
QString getParamString () const
void selectAllFromStack (QList< long > &stack, bool select, bool updateInfoView)
Protected Attributes
QList< long > m_redoIDs
SelectItemType m_type
QList< long > m_undoIDs
bool m_updated
Protected Attributes inherited from BaseCommand
QList< BaseCommand * > m_commands
BaseCommand::CrossViewType m_crossViewType
int m_index = 0
QUndoCommand * m_parentCommand = nullptr
bool m_redoOnly = false
SketchWidget * m_sketchWidget = nullptr
bool m_skipFirstRedo = false
bool m_undoOnly = false
Static Protected Attributes
static int selectItemCommandID = 3
Static Protected Attributes inherited from BaseCommand
static CommandProgress m_commandProgress
static int nextIndex = 0
Additional Inherited Members
Static Public Member Functions inherited from BaseCommand
static void clearProgress ()
static CommandProgress * initProgress ()
static int totalChildCount (const QUndoCommand *)
Member Enumeration Documentation
SelectItemType
enum SelectItemCommand::SelectItemType
Enumerator
NormalSelect
NormalDeselect
SelectAll
DeselectAll
Constructor & Destructor Documentation
SelectItemCommand()
SelectItemCommand::SelectItemCommand (class SketchWidget * sketchWidget, SelectItemType type, QUndoCommand * parent)
Member Function Documentation
addRedo()
void SelectItemCommand::addRedo (long id)
References m_redoIDs, m_type, and NormalSelect.
addUndo()
void SelectItemCommand::addUndo (long id)
References m_undoIDs.
clearRedo()
void SelectItemCommand::clearRedo ()
References m_redoIDs.
copyRedo()
void SelectItemCommand::copyRedo (SelectItemCommand * sother)
References m_redoIDs.
copyUndo()
void SelectItemCommand::copyUndo (SelectItemCommand * sother)
References m_undoIDs.
getParamString()
QString SelectItemCommand::getParamString () const protected virtual
Reimplemented from BaseCommand.
References BaseCommand::getParamString(), and m_type.
id()
int SelectItemCommand::id () const
References selectItemCommandID.
mergeWith()
bool SelectItemCommand::mergeWith (const QUndoCommand * other)
References BaseCommand::crossViewType(), id(), and m_redoIDs.
redo()
void SelectItemCommand::redo ()
References BaseCommand::CrossView, DeselectAll, BaseCommand::m_crossViewType, m_redoIDs, BaseCommand::m_sketchWidget, m_type, NormalDeselect, NormalSelect, BaseCommand::redo(), SelectAll, selectAllFromStack(), and SketchWidget::selectAllItems().
selectAllFromStack()
void SelectItemCommand::selectAllFromStack (QList< long > & stack, bool select, bool updateInfoView) protected
References SketchWidget::clearSelection(), BaseCommand::CrossView, BaseCommand::m_crossViewType, BaseCommand::m_sketchWidget, and SketchWidget::selectItem().
setSelectItemType()
void SelectItemCommand::setSelectItemType (SelectItemType type)
References m_type.
setUpdated()
void SelectItemCommand::setUpdated (bool updated)
References m_updated, and updated().
undo()
void SelectItemCommand::undo ()
References m_undoIDs, selectAllFromStack(), and BaseCommand::undo().
updated()
bool SelectItemCommand::updated ()
References m_updated.
Member Data Documentation
m_redoIDs
QList<long> SelectItemCommand::m_redoIDs protected
m_type
SelectItemType SelectItemCommand::m_type protected
m_undoIDs
QList<long> SelectItemCommand::m_undoIDs protected
m_updated
bool SelectItemCommand::m_updated protected
selectItemCommandID
int SelectItemCommand::selectItemCommandID = 3 static protected
The documentation for this class was generated from the following files:
commands.h
commands.cpp