Fritzing: CommandProgress Class Reference
CommandProgress Class Reference
#include <commands.h>
Signals
void incRedo ()
void incUndo ()
Public Member Functions
CommandProgress ()=default
constexpr bool active () const noexcept
void emitRedo ()
void emitUndo ()
void setActive (bool)
Protected Attributes
bool m_active = false
Constructor & Destructor Documentation
CommandProgress()
CommandProgress::CommandProgress () default
Member Function Documentation
active()
constexpr bool CommandProgress::active () const inline noexcept
References m_active.
emitRedo()
void CommandProgress::emitRedo ()
References incRedo().
emitUndo()
void CommandProgress::emitUndo ()
References incUndo().
incRedo
void CommandProgress::incRedo () signal
incUndo
void CommandProgress::incUndo () signal
setActive()
void CommandProgress::setActive (bool active)
References active(), and m_active.
Member Data Documentation
m_active
bool CommandProgress::m_active = false protected
The documentation for this class was generated from the following files:
commands.h
commands.cpp