Fritzing: GraphUtils Class Reference
GraphUtils Class Reference
#include <graphutils.h>
Static Public Member Functions
static bool chooseRatsnestGraph (const QList< ConnectorItem * > *equipotentials, ViewGeometry::WireFlags, ConnectorPairHash &result)
static void minCut (QList< ConnectorItem * > &connectorItems, QList< class SketchWidget * > &foreighSketchWidgets, ConnectorItem *source, ConnectorItem *sink, QList< ConnectorEdge * > &cutSet)
static bool scoreOneNet (QList< ConnectorItem * > &partConnectorItems, ViewGeometry::WireFlags, RoutingStatus &routingStatus)
Static Protected Member Functions
static void collectBreadboard (ConnectorItem *connectorItem, QList< ConnectorItem * > &partConnectorItems, QList< ConnectorItem * > &ends)
Member Function Documentation
chooseRatsnestGraph()
bool GraphUtils::chooseRatsnestGraph (const QList< ConnectorItem * > * equipotentials, ViewGeometry::WireFlags flags, ConnectorPairHash & result) static
References NonConnectorItem::attachedTo(), ConnectorItem::bus(), ConnectorItem::collectEqualPotential(), DebugDialog::debug(), ConnectorItem::getCrossLayerConnectorItem(), int(), and ConnectorItem::sceneAdjustedTerminalPoint().
collectBreadboard()
void GraphUtils::collectBreadboard (ConnectorItem * connectorItem, QList< ConnectorItem * > & partConnectorItems, QList< ConnectorItem * > & ends) static protected
References NonConnectorItem::attachedTo(), ConnectorItem::bus(), ItemBase::busConnectorItems(), and ConnectorItem::connectedToItems().
minCut()
void GraphUtils::minCut (QList< ConnectorItem * > & connectorItems, QList< class SketchWidget * > & foreighSketchWidgets, ConnectorItem * source, ConnectorItem * sink, QList< ConnectorEdge * > & cutSet) static
References appendVertIf, NonConnectorItem::attachedTo(), NonConnectorItem::attachedToItemType(), ConnectorItem::bus(), ItemBase::busConnectorItems(), ConnectorEdge::c0, ConnectorEdge::c1, Wire::collectChained(), ConnectorItem::connectedToItems(), ConnectorItem::connectorType(), ConnectorItem::debugInfo(), Connector::Female, SketchWidget::findConnectorItem(), SketchWidget::findItem(), ConnectorItem::getCrossLayerConnectorItem(), ConnectorEdge::head, ItemBase::id(), ItemBase::isEverVisible(), LastVertex, makeConnectorEdge(), ConnectorEdge::setHeadTail(), ConnectorEdge::tail, ConnectorEdge::visible, ConnectorEdge::weight, ConnectorEdge::wire, and ModelPart::Wire.
scoreOneNet()
bool GraphUtils::scoreOneNet (QList< ConnectorItem * > & partConnectorItems, ViewGeometry::WireFlags myTrace, RoutingStatus & routingStatus) static
References add_edge_d, NonConnectorItem::attachedTo(), NonConnectorItem::attachedToItemType(), ModelPart::Breadboard, ConnectorItem::bus(), collectBreadboard(), Wire::collectChained(), ConnectorItem::connectedToItems(), ItemBase::getViewGeometry(), ConnectorItem::isCrossLayerConnectorItem(), ItemBase::isEverVisible(), ModelPart::Jumper, RoutingStatus::m_connectorsLeftToRoute, RoutingStatus::m_jumperItemCount, RoutingStatus::m_netCount, RoutingStatus::m_netRoutedCount, ModelPart::Symbol, ModelPart::Wire, and ViewGeometry::wireFlags().
The documentation for this class was generated from the following files:
utils/graphutils.h
utils/graphutils.cpp