Fritzing: FolderUtils Class Reference
FolderUtils Class Reference
#include <folderutils.h>
Static Public Member Functions
static void cleanup ()
static void collectFiles (const QDir &parent, QStringList &filters, QStringList &files, bool recursive)
static void copyBin (const QString &dest, const QString &source)
static bool createFolderAndCdIntoIt (QDir &dir, QString newFolder)
static bool createFZAndSaveTo (const QDir &dirToCompress, const QString &filename, const QStringList &skipSuffixes)
static void createUserDataStoreFolders ()
static bool createZipAndSaveTo (const QDir &dirToCompress, const QString &filename, const QStringList &skipSuffixes)
static QDir getApplicationSubFolder (QString)
static QString getApplicationSubFolderPath (QString)
static QDir getAppPartsSubFolder (QString)
static QString getAppPartsSubFolderPath (QString)
static const QString getLibraryPath ()
static QString getOpenFileName (QWidget *parent=0, const QString &caption=QString(), const QString &dir=QString(), const QString &filter=QString(), QString *selectedFilter=0, QFileDialog::Options options=0)
static QStringList getOpenFileNames (QWidget *parent=0, const QString &caption=QString(), const QString &dir=QString(), const QString &filter=QString(), QString *selectedFilter=0, QFileDialog::Options options=0)
static QString getSaveFileName (QWidget *parent=0, const QString &caption=QString(), const QString &dir=QString(), const QString &filter=QString(), QString *selectedFilter=0, QFileDialog::Options options=0)
static QString getTopLevelDocumentsPath ()
static QString getTopLevelUserDataStorePath ()
static QString getUserBinsPath ()
static QString getUserPartsPath ()
static bool isEmptyFileName (const QString &filename, const QString &unsavedFilename)
static void makePartFolderHierarchy (const QString &prefixFolder, const QString &destFolder)
static const QString openSaveFolder ()
static void replicateDir (QDir srcDir, QDir targDir)
static void rmdir (const QString &dirPath)
static void rmdir (QDir &dir)
static bool setApplicationPath (const QString &path)
static bool setAppPartsPath (const QString &path)
static void setOpenSaveFolder (const QString &path)
static void setOpenSaveFolderAux (const QString &path)
static void showInFolder (const QString &path)
static bool slamCopy (QFile &, const QString &dest)
static bool unzipTo (const QString &filepath, const QString &dirToDecompress, QString &error)
Protected Member Functions
FolderUtils ()
~FolderUtils ()
const QString applicationDirPath ()
QDir getAppPartsSubFolder2 (QString)
const QString libraryPath ()
bool setApplicationPath2 (const QString &path)
bool setPartsPath2 (const QString &path)
const QStringList & userDataStoreFolders ()
Protected Attributes
QString m_appPath
QStringList m_documentFolders
QString m_partsPath
QStringList m_userFolders
Static Protected Attributes
static QString m_openSaveFolder = ""
static FolderUtils * singleton = NULL
Constructor & Destructor Documentation
FolderUtils()
FolderUtils::FolderUtils () protected
References ___emptyString___, m_documentFolders, m_openSaveFolder, and m_userFolders.
~FolderUtils()
FolderUtils::~FolderUtils () protected
Member Function Documentation
applicationDirPath()
const QString FolderUtils::applicationDirPath () protected
References DebugDialog::debug(), and m_appPath.
cleanup()
void FolderUtils::cleanup () static
References singleton.
collectFiles()
void FolderUtils::collectFiles (const QDir & parent, QStringList & filters, QStringList & files, bool recursive) static
copyBin()
void FolderUtils::copyBin (const QString & dest, const QString & source) static
References DebugDialog::debug().
createFolderAndCdIntoIt()
bool FolderUtils::createFolderAndCdIntoIt (QDir & dir, QString newFolder) static
createFZAndSaveTo()
bool FolderUtils::createFZAndSaveTo (const QDir & dirToCompress, const QString & filename, const QStringList & skipSuffixes) static
References DebugDialog::debug(), and LockManager::LockedFileName.
createUserDataStoreFolders()
void FolderUtils::createUserDataStoreFolders () static
References FolderUtils(), getTopLevelDocumentsPath(), getTopLevelUserDataStorePath(), FMessageBox::information(), m_documentFolders, m_userFolders, replicateDir(), rmdir(), and singleton.
createZipAndSaveTo()
bool FolderUtils::createZipAndSaveTo (const QDir & dirToCompress, const QString & filename, const QStringList & skipSuffixes) static
References QuaZip::close(), QuaZipFile::close(), DebugDialog::debug(), TextUtils::getRandText(), QuaZip::getZipError(), QuaZipFile::getZipError(), LockManager::LockedFileName, QuaZip::mdCreate, QuaZip::open(), QuaZipFile::open(), slamCopy(), and UNZ_OK.
getApplicationSubFolder()
QDir FolderUtils::getApplicationSubFolder (QString search) static
References applicationDirPath(), DebugDialog::debug(), FolderUtils(), and singleton.
getApplicationSubFolderPath()
QString FolderUtils::getApplicationSubFolderPath (QString search) static
References FolderUtils(), getApplicationSubFolder(), and singleton.
getAppPartsSubFolder()
QDir FolderUtils::getAppPartsSubFolder (QString search) static
References FolderUtils(), getAppPartsSubFolder2(), and singleton.
getAppPartsSubFolder2()
QDir FolderUtils::getAppPartsSubFolder2 (QString search) protected
References getApplicationSubFolder(), and m_partsPath.
getAppPartsSubFolderPath()
QString FolderUtils::getAppPartsSubFolderPath (QString search) static
References FolderUtils(), getAppPartsSubFolder(), and singleton.
getLibraryPath()
const QString FolderUtils::getLibraryPath () static
References FolderUtils(), libraryPath(), and singleton.
getOpenFileName()
QString FolderUtils::getOpenFileName (QWidget * parent = 0, const QString & caption = QString(), const QString & dir = QString(), const QString & filter = QString(), QString * selectedFilter = 0, QFileDialog::Options options = 0) static
References setOpenSaveFolder().
getOpenFileNames()
QStringList FolderUtils::getOpenFileNames (QWidget * parent = 0, const QString & caption = QString(), const QString & dir = QString(), const QString & filter = QString(), QString * selectedFilter = 0, QFileDialog::Options options = 0) static
References setOpenSaveFolder().
getSaveFileName()
QString FolderUtils::getSaveFileName (QWidget * parent = 0, const QString & caption = QString(), const QString & dir = QString(), const QString & filter = QString(), QString * selectedFilter = 0, QFileDialog::Options options = 0) static
References setOpenSaveFolder().
getTopLevelDocumentsPath()
QString FolderUtils::getTopLevelDocumentsPath () static
getTopLevelUserDataStorePath()
QString FolderUtils::getTopLevelUserDataStorePath () static
getUserBinsPath()
QString FolderUtils::getUserBinsPath () static
References getTopLevelDocumentsPath().
getUserPartsPath()
QString FolderUtils::getUserPartsPath () static
References getTopLevelDocumentsPath().
isEmptyFileName()
bool FolderUtils::isEmptyFileName (const QString & filename, const QString & unsavedFilename) static
libraryPath()
const QString FolderUtils::libraryPath () protected
References applicationDirPath().
makePartFolderHierarchy()
void FolderUtils::makePartFolderHierarchy (const QString & prefixFolder, const QString & destFolder) static
openSaveFolder()
const QString FolderUtils::openSaveFolder () static
References getTopLevelDocumentsPath(), and m_openSaveFolder.
replicateDir()
void FolderUtils::replicateDir (QDir srcDir, QDir targDir) static
References DebugDialog::debug().
rmdir() [1/2]
void FolderUtils::rmdir (const QString & dirPath) static
rmdir() [2/2]
void FolderUtils::rmdir (QDir & dir) static
References rmdir().
setApplicationPath()
bool FolderUtils::setApplicationPath (const QString & path) static
References FolderUtils(), setApplicationPath2(), and singleton.
setApplicationPath2()
bool FolderUtils::setApplicationPath2 (const QString & path) protected
References m_appPath.
setAppPartsPath()
bool FolderUtils::setAppPartsPath (const QString & path) static
References FolderUtils(), setPartsPath2(), and singleton.
setOpenSaveFolder()
void FolderUtils::setOpenSaveFolder (const QString & path) static
References m_openSaveFolder, and setOpenSaveFolderAux().
setOpenSaveFolderAux()
void FolderUtils::setOpenSaveFolderAux (const QString & path) static
References m_openSaveFolder.
setPartsPath2()
bool FolderUtils::setPartsPath2 (const QString & path) protected
References m_partsPath.
showInFolder()
void FolderUtils::showInFolder (const QString & path) static
slamCopy()
bool FolderUtils::slamCopy (QFile & file, const QString & dest) static
unzipTo()
bool FolderUtils::unzipTo (const QString & filepath, const QString & dirToDecompress, QString & error) static
References QuaZipFile::atEnd(), BUFFERSIZE, QuaZip::close(), QuaZipFile::close(), DebugDialog::debug(), QuaZipFile::getActualFileName(), QuaZip::getCurrentFileInfo(), QuaZip::getEntriesCount(), QuaZip::getZipError(), QuaZipFile::getZipError(), QuaZip::goToFirstFile(), QuaZip::goToNextFile(), QuaZip::mdUnzip, QuaZip::open(), QuaZipFile::open(), QuaZip::setFileNameCodec(), and UNZ_OK.
userDataStoreFolders()
const QStringList& FolderUtils::userDataStoreFolders () protected
Member Data Documentation
m_appPath
QString FolderUtils::m_appPath protected
m_documentFolders
QStringList FolderUtils::m_documentFolders protected
m_openSaveFolder
QString FolderUtils::m_openSaveFolder = "" static protected
m_partsPath
QString FolderUtils::m_partsPath protected
m_userFolders
QStringList FolderUtils::m_userFolders protected
singleton
FolderUtils * FolderUtils::singleton = NULL static protected
The documentation for this class was generated from the following files:
utils/folderutils.h
utils/folderutils.cpp