Fritzing: BaseCommand Class Reference
BaseCommand Class Reference
#include <commands.h>
Public Types
enum CrossViewType { SingleView, CrossView }
Public Member Functions
BaseCommand (BaseCommand::CrossViewType, SketchWidget *, QUndoCommand *parent)
~BaseCommand ()
void addSubCommand (BaseCommand *subCommand)
BaseCommand::CrossViewType crossViewType () const noexcept
virtual QString getDebugString () const
int index () const
const QUndoCommand * parentCommand () const
void redo ()
void setCrossViewType (BaseCommand::CrossViewType)
void setRedoOnly ()
void setSkipFirstRedo ()
void setUndoOnly ()
SketchWidget * sketchWidget () const
const BaseCommand * subCommand (int index) const
int subCommandCount () const
void subRedo ()
void subRedo (int index)
void subUndo ()
void subUndo (int index)
void undo ()
Static Public Member Functions
static void clearProgress ()
static CommandProgress * initProgress ()
static int totalChildCount (const QUndoCommand *)
Protected Member Functions
virtual QString getParamString () const
Protected Attributes
QList< BaseCommand * > m_commands
BaseCommand::CrossViewType m_crossViewType
int m_index = 0
QUndoCommand * m_parentCommand = nullptr
bool m_redoOnly = false
SketchWidget * m_sketchWidget = nullptr
bool m_skipFirstRedo = false
bool m_undoOnly = false
Static Protected Attributes
static CommandProgress m_commandProgress
static int nextIndex = 0
Member Enumeration Documentation
CrossViewType
enum BaseCommand::CrossViewType
Enumerator
SingleView
CrossView
Constructor & Destructor Documentation
BaseCommand()
BaseCommand::BaseCommand (BaseCommand::CrossViewType crossViewType, SketchWidget * sketchWidget, QUndoCommand * parent)
~BaseCommand()
BaseCommand::~BaseCommand ()
References m_commands.
Member Function Documentation
addSubCommand()
void BaseCommand::addSubCommand (BaseCommand * subCommand)
References m_commands, m_sketchWidget, subCommand(), SketchWidget::undoStack(), and WaitPushUndoStack::writeUndo().
clearProgress()
void BaseCommand::clearProgress () static
References m_commandProgress, and CommandProgress::setActive().
crossViewType()
BaseCommand::CrossViewType BaseCommand::crossViewType () const noexcept
References m_crossViewType.
getDebugString()
QString BaseCommand::getDebugString () const virtual
References getParamString().
getParamString()
QString BaseCommand::getParamString () const protected virtual
Reimplemented in PackItemsCommand, AddSubpartCommand, HidePartLayerCommand, WireExtrasCommand, GroundFillSeedCommand, RenamePinsCommand, SetDropOffsetCommand, ChangeBoardLayersCommand, LoadLogoImageCommand, ShowLabelCommand, ResizeJumperItemCommand, SetPropCommand, SetResistanceCommand, ResizeBoardCommand, ResizeNoteCommand, RotateFlipLabelCommand, ChangeNoteTextCommand, ChangeLabelTextCommand, IncLabelTextCommand, MoveLockCommand, MoveLabelCommand, ShowLabelFirstTimeCommand, RestoreLabelCommand, CleanUpRatsnestsCommand, CleanUpWiresCommand, RoutingStatusCommand, WireWidthChangeCommand, WireColorChangeCommand, CheckStickyCommand, ChangeZCommand, SelectItemCommand, ChangeLayerCommand, RotateLegCommand, ChangeLegBendpointCommand, ChangeLegCurveCommand, MoveLegBendpointCommand, ChangeLegCommand, ChangeWireCurveCommand, ChangeWireCommand, ChangeConnectionCommand, TransformItemCommand, FlipItemCommand, RotateItemCommand, MoveItemsCommand, ChangeSMDCommand, RemoveBusConnectorCommand, SimpleMoveItemCommand, MoveTerminalPointCommand, MoveItemCommand, DeleteItemCommand, RelocateConnectorSvgCommand, AddItemCommand, ChangeSvgCommand, AddDeleteItemCommand, ChangePropertiesCommand, ChangeTagsCommand, ChangeFzpCommand, ChangeConnectorMetadataCommand, ChangeMetadataCommand, and PEBaseCommand.
References m_crossViewType, m_sketchWidget, SingleView, and SketchWidget::viewName().
index()
int BaseCommand::index () const
References m_index.
initProgress()
CommandProgress * BaseCommand::initProgress () static
References m_commandProgress, and CommandProgress::setActive().
parentCommand()
const QUndoCommand * BaseCommand::parentCommand () const
References m_parentCommand.
redo()
void BaseCommand::redo ()
References CommandProgress::active(), CommandProgress::emitRedo(), and m_commandProgress.
setCrossViewType()
void BaseCommand::setCrossViewType (BaseCommand::CrossViewType crossViewType)
References crossViewType(), and m_crossViewType.
setRedoOnly()
void BaseCommand::setRedoOnly ()
References m_redoOnly.
setSkipFirstRedo()
void BaseCommand::setSkipFirstRedo ()
References m_skipFirstRedo.
setUndoOnly()
void BaseCommand::setUndoOnly ()
References m_undoOnly.
sketchWidget()
SketchWidget * BaseCommand::sketchWidget () const
References m_sketchWidget.
subCommand()
const BaseCommand * BaseCommand::subCommand (int index) const
References m_commands.
subCommandCount()
int BaseCommand::subCommandCount () const
References m_commands.
subRedo() [1/2]
void BaseCommand::subRedo ()
References m_commands, and redo().
subRedo() [2/2]
void BaseCommand::subRedo (int index)
References index(), and m_commands.
subUndo() [1/2]
void BaseCommand::subUndo ()
References m_commands.
subUndo() [2/2]
void BaseCommand::subUndo (int index)
References index(), and m_commands.
totalChildCount()
int BaseCommand::totalChildCount (const QUndoCommand * command) static
undo()
void BaseCommand::undo ()
References CommandProgress::active(), CommandProgress::emitUndo(), and m_commandProgress.
Member Data Documentation
m_commandProgress
CommandProgress BaseCommand::m_commandProgress static protected
m_commands
QList<BaseCommand *> BaseCommand::m_commands protected
m_crossViewType
BaseCommand::CrossViewType BaseCommand::m_crossViewType protected
m_index
int BaseCommand::m_index = 0 protected
m_parentCommand
QUndoCommand* BaseCommand::m_parentCommand = nullptr protected
m_redoOnly
bool BaseCommand::m_redoOnly = false protected
m_sketchWidget
SketchWidget* BaseCommand::m_sketchWidget = nullptr protected
m_skipFirstRedo
bool BaseCommand::m_skipFirstRedo = false protected
m_undoOnly
bool BaseCommand::m_undoOnly = false protected
nextIndex
int BaseCommand::nextIndex = 0 static protected
The documentation for this class was generated from the following files:
commands.h
commands.cpp