Fritzing: Board Class Reference
Board Class Reference
#include <resizableboard.h>
Public Member Functions
Board (ModelPart *, ViewLayer::ViewID, const ViewGeometry &viewGeometry, long id, QMenu *itemMenu, bool doLabel)
~Board ()
bool canFindConnectorsUnder ()
bool collectExtraInfo (QWidget *parent, const QString &family, const QString &prop, const QString &value, bool swappingEnabled, QString &returnProp, QString &returnValue, QWidget *&returnWidget, bool &hide)
QStringList collectValues (const QString &family, const QString &prop, QString &value)
PluralType isPlural ()
void paintHover (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
bool rotation45Allowed ()
bool stickyEnabled ()
Public Member Functions inherited from PaletteItem
PaletteItem (ModelPart *, ViewLayer::ViewID, const ViewGeometry &viewGeometry, long id, QMenu *itemMenu, bool doLabel)
~PaletteItem ()
void addLayerKin (class LayerKinPaletteItem *lkpi)
virtual bool changePinLabels (bool singleRow, bool sip)
void clearModelPart ()
bool collectFemaleConnectees (QSet< ItemBase * > &items)
void collectWireConnectees (QSet< class Wire * > &wires)
void flipItem (Qt::Orientations orientation)
QStringList getPinLabels (bool &hasLocal)
const QList< class ItemBase * > & layerKin ()
virtual void loadLayerKin (const LayerHash &viewLayers, ViewLayer::ViewLayerPlacement)
bool mousePressEventK (PaletteItemBase *originalItem, QGraphicsSceneMouseEvent *)
void moveItem (ViewGeometry &viewGeometry)
void removeLayerKin ()
void renamePins (const QStringList &labels, bool singleRow)
bool renderImage (ModelPart *modelPart, ViewLayer::ViewID viewID, const LayerHash &viewLayers, ViewLayer::ViewLayerID, bool doConnectors, QString &error)
void resetConnector (ItemBase *itemBase, SvgIdLayer *svgIdLayer)
void resetConnectors ()
void resetConnectors (ItemBase *otherLayer, FSvgRenderer *otherLayerRenderer)
void resetID ()
void resetImage (class InfoGraphicsView *)
void resetKinImage (ItemBase *layerKin, InfoGraphicsView *infoGraphicsView)
void resetLayerKin (const QString &svg)
void retransform (const QTransform &)
void rotateItem (double degrees, bool includeRatsnest)
void setHidden (bool hidden)
void setInactive (bool inactivate)
void setInstanceTitle (const QString &, bool initial)
void setItemPos (QPointF &pos)
void setTransforms ()
QStringList sipOrDipOrLabels (bool &hasLayout, bool &sip)
void slamZ (double z)
bool swap (ModelPart *newModelPart, const LayerHash &layerHash, bool reinit, class SwapCommand *)
void syncKinMoved (QPointF offset, QPointF loc)
void transformItem2 (const QMatrix &)
QTransform untransform ()
Public Member Functions inherited from PaletteItemBase
PaletteItemBase (ModelPart *, ViewLayer::ViewID, const ViewGeometry &viewGeometry, long id, QMenu *itemMenu)
bool acceptsMousePressConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
void blockItemSelectedChange (bool selected)
QRectF boundingRect () const
QRectF boundingRectWithoutLegs () const
virtual bool canEditPart ()
bool collectFemaleConnectees (QSet< ItemBase * > &items)
void collectWireConnectees (QSet< class Wire * > &wires)
void connectedMoved (ConnectorItem *from, ConnectorItem *to, QList< ConnectorItem * > &already)
void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
void cursorKeyEvent (Qt::KeyboardModifiers modifiers)
const QCursor * getCursor (Qt::KeyboardModifiers)
void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
void hoverMoveEvent (QGraphicsSceneHoverEvent *event)
QPainterPath hoverShape () const
bool itemMoved ()
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
virtual void mouseMoveEventK (PaletteItemBase *originalItem, QGraphicsSceneMouseEvent *event)
void mousePressConnectorEvent (class ConnectorItem *, QGraphicsSceneMouseEvent *)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
virtual void mouseReleaseEventK (PaletteItemBase *originalItem, QGraphicsSceneMouseEvent *event)
void moveItem (ViewGeometry &)
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
void paintSelected (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
QString retrieveSvg (ViewLayer::ViewLayerID, QHash< QString, QString > &svgHash, bool blackOnly, double dpi, double &factor)
void saveGeometry ()
virtual void saveInstanceLocation (QXmlStreamWriter &)
void setProp (const QString &prop, const QString &value)
virtual bool setUpImage (ModelPart *modelPart, const LayerHash &viewLayers, LayerAttributes &)
QPainterPath shape () const
QPointF syncMoved ()
bool syncSelected ()
Public Member Functions inherited from ItemBase
ItemBase (ModelPart *, ViewLayer::ViewID, const ViewGeometry &, long id, QMenu *itemMenu)
virtual ~ItemBase ()
virtual bool acceptsMouseDoubleClickConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual bool acceptsMouseMoveConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual bool acceptsMousePressLegEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual bool acceptsMouseReleaseConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
virtual void addedToScene (bool temporary)
virtual void addSticky (ItemBase *, bool stickem)
void addSubpart (ItemBase *)
virtual bool alreadySticking (ItemBase *itemBase)
ConnectorItem * anyConnectorItem ()
QRectF boundingRect () const
virtual void busConnectorItems (Bus *bus, ConnectorItem *, QList< ConnectorItem * > &items)
QList< Bus * > buses ()
const QList< ConnectorItem * > & cachedConnectorItems ()
const QList< ConnectorItem * > & cachedConnectorItemsConst () const
virtual void calcRotation (QTransform &rotation, QPointF center, ViewGeometry &)
bool canFlip (Qt::Orientations)
bool canFlipHorizontal ()
bool canFlipVertical ()
virtual void clearConnectorHover ()
void clearConnectorItemCache ()
void clearPartLabel ()
void collectConnectors (ConnectorPairHash &connectorHash, SkipCheckFunction)
void collectPropsMap (QString &family, QMap< QString, QString > &)
virtual void collectWireConnectees (QSet< Wire * > &wires)
virtual void connectionChange (ConnectorItem *onMe, ConnectorItem *onIt, bool connect)
virtual bool connectionIsAllowed (ConnectorItem *)
virtual void connectorHover (ConnectorItem *, ItemBase *, bool hovering)
const QString & constTitle () const
void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
void debugInfo (const QString &msg) const
void debugInfo2 (const QString &msg) const
virtual void doneLoading ()
void doRotateFlipPartLabel (double degrees, Qt::Orientations)
void ensureUniqueTitle (const QString &title, bool force)
QString family ()
const QString & filename ()
virtual bool filterMousePressConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
ConnectorItem * findConnectorItemWithSharedID (const QString &connectorID, ViewLayer::ViewLayerPlacement)
ConnectorItem * findConnectorItemWithSharedID (const QString &connectorID)
ItemBase * findSubpart (const QString &connectorID, ViewLayer::ViewLayerPlacement)
FSvgRenderer * fsvgRenderer () const
virtual void getConnectedColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
virtual void getEqualPotentialColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
virtual void getHoverColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
virtual QString getInspectorTitle ()
virtual void getNormalColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
QPixmap * getPixmap (QSize size)
void getPixmaps (QPixmap *&, QPixmap *&, QPixmap *&, bool swappingEnabled, QSize)
virtual QString getProperty (const QString &key)
bool getRatsnest ()
virtual void getUnconnectedColor (ConnectorItem *, QBrush &, QPen &, double &opacity, double &negativePenWidth, bool &negativeOffsetRect)
ViewGeometry & getViewGeometry ()
bool hasConnections ()
bool hasConnectors ()
virtual bool hasCustomSVG ()
bool hasNonConnectors ()
virtual bool hasPartLabel ()
virtual bool hasPartNumberProperty ()
bool hasRubberBandLeg () const
constexpr bool hidden () const noexcept
virtual void hoverEnterConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
void hoverEnterConnectorItem ()
void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
virtual void hoverLeaveConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
void hoverLeaveConnectorItem ()
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
virtual void hoverMoveConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
virtual void hoverUpdate ()
constexpr qint64 id () const noexcept
constexpr bool inactive () const noexcept
bool inHover ()
void initLayerAttributes (LayerAttributes &layerAttributes, ViewLayer::ViewID, ViewLayer::ViewLayerID, ViewLayer::ViewLayerPlacement, bool doConnectors, bool doCreateShape)
virtual bool inRotation ()
const QString & instanceTitle () const
virtual bool isBaseSticky ()
bool isEverVisible ()
bool isLocalSticky ()
bool isObsolete ()
bool isPartLabelVisible ()
virtual bool isSticky ()
virtual bool isSwappable ()
int itemType () const
void killRubberBandLeg ()
QString label ()
constexpr bool layerHidden () const noexcept
virtual ItemBase * layerKinChief ()
QString makePartLabelSvg (bool blackOnly, double dpi, double printerScale)
ModelPart * modelPart ()
ModelPartShared * modelPartShared ()
const QString & moduleID ()
virtual void mouseDoubleClickConnectorEvent (ConnectorItem *)
virtual void mouseMoveConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
void mousePressEvent (QGraphicsSceneMouseEvent *event)
virtual void mouseReleaseConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
bool moveLock ()
void movePartLabel (QPointF newPos, QPointF newOffset)
virtual ConnectorItem * newConnectorItem (Connector *connector)
virtual ConnectorItem * newConnectorItem (ItemBase *layerkin, Connector *connector)
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
PartLabel * partLabel ()
void partLabelMoved (QPointF oldPos, QPointF oldOffset, QPointF newPos, QPointF newOffset)
QRectF partLabelSceneBoundingRect ()
QPointF partLabelScenePos ()
void partLabelSetHidden (bool hide)
ViewLayer::ViewLayerID partLabelViewLayerID ()
void prepareGeometryChange ()
virtual QHash< QString, QString > prepareProps (ModelPart *, bool wantDebug, QStringList &keys)
QString prop (const QString &p)
bool reloadRenderer (const QString &svg, bool fastload)
void removeTooltip ()
bool resetRenderer (const QString &svg)
bool resetRenderer (const QString &svg, QString &newSvg)
void resetValues (const QString &family, const QString &prop)
void restorePartLabel (QDomElement &labelGeometry, ViewLayer::ViewLayerID)
ConnectorItem * rightClickedConnector ()
void rotateFlipPartLabel (double degrees, Qt::Orientations)
virtual bool rotationAllowed ()
virtual void saveInstance (QXmlStreamWriter &)
bool sceneEvent (QEvent *event)
const QPainterPath & selectionShape ()
virtual void setAcceptsMousePressLegEvent (bool)
void setCanFlipHorizontal (bool)
void setCanFlipVertical (bool)
virtual void setDropOffset (QPointF offset)
void setEverVisible (bool)
void setFilename (const QString &)
virtual void setInRotation (bool)
virtual void setInspectorTitle (const QString &oldText, const QString &newText)
void setItemIsSelectable (bool selectable)
virtual void setLayerHidden (bool hidden)
void setLocalSticky (bool)
void setModelPart (ModelPart *)
virtual void setMoveLock (bool)
void setSharedRendererEx (FSvgRenderer *)
void setSquashShape (bool)
virtual void setSticky (bool)
void setSuperpart (ItemBase *)
virtual void setSwappable (bool)
void setTooltip ()
virtual void setTransform2 (const QTransform &)
FSvgRenderer * setUpImage (ModelPart *modelPart, LayerAttributes &)
void setViewLayerID (ViewLayer::ViewLayerID, const LayerHash &viewLayers)
void setViewLayerID (const QString &layerName, const LayerHash &viewLayers)
void setViewLayerPlacement (ViewLayer::ViewLayerPlacement)
void showConnectors (const QStringList &)
constexpr QSizeF size () const noexcept
const QString & spice () const
const QString & spiceModel () const
virtual ItemBase * stickingTo ()
virtual QList< QPointer< ItemBase > > stickyList ()
const QList< QPointer< ItemBase > > & subparts ()
ItemBase * superpart ()
virtual const QString & title ()
bool topLevel ()
virtual void transformItem (const QTransform &, bool includeRatsnest)
void updateConnections (ConnectorItem *, bool includeRatsnest, QList< ConnectorItem * > &already)
void updateConnectionsAux (bool includeRatsnest, QList< ConnectorItem * > &already)
void updateConnectors ()
void updatePartLabelInstanceTitle ()
virtual void updateTooltip ()
ViewLayer::ViewID viewID ()
QString & viewIDName ()
ViewLayer::ViewLayerID viewLayerID () const
ViewLayer::ViewLayerPlacement viewLayerPlacement () const
ViewGeometry::WireFlags wireFlags () const
virtual void writeGeometry (QXmlStreamWriter &)
virtual void writeXml (QXmlStreamWriter &)
double z ()
Static Public Member Functions
static QString convertFromXmlName (const QString &)
static QString convertToXmlName (const QString &)
static bool isBoard (ItemBase *)
static bool isBoard (ModelPart *)
Static Public Member Functions inherited from PaletteItem
static bool changeDiameter (HoleSettings &holeSettings, QObject *sender)
static bool changeThickness (HoleSettings &holeSettings, QObject *sender)
static QString changeUnits (HoleSettings &)
static QWidget * createHoleSettings (QWidget *parent, HoleSettings &, bool swappingEnabled, const QString &currentHoleSize, bool advanced)
static QString genFZP (const QString &moduleid, const QString &templateName, int minPins, int maxPins, int steps, bool smd)
static void initHoleSettings (HoleSettings &holeSettings, HoleClassThing *)
static bool setHoleSize (QString &holeSize, bool force, HoleSettings &holeSettings)
static void updateEditTexts (HoleSettings &)
static void updateSizes (HoleSettings &)
static void updateValidators (HoleSettings &)
Static Public Member Functions inherited from ItemBase
static void cleanup ()
static QColor connectedColor ()
static ItemBase * extractTopLevelItemBase (QGraphicsItem *thing)
static qint64 getNextID ()
static qint64 getNextID (qint64 fromIndex)
static void initNames ()
static void renderOne (QDomDocument *, QImage *, const QRectF &renderRect)
static void setConnectedColor (QColor &)
static void setReferenceModel (ReferenceModel *)
static void setUnconnectedColor (QColor &)
static QColor standardConnectedColor ()
static QColor standardUnconnectedColor ()
static QString translatePropertyName (const QString &key)
static QColor unconnectedColor ()
static bool zLessThan (ItemBase *&p1, ItemBase *&p2)
Static Public Attributes
static QString OneLayerTranslated
static QString TwoLayersTranslated
Static Public Attributes inherited from PaletteItem
static const QString HoleSizePrefix
Static Public Attributes inherited from ItemBase
static const QColor ConnectorHoverColor
static const double ConnectorHoverOpacity = .40
static const QList< ItemBase * > EmptyList
static const QColor HoverColor
static const double HoverOpacity = .20
static const QString ITEMBASE_FONT_PREFIX = "<font size='2'>"
static const QString ITEMBASE_FONT_SUFFIX = "</font>"
static QString PartInstanceDefaultTitle
static QHash< QString, QString > TranslatedPropertyNames
Protected Slots
void fileNameEntry (const QString &filename)
void prepLoadImage ()
Protected Slots inherited from PaletteItem
void changeDiameter ()
virtual void changeHoleSize (const QString &)
void changeThickness ()
virtual void changeUnits (bool)
void openPinLabelDialog ()
Protected Slots inherited from PaletteItemBase
void partPropertyEntry ()
Protected Member Functions
bool canLoad (const QString &fileName, const QString &reason)
virtual bool checkImage (const QString &filename)
virtual QStringList & getImageNames ()
virtual QStringList & getNewImageNames ()
virtual void prepLoadImageAux (const QString &fileName, bool addName)
void setFileNameItems ()
void setupLoadImage (QWidget *parent, const QString &family, const QString &prop, const QString &value, bool swappingEnabled, QString &returnProp, QString &returnValue, QWidget *&returnWidget)
void unableToLoad (const QString &fileName, const QString &reason)
ViewLayer::ViewID useViewIDForPixmap (ViewLayer::ViewID, bool swappingEnabled)
Protected Member Functions inherited from PaletteItem
QString appendHoleSize (const QString &moduleID, const QString &holeSize, const QString &ringThickness)
bool collectHoleSizeInfo (const QString &defaultHoleSizeValue, QWidget *parent, bool swappingEnabled, QString &returnProp, QString &returnValue, QWidget *&returnWidget)
void figureHover ()
void generateSwap (const QString &text, GenModuleID, GenFzp, GenSvg makeBreadboardSvg, GenSvg makeSchematicSvg, GenSvg makePcbSvg)
QString hackFzpHoleSize (const QString &moduleID, const QString &pcbFilename, const QString &holeSize)
QString hackSvgHoleSize (const QString &holeDiameter, const QString &ringThickness)
bool isSingleRow (const QList< ConnectorItem * > &connectorItems)
QVariant itemChange (GraphicsItemChange change, const QVariant &value)
bool makeLocalModifications (QByteArray &svg, const QString &filename)
void makeOneKin (qint64 &id, ViewLayer::ViewLayerID, ViewLayer::ViewLayerPlacement, ViewGeometry &, const LayerHash &)
void mousePressEvent (QGraphicsSceneMouseEvent *event)
void setUpHoleSizes (const QString &type, HoleClassThing &)
void setUpHoleSizesAux (HoleClassThing &, const QString &type)
QList< Connector * > sortConnectors ()
void syncKinSelection (bool selected, PaletteItemBase *originator)
void updateConnections (bool includeRatsnest, QList< ConnectorItem * > &already)
Protected Member Functions inherited from PaletteItemBase
virtual void cacheLoaded (const LayerAttributes &)
void checkFreeRotation (Qt::KeyboardModifiers modifiers, QPointF scenePos)
void findConnectorsUnder ()
virtual bool freeRotationAllowed (Qt::KeyboardModifiers modifiers)
bool freeRotationAllowed ()
bool inRotationLocation (QPointF scenePos, Qt::KeyboardModifiers modifiers, QPointF &returnPoint)
virtual LayerKinPaletteItem * newLayerKinPaletteItem (PaletteItemBase *chief, ModelPart *, const ViewGeometry &, long id, QMenu *itemMenu, const LayerHash &, LayerAttributes &)
virtual void setInitialTransform (const QTransform &)
void setUpConnectors (FSvgRenderer *, bool ignoreTerminalPoints)
Protected Member Functions inherited from ItemBase
void createShape (LayerAttributes &layerAttributes)
QPixmap * getPixmap (ViewLayer::ViewID, bool swappingEnabled, QSize size)
QVariant itemChange (QGraphicsItem::GraphicsItemChange change, const QVariant &value)
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
virtual void paintBody (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
virtual void paintHover (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget, const QPainterPath &shape)
void saveLocAndTransform (QXmlStreamWriter &streamWriter)
virtual void setDefaultTooltip ()
void setInstanceTitleAux (const QString &title, bool initial)
void setInstanceTitleTooltip (const QString &text)
void updateHidden ()
Static Protected Member Functions
static void moreCheckImage (const QString &filename)
static QString setBoardOutline (const QString &svg)
Static Protected Member Functions inherited from PaletteItem
static QStringList getSizes (QString &holeSize, HoleSettings &)
static QString hackFzpHoleSize (QDomDocument &document, const QString &newModuleID, const QString &pcbFilename, const QString &newSize)
static QString hackFzpHoleSize (const QString &fzp, const QString &moduleid, int hsix)
static QString hackSvgHoleSize (QDomDocument &domDocument, const QString &holeDiameter, const QString &ringThickness)
static QString hackSvgHoleSizeAux (const QString &svg, const QString &expectedFileName)
Static Protected Member Functions inherited from PaletteItemBase
static QString normalizeSvg (QString &svg, ViewLayer::ViewLayerID viewLayerID, bool blackOnly, double dpi, double &factor)
Static Protected Member Functions inherited from ItemBase
static bool fixCopper1 (ModelPart *modelPart, const QString &filename, ViewLayer::ViewLayerID viewLayerID, ViewLayer::ViewLayerPlacement, QDomDocument &)
static bool getFlipDoc (ModelPart *modelPart, const QString &filename, ViewLayer::ViewLayerID viewLayerID, ViewLayer::ViewLayerPlacement, QDomDocument &, Qt::Orientations)
Protected Attributes
QPointer< QComboBox > m_fileNameComboBox
bool m_svgOnly
Protected Attributes inherited from PaletteItem
int m_flipCount
HoleSettings m_holeSettings
QList< class ItemBase * > m_layerKin
Protected Attributes inherited from PaletteItemBase
bool m_blockItemSelectedChange
bool m_blockItemSelectedValue
QPointF m_offset
bool m_svg
QPointF m_syncMoved
bool m_syncSelected
Protected Attributes inherited from ItemBase
bool m_acceptsMousePressLegEvent = true
QList< ConnectorItem * > m_cachedConnectorItems
bool m_canFlipHorizontal = false
bool m_canFlipVertical = false
int m_connectorHoverCount = 0
int m_connectorHoverCount2 = 0
bool m_everVisible = true
QString m_filename
FSvgRenderer * m_fsvgRenderer = nullptr
bool m_hasRubberBandLeg = false
bool m_hidden = false
int m_hoverCount = 0
bool m_hoverEnterSpaceBarWasPressed = false
qint64 m_id = 0
bool m_inactive = false
bool m_inRotation = false
QMenu * m_itemMenu = nullptr
bool m_layerHidden = false
QPointer< ModelPart > m_modelPart
bool m_moveLock = false
QGraphicsSvgItem * m_moveLockItem = nullptr
QPointer< PartLabel > m_partLabel
QMap< QString, QString > m_propsMap
ConnectorItem * m_rightClickedConnector = nullptr
QPainterPath m_selectionShape
QSizeF m_size
bool m_spaceBarWasPressed = false
bool m_squashShape = false
bool m_sticky = false
QGraphicsSvgItem * m_stickyItem = nullptr
QHash< long, QPointer< ItemBase > > m_stickyList
QList< QPointer< ItemBase > > m_subparts
QPointer< ItemBase > m_superpart
bool m_swappable = true
ViewGeometry m_viewGeometry
ViewLayer::ViewID m_viewID
ViewLayer::ViewLayerID m_viewLayerID
ViewLayer::ViewLayerPlacement m_viewLayerPlacement
bool m_zUninitialized = true
Static Protected Attributes
static QStringList BoardImageNames
static QStringList NewBoardImageNames
Static Protected Attributes inherited from ItemBase
static QBrush ChosenBrush
static QPen ChosenPen
static QBrush ConnectedBrush
static QPen ConnectedPen
static QBrush EqualPotentialBrush
static QPen EqualPotentialPen
static QBrush HoverBrush
static QPen HoverPen
static long nextID
static QBrush NormalBrush
static constexpr double NormalConnectorOpacity = 0.4
static QPen NormalPen
static QPointer< ReferenceModel > TheReferenceModel = nullptr
static QBrush UnconnectedBrush
static QPen UnconnectedPen
Additional Inherited Members
Public Types inherited from ItemBase
enum PluralType { Singular, Plural, NotSure }
Public Slots inherited from ItemBase
void hidePartLabel ()
void partLabelChanged (const QString &newText)
void showInFolder ()
void showPartLabel (bool show, ViewLayer *)
virtual void swapEntry (const QString &text)
Signals inherited from PaletteItem
void pinLabelSwap (ItemBase *, const QString &moduleID)
Constructor & Destructor Documentation
Board()
Board::Board (ModelPart * modelPart, ViewLayer::ViewID viewID, const ViewGeometry & viewGeometry, long id, QMenu * itemMenu, bool doLabel)
References ModelPart::Board, isBoard(), ItemBase::itemType(), ModelPart::localProp(), m_fileNameComboBox, m_svgOnly, ItemBase::modelPart(), ModelPart::modelPartShared(), NamesToXmlNames, ModelPart::properties(), ModelPart::setLocalProp(), ModelPartShared::setProperty(), StandardCustomBoardExplanation, and XmlNamesToNames.
~Board()
Board::~Board ()
Member Function Documentation
canFindConnectorsUnder()
bool Board::canFindConnectorsUnder () virtual
Reimplemented from PaletteItemBase.
canLoad()
bool Board::canLoad (const QString & fileName, const QString & reason) protected
checkImage()
bool Board::checkImage (const QString & filename) protected virtual
Reimplemented in BoardLogoItem, and LogoItem.
References ViewLayer::Board, canLoad(), TextUtils::findElementsWithAttribute(), layers(), moreCheckImage(), ViewLayer::Silkscreen0, ViewLayer::Silkscreen1, StandardCustomBoardExplanation, unableToLoad(), ViewLayer::UnknownLayer, ItemBase::viewLayerID(), and ViewLayer::viewLayerIDFromXmlString().
collectExtraInfo()
bool Board::collectExtraInfo (QWidget * parent, const QString & family, const QString & prop, const QString & value, bool swappingEnabled, QString & returnProp, QString & returnValue, QWidget *& returnWidget, bool & hide) virtual
Reimplemented from PaletteItem.
Reimplemented in ResizableBoard, and SchematicFrame.
References PaletteItem::collectExtraInfo(), ItemBase::family(), isBoard(), ItemBase::prop(), and setupLoadImage().
collectValues()
QStringList Board::collectValues (const QString & family, const QString & prop, QString & value) virtual
Reimplemented from PaletteItem.
Reimplemented in ResizableBoard.
References ModuleIDNames::BoardLogoImageModuleIDName, PaletteItem::collectValues(), ItemBase::family(), isBoard(), ModelPart::localProp(), ItemBase::modelPart(), ItemBase::moduleID(), OneLayerTranslated, ItemBase::prop(), and TwoLayersTranslated.
convertFromXmlName()
QString Board::convertFromXmlName (const QString & xmlName) static
References ItemBase::TranslatedPropertyNames, and XmlNamesToNames.
convertToXmlName()
QString Board::convertToXmlName (const QString & name) static
References NamesToXmlNames, and ItemBase::TranslatedPropertyNames.
fileNameEntry
void Board::fileNameEntry (const QString & filename) protected slot
References FolderUtils::getAppPartsSubFolderPath(), getImageNames(), and prepLoadImageAux().
getImageNames()
QStringList & Board::getImageNames () protected virtual
Reimplemented in BoardLogoItem, CopperLogoItem, and LogoItem.
References BoardImageNames.
getNewImageNames()
QStringList & Board::getNewImageNames () protected virtual
Reimplemented in BoardLogoItem, and LogoItem.
References NewBoardImageNames.
isBoard() [1/2]
bool Board::isBoard (ItemBase * itemBase) static
References ItemBase::modelPart().
isBoard() [2/2]
bool Board::isBoard (ModelPart * modelPart) static
References ModelPart::Board, ModelPart::family(), ModelPart::itemType(), ModelPart::Logo, ItemBase::modelPart(), and ModelPart::ResizableBoard.
isPlural()
ItemBase::PluralType Board::isPlural () virtual
Reimplemented from ItemBase.
Reimplemented in SchematicFrame.
References ItemBase::Plural.
moreCheckImage()
void Board::moreCheckImage (const QString & filename) static protected
References TextUtils::findElementWithAttribute(), GerberGenerator::MagicBoardOutlineID, MultipleZs(), and setBoardOutline().
paintHover()
void Board::paintHover (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) virtual
Reimplemented from PaletteItemBase.
References ItemBase::HoverColor, and PaletteItemBase::hoverShape().
prepLoadImage
void Board::prepLoadImage () protected slot
References checkImage(), FolderUtils::getOpenFileName(), m_svgOnly, and prepLoadImageAux().
prepLoadImageAux()
void Board::prepLoadImageAux (const QString & fileName, bool addName) protected virtual
Reimplemented in LogoItem.
References InfoGraphicsView::getInfoGraphicsView(), and InfoGraphicsView::loadLogoImage().
rotation45Allowed()
bool Board::rotation45Allowed () virtual
Reimplemented from ItemBase.
Reimplemented in SchematicFrame.
setBoardOutline()
QString Board::setBoardOutline (const QString & svg) static protected
References TextUtils::collectLeaves(), TextUtils::findElementWithAttribute(), GerberGenerator::MagicBoardOutlineID, and TextUtils::removeXMLEntities().
setFileNameItems()
void Board::setFileNameItems () protected
References getImageNames(), getNewImageNames(), m_fileNameComboBox, and ItemBase::prop().
setupLoadImage()
void Board::setupLoadImage (QWidget * parent, const QString & family, const QString & prop, const QString & value, bool swappingEnabled, QString & returnProp, QString & returnValue, QWidget *& returnWidget) protected
References ItemBase::family(), fileNameEntry(), m_fileNameComboBox, prepLoadImage(), ItemBase::prop(), and setFileNameItems().
stickyEnabled()
bool Board::stickyEnabled () virtual
Reimplemented from ItemBase.
Reimplemented in SchematicFrame.
unableToLoad()
void Board::unableToLoad (const QString & fileName, const QString & reason) protected
useViewIDForPixmap()
ViewLayer::ViewID Board::useViewIDForPixmap (ViewLayer::ViewID vid, bool swappingEnabled) protected virtual
Reimplemented from ItemBase.
Reimplemented in SchematicFrame.
References ViewLayer::IconView, ViewLayer::PCBView, and ViewLayer::UnknownView.
Member Data Documentation
BoardImageNames
QStringList Board::BoardImageNames static protected
m_fileNameComboBox
QPointer<QComboBox> Board::m_fileNameComboBox protected
m_svgOnly
bool Board::m_svgOnly protected
NewBoardImageNames
QStringList Board::NewBoardImageNames static protected
OneLayerTranslated
QString Board::OneLayerTranslated static
TwoLayersTranslated
QString Board::TwoLayersTranslated static
The documentation for this class was generated from the following files:
items/resizableboard.h
items/resizableboard.cpp