Fritzing: AddItemCommand Class Reference
AddItemCommand Class Reference
#include <commands.h>
Public Member Functions
AddItemCommand (class SketchWidget *sketchWidget, BaseCommand::CrossViewType, QString moduleID, ViewLayer::ViewLayerPlacement, ViewGeometry &, qint64 id, bool updateInfoView, long modelIndex, QUndoCommand *parent)
void addRestoreIndexesCommand (class RestoreIndexesCommand *)
void redo ()
void undo ()
Public Member Functions inherited from AddDeleteItemCommand
AddDeleteItemCommand (SketchWidget *sketchWidget, BaseCommand::CrossViewType, QString moduleID, ViewLayer::ViewLayerPlacement, ViewGeometry &, qint64 id, long modelIndex, QUndoCommand *parent)
SketchWidget * dropOrigin ()
long itemID () const
void setDropOrigin (SketchWidget *)
Public Member Functions inherited from BaseCommand
BaseCommand (BaseCommand::CrossViewType, SketchWidget *, QUndoCommand *parent)
~BaseCommand ()
void addSubCommand (BaseCommand *subCommand)
BaseCommand::CrossViewType crossViewType () const noexcept
virtual QString getDebugString () const
int index () const
const QUndoCommand * parentCommand () const
void redo ()
void setCrossViewType (BaseCommand::CrossViewType)
void setRedoOnly ()
void setSkipFirstRedo ()
void setUndoOnly ()
SketchWidget * sketchWidget () const
const BaseCommand * subCommand (int index) const
int subCommandCount () const
void subRedo ()
void subRedo (int index)
void subUndo ()
void subUndo (int index)
void undo ()
Protected Member Functions
QString getParamString () const
Protected Attributes
bool m_module = false
RestoreIndexesCommand * m_restoreIndexesCommand = nullptr
bool m_updateInfoView = false
Protected Attributes inherited from AddDeleteItemCommand
SketchWidget * m_dropOrigin
long m_itemID
long m_modelIndex
QString m_moduleID
ViewGeometry m_viewGeometry
ViewLayer::ViewLayerPlacement m_viewLayerPlacement
Protected Attributes inherited from BaseCommand
QList< BaseCommand * > m_commands
BaseCommand::CrossViewType m_crossViewType
int m_index = 0
QUndoCommand * m_parentCommand = nullptr
bool m_redoOnly = false
SketchWidget * m_sketchWidget = nullptr
bool m_skipFirstRedo = false
bool m_undoOnly = false
Additional Inherited Members
Public Types inherited from BaseCommand
enum CrossViewType { SingleView, CrossView }
Static Public Member Functions inherited from BaseCommand
static void clearProgress ()
static CommandProgress * initProgress ()
static int totalChildCount (const QUndoCommand *)
Static Protected Attributes inherited from BaseCommand
static CommandProgress m_commandProgress
static int nextIndex = 0
Constructor & Destructor Documentation
AddItemCommand()
AddItemCommand::AddItemCommand (class SketchWidget * sketchWidget, BaseCommand::CrossViewType crossViewType, QString moduleID, ViewLayer::ViewLayerPlacement viewLayerPlacement, ViewGeometry & viewGeometry, qint64 id, bool updateInfoView, long modelIndex, QUndoCommand * parent)
Member Function Documentation
addRestoreIndexesCommand()
void AddItemCommand::addRestoreIndexesCommand (class RestoreIndexesCommand *)
getParamString()
QString AddItemCommand::getParamString () const protected virtual
Reimplemented from AddDeleteItemCommand.
References AddDeleteItemCommand::getParamString(), ViewGeometry::line(), ViewGeometry::loc(), and AddDeleteItemCommand::m_viewGeometry.
redo()
void AddItemCommand::redo ()
References SketchWidget::addItem(), BaseCommand::m_crossViewType, AddDeleteItemCommand::m_itemID, AddDeleteItemCommand::m_modelIndex, AddDeleteItemCommand::m_moduleID, BaseCommand::m_sketchWidget, BaseCommand::m_skipFirstRedo, AddDeleteItemCommand::m_viewGeometry, AddDeleteItemCommand::m_viewLayerPlacement, and BaseCommand::redo().
undo()
void AddItemCommand::undo ()
References SketchWidget::deleteItem(), AddDeleteItemCommand::m_itemID, BaseCommand::m_sketchWidget, and BaseCommand::undo().
Member Data Documentation
m_module
bool AddItemCommand::m_module = false protected
m_restoreIndexesCommand
RestoreIndexesCommand* AddItemCommand::m_restoreIndexesCommand = nullptr protected
m_updateInfoView
bool AddItemCommand::m_updateInfoView = false protected
The documentation for this class was generated from the following files:
commands.h
commands.cpp