Fritzing: PcbXML Class Reference
PcbXML Class Reference
#include <pcbxml.h>
Public Member Functions
PcbXML (const QDomElement &pcbDocument)
QString getSvgFile ()
Private Member Functions
void drawElementArc (QDomNode node)
void drawElementLine (QDomNode node)
void drawMark (QDomNode node)
void drawNode (QDomNode node)
void drawPad (QDomNode node)
void drawPin (QDomNode node)
void minMax (int, int, int)
void shiftCoordinates ()
Private Attributes
QDomElement m_copper
QDomElement m_keepout
int m_markx
int m_marky
QDomElement m_mask
int m_maxx
int m_maxy
int m_minx
int m_miny
QDomElement m_outline
int m_padCount
int m_pinCount
QDomElement m_silkscreen
SVGDomDocument * m_svg
QString m_svgFile
QDomElement m_svgroot
QString m_units
Constructor & Destructor Documentation
PcbXML()
PcbXML::PcbXML (const QDomElement & pcbDocument)
References SVGDomDocument::createGroup(), DebugDialog::debug(), drawNode(), m_copper, m_keepout, m_markx, m_marky, m_mask, m_maxx, m_maxy, m_minx, m_miny, m_outline, m_padCount, m_pinCount, m_silkscreen, m_svg, m_svgFile, m_svgroot, m_units, SVGDomDocument::save(), SVGDomDocument::setHeight(), SVGDomDocument::setViewBox(), SVGDomDocument::setWidth(), and shiftCoordinates().
Member Function Documentation
drawElementArc()
void PcbXML::drawElementArc (QDomNode node) private
References m_markx, and m_marky.
drawElementLine()
void PcbXML::drawElementLine (QDomNode node) private
References m_markx, m_marky, m_silkscreen, m_svg, and minMax().
drawMark()
void PcbXML::drawMark (QDomNode node) private
drawNode()
void PcbXML::drawNode (QDomNode node) private
References DebugDialog::debug(), drawElementArc(), drawElementLine(), drawMark(), drawPad(), and drawPin().
drawPad()
void PcbXML::drawPad (QDomNode node) private
References m_copper, m_markx, m_marky, m_padCount, m_svg, minMax(), qMax(), and qMin().
drawPin()
void PcbXML::drawPin (QDomNode node) private
References m_copper, m_markx, m_marky, m_pinCount, m_svg, and minMax().
getSvgFile()
QString PcbXML::getSvgFile ()
References m_svgFile.
minMax()
void PcbXML::minMax (int x, int y, int width) private
References m_maxx, m_maxy, m_minx, m_miny, qMax(), and qMin().
shiftCoordinates()
void PcbXML::shiftCoordinates () private
References m_minx, m_miny, and m_svgroot.
Member Data Documentation
m_copper
QDomElement PcbXML::m_copper private
m_keepout
QDomElement PcbXML::m_keepout private
m_markx
int PcbXML::m_markx private
m_marky
int PcbXML::m_marky private
m_mask
QDomElement PcbXML::m_mask private
m_maxx
int PcbXML::m_maxx private
m_maxy
int PcbXML::m_maxy private
m_minx
int PcbXML::m_minx private
m_miny
int PcbXML::m_miny private
m_outline
QDomElement PcbXML::m_outline private
m_padCount
int PcbXML::m_padCount private
m_pinCount
int PcbXML::m_pinCount private
m_silkscreen
QDomElement PcbXML::m_silkscreen private
m_svg
SVGDomDocument* PcbXML::m_svg private
m_svgFile
QString PcbXML::m_svgFile private
m_svgroot
QDomElement PcbXML::m_svgroot private
m_units
QString PcbXML::m_units private
The documentation for this class was generated from the following files:
partseditor/obsolete/pcbxml.h
partseditor/obsolete/pcbxml.cpp