Fritzing: VersionChecker Class Reference
VersionChecker Class Reference
#include <versionchecker.h>
Public Slots
void fetch ()
void finished (QNetworkReply *)
Signals
void httpError (QNetworkReply::NetworkError)
void releasesAvailable ()
void xmlError (QXmlStreamReader::Error errorCode)
Public Member Functions
VersionChecker ()
~VersionChecker ()
const QList< AvailableRelease * > & availableReleases ()
void ignore (const QString &version, bool interim)
void setUrl (const QString &url)
void stop ()
Protected Member Functions
void parseEntry ()
void parseXml ()
Protected Attributes
QList< AvailableRelease * > m_availableReleases
QString m_currentCategoryTerm
QString m_currentLinkHref
QString m_currentSummary
QString m_currentTitle
QString m_currentUpdated
int m_depth
VersionThing m_ignoreInterimVersion
VersionThing m_ignoreMainVersion
bool m_inEntry
bool m_inSummary
bool m_inTitle
bool m_inUpdated
QNetworkReply * m_networkReply
QMutex m_networkReplyLock
QString m_urlString
QString m_version
QXmlStreamReader m_xml
Constructor & Destructor Documentation
VersionChecker()
VersionChecker::VersionChecker ()
References m_depth, m_ignoreInterimVersion, m_ignoreMainVersion, m_inEntry, m_inSummary, m_inTitle, m_inUpdated, m_networkReply, and VersionThing::ok.
~VersionChecker()
VersionChecker::~VersionChecker ()
References m_availableReleases.
Member Function Documentation
availableReleases()
const QList< AvailableRelease * > & VersionChecker::availableReleases ()
References m_availableReleases.
fetch
void VersionChecker::fetch () slot
References DebugDialog::debug(), finished(), m_networkReply, m_networkReplyLock, m_urlString, and m_xml.
finished
void VersionChecker::finished (QNetworkReply * networkReply) slot
References DebugDialog::debug(), httpError(), m_networkReply, m_networkReplyLock, m_xml, parseXml(), and releasesAvailable().
httpError
void VersionChecker::httpError (QNetworkReply::NetworkError) signal
ignore()
void VersionChecker::ignore (const QString & version, bool interim)
References m_ignoreInterimVersion, m_ignoreMainVersion, and Version::toVersionThing().
parseEntry()
void VersionChecker::parseEntry () protected
References Version::candidateGreaterThanCurrent(), AvailableRelease::dateTime, Version::greaterThan(), AvailableRelease::interim, AvailableRelease::link, m_availableReleases, m_currentCategoryTerm, m_currentLinkHref, m_currentSummary, m_currentTitle, m_currentUpdated, m_ignoreInterimVersion, m_ignoreMainVersion, VersionThing::ok, AvailableRelease::summary, Version::toVersionThing(), and AvailableRelease::versionString.
parseXml()
void VersionChecker::parseXml () protected
References m_currentCategoryTerm, m_currentLinkHref, m_currentSummary, m_currentTitle, m_currentUpdated, m_depth, m_inEntry, m_inSummary, m_inTitle, m_inUpdated, m_xml, parseEntry(), and xmlError().
releasesAvailable
void VersionChecker::releasesAvailable () signal
setUrl()
void VersionChecker::setUrl (const QString & url)
References m_urlString.
stop()
void VersionChecker::stop ()
References m_networkReply, and m_networkReplyLock.
xmlError
void VersionChecker::xmlError (QXmlStreamReader::Error errorCode) signal
Member Data Documentation
m_availableReleases
QList<AvailableRelease *> VersionChecker::m_availableReleases protected
m_currentCategoryTerm
QString VersionChecker::m_currentCategoryTerm protected
m_currentLinkHref
QString VersionChecker::m_currentLinkHref protected
m_currentSummary
QString VersionChecker::m_currentSummary protected
m_currentTitle
QString VersionChecker::m_currentTitle protected
m_currentUpdated
QString VersionChecker::m_currentUpdated protected
m_depth
int VersionChecker::m_depth protected
m_ignoreInterimVersion
VersionThing VersionChecker::m_ignoreInterimVersion protected
m_ignoreMainVersion
VersionThing VersionChecker::m_ignoreMainVersion protected
m_inEntry
bool VersionChecker::m_inEntry protected
m_inSummary
bool VersionChecker::m_inSummary protected
m_inTitle
bool VersionChecker::m_inTitle protected
m_inUpdated
bool VersionChecker::m_inUpdated protected
m_networkReply
QNetworkReply* VersionChecker::m_networkReply protected
m_networkReplyLock
QMutex VersionChecker::m_networkReplyLock protected
m_urlString
QString VersionChecker::m_urlString protected
m_version
QString VersionChecker::m_version protected
m_xml
QXmlStreamReader VersionChecker::m_xml protected
The documentation for this class was generated from the following files:
version/versionchecker.h
version/versionchecker.cpp