Fritzing: autoroute/panelizer.cpp File Reference
panelizer.cpp File Reference
#include "panelizer.h"
#include "../debugdialog.h"
#include "../sketch/pcbsketchwidget.h"
#include "../utils/textutils.h"
#include "../utils/graphicsutils.h"
#include "../utils/folderutils.h"
#include "../items/resizableboard.h"
#include "../items/logoitem.h"
#include "../items/groundplane.h"
#include "../fsvgrenderer.h"
#include "../fapplication.h"
#include "../svg/gerbergenerator.h"
#include "../referencemodel/referencemodel.h"
#include "../version/version.h"
#include "../processeventblocker.h"
#include "../connectors/connectoritem.h"
#include "../connectors/svgidlayer.h"
#include "cmrouter/tileutils.h"
#include <QFile>
#include <QDomDocument>
#include <QDomElement>
#include <QDir>
#include <qmath.h>
#include <limits>
#include <QPrinter>
Functions
int allObstacles (Tile *tile, UserData userData)
int allSpaces (Tile *tile, UserData userData)
bool areaGreaterThan (PanelItem *p1, PanelItem *p2)
bool byOptionalPriority (PanelItem *p1, PanelItem *p2)
void collectTexts (const QString &svg, QStringList &strings)
int roomAnywhere (Tile *tile, UserData userData)
int roomOn (Tile *tile, TileRect &tileRect, BestPlace *bestPlace)
int roomOnBottom (Tile *tile, UserData userData)
int roomOnLeft (Tile *tile, UserData userData)
int roomOnRight (Tile *tile, UserData userData)
int roomOnTop (Tile *tile, UserData userData)
Variables
static int OutlineLayer = 0
static QSet< QString > PanelizerFileNames
static QString PanelizerOutputPath
static int PlanePairIndex = 0
static int SilkTopLayer = 0
Function Documentation
allObstacles()
int allObstacles (Tile * tile, UserData userData)
References Tile::OBSTACLE, and TiGetType().
allSpaces()
int allSpaces (Tile * tile, UserData userData)
References Tile::SPACE, and TiGetType().
areaGreaterThan()
bool areaGreaterThan (PanelItem * p1, PanelItem * p2)
References PanelItem::boardSizeInches.
byOptionalPriority()
bool byOptionalPriority (PanelItem * p1, PanelItem * p2)
References PanelItem::optionalPriority.
collectTexts()
void collectTexts (const QString & svg, QStringList & strings)
roomAnywhere()
int roomAnywhere (Tile * tile, UserData userData)
References roomOn(), Tile::SPACE, TiGetType(), and TiToRect().
roomOn()
int roomOn (Tile * tile, TileRect & tileRect, BestPlace * bestPlace)
References allSpaces(), BestPlace::bestTile, BestPlace::height, BestPlace::plane, TiSrArea(), BestPlace::width, TileRect::xmaxi, TileRect::xmini, TileRect::ymaxi, and TileRect::ymini.
roomOnBottom()
int roomOnBottom (Tile * tile, UserData userData)
References BestPlace::maxRect, roomOn(), Tile::SPACE, TiGetType(), TiToRect(), and TileRect::ymaxi.
roomOnLeft()
int roomOnLeft (Tile * tile, UserData userData)
References BestPlace::maxRect, roomOn(), Tile::SPACE, TiGetType(), TiToRect(), and TileRect::xmini.
roomOnRight()
int roomOnRight (Tile * tile, UserData userData)
References BestPlace::maxRect, roomOn(), Tile::SPACE, TiGetType(), TiToRect(), and TileRect::xmaxi.
roomOnTop()
int roomOnTop (Tile * tile, UserData userData)
References BestPlace::maxRect, roomOn(), Tile::SPACE, TiGetType(), TiToRect(), and TileRect::ymini.
Variable Documentation
OutlineLayer
int OutlineLayer = 0 static
PanelizerFileNames
QSet<QString> PanelizerFileNames static
PanelizerOutputPath
QString PanelizerOutputPath static
PlanePairIndex
int PlanePairIndex = 0 static
SilkTopLayer
int SilkTopLayer = 0 static