Fritzing: utils/textutils.cpp File Reference
textutils.cpp File Reference
#include <QTextDocument>
#include <QTextStream>
#include "textutils.h"
#include "misc.h"
#include "../installedfonts.h"
#include <QRegExp>
#include <QBuffer>
#include <QFile>
#include <QSettings>
#include <QUrl>
#include <QUuid>
#include <QCryptographicHash>
#include <QDebug>
#include <qmath.h>
#include <qnumeric.h>
Classes
struct MatchThing
Typedefs
typedef QHash< QString, QString > FixedFontsHash
Functions
FixedFontsHash fixFontsMapping (const QSet< QString > fontsTofix, const QString &destFont)
bool fixUnavailableFontFamilies (QString &fileContent, const QString &destFont)
QSet< QString > getAttrFontFamilies (const QString &fileContent)
QSet< QString > getFontFamiliesInsideStyleTag (const QString &fileContent)
static const QRegExp HexExpr ("&#x[0-9a-fA-F];")
QString makeDashString (bool dashed, const QVector< qreal > &pattern, double dpi, double printerScale)
static const QRegExp SodipodiAttributeDetector ("(inkscape|sodipodi):[^=\\s]+=\"([^\"\\\\]*(\\\\.[^\"\\\\]*)*)\"")
static const QRegExp SodipodiElementDetector ("</{0,1}(inkscape|sodipodi):[^>]+>")
static const QRegExp Xmlns ("xmlns=([\"|'])[^\"']*\\1")
Variables
static const QString fontFamilyQuotesPattern = R"x(font-family(?:="|:)('[^']*')"?)x"
QList< QString > PowerPrefixes
QList< double > PowerPrefixValues
Typedef Documentation
FixedFontsHash
typedef QHash<QString , QString > FixedFontsHash
Function Documentation
fixFontsMapping()
FixedFontsHash fixFontsMapping (const QSet< QString > fontsTofix, const QString & destFont)
References InstalledFonts::InstalledFontsList, and InstalledFonts::InstalledFontsNameMapper.
fixUnavailableFontFamilies()
bool fixUnavailableFontFamilies (QString & fileContent, const QString & destFont)
References fixFontsMapping(), getAttrFontFamilies(), and getFontFamiliesInsideStyleTag().
getAttrFontFamilies()
QSet<QString> getAttrFontFamilies (const QString & fileContent)
References TextUtils::getRegexpCaptures().
getFontFamiliesInsideStyleTag()
QSet<QString> getFontFamiliesInsideStyleTag (const QString & fileContent)
References TextUtils::getRegexpCaptures().
HexExpr()
static const QRegExp HexExpr ("&#x;" [0-9a-fA-F]) static
makeDashString()
QString makeDashString (bool dashed, const QVector< qreal > & pattern, double dpi, double printerScale)
SodipodiAttributeDetector()
static const QRegExp SodipodiAttributeDetector ("(inkscape|sodipodi):+ [^=\\s] = \"([^\"\\\\]*(\\\\.[^\"\\\\]*)*)\"") static
SodipodiElementDetector()
static const QRegExp SodipodiElementDetector ("</{0,1}(inkscape|sodipodi):[^>]+ , ") static
Xmlns()
static const QRegExp Xmlns (" xmlns = ([\"|'])[^\"']*\\1") static
Variable Documentation
fontFamilyQuotesPattern
const QString fontFamilyQuotesPattern = R"x(font-family(?:="|:)('[^']*')"?)x" static
PowerPrefixes
QList<QString> PowerPrefixes
PowerPrefixValues
QList<double> PowerPrefixValues