Fritzing: WelcomeView Class Reference
WelcomeView Class Reference
#include <welcomeview.h>
Signals
void newSketch ()
void openSketch ()
void recentSketch (const QString &filename, const QString &actionText)
Public Member Functions
WelcomeView (QWidget *parent=0)
~WelcomeView ()=default
void dragEnterEvent (QDragEnterEvent *event)
void showEvent (QShowEvent *event)
void updateRecent ()
Protected Slots
void blogItemClicked (QListWidgetItem *)
void clickBlog (const QString &)
void clickRecent (const QString &)
void gotBlogImage (QNetworkReply *)
void gotBlogSnippet (QNetworkReply *)
void nextTip ()
void recentItemClicked (QListWidgetItem *)
Protected Member Functions
BlogListWidget * createBlogContentFrame (const QString &url, const QString &urlText, const QString &logoPath, const QString &footerLabelColor)
QFrame * createHeaderFrame (const QString &url1, const QString &urlText1, const QString &url2, const QString &urlText2, const QString &inactiveColor, const QString &activeColor, QLabel *&label1, QLabel *&label2)
QWidget * createShopContentFrame (const QString &imagePath, const QString &headline, const QString &description, const QString &url, const QString &urlText, const QString &urlText2, const QString &logoPath, const QString &footerLabelColor)
void getNextBlogImage (int ix, bool blog)
QWidget * initBlog ()
void initLayout ()
QWidget * initRecent ()
QWidget * initShop ()
QWidget * initTip ()
QWidget * makeRecentItem (const QString &objectName, const QString &iconText, const QString &textText, QLabel *&icon, QLabel *&text)
void readBlog (const QDomDocument &, bool doEmit, bool blog, const QString &prefix)
void setBlogItemImage (QPixmap &, int index, bool blog)
Protected Attributes
QLabel * m_blogLabel = nullptr
BlogListWidget * m_blogListWidget = nullptr
QWidget * m_blogUberFrame = nullptr
QLabel * m_donateLabel = nullptr
QWidget * m_donateUberFrame = nullptr
QLabel * m_fabLabel = nullptr
QWidget * m_fabUberFrame = nullptr
BlogListWidget * m_projectListWidget = nullptr
QLabel * m_projectsLabel = nullptr
QWidget * m_projectsUberFrame = nullptr
QListWidget * m_recentListWidget = nullptr
QLabel * m_shopLabel = nullptr
QWidget * m_shopUberFrame = nullptr
QLabel * m_tip = nullptr
Static Protected Attributes
static QString m_activeHeaderLabelColor = "#333"
static QString m_inactiveHeaderLabelColor = "#b1b1b1"
Constructor & Destructor Documentation
WelcomeView()
WelcomeView::WelcomeView (QWidget * parent = 0)
References gotBlogSnippet(), initLayout(), TipsAndTricks::initTipSets(), newSketch(), nextTip(), openSketch(), and recentSketch().
~WelcomeView()
WelcomeView::~WelcomeView () default
Member Function Documentation
blogItemClicked
void WelcomeView::blogItemClicked (QListWidgetItem * item) protected slot
References RefRole.
clickBlog
void WelcomeView::clickBlog (const QString & url) protected slot
References hackColor(), m_activeHeaderLabelColor, m_blogLabel, m_blogUberFrame, m_donateLabel, m_donateUberFrame, m_fabLabel, m_fabUberFrame, m_inactiveHeaderLabelColor, m_projectsLabel, m_projectsUberFrame, and nextTip().
clickRecent
void WelcomeView::clickRecent (const QString & url) protected slot
References newSketch(), and openSketch().
createBlogContentFrame()
BlogListWidget * WelcomeView::createBlogContentFrame (const QString & url, const QString & urlText, const QString & logoPath, const QString & footerLabelColor) protected
References blogItemClicked(), clickBlog(), and zeroMargin().
createHeaderFrame()
QFrame * WelcomeView::createHeaderFrame (const QString & url1, const QString & urlText1, const QString & url2, const QString & urlText2, const QString & inactiveColor, const QString & activeColor, QLabel *& label1, QLabel *& label2) protected
References clickBlog(), makeUrlText(), and zeroMargin().
createShopContentFrame()
QWidget * WelcomeView::createShopContentFrame (const QString & imagePath, const QString & headline, const QString & description, const QString & url, const QString & urlText, const QString & urlText2, const QString & logoPath, const QString & footerLabelColor) protected
References clickBlog(), and zeroMargin().
dragEnterEvent()
void WelcomeView::dragEnterEvent (QDragEnterEvent * event)
References DebugDialog::debug().
getNextBlogImage()
void WelcomeView::getNextBlogImage (int ix, bool blog) protected
References gotBlogImage(), BlogListWidget::imageRequestList(), m_blogListWidget, and m_projectListWidget.
gotBlogImage
void WelcomeView::gotBlogImage (QNetworkReply * networkReply) protected slot
References getNextBlogImage(), ImageSpace, BaseCommand::index(), and setBlogItemImage().
gotBlogSnippet
void WelcomeView::gotBlogSnippet (QNetworkReply * networkReply) protected slot
References cleanData(), and readBlog().
initBlog()
QWidget * WelcomeView::initBlog () protected
References clickBlog(), createBlogContentFrame(), createHeaderFrame(), m_activeHeaderLabelColor, m_blogLabel, m_blogListWidget, m_blogUberFrame, m_inactiveHeaderLabelColor, m_projectListWidget, m_projectsLabel, m_projectsUberFrame, and zeroMargin().
initLayout()
void WelcomeView::initLayout () protected
References initBlog(), initRecent(), initShop(), and initTip().
initRecent()
QWidget * WelcomeView::initRecent () protected
References m_recentListWidget, makeRecentItem(), recentItemClicked(), and zeroMargin().
initShop()
QWidget * WelcomeView::initShop () protected
References clickBlog(), createHeaderFrame(), createShopContentFrame(), m_activeHeaderLabelColor, m_donateLabel, m_donateUberFrame, m_fabLabel, m_fabUberFrame, m_inactiveHeaderLabelColor, and zeroMargin().
initTip()
QWidget * WelcomeView::initTip () protected
References m_tip, nextTip(), and zeroMargin().
makeRecentItem()
QWidget * WelcomeView::makeRecentItem (const QString & objectName, const QString & iconText, const QString & textText, QLabel *& icon, QLabel *& text) protected
References clickRecent(), and zeroMargin().
newSketch
void WelcomeView::newSketch () signal
nextTip
void WelcomeView::nextTip () protected slot
References m_tip, and TipsAndTricks::randomTip().
openSketch
void WelcomeView::openSketch () signal
readBlog()
void WelcomeView::readBlog (const QDomDocument & doc, bool doEmit, bool blog, const QString & prefix) protected
References AuthorRole, DateRole, getNextBlogImage(), BlogListWidget::imageRequestList(), IntroRole, m_blogListWidget, m_projectListWidget, readBlog(), RefRole, and TitleRole.
recentItemClicked
void WelcomeView::recentItemClicked (QListWidgetItem * item) protected slot
References recentSketch().
recentSketch
void WelcomeView::recentSketch (const QString & filename, const QString & actionText) signal
setBlogItemImage()
void WelcomeView::setBlogItemImage (QPixmap & pixmap, int index, bool blog) protected
References IconRole, BaseCommand::index(), m_blogListWidget, and m_projectListWidget.
showEvent()
void WelcomeView::showEvent (QShowEvent * event)
References updateRecent().
updateRecent()
void WelcomeView::updateRecent ()
References m_recentListWidget.
Member Data Documentation
m_activeHeaderLabelColor
QString WelcomeView::m_activeHeaderLabelColor = "#333" static protected
m_blogLabel
QLabel* WelcomeView::m_blogLabel = nullptr protected
m_blogListWidget
BlogListWidget* WelcomeView::m_blogListWidget = nullptr protected
m_blogUberFrame
QWidget* WelcomeView::m_blogUberFrame = nullptr protected
m_donateLabel
QLabel* WelcomeView::m_donateLabel = nullptr protected
m_donateUberFrame
QWidget* WelcomeView::m_donateUberFrame = nullptr protected
m_fabLabel
QLabel* WelcomeView::m_fabLabel = nullptr protected
m_fabUberFrame
QWidget* WelcomeView::m_fabUberFrame = nullptr protected
m_inactiveHeaderLabelColor
QString WelcomeView::m_inactiveHeaderLabelColor = "#b1b1b1" static protected
m_projectListWidget
BlogListWidget* WelcomeView::m_projectListWidget = nullptr protected
m_projectsLabel
QLabel* WelcomeView::m_projectsLabel = nullptr protected
m_projectsUberFrame
QWidget* WelcomeView::m_projectsUberFrame = nullptr protected
m_recentListWidget
QListWidget* WelcomeView::m_recentListWidget = nullptr protected
m_shopLabel
QLabel* WelcomeView::m_shopLabel = nullptr protected
m_shopUberFrame
QWidget* WelcomeView::m_shopUberFrame = nullptr protected
m_tip
QLabel* WelcomeView::m_tip = nullptr protected
The documentation for this class was generated from the following files:
sketch/welcomeview.h
sketch/welcomeview.cpp