Fritzing: autoroute/cmrouter/tile.h File Reference
tile.h File Reference
#include <QGraphicsItem>
#include <QDebug>
Classes
struct Plane
struct Tile
struct TilePoint
struct TileRect
Macros
#define BADTILE ((Tile *) 0) /* Invalid tile pointer */
#define NEXT_TILE_DOWN(tResult, t, x)
#define NEXT_TILE_LEFT(tResult, t, y)
#define NEXT_TILE_RIGHT(tResult, t, y)
#define NEXT_TILE_UP(tResult, t, x)
#define TiBottom(tileP) (YMIN(tileP))
#define TiLeft(tileP) (LEFT(tileP))
#define TiRight(tileP) (RIGHT(tileP))
#define TiTop(tileP) (YMAX(tileP))
Typedefs
typedef int(* TileCallback) (Tile *, UserData)
typedef void(* TileFunc) (Tile *)
typedef void * UserData
Functions
Tile * BL (Tile *tileP)
Tile * gotoPoint (Tile *tile, TilePoint p)
int HEIGHT (Tile *tileP)
Tile * LB (Tile *tileP)
int LEFT (Tile *tileP)
int RIGHT (Tile *tileP)
Tile * RT (Tile *tileP)
void SETBL (Tile *tileP, Tile *val)
void SETLB (Tile *tileP, Tile *val)
void SETLEFT (Tile *tileP, int val)
void SETRIGHT (Tile *tileP, int val)
void SETRT (Tile *tileP, Tile *val)
void SETTR (Tile *tileP, Tile *val)
void SETYMAX (Tile *tileP, int val)
void SETYMIN (Tile *tileP, int val)
Tile * TiAlloc ()
void TiFree (Tile *)
void TiFreePlane (Plane *plane)
QGraphicsItem * TiGetBody (Tile *tileP)
QGraphicsItem * TiGetClient (Tile *tileP)
Tile::TileType TiGetType (Tile *tileP)
Tile * TiInsertTile (Plane *, TileRect *rect, QGraphicsItem *body, Tile::TileType type)
void TiJoinX (Tile *tile1, Tile *tile2, Plane *plane)
void TiJoinY (Tile *tile1, Tile *tile2, Plane *plane)
Plane * TiNewPlane (Tile *tile, int minx, int miny, int maxx, int maxy)
void TiSetBody (Tile *tileP, QGraphicsItem *b)
void TiSetClient (Tile *tileP, QGraphicsItem *b)
void TiSetType (Tile *tileP, Tile::TileType t)
Tile * TiSplitX (Tile *tile, int x)
Tile * TiSplitX_Left (Tile *tile, int x)
Tile * TiSplitY (Tile *tile, int y)
Tile * TiSplitY_Bottom (Tile *tile, int y)
int TiSrArea (Tile *hintTile, Plane *plane, TileRect *rect, TileCallback, UserData arg)
Tile * TiSrPoint (Tile *hintTile, Plane *plane, int x, int y)
void TiToRect (Tile *tile, TileRect *rect)
Tile * TR (Tile *tileP)
int WIDTH (Tile *tileP)
int YMAX (Tile *tileP)
int YMIN (Tile *tileP)
Variables
int MINDIFF
int MINFINITY
int TINFINITY
Macro Definition Documentation
BADTILE
#define BADTILE ((Tile *) 0) /* Invalid tile pointer */
NEXT_TILE_DOWN
#define NEXT_TILE_DOWN (tResult, t, x)
Value:
for ((tResult) = LB(t); RIGHT(tResult) <= (x); (tResult) = TR(tResult)) \
        /* Nothing */;
NEXT_TILE_LEFT
#define NEXT_TILE_LEFT (tResult, t, y)
Value:
for ((tResult) = BL(t); YMAX(tResult) <= (y); (tResult) = RT(tResult)) \
        /* Nothing */;
NEXT_TILE_RIGHT
#define NEXT_TILE_RIGHT (tResult, t, y)
Value:
for ((tResult) = TR(t); YMIN(tResult) > (y); (tResult) = LB(tResult)) \
        /* Nothing */;
NEXT_TILE_UP
#define NEXT_TILE_UP (tResult, t, x)
Value:
for ((tResult) = RT(t); LEFT(tResult) > (x); (tResult) = BL(tResult)) \
        /* Nothing */;
TiBottom
#define TiBottom (tileP) (YMIN(tileP))
TiLeft
#define TiLeft (tileP) (LEFT(tileP))
TiRight
#define TiRight (tileP) (RIGHT(tileP))
TiTop
#define TiTop (tileP) (YMAX(tileP))
Typedef Documentation
TileCallback
typedef int(* TileCallback) (Tile *, UserData)
TileFunc
typedef void(* TileFunc) (Tile *)
UserData
typedef void* UserData
Function Documentation
BL()
Tile* BL (Tile * tileP) inline
References Tile::ti_bl.
gotoPoint()
Tile* gotoPoint (Tile * tile, TilePoint p)
References BL(), LB(), LEFT(), RIGHT(), RT(), TR(), TilePoint::xi, TilePoint::yi, YMAX(), and YMIN().
HEIGHT()
int HEIGHT (Tile * tileP) inline
References YMAX(), and YMIN().
LB()
Tile* LB (Tile * tileP) inline
References Tile::ti_lb.
LEFT()
int LEFT (Tile * tileP) inline
References Tile::ti_ll, and TilePoint::xi.
RIGHT()
int RIGHT (Tile * tileP) inline
References LEFT(), and TR().
RT()
Tile* RT (Tile * tileP) inline
References Tile::ti_rt.
SETBL()
void SETBL (Tile * tileP, Tile * val) inline
References Tile::ti_bl.
SETLB()
void SETLB (Tile * tileP, Tile * val) inline
References Tile::ti_lb.
SETLEFT()
void SETLEFT (Tile * tileP, int val) inline
References Tile::ti_ll, and TilePoint::xi.
SETRIGHT()
void SETRIGHT (Tile * tileP, int val) inline
References SETLEFT(), and TR().
SETRT()
void SETRT (Tile * tileP, Tile * val) inline
References Tile::ti_rt.
SETTR()
void SETTR (Tile * tileP, Tile * val) inline
References Tile::ti_tr.
SETYMAX()
void SETYMAX (Tile * tileP, int val) inline
References RT(), and SETYMIN().
SETYMIN()
void SETYMIN (Tile * tileP, int val) inline
References Tile::ti_ll, and TilePoint::yi.
TiAlloc()
Tile* TiAlloc ()
References Tile::NOTYPE, SETBL(), SETLB(), SETRT(), SETTR(), TiSetBody(), TiSetClient(), and TiSetType().
TiFree()
void TiFree (Tile *)
TiFreePlane()
void TiFreePlane (Plane * plane)
References Plane::pl_bottom, Plane::pl_left, Plane::pl_right, Plane::pl_top, searchArg::plane, and TiFree().
TiGetBody()
QGraphicsItem* TiGetBody (Tile * tileP) inline
References Tile::ti_body.
TiGetClient()
QGraphicsItem* TiGetClient (Tile * tileP) inline
References Tile::ti_client.
TiGetType()
Tile::TileType TiGetType (Tile * tileP) inline
References Tile::ti_type.
TiInsertTile()
Tile* TiInsertTile (Plane * , TileRect * rect, QGraphicsItem * body, Tile::TileType type)
References searchArg::body, DBPlaceCell(), searchArg::plane, searchArg::rect, TiSrPoint(), searchArg::type, TileRect::xmini, and TileRect::ymini.
TiJoinX()
void TiJoinX (Tile * tile1, Tile * tile2, Plane * plane)
References BL(), LB(), LEFT(), Plane::pl_hint, searchArg::plane, RT(), SETBL(), SETLB(), SETLEFT(), SETRT(), SETTR(), TiFree(), and TR().
TiJoinY()
void TiJoinY (Tile * tile1, Tile * tile2, Plane * plane)
References BL(), LB(), Plane::pl_hint, searchArg::plane, RT(), SETBL(), SETLB(), SETRT(), SETTR(), SETYMIN(), TiFree(), TR(), and YMIN().
TiNewPlane()
Plane* TiNewPlane (Tile * tile, int minx, int miny, int maxx, int maxy)
References BADTILE, Tile::DUMMYBOTTOM, Tile::DUMMYLEFT, Tile::DUMMYRIGHT, Tile::DUMMYTOP, Plane::maxRect, MINFINITY, Plane::pl_bottom, Plane::pl_hint, Plane::pl_left, Plane::pl_right, Plane::pl_top, SETBL(), SETLB(), SETLEFT(), SETRT(), SETTR(), SETYMIN(), TiAlloc(), TINFINITY, TiSetBody(), TiSetType(), TileRect::xmaxi, TileRect::xmini, TileRect::ymaxi, and TileRect::ymini.
TiSetBody()
void TiSetBody (Tile * tileP, QGraphicsItem * b) inline
References Tile::ti_body.
TiSetClient()
void TiSetClient (Tile * tileP, QGraphicsItem * b) inline
References Tile::ti_client.
TiSetType()
void TiSetType (Tile * tileP, Tile::TileType t) inline
References Tile::ti_type.
TiSplitX()
Tile* TiSplitX (Tile * tile, int x)
References BL(), dupTileBody(), LB(), LEFT(), RIGHT(), RT(), SETBL(), SETLB(), SETLEFT(), SETRT(), SETTR(), SETYMIN(), TiAlloc(), TR(), and YMIN().
TiSplitX_Left()
Tile* TiSplitX_Left (Tile * tile, int x)
References BL(), dupTileBody(), LB(), LEFT(), RIGHT(), RT(), SETBL(), SETLB(), SETLEFT(), SETRT(), SETTR(), SETYMIN(), TiAlloc(), TR(), and YMIN().
TiSplitY()
Tile* TiSplitY (Tile * tile, int y)
References BL(), dupTileBody(), LB(), LEFT(), RT(), SETBL(), SETLB(), SETLEFT(), SETRT(), SETTR(), SETYMIN(), TiAlloc(), TR(), YMAX(), and YMIN().
TiSplitY_Bottom()
Tile* TiSplitY_Bottom (Tile * tile, int y)
References BL(), dupTileBody(), LB(), LEFT(), RT(), SETBL(), SETLB(), SETLEFT(), SETRT(), SETTR(), SETYMIN(), TiAlloc(), TR(), YMAX(), and YMIN().
TiSrArea()
int TiSrArea (Tile * hintTile, Plane * plane, TileRect * rect, TileCallback , UserData arg)
References gotoPoint(), MINDIFF, Plane::pl_hint, searchArg::plane, searchArg::rect, RIGHT(), tiSrAreaEnum(), TR(), TilePoint::xi, TileRect::xmini, TilePoint::yi, TileRect::ymaxi, YMIN(), and TileRect::ymini.
TiSrPoint()
Tile* TiSrPoint (Tile * hintTile, Plane * plane, int x, int y)
References gotoPoint(), Plane::pl_hint, searchArg::plane, and TilePoint::xi.
TiToRect()
void TiToRect (Tile * tile, TileRect * rect)
References LEFT(), searchArg::rect, RIGHT(), TileRect::xmaxi, TileRect::xmini, YMAX(), TileRect::ymaxi, YMIN(), and TileRect::ymini.
TR()
Tile* TR (Tile * tileP) inline
References Tile::ti_tr.
WIDTH()
int WIDTH (Tile * tileP) inline
References LEFT(), and RIGHT().
YMAX()
int YMAX (Tile * tileP) inline
References RT(), and YMIN().
YMIN()
int YMIN (Tile * tileP) inline
References Tile::ti_ll, and TilePoint::yi.
Variable Documentation
MINDIFF
int MINDIFF
MINFINITY
int MINFINITY
TINFINITY
int TINFINITY