Fritzing: ConsoleWindow Class Reference
ConsoleWindow Class Reference
#include <consolewindow.h>
Public Member Functions
ConsoleWindow (QWidget *parent=0)
~ConsoleWindow ()
void closeSerialPort (const QString portName)
void openSerialPort (const QString portName)
Protected Member Functions
void closeEvent (QCloseEvent *event)
Private Slots
void about ()
void closeSerialPort ()
void handleError (QSerialPort::SerialPortError error)
void openSerialPort ()
void readData ()
void writeData (const QByteArray &data)
Private Member Functions
void initActionsConnections ()
Private Attributes
Console * console
QSerialPort * serial
ConsoleSettings * settings
Ui::ConsoleWindow * ui
Constructor & Destructor Documentation
ConsoleWindow()
ConsoleWindow::ConsoleWindow (QWidget * parent = 0) explicit
References console, handleError(), initActionsConnections(), readData(), serial, settings, ui, and writeData().
~ConsoleWindow()
ConsoleWindow::~ConsoleWindow ()
References settings, and ui.
Member Function Documentation
about
void ConsoleWindow::about () private slot
closeEvent()
void ConsoleWindow::closeEvent (QCloseEvent * event) protected
References closeSerialPort(), and settings.
closeSerialPort() [1/2]
void ConsoleWindow::closeSerialPort (const QString portName)
References closeSerialPort(), and serial.
closeSerialPort [2/2]
void ConsoleWindow::closeSerialPort () private slot
References console, serial, and ui.
handleError
void ConsoleWindow::handleError (QSerialPort::SerialPortError error) private slot
References closeSerialPort(), and serial.
initActionsConnections()
void ConsoleWindow::initActionsConnections () private
References about(), closeSerialPort(), console, openSerialPort(), settings, and ui.
openSerialPort() [1/2]
void ConsoleWindow::openSerialPort (const QString portName)
References closeSerialPort(), openSerialPort(), ConsoleSettings::selectPortName(), serial, and settings.
openSerialPort [2/2]
void ConsoleWindow::openSerialPort () private slot
References ConsoleSettings::Settings::baudRate, console, ConsoleSettings::Settings::dataBits, ConsoleSettings::Settings::flowControl, ConsoleSettings::Settings::localEchoEnabled, ConsoleSettings::Settings::name, ConsoleSettings::Settings::parity, serial, Console::setLocalEchoEnabled(), ConsoleSettings::settings(), settings, ConsoleSettings::Settings::stopBits, ConsoleSettings::Settings::stringBaudRate, ConsoleSettings::Settings::stringDataBits, ConsoleSettings::Settings::stringFlowControl, ConsoleSettings::Settings::stringParity, ConsoleSettings::Settings::stringStopBits, and ui.
readData
void ConsoleWindow::readData () private slot
References console, Console::putData(), and serial.
writeData
void ConsoleWindow::writeData (const QByteArray & data) private slot
References serial.
Member Data Documentation
console
Console* ConsoleWindow::console private
serial
QSerialPort* ConsoleWindow::serial private
settings
ConsoleSettings* ConsoleWindow::settings private
ui
Ui::ConsoleWindow* ConsoleWindow::ui private
The documentation for this class was generated from the following files:
program/consolewindow.h
program/consolewindow.cpp