Fritzing: QuoteDialog Class Reference
QuoteDialog Class Reference
#include <quotedialog.h>
Public Member Functions
QuoteDialog (bool full, QWidget *parent=0)
~QuoteDialog ()
void setText ()
Static Public Member Functions
static QString countArgs ()
static bool quoteSucceeded ()
static void setArea (double area, int boardCount)
static void setCountCost (int index, int count, double cost)
static void setQuoteSucceeded (bool)
Static Public Attributes
static const int MessageCount = 4
Protected Slots
void visitFritzingFab ()
Static Protected Member Functions
static void initCounts ()
Protected Attributes
QLabel * m_messageLabel
QTableWidget * m_tableWidget
Constructor & Destructor Documentation
QuoteDialog()
QuoteDialog::QuoteDialog (bool full, QWidget * parent = 0)
References DebugDialog::debug(), initCounts(), m_messageLabel, m_tableWidget, MessageCount, and visitFritzingFab().
~QuoteDialog()
QuoteDialog::~QuoteDialog ()
Member Function Documentation
countArgs()
QString QuoteDialog::countArgs () static
References Counts, and initCounts().
initCounts()
void QuoteDialog::initCounts () static protected
References Counts.
quoteSucceeded()
bool QuoteDialog::quoteSucceeded () static
References QuoteSucceeded.
setArea()
void QuoteDialog::setArea (double area, int boardCount) static
References TheArea, and TheBoardCount.
setCountCost()
void QuoteDialog::setCountCost (int index, int count, double cost) static
References CountCost::cost, CountCost::count, MessageCount, and TheCountCost.
setQuoteSucceeded()
void QuoteDialog::setQuoteSucceeded (bool succeeded) static
References QuoteSucceeded.
setText()
void QuoteDialog::setText ()
References CountCost::cost, CountCost::count, EuroSymbol(), hundredths(), m_messageLabel, m_tableWidget, MessageCount, TheArea, TheBoardCount, TheCountCost, and ThinSpaceSymbol().
visitFritzingFab
void QuoteDialog::visitFritzingFab () protected slot
Member Data Documentation
m_messageLabel
QLabel* QuoteDialog::m_messageLabel protected
m_tableWidget
QTableWidget* QuoteDialog::m_tableWidget protected
MessageCount
const int QuoteDialog::MessageCount = 4 static
The documentation for this class was generated from the following files:
dialogs/quotedialog.h
dialogs/quotedialog.cpp