Fritzing: FritzingWindow Class Reference
FritzingWindow Class Reference abstract
#include <fritzingwindow.h>
Signals
void readOnlyChanged (bool isReadOnly)
Public Member Functions
FritzingWindow (const QString &untitledFileName, int &untitledFileCount, QString fileExt, QWidget *parent=0, Qt::WindowFlags f=0)
const QString & fileName ()
virtual void notClosableForAWhile ()
void setFileName (const QString &)
Public Member Functions inherited from Bundler
virtual ~Bundler ()
virtual bool loadBundledAux (QDir &dir, QList< class ModelPart * > mps)
virtual bool preloadBundledAux (QDir &dir, bool dontAsk)
Static Public Member Functions
static bool alreadyHasExtension (const QString &fileName, const QString &extension=___emptyString___)
Static Public Attributes
static const QString QtFunkyPlaceholder = QLatin1String("[*]")
static QString ReadOnlyPlaceholder
Protected Slots
virtual bool save ()
virtual bool saveAs ()
void undoStackCleanChanged (bool isClean)
Protected Member Functions
virtual bool anyModified ()
virtual bool beforeClosing (bool showCancel, bool &discard)
QMessageBox::StandardButton beforeClosingMessage (const QString &filename, bool showCancel)
void createCloseAction ()
virtual const QString defaultSaveFolder ()=0
virtual const QString fileExtension ()=0
virtual const QString fritzingTitle ()
virtual QStringList getExtensions ()=0
virtual QString getExtensionString ()=0
bool save (const QString &filename, bool readOnly)
bool saveAs (const QString &filename, bool readOnly)
virtual bool saveAsAux (const QString &fileName)=0
virtual void setBeforeClosingText (const QString &filename, QMessageBox &messageBox)
void setReadOnly (bool readOnly)
virtual void setTitle ()
virtual int & untitledFileCount ()=0
virtual const QString untitledFileName ()=0
Protected Attributes
QAction * m_closeAct = nullptr
QString m_fwFilename
bool m_readOnly = false
QStatusBar * m_statusBar = nullptr
QDir m_tempDir
class WaitPushUndoStack * m_undoStack = nullptr
Static Protected Attributes
static QStringList OtherKnownExtensions
Constructor & Destructor Documentation
FritzingWindow()
FritzingWindow::FritzingWindow (const QString & untitledFileName, int & untitledFileCount, QString fileExt, QWidget * parent = 0, Qt::WindowFlags f = 0)
References ___fritzingTitle___, m_undoStack, setFileName(), setTitle(), undoStackCleanChanged(), untitledFileCount(), and untitledFileName().
Member Function Documentation
alreadyHasExtension()
bool FritzingWindow::alreadyHasExtension (const QString & fileName, const QString & extension = ___emptyString___) static
References fileName(), fritzingExtensions(), and OtherKnownExtensions.
anyModified()
bool FritzingWindow::anyModified () protected virtual
beforeClosing()
bool FritzingWindow::beforeClosing (bool showCancel, bool & discard) protected virtual
Reimplemented in ProgramWindow.
References anyModified(), beforeClosingMessage(), m_fwFilename, and save().
beforeClosingMessage()
QMessageBox::StandardButton FritzingWindow::beforeClosingMessage (const QString & filename, bool showCancel) protected
References m_fwFilename, setBeforeClosingText(), and untitledFileName().
createCloseAction()
void FritzingWindow::createCloseAction () protected
References m_closeAct.
defaultSaveFolder()
virtual const QString FritzingWindow::defaultSaveFolder () protected pure virtual
Implemented in MainWindow, PartsEditorMainWindow, and ProgramWindow.
fileExtension()
virtual const QString FritzingWindow::fileExtension () protected pure virtual
Implemented in MainWindow, ProgramWindow, and PartsEditorMainWindow.
fileName()
const QString & FritzingWindow::fileName ()
References m_fwFilename.
fritzingTitle()
const QString FritzingWindow::fritzingTitle () protected virtual
Reimplemented in MainWindow, and PartsEditorMainWindow.
References ___fritzingTitle___.
getExtensions()
virtual QStringList FritzingWindow::getExtensions () protected pure virtual
Implemented in MainWindow, ProgramWindow, and PartsEditorMainWindow.
getExtensionString()
virtual QString FritzingWindow::getExtensionString () protected pure virtual
Implemented in MainWindow, ProgramWindow, and PartsEditorMainWindow.
notClosableForAWhile()
void FritzingWindow::notClosableForAWhile () virtual
Reimplemented in MainWindow.
readOnlyChanged
void FritzingWindow::readOnlyChanged (bool isReadOnly) signal
save [1/2]
bool FritzingWindow::save () protected virtual slot
Reimplemented in PartsEditorMainWindow.
References FolderUtils::isEmptyFileName(), m_fwFilename, m_readOnly, saveAs(), saveAsAux(), and untitledFileName().
save() [2/2]
bool FritzingWindow::save (const QString & filename, bool readOnly) protected
References FolderUtils::isEmptyFileName(), m_readOnly, saveAs(), saveAsAux(), and untitledFileName().
saveAs [1/2]
bool FritzingWindow::saveAs () protected virtual slot
Reimplemented in PartsEditorMainWindow.
References m_fwFilename, and m_readOnly.
saveAs() [2/2]
bool FritzingWindow::saveAs (const QString & filename, bool readOnly) protected
References alreadyHasExtension(), DebugDialog::debug(), defaultSaveFolder(), getExtensions(), getExtensionString(), FolderUtils::getSaveFileName(), saveAsAux(), and untitledFileName().
saveAsAux()
virtual bool FritzingWindow::saveAsAux (const QString & fileName) protected pure virtual
Implements Bundler.
Implemented in MainWindow, ProgramWindow, and PartsEditorMainWindow.
setBeforeClosingText()
void FritzingWindow::setBeforeClosingText (const QString & filename, QMessageBox & messageBox) protected virtual
Reimplemented in PEMainWindow.
setFileName()
void FritzingWindow::setFileName (const QString & filename)
References m_fwFilename.
setReadOnly()
void FritzingWindow::setReadOnly (bool readOnly) protected
References m_readOnly, and readOnlyChanged().
setTitle()
void FritzingWindow::setTitle () protected virtual
Reimplemented in ProgramWindow, and PEMainWindow.
References fileName(), fritzingTitle(), m_fwFilename, m_readOnly, QtFunkyPlaceholder, and ReadOnlyPlaceholder.
undoStackCleanChanged
void FritzingWindow::undoStackCleanChanged (bool isClean) protected slot
untitledFileCount()
virtual int& FritzingWindow::untitledFileCount () protected pure virtual
Implemented in MainWindow, ProgramWindow, and PartsEditorMainWindow.
untitledFileName()
virtual const QString FritzingWindow::untitledFileName () protected pure virtual
Implemented in MainWindow, ProgramWindow, and PartsEditorMainWindow.
Member Data Documentation
m_closeAct
QAction* FritzingWindow::m_closeAct = nullptr protected
m_fwFilename
QString FritzingWindow::m_fwFilename protected
m_readOnly
bool FritzingWindow::m_readOnly = false protected
m_statusBar
QStatusBar* FritzingWindow::m_statusBar = nullptr protected
m_tempDir
QDir FritzingWindow::m_tempDir protected
m_undoStack
class WaitPushUndoStack* FritzingWindow::m_undoStack = nullptr protected
OtherKnownExtensions
QStringList FritzingWindow::OtherKnownExtensions static protected
QtFunkyPlaceholder
const QString FritzingWindow::QtFunkyPlaceholder = QLatin1String("[*]") static
ReadOnlyPlaceholder
QString FritzingWindow::ReadOnlyPlaceholder static
The documentation for this class was generated from the following files:
mainwindow/fritzingwindow.h
mainwindow/fritzingwindow.cpp