Fritzing: BreadboardSketchWidget Class Reference
BreadboardSketchWidget Class Reference
#include <breadboardsketchwidget.h>
Public Member Functions
BreadboardSketchWidget (ViewLayer::ViewID, QWidget *parent=0)
void addDefaultParts ()
void addViewLayers ()
bool canDisconnectAll ()
bool coloringWiresByLength ()
void colorWiresByLength (bool)
void getBendpointWidths (class Wire *, double w, double &w1, double &w2, bool &negativeOffsetRect)
double getWireStrokeWidth (Wire *, double wireWidth)
bool ignoreFemale ()
void initWire (Wire *, int penWidth)
void showEvent (QShowEvent *event)
Public Member Functions inherited from SketchWidget
SketchWidget (ViewLayer::ViewID, QWidget *parent=0, int size=400, int minSize=300)
~SketchWidget ()
void addBendpoint (ItemBase *lastHoverEnterItem, ConnectorItem *lastHoverEnterConnectorItem, QPointF lastLocation)
ItemBase * addItem (ModelPart *, ViewLayer::ViewLayerPlacement, BaseCommand::CrossViewType, const ViewGeometry &, long id, long modelIndex, AddDeleteItemCommand *originatingCommand)
ItemBase * addItem (const QString &moduleID, ViewLayer::ViewLayerPlacement, BaseCommand::CrossViewType, const ViewGeometry &, long id, long modelIndex, AddDeleteItemCommand *originatingCommand)
virtual ItemBase * addItemAux (ModelPart *, ViewLayer::ViewLayerPlacement, const ViewGeometry &, long id, bool doConnectors, ViewLayer::ViewID, bool temporary)
ItemBase * addItemAuxTemp (ModelPart *, ViewLayer::ViewLayerPlacement, const ViewGeometry &, long id, bool doConnectors, ViewLayer::ViewID, bool temporary)
void addLegBendpoint (long id, const QString &connectorID, int index, QPointF, const class Bezier *, const class Bezier *)
void addToSketch (QList< ModelPart * > &)
void addViewLayer (ViewLayer *)
QGraphicsItem * addWatermark (const QString &filename)
bool alignedToGrid ()
void alignItems (Qt::Alignment)
QPointF alignOneToGrid (ItemBase *itemBase)
void alignToGrid (bool)
const QColor & background ()
void blockUI (bool)
void bringForward ()
void bringToFront ()
ItemCount calcItemCount ()
virtual bool canCopyItem (QGraphicsItem *item, int count)
virtual bool canDeleteItem (QGraphicsItem *item, int count)
void changeBus (ItemBase *, bool connec, const QString &oldBus, const QString &newBus, QList< ConnectorItem * > &, const QString &message, const QString &oldLayout, const QString &newLayout)
virtual void changeConnection (long fromID, const QString &fromConnectorID, long toID, const QString &toConnectorID, ViewLayer::ViewLayerPlacement, bool connect, bool doEmit, bool updateConnections)
virtual void changeLayer (long id, double z, ViewLayer::ViewLayerID viewLayerID)
void changeLeg (long fromID, const QString &connectorID, const QPolygonF &, bool relative, const QString &why)
void changeLegCurve (long id, const QString &connectorID, int index, const Bezier *)
void changeWire (long fromID, QLineF line, QPointF pos, bool updateConnections, bool updateRatsnest)
void changeWireColor (long wireId, const QString &color, double opacity)
void changeWireCurve (long id, const Bezier *, bool autoroutable)
void changeWireFlags (long wireId, ViewGeometry::WireFlags wireFlags)
void changeWireWidth (long wireId, double width)
void changeZ (QHash< long, RealPair * >, double(*pairAccessor)(RealPair *))
void checkForReversedWires ()
void cleanUpWires (bool doEmit, class CleanUpWiresCommand *)
void clearPasteOffset ()
void clearSelection ()
void collectAllNets (QHash< class ConnectorItem *, int > &indexer, QList< QList< class ConnectorItem * > * > &allPartConnectorItems, bool includeSingletons, bool bothSides)
void collectParts (QList< ItemBase * > &partList)
void copy ()
void copyHeart (QList< ItemBase * > &bases, bool saveBoundingRects, QByteArray &itemData, QList< long > &modelIndexes)
virtual void createTrace (Wire *, bool useLastWireColor)
long createWire (ConnectorItem *from, ConnectorItem *to, ViewGeometry::WireFlags, bool dontUpdate, BaseCommand::CrossViewType, QUndoCommand *parentCommand)
bool curvyWires ()
bool curvyWiresIndicated (Qt::KeyboardModifiers)
void cut ()
virtual ViewLayer::ViewLayerPlacement defaultViewLayerPlacement (ModelPart *)
void deleteItem (long id, bool deleteModelPart, bool doEmit, bool later)
virtual void deleteItem (ItemBase *, bool deleteModelPart, bool doEmit, bool later)
void deleteMiddle (QSet< ItemBase * > &deletedItems, QUndoCommand *parentCommand)
void deleteSelected (Wire *, bool minus)
void disconnectAll ()
void ensureLayerVisible (ViewLayer::ViewLayerID)
constexpr bool everZoomed () const noexcept
const QString & filenameIf ()
ConnectorItem * findConnectorItem (ConnectorItem *foreignConnectorItem)
ItemBase * findItem (long id)
double fitInWindow ()
void flattenCurve (ItemBase *lastHoverEnterItem, ConnectorItem *lastHoverEnterConnectorItem, QPointF lastLocation)
void flipItem (long id, Qt::Orientations orientation)
void flipX (Qt::Orientations orientation, bool rubberBandLegEnabled)
virtual void forwardRoutingStatus (const RoutingStatus &)
virtual QHash< QString, QString > getAutorouterSettings ()
void getBendpointWidths (class Wire *, double w, double &w1, double &w2, bool &negativeOffsetRect)
void getRatsnestColor (QColor &)
PaletteItem * getSelectedPart ()
const QString & getShortName ()
float getTopZ ()
ViewGeometry::WireFlag getTraceFlag ()
virtual ViewLayer::ViewLayerID getWireViewLayerID (const ViewGeometry &viewGeometry, ViewLayer::ViewLayerPlacement)
constexpr const QColor & gridColor () const noexcept
QString gridSizeText ()
virtual bool hasAnyNets ()
void hideConnectors (bool hide)
void hidePartLabel (ItemBase *item)
void hidePartLayer (long id, ViewLayer::ViewLayerID, bool hide)
void hidePartLayer (ItemBase *, ViewLayer::ViewLayerID, bool hide)
void hoverEnterConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
void hoverEnterItem (QGraphicsSceneHoverEvent *event, ItemBase *item)
void hoverLeaveConnectorItem (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
void hoverLeaveItem (QGraphicsSceneHoverEvent *event, ItemBase *item)
virtual bool includeSymbols ()
void initGrid ()
ConnectorItem * lastHoverEnterConnectorItem ()
ItemBase * lastHoverEnterItem ()
bool layerIsActive (ViewLayer::ViewLayerID)
bool layerIsVisible (ViewLayer::ViewLayerID)
virtual void loadFromModelParts (QList< ModelPart * > &modelParts, BaseCommand::CrossViewType, QUndoCommand *parentCommand, bool offsetPaste, const QRectF *boundingRect, bool seekOutsideConnections, QList< long > &newIDs)
void loadLogoImage (ItemBase *, const QString &oldSvg, const QSizeF oldAspectRatio, const QString &oldFilename, const QString &newFilename, bool addName)
void loadLogoImage (long itemID, const QString &oldSvg, const QSizeF oldAspectRatio, const QString &oldFilename)
void loadLogoImage (long itemID, const QString &newFilename, bool addName)
void makeDeleteItemCommand (ItemBase *itemBase, BaseCommand::CrossViewType, QUndoCommand *parentCommand)
VirtualWire * makeOneRatsnestWire (ConnectorItem *source, ConnectorItem *dest, bool routed, QColor color, bool force)
void makeWiresChangeConnectionCommands (const QList< Wire * > &wires, QUndoCommand *parentCommand)
void mousePressConnectorEvent (ConnectorItem *, QGraphicsSceneMouseEvent *)
void moveItem (long id, ViewGeometry &, bool updateRatsnest)
void moveItem (long id, const QPointF &p, bool updateRatsnest)
void moveItem (ItemBase *, double x, double y)
void moveLegBendpoint (long id, const QString &connectorID, int index, QPointF)
void movePartLabel (long itemID, QPointF newPos, QPointF newOffset)
void noteChanged (ItemBase *, const QString &oldText, const QString &newtext, QSizeF oldSize, QSizeF newSize)
void noteSizeChanged (ItemBase *itemBase, const QSizeF &oldSize, const QSizeF &newSize)
void partLabelChanged (ItemBase *, const QString &oldText, const QString &newtext)
void partLabelMoved (ItemBase *, QPointF oldPos, QPointF oldOffset, QPointF newPos, QPointF newOffset)
bool partLabelsVisible ()
void pasteHeart (QByteArray &itemData, bool seekOutsideConnections)
void prepLegBendpointChange (ConnectorItem *from, int oldCount, int newCount, int index, QPointF pos, const class Bezier *, const class Bezier *, const class Bezier *, bool triggerFirstTime)
void prepLegBendpointMove (ConnectorItem *from, int index, QPointF oldPos, QPointF newPos, ConnectorItem *to, bool changeConnections)
void prepLegCurveChange (ConnectorItem *from, int index, const class Bezier *oldB, const class Bezier *newB, bool triggerFirstTime)
void prepLegSelection (ItemBase *)
void pushCommand (QUndoCommand *, QObject *signalTarget)
void ratsnestConnect (ConnectorItem *connectorItem, bool connect)
void ratsnestConnect (ItemBase *, bool connect)
void ratsnestConnect (ConnectorItem *c1, ConnectorItem *c2, bool connect, bool wait)
double ratsnestOpacity ()
double ratsnestWidth ()
void recalcLeg (long fromID, const QString &connectorID, const QPolygonF &, bool relative, bool active, const QString &why)
class ReferenceModel * referenceModel ()
void removeLegBendpoint (long id, const QString &connectorID, int index, const class Bezier *)
void renamePins (ItemBase *, const QStringList &oldLabels, const QStringList &newLabels, bool singleRow)
void renamePins (long itemID, const QStringList &labels, bool singleRow)
QString renderToSVG (RenderThing &, QGraphicsItem *board, const LayerList &)
void resizeNote (long itemID, const QSizeF &)
void resolveTemporary (bool, ItemBase *)
void restoreLayerVisibility ()
void restorePartLabel (long itemID, QDomElement &element)
double retrieveZoom ()
void rotateFlipPartLabel (ItemBase *, double degrees, Qt::Orientations flipDirection)
void rotateFlipPartLabel (long itemID, double degrees, Qt::Orientations flipDirection)
void rotateItem (long id, double degrees)
void rotateLeg (long fromID, const QString &connectorID, const QPolygonF &, bool active)
void rotateX (double degrees, bool rubberBandLegEnabled, ItemBase *originatingItem)
virtual bool routeBothSides ()
virtual bool sameElectricalLayer2 (ViewLayer::ViewLayerID, ViewLayer::ViewLayerID)
void saveLayerVisibility ()
void saveZoom (double)
int selectAllMoveLock ()
QList< ItemBase * > selectAllObsolete ()
virtual void selectAllWires (ViewGeometry::WireFlag)
void selectDeselectAllCommand (bool state)
const QString & selectedModuleID ()
void selectItem (long id, bool state, bool updateInfoView, bool doEmit)
void selectItem (ItemBase *itemBase)
void selectItems (QList< ItemBase * >)
void selectItemsWithModuleID (ModelPart *)
void sendBackward ()
void sendToBack ()
void setAllLayersVisible (bool visible)
void setAnyInRotation ()
virtual void setAutorouterSettings (QHash< QString, QString > &)
void setBackground (QColor)
void setBackgroundColor (QColor, bool setPref)
void setChainDrag (bool)
virtual void setClipEnds (class ClipableWire *, bool)
virtual void setCurrent (bool current)
void setCurvyWires (bool)
void setEverZoomed (bool)
void setGridColor (QColor)
void setGridSize (const QString &)
void setGroundFillSeed (long id, const QString &connectorID, bool seed)
void setIgnoreSelectionChangeEvents (bool)
void setInfoViewOnHover (bool infoViewOnHover)
void setItemDropOffset (long id, QPointF offset)
void setItemMenu (QMenu *)
void setLayerActive (ViewLayer *viewLayer, bool active)
void setLayerActive (ViewLayer::ViewLayerID viewLayerID, bool active)
void setLayerVisible (ViewLayer *viewLayer, bool visible, bool doChildLayers)
void setLayerVisible (ViewLayer::ViewLayerID viewLayerID, bool visible, bool doChildLayers)
void setMoveLock (long id, bool lock)
void setNoteFocus (QGraphicsItem *, bool inFocus)
void setPasting (bool)
void setRatsnestOpacity (double)
void setRatsnestWidth (double)
void setReferenceModel (class ReferenceModel *referenceModel)
void setSketchModel (SketchModel *)
void setUndoStack (class WaitPushUndoStack *)
virtual long setUpSwap (SwapThing &, bool master)
void setViewLayerIDs (ViewLayer::ViewLayerID part, ViewLayer::ViewLayerID wire, ViewLayer::ViewLayerID connector, ViewLayer::ViewLayerID ruler, ViewLayer::ViewLayerID note)
void setWireExtras (long id, QDomElement &)
void setWireMenu (QMenu *)
void showEvent (QShowEvent *event)
void showGrid (bool)
bool showingGrid ()
void showPartLabels (bool show)
void showUnrouted ()
void simpleMoveItem (long id, QPointF)
void sortAnyByZ (const QList< QGraphicsItem * > &items, QList< ItemBase * > &bases)
bool spaceBarIsPressed () noexcept
class SelectItemCommand * stackSelectionState (bool pushIt, QUndoCommand *parentCommand)
QColor standardBackground ()
void stickem (long stickTargetID, long stickSourceID, bool stick)
void stickyScoop (ItemBase *stickyOne, bool checkCurrent, CheckStickyCommand *)
bool swappingEnabled (ItemBase *)
void testConnectors ()
virtual void tidyWires ()
void transformItem (long id, const QMatrix &)
void triggerRotate (ItemBase *, double degrees)
class WaitPushUndoStack * undoStack ()
void updateInfoView ()
void updateRoutingStatus (CleanUpWiresCommand *, RoutingStatus &, bool manual)
void updateRoutingStatus (RoutingStatus &, bool manual)
void updateWire (long id, const QString &connectorID, bool updateRatsnest)
void updateWires ()
constexpr ViewLayer::ViewID viewID () const noexcept
void viewItemInfo (ItemBase *item)
LayerHash & viewLayers ()
constexpr const QString & viewName () const noexcept
Public Member Functions inherited from InfoGraphicsView
InfoGraphicsView (QWidget *parent=0)
int boardLayers ()
virtual void changePinLabels (ItemBase *, bool singleRow)
virtual void changeWireColor (const QString newColor)
virtual void changeWireWidthMils (const QString newWidth)
virtual QString generateCopperFillUnit (ItemBase *itemBase, QPointF whereToStart)
virtual double getLabelFontSizeLarge ()
virtual double getLabelFontSizeMedium ()
virtual double getLabelFontSizeSmall ()
virtual double getLabelFontSizeTiny ()
virtual bool hasBigDots ()
class HtmlInfoView * infoView ()
virtual void newWire (Wire *)
void setActiveConnectorItem (ConnectorItem *)
void setActiveWire (Wire *)
virtual void setBoardLayers (int, bool redraw)
virtual void setHoleSize (ItemBase *, const QString &propName, const QString &translatedPropName, const QString &oldValue, const QString &newValue, QRectF &oldRect, QRectF &newRect, bool redraw)
void setInfoView (class HtmlInfoView *)
virtual void setProp (ItemBase *, const QString &propName, const QString &translatedPropName, const QString &oldValue, const QString &newValue, bool redraw)
virtual void setResistance (QString resistance, QString pinSpacing)
void setSMDOrientation (Qt::Orientations)
Qt::Orientations smdOrientation ()
virtual void swap (const QString &family, const QString &prop, QMap< QString, QString > &propsMap, ItemBase *)
void updateRotation (ItemBase *)
Public Member Functions inherited from ZoomableGraphicsView
ZoomableGraphicsView (QWidget *parent=0)
void absoluteZoom (double percent)
double currentZoom ()
virtual void ensureFixedToBottomRightItems ()
void relativeZoom (double step, bool centerToCursor)
void setAcceptWheelEvents (bool)
virtual void setViewFromBelow (bool)
bool viewFromBelow ()
Protected Member Functions
bool canDropModelPart (ModelPart *modelPart)
bool checkUnder ()
bool collectFemaleConnectees (ItemBase *, QSet< ItemBase * > &)
double defaultGridSizeInches ()
bool disconnectFromFemale (ItemBase *item, QHash< long, ItemBase * > &savedItems, ConnectorPairHash &, bool doCommand, bool rubberBandLegEnabled, QUndoCommand *parentCommand)
void findConnectorsUnder (ItemBase *item)
void getLabelFont (QFont &, QColor &, ItemBase *)
ViewLayer::ViewLayerID getLabelViewLayerID (ItemBase *)
double getTraceWidth ()
void setNewPartVisible (ItemBase *)
void setWireVisible (Wire *wire)
const QString & traceColor (ViewLayer::ViewLayerPlacement)
BaseCommand::CrossViewType wireSplitCrossView ()
Protected Member Functions inherited from SketchWidget
virtual bool acceptsTrace (const ViewGeometry &)
virtual PaletteItem * addPartItem (ModelPart *, ViewLayer::ViewLayerPlacement, PaletteItem *, bool doConnectors, bool &ok, ViewLayer::ViewID, bool temporary)
void addToScene (ItemBase *item, ViewLayer::ViewLayerID viewLayerID)
void addViewLayersAux (const LayerList &, const LayerList &layersFromBelow, float startZ=1.5)
void addWireExtras (long newID, QDomElement &view, QUndoCommand *parentCommand)
void alignLoc (QPointF &loc, const QPointF startPoint, const QPointF newLoc, const QPointF originalLoc)
QPointF calcNewLoc (ItemBase *moveBase, ItemBase *detachFrom)
virtual bool canAlignToCenter (ItemBase *)
virtual bool canAlignToTopLeft (ItemBase *)
virtual bool canChainMultiple ()
virtual bool canChainWire (Wire *)
bool canConnect (ItemBase *from, ItemBase *to)
virtual bool canConnect (Wire *from, ItemBase *to)
virtual bool canCreateWire (Wire *dragWire, ConnectorItem *from, ConnectorItem *to)
virtual bool canDragWire (Wire *)
void categorizeDragLegs (bool rubberBandLegEnabled)
void categorizeDragWires (QSet< Wire * > &wires, QList< ItemBase * > &freeWires)
void changeConnectionAux (long fromID, const QString &fromConnectorID, long toID, const QString &toConnectorID, ViewLayer::ViewLayerPlacement, bool connect, bool updateConnections)
void changeLegAux (long fromID, const QString &fromConnectorID, const QPolygonF &, bool reset, bool relative, bool active, const QString &why)
bool checkAutoscroll (QPoint globalPos)
virtual QString checkDroppedModuleID (const QString &moduleID)
void checkFit (ModelPart *newModelPart, ItemBase *itemBase, long newID, QHash< ConnectorItem *, Connector * > &found, QList< ConnectorItem * > &notFound, QHash< ConnectorItem *, ConnectorItem * > &m2f, QHash< ConnectorItem *, Connector * > &byWire, QHash< QString, QPolygonF > &legs, QHash< QString, ConnectorItem * > &formerLegs, QUndoCommand *parentCommand)
void checkFitAux (ItemBase *tempItemBase, ItemBase *itemBase, long newID, QHash< ConnectorItem *, Connector * > &found, QList< ConnectorItem * > &notFound, QHash< ConnectorItem *, ConnectorItem * > &m2f, QHash< ConnectorItem *, Connector * > &byWire, QHash< QString, QPolygonF > &legs, QHash< QString, ConnectorItem * > &formerLegs, QUndoCommand *parentCommand)
bool checkMoved (bool wait)
bool checkUpdateRatsnest (QList< ConnectorItem * > &connectorItems)
void cleanupRatsnests (QList< QPointer< ConnectorItem > > &connectorItems, bool connect)
void clearDragWireTempCommand ()
void clearHoldingSelectItem ()
void clearTemporaries ()
void clickBackground (QMouseEvent *)
QList< ItemBase * > collectSuperSubs (ItemBase *)
void contextMenuEvent (QContextMenuEvent *)
void continueZChange (QList< ItemBase * > &bases, int start, int end, bool(*test)(int current, int start), int inc, const QString &text)
void continueZChangeAux (QList< ItemBase * > &bases, const QString &text)
void continueZChangeMax (QList< ItemBase * > &bases, int start, int end, bool(*test)(int current, int start), int inc, const QString &text)
void copyAux (QList< ItemBase * > &bases, bool saveBoundingRects)
void copyDrop ()
bool createOneTrace (Wire *wire, ViewGeometry::WireFlag flag, bool allowAny, QList< Wire * > &done, bool useLastWireColor, QUndoCommand *parentCommand)
virtual Wire * createTempWireForDragging (Wire *fromWire, ModelPart *wireModel, ConnectorItem *connectorItem, ViewGeometry &viewGeometry, ViewLayer::ViewLayerPlacement)
void createTrace (Wire *fromWire, const QString &commandString, ViewGeometry::WireFlag, bool useLastWireColor)
virtual ViewLayer::ViewLayerPlacement createWireViewLayerPlacement (ConnectorItem *from, ConnectorItem *to)
bool currentlyInfoviewed (ItemBase *item)
void cutDeleteAux (QString undoStackMessage, bool minus, Wire *wire)
void deleteAux (QSet< ItemBase * > &deletedItems, QUndoCommand *parentCommand, bool doPush)
void dragEnterEvent (QDragEnterEvent *)
bool dragEnterEventAux (QDragEnterEvent *)
bool draggingWireEnd ()
void dragLeaveEvent (QDragLeaveEvent *)
void dragMoveEvent (QDragMoveEvent *)
void dragMoveHighlightConnector (QPoint eventPos)
void dragRatsnestChanged ()
void dragWireChanged (class Wire *wire, ConnectorItem *from, ConnectorItem *to)
void drawBackground (QPainter *painter, const QRectF &rect)
void dropEvent (QDropEvent *)
void dropItemEvent (QDropEvent *event)
ChangeConnectionCommand * extendChangeConnectionCommand (BaseCommand::CrossViewType, long fromID, const QString &fromConnectorID, long toID, const QString &toConnectorID, ViewLayer::ViewLayerPlacement, bool connect, QUndoCommand *parent)
ChangeConnectionCommand * extendChangeConnectionCommand (BaseCommand::CrossViewType, ConnectorItem *fromConnectorItem, ConnectorItem *toConnectorItem, ViewLayer::ViewLayerPlacement, bool connect, QUndoCommand *parentCommand)
virtual void extraRenderSvgStep (ItemBase *, QPointF offset, double dpi, double printerScale, QString &outputSvg)
virtual void findAlignmentAnchor (ItemBase *originatingItem, QHash< long, ItemBase * > &savedItems, QHash< Wire *, ConnectorItem * > &savedWires)
ConnectorItem * findConnectorItem (ItemBase *item, const QString &connectorID, ViewLayer::ViewLayerPlacement)
long findPartOrWire (long itemID)
QGraphicsItem * getClickedItem (QList< QGraphicsItem * > &items)
ViewLayer::ViewLayerID getConnectorViewLayerID ()
virtual ViewLayer::ViewLayerID getDragWireViewLayerID (ConnectorItem *)
ViewLayer::ViewLayerID getNoteViewLayerID ()
ViewLayer::ViewLayerID getPartViewLayerID ()
ViewLayer::ViewLayerID getRulerViewLayerID ()
ViewLayer::ViewLayerID getViewLayerID (ModelPart *, ViewLayer::ViewID, ViewLayer::ViewLayerPlacement)
virtual ViewLayer::ViewLayerPlacement getViewLayerPlacement (ModelPart *, QDomElement &instance, QDomElement &view, ViewGeometry &)
double gridSizeInches ()
void handleConnect (QDomElement &connect, ModelPart *, const QString &fromConnectorID, ViewLayer::ViewLayerID, QStringList &alreadyConnected, QHash< long, ItemBase * > &newItems, QUndoCommand *parentCommand, bool seekOutsideConnections)
virtual const QString & hoverEnterPartConnectorMessage (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
virtual const QString & hoverEnterWireConnectorMessage (QGraphicsSceneHoverEvent *event, ConnectorItem *item)
void initBackgroundColor ()
void keyPressEvent (QKeyEvent *)
void keyReleaseEvent (QKeyEvent *)
void killDroppingItem ()
QString makeMoveSVG (double printerScale, double dpi, QPointF &offset)
void makeRatsnestViewGeometry (ViewGeometry &viewGeometry, ConnectorItem *source, ConnectorItem *dest)
void makeSwapWire (SketchWidget *, ItemBase *, long newID, ConnectorItem *fromConnectorItem, ConnectorItem *toConnectorItem, Connector *newConnector, QUndoCommand *parentCommand)
QString makeWireSVG (Wire *wire, QPointF offset, double dpi, double printerscale, bool blackOnly)
QString makeWireSVGAux (Wire *wire, double width, const QString &color, QPointF offset, double dpi, double printerScale, bool blackOnly, bool dashed)
bool matchesLayer (ModelPart *modelPart)
void mouseDoubleClickEvent (QMouseEvent *)
void mouseMoveEvent (QMouseEvent *)
virtual void mousePressEvent (QMouseEvent *)
void mouseReleaseEvent (QMouseEvent *)
bool moveByArrow (double dx, double dy, QKeyEvent *)
void moveItems (QPoint globalPos, bool checkAutoScroll, bool rubberBandLegEnabled)
void moveLegBendpoints (bool undoOnly, QUndoCommand *parentCommand)
void moveLegBendpointsAux (ConnectorItem *connectorItem, bool undoOnly, QUndoCommand *parentCommand)
virtual ViewLayer::ViewLayerID multiLayerGetViewLayerID (ModelPart *modelPart, ViewLayer::ViewID, ViewLayer::ViewLayerPlacement, LayerList &)
AddItemCommand * newAddItemCommand (BaseCommand::CrossViewType crossViewType, ModelPart *, QString moduleID, ViewLayer::ViewLayerPlacement, ViewGeometry &viewGeometry, qint64 id, bool updateInfoView, long modelIndex, bool addSubparts, QUndoCommand *parent)
ItemBase * overSticky (ItemBase *)
void paintEvent (QPaintEvent *)
void partLabelChangedAux (ItemBase *pitem, const QString &oldText, const QString &newText)
virtual ItemBase * placePartDroppedInOtherView (ModelPart *, ViewLayer::ViewLayerPlacement, const ViewGeometry &viewGeometry, long id, SketchWidget *dropOrigin)
void prepDeleteOtherProps (ItemBase *itemBase, long id, const QString &newModuleID, QMap< QString, QString > &propsMap, QUndoCommand *parentCommand)
void prepDeleteProps (ItemBase *itemBase, long id, const QString &newModuleID, QMap< QString, QString > &propsMap, QUndoCommand *parentCommand)
void prepDragBendpoint (Wire *, QPoint eventPos, bool dragCurve)
void prepDragWire (Wire *)
void prepMove (ItemBase *originatingItem, bool rubberBandLegEnabled, bool includeRatsnest)
virtual void prereleaseTempWireForDragging (Wire *)
void removeDragWire ()
QByteArray removeOutsideConnections (const QByteArray &itemData, QList< long > &modelIndexes)
void removeWire (Wire *w, QList< ConnectorItem * > &ends, QList< Wire * > &done, QUndoCommand *parentCommand)
QString renderToSVG (RenderThing &, const LayerList &)
QString renderToSVG (RenderThing &, QList< QGraphicsItem * > &itemsAndLabels)
void resizeBoard ()
void resizeEvent (QResizeEvent *)
void resizeWithHandle (ItemBase *itemBase, double mmW, double mmH)
bool resizingBoardPress (ItemBase *)
bool resizingBoardRelease ()
virtual bool resizingJumperItemPress (ItemBase *)
virtual bool resizingJumperItemRelease ()
virtual void rotatePartLabels (double degrees, QTransform &, QPointF center, QUndoCommand *parentCommand)
void rotateWire (Wire *, QTransform &rotation, QPointF center, bool undoOnly, QUndoCommand *parentCommand)
int selectAllItems (QSet< ItemBase * > &itemBases, const QString &msg)
void selectAllWiresFrom (ViewGeometry::WireFlag flag, QList< QGraphicsItem * > &items)
void setLastPaletteItemSelected (PaletteItem *paletteItem)
void setLastPaletteItemSelectedIf (ItemBase *itemBase)
void setupAutoscroll (bool moving)
virtual void setUpColor (ConnectorItem *fromConnectorItem, ConnectorItem *toConnectorItem, Wire *wire, QUndoCommand *parentCommand)
void setUpSwapReconnect (SwapThing &, ItemBase *itemBase, long newID, bool master)
void showPartLabelsAux (bool show, QList< ItemBase * > &itemBases)
void squashShapes (QPointF scenePos)
bool startZChange (QList< ItemBase * > &bases)
bool swappedGender (ConnectorItem *originalConnectorItem, Connector *newConnector)
void turnOffAutoscroll ()
void unsquashShapes ()
virtual bool updateOK (ConnectorItem *, ConnectorItem *)
virtual void viewGeometryConversionHack (ViewGeometry &, ModelPart *)
bool viewportEvent (QEvent *)
virtual ViewLayer::ViewLayerPlacement wireViewLayerPlacement (ConnectorItem *)
Protected Member Functions inherited from InfoGraphicsView
QGraphicsItem * selectedAux ()
Protected Member Functions inherited from ZoomableGraphicsView
virtual void wheelEvent (QWheelEvent *event)
Protected Attributes
bool m_colorWiresByLength
Protected Attributes inherited from SketchWidget
bool m_addDefaultParts = false
QPointer< ItemBase > m_addedDefaultPart
QList< ItemBase * > m_additionalSavedItems
QPointer< ItemBase > m_alignmentItem
QPointF m_alignmentStartPoint
bool m_alignToGrid = true
bool m_anyInRotation
QTimer m_arrowTimer
double m_arrowTotalX = 0.0
double m_arrowTotalY = 0.0
volatile int m_autoScrollCount = 0
int m_autoScrollThreshold = 0
QTimer m_autoScrollTimer
volatile int m_autoScrollX = 0
volatile int m_autoScrollY = 0
ViewGeometry m_bendpointVG
QPointer< Wire > m_bendpointWire
bool m_chainDrag = false
QList< ItemBase * > m_checkUnder
bool m_clearSceneRect = false
QPointer< ConnectorItem > m_connectorDragConnector
QPointer< Wire > m_connectorDragWire
ViewLayer::ViewLayerID m_connectorViewLayerID
bool m_current = false
bool m_curvyWires = false
QPoint m_dragBendpointPos
QPointer< Wire > m_dragBendpointWire
bool m_dragCurve = false
bool m_draggingBendpoint = false
QPointer< ItemBase > m_droppingItem
QPointF m_droppingOffset
bool m_droppingWire = false
bool m_everZoomed = false
QPoint m_globalPos
QColor m_gridColor
double m_gridSizeInches = 0.0
QString m_gridSizeText
class SelectItemCommand * m_holdingSelectItemCommand = nullptr
int m_ignoreSelectionChangeEvents = 0
QList< QGraphicsItem * > m_inFocus
bool m_infoViewOnHover
QMenu * m_itemMenu = nullptr
QString m_lastColorSelected
QPointer< ConnectorItem > m_lastHoverEnterConnectorItem
QPointer< ItemBase > m_lastHoverEnterItem
QPointer< PaletteItem > m_lastPaletteItemSelected
bool m_middleMouseIsPressed = false
QPointF m_mousePressGlobalPos
QPointF m_mousePressScenePos
ConnectorPairHash m_moveDisconnectedFromFemale
int m_moveEventCount = 0
QPointer< ItemBase > m_moveReferenceItem
bool m_movingByArrow = false
bool m_movingByMouse = false
QPointer< QGraphicsSvgItem > m_movingItem
QPointF m_movingSVGOffset
QPointer< QSvgRenderer > m_movingSVGRenderer
ViewLayer::ViewLayerID m_noteViewLayerID
QPointer< ItemBase > m_originatingItem
ViewLayer::ViewLayerID m_partViewLayerID
int m_pasteCount = 0
QPointF m_pasteOffset
bool m_pasting = false
QList< QPointer< ConnectorItem > > m_ratsnestCacheConnect
QList< QPointer< ConnectorItem > > m_ratsnestCacheDisconnect
double m_ratsnestOpacity = 0.0
QList< QPointer< ConnectorItem > > m_ratsnestUpdateConnect
QList< QPointer< ConnectorItem > > m_ratsnestUpdateDisconnect
double m_ratsnestWidth = 0.0
QPointer< class ReferenceModel > m_referenceModel
QPointer< class ResizableBoard > m_resizingBoard
RoutingStatus m_routingStatus
bool m_rubberBandLegWasEnabled = false
ViewLayer::ViewLayerID m_rulerViewLayerID
QHash< long, ItemBase * > m_savedItems
QHash< Wire *, ConnectorItem * > m_savedWires
QString m_shortName
bool m_showGrid = true
QPointer< SizeItem > m_sizeItem
QPointer< SketchModel > m_sketchModel
bool m_spaceBarIsPressed = false
bool m_spaceBarWasPressed = false
QList< QPointer< ItemBase > > m_squashShapes
StatusConnectStatus m_statusConnectState = StatusConnectNotTried
QMultiHash< ItemBase *, ConnectorItem * > m_stretchingLegs
class SelectItemCommand * m_tempDragWireCommand = nullptr
QList< QGraphicsItem * > m_temporaries
class WaitPushUndoStack * m_undoStack = nullptr
ViewLayer::ViewID m_viewID
LayerHash m_viewLayers
QHash< ViewLayer::ViewLayerID, bool > m_viewLayerVisibility
QString m_viewName
QMenu * m_wireMenu = nullptr
ViewLayer::ViewLayerID m_wireViewLayerID
float m_z
double m_zoom = 100
Protected Attributes inherited from InfoGraphicsView
int m_boardLayers
bool m_hoverEnterConnectorMode
bool m_hoverEnterMode
class HtmlInfoView * m_infoView
Qt::Orientations m_smdOrientation
Protected Attributes inherited from ZoomableGraphicsView
bool m_acceptWheelEvents
int m_maxScaleValue
int m_minScaleValue
double m_scaleValue
bool m_viewFromBelow
Additional Inherited Members
Public Types inherited from ZoomableGraphicsView
enum WheelMapping { ScrollPrimary, ZoomPrimary, WheelMappingCount }
Public Slots inherited from SketchWidget
void addSubpart (long id, long subpartid, bool doEmit)
virtual void changeBoardLayers (int layers, bool doEmit)
void changeWireColor (const QString newColor)
void changeWireWidthMils (const QString newWidth)
void checkSticky (long id, bool doEmit, bool checkCurrent, CheckStickyCommand *)
void cleanupRatsnests (bool doEmit)
void disconnectAllSlot (QList< ConnectorItem * >, QHash< ItemBase *, SketchWidget * > &itemsToDelete, QUndoCommand *parentCommand)
void incInstanceTitle (long id)
void packItems (int columns, const QList< long > &ids, QUndoCommand *parent, bool doEmit)
void ratsnestConnect (long id, const QString &connectorID, bool connect, bool doEmit)
virtual ItemBase * resizeBoard (long id, double w, double h)
void resizeBoard (double w, double h, bool doEmit)
void resizeJumperItem (long id, QPointF pos, QPointF c0, QPointF c1)
void selectAllItems (bool state, bool doEmit)
void setHoleSize (ItemBase *, const QString &propName, const QString &translatedPropName, const QString &oldValue, const QString &newValue, QRectF &oldRect, QRectF &newRect, bool redraw)
void setInstanceTitle (long id, const QString &oldTitle, const QString &newTitle, bool isUndoable, bool doEmit)
void setNoteText (long itemID, const QString &newText)
void setProp (long itemID, const QString &prop, const QString &value, bool redraw, bool doEmit)
virtual void setProp (ItemBase *, const QString &propName, const QString &translatedPropName, const QString &oldValue, const QString &newValue, bool redraw)
void setResistance (long itemID, QString resistance, QString pinSpacing, bool doEmit)
void setResistance (QString resistance, QString pinSpacing)
virtual void showLabelFirstTime (long itemID, bool show, bool doEmit)
void showPartLabel (long id, bool showIt)
void updateConnectors ()
Public Slots inherited from InfoGraphicsView
virtual void resizeBoard (double w, double h, bool doEmit)
virtual void setInstanceTitle (long id, const QString &oldTitle, const QString &newTitle, bool isUndoable, bool doEmit)
virtual void setVoltage (double, bool doEmit)
Signals inherited from SketchWidget
void addSubpartSignal (long id, long subpartID, bool doEmit)
void canConnectSignal (Wire *from, ItemBase *to, bool &connect)
void changeBoardLayersSignal (int, bool doEmit)
void changeConnectionSignal (long fromID, QString fromConnectorID, long toID, QString toConnectorID, ViewLayer::ViewLayerPlacement, bool connect, bool updateConnections)
void checkStickySignal (long id, bool doEmit, bool checkCurrent, CheckStickyCommand *)
void cleanupRatsnestsSignal (bool doEmit)
void cleanUpWiresSignal (CleanUpWiresCommand *)
void clearSelectionSignal ()
void clickedItemCandidateSignal (QGraphicsItem *, bool &ok)
void collectRatsnestSignal (QList< SketchWidget * > &foreignSketchWidgets)
void copyBoundingRectsSignal (QHash< QString, QRectF > &)
void cursorLocationSignal (double xinches, double yinches, double width=0.0, double height=0.0)
void deleteTracesSignal (QSet< ItemBase * > &deletedItems, QHash< ItemBase *, SketchWidget * > &otherDeletedItems, QList< long > &deletedIDs, bool isForeign, QUndoCommand *parentCommand)
void disconnectAllSignal (QList< ConnectorItem * >, QHash< ItemBase *, SketchWidget * > &itemsToDelete, QUndoCommand *parentCommand)
void dropPasteSignal (SketchWidget *)
void dropSignal (const QPoint &pos)
void filenameIfSignal (QString &filename)
void getDroppedItemViewLayerPlacementSignal (ModelPart *modelPart, ViewLayer::ViewLayerPlacement &)
void itemAddedSignal (ModelPart *, ItemBase *, ViewLayer::ViewLayerPlacement, const ViewGeometry &, long id, SketchWidget *dropOrigin)
void itemDeletedSignal (long id)
void itemMovedSignal (ItemBase *)
void itemSelectedSignal (long id, bool state)
void makeDeleteItemCommandFinalSignal (ItemBase *itemBase, bool foreign, QUndoCommand *parentCommand)
void makeDeleteItemCommandPrepSignal (ItemBase *itemBase, bool foreign, QUndoCommand *parentCommand)
void movingSignal (SketchWidget *, QUndoCommand *parentCommand)
void packItemsSignal (int columns, const QList< long > &ids, QUndoCommand *parent, bool doEmit)
void ratsnestConnectSignal (long id, const QString &connectorID, bool connect, bool doEmit)
void removeRatsnestSignal (QList< struct ConnectorEdge * > &cutSet, QUndoCommand *parentCommand)
void resizedSignal (ItemBase *)
void resizeSignal ()
void routingStatusSignal (SketchWidget *, const RoutingStatus &)
void selectAllItemsSignal (bool state, bool doEmit)
void selectionChangedSignal ()
void setInstanceTitleSignal (long id, const QString &oldTitle, const QString &newTitle, bool isUndoable, bool doEmit)
void setPropSignal (long itemID, const QString &prop, const QString &value, bool doRedraw, bool doEmit)
void setResistanceSignal (long itemID, QString resistance, QString pinSpacing, bool doEmit)
void showing (SketchWidget *)
void showLabelFirstTimeSignal (long itemID, bool show, bool doEmit)
void statusMessageSignal (QString, int timeout)
void swapBoardImageSignal (SketchWidget *sketchWidget, ItemBase *itemBase, const QString &filename, const QString &moduleID, bool addName)
void swapStartSignal (SwapThing &swapThing, bool master)
void updateLayerMenuSignal ()
void updatePartLabelInstanceTitleSignal (long itemID)
void wireConnectedSignal (long fromID, QString fromConnectorID, long toID, QString toConnectorID)
void wireDisconnectedSignal (long fromID, QString fromConnectorID)
Signals inherited from InfoGraphicsView
void changePinLabelsSignal (ItemBase *, bool singleRow)
void newWireSignal (Wire *)
void setActiveConnectorItemSignal (ConnectorItem *)
void setActiveWireSignal (Wire *)
void setVoltageSignal (double, bool doEmit)
void swapSignal (const QString &family, const QString &prop, QMap< QString, QString > &propsMap, ItemBase *)
Signals inherited from ZoomableGraphicsView
void wheelSignal ()
void zoomChanged (double zoom)
void zoomOutOfRange (double zoom)
Static Public Member Functions inherited from SketchWidget
static ViewLayer::ViewLayerID defaultConnectorLayer (ViewLayer::ViewID viewId)
Static Public Member Functions inherited from InfoGraphicsView
static InfoGraphicsView * getInfoGraphicsView (QGraphicsItem *)
Static Public Member Functions inherited from ZoomableGraphicsView
static void setWheelMapping (WheelMapping)
static WheelMapping wheelMapping ()
Static Public Attributes inherited from SketchWidget
static bool m_blockUI = false
static constexpr int PropChangeDelay = 100
Static Public Attributes inherited from ZoomableGraphicsView
static const int MaxScaleValue = 3000
Protected Types inherited from SketchWidget
enum StatusConnectStatus { StatusConnectNotTried, StatusConnectSucceeded, StatusConnectFailed }
Protected Slots inherited from SketchWidget
void arrowTimerTimeout ()
void autoScrollTimeout ()
void canConnect (Wire *from, ItemBase *to, bool &connect)
void changeConnectionSlot (long fromID, QString fromConnectorID, long toID, QString toConnectorID, ViewLayer::ViewLayerPlacement, bool connect, bool updateConnections)
void changePinLabels (ItemBase *, bool singleRow)
void changePinLabelsSlot (ItemBase *itemBase, bool singleRow)
void cleanUpWiresSlot (CleanUpWiresCommand *)
void clearSelectionSlot ()
void collectRatsnestSlot (QList< SketchWidget * > &foreignSketchWidgets)
void copyBoundingRectsSlot (QHash< QString, QRectF > &)
void deleteRatsnest (Wire *, QUndoCommand *parentCommand)
void deleteTemporary ()
void deleteTracesSlot (QSet< ItemBase * > &deletedItems, QHash< ItemBase *, SketchWidget * > &otherDeletedItems, QList< long > &deletedIDs, bool isForeign, QUndoCommand *parentCommand)
void dragAutoScrollTimeout ()
void dragIsDoneSlot (class ItemDrag *)
virtual void getDroppedItemViewLayerPlacement (ModelPart *modelPart, ViewLayer::ViewLayerPlacement &)
void itemAddedSlot (ModelPart *, ItemBase *, ViewLayer::ViewLayerPlacement, const ViewGeometry &, long id, SketchWidget *dropOrigin)
void itemDeletedSlot (long id)
void itemSelectedSlot (long id, bool state)
void makeDeleteItemCommandFinalSlot (ItemBase *itemBase, bool foreign, QUndoCommand *parentCommand)
void makeDeleteItemCommandPrepSlot (ItemBase *itemBase, bool foreign, QUndoCommand *parentCommand)
void moveAutoScrollTimeout ()
void rememberSticky (long id, QUndoCommand *parentCommand)
void rememberSticky (ItemBase *, QUndoCommand *parentCommand)
void removeRatsnestSlot (QList< struct ConnectorEdge * > &cutSet, QUndoCommand *parentCommand)
void restartPasteCount ()
void selectionChangedSlot ()
void spaceBarIsPressedSlot (bool)
void statusMessage (QString message, int timeout=0)
long swapStart (SwapThing &swapThing, bool master)
void toggleLayerVisibility ()
void updateInfoViewSlot ()
void updatePartLabelInstanceTitleSlot (long itemID)
void vScrollToZero ()
void wireChangedCurveSlot (class Wire *, const Bezier *oldB, const Bezier *newB, bool triggerFirstTime)
void wireChangedSlot (class Wire *, const QLineF &oldLine, const QLineF &newLine, QPointF oldPos, QPointF newPos, ConnectorItem *from, ConnectorItem *to)
void wireConnectedSlot (long fromID, QString fromConnectorID, long toID, QString toConnectorID)
void wireDisconnectedSlot (long fromID, QString fromConnectorID)
void wireJoinSlot (class Wire *, ConnectorItem *clickedConnectorItem)
virtual void wireSplitSlot (class Wire *, QPointF newPos, QPointF oldPos, const QLineF &oldLine)
Static Protected Member Functions inherited from SketchWidget
static bool greaterThan (int a, int b)
static bool lessThan (int a, int b)
Static Protected Attributes inherited from SketchWidget
static constexpr int DragAutoScrollThreshold = 10
static constexpr int MoveAutoScrollThreshold = 5
Static Protected Attributes inherited from ZoomableGraphicsView
static WheelMapping m_wheelMapping
Properties inherited from SketchWidget
QColor gridColor
double ratsnestOpacity
double ratsnestWidth
Constructor & Destructor Documentation
BreadboardSketchWidget()
BreadboardSketchWidget::BreadboardSketchWidget (ViewLayer::ViewID viewID, QWidget * parent = 0)
References colorWiresByLength(), SketchWidget::getShortName(), SketchWidget::initBackgroundColor(), m_colorWiresByLength, SketchWidget::m_shortName, and SketchWidget::m_viewName.
Member Function Documentation
addDefaultParts()
void BreadboardSketchWidget::addDefaultParts () virtual
Reimplemented from SketchWidget.
References SketchWidget::addItem(), BaseCommand::CrossView, SketchWidget::defaultViewLayerPlacement(), ModuleIDNames::FullPlusBreadboardModuleIDName, ItemBase::getNextID(), SketchWidget::m_addDefaultParts, SketchWidget::m_addedDefaultPart, SketchWidget::referenceModel(), ReferenceModel::retrieveModelPart(), and ViewGeometry::setLoc().
addViewLayers()
void BreadboardSketchWidget::addViewLayers () virtual
Reimplemented from SketchWidget.
References SketchWidget::addViewLayersAux(), ViewLayer::Breadboard, ViewLayer::BreadboardNote, ViewLayer::BreadboardRuler, ViewLayer::BreadboardView, ViewLayer::BreadboardWire, ViewLayer::layersForView(), ViewLayer::layersForViewFromBelow(), and SketchWidget::setViewLayerIDs().
canDisconnectAll()
bool BreadboardSketchWidget::canDisconnectAll () virtual
Reimplemented from SketchWidget.
canDropModelPart()
bool BreadboardSketchWidget::canDropModelPart (ModelPart * modelPart) protected virtual
Reimplemented from SketchWidget.
References SketchWidget::canDropModelPart(), ModuleIDNames::CopperBlockerModuleIDName, ModelPart::CopperFill, ModelPart::Hole, Board::isBoard(), ModelPart::itemType(), ModelPart::Jumper, ModelPart::Logo, SketchWidget::matchesLayer(), ModelPart::moduleID(), ModuleIDNames::PadModuleIDName, ModuleIDNames::SchematicFrameModuleIDName, ModelPart::SchematicSubpart, ModelPart::Symbol, and ModelPart::Via.
checkUnder()
bool BreadboardSketchWidget::checkUnder () protected virtual
Reimplemented from SketchWidget.
collectFemaleConnectees()
bool BreadboardSketchWidget::collectFemaleConnectees (ItemBase * itemBase, QSet< ItemBase * > & items) protected virtual
Reimplemented from SketchWidget.
References ItemBase::collectFemaleConnectees().
coloringWiresByLength()
bool BreadboardSketchWidget::coloringWiresByLength ()
References m_colorWiresByLength.
colorWiresByLength()
void BreadboardSketchWidget::colorWiresByLength (bool colorByLength)
References Wire::colorByLength(), m_colorWiresByLength, and SketchWidget::viewName().
defaultGridSizeInches()
double BreadboardSketchWidget::defaultGridSizeInches () protected virtual
Reimplemented from SketchWidget.
disconnectFromFemale()
bool BreadboardSketchWidget::disconnectFromFemale (ItemBase * item, QHash< long, ItemBase * > & savedItems, ConnectorPairHash & connectorHash, bool doCommand, bool rubberBandLegEnabled, QUndoCommand * parentCommand) protected virtual
Reimplemented from SketchWidget.
References NonConnectorItem::attachedTo(), ItemBase::cachedConnectorItems(), ConnectorItem::connectedToItems(), ConnectorItem::connectorType(), BaseCommand::CrossView, SketchWidget::extendChangeConnectionCommand(), Connector::Female, ConnectorItem::hasRubberBandLeg(), ItemBase::id(), ItemBase::layerKinChief(), ViewLayer::NewBottom, and ConnectorItem::tempRemove().
findConnectorsUnder()
void BreadboardSketchWidget::findConnectorsUnder (ItemBase * item) protected virtual
Reimplemented from SketchWidget.
References ItemBase::findConnectorsUnder().
getBendpointWidths()
void BreadboardSketchWidget::getBendpointWidths (class Wire * wire, double w, double & w1, double & w2, bool & negativeOffsetRect) virtual
Reimplemented from InfoGraphicsView.
getLabelFont()
void BreadboardSketchWidget::getLabelFont (QFont & font, QColor & color, ItemBase *) protected virtual
Reimplemented from InfoGraphicsView.
getLabelViewLayerID()
ViewLayer::ViewLayerID BreadboardSketchWidget::getLabelViewLayerID (ItemBase *) protected virtual
Reimplemented from SketchWidget.
References ViewLayer::BreadboardLabel.
getTraceWidth()
double BreadboardSketchWidget::getTraceWidth () protected virtual
Reimplemented from SketchWidget.
getWireStrokeWidth()
double BreadboardSketchWidget::getWireStrokeWidth (Wire * , double wireWidth) virtual
Reimplemented from InfoGraphicsView.
References WireHoverStrokeFactor.
ignoreFemale()
bool BreadboardSketchWidget::ignoreFemale () virtual
Reimplemented from SketchWidget.
initWire()
void BreadboardSketchWidget::initWire (Wire * wire, int penWidth) virtual
Reimplemented from InfoGraphicsView.
References Wire::colorByLength(), ItemBase::getRatsnest(), m_colorWiresByLength, Wire::setColorString(), Wire::setPenWidth(), and WireHoverStrokeFactor.
setNewPartVisible()
void BreadboardSketchWidget::setNewPartVisible (ItemBase * itemBase) protected virtual
Reimplemented from SketchWidget.
References ModelPart::CopperFill, ModelPart::Hole, ItemBase::itemType(), ModelPart::Jumper, ModelPart::Logo, ItemBase::moduleID(), ModuleIDNames::PadModuleIDName, ModuleIDNames::PowerModuleIDName, ModuleIDNames::SchematicFrameModuleIDName, ModelPart::SchematicSubpart, ItemBase::setEverVisible(), ModelPart::Symbol, and ModelPart::Via.
setWireVisible()
void BreadboardSketchWidget::setWireVisible (Wire * wire) protected virtual
Reimplemented from SketchWidget.
References Wire::getTrace(), and ItemBase::setEverVisible().
showEvent()
void BreadboardSketchWidget::showEvent (QShowEvent * event)
References SketchWidget::alignOneToGrid(), SketchWidget::m_addDefaultParts, SketchWidget::m_addedDefaultPart, SketchWidget::showEvent(), and SketchWidget::vScrollToZero().
traceColor()
const QString & BreadboardSketchWidget::traceColor (ViewLayer::ViewLayerPlacement) protected virtual
Reimplemented from SketchWidget.
References SketchWidget::m_lastColorSelected.
wireSplitCrossView()
BaseCommand::CrossViewType BreadboardSketchWidget::wireSplitCrossView () protected virtual
Reimplemented from SketchWidget.
References BaseCommand::CrossView.
Member Data Documentation
m_colorWiresByLength
bool BreadboardSketchWidget::m_colorWiresByLength protected
The documentation for this class was generated from the following files:
sketch/breadboardsketchwidget.h
sketch/breadboardsketchwidget.cpp