Fritzing: TrieNode Class Reference
TrieNode Class Reference
#include <trienode.h>
Public Member Functions
TrieNode (QChar)
virtual ~TrieNode ()
virtual void addString (QString &s, bool caseInsensitive, TrieLeaf *leaf)
virtual bool matches (QString &string, TrieLeaf *&leaf)
Protected Member Functions
virtual void addStringAux (QChar c, QString &next, bool caseInsensitive, TrieLeaf *leaf)
virtual bool matchesChar (QChar c)
Protected Attributes
bool m_caseInsensitive
QChar m_char
QList< TrieNode * > m_children
bool m_isLeaf
TrieLeaf * m_leafData
Constructor & Destructor Documentation
TrieNode()
TrieNode::TrieNode (QChar c)
References m_caseInsensitive, m_char, m_isLeaf, and m_leafData.
~TrieNode()
TrieNode::~TrieNode () virtual
References m_children.
Member Function Documentation
addString()
void TrieNode::addString (QString & s, bool caseInsensitive, TrieLeaf * leaf) virtual
References addStringAux(), m_isLeaf, and m_leafData.
addStringAux()
void TrieNode::addStringAux (QChar c, QString & next, bool caseInsensitive, TrieLeaf * leaf) protected virtual
References addString(), m_children, matchesChar(), and TrieNode().
matches()
bool TrieNode::matches (QString & string, TrieLeaf *& leaf) virtual
References m_children, m_isLeaf, m_leafData, matches(), and matchesChar().
matchesChar()
bool TrieNode::matchesChar (QChar c) protected virtual
References m_char.
Member Data Documentation
m_caseInsensitive
bool TrieNode::m_caseInsensitive protected
m_char
QChar TrieNode::m_char protected
m_children
QList<TrieNode *> TrieNode::m_children protected
m_isLeaf
bool TrieNode::m_isLeaf protected
m_leafData
TrieLeaf* TrieNode::m_leafData protected
The documentation for this class was generated from the following files:
program/trienode.h
program/trienode.cpp